#!/usr/bin/env python3
"""TEMPORARY evidence probe: put the real review-mode pages into the probe app, so the pictures are of
the code the task branch ships.

- Views/WikiView.swift (home, entry, Review) and Views/Typography.swift (the font tokens) go in whole.
- ApprovalCards.swift's `ApprovalActions` and `approvalActionLabel()` — the stack Review's answers use.
- WikiSettingsView.swift's pure pieces — the actions, the page, the picker option, the choice and the
  Set up form — cut verbatim; the screen that reads AppModel stays behind.
- WikiRunView.swift's actions, page and list style, cut verbatim; the screen stays behind.

usage: gen.py <repo root> <probe dir>
"""
import sys
from pathlib import Path

root, probe = Path(sys.argv[1]), Path(sys.argv[2])
app = root / "src/macos/OrbitApp/Sources/OrbitApp"
out = probe / "ios/Generated"
out.mkdir(parents=True, exist_ok=True)


def lines(path):
    return path.read_text(encoding="utf-8").split("\n")


def block(src, start, containing=None, after=0):
    """From the first line at or after `after` holding `start` (and whose block holds `containing`)
    until its braces balance — or, for a one-line declaration, that line."""
    for first in range(after, len(src)):
        if start not in src[first]:
            continue
        depth = 0
        stop = first
        for stop in range(first, len(src)):
            depth += src[stop].count("{") - src[stop].count("}")
            if depth <= 0 and (stop > first or "{" not in src[first]):
                break
        cut = src[first:stop + 1]
        if containing is None or any(containing in l for l in cut):
            return "\n".join(cut)
    sys.exit(f"gen.py: no `{start}`" + (f" holding `{containing}`" if containing else ""))


def write(name, text):
    (out / name).write_text(text, encoding="utf-8")
    print(f"==> generated {name} ({len(text.splitlines())} lines)")


for rel in ["Views/WikiView.swift", "Views/Typography.swift"]:
    write(Path(rel).name, (app / rel).read_text(encoding="utf-8"))

approvals = lines(app / "Views/ApprovalCards.swift")
write("ApprovalActions.swift", "import SwiftUI\n\n// GENERATED by gen.py: cut verbatim out of ApprovalCards.swift.\n\n"
      + block(approvals, "struct ApprovalActions<Content: View>: View {") + "\n\n"
      + block(approvals, "extension View {", containing="func approvalActionLabel()") + "\n")

settings = lines(app / "Views/WikiSettingsView.swift")
write("WikiSettingsPage.swift", "import SwiftUI\nimport OrbitKit\n\n// GENERATED by gen.py: cut verbatim out of WikiSettingsView.swift.\n\n"
      + "\n\n".join(block(settings, start) for start in [
          "struct WikiSettingsActions {", "struct WikiSettingsPage: View {", "struct WikiPickerOption: Identifiable, Equatable {",
          "struct WikiMaintenanceChoice: Equatable {", "struct WikiMaintenanceForm: View {"]) + "\n")

run = lines(app / "Views/WikiRunView.swift")
write("WikiRunPage.swift", "import SwiftUI\nimport OrbitKit\n\n// GENERATED by gen.py: cut verbatim out of WikiRunView.swift.\n\n"
      + "\n\n".join([block(run, "struct WikiRunActions {"), block(run, "struct WikiRunPage: View {"),
                     block(run, "private extension View {", containing="func wikiRunListStyle()")]) + "\n")
