#!/usr/bin/env python3
"""TEMPORARY evidence probe: put the real Wiki code into the probe app, so the pictures are of the code
the commit ships.

- Views/WikiView.swift (the three pages) and Views/Typography.swift (the font tokens) go in whole.
- ApprovalCards.swift's `ApprovalActions` and `approvalActionLabel()` — the stack Review's answers use.
- CompactShell.swift's drawer pieces: the rail's work rows (`ForEach(AppSection.workSections)`), the
  Projects, Tasks and Wiki rows, the pill, the Workspaces header, the group label, the metrics and
  surfaces, and `drawerRow()` — cut verbatim into DrawerProbe.swift.in.
- The OrbitKit tests' WikiTestFixtures.swift, the same reads the tests decode.

usage: gen.py <repo root> <probe dir>
"""
import sys
from pathlib import Path

root, probe = Path(sys.argv[1]), Path(sys.argv[2])
app = root / "src/macos/OrbitApp/Sources/OrbitApp"
out = probe / "ios/Generated"
out.mkdir(parents=True, exist_ok=True)


def lines(path):
    return path.read_text(encoding="utf-8").split("\n")


def block(src, start, containing=None, after=0):
    """From the first line at or after `after` holding `start` (and whose block holds `containing`)
    until its braces balance — or, for a one-line declaration, that line."""
    for first in range(after, len(src)):
        if start not in src[first]:
            continue
        depth = 0
        stop = first
        for stop in range(first, len(src)):
            depth += src[stop].count("{") - src[stop].count("}")
            if depth <= 0 and (stop > first or "{" not in src[first]):
                break
        cut = src[first:stop + 1]
        if containing is None or any(containing in l for l in cut):
            return "\n".join(cut)
    sys.exit(f"gen.py: no `{start}`" + (f" holding `{containing}`" if containing else ""))


def write(name, text):
    (out / name).write_text(text, encoding="utf-8")
    print(f"==> generated {name} ({len(text.splitlines())} lines)")


# Whole files.
for rel in ["Views/WikiView.swift", "Views/Typography.swift"]:
    write(Path(rel).name, (app / rel).read_text(encoding="utf-8"))

fixtures = (root / "src/macos/OrbitKit/Tests/OrbitKitTests/WikiTestFixtures.swift").read_text(encoding="utf-8")
write("WikiTestFixtures.swift", fixtures.replace("@testable import OrbitKit", "import OrbitKit"))

# Review's answers: the approval cards' own stack.
approvals = lines(app / "Views/ApprovalCards.swift")
write("ApprovalActions.swift", "import SwiftUI\n\n// GENERATED by gen.py: cut verbatim out of ApprovalCards.swift.\n\n"
      + block(approvals, "struct ApprovalActions<Content: View>: View {") + "\n\n"
      + block(approvals, "extension View {", containing="func approvalActionLabel()") + "\n")

# The drawer.
shell = lines(app / "Views/CompactShell.swift")
drawer = next(n for n, l in enumerate(shell) if "private struct NavigationDrawer: View {" in l)
globals_ = "\n\n".join([
    block(shell, "private let drawerSurface = "),
    block(shell, "private let drawerChip = "),
    block(shell, "private let drawerRaisedChip = "),
    block(shell, "private let drawerRaisedShadow = "),
    block(shell, "private struct DrawerCircleGlyph: View {"),
    block(shell, "private enum DrawerMetrics {"),
    block(shell, "private extension View {", containing="func drawerRow()"),
])
rows = "\n\n".join([
    block(shell, "private func pill(selected: Bool", after=drawer),
    block(shell, "private func sectionRow(_ section: AppSection)", after=drawer),
    block(shell, "private var projectsRow: some View {", after=drawer),
    block(shell, "private var wikiRow: some View {", after=drawer),
    block(shell, "private var workspacesHeader: some View {", after=drawer),
    block(shell, "private func drawerGroupLabel(", after=drawer),
])
rail = block(shell, "ForEach(AppSection.workSections) { section in", after=drawer)
template = (probe / "ios/DrawerProbe.swift.in").read_text(encoding="utf-8")
write("DrawerProbe.swift", template.replace("{GLOBALS}", globals_).replace("{ROWS}", rows).replace("{RAIL}", rail))
