#!/usr/bin/env python3
"""TEMPORARY evidence probe (shots branch only; see README.md).

Puts the real code under test into the two probe apps, so the pictures are of what the task branch
ships rather than of a re-implementation:

- Views/AgentIdentity.swift goes in whole (ProviderSwitchSheet, ProviderMark, PoolCountBadge
  verbatim); Views/Typography.swift, Views/BrandMarks.swift, Views/ProviderPoolViews.swift and
  Platform.swift go in whole as the neighbours they need to compile.
- Views/ComposerView.swift is cut by brace balance: the composer's plan-usage pill, its detail
  presentation, the pool row of its toolbar, and the gauges/formatting those read.
- src/ios/Support/Info.plist is copied with ATS off, so the real app can reach the stub on
  127.0.0.1 (the simulator shares the host's loopback).

usage: gen.py <repo root> <probe dir> [<path to the Info.plist to adapt>]
"""
import plistlib
import sys
from pathlib import Path

root, probe = Path(sys.argv[1]).resolve(), Path(sys.argv[2]).resolve()
app = root / "src/macos/OrbitApp/Sources/OrbitApp"
out = probe / "ios/Generated"
out.mkdir(parents=True, exist_ok=True)


def lines(path):
    return path.read_text(encoding="utf-8").split("\n")


def block(src, start):
    """The lines from `start` through the brace that closes it, verbatim."""
    for first in range(len(src)):
        if start not in src[first]:
            continue
        depth = 0
        stop = first
        for stop in range(first, len(src)):
            depth += src[stop].count("{") - src[stop].count("}")
            if depth <= 0 and stop > first:
                break
        return "\n".join(src[first:stop + 1])
    sys.exit(f"gen.py: no `{start}`")


def write(name, text):
    (out / name).write_text(text, encoding="utf-8")
    print(f"==> generated {name} ({len(text.splitlines())} lines)")


# The real views, whole.
for rel in ["Views/AgentIdentity.swift", "Views/ProviderPoolViews.swift", "Views/Typography.swift",
            "Views/BrandMarks.swift", "Platform.swift"]:
    write(Path(rel).name, (app / rel).read_text(encoding="utf-8"))

# The composer's pill and the pool row beside it, cut verbatim out of ComposerView.swift, plus the
# probe's own screen that draws them (ios/Probe/ComposerShot.swift) — appended to the same file, so the
# cuts keep the access they have in the app (`private` and all) and nothing of the real code is edited.
composer = lines(app / "Views/ComposerView.swift")
write("ComposerPieces.swift", "\n".join([
    "import SwiftUI",
    "import OrbitKit",
    "",
    "// GENERATED by gen.py: cut verbatim out of ComposerView.swift, then the probe's own composer",
    "// screen (ios/Probe/ComposerShot.swift) appended — it draws them where the real toolbar would.",
    "",
    block(composer, "private struct PlanUsageIndicator: View {"),
    "",
    block(composer, "private struct PlanUsageDetailPresentation: ViewModifier {"),
    "",
    block(composer, "private struct PlanUsageDetailRows: View {"),
    "",
    block(composer, "private struct UsageBar: View {"),
    "",
    block(composer, "private enum ComposerFooterDetailLayout {"),
    "",
    block(composer, "private func formatReset(_ iso: String) -> String? {"),
    "",
    # ComposerView.toolbar's own four lines about the account beside the gauge (`console` is the
    # stand-in in PoolComposerStandIn.swift).
    "// --- the pool row of ComposerView.toolbar, cut verbatim ---",
    "",
    "struct ComposerPoolRow: View {",
    "    let console: PoolComposerStandIn",
    "",
    "    var body: some View {",
    "        " + block(composer, "if let pool = console.currentPool, let account = console.poolAccount {")
        .replace("\n", "\n        "),
    "    }",
    "}",
    "",
    (probe / "ios/Probe/ComposerShot.swift").read_text(encoding="utf-8"),
    "",
]))

# ATS off for the real-app target: the stub is plain http on the host's loopback.
plist_in = Path(sys.argv[3]) if len(sys.argv) > 3 else root / "src/ios/Support/Info.plist"
with plist_in.open("rb") as fh:
    plist = plistlib.load(fh)
plist["NSAppTransportSecurity"] = {"NSAllowsArbitraryLoads": True}
# The probe app is a throwaway: no push entitlement is taken, so asking for the remote-notification
# background mode would only add an unbacked capability to the build.
plist.pop("UIBackgroundModes", None)
with (out / "Info-probe.plist").open("wb") as fh:
    plistlib.dump(plist, fh)
print("==> generated Info-probe.plist (ATS off)")
