#!/usr/bin/env python3
"""TEMPORARY evidence probe: put the real Providers and pool pages into the probe app, so the pictures
are of the code the task branch ships.

- Views/ProviderPoolViews.swift (Providers form, shared pool page, Add a key sheet, account pool page),
  Views/Typography.swift, Views/BrandMarks.swift and Platform.swift go in whole.
- AgentIdentity.swift's `ProviderMark` and `PoolCountBadge`, and SettingsSheet.swift's `SettingsHeader`,
  are cut out verbatim.

usage: gen.py <repo root> <probe dir>
"""
import sys
from pathlib import Path

root, probe = Path(sys.argv[1]), Path(sys.argv[2])
app = root / "src/macos/OrbitApp/Sources/OrbitApp"
out = probe / "ios/Generated"
out.mkdir(parents=True, exist_ok=True)


def lines(path):
    return path.read_text(encoding="utf-8").split("\n")


def block(src, start):
    for first in range(len(src)):
        if start not in src[first]:
            continue
        depth = 0
        stop = first
        for stop in range(first, len(src)):
            depth += src[stop].count("{") - src[stop].count("}")
            if depth <= 0 and stop > first:
                break
        return "\n".join(src[first:stop + 1])
    sys.exit(f"gen.py: no `{start}`")


def write(name, text):
    (out / name).write_text(text, encoding="utf-8")
    print(f"==> generated {name} ({len(text.splitlines())} lines)")


for rel in ["Views/ProviderPoolViews.swift", "Views/Typography.swift", "Views/BrandMarks.swift", "Platform.swift"]:
    write(Path(rel).name, (app / rel).read_text(encoding="utf-8"))

identity = lines(app / "Views/AgentIdentity.swift")
write("ProviderMark.swift", "import SwiftUI\nimport OrbitKit\n\n// GENERATED by gen.py: cut verbatim out of AgentIdentity.swift.\n\n"
      + block(identity, "struct ProviderMark: View {") + "\n\n"
      + block(identity, "private struct PoolCountBadge: View {") + "\n")
settings = lines(app / "Views/SettingsSheet.swift")
write("SettingsHeader.swift", "import SwiftUI\n\n// GENERATED by gen.py: cut verbatim out of SettingsSheet.swift.\n\n"
      + block(settings, "struct SettingsHeader: View {") + "\n")
