-- ══════════════════════════════════════════════════════════════════════════════════════════════
-- Orbit Wiki, phase 2, criterion 9: the articles. A topic has a display name and a category, and
-- its article — or, for a topic too big for one, an overview and the subtopic articles under it — is
-- a disposable cache generated by the local model from the topic's active entries, every sentence
-- footnoted to one of them. contracts/wiki.contract.json `articles` is the authority for everything
-- below (design §3 `wiki_topic_summary`, §12.1), and src/apiserver/src/wiki/wiki-articles.pg.spec.ts
-- holds these CHECKs to it.
--
-- WHAT IS ADDED
-- -------------
--   wiki_topic.category   which of the contract's six categories (articles.categories) the topic
--                         is filed under. NULL for a topic nothing has filed yet: phase 1 wrote no
--                         topic row at all, and the display name is the existing `title`.
--   wiki_topic (id, owner_id)  a unique key, the one a summary reaches its topic through.
--   wiki_topic_summary    one row per article: part 0 is the topic's own article (kind `article`)
--                         or, when the topic was split, its overview (kind `overview`); parts 1…N
--                         are the subtopic articles (kind `subtopic`), each hanging on its overview
--                         through parent_id. Each row keeps the entry-set fingerprint it was
--                         generated from (entry_set_sha256), the ref it was generated at, its body
--                         (blocks of footnoted sentences), its citations (footnote -> entry and
--                         revision), the entries it was written from, and what the validation did.
--
-- A CACHE, NOT A RECORD: every row can be thrown away and written again from the entries. A topic's
-- rows are replaced together when its entry set changes, and nothing else points at them: no op, no
-- source, no exposure. That is also why a summary is never a source (sourceRules.firstHand) — there
-- is no source kind that names this table.
--
-- TENANCY
-- -------
-- wiki_topic_summary reaches its topic through (topic_id, owner_id) -> wiki_topic(id, owner_id), and a
-- subtopic its overview through (parent_id, owner_id) -> wiki_topic_summary(id, owner_id), both ON
-- DELETE CASCADE, as every other wiki child reaches its parent (0307): a space's delete takes its
-- topics, and a topic's delete its articles. The entry ids it keeps (entry_ids, and those inside
-- citations) carry no foreign key: they are what the article was written from, a snapshot, and the
-- next generation replaces them.
--
-- WHAT DOES NOT CHANGE
-- --------------------
-- No row is written, read or locked. wiki_topic gains one nullable column with no default (catalog-
-- only) whose CHECK every existing row satisfies, and one unique index over (id, owner_id), which the
-- primary key already makes unique. No function, trigger or type is created, replaced or dropped;
-- no table outside the wiki is named.
--
-- NUMBERING, RE-RUNNABILITY
-- -------------------------
-- 0317: origin/main stood at 0313 and project/34VR0RwUSIcaoO7ZZqv52 at 0315 when this was written
-- (2026-09-28), and the project's coordinator gave 0314 and 0316 to its other tasks and 0317 to this.
-- Every statement can run twice: ADD COLUMN IF NOT EXISTS, the CHECK dropped IF EXISTS before it is
-- added, and CREATE TABLE / INDEX IF NOT EXISTS with the table's constraints inside its CREATE.
-- ══════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE "wiki_topic" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "wiki_topic" DROP CONSTRAINT IF EXISTS "wiki_topic_category_chk";
ALTER TABLE "wiki_topic" ADD CONSTRAINT "wiki_topic_category_chk"
  CHECK ("category" IS NULL OR "category" IN ('platform', 'runner', 'clients', 'data', 'engineering', 'collaboration'));
-- The key a summary's composite foreign key names, as every wiki parent has one (0307).
CREATE UNIQUE INDEX IF NOT EXISTS "wiki_topic_id_owner_id_key" ON "wiki_topic" ("id", "owner_id");

CREATE TABLE IF NOT EXISTS "wiki_topic_summary" (
  "id"               UUID NOT NULL,
  "topic_id"         UUID NOT NULL,
  "owner_id"         UUID NOT NULL,
  "part"             INTEGER NOT NULL,
  "kind"             TEXT NOT NULL,
  "parent_id"        UUID,
  "title"            TEXT NOT NULL,
  "body"             JSONB NOT NULL,
  "citations"        JSONB NOT NULL,
  "entry_ids"        UUID[] NOT NULL DEFAULT '{}',
  "entry_set_sha256" CHAR(64) NOT NULL,
  "ref"              TEXT,
  "model"            TEXT,
  "stats"            JSONB NOT NULL DEFAULT '{}',
  "generated_at"     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "wiki_topic_summary_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "wiki_topic_summary_id_owner_id_key" UNIQUE ("id", "owner_id"),
  CONSTRAINT "wiki_topic_summary_topic_fkey"
    FOREIGN KEY ("topic_id", "owner_id") REFERENCES "wiki_topic" ("id", "owner_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "wiki_topic_summary_parent_fkey"
    FOREIGN KEY ("parent_id", "owner_id") REFERENCES "wiki_topic_summary" ("id", "owner_id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "wiki_topic_summary_kind_chk" CHECK ("kind" IN ('article', 'overview', 'subtopic')),
  -- Part 0 is the topic's own article or overview; a subtopic article is part 1 or later, and hangs
  -- on its overview.
  CONSTRAINT "wiki_topic_summary_part_chk" CHECK ("part" >= 0 AND ("kind" = 'subtopic') = ("part" >= 1)),
  CONSTRAINT "wiki_topic_summary_parent_chk" CHECK (("kind" = 'subtopic') = ("parent_id" IS NOT NULL)),
  CONSTRAINT "wiki_topic_summary_title_chk" CHECK (btrim("title") <> '' AND char_length("title") <= 120),
  -- [{ heading, sentences: [{ text, notes }] }, …] and [{ n, entryId, revision }, …].
  CONSTRAINT "wiki_topic_summary_body_chk" CHECK (jsonb_typeof("body") = 'array'),
  CONSTRAINT "wiki_topic_summary_citations_chk" CHECK (jsonb_typeof("citations") = 'array'),
  CONSTRAINT "wiki_topic_summary_entry_set_chk" CHECK ("entry_set_sha256" ~ '^[0-9a-f]{64}$'),
  CONSTRAINT "wiki_topic_summary_ref_chk" CHECK ("ref" IS NULL OR (btrim("ref") <> '' AND char_length("ref") <= 200)),
  CONSTRAINT "wiki_topic_summary_model_chk" CHECK ("model" IS NULL OR (btrim("model") <> '' AND char_length("model") <= 200)),
  CONSTRAINT "wiki_topic_summary_stats_chk" CHECK (jsonb_typeof("stats") = 'object')
);
-- One article per part of a topic, and so one part 0.
CREATE UNIQUE INDEX IF NOT EXISTS "wiki_topic_summary_topic_id_part_key" ON "wiki_topic_summary" ("topic_id", "part");
-- The cascade from an overview to its subtopic articles, and a subtopic article's overview.
CREATE INDEX IF NOT EXISTS "wiki_topic_summary_parent_id_idx" ON "wiki_topic_summary" ("parent_id");
