/**
 * The Watch API, over real HTTP and against a real PostgreSQL.
 *
 * What is under test is what a client gets back and what the database then holds, so both are read:
 * every request goes through the real controller, the global ValidationPipe and the public-id
 * interceptor, and every claim about "nothing was written" or "exactly one Match" is a count of the
 * rows 0259 created. Only the bearer check is stood in for — `JwtService.verifyAsync` answers with
 * the account a token was issued to, which is what `JwtAuthGuard` puts on the request.
 *
 * The contract is `contracts/watch.contract.json`. The first case holds the served vocabulary to
 * it, and the leaf cases drive the contract's own vectors through the create path.
 *
 * The concurrency cases do not hope for an interleaving: they hold the owner's `user` row, which
 * every watch INSERT needs FOR KEY SHARE on, and release it only once every create is parked on a
 * lock inside its transaction — so none of them can have seen another's commit.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/watches/watch-api.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { after, test } from 'node:test';
import { setTimeout as sleep } from 'node:timers/promises';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import {
  WATCH_ACTIONS,
  WATCH_LEAVES,
  WATCH_LIMITS,
  WATCH_PREDICATE_VERSION,
  WATCH_REFUSAL_CODES,
  WATCH_RESOURCE_KINDS,
  WATCH_STATES,
  toUuid,
} from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { WATCH_LEAF_TARGET_KIND, WATCH_PREDICATE_VERSION as EVALUATED_PREDICATE_VERSION } from './watch-predicate';
import { WatchesController } from './watches.controller';
import { WatchesService } from './watches.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

// From build/watches back to the repository root.
const CONTRACT = JSON.parse(
  readFileSync(path.resolve(__dirname, '../../../../contracts/watch.contract.json'), 'utf8'),
);

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  /** bearer → the account it was issued to */
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();

    @Module({
      controllers: [WatchesController],
      providers: [
        { provide: WatchesService, useValue: new WatchesService(prisma as unknown as PrismaService) },
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub };
            },
          },
        },
      ],
    })
    class WatchApiModule {}

    const app = await NestFactory.create(WatchApiModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

async function call(h: Harness, bearer: string | null, method: string, route: string, body?: unknown): Promise<Answer> {
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers: { 'content-type': 'application/json', ...(bearer ? { authorization: `Bearer ${bearer}` } : {}) },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

function expectRefusal(answer: Answer, code: string, why: string): void {
  expectStatus(answer, code === 'PERMISSION_DENIED' ? 403 : 400, why);
  assert.equal(answer.body.code, code, `${why}: ${JSON.stringify(answer.body)}`);
  assert.equal(answer.body.kind, 'REFUSAL', why);
}

const ALL_TERMINAL = { kind: 'ALL', over: 'ALL_TARGETS', leaf: 'TASK_TERMINAL' };
const ALL_SETTLED = { kind: 'ALL', over: 'ALL_TARGETS', leaf: 'SESSION_TURN_SETTLED' };

const tasks = (ids: string[]) => ids.map((id) => ({ kind: 'TASK', id }));
const sessions = (ids: string[]) => ids.map((id) => ({ kind: 'SESSION', id }));

function watchBody(targets: unknown[], over: Record<string, unknown> = {}): Record<string, unknown> {
  return { predicateVersion: 1, predicate: ALL_TERMINAL, targets, action: 'NOTIFY_USER', ...over };
}

/** Target id → state, from either a watch's targets or a Match snapshot's. */
function statesById(targets: Array<{ targetResourceId?: string; id?: string; state: string }>): Map<string, string> {
  return new Map(targets.map((target) => [toUuid((target.targetResourceId ?? target.id)!), target.state]));
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`,
    [id, `watch-api-${id}@watch.invalid`, name],
  );
  const bearer = `bearer-${id}`;
  h.bearers.set(bearer, id);
  return { id, bearer };
}

async function task(h: Harness, ownerId: string, status: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","updated_at","completion_criterion")
     VALUES ($1,'watched work',$2,'USER',$2,$3,now(),'EVIDENCE_JUDGMENT')`,
    [id, ownerId, status],
  );
  return id;
}

interface SessionShape {
  status?: string;
  endReason?: string | null;
  completedAt?: Date | null;
  deletedAt?: Date | null;
  pendingApprovals?: number;
}

async function session(h: Harness, ownerId: string, shape: SessionShape = {}): Promise<string> {
  const id = randomUUID();
  // `archived_at` is the deprecated mirror of `completed_at`; a fixture keeps the two in step.
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","status","end_reason",
                           "completed_at","archived_at","deleted_at","updated_at")
     VALUES ($1,'watched session','p',$2,$2,$3,$4,$5,$5,$6,now())`,
    [id, ownerId, shape.status ?? 'RUNNING', shape.endReason ?? null, shape.completedAt ?? null, shape.deletedAt ?? null],
  );
  for (let n = 0; n < (shape.pendingApprovals ?? 0); n += 1) {
    await h.sql.query(
      `INSERT INTO "approval"("id","session_id","tool_name","input","status") VALUES ($1,$2,'Bash','{}'::jsonb,'PENDING')`,
      [randomUUID(), id],
    );
  }
  return id;
}

interface Rows {
  watches: number;
  targets: number;
  matches: number;
  deliveries: number;
}

async function rowsOf(h: Harness, ownerId: string): Promise<Rows> {
  const { rows } = await h.sql.query<Rows>(
    `SELECT (SELECT count(*) FROM "watch" w WHERE w."owner_id" = $1)::int AS watches,
            (SELECT count(*) FROM "watch_target" t JOIN "watch" w ON w."id" = t."watch_id"
              WHERE w."owner_id" = $1)::int AS targets,
            (SELECT count(*) FROM "watch_match" m JOIN "watch" w ON w."id" = m."watch_id"
              WHERE w."owner_id" = $1)::int AS matches,
            (SELECT count(*) FROM "watch_delivery" d JOIN "watch_match" m ON m."id" = d."match_id"
              JOIN "watch" w ON w."id" = m."watch_id" WHERE w."owner_id" = $1)::int AS deliveries`,
    [ownerId],
  );
  return rows[0];
}

const NOTHING: Rows = { watches: 0, targets: 0, matches: 0, deliveries: 0 };

async function create(h: Harness, who: Account, body: Record<string, unknown>, why: string) {
  const answer = await call(h, who.bearer, 'POST', '/watches', body);
  expectStatus(answer, 201, why);
  return answer.body;
}

/**
 * Run `fire` while the owner's `user` row is held FOR UPDATE, and let go only once `waiters`
 * backends are parked on a lock. Every watch INSERT's foreign key needs that row FOR KEY SHARE, so
 * each create is inside its transaction, past its reads and its idempotency lookup, and has not
 * committed; a create with a key another create already inserted waits on that one instead.
 */
async function whileOwnerRowIsHeld<T>(h: Harness, ownerId: string, waiters: number, fire: () => Promise<T>): Promise<T> {
  const holder = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
  await holder.connect();
  try {
    await holder.query('BEGIN');
    await holder.query(`SELECT 1 FROM "user" WHERE "id" = $1 FOR UPDATE`, [ownerId]);
    const holderPid = (await holder.query<{ pid: number }>('SELECT pg_backend_pid() AS pid')).rows[0].pid;
    // The first create's interactive transaction is open for as long as the row is held, and Prisma
    // gives it 5s. A racer answering 500 here is that timeout on a starved host, not the product.
    const heldSince = Date.now();
    let settled = false;
    const inFlight = fire().finally(() => {
      settled = true;
    });
    const deadline = Date.now() + 20_000;
    for (;;) {
      const { rows } = await h.sql.query<{ n: number }>(
        `SELECT count(*)::int AS n FROM pg_stat_activity
          WHERE datname = current_database() AND wait_event_type = 'Lock' AND pid <> $1`,
        [holderPid],
      );
      if (rows[0].n >= waiters) break;
      if (settled) {
        await inFlight;
        assert.fail(`the requests finished while only ${rows[0].n} of ${waiters} were parked on the held row`);
      }
      if (Date.now() > deadline) assert.fail(`only ${rows[0].n} of ${waiters} creates reached the held row`);
      await sleep(10);
    }
    console.log(`owner row held ${Date.now() - heldSince}ms until ${waiters} creates were parked on it`);
    await holder.query('COMMIT');
    return await inFlight;
  } finally {
    await holder.query('ROLLBACK').catch(() => undefined);
    await holder.end().catch(() => undefined);
  }
}

// ── the versioned schema ────────────────────────────────────────────────────────────────────────

test('the served schema is the frozen contract: its predicate version, leaves, kinds, actions, states, refusal codes and limits', () => {
  assert.equal(WATCH_PREDICATE_VERSION, CONTRACT.predicateVersion);
  const contractLeaves = Object.fromEntries(
    Object.entries(CONTRACT.leaves as Record<string, { targetKind: string }>).map(([leaf, { targetKind }]) => [leaf, targetKind]),
  );
  assert.deepEqual(WATCH_LEAVES, contractLeaves);
  // The door and the evaluator read one grammar: what the API accepts is what gets decided.
  assert.deepEqual(WATCH_LEAF_TARGET_KIND, contractLeaves);
  assert.equal(EVALUATED_PREDICATE_VERSION, CONTRACT.predicateVersion);
  assert.deepEqual([...WATCH_RESOURCE_KINDS], CONTRACT.resourceKinds);
  assert.deepEqual([...WATCH_ACTIONS], CONTRACT.actions.map((action: { kind: string }) => action.kind));
  assert.deepEqual([...WATCH_STATES], CONTRACT.states.watch.values);
  assert.deepEqual([...WATCH_REFUSAL_CODES].sort(), CONTRACT.refusals.map((refusal: { code: string }) => refusal.code).sort());
  for (const [limit, value] of Object.entries(WATCH_LIMITS)) {
    assert.equal(value, CONTRACT.limits[limit], `limits.${limit}`);
  }
});

test('a predicate outside the v1 grammar is refused with the contract code, and nothing is written', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'grammar');
  const done = await task(h, owner.id, 'DONE');
  const targets = tasks([done]);

  const refused: Array<[string, Record<string, unknown>, string]> = [
    ['a shell command', { predicate: { kind: 'SHELL', command: 'test -f /tmp/done' } }, 'UNKNOWN_PREDICATE_KIND'],
    ['a SQL query', { predicate: { kind: 'SQL', query: 'SELECT true FROM task' } }, 'UNKNOWN_PREDICATE_KIND'],
    ['a log regex', { predicate: { kind: 'LOG_REGEX', pattern: 'status=DONE$' } }, 'UNKNOWN_PREDICATE_KIND'],
    ['a free-text expression', { predicate: "task.status == 'DONE'" }, 'UNKNOWN_PREDICATE_KIND'],
    ['a script riding on a valid term', { predicate: { ...ALL_TERMINAL, script: 'rm -rf /' } }, 'UNKNOWN_PREDICATE_KIND'],
    ['a leaf outside the seven', { predicate: { ...ALL_TERMINAL, leaf: 'TASK_TERMINAL; DROP TABLE task' } }, 'UNKNOWN_PREDICATE_KIND'],
    ['a selector outside ALL_TARGETS', { predicate: { ...ALL_TERMINAL, over: 'SELECT id FROM task' } }, 'UNKNOWN_PREDICATE_KIND'],
    ['a composite with no operands', { predicate: { kind: 'ALL_OF', operands: [] } }, 'UNKNOWN_PREDICATE_KIND'],
    ['an array', { predicate: [ALL_TERMINAL] }, 'UNKNOWN_PREDICATE_KIND'],
    ['no predicate', { predicate: undefined }, 'UNKNOWN_PREDICATE_KIND'],
    [
      'three terms deep',
      { predicate: { kind: 'ANY_OF', operands: [{ kind: 'ALL_OF', operands: [ALL_TERMINAL] }] } },
      'PREDICATE_TOO_DEEP',
    ],
    ['five operands', { predicate: { kind: 'ANY_OF', operands: Array(5).fill(ALL_TERMINAL) } }, 'PREDICATE_TOO_DEEP'],
    ['no predicateVersion', { predicateVersion: undefined }, 'PREDICATE_VERSION_UNSUPPORTED'],
    ['predicateVersion 2', { predicateVersion: 2 }, 'PREDICATE_VERSION_UNSUPPORTED'],
    ['predicateVersion as text', { predicateVersion: '1' }, 'PREDICATE_VERSION_UNSUPPORTED'],
  ];
  for (const [why, over, code] of refused) {
    expectRefusal(await call(h, owner.bearer, 'POST', '/watches', watchBody(targets, over)), code, why);
  }
  assert.deepEqual(await rowsOf(h, owner.id), NOTHING, 'a refused predicate wrote something');

  // The same request with a predicate the grammar has is accepted, so each refusal above was about
  // its predicate and not about the target, the account or the rest of the body. Every shape the
  // contract lists is accepted, up to both structural limits.
  let accepted = 0;
  for (const kind of CONTRACT.aggregations) {
    for (const leaf of ['TASK_TERMINAL', 'TASK_FAILED', 'TASK_DONE']) {
      await create(h, owner, watchBody(targets, { predicate: { kind, over: CONTRACT.targetSelectors[0], leaf } }), `${kind} ${leaf}`);
      accepted += 1;
    }
  }
  for (const kind of CONTRACT.composites) {
    const operands = Array(WATCH_LIMITS.maxOperandsPerComposite).fill(ALL_TERMINAL);
    await create(h, owner, watchBody(targets, { predicate: { kind, operands } }), `${kind} at its operand limit`);
    accepted += 1;
  }
  assert.equal(accepted, 8);
  assert.equal((await rowsOf(h, owner.id)).watches, accepted);
});

test('create refuses what the contract refuses: an empty set, too many targets, a kind mismatch, a live set, a self-wake loop, a TTL out of range', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'shapes');
  const done = await task(h, owner.id, 'DONE');
  const observer = await session(h, owner.id, { status: 'AWAITING_INPUT' });
  const other = await session(h, owner.id, { status: 'AWAITING_INPUT' });

  const refused: Array<[string, Record<string, unknown>, string]> = [
    ['an empty target set', watchBody([]), 'EMPTY_TARGET_SET'],
    [
      'one target past the limit',
      watchBody(Array.from({ length: WATCH_LIMITS.maxTargetsPerWatch + 1 }, () => ({ kind: 'TASK', id: randomUUID() }))),
      'TOO_MANY_TARGETS',
    ],
    ['a task leaf over a session', watchBody(sessions([other])), 'TARGET_KIND_MISMATCH'],
    [
      'a session leaf inside a composite over tasks',
      watchBody(tasks([done]), { predicate: { kind: 'ANY_OF', operands: [ALL_TERMINAL, ALL_SETTLED] } }),
      'TARGET_KIND_MISMATCH',
    ],
    ['a task list as live membership', watchBody([{ kind: 'TASK_LIST', id: randomUUID(), membership: 'live' }]), 'DYNAMIC_SET_UNSUPPORTED'],
    ['a project as live membership', watchBody([{ kind: 'PROJECT', id: randomUUID() }]), 'DYNAMIC_SET_UNSUPPORTED'],
    [
      'a resume watch naming its own observer',
      watchBody(sessions([other, observer]), { predicate: ALL_SETTLED, action: 'RESUME_SESSION', observerSessionId: observer }),
      'SELF_WATCH_LOOP',
    ],
    ['a TTL under the minimum', watchBody(tasks([done]), { ttlSeconds: WATCH_LIMITS.minTtlSeconds - 1 }), 'TTL_OUT_OF_RANGE'],
    ['a TTL over the maximum', watchBody(tasks([done]), { ttlSeconds: WATCH_LIMITS.maxTtlSeconds + 1 }), 'TTL_OUT_OF_RANGE'],
  ];
  for (const [why, body, code] of refused) {
    expectRefusal(await call(h, owner.bearer, 'POST', '/watches', body), code, why);
  }
  // Refused without a contract code because they are not domain refusals: the request is malformed.
  expectStatus(await call(h, owner.bearer, 'POST', '/watches', watchBody(tasks([done]), { mode: 'CONTINUOUS' })), 400, 'CONTINUOUS is not served');
  expectStatus(await call(h, owner.bearer, 'POST', '/watches', watchBody(tasks([done]), { action: 'RESUME_SESSION' })), 400, 'a resume watch with no observer session');
  expectStatus(await call(h, owner.bearer, 'POST', '/watches', watchBody([{ kind: 'RUNNER', id: randomUUID() }])), 400, 'a kind that is no resource');
  assert.deepEqual(await rowsOf(h, owner.id), NOTHING, 'a refused create wrote something');

  // Each boundary, from the accepted side.
  const { rows } = await h.sql.query<{ id: string }>(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","updated_at","completion_criterion")
     SELECT gen_random_uuid(), 'one of many', $1, 'USER', $1, 'OPEN', now(), 'EVIDENCE_JUDGMENT'
       FROM generate_series(1, ${WATCH_LIMITS.maxTargetsPerWatch}) RETURNING "id"`,
    [owner.id],
  );
  const many = await create(h, owner, watchBody(tasks(rows.map((row) => row.id))), 'exactly the target limit');
  assert.equal(many.targets.length, WATCH_LIMITS.maxTargetsPerWatch);
  assert.equal(many.state, 'ACTIVE');

  for (const ttlSeconds of [WATCH_LIMITS.minTtlSeconds, WATCH_LIMITS.maxTtlSeconds, undefined]) {
    const watch = await create(h, owner, watchBody(tasks([done]), { ttlSeconds }), `ttlSeconds ${ttlSeconds}`);
    assert.equal(
      Date.parse(watch.expiresAt) - Date.parse(watch.createdAt),
      (ttlSeconds ?? WATCH_LIMITS.defaultTtlSeconds) * 1000,
      `ttlSeconds ${ttlSeconds} set the expiry`,
    );
  }
  const resume = await create(
    h,
    owner,
    watchBody(sessions([other]), { predicate: ALL_SETTLED, action: 'RESUME_SESSION', observerSessionId: observer }),
    'a resume watch over a session that is not its observer',
  );
  assert.equal(resume.observerType, 'SESSION');
  assert.equal(toUuid(resume.observerSessionId), observer);
  const twice = await create(h, owner, watchBody([...tasks([done]), ...tasks([done])]), 'a target named twice');
  assert.equal(twice.targets.length, 1, 'a target named twice is one target');
});

// ── evaluation at create ────────────────────────────────────────────────────────────────────────

test('a condition already true at create is matched in the create itself: one Match at generation 1, with its delivery', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'immediate');
  const done = await task(h, owner.id, 'DONE');
  const cancelled = await task(h, owner.id, 'CANCELLED');

  const watch = await create(h, owner, watchBody(tasks([done, cancelled])), 'a create over two terminal tasks');
  assert.equal(watch.state, 'MATCHED');
  assert.equal(watch.generation, 1);
  assert.equal(watch.nextEvaluateAt, null, 'a terminal watch is not scheduled');
  assert.equal(watch.predicateVersion, WATCH_PREDICATE_VERSION);
  assert.equal(watch.mode, 'ONE_SHOT');
  assert.equal(watch.observerType, 'USER');
  assert.deepEqual(watch.targets.map((target: { state: string }) => target.state), ['SATISFIED', 'SATISFIED']);
  assert.equal(watch.matches.length, 1);
  const [match] = watch.matches;
  assert.equal(match.generation, 1);
  assert.equal(match.predicateVersion, WATCH_PREDICATE_VERSION);
  assert.equal(match.reason, 'ALL TASK_TERMINAL 2/2');
  assert.ok(Date.parse(match.perTargetSnapshot.evaluatedAt) > 0, 'the snapshot says when it was taken');
  const byId = (left: { id: string }, right: { id: string }) => left.id.localeCompare(right.id);
  assert.deepEqual(
    match.perTargetSnapshot.targets
      .map((target: Record<string, unknown>) => ({
        kind: target.kind,
        id: toUuid(target.id as string),
        epoch: target.epoch,
        state: target.state,
        changed: target.changed,
        leaves: target.leaves,
        observed: target.observed,
      }))
      .sort(byId),
    [
      { kind: 'TASK', id: done, epoch: 0, state: 'SATISFIED', changed: true, leaves: { TASK_TERMINAL: true }, observed: { status: 'DONE' } },
      { kind: 'TASK', id: cancelled, epoch: 0, state: 'SATISFIED', changed: true, leaves: { TASK_TERMINAL: true }, observed: { status: 'CANCELLED' } },
    ].sort(byId),
  );

  const id = toUuid(watch.id);
  const { rows: stored } = await h.sql.query(
    `SELECT w."state", w."generation", w."next_evaluate_at", m."generation" AS match_generation,
            d."action", d."state" AS delivery_state, d."attempts", d."next_attempt_at"
       FROM "watch" w JOIN "watch_match" m ON m."watch_id" = w."id" JOIN "watch_delivery" d ON d."match_id" = m."id"
      WHERE w."id" = $1`,
    [id],
  );
  assert.equal(stored.length, 1, 'one match and one delivery');
  assert.equal(stored[0].state, 'MATCHED');
  assert.equal(stored[0].match_generation, 1);
  assert.equal(stored[0].action, 'NOTIFY_USER');
  assert.equal(stored[0].delivery_state, 'PENDING');
  assert.equal(stored[0].attempts, 0);
  assert.ok(stored[0].next_attempt_at, 'the delivery is due');
  assert.deepEqual(await rowsOf(h, owner.id), { watches: 1, targets: 2, matches: 1, deliveries: 1 });

  const read = await call(h, owner.bearer, 'GET', `/watches/${watch.id}`);
  expectStatus(read, 200, 'the created watch reads back');
  assert.deepEqual(read.body, watch, 'GET answers what the create answered');

  // The resume action records its own delivery kind, for the observer session it names.
  const observer = await session(h, owner.id, { status: 'AWAITING_INPUT' });
  const resume = await create(
    h,
    owner,
    watchBody(tasks([done]), { action: 'RESUME_SESSION', observerSessionId: observer }),
    'a resume watch over a done task',
  );
  assert.equal(resume.state, 'MATCHED');
  const { rows: resumeDelivery } = await h.sql.query(
    `SELECT d."action" FROM "watch_delivery" d JOIN "watch_match" m ON m."id" = d."match_id" WHERE m."watch_id" = $1`,
    [toUuid(resume.id)],
  );
  assert.deepEqual(resumeDelivery, [{ action: 'RESUME_SESSION' }]);
});

test('the contract leaf vectors decide create-time matches: settled, run-terminal, lifecycle-terminal, needs-attention and task completion stay apart', { skip, timeout: 180_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'vectors');
  let decided = 0;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  for (const vector of CONTRACT.vectors as Array<{ id: string; given: Record<string, any>; expect: Record<string, unknown> }>) {
    const leaves = Object.entries(vector.expect).filter(([key]) => key in WATCH_LEAVES) as Array<[keyof typeof WATCH_LEAVES, boolean]>;
    if (leaves.length === 0) continue;
    const given = vector.given;
    const sessionId = given.session
      ? await session(h, owner.id, {
          status: given.session.status,
          endReason: given.session.endReason ?? null,
          completedAt: given.session.completedAt ? new Date() : null,
          deletedAt: given.session.deletedAt ? new Date() : null,
          pendingApprovals: (given.approvals ?? []).filter((status: string) => status === 'PENDING').length,
        })
      : undefined;
    const taskId = given.task ? await task(h, owner.id, given.task.status) : undefined;
    for (const [leaf, expected] of leaves) {
      const target = WATCH_LEAVES[leaf] === 'SESSION' ? { kind: 'SESSION', id: sessionId } : { kind: 'TASK', id: taskId };
      assert.ok(target.id, `${vector.id}: ${leaf} names a ${WATCH_LEAVES[leaf]} the vector does not give`);
      const watch = await create(
        h,
        owner,
        watchBody([target], { predicate: { kind: 'ALL', over: 'ALL_TARGETS', leaf } }),
        `${vector.id}: ${leaf}`,
      );
      assert.equal(watch.state, expected ? 'MATCHED' : 'ACTIVE', `${vector.id}: ${leaf} should be ${expected}`);
      assert.equal(watch.matches.length, expected ? 1 : 0, `${vector.id}: ${leaf}`);
      decided += 1;
    }
  }
  // Twenty (vector, leaf) pairs in the contract as frozen. Fewer means the vectors stopped being read.
  assert.ok(decided >= 20, `only ${decided} leaf expectations were driven through the API`);
});

test('the canonical "all terminal or any failed" request fires through its ANY branch at create, and does not fire without one', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'canonical');
  const vector = CONTRACT.vectors.find((candidate: { id: string }) => candidate.id === 'all-terminal-or-any-failed');
  const statuses: string[] = vector.given.tasks;
  const ids: string[] = [];
  for (const status of statuses) ids.push(await task(h, owner.id, status));

  const watch = await create(h, owner, watchBody(tasks(ids), { predicate: vector.given.predicate }), 'the canonical request');
  assert.equal(watch.state, vector.expect.matches ? 'MATCHED' : 'ACTIVE');
  // The reason counts each operand's leaf over the set; the operand whose count holds is the branch that fired.
  const operands = /^ANY_OF\((.*)\)$/.exec(watch.matches[0].reason)?.[1].split(', ') ?? [];
  assert.deepEqual(operands, ['ALL TASK_TERMINAL 4/7', 'ANY TASK_FAILED 1/7']);
  const holds = (operand: string) => {
    const [kind, , count] = operand.split(' ');
    const [held, of] = count.split('/').map(Number);
    return kind === 'ALL' ? held === of : held > 0;
  };
  assert.equal(operands.findIndex(holds), vector.expect.viaOperand, 'the branch the contract says fires is the one that held');
  const stateOf = statesById(watch.matches[0].perTargetSnapshot.targets);
  statuses.forEach((status, index) => {
    const terminal = ['DONE', 'CANCELLED', 'FAILED'].includes(status);
    assert.equal(stateOf.get(ids[index]), terminal ? 'SATISFIED' : 'OBSERVED', `a ${status} target`);
  });

  // The paired negative: nothing failed and not everything is terminal, so neither branch holds.
  const quiet = [await task(h, owner.id, 'DONE'), await task(h, owner.id, 'IN_PROGRESS')];
  const waiting = await create(h, owner, watchBody(tasks(quiet), { predicate: vector.given.predicate }), 'no branch holds');
  assert.equal(waiting.state, 'ACTIVE');
  assert.equal(waiting.matches.length, 0);

  const allOf = await create(
    h,
    owner,
    watchBody(tasks([ids[0], ids[1]]), {
      predicate: { kind: 'ALL_OF', operands: [{ kind: 'ANY', over: 'ALL_TARGETS', leaf: 'TASK_DONE' }, ALL_TERMINAL] },
    }),
    'an ALL_OF whose operands both hold',
  );
  assert.equal(allOf.state, 'MATCHED');
  assert.equal(allOf.matches[0].reason, 'ALL_OF(ANY TASK_DONE 2/2, ALL TASK_TERMINAL 2/2)');
});

test('a condition not yet true stays ACTIVE, unmatched and due, and is decided from the rows as they are', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'waiting');
  const open = await task(h, owner.id, 'OPEN');
  const done = await task(h, owner.id, 'DONE');

  const before = Date.now();
  const watch = await create(h, owner, watchBody(tasks([open, done])), 'one target still open');
  assert.equal(watch.state, 'ACTIVE');
  assert.equal(watch.generation, 0);
  assert.deepEqual(watch.matches, []);
  const stateOf = statesById(watch.targets);
  assert.equal(stateOf.get(open), 'OBSERVED');
  assert.equal(stateOf.get(done), 'SATISFIED');
  assert.ok(watch.lastEvaluatedAt, 'the create evaluated it');
  assert.ok(watch.nextEvaluateAt, 'a live watch is scheduled');
  assert.ok(Date.parse(watch.nextEvaluateAt) <= Date.now(), 'and due at once, not at some later tick');
  assert.ok(Date.parse(watch.nextEvaluateAt) >= before - 1000);
  assert.ok(Date.parse(watch.nextEvaluateAt) <= Date.parse(watch.expiresAt));
  assert.deepEqual(await rowsOf(h, owner.id), { watches: 1, targets: 2, matches: 0, deliveries: 0 });

  // The open task then fails. The API does not match on a write it never saw: the watch is still
  // ACTIVE and still due, which is the schedule the evaluation sweep reads.
  await h.sql.query(`UPDATE "task" SET "status" = 'FAILED', "updated_at" = now() WHERE "id" = $1`, [open]);
  const later = await call(h, owner.bearer, 'GET', `/watches/${watch.id}`);
  expectStatus(later, 200, 'read the waiting watch');
  assert.equal(later.body.state, 'ACTIVE');
  assert.deepEqual(later.body.matches, []);
  assert.ok(Date.parse(later.body.nextEvaluateAt) <= Date.now());

  // The same request made now is decided from the rows as they are, and matches.
  const again = await create(h, owner, watchBody(tasks([open, done])), 'the same request after the change');
  assert.equal(again.state, 'MATCHED');
});

// ── permission ──────────────────────────────────────────────────────────────────────────────────

test('another account\'s targets and sessions are unreadable: PERMISSION_DENIED, nothing written, and no oracle for which ids exist', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const alice = await account(h, 'alice');
  const bob = await account(h, 'bob');
  const alicesTask = await task(h, alice.id, 'DONE');
  const alicesSession = await session(h, alice.id, { status: 'AWAITING_INPUT' });
  const bobsTask = await task(h, bob.id, 'DONE');

  const foreign = await call(h, bob.bearer, 'POST', '/watches', watchBody(tasks([alicesTask])));
  expectRefusal(foreign, 'PERMISSION_DENIED', "Bob names Alice's task");
  const missing = await call(h, bob.bearer, 'POST', '/watches', watchBody(tasks([randomUUID()])));
  expectRefusal(missing, 'PERMISSION_DENIED', 'Bob names a task nobody has');
  assert.deepEqual(foreign.body, missing.body, 'a foreign target and a missing one are refused alike');

  expectRefusal(
    await call(h, bob.bearer, 'POST', '/watches', watchBody(tasks([bobsTask, alicesTask]))),
    'PERMISSION_DENIED',
    'one of his own and one of hers: every target must be readable',
  );
  expectRefusal(
    await call(h, bob.bearer, 'POST', '/watches', watchBody(sessions([alicesSession]), { predicate: ALL_SETTLED })),
    'PERMISSION_DENIED',
    "Bob names Alice's session",
  );
  expectRefusal(
    await call(h, bob.bearer, 'POST', '/watches', watchBody(tasks([bobsTask]), { action: 'RESUME_SESSION', observerSessionId: alicesSession })),
    'PERMISSION_DENIED',
    "Bob makes Alice's session the observer to be resumed",
  );
  expectStatus(await call(h, null, 'POST', '/watches', watchBody(tasks([bobsTask]))), 401, 'no bearer');
  expectStatus(await call(h, 'a-bearer-nobody-issued', 'GET', '/watches'), 401, 'a bearer nobody issued');
  assert.deepEqual(await rowsOf(h, bob.id), NOTHING, "a refusal wrote under Bob's account");
  assert.deepEqual(await rowsOf(h, alice.id), NOTHING, "a refusal wrote under Alice's account");

  // Bob's own task is readable, so the refusals above were about whose rows they were.
  const own = await create(h, bob, watchBody(tasks([bobsTask])), "Bob's own task");
  assert.equal(own.state, 'MATCHED');
});

test('another account can neither see nor change a watch', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const alice = await account(h, 'alice');
  const bob = await account(h, 'bob');
  const open = await task(h, alice.id, 'OPEN');
  const watch = await create(h, alice, watchBody(tasks([open])), "Alice's watch");

  const attempts: Array<[string, string, unknown?]> = [
    ['GET', `/watches/${watch.id}`],
    ['PATCH', `/watches/${watch.id}`, { ttlSeconds: 600 }],
    ['POST', `/watches/${watch.id}/pause`],
    ['POST', `/watches/${watch.id}/resume`],
    ['POST', `/watches/${watch.id}/cancel`],
  ];
  for (const [method, route, body] of attempts) {
    expectStatus(await call(h, bob.bearer, method, route, body), 404, `Bob ${method} ${route}`);
  }
  const bobsList = await call(h, bob.bearer, 'GET', '/watches');
  expectStatus(bobsList, 200, "Bob's list");
  assert.deepEqual(bobsList.body, []);

  const unchanged = await call(h, alice.bearer, 'GET', `/watches/${watch.id}`);
  expectStatus(unchanged, 200, "Alice's watch");
  assert.deepEqual(unchanged.body, watch, "nothing Bob sent changed Alice's watch");
  const alicesList = await call(h, alice.bearer, 'GET', '/watches');
  assert.deepEqual(alicesList.body.map((item: { id: string }) => item.id), [watch.id]);
});

// ── deleted targets ─────────────────────────────────────────────────────────────────────────────

test('a deleted target cannot be frozen into a new watch; a trashed session still can, and is lifecycle-terminal; a target deleted later stays in the frozen set', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'deleted');

  const gone = await task(h, owner.id, 'DONE');
  await h.sql.query(`DELETE FROM "task" WHERE "id" = $1`, [gone]);
  const kept = await task(h, owner.id, 'DONE');
  expectRefusal(await call(h, owner.bearer, 'POST', '/watches', watchBody(tasks([gone]))), 'PERMISSION_DENIED', 'a deleted task');
  expectRefusal(
    await call(h, owner.bearer, 'POST', '/watches', watchBody(tasks([kept, gone]))),
    'PERMISSION_DENIED',
    'a live task beside a deleted one',
  );
  assert.deepEqual(await rowsOf(h, owner.id), NOTHING, 'a create naming a deleted target wrote something');

  // Trash keeps the row, so the owner can still read it, and TRASH is lifecycle-terminal.
  const trashed = await session(h, owner.id, { status: 'AWAITING_INPUT', deletedAt: new Date() });
  const lifecycle = await create(
    h,
    owner,
    watchBody(sessions([trashed]), { predicate: { kind: 'ALL', over: 'ALL_TARGETS', leaf: 'SESSION_LIFECYCLE_TERMINAL' } }),
    'a trashed session',
  );
  assert.equal(lifecycle.state, 'MATCHED');
  assert.equal(
    lifecycle.matches[0].perTargetSnapshot.targets[0].observed.lifecycleState,
    'TRASH',
    'the snapshot records the lifecycle it saw',
  );

  // Deleted after the create: the frozen set is not rewritten and the watch still reads back whole.
  const later = await task(h, owner.id, 'OPEN');
  const waiting = await create(h, owner, watchBody(tasks([later, kept])), 'a watch whose target will be deleted');
  await h.sql.query(`DELETE FROM "task" WHERE "id" = $1`, [later]);
  const read = await call(h, owner.bearer, 'GET', `/watches/${waiting.id}`);
  expectStatus(read, 200, 'the watch reads back after its target was deleted');
  assert.equal(read.body.state, 'ACTIVE');
  assert.deepEqual([...statesById(read.body.targets).keys()].sort(), [later, kept].sort());
});

// ── lifecycle ───────────────────────────────────────────────────────────────────────────────────

test('pause, resume, edit and cancel move only along the contract transitions', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'lifecycle');
  const open = await task(h, owner.id, 'OPEN');
  const watch = await create(h, owner, watchBody(tasks([open])), 'a waiting watch');
  const route = `/watches/${watch.id}`;

  const paused = await call(h, owner.bearer, 'POST', `${route}/pause`);
  expectStatus(paused, 200, 'pause');
  assert.equal(paused.body.state, 'PAUSED');
  assert.equal(paused.body.nextEvaluateAt, paused.body.expiresAt, 'a paused watch is still reached at its expiry');
  const pausedAgain = await call(h, owner.bearer, 'POST', `${route}/pause`);
  expectStatus(pausedAgain, 200, 'pause is idempotent');
  assert.deepEqual(pausedAgain.body, paused.body, 'a second pause writes nothing');

  const extended = await call(h, owner.bearer, 'PATCH', route, { ttlSeconds: 120 });
  expectStatus(extended, 200, 'edit the TTL of a paused watch');
  assert.equal(extended.body.state, 'PAUSED');
  assert.ok(Math.abs(Date.parse(extended.body.expiresAt) - (Date.now() + 120_000)) < 30_000, 'the TTL counts from the edit');
  assert.equal(extended.body.nextEvaluateAt, extended.body.expiresAt);

  const resumed = await call(h, owner.bearer, 'POST', `${route}/resume`);
  expectStatus(resumed, 200, 'resume');
  assert.equal(resumed.body.state, 'ACTIVE');
  assert.ok(Date.parse(resumed.body.nextEvaluateAt) <= Date.now(), 'a resumed watch is due at once');
  expectStatus(await call(h, owner.bearer, 'POST', `${route}/resume`), 200, 'resume is idempotent');

  const anyFailed = { kind: 'ANY', over: 'ALL_TARGETS', leaf: 'TASK_FAILED' };
  const edited = await call(h, owner.bearer, 'PATCH', route, { predicateVersion: 1, predicate: anyFailed });
  expectStatus(edited, 200, 'edit the condition');
  assert.deepEqual(edited.body.predicate, anyFailed);
  assert.equal(edited.body.state, 'ACTIVE');
  assert.deepEqual(edited.body.targets, resumed.body.targets, 'the target set is frozen');

  const refusedEdits: Array<[string, Record<string, unknown>, string | number]> = [
    ['a script', { predicateVersion: 1, predicate: { kind: 'SHELL', command: 'exit 0' } }, 'UNKNOWN_PREDICATE_KIND'],
    ['a session leaf over task targets', { predicateVersion: 1, predicate: ALL_SETTLED }, 'TARGET_KIND_MISMATCH'],
    ['a predicate without its version', { predicate: ALL_TERMINAL }, 'PREDICATE_VERSION_UNSUPPORTED'],
    ['a TTL out of range', { ttlSeconds: WATCH_LIMITS.maxTtlSeconds + 1 }, 'TTL_OUT_OF_RANGE'],
    ['nothing to change', {}, 400],
  ];
  for (const [why, body, expected] of refusedEdits) {
    const answer = await call(h, owner.bearer, 'PATCH', route, body);
    if (typeof expected === 'number') expectStatus(answer, expected, why);
    else expectRefusal(answer, expected, why);
  }
  const afterRefusals = await call(h, owner.bearer, 'GET', route);
  assert.deepEqual(afterRefusals.body, edited.body, 'a refused edit changed the watch');

  const cancelled = await call(h, owner.bearer, 'POST', `${route}/cancel`);
  expectStatus(cancelled, 200, 'cancel');
  assert.equal(cancelled.body.state, 'CANCELLED');
  assert.equal(cancelled.body.nextEvaluateAt, null, 'a cancelled watch is not scheduled');
  const cancelledAgain = await call(h, owner.bearer, 'POST', `${route}/cancel`);
  expectStatus(cancelledAgain, 200, 'cancel is idempotent');
  assert.deepEqual(cancelledAgain.body, cancelled.body);
  for (const [method, target, body] of [
    ['POST', `${route}/resume`],
    ['POST', `${route}/pause`],
    ['PATCH', route, { ttlSeconds: 600 }],
  ] as Array<[string, string, unknown?]>) {
    const answer = await call(h, owner.bearer, method, target, body);
    expectStatus(answer, 409, `${method} ${target} on a cancelled watch`);
    assert.equal(answer.body.state, 'CANCELLED');
  }

  // A matched watch is terminal too.
  const done = await task(h, owner.id, 'DONE');
  const matched = await create(h, owner, watchBody(tasks([done])), 'a matched watch');
  for (const verb of ['pause', 'cancel']) {
    const answer = await call(h, owner.bearer, 'POST', `/watches/${matched.id}/${verb}`);
    expectStatus(answer, 409, `${verb} a matched watch`);
    assert.equal(answer.body.state, 'MATCHED');
  }

  const listed = await call(h, owner.bearer, 'GET', '/watches');
  assert.deepEqual(listed.body.map((item: { id: string }) => item.id), [matched.id, watch.id], 'newest first');
  const onlyCancelled = await call(h, owner.bearer, 'GET', '/watches?state=CANCELLED');
  assert.deepEqual(onlyCancelled.body.map((item: { id: string }) => item.id), [watch.id]);
  expectStatus(await call(h, owner.bearer, 'GET', '/watches?state=SOMETIMES'), 400, 'a state the contract does not have');
  expectStatus(await call(h, owner.bearer, 'GET', `/watches/${randomUUID()}`), 404, 'a watch nobody has');
});

// ── idempotency ─────────────────────────────────────────────────────────────────────────────────

test('an idempotency key replays the committed watch, refuses a different request, and belongs to one account', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'idempotent');
  const done = await task(h, owner.id, 'DONE');
  const open = await task(h, owner.id, 'OPEN');
  const body = watchBody(tasks([done]), { idempotencyKey: 'wake-me-once' });

  const first = await create(h, owner, body, 'the first create');
  assert.equal(first.state, 'MATCHED');
  const replayed = await create(h, owner, { ...body, targets: tasks([done, done]) }, 'the same request again');
  assert.deepEqual(replayed, first, 'a replay answers the committed watch');
  assert.deepEqual(await rowsOf(h, owner.id), { watches: 1, targets: 1, matches: 1, deliveries: 1 }, 'a replay wrote something');

  // A replay is a lookup, not a second decision: the world changing does not change the answer.
  const waitingBody = watchBody(tasks([open]), { idempotencyKey: 'still-waiting' });
  const waiting = await create(h, owner, waitingBody, 'a watch that has not matched');
  await h.sql.query(`UPDATE "task" SET "status" = 'CANCELLED', "updated_at" = now() WHERE "id" = $1`, [open]);
  const waitingReplay = await create(h, owner, waitingBody, 'its replay after the target settled');
  assert.equal(waitingReplay.id, waiting.id);
  assert.equal(waitingReplay.state, 'ACTIVE');
  assert.deepEqual(waitingReplay.matches, []);

  const conflicting: Array<[string, Record<string, unknown>]> = [
    ['another target', { targets: tasks([open]) }],
    ['another TTL', { ttlSeconds: 3600 }],
    ['another predicate', { predicate: { kind: 'ANY', over: 'ALL_TARGETS', leaf: 'TASK_TERMINAL' } }],
    ['another action', { action: 'RESUME_SESSION', observerSessionId: await session(h, owner.id, { status: 'AWAITING_INPUT' }) }],
  ];
  const beforeConflicts = await rowsOf(h, owner.id);
  for (const [why, over] of conflicting) {
    expectStatus(await call(h, owner.bearer, 'POST', '/watches', { ...body, ...over }), 409, `the key with ${why}`);
  }
  assert.deepEqual(await rowsOf(h, owner.id), beforeConflicts, 'a refused key reuse wrote something');
  assert.deepEqual((await call(h, owner.bearer, 'GET', `/watches/${first.id}`)).body, first);

  // The key is the account's own. A stranger replaying the owner's exact request finds nothing under
  // its own account, so it is decided afresh — and refused on the owner's task — rather than handed
  // the owner's watch. Its own use of the same string then makes its own watch.
  const stranger = await account(h, 'stranger');
  expectRefusal(await call(h, stranger.bearer, 'POST', '/watches', body), 'PERMISSION_DENIED', "a stranger replaying the owner's request");
  const strangersDone = await task(h, stranger.id, 'DONE');
  const theirs = await create(h, stranger, watchBody(tasks([strangersDone]), { idempotencyKey: 'wake-me-once' }), 'the same key under another account');
  assert.notEqual(toUuid(theirs.id), toUuid(first.id));
  assert.deepEqual((await call(h, owner.bearer, 'GET', `/watches/${first.id}`)).body, first, "the stranger's key left the owner's watch alone");

  // The committed watch comes back before any gate: its target has since been deleted, and a
  // retry of the create that made it still reads it back rather than being refused.
  await h.sql.query(`DELETE FROM "task" WHERE "id" = $1`, [done]);
  const afterDeletion = await create(h, owner, body, 'a retry after the target was deleted');
  assert.equal(afterDeletion.id, first.id);
  expectRefusal(
    await call(h, owner.bearer, 'POST', '/watches', { ...body, idempotencyKey: 'a-fresh-key' }),
    'PERMISSION_DENIED',
    'a fresh key over the deleted target',
  );
});

// ── concurrency ─────────────────────────────────────────────────────────────────────────────────

test('concurrent creates with one key and one request make one watch, one Match and one delivery', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'concurrent-key');
  const done = await task(h, owner.id, 'DONE');
  const body = watchBody(tasks([done]), { idempotencyKey: 'racing' });
  const racers = 3;

  const answers = await whileOwnerRowIsHeld(h, owner.id, racers, () =>
    Promise.all(Array.from({ length: racers }, () => call(h, owner.bearer, 'POST', '/watches', body))),
  );
  answers.forEach((answer, index) => expectStatus(answer, 201, `racer ${index}`));
  assert.equal(new Set(answers.map((answer) => toUuid(answer.body.id))).size, 1, 'every racer got the same watch');
  for (const answer of answers) {
    assert.equal(answer.body.state, 'MATCHED');
    assert.equal(answer.body.matches.length, 1);
  }
  assert.deepEqual(await rowsOf(h, owner.id), { watches: 1, targets: 1, matches: 1, deliveries: 1 });
});

test('concurrent creates with one key and two different requests make one watch, and the other request is refused', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'concurrent-conflict');
  const done = await task(h, owner.id, 'DONE');
  const cancelled = await task(h, owner.id, 'CANCELLED');
  const variants = [
    watchBody(tasks([done]), { idempotencyKey: 'contested' }),
    watchBody(tasks([cancelled]), { idempotencyKey: 'contested' }),
  ];
  const sent = [0, 1, 0, 1];

  const answers = await whileOwnerRowIsHeld(h, owner.id, sent.length, () =>
    Promise.all(sent.map((variant) => call(h, owner.bearer, 'POST', '/watches', variants[variant]))),
  );
  const winners = sent.filter((_, index) => answers[index].status === 201);
  assert.equal(winners.length, 2, `answers: ${answers.map((answer) => answer.status).join(', ')}`);
  assert.equal(new Set(winners).size, 1, 'every 201 was sent the same request');
  sent.forEach((variant, index) => {
    expectStatus(answers[index], variant === winners[0] ? 201 : 409, `racer ${index} with request ${variant}`);
  });
  assert.equal(new Set(answers.filter((answer) => answer.status === 201).map((answer) => toUuid(answer.body.id))).size, 1);
  assert.deepEqual(await rowsOf(h, owner.id), { watches: 1, targets: 1, matches: 1, deliveries: 1 });
});

test('concurrent creates without a key each make their own watch, with exactly one Match apiece', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'concurrent-unkeyed');
  const done = await task(h, owner.id, 'DONE');
  const racers = 3;

  const answers = await whileOwnerRowIsHeld(h, owner.id, racers, () =>
    Promise.all(Array.from({ length: racers }, () => call(h, owner.bearer, 'POST', '/watches', watchBody(tasks([done]))))),
  );
  answers.forEach((answer, index) => expectStatus(answer, 201, `racer ${index}`));
  assert.equal(new Set(answers.map((answer) => toUuid(answer.body.id))).size, racers, 'no two racers share a watch');
  const { rows } = await h.sql.query<{ matches: number }>(
    `SELECT count(m."id")::int AS matches FROM "watch" w LEFT JOIN "watch_match" m ON m."watch_id" = w."id"
      WHERE w."owner_id" = $1 GROUP BY w."id"`,
    [owner.id],
  );
  assert.deepEqual(rows.map((row) => row.matches), Array(racers).fill(1));
  assert.deepEqual(await rowsOf(h, owner.id), { watches: racers, targets: racers, matches: racers, deliveries: racers });
});
