-- Codex earned rate-limit reset: the operation a user's confirmation creates, and the two facts about
-- a runner's last heartbeat that decide whether one may be created
-- (docs/codex-rate-limit-reset-contract.md §5, §7, §9.3). Admission and persistence only: nothing here
-- hands a command to a runner or calls a provider.
--
-- WHAT A ROW IS
-- =============
-- One confirmed reset, scoped to one owner, one runner and one account fingerprint. It carries two
-- idempotency keys with different jobs (§5), and neither may stand in for the other:
--   * `client_request_id` is the browser's: one per confirmation, reused by every retry of that POST.
--     Unique per owner, so a retried POST finds the row it already created instead of adding a second.
--   * `provider_idempotency_key` is the provider's: generated by the apiserver in the transaction that
--     inserts the row, and never replaced. It is the only key `account/rateLimitResetCredit/consume` is
--     ever sent, so "one confirmation consumes at most one credit" rests on this column being written
--     exactly once. No user-facing response carries it.
-- Progress is two checkpoints persisted apart (§7.1, §7.2): the consume (`consume_state`, with the
-- provider's `consume_outcome` and `consume_confirmed_at`) and the authoritative read after it
-- (`refresh_state`). The status clients read is derived from the pair (§7.3) and never stored. The claim
-- columns are the heartbeat relay's delivery fence (§7.4); `failure_code` says why a settled operation
-- did not succeed, `last_error_code` the latest recoverable problem while it was active.
--
-- WHAT THE DATABASE REFUSES, WHATEVER WROTE IT
-- ============================================
--   * a second active operation for one runner and account (I1): a partial unique index whose predicate
--     is exactly the checkpoint combinations the contract calls active (PENDING, CONSUMING, REFRESHING);
--   * a checkpoint combination §7.3 does not list, and a failure code, completion time or confirmation
--     time that disagrees with the combination beside it (CHECKs). A CHECK whose expression is NULL
--     passes, so the one nullable column compared inside them goes through COALESCE;
--   * a change to an immutable column, a checkpoint moving anywhere §7.1 / §7.2 does not allow, a
--     recorded outcome or confirmation time being rewritten, `claim_generation` going down, and any
--     change at all to a settled row (I3, I5, I6): the guard trigger, which states in SQL what
--     `codexResetTransitionViolations` states in TypeScript.
--
-- THE RUNNER COLUMNS
-- ==================
-- `heartbeat_lease_owner` and `heartbeat_draining` are what the LAST heartbeat said about the process
-- sending it, overwritten by every heartbeat. A runner too old to send them writes NULL, which admission
-- reads as NO_ACTIVE_LEASE and not draining; such a runner does not declare the capability either.
-- Both are nullable with no default: a catalog-only change with nothing to backfill.
--
-- NUMBERING, RE-RUNNABILITY, ROLLBACK
-- ===================================
-- 0255 is the next number above every migration on main and in every open worktree. Every statement is
-- re-runnable: IF NOT EXISTS, constraints added inside a `duplicate_object` guard, the function replaced
-- in place and its trigger dropped by name before being created. `down.sql` beside this file reverses it
-- and is re-runnable the same way; `scripts/test-codex-reset-operation.sh` runs both directions.

ALTER TABLE "runner" ADD COLUMN IF NOT EXISTS "heartbeat_lease_owner" UUID;
ALTER TABLE "runner" ADD COLUMN IF NOT EXISTS "heartbeat_draining" BOOLEAN;

CREATE TABLE IF NOT EXISTS "codex_rate_limit_reset_operation" (
  "id"                       UUID PRIMARY KEY,
  "owner_id"                 UUID NOT NULL,
  "runner_id"                UUID NOT NULL,
  -- `cxa1_` + 32 hex, computed by the runner. Never an account id, an email or a token.
  "account_fingerprint"      TEXT NOT NULL,
  "client_request_id"        UUID NOT NULL,
  "provider_idempotency_key" UUID NOT NULL,
  "consume_state"            TEXT NOT NULL,
  "consume_outcome"          TEXT,
  "refresh_state"            TEXT NOT NULL,
  "failure_code"             TEXT,
  "last_error_code"          TEXT,
  "claim_lease_owner"        UUID,
  "claim_generation"         INTEGER NOT NULL DEFAULT 0,
  "claimed_at"               TIMESTAMPTZ(3),
  "claims_with_unknown_call" INTEGER NOT NULL DEFAULT 0,
  "created_at"               TIMESTAMPTZ(3) NOT NULL,
  "updated_at"               TIMESTAMPTZ(3) NOT NULL,
  "consume_confirmed_at"     TIMESTAMPTZ(3),
  "completed_at"             TIMESTAMPTZ(3)
);

DO $$ BEGIN
  ALTER TABLE "codex_rate_limit_reset_operation"
    ADD CONSTRAINT "codex_rate_limit_reset_operation_owner_id_fkey"
      FOREIGN KEY ("owner_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT "codex_rate_limit_reset_operation_runner_id_fkey"
      FOREIGN KEY ("runner_id") REFERENCES "runner"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "codex_rate_limit_reset_operation"
    ADD CONSTRAINT "codex_rate_limit_reset_operation_account_fingerprint_check"
      CHECK ("account_fingerprint" ~ '^cxa1_[0-9a-f]{32}$'),
    ADD CONSTRAINT "codex_rate_limit_reset_operation_values_check" CHECK (
      "consume_state" IN ('PENDING', 'CLAIMED', 'CONFIRMED', 'NOT_ATTEMPTED', 'UNRESOLVED')
      AND "refresh_state" IN ('NONE', 'PENDING', 'SUCCEEDED', 'FAILED', 'NOT_REQUIRED')
      AND ("consume_outcome" IS NULL
        OR "consume_outcome" IN ('reset', 'nothingToReset', 'noCredit', 'alreadyRedeemed'))
      AND ("failure_code" IS NULL
        OR "failure_code" IN ('ACCOUNT_MISMATCH', 'UNSUPPORTED_AUTH', 'PROVIDER_UNSUPPORTED',
          'PROTOCOL_UNSUPPORTED', 'ACCOUNT_CHANGED', 'CONSUME_EXPIRED', 'REFRESH_EXPIRED'))
      AND ("last_error_code" IS NULL
        OR "last_error_code" IN ('ACCOUNT_MISMATCH', 'UNSUPPORTED_AUTH', 'PROVIDER_UNSUPPORTED',
          'PROTOCOL_UNSUPPORTED', 'PROVIDER_ERROR', 'PROVIDER_TIMEOUT', 'APP_SERVER_UNAVAILABLE',
          'READ_FAILED', 'ACCOUNT_UNIDENTIFIED', 'RUNNER_DRAINING'))
      AND "claim_generation" >= 0
      AND "claims_with_unknown_call" >= 0
    ),
    -- §7.3, row for row: every combination the status derivation lists, and nothing else.
    ADD CONSTRAINT "codex_rate_limit_reset_operation_checkpoints_check" CHECK (
      ("consume_state" IN ('PENDING', 'CLAIMED')
        AND "consume_outcome" IS NULL AND "refresh_state" = 'NONE')
      OR ("consume_state" = 'CONFIRMED'
        AND COALESCE("consume_outcome", '') IN ('reset', 'alreadyRedeemed')
        AND "refresh_state" IN ('PENDING', 'SUCCEEDED', 'FAILED'))
      OR ("consume_state" = 'CONFIRMED'
        AND COALESCE("consume_outcome", '') IN ('nothingToReset', 'noCredit')
        AND "refresh_state" = 'NOT_REQUIRED')
      OR ("consume_state" IN ('NOT_ATTEMPTED', 'UNRESOLVED')
        AND "consume_outcome" IS NULL AND "refresh_state" = 'NOT_REQUIRED')
    ),
    -- A failure code exactly on REFRESH_FAILED, NOT_ATTEMPTED and UNRESOLVED.
    ADD CONSTRAINT "codex_rate_limit_reset_operation_failure_code_check" CHECK (
      ("failure_code" IS NOT NULL)
        = ("consume_state" IN ('NOT_ATTEMPTED', 'UNRESOLVED') OR "refresh_state" = 'FAILED')
    ),
    -- A completion time exactly when the operation is no longer active.
    ADD CONSTRAINT "codex_rate_limit_reset_operation_completed_at_check" CHECK (
      ("completed_at" IS NULL)
        = ("consume_state" IN ('PENDING', 'CLAIMED')
          OR ("consume_state" = 'CONFIRMED' AND "refresh_state" = 'PENDING'))
    ),
    -- A confirmation time exactly when the consume is CONFIRMED.
    ADD CONSTRAINT "codex_rate_limit_reset_operation_consume_confirmed_at_check" CHECK (
      ("consume_confirmed_at" IS NOT NULL) = ("consume_state" = 'CONFIRMED')
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- I2: one operation per confirmation of one owner.
CREATE UNIQUE INDEX IF NOT EXISTS "codex_rate_limit_reset_operation_owner_id_client_request_id_key"
  ON "codex_rate_limit_reset_operation" ("owner_id", "client_request_id");

-- One provider key per operation, and never the same key for two.
CREATE UNIQUE INDEX IF NOT EXISTS "codex_rate_limit_reset_operation_provider_idempotency_key_key"
  ON "codex_rate_limit_reset_operation" ("provider_idempotency_key");

-- I1: at most one active operation per runner and account. The predicate is the one
-- `codexResetOperationStatus` calls active, spelled over the two checkpoints.
CREATE UNIQUE INDEX IF NOT EXISTS "codex_rate_limit_reset_operation_in_flight_key"
  ON "codex_rate_limit_reset_operation" ("runner_id", "account_fingerprint")
  WHERE "consume_state" IN ('PENDING', 'CLAIMED')
     OR ("consume_state" = 'CONFIRMED' AND "refresh_state" = 'PENDING');

-- A runner's page reads its active and most recent operation; the runner cascade uses it too.
CREATE INDEX IF NOT EXISTS "codex_rate_limit_reset_operation_runner_id_created_at_idx"
  ON "codex_rate_limit_reset_operation" ("runner_id", "created_at");

CREATE OR REPLACE FUNCTION "codex_rate_limit_reset_operation_guard"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW."id" IS DISTINCT FROM OLD."id"
     OR NEW."owner_id" IS DISTINCT FROM OLD."owner_id"
     OR NEW."runner_id" IS DISTINCT FROM OLD."runner_id"
     OR NEW."account_fingerprint" IS DISTINCT FROM OLD."account_fingerprint"
     OR NEW."client_request_id" IS DISTINCT FROM OLD."client_request_id"
     OR NEW."provider_idempotency_key" IS DISTINCT FROM OLD."provider_idempotency_key"
     OR NEW."created_at" IS DISTINCT FROM OLD."created_at" THEN
    RAISE EXCEPTION 'codex rate-limit reset operation %: id, owner_id, runner_id, account_fingerprint, client_request_id, provider_idempotency_key and created_at are immutable', OLD."id"
      USING ERRCODE = 'check_violation';
  END IF;
  IF NOT (OLD."consume_state" IN ('PENDING', 'CLAIMED')
          OR (OLD."consume_state" = 'CONFIRMED' AND OLD."refresh_state" = 'PENDING'))
     AND NEW IS DISTINCT FROM OLD THEN
    RAISE EXCEPTION 'codex rate-limit reset operation %: a settled operation never changes', OLD."id"
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW."consume_state" <> OLD."consume_state" AND NOT (
       (OLD."consume_state" = 'PENDING' AND NEW."consume_state" IN ('CLAIMED', 'NOT_ATTEMPTED'))
    OR (OLD."consume_state" = 'CLAIMED' AND NEW."consume_state" IN ('CONFIRMED', 'NOT_ATTEMPTED', 'UNRESOLVED'))
  ) THEN
    RAISE EXCEPTION 'codex rate-limit reset operation %: consume_state may not move from % to %',
      OLD."id", OLD."consume_state", NEW."consume_state"
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW."refresh_state" <> OLD."refresh_state" AND NOT (
       (OLD."refresh_state" = 'NONE' AND NEW."refresh_state" IN ('PENDING', 'NOT_REQUIRED'))
    OR (OLD."refresh_state" = 'PENDING' AND NEW."refresh_state" IN ('SUCCEEDED', 'FAILED'))
  ) THEN
    RAISE EXCEPTION 'codex rate-limit reset operation %: refresh_state may not move from % to %',
      OLD."id", OLD."refresh_state", NEW."refresh_state"
      USING ERRCODE = 'check_violation';
  END IF;
  IF OLD."consume_outcome" IS NOT NULL AND NEW."consume_outcome" IS DISTINCT FROM OLD."consume_outcome" THEN
    RAISE EXCEPTION 'codex rate-limit reset operation %: consume_outcome is immutable once recorded', OLD."id"
      USING ERRCODE = 'check_violation';
  END IF;
  IF OLD."consume_confirmed_at" IS NOT NULL
     AND NEW."consume_confirmed_at" IS DISTINCT FROM OLD."consume_confirmed_at" THEN
    RAISE EXCEPTION 'codex rate-limit reset operation %: consume_confirmed_at is immutable once recorded', OLD."id"
      USING ERRCODE = 'check_violation';
  END IF;
  IF NEW."claim_generation" < OLD."claim_generation" THEN
    RAISE EXCEPTION 'codex rate-limit reset operation %: claim_generation never decreases', OLD."id"
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "codex_rate_limit_reset_operation_guard" ON "codex_rate_limit_reset_operation";
CREATE TRIGGER "codex_rate_limit_reset_operation_guard"
  BEFORE UPDATE ON "codex_rate_limit_reset_operation"
  FOR EACH ROW EXECUTE FUNCTION "codex_rate_limit_reset_operation_guard"();
