#!/usr/bin/env python3
"""Lift the views under test out of the app's own AgentsView.swift, verbatim.

The probe screenshots the REAL views, not a re-typed copy — a copy that had drifted would make
this a screenshot of the copy. AgentsView.swift as a whole cannot be compiled into a throwaway
app (it imports AppModel, AgentsModel and the rest of the app), so the six leaf views that draw
the status marks are lifted out of it by name, braces matched, and reprinted byte for byte.

Exits non-zero if a name is missing: a silently empty extraction would render a blank screen and
cost a whole Mac runner to diagnose.
"""
import re
import sys

WANTED = [
    "SpinnerGlyph",
    "BreathingGlyph",
    "StatusGlyphView",
    "SessionLiveIndicator",
    "WorkspaceFolderIcon",
    "WorkspaceNavigationRow",
]


def extract(source: str, name: str) -> str:
    start = re.search(rf"^(?:@\w+\s+)*struct {name}\b[^{{]*\{{", source, re.M)
    if not start:
        sys.exit(f"extract_views: no `struct {name}` in AgentsView.swift")
    depth = 0
    i = start.end() - 1
    while i < len(source):
        if source[i] == "{":
            depth += 1
        elif source[i] == "}":
            depth -= 1
            if depth == 0:
                body = source[start.start(): i + 1]
                # The two workspace views live inside `#if os(iOS)`; the probe IS an iOS build.
                return body
        i += 1
    sys.exit(f"extract_views: unbalanced braces after `struct {name}`")


def main() -> None:
    path = sys.argv[1]
    out = sys.argv[2]
    source = open(path, encoding="utf-8").read()
    parts = [extract(source, name) for name in WANTED]
    header = (
        "// GENERATED by .ios-probe/extract_views.py from\n"
        "// src/macos/OrbitApp/Sources/OrbitApp/Views/AgentsView.swift — verbatim, do not edit.\n"
        "import SwiftUI\nimport OrbitKit\n\n"
    )
    open(out, "w", encoding="utf-8").write(header + "\n\n".join(parts) + "\n")
    print(f"extracted {len(parts)} views -> {out}")


if __name__ == "__main__":
    main()
