#!/usr/bin/env python3
"""TEMPORARY evidence probe: put the real start card, change card, receipt and Project started card
into the probe apps, so the pictures are of the code the task branch ships.

- Views/Typography.swift, Platform.swift and Views/ProjectStartedCardView.swift go in whole.
- Out of Views/ApprovalCards.swift, verbatim: the card language (ApprovalMetrics, the two View
  extensions, ApprovalHeader, ApprovalActions) and everything from "the record a confirmation leaves"
  up to "the two cards a project's OWNER answers" — the receipt, Start this project?, Confirm the new
  criteria?, their section heads and panels, and the settings line. The three cards the probe's root
  draws are file-private there; here only their `private` is dropped, so another file can name them.

usage: gen.py <repo root> <out dir>
"""
import sys
from pathlib import Path

root, out = Path(sys.argv[1]), Path(sys.argv[2])
app = root / "src/macos/OrbitApp/Sources/OrbitApp"
out.mkdir(parents=True, exist_ok=True)


def lines(path):
    return path.read_text(encoding="utf-8").split("\n")


def block(src, start, exact=False):
    for first in range(len(src)):
        hit = src[first].strip() == start if exact else start in src[first]
        if not hit:
            continue
        depth = 0
        stop = first
        for stop in range(first, len(src)):
            depth += src[stop].count("{") - src[stop].count("}")
            if depth <= 0 and stop > first:
                break
        # The doc comment above the declaration comes with it.
        head = first
        while head > 0 and src[head - 1].strip().startswith("///"):
            head -= 1
        return "\n".join(src[head:stop + 1])
    sys.exit(f"gen.py: no `{start}`")


def region(src, start, end):
    try:
        a = next(i for i, line in enumerate(src) if line.strip() == start)
        b = next(i for i, line in enumerate(src) if i > a and line.strip() == end)
    except StopIteration:
        sys.exit(f"gen.py: no region `{start}` … `{end}`")
    return "\n".join(src[a:b])


def write(name, text):
    (out / name).write_text(text, encoding="utf-8")
    print(f"==> generated {name} ({len(text.splitlines())} lines)")


for rel in ["Views/Typography.swift", "Platform.swift", "Views/ProjectStartedCardView.swift"]:
    write(Path(rel).name, (app / rel).read_text(encoding="utf-8"))

cards = lines(app / "Views/ApprovalCards.swift")
parts = [
    block(cards, "private enum ApprovalMetrics {"),
    block(cards, "private extension View {", exact=True),
    block(cards, "extension View {", exact=True),
    block(cards, "private struct ApprovalHeader: View {"),
    block(cards, "struct ApprovalActions<Content: View>: View {"),
    region(cards, "// MARK: - the record a confirmation leaves",
           "// MARK: - the two cards a project's OWNER answers"),
]
text = "\n\n".join(parts)
for name in ["AcceptanceConfirmationReceiptCard", "StartProjectCardView", "CriteriaChangeCardView"]:
    declaration = f"private struct {name}: View {{"
    if declaration not in text:
        sys.exit(f"gen.py: no `{declaration}` in the cut")
    text = text.replace(declaration, f"struct {name}: View {{")
write("Cards.swift", "import SwiftUI\nimport OrbitKit\n\n"
      "// GENERATED by gen.py: cut verbatim out of ApprovalCards.swift (three `private`s dropped).\n\n"
      + text + "\n")
