/**
 * A plan drafted and revised on the server (contracts/wiki.contract.json `plan.jobs.server`, design §8, P6),
 * against a real PostgreSQL, the real doors and plan service, a System model played by a local Node http server,
 * and the space's runner played by this file: it claims the job's repository operations and answers them with
 * the snapshot index and the file texts of `wiki-plan.fixture.json` — a real checkout, indexed by the runner's own
 * code.
 *
 * The cases are `src/runner-go/wiki_plan_job_test.go`'s, as the server runs them — the command's own half (its
 * flags, its work directory, its clean Claude Code) stays the runner's and is tested there:
 *
 *   1. a draft in four steps — the catalogue, each category's details, each document's outline, the rules beside
 *      them — every call a queue request at the plan's max_tokens, each outline given its own document's
 *      materials; gated here and on the server, stored as the job's version; its rounds on the plan job, which is
 *      what the plan page reads; no task, no session;
 *   2. a catalogue outside the target is written again before any document of it, with the gate's own count error;
 *   3. a count still outside after two tries is the gate's, and three rounds end the plan job failed with the
 *      last errors and the last draft;
 *   4. every file, docs section and symbol is checked on the snapshot — a symbol the index does not name by the
 *      text a read at the sha brings — and only the document with errors is written again, told every one;
 *   5. what the server's gate finds goes back to the model the same way, and three rounds of it fail the job;
 *   6. a revision keeps the protected document as it is, moves only a convention into the agents' category,
 *      holds the count, and names the projects it hands the model by title;
 *   7. a job taken over after its worker died, or replayed after its draft was stored, asks nothing twice and
 *      stores one version — and a snapshot that moved under it makes it start over;
 *   8. a job runs only as its own: one whose plan job ended asks nothing, and a revision without the owner's
 *      words ends failed;
 *   9. where the switch puts a plan job: a wiki_job at the owner's priority under server and for a listed canary
 *      account, a task under runner and for an account canary does not list — and a job that never started is
 *      cancelled when the switch moves back;
 *  10. the runner door hands no session a plan job when the server drafts (WIKI_SERVER_EXECUTES), so an `orbit
 *      wiki plan draft` that predates this asks no model — while a build job's session, the runner's until the
 *      documents move (P7), keeps its job routes; under runner it answers exactly as it always has.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki-worker/wiki-plan-draft-job.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every row belongs to an account the run created.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import type { AddressInfo, Socket } from 'node:net';
import path from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { after, afterEach, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { toUuid, uuidToBase62, WIKI_MODEL_QUEUE, WIKI_PLAN_SERVER_JOB, WIKI_REPO_OP_CAPABILITY, WIKI_REPO_OPS } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { encryptSecret } from '../providers/provider-crypto';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiPlanController } from '../runner-api/runner-wiki-plan.controller';
import { WikiPlans } from '../wiki/wiki-plan';
import { WikiPlanController } from '../wiki/wiki-plan.controller';
import { WikiRetrieval } from '../wiki/wiki-retrieval';
import { WikiController } from '../wiki/wiki.controller';
import { WikiService } from '../wiki/wiki.service';
import { WikiJobExecutor } from './wiki-job-executor';
import { WikiModelRequestQueue } from './wiki-model-queue.service';
import { WikiModelStatusProbe } from './wiki-model-status';
import { wikiPlanDraftJobRunner } from './wiki-plan-draft-job';
import { WIKI_PLAN_SYSTEM_PROMPT } from './wiki-plan-prompts';
import { WikiRepoOps } from './wiki-repo-ops';
import { readWikiSystemModel, type WikiSystemModelConfig } from './wiki-system-model';

const URL_ = process.env.COORDINATOR_PG_URL;
const skip = !URL_;
process.env.PROVIDER_SECRET_KEY ??= 'wiki-plan-draft-job-spec';

const KEY = `sk-spec-${randomUUID()}`;
const MODEL = 'qwen3.8-27b-fp8';

/** The repository the played runner reads: a real checkout's snapshot index and file texts, the Go side's own. */
const FIXTURE = JSON.parse(readFileSync(path.resolve(__dirname, '../../../shared/src/wiki-plan.fixture.json'), 'utf8')) as {
  files: Record<string, string>;
  index: { sha: string } & Record<string, unknown>;
  rounds: Array<{ name: string; catalogue: string; details: Record<string, string>; outlines: Record<string, string> }>;
};
const CLEAN = FIXTURE.rounds.find((round) => round.name === 'draft-clean')!;
const SHA = FIXTURE.index.sha;

// The answers of wiki_plan_job_test.go: the four steps right, and a document's outline wrong.
const SKELETON = CLEAN.catalogue;
const SKELETON_FOUR = '## 1. 产品 `product` —— 这个服务是什么、怎么运转\n'
  + '- 1.1 服务概览 `service-overview`｜这个服务是什么、由哪些部分组成｜含：定位；组件；入口\n'
  + '- 1.2 存储 `storage`｜数据怎么存、怎么取｜含：Store；保存\n'
  + '- 1.3 发布渠道 `release-channels`｜版本从哪里发出去｜含：渠道；节奏\n'
  + '## 2. 开发约定 `dev` —— 给写代码的 agent 看的约定 [agents]\n'
  + '- 2.1 测试约定 `testing`｜怎么跑测试｜含：go test；夹具\n';
const OUTLINE_STORAGE = CLEAN.outlines.storage;
const OUTLINE_OVERVIEW = CLEAN.outlines['service-overview'];
const OUTLINE_STORAGE_WRONG = '### 1. 保存流程 | flow | 500\n讲什么：Store.Load 怎么读，见 9.9。\n'
  + '- 文档：docs/wiki-design.md § 5. 不存在的章节\n- 代码：src/app/store.go: Store.Save, Store.Load, localHelper\n- 代码：src/app/missing.go: Foo\n'
  + '- 代码：src/web/client.ts: localHelper\n- 备注：这一行不在格式里\n'
  + '### 2. 约定 | conventions | 200\n讲什么：保存前先校验。\n';
const RULES = '## 引用规则\n1. 脚注引一手原文。\n## 归并规则\n1. 新决定覆盖旧的。\n## 维护规则\n1. 只重写受影响的节。\n';

// ── the System model ─────────────────────────────────────────────────────────────────────────────────

interface Hit {
  prompt: string;
  system: string;
  body: Record<string, unknown>;
  authorization: string;
}

/** The scripted model of wiki_plan_job_test.go (`planModel`): each prompt answered by what it asks. */
interface PlanModel {
  skeleton?: (n: number) => string;
  outline?: (title: string) => string | undefined;
  redo?: (title: string, prompt: string) => string;
  revise?: (round: number, prompt: string) => string;
  rewrite?: (title: string) => string;
  /** Called with each prompt before it is answered: what a case does at a moment of the run. */
  onPrompt?: (prompt: string) => Promise<void> | void;
}

interface FakeModel {
  base: string;
  hits: Hit[];
  script: PlanModel;
  skeletons: number;
  rounds: number;
  /** Answer with this status instead, while it is set. */
  status: number;
  close: () => Promise<void>;
}

const TITLE_IN = /《([^》]+)》/u;

function answerOf(model: FakeModel, prompt: string): string {
  const s = model.script;
  const title = TITLE_IN.exec(prompt.slice(prompt.lastIndexOf('# 任务')))?.[1] ?? '';
  if (prompt.includes('第一步：文档目录的骨架') || prompt.includes('# 任务：改正 wiki「')) {
    model.skeletons += 1;
    return s.skeleton ? s.skeleton(model.skeletons) : SKELETON;
  }
  if (prompt.includes('第二步：给大类「产品」')) return CLEAN.details['1'];
  if (prompt.includes('第二步：给大类「开发约定」')) return CLEAN.details['2'];
  if (prompt.includes('第三步 —— 给《')) return s.outline?.(title) ?? ({ 服务概览: OUTLINE_OVERVIEW, 存储: OUTLINE_STORAGE, 测试约定: CLEAN.outlines.testing } as Record<string, string>)[title] ?? '';
  if (prompt.includes('第四步 —— 三条规则的草案')) return RULES;
  if (prompt.includes('按 owner 的要求修订 plan 的目录')) {
    model.rounds += 1;
    return s.revise!(model.rounds, prompt);
  }
  if (prompt.includes('# 任务：写新草稿里《')) return s.rewrite!(title);
  if (prompt.includes('# 任务：改正 plan 里《')) return s.redo!(title, prompt);
  return '（不认得的提示）';
}

async function fakeModel(): Promise<FakeModel> {
  const sockets = new Set<Socket>();
  const model = { base: '', hits: [] as Hit[], script: {}, skeletons: 0, rounds: 0, status: 200 } as FakeModel;
  const server = createServer((request: IncomingMessage, response: ServerResponse) => {
    let raw = '';
    request.on('data', (chunk: Buffer) => {
      raw += chunk.toString();
    });
    request.on('end', () => {
      void (async () => {
        if (request.url === '/health') {
          response.writeHead(200, { 'content-type': 'application/json' });
          response.end('{}');
          return;
        }
        const body = JSON.parse(raw) as { system?: string; messages?: Array<{ content?: string }> };
        const prompt = body.messages?.[0]?.content ?? '';
        model.hits.push({ prompt, system: body.system ?? '', body: body as Record<string, unknown>, authorization: String(request.headers.authorization ?? '') });
        if (model.status !== 200) {
          response.writeHead(model.status, { 'content-type': 'application/json' });
          response.end(JSON.stringify({ type: 'error', error: { type: 'api_error', message: 'away' } }));
          return;
        }
        await model.script.onPrompt?.(prompt);
        const text = answerOf(model, prompt);
        response.writeHead(200, { 'content-type': 'text/event-stream' });
        const event = (name: string, data: unknown) => `event: ${name}\ndata: ${JSON.stringify(data)}\n\n`;
        response.write(event('message_start', { type: 'message_start', message: { model: MODEL, usage: { input_tokens: 100, output_tokens: 1 } } }));
        response.write(event('content_block_delta', { type: 'content_block_delta', index: 0, delta: { type: 'text_delta', text } }));
        response.write(event('message_delta', { type: 'message_delta', delta: { stop_reason: 'end_turn' }, usage: { output_tokens: 20 } }));
        response.write(event('message_stop', { type: 'message_stop' }));
        response.end();
      })();
    });
  });
  server.on('connection', (socket: Socket) => {
    sockets.add(socket);
    socket.on('close', () => sockets.delete(socket));
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  model.base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  model.close = async () => {
    for (const socket of sockets) socket.destroy();
    await new Promise<void>((resolve) => server.close(() => resolve()));
  };
  return model;
}

// ── the harness ──────────────────────────────────────────────────────────────────────────────────────

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  plans: WikiPlans;
  model: FakeModel;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL_);
    const sql = new Client({ connectionString: URL_, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL_ as string);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined, publishForUser: () => undefined } as unknown as RealtimeService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, { notifyWikiReviewModeTripped: async () => undefined } as unknown as PushService);
    const plans = new WikiPlans(prisma as unknown as PrismaService, hub);

    @Module({
      controllers: [WikiController, WikiPlanController, RunnerWikiPlanController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiPlans, useValue: plans },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiPlanDraftJobModule {}

    const app = await NestFactory.create(WikiPlanDraftJobModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, plans, model: await fakeModel(), bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql, model } = await harness;
  delete process.env.ORBIT_WIKI_EXECUTOR;
  delete process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS;
  await sql.query('DELETE FROM "wiki_model_status"').catch(() => undefined);
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
  await model.close().catch(() => undefined);
});

/** The workers and runners a case started: one that fails halfway must not leave one working the next case's rows. */
const live: Array<{ stop: () => Promise<void> }> = [];

afterEach(async () => {
  for (const one of live.splice(0)) await one.stop().catch(() => undefined);
});

function config(h: Harness): WikiSystemModelConfig {
  return readWikiSystemModel({
    ORBIT_WIKI_MODEL_BASE_URL: h.model.base,
    ORBIT_WIKI_MODEL_API_KEY: KEY,
    ORBIT_WIKI_MODEL: MODEL,
    ORBIT_WIKI_MODEL_CONCURRENCY: '4',
  });
}

interface Worker {
  queue: WikiModelRequestQueue;
  executor: WikiJobExecutor;
}

/** A worker as the wiki-worker module builds one, with fast timings: the plan's two kinds in its map. */
function worker(h: Harness): Worker {
  const options = { leaseMs: 1_500, renewMs: 200, partialMs: 40, pollMs: 25 };
  const prisma = h.prisma as unknown as PrismaService;
  const probe = new WikiModelStatusProbe(prisma, config(h));
  const queue = new WikiModelRequestQueue(prisma, config(h), probe, undefined, options);
  const plan = wikiPlanDraftJobRunner({
    prisma, plans: h.plans, repoOps: new WikiRepoOps(prisma), model: MODEL, snapshotWaitMs: 8_000, readWaitMs: 8_000, sliceMs: 1,
  });
  const executor = new WikiJobExecutor(prisma, queue, options, {
    [WIKI_PLAN_SERVER_JOB.kinds.draft]: plan,
    [WIKI_PLAN_SERVER_JOB.kinds.revise]: plan,
  });
  live.push({
    stop: async () => {
      await executor.onModuleDestroy();
      await queue.onModuleDestroy();
    },
  });
  return { queue, executor };
}

async function reset(h: Harness, mode: 'server' | 'canary' | 'runner' = 'server', canary: string[] = []): Promise<void> {
  process.env.ORBIT_WIKI_EXECUTOR = mode;
  process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS = canary.join(',');
  h.model.hits.length = 0;
  h.model.script = {};
  h.model.skeletons = 0;
  h.model.rounds = 0;
  h.model.status = 200;
  await h.sql.query('DELETE FROM "wiki_model_status"');
  await new WikiModelStatusProbe(h.prisma as unknown as PrismaService, config(h)).check();
}

// ── requests ─────────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 1500)}`);
}

// ── fixtures ─────────────────────────────────────────────────────────────────────────────────────────

/** The owner, their machine (capable, online), a workspace with a working directory, a provider, and a space. */
interface Owner {
  id: string;
  bearer: string;
  runnerId: string;
  runnerToken: string;
  workspaceId: string;
  slug: string;
  spaceId: string;
}

async function owner(h: Harness): Promise<Owner> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,'plan job spec','x')`, [id, `wiki-plan-job-${id}@wiki.invalid`]);
  const bearer = `bearer-${id}`;
  h.bearers.set(bearer, id);
  const runnerId = randomUUID();
  const runnerToken = `runner-${runnerId}`;
  await h.sql.query(
    `INSERT INTO "runner"("id","name","owner_id","token_hash","capabilities","capabilities_reported_at","last_heartbeat_at")
     VALUES ($1,'spec',$2,$3,$4,now(),now())`,
    [runnerId, id, createHash('sha256').update(runnerToken).digest('hex'), [WIKI_REPO_OP_CAPABILITY]],
  );
  const workspaceId = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env","runner_id","work_dir") VALUES ($1,'app',$2,'{}',$3,'~/app')`, [workspaceId, id, runnerId]);
  const slug = `local-vllm-${randomUUID().slice(0, 8)}`;
  await h.prisma.modelProvider.create({
    data: {
      slug, label: 'Local vLLM', runtime: 'claude', baseUrl: 'http://127.0.0.1:8000', apiKeyEnc: encryptSecret(`vllm-key-${randomUUID()}`),
      models: [{ value: MODEL, label: 'Qwen', contextWindow: 131072 }], defaultModel: MODEL, enabled: true, ownerId: id,
    },
  });
  for (const title of ['App 项目', '同名项目', '同名项目']) {
    await h.sql.query(`INSERT INTO "project"("id","title","owner_id","updated_at") VALUES ($1,$2,$3,now())`, [randomUUID(), title, id]);
  }
  const made = await call(h, { bearer }, 'POST', '/wiki/spaces', {
    title: 'App',
    repoUrl: `https://github.com/spec/app-${randomUUID().slice(0, 8)}`,
    maintenance: { workspaceId, provider: slug },
  });
  expectStatus(made, 201, 'the owner creates a space with its maintenance set up');
  const spaceId = toUuid(made.body.id as string);
  await h.sql.query('INSERT INTO "wiki_topic"("id","space_id","owner_id","slug","title","category","path_prefixes") VALUES ($1,$2,$3,$4,$5,$6,$7)', [
    randomUUID(), spaceId, id, 'storage-topic', '存储', 'data', ['src/app/'],
  ]);
  return { id, bearer, runnerId, runnerToken, workspaceId, slug, spaceId };
}

/** The space's plan jobs, oldest first. */
async function planJobs(h: Harness, spaceId: string): Promise<Array<Record<string, any>>> {
  return (await h.sql.query(
    `SELECT "id","kind","trigger","state","outcome","version","task_id","job_id","session_id","attempt","started_at","errors","error","report","draft","materials","instructions"
       FROM "wiki_plan_job" WHERE "space_id" = $1 ORDER BY "created_at", "id"`,
    [spaceId],
  )).rows;
}

/** Forget the job the space's creation asked for, so a case makes its own the way the owner asks. */
async function clearJobs(h: Harness, spaceId: string): Promise<void> {
  await h.sql.query('DELETE FROM "wiki_job" WHERE "space_id" = $1', [spaceId]);
  await h.sql.query('DELETE FROM "wiki_plan_job" WHERE "space_id" = $1', [spaceId]);
}

interface BaseDoc {
  category: string;
  slug: string;
  title: string;
  protected?: boolean;
  sections: Array<{ key: string; title: string; kind: string; sources?: Record<string, unknown> }>;
}

/**
 * A version of the owner's, confirmed, as the plan's own writes would have left it: what a draft revises and
 * the target it is held to (wiki_plan_job_test.go `planBase`, and a target of its own).
 */
async function baseVersion(h: Harness, o: Owner, target: { min: number; max: number }, docs: BaseDoc[] = [], categories = [
  { key: 'product', title: '产品', question: '这个服务是什么', forAgents: false, extra: {} },
  { key: 'dev', title: '开发约定', question: '给 agent 的约定', forAgents: true, extra: {} },
]): Promise<void> {
  const planId = randomUUID();
  await h.sql.query(
    `INSERT INTO "wiki_plan"("id","space_id","owner_id","version","status","origin","categories","new_fields","docs_min","docs_max","gate",
                             "author_user_id","confirmed_by_user_id","confirmed_at")
     VALUES ($1,$2,$3,1,'confirmed','owner',$4,'[]',$5,$6,'{}',$3,$3,now())`,
    [planId, o.spaceId, o.id, JSON.stringify(categories), target.min, target.max],
  );
  for (const [position, doc] of docs.entries()) {
    const docId = randomUUID();
    await h.sql.query(
      `INSERT INTO "wiki_plan_doc"("id","plan_id","owner_id","position","category","slug","title","question","audience","scope_in","scope_out",
                                   "length_min","length_max","protected","extra")
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'[]',500,900,$11,'{}')`,
      [docId, planId, o.id, position, doc.category, doc.slug, doc.title, `${doc.title}是什么？`, ['开发者：读完能改它'], [doc.title], doc.protected ?? false],
    );
    for (const [sp, s] of doc.sections.entries()) {
      await h.sql.query(
        `INSERT INTO "wiki_plan_section"("id","doc_id","owner_id","position","key","title","kind","covers","length","sources","extra")
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,300,$9,'{}')`,
        [randomUUID(), docId, o.id, sp, s.key, s.title, s.kind, `${s.title}的内容。`,
          JSON.stringify(s.sources ?? { docs: [], code: [], contracts: [], sessions: null })],
      );
    }
  }
}

/** wiki_plan_job_test.go's `planBase`: three documents, the first protected. */
const PLAN_BASE: BaseDoc[] = [
  { category: 'product', slug: 'service-overview', title: '服务概览', protected: true, sections: [
    { key: 's1', title: '总览', kind: 'overview' },
    { key: 's2', title: '组件', kind: 'concepts', sources: { docs: [{ path: 'docs/architecture.md', section: 'Execution model' }], code: [{ path: 'src/app/main.go', symbols: ['Server'] }], contracts: [], sessions: null } },
    { key: 's3', title: '已知的坑', kind: 'pitfalls' },
  ] },
  { category: 'product', slug: 'storage', title: '存储', sections: [
    { key: 's1', title: '保存流程', kind: 'flow' }, { key: 's2', title: '保存约定', kind: 'conventions' }, { key: 's3', title: '决策与理由', kind: 'decisions' },
  ] },
  { category: 'dev', slug: 'testing', title: '测试约定', sections: [{ key: 's1', title: '怎么跑测试', kind: 'conventions' }] },
];

/** The owner asks on the plan page: a draft, or with instructions a revision. Answers the plan job. */
async function redraft(h: Harness, o: Owner, instructions?: string): Promise<string> {
  const answer = await call(h, { bearer: o.bearer }, 'POST', `/wiki/spaces/${o.spaceId}/plan/redraft`, instructions ? { instructions } : {});
  expectStatus(answer, 200, 'the owner asks for a draft');
  return toUuid(answer.body.job.id as string);
}

// ── the runner ───────────────────────────────────────────────────────────────────────────────────────

/** One read answered the way wiki_repo_ops.go answers it: each item within its own limit, the whole within one section's material. */
function readAnswer(input: { sha: string; items: Array<{ path: string; maxChars?: number }> }): Record<string, unknown> {
  let total = 0;
  const items = input.items.map((item) => {
    const text = FIXTURE.files[item.path];
    if (text === undefined) return { path: item.path, found: false, chars: 0 };
    let max = item.maxChars && item.maxChars > 0 ? item.maxChars : WIKI_REPO_OPS.docSectionChars;
    max = Math.min(max, WIKI_REPO_OPS.sectionChars, WIKI_REPO_OPS.sectionChars - total);
    const runes = [...text];
    const cut = runes.length <= max ? text : `${runes.slice(0, max - 8).join('')}\n…（后略）\n`;
    total += [...cut].length;
    return { path: item.path, found: true, text: cut, truncated: cut !== text, chars: [...cut].length };
  });
  return { read: { sha: input.sha, items, chars: total } };
}

interface PlayedRunner {
  /** Every operation the runner was handed, in order. */
  ops: Array<{ kind: string; input: Record<string, unknown> }>;
  stop: () => Promise<void>;
}

/** The space's runner, as its heartbeat would be: it claims what is queued for it and answers from the fixture. */
function playRunner(h: Harness, o: Owner, over: { sha?: string; index?: string } = {}): PlayedRunner {
  const ops = new WikiRepoOps(h.prisma as unknown as PrismaService);
  const seen: PlayedRunner['ops'] = [];
  let stopped = false;
  const loop = (async () => {
    while (!stopped) {
      const claimed = await ops.dispatch({ runnerId: o.runnerId, leaseOwner: randomUUID(), draining: false, capabilities: [WIKI_REPO_OP_CAPABILITY] });
      for (const op of claimed) {
        seen.push({ kind: op.kind, input: op.input });
        const result = op.kind === 'snapshot'
          ? { sha: over.sha ?? SHA, index: over.index ?? JSON.stringify(FIXTURE.index) }
          : readAnswer(op.input as { sha: string; items: Array<{ path: string; maxChars?: number }> });
        await ops.applyWikiRepoOpResult({
          id: op.id, runnerId: o.runnerId,
          body: { claimGeneration: op.claimGeneration, leaseOwner: op.leaseOwner, state: 'succeeded', result },
        });
      }
      await delay(15);
    }
  })();
  const played = { ops: seen, stop: async () => {
    stopped = true;
    await loop;
  } };
  live.push(played);
  return played;
}

/** Passes of the worker until the plan job ends, and its row then. */
async function drive(h: Harness, w: Worker, planJobId: string, seconds = 60): Promise<Record<string, any>> {
  const deadline = Date.now() + seconds * 1000;
  for (;;) {
    await w.executor.runOnce();
    await w.queue.runOnce();
    const { rows: [row] } = await h.sql.query('SELECT "state", "job_id" FROM "wiki_plan_job" WHERE "id" = $1', [planJobId]);
    const { rows: [job] } = row?.job_id ? await h.sql.query('SELECT "state" FROM "wiki_job" WHERE "id" = $1', [row.job_id]) : { rows: [undefined] };
    if (row?.state === 'ended' && job && !['queued', 'running', 'waiting'].includes(job.state)) break;
    assert.ok(Date.now() < deadline, `the plan job ${planJobId} to end within ${seconds}s (it is ${row?.state}, its job ${job?.state})`);
    await delay(20);
  }
  await w.executor.whenIdle();
  const { rows: [row] } = await h.sql.query('SELECT * FROM "wiki_plan_job" WHERE "id" = $1', [planJobId]);
  return row;
}

/** The wiki_job a plan job was made with. */
async function wikiJobOf(h: Harness, planJobId: string): Promise<Record<string, any>> {
  const { rows: [row] } = await h.sql.query('SELECT j.* FROM "wiki_job" j JOIN "wiki_plan_job" p ON p."job_id" = j."id" WHERE p."id" = $1', [planJobId]);
  return row;
}

async function requests(h: Harness, jobId: string): Promise<Array<Record<string, any>>> {
  return (await h.sql.query('SELECT * FROM "wiki_model_request" WHERE "job_id" = $1 ORDER BY "enqueued_at", "id"', [jobId])).rows;
}

async function versions(h: Harness, spaceId: string): Promise<Array<Record<string, any>>> {
  return (await h.sql.query('SELECT * FROM "wiki_plan" WHERE "space_id" = $1 ORDER BY "version"', [spaceId])).rows;
}

async function storedDraft(h: Harness, o: Owner, version: number): Promise<Record<string, any>> {
  const answer = await call(h, { bearer: o.bearer }, 'GET', `/wiki/spaces/${o.spaceId}/plan/versions/${version}`);
  expectStatus(answer, 200, `the owner reads version ${version}`);
  return answer.body;
}

const asked = (h: Harness, marker: string): string[] => h.model.hits.map((hit) => hit.prompt).filter((prompt) => prompt.includes(marker));

// ── 1. four steps ────────────────────────────────────────────────────────────────────────────────────

test('a draft is written in four steps through the queue, gated on the snapshot, and stored by the job; no task, no session', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  await reset(h);
  const o = await owner(h);
  // The space's creation asked for a draft, made on the server at the owner's priority — and no task.
  const created = await planJobs(h, o.spaceId);
  assert.equal(created.length, 1);
  assert.equal(created[0].trigger, 'space_created');
  assert.equal(created[0].state, 'made');
  assert.equal(created[0].task_id, null, 'no task is made for a job the server runs');
  const made = await wikiJobOf(h, created[0].id);
  assert.equal(made.kind, 'plan_draft');
  assert.equal(made.priority, WIKI_PLAN_SERVER_JOB.priority);
  assert.deepEqual(made.input, { planJobId: created[0].id });
  // The case's own draft: the version it revises holds it to three documents.
  await clearJobs(h, o.spaceId);
  await baseVersion(h, o, { min: 3, max: 3 });
  const planJobId = await redraft(h, o);
  const runner = playRunner(h, o);
  const w = worker(h);
  // While the run is on its outlines, the plan page shows it drafting, its round, and when it started.
  let page = null as Answer | null;
  h.model.script.onPrompt = async (prompt) => {
    if (page === null && prompt.includes('第三步 —— 给《')) page = await call(h, { bearer: o.bearer }, 'GET', `/wiki/spaces/${o.spaceId}/plan`);
  };
  const end = await drive(h, w, planJobId);

  assert.equal(end.outcome, 'succeeded', `the plan job: ${end.error}`);
  assert.equal(end.version, 2);
  assert.equal(end.attempt, 1);
  assert.equal(end.session_id, null, 'a server-run job has no session');
  assert.ok(end.started_at, 'the run said it started');
  const seen = page as Answer | null;
  assert.ok(seen, 'the plan page was read while the run wrote its outlines');
  assert.equal(seen.body.job.state, 'running');
  assert.equal(seen.body.job.attempt, 1);
  assert.ok(seen.body.job.startedAt, 'the plan page shows when the draft started');
  assert.equal(seen.body.job.taskId, null);
  // The calls, in order: the catalogue first, every category's details before any outline, the rules beside them.
  const job = await wikiJobOf(h, planJobId);
  assert.equal(job.state, 'succeeded');
  const rows = await requests(h, job.id);
  const steps = rows.map((row) => row.step);
  assert.equal(steps[0], 'plan_skeleton');
  assert.equal(steps.length, 7, `the calls: ${steps.join(', ')}`);
  assert.deepEqual([...steps].sort(), ['plan_details', 'plan_details', 'plan_outline', 'plan_outline', 'plan_outline', 'plan_rules', 'plan_skeleton']);
  const lastDetails = steps.lastIndexOf('plan_details');
  assert.ok(lastDetails < steps.indexOf('plan_outline'), `an outline was asked before every category's details: ${steps.join(', ')}`);
  for (const row of rows) {
    assert.equal(row.state, 'succeeded');
    assert.equal(row.priority, WIKI_PLAN_SERVER_JOB.priority, 'the owner\'s draft goes before background maintenance');
    assert.deepEqual(Object.keys(row.request).sort(), ['maxTokens', 'prompt', 'system']);
    assert.equal(row.request.maxTokens, 32_000);
    assert.equal(row.request.system, WIKI_PLAN_SYSTEM_PROMPT);
    assert.match(row.unit, /^a1\/[A-Za-z0-9._-]+@[0-9a-f]{12}$/u);
  }
  // Each call reached the System model as one user message, with the key the worker holds and nothing else.
  assert.equal(h.model.hits.length, 7);
  for (const hit of h.model.hits) {
    assert.equal(hit.authorization, `Bearer ${KEY}`);
    assert.equal(hit.body.max_tokens, 32_000);
    assert.equal(hit.system, WIKI_PLAN_SYSTEM_PROMPT);
    assert.equal('tools' in hit.body, false);
    assert.equal('thinking' in hit.body, false);
  }
  // Each outline was asked with its own document's materials: its docs' whole heading tree and its code's symbols.
  const storage = asked(h, '第三步 —— 给《存储》');
  assert.equal(storage.length, 1);
  for (const want of ['### docs/wiki-design.md', '- 4. 写路径', 'src/app/store.go: Store, Store.Save']) assert.ok(storage[0].includes(want), `the outline of 存储 lacks ${want}`);
  assert.ok(!storage[0].includes('这不是一个章节') && !storage[0].includes('Mock heading'), 'a heading inside a code fence, or a mockup\'s, reached the materials');
  // The repository was read once a snapshot at the job's start, and what the snapshot does not carry read at its sha.
  assert.equal(runner.ops[0].kind, 'snapshot');
  assert.ok(runner.ops.some((op) => op.kind === 'read' && (op.input.items as Array<{ path: string }>).some((item) => item.path === 'docs/README.md')),
    'the overview\'s documents are read at the sha');
  // What was stored: the whole plan, the job its author, the System model its model, the snapshot its check.
  const stored = await versions(h, o.spaceId);
  assert.equal(stored.length, 2);
  assert.equal(stored[1].author_job_id, job.id);
  assert.equal(stored[1].author_session_id, null);
  assert.equal(stored[1].origin, 'maintenance');
  assert.equal(stored[1].model, MODEL);
  assert.equal(stored[1].repo_sha, SHA);
  assert.ok(stored[1].repo_check.checked >= 8 && stored[1].repo_check.missing.length === 0, JSON.stringify(stored[1].repo_check));
  const draft = await storedDraft(h, o, 2);
  assert.equal(draft.authorJobId, uuidPublic(job.id));
  assert.deepEqual(draft.categories.map((c: { key: string }) => c.key), ['product', 'dev']);
  assert.equal(draft.categories[1].forAgents, true);
  assert.deepEqual(draft.docs.map((d: { slug: string }) => d.slug), ['service-overview', 'storage', 'testing']);
  const overview = draft.docs[0];
  assert.deepEqual(overview.length, { min: 800, max: 1200 });
  assert.deepEqual(overview.scopeOut, [{ text: '存储细节', docs: ['storage'] }]);
  const components = overview.sections[1];
  assert.equal(components.kind, 'concepts');
  assert.ok(components.covers.includes('见 1.2'));
  assert.deepEqual(components.sources.code, [{ path: 'src/app/main.go', symbols: ['Server', 'Serve()'] }]);
  const sessions = overview.sections[2].sources.sessions;
  assert.equal(sessions.since, '2026-09-01');
  assert.equal(sessions.until, null);
  assert.deepEqual(sessions.entryKinds, ['pitfall']);
  assert.deepEqual(sessions.topics, ['storage-topic']);
  assert.equal(sessions.projects.length, 1, 'the project named by its title is the one of that title');
  assert.equal(sessions.evidence, 'owner 说端口不能写死的原话');
  // The report, on the plan job and on its wiki_job.
  assert.equal(end.report.docs, 3);
  assert.equal(end.report.sections, 6);
  assert.equal(end.report.tokens.calls, 7);
  assert.equal(end.report.tokens.input, 700);
  assert.equal(end.report.model, MODEL);
  assert.ok(String(end.report.rulesDraft).includes('## 引用规则'));
  assert.deepEqual(end.report.attempts, [{ attempt: 1, local: 0, server: 0, checks: {} }]);
  assert.equal(job.report.planJobId, planJobId);
  assert.equal(job.report.version, 2);
  // The materials the job drafted from are kept on it, for a replay.
  assert.equal(end.materials.sha, SHA);
  assert.equal(end.materials.materials.title, 'App');
  assert.ok('docs/README.md' in end.materials.texts);
  // No task and no session: the server ran it.
  const { rows: [counts] } = await h.sql.query(
    `SELECT (SELECT count(*)::int FROM "task" WHERE "owner_id" = $1) AS "tasks", (SELECT count(*)::int FROM "session" WHERE "owner_id" = $1) AS "sessions"`, [o.id]);
  assert.deepEqual(counts, { tasks: 0, sessions: 0 });
  // The plan's check reads the job as a task's acceptance command would.
  const check = await call(h, { runner: o.runnerToken }, 'GET', `/runner/wiki/spaces/${o.spaceId}/plan/check?jobId=${planJobId}`);
  expectStatus(check, 200, 'the check of a server-run job');
  assert.equal(check.body.ok, true);
});

/** An id in the spelling the doors answer it (PublicIdInterceptor). */
function uuidPublic(id: string): string {
  return uuidToBase62(id);
}

// ── 2–3. the count ───────────────────────────────────────────────────────────────────────────────────

test('a catalogue outside the target is written again with the gate\'s count before any document of it', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  await reset(h);
  const o = await owner(h);
  await clearJobs(h, o.spaceId);
  await baseVersion(h, o, { min: 3, max: 3 });
  h.model.script.skeleton = (n) => (n === 1 ? SKELETON_FOUR : SKELETON);
  const planJobId = await redraft(h, o);
  playRunner(h, o);
  const end = await drive(h, worker(h), planJobId);
  assert.equal(end.outcome, 'succeeded', end.error);
  const order = h.model.hits.map((hit) => (hit.prompt.includes('第一步') || hit.prompt.includes('# 任务：改正 wiki「') ? 'catalogue' : 'body'));
  assert.deepEqual(order.slice(0, 2), ['catalogue', 'catalogue']);
  assert.equal(order.filter((x) => x === 'catalogue').length, 2);
  assert.equal(order.length, 8, 'the catalogue twice and the six calls a draft of three documents asks');
  const again = asked(h, '# 任务：改正 wiki「');
  assert.equal(again.length, 1);
  assert.ok(again[0].includes("[docCount] plan.docs：the plan has 4 documents; it must have 3 to 3: merge documents that answer the same reader's question — 1 too many"));
  assert.ok(again[0].includes('release-channels'));
  for (const hit of h.model.hits) {
    if (!hit.prompt.includes('第一步') && !hit.prompt.includes('# 任务：改正 wiki「')) assert.ok(!hit.prompt.includes('release-channels'), 'a document of the catalogue sent back was written');
  }
  assert.deepEqual(end.report.attempts.map((a: { attempt: number }) => a.attempt), [1]);
  assert.equal(end.report.tokens.calls, 8);
  const rows = await requests(h, (await wikiJobOf(h, planJobId)).id);
  assert.deepEqual(rows.filter((row) => row.step === 'plan_skeleton').map((row) => row.unit.split('@')[0]), ['a1/catalogue', 'a1/catalogue-count-1']);
});

test('a count still outside the target after two tries is the gate\'s, and three rounds end the job failed with its errors and its draft', { skip, timeout: 150_000 }, async () => {
  const h = await boot();
  await reset(h);
  const o = await owner(h);
  await clearJobs(h, o.spaceId);
  await baseVersion(h, o, { min: 4, max: 5 });
  const planJobId = await redraft(h, o);
  playRunner(h, o);
  const end = await drive(h, worker(h), planJobId, 90);
  assert.equal(end.outcome, 'failed');
  assert.ok(String(end.error).includes("did not pass the plan's gate in 3 rounds"), end.error);
  // Each round: the catalogue (round 1's skeleton, a later round's sent back with the gate's errors), then twice
  // more with the count before any document — wiki_plan_job_test.go's 9 and 8.
  assert.equal(asked(h, '第一步').length, 9, 'the catalogue asked three times in each of three rounds');
  const again = asked(h, '# 任务：改正 wiki「');
  assert.equal(again.length, 8, 'and sent back eight times');
  for (const prompt of again) {
    assert.ok(prompt.includes('[docCount] plan.docs：the plan has 3 documents; it must have 4 to 5: split the broadest documents, or add the ones the categories are missing — 1 too few'));
  }
  assert.equal(asked(h, '第二步').length + asked(h, '第三步 —— 给《').length, 5, 'the documents were written once: the catalogues sent back kept every one of them');
  assert.equal((await versions(h, o.spaceId)).length, 1, 'nothing this job\'s gate refused reached the server\'s');
  assert.equal(end.attempt, 3);
  assert.deepEqual(end.errors.map((e: { check: string }) => e.check), ['docCount']);
  assert.equal(end.draft.docs.length, 3, 'the last draft is kept on the plan job for its owner to read');
  for (const round of end.report.attempts) assert.equal(round.checks.docCount, 1);
  const job = await wikiJobOf(h, planJobId);
  assert.equal(job.state, 'failed');
  assert.equal(job.failure_kind, 'content');
  assert.equal(job.report.outcome, 'failed');
  const page = await call(h, { bearer: o.bearer }, 'GET', `/wiki/spaces/${o.spaceId}/plan`);
  assert.equal(page.body.job.state, 'failed');
  assert.equal(page.body.job.errors[0].check, 'docCount');
});

// ── 4. references, and a round with the gate's errors ────────────────────────────────────────────────

test('every reference is checked on the snapshot — a symbol the index lacks by a read of its file — and only the document with errors is written again', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  await reset(h);
  const o = await owner(h);
  await clearJobs(h, o.spaceId);
  await baseVersion(h, o, { min: 3, max: 3 });
  h.model.script.outline = (title) => (title === '存储' ? OUTLINE_STORAGE_WRONG : undefined);
  h.model.script.redo = () => `标题：存储\n${OUTLINE_STORAGE}`;
  const planJobId = await redraft(h, o);
  const runner = playRunner(h, o);
  const end = await drive(h, worker(h), planJobId);
  assert.equal(end.outcome, 'succeeded', end.error);
  assert.deepEqual(end.report.attempts.map((a: { attempt: number }) => a.attempt), [1, 2]);
  const first = end.report.attempts[0];
  assert.equal(first.server, 0);
  assert.deepEqual(first.checks, { references: 5, schema: 1 });
  // The file a symbol was looked for in, read at the sha: localHelper is declared in client.ts, not store.go.
  const reads = runner.ops.filter((op) => op.kind === 'read').flatMap((op) => (op.input.items as Array<{ path: string }>).map((item) => item.path));
  for (const file of ['src/app/store.go', 'src/web/client.ts']) assert.ok(reads.includes(file), `${file} was not read for a symbol: ${reads.join(', ')}`);
  for (const op of runner.ops.filter((one) => one.kind === 'read')) assert.equal(op.input.sha, SHA, 'every read is at the snapshot\'s sha');
  const redos = asked(h, '# 任务：改正 plan 里《');
  assert.equal(redos.length, 1);
  assert.ok(redos[0].includes('改正 plan 里《存储》'));
  for (const want of [
    '"Store.Load" is no symbol of src/app/store.go', 'it declares: Store; Store.Save; storeVersion',
    '"localHelper" is no symbol of src/app/store.go',
    'has no section "5. 不存在的章节"', 'its sections are: 4. 写路径; 4.4 锚点',
    '"src/app/missing.go" is no file or directory',
    'points at "9.9", which is no document of this plan',
    '"备注：这一行不在格式里" is not a line of a section',
    '1.2《存储》 第 1 节「保存流程」',
  ]) assert.ok(redos[0].includes(want), `the redo does not say ${want}`);
  assert.ok(!redos[0].includes('"localHelper" is no symbol of src/web/client.ts'), 'a symbol the file spells is found by its text');
  const draft = await storedDraft(h, o, 2);
  assert.deepEqual(draft.docs[1].sections[0].sources.code, [{ path: 'src/app/store.go', symbols: ['Store.Save'] }]);
  assert.ok(draft.docs[1].audience.length > 0 && draft.docs[1].length.min === 600, 'the redone document kept its header');
  assert.equal(draft.repoCheck.missing.length, 0);
  // Round 2's calls are their own requests: the round is in the unit.
  const rows = await requests(h, (await wikiJobOf(h, planJobId)).id);
  assert.deepEqual(rows.filter((row) => row.step === 'plan_redo_doc').map((row) => row.unit.split('@')[0]), ['a2/storage']);
});

// ── 5. the server's gate ─────────────────────────────────────────────────────────────────────────────

test('what the server\'s gate finds goes back to the model, and three rounds of it end the job with the last errors', { skip, timeout: 150_000 }, async () => {
  const h = await boot();
  await reset(h);
  const o = await owner(h);
  await clearJobs(h, o.spaceId);
  await baseVersion(h, o, { min: 3, max: 3 });
  // The project the outline names is renamed once the job has read its materials: this job's gate still knows
  // its title, and the server's, which reads the account's projects as they are, does not.
  h.model.script.onPrompt = async (prompt) => {
    if (prompt.includes('第一步')) await h.sql.query(`UPDATE "project" SET "title" = 'App 项目（改名）' WHERE "owner_id" = $1 AND "title" = 'App 项目'`, [o.id]);
  };
  h.model.script.redo = () => OUTLINE_OVERVIEW;
  const planJobId = await redraft(h, o);
  playRunner(h, o);
  const end = await drive(h, worker(h), planJobId, 90);
  assert.equal(end.outcome, 'failed');
  assert.equal(end.attempt, 3);
  assert.equal((await versions(h, o.spaceId)).length, 1, 'nothing was stored');
  const redos = asked(h, '# 任务：改正 plan 里《服务概览》');
  assert.equal(redos.length, 2);
  for (const prompt of redos) {
    assert.ok(prompt.includes('[references] 1.1《服务概览》 第 3 节「已知的坑」 · sources.sessions.projects[0]：no project of this account is titled "App 项目"'),
      'the redo hands the server\'s error back');
  }
  assert.equal(end.errors.length, 1);
  assert.equal(end.errors[0].path, 'plan.docs[0].sections[2].sources.sessions.projects[0]');
  assert.equal(end.draft.docs.length, 3);
  assert.deepEqual(end.report.attempts.map((a: { server: number; local: number }) => [a.local, a.server]), [[0, 1], [0, 1], [0, 1]]);
});

// ── 6. a revision ────────────────────────────────────────────────────────────────────────────────────

test('a revision keeps the protected document as it is, moves only a convention, holds the count and names projects by title', { skip, timeout: 150_000 }, async () => {
  const h = await boot();
  await reset(h);
  const o = await owner(h);
  await clearJobs(h, o.spaceId);
  const { rows: [app] } = await h.sql.query(`SELECT "id" FROM "project" WHERE "owner_id" = $1 AND "title" = 'App 项目'`, [o.id]);
  const base = structuredClone(PLAN_BASE);
  base[1].sections[1].sources = { docs: [], code: [], contracts: [], sessions: { projects: [app.id], since: null, until: null, keywords: ['保存'], anchorPaths: [],
    entryKinds: ['convention'], topics: [], evidence: 'owner 说保存前要校验的原话' } };
  await baseVersion(h, o, { min: 3, max: 3 }, base);
  h.model.script.revise = (round) => (round === 1
    ? '## 1. 产品 `product` —— 这个服务是什么\n- 1.1 服务概览 `service-overview`｜是什么｜来源：1.1｜含：定位\n'
      + '- 1.2 存储 `storage`｜怎么存｜来源：1.2｜含：保存\n- 1.3 存储决策 `storage-decisions`｜为什么这么存｜来源：无｜含：决策\n'
      + '## 2. 开发约定 `dev` —— 给 agent 的约定 [agents]\n- 2.1 测试约定 `testing`｜怎么跑测试｜来源：2.1｜含：go test\n'
      + '### 移到给 agent 的大类的节\n- 1.1 §3 → 2.1\n- 1.2 §3 → 2.1\n'
    : '## 1. 产品 `product` —— 这个服务是什么\n- 1.1 服务概览 `service-overview`｜是什么｜来源：1.1｜含：定位\n'
      + '- 1.2 存储 `storage`｜怎么存｜来源：1.2｜含：保存\n'
      + '## 2. 开发约定 `dev` —— 给 agent 的约定 [agents]\n- 2.1 测试约定 `testing`｜怎么跑测试与保存前的校验｜来源：2.1｜含：go test；保存前校验\n'
      + '### 移到给 agent 的大类的节\n- 1.2 §2 → 2.1\n');
  h.model.script.rewrite = (title) => `标题：${title}\n问题：怎么跑测试？\n读者：写代码的 agent：读完知道怎么跑测试\n含：go test；保存前校验\n篇幅：400–600 字\n`
    + '### 1. 怎么跑测试 | conventions | 300\n讲什么：用 go test 跑。\n- 代码：src/web/client.ts: render()\n'
    + '### 2. 保存约定 | conventions | 200\n讲什么：保存前先校验，见 1.2。\n- 会话：项目「App 项目」；关键词 保存；kind convention；要找：owner 说保存前要校验的原话\n';
  const planJobId = await redraft(h, o, '把存储的约定移到开发约定里，篇数不变。');
  const job = await wikiJobOf(h, planJobId);
  assert.equal(job.kind, 'plan_revise');
  playRunner(h, o);
  const end = await drive(h, worker(h), planJobId, 90);
  assert.equal(end.outcome, 'succeeded', end.error);
  const first = end.report.attempts[0];
  assert.equal(first.server, 0);
  assert.equal(first.checks.docCount, 1);
  assert.equal(first.checks.protected, 2);
  const catalogues = asked(h, '按 owner 的要求修订 plan 的目录');
  assert.equal(catalogues.length, 2);
  assert.ok(catalogues[0].includes('把存储的约定移到开发约定里') && catalogues[0].includes('服务概览 `service-overview`［受保护］') && catalogues[0].includes('§2 保存约定（conventions）'));
  for (const want of ['the plan has 4 documents; it must have 3 to 3', 'moves §3 out of 1.1 «服务概览», which is protected',
    'moves §3 «决策与理由» of 1.2, a decisions section: only a conventions section moves']) assert.ok(catalogues[1].includes(want), `the second catalogue does not say ${want}`);
  const rewrites = asked(h, '# 任务：写新草稿里《测试约定》');
  assert.ok(rewrites.length >= 1);
  const last = rewrites[rewrites.length - 1];
  assert.ok(last.includes('【现在的 1.2 第 2 节（移入本篇）】'), 'the rewrite was handed the moved section');
  assert.ok(last.includes('- 会话：项目「App 项目」；关键词 保存；kind convention') && !last.includes(app.id), 'the moved section\'s project is named by its title');
  const stored = await versions(h, o.spaceId);
  assert.equal(stored.length, 2);
  assert.equal(stored[1].base_version, 1);
  const draft = await storedDraft(h, o, 2);
  assert.equal(draft.docs.length, 3);
  assert.equal(draft.docs[0].protected, true, 'the protected document is carried as it was');
  assert.deepEqual(draft.docs[0].sections.map((s: { title: string; key: string }) => [s.key, s.title]), [['s1', '总览'], ['s2', '组件'], ['s3', '已知的坑']]);
  assert.deepEqual(draft.docs[1].sections.map((s: { title: string }) => s.title), ['保存流程', '决策与理由']);
  assert.equal(draft.docs[1].sections[0].key, 's1');
  assert.deepEqual(draft.docs[2].sections.map((s: { title: string }) => s.title), ['怎么跑测试', '保存约定']);
  assert.ok(draft.docs[2].sections[1].covers.includes('见 1.2'));
  assert.equal(draft.docs[2].sections[1].sources.sessions.projects[0].id, uuidPublic(app.id), 'the title the model wrote is the project\'s id once stored');
});

// ── 7. a replay ──────────────────────────────────────────────────────────────────────────────────────

test('a job replayed — taken over, or after its draft was stored — asks nothing twice and stores one version; a moved snapshot starts it over', { skip, timeout: 180_000 }, async () => {
  const h = await boot();
  await reset(h);
  const o = await owner(h);
  await clearJobs(h, o.spaceId);
  await baseVersion(h, o, { min: 3, max: 3 });
  // The worker dies once the outlines are under way: its lease runs out, and the next one takes the job over.
  let first: Worker | null = worker(h);
  let killed = false;
  h.model.script.onPrompt = async (prompt) => {
    if (!killed && prompt.includes('第三步 —— 给《')) {
      killed = true;
      const dying = first!;
      first = null;
      void dying.executor.onModuleDestroy().then(() => dying.queue.onModuleDestroy());
    }
  };
  const planJobId = await redraft(h, o);
  playRunner(h, o);
  const deadline = Date.now() + 30_000;
  while (!killed) {
    assert.ok(Date.now() < deadline, 'the first worker reached the outlines');
    if (first) {
      await first.executor.runOnce();
      await first.queue.runOnce();
    }
    await delay(20);
  }
  const second = worker(h);
  const end = await drive(h, second, planJobId, 90);
  assert.equal(end.outcome, 'succeeded', end.error);
  const job = await wikiJobOf(h, planJobId);
  const rows = await requests(h, job.id);
  const units = rows.map((row) => `${row.step}/${row.unit}`);
  assert.equal(new Set(units).size, units.length, 'no unit was asked twice');
  assert.equal(rows.length, 7);
  assert.ok(rows.every((row) => row.state === 'succeeded'));
  // Once a unit — and again only a call the dead worker had in flight, which the takeover re-issues.
  assert.ok(h.model.hits.length >= rows.length && h.model.hits.length <= rows.length + WIKI_MODEL_QUEUE.maxInFlightPerJob,
    `the model was asked ${h.model.hits.length} times for ${rows.length} units`);
  const hitsAfter = h.model.hits.length;
  assert.equal((await versions(h, o.spaceId)).length, 2);

  // Its draft was stored and its end was not said — the worker died between the two: replayed, it is answered
  // with the version its draft became, and asks the model nothing.
  await h.sql.query(`UPDATE "wiki_plan_job" SET "state" = 'made', "outcome" = NULL, "version" = NULL, "ended_at" = NULL, "report" = NULL WHERE "id" = $1`, [planJobId]);
  await h.sql.query(`UPDATE "wiki_job" SET "state" = 'queued', "ended_at" = NULL, "report" = NULL WHERE "id" = $1`, [job.id]);
  const replayed = await drive(h, second, planJobId, 60);
  assert.equal(replayed.outcome, 'succeeded');
  assert.equal(replayed.version, 2, 'the version the first submission stored');
  assert.equal((await versions(h, o.spaceId)).length, 2, 'one version');
  assert.equal(h.model.hits.length, hitsAfter, 'nothing was asked again');

  // A frame a run left at a sha the space's snapshot is no longer at (another job of the space took a newer one):
  // the replay starts over at the snapshot as it is, its materials read again.
  const next = await redraft(h, o);
  const moved = { sha: 'e'.repeat(40), date: '2026-10-01', materials: { title: 'App' }, texts: {} };
  await h.sql.query('UPDATE "wiki_plan_job" SET "materials" = $2 WHERE "id" = $1', [next, JSON.stringify(moved)]);
  const over = await drive(h, second, next, 60);
  assert.equal(over.outcome, 'succeeded', over.error);
  assert.equal(over.materials.sha, SHA, 'the frame is the snapshot\'s as it is');
  assert.equal(over.materials.materials.projects.length, 3, 'and the materials were read again');
  assert.equal(over.version, 3);
});

// ── 8. only its own job ──────────────────────────────────────────────────────────────────────────────

test('a job runs only as its own: one whose plan job ended asks nothing, and one its plan job was not made with asks nothing either', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  await reset(h);
  const o = await owner(h);
  const [created] = await planJobs(h, o.spaceId);
  const job = await wikiJobOf(h, created.id);
  await h.sql.query(`UPDATE "wiki_plan_job" SET "state" = 'ended', "outcome" = 'failed', "ended_at" = now(), "error" = 'ended by its owner' WHERE "id" = $1`, [created.id]);
  const w = worker(h);
  const ended = async (id: string): Promise<Record<string, any>> => {
    const deadline = Date.now() + 20_000;
    for (;;) {
      await w.executor.runOnce();
      const { rows: [row] } = await h.sql.query('SELECT "state", "error" FROM "wiki_job" WHERE "id" = $1', [id]);
      if (row.state === 'failed' || row.state === 'succeeded') return row;
      assert.ok(Date.now() < deadline, `the job ${id} ends`);
      await delay(20);
    }
  };
  const first = await ended(job.id);
  assert.equal(first.state, 'failed');
  assert.ok(String(first.error).includes('ended by its owner'), first.error);
  // A job whose input names a plan job another job was made with — say, one written by hand — is not its own.
  const stray = randomUUID();
  await h.sql.query(`INSERT INTO "wiki_job"("id","owner_id","space_id","kind","input","priority","state") VALUES ($1,$2,$3,'plan_draft',$4,1,'queued')`, [
    stray, o.id, o.spaceId, JSON.stringify({ planJobId: created.id }),
  ]);
  const second = await ended(stray);
  assert.equal(second.state, 'failed');
  assert.ok(String(second.error).includes('not this job\'s'), second.error);
  assert.equal(h.model.hits.length, 0, 'neither asked the model anything');
  const { rows: [{ n }] } = await h.sql.query('SELECT count(*)::int AS "n" FROM "wiki_repo_op" WHERE "space_id" = $1', [o.spaceId]);
  assert.equal(n, 0, 'nor the repository');
});

// ── 9. where the switch puts a plan job ──────────────────────────────────────────────────────────────

test('the switch decides: a wiki_job under server and for a listed canary account, a task under runner and for one not listed', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  // canary, listed: a wiki_job.
  await reset(h, 'canary', []);
  const listed = await owner(h);
  await reset(h, 'canary', [listed.id]);
  await clearJobs(h, listed.spaceId);
  const listedJob = await redraft(h, listed);
  const [one] = await planJobs(h, listed.spaceId);
  assert.equal(one.id, listedJob);
  assert.equal(one.task_id, null);
  assert.equal((await wikiJobOf(h, listedJob)).kind, 'plan_draft');
  // canary, not listed: a task, exactly as under runner.
  const other = await owner(h);
  const [otherJob] = await planJobs(h, other.spaceId);
  assert.equal(otherJob.state, 'made');
  assert.ok(otherJob.task_id, 'an account canary does not list gets the task it always got');
  assert.equal(otherJob.job_id, null);
  const { rows: [task] } = await h.sql.query('SELECT "provider", "acceptance_command" FROM "task" WHERE "id" = $1', [otherJob.task_id]);
  assert.equal(task.provider, other.slug);
  assert.ok(String(task.acceptance_command).startsWith('orbit wiki plan check'));
  // runner: a task for everyone; the worker claims nothing.
  await reset(h, 'runner');
  const plain = await owner(h);
  const [plainJob] = await planJobs(h, plain.spaceId);
  assert.ok(plainJob.task_id && plainJob.job_id === null);
  const { rows: [{ n }] } = await h.sql.query('SELECT count(*)::int AS "n" FROM "wiki_job" WHERE "owner_id" = $1', [plain.id]);
  assert.equal(n, 0);
  // A revision under server: plan_revise, at the owner's priority, with the instructions kept on the plan job.
  await reset(h, 'server');
  const reviser = await owner(h);
  await clearJobs(h, reviser.spaceId);
  await baseVersion(h, reviser, { min: 3, max: 3 }, PLAN_BASE);
  const revise = await redraft(h, reviser, '合并存储。');
  const reviseJob = await wikiJobOf(h, revise);
  assert.equal(reviseJob.kind, 'plan_revise');
  assert.equal(reviseJob.priority, WIKI_PLAN_SERVER_JOB.priority);
  // No workspace: held, as on the runner's path.
  const held = await owner(h);
  await clearJobs(h, held.spaceId);
  await h.sql.query(`UPDATE "wiki_space" SET "settings" = jsonb_set("settings", '{maintenance,workspaceId}', 'null') WHERE "id" = $1`, [held.spaceId]);
  await redraft(h, held);
  const [heldJob] = await planJobs(h, held.spaceId);
  assert.equal(heldJob.state, 'held');
  // The switch moves back to runner while a server job has not started: the owner's next request cancels it and
  // is made on the runner's path.
  await reset(h, 'runner');
  const back = await redraft(h, listed);
  assert.notEqual(back, listedJob);
  const { rows: [cancelled] } = await h.sql.query('SELECT "state" FROM "wiki_job" WHERE "id" = $1', [(await wikiJobOf(h, listedJob)).id]);
  assert.equal(cancelled.state, 'cancelled');
  const rows = await planJobs(h, listed.spaceId);
  assert.equal(rows[0].state, 'ended');
  assert.ok(String(rows[0].error).includes('no longer executes'));
  assert.equal(rows[1].job_id, null, 'the next draft is the runner\'s again');
  assert.ok(['queued', 'made'].includes(rows[1].state), `the next draft is ${rows[1].state}`);
});

// ── 10. the runner door ──────────────────────────────────────────────────────────────────────────────

test('the runner door hands no session a plan job when the server drafts it — a build\'s session aside — and under runner it answers as it always has', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  // Under runner: the job's task, its session, and the door as it always was.
  await reset(h, 'runner');
  const o = await owner(h);
  const [job] = await planJobs(h, o.spaceId);
  const session = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id","task_id","status","dispatch_origin","updated_at")
     VALUES ($1,'a plan job session','p',$2,$2,$3,$4,$5,'RUNNING'::run_status,'USER',now())`,
    [session, o.id, o.workspaceId, o.runnerId, job.task_id],
  );
  const as = { runner: o.runnerToken, session };
  const context = await call(h, as, 'GET', `/runner/wiki/spaces/${o.spaceId}/plan/job`);
  expectStatus(context, 200, 'under runner the job\'s session reads its job');
  assert.equal(toUuid(context.body.job.id), job.id);
  expectStatus(await call(h, as, 'GET', `/runner/wiki/spaces/${o.spaceId}/plan/materials`), 200, 'and its materials');
  expectStatus(await call(h, as, 'POST', `/runner/wiki/spaces/${o.spaceId}/plan/job/progress`, { attempt: 1 }), 200, 'and says its round');
  const stranger = await call(h, { runner: o.runnerToken, session: await strangerSession(h, o) }, 'GET', `/runner/wiki/spaces/${o.spaceId}/plan/job`);
  assert.equal(stranger.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
  const build = await buildJobSession(h, o, job.task_id);
  const asBuild = { runner: o.runnerToken, session: build.session };

  // Under server (and for a listed canary account): every route a run of `orbit wiki plan draft` reaches is the
  // server's, whoever asks — so a command that predates this stops at its first call, before any model.
  for (const [mode, canary] of [['server', []], ['canary', [o.id]]] as const) {
    await reset(h, mode, [...canary]);
    for (const [method, route, body] of [
      ['GET', 'plan/job', undefined], ['GET', 'plan/materials', undefined], ['POST', 'plan/job/progress', { attempt: 1 }],
      ['POST', 'plan/job/finish', { outcome: 'failed', error: 'x' }], ['POST', 'plan/drafts', { baseVersion: null, plan: {}, repoCheck: { sha: SHA, checked: 0, missing: [] } }],
    ] as const) {
      const answer = await call(h, as, method, `/runner/wiki/spaces/${o.spaceId}/${route}`, body);
      expectStatus(answer, 409, `${mode}: ${method} ${route}`);
      assert.equal(answer.body.code, 'WIKI_SERVER_EXECUTES');
    }
    // What a maintenance run still reads of the plan is unchanged; another owner's space is still a 404.
    expectStatus(await call(h, as, 'GET', `/runner/wiki/spaces/${o.spaceId}/plan`), 200, `${mode}: a maintenance run reads the plan`);
    const theirs = await owner(h);
    expectStatus(await call(h, as, 'GET', `/runner/wiki/spaces/${theirs.spaceId}/plan/job`), 404, `${mode}: another owner's space`);
    // A build is not drafted: its job is the runner's task until the documents move to the server (P7), so its own
    // session reads its job and says how far it got — and is refused, like any other, what only a draft reads.
    const built = await call(h, asBuild, 'GET', `/runner/wiki/spaces/${o.spaceId}/plan/job`);
    expectStatus(built, 200, `${mode}: a build job's session reads its job`);
    assert.equal(toUuid(built.body.job.id), build.planJobId);
    assert.equal(built.body.job.kind, 'build');
    expectStatus(
      await call(h, asBuild, 'POST', `/runner/wiki/spaces/${o.spaceId}/plan/job/progress`, { docs: { done: 0, total: 3 }, current: null }),
      200, `${mode}: and says how far it got`,
    );
    for (const [method, route, body] of [
      ['GET', 'plan/materials', undefined], ['POST', 'plan/drafts', { baseVersion: null, plan: {}, repoCheck: { sha: SHA, checked: 0, missing: [] } }],
    ] as const) {
      const answer = await call(h, asBuild, method, `/runner/wiki/spaces/${o.spaceId}/${route}`, body);
      expectStatus(answer, 409, `${mode}: a build job's session, ${method} ${route}`);
      assert.equal(answer.body.code, 'WIKI_SERVER_EXECUTES');
    }
  }
  // Under canary, an account the list does not name is the runner's: the door answers it as before.
  await reset(h, 'canary', [randomUUID()]);
  expectStatus(await call(h, as, 'GET', `/runner/wiki/spaces/${o.spaceId}/plan/job`), 200, 'canary, not listed: as before');
});

/**
 * A build job made on the runner's path, as a confirmation makes one: its task in the space's hidden list (the one
 * the draft job's task is in), the confirmed version it writes, and the task's session on the owner's machine.
 */
async function buildJobSession(h: Harness, o: Owner, draftTaskId: string): Promise<{ planJobId: string; session: string }> {
  await baseVersion(h, o, { min: 3, max: 3 });
  const [{ list_id: listId }] = (await h.sql.query('SELECT "list_id" FROM "task" WHERE "id" = $1', [draftTaskId])).rows;
  const taskId = randomUUID();
  await h.prisma.task.create({
    data: { id: taskId, title: 'Wiki documents: App', ownerId: o.id, creatorType: 'USER', creatorId: o.id, listId, completionCriterion: 'OWNER_CONFIRMED' },
  });
  const planJob = await h.prisma.wikiPlanJob.create({
    data: { spaceId: o.spaceId, ownerId: o.id, kind: 'build', trigger: 'owner', state: 'made', taskId, madeAt: new Date(), version: 1 },
    select: { id: true },
  });
  const session = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id","task_id","status","dispatch_origin","updated_at")
     VALUES ($1,'a build job session','p',$2,$2,$3,$4,$5,'RUNNING'::run_status,'USER',now())`,
    [session, o.id, o.workspaceId, o.runnerId, taskId],
  );
  return { planJobId: planJob.id, session };
}

async function strangerSession(h: Harness, o: Owner): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id","status","dispatch_origin","updated_at")
     VALUES ($1,'a session','p',$2,$2,$3,$4,'RUNNING'::run_status,'USER',now())`,
    [id, o.id, o.workspaceId, o.runnerId],
  );
  return id;
}
