/**
 * `orbit wiki import` on the server (contracts/wiki.contract.json `import.server`, design §2.2 and §8, P5), against a
 * real PostgreSQL, the real runner door and wiki service, and a System model played by a local Node http server.
 *
 * The cases are `src/runner-go/wiki_import_test.go`'s, case for case, as the server runs them — the command's
 * own half (listing the files, their frontmatter, its memory) stays the runner's and is tested there:
 *
 *   1. each note is read as the server kept it, and what the model found is proposed: a dry run, then the batch
 *      under its key as the calling session, origin import; a principle counted and never proposed; the quote the
 *      note's own; the anchors the snapshot's — and the call itself is the importer's: its system prompt, its
 *      max_tokens, one user message, no tools and no thinking;
 *   2. what needs review goes a batch at a time: an op refused for what it says is dropped, and from the first one
 *      refused for room the rest wait — the next job proposes them without reading anything again, and a queue with
 *      no room stops the run;
 *   3. it takes effect as the space's mode says: Tiered applies, Automatic holds for the verification;
 *   4. a run picks up where the last one stopped: the notes it did not reach, and the ops it did not propose;
 *   5. the same batch sent again is the same key, and recorded once;
 *   6. a refused key pauses the import rather than failing it, and a restarted worker goes on from there;
 *   7. a model that is away is waited for, and a request that waited past its limit is asked again when the job
 *      is retried — once the model is back, the job finishes;
 *   8. an answer that does not hold up is asked about once more, with what was wrong, and a note the model never
 *      answers readably is failed and not read again;
 *   9. a Chinese note's entries are titled in Chinese;
 *  10. the anchors are held to a fresh snapshot when the space's runner can take one, and to the one the space
 *      holds when it cannot;
 *  11. a worker that dies mid-import: the next one finishes it, asking nothing twice and proposing once;
 *  12. the door: which path an import takes, a job made once under its id, the notes the space's own, nothing for
 *      an account the runner serves, and another owner's job is not there;
 *  13. the session's own model is out of it: when the server reads, the note route refuses a command that would
 *      read the note itself (WIKI_SERVER_EXECUTES) and hands the text to none, and the proposal route takes no
 *      entries a session's model wrote — and under the default runner both answer exactly as they always have.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki-worker/wiki-import-job.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every row belongs to an account the run created.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import type { AddressInfo, Socket } from 'node:net';
import { setTimeout as delay } from 'node:timers/promises';
import { after, afterEach, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { toUuid, WIKI_IMPORT_JOB, WIKI_REPO_OP_CAPABILITY } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiController } from '../wiki/wiki.controller';
import { WikiRetrieval } from '../wiki/wiki-retrieval';
import { WikiService, type WikiPrincipal, type WikiProposeInput } from '../wiki/wiki.service';
import { WikiJobExecutor } from './wiki-job-executor';
import { wikiImportJobRunner } from './wiki-import-job';
import { WikiModelRequestQueue } from './wiki-model-queue.service';
import { WikiModelStatusProbe } from './wiki-model-status';
import { WikiRepoOps } from './wiki-repo-ops';
import { readWikiSystemModel, type WikiSystemModelConfig } from './wiki-system-model';

const URL_ = process.env.COORDINATOR_PG_URL;
const skip = !URL_;

const KEY = `sk-spec-${randomUUID()}`;
const MODEL = 'qwen3.8-27b-fp8';
/** The one secret a note holds: one of the owner's workspace.env values, which registration takes out. */
const SECRET = ['SECRET', 'VALUE', randomUUID().slice(0, 8)].join('-');

// ── the System model ─────────────────────────────────────────────────────────────────────────────────

interface Hit {
  prompt: string;
  system: string;
  body: Record<string, unknown>;
  authorization: string;
}

type Reply = { status: number; text?: string };

interface FakeModel {
  base: string;
  health: number;
  answer: (prompt: string) => Reply;
  hits: Hit[];
  close: () => Promise<void>;
}

async function fakeModel(): Promise<FakeModel> {
  const sockets = new Set<Socket>();
  const model = { base: '', health: 200, answer: (): Reply => ({ status: 200, text: '[]' }), hits: [] as Hit[] } as unknown as FakeModel;
  const server = createServer((request: IncomingMessage, response: ServerResponse) => {
    let raw = '';
    request.on('data', (chunk: Buffer) => {
      raw += chunk.toString();
    });
    request.on('end', () => {
      if (request.url === '/health') {
        response.writeHead(model.health, { 'content-type': 'application/json' });
        response.end('{}');
        return;
      }
      const body = JSON.parse(raw) as { system?: string; messages?: Array<{ content?: string }> };
      const prompt = body.messages?.[0]?.content ?? '';
      model.hits.push({ prompt, system: body.system ?? '', body: body as Record<string, unknown>, authorization: String(request.headers.authorization ?? '') });
      const reply = model.answer(prompt);
      if (reply.status !== 200) {
        response.writeHead(reply.status, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ type: 'error', error: { type: reply.status === 401 ? 'authentication_error' : 'api_error', message: 'no' } }));
        return;
      }
      response.writeHead(200, { 'content-type': 'text/event-stream' });
      const event = (name: string, data: unknown) => `event: ${name}\ndata: ${JSON.stringify(data)}\n\n`;
      response.write(event('message_start', { type: 'message_start', message: { model: MODEL, usage: { input_tokens: 100, output_tokens: 1 } } }));
      response.write(event('content_block_delta', { type: 'content_block_delta', index: 0, delta: { type: 'text_delta', text: reply.text ?? '' } }));
      response.write(event('message_delta', { type: 'message_delta', delta: { stop_reason: 'end_turn' }, usage: { output_tokens: 20 } }));
      response.write(event('message_stop', { type: 'message_stop' }));
      response.end();
    });
  });
  server.on('connection', (socket: Socket) => {
    sockets.add(socket);
    socket.on('close', () => sockets.delete(socket));
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  model.base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  model.close = async () => {
    for (const socket of sockets) socket.destroy();
    await new Promise<void>((resolve) => server.close(() => resolve()));
  };
  return model;
}

/** Each note answered by its path; a note it names nothing for gets []. */
function scripted(answers: Record<string, string>): (prompt: string) => Reply {
  return (prompt) => {
    for (const [path, text] of Object.entries(answers)) {
      if (prompt.includes(`==== NOTE (${path},`)) return { status: 200, text };
    }
    return { status: 200, text: '[]' };
  };
}

function manyEntries(prefix: string, n: number): string {
  const entries = [];
  for (let i = 1; i <= n; i += 1) {
    entries.push(`{"kind":"concept","title":"${prefix} ${i}","summary":"What ${prefix} ${i} means.","definition":"It is ${i}.",`
      + `"boundaries":"Not ${i + 1}.","anchors":{"paths":[],"commits":[]},"quote":"fact"}`);
  }
  return `[${entries.join(',')}]`;
}

// ── the harness ──────────────────────────────────────────────────────────────────────────────────────

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  model: FakeModel;
  bearers: Map<string, string>;
  /** Every proposal the job made, as the wiki service was asked for it. */
  proposals: Array<{ principal: WikiPrincipal; spaceId: string; input: WikiProposeInput }>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  process.env.ORBIT_WIKI_EXECUTOR = 'server';
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL_);
    const sql = new Client({ connectionString: URL_, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL_ as string);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = { notifyWikiReviewModeTripped: async () => undefined } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);
    const proposals: Harness['proposals'] = [];
    const submit = service.submitChangeset.bind(service);
    service.submitChangeset = async (principal, spaceId, input) => {
      proposals.push({ principal, spaceId, input: JSON.parse(JSON.stringify(input)) as WikiProposeInput });
      return submit(principal, spaceId, input);
    };

    @Module({
      controllers: [WikiController, RunnerWikiController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiImportJobModule {}

    const app = await NestFactory.create(WikiImportJobModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, model: await fakeModel(), bearers, proposals };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql, model } = await harness;
  delete process.env.ORBIT_WIKI_EXECUTOR;
  await sql.query('DELETE FROM "wiki_model_status"').catch(() => undefined);
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
  await model.close().catch(() => undefined);
});

/** The workers a case started: one that fails halfway must not leave one claiming the next case's jobs. */
const live: Array<{ queue: WikiModelRequestQueue; executor: WikiJobExecutor }> = [];

afterEach(async () => {
  for (const one of live.splice(0)) {
    await one.executor.onModuleDestroy().catch(() => undefined);
    await one.queue.onModuleDestroy().catch(() => undefined);
  }
});

function config(h: Harness): WikiSystemModelConfig {
  return readWikiSystemModel({
    ORBIT_WIKI_MODEL_BASE_URL: h.model.base,
    ORBIT_WIKI_MODEL_API_KEY: KEY,
    ORBIT_WIKI_MODEL: MODEL,
    ORBIT_WIKI_MODEL_CONCURRENCY: '4',
  });
}

/** A worker as the wiki-worker module builds one, with fast timings: the import kind in its map. */
function worker(h: Harness, over: { snapshotWaitMs?: number } = {}): { queue: WikiModelRequestQueue; executor: WikiJobExecutor } {
  const options = { leaseMs: 1_000, renewMs: 200, partialMs: 40, pollMs: 25 };
  const prisma = h.prisma as unknown as PrismaService;
  const probe = new WikiModelStatusProbe(prisma, config(h));
  const queue = new WikiModelRequestQueue(prisma, config(h), probe, undefined, options);
  const runners = {
    import: wikiImportJobRunner({
      prisma, wiki: h.service, repoOps: new WikiRepoOps(prisma), model: MODEL, snapshotWaitMs: over.snapshotWaitMs ?? 5_000,
    }),
  };
  const executor = new WikiJobExecutor(prisma, queue, options, runners);
  live.push({ queue, executor });
  return { queue, executor };
}

/** The model up, as a fresh worker's first probe writes it. */
async function modelUp(h: Harness): Promise<void> {
  h.model.health = 200;
  await h.sql.query('DELETE FROM "wiki_model_status"');
  await new WikiModelStatusProbe(h.prisma as unknown as PrismaService, config(h)).check();
}

async function reset(h: Harness): Promise<void> {
  h.model.hits.length = 0;
  h.model.answer = () => ({ status: 200, text: '[]' });
  h.proposals.length = 0;
  await modelUp(h);
}

// ── requests ─────────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

// ── fixtures ─────────────────────────────────────────────────────────────────────────────────────────

type Mode = 'manual' | 'tiered' | 'automatic';

/** The owner, their machine, a workspace (with the secret in its env), a space in `mode`, and a session that imports. */
interface Importer {
  ownerId: string;
  bearer: string;
  runnerId: string;
  workspaceId: string;
  spaceId: string;
  session: string;
  as: Caller;
}

async function importer(h: Harness, mode: Mode): Promise<Importer> {
  const ownerId = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,'import job spec','x')`, [
    ownerId, `wiki-import-job-${ownerId}@wiki.invalid`,
  ]);
  const bearer = `bearer-${ownerId}`;
  h.bearers.set(bearer, ownerId);
  const runnerId = randomUUID();
  const token = `runner-${runnerId}`;
  await h.sql.query(
    `INSERT INTO "runner"("id","name","owner_id","token_hash","capabilities","capabilities_reported_at","last_heartbeat_at")
     VALUES ($1,'spec',$2,$3,$4,now(),now())`,
    [runnerId, ownerId, createHash('sha256').update(token).digest('hex'), [WIKI_REPO_OP_CAPABILITY]],
  );
  const workspaceId = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env","runner_id","work_dir") VALUES ($1,'spec',$2,$3,$4,'/tmp/import-spec')`, [
    workspaceId, ownerId, JSON.stringify({ VAULT_KEY: SECRET }), runnerId,
  ]);
  const made = await call(h, { bearer }, 'POST', '/wiki/spaces', { title: `An ${mode} import` });
  expectStatus(made, 201, 'the owner creates a space');
  const spaceId = toUuid(made.body.id as string);
  expectStatus(await call(h, { bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { reviewMode: mode }), 200, `the space goes ${mode}`);
  const session = await sessionOf(h, ownerId, workspaceId, runnerId);
  return { ownerId, bearer, runnerId, workspaceId, spaceId, session, as: { runner: token, session } };
}

async function sessionOf(h: Harness, ownerId: string, workspaceId: string, runnerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id","dispatch_origin","updated_at")
     VALUES ($1,'an import session','p',$2,$2,$3,$4,'USER',now())`,
    [id, ownerId, workspaceId, runnerId],
  );
  return id;
}

/** One file registered through the door, as the command registers it when the server reads: its id as the door answers it. */
async function note(h: Harness, who: Importer, path: string, text: string): Promise<{ id: string }> {
  const answer = await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/notes`, { path, text, readBy: 'server' });
  expectStatus(answer, 200, `the file ${path} is registered as a note`);
  assert.equal('text' in answer.body, false, 'the text the server reads is not handed back');
  return answer.body as { id: string };
}

/** The space's snapshot, as a settled snapshot operation leaves it: the tree and the commits origin/main reaches. */
async function snapshot(h: Harness, who: Importer, sha: string, files: string[], commits: string[]): Promise<void> {
  const index = JSON.stringify({ sha, files: files.map((path) => ({ path, size: 1 })), commits });
  await h.prisma.wikiRepoSnapshot.deleteMany({ where: { spaceId: who.spaceId } });
  await h.prisma.wikiRepoSnapshot.create({
    data: {
      spaceId: who.spaceId, ownerId: who.ownerId, sha,
      digest: createHash('sha256').update(index).digest('hex'), sizeBytes: BigInt(Buffer.byteLength(index)), fragmentCount: 1,
    },
  });
  await h.prisma.wikiRepoSnapshotFragment.create({ data: { spaceId: who.spaceId, ordinal: 0, content: index } });
}

interface JobNote {
  noteId: string;
  file: string;
  date: string;
  ops?: Array<{ index: number; body: Record<string, unknown> }>;
}

/** The job the command makes: its id named, through the door. */
async function makeJob(h: Harness, who: Importer, notes: JobNote[], over: Record<string, unknown> = {}): Promise<string> {
  const id = randomUUID();
  const made = await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/import-jobs`, { id, maxOps: 30, concurrency: 4, notes, ...over });
  expectStatus(made, 200, 'the import job is made');
  return id;
}

/** The job as the command reads it. */
async function readJob(h: Harness, who: Importer, id: string): Promise<Answer> {
  return call(h, who.as, 'GET', `/runner/wiki/spaces/${who.spaceId}/import-jobs/${id}`);
}

/** Run the worker until the job ends, and read it as the command would. */
async function drive(
  h: Harness,
  who: Importer,
  id: string,
  w: { queue: WikiModelRequestQueue; executor: WikiJobExecutor },
  seconds = 20,
): Promise<Answer> {
  await passes(w, async () => {
    const { rows: [row] } = await h.sql.query<{ state: string }>('SELECT "state" FROM "wiki_job" WHERE "id" = $1', [id]);
    return ['succeeded', 'failed', 'cancelled'].includes(row.state);
  }, `the job ${id} to end`, seconds);
  await w.executor.whenIdle();
  return readJob(h, who, id);
}

/** Passes of the worker until `ok`, with no wait for what the job is still doing. */
async function passes(
  w: { queue: WikiModelRequestQueue; executor: WikiJobExecutor },
  ok: () => Promise<boolean>,
  what: string,
  seconds = 20,
): Promise<void> {
  const deadline = Date.now() + seconds * 1000;
  for (;;) {
    await w.executor.runOnce();
    await w.queue.runOnce();
    if (await ok()) return;
    assert.ok(Date.now() < deadline, `${what} within ${seconds}s`);
    await delay(25);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function titles(ops: any[]): string[] {
  return ops.map((op) => op.entry?.title as string);
}

/** Every op the job proposed for real, in order. */
function proposed(h: Harness): Array<Record<string, unknown>> {
  return h.proposals.filter((one) => !one.input.dryRun).flatMap((one) => one.input.ops as Array<Record<string, unknown>>);
}

const date = '2026-09-20';

// ── 1. one import, end to end ────────────────────────────────────────────────────────────────────────

test('each note is read as the server kept it, and what the model found is proposed as the calling session', { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const HEAD = createHash('sha1').update(randomUUID()).digest('hex');
  await snapshot(h, who, HEAD, ['src/app/main.go', 'docs/guide.md'], [HEAD]);
  // The space's repository, as binding a workspace on github.com/wikova/orbit names it: a note's /root/orbit/… is a path in it.
  await h.sql.query('UPDATE "wiki_space" SET "repo_url_norm" = $2 WHERE "id" = $1', [who.spaceId, 'github.com/wikova/orbit']);
  const rules = await note(h, who, 'memory/feedback-rules.md', `Reply in Chinese; code stays as it is.\nNever keep a credential in a file: the vault key is ${SECRET}.\n`);
  const release = await note(h, who, 'memory/reference-release.md',
    '`release.sh next` tags at once: it is not a dry run.\nThe guard lives in src/app/main.go, and docs/guide.md explains it.\n');
  const status = await note(h, who, 'memory/project-status.md', 'The import task is in progress.');
  h.model.answer = scripted({
    'memory/feedback-rules.md': '[{"kind":"convention","title":"Reply in Chinese","summary":"Answer the owner in Chinese; leave code as it is.",'
      + '"rule":"Reply in Chinese","scope":"every reply","exceptions":"","anchors":{"paths":[],"commits":[]},"quote":"Reply in Chinese; code stays as it is."},'
      + '{"kind":"principle","title":"Secrets are never stored","summary":"x","statement":"Never store a secret.","rationale":"It leaks.","quote":"Never store a secret"}]',
    'memory/reference-release.md': 'Here is what I found.\n```json\n'
      + '[{"kind":"pitfall","title":"release.sh next tags at once","summary":"It is not a dry run.",'
      + '"trigger":{"paths":[],"commands":["release.sh next"],"errorSignature":""},"symptom":"A tag appears","cause":"next tags","fix":"Run it only to release",'
      + `"anchors":{"paths":["src/app/main.go","/root/orbit/docs/guide.md","src/does/not/exist.go"],"commits":["${HEAD.slice(0, 9)}","0000000"]},`
      + '"quote":"release.sh next tags at once: it is not a dry run."}]\n```',
  });
  const w = worker(h);
  const id = await makeJob(h, who, [
    { noteId: rules.id, file: 'memory/feedback-rules.md', date },
    { noteId: release.id, file: 'memory/reference-release.md', date },
    { noteId: status.id, file: 'memory/project-status.md', date },
  ]);
  const job = await drive(h, who, id, w);
  assert.equal(job.body.state, 'succeeded', JSON.stringify(job.body));

  // The model read what the server kept — the secret redacted — never the file as it was read; one call a note,
  // each the importer's: its own system prompt, its max_tokens, one user message, no tools and no thinking.
  assert.equal(h.model.hits.length, 3, 'the model was asked once per note');
  let handed = false;
  for (const hit of h.model.hits) {
    assert.ok(!hit.prompt.includes(SECRET), "the file's secret reached the model");
    assert.equal(hit.system, WIKI_IMPORT_JOB.systemPrompt);
    assert.deepEqual(Object.keys(hit.body).sort(), ['max_tokens', 'messages', 'model', 'stream', 'system']);
    assert.equal(hit.body.max_tokens, WIKI_IMPORT_JOB.maxTokens);
    assert.equal(hit.body.model, MODEL);
    assert.equal(hit.authorization, `Bearer ${KEY}`);
    if (hit.prompt.includes(`==== NOTE (memory/feedback-rules.md, ${date}) ====`)) handed = hit.prompt.includes('the vault key is [redacted].');
  }
  assert.ok(handed, "the model was handed the kept text, under the note's path and date");

  // A dry run first, then the ops that passed it, under a key; as the calling session, origin import.
  assert.equal(h.proposals.length, 2);
  const [dry, real] = h.proposals;
  assert.equal(dry.input.dryRun, true);
  assert.equal(dry.input.idempotencyKey, undefined);
  assert.equal(real.input.dryRun, undefined);
  assert.match(real.input.idempotencyKey ?? '', /^wiki-import:[0-9a-f]{40}$/u);
  assert.deepEqual(dry.input.ops, real.input.ops, 'what was proposed is what the dry run checked');
  for (const one of h.proposals) {
    assert.deepEqual([one.principal.origin, one.principal.sessionId, one.spaceId], ['import', who.session, who.spaceId]);
  }
  assert.match(String(real.input.rationale), new RegExp(`^orbit wiki import: 2 entries the System model \\(${MODEL}\\) read in 2 notes: memory/feedback-rules.md, memory/reference-release.md$`, 'u'));
  const ops = proposed(h);
  assert.deepEqual(titles(ops), ['Reply in Chinese', 'release.sh next tags at once'], "the principle is the owner's and never proposed");
  const [convention, pitfall] = ops as Array<{ entry: Record<string, unknown>; sources: Array<Record<string, unknown>> }>;
  assert.deepEqual(convention.sources, [{ kind: 'note', ref: toUuid(rules.id), quote: 'Reply in Chinese; code stays as it is.' }]);
  assert.deepEqual(convention.entry.fields, { rule: 'Reply in Chinese', scope: ['every reply'] }, 'a lone scope is a list of one, and a blank exception is left out');
  // The model dropped the backticks from its quote: the note's own span is cited instead.
  assert.deepEqual(pitfall.sources, [{ kind: 'note', ref: toUuid(release.id), quote: '`release.sh next` tags at once: it is not a dry run.' }]);
  // Only the anchors the snapshot has: the paths it holds, made relative, and its commit in full.
  assert.deepEqual(pitfall.entry.anchors, [
    { type: 'path', path: 'src/app/main.go' },
    { type: 'path', path: 'docs/guide.md' },
    { type: 'commit', sha: HEAD },
  ]);
  assert.deepEqual((pitfall.entry.fields as Record<string, unknown>).trigger, { paths: [], commands: ['release.sh next'] });

  // The report: what the command prints.
  const report = job.body.report;
  assert.equal(report.model, MODEL);
  assert.deepEqual(report.snapshot, { sha: HEAD, fresh: false }, 'the space names no workspace to snapshot in: the snapshot it holds');
  assert.deepEqual(
    { ...report.summary, refusals: report.summary.refusals.length },
    {
      notes: 3, read: 3, entries: 2, principles: 1, dropped: 0, failed: 0, proposed: 2, applied: 2, pending: 0, verifying: 0,
      refused: 0, deferred: 0, calls: 3, inputTokens: 300, outputTokens: 60, refusals: 0, stopped: '',
    },
  );
  assert.deepEqual(report.notes.map((n: { file: string; status: string; ops: unknown[] }) => [n.file, n.status, n.ops.length]), [
    ['memory/feedback-rules.md', 'read', 1],
    ['memory/reference-release.md', 'read', 1],
    ['memory/project-status.md', 'read', 0],
  ]);
  for (const op of report.notes.flatMap((n: { ops: Array<{ outcome: string; opId: string; entryId: string }> }) => n.ops)) {
    assert.equal(op.outcome, 'applied');
    assert.ok(op.opId && op.entryId, 'an applied op names its op and entry');
  }
  // Recorded once, against the calling session, with origin import.
  const changesets = await h.prisma.wikiChangeset.findMany({ where: { spaceId: who.spaceId }, select: { origin: true, sessionId: true, idempotencyKey: true } });
  assert.deepEqual(changesets, [{ origin: 'import', sessionId: who.session, idempotencyKey: real.input.idempotencyKey }]);
});

// ── 2. what needs review, a batch at a time ──────────────────────────────────────────────────────────

test('what needs review is proposed a batch at a time, and the rest waits for the next run', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'manual');
  const a = await note(h, who, 'memory/feedback-a.md', 'A fact, and another fact.');
  const b = await note(h, who, 'memory/feedback-b.md', 'More fact here.');
  // A title that holds nothing but a byte-order mark: the importer's checks keep it (Go's TrimSpace does not take
  // U+FEFF out), and the server's schema refuses it — an op refused for what it says.
  h.model.answer = scripted({
    'memory/feedback-a.md': manyEntries('Alpha', 4).replace('"title":"Alpha 2"', '"title":"\\ufeff"'),
    'memory/feedback-b.md': manyEntries('Beta', 4),
  });
  const w = worker(h);
  const first = await drive(h, who, await makeJob(h, who, [
    { noteId: a.id, file: 'memory/feedback-a.md', date },
    { noteId: b.id, file: 'memory/feedback-b.md', date },
  ], { concurrency: 2 }), w);
  // Manual: five that wait for review a request. The dry run says which pass; one refused for what it says is
  // dropped, and from the first one refused for room the rest wait for the next run.
  assert.deepEqual(titles(proposed(h)), ['Alpha 1', 'Alpha 3', 'Alpha 4', 'Beta 1', 'Beta 2']);
  const summary = first.body.report.summary;
  assert.deepEqual([summary.pending, summary.refused, summary.deferred, summary.proposed], [5, 1, 2, 5]);
  assert.deepEqual(summary.refusals.map((r: { code: string; file: string }) => [r.code, r.file]), [['WIKI_SCHEMA', 'memory/feedback-a.md']]);
  const leftB = first.body.report.notes.find((n: { file: string }) => n.file === 'memory/feedback-b.md');
  assert.deepEqual(leftB.ops.map((op: { outcome: string }) => op.outcome), ['pending', 'pending', '', ''], "the two that had no room are still nobody's");

  // The next run carries what waited, and reads nothing again.
  const calls = h.model.hits.length;
  h.proposals.length = 0;
  const carried = leftB.ops.filter((op: { outcome: string }) => op.outcome === '').map((op: { index: number; body: Record<string, unknown> }) => ({ index: op.index, body: op.body }));
  const second = await drive(h, who, await makeJob(h, who, [{ noteId: b.id, file: 'memory/feedback-b.md', date, ops: carried }]), w);
  assert.deepEqual(titles(proposed(h)), ['Beta 3', 'Beta 4']);
  assert.equal(h.model.hits.length, calls, 'nothing was read again');
  assert.deepEqual([second.body.report.summary.pending, second.body.report.summary.calls], [2, 0]);
  assert.deepEqual(
    second.body.report.notes.map((n: { status: string; ops: Array<{ index: number; outcome: string }> }) =>
      [n.status, n.ops.map(({ index, outcome }) => ({ index, outcome }))]),
    [['carried', [{ index: 2, outcome: 'pending' }, { index: 3, outcome: 'pending' }]]],
    'the carried ops answered at the places the command keeps them',
  );

  // A review queue with no room: nothing can be proposed, so the run says so.
  for (let i = 0; i < 6; i += 1) {
    const filler = await sessionOf(h, who.ownerId, who.workspaceId, who.runnerId);
    for (let j = 0; j < 2 && (i * 10 + j * 5) < 30 - 7; j += 1) {
      await h.service.submitChangeset({ origin: 'agent', ownerId: who.ownerId, userId: null, sessionId: filler, toolCallId: null }, who.spaceId, {
        rationale: 'filling the review queue',
        ops: Array.from({ length: 5 }, (_, k) => ({
          op: 'add',
          entry: { kind: 'concept', title: `Filler ${i}-${j}-${k}`, summary: 's', fields: { definition: 'd', boundaries: 'b' } },
          sources: [{ kind: 'note', ref: toUuid(a.id) }],
        })),
      });
    }
  }
  const pending = await h.prisma.wikiChangesetOp.count({ where: { ownerId: who.ownerId, decision: 'pending', changeset: { spaceId: who.spaceId } } });
  assert.ok(pending >= 30, `the space holds ${pending} ops waiting for review`);
  const c = await note(h, who, 'memory/feedback-c.md', 'The last fact.');
  h.model.answer = scripted({ 'memory/feedback-c.md': manyEntries('Gamma', 2) });
  h.proposals.length = 0;
  const fresh = await sessionOf(h, who.ownerId, who.workspaceId, who.runnerId);
  const full = await drive(h, { ...who, session: fresh, as: { ...who.as, session: fresh } },
    await makeJob(h, { ...who, session: fresh, as: { ...who.as, session: fresh } }, [{ noteId: c.id, file: 'memory/feedback-c.md', date }]), w);
  const stopped = full.body.report.summary;
  assert.equal(stopped.proposed, 0);
  assert.equal(stopped.deferred, 2);
  assert.match(stopped.stopped, /^no room to propose anything now \(WIKI_REVIEW_QUEUE_FULL: /u);
  assert.equal(proposed(h).length, 0, 'a dry run, and nothing proposed');
});

// ── 3. the space's mode ──────────────────────────────────────────────────────────────────────────────

test('what is proposed takes effect as the space\'s mode says: Tiered applies, Automatic holds for the verification', { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  for (const [mode, applied, verifying] of [['tiered', 2, 0], ['automatic', 0, 2]] as const) {
    await reset(h);
    const who = await importer(h, mode);
    const one = await note(h, who, 'memory/reference-a.md', `Two facts, ${mode}.`);
    h.model.answer = scripted({ 'memory/reference-a.md': manyEntries('Fact', 2) });
    const job = await drive(h, who, await makeJob(h, who, [{ noteId: one.id, file: 'memory/reference-a.md', date }]), worker(h));
    const summary = job.body.report.summary;
    assert.deepEqual([summary.proposed, summary.applied, summary.pending, summary.verifying], [2, applied, 0, verifying], mode);
    assert.deepEqual(job.body.report.notes[0].ops.map((op: { outcome: string }) => op.outcome), mode === 'tiered' ? ['applied', 'applied'] : ['verifying', 'verifying']);
  }
});

// ── 4. where a run stops, and where the next one starts ──────────────────────────────────────────────

test('a run picks up where the last one stopped: the notes it did not reach, and the ops it did not propose', { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const notes = [];
  for (const n of ['1', '2', '3']) notes.push(await note(h, who, `memory/feedback-${n}.md`, `fact ${n}`));
  h.model.answer = scripted({
    'memory/feedback-1.md': manyEntries('One', 2),
    'memory/feedback-2.md': manyEntries('Two', 2),
    'memory/feedback-3.md': manyEntries('Three', 2),
  });
  const w = worker(h);
  const input = notes.map((n, i) => ({ noteId: n.id, file: `memory/feedback-${i + 1}.md`, date }));
  const first = await drive(h, who, await makeJob(h, who, input, { maxOps: 3, concurrency: 1 }), w);
  assert.deepEqual(titles(proposed(h)), ['One 1', 'One 2', 'Two 1']);
  assert.equal(first.body.report.summary.calls, 2, 'the third note was not reached');
  assert.deepEqual(first.body.report.notes.map((n: { file: string }) => n.file), ['memory/feedback-1.md', 'memory/feedback-2.md']);
  const two = first.body.report.notes[1];
  assert.deepEqual(two.ops.map((op: { outcome: string }) => op.outcome), ['applied', '']);

  // The command's next run: the op it did not propose, carried, and the note it did not reach.
  h.proposals.length = 0;
  const second = await drive(h, who, await makeJob(h, who, [
    { ...input[1], ops: [{ index: 1, body: two.ops[1].body }] },
    input[2],
  ], { maxOps: 3, concurrency: 1 }), w);
  assert.deepEqual(titles(proposed(h)), ['Two 2', 'Three 1', 'Three 2']);
  assert.equal(second.body.report.summary.calls, 1, 'only the note not read before was read');
  assert.equal(h.model.hits.length, 3);
});

// ── 5. the same batch, the same key ─────────────────────────────────────────────────────────────────

test('a batch sent again goes under the same key, and the server records it once', { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const one = await note(h, who, 'memory/feedback-1.md', 'fact one');
  h.model.answer = scripted({ 'memory/feedback-1.md': manyEntries('One', 2) });
  const w = worker(h);
  const first = await drive(h, who, await makeJob(h, who, [{ noteId: one.id, file: 'memory/feedback-1.md', date }]), w);
  // The report never reached the machine: its memory still has both ops unanswered, and its next run carries them.
  const carried = first.body.report.notes[0].ops.map((op: { index: number; body: Record<string, unknown> }) => ({ index: op.index, body: op.body }));
  const again = await drive(h, who, await makeJob(h, who, [{ noteId: one.id, file: 'memory/feedback-1.md', date, ops: carried }]), w);
  const keys = h.proposals.filter((p) => !p.input.dryRun).map((p) => p.input.idempotencyKey);
  assert.equal(keys.length, 2);
  assert.equal(keys[0], keys[1], 'the same ops go under the same key, which the server replays');
  assert.equal(await h.prisma.wikiChangeset.count({ where: { spaceId: who.spaceId } }), 1, 'recorded once');
  assert.deepEqual(
    again.body.report.notes[0].ops.map((op: { opId: string }) => op.opId),
    first.body.report.notes[0].ops.map((op: { opId: string }) => op.opId),
    'the replay answers with the ops the first send recorded',
  );
});

// ── 6. a refused key ─────────────────────────────────────────────────────────────────────────────────

test('a refused key pauses the import rather than failing it, and a restarted worker goes on from there', { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const one = await note(h, who, 'memory/feedback-1.md', 'fact one');
  const two = await note(h, who, 'memory/feedback-2.md', 'fact two');
  h.model.answer = () => ({ status: 401 });
  const w = worker(h);
  const id = await makeJob(h, who, [
    { noteId: one.id, file: 'memory/feedback-1.md', date },
    { noteId: two.id, file: 'memory/feedback-2.md', date },
  ], { concurrency: 1 });
  await passes(w, async () => h.model.hits.length >= 1, 'the first read');
  // The queue stops at the first 401: the model is not asked again while the key is refused, nothing is proposed.
  for (let i = 0; i < 10; i += 1) {
    await w.queue.runOnce();
    await delay(25);
  }
  assert.equal(h.model.hits.length, 1, 'the endpoint was asked once: the first 401 pauses the queue');
  assert.equal(h.proposals.length, 0, 'nothing was proposed after the 401');
  const waiting = await readJob(h, who, id);
  assert.equal(waiting.body.state, 'running', 'the job waits; it does not fail for what is the deployment\'s to fix');
  assert.equal(waiting.body.model.state, 'auth_failed', 'and the command reads why it waits');

  // The deployment fixes the key and the worker restarts: the job goes on, and reads both notes.
  await w.executor.onModuleDestroy();
  await w.queue.onModuleDestroy();
  h.model.answer = scripted({ 'memory/feedback-1.md': manyEntries('One', 1), 'memory/feedback-2.md': manyEntries('Two', 1) });
  await modelUp(h);
  const job = await drive(h, who, id, worker(h));
  assert.equal(job.body.state, 'succeeded');
  assert.deepEqual([job.body.report.summary.proposed, job.body.report.summary.read], [2, 2]);
});

// ── 7. a model that is away ──────────────────────────────────────────────────────────────────────────

test('a model that is away is waited for, and a read that waited past its limit is asked again once the job is retried', { skip, timeout: 120_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const one = await note(h, who, 'memory/feedback-1.md', 'fact one');
  h.model.answer = scripted({ 'memory/feedback-1.md': manyEntries('One', 1) });
  // Down: the probe says so, and the queue takes nothing.
  h.model.health = 503;
  await new WikiModelStatusProbe(h.prisma as unknown as PrismaService, config(h)).check();
  const w = worker(h);
  const id = await makeJob(h, who, [{ noteId: one.id, file: 'memory/feedback-1.md', date }]);
  await passes(w, async () => (await h.prisma.wikiModelRequest.count({ where: { jobId: id } })) === 1, 'the read is queued');
  for (let i = 0; i < 10; i += 1) {
    await w.queue.runOnce();
    await delay(20);
  }
  assert.equal(h.model.hits.length, 0, 'nothing is asked of a model that is down');
  // It waits past its step's limit: the request fails, and the job goes back to the queue as the platform's failure.
  await h.sql.query(`UPDATE "wiki_model_request" SET "enqueued_at" = now() - interval '601 seconds' WHERE "job_id" = $1`, [id]);
  await w.queue.runOnce();
  await waitFor(async () => (await h.sql.query('SELECT "state" FROM "wiki_job" WHERE "id" = $1', [id])).rows[0].state === 'queued', 'the job is requeued');
  await w.executor.whenIdle();
  const requeued = await readJob(h, who, id);
  assert.equal(requeued.body.failureKind, 'infra');
  assert.match(requeued.body.error, /waited past its step's limit \(600 s\)/u);
  // The model comes back; the retried job asks again — a new attempt of the same read — and finishes.
  await h.sql.query(`UPDATE "wiki_job" SET "next_attempt_at" = now() WHERE "id" = $1`, [id]);
  await modelUp(h);
  const job = await drive(h, who, id, w);
  assert.equal(job.body.state, 'succeeded');
  assert.equal(job.body.report.summary.proposed, 1);
  const attempts = await h.prisma.wikiModelRequest.findMany({ where: { jobId: id }, orderBy: { attempt: 'asc' }, select: { attempt: true, state: true } });
  assert.deepEqual(attempts, [{ attempt: 1, state: 'failed' }, { attempt: 2, state: 'succeeded' }]);
  assert.equal(h.model.hits.length, 1);
});

// ── 8. once more, with what was wrong ────────────────────────────────────────────────────────────────

test('an answer that does not hold up is asked about once more, and a note never answered readably is failed', { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const one = await note(h, who, 'memory/feedback-1.md', 'fact one');
  const two = await note(h, who, 'memory/feedback-2.md', 'fact two');
  h.model.answer = (prompt) => {
    const retry = prompt.includes('SOME ENTRIES IN YOUR ANSWER WERE REJECTED');
    if (prompt.includes('==== NOTE (memory/feedback-1.md,') && retry) {
      return { status: 200, text: '[{"kind":"convention","title":"Keep it","summary":"s","rule":"Keep it","scope":["here"]}]' };
    }
    if (prompt.includes('==== NOTE (memory/feedback-1.md,')) {
      return { status: 200, text: '[{"kind":"convention","title":"Keep it","summary":"s","rule":"Keep it"},{"kind":"concept","title":"Also","summary":"s","definition":"d","boundaries":"b"}]' };
    }
    return { status: 200, text: 'I would rather not.' };
  };
  const job = await drive(h, who, await makeJob(h, who, [
    { noteId: one.id, file: 'memory/feedback-1.md', date },
    { noteId: two.id, file: 'memory/feedback-2.md', date },
  ], { concurrency: 1 }), worker(h));
  assert.equal(h.model.hits.length, 4, 'once per note, and once more for each answer that did not hold up');
  assert.ok(h.model.hits[1].prompt.includes('entry "Keep it": scope is missing'), 'the second ask says what was wrong');
  assert.ok(h.model.hits[3].prompt.includes('YOUR ANSWER WAS NOT A JSON ARRAY'), 'the second ask of an unreadable answer says so');
  assert.deepEqual(titles(proposed(h)), ['Also', 'Keep it'], 'the corrected entry joins the one that held up');
  const summary = job.body.report.summary;
  assert.deepEqual([summary.failed, summary.dropped, summary.calls], [1, 0, 4]);
  const failed = job.body.report.notes.find((n: { file: string }) => n.file === 'memory/feedback-2.md');
  assert.deepEqual([failed.status, failed.why], ['failed', "the model's answer held no JSON array of entries"]);
});

// ── 9. a Chinese note ────────────────────────────────────────────────────────────────────────────────

test("a Chinese note's entries are titled in Chinese, and an English title for one is sent back", { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const zh = await note(h, who, 'memory/feedback-zh.md', '发版前先核对 `origin/main`：别直接给会话分支打 tag，否则客户端会倒退。\n');
  const en = await note(h, who, 'memory/feedback-en.md', 'Check `origin/main` before tagging a release.\n');
  h.model.answer = (prompt) => {
    const retry = prompt.includes('SOME ENTRIES IN YOUR ANSWER WERE REJECTED');
    if (prompt.includes('==== NOTE (memory/feedback-zh.md,') && retry) {
      return { status: 200, text: '[{"kind":"convention","title":"发版前先核对 origin/main","summary":"别给会话分支打 tag。","rule":"先核对 origin/main 再打 tag","scope":["发版"]}]' };
    }
    if (prompt.includes('==== NOTE (memory/feedback-zh.md,')) {
      return { status: 200, text: '[{"kind":"convention","title":"Check origin/main before a release","summary":"别给会话分支打 tag。","rule":"先核对 origin/main 再打 tag","scope":["发版"]}]' };
    }
    return { status: 200, text: '[{"kind":"convention","title":"Check origin/main before tagging","summary":"Never tag a session branch.","rule":"Check origin/main first","scope":["releases"]}]' };
  };
  await drive(h, who, await makeJob(h, who, [
    { noteId: zh.id, file: 'memory/feedback-zh.md', date },
    { noteId: en.id, file: 'memory/feedback-en.md', date },
  ], { concurrency: 1 }), worker(h));
  assert.equal(h.model.hits.length, 3, 'once per note, and once more for the English title');
  const line = 'This note is written in Chinese: write every title, summary and text field in Chinese';
  for (const hit of h.model.hits) assert.equal(hit.prompt.includes(line), hit.prompt.includes('==== NOTE (memory/feedback-zh.md,'));
  assert.ok(h.model.hits.some((hit) => hit.prompt.includes('entry "Check origin/main before a release": title is not in the note\'s language')));
  assert.deepEqual(titles(proposed(h)), ['发版前先核对 origin/main', 'Check origin/main before tagging']);
});

// ── 10. the snapshot ─────────────────────────────────────────────────────────────────────────────────

test("the anchors are held to a fresh snapshot when the space's runner can take one, and to the space's own otherwise", { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const OLD = createHash('sha1').update(`old-${randomUUID()}`).digest('hex');
  const NEW = createHash('sha1').update(`new-${randomUUID()}`).digest('hex');
  await snapshot(h, who, OLD, ['src/old.go'], [OLD]);
  // The space reads its repository in the workspace on the runner the fixture made: a capable machine, online.
  await h.sql.query(`UPDATE "wiki_space" SET "settings" = jsonb_build_object('maintenance', jsonb_build_object('workspaceId', $2::text)) WHERE "id" = $1`, [
    who.spaceId, who.workspaceId,
  ]);
  const one = await note(h, who, 'memory/feedback-1.md', 'src/new.go and src/old.go, at both commits.');
  h.model.answer = scripted({
    'memory/feedback-1.md': '[{"kind":"concept","title":"Both files","summary":"s","definition":"d","boundaries":"b",'
      + `"anchors":{"paths":["src/new.go","src/old.go"],"commits":["${NEW}","${OLD}"]}}]`,
  });
  const ops = new WikiRepoOps(h.prisma as unknown as PrismaService);
  const w = worker(h, { snapshotWaitMs: 15_000 });
  const id = await makeJob(h, who, [{ noteId: one.id, file: 'memory/feedback-1.md', date }]);
  // The runner, as its heartbeat would: it claims the job's snapshot operation and answers with the tree it read.
  const playRunner = (async () => {
    for (let i = 0; i < 400; i += 1) {
      const claimed = await ops.dispatch({ runnerId: who.runnerId, leaseOwner: randomUUID(), draining: false, capabilities: [WIKI_REPO_OP_CAPABILITY] });
      const op = claimed.find((c) => c.kind === 'snapshot');
      if (op) {
        assert.deepEqual(op.input, { skipSha: OLD }, 'the snapshot the space holds is named, so an unchanged commit is not sent again');
        const index = JSON.stringify({ sha: NEW, files: [{ path: 'src/new.go', size: 1 }], commits: [NEW] });
        await ops.applyWikiRepoOpResult({
          id: op.id, runnerId: who.runnerId,
          body: { claimGeneration: op.claimGeneration, leaseOwner: op.leaseOwner, state: 'succeeded', result: { sha: NEW, index } },
        });
        return;
      }
      await delay(25);
    }
    assert.fail('no snapshot operation was handed to the runner');
  })();
  const job = await drive(h, who, id, w);
  await playRunner;
  assert.deepEqual(job.body.report.snapshot, { sha: NEW, fresh: true });
  assert.deepEqual((proposed(h)[0] as { entry: Record<string, unknown> }).entry.anchors, [
    { type: 'path', path: 'src/new.go' },
    { type: 'commit', sha: NEW },
  ], 'what the fresh snapshot holds, and nothing the old one held that origin/main no longer has');

  // The runner is away: the job does not wait for it, and holds the anchors to the snapshot the space holds.
  await h.sql.query(`UPDATE "runner" SET "last_heartbeat_at" = now() - interval '1 hour' WHERE "id" = $1`, [who.runnerId]);
  const two = await note(h, who, 'memory/feedback-2.md', 'src/new.go again.');
  h.model.answer = scripted({ 'memory/feedback-2.md': `[{"kind":"concept","title":"Again","summary":"s","definition":"d","boundaries":"b","anchors":{"paths":["src/new.go"],"commits":["${NEW}"]}}]` });
  h.proposals.length = 0;
  const away = await drive(h, who, await makeJob(h, who, [{ noteId: two.id, file: 'memory/feedback-2.md', date }]), w);
  assert.deepEqual(away.body.report.snapshot, { sha: NEW, fresh: false });
  assert.deepEqual((proposed(h)[0] as { entry: Record<string, unknown> }).entry.anchors, [{ type: 'path', path: 'src/new.go' }, { type: 'commit', sha: NEW }]);

  // A space that holds no snapshot at all: no anchors, rather than unchecked ones.
  await h.prisma.wikiRepoSnapshot.deleteMany({ where: { spaceId: who.spaceId } });
  const three = await note(h, who, 'memory/feedback-3.md', 'src/new.go once more.');
  h.model.answer = scripted({ 'memory/feedback-3.md': `[{"kind":"concept","title":"Once more","summary":"s","definition":"d","boundaries":"b","anchors":{"paths":["src/new.go"],"commits":["${NEW}"]}}]` });
  h.proposals.length = 0;
  const none = await drive(h, who, await makeJob(h, who, [{ noteId: three.id, file: 'memory/feedback-3.md', date }]), w);
  assert.equal(none.body.report.snapshot, null);
  assert.equal((proposed(h)[0] as { entry: Record<string, unknown> }).entry.anchors, undefined);
});

// ── 11. a worker that dies ───────────────────────────────────────────────────────────────────────────

test('a worker that dies mid-import: the next one finishes it, asking nothing twice and proposing once', { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const one = await note(h, who, 'memory/feedback-1.md', 'fact one');
  const two = await note(h, who, 'memory/feedback-2.md', 'fact two');
  h.model.answer = scripted({ 'memory/feedback-1.md': manyEntries('One', 1), 'memory/feedback-2.md': manyEntries('Two', 1) });
  const w = worker(h);
  const id = await makeJob(h, who, [
    { noteId: one.id, file: 'memory/feedback-1.md', date },
    { noteId: two.id, file: 'memory/feedback-2.md', date },
  ], { concurrency: 1 });
  // The first worker reads the first note, and is stopped while the second read waits in the queue.
  await w.executor.runOnce();
  await waitFor(async () => (await h.prisma.wikiModelRequest.count({ where: { jobId: id } })) === 1, 'the first read is queued');
  await w.queue.runOnce();
  await waitFor(async () => (await h.prisma.wikiModelRequest.count({ where: { jobId: id, state: 'succeeded' } })) === 1, 'the first read answered');
  await waitFor(async () => (await h.prisma.wikiModelRequest.count({ where: { jobId: id } })) === 2, 'the second read is queued');
  await w.executor.onModuleDestroy();
  await w.queue.onModuleDestroy();
  assert.equal(h.model.hits.length, 1);
  assert.equal(h.proposals.length, 0);
  // The next worker takes the job over and finishes it from the answer it already has.
  const job = await drive(h, who, id, worker(h));
  assert.equal(job.body.state, 'succeeded');
  assert.equal(h.model.hits.length, 2, 'the first note was not read again');
  assert.deepEqual(titles(proposed(h)), ['One 1', 'Two 1']);
  assert.equal(await h.prisma.wikiChangeset.count({ where: { spaceId: who.spaceId } }), 1);
});

// ── 12. the door ─────────────────────────────────────────────────────────────────────────────────────

test('the door: which path an import takes, a job made once under its id, the notes the space\'s own, nothing for a runner account', { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const one = await note(h, who, 'memory/feedback-1.md', 'fact one');

  // Which path: the server's, with the System model's name and state; never its address or key.
  const asked = await call(h, who.as, 'GET', `/runner/wiki/spaces/${who.spaceId}/import`);
  expectStatus(asked, 200, 'the command asks which path');
  assert.deepEqual(asked.body, { executor: 'server', model: MODEL, modelState: 'up' });
  assert.ok(!JSON.stringify(asked.body).includes(h.model.base) && !JSON.stringify(asked.body).includes(KEY));

  // The job, made once under the id the command names: the same request again is the same job.
  const id = randomUUID();
  const body = { id, maxOps: 5, notes: [{ noteId: one.id, file: 'memory/feedback-1.md', date }] };
  const made = await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/import-jobs`, body);
  expectStatus(made, 200, 'the job is made');
  assert.equal(toUuid(made.body.id), id);
  assert.equal(made.body.state, 'queued');
  expectStatus(await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/import-jobs`, body), 200, 'sent again');
  const rows = await h.prisma.wikiJob.findMany({ where: { spaceId: who.spaceId, kind: 'import' }, select: { id: true, input: true, priority: true } });
  assert.equal(rows.length, 1, 'one job, however often its request was sent');
  assert.equal(rows[0].priority, WIKI_IMPORT_JOB.priority);
  assert.deepEqual(rows[0].input, {
    sessionId: who.session, maxOps: 5, concurrency: WIKI_IMPORT_JOB.defaultConcurrency, checkoutRoot: '',
    notes: [{ noteId: toUuid(one.id), file: 'memory/feedback-1.md', date }],
  });

  // The body as the contract gives it, every field named that is not; a note of another space is no note of this import.
  const wrong = await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/import-jobs`, {
    id: 'not-an-id', maxOps: 31, concurrency: 9, notes: [{ noteId: one.id, file: '', date: 'yesterday', ops: [{ index: -1, body: [] }] }],
  });
  expectStatus(wrong, 400, 'a body that is not the contract\'s');
  assert.equal(wrong.body.code, 'WIKI_SCHEMA');
  assert.deepEqual(wrong.body.errors.map((e: { path: string }) => e.path).sort(), [
    'concurrency', 'id', 'maxOps', 'notes[0].date', 'notes[0].file', 'notes[0].ops[0].body', 'notes[0].ops[0].index',
  ]);
  const other = await importer(h, 'tiered');
  const theirs = await note(h, other, 'memory/theirs.md', 'not this space');
  const foreign = await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/import-jobs`, {
    id: randomUUID(), maxOps: 5, notes: [{ noteId: theirs.id, file: 'memory/theirs.md', date }],
  });
  expectStatus(foreign, 400, 'another space\'s note');
  assert.deepEqual(foreign.body.errors, [{ path: 'notes[0].noteId', message: 'names no note of this space' }]);

  // Another owner's job is not there; nor is a job read without a session.
  expectStatus(await call(h, other.as, 'GET', `/runner/wiki/spaces/${who.spaceId}/import-jobs/${id}`), 404, 'another owner reads the job');
  expectStatus(await call(h, { runner: who.as.runner }, 'GET', `/runner/wiki/spaces/${who.spaceId}/import-jobs/${id}`), 400, 'no session');
  const read = await readJob(h, who, id);
  expectStatus(read, 200, 'the job is read');
  assert.deepEqual(Object.keys(read.body).filter((key) => !key.endsWith('PublicId') && key !== 'publicId').sort(), [
    'attempts', 'createdAt', 'endedAt', 'error', 'failureKind', 'id', 'model', 'progress', 'report', 'spaceId', 'startedAt', 'state', 'waitingFor',
  ]);

  // An account the runner serves: the command reads with its own model, and the server makes no job for it.
  process.env.ORBIT_WIKI_EXECUTOR = 'runner';
  try {
    const runnerPath = await call(h, who.as, 'GET', `/runner/wiki/spaces/${who.spaceId}/import`);
    expectStatus(runnerPath, 200, 'the command asks under runner');
    assert.equal(runnerPath.body.executor, 'runner');
    expectStatus(await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/import-jobs`, { ...body, id: randomUUID() }), 409, 'no job under runner');
    process.env.ORBIT_WIKI_EXECUTOR = 'canary';
    process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS = other.ownerId;
    assert.equal((await call(h, who.as, 'GET', `/runner/wiki/spaces/${who.spaceId}/import`)).body.executor, 'runner', 'a canary list without this account');
    process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS = `${other.ownerId},${who.ownerId}`;
    assert.equal((await call(h, who.as, 'GET', `/runner/wiki/spaces/${who.spaceId}/import`)).body.executor, 'server', 'the canary account');
  } finally {
    process.env.ORBIT_WIKI_EXECUTOR = 'server';
    delete process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS;
  }
  expectStatus(await call(h, other.as, 'GET', `/runner/wiki/spaces/${who.spaceId}/import`), 404, "another owner's space");
});

// ── 13. the session's own model ─────────────────────────────────────────────────────────────────────

test("when the server reads, no session's model does: the note's text is handed to none, and what one wrote is not taken", { skip, timeout: 90_000 }, async () => {
  const h = await boot();
  await reset(h);
  const who = await importer(h, 'tiered');
  const notesOf = async () => h.prisma.wikiNote.count({ where: { spaceId: who.spaceId } });
  const changesetsOf = async () => h.prisma.wikiChangeset.count({ where: { spaceId: who.spaceId } });
  const op = (noteId: string) => ({
    op: 'add',
    entry: { kind: 'concept', title: 'Written by a session', summary: 's', fields: { definition: 'd', boundaries: 'b' } },
    sources: [{ kind: 'note', ref: noteId }],
  });

  // Server: a registration that does not say the server reads it — an orbit wiki import that predates the
  // server's, which would read the text with the session's own provider — is refused, and nothing is kept.
  const before = await notesOf();
  const old = await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/notes`, { path: 'memory/old.md', text: 'an old runner reads this' });
  expectStatus(old, 409, 'a command that would read the note itself');
  assert.equal(old.body.code, 'WIKI_SERVER_EXECUTES');
  assert.match(old.body.message, /upgrade the runner/u);
  assert.equal(await notesOf(), before, 'nothing was registered');
  // One that says so is registered, and handed no text.
  const kept = await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/notes`, { path: 'memory/new.md', text: 'the server reads this', readBy: 'server' });
  expectStatus(kept, 200, 'a command whose notes the server reads');
  assert.deepEqual(Object.keys(kept.body).filter((key) => !key.endsWith('PublicId') && key !== 'publicId').sort(),
    ['chars', 'contentSha256', 'created', 'id', 'path', 'redacted', 'spaceId']);
  // And entries a session's own model wrote are not taken.
  const proposedBySession = await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/imports`, {
    rationale: 'orbit wiki import: what the local model found', ops: [op(kept.body.id)],
  });
  expectStatus(proposedBySession, 409, "a session's own entries");
  assert.equal(proposedBySession.body.code, 'WIKI_SERVER_EXECUTES');
  assert.equal(await changesetsOf(), 0, 'nothing was proposed');

  // Runner, the default: both routes answer as they always have — the text handed back, the entries taken.
  process.env.ORBIT_WIKI_EXECUTOR = 'runner';
  try {
    const registered = await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/notes`, { path: 'memory/runner.md', text: 'the session reads this' });
    expectStatus(registered, 200, 'a registration under runner');
    assert.equal(registered.body.text, 'the session reads this');
    expectStatus(await call(h, who.as, 'POST', `/runner/wiki/spaces/${who.spaceId}/imports`, {
      rationale: 'orbit wiki import: what the local model found', ops: [op(registered.body.id)],
    }), 200, 'a proposal under runner');
    assert.equal(await changesetsOf(), 1);
  } finally {
    process.env.ORBIT_WIKI_EXECUTOR = 'server';
  }
});

async function waitFor(ok: () => Promise<boolean>, what: string, seconds = 10): Promise<void> {
  const deadline = Date.now() + seconds * 1000;
  for (;;) {
    if (await ok()) return;
    assert.ok(Date.now() < deadline, `${what} within ${seconds}s`);
    await delay(20);
  }
}
