/**
 * The documents built on the server (contracts/wiki.contract.json `docs.build.server`, `jobs.kindRuns.docs_build`;
 * design §8, P7), against a real PostgreSQL, the real doors and wiki services, a System model played by a local
 * Node http server, and the space's runner played here: it claims the job's repository operations as a heartbeat
 * would and answers them from a tree of files at one commit, the way src/runner-go/wiki_repo_ops.go reads a checkout.
 *
 *   1. canary: the owner's confirmation makes a `docs_build` job and no task of the hidden list; the worker reads the
 *      repository at the snapshot's commit through the runner, writes every section through the queue with the
 *      System model, and the plan job says how far it got and how it ended — the plan page's «Writing documents»;
 *   2. the next build: a section whose material did not change is left as it is and nothing is asked of the model for
 *      it — only the section whose definition changed, and the overview over it, are written again;
 *   3. runner mode, and an account the canary does not list: the confirmation makes the build's task, word for word as
 *      it always did, and no job;
 *   4. the runner door: the documents' routes answer a maintenance session as ever under runner, and
 *      WIKI_SERVER_EXECUTES for an account the server runs, before anything is read — so an older runner's
 *      `orbit wiki docs build` asks its session's model nothing;
 *   5. a space whose maintenance names no workspace holds the build, on the server path too; and a build the server
 *      never started is cancelled when the switch goes back to runner, by the next confirmation's request;
 *   6. a worker that stops mid-build: the next one finishes it, asking no call twice and writing each section once;
 *   7. a plan of version 27's shape (2026-10-09): sections of one document that name the same article are built side
 *      by side, and each is shown the article only once its read landed;
 *   8. a session condition whose projects are { id, title } — the read's spelling — is read as ids by every reader on
 *      the way: the plan's reads, the runner door's material and the build's own;
 *  11. a worker that stops while the build waits for its reads lets the job's lease out to now (design §5.4): no
 *      REPO_OP_FAILED, no read asked again — the third read, waiting for a slot, is never asked — and the next worker
 *      takes the job over.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki-worker/wiki-docs-build-job.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every row belongs to an account the run created.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import type { AddressInfo, Socket } from 'node:net';
import { setTimeout as delay } from 'node:timers/promises';
import { after, afterEach, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { toUuid, WIKI_DOCS_BUILD_JOB, WIKI_REPO_OP_CAPABILITY, WIKI_REPO_OP_READ_CAPABILITY, WIKI_REPO_OPS } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiDocsController } from '../runner-api/runner-wiki-docs.controller';
import { RunnerWikiPlanController } from '../runner-api/runner-wiki-plan.controller';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiDocs } from '../wiki/wiki-docs';
import { WikiDocsController } from '../wiki/wiki-docs.controller';
import { WikiPlans } from '../wiki/wiki-plan';
import { WikiPlanController } from '../wiki/wiki-plan.controller';
import { WikiRetrieval } from '../wiki/wiki-retrieval';
import { WikiController } from '../wiki/wiki.controller';
import { WikiService } from '../wiki/wiki.service';
import { wikiDocsBuildJobRunner } from './wiki-docs-build-job';
import { WIKI_DOCS_BUILD_SYSTEM_PROMPT } from './wiki-docs-writer';
import { WikiJobExecutor } from './wiki-job-executor';
import { WikiModelRequestQueue } from './wiki-model-queue.service';
import { WikiModelStatusProbe } from './wiki-model-status';
import { WikiRepoOps, type WikiRepoOpClaim } from './wiki-repo-ops';
import { readWikiSystemModel, type WikiSystemModelConfig } from './wiki-system-model';

const URL_ = process.env.COORDINATOR_PG_URL;
const skip = !URL_;

const KEY = `sk-spec-${randomUUID()}`;
const MODEL = 'qwen3.8-27b-fp8';
const SLUG = 'session-runtime';

// ── the System model ─────────────────────────────────────────────────────────────────────────────────

interface Hit {
  prompt: string;
  system: string;
  body: Record<string, unknown>;
  authorization: string;
}

interface FakeModel {
  base: string;
  hits: Hit[];
  /** Every prompt answered as a writer that cites what it was handed would answer it. */
  answer: (prompt: string) => string;
  close: () => Promise<void>;
}

/**
 * A writer's answer to each of the build's prompts: every piece handed to the merge adopted; every piece the write
 * prompt lists cited in a sentence of its own, with a verbatim quote — the first line of the piece long enough to be
 * one; the overview citing the first footnote it was given.
 */
function writerAnswer(prompt: string): string {
  if (prompt.includes('做「归并」')) {
    const ids = [...prompt.matchAll(/^\[([A-Z]\d+)\] /gmu)].map(([, id]) => id);
    return `${ids.map((id) => `${id} | 采用 | 讲的正是本节`).join('\n')}\n现状：\n- 本节要点 [${ids[0] ?? 'D1'}]\n`;
  }
  if (prompt.includes('（概述，')) return '### 总览\n这篇讲一个会话怎么运转[F1]。\n';
  if (prompt.includes('补逐字引文')) return '';
  if (!prompt.includes('# 任务：写文档')) return '?';
  const materials = prompt.split('## 可用材料（只可引用这些，编号不变）\n')[1]?.split('\n\n## 写法')[0] ?? '';
  const sentences: string[] = [];
  const quotes: string[] = [];
  for (const block of materials.split(/\n(?=\[[A-Z]\d+\] )/u)) {
    const id = /^\[([A-Z]\d+)\] /u.exec(block)?.[1];
    if (!id) continue;
    const line = block.split('\n').slice(1).map((one) => one.trim()).find((one) => one.length >= 10 && !one.startsWith('```'));
    sentences.push(`本节依据 ${id} 写成一句话[${id}]。`);
    if (line) quotes.push(`[${id}] 「${Array.from(line).slice(0, 60).join('')}」`);
  }
  if (sentences.length === 0) return '### 边界\n本篇只讲会话怎么运转。\n';
  return `### 本节\n${sentences.join('')}\n\n引文：\n${quotes.join('\n')}\n`;
}

async function fakeModel(): Promise<FakeModel> {
  const sockets = new Set<Socket>();
  const model = { base: '', hits: [] as Hit[], answer: writerAnswer } as unknown as FakeModel;
  const server = createServer((request: IncomingMessage, response: ServerResponse) => {
    let raw = '';
    request.on('data', (chunk: Buffer) => {
      raw += chunk.toString();
    });
    request.on('end', () => {
      if (request.url === '/health') {
        response.writeHead(200, { 'content-type': 'application/json' });
        response.end('{}');
        return;
      }
      const body = JSON.parse(raw) as { system?: string; messages?: Array<{ content?: string }> };
      const prompt = body.messages?.[0]?.content ?? '';
      model.hits.push({ prompt, system: body.system ?? '', body: body as Record<string, unknown>, authorization: String(request.headers.authorization ?? '') });
      const text = model.answer(prompt);
      response.writeHead(200, { 'content-type': 'text/event-stream' });
      const event = (name: string, data: unknown) => `event: ${name}\ndata: ${JSON.stringify(data)}\n\n`;
      response.write(event('message_start', { type: 'message_start', message: { model: MODEL, usage: { input_tokens: 100, output_tokens: 1 } } }));
      response.write(event('content_block_delta', { type: 'content_block_delta', index: 0, delta: { type: 'text_delta', text } }));
      response.write(event('message_delta', { type: 'message_delta', delta: { stop_reason: 'end_turn' }, usage: { output_tokens: 20 } }));
      response.write(event('message_stop', { type: 'message_stop' }));
      response.end();
    });
  });
  server.on('connection', (socket: Socket) => {
    sockets.add(socket);
    socket.on('close', () => sockets.delete(socket));
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  model.base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  model.close = async () => {
    for (const socket of sockets) socket.destroy();
    await new Promise<void>((resolve) => server.close(() => resolve()));
  };
  return model;
}

// ── the harness ──────────────────────────────────────────────────────────────────────────────────────

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  docs: WikiDocs;
  model: FakeModel;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL_);
    const sql = new Client({ connectionString: URL_, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL_ as string);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined, publishForUser: () => undefined } as unknown as RealtimeService;
    const push = { notifyWikiReviewModeTripped: async () => undefined, notifyWikiVerificationTripped: async () => undefined } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);
    const plans = new WikiPlans(prisma as unknown as PrismaService, hub);
    const docs = new WikiDocs(prisma as unknown as PrismaService, service, hub);

    @Module({
      controllers: [WikiController, WikiPlanController, WikiDocsController, RunnerWikiController, RunnerWikiPlanController, RunnerWikiDocsController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiPlans, useValue: plans },
        { provide: WikiDocs, useValue: docs },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiDocsBuildJobModule {}

    const app = await NestFactory.create(WikiDocsBuildJobModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, docs, model: await fakeModel(), bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql, model } = await harness;
  delete process.env.ORBIT_WIKI_EXECUTOR;
  delete process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS;
  await sql.query('DELETE FROM "wiki_model_status"').catch(() => undefined);
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
  await model.close().catch(() => undefined);
});

/** The executor switch, as the apiserver and the worker read it from the environment at each call. */
function executor(mode: 'runner' | 'canary', owners: string[] = []): void {
  if (mode === 'runner') {
    delete process.env.ORBIT_WIKI_EXECUTOR;
    delete process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS;
    return;
  }
  process.env.ORBIT_WIKI_EXECUTOR = mode;
  process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS = owners.join(',');
}

const live: Array<{ queue: WikiModelRequestQueue; executor: WikiJobExecutor }> = [];
const players: Array<{ stop: () => Promise<void> }> = [];

afterEach(async () => {
  for (const one of live.splice(0)) {
    await one.executor.onModuleDestroy().catch(() => undefined);
    await one.queue.onModuleDestroy().catch(() => undefined);
  }
  for (const player of players.splice(0)) await player.stop();
  executor('runner');
});

function config(h: Harness): WikiSystemModelConfig {
  return readWikiSystemModel({
    ORBIT_WIKI_MODEL_BASE_URL: h.model.base,
    ORBIT_WIKI_MODEL_API_KEY: KEY,
    ORBIT_WIKI_MODEL: MODEL,
    ORBIT_WIKI_MODEL_CONCURRENCY: '4',
  });
}

/** A worker as the wiki-worker module builds one, with fast timings: the docs_build kind in its map. */
function worker(h: Harness): { queue: WikiModelRequestQueue; executor: WikiJobExecutor } {
  const options = { leaseMs: 2_000, renewMs: 300, partialMs: 40, pollMs: 25 };
  const prisma = h.prisma as unknown as PrismaService;
  const probe = new WikiModelStatusProbe(prisma, config(h));
  const queue = new WikiModelRequestQueue(prisma, config(h), probe, undefined, options);
  const runners = {
    docs_build: wikiDocsBuildJobRunner({ prisma, docs: h.docs, wiki: h.service, repoOps: new WikiRepoOps(prisma), model: MODEL, repoWaitMs: 15_000 }),
  };
  const run = new WikiJobExecutor(prisma, queue, options, runners);
  live.push({ queue, executor: run });
  return { queue, executor: run };
}

async function modelUp(h: Harness): Promise<void> {
  await h.sql.query('DELETE FROM "wiki_model_status"');
  await new WikiModelStatusProbe(h.prisma as unknown as PrismaService, config(h)).check();
}

/** Passes of the worker until `ok`. */
async function passes(w: { queue: WikiModelRequestQueue; executor: WikiJobExecutor }, ok: () => Promise<boolean>, what: string, seconds = 60): Promise<void> {
  const deadline = Date.now() + seconds * 1000;
  for (;;) {
    await w.executor.runOnce();
    await w.queue.runOnce();
    if (await ok()) return;
    assert.ok(Date.now() < deadline, `${what} within ${seconds}s`);
    await delay(25);
  }
}

// ── the space's runner ───────────────────────────────────────────────────────────────────────────────

interface Tree {
  sha: string;
  files: Record<string, string>;
}

/** What one `read` item answers, as src/runner-go/wiki_repo_ops.go's wikiRepoOpReadOne answers it: the whole
 *  file up to the file cap (owner 2026-10-08), `too_large` past it, and the bounded window when a limit is
 *  named (what an older control plane asks by). */
function readOne(tree: Tree, item: { path: string; maxChars?: number }): Record<string, unknown> {
  if (!(item.path in tree.files)) return { path: item.path, found: false, chars: 0 };
  const text = tree.files[item.path];
  const size = Buffer.byteLength(text, 'utf8');
  if (size > WIKI_REPO_OPS.wholeFileBytes) return { path: item.path, found: false, reason: 'too_large', size, chars: 0 };
  let out = text;
  if (item.maxChars && item.maxChars > 0) {
    const max = Math.min(item.maxChars, WIKI_REPO_OPS.boundedChars);
    const runes = Array.from(text);
    if (runes.length > max) {
      const marker = '\n…（后略）\n';
      out = runes.slice(0, max - Array.from(marker).length).join('') + marker;
    }
  }
  return { path: item.path, found: true, size, text: out, truncated: out !== text, chars: Array.from(out).length };
}

/**
 * The space's runner: claims what its heartbeat would be handed and answers each operation from the tree — a
 * snapshot as the index of its paths and sizes (or skipped, when the space holds that commit), a read as the text.
 * While `hold.reads` is set, a read it claimed is not answered — a runner whose fetch hangs — until the hold is lifted.
 */
function playRunner(h: Harness, runnerId: string, tree: () => Tree, hold: { reads: boolean } = { reads: false }): { ops: Array<{ kind: string; input: Record<string, unknown> }>; stop: () => Promise<void> } {
  const ops = new WikiRepoOps(h.prisma as unknown as PrismaService);
  const seen: Array<{ kind: string; input: Record<string, unknown> }> = [];
  const held: WikiRepoOpClaim[] = [];
  let running = true;
  const loop = (async () => {
    while (running) {
      const claimed = await ops.dispatch({ runnerId, leaseOwner: randomUUID(), draining: false, capabilities: [WIKI_REPO_OP_CAPABILITY, WIKI_REPO_OP_READ_CAPABILITY] }).catch(() => []);
      for (const op of claimed) seen.push({ kind: op.kind, input: op.input });
      for (const op of [...held.splice(0), ...claimed]) {
        if (op.kind === 'read' && hold.reads) {
          held.push(op);
          continue;
        }
        const at = tree();
        let result: Record<string, unknown>;
        if (op.kind === 'snapshot') {
          const held = await h.prisma.wikiRepoSnapshot.findFirst({ where: { sha: at.sha }, select: { sha: true } });
          result = op.input.skipSha === at.sha && held
            ? { sha: at.sha, skipped: true }
            : { sha: at.sha, index: JSON.stringify({ sha: at.sha, files: Object.entries(at.files).map(([path, text]) => ({ path, size: Buffer.byteLength(text) })), commits: [at.sha] }) };
        } else {
          const items = (op.input.items as Array<{ path: string; maxChars?: number }>) ?? [];
          let chars = 0;
          const answered = items.map((item) => {
            const one = readOne(at, item);
            chars += one.chars as number;
            return one;
          });
          result = { read: { sha: op.input.sha, items: answered, chars } };
        }
        await ops.applyWikiRepoOpResult({
          id: op.id, runnerId,
          body: { claimGeneration: op.claimGeneration, leaseOwner: op.leaseOwner, state: 'succeeded', result },
        });
      }
      await delay(15);
    }
  })();
  const player = { ops: seen, stop: async () => { running = false; await loop; } };
  players.push(player);
  return player;
}

// ── requests ─────────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 1500)}`);
}

// ── the scene ────────────────────────────────────────────────────────────────────────────────────────

/** The repository at the commit the runner reads: a design document, code and a contract. */
const DESIGN = '# Design\n\n## 1. Transport\n\nThe runner polls the server over outbound HTTP; no inbound port is needed.\n\n'
  + '## 2. Delivery\n\nA turn is stored before it is delivered, and delivered at least once.\nDelivery is idempotent on the turn\'s id.\n\n'
  + '## 3. Recovery\n\nSeq stays monotonic across respawn.\n';
const RUNLOOP = 'package main\n\n// runLoop claims work from the server and keeps the heartbeat going.\n// It never opens an inbound port.\n'
  + 'func runLoop() {\n\tfor {\n\t\tclaim()\n\t}\n}\n';
const CONTRACT = '{\n  "name": "session",\n  "delivery": "at least once, idempotent on the turn id"\n}\n';

function tree(sha: string): Tree {
  return { sha, files: { 'docs/design.md': DESIGN, 'src/runloop.go': RUNLOOP, 'contracts/session.contract.json': CONTRACT, 'README.md': 'An app.\n' } };
}

const KEYWORD = 'runner 宿主';
const OWNER_WORDS = 'runner-go 的全量测试要在 runner 宿主上跑，别在引擎的 Bash 里跑。';
const DELIVERY = '交付：在 runner 宿主上跑完整包，清掉会话变量后 0 FAIL。';

interface Scene {
  owner: { id: string; bearer: string };
  runner: { id: string; token: string };
  workspaceId: string;
  spaceId: string;
  listId: string;
  maintainer: Caller;
  projectId: string;
}

async function scene(h: Harness, name: string): Promise<Scene> {
  const ownerId = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [ownerId, `wiki-docs-build-job-${ownerId}@wiki.invalid`, name]);
  const bearer = `bearer-${ownerId}`;
  h.bearers.set(bearer, ownerId);
  const runnerId = randomUUID();
  const token = `runner-${runnerId}`;
  await h.sql.query(
    `INSERT INTO "runner"("id","name","owner_id","token_hash","capabilities","capabilities_reported_at","last_heartbeat_at")
     VALUES ($1,'spec',$2,$3,$4,now(),now())`,
    [runnerId, ownerId, createHash('sha256').update(token).digest('hex'), [WIKI_REPO_OP_CAPABILITY, WIKI_REPO_OP_READ_CAPABILITY]],
  );
  const workspaceId = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env","runner_id","work_dir") VALUES ($1,'spec',$2,'{}',$3,'/tmp/docs-build-spec')`, [
    workspaceId, ownerId, runnerId,
  ]);
  const made = await call(h, { bearer }, 'POST', '/wiki/spaces', { title: `${name} space` });
  expectStatus(made, 201, 'the owner creates a space');
  const spaceId = toUuid(made.body.id as string);
  expectStatus(await call(h, { bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId }), 200, 'the owner binds the workspace');
  const on = await call(h, { bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true, workspaceId } });
  expectStatus(on, 200, 'the owner turns maintenance on');
  const listId = toUuid(on.body.settings.maintenance.listId as string);
  const taskId = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id","completion_criterion","updated_at")
     VALUES ($1,'Wiki maintenance run',$2,'USER',$2,'DONE'::task_status,$3,$4,'OWNER_CONFIRMED',now())`,
    [taskId, ownerId, workspaceId, listId],
  );
  const maintenanceSession = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id","task_id","status","dispatch_origin","updated_at")
     VALUES ($1,'Wiki maintenance run','p',$2,$2,$3,$4,$5,'RUNNING'::run_status,'USER',now())`,
    [maintenanceSession, ownerId, workspaceId, runnerId, taskId],
  );
  // A project whose coordinator heard the owner's words, and whose task carries a delivery comment.
  const coordinator = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id","status","dispatch_origin","updated_at")
     VALUES ($1,'the coordinator','p',$2,$2,$3,$4,'RUNNING'::run_status,'USER',now())`,
    [coordinator, ownerId, workspaceId, runnerId],
  );
  const projectId = randomUUID();
  await h.sql.query(`INSERT INTO "project"("id","title","owner_id","coordinator_session_id","updated_at") VALUES ($1,'Runner 托管后台作业',$2,$3,now())`, [projectId, ownerId, coordinator]);
  await h.sql.query(
    `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status","kind","send_intent","created_at")
     VALUES ($1,$2,1,$3,$4,'ANSWERED','message','NEXT_TURN','2026-09-20T10:00:00Z')`,
    [randomUUID(), coordinator, randomUUID(), OWNER_WORDS],
  );
  const projectTask = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","project_id","completion_criterion","updated_at")
     VALUES ($1,'整包测试在宿主上跑',$2,'USER',$2,'OPEN'::task_status,$3,$4,'OWNER_CONFIRMED',now())`,
    [projectTask, ownerId, workspaceId, projectId],
  );
  await h.sql.query(`INSERT INTO "task_comment"("id","task_id","author_type","author_id","body","created_at") VALUES ($1,$2,'AGENT'::creator_type,$3,$4,'2026-09-22T10:00:00Z')`, [
    randomUUID(), projectTask, ownerId, DELIVERY,
  ]);
  return {
    owner: { id: ownerId, bearer }, runner: { id: runnerId, token }, workspaceId, spaceId, listId,
    maintainer: { runner: token, session: maintenanceSession }, projectId,
  };
}

/** One document: an overview, a mechanism read from the repository, and conventions read from the records. */
function planFor(s: Scene): Record<string, unknown> {
  return {
    categories: [{ key: 'dev', title: 'Development', question: 'How it works', forAgents: true }],
    docs: [{
      category: 'dev',
      slug: SLUG,
      title: '会话运行模型',
      question: '一个会话怎么运转？',
      audience: ['新加入的开发者'],
      scopeIn: ['一轮怎么投递'],
      scopeOut: [],
      length: { min: 800, max: 4000 },
      sections: [
        { title: '总览', kind: 'overview', covers: '这篇讲一个会话怎么运转。', length: 300, sources: {} },
        {
          title: 'turn 怎么投递', kind: 'flow', covers: '一轮 turn 从落库到投递。', length: 400,
          sources: {
            docs: [{ path: 'docs/design.md', section: '2. Delivery' }],
            code: [{ path: 'src/runloop.go', symbols: ['runLoop'] }],
            contracts: [{ path: 'contracts/session.contract.json' }],
          },
        },
        {
          title: '约定', kind: 'conventions', covers: '跑测试的约定。', length: 400,
          sources: {
            sessions: {
              projects: [s.projectId], since: '2026-09-01', until: '2026-09-30', keywords: [KEYWORD], anchorPaths: [],
              entryKinds: ['convention'], topics: [], evidence: 'where the suite runs',
            },
          },
        },
      ],
    }],
  };
}

/**
 * The space's first draft, stored by a maintenance run as a plan job's run stores one — under the runner switch,
 * whatever the test's: drafting is the plan's pipeline, not the documents'.
 */
async function draft(h: Harness, s: Scene, plan: Record<string, unknown>): Promise<number> {
  const mode = process.env.ORBIT_WIKI_EXECUTOR;
  const owners = process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS;
  executor('runner');
  try {
    const drafted = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/drafts`, {
      baseVersion: null, target: { min: 1, max: 10 }, plan, repoCheck: { sha: 'a'.repeat(40), checked: 3, missing: [] }, model: MODEL,
    });
    expectStatus(drafted, 200, 'the maintenance run drafts the plan');
    return drafted.body.version as number;
  } finally {
    if (mode === undefined) delete process.env.ORBIT_WIKI_EXECUTOR;
    else process.env.ORBIT_WIKI_EXECUTOR = mode;
    if (owners === undefined) delete process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS;
    else process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS = owners;
  }
}

/** The owner's edit of the overview's covers: a new draft on the newest version. */
async function editOverview(h: Harness, s: Scene, base: number, covers: string): Promise<number> {
  const plan = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/plan`);
  const doc = (plan.body.draft ?? plan.body.confirmed).docs.find((d: { slug: string }) => d.slug === SLUG);
  const section = doc.sections.find((one: { kind: string }) => one.kind === 'overview');
  const edited = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/plan/edits`, {
    baseVersion: base,
    docSlug: SLUG,
    sectionKey: section.key,
    section: { key: section.key, title: section.title, kind: 'overview', covers, length: section.length, sources: {} },
  });
  expectStatus(edited, 200, 'the owner edits the overview');
  return edited.body.version as number;
}

async function confirm(h: Harness, s: Scene, version: number): Promise<void> {
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/plan/versions/${version}/confirm`), 200, `the owner confirms version ${version}`);
}

interface BuildRow {
  id: string;
  state: string;
  version: number | null;
  task_id: string | null;
  job_id: string | null;
  outcome: string | null;
  error: string | null;
  report: Record<string, unknown> | null;
  progress: Record<string, unknown> | null;
}

async function builds(h: Harness, spaceId: string): Promise<BuildRow[]> {
  return (await h.sql.query<BuildRow>(
    `SELECT "id","state","version","task_id","job_id","outcome","error","report","progress" FROM "wiki_plan_job"
      WHERE "space_id" = $1 AND "kind" = 'build' ORDER BY "created_at","id"`,
    [spaceId],
  )).rows;
}

interface JobRow {
  id: string;
  kind: string;
  priority: number;
  state: string;
  input: Record<string, unknown>;
  report: Record<string, unknown> | null;
  error: string | null;
}

async function job(h: Harness, id: string): Promise<JobRow> {
  return (await h.sql.query<JobRow>('SELECT "id","kind","priority","state","input","report","error" FROM "wiki_job" WHERE "id" = $1', [id])).rows[0];
}

async function buildTasks(h: Harness, s: Scene): Promise<number> {
  return (await h.sql.query<{ n: number }>(`SELECT count(*)::int AS n FROM "task" WHERE "list_id" = $1 AND "title" LIKE 'Wiki documents:%'`, [s.listId])).rows[0].n;
}

async function runToEnd(h: Harness, w: { queue: WikiModelRequestQueue; executor: WikiJobExecutor }, jobId: string): Promise<JobRow> {
  await passes(w, async () => ['succeeded', 'failed', 'cancelled'].includes((await job(h, jobId)).state), `the build ${jobId} to end`);
  await w.executor.whenIdle();
  return job(h, jobId);
}

// ── 1 and 2. canary: two builds ──────────────────────────────────────────────────────────────────────

test('canary: the confirmation makes a docs_build job and no task; the worker builds every section with the System model, and the next build leaves what did not change', { skip, timeout: 180_000 }, async () => {
  const h = await boot();
  await modelUp(h);
  h.model.hits.length = 0;
  const s = await scene(h, 'canary');
  const v1 = await draft(h, s, planFor(s));
  executor('canary', [s.owner.id]);
  await confirm(h, s, v1);

  // The build is the worker's: a job of the documents' kind, owner-initiated, naming its plan job — and no task.
  const [first] = await builds(h, s.spaceId);
  assert.deepEqual([first.state, first.version, first.task_id], ['made', v1, null]);
  assert.ok(first.job_id, 'the plan job is made by a wiki job');
  const made = await job(h, first.job_id!);
  assert.deepEqual([made.kind, made.priority, made.state, made.input], [WIKI_DOCS_BUILD_JOB.kind, WIKI_DOCS_BUILD_JOB.priority, 'queued', { planJobId: first.id }]);
  assert.equal(await buildTasks(h, s), 0, 'no task of the hidden list was made for the build');
  const page = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/plan`);
  assert.deepEqual([page.body.job.kind, page.body.job.state, page.body.job.taskId, page.body.job.provider], ['build', 'running', null, null],
    'the plan page reads the build as writing the documents');

  const HEAD = createHash('sha1').update(`head-${randomUUID()}`).digest('hex');
  const runner = playRunner(h, s.runner.id, () => tree(HEAD));
  const w = worker(h);
  const ended = await runToEnd(h, w, made.id);
  assert.equal(ended.state, 'succeeded', JSON.stringify(ended));
  const report = ended.report as Record<string, unknown>;
  assert.deepEqual([report.kind, report.planJobId, report.planVersion, report.repoSha, report.written, report.unchanged, report.failed],
    ['docs_build', first.id, v1, HEAD, 3, 0, 0]);

  // The plan job ended as a session's run would have said it: succeeded, the version written, its report.
  const [built] = await builds(h, s.spaceId);
  assert.deepEqual([built.state, built.outcome, built.version], ['ended', 'succeeded', v1]);
  assert.deepEqual(built.progress, { docs: { done: 1, total: 1 }, current: null });
  assert.deepEqual(built.report, {
    planVersion: v1, repoSha: HEAD, docs: { total: 1, written: 1 }, sections: { written: 3, unchanged: 0, failed: 0 },
    tokens: (built.report as { tokens: unknown }).tokens, seconds: (built.report as { seconds: unknown }).seconds, model: MODEL,
  });

  // The repository was read through the runner at the snapshot's commit: one snapshot, and reads of the files named.
  assert.equal(runner.ops[0]?.kind, 'snapshot');
  const read = runner.ops.filter((op) => op.kind === 'read').flatMap((op) => (op.input.items as Array<{ path: string }>).map((item) => item.path));
  assert.deepEqual([...read].sort(), ['contracts/session.contract.json', 'docs/design.md', 'src/runloop.go'], 'the files the sections name, each once');
  for (const op of runner.ops.filter((one) => one.kind === 'read')) assert.equal(op.input.sha, HEAD);

  // Every call went through the queue to the System model, as the documents' writer: its system prompt, its
  // max_tokens, one user message, no tools and no thinking, the deployment's key.
  const firstHits = h.model.hits.length;
  assert.ok(firstHits >= 5, `${firstHits} calls`);
  for (const hit of h.model.hits) {
    assert.equal(hit.system, WIKI_DOCS_BUILD_SYSTEM_PROMPT);
    assert.deepEqual(Object.keys(hit.body).sort(), ['max_tokens', 'messages', 'model', 'stream', 'system']);
    assert.equal(hit.body.max_tokens, WIKI_DOCS_BUILD_JOB.maxTokens);
    assert.equal(hit.authorization, `Bearer ${KEY}`);
  }
  const requests = (await h.sql.query<{ step: string; state: string; n: number }>(
    'SELECT "step","state",count(*)::int AS n FROM "wiki_model_request" WHERE "job_id" = $1 GROUP BY 1,2 ORDER BY 1,2', [made.id])).rows;
  assert.ok(requests.every((row) => row.state === 'succeeded' && row.step.startsWith('docs_')), JSON.stringify(requests));
  assert.equal(requests.reduce((sum, row) => sum + row.n, 0), firstHits, 'one request a call');

  // What was written: every section at the commit read, a repository quote found in its file there.
  const written = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/${SLUG}`);
  expectStatus(written, 200, 'the owner reads the document');
  assert.deepEqual(written.body.sections.map((section: { written: boolean; repoSha: string }) => [section.written, section.repoSha]),
    [[true, HEAD], [true, HEAD], [true, HEAD]]);
  const repoNotes = written.body.footnotes.filter((note: { path: string | null }) => note.path !== null);
  assert.ok(repoNotes.length >= 3 && repoNotes.every((note: { sha: string; verdict: string }) => note.sha === HEAD && note.verdict === 'verified'),
    JSON.stringify(repoNotes.map((note: { path: string; verdict: string }) => [note.path, note.verdict])));
  assert.ok(written.body.footnotes.some((note: { kind: string }) => note.kind === 'turn'), 'the conventions cite the owner\'s words');

  // 2. The owner edits the overview's covers and confirms: the next build leaves the two sections whose material
  // did not change as they are — nothing asked of the model for them — and writes the overview again.
  const v2 = await editOverview(h, s, v1, '这篇讲一个会话怎么运转，第二稿。');
  await confirm(h, s, v2);
  const second = (await builds(h, s.spaceId)).find((row) => row.version === v2 && row.state === 'made');
  assert.ok(second?.job_id, 'the second confirmation made a second build job');
  const again = await runToEnd(h, w, second!.job_id!);
  assert.equal(again.state, 'succeeded', JSON.stringify(again));
  const sections = ((again.report as { docs: Array<{ sections: Array<{ key: string; outcome: string; calls: number }> }> }).docs[0].sections);
  assert.deepEqual(sections.map((section) => [section.outcome, section.calls]), [['written', 1], ['unchanged', 0], ['unchanged', 0]],
    'the overview written again from one call; the sections whose material did not change left as they are');
  assert.deepEqual([(again.report as Record<string, unknown>).written, (again.report as Record<string, unknown>).unchanged], [1, 2]);
  assert.equal(h.model.hits.length - firstHits, 1, 'one call in all: the overview\'s');
  assert.ok(h.model.hits.slice(firstHits).every((hit) => hit.prompt.includes('（概述，')));
  const [, secondRow] = await builds(h, s.spaceId);
  assert.deepEqual([secondRow.state, secondRow.outcome, secondRow.version, (secondRow.report as { sections: unknown }).sections],
    ['ended', 'succeeded', v2, { written: 1, unchanged: 2, failed: 0 }]);
  // The snapshot was not sent again: the space already held that commit.
  assert.deepEqual(runner.ops.filter((op) => op.kind === 'snapshot').map((op) => op.input.skipSha), [null, HEAD]);
});

// ── 3. runner mode, and an account the canary does not list ──────────────────────────────────────────

test('under runner, and for an account the canary does not list, the confirmation makes the build\'s task as it always did, and no job', { skip, timeout: 60_000 }, async () => {
  const h = await boot();
  for (const mode of ['runner', 'canary-unlisted'] as const) {
    const s = await scene(h, mode);
    const version = await draft(h, s, planFor(s));
    executor(mode === 'runner' ? 'runner' : 'canary', [randomUUID()]);
    await confirm(h, s, version);
    // The runner path's own check ran — the space names a provider no run could start on, which the server path
    // does not ask about — and the server was asked for nothing. (The task it makes once the provider is usable is
    // wiki-maintenance.pg.spec.ts's.)
    const [row] = await builds(h, s.spaceId);
    assert.deepEqual([row.state, row.job_id], ['held', null], `${mode}: the build waits on the runner path`);
    const reason = (await h.sql.query<{ held_reason: string }>('SELECT "held_reason" FROM "wiki_plan_job" WHERE "id" = $1', [row.id])).rows[0].held_reason;
    assert.equal(reason, 'maintenance_provider_unusable', `${mode}: held for the provider`);
    const jobs = (await h.sql.query<{ n: number }>('SELECT count(*)::int AS n FROM "wiki_job" WHERE "space_id" = $1', [s.spaceId])).rows[0].n;
    assert.equal(jobs, 0, `${mode}: no wiki job`);
  }
});

// ── 4. the runner door ───────────────────────────────────────────────────────────────────────────────

test('the documents\' runner door: a maintenance session reads as ever under runner, and is refused WIKI_SERVER_EXECUTES for an account the server runs', { skip, timeout: 60_000 }, async () => {
  const h = await boot();
  const s = await scene(h, 'door');
  const version = await draft(h, s, planFor(s));
  await confirm(h, s, version);
  const state = await call(h, s.maintainer, 'GET', `/runner/wiki/spaces/${s.spaceId}/plan`);
  const key = state.body.confirmed.docs[0].sections[2].key as string;
  const routes: Array<[string, string, unknown?]> = [
    ['GET', `/runner/wiki/spaces/${s.spaceId}/docs`],
    ['GET', `/runner/wiki/spaces/${s.spaceId}/docs/${SLUG}/material?section=${key}`],
    ['GET', `/runner/wiki/spaces/${s.spaceId}/maintenance/docs`],
    ['POST', `/runner/wiki/spaces/${s.spaceId}/docs/${SLUG}`, { planVersion: version, repoSha: 'a'.repeat(40), sections: [] }],
  ];
  // Under the default runner: answered as ever (the empty write is the schema's refusal, not the switch's).
  executor('runner');
  for (const [method, route, body] of routes) {
    const answer = await call(h, s.maintainer, method, route, body);
    assert.notEqual(answer.body?.code, 'WIKI_SERVER_EXECUTES', `${method} ${route} under runner: ${JSON.stringify(answer.body).slice(0, 300)}`);
    assert.ok(answer.status === 200 || answer.body?.code === 'WIKI_DOC_INVALID', `${method} ${route} under runner answered ${answer.status}`);
  }
  // For an account the server runs: refused before anything is read, so an older runner's command asks no model.
  executor('canary', [s.owner.id]);
  for (const [method, route, body] of routes) {
    const answer = await call(h, s.maintainer, method, route, body);
    expectStatus(answer, 409, `${method} ${route} for a canary account`);
    assert.equal(answer.body.code, 'WIKI_SERVER_EXECUTES');
    assert.match(answer.body.message, /Nothing was read or written/u);
  }
  // Another session of the owner is still not a maintenance run, whatever the switch says.
  const ordinary = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id","status","dispatch_origin","updated_at")
     VALUES ($1,'an ordinary session','p',$2,$2,$3,$4,'RUNNING'::run_status,'USER',now())`,
    [ordinary, s.owner.id, s.workspaceId, s.runner.id],
  );
  const other = await call(h, { runner: s.runner.token, session: ordinary }, 'GET', `/runner/wiki/spaces/${s.spaceId}/docs`);
  assert.equal(other.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
});

// ── 5. held, and cancelled by the switch going back ──────────────────────────────────────────────────

test('a space whose maintenance names no workspace holds the build on the server path too; a build the server never started is cancelled when the switch goes back to runner', { skip, timeout: 60_000 }, async () => {
  const h = await boot();
  const s = await scene(h, 'held');
  const v1 = await draft(h, s, planFor(s));
  executor('canary', [s.owner.id]);
  await h.sql.query(`UPDATE "wiki_space" SET "settings" = jsonb_set("settings", '{maintenance,workspaceId}', 'null') WHERE "id" = $1`, [s.spaceId]);
  await confirm(h, s, v1);
  let [row] = await builds(h, s.spaceId);
  assert.deepEqual([row.state, row.job_id], ['held', null]);
  // The owner names the workspace again: the next request makes it on the server.
  await h.sql.query(`UPDATE "wiki_space" SET "settings" = jsonb_set("settings", '{maintenance,workspaceId}', to_jsonb($2::text)) WHERE "id" = $1`, [s.spaceId, s.workspaceId]);
  const v2 = await editOverview(h, s, v1, '第二稿。');
  await confirm(h, s, v2);
  [row] = await builds(h, s.spaceId);
  assert.deepEqual([row.state, row.version, row.task_id !== null, row.job_id !== null], ['made', v2, false, true]);
  // The switch goes back to runner before any worker took the job: the next confirmation ends it — its job
  // cancelled — and makes its own build the runner's way.
  executor('runner');
  const v3 = await editOverview(h, s, v2, '第三稿。');
  await confirm(h, s, v3);
  const rows = await builds(h, s.spaceId);
  assert.deepEqual([rows[0].state, rows[0].outcome], ['ended', 'failed']);
  assert.match(rows[0].error ?? '', /no longer executes this account's wiki/u);
  assert.equal((await job(h, row.job_id!)).state, 'cancelled');
  assert.equal(rows[1].job_id, null, 'the new build is the runner\'s');
});

// ── 6. a worker that stops mid-build ─────────────────────────────────────────────────────────────────

test('a worker that stops mid-build: the next one finishes it, asking again only what was in flight and writing each section once', { skip, timeout: 180_000 }, async () => {
  const h = await boot();
  await modelUp(h);
  h.model.hits.length = 0;
  const s = await scene(h, 'restart');
  const v1 = await draft(h, s, planFor(s));
  executor('canary', [s.owner.id]);
  await confirm(h, s, v1);
  const [row] = await builds(h, s.spaceId);
  const HEAD = createHash('sha1').update(`head-${randomUUID()}`).digest('hex');
  playRunner(h, s.runner.id, () => tree(HEAD));
  const first = worker(h);
  // Run until a section is written, then stop the worker as SIGTERM would.
  await passes(first, async () => {
    const { rows } = await h.sql.query<{ n: number }>(
      `SELECT count(*)::int AS n FROM "wiki_doc_section" x JOIN "wiki_doc" d ON d."id" = x."doc_id" WHERE d."space_id" = $1`, [s.spaceId]);
    return rows[0].n >= 1;
  }, 'a first section written');
  await first.executor.onModuleDestroy();
  await first.queue.onModuleDestroy();
  const asked = h.model.hits.length;
  const second = worker(h);
  const ended = await runToEnd(h, second, row.job_id!);
  assert.equal(ended.state, 'succeeded', JSON.stringify(ended));
  // A call answered before the stop is not asked again: its row answers the replay. One the stop cut off is asked
  // again (design §5.4) — at most the job's calls in flight.
  const counts = new Map<string, number>();
  for (const hit of h.model.hits) counts.set(hit.prompt, (counts.get(hit.prompt) ?? 0) + 1);
  const repeated = [...counts.values()].filter((n) => n > 1).length;
  assert.ok(repeated <= 4, `${repeated} calls asked twice (${asked} before the stop, ${h.model.hits.length} in all)`);
  const rows = (await h.sql.query<{ state: string; n: number }>(
    'SELECT "state",count(*)::int AS n FROM "wiki_model_request" WHERE "job_id" = $1 GROUP BY 1', [row.job_id])).rows;
  assert.deepEqual(rows, [{ state: 'succeeded', n: counts.size }], 'one request a call, each answered once and reused');
  const report = ended.report as { written: number; unchanged: number; failed: number };
  assert.equal(report.failed, 0);
  assert.equal(report.written + report.unchanged, 3, 'every section written once: what the first worker wrote is unchanged for the second');
  const versions = (await h.sql.query<{ n: number }>(
    `SELECT count(*)::int AS n FROM "wiki_doc_section" x JOIN "wiki_doc" d ON d."id" = x."doc_id" WHERE d."space_id" = $1`, [s.spaceId])).rows[0].n;
  assert.equal(versions, 3);
});

// ── 7. the CHECK the server's maker needed (0405) ────────────────────────────────────────────────────

test('a made plan job names one maker — its task, or its wiki job — and made_at with it (0405 over 0338 and 0401)', { skip, timeout: 60_000 }, async () => {
  const h = await boot();
  const s = await scene(h, 'checks');
  const wikiJob = randomUUID();
  await h.sql.query(`INSERT INTO "wiki_job"("id","owner_id","space_id","kind","state") VALUES ($1,$2,$3,'docs_build','queued')`, [wikiJob, s.owner.id, s.spaceId]);
  const insert = (values: string, params: unknown[]) => h.sql.query(
    `INSERT INTO "wiki_plan_job"("id","space_id","owner_id","kind","trigger","state","version","task_id","job_id","made_at")
     VALUES ($1,$2,$3,'build','owner',${values})`,
    [randomUUID(), s.spaceId, s.owner.id, ...params],
  ).then(() => null, (e: Error) => e);
  // Made by its wiki job alone: taken.
  assert.equal(await insert(`'made',1,NULL,$4::uuid,now()`, [wikiJob]), null);
  // Made by nothing, made without its time, or made by both: refused.
  const none = await insert(`'made',1,NULL,NULL,now()`, []);
  assert.match(none?.message ?? '', /wiki_plan_job_made_chk/u);
  const untimed = await insert(`'made',1,NULL,$4::uuid,NULL`, [wikiJob]);
  assert.match(untimed?.message ?? '', /wiki_plan_job_made_chk/u);
  const both = await insert(`'made',1,$4::uuid,$5::uuid,now()`, [randomUUID(), wikiJob]);
  assert.match(both?.message ?? '', /wiki_plan_job_maker_chk/u);
});

// ── 7 and 8. version 27 (2026-10-09) ──────────────────────────────────────────────────────────────────

const ARTICLE = 'docs/article-durable-agent-work.md';
const ARTICLE_TEXT = '# Durable agent work\n\n## 1. Turns outlive runners\n\nA turn is stored before it is delivered, so it outlives the runner that ran it.\n\n'
  + '## 2. Where the suite runs\n\nThe full suite runs on the runner host, never in the engine\'s Bash.\n';

function treeWithArticle(sha: string): Tree {
  return { sha, files: { ...tree(sha).files, [ARTICLE]: ARTICLE_TEXT } };
}

/** Version 27's shape: the mechanism and the conventions of one document both name the same article. */
function articlePlanFor(s: Scene): Record<string, unknown> {
  const plan = planFor(s) as { docs: Array<{ sections: Array<{ sources: { docs?: unknown[] } }> }> };
  const [, flow, conventions] = plan.docs[0].sections;
  flow.sources.docs = [...(flow.sources.docs ?? []), { path: ARTICLE, section: '1. Turns outlive runners' }];
  conventions.sources.docs = [{ path: ARTICLE, section: '2. Where the suite runs' }];
  return plan;
}

/** Passes until the build ends — or until an attempt of it failed and went back to the queue, which is as far as it gets. */
async function buildEnd(h: Harness, w: { queue: WikiModelRequestQueue; executor: WikiJobExecutor }, jobId: string): Promise<JobRow> {
  await passes(w, async () => {
    const row = await job(h, jobId);
    return ['succeeded', 'failed', 'cancelled'].includes(row.state) || row.error !== null;
  }, `the build ${jobId} to end`);
  await w.executor.whenIdle();
  return job(h, jobId);
}

test('a plan of version 27\'s shape builds: sections that name one article each wait for its read (2026-10-09, «was shown before it was read»)', { skip, timeout: 180_000 }, async () => {
  const h = await boot();
  await modelUp(h);
  const s = await scene(h, 'v27');
  const version = await draft(h, s, articlePlanFor(s));
  executor('canary', [s.owner.id]);
  await confirm(h, s, version);
  const [row] = await builds(h, s.spaceId);
  const HEAD = createHash('sha1').update(`head-${randomUUID()}`).digest('hex');
  const runner = playRunner(h, s.runner.id, () => treeWithArticle(HEAD));
  const ended = await buildEnd(h, worker(h), row.job_id!);
  assert.equal(ended.state, 'succeeded', JSON.stringify(ended));
  assert.deepEqual([ended.report?.written, ended.report?.failed], [3, 0]);
  // The article was read once, for both sections that name it.
  const read = runner.ops.filter((op) => op.kind === 'read').flatMap((op) => (op.input.items as Array<{ path: string }>).map((item) => item.path));
  assert.equal(read.filter((path) => path === ARTICLE).length, 1, JSON.stringify(read));
  // Both sections cite it, found in the file at the commit read.
  const written = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/${SLUG}`);
  expectStatus(written, 200, 'the owner reads the document');
  const cited = written.body.footnotes.filter((note: { path: string | null }) => note.path === ARTICLE);
  assert.ok(cited.length >= 2 && cited.every((note: { sha: string; verdict: string }) => note.sha === HEAD && note.verdict === 'verified'),
    JSON.stringify(cited.map((note: { section: string; verdict: string }) => [note.section, note.verdict])));
  const [built] = await builds(h, s.spaceId);
  assert.deepEqual([built.state, built.outcome, built.version], ['ended', 'succeeded', version]);
});

/**
 * A version's session conditions with their projects spelled as a read of the plan spells them, { id, title }. The plan's
 * writer stores the id each project resolved to, but that is the spelling the production plan was reported in, and the
 * one the maintenance run's documents step was handed: stored that way, every reader must still take the id.
 */
async function nameProjects(h: Harness, s: Scene, version: number): Promise<void> {
  const updated = await h.sql.query(
    `UPDATE "wiki_plan_section" x SET "sources" = jsonb_set(x."sources", '{sessions,projects}', $2::jsonb)
       FROM "wiki_plan_doc" d, "wiki_plan" p
      WHERE x."doc_id" = d."id" AND d."plan_id" = p."id" AND p."space_id" = $1 AND p."version" = $3
        AND jsonb_typeof(x."sources"->'sessions') = 'object'`,
    [s.spaceId, JSON.stringify([{ id: s.projectId, title: 'Runner 托管后台作业' }]), version],
  );
  assert.equal(updated.rowCount, 1, 'the conventions section is the one with a session condition');
}

test('a session condition whose projects are { id, title } is read as ids: the plan\'s reads, the runner door\'s material and the build', { skip, timeout: 180_000 }, async () => {
  const h = await boot();
  await modelUp(h);
  const s = await scene(h, 'projects');
  const version = await draft(h, s, planFor(s));
  await nameProjects(h, s, version);
  // The plan's reads: the owner's page, as ever { id, title } with the title as it stands now.
  await confirm(h, s, version);
  const page = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/plan`);
  expectStatus(page, 200, 'the owner reads the plan');
  const conventions = page.body.confirmed.docs[0].sections[2];
  assert.deepEqual(conventions.sources.sessions.projects.map((project: { id: string; title: string }) => [toUuid(project.id), project.title]),
    [[s.projectId, 'Runner 托管后台作业']]);
  // The runner door's material — what the runner path's build reads: the condition's projects found the owner's words.
  const material = await call(h, s.maintainer, 'GET', `/runner/wiki/spaces/${s.spaceId}/docs/${SLUG}/material?section=${conventions.key}`);
  expectStatus(material, 200, 'the runner path reads the conventions\' material');
  assert.deepEqual(material.body.condition.projects.map((project: { id: string }) => toUuid(project.id)), [s.projectId]);
  assert.ok(material.body.records.some((record: { text: string }) => record.text.includes(KEYWORD)), JSON.stringify(material.body.records));
  // The server's build reads the same condition the same way. (The owner's edit carried it as ids — the plan's gate read
  // the stored objects as their ids — so the new version is spelled the read's way again.)
  executor('canary', [s.owner.id]);
  const second = await editOverview(h, s, version, '这篇讲一个会话怎么运转。');
  const carried = await h.sql.query<{ projects: unknown }>(
    `SELECT x."sources"->'sessions'->'projects' AS "projects" FROM "wiki_plan_section" x JOIN "wiki_plan_doc" d ON d."id" = x."doc_id"
       JOIN "wiki_plan" p ON p."id" = d."plan_id" WHERE p."space_id" = $1 AND p."version" = $2 AND jsonb_typeof(x."sources"->'sessions') = 'object'`,
    [s.spaceId, second]);
  assert.deepEqual(carried.rows.map((one) => one.projects), [[s.projectId]]);
  await nameProjects(h, s, second);
  await confirm(h, s, second);
  const row = (await builds(h, s.spaceId)).find((one) => one.version === second && one.state === 'made');
  assert.ok(row?.job_id, 'the confirmation made a build job');
  const HEAD = createHash('sha1').update(`head-${randomUUID()}`).digest('hex');
  playRunner(h, s.runner.id, () => tree(HEAD));
  const ended = await buildEnd(h, worker(h), row!.job_id!);
  assert.equal(ended.state, 'succeeded', JSON.stringify(ended));
  const written = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/${SLUG}`);
  expectStatus(written, 200, 'the owner reads the document');
  assert.ok(written.body.footnotes.some((note: { kind: string }) => note.kind === 'turn'), 'the conventions cite the owner\'s words, found by the project');
});

// ── 9. a file with a raw NUL in it (2026-10-09) ──────────────────────────────────────────────────────

// Built rather than written: a raw NUL in this source is the hazard itself (runner-api/strip-nul.ts).
const NUL = String.fromCharCode(0);
/** The code the flow section names, with a raw NUL in the symbol it names — as three files on main have one. */
const RUNLOOP_WITH_NUL = 'package main\n\n// runLoop claims work from the server and keeps the heartbeat going.\n// It never opens an inbound port.\n'
  + `func runLoop() {\n\tsep := "a${NUL}b"\n\tfor {\n\t\tclaim(sep)\n\t}\n}\n`;

test('a section whose code has a raw NUL in it builds: the model is shown the code byte for byte, the cache keeps the file, the footnote its lines', { skip, timeout: 180_000 }, async () => {
  const h = await boot();
  await modelUp(h);
  const s = await scene(h, 'nul');
  const version = await draft(h, s, planFor(s));
  executor('canary', [s.owner.id]);
  await confirm(h, s, version);
  const [row] = await builds(h, s.spaceId);
  const HEAD = createHash('sha1').update(`head-${randomUUID()}`).digest('hex');
  playRunner(h, s.runner.id, () => ({ sha: HEAD, files: { ...tree(HEAD).files, 'src/runloop.go': RUNLOOP_WITH_NUL } }));
  // A writer that quotes the code with words it does not have: the footnote's excerpt is then the piece's own head —
  // the code, NUL and all — which is what a model that paraphrases leaves a footnote with, and the write must store.
  const asWritten = h.model.answer;
  h.model.answer = (prompt) => asWritten(prompt).replace(/^\[C1\] 「.*」$/mu, '[C1] 「a line the code does not have」');
  h.model.hits.length = 0;
  try {
    const ended = await buildEnd(h, worker(h), row.job_id!);
    assert.equal(ended.state, 'succeeded', JSON.stringify(ended));
    assert.deepEqual([ended.report?.written, ended.report?.failed], [3, 0]);

    // The model was shown the code as the file has it: the NUL line, byte for byte.
    const shown = h.model.hits.filter((hit) => hit.prompt.includes('func runLoop()'));
    assert.ok(shown.length > 0, 'the flow section\'s calls show the code');
    for (const hit of shown) assert.ok(hit.prompt.includes(`\tsep := "a${NUL}b"`), 'the prompt carries the NUL the file has');
    // The calls that carried it were queued as their bytes (decoded here, not in SQL: text cannot hold what they
    // decode to), and the file is cached as its bytes.
    const requests = (await h.sql.query<{ request: { prompt: string; encoding?: string } }>(
      'SELECT "request" FROM "wiki_model_request" WHERE "job_id" = $1', [row.job_id])).rows;
    const carrying = requests.filter(({ request }) =>
      (request.encoding === 'base64' ? Buffer.from(request.prompt, 'base64').toString('utf8') : request.prompt).includes('func runLoop()'));
    assert.ok(carrying.length > 0, 'the calls that show the code are in the queue');
    assert.deepEqual([...new Set(carrying.map(({ request }) => request.encoding))], ['base64'], 'each kept as its bytes, beside `encoding`');
    const { rows: [cached] } = await h.sql.query<{ content: string; content_encoding: string }>(
      'SELECT "content", "content_encoding" FROM "wiki_repo_file" WHERE "space_id" = $1 AND "sha" = $2 AND "path" = $3', [s.spaceId, HEAD, 'src/runloop.go']);
    assert.equal(cached.content_encoding, 'base64');
    assert.ok(Buffer.from(cached.content, 'base64').equals(Buffer.from(RUNLOOP_WITH_NUL, 'utf8')), 'the cache holds the file byte for byte');

    // The footnote that cites the code keeps the lines it was taken from, without the NUL text cannot hold.
    const { rows: notes } = await h.sql.query<{ excerpt: string | null; quote: string | null; verdict: string }>(
      `SELECT f."excerpt", f."quote", f."verdict" FROM "wiki_doc_footnote" f
         JOIN "wiki_doc_sentence" t ON t."id" = f."sentence_id" JOIN "wiki_doc_section" x ON x."id" = t."section_id"
         JOIN "wiki_doc" d ON d."id" = x."doc_id" WHERE d."space_id" = $1 AND f."ref" = 'src/runloop.go'`, [s.spaceId]);
    assert.ok(notes.length >= 1, 'the code is cited');
    for (const note of notes) {
      assert.equal(note.quote, 'a line the code does not have');
      assert.equal(note.verdict, 'not_found');
      assert.ok(note.excerpt?.includes('\tsep := "ab"'), `the excerpt is the code's lines, the NUL left out: ${JSON.stringify(note.excerpt)}`);
      assert.equal(note.excerpt?.includes(NUL), false);
    }
  } finally {
    h.model.answer = asWritten;
  }
});

// ── 10. a NUL in the model's answer (2026-10-09) ─────────────────────────────────────────────────────

test('a NUL in the model\'s answer, raw or as \\u0000: the build succeeds, the answer is kept as it came, and what is written has no NUL', { skip, timeout: 180_000 }, async () => {
  const h = await boot();
  await modelUp(h);
  const s = await scene(h, 'nul-answer');
  const version = await draft(h, s, planFor(s));
  executor('canary', [s.owner.id]);
  await confirm(h, s, version);
  const [row] = await builds(h, s.spaceId);
  const HEAD = createHash('sha1').update(`head-${randomUUID()}`).digest('hex');
  playRunner(h, s.runner.id, () => tree(HEAD));
  // A writer that copies a NUL into what it writes: raw in the flow section — the sentence and its quote — and as the
  // six characters \u0000 in the conventions section, which is not JSON, so they stay the text the model wrote.
  const asWritten = h.model.answer;
  h.model.answer = (prompt) => {
    const text = asWritten(prompt);
    // Which section a write prompt is for is its header's number: the outline below it names every section.
    const section = /^# 任务：写文档《[^》]*》的第 (\d+) 节/mu.exec(prompt)?.[1];
    if (section === '2') return text.replace(/写成一句话/gu, `写成一句${NUL}话`).replace(/「/gu, `「${NUL}`);
    if (section === '3') return text.replace(/写成一句话/gu, '写成一句\\u0000话');
    return text;
  };
  try {
    const ended = await buildEnd(h, worker(h), row.job_id!);
    assert.equal(ended.state, 'succeeded', JSON.stringify(ended));
    assert.deepEqual([ended.report?.written, ended.report?.failed], [3, 0]);

    // The answers were kept as the model sent them: the one with a raw NUL as its bytes, read back to the same text.
    const { rows: writes } = await h.sql.query<{ answer: string; answer_encoding: string }>(
      `SELECT "answer", "answer_encoding" FROM "wiki_model_request" WHERE "job_id" = $1 AND "step" = 'docs_write' AND "state" = 'succeeded'`,
      [row.job_id]);
    const kept = writes.map((one) => (one.answer_encoding === 'base64' ? Buffer.from(one.answer, 'base64').toString('utf8') : one.answer));
    assert.ok(writes.some((one) => one.answer_encoding === 'base64'), 'the answer with a raw NUL is kept as its bytes');
    assert.ok(kept.some((text) => text.includes(`写成一句${NUL}话`)), 'and read back with its NUL');
    assert.ok(kept.some((text) => text.includes('写成一句\\u0000话')), 'the escaped one is kept as the six characters it is');

    // What was written has no NUL: the raw one left out, the escaped one the text the model wrote.
    const { rows: sentences } = await h.sql.query<{ text: string }>(
      `SELECT t."text" FROM "wiki_doc_sentence" t JOIN "wiki_doc_section" x ON x."id" = t."section_id"
         JOIN "wiki_doc" d ON d."id" = x."doc_id" WHERE d."space_id" = $1`, [s.spaceId]);
    assert.ok(sentences.length > 0);
    assert.ok(sentences.every((one) => !one.text.includes(NUL)), JSON.stringify(sentences));
    // The flow section is the one citing the code (C1): its sentence, the NUL the model put in it left out.
    assert.ok(sentences.some((one) => one.text.includes('依据 C1 写成一句话')), 'the flow section\'s sentence, its NUL left out');
    assert.ok(sentences.some((one) => one.text.includes('写成一句\\u0000话')), 'the conventions section\'s sentence, as the model wrote it');
    const { rows: notes } = await h.sql.query<{ quote: string | null }>(
      `SELECT f."quote" FROM "wiki_doc_footnote" f JOIN "wiki_doc_sentence" t ON t."id" = f."sentence_id"
         JOIN "wiki_doc_section" x ON x."id" = t."section_id" JOIN "wiki_doc" d ON d."id" = x."doc_id" WHERE d."space_id" = $1`, [s.spaceId]);
    assert.ok(notes.every((one) => !(one.quote ?? '').includes(NUL)), JSON.stringify(notes));
  } finally {
    h.model.answer = asWritten;
  }
});

// ── 11. a worker that stops while the build waits for its reads (2026-10-09) ─────────────────────────

/** Three sections that each read a file of their own: one read more than `readsInFlight`, so one waits for a slot. */
function threeReadsPlanFor(s: Scene): Record<string, unknown> {
  const plan = planFor(s) as { docs: Array<{ sections: unknown[] }> };
  const [overview] = plan.docs[0].sections;
  plan.docs[0].sections = [
    overview,
    { title: '设计', kind: 'flow', covers: '一轮 turn 怎么投递。', length: 400, sources: { docs: [{ path: 'docs/design.md', section: '2. Delivery' }] } },
    { title: '主循环', kind: 'flow', covers: 'runner 怎么领取工作。', length: 400, sources: { code: [{ path: 'src/runloop.go', symbols: ['runLoop'] }] } },
    { title: '合同', kind: 'interface', covers: '会话的合同。', length: 400, sources: { contracts: [{ path: 'contracts/session.contract.json' }] } },
  ];
  return plan;
}

/** The job's row as a stop leaves it: whether its lease was let out, and what it counted and said. */
async function jobLease(h: Harness, jobId: string): Promise<{ state: string; let_out: boolean | null; attempts: number; failure_kind: string | null; error: string | null }> {
  return (await h.sql.query(
    'SELECT "state", "lease_deadline_at" <= now() AS "let_out", "attempts", "failure_kind", "error" FROM "wiki_job" WHERE "id" = $1', [jobId],
  )).rows[0];
}

async function repoOpsOf(h: Harness, jobId: string): Promise<Array<{ id: string; kind: string }>> {
  return (await h.sql.query<{ id: string; kind: string }>('SELECT "id", "kind" FROM "wiki_repo_op" WHERE "job_id" = $1 ORDER BY "created_at", "id"', [jobId])).rows;
}

test('a worker that stops while the build waits for its reads lets the lease out to now: no REPO_OP_FAILED, no read asked again, and the next worker takes it over (design §5.4)', { skip, timeout: 180_000 }, async () => {
  const h = await boot();
  await modelUp(h);
  const s = await scene(h, 'stop-on-read');
  const version = await draft(h, s, threeReadsPlanFor(s));
  executor('canary', [s.owner.id]);
  await confirm(h, s, version);
  const [row] = await builds(h, s.spaceId);
  const jobId = row.job_id!;
  const HEAD = createHash('sha1').update(`head-${randomUUID()}`).digest('hex');
  // A runner whose reads hang: the snapshot is answered, no read is.
  const hold = { reads: true };
  playRunner(h, s.runner.id, () => tree(HEAD), hold);
  const first = worker(h);
  await passes(first, async () => (await repoOpsOf(h, jobId)).filter((op) => op.kind === 'read').length === WIKI_DOCS_BUILD_JOB.readsInFlight,
    'the build waiting on its reads, the third section\'s waiting for a slot');
  const before = await repoOpsOf(h, jobId);

  // SIGTERM: the worker stops, and the reads' waits are cancelled with it.
  await first.executor.onModuleDestroy();
  await first.queue.onModuleDestroy();
  await delay(300);
  assert.deepEqual(
    { ...(await jobLease(h, jobId)), asked: (await repoOpsOf(h, jobId)).slice(before.length).map((op) => op.kind) },
    { state: 'running', let_out: true, attempts: 0, failure_kind: null, error: null, asked: [] },
    'the job lets its lease out to now — nothing settled, nothing counted, no REPO_OP_FAILED — and asks the runner for nothing more',
  );

  // The next worker takes the job over at once, the attempt the stop cut short counted as the lease sweep counts
  // one, and its replay finishes the build.
  hold.reads = false;
  const ended = await runToEnd(h, worker(h), jobId);
  assert.equal(ended.state, 'succeeded', JSON.stringify(ended));
  assert.equal((await jobLease(h, jobId)).attempts, 1, 'the lost attempt, counted once');
  assert.deepEqual([ended.report?.written, ended.report?.failed], [4, 0]);
});
