/**
 * The turn that tells a coordinator the owner's answer carries an `ownerAnswer` card (§5.2 R10) —
 * against a real PostgreSQL.
 *
 * The turn's words are written for the agent (`From Orbit · owner answer: you asked "…"`) and stay
 * exactly that; the card beside them is what lets a client draw the turn as one line,
 * `Sent to the coordinator · HH:mm`, instead of a bubble the owner typed. It is read where every turn
 * card is read (sessions/turn-cards.ts): off both views of the queue while the turn waits, and onto
 * the runner's echo when it is stored. Each case below queues the turn through the door that writes
 * it in production, reads both views, hands the turn to the runner, echoes it through the real event
 * ingest, and holds every reading to the card the rows say it is:
 *
 *   (1) a question the coordinator asked, answered by the owner;
 *   (2) the coordinator's request to record the project done, sent back with Not yet…;
 *   (3) an ordinary message of the owner's — and one filed under the answer's key with no delivery
 *       behind it, or naming another conversation — carries none;
 *   (4) the time on the card is THIS conversation's delivery: a coordinator rotated in after the
 *       answer reads when it was told, not when the owner answered or when the first one was told.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/projects/owner-answer-turn-card.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { JwtService } from '@nestjs/jwt';
import {
  type Prisma,
  type PrismaClient,
  RunStatus,
  RunnerStatus,
  SessionDispatchOrigin,
  SessionRunSource,
} from '@prisma/client';
import { RunEventType, RunStatus as SharedRunStatus, type OwnerAnswerCard } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import type { PrismaService } from '../prisma/prisma.service';
import type { PushService } from '../push/push.service';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerOrchestrationAuthorizer } from '../runner-api/runner-orchestration-authorizer';
import { SessionRequestService } from '../sessions/session-request.service';
import { SessionsService } from '../sessions/sessions.service';
import { OwnerConfirmationReviewService } from '../tasks/owner-confirmation-review.service';
import { TasksService } from '../tasks/tasks.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from './coordinator-pg-test-safety';
import { DONE_REQUEST_DEDUPE_KEY, DONE_REQUEST_KIND, DONE_REQUEST_TITLE } from './project-done-request';
import { OWNER_ANSWER_TURN_PREFIX, ownerAnswerTurnId } from './project-open-item';
import { ProjectOpenItemService } from './project-open-item.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

const QUESTION = 'Two ready tasks both rewrite session_pool.go. Which one starts first?';
const OPTIONS = [
  { label: 'Start t4 first, then t7 once t4 lands' },
  { label: 'Start both now — expect a merge conflict to resolve' },
];

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

/** A card as a client reads it: over the wire, so compared as the JSON it is sent as. */
const wire = (value: unknown): unknown => (value === undefined ? undefined : JSON.parse(JSON.stringify(value)));

test('the turn telling a coordinator the owner’s answer carries an ownerAnswer card, on the queue and on the echo', {
  skip, concurrency: 1, timeout: 600_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });
  const db = prisma as unknown as PrismaService;

  // ── the world: one account, one machine, one workspace every conversation runs in ────────────
  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const workspaceId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `owner-answer-${ownerId}@turn-card.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: {
      id: runnerId, ownerId, name: 'the machine every coordinator runs on', tokenHash: sha256(`token-${runnerId}`),
      status: RunnerStatus.ONLINE, lastHeartbeatAt: new Date(), capabilities: [], capabilitiesReportedAt: new Date(),
    },
  });
  await prisma.workspace.create({ data: { id: workspaceId, ownerId, runnerId, name: 'orbit-coordinator', enabled: true } });

  /** A conversation on this runner, parked between turns: what a coordinator is when a turn is queued. */
  async function conversation(title: string, data: Partial<Prisma.SessionUncheckedCreateInput> = {}): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id, ownerId, creatorId: ownerId, workspaceId, assignedRunnerId: runnerId,
        title, prompt: title, provider: 'claude', status: RunStatus.AWAITING_INPUT,
        numTurns: 1, startedAt: new Date(), runtimeSessionId: `runtime-${id}`,
        dispatchOrigin: SessionDispatchOrigin.USER, runSource: SessionRunSource.MANUAL,
        titleManagedByProject: true, ...data,
      },
    });
    return id;
  }

  /** A project coordinated from a conversation of record: the one an answer is told to. */
  async function coordinatedProject(title: string): Promise<{ projectId: string; coordinator: string }> {
    const coordinator = await conversation(`coordinator: ${title}`);
    const projectId = randomUUID();
    await prisma.project.create({
      data: {
        id: projectId, ownerId, title, coordinatorEnabled: true,
        coordinatorSessionId: coordinator, coordinatorWorkspaceId: workspaceId,
      },
    });
    return { projectId, coordinator };
  }

  // ── the doors ─────────────────────────────────────────────────────────────────────────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(db, queue as never, realtime as never);
  const tasks = new TasksService(db, sessions, realtime as never);
  const requests = new SessionRequestService(db, sessions, realtime as never);
  const push = { notifyConfirmationProblems: async () => undefined } as unknown as PushService;
  const reviews = new OwnerConfirmationReviewService(db, sessions, realtime as never, push);
  const openItems = new ProjectOpenItemService(db, sessions);
  const orchestration = new RunnerOrchestrationAuthorizer(db, new JwtService({ secret: 'owner-answer-turn-card-pg' }));
  const api = new RunnerApiController(
    db,
    queue as never,
    realtime as never,
    {} as never,
    orchestration,
    // The turns here carry no `#`-references and reach no list console.
    { expand: async (_owner: string, content?: string) => content } as never,
    { appendFor: async (_tx: unknown, _id: string, content?: string) => content } as never,
    undefined,
    undefined,
    tasks,
    undefined,
    sessions,
    undefined,
    undefined,
    undefined,
    undefined,
    requests,
    reviews,
  );

  /** The owner's own message, waiting at the head of the queue: what the answer's turn waits behind. */
  async function ownerSays(sessionId: string, words: string, clientTurnId: string = randomUUID()): Promise<string> {
    return (await sessions.createTurn(ownerId, sessionId, { clientTurnId, content: words })).turnId;
  }

  /** The one turn of a conversation whose key starts with `prefix`. */
  async function turnKeyed(sessionId: string, prefix: string) {
    const turns = await prisma.conversationTurn.findMany({ where: { sessionId, clientTurnId: { startsWith: prefix } } });
    assert.equal(turns.length, 1, `expected one ${prefix} turn on the conversation, found ${turns.length}`);
    return turns[0]!;
  }

  /** What the runner's claim does to a queued conversation, then the polls that hand its next message out. */
  async function deliver(sessionId: string): Promise<{ turnId: string; content: string }> {
    await prisma.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    for (;;) {
      const handed = await (api as unknown as {
        dequeueTurn: (sessionId: string, runnerId: string, leaseGeneration: string | null) => Promise<Record<string, unknown> | null>;
      }).dequeueTurn.call(api, sessionId, runnerId, null);
      assert.ok(handed, `the inbox of ${sessionId} handed nothing out`);
      const turn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: String(handed.turnId) } });
      if (turn.kind !== 'message') continue;
      return { turnId: turn.id, content: String(handed.content ?? '') };
    }
  }

  const seqs = new Map<string, number>();
  /** The runner's event for one turn, through the real ingest. Answers the payload that was stored. */
  async function say(sessionId: string, turnId: string, type: RunEventType, payload: Record<string, unknown>) {
    const seq = (seqs.get(sessionId) ?? 100) + 1;
    seqs.set(sessionId, seq);
    await api.events({ id: runnerId } as never, sessionId, {
      events: [{ seq, type, ts: new Date().toISOString(), turnId, payload }],
    } as never);
    return (await prisma.runEvent.findFirstOrThrow({ where: { sessionId, seq } })).payload as Record<string, unknown>;
  }

  /** The turn ends as the runner reports it: something said, then the completion. */
  async function finish(sessionId: string, turnId: string) {
    await say(sessionId, turnId, RunEventType.ASSISTANT, { text: 'Done.' });
    await api.turnComplete({ id: runnerId } as never, sessionId, {
      turnId, status: SharedRunStatus.SUCCEEDED, subtype: 'success', numTurns: 1, costUsd: 0,
    } as never);
  }

  /** The card the rows say this conversation's turn for `itemId` is: the item, and its own delivery's moment. */
  async function cardFromRows(itemId: string, sessionId: string): Promise<OwnerAnswerCard> {
    const { rows } = await sql.query<{ kind: OwnerAnswerCard['kind']; created_at: Date }>(
      `SELECT i."kind", d."created_at"
         FROM "project_open_item_delivery" d JOIN "project_open_item" i ON i."id" = d."item_id"
        WHERE d."item_id" = $1::uuid AND d."session_id" = $2::uuid AND d."purpose" = 'ANSWER'`,
      [itemId, sessionId],
    );
    assert.equal(rows.length, 1, 'the delivery wrote one ANSWER row for this conversation');
    return { itemId, kind: rows[0]!.kind, sessionId, deliveredAt: rows[0]!.created_at.toISOString() };
  }

  /**
   * The assertion every delivery below makes: `turnId` waits behind `ahead` in `sessionId`'s queue
   * and carries `expected` on both views; then, handed out, on the active view's accepted row; then
   * on the echo the ingest stores. Its words reach the runner unchanged — ahead of whatever delivery
   * appends to a coordinator's turn (its standing role). Answers the stored echo.
   */
  async function assertCarried(
    sessionId: string,
    ahead: string,
    turnId: string,
    expected: OwnerAnswerCard,
  ): Promise<Record<string, unknown>> {
    const words = (await prisma.conversationTurn.findUniqueOrThrow({ where: { id: turnId } })).content!;
    const queued = (await sessions.listQueuedTurns(ownerId, sessionId)).find((row) => row.turnId === turnId);
    assert.ok(queued, 'the queue view does not list the waiting turn');
    assert.deepEqual(wire(queued.ownerAnswer), expected, 'the queue view');
    const active = (await sessions.listQueuedTurns(ownerId, sessionId, 'active')).find((row) => row.turnId === turnId);
    assert.ok(active, 'the active view does not list the waiting turn');
    assert.deepEqual(wire(active.ownerAnswer), expected, 'the active view');

    const head = await deliver(sessionId);
    assert.equal(head.turnId, ahead, 'the owner’s message ahead of it was handed out first');
    await finish(sessionId, head.turnId);
    const handed = await deliver(sessionId);
    assert.equal(handed.turnId, turnId, 'the runner was handed another turn');
    assert.ok(handed.content.startsWith(words), 'the agent is handed the words the turn was written with');
    const accepted = (await sessions.listQueuedTurns(ownerId, sessionId, 'active')).find((row) => row.turnId === turnId);
    assert.ok(accepted, 'the active view lost the turn between hand-out and echo');
    assert.deepEqual(wire(accepted.ownerAnswer), expected, 'the accepted row');

    const echo = await say(sessionId, turnId, RunEventType.USER, {
      text: handed.content,
      // Only the control plane says what a turn is: a card the runner sends is dropped for the one read here.
      ownerAnswer: { itemId: randomUUID(), kind: 'COORDINATOR_QUESTION', sessionId, deliveredAt: '2000-01-01T00:00:00.000Z' },
    });
    assert.deepEqual(wire(echo.ownerAnswer), expected, 'the echo');
    assert.ok(String(echo.text).startsWith(words), 'the echo keeps the words the agent read');
    return echo;
  }

  await t.test('(1) a question the coordinator asked, answered by the owner', async () => {
    const { projectId, coordinator } = await coordinatedProject('the project whose coordinator asks');
    const asked = await openItems.askOwner(ownerId, projectId, coordinator, {
      question: QUESTION, options: OPTIONS, recommendedOption: 0, clientQuestionId: randomUUID(),
    });
    const ahead = await ownerSays(coordinator, 'the owner says something first');
    const answered = await openItems.answerOpenItem(ownerId, projectId, asked.itemId, { option: 1 });
    const told = await turnKeyed(coordinator, OWNER_ANSWER_TURN_PREFIX);
    assert.equal(answered.delivery?.turnId, told.id);
    assert.equal(told.clientTurnId, ownerAnswerTurnId(asked.itemId, coordinator));
    assert.match(told.content ?? '', /^From Orbit · owner answer: you asked "/, 'the agent’s words are what they were');
    assert.ok(told.content?.includes(QUESTION) && told.content.includes(OPTIONS[1]!.label));

    const expected = await cardFromRows(asked.itemId, coordinator);
    assert.equal(expected.kind, 'COORDINATOR_QUESTION');
    await assertCarried(coordinator, ahead, told.id, expected);
  });

  await t.test('(2) a request to record the project done, sent back with Not yet…', async () => {
    const { projectId, coordinator } = await coordinatedProject('the project the owner sends back');
    const now = new Date();
    const request = await prisma.projectOpenItem.create({
      data: {
        projectId, ownerId, kind: DONE_REQUEST_KIND, state: 'OPEN', assignee: 'OWNER', assigneeReason: 'DEFAULT',
        askedBySessionId: coordinator, dedupeKey: DONE_REQUEST_DEDUPE_KEY, title: DONE_REQUEST_TITLE,
        payload: { criteriaDigest: 'c'.repeat(64), judgment: 'Every criterion is landed.', gaps: [] },
        waitingSince: now, assignedAt: now, escalateAt: null,
      },
      select: { id: true },
    });
    const ahead = await ownerSays(coordinator, 'the owner says something first');
    const declined = await openItems.declineDoneRequest(ownerId, projectId, request.id, {
      note: 'The production migration has not run yet.',
    });
    const told = await turnKeyed(coordinator, OWNER_ANSWER_TURN_PREFIX);
    assert.equal(declined.delivery?.turnId, told.id);
    assert.equal(told.clientTurnId, ownerAnswerTurnId(request.id, coordinator));
    assert.match(told.content ?? '', /^From Orbit · owner says not yet for /, 'the agent’s words are what they were');

    const expected = await cardFromRows(request.id, coordinator);
    assert.equal(expected.kind, 'DONE_REQUEST');
    await assertCarried(coordinator, ahead, told.id, expected);
  });

  await t.test('(3) an ordinary message carries no card — nor one filed under the answer’s key that nothing delivered', async () => {
    const { projectId, coordinator } = await coordinatedProject('the project the owner talks to');
    const asked = await openItems.askOwner(ownerId, projectId, coordinator, {
      question: QUESTION, options: OPTIONS, clientQuestionId: randomUUID(),
    });
    const elsewhere = await conversation('a conversation that coordinates nothing');
    // The head of the queue, so each turn below waits behind it on both views.
    const ahead = await ownerSays(coordinator, 'the owner says something first');
    const plain = await ownerSays(coordinator, 'what is the status of t4?');
    // The answer's own key for this conversation, taken by a message before any answer exists: no
    // delivery row stands behind it. And a key naming another conversation, and one that is no key.
    const squatted = await ownerSays(coordinator, 'my own words', ownerAnswerTurnId(asked.itemId, coordinator));
    const foreign = await ownerSays(coordinator, 'more words', ownerAnswerTurnId(asked.itemId, elsewhere));
    const malformed = await ownerSays(coordinator, 'and more', `${OWNER_ANSWER_TURN_PREFIX}not-an-item:nobody`);
    // And the answer once delivered elsewhere: a row exists for the item, but not for this conversation.
    await prisma.project.update({ where: { id: projectId }, data: { coordinatorSessionId: elsewhere } });
    await openItems.answerOpenItem(ownerId, projectId, asked.itemId, { option: 0 });
    await turnKeyed(elsewhere, OWNER_ANSWER_TURN_PREFIX);

    const ours = [plain, squatted, foreign, malformed];
    const views = [
      ['queue', await sessions.listQueuedTurns(ownerId, coordinator)],
      ['active', await sessions.listQueuedTurns(ownerId, coordinator, 'active')],
    ] as const;
    for (const [view, rows] of views) {
      for (const turnId of ours) {
        const row = rows.find((each) => each.turnId === turnId);
        assert.ok(row, `the ${view} view does not list ${turnId}`);
        assert.equal(row.ownerAnswer, undefined, `the ${view} view: ${turnId} carries a card`);
      }
    }
    // Each echoed through the ingest: none is stored with a card — not even one the runner sends —
    // and none costs the batch.
    const head = await deliver(coordinator);
    assert.equal(head.turnId, ahead, 'the head of the queue was handed out first');
    await finish(coordinator, head.turnId);
    for (const turnId of ours) {
      const handed = await deliver(coordinator);
      assert.equal(handed.turnId, turnId, 'the turns are handed out in the order they were queued');
      const echo = await say(coordinator, turnId, RunEventType.USER, {
        text: handed.content,
        ownerAnswer: { itemId: asked.itemId, kind: 'COORDINATOR_QUESTION', sessionId: coordinator, deliveredAt: new Date().toISOString() },
      });
      assert.equal(echo.ownerAnswer, undefined, `the echo of ${turnId} carries a card`);
      await finish(coordinator, turnId);
    }
  });

  await t.test('(4) the card’s time is this conversation’s delivery, also after a rotation', async () => {
    const { projectId, coordinator: first } = await coordinatedProject('the project that rotates its coordinator');
    const asked = await openItems.askOwner(ownerId, projectId, first, {
      question: QUESTION, options: OPTIONS, clientQuestionId: randomUUID(),
    });
    await openItems.answerOpenItem(ownerId, projectId, asked.itemId, { option: 0 });
    const toldFirst = await turnKeyed(first, OWNER_ANSWER_TURN_PREFIX);
    // The first coordinator was told two hours ago. (The item itself is terminal and cannot be edited.)
    await sql.query(
      `UPDATE "project_open_item_delivery" SET "created_at" = "created_at" - interval '2 hours'
        WHERE "item_id" = $1::uuid AND "session_id" = $2::uuid`,
      [asked.itemId, first],
    );
    const firstCard = await cardFromRows(asked.itemId, first);

    // A new conversation takes over, already busy; the answer is owed to it (§5.2 R11) — told a
    // moment after the answer, so the two clocks cannot round onto one millisecond.
    await new Promise((resolve) => setTimeout(resolve, 50));
    const next = await conversation('the coordinator rotated in');
    const ahead = await ownerSays(next, 'the new coordinator has work queued');
    await prisma.project.update({ where: { id: projectId }, data: { coordinatorSessionId: next } });
    await openItems.deliverOwed(projectId, first);
    const toldNext = await turnKeyed(next, OWNER_ANSWER_TURN_PREFIX);
    assert.equal(toldNext.clientTurnId, ownerAnswerTurnId(asked.itemId, next));

    const nextCard = await cardFromRows(asked.itemId, next);
    const { resolvedAt } = await prisma.projectOpenItem.findUniqueOrThrow({
      where: { id: asked.itemId }, select: { resolvedAt: true },
    });
    assert.ok(Date.parse(nextCard.deliveredAt) > resolvedAt!.getTime(), 'not the moment the owner answered');
    assert.notEqual(nextCard.deliveredAt, firstCard.deliveredAt, 'not the moment the first coordinator was told');
    assert.ok(Date.parse(nextCard.deliveredAt) - Date.parse(firstCard.deliveredAt) > 60 * 60 * 1000);
    await assertCarried(next, ahead, toldNext.id, nextCard);

    // The first conversation's turn still reads its own delivery.
    const handedFirst = await deliver(first);
    assert.equal(handedFirst.turnId, toldFirst.id);
    const echoFirst = await say(first, toldFirst.id, RunEventType.USER, { text: handedFirst.content });
    assert.deepEqual(wire(echoFirst.ownerAnswer), firstCard, 'the first coordinator’s line keeps its own time');
  });
});
