// TEMPORARY evidence probe (see ../../README.md): the data every screen draws, as the server would
// send it (generated by the task session from the same rows its web screenshots use).
let probeDataJSON = #"""
{
 "now": "2026-09-28T09:41:00.000Z",
 "spaceAuto": {
  "id": "0196b700-0000-7000-8000-000000000001",
  "slug": "orbit",
  "title": "orbit",
  "repoUrlNorm": "github.com/jianghailong-xy/orbit",
  "rootCommitSha": "1588c3b444444444444444444444444444444444",
  "settings": {
   "push": true,
   "autoAcceptReinforce": true,
   "reviewMode": "automatic",
   "automaticSpotChecks": false,
   "maintenance": {
    "enabled": false,
    "workspaceId": null,
    "provider": "local-vllm",
    "dailyRunLimit": 8,
    "listId": null
   }
  },
  "createdAt": "2026-09-23T09:41:00.000Z",
  "updatedAt": "2026-09-28T08:41:00.000Z",
  "pendingOps": 3,
  "usage": {
   "days": 7,
   "sessionsPushed": 186,
   "searches": 41,
   "gets": 12,
   "entries": []
  }
 },
 "spaceOn": {
  "id": "0196b700-0000-7000-8000-000000000001",
  "slug": "orbit",
  "title": "orbit",
  "repoUrlNorm": "github.com/jianghailong-xy/orbit",
  "rootCommitSha": "1588c3b444444444444444444444444444444444",
  "settings": {
   "push": true,
   "autoAcceptReinforce": true,
   "reviewMode": "tiered",
   "automaticSpotChecks": false,
   "maintenance": {
    "enabled": true,
    "workspaceId": "ws-orbit",
    "provider": "local-vllm",
    "dailyRunLimit": 8,
    "listId": "list"
   },
   "reviewModeChangedAt": "2026-09-27T12:00:00.000Z",
   "reviewModeChangedBy": "verification"
  },
  "createdAt": "2026-09-23T09:41:00.000Z",
  "updatedAt": "2026-09-28T08:41:00.000Z",
  "pendingOps": 3,
  "usage": {
   "days": 7,
   "sessionsPushed": 186,
   "searches": 41,
   "gets": 12,
   "entries": []
  }
 },
 "entries": [
  {
   "id": "0196b700-0000-7000-8000-000000000011",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "pitfall",
   "status": "active",
   "trust": "unreviewed",
   "currentRevision": 1,
   "title": "captureBeyondViewport 重排致截图横向偏移",
   "summary": "CDP 截图开 captureBeyondViewport 会触发重排导致横向偏移；应设 false 并按元素 rect 裁切。",
   "fields": {
    "symptom": "并排截图出现横向错位",
    "cause": "captureBeyondViewport true 时 Chrome 触发重排，布局偏移",
    "fix": "captureBeyondViewport 设 false，按元素 rect 裁切取景"
   },
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [],
   "anchorState": "unchecked",
   "anchorCheckedRef": null,
   "anchorCheckedAt": null,
   "tainted": false,
   "challenged": false,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  },
  {
   "id": "0196b700-0000-7000-8000-000000000012",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "recipe",
   "status": "active",
   "trust": "auto",
   "currentRevision": 1,
   "title": "用 chromium headless 渲染 mock HTML 生成 PNG 效果图",
   "summary": "把设计稿写成 HTML，chromium --headless=new 配 --window-size 与 --force-device-scale-factor 出 PNG。",
   "fields": {
    "steps": [
     "写 HTML 设计稿",
     "chromium --headless=new --window-size=W,H --screenshot"
    ],
    "verify": {
     "command": "ls docs/mocks/*.png",
     "expectedExit": 0
    }
   },
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [
    {
     "type": "path",
     "path": "docs/mocks/wiki",
     "check": {
      "state": "verified",
      "ref": "1588c3b444444444444444444444444444444444",
      "at": "2026-09-28T09:11:00.000Z"
     }
    }
   ],
   "anchorState": "verified",
   "anchorCheckedRef": "1588c3b444444444444444444444444444444444",
   "anchorCheckedAt": "2026-09-28T09:11:00.000Z",
   "tainted": false,
   "challenged": false,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  },
  {
   "id": "0196b700-0000-7000-8000-000000000013",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "decision",
   "status": "active",
   "trust": "unreviewed",
   "currentRevision": 1,
   "title": "scroll 按钮全面向 ChatGPT 对齐:40pt 空灵玻璃",
   "summary": "滚到底按钮与 ChatGPT 一致：40pt、玻璃材质、无描边。",
   "fields": {
    "context": "iOS 与 web 的滚到底按钮不一致",
    "decision": "全面向 ChatGPT 对齐：40pt 空灵玻璃",
    "consequences": "两端同一套尺寸"
   },
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [],
   "anchorState": "unchecked",
   "anchorCheckedRef": null,
   "anchorCheckedAt": null,
   "tainted": true,
   "challenged": false,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  },
  {
   "id": "0196b700-0000-7000-8000-000000000014",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "pitfall",
   "status": "active",
   "trust": "confirmed",
   "currentRevision": 1,
   "title": "wikiAnchorMark 读锚点状态时要带 ref",
   "summary": "已验证的锚点显示验证时的提交号，没有 ref 时写 Checked。",
   "fields": {
    "symptom": "徽章只写 Checked",
    "cause": "没有传 anchorCheckedRef",
    "fix": "把 ref 一起传进 wikiAnchorMark"
   },
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [
    {
     "type": "symbol",
     "path": "src/web/src/lib/wiki.ts",
     "symbol": "wikiAnchorMark",
     "check": {
      "state": "changed",
      "ref": "1588c3b444444444444444444444444444444444",
      "at": "2026-09-28T09:01:00.000Z"
     }
    },
    {
     "type": "commit",
     "sha": "abcdef0222222222222222222222222222222222",
     "check": {
      "state": "missing",
      "ref": "1588c3b444444444444444444444444444444444",
      "at": "2026-09-28T09:01:00.000Z"
     }
    },
    {
     "type": "path",
     "path": "src/web/src/lib/wiki.ts",
     "check": {
      "state": "verified",
      "ref": "1588c3b444444444444444444444444444444444",
      "at": "2026-09-28T09:01:00.000Z"
     }
    }
   ],
   "anchorState": "missing",
   "anchorCheckedRef": null,
   "anchorCheckedAt": null,
   "tainted": false,
   "challenged": true,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  },
  {
   "id": "0196b700-0000-7000-8000-000000000040",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "recipe",
   "status": "active",
   "trust": "auto",
   "currentRevision": 1,
   "title": "hover 只改可见性不改布局，kebab 预留占位淡入",
   "summary": "hover 时不引入新元素挤动布局，kebab 菜单槽位始终占位、默认隐藏。",
   "fields": {},
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [],
   "anchorState": "unchecked",
   "anchorCheckedRef": null,
   "anchorCheckedAt": null,
   "tainted": false,
   "challenged": false,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  },
  {
   "id": "0196b700-0000-7000-8000-000000000041",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "convention",
   "status": "active",
   "trust": "auto",
   "currentRevision": 1,
   "title": "界面效果图用 HTML/CSS 手绘导出，不用 imagegen",
   "summary": "绘制 UI 效果图时直接用 HTML/CSS 并导出图片。",
   "fields": {},
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [],
   "anchorState": "unchecked",
   "anchorCheckedRef": null,
   "anchorCheckedAt": null,
   "tainted": false,
   "challenged": false,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  },
  {
   "id": "0196b700-0000-7000-8000-000000000042",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "recipe",
   "status": "active",
   "trust": "auto",
   "currentRevision": 1,
   "title": "本地 vite + headless chromium 渲染 UI 截图冒烟",
   "summary": "用临时 .ux-preview 页面渲染代表数据，chromium headless 截桌面/窄屏图。",
   "fields": {},
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [],
   "anchorState": "unchecked",
   "anchorCheckedRef": null,
   "anchorCheckedAt": null,
   "tainted": false,
   "challenged": false,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  },
  {
   "id": "0196b700-0000-7000-8000-000000000043",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "convention",
   "status": "active",
   "trust": "unreviewed",
   "currentRevision": 1,
   "title": "重出 mock PNG 前先复现原图校验渲染管线",
   "summary": "先把原图复现一遍，确认字体与窗口一致再改。",
   "fields": {},
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [],
   "anchorState": "unchecked",
   "anchorCheckedRef": null,
   "anchorCheckedAt": null,
   "tainted": false,
   "challenged": false,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  },
  {
   "id": "0196b700-0000-7000-8000-000000000044",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "recipe",
   "status": "active",
   "trust": "auto",
   "currentRevision": 1,
   "title": "UI 效果图按仓库惯例放进 docs/mocks/",
   "summary": "批准的效果图（html 和 png）放进 docs/mocks/ 目录。",
   "fields": {},
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [],
   "anchorState": "unchecked",
   "anchorCheckedRef": null,
   "anchorCheckedAt": null,
   "tainted": false,
   "challenged": false,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  },
  {
   "id": "0196b700-0000-7000-8000-000000000045",
   "spaceId": "0196b700-0000-7000-8000-000000000001",
   "kind": "convention",
   "status": "active",
   "trust": "confirmed",
   "currentRevision": 1,
   "title": "worktree index.lock 残留导致 git add 报 Exit 128",
   "summary": "先删掉残留的 index.lock 再提交。",
   "fields": {},
   "topics": [
    "ui-design"
   ],
   "aliases": [],
   "anchors": [],
   "anchorState": "unchecked",
   "anchorCheckedRef": null,
   "anchorCheckedAt": null,
   "tainted": false,
   "challenged": false,
   "unsupported": false,
   "pinned": false,
   "supersedesId": null,
   "supersededById": null,
   "validFrom": "2026-09-28T07:41:00.000Z",
   "validTo": null,
   "recordedAt": "2026-09-28T07:41:00.000Z",
   "retiredAt": null
  }
 ],
 "run": {
  "id": "0196b700-0000-7000-8000-000000000021",
  "spaceId": "0196b700-0000-7000-8000-000000000001",
  "origin": "maintenance",
  "sessionId": "0196b700-0000-7000-8000-000000000031",
  "toolCallId": null,
  "rationale": "Wiki maintenance",
  "status": "pending",
  "createdAt": "2026-09-28T07:41:00.000Z",
  "decidedAt": null,
  "expiresAt": "2026-10-11T09:41:00.000Z",
  "ops": [
   {
    "id": "0196b700-0000-7000-8000-000000000101",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 0,
    "op": "add",
    "entryId": null,
    "baseRevision": null,
    "payload": {
     "entry": {
      "kind": "pitfall",
      "title": "captureBeyondViewport 重排致截图横向偏移",
      "summary": "CDP 截图开 captureBeyondViewport 会触发重排导致横向偏移。",
      "fields": {}
     }
    },
    "similar": [],
    "tainted": false,
    "decision": "pending",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": "0196b700-0000-7000-8000-000000000011",
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": "automatic",
    "spotCheck": true,
    "verification": {
     "verdict": "partial",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": null,
     "evidence": "readable"
    }
   },
   {
    "id": "0196b700-0000-7000-8000-000000000102",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 1,
    "op": "add",
    "entryId": null,
    "baseRevision": null,
    "payload": {},
    "similar": [],
    "tainted": false,
    "decision": "auto_applied",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": "0196b700-0000-7000-8000-000000000040",
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": "automatic",
    "spotCheck": false,
    "verification": {
     "verdict": "supported",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": null,
     "evidence": "readable"
    }
   },
   {
    "id": "0196b700-0000-7000-8000-000000000103",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 2,
    "op": "add",
    "entryId": null,
    "baseRevision": null,
    "payload": {},
    "similar": [],
    "tainted": false,
    "decision": "auto_applied",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": "0196b700-0000-7000-8000-000000000041",
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": "automatic",
    "spotCheck": false,
    "verification": {
     "verdict": "supported",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": null,
     "evidence": "readable"
    }
   },
   {
    "id": "0196b700-0000-7000-8000-000000000104",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 3,
    "op": "add",
    "entryId": null,
    "baseRevision": null,
    "payload": {},
    "similar": [],
    "tainted": false,
    "decision": "auto_applied",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": "0196b700-0000-7000-8000-000000000042",
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": "automatic",
    "spotCheck": false,
    "verification": {
     "verdict": "supported",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": null,
     "evidence": "readable"
    }
   },
   {
    "id": "0196b700-0000-7000-8000-000000000105",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 4,
    "op": "add",
    "entryId": null,
    "baseRevision": null,
    "payload": {},
    "similar": [],
    "tainted": false,
    "decision": "auto_applied",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": "0196b700-0000-7000-8000-000000000043",
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": "automatic",
    "spotCheck": false,
    "verification": {
     "verdict": "partial",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": null,
     "evidence": "readable"
    }
   },
   {
    "id": "0196b700-0000-7000-8000-000000000106",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 5,
    "op": "add",
    "entryId": null,
    "baseRevision": null,
    "payload": {},
    "similar": [],
    "tainted": false,
    "decision": "auto_applied",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": "0196b700-0000-7000-8000-000000000044",
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": "automatic",
    "spotCheck": false,
    "verification": {
     "verdict": "supported",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": null,
     "evidence": "readable"
    }
   },
   {
    "id": "0196b700-0000-7000-8000-000000000107",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 6,
    "op": "amend",
    "entryId": "0196b700-0000-7000-8000-000000000012",
    "baseRevision": 1,
    "payload": {
     "changes": {
      "summary": "x"
     }
    },
    "similar": [],
    "tainted": false,
    "decision": "auto_applied",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": null,
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": "automatic",
    "spotCheck": false,
    "verification": {
     "verdict": "supported",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": null,
     "evidence": "readable"
    }
   },
   {
    "id": "0196b700-0000-7000-8000-000000000108",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 7,
    "op": "amend",
    "entryId": "0196b700-0000-7000-8000-000000000044",
    "baseRevision": 1,
    "payload": {
     "changes": {
      "summary": "y"
     }
    },
    "similar": [],
    "tainted": false,
    "decision": "auto_applied",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": null,
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": "automatic",
    "spotCheck": false,
    "verification": {
     "verdict": "supported",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": null,
     "evidence": "readable"
    }
   },
   {
    "id": "0196b700-0000-7000-8000-000000000109",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 8,
    "op": "reinforce",
    "entryId": "0196b700-0000-7000-8000-000000000045",
    "baseRevision": null,
    "payload": {},
    "similar": [],
    "tainted": false,
    "decision": "auto_applied",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": null,
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": null,
    "spotCheck": false,
    "verification": null
   },
   {
    "id": "0196b700-0000-7000-8000-000000000110",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 9,
    "op": "add",
    "entryId": null,
    "baseRevision": null,
    "payload": {
     "entry": {
      "title": "x"
     }
    },
    "similar": [],
    "tainted": false,
    "decision": "rejected",
    "decisionReason": "not_true",
    "decisionNote": null,
    "resultEntryId": "0196b700-0000-7000-8000-000000000060",
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": null,
    "spotCheck": false,
    "verification": {
     "verdict": "unsupported",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": null,
     "evidence": "readable"
    }
   },
   {
    "id": "0196b700-0000-7000-8000-000000000111",
    "changesetId": "0196b700-0000-7000-8000-000000000021",
    "seq": 10,
    "op": "add",
    "entryId": null,
    "baseRevision": null,
    "payload": {
     "entry": {
      "title": "y"
     }
    },
    "similar": [],
    "tainted": false,
    "decision": "rejected",
    "decisionReason": "duplicate",
    "decisionNote": null,
    "resultEntryId": "0196b700-0000-7000-8000-000000000061",
    "resultRevision": 1,
    "decidedAt": "2026-09-28T07:41:00.000Z",
    "appliedByMode": null,
    "spotCheck": false,
    "verification": {
     "verdict": "duplicate",
     "reason": "the sources say so",
     "model": "qwen3.8-27b-fp8",
     "at": "2026-09-28T07:42:00.000Z",
     "duplicateOf": "0196b700-0000-7000-8000-000000000040",
     "evidence": "readable"
    }
   }
  ]
 },
 "challenge": {
  "id": "0196b700-0000-7000-8000-000000000022",
  "spaceId": "0196b700-0000-7000-8000-000000000001",
  "origin": "maintenance",
  "sessionId": null,
  "toolCallId": null,
  "rationale": "Anchor re-verification on origin/main at 1588c3b44444: this entry's anchors no longer hold as recorded.",
  "status": "pending",
  "createdAt": "2026-09-28T09:01:00.000Z",
  "decidedAt": null,
  "expiresAt": "2026-10-12T09:41:00.000Z",
  "ops": [
   {
    "id": "0196b700-0000-7000-8000-000000000201",
    "changesetId": "0196b700-0000-7000-8000-000000000022",
    "seq": 0,
    "op": "challenge",
    "entryId": "0196b700-0000-7000-8000-000000000014",
    "baseRevision": null,
    "payload": {
     "reason": "Anchor re-verification on origin/main at 1588c3b444444444444444444444444444444444: symbol wikiAnchorMark in src/web/src/lib/wiki.ts has changed; commit abcdef0 is missing."
    },
    "similar": [],
    "tainted": false,
    "decision": "pending",
    "decisionReason": null,
    "decisionNote": null,
    "resultEntryId": null,
    "resultRevision": null,
    "decidedAt": null,
    "appliedByMode": null,
    "spotCheck": false,
    "verification": null
   }
  ]
 },
 "timeline": [
  {
   "opId": "0196b700-0000-7000-8000-000000000101",
   "op": "add",
   "decision": "pending",
   "origin": "maintenance",
   "appliedByMode": "automatic",
   "spotCheck": true,
   "at": "2026-09-28T07:41:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000011",
   "title": "run op",
   "kind": "pitfall",
   "status": "active",
   "trust": "auto",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000102",
   "op": "add",
   "decision": "auto_applied",
   "origin": "maintenance",
   "appliedByMode": "automatic",
   "spotCheck": false,
   "at": "2026-09-28T07:40:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000040",
   "title": "run op",
   "kind": "pitfall",
   "status": "active",
   "trust": "auto",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000103",
   "op": "add",
   "decision": "auto_applied",
   "origin": "maintenance",
   "appliedByMode": "automatic",
   "spotCheck": false,
   "at": "2026-09-28T07:39:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000041",
   "title": "run op",
   "kind": "pitfall",
   "status": "active",
   "trust": "auto",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000104",
   "op": "add",
   "decision": "auto_applied",
   "origin": "maintenance",
   "appliedByMode": "automatic",
   "spotCheck": false,
   "at": "2026-09-28T07:38:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000042",
   "title": "run op",
   "kind": "pitfall",
   "status": "active",
   "trust": "auto",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000105",
   "op": "add",
   "decision": "auto_applied",
   "origin": "maintenance",
   "appliedByMode": "automatic",
   "spotCheck": false,
   "at": "2026-09-28T07:37:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000043",
   "title": "run op",
   "kind": "pitfall",
   "status": "active",
   "trust": "auto",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000106",
   "op": "add",
   "decision": "auto_applied",
   "origin": "maintenance",
   "appliedByMode": "automatic",
   "spotCheck": false,
   "at": "2026-09-28T07:36:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000044",
   "title": "run op",
   "kind": "pitfall",
   "status": "active",
   "trust": "auto",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000107",
   "op": "amend",
   "decision": "auto_applied",
   "origin": "maintenance",
   "appliedByMode": "automatic",
   "spotCheck": false,
   "at": "2026-09-28T07:35:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000012",
   "title": "run op",
   "kind": "pitfall",
   "status": "active",
   "trust": "auto",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000108",
   "op": "amend",
   "decision": "auto_applied",
   "origin": "maintenance",
   "appliedByMode": "automatic",
   "spotCheck": false,
   "at": "2026-09-28T07:34:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000044",
   "title": "run op",
   "kind": "pitfall",
   "status": "active",
   "trust": "auto",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000109",
   "op": "reinforce",
   "decision": "auto_applied",
   "origin": "maintenance",
   "appliedByMode": null,
   "spotCheck": false,
   "at": "2026-09-28T07:33:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000045",
   "title": "run op",
   "kind": "pitfall",
   "status": "active",
   "trust": "auto",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000301",
   "op": "add",
   "decision": "accepted",
   "origin": "agent",
   "appliedByMode": null,
   "spotCheck": false,
   "at": "2026-09-28T06:41:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000045",
   "title": "iOS 对齐设计先出效果图并给 A/B/C 多方案，由 owner 拍板",
   "kind": "convention",
   "status": "active",
   "trust": "confirmed",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000302",
   "op": "add",
   "decision": "auto_applied",
   "origin": "agent",
   "appliedByMode": "tiered",
   "spotCheck": false,
   "at": "2026-09-28T05:41:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000043",
   "title": "重出 mock PNG 前先复现原图校验渲染管线",
   "kind": "recipe",
   "status": "active",
   "trust": "unreviewed",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": null
  },
  {
   "opId": "0196b700-0000-7000-8000-000000000303",
   "op": "retire",
   "decision": "auto_applied",
   "origin": "owner",
   "appliedByMode": null,
   "spotCheck": false,
   "at": "2026-09-28T04:41:00.000Z",
   "entryId": "0196b700-0000-7000-8000-000000000062",
   "title": "狼人杀「板子」默认 12 人预女猎白",
   "kind": "concept",
   "status": "retired",
   "trust": "confirmed",
   "supersededById": null,
   "supersededByTitle": null,
   "reason": "not this codebase"
  }
 ],
 "unreviewed": {
  "id": "0196b700-0000-7000-8000-000000000011",
  "spaceId": "0196b700-0000-7000-8000-000000000001",
  "kind": "pitfall",
  "status": "active",
  "trust": "unreviewed",
  "currentRevision": 1,
  "title": "captureBeyondViewport 重排致截图横向偏移",
  "summary": "CDP 截图开 captureBeyondViewport 会触发重排导致横向偏移；应设 false 并按元素 rect 裁切。",
  "fields": {
   "symptom": "并排截图出现横向错位",
   "cause": "captureBeyondViewport true 时 Chrome 触发重排，布局偏移",
   "fix": "captureBeyondViewport 设 false，按元素 rect 裁切取景"
  },
  "topics": [
   "ui-design"
  ],
  "aliases": [],
  "anchors": [],
  "anchorState": "unchecked",
  "anchorCheckedRef": null,
  "anchorCheckedAt": null,
  "tainted": false,
  "challenged": false,
  "unsupported": false,
  "pinned": false,
  "supersedesId": null,
  "supersededById": null,
  "validFrom": "2026-09-28T07:41:00.000Z",
  "validTo": null,
  "recordedAt": "2026-09-28T07:41:00.000Z",
  "retiredAt": null,
  "sources": [
   {
    "id": "0196b700-0000-7000-8000-000000000011-s1",
    "kind": "turn",
    "ref": "0196b700-0000-7000-8000-000000000031",
    "locator": {
     "seq": 12,
     "turnId": "0196b700-0000-7000-8000-000000000032"
    },
    "quote": "CDP 截图开 captureBeyondViewport 会触发重排导致横向偏移；应设 false 并按元素 rect 裁切。",
    "quoteVerified": true,
    "state": "live",
    "tainted": false,
    "createdAt": "2026-09-28T07:41:00.000Z"
   }
  ],
  "history": [
   {
    "id": "0196b700-0000-7000-8000-000000000011-r1",
    "entryId": "0196b700-0000-7000-8000-000000000011",
    "revision": 1,
    "title": "captureBeyondViewport 重排致截图横向偏移",
    "summary": "CDP 截图开 captureBeyondViewport 会触发重排导致横向偏移；应设 false 并按元素 rect 裁切。",
    "authorKind": "maintenance",
    "authorSessionId": null,
    "changesetOpId": null,
    "createdAt": "2026-09-28T07:41:00.000Z"
   }
  ],
  "exposure": []
 },
 "auto": {
  "id": "0196b700-0000-7000-8000-000000000012",
  "spaceId": "0196b700-0000-7000-8000-000000000001",
  "kind": "recipe",
  "status": "active",
  "trust": "auto",
  "currentRevision": 1,
  "title": "用 chromium headless 渲染 mock HTML 生成 PNG 效果图",
  "summary": "把设计稿写成 HTML，chromium --headless=new 配 --window-size 与 --force-device-scale-factor 出 PNG。",
  "fields": {
   "steps": [
    "写 HTML 设计稿",
    "chromium --headless=new --window-size=W,H --screenshot"
   ],
   "verify": {
    "command": "ls docs/mocks/*.png",
    "expectedExit": 0
   }
  },
  "topics": [
   "ui-design"
  ],
  "aliases": [],
  "anchors": [
   {
    "type": "path",
    "path": "docs/mocks/wiki",
    "check": {
     "state": "verified",
     "ref": "1588c3b444444444444444444444444444444444",
     "at": "2026-09-28T09:11:00.000Z"
    }
   }
  ],
  "anchorState": "verified",
  "anchorCheckedRef": "1588c3b444444444444444444444444444444444",
  "anchorCheckedAt": "2026-09-28T09:11:00.000Z",
  "tainted": false,
  "challenged": false,
  "unsupported": false,
  "pinned": false,
  "supersedesId": null,
  "supersededById": null,
  "validFrom": "2026-09-28T07:41:00.000Z",
  "validTo": null,
  "recordedAt": "2026-09-28T07:41:00.000Z",
  "retiredAt": null,
  "sources": [
   {
    "id": "0196b700-0000-7000-8000-000000000012-s1",
    "kind": "turn",
    "ref": "0196b700-0000-7000-8000-000000000031",
    "locator": {
     "seq": 12,
     "turnId": "0196b700-0000-7000-8000-000000000032"
    },
    "quote": "把设计稿写成 HTML，chromium --headless=new 配 --window-size 与 --force-device-scale-factor 出 PNG。",
    "quoteVerified": true,
    "state": "live",
    "tainted": false,
    "createdAt": "2026-09-28T07:41:00.000Z"
   }
  ],
  "history": [
   {
    "id": "0196b700-0000-7000-8000-000000000012-r1",
    "entryId": "0196b700-0000-7000-8000-000000000012",
    "revision": 1,
    "title": "用 chromium headless 渲染 mock HTML 生成 PNG 效果图",
    "summary": "把设计稿写成 HTML，chromium --headless=new 配 --window-size 与 --force-device-scale-factor 出 PNG。",
    "authorKind": "maintenance",
    "authorSessionId": null,
    "changesetOpId": null,
    "createdAt": "2026-09-28T07:41:00.000Z"
   }
  ],
  "exposure": [
   {
    "sessionId": "0196b700-0000-7000-8000-000000000031",
    "entryId": "0196b700-0000-7000-8000-000000000012",
    "revision": 1,
    "channel": "push",
    "at": "2026-09-28T09:21:00.000Z"
   }
  ]
 },
 "web": {
  "id": "0196b700-0000-7000-8000-000000000013",
  "spaceId": "0196b700-0000-7000-8000-000000000001",
  "kind": "decision",
  "status": "active",
  "trust": "unreviewed",
  "currentRevision": 1,
  "title": "scroll 按钮全面向 ChatGPT 对齐:40pt 空灵玻璃",
  "summary": "滚到底按钮与 ChatGPT 一致：40pt、玻璃材质、无描边。",
  "fields": {
   "context": "iOS 与 web 的滚到底按钮不一致",
   "decision": "全面向 ChatGPT 对齐：40pt 空灵玻璃",
   "consequences": "两端同一套尺寸"
  },
  "topics": [
   "ui-design"
  ],
  "aliases": [],
  "anchors": [],
  "anchorState": "unchecked",
  "anchorCheckedRef": null,
  "anchorCheckedAt": null,
  "tainted": true,
  "challenged": false,
  "unsupported": false,
  "pinned": false,
  "supersedesId": null,
  "supersededById": null,
  "validFrom": "2026-09-28T07:41:00.000Z",
  "validTo": null,
  "recordedAt": "2026-09-28T07:41:00.000Z",
  "retiredAt": null,
  "sources": [
   {
    "id": "0196b700-0000-7000-8000-000000000013-s1",
    "kind": "turn",
    "ref": "0196b700-0000-7000-8000-000000000031",
    "locator": {
     "seq": 12,
     "turnId": "0196b700-0000-7000-8000-000000000032"
    },
    "quote": "滚到底按钮与 ChatGPT 一致：40pt、玻璃材质、无描边。",
    "quoteVerified": true,
    "state": "live",
    "tainted": true,
    "createdAt": "2026-09-28T07:41:00.000Z"
   }
  ],
  "history": [
   {
    "id": "0196b700-0000-7000-8000-000000000013-r1",
    "entryId": "0196b700-0000-7000-8000-000000000013",
    "revision": 1,
    "title": "scroll 按钮全面向 ChatGPT 对齐:40pt 空灵玻璃",
    "summary": "滚到底按钮与 ChatGPT 一致：40pt、玻璃材质、无描边。",
    "authorKind": "maintenance",
    "authorSessionId": null,
    "changesetOpId": null,
    "createdAt": "2026-09-28T07:41:00.000Z"
   }
  ],
  "exposure": []
 },
 "challenged": {
  "id": "0196b700-0000-7000-8000-000000000014",
  "spaceId": "0196b700-0000-7000-8000-000000000001",
  "kind": "pitfall",
  "status": "active",
  "trust": "confirmed",
  "currentRevision": 1,
  "title": "wikiAnchorMark 读锚点状态时要带 ref",
  "summary": "已验证的锚点显示验证时的提交号，没有 ref 时写 Checked。",
  "fields": {
   "symptom": "徽章只写 Checked",
   "cause": "没有传 anchorCheckedRef",
   "fix": "把 ref 一起传进 wikiAnchorMark"
  },
  "topics": [
   "ui-design"
  ],
  "aliases": [],
  "anchors": [
   {
    "type": "symbol",
    "path": "src/web/src/lib/wiki.ts",
    "symbol": "wikiAnchorMark",
    "check": {
     "state": "changed",
     "ref": "1588c3b444444444444444444444444444444444",
     "at": "2026-09-28T09:01:00.000Z"
    }
   },
   {
    "type": "commit",
    "sha": "abcdef0222222222222222222222222222222222",
    "check": {
     "state": "missing",
     "ref": "1588c3b444444444444444444444444444444444",
     "at": "2026-09-28T09:01:00.000Z"
    }
   },
   {
    "type": "path",
    "path": "src/web/src/lib/wiki.ts",
    "check": {
     "state": "verified",
     "ref": "1588c3b444444444444444444444444444444444",
     "at": "2026-09-28T09:01:00.000Z"
    }
   }
  ],
  "anchorState": "missing",
  "anchorCheckedRef": null,
  "anchorCheckedAt": null,
  "tainted": false,
  "challenged": true,
  "unsupported": false,
  "pinned": false,
  "supersedesId": null,
  "supersededById": null,
  "validFrom": "2026-09-28T07:41:00.000Z",
  "validTo": null,
  "recordedAt": "2026-09-28T07:41:00.000Z",
  "retiredAt": null
 }
}
"""#
