/**
 * A resumed run's brief, while it waits, is listed as the TaskStart card its echo is stored with —
 * against a real PostgreSQL.
 *
 * A run request that finds its task's run paused hands that run the task's brief as a new turn of
 * the same session (`task-run:v1:<session>:<press>`, task-run-identity.ts). Once the runner echoes
 * it, the turn is drawn as the task it was built from (`taskStart`, task-start-card.ts) rather than
 * as the brief's protocol in the reader's own bubble. Until both views of the queue read their cards
 * where the echo does (sessions/turn-cards.ts), that card reached the echo alone: while the brief
 * waited — behind a turn the run was still working through, or as the next turn of a run whose
 * runner was busy or away — the queue listed it bare.
 *
 * Each case presses Run through the door production takes (`TasksService.execute`, what Run,
 * `task_start` and `orbit task start` call), so the turn under test is the one that door writes — its
 * key and its brief — not one built here to look like it. The inbox, the event ingest and the turn
 * completion are the real RunnerApiController methods, called as the runner does. At every moment the
 * brief waits, each view that lists it must carry its taskStart, and the echo must be stored with the
 * same card, compared as the JSON a client is sent.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/tasks/task-run-resume-card.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { JwtService } from '@nestjs/jwt';
import {
  CreatorType,
  type PrismaClient,
  RunStatus,
  RunnerStatus,
  SessionDispatchOrigin,
  SessionRunSource,
} from '@prisma/client';
import { RunEventType, RunStatus as SharedRunStatus } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import type { PrismaService } from '../prisma/prisma.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerOrchestrationAuthorizer } from '../runner-api/runner-orchestration-authorizer';
import { SessionsService } from '../sessions/sessions.service';
import type { TurnCards } from '../sessions/turn-cards';
import { taskRunResumeTurnId } from './task-run-identity';
import { TasksService } from './tasks.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

const TITLE = 'task-run 恢复 brief 排队时画成 TaskStart 卡';
const INSTRUCTIONS = 'New tests go in new files.';

/** Every card a turn can carry, by the name its echo stores it under: a brief must carry exactly one. */
const CARD_FIELDS: Record<keyof TurnCards, true> = {
  openItemDelivery: true,
  taskStart: true,
  projectStarted: true,
  confirmationReviewRequest: true,
  confirmationReturn: true,
  sessionMessage: true,
  sessionReplies: true,
};
const FIELDS = Object.keys(CARD_FIELDS) as Array<keyof TurnCards>;

/** The card fields a row or a payload carries, as a client reads them — over the wire, so a value is
 *  compared as the JSON it is sent as — with every absent field left out. */
function cardsOf(carrier: object): Partial<Record<keyof TurnCards, unknown>> {
  const fields = carrier as Record<string, unknown>;
  return Object.fromEntries(FIELDS
    .filter((field) => fields[field] !== undefined)
    .map((field) => [field, JSON.parse(JSON.stringify(fields[field]))]));
}

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

interface Run {
  ownerId: string;
  runnerId: string;
  projectId: string;
  taskId: string;
  sessionId: string;
}

test('a resumed run\'s brief waits as the TaskStart card its echo is stored with', {
  skip, concurrency: 1, timeout: 600_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });
  const db = prisma as unknown as PrismaService;

  // ── the doors ─────────────────────────────────────────────────────────────────────────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(db, queue as never, realtime as never);
  const tasks = new TasksService(db, sessions, realtime as never);
  const orchestration = new RunnerOrchestrationAuthorizer(db, new JwtService({ secret: 'task-run-resume-card-pg' }));
  const api = new RunnerApiController(
    db,
    queue as never,
    realtime as never,
    {} as never,
    orchestration,
    // The turns here carry no `#`-references and reach no list console.
    { expand: async (_owner: string, content?: string) => content } as never,
    { appendFor: async (_tx: unknown, _id: string, content?: string) => content } as never,
    undefined,
    undefined,
    tasks,
    undefined,
    sessions,
  );

  // ── the world ─────────────────────────────────────────────────────────────────────────────────

  /**
   * A task whose run is paused between turns — its opening brief answered, nothing that will wake it
   * — on a machine of its own, in a project and a list with standing instructions, so the card has
   * every part a brief can give it. `provider` is the run's engine, `machine` how its runner stands.
   */
  async function pausedRun(label: string, provider: 'claude' | 'codex', machine: RunnerStatus): Promise<Run> {
    const ownerId = randomUUID();
    const runnerId = randomUUID();
    const workspaceId = randomUUID();
    const sessionId = randomUUID();
    await prisma.user.create({
      data: { id: ownerId, email: `${label}-${ownerId}@task-run-resume-card.invalid`, name: label, passwordHash: 'x' },
    });
    await prisma.runner.create({
      data: {
        id: runnerId, ownerId, name: `${label}: the machine`, tokenHash: sha256(`token-${runnerId}`),
        status: machine, lastHeartbeatAt: new Date(), capabilities: [], capabilitiesReportedAt: new Date(),
      },
    });
    await prisma.workspace.create({ data: { id: workspaceId, ownerId, runnerId, name: `${label}-agent`, enabled: true } });
    const project = await prisma.project.create({
      data: { ownerId, title: '统一排队与已投递消息的卡片渲染' }, select: { id: true },
    });
    const list = await prisma.taskList.create({
      data: { ownerId, title: 'card work', instructions: INSTRUCTIONS }, select: { id: true },
    });
    const task = await prisma.task.create({
      data: {
        ownerId, projectId: project.id, listId: list.id, assigneeId: workspaceId, title: TITLE,
        description: '在已有会话上恢复运行的任务，brief 排队时也画成 TaskStart 卡。',
        acceptanceCriteria: 'the pg spec passes on an isolated database',
        creatorType: CreatorType.USER, creatorId: ownerId, completionCriterion: 'EVIDENCE_JUDGMENT',
      },
      select: { id: true },
    });
    await prisma.session.create({
      data: {
        id: sessionId, ownerId, creatorId: ownerId, taskId: task.id, workspaceId, assignedRunnerId: runnerId,
        title: `执行任务：${TITLE}`, prompt: 'the brief the run was started with', provider,
        status: RunStatus.AWAITING_INPUT, startsTaskWork: true, numTurns: 1,
        startedAt: new Date(Date.now() - 60 * 60_000), runtimeSessionId: `runtime-${sessionId}`,
        dispatchOrigin: SessionDispatchOrigin.USER, runSource: SessionRunSource.MANUAL,
      },
    });
    await prisma.conversationTurn.create({
      data: {
        sessionId, seq: 1, kind: 'message', content: 'the brief the run was started with',
        clientTurnId: SessionsService.initialTurnClientId(sessionId), status: 'ANSWERED',
      },
    });
    return { ownerId, runnerId, projectId: project.id, taskId: task.id, sessionId };
  }

  // ── what the runner and the owner do ──────────────────────────────────────────────────────────

  /** The owner's own message to the run. */
  async function ownerSays(run: Run, words: string): Promise<string> {
    return (await sessions.createTurn(run.ownerId, run.sessionId, { clientTurnId: randomUUID(), content: words })).turnId;
  }

  /**
   * What the runner's claim does to a queued session, then one poll of its inbox, from a runner that
   * can act on a steer (`acceptsSteer`) or not. Answers the turn it handed out.
   */
  async function take(run: Run, acceptsSteer = false): Promise<{ turnId: string; content: string }> {
    await prisma.session.update({ where: { id: run.sessionId }, data: { status: RunStatus.RUNNING } });
    const handed = await (api as unknown as {
      dequeueTurn: (sessionId: string, runnerId: string, leaseGeneration: string | null, acceptsSteer?: boolean)
        => Promise<Record<string, unknown> | null>;
    }).dequeueTurn.call(api, run.sessionId, run.runnerId, null, acceptsSteer);
    assert.ok(handed, `the inbox of ${run.sessionId} handed nothing out`);
    return { turnId: String(handed.turnId), content: String(handed.content ?? '') };
  }

  const seqs = new Map<string, number>();
  /** The runner's event for one turn, through the real ingest. Answers the payload that was stored. */
  async function say(run: Run, turnId: string, type: RunEventType, payload: Record<string, unknown>) {
    const seq = (seqs.get(run.sessionId) ?? 100) + 1;
    seqs.set(run.sessionId, seq);
    await api.events({ id: run.runnerId } as never, run.sessionId, {
      events: [{ seq, type, ts: new Date().toISOString(), turnId, payload }],
    } as never);
    return (await prisma.runEvent.findFirstOrThrow({ where: { sessionId: run.sessionId, seq } })).payload as Record<string, unknown>;
  }

  /** The turn ends as the runner reports it: something said, then the completion. */
  async function finish(run: Run, turnId: string) {
    await say(run, turnId, RunEventType.ASSISTANT, { text: 'Rebased.' });
    await api.turnComplete({ id: run.runnerId } as never, run.sessionId, {
      turnId, status: SharedRunStatus.SUCCEEDED, subtype: 'success', numTurns: 1, costUsd: 0,
    } as never);
  }

  /**
   * The window between a press's decision and its write. The press read the run as paused and
   * planned to hand it the brief (`planWorkspaceRun`); before that write lands (`applyWorkspaceRun`
   * → `SessionsService.resume`), the owner's message reaches the run and its runner takes it. Nothing
   * in the write reads the run again, so the brief arrives while the run works on that turn — the way
   * a press reaches a busy run, since a press that READS the run busy is refused
   * (TASK_ALREADY_RUNNING). Installed for one write; answers the turn the run is working on.
   */
  function ownerGetsInFirst(run: Run, words: string): () => string {
    let working: string | undefined;
    const resume = sessions.resume.bind(sessions);
    sessions.resume = (async (...args: Parameters<SessionsService['resume']>) => {
      sessions.resume = resume;
      working = await ownerSays(run, words);
      const taken = await take(run);
      assert.equal(taken.turnId, working, 'the runner took another turn than the owner\'s');
      await say(run, working, RunEventType.USER, { text: taken.content });
      return resume(...args);
    }) as SessionsService['resume'];
    return () => {
      assert.ok(working, 'the press never reached its write');
      return working;
    };
  }

  /** Run, pressed by the owner. It must continue the paused run rather than open another. */
  async function pressRun(run: Run, press: string): Promise<void> {
    const answer = await tasks.execute(run.ownerId, run.taskId, undefined, press);
    assert.equal(answer.ok, true, `Run was refused: ${JSON.stringify(answer)}`);
    assert.equal(answer.sessionId, run.sessionId, 'Run did not continue the paused run');
  }

  /** The turn the press wrote, under the key it names. */
  function briefOf(run: Run, press: string) {
    return prisma.conversationTurn.findUniqueOrThrow({
      where: { sessionId_clientTurnId: { sessionId: run.sessionId, clientTurnId: taskRunResumeTurnId(press, run.sessionId) } },
    });
  }

  async function queueRow(run: Run, turnId: string) {
    const row = (await sessions.listQueuedTurns(run.ownerId, run.sessionId)).find((each) => each.turnId === turnId);
    assert.ok(row, 'the queue view does not list the waiting brief');
    return row;
  }

  async function activeRow(run: Run, turnId: string) {
    const row = (await sessions.listQueuedTurns(run.ownerId, run.sessionId, 'active')).find((each) => each.turnId === turnId);
    assert.ok(row, 'the active view does not list the waiting brief');
    return row;
  }

  /** The first reading of a waiting brief: the one card it carries, and that card is this task's. */
  function cardOfTheTask(carrier: object, run: Run, where: string): Partial<Record<keyof TurnCards, unknown>> {
    const cards = cardsOf(carrier);
    assert.deepEqual(Object.keys(cards), ['taskStart'], `${where} does not list the waiting brief as its TaskStart card`);
    const card = cards.taskStart as Record<string, unknown>;
    assert.equal(card.taskId, run.taskId);
    assert.equal(card.title, TITLE);
    assert.deepEqual(card.project, { id: run.projectId, title: '统一排队与已投递消息的卡片渲染' });
    assert.equal(card.listInstructions, INSTRUCTIONS);
    assert.equal(card.completionCriterion, 'EVIDENCE_JUDGMENT');
    assert.equal(card.auto, false, 'a press is not an automatic start');
    return cards;
  }

  /** Every other reading carries the same card fields, compared one by one. */
  function assertSameCards(where: string, carrier: object, expected: Partial<Record<keyof TurnCards, unknown>>) {
    const cards = cardsOf(carrier);
    for (const each of FIELDS) {
      assert.deepEqual(cards[each], expected[each], `${each}: ${where} is not the card the brief waited as`);
    }
  }

  // ── the cases ─────────────────────────────────────────────────────────────────────────────────

  await t.test('behind the turn its run is working on: queued in both views, then the accepted head, as its card throughout', async () => {
    // Codex, on a runner that has declared no turn/steer: a message that reaches the run mid-turn
    // waits behind that turn rather than being written into it (`supportsMidTurnSteer`).
    const run = await pausedRun('queued-behind', 'codex', RunnerStatus.ONLINE);
    const press = `press-${randomUUID()}`;
    const working = ownerGetsInFirst(run, 'first, rebase onto main');
    await pressRun(run, press);
    const brief = await briefOf(run, press);
    assert.equal(brief.kind, 'message', 'the brief was written into the running turn rather than queued behind it');
    assert.equal(brief.status, 'PENDING');

    const expected = cardOfTheTask(await queueRow(run, brief.id), run, 'the queue view');
    const readings: Array<[string, object]> = [];
    const queued = await activeRow(run, brief.id);
    assert.equal(queued.placement, 'queued');
    readings.push(['the active view, queued behind the running turn', queued]);

    // The owner's turn ends, and the brief is next with nobody taking it yet — its runner busy with
    // something else, or away. It is the accepted head now, a row the active view lists and the queue
    // view leaves out by its contract (`listQueuedTurns`).
    await finish(run, working());
    const head = await activeRow(run, brief.id);
    assert.equal(head.placement, 'accepted', 'the brief is not the accepted head once the turn ahead of it ended');
    readings.push(['the active view, the accepted head nobody has taken', head]);

    const handed = await take(run);
    assert.equal(handed.turnId, brief.id, 'the runner was handed another turn than the brief');
    const leased = await activeRow(run, brief.id);
    assert.equal(leased.placement, 'accepted');
    readings.push(['the active view, the accepted head the runner has', leased]);

    readings.push(['the echo', await say(run, brief.id, RunEventType.USER, { text: handed.content })]);
    for (const [where, carrier] of readings) assertSameCards(where, carrier, expected);
  });

  await t.test('a press on a paused run whose runner is away: the accepted head at once, as its card', async () => {
    const run = await pausedRun('runner-away', 'claude', RunnerStatus.OFFLINE);
    const press = `press-${randomUUID()}`;
    await pressRun(run, press);
    const brief = await briefOf(run, press);
    assert.equal(brief.status, 'PENDING');

    const waiting = await activeRow(run, brief.id);
    assert.equal(waiting.placement, 'accepted', 'the brief a paused run is handed is not the head of its queue');
    const expected = cardOfTheTask(waiting, run, 'the active view');

    // The machine comes back and takes it.
    await prisma.runner.update({ where: { id: run.runnerId }, data: { status: RunnerStatus.ONLINE, lastHeartbeatAt: new Date() } });
    const handed = await take(run);
    assert.equal(handed.turnId, brief.id, 'the runner was handed another turn than the brief');
    const leased = await activeRow(run, brief.id);
    assert.equal(leased.placement, 'accepted');
    assertSameCards('the active view, the accepted head the runner has', leased, expected);
    assertSameCards('the echo', await say(run, brief.id, RunEventType.USER, { text: handed.content }), expected);
  });

  await t.test('mid-turn on an engine that takes a steer: on its way into the running turn, as its card', async () => {
    // Claude folds a message that reaches it mid-turn into the turn it is running
    // (`supportsMidTurnSteer`), so there the brief is a steer — not waiting its turn but on its way
    // into this one — and both views list it as one until the runner takes it.
    const run = await pausedRun('steered', 'claude', RunnerStatus.ONLINE);
    const press = `press-${randomUUID()}`;
    const working = ownerGetsInFirst(run, 'first, rebase onto main');
    await pressRun(run, press);
    const brief = await briefOf(run, press);
    assert.equal(brief.kind, 'steer', 'the brief was queued behind the running turn rather than written into it');
    // An intent-less steer names no turn (`createTurn`'s N-1 rule): it joins whichever one is running.
    const running = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: working() } });
    assert.equal(running.status, 'IN_FLIGHT');

    const expected = cardOfTheTask(await queueRow(run, brief.id), run, 'the queue view');
    const active = await activeRow(run, brief.id);
    assert.equal(active.placement, 'steer');
    assertSameCards('the active view', active, expected);

    const handed = await take(run, true);
    assert.equal(handed.turnId, brief.id, 'the runner was handed another turn than the brief');
    assertSameCards('the echo', await say(run, brief.id, RunEventType.USER, { text: handed.content, steer: true }), expected);
  });
});
