/**
 * Interrupting a session takes the payload of every `bg-wake:` turn it deletes with it.
 *
 * The other half of `background-wake-withdraw.pg.spec.ts`. A control-plane wake turn carries nobody's
 * words: what it delivers lives in `background_job_wake` and `session_scheduled_wakeup`, keyed by the
 * turn's `client_turn_id` and written into the content only at the claim. `SessionsService.interrupt`
 * deletes every follow-up queued behind the turn it stops — stopping means stop — and a wake turn is
 * one of them, so it reaches the same payload a withdrawal does, in bulk instead of by name, and it
 * settled only the Watch half of it (`deadLetterQueuedWatchWakes`). Against real PostgreSQL, the real
 * runner door and the real scheduled-wakeup worker:
 *
 *   1. A due wakeup filed onto an interrupted turn does not stay DELIVERED against a turn that no
 *      longer exists. It is CANCELLED — called off before it woke anybody, the state a
 *      `schedule_wakeup({stop: true})` writes, and the one a withdrawal writes — and the worker that
 *      only ever scans PENDING agrees: a later drain files nothing and opens no turn. DROPPED would
 *      be the other thing it could say, and it would be untrue: an interrupted session has not ended.
 *   2. An interrupted turn's job wakes do not come back. `background_job_wake` is unique on
 *      `(session_id, client_turn_id, job_id)` and a job's wake turn is keyed by the job itself, so a
 *      row left behind would be found, updated and delivered by that job's NEXT wake. The turn the
 *      next wake opens carries that wake alone.
 *   3. The negative control: interrupting a session whose queue holds an ordinary message behaves
 *      exactly as it did — and reaches nothing carried by a turn it does not delete, neither the wake
 *      turn the runner had already taken in that same session nor another session's queued one.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/sessions/background-wake-interrupt.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { type Prisma, type PrismaClient, RunStatus, SessionDispatchOrigin } from '@prisma/client';
import { uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { publicIdHeaders } from '../common/public-id-headers';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { AttemptBudgetMeterService } from '../projects/attempt-budget-meter.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { PushService } from '../push/push.service';
import { QueueService } from '../queue/queue.service';
import { RealtimeService } from '../realtime/realtime.service';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerOrchestrationAuthorizer } from '../runner-api/runner-orchestration-authorizer';
import { ScheduledWakeupWorker } from '../runner-api/scheduled-wakeup.worker';
import { ListEventsService } from '../task-lists/list-events.service';
import { ReferenceExpansionService } from '../tasks/reference-expansion';
import { TasksService } from '../tasks/tasks.service';
import { MergeReceiptService } from './merge-receipt.service';
import { SessionsService } from './sessions.service';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a session row carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The runner credential, in the clear. Its hash is what `RunnerAuthGuard` matches. */
const RUNNER_TOKEN = 'the-runner-token-for-interrupted-wakes';

const HOUR = 60 * 60 * 1000;

/** A response, kept as text as well as JSON: a body that failed to parse has to be readable. */
interface Answer {
  status: number;
  text: string;
  json: Record<string, unknown>;
}

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

/** What the runner reports when a job that asked to be woken for its exit has exited. */
function exitWake(jobId: string, fields: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    wakeId: `${jobId}:exit`,
    jobId,
    trigger: 'exit',
    kind: 'watch',
    command: 'gh run watch 4242 --exit-status',
    status: 'completed',
    exitCode: 0,
    outputPath: `/root/.orbit/runs/interrupt-spec/${jobId}.output`,
    outputOffset: 0,
    outputSize: 512,
    outputExcerpt: 'the wake that was interrupted',
    ...fields,
  };
}

test('an interrupt takes the payload of the wake turns it deletes with it', {
  skip, concurrency: 1, timeout: 300_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  let app: INestApplication | undefined;
  t.after(async () => {
    await app?.close().catch(() => undefined);
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  const ownerId = randomUUID();
  const runnerId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `interrupt-${ownerId}@wake-turn.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: { id: runnerId, name: 'the machine the jobs run on', ownerId, tokenHash: sha256(RUNNER_TOKEN) },
  });

  /** A session on this runner, parked between turns: the state a long wait leaves it in. */
  async function session(data: Partial<Prisma.SessionUncheckedCreateInput> = {}): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id,
        ownerId,
        creatorId: ownerId,
        title: 'a session parked on something that takes a while',
        prompt: 'wait for the build and tell me how it went',
        provider: 'claude',
        status: RunStatus.AWAITING_INPUT,
        dispatchOrigin: SessionDispatchOrigin.USER,
        startsTaskWork: false,
        assignedRunnerId: runnerId,
        numTurns: 1,
        ...data,
      },
    });
    return id;
  }

  /**
   * A session with a turn the engine is running: what an interrupt is for. The wake turns below queue
   * behind it, which is the shape the bug lives in — a job's wake or a due wakeup arriving while the
   * agent is working, and the owner pressing stop.
   */
  async function sessionRunningATurn(): Promise<{ sessionId: string; running: string }> {
    const sessionId = await session({ status: RunStatus.RUNNING });
    const running = randomUUID();
    await sql.query(
      `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","kind","content","status","delivered_at","lease_deadline_at")
       VALUES ($1,$2,1,$3,'message','the turn the session is running','IN_FLIGHT',now(),now() + interval '10 minutes')`,
      [running, sessionId, `current-${running}`],
    );
    return { sessionId, running };
  }

  // ── the app: the real runner door, its guard, main.ts's middleware and interceptor ─────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(prisma as unknown as PrismaService, queue as never, realtime as never);
  // Never started: a case delivers what is due by calling drain() itself.
  const wakeups = new ScheduledWakeupWorker(prisma as unknown as PrismaService, sessions, { pollIntervalMs: HOUR });
  @Module({
    controllers: [RunnerApiController],
    providers: [
      { provide: PrismaService, useValue: prisma },
      { provide: QueueService, useValue: queue },
      { provide: SessionsService, useValue: sessions },
      { provide: RealtimeService, useValue: realtime },
      { provide: PushService, useValue: silent() },
      { provide: RunnerOrchestrationAuthorizer, useValue: {} },
      // A wake has no `#`-references to expand and no list console to report into.
      { provide: ReferenceExpansionService, useValue: { expand: async (_owner: string, content?: string) => content } },
      { provide: ListEventsService, useValue: { appendFor: async (_tx: unknown, _id: string, content?: string) => content } },
      { provide: AttemptBudgetMeterService, useValue: {} },
      { provide: ProjectAcceptanceService, useValue: {} },
      { provide: TasksService, useValue: {} },
      { provide: MergeReceiptService, useValue: {} },
      RunnerAuthGuard,
    ],
  })
  class RunnerDoor {}

  app = await NestFactory.create(RunnerDoor, { logger: false, abortOnError: false });
  app.use(publicIdHeaders);
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
  app.useGlobalInterceptors(new PublicIdInterceptor());
  await app.listen(0, '127.0.0.1');
  const base = await app.getUrl();

  async function send(method: 'GET' | 'POST', route: string, body?: unknown): Promise<Answer> {
    const response = await fetch(`${base}/api${route}`, {
      method,
      headers: {
        authorization: `Bearer ${RUNNER_TOKEN}`,
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    const text = await response.text();
    let json: Record<string, unknown> = {};
    try { json = JSON.parse(text) as Record<string, unknown>; } catch { /* asserted on by the caller */ }
    return { status: response.status, text, json };
  }

  const wake = (sessionId: string, body: Record<string, unknown>): Promise<Answer> =>
    send('POST', `/runner/sessions/${uuidToBase62(sessionId)}/background-wake`, body);

  const turnsOf = (sessionId: string) =>
    prisma.conversationTurn.findMany({ where: { sessionId }, orderBy: { seq: 'asc' } });

  /** The session's `bg-wake:` turns, which is what an interrupt deletes and this spec is about. */
  async function wakeTurnsOf(sessionId: string) {
    const turns = await turnsOf(sessionId);
    return turns.filter((turn) => turn.clientTurnId.startsWith('bg-wake:'));
  }

  /** What the runner's claim does to a queued session, then the inbox poll that follows it. */
  async function claimAndPoll(sessionId: string): Promise<Answer> {
    await prisma.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    return send('GET', `/runner/sessions/${uuidToBase62(sessionId)}/inbox`);
  }

  /** The aborted turn ends: what turn-complete writes when the engine finally reports it. */
  async function abortedTurnEnds(turnId: string): Promise<void> {
    await sql.query(`UPDATE "conversation_turn" SET "status" = 'ANSWERED', "answered_at" = now() WHERE "id" = $1`, [turnId]);
  }

  /**
   * The wakeup the agent asked for, made due. `schedule_wakeup`'s floor is a minute out, so the row
   * is written by the production door and then backdated here rather than inserted by hand: what the
   * worker reads is a row the door really wrote.
   */
  async function wakeupDueNow(sessionId: string, reason: string, prompt: string): Promise<string> {
    const held = await send('POST', `/runner/sessions/${uuidToBase62(sessionId)}/scheduled-wakeup`, {
      delaySeconds: 60, reason, prompt,
    });
    assert.equal(held.status, 200, `scheduled-wakeup answered ${held.status}: ${held.text}`);
    assert.equal(held.json.outcome, 'SCHEDULED', held.text);
    // Read the row rather than the receipt's id: the public-id interceptor rewrites what the door
    // answers, and what is wanted here is the primary key the worker reads.
    const { id } = await prisma.sessionScheduledWakeup.findFirstOrThrow({ where: { sessionId, state: 'PENDING' } });
    await sql.query(`UPDATE "session_scheduled_wakeup" SET "due_at" = now() - interval '1 second' WHERE "id" = $1`, [id]);
    return id;
  }

  const wakeupRow = async (id: string) =>
    prisma.sessionScheduledWakeup.findUniqueOrThrow({ where: { id } });

  await t.test('a wakeup filed onto an interrupted turn is cancelled, not left pointing at nothing', async () => {
    const { sessionId, running } = await sessionRunningATurn();
    const wakeupId = await wakeupDueNow(sessionId, 'watching the deploy', 'check whether the rollout finished');

    assert.deepEqual(await wakeups.drain(), ['DELIVERED'], 'the due wakeup was not filed as a turn');
    const [turn] = await wakeTurnsOf(sessionId);
    assert.ok(turn, 'the due wakeup opened no turn');
    assert.equal(turn.clientTurnId, `bg-wake:wakeup:${wakeupId}`);
    assert.equal(turn.status, 'PENDING', 'the wake turn was not queued behind the running one');
    const filed = await wakeupRow(wakeupId);
    assert.equal(filed.state, 'DELIVERED');
    assert.equal(filed.clientTurnId, turn.clientTurnId, 'the wakeup was not settled onto the turn that carries it');

    // Stop, through the production door — no follow-up, just the interrupt itself.
    assert.deepEqual(await sessions.interrupt(ownerId, sessionId), { ok: true });
    assert.deepEqual(await wakeTurnsOf(sessionId), [], 'the interrupt left the wake turn queued');
    // An interrupt stops a turn; the session lives on, which is what makes the state below a choice.
    const after = await prisma.session.findUniqueOrThrow({ where: { id: sessionId } });
    assert.equal(after.status, RunStatus.RUNNING, 'the interrupt ended the session');
    const [aborted] = (await turnsOf(sessionId)).filter((row) => row.id === running);
    assert.equal(aborted?.status, 'IN_FLIGHT', 'the interrupt deleted the turn it was stopping');

    // THE STATE IT LANDS IN: cancelled — called off before it woke anybody — and still naming the
    // turn it had been filed onto. Not DROPPED: that is the worker's word for a session that had
    // already ended, and this one is stopped, not gone.
    const settled = await wakeupRow(wakeupId);
    assert.equal(settled.state, 'CANCELLED',
      `an interrupted wakeup was left ${settled.state}: DELIVERED points at a turn that no longer exists, `
      + 'and PENDING would re-file the identical turn on the next pass');
    assert.ok(settled.settledAt, 'the cancelled wakeup records no settling time');
    assert.equal(settled.clientTurnId, turn.clientTurnId, 'nothing records which turn it had been filed onto');

    // AND THE WORKER AGREES WITH THAT STATE. It scans PENDING alone, so a cancelled wakeup is not
    // due again — no second turn, however many passes reach it, and the session the owner stopped
    // is not started back up.
    assert.deepEqual(await wakeups.drain(), [], 'an interrupted wakeup was delivered again');
    assert.deepEqual(await wakeups.drain(), [], 'an interrupted wakeup was delivered again');
    assert.deepEqual(await wakeTurnsOf(sessionId), [], 'the interrupted wakeup came back as a turn');
  });

  await t.test('an interrupted turn\'s job wakes do not come back with the job\'s next wake', async () => {
    const { sessionId, running } = await sessionRunningATurn();
    const build = 'bgj_444444444444';
    const deploy = 'bgj_555555555555';

    // One turn, two jobs: the second wake joins the first's turn, so its row is keyed by the turn
    // the FIRST job opened — `bg-wake:<build>:exit`, the same string the build's next wake computes.
    const opened = await wake(sessionId, exitWake(build, {
      status: 'failed', exitCode: 1, outputExcerpt: 'the build wake that was interrupted',
    }));
    assert.equal(opened.json.outcome, 'ENQUEUED', opened.text);
    const joined = await wake(sessionId, exitWake(deploy, { outputExcerpt: 'the deploy wake that was interrupted' }));
    assert.equal(joined.json.outcome, 'MERGED', joined.text);
    const queuedTurns = await wakeTurnsOf(sessionId);
    assert.equal(queuedTurns.length, 1, 'the two wakes opened more than one turn');
    const [interrupted] = queuedTurns;
    assert.equal(interrupted.clientTurnId, `bg-wake:${build}:exit`);
    assert.equal(
      await prisma.backgroundJobWake.count({ where: { sessionId, clientTurnId: interrupted.clientTurnId } }), 2,
      'the two wakes were not filed onto the one turn',
    );

    assert.deepEqual(await sessions.interrupt(ownerId, sessionId), { ok: true });
    assert.deepEqual(await wakeTurnsOf(sessionId), [], 'the interrupt left the wake turn queued');
    assert.equal(
      await prisma.backgroundJobWake.count({ where: { sessionId } }), 0,
      'the interrupted turn left its wakes behind, under the key the next wake of the same job reuses',
    );

    // The build's ending is reported again — a runner that restarted and re-read the job it adopted,
    // quoting further into the same output. Its wake id is the same stable string, so the turn it
    // opens carries the same client_turn_id the interrupted one did.
    const again = await wake(sessionId, exitWake(build, {
      outputOffset: 512, outputSize: 900, status: 'failed', exitCode: 1, outputExcerpt: 'the build wake that came after',
    }));
    assert.equal(again.status, 200, `background-wake answered ${again.status}: ${again.text}`);
    assert.equal(again.json.outcome, 'ENQUEUED', again.text);
    const [reopened] = await wakeTurnsOf(sessionId);
    assert.equal(reopened.clientTurnId, `bg-wake:${build}:exit`);

    // The stopped turn ends, and the new wake turn is what the runner is handed next — after the
    // interrupt frame itself, which every poll hands out first.
    await abortedTurnEnds(running);
    const stop = await claimAndPoll(sessionId);
    assert.equal(stop.json.kind, 'interrupt', `the inbox handed out something other than the stop: ${stop.text}`);
    const delivered = await claimAndPoll(sessionId);
    assert.equal(delivered.status, 200, `inbox answered ${delivered.status}: ${delivered.text}`);
    assert.equal(delivered.json.kind, 'message', `the inbox handed out something else: ${delivered.text}`);
    assert.equal(delivered.json.seq, reopened.seq, `the inbox handed out another turn: ${delivered.text}`);
    const content = String(delivered.json.content ?? '');
    assert.ok(content.includes('the build wake that came after'), `the new turn does not carry the new wake:\n${content}`);
    assert.ok(content.includes('exit code 1'), `the new turn does not carry how the job ended:\n${content}`);
    for (const gone of ['the build wake that was interrupted', 'the deploy wake that was interrupted', deploy]) {
      assert.ok(!content.includes(gone), `an interrupted wake was delivered again: ${gone}\n${content}`);
    }
    assert.ok(content.includes('bytes 512–900'),
      `the new turn covers output the interrupted wake had already reported:\n${content}`);
  });

  await t.test('interrupting an ordinary message is unchanged, and reaches no wake it does not delete', async () => {
    // Another session of the same owner on the same runner, with a wake turn queued: nobody
    // interrupts it, and an interrupt of one session must not reach another's payload.
    const bystander = await session();
    const bystanderWake = await wake(bystander, exitWake('bgj_666666666666', { outputExcerpt: 'the bystander\'s wake' }));
    assert.equal(bystanderWake.json.outcome, 'ENQUEUED', bystanderWake.text);
    const bystanderWakeupId = await wakeupDueNow(bystander, 'the bystander\'s wakeup', 'pick the thread back up');
    assert.deepEqual(await wakeups.drain(), ['DELIVERED'], 'the bystander\'s wakeup was not filed');

    // The session to be interrupted: its wake turn is one the RUNNER ALREADY TOOK, so the interrupt
    // does not delete it — the engine received it, and what that run comes to is the session's to say.
    const sessionId = await session();
    const taken = await wake(sessionId, exitWake('bgj_777777777777', { outputExcerpt: 'the wake the runner took' }));
    assert.equal(taken.json.outcome, 'ENQUEUED', taken.text);
    const wakeupId = await wakeupDueNow(sessionId, 'the wakeup the runner took', 'carry on where you left off');
    assert.deepEqual(await wakeups.drain(), ['DELIVERED'], 'the due wakeup was not filed');
    const [wakeTurn] = await wakeTurnsOf(sessionId);
    assert.equal((await wakeupRow(wakeupId)).clientTurnId, wakeTurn.clientTurnId, 'the wakeup joined another turn');
    const handed = await claimAndPoll(sessionId);
    assert.equal(handed.status, 200, `inbox answered ${handed.status}: ${handed.text}`);
    assert.equal(handed.json.seq, wakeTurn.seq, `the inbox handed out another turn: ${handed.text}`);
    for (const fact of ['the wake the runner took', 'the wakeup the runner took', 'carry on where you left off']) {
      assert.ok(String(handed.json.content ?? '').includes(fact), `the wake turn does not say ${fact}: ${handed.text}`);
    }

    // And an ordinary message queued behind it, which is all the interrupt has to delete.
    const message = await sessions.createTurn(ownerId, sessionId, {
      clientTurnId: randomUUID(),
      content: 'never mind the build, look at the flaky test instead',
      intent: 'NEXT_TURN',
    });
    assert.ok(message.turnId, `the message was not queued: ${JSON.stringify(message)}`);

    // What interrupting has always done: the queued message goes, the turn being stopped stays in
    // flight, the interrupt itself is recorded, and the session lives on.
    assert.deepEqual(await sessions.interrupt(ownerId, sessionId), { ok: true });
    const left = await turnsOf(sessionId);
    assert.deepEqual(
      left.map((row) => ({ kind: row.kind, status: row.status })),
      [{ kind: 'message', status: 'IN_FLIGHT' }, { kind: 'interrupt', status: 'PENDING' }],
      'interrupting took something other than the queued message off the queue',
    );
    assert.equal(left[0].id, wakeTurn.id, 'the interrupt deleted the wake turn the runner had taken');
    assert.ok(!left.some((row) => row.id === message.turnId), 'the queued message was not deleted');
    assert.equal((await prisma.session.findUniqueOrThrow({ where: { id: sessionId } })).status, RunStatus.RUNNING);

    // The payload of the turn it did not delete is untouched: the engine has it.
    assert.equal((await wakeupRow(wakeupId)).state, 'DELIVERED',
      'the interrupt settled a wakeup carried by the turn the runner had already taken');
    assert.equal(await prisma.backgroundJobWake.count({ where: { sessionId } }), 1,
      'the interrupt deleted a wake carried by the turn the runner had already taken');

    // …and so is the other session's, which this interrupt had no business reaching.
    const [stillQueued] = await wakeTurnsOf(bystander);
    assert.equal(stillQueued?.status, 'PENDING', 'another session lost its queued wake turn');
    assert.equal((await wakeupRow(bystanderWakeupId)).state, 'DELIVERED', 'another session\'s wakeup was cancelled');
    assert.equal(await prisma.backgroundJobWake.count({ where: { sessionId: bystander } }), 1,
      'another session\'s queued wake was deleted');
  });
});
