/**
 * A transient failure of the turn a background job's exit was written into re-sends THAT turn — against
 * a real PostgreSQL.
 *
 * A job that ends while its session is running a turn is written into that turn as a CURRENT_WORK steer
 * (createTurn's `steerIfLive`, runner-api/background-job-wake.ts), and the runner echoes the steer as its
 * `user` event. When the turn then failed on a transient provider error, the auto-retry's chooser
 * (auto-retry.service.ts `messageToResend`) met that echo first, read it as a wake turn that had failed —
 * nobody's words, nothing to re-send — and disarmed: the person's message, which is what failed, was
 * never re-sent. A wake STEER is followed to the turn it joined, as any CURRENT_WORK steer is and as a
 * reply steer is (session-reply-steer.pg.spec.ts, 32); a wake that is a turn of its own still re-sends
 * nothing:
 *
 *   1. the turn a job's exit was steered into fails on a 529, and the retry re-sends that turn — a new
 *      `auto-retry:` turn carrying its words — whether the steer was written off unread when the turn
 *      failed, or the engine had read it and carried on;
 *   2. a steer that missed its turn — at the target's completion (requeueUnreadCurrentWorkSteers), or
 *      handed back by the runner (steer_requeue) — is a wake turn of its own again, and when that turn
 *      fails on a 529 the retry re-sends nothing: least of all the person's message before it, which
 *      was answered.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/sessions/background-wake-steer-retry.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import {
  type PrismaClient,
  RunStatus,
  RunnerStatus,
  SessionDispatchOrigin,
  SessionRunSource,
} from '@prisma/client';
import {
  RunEventType,
  RunStatus as SharedRunStatus,
  SESSION_CURRENT_WORK_ROUTING_V1,
  TURN_COMPLETE_STEER_REQUEUE,
} from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { BACKGROUND_WAKE_TURN_PREFIX, type BackgroundWakeDto } from '../runner-api/background-job-wake';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { AutoRetryService } from './auto-retry.service';
import { SessionsService } from './sessions.service';
import { AUTO_RETRY_TURN_KEY_PREFIX } from './watch-turn-key';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a session row carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;
const HOUR = 60 * 60 * 1000;
const ROUTING = [SESSION_CURRENT_WORK_ROUTING_V1];
const OVERLOADED = 'API Error: 529 {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}';

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

/** One job's exit, as runner-go reports it. */
function exitWake(jobId: string): BackgroundWakeDto {
  return {
    wakeId: `${jobId}:exit`,
    jobId,
    trigger: 'exit',
    kind: 'build',
    command: 'npm run build',
    description: 'the release build',
    status: 'failed',
    exitCode: 2,
    outputPath: `/root/.orbit/runs/${jobId}.output`,
    outputOffset: 0,
    outputSize: 4096,
    outputExcerpt: 'make: *** [build] Error 2',
  } as BackgroundWakeDto;
}

test('a transient failure of the turn a job\'s exit was steered into re-sends that turn', {
  skip, concurrency: 1, timeout: 600_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });
  const db = prisma as unknown as PrismaService;

  // ── the world: one account, one machine that declared routing-v1, one workspace ─────────────────
  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const workspaceId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `background-wake-steer-retry-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: {
      id: runnerId, ownerId, name: 'the machine every session runs on', tokenHash: sha256(`token-${runnerId}`),
      status: RunnerStatus.ONLINE, lastHeartbeatAt: new Date(), capabilities: ROUTING, capabilitiesReportedAt: new Date(),
    },
  });
  await prisma.workspace.create({ data: { id: workspaceId, ownerId, runnerId, name: 'orbit-worker', enabled: true } });
  const runner = { id: runnerId, ownerId };
  /** The runner says it is alive: a sweep releases no retry onto a machine it believes is down. */
  const heartbeat = () => prisma.runner.update({ where: { id: runnerId }, data: { lastHeartbeatAt: new Date() } });

  /** A Claude session on this runner, parked between turns. */
  async function session(title: string): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id, ownerId, creatorId: ownerId, workspaceId, assignedRunnerId: runnerId,
        title, prompt: title, provider: 'claude', status: RunStatus.AWAITING_INPUT,
        numTurns: 1, startedAt: new Date(), runtimeSessionId: `runtime-${id}`,
        dispatchOrigin: SessionDispatchOrigin.USER, runSource: SessionRunSource.MANUAL,
      },
    });
    return id;
  }

  // ── the doors ─────────────────────────────────────────────────────────────────────────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(db, queue as never, realtime as never);
  const api = new RunnerApiController(
    db,
    queue as never,
    realtime as never,
    silent() as never,
    {} as never,
    // The messages here carry no `#`-references and reach no list console.
    { expand: async (_owner: string, content?: string) => content } as never,
    { appendFor: async (_tx: unknown, _id: string, content?: string) => content } as never,
    undefined,
    undefined,
    undefined,
    undefined,
    sessions,
  );
  const retries = new AutoRetryService(db, sessions, realtime as never);

  /** The claim, then the polls after it until a message comes out (a control turn is answered on the spot). */
  async function deliver(sessionId: string): Promise<{ turnId: string; content: string }> {
    await prisma.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    for (;;) {
      const handed = await (api as unknown as {
        dequeueTurn: (sessionId: string, runnerId: string, leaseGeneration: string | null) => Promise<Record<string, unknown> | null>;
      }).dequeueTurn.call(api, sessionId, runnerId, null);
      assert.ok(handed, `the inbox of ${sessionId} handed nothing out`);
      const turn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: String(handed.turnId) } });
      if (turn.kind !== 'message') continue;
      return { turnId: turn.id, content: String(handed.content ?? '') };
    }
  }

  /** The runner's claim of a steer, as a poller that can write one into the running turn and declared routing-v1. */
  async function deliverSteer(sessionId: string): Promise<{ turnId: string; content: string }> {
    const handed = await (api as unknown as {
      dequeueTurn: (
        sessionId: string, runnerId: string, leaseGeneration: string | null, acceptsSteer: boolean,
        declaredCapabilities: readonly string[],
      ) => Promise<Record<string, unknown> | null>;
    }).dequeueTurn.call(api, sessionId, runnerId, null, true, ROUTING);
    assert.ok(handed, `the inbox of ${sessionId} handed no steer out`);
    const turn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: String(handed.turnId) } });
    assert.equal(turn.kind, 'steer', `the inbox handed out a ${turn.kind}, not the steer`);
    return { turnId: turn.id, content: String(handed.content ?? '') };
  }

  const seqs = new Map<string, number>();
  /** The runner's events for one turn, through the real ingest. */
  async function say(sessionId: string, turnId: string, type: RunEventType, payload: Record<string, unknown>) {
    const seq = (seqs.get(sessionId) ?? 100) + 1;
    seqs.set(sessionId, seq);
    await api.events({ id: runnerId } as never, sessionId, {
      events: [{ seq, type, ts: new Date().toISOString(), turnId, payload }],
    } as never);
  }

  /** The turn ends as the runner reports it: the engine's answer, then the completion. */
  async function finish(sessionId: string, turnId: string, words: string) {
    await say(sessionId, turnId, RunEventType.ASSISTANT, { text: words });
    await api.turnComplete({ id: runnerId } as never, sessionId, {
      turnId, status: SharedRunStatus.SUCCEEDED, subtype: 'success', numTurns: 1, costUsd: 0,
    } as never);
  }

  /** The provider is overloaded mid-turn: the error the engine reports, then the failed completion. */
  async function overloaded(sessionId: string, turnId: string) {
    await say(sessionId, turnId, RunEventType.ASSISTANT, { text: OVERLOADED });
    await api.turnComplete({ id: runnerId } as never, sessionId, {
      turnId, status: SharedRunStatus.FAILED, subtype: 'error_during_execution',
      numTurns: 1, costUsd: 0, error: OVERLOADED,
    } as never);
    const failed = await prisma.session.findUniqueOrThrow({ where: { id: sessionId } });
    assert.equal(failed.status, RunStatus.FAILED);
    assert.ok(failed.retryAt, 'the overload armed no retry');
  }

  /** A person's message, handed to the engine and echoed: the turn a job's exit will join. */
  async function running(sessionId: string, words: string): Promise<string> {
    await sessions.createTurn(ownerId, sessionId, { clientTurnId: randomUUID(), content: words });
    const turn = await deliver(sessionId);
    await say(sessionId, turn.turnId, RunEventType.USER, { text: turn.content });
    return turn.turnId;
  }

  /** A job exits while `target` runs: a CURRENT_WORK steer aimed at it, its block written in at delivery. */
  async function jobExits(sessionId: string, target: string, jobId: string): Promise<string> {
    const receipt = await api.backgroundWake(runner, sessionId, exitWake(jobId));
    assert.equal(receipt.outcome, 'ENQUEUED');
    const steer = await turnRow(receipt.turnId!);
    assert.deepEqual(
      [steer.kind, steer.sendIntent, steer.targetTurnId, steer.clientTurnId, steer.content],
      ['steer', 'CURRENT_WORK', target, `${BACKGROUND_WAKE_TURN_PREFIX}${jobId}:exit`, ''],
    );
    return steer.id;
  }

  /** The runner writes the steer into the running turn and echoes it: the last message it recorded. */
  async function writtenIn(sessionId: string, steer: string) {
    const handed = await deliverSteer(sessionId);
    assert.equal(handed.turnId, steer);
    await say(sessionId, steer, RunEventType.USER, { text: handed.content, steer: true, delivery: 'enqueued' });
  }

  /** The auto-retry's sweep, with the retry due and the runner alive. */
  async function sweep(sessionId: string) {
    await prisma.session.update({ where: { id: sessionId }, data: { retryAt: new Date(Date.now() - HOUR) } });
    await heartbeat();
    await retries.sweep();
  }

  const turnRow = (id: string) => prisma.conversationTurn.findUniqueOrThrow({ where: { id } });
  const resentOf = (sessionId: string) => prisma.conversationTurn.findMany({
    where: { sessionId, clientTurnId: { startsWith: AUTO_RETRY_TURN_KEY_PREFIX } },
  });

  // ── 1. the turn the wake was steered into fails ───────────────────────────────────────────────

  await t.test('the turn a job\'s exit was steered into fails, the steer written off unread: the retry re-sends that turn', async () => {
    const id = await session('Worker: overloaded with a job\'s exit unread in its turn');
    const words = 'ship the release once the build is green';
    const target = await running(id, words);
    const steer = await jobExits(id, target, 'bgj_r10000000001');
    await writtenIn(id, steer);
    await overloaded(id, target);
    // Written off with the turn it joined: nothing will deliver it, and it is still the steer it was.
    const off = await turnRow(steer);
    assert.deepEqual([off.kind, off.status, off.deliveryStatus], ['steer', 'ANSWERED', 'FAILED']);

    // What the failure card's Retry offers is what the sweep re-sends: the person's words.
    assert.deepEqual(await retries.retryMessage(ownerId, id), { text: words });
    await sweep(id);
    const resent = await resentOf(id);
    assert.deepEqual(resent.map((turn) => turn.content), [words],
      'the retry did not re-send the turn the job\'s exit was steered into');
    const back = await deliver(id);
    assert.equal(back.turnId, resent[0].id);
    assert.ok(back.content.startsWith(words), back.content);
  });

  await t.test('the turn a job\'s exit was steered into fails after the engine read it: the retry re-sends that turn', async () => {
    const id = await session('Worker: read a job\'s exit, carried on, then overloaded');
    const words = 'fix the failing build and push the fix';
    const target = await running(id, words);
    const steer = await jobExits(id, target, 'bgj_r20000000001');
    await writtenIn(id, steer);
    // The engine read it — the CLI's replay — and the steer is settled; the turn it joined carries on.
    await say(id, target, RunEventType.USER_DELIVERY, { turnId: steer, delivery: 'acknowledged' });
    await api.turnComplete({ id: runnerId } as never, id, {
      turnId: steer, status: SharedRunStatus.SUCCEEDED, subtype: 'steer',
    } as never);
    const read = await turnRow(steer);
    assert.deepEqual([read.kind, read.status, read.deliveryStatus], ['steer', 'ANSWERED', 'ACKNOWLEDGED']);
    await say(id, target, RunEventType.ASSISTANT, { text: 'The build failed; reading its output.' });
    await overloaded(id, target);

    assert.deepEqual(await retries.retryMessage(ownerId, id), { text: words });
    await sweep(id);
    const resent = await resentOf(id);
    assert.deepEqual(resent.map((turn) => turn.content), [words],
      'the retry did not re-send the turn the job\'s exit was steered into');
    const back = await deliver(id);
    assert.equal(back.turnId, resent[0].id);
    assert.ok(back.content.startsWith(words), back.content);
  });

  // ── 2. the wake missed its turn and failed as one of its own ──────────────────────────────────

  const missed: Array<[string, string, (id: string, target: string, steer: string) => Promise<void>]> = [
    ['missed at the target\'s completion', 'bgj_r30000000001', async (id, target, steer) => {
      // Still waiting for the runner when the turn it was aimed at ended.
      await finish(id, target, 'The index is rebuilt.');
      assert.equal((await turnRow(steer)).kind, 'message');
    }],
    ['handed back by the runner', 'bgj_r40000000001', async (id, target, steer) => {
      // Written in and echoed, then put back unread: the runner fenced the engine before it read it.
      await writtenIn(id, steer);
      await say(id, target, RunEventType.USER_DELIVERY, { turnId: steer, delivery: 'requeued' });
      await api.turnComplete({ id: runnerId } as never, id, {
        turnId: steer, status: SharedRunStatus.SUCCEEDED, subtype: TURN_COMPLETE_STEER_REQUEUE,
      } as never);
      assert.equal((await turnRow(steer)).kind, 'message');
      await finish(id, target, 'The index is rebuilt.');
    }],
  ];
  for (const [how, jobId, misses] of missed) {
    await t.test(`a job's exit ${how} fails as a wake turn of its own: the retry re-sends nothing`, async () => {
      const id = await session(`Worker: a wake ${how}, then overloaded`);
      const words = 'rebuild the search index';
      const target = await running(id, words);
      const steer = await jobExits(id, target, jobId);
      await misses(id, target, steer);
      const wake = await deliver(id);
      assert.equal(wake.turnId, steer, 'the missed wake was not the next turn handed out');
      const requeued = await turnRow(steer);
      assert.deepEqual([requeued.kind, requeued.sendIntent, requeued.targetTurnId], ['message', 'NEXT_TURN', null]);
      await say(id, wake.turnId, RunEventType.USER, { text: wake.content });
      await overloaded(id, wake.turnId);

      assert.deepEqual(await retries.retryMessage(ownerId, id), { text: '' });
      await sweep(id);
      assert.deepEqual(await resentOf(id), [], 'the retry of a failed wake re-sent the message before it');
      const after = await prisma.session.findUniqueOrThrow({ where: { id } });
      assert.equal(after.retryAt, null, 'the retry was not disarmed');
      assert.equal(after.status, RunStatus.FAILED);
    });
  }
});
