/**
 * Withdrawing a queued `bg-wake:` turn takes the payload kept beside it with it.
 *
 * A control-plane wake turn carries nobody's words: what it delivers lives in `background_job_wake`
 * and `session_scheduled_wakeup`, keyed by the turn's `client_turn_id` and written into the content
 * only at the claim. Task 34PdPgcb32YbndCchX3oT made such a turn visible to both clients, whose
 * cards already offered a withdraw, so `SessionsService.cancelQueuedTurn` can now reach one — and it
 * only ever settled the Watch half of that payload (`deadLetterQueuedWatchWakes`). Against real
 * PostgreSQL, the real runner door and the real scheduled-wakeup worker:
 *
 *   1. A due wakeup filed onto a withdrawn turn does not stay DELIVERED against a turn that no longer
 *      exists. It is CANCELLED — the state a `schedule_wakeup({stop: true})` writes — and the worker
 *      that only ever scans PENDING agrees: a later drain files nothing.
 *   2. A withdrawn turn's job wakes do not come back. `background_job_wake` is unique on
 *      `(session_id, client_turn_id, job_id)` and a job's wake turn is keyed by the job itself, so a
 *      row left behind would be found, updated and delivered by that job's NEXT wake. The turn the
 *      next wake opens carries that wake alone.
 *   3. The negative control: withdrawing an ordinary user message behaves exactly as it did — and
 *      reaches nothing of the wake turn queued beside it.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/sessions/background-wake-withdraw.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { type Prisma, type PrismaClient, RunStatus, SessionDispatchOrigin } from '@prisma/client';
import { uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { publicIdHeaders } from '../common/public-id-headers';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { AttemptBudgetMeterService } from '../projects/attempt-budget-meter.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { PushService } from '../push/push.service';
import { QueueService } from '../queue/queue.service';
import { RealtimeService } from '../realtime/realtime.service';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerOrchestrationAuthorizer } from '../runner-api/runner-orchestration-authorizer';
import { ScheduledWakeupWorker } from '../runner-api/scheduled-wakeup.worker';
import { ListEventsService } from '../task-lists/list-events.service';
import { ReferenceExpansionService } from '../tasks/reference-expansion';
import { TasksService } from '../tasks/tasks.service';
import { MergeReceiptService } from './merge-receipt.service';
import { SessionsService } from './sessions.service';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a session row carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The runner credential, in the clear. Its hash is what `RunnerAuthGuard` matches. */
const RUNNER_TOKEN = 'the-runner-token-for-withdrawn-wakes';

const HOUR = 60 * 60 * 1000;

/** A response, kept as text as well as JSON: a body that failed to parse has to be readable. */
interface Answer {
  status: number;
  text: string;
  json: Record<string, unknown>;
}

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

/** What the runner reports when a job that asked to be woken for its exit has exited. */
function exitWake(jobId: string, fields: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    wakeId: `${jobId}:exit`,
    jobId,
    trigger: 'exit',
    kind: 'watch',
    command: 'gh run watch 4242 --exit-status',
    status: 'completed',
    exitCode: 0,
    outputPath: `/root/.orbit/runs/withdraw-spec/${jobId}.output`,
    outputOffset: 0,
    outputSize: 512,
    outputExcerpt: 'the wake that was withdrawn',
    ...fields,
  };
}

test('a withdrawn wake turn takes its payload with it', {
  skip, concurrency: 1, timeout: 300_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  let app: INestApplication | undefined;
  t.after(async () => {
    await app?.close().catch(() => undefined);
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  const ownerId = randomUUID();
  const runnerId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `withdraw-${ownerId}@wake-turn.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: { id: runnerId, name: 'the machine the jobs run on', ownerId, tokenHash: sha256(RUNNER_TOKEN) },
  });

  /** A session on this runner, parked between turns: the state a long wait leaves it in. */
  async function session(data: Partial<Prisma.SessionUncheckedCreateInput> = {}): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id,
        ownerId,
        creatorId: ownerId,
        title: 'a session parked on something that takes a while',
        prompt: 'wait for the build and tell me how it went',
        provider: 'claude',
        status: RunStatus.AWAITING_INPUT,
        dispatchOrigin: SessionDispatchOrigin.USER,
        startsTaskWork: false,
        assignedRunnerId: runnerId,
        numTurns: 1,
        ...data,
      },
    });
    return id;
  }

  // ── the app: the real runner door, its guard, main.ts's middleware and interceptor ─────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(prisma as unknown as PrismaService, queue as never, realtime as never);
  // Never started: a case delivers what is due by calling drain() itself.
  const wakeups = new ScheduledWakeupWorker(prisma as unknown as PrismaService, sessions, { pollIntervalMs: HOUR });
  @Module({
    controllers: [RunnerApiController],
    providers: [
      { provide: PrismaService, useValue: prisma },
      { provide: QueueService, useValue: queue },
      { provide: SessionsService, useValue: sessions },
      { provide: RealtimeService, useValue: realtime },
      { provide: PushService, useValue: silent() },
      { provide: RunnerOrchestrationAuthorizer, useValue: {} },
      // A wake has no `#`-references to expand and no list console to report into.
      { provide: ReferenceExpansionService, useValue: { expand: async (_owner: string, content?: string) => content } },
      { provide: ListEventsService, useValue: { appendFor: async (_tx: unknown, _id: string, content?: string) => content } },
      { provide: AttemptBudgetMeterService, useValue: {} },
      { provide: ProjectAcceptanceService, useValue: {} },
      { provide: TasksService, useValue: {} },
      { provide: MergeReceiptService, useValue: {} },
      RunnerAuthGuard,
    ],
  })
  class RunnerDoor {}

  app = await NestFactory.create(RunnerDoor, { logger: false, abortOnError: false });
  app.use(publicIdHeaders);
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
  app.useGlobalInterceptors(new PublicIdInterceptor());
  await app.listen(0, '127.0.0.1');
  const base = await app.getUrl();

  async function send(method: 'GET' | 'POST', route: string, body?: unknown): Promise<Answer> {
    const response = await fetch(`${base}/api${route}`, {
      method,
      headers: {
        authorization: `Bearer ${RUNNER_TOKEN}`,
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    const text = await response.text();
    let json: Record<string, unknown> = {};
    try { json = JSON.parse(text) as Record<string, unknown>; } catch { /* asserted on by the caller */ }
    return { status: response.status, text, json };
  }

  const wake = (sessionId: string, body: Record<string, unknown>): Promise<Answer> =>
    send('POST', `/runner/sessions/${uuidToBase62(sessionId)}/background-wake`, body);

  const turnsOf = (sessionId: string) =>
    prisma.conversationTurn.findMany({ where: { sessionId }, orderBy: { seq: 'asc' } });

  /** What the runner's claim does to a queued session, then the inbox poll that follows it. */
  async function claimAndPoll(sessionId: string): Promise<Answer> {
    await prisma.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    return send('GET', `/runner/sessions/${uuidToBase62(sessionId)}/inbox`);
  }

  /**
   * The wakeup the agent asked for, made due. `schedule_wakeup`'s floor is a minute out, so the row
   * is written by the production door and then backdated here rather than inserted by hand: what the
   * worker reads is a row the door really wrote.
   */
  async function wakeupDueNow(sessionId: string, reason: string, prompt: string): Promise<string> {
    const held = await send('POST', `/runner/sessions/${uuidToBase62(sessionId)}/scheduled-wakeup`, {
      delaySeconds: 60, reason, prompt,
    });
    assert.equal(held.status, 200, `scheduled-wakeup answered ${held.status}: ${held.text}`);
    assert.equal(held.json.outcome, 'SCHEDULED', held.text);
    // Read the row rather than the receipt's id: the public-id interceptor rewrites what the door
    // answers, and what is wanted here is the primary key the worker reads.
    const { id } = await prisma.sessionScheduledWakeup.findFirstOrThrow({ where: { sessionId, state: 'PENDING' } });
    await sql.query(`UPDATE "session_scheduled_wakeup" SET "due_at" = now() - interval '1 second' WHERE "id" = $1`, [id]);
    return id;
  }

  const wakeupRow = async (id: string) =>
    prisma.sessionScheduledWakeup.findUniqueOrThrow({ where: { id } });

  await t.test('a wakeup filed onto a withdrawn turn is cancelled, not left pointing at nothing', async () => {
    const sessionId = await session();
    const wakeupId = await wakeupDueNow(sessionId, 'watching the deploy', 'check whether the rollout finished');

    assert.deepEqual(await wakeups.drain(), ['DELIVERED'], 'the due wakeup was not filed as a turn');
    const [turn] = await turnsOf(sessionId);
    assert.ok(turn, 'the due wakeup opened no turn');
    assert.equal(turn.clientTurnId, `bg-wake:wakeup:${wakeupId}`);
    assert.equal(turn.status, 'PENDING', 'the turn was not queued');
    const filed = await wakeupRow(wakeupId);
    assert.equal(filed.state, 'DELIVERED');
    assert.equal(filed.clientTurnId, turn.clientTurnId, 'the wakeup was not settled onto the turn that carries it');

    // The withdraw both clients' cards offer, through the production door.
    assert.deepEqual(await sessions.cancelQueuedTurn(ownerId, sessionId, turn.id), { ok: true });
    assert.equal((await turnsOf(sessionId)).length, 0, 'the withdrawn turn is still queued');

    // THE STATE IT LANDS IN: cancelled, and still naming the turn it had been filed onto — an
    // agent's own stop only ever reaches a PENDING row, so CANCELLED with a client_turn_id says
    // precisely that this wakeup had been filed onto a turn somebody then withdrew.
    const settled = await wakeupRow(wakeupId);
    assert.equal(settled.state, 'CANCELLED',
      `a withdrawn wakeup was left ${settled.state}: DELIVERED points at a turn that no longer exists, `
      + 'and PENDING would re-file the identical turn on the next pass');
    assert.ok(settled.settledAt, 'the cancelled wakeup records no settling time');
    assert.equal(settled.clientTurnId, turn.clientTurnId, 'nothing records which turn it had been filed onto');

    // AND THE WORKER AGREES WITH THAT STATE. It scans PENDING alone, so a cancelled wakeup is not
    // due again — no second turn, however many passes reach it.
    assert.deepEqual(await wakeups.drain(), [], 'a withdrawn wakeup was delivered again');
    assert.deepEqual(await wakeups.drain(), [], 'a withdrawn wakeup was delivered again');
    assert.equal((await turnsOf(sessionId)).length, 0, 'the withdrawn wakeup came back as a turn');

    // Withdrawing the last executable turn leaves the session idle rather than holding a slot.
    const after = await prisma.session.findUniqueOrThrow({ where: { id: sessionId } });
    assert.equal(after.status, RunStatus.AWAITING_INPUT, 'the withdrawn wake left the session holding a queue slot');
  });

  await t.test('a withdrawn turn\'s job wakes do not come back with the job\'s next wake', async () => {
    const sessionId = await session();
    const build = 'bgj_111111111111';
    const deploy = 'bgj_222222222222';

    // One turn, two jobs: the second wake joins the first's turn, so its row is keyed by the turn
    // the FIRST job opened — `bg-wake:<build>:exit`, the same string the build's next wake computes.
    const opened = await wake(sessionId, exitWake(build, {
      status: 'failed', exitCode: 1, outputExcerpt: 'the build wake that was withdrawn',
    }));
    assert.equal(opened.json.outcome, 'ENQUEUED', opened.text);
    const joined = await wake(sessionId, exitWake(deploy, { outputExcerpt: 'the deploy wake that was withdrawn' }));
    assert.equal(joined.json.outcome, 'MERGED', joined.text);
    const queuedTurns = await turnsOf(sessionId);
    assert.equal(queuedTurns.length, 1, 'the two wakes opened more than one turn');
    const [withdrawn] = queuedTurns;
    assert.equal(withdrawn.clientTurnId, `bg-wake:${build}:exit`);
    assert.equal(
      await prisma.backgroundJobWake.count({ where: { sessionId, clientTurnId: withdrawn.clientTurnId } }), 2,
      'the two wakes were not filed onto the one turn',
    );

    assert.deepEqual(await sessions.cancelQueuedTurn(ownerId, sessionId, withdrawn.id), { ok: true });
    assert.equal((await turnsOf(sessionId)).length, 0, 'the withdrawn turn is still queued');
    assert.equal(
      await prisma.backgroundJobWake.count({ where: { sessionId } }), 0,
      'the withdrawn turn left its wakes behind, under the key the next wake of the same job reuses',
    );

    // The build's ending is reported again — a runner that restarted and re-read the job it adopted,
    // quoting further into the same output. Its wake id is the same stable string, so the turn it
    // opens carries the same client_turn_id the withdrawn one did.
    const again = await wake(sessionId, exitWake(build, {
      outputOffset: 512, outputSize: 900, status: 'failed', exitCode: 1, outputExcerpt: 'the build wake that came after',
    }));
    assert.equal(again.status, 200, `background-wake answered ${again.status}: ${again.text}`);
    assert.equal(again.json.outcome, 'ENQUEUED', again.text);
    const [reopened] = await turnsOf(sessionId);
    assert.equal(reopened.clientTurnId, `bg-wake:${build}:exit`);

    const delivered = await claimAndPoll(sessionId);
    assert.equal(delivered.status, 200, `inbox answered ${delivered.status}: ${delivered.text}`);
    const content = String(delivered.json.content ?? '');
    assert.ok(content.includes('the build wake that came after'), `the new turn does not carry the new wake:\n${content}`);
    assert.ok(content.includes('exit code 1'), `the new turn does not carry how the job ended:\n${content}`);
    for (const gone of ['the build wake that was withdrawn', 'the deploy wake that was withdrawn', deploy]) {
      assert.ok(!content.includes(gone), `a withdrawn wake was delivered again: ${gone}\n${content}`);
    }
    assert.ok(content.includes('bytes 512–900'),
      `the new turn covers output the withdrawn wake had already reported:\n${content}`);
  });

  await t.test('withdrawing an ordinary message is unchanged, and reaches no wake queued beside it', async () => {
    const sessionId = await session();

    // A wake turn queued first, carrying both kinds of payload, then an ordinary message behind it.
    const filed = await wake(sessionId, exitWake('bgj_333333333333', { outputExcerpt: 'the wake nobody withdrew' }));
    assert.equal(filed.json.outcome, 'ENQUEUED', filed.text);
    const wakeupId = await wakeupDueNow(sessionId, 'the wakeup nobody withdrew', 'pick the thread back up');
    assert.deepEqual(await wakeups.drain(), ['DELIVERED'], 'the due wakeup was not filed');
    const queuedTurns = await turnsOf(sessionId);
    assert.equal(queuedTurns.length, 1, 'the wakeup did not join the queued wake turn');
    const [wakeTurn] = queuedTurns;
    assert.equal(wakeTurn.clientTurnId, 'bg-wake:bgj_333333333333:exit');
    assert.equal((await wakeupRow(wakeupId)).clientTurnId, wakeTurn.clientTurnId);

    const message = await sessions.createTurn(ownerId, sessionId, {
      clientTurnId: randomUUID(),
      content: 'never mind the build, look at the flaky test instead',
      intent: 'NEXT_TURN',
    });
    assert.ok(message.turnId, `the message was not queued: ${JSON.stringify(message)}`);

    // What withdrawing an ordinary message has always done: the row goes, and nothing else does.
    assert.deepEqual(await sessions.cancelQueuedTurn(ownerId, sessionId, message.turnId), { ok: true });
    const left = await turnsOf(sessionId);
    assert.deepEqual(left.map((row) => row.clientTurnId), [wakeTurn.clientTurnId],
      'withdrawing a message took something else off the queue');
    assert.equal((await wakeupRow(wakeupId)).state, 'DELIVERED',
      'withdrawing an ordinary message settled a wakeup filed onto another turn');
    assert.equal(await prisma.backgroundJobWake.count({ where: { sessionId } }), 1,
      'withdrawing an ordinary message deleted a wake queued beside it');

    // Withdrawing it twice is the same refusal it always was.
    await assert.rejects(
      () => sessions.cancelQueuedTurn(ownerId, sessionId, message.turnId),
      /already started or not found/,
      'a second withdraw of the same message answered something new',
    );

    // And the wake it was queued beside still delivers everything it was carrying.
    const delivered = await claimAndPoll(sessionId);
    assert.equal(delivered.status, 200, `inbox answered ${delivered.status}: ${delivered.text}`);
    const content = String(delivered.json.content ?? '');
    for (const fact of ['the wake nobody withdrew', 'the wakeup nobody withdrew', 'pick the thread back up']) {
      assert.ok(content.includes(fact), `the surviving wake turn does not say ${fact}:\n${content}`);
    }
    assert.ok(!content.includes('flaky test'), `the withdrawn message was delivered anyway:\n${content}`);
  });
});
