/**
 * One Orbit session asking another for a reply — every outcome, handed back once — against a real
 * PostgreSQL (docs/session-request-reply-contract.md §8, P1 criteria 5–10).
 *
 *   5. Each of the five outcomes, end to end: the request written beside its turn, the outcome written
 *      once, and the asker handed exactly one reply for it. A `session_reply` racing the NO_REPLY
 *      judgment of the same request: exactly one of them is the outcome.
 *   6. NO_REPLY is not judged while the recipient has any of the five wake sources — an ACTIVE watch,
 *      a running background job, a PENDING scheduled wakeup, an OPEN request of its own, an open
 *      `ask_owner` question — and is judged when it has none.
 *   7. Two outcomes arriving before the asker's runner takes the reply turn make one reply turn.
 *   8. An asker that has ended is not revived; the task it ran gets one comment, and handing the
 *      outcome back again writes no second one.
 *   9. A reply turn dropped by an interrupt is said on the asker's next delivered turn.
 *  10. (here, for the runner doors: the user doors are in session-reply-prefix-doors.spec.ts) the
 *      `session-reply:` prefix is refused as a caller's own key.
 *
 * The doors are the real controllers with the real orchestration credential; the inbox, the event
 * ingest and the turn completion are the real RunnerApiController methods, called as the runner does.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/sessions/session-request.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { JwtService } from '@nestjs/jwt';
import {
  type Prisma,
  type PrismaClient,
  type Runner,
  RunStatus,
  RunnerStatus,
  SessionDispatchOrigin,
  SessionRunSource,
} from '@prisma/client';
import { RunEventType, RunStatus as SharedRunStatus, base62ToUuid, uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { establishProjectContractForPgTest } from '../projects/project-contract-test-helper';
import { ProjectsService } from '../projects/projects.service';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerOrchestrationAuthorizer } from '../runner-api/runner-orchestration-authorizer';
import { RunnerProjectsController } from '../runner-api/runner-projects.controller';
import { RunnerSessionsController } from '../runner-api/runner-sessions.controller';
import {
  closeUnansweredRequests,
  MAX_OPEN_REQUESTS_PER_SESSION,
  REQUEST_CLOSED_CODE,
  SELF_REQUEST_CODE,
  SESSION_REPLY_TURN_PREFIX,
  TOO_MANY_OPEN_REQUESTS_CODE,
} from './session-request';
import { SessionRequestService, sessionReplyCommentId } from './session-request.service';
import { SessionRequestWorker } from './session-request.worker';
import { SessionsService } from './sessions.service';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a session row carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;
const HOUR = 60 * 60 * 1000;

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

/** The refusal an exception carries, as a caller reads it. */
function refusalOf(error: unknown): { status: number | undefined; body: Record<string, unknown> } {
  const response = (error as { getResponse?: () => unknown }).getResponse?.();
  assert.ok(response && typeof response === 'object', `expected a structured refusal, got ${String(error)}`);
  return { status: (error as { getStatus?: () => number }).getStatus?.(), body: response as Record<string, unknown> };
}

test('a session asks another for a reply, and every request comes to exactly one outcome, handed back once', {
  skip, concurrency: 1, timeout: 600_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });
  const db = prisma as unknown as PrismaService;

  // ── the world: one account, one machine, a workspace for the workers and one for coordinators ──
  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const workerWorkspaceId = randomUUID();
  const landingWorkspaceId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `session-request-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: {
      id: runnerId, ownerId, name: 'the machine every session runs on', tokenHash: sha256(`token-${runnerId}`),
      status: RunnerStatus.ONLINE, lastHeartbeatAt: new Date(), capabilities: [], capabilitiesReportedAt: new Date(),
    },
  });
  await prisma.workspace.create({ data: { id: workerWorkspaceId, ownerId, runnerId, name: 'orbit-worker', enabled: true } });
  await prisma.workspace.create({ data: { id: landingWorkspaceId, ownerId, runnerId, name: 'orbit-coordinator', enabled: true } });
  const runner = { id: runnerId, ownerId } as Runner;

  /** A session on this runner, parked between turns — the shape a live orchestrating caller has. */
  async function session(title: string, data: Partial<Prisma.SessionUncheckedCreateInput> = {}): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id, ownerId, creatorId: ownerId, workspaceId: workerWorkspaceId, assignedRunnerId: runnerId,
        title, prompt: title, provider: 'claude', status: RunStatus.AWAITING_INPUT,
        numTurns: 1, startedAt: new Date(), runtimeSessionId: `runtime-${id}`,
        dispatchOrigin: SessionDispatchOrigin.USER, runSource: SessionRunSource.MANUAL,
        ...data,
      },
    });
    return id;
  }

  async function task(title: string): Promise<string> {
    const created = await prisma.task.create({
      data: { ownerId, title, creatorType: 'USER', creatorId: ownerId, completionCriterion: 'OWNER_CONFIRMED' },
      select: { id: true },
    });
    return created.id;
  }

  // ── the doors ─────────────────────────────────────────────────────────────────────────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(db, queue as never, realtime as never);
  const requests = new SessionRequestService(db, sessions, realtime as never);
  // Never started: each case drives its passes by hand.
  const worker = new SessionRequestWorker(db, requests, { pollIntervalMs: HOUR });
  const orchestration = new RunnerOrchestrationAuthorizer(db, new JwtService({ secret: 'session-request-pg' }));
  const attempts = { chargeSteer: async () => undefined };
  const sendDoor = new RunnerSessionsController(sessions, orchestration, {} as never, attempts as never, undefined, requests);
  const projects = new ProjectsService(db, new ProjectAcceptanceService(db), sessions);
  const projectDoor = new RunnerProjectsController(
    projects, new ProjectAcceptanceService(db), {} as never, orchestration, undefined, attempts as never,
  );
  const api = new RunnerApiController(
    db,
    queue as never,
    realtime as never,
    {} as never,
    orchestration,
    // The messages here carry no `#`-references and reach no list console.
    { expand: async (_owner: string, content?: string) => content } as never,
    { appendFor: async (_tx: unknown, _id: string, content?: string) => content } as never,
    undefined,
    undefined,
    undefined,
    undefined,
    sessions,
    undefined,
    undefined,
    undefined,
    undefined,
    requests,
  );

  /** `session_send` as the runner calls it: from a session with its own credential, or headless. */
  async function sessionSend(
    from: string | null,
    to: string,
    message: string,
    extra: Record<string, unknown> = {},
  ): Promise<Record<string, unknown>> {
    return sendDoor.sendMessage(
      runner,
      undefined,
      from ?? undefined,
      from ? await orchestration.issue(runnerId, from) : undefined,
      to,
      { message, clientTurnId: randomUUID(), ...extra } as never,
    ) as Promise<Record<string, unknown>>;
  }

  /** `session_send` with `expectReply`: the receipt, and the request's uuid beside its public id. */
  async function ask(
    from: string,
    to: string,
    message: string,
    extra: Record<string, unknown> = {},
  ): Promise<{ requestId: string; replyBy: string; id: string; turnId: string }> {
    const receipt = await sessionSend(from, to, message, { expectReply: true, ...extra });
    assert.equal(typeof receipt.requestId, 'string', `the send answered no request: ${JSON.stringify(receipt)}`);
    assert.equal(typeof receipt.replyBy, 'string', `the send answered no deadline: ${JSON.stringify(receipt)}`);
    return {
      requestId: String(receipt.requestId),
      replyBy: String(receipt.replyBy),
      turnId: String(receipt.turnId),
      id: base62ToUuid(String(receipt.requestId)),
    };
  }

  /**
   * `session_reply` as the runner calls it, from the calling session's own credential. The route's
   * PublicIdPipe decodes the public id the request was answered with; called directly, the door is
   * handed what that pipe hands it.
   */
  async function reply(from: string, requestId: string, body: { message?: string; option?: number }) {
    return sendDoor.replyToRequest(
      runner, undefined, from, await orchestration.issue(runnerId, from), base62ToUuid(requestId), body as never,
    );
  }

  /**
   * What the runner's claim does to a queued session, then the polls that follow it until a message
   * comes out — a control turn (an interrupt) is handed out first and answered on the spot. The poll
   * declares no steer support, so a steer stays queued until its turn ends and is re-filed.
   */
  async function deliver(sessionId: string): Promise<{ turnId: string; content: string; clientTurnId: string }> {
    await prisma.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    for (;;) {
      const handed = await (api as unknown as {
        dequeueTurn: (sessionId: string, runnerId: string, leaseGeneration: string | null) => Promise<Record<string, unknown> | null>;
      }).dequeueTurn.call(api, sessionId, runnerId, null);
      assert.ok(handed, `the inbox of ${sessionId} handed nothing out`);
      const turn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: String(handed.turnId) } });
      if (turn.kind !== 'message') continue;
      return { turnId: turn.id, content: String(handed.content ?? ''), clientTurnId: turn.clientTurnId };
    }
  }

  const seqs = new Map<string, number>();
  /** The runner's events for one turn, through the real ingest. Answers what was stored. */
  async function say(sessionId: string, turnId: string, type: RunEventType, payload: Record<string, unknown>) {
    const seq = (seqs.get(sessionId) ?? 100) + 1;
    seqs.set(sessionId, seq);
    await api.events({ id: runnerId } as never, sessionId, {
      events: [{ seq, type, ts: new Date().toISOString(), turnId, payload }],
    } as never);
    return (await prisma.runEvent.findFirstOrThrow({ where: { sessionId, seq } })).payload as Record<string, unknown>;
  }

  /** The turn ends as the runner reports it: something said, then the completion. */
  async function finish(sessionId: string, turnId: string, words = 'done looking') {
    await say(sessionId, turnId, RunEventType.ASSISTANT, { text: words });
    await api.turnComplete({ id: runnerId } as never, sessionId, {
      turnId, status: SharedRunStatus.SUCCEEDED, subtype: 'success', numTurns: 1, costUsd: 0,
    } as never);
  }

  const requestRow = (id: string) => prisma.sessionRequest.findUniqueOrThrow({ where: { id } });
  const replyTurnsOf = (sessionId: string) => prisma.conversationTurn.findMany({
    where: { sessionId, clientTurnId: { startsWith: SESSION_REPLY_TURN_PREFIX } },
    orderBy: { seq: 'asc' },
  });
  /** How many `<orbit-session-reply>` blocks for this request a text carries. */
  const blocksFor = (content: string, requestId: string) =>
    content.split(`<orbit-session-reply request-id="${uuidToBase62(requestId)}"`).length - 1;

  // ── 5. REPLIED, end to end ────────────────────────────────────────────────────────────────────

  await t.test('REPLIED: the recipient reads the request, answers it, and the asker is handed the answer once', async () => {
    const asker = await session('Worker: needs a decision');
    const recipient = await session('Coordinator: decides');
    const options = [{ label: 'merge now', description: 'the checks are green' }, { label: 'wait for review' }];
    const request = await ask(asker, recipient, 'criterion 3 is ready — merge now or wait for review?', {
      replyOptions: options, replyWithinSeconds: 3_600,
    });
    const row = await requestRow(request.id);
    assert.equal(row.state, 'OPEN');
    assert.equal(row.fromSessionId, asker);
    assert.equal(row.toSessionId, recipient);
    assert.deepEqual(row.options, options);
    assert.ok(Math.abs(row.replyBy.getTime() - (Date.now() + 3_600_000)) < 60_000, 'the deadline is not an hour away');
    assert.equal(new Date(String(request.replyBy)).getTime(), row.replyBy.getTime());

    // The recipient reads the request in its block: who, which request, by when, how to answer.
    const handed = await deliver(recipient);
    assert.equal(handed.turnId, row.turnId);
    assert.match(handed.content, new RegExp(`request-id="${uuidToBase62(request.id)}"`));
    assert.match(handed.content, /reply-by="\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ"/);
    assert.match(handed.content, new RegExp(`session_reply\\(requestId="${uuidToBase62(request.id)}"\\)`));
    assert.match(handed.content, /NO_REPLY/);
    assert.match(handed.content, /\n0\. merge now：the checks are green\n1\. wait for review\n/);
    // The echo carries the request on its card, so a client can read the request's state.
    const echoed = await say(recipient, handed.turnId, RunEventType.USER, { text: handed.content });
    assert.equal((echoed.sessionMessage as Record<string, unknown>).requestId, uuidToBase62(request.id));

    // Refusals: only the recipient answers; an answer must say something the request can take.
    await assert.rejects(() => reply(asker, request.requestId, { message: 'I answer myself' }), (e: unknown) => {
      assert.equal(refusalOf(e).status, 403);
      return true;
    });
    await assert.rejects(() => reply(recipient, request.requestId, {}), (e: unknown) => {
      assert.equal(refusalOf(e).status, 400);
      return true;
    });
    await assert.rejects(() => reply(recipient, request.requestId, { option: 2 }), (e: unknown) => {
      assert.equal(refusalOf(e).status, 400);
      return true;
    });

    const answered = await reply(recipient, request.requestId, { option: 1, message: 'the reviewer is back at 3' });
    assert.equal(answered.state, 'REPLIED');
    assert.equal(answered.handOff, 'QUEUED');
    const closed = await requestRow(request.id);
    assert.equal(closed.state, 'REPLIED');
    assert.equal(closed.replyOption, 1);
    assert.equal(closed.replyText, 'the reviewer is back at 3');
    // Once answered, always answered: the second answer is refused with the first's outcome.
    await assert.rejects(() => reply(recipient, request.requestId, { option: 0 }), (e: unknown) => {
      const refusal = refusalOf(e);
      assert.equal(refusal.status, 409);
      assert.equal(refusal.body.code, REQUEST_CLOSED_CODE);
      assert.equal(refusal.body.outcome, 'REPLIED');
      return true;
    });
    // The recipient's turn settling now finds nothing OPEN to judge.
    await finish(recipient, handed.turnId);
    assert.equal((await requestRow(request.id)).state, 'REPLIED');

    // The asker: one reply turn, nobody's words in it, and the answer said at delivery.
    const replyTurns = await replyTurnsOf(asker);
    assert.equal(replyTurns.length, 1);
    assert.equal(replyTurns[0].content, '');
    assert.equal(replyTurns[0].sendIntent, 'NEXT_TURN');
    assert.equal(replyTurns[0].senderSessionId, null, 'a reply turn was signed and counted as a message');
    assert.equal((await prisma.session.findUniqueOrThrow({ where: { id: asker } })).status, RunStatus.PENDING);
    const back = await deliver(asker);
    assert.equal(back.turnId, replyTurns[0].id);
    assert.equal(blocksFor(back.content, request.id), 1);
    assert.match(back.content, new RegExp(`from-session="${uuidToBase62(recipient)}"`));
    assert.match(back.content, /outcome="REPLIED"/);
    assert.match(back.content, /你问的是：criterion 3 is ready — merge now or wait for review\?/);
    assert.match(back.content, /选择：1\. wait for review/);
    assert.match(back.content, /回复：the reviewer is back at 3/);
    // ...and stored as reply cards, not as the owner's words.
    const card = await say(asker, back.turnId, RunEventType.USER, { text: back.content });
    const cards = card.sessionReplies as Array<Record<string, unknown>>;
    assert.equal(cards.length, 1);
    assert.equal(cards[0].requestId, uuidToBase62(request.id));
    assert.equal(cards[0].outcome, 'REPLIED');
    assert.equal(cards[0].fromSessionId, recipient);
    assert.equal(cards[0].replyOptionLabel, 'wait for review');
    assert.equal(card.controlPlaneNote, back.content, 'the whole delivery is the control plane\'s note');
    // Handing it back again is nothing.
    assert.equal(await requests.handOff(request.id), 'ALREADY');
    assert.equal((await replyTurnsOf(asker)).length, 1);
  });

  // ── 5 + 6. NO_REPLY ───────────────────────────────────────────────────────────────────────────

  await t.test('NO_REPLY: the recipient read it, went idle with nothing left to wake it, and never answered', async () => {
    const asker = await session('Worker: asks and moves on');
    const recipient = await session('Worker: forgets to answer');
    const request = await ask(asker, recipient, 'which port does the gateway listen on?');
    const handed = await deliver(recipient);
    await finish(recipient, handed.turnId, 'The gateway listens on 8443 — I checked compose.yml.');
    const closed = await requestRow(request.id);
    assert.equal(closed.state, 'NO_REPLY');
    assert.equal(closed.excerpt, 'The gateway listens on 8443 — I checked compose.yml.');
    assert.equal((await prisma.session.findUniqueOrThrow({ where: { id: recipient } })).status, RunStatus.AWAITING_INPUT);
    // Handed back by the completion itself, after its commit.
    const back = await deliver(asker);
    assert.equal(blocksFor(back.content, request.id), 1);
    assert.match(back.content, /outcome="NO_REPLY"/);
    assert.match(back.content, /不是正式回复/);
    assert.match(back.content, /The gateway listens on 8443/);
  });

  await t.test('NO_REPLY waits while any of the five wake sources is pending, and is judged once none is', async () => {
    const askers = new Map<string, string>();
    /** A recipient with one wake source, asked a question it reads and does not answer. */
    async function judged(
      label: string,
      arm: (recipient: string) => Promise<void>,
      data: Partial<Prisma.SessionUncheckedCreateInput> = {},
    ) {
      const asker = await session(`Worker: asks the one with ${label}`);
      const recipient = await session(`Worker: has ${label}`, data);
      askers.set(label, asker);
      const request = await ask(asker, recipient, `are you still on it? (${label})`);
      await arm(recipient);
      const handed = await deliver(recipient);
      await finish(recipient, handed.turnId, `still going (${label})`);
      return (await requestRow(request.id)).state;
    }

    assert.equal(await judged('an ACTIVE watch', async (recipient) => {
      await prisma.watch.create({
        data: {
          ownerId, observerType: 'SESSION', observerSessionId: recipient,
          predicate: { kind: 'ALL', over: 'ALL_TARGETS', leaf: 'TASK_TERMINAL' },
          action: 'RESUME_SESSION', state: 'ACTIVE', expiresAt: new Date(Date.now() + 24 * HOUR),
        },
      });
    }), 'OPEN', 'an ACTIVE watch will wake it, and it may answer then');

    assert.equal(await judged('a running background job', async (recipient) => {
      await prisma.session.update({ where: { id: recipient }, data: { runningBgJobs: ['bgj_0123456789ab'] } });
    }), 'OPEN', 'a running job is work that comes back to it');

    assert.equal(await judged('a pending scheduled wakeup', async (recipient) => {
      await prisma.sessionScheduledWakeup.create({
        data: { sessionId: recipient, delaySeconds: 600, reason: 'check the build', dueAt: new Date(Date.now() + 600_000) },
      });
    }), 'OPEN', 'a wakeup it asked for will wake it');

    assert.equal(await judged('an open request of its own', async (recipient) => {
      const third = await session('Worker: asked by the recipient');
      await ask(recipient, third, 'I need your numbers before I can answer');
    }), 'OPEN', 'the answer to its own request will come back to it as a turn');

    assert.equal(await judged('an open ask_owner question', async (recipient) => {
      const projectId = randomUUID();
      await prisma.project.create({
        data: { id: projectId, ownerId, title: 'asks the owner', coordinatorEnabled: true, coordinatorWorkspaceId: landingWorkspaceId },
      });
      await establishProjectContractForPgTest(prisma, ownerId, projectId, 'asks the owner');
      await prisma.project.update({ where: { id: projectId }, data: { coordinatorSessionId: recipient } });
      await prisma.projectOpenItem.create({
        data: {
          projectId, ownerId, kind: 'COORDINATOR_QUESTION', state: 'OPEN', assignee: 'OWNER', assigneeReason: 'DEFAULT',
          askedBySessionId: recipient, dedupeKey: `CQ:${randomUUID()}`, title: 'Coordinator asks: ship it?',
          payload: { question: 'ship it?', options: [], blocksTaskIds: [], ifUnanswered: null },
          waitingSince: new Date(), assignedAt: new Date(),
        },
      } as never);
    }, { workspaceId: landingWorkspaceId, titleManagedByProject: true }), 'OPEN', 'the owner\'s answer to its question will wake it');

    assert.equal(await judged('nothing at all', async () => undefined), 'NO_REPLY');
    // None of the five waiting ones was handed anything back; the last one was.
    for (const [label, asker] of askers) {
      assert.equal((await replyTurnsOf(asker)).length, label === 'nothing at all' ? 1 : 0, label);
    }
  });

  await t.test('a request the recipient has not read yet is not judged when another turn of it settles', async () => {
    const asker = await session('Worker: asks a busy one');
    const recipient = await session('Worker: busy with something else');
    // The recipient is working on a turn of its own when the request arrives, so it queues behind it.
    await sessions.createTurn(ownerId, recipient, { clientTurnId: randomUUID(), content: 'the owner\'s own task' });
    const running = await deliver(recipient);
    const request = await ask(asker, recipient, 'when you are done, which branch?');
    assert.equal((await requestRow(request.id)).state, 'OPEN');
    await finish(recipient, running.turnId);
    assert.equal((await requestRow(request.id)).state, 'OPEN', 'judged before it was ever read');
    const handed = await deliver(recipient);
    assert.equal(handed.turnId, (await requestRow(request.id)).turnId);
    await finish(recipient, handed.turnId, 'main');
    assert.equal((await requestRow(request.id)).state, 'NO_REPLY');

    // And the rule itself, where nothing else holds the judgment off. The completion above never
    // reached the judgment, because the request still queued kept the session busy; asked directly,
    // the one function that judges (contract §4.1) passes over a request no engine has been handed,
    // even with nothing left that would wake its recipient.
    const idle = await session('Worker: idle, a request still queued');
    const queued = await ask(asker, idle, 'which branch, once you get to it?');
    const judged = await prisma.$transaction((tx) =>
      closeUnansweredRequests(tx, { id: idle, runningBgJobs: [], lastAssistantText: 'not started' }));
    assert.deepEqual(judged, [], 'a request was judged before any engine read it');
    assert.equal((await requestRow(queued.id)).state, 'OPEN');
    const read = await deliver(idle);
    await finish(idle, read.turnId, 'main, again');
    assert.equal((await requestRow(queued.id)).state, 'NO_REPLY');
  });

  // ── 5. the race ───────────────────────────────────────────────────────────────────────────────

  await t.test('session_reply racing the NO_REPLY judgment: exactly one is the outcome, handed back once', async () => {
    const outcomes: string[] = [];
    for (let round = 0; round < 6; round++) {
      const asker = await session(`Worker: races ${round}`);
      const recipient = await session(`Worker: answers as it stops ${round}`);
      const request = await ask(asker, recipient, `race ${round}`);
      const handed = await deliver(recipient);
      await say(recipient, handed.turnId, RunEventType.ASSISTANT, { text: `my last words ${round}` });
      const [answered, completed] = await Promise.allSettled([
        reply(recipient, request.requestId, { message: `the answer ${round}` }),
        api.turnComplete({ id: runnerId } as never, recipient, {
          turnId: handed.turnId, status: SharedRunStatus.SUCCEEDED, subtype: 'success', numTurns: 1, costUsd: 0,
        } as never),
      ]);
      assert.equal(completed.status, 'fulfilled', `the completion failed: ${String((completed as PromiseRejectedResult).reason)}`);
      const row = await requestRow(request.id);
      if (answered.status === 'fulfilled') {
        assert.equal(row.state, 'REPLIED');
        assert.equal(row.replyText, `the answer ${round}`);
      } else {
        const refusal = refusalOf(answered.reason);
        assert.equal(refusal.body.code, REQUEST_CLOSED_CODE, `the answer failed some other way: ${String(answered.reason)}`);
        assert.equal(row.state, 'NO_REPLY');
        assert.equal(row.replyText, null);
      }
      outcomes.push(row.state);
      // Whichever won, one hand-off. Run the worker too: it must find nothing left to hand.
      await worker.drain();
      const turns = await replyTurnsOf(asker);
      assert.equal(turns.length, 1, `round ${round} handed back ${turns.length} turns`);
      const back = await deliver(asker);
      assert.equal(blocksFor(back.content, request.id), 1);
    }
    assert.ok(outcomes.every((state) => state === 'REPLIED' || state === 'NO_REPLY'));
  });

  // ── 5. RECIPIENT_ENDED ────────────────────────────────────────────────────────────────────────

  await t.test('RECIPIENT_ENDED: the recipient completed, failed, or went to Trash — whichever writer ended it', async () => {
    // Completed: the owner files it.
    const asker = await session('Worker: asks three that end');
    const completed = await session('Worker: completed by the owner');
    const viaComplete = await ask(asker, completed, 'please confirm the schema');
    const handed = await deliver(completed);
    await say(completed, handed.turnId, RunEventType.ASSISTANT, { text: 'half way through the schema' });
    await prisma.session.update({ where: { id: completed }, data: { runningBgJobs: ['bgj_keepsitopen1'] } });
    await finish(completed, handed.turnId, 'half way through the schema');
    assert.equal((await requestRow(viaComplete.id)).state, 'OPEN', 'the job should have kept it open');
    await sessions.complete(ownerId, completed);
    const ended = await requestRow(viaComplete.id);
    assert.equal(ended.state, 'RECIPIENT_ENDED');
    assert.match(String(ended.closeReason), /^COMPLETED/);
    assert.equal(ended.excerpt, 'half way through the schema');

    // Failed with no retry: the runner's turn fails and the run ends with it.
    const failing = await session('Worker: fails');
    const viaFailure = await ask(asker, failing, 'can you reproduce the crash?');
    const failingTurn = await deliver(failing);
    await say(failing, failingTurn.turnId, RunEventType.ASSISTANT, { text: 'reproducing…' });
    await api.turnComplete({ id: runnerId } as never, failing, {
      turnId: failingTurn.turnId, status: SharedRunStatus.FAILED, subtype: 'error_during_execution', numTurns: 1, costUsd: 0,
      error: 'the engine crashed',
    } as never);
    assert.equal((await requestRow(viaFailure.id)).state, 'RECIPIENT_ENDED');
    assert.match(String((await requestRow(viaFailure.id)).closeReason), /^FAILED/);

    // Trash, while the request is still queued and unread: the end wins over the undelivered queue.
    const trashed = await session('Worker: moved to Trash');
    const viaTrash = await ask(asker, trashed, 'is this still needed?');
    await sessions.remove(ownerId, trashed);
    const trashedRow = await requestRow(viaTrash.id);
    assert.equal(trashedRow.state, 'RECIPIENT_ENDED');
    assert.match(String(trashedRow.closeReason), /^TRASHED/);

    // Nothing in application code hands these back: the worker does, once each, in one turn.
    const drained = await worker.drain();
    for (const id of [viaComplete.id, viaFailure.id, viaTrash.id]) {
      assert.ok(drained.handedOff.includes(id), `the worker did not hand back ${id}`);
    }
    assert.deepEqual((await worker.drain()).handedOff, []);
    const turns = await replyTurnsOf(asker);
    assert.equal(turns.length, 1, 'three outcomes queued together were not one reply turn');
    const back = await deliver(asker);
    for (const id of [viaComplete.id, viaFailure.id, viaTrash.id]) assert.equal(blocksFor(back.content, id), 1);
    assert.match(back.content, /对方的会话已经结束（COMPLETED/);
  });

  await t.test('a run the auto-retry sweep claims has not ended: its requests stay open until the retry is given up', async () => {
    const asker = await session('Worker: asks one that hits a quota');
    const recipient = await session('Worker: about to hit a quota');
    const { id } = await ask(asker, recipient, 'ping');
    // Its turn fails on a usage limit with a retry armed — the same session goes on; not an end.
    await prisma.session.update({
      where: { id: recipient },
      data: { status: RunStatus.FAILED, retryAt: new Date(Date.now() + 60_000), retryAttempts: 1 },
    });
    assert.equal((await requestRow(id)).state, 'OPEN', 'a failure with a retry armed ended the run');
    // The sweep's claim: the arm cleared and an attempt spent in one statement.
    await sql.query(
      `UPDATE "session" SET "retry_at" = NULL, "retry_attempts" = "retry_attempts" + 1 WHERE id = $1::uuid`,
      [recipient],
    );
    assert.equal((await requestRow(id)).state, 'OPEN', 'the sweep claiming its retry ended the run');
    // The sweep gives up: the arm cleared and no attempt spent.
    await sql.query(`UPDATE "session" SET "retry_at" = NULL WHERE id = $1::uuid`, [recipient]);
    assert.equal((await requestRow(id)).state, 'RECIPIENT_ENDED');
  });

  // ── 5. EXPIRED ────────────────────────────────────────────────────────────────────────────────

  await t.test('EXPIRED: the deadline passed with the request open, and the asker is told how the recipient stood', async () => {
    const asker = await session('Worker: asks with a deadline');
    const recipient = await session('Worker: slow');
    const request = await ask(asker, recipient, 'need this within the minute', { replyWithinSeconds: 60 });
    const handed = await deliver(recipient);
    await say(recipient, handed.turnId, RunEventType.ASSISTANT, { text: 'still compiling…' });
    // Not due yet: the worker leaves it.
    assert.deepEqual((await worker.drain()).expired, []);
    const due = new Date((await requestRow(request.id)).replyBy.getTime() + 1_000);
    const pass = await worker.drain(due);
    assert.deepEqual(pass.expired, [request.id]);
    const expired = await requestRow(request.id);
    assert.equal(expired.state, 'EXPIRED');
    assert.equal(expired.closeReason, 'RUNNING');
    assert.equal(expired.excerpt, 'still compiling…');
    // The answer that comes after it is refused with the outcome it already has.
    await assert.rejects(() => reply(recipient, request.requestId, { message: 'done!' }), (e: unknown) => {
      assert.equal(refusalOf(e).body.outcome, 'EXPIRED');
      return true;
    });
    const back = await deliver(asker);
    assert.equal(blocksFor(back.content, request.id), 1);
    assert.match(back.content, /outcome="EXPIRED"/);
    assert.match(back.content, /对方当时的状态：RUNNING/);
  });

  await t.test('a request that expired in the queue tells its reader there is nothing to answer', async () => {
    const asker = await session('Worker: asks a queue');
    const recipient = await session('Worker: has a long queue');
    await sessions.createTurn(ownerId, recipient, { clientTurnId: randomUUID(), content: 'a long job first' });
    const running = await deliver(recipient);
    const request = await ask(asker, recipient, 'quick one', { replyWithinSeconds: 60 });
    await worker.drain(new Date(Date.now() + 120_000));
    assert.equal((await requestRow(request.id)).state, 'EXPIRED');
    await finish(recipient, running.turnId);
    const handed = await deliver(recipient);
    assert.match(handed.content, /已经以 EXPIRED 结案，不必再调用 session_reply/);
    assert.doesNotMatch(handed.content, /对方在等你回复/);
  });

  // ── 5. UNDELIVERED ────────────────────────────────────────────────────────────────────────────

  await t.test('UNDELIVERED: the owner withdrew the message, or an interrupt dropped it, before it was read', async () => {
    const asker = await session('Worker: asks one that gets stopped');
    const recipient = await session('Worker: about to be interrupted');
    // Idle, so the request waits as the next message — which the owner takes back.
    const withdrawn = await ask(asker, recipient, 'and this too');
    await sessions.cancelQueuedTurn(ownerId, recipient, (await requestRow(withdrawn.id)).turnId);
    const withdrawnRow = await requestRow(withdrawn.id);
    assert.equal(withdrawnRow.state, 'UNDELIVERED');
    assert.equal(withdrawnRow.closeReason, 'WITHDRAWN');
    // Busy, so the next request is written into the running turn (a steer) — and the owner stops the
    // session before it gets there, which drops it with the rest of the queue.
    await sessions.createTurn(ownerId, recipient, { clientTurnId: randomUUID(), content: 'something long' });
    await deliver(recipient);
    const interrupted = await ask(asker, recipient, 'and after that, this');
    assert.equal(
      (await prisma.conversationTurn.findUniqueOrThrow({ where: { id: (await requestRow(interrupted.id)).turnId } })).kind,
      'steer',
    );
    await sessions.interrupt(ownerId, recipient);
    const interruptedRow = await requestRow(interrupted.id);
    assert.equal(interruptedRow.state, 'UNDELIVERED');
    assert.equal(interruptedRow.closeReason, 'INTERRUPTED');
    assert.equal(await prisma.conversationTurn.count({ where: { id: interruptedRow.turnId } }), 0, 'the turn was not dropped');

    const drained = await worker.drain();
    for (const id of [interrupted.id, withdrawn.id]) {
      assert.ok(drained.handedOff.includes(id), `the worker did not hand back ${id}`);
    }
    const back = await deliver(asker);
    assert.equal(blocksFor(back.content, interrupted.id), 1);
    assert.equal(blocksFor(back.content, withdrawn.id), 1);
    assert.match(back.content, /被账号 owner 撤回了/);
    assert.match(back.content, /随队列一起被清掉了/);
  });

  // ── 7. two outcomes, one reply turn ───────────────────────────────────────────────────────────

  await t.test('outcomes that arrive before the asker is handed its reply turn are one turn', async () => {
    const asker = await session('Coordinator: asks two workers');
    const first = await session('Worker: answers first');
    const second = await session('Worker: answers second');
    const one = await ask(asker, first, 'status of shard 1?');
    const two = await ask(asker, second, 'status of shard 2?');
    await deliver(first);
    await deliver(second);
    assert.equal((await reply(first, one.requestId as string, { message: 'shard 1 done' })).handOff, 'QUEUED');
    assert.equal((await reply(second, two.requestId as string, { message: 'shard 2 done' })).handOff, 'MERGED');
    const turns = await replyTurnsOf(asker);
    assert.equal(turns.length, 1);
    const back = await deliver(asker);
    assert.equal(back.turnId, turns[0].id);
    assert.equal(blocksFor(back.content, one.id), 1);
    assert.equal(blocksFor(back.content, two.id), 1);
    assert.ok(back.content.indexOf('shard 1 done') < back.content.indexOf('shard 2 done'), 'out of the order they came');
    const stored = await say(asker, back.turnId, RunEventType.USER, { text: back.content });
    assert.equal((stored.sessionReplies as unknown[]).length, 2);

    // A third answer once that turn is out is a turn of its own.
    const third = await session('Worker: answers late');
    const three = await ask(asker, third, 'status of shard 3?');
    await deliver(third);
    assert.equal((await reply(third, three.requestId as string, { message: 'shard 3 done' })).handOff, 'QUEUED');
    assert.equal((await replyTurnsOf(asker)).length, 2);
  });

  // ── 8. the asker has ended ────────────────────────────────────────────────────────────────────

  await t.test('an asker that has ended is not revived; its task is told once', async () => {
    const taskId = await task('the task the asker ran');
    const asker = await session('Worker: ends before the answer comes', { taskId });
    const recipient = await session('Coordinator: answers late');
    const request = await ask(asker, recipient, 'which migration number is free?');
    await sessions.complete(ownerId, asker);
    const before = await prisma.session.findUniqueOrThrow({ where: { id: asker } });
    await deliver(recipient);
    const answered = await reply(recipient, request.requestId, { message: '0348' });
    assert.equal(answered.handOff, 'HELD');
    const after = await prisma.session.findUniqueOrThrow({ where: { id: asker } });
    assert.equal(after.status, before.status, 'the asker was revived');
    assert.ok(after.completedAt, 'the asker was taken out of Completed');
    assert.equal((await replyTurnsOf(asker)).length, 0);
    const held = await requestRow(request.id);
    assert.ok(held.replyHeldAt);
    assert.equal(held.replyClientTurnId, null);
    const comments = await prisma.taskComment.findMany({ where: { taskId } });
    assert.equal(comments.length, 1);
    assert.equal(comments[0].id, sessionReplyCommentId(request.id));
    assert.match(comments[0].body, /0348/);
    // Processed again — by hand, by the worker, and once the hold is lifted — no second comment.
    assert.equal(await requests.handOff(request.id), 'ALREADY');
    await worker.drain();
    await prisma.sessionRequest.update({ where: { id: request.id }, data: { replyHeldAt: null } });
    assert.equal(await requests.handOff(request.id), 'HELD');
    assert.equal(await prisma.taskComment.count({ where: { taskId } }), 1);

    // An asker with no task has nowhere to be told: held, and nothing written.
    const loose = await session('Worker: no task, ends');
    const looseRequest = await ask(loose, recipient, 'anything?');
    await sessions.remove(ownerId, loose);
    assert.equal((await reply(recipient, looseRequest.requestId as string, { message: 'no' })).handOff, 'HELD');
    assert.equal((await replyTurnsOf(loose)).length, 0);
  });

  // ── 9. the asker was interrupted ──────────────────────────────────────────────────────────────

  await t.test('a reply turn an interrupt dropped is said on the asker\'s next delivered turn', async () => {
    const asker = await session('Worker: interrupted while an answer is queued');
    const recipient = await session('Coordinator: answers');
    const request = await ask(asker, recipient, 'go or no-go?');
    // The asker is busy with a turn of its own when the answer comes, so the reply turn queues.
    await sessions.createTurn(ownerId, asker, { clientTurnId: randomUUID(), content: 'keep working' });
    await deliver(asker);
    await deliver(recipient);
    assert.equal((await reply(recipient, request.requestId, { option: undefined, message: 'go' })).handOff, 'QUEUED');
    assert.equal((await replyTurnsOf(asker)).length, 1);
    // Stopped: the queued reply turn goes with the queue, and nothing starts it running again.
    await sessions.interrupt(ownerId, asker);
    assert.equal((await replyTurnsOf(asker)).length, 0);
    const held = await requestRow(request.id);
    assert.ok(held.replyHeldAt, 'the outcome was not held for the next turn');
    assert.equal(held.replyClientTurnId, null);
    assert.deepEqual((await worker.drain()).handedOff, [], 'the worker queued it again, after a stop');
    assert.equal((await replyTurnsOf(asker)).length, 0);
    // The asker's next turn — the owner's own message — carries it.
    const ownerKey = randomUUID();
    await sessions.createTurn(ownerId, asker, { clientTurnId: ownerKey, content: 'what did the coordinator say?' });
    // The interrupted turn finishes first.
    const inFlight = await prisma.conversationTurn.findFirstOrThrow({ where: { sessionId: asker, status: 'IN_FLIGHT', kind: 'message' } });
    await finish(asker, inFlight.id);
    const next = await deliver(asker);
    assert.equal(next.clientTurnId, ownerKey);
    assert.ok(next.content.startsWith('what did the coordinator say?'), 'the owner\'s words were not first');
    assert.equal(blocksFor(next.content, request.id), 1);
    assert.equal((await requestRow(request.id)).replyClientTurnId, ownerKey);
    const stored = await say(asker, next.turnId, RunEventType.USER, { text: next.content });
    assert.equal((stored.sessionReplies as unknown[]).length, 1);
    // Said once: the turn after that carries nothing.
    await finish(asker, next.turnId);
    await sessions.createTurn(ownerId, asker, { clientTurnId: randomUUID(), content: 'thanks' });
    assert.equal(blocksFor((await deliver(asker)).content, request.id), 0);
  });

  // ── 3.1: what a send may ask, and what it is refused ─────────────────────────────────────────

  await t.test('the send door refuses a headless request, a request to oneself, the fifty-first, and a malformed one', async () => {
    const asker = await session('Worker: tries everything');
    const recipient = await session('Worker: the one asked');
    await assert.rejects(() => sessionSend(null, recipient, 'from a bridge', { expectReply: true }), (e: unknown) => {
      assert.equal(refusalOf(e).status, 403);
      return true;
    });
    await assert.rejects(() => sessionSend(asker, asker, 'me to me', { expectReply: true }), (e: unknown) => {
      const refusal = refusalOf(e);
      assert.equal(refusal.status, 400);
      assert.equal(refusal.body.code, SELF_REQUEST_CODE);
      return true;
    });
    for (const extra of [
      { replyOptions: [{ label: 'a' }, { label: 'b' }] },
      { replyWithinSeconds: 600 },
      { expectReply: true, replyOptions: [{ label: 'only one' }] },
      { expectReply: true, replyOptions: [{ label: '1' }, { label: '2' }, { label: '3' }, { label: '4' }, { label: '5' }] },
      { expectReply: true, replyWithinSeconds: 59 },
      { expectReply: true, replyWithinSeconds: 2_592_001 },
      { expectReply: true, replyOptions: [{ label: 'a', colour: 'red' }, { label: 'b' }] },
    ]) {
      await assert.rejects(() => sessionSend(asker, recipient, 'malformed', extra), (e: unknown) => {
        assert.equal(refusalOf(e).status, 400, JSON.stringify(extra));
        return true;
      });
    }
    assert.equal(await prisma.conversationTurn.count({ where: { sessionId: recipient } }), 0, 'a refused send wrote a turn');

    // Fifty OPEN requests is the most one session may have waiting.
    const others = await Promise.all([1, 2, 3].map((i) => session(`Worker: asked in bulk ${i}`)));
    for (let i = 0; i < MAX_OPEN_REQUESTS_PER_SESSION - 1; i++) {
      await prisma.sessionRequest.create({
        data: {
          ownerId, fromSessionId: asker, toSessionId: others[i % 3], turnId: randomUUID(), clientTurnId: randomUUID(),
          requestPreview: `bulk ${i}`, replyBy: new Date(Date.now() + HOUR),
        },
      });
    }
    const fiftieth = await ask(asker, recipient, 'the fiftieth');
    await assert.rejects(() => ask(asker, recipient, 'the fifty-first'), (e: unknown) => {
      const refusal = refusalOf(e);
      assert.equal(refusal.status, 409);
      assert.equal(refusal.body.code, TOO_MANY_OPEN_REQUESTS_CODE);
      assert.equal(refusal.body.retryable, false);
      return true;
    });
    // A plain message is no request, and is not held back by them.
    await sessionSend(asker, recipient, 'just saying');
    // A retry of the fiftieth is the fiftieth, not a fifty-first.
    const key = randomUUID();
    await prisma.sessionRequest.update({ where: { id: fiftieth.id }, data: { state: 'NO_REPLY', closedAt: new Date() } });
    const once = await sessionSend(asker, recipient, 'retried', { expectReply: true, clientTurnId: key });
    const twice = await sessionSend(asker, recipient, 'retried', { expectReply: true, clientTurnId: key });
    assert.equal(twice.requestId, once.requestId);
    assert.equal(twice.turnId, once.turnId);
    // ...and a key used for a request cannot come back as a plain message, nor the other way round.
    await assert.rejects(() => sessionSend(asker, recipient, 'retried', { clientTurnId: key }), (e: unknown) => {
      assert.equal(refusalOf(e).status, 409);
      return true;
    });
    const plainKey = randomUUID();
    await sessionSend(asker, recipient, 'plain', { clientTurnId: plainKey });
    await assert.rejects(() => sessionSend(asker, recipient, 'plain', { clientTurnId: plainKey, expectReply: true }), (e: unknown) => {
      assert.equal(refusalOf(e).status, 409);
      return true;
    });
  });

  // ── 3.1: project_send ─────────────────────────────────────────────────────────────────────────

  await t.test('project_send records the coordinator it delivered to, and the request stays with it through a rotation', async () => {
    const projectId = randomUUID();
    await prisma.project.create({
      data: { id: projectId, ownerId, title: 'rotates', coordinatorEnabled: true, coordinatorWorkspaceId: landingWorkspaceId },
    });
    await establishProjectContractForPgTest(prisma, ownerId, projectId, 'rotates');
    const coordinator = await session('coordinator: rotates', { workspaceId: landingWorkspaceId, titleManagedByProject: true });
    await prisma.project.update({ where: { id: projectId }, data: { coordinatorSessionId: coordinator } });
    const worker1 = await session('Worker: reports to the coordinator');

    const sent = await projectDoor.sendToCoordinator(
      runner, projectId, worker1, await orchestration.issue(runnerId, worker1),
      { message: 'criterion 2 is blocked on a decision', expectReply: true, replyOptions: [{ label: 'skip' }, { label: 'wait' }] } as never,
    ) as Record<string, unknown>;
    assert.equal(sent.sessionId, coordinator);
    const request = await requestRow(base62ToUuid(String(sent.requestId)));
    assert.equal(request.toSessionId, coordinator);
    assert.equal(typeof sent.replyBy, 'string');

    // The coordinator asking its own project is asking itself.
    const coordinatorToken = await orchestration.issue(runnerId, coordinator);
    await assert.rejects(() => projectDoor.sendToCoordinator(
      runner, projectId, coordinator, coordinatorToken, { message: 'self', expectReply: true } as never,
    ), (e: unknown) => {
      assert.equal(refusalOf(e).body.code, SELF_REQUEST_CODE);
      return true;
    });

    // The project rotates to another conversation; the request stays with the one it was put to,
    // and that conversation ending is its outcome.
    const replacement = await session('coordinator: the replacement', { workspaceId: landingWorkspaceId, titleManagedByProject: true });
    await prisma.project.update({ where: { id: projectId }, data: { coordinatorSessionId: replacement } });
    assert.equal((await requestRow(request.id)).toSessionId, coordinator);
    await sessions.complete(ownerId, coordinator);
    assert.equal((await requestRow(request.id)).state, 'RECIPIENT_ENDED');
  });

  // ── 10. the runner doors refuse the reserved prefix ───────────────────────────────────────────

  await t.test('the session-reply: prefix is the platform\'s: the runner doors refuse it as a caller\'s key', async () => {
    const asker = await session('Worker: picks a bad key');
    const recipient = await session('Worker: receives');
    await assert.rejects(
      () => sessionSend(asker, recipient, 'sneaky', { clientTurnId: `${SESSION_REPLY_TURN_PREFIX}${randomUUID()}` }),
      (e: unknown) => {
        assert.equal(refusalOf(e).status, 400);
        return true;
      },
    );
    await assert.rejects(
      async () => sendDoor.interruptSession(
        runner, undefined, asker, await orchestration.issue(runnerId, asker), recipient,
        { message: 'stop and do this', clientTurnId: `${SESSION_REPLY_TURN_PREFIX}x` },
      ),
      (e: unknown) => {
        assert.equal(refusalOf(e).status, 400);
        return true;
      },
    );
    assert.equal(await prisma.conversationTurn.count({ where: { sessionId: recipient } }), 0);
  });
});
