/**
 * The transcript read from the middle (sessions/transcript-around.ts), over real HTTP and against a
 * real PostgreSQL: what a link that names one record — a turn, an event or a tool call — opens on.
 *
 *   1. `GET /sessions/:id/events/page?around=<record>` returns the page that record sits in, the
 *      anchor it resolved to, and a cursor each way; paging out with `before=` and `after=` walks the
 *      whole transcript, contiguously, from either end of that page;
 *   2. each of the three kinds lands where the reader expects it: an event on itself, a turn on the
 *      message it sent, a tool call on its use;
 *   3. across tenants it is 404, every way round: another owner's session, another owner's record in
 *      one's own session, and a record of one's own other session.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/sessions/session-transcript-around.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the bearer check is stood in for.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { RealtimeService } from '../realtime/realtime.service';
import { SessionTagsService } from '../session-tags/session-tags.service';
import { AutoRetryService } from './auto-retry.service';
import { MergeReceiptService } from './merge-receipt.service';
import { SessionsController } from './sessions.controller';
import { SessionsService } from './sessions.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

/** What Nest itself looks for on every provider at boot and shutdown; absent, not a use. */
const LIFECYCLE = new Set([
  'then',
  'onModuleInit',
  'onApplicationBootstrap',
  'onModuleDestroy',
  'beforeApplicationShutdown',
  'onApplicationShutdown',
]);

/** A collaborator the page reads never reach: any call on it is the route going somewhere it should not. */
const unreachable = (name: string): unknown =>
  new Proxy({}, {
    get: (_target, key) => {
      if (typeof key === 'symbol' || LIFECYCLE.has(key)) return undefined;
      return () => {
        throw new Error(`${name}.${key} is not part of a transcript page read`);
      };
    },
  });

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL!);
    const bearers = new Map<string, string>();
    const sessions = new SessionsService(
      prisma as unknown as PrismaService,
      unreachable('queue') as never,
      unreachable('realtime') as never,
    );

    @Module({
      controllers: [SessionsController],
      providers: [
        { provide: SessionsService, useValue: sessions },
        { provide: PrismaService, useValue: prisma },
        { provide: RealtimeService, useValue: unreachable('realtime') },
        { provide: SessionTagsService, useValue: unreachable('tags') },
        { provide: MergeReceiptService, useValue: unreachable('mergeReceipts') },
        { provide: AutoRetryService, useValue: unreachable('autoRetry') },
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@around.invalid` };
            },
          },
        },
      ],
    })
    class TranscriptAroundModule {}

    const app = await NestFactory.create(TranscriptAroundModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

async function page(h: Harness, bearer: string, sessionId: string, query: string): Promise<Answer> {
  const response = await fetch(
    `${h.base}/api/sessions/${uuidToBase62(sessionId)}/events/page?${query}`,
    { headers: { authorization: `Bearer ${bearer}` } },
  );
  const text = await response.text();
  return { status: response.status, body: text ? JSON.parse(text) : null };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 400)}`);
}

const seqs = (answer: Answer): number[] => answer.body.events.map((e: { seq: number }) => e.seq);

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

async function account(h: Harness, name: string): Promise<{ id: string; bearer: string }> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `transcript-around-${id}@around.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function session(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","status","dispatch_origin","created_at","updated_at")
     VALUES ($1,'around','p',$2,$2,'AWAITING_INPUT'::run_status,'USER',now(),now())`,
    [id, ownerId],
  );
  return id;
}

/** A session's transcript as the runner writes it, one call per event, seq in order of the calls. */
class Transcript {
  private seq = 0;
  /** Every event a page may show, in order — the pings each page must skip are not in it. */
  readonly shown: number[] = [];

  constructor(private readonly h: Harness, readonly sessionId: string) {}

  async event(type: string, payload: unknown, turnId: string | null = null): Promise<{ id: string; seq: number }> {
    const id = randomUUID();
    const seq = ++this.seq;
    await this.h.sql.query(
      `INSERT INTO "run_event"("id","session_id","seq","type","payload","turn_id") VALUES ($1,$2,$3,$4,$5,$6)`,
      [id, this.sessionId, seq, type, JSON.stringify(payload), turnId],
    );
    // A bare progress ping is stored but never crosses the wire (common/system-noise.ts).
    const ping = type === 'system' && Object.keys(payload as object).every((k) => ['model', 'subtype', 'sessionId'].includes(k))
      && (payload as { subtype?: string }).subtype !== 'init';
    if (!ping) this.shown.push(seq);
    return { id, seq };
  }

  /** A turn the person sent: the conversation_turn row and, when it was delivered, its `user` echo. */
  async turn(text: string, echoed = true): Promise<{ turnId: string; userSeq: number | null }> {
    const turnId = randomUUID();
    await this.h.sql.query(
      `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status","kind","send_intent")
       VALUES ($1,$2,(SELECT COALESCE(MAX("seq"),0)+1 FROM "conversation_turn" WHERE "session_id" = $2),$3,$4,'ANSWERED','message','NEXT_TURN')`,
      [turnId, this.sessionId, randomUUID(), text],
    );
    if (!echoed) return { turnId, userSeq: null };
    const user = await this.event('user', { text }, turnId);
    return { turnId, userSeq: user.seq };
  }

  /** A tool call: its tool_use and tool_result events, and the tool_call row the runner audits. */
  async tool(name: string, turnId: string): Promise<{ toolCallId: string; useSeq: number }> {
    const toolUseId = `toolu_${randomUUID().replace(/-/g, '')}`;
    const use = await this.event('tool_use', { id: toolUseId, name, input: { command: 'ls' } }, turnId);
    await this.event('tool_result', { toolUseId, content: 'a\nb', isError: false }, turnId);
    const toolCallId = randomUUID();
    await this.h.sql.query(
      `INSERT INTO "tool_call"("id","session_id","name","tool_use_id","input","output") VALUES ($1,$2,$3,$4,$5,$6)`,
      [toolCallId, this.sessionId, name, toolUseId, JSON.stringify({ command: 'ls' }), JSON.stringify('a\nb')],
    );
    return { toolCallId, useSeq: use.seq };
  }
}

interface Story {
  owner: { id: string; bearer: string };
  stranger: { id: string; bearer: string };
  transcript: Transcript;
  /** A turn from early on, deep below the tail page. */
  early: { turnId: string; userSeq: number };
  /** A tool call in the middle of the session. */
  call: { toolCallId: string; useSeq: number };
  /** An assistant reply in the middle, cited as an event. */
  reply: { id: string; seq: number };
  /** A turn that never reached the transcript (withdrawn before delivery). */
  silent: string;
  first: { id: string; seq: number };
  last: { id: string; seq: number };
  /** Another session of the same owner, and one of the stranger's. */
  otherSession: { sessionId: string; eventId: string };
  strangers: { sessionId: string; eventId: string; turnId: string };
}

let story: Promise<Story> | undefined;

/** 60-odd events with pings between them: a session whose early records are pages below its tail. */
function seed(): Promise<Story> {
  story ??= (async () => {
    const h = await boot();
    const owner = await account(h, 'owner');
    const stranger = await account(h, 'stranger');
    const transcript = new Transcript(h, await session(h, owner.id));

    const first = await transcript.event('system', { subtype: 'init', sessionId: 'rt-1', model: 'm' });
    const early = await transcript.turn('the early question');
    await transcript.event('assistant', { text: 'the early answer' }, early.turnId);
    await transcript.event('turn_end', { subtype: 'success' }, early.turnId);
    for (let i = 0; i < 12; i++) {
      const t = await transcript.turn(`question ${i}`);
      await transcript.event('system', { subtype: 'status', sessionId: 'rt-1', model: null });
      await transcript.event('assistant', { text: `answer ${i}` }, t.turnId);
    }
    const middle = await transcript.turn('look at the files');
    const call = await transcript.tool('Bash', middle.turnId);
    const reply = await transcript.event('assistant', { text: 'the files are a and b' }, middle.turnId);
    const silent = (await transcript.turn('withdrawn before delivery', false)).turnId;
    for (let i = 0; i < 12; i++) {
      const t = await transcript.turn(`later question ${i}`);
      await transcript.event('system', { subtype: 'status', sessionId: 'rt-1', model: null });
      await transcript.event('assistant', { text: `later answer ${i}` }, t.turnId);
    }
    const last = await transcript.event('turn_end', { subtype: 'success' });

    const other = new Transcript(h, await session(h, owner.id));
    const otherEvent = await other.event('assistant', { text: 'another session of the same owner' });

    const theirs = new Transcript(h, await session(h, stranger.id));
    const theirTurn = await theirs.turn('the stranger asks');
    const theirEvent = await theirs.event('assistant', { text: 'the stranger is answered' }, theirTurn.turnId);

    return {
      owner,
      stranger,
      transcript,
      early: { turnId: early.turnId, userSeq: early.userSeq! },
      call,
      reply,
      silent,
      first,
      last,
      otherSession: { sessionId: other.sessionId, eventId: otherEvent.id },
      strangers: { sessionId: theirs.sessionId, eventId: theirEvent.id, turnId: theirTurn.turnId },
    };
  })();
  return story;
}

// ── 1. the page around a record, and the pages out from it ──────────────────────────────────────────

test('around an event: the page it sits in, centred on it, with a cursor each way', { skip }, async () => {
  const h = await boot();
  const s = await seed();
  const shown = s.transcript.shown;
  const answer = await page(h, s.owner.bearer, s.transcript.sessionId, `around=${uuidToBase62(s.reply.id)}&limit=10`);
  expectStatus(answer, 200, 'the owner reads around their own event');

  // Where the record resolved to, in the public spelling a link carries.
  assert.equal(answer.body.anchor.kind, 'event');
  assert.equal(answer.body.anchor.id, uuidToBase62(s.reply.id));
  assert.equal(answer.body.anchor.seq, s.reply.seq);

  // Ten events the reader can see, in order, the record among them with half the page either side —
  // and not one of the pings stored between them.
  const at = shown.indexOf(s.reply.seq);
  assert.deepEqual(seqs(answer), shown.slice(at - 5, at + 5));

  // A cursor each way, and they are the page's own edges: `before=` and `after=` continue from them.
  assert.equal(answer.body.before, shown[at - 5]);
  assert.equal(answer.body.after, shown[at + 4]);
  assert.equal(answer.body.hasMore, true, 'older events remain, as on every page');
});

test('paging out from the anchor both ways walks the whole transcript without a gap or a repeat', { skip }, async () => {
  const h = await boot();
  const s = await seed();
  const shown = s.transcript.shown;
  const around = await page(h, s.owner.bearer, s.transcript.sessionId, `around=${uuidToBase62(s.call.toolCallId)}&limit=8`);
  expectStatus(around, 200, 'the owner reads around their own tool call');
  let walked = seqs(around);

  // Older, with the ordinary `before=` read, until the cursor says the start of the session is in.
  let before: number | null = around.body.before;
  let steps = 0;
  while (before !== null) {
    const older = await page(h, s.owner.bearer, s.transcript.sessionId, `before=${before}&limit=7`);
    expectStatus(older, 200, 'an older page');
    walked = [...seqs(older), ...walked];
    before = older.body.hasMore ? older.body.events[0].seq : null;
    assert.ok(++steps < 50, 'paging older never ends');
  }

  // Newer, with `after=`, until the cursor comes back null at the tail.
  let afterCursor: number | null = around.body.after;
  while (afterCursor !== null) {
    const newer = await page(h, s.owner.bearer, s.transcript.sessionId, `after=${afterCursor}&limit=7`);
    expectStatus(newer, 200, 'a newer page');
    assert.equal(newer.body.hasMore, true, 'a page newer than a cursor has older events behind it');
    assert.equal(newer.body.before, newer.body.events[0].seq);
    walked = [...walked, ...seqs(newer)];
    afterCursor = newer.body.after;
    assert.ok(++steps < 50, 'paging newer never ends');
  }

  assert.deepEqual(walked, shown, 'both walks together are the transcript, once each, in order');
  assert.equal(walked[0], s.first.seq);
  assert.equal(walked[walked.length - 1], s.last.seq);
});

test('a record near either end still comes back in a full page, with no cursor past that end', { skip }, async () => {
  const h = await boot();
  const s = await seed();
  const shown = s.transcript.shown;

  const start = await page(h, s.owner.bearer, s.transcript.sessionId, `around=${uuidToBase62(s.first.id)}&limit=10`);
  expectStatus(start, 200, 'around the first event');
  assert.deepEqual(seqs(start), shown.slice(0, 10), 'the room older events would have had goes to newer ones');
  assert.equal(start.body.before, null);
  assert.equal(start.body.hasMore, false);
  assert.equal(start.body.after, shown[9]);

  const end = await page(h, s.owner.bearer, s.transcript.sessionId, `around=${uuidToBase62(s.last.id)}&limit=10`);
  expectStatus(end, 200, 'around the last event');
  assert.deepEqual(seqs(end), shown.slice(-10));
  assert.equal(end.body.after, null, 'the page reaches the tail: nothing newer to page to');
  assert.equal(end.body.before, shown[shown.length - 10]);

  // Past the tail, the `after=` read is an empty page that says so.
  const beyond = await page(h, s.owner.bearer, s.transcript.sessionId, `after=${s.last.seq}&limit=10`);
  expectStatus(beyond, 200, 'after the last event');
  assert.deepEqual(beyond.body.events, []);
  assert.equal(beyond.body.after, null);
});

// ── 2. each kind of record lands where the reader expects ───────────────────────────────────────────

test('a turn lands on the message it sent, deep below the tail page', { skip }, async () => {
  const h = await boot();
  const s = await seed();
  const answer = await page(h, s.owner.bearer, s.transcript.sessionId, `around=${uuidToBase62(s.early.turnId)}&limit=6`);
  expectStatus(answer, 200, 'around an early turn');
  assert.equal(answer.body.anchor.kind, 'turn');
  assert.equal(answer.body.anchor.id, uuidToBase62(s.early.turnId));
  assert.equal(answer.body.anchor.seq, s.early.userSeq);
  const user = answer.body.events.find((e: { seq: number }) => e.seq === s.early.userSeq);
  assert.equal(user.type, 'user');
  assert.equal(user.payload.text, 'the early question');
  // The tail page a session opens on does not reach it: this is the read that makes it reachable.
  const tail = await page(h, s.owner.bearer, s.transcript.sessionId, 'tail=10');
  expectStatus(tail, 200, 'the tail page');
  assert.ok(!seqs(tail).includes(s.early.userSeq));
});

test('a tool call lands on its tool_use event', { skip }, async () => {
  const h = await boot();
  const s = await seed();
  const answer = await page(h, s.owner.bearer, s.transcript.sessionId, `around=${uuidToBase62(s.call.toolCallId)}&limit=5`);
  expectStatus(answer, 200, 'around a tool call');
  assert.equal(answer.body.anchor.kind, 'tool_call');
  assert.equal(answer.body.anchor.seq, s.call.useSeq);
  const use = answer.body.events.find((e: { seq: number }) => e.seq === s.call.useSeq);
  assert.equal(use.type, 'tool_use');
  assert.equal(use.payload.name, 'Bash');
});

test('the record id is read in either spelling, and a malformed one is a 400', { skip }, async () => {
  const h = await boot();
  const s = await seed();
  const byUuid = await page(h, s.owner.bearer, s.transcript.sessionId, `around=${s.reply.id}&limit=4`);
  const byPublicId = await page(h, s.owner.bearer, s.transcript.sessionId, `around=${uuidToBase62(s.reply.id)}&limit=4`);
  expectStatus(byUuid, 200, 'a raw uuid');
  assert.deepEqual(byUuid.body, byPublicId.body);
  expectStatus(await page(h, s.owner.bearer, s.transcript.sessionId, 'around=not-an-id!'), 400, 'a malformed id');
});

test('a turn the transcript shows nothing of is not found', { skip }, async () => {
  const h = await boot();
  const s = await seed();
  expectStatus(
    await page(h, s.owner.bearer, s.transcript.sessionId, `around=${uuidToBase62(s.silent)}`),
    404,
    'a withdrawn turn has nowhere to be scrolled to',
  );
  expectStatus(
    await page(h, s.owner.bearer, s.transcript.sessionId, `around=${uuidToBase62(randomUUID())}`),
    404,
    'an id nothing has',
  );
});

// ── 3. across tenants: 404, every way round ─────────────────────────────────────────────────────────

test('across tenants it is 404 every way round', { skip }, async () => {
  const h = await boot();
  const s = await seed();
  const mine = s.transcript.sessionId;

  // The stranger, naming the owner's session and the owner's own record in it.
  for (const record of [s.reply.id, s.early.turnId, s.call.toolCallId]) {
    const answer = await page(h, s.stranger.bearer, mine, `around=${uuidToBase62(record)}`);
    expectStatus(answer, 404, 'another owner\'s session');
    assert.equal(answer.body.events, undefined, 'nothing of the transcript rides the refusal');
  }
  // … nor page it any other way, `after=` included.
  expectStatus(await page(h, s.stranger.bearer, mine, 'after=0'), 404, 'another owner\'s session, paged newer');

  // The owner, naming the stranger's records inside their own session: the record is not this session's.
  for (const record of [s.strangers.eventId, s.strangers.turnId]) {
    expectStatus(await page(h, s.owner.bearer, mine, `around=${uuidToBase62(record)}`), 404, 'another owner\'s record');
  }
  // The stranger, naming their own record inside the owner's session: still the owner's session.
  expectStatus(
    await page(h, s.stranger.bearer, mine, `around=${uuidToBase62(s.strangers.eventId)}`),
    404,
    'one\'s own record, in another owner\'s session',
  );

  // And within one owner, a record belongs to the session it is in: the link names both.
  expectStatus(
    await page(h, s.owner.bearer, mine, `around=${uuidToBase62(s.otherSession.eventId)}`),
    404,
    'a record of the owner\'s other session',
  );
  expectStatus(
    await page(h, s.owner.bearer, s.otherSession.sessionId, `around=${uuidToBase62(s.otherSession.eventId)}`),
    200,
    'the same record, in its own session',
  );
});
