/**
 * A session request's outcome, handed back to an asker that is running a turn, is written INTO that
 * turn — against a real PostgreSQL (docs/session-request-reply-contract.md §4.2, §8 criteria 28–32).
 *
 * It used to be queued behind the turn: the asker read the answer only once the turn it was in had
 * finished, and that turn was often the one waiting for it. Now the hand-off routes an outcome the way
 * a background job's exit is routed (createTurn's `steerIfLive`, runner-api/background-job-wake.ts):
 *
 *   28. a Claude asker running a turn under a live lease, behind a runner that declared routing-v1, is
 *       handed the outcome as a CURRENT_WORK steer aimed at that exact turn — listed as a steer with its
 *       reply cards, never withdrawable, delivered with blocks that say they joined the turn the asker
 *       is in, charged neither as a steer nor against the pair's hourly limit; and an idle asker, a turn
 *       whose lease has run out, a kimi asker, or a runner without routing-v1 gets the next-turn reply
 *       turn it always got;
 *   29. outcomes join a reply waiting on their own route only: a steer still waiting for the same
 *       running turn, or the queued next-turn reply turn — never each other's, and never a steer the
 *       runner has already taken;
 *   30. a reply steer whose turn ended before the engine read it — at the target's completion, or
 *       handed back by the runner — is the next-turn reply turn again, on the same row: every outcome
 *       it carried still names it, and a reply turn already queued is folded into it, so one turn says
 *       them all. One the runner could not write in lets its outcome go, and the request worker hands
 *       it back;
 *   31. an interrupt takes a reply steer the runner has not taken with the rest of the queue: the
 *       outcome is held on its request row, nothing queues it again, and the asker's next delivered
 *       turn says it;
 *   32. a transient failure of the turn a reply steer joined has the auto-retry re-send THAT turn —
 *       the person's words, not a reply turn in their place — and the re-sent turn says the outcome
 *       the steer never got to.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/sessions/session-reply-steer.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { ConflictException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import {
  type Prisma,
  type PrismaClient,
  type Runner,
  RunStatus,
  RunnerStatus,
  SessionDispatchOrigin,
  SessionRunSource,
} from '@prisma/client';
import {
  RunEventType,
  RunStatus as SharedRunStatus,
  SESSION_CURRENT_WORK_ROUTING_V1,
  TURN_COMPLETE_STEER_REQUEUE,
  base62ToUuid,
  uuidToBase62,
} from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerOrchestrationAuthorizer } from '../runner-api/runner-orchestration-authorizer';
import { RunnerSessionsController } from '../runner-api/runner-sessions.controller';
import { AutoRetryService } from './auto-retry.service';
import { SESSION_REPLY_TURN_PREFIX } from './session-request';
import { SessionRequestService } from './session-request.service';
import { SessionRequestWorker } from './session-request.worker';
import { SessionsService } from './sessions.service';
import { AUTO_RETRY_TURN_KEY_PREFIX } from './watch-turn-key';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a session row carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;
const HOUR = 60 * 60 * 1000;
const ROUTING = [SESSION_CURRENT_WORK_ROUTING_V1];

/** How a block delivered by a steer says it joined the turn the asker is in. */
const STEER_HEAD = 'You are working, so this reply was added to the turn you are in; no turn was opened for it.';

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

test('an outcome handed back to an asker running a turn is written into that turn, and is never lost on the way', {
  skip, concurrency: 1, timeout: 600_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });
  const db = prisma as unknown as PrismaService;

  // ── the world: one account, one machine that declared routing-v1, one workspace ─────────────────
  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const workspaceId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `session-reply-steer-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: {
      id: runnerId, ownerId, name: 'the machine every session runs on', tokenHash: sha256(`token-${runnerId}`),
      status: RunnerStatus.ONLINE, lastHeartbeatAt: new Date(), capabilities: ROUTING, capabilitiesReportedAt: new Date(),
    },
  });
  await prisma.workspace.create({ data: { id: workspaceId, ownerId, runnerId, name: 'orbit-worker', enabled: true } });
  const runner = { id: runnerId, ownerId } as Runner;
  /** The runner says it is alive: a sweep releases no retry onto a machine it believes is down. */
  const heartbeat = () => prisma.runner.update({ where: { id: runnerId }, data: { lastHeartbeatAt: new Date() } });

  /** A session on this runner, parked between turns. */
  async function session(title: string, data: Partial<Prisma.SessionUncheckedCreateInput> = {}): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id, ownerId, creatorId: ownerId, workspaceId, assignedRunnerId: runnerId,
        title, prompt: title, provider: 'claude', status: RunStatus.AWAITING_INPUT,
        numTurns: 1, startedAt: new Date(), runtimeSessionId: `runtime-${id}`,
        dispatchOrigin: SessionDispatchOrigin.USER, runSource: SessionRunSource.MANUAL,
        ...data,
      },
    });
    return id;
  }

  // ── the doors ─────────────────────────────────────────────────────────────────────────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(db, queue as never, realtime as never);
  const requests = new SessionRequestService(db, sessions, realtime as never);
  // Never started: each case drives its passes by hand.
  const worker = new SessionRequestWorker(db, requests, { pollIntervalMs: HOUR });
  const orchestration = new RunnerOrchestrationAuthorizer(db, new JwtService({ secret: 'session-reply-steer-pg' }));
  const attempts = { chargeSteer: async () => undefined };
  const sendDoor = new RunnerSessionsController(sessions, orchestration, {} as never, attempts as never, undefined, requests);
  const api = new RunnerApiController(
    db,
    queue as never,
    realtime as never,
    {} as never,
    orchestration,
    // The messages here carry no `#`-references and reach no list console.
    { expand: async (_owner: string, content?: string) => content } as never,
    { appendFor: async (_tx: unknown, _id: string, content?: string) => content } as never,
    undefined,
    undefined,
    undefined,
    undefined,
    sessions,
    undefined,
    undefined,
    undefined,
    undefined,
    requests,
  );

  /** What every hand-off asked createTurn for: the route, and whether anything was charged for it. */
  const handOffs: Array<{ steerIfLive?: boolean; participateSendTransaction?: unknown }> = [];
  const createTurn = sessions.createTurn.bind(sessions);
  (sessions as { createTurn: typeof createTurn }).createTurn = (owner, id, dto, opts) => {
    if (dto.clientTurnId.startsWith(SESSION_REPLY_TURN_PREFIX)) handOffs.push(opts ?? {});
    return createTurn(owner, id, dto, opts);
  };

  /** `session_send` with `expectReply`, from a session with its own credential. */
  async function ask(from: string, to: string, message: string): Promise<{ requestId: string; id: string }> {
    const receipt = await sendDoor.sendMessage(
      runner, undefined, from, await orchestration.issue(runnerId, from), to,
      { message, clientTurnId: randomUUID(), expectReply: true } as never,
    ) as Record<string, unknown>;
    assert.equal(typeof receipt.requestId, 'string', `the send answered no request: ${JSON.stringify(receipt)}`);
    return { requestId: String(receipt.requestId), id: base62ToUuid(String(receipt.requestId)) };
  }

  /** `session_reply` as the runner calls it, from the recipient's own credential. */
  async function reply(from: string, requestId: string, message: string) {
    return sendDoor.replyToRequest(
      runner, undefined, from, await orchestration.issue(runnerId, from), base62ToUuid(requestId), { message } as never,
    );
  }

  /**
   * The claim's own write, as the runner's lease routes make it: PENDING -> RUNNING is dropped in
   * silence for a session that has a recorded engine unless the same transaction declares it reads
   * that engine (migration 0414, `common/session-scheduling.ts`).
   */
  async function claimSession(sessionId: string): Promise<void> {
    await prisma.$transaction(async (tx) => {
      await tx.$executeRaw`SELECT set_config('orbit.claim_reads_session_engine', '1', true)`;
      await tx.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    });
  }

  /** The claim, then the polls after it until a message comes out (a control turn is answered on the spot). */
  async function deliver(sessionId: string): Promise<{ turnId: string; content: string; clientTurnId: string }> {
    await claimSession(sessionId);
    for (;;) {
      const handed = await (api as unknown as {
        dequeueTurn: (sessionId: string, runnerId: string, leaseGeneration: string | null) => Promise<Record<string, unknown> | null>;
      }).dequeueTurn.call(api, sessionId, runnerId, null);
      assert.ok(handed, `the inbox of ${sessionId} handed nothing out`);
      const turn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: String(handed.turnId) } });
      if (turn.kind !== 'message') continue;
      return { turnId: turn.id, content: String(handed.content ?? ''), clientTurnId: turn.clientTurnId };
    }
  }

  /** The runner's claim of a steer, as a poller that can write one into the running turn and declared routing-v1. */
  async function deliverSteer(sessionId: string): Promise<{ turnId: string; content: string; targetTurnId?: string }> {
    const handed = await (api as unknown as {
      dequeueTurn: (
        sessionId: string, runnerId: string, leaseGeneration: string | null, acceptsSteer: boolean,
        declaredCapabilities: readonly string[],
      ) => Promise<Record<string, unknown> | null>;
    }).dequeueTurn.call(api, sessionId, runnerId, null, true, ROUTING);
    assert.ok(handed, `the inbox of ${sessionId} handed no steer out`);
    const turn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: String(handed.turnId) } });
    assert.equal(turn.kind, 'steer', `the inbox handed out a ${turn.kind}, not the steer`);
    assert.equal(turn.status, 'IN_FLIGHT');
    return {
      turnId: turn.id,
      content: String(handed.content ?? ''),
      ...(handed.targetTurnId ? { targetTurnId: String(handed.targetTurnId) } : {}),
    };
  }

  /** The runner settles a steer: the engine took it, or it could not be written in. */
  function settleSteer(sessionId: string, turnId: string, delivered: boolean) {
    return api.turnComplete({ id: runnerId } as never, sessionId, {
      turnId,
      status: delivered ? SharedRunStatus.SUCCEEDED : SharedRunStatus.FAILED,
      subtype: 'steer',
      ...(delivered ? {} : { result: 'steer not delivered to the engine: delivery unconfirmed' }),
    } as never);
  }

  /** The runner hands a steer back: the engine provably never read it. */
  function requeueSteer(sessionId: string, turnId: string) {
    return api.turnComplete({ id: runnerId } as never, sessionId, {
      turnId, status: SharedRunStatus.SUCCEEDED, subtype: TURN_COMPLETE_STEER_REQUEUE,
    } as never);
  }

  /** An asker in the middle of a turn of its own: the owner's message, handed to its engine. */
  async function busy(asker: string, words = 'migrate the remaining shards'): Promise<string> {
    await sessions.createTurn(ownerId, asker, { clientTurnId: randomUUID(), content: words });
    return (await deliver(asker)).turnId;
  }

  /** The running turn's lease runs out, or is taken again: what decides whether a turn can be steered. */
  const leaseRunsOut = (turnId: string) =>
    prisma.conversationTurn.update({ where: { id: turnId }, data: { leaseDeadlineAt: new Date(Date.now() - 60_000) } });
  const leaseRenewed = (turnId: string) =>
    prisma.conversationTurn.update({ where: { id: turnId }, data: { leaseDeadlineAt: new Date(Date.now() + 5 * 60_000) } });

  const seqs = new Map<string, number>();
  /** The runner's events for one turn, through the real ingest. Answers what was stored. */
  async function say(sessionId: string, turnId: string, type: RunEventType, payload: Record<string, unknown>) {
    const seq = (seqs.get(sessionId) ?? 100) + 1;
    seqs.set(sessionId, seq);
    await api.events({ id: runnerId } as never, sessionId, {
      events: [{ seq, type, ts: new Date().toISOString(), turnId, payload }],
    } as never);
    return (await prisma.runEvent.findFirstOrThrow({ where: { sessionId, seq } })).payload as Record<string, unknown>;
  }

  /** The turn ends as the runner reports it: something said, then the completion. */
  async function finish(sessionId: string, turnId: string, words = 'done') {
    await say(sessionId, turnId, RunEventType.ASSISTANT, { text: words });
    await api.turnComplete({ id: runnerId } as never, sessionId, {
      turnId, status: SharedRunStatus.SUCCEEDED, subtype: 'success', numTurns: 1, costUsd: 0,
    } as never);
  }

  const requestRow = (id: string) => prisma.sessionRequest.findUniqueOrThrow({ where: { id } });
  const turnRow = (id: string) => prisma.conversationTurn.findUniqueOrThrow({ where: { id } });
  const replyTurnsOf = (sessionId: string) => prisma.conversationTurn.findMany({
    where: { sessionId, clientTurnId: { startsWith: SESSION_REPLY_TURN_PREFIX } },
    orderBy: { seq: 'asc' },
  });
  const statusOf = async (sessionId: string) => (await prisma.session.findUniqueOrThrow({ where: { id: sessionId } })).status;
  /** How many `<orbit-session-reply>` blocks for this request a text carries. */
  const blocksFor = (content: string, requestId: string) =>
    content.split(`<orbit-session-reply request-id="${uuidToBase62(requestId)}"`).length - 1;
  /** The executable turns of a session still waiting for a runner. */
  const queuedExecutables = (sessionId: string) => prisma.conversationTurn.count({
    where: { sessionId, kind: { in: ['message', 'shell'] }, status: 'PENDING' },
  });

  type Listed = {
    turnId: string;
    kind: string;
    placement?: string;
    targetTurnId?: string;
    content: string;
    sessionReplies?: Array<Record<string, unknown>>;
  };
  const listed = async (sessionId: string, view?: 'active'): Promise<Listed[]> =>
    (view === 'active'
      ? await sessions.listQueuedTurns(ownerId, sessionId, 'active')
      : await sessions.listQueuedTurns(ownerId, sessionId)) as unknown as Listed[];

  // ── 28. the route ─────────────────────────────────────────────────────────────────────────────

  await t.test('an asker running a turn is handed the outcome as a CURRENT_WORK steer aimed at that turn', async () => {
    const asker = await session('Coordinator: waits in its turn for the answer');
    const recipient = await session('Worker: answers');
    const request = await ask(asker, recipient, 'is shard 3 migrated?');
    const running = await busy(asker);
    const sent = handOffs.length;

    assert.equal((await reply(recipient, request.requestId, 'yes, shard 3 is migrated')).handOff, 'QUEUED');
    const [steer, ...more] = await replyTurnsOf(asker);
    assert.ok(steer, 'the outcome was handed back on no turn');
    assert.equal(more.length, 0);
    assert.deepEqual(
      {
        kind: steer.kind, sendIntent: steer.sendIntent, targetTurnId: steer.targetTurnId,
        status: steer.status, content: steer.content, senderSessionId: steer.senderSessionId,
      },
      {
        kind: 'steer', sendIntent: 'CURRENT_WORK', targetTurnId: running,
        // Nobody's words, as for every reply turn: the blocks are written in at delivery.
        status: 'PENDING', content: '', senderSessionId: null,
      },
    );
    assert.equal((await requestRow(request.id)).replyClientTurnId, steer.clientTurnId);
    // No turn was opened for it: the asker is still running the turn it was running.
    assert.equal(await statusOf(asker), RunStatus.RUNNING);
    assert.equal((await turnRow(running)).status, 'IN_FLIGHT');
    // A platform delivery: routed by the server, charged neither as a steer nor against the pair's
    // hourly limit (§4.2).
    assert.deepEqual(handOffs.slice(sent).map((opts) => [opts.steerIfLive, opts.participateSendTransaction]), [[true, undefined]]);
    assert.equal(await prisma.sessionMessageCharge.count({ where: { fromSessionId: recipient, toSessionId: asker } }), 0);

    // Listed as a steer in both views, with its reply cards and the blocks the runner will be handed;
    // not withdrawable, and the refusal takes nothing of it along.
    const active = (await listed(asker, 'active')).find((row) => row.turnId === steer.id);
    const queued = (await listed(asker)).find((row) => row.turnId === steer.id);
    assert.ok(active && queued, 'the reply steer is not listed in both views');
    assert.equal(active.kind, 'steer');
    assert.equal(active.placement, 'steer');
    assert.equal(active.targetTurnId, running);
    assert.equal(queued.kind, 'steer');
    for (const row of [active, queued]) {
      assert.deepEqual(row.sessionReplies?.map((card) => [card.requestId, card.replyText]), [
        [request.requestId, 'yes, shard 3 is migrated'],
      ]);
      assert.ok(row.content.includes(STEER_HEAD), row.content);
      assert.equal(blocksFor(row.content, request.id), 1);
    }
    await assert.rejects(sessions.cancelQueuedTurn(ownerId, asker, steer.id), ConflictException);
    assert.equal((await requestRow(request.id)).replyClientTurnId, steer.clientTurnId);

    // The runner takes it with the blocks written in, saying they joined the turn the asker is in —
    // the same bytes both views listed.
    const handed = await deliverSteer(asker);
    assert.equal(handed.turnId, steer.id);
    assert.equal(handed.targetTurnId, running);
    assert.equal(blocksFor(handed.content, request.id), 1);
    assert.match(handed.content, /Reply: yes, shard 3 is migrated/);
    assert.ok(handed.content.includes(STEER_HEAD), handed.content);
    assert.equal(handed.content, active.content);
    assert.equal(handed.content, queued.content);
    // Its echo is the control plane's note, drawn as the reply card.
    const echoed = await say(asker, steer.id, RunEventType.USER, { text: handed.content, steer: true, delivery: 'acknowledged' });
    assert.equal(echoed.controlPlaneNote, handed.content, 'the outcome was stored as words somebody wrote');
    assert.deepEqual((echoed.sessionReplies as Array<Record<string, unknown>>).map((card) => card.requestId), [request.requestId]);
    assert.equal((await turnRow(steer.id)).deliveryStatus, 'ACKNOWLEDGED');

    // Read in the turn it joined: settled, and nothing is queued to say it again.
    await settleSteer(asker, steer.id, true);
    await finish(asker, running);
    assert.equal(await statusOf(asker), RunStatus.AWAITING_INPUT);
    assert.equal(await queuedExecutables(asker), 0);
    assert.equal((await replyTurnsOf(asker)).length, 1);
    assert.equal((await requestRow(request.id)).replyClientTurnId, steer.clientTurnId);
  });

  await t.test('an idle asker, a lease that ran out, a kimi asker or a runner without routing-v1: the next-turn reply turn, as always', async () => {
    const cases: Array<[string, (asker: string) => Promise<void>, Partial<Prisma.SessionUncheckedCreateInput>?]> = [
      ['an idle asker', async () => undefined],
      ['a running turn whose lease has run out', async (asker) => { await leaseRunsOut(await busy(asker)); }],
      // The built-in kimi runtime: a runtime with no mid-turn steer, whatever the runner declared.
      ['a kimi asker running a turn', async (asker) => { await busy(asker); }, { provider: 'kimi', providerBuiltin: true }],
      ['a runner that never declared routing-v1', async (asker) => {
        await busy(asker);
        await prisma.runner.update({ where: { id: runnerId }, data: { capabilities: [] } });
      }],
    ];
    try {
      for (const [how, setUp, data] of cases) {
        const asker = await session(`Coordinator: ${how}`, data);
        const recipient = await session('Worker: answers');
        const request = await ask(asker, recipient, `can you take ${how}?`);
        await setUp(asker);
        const sent = handOffs.length;
        assert.equal((await reply(recipient, request.requestId, 'taken')).handOff, 'QUEUED', how);
        const [turn, ...more] = await replyTurnsOf(asker);
        assert.equal(more.length, 0, how);
        assert.deepEqual(
          { kind: turn.kind, sendIntent: turn.sendIntent, targetTurnId: turn.targetTurnId, status: turn.status },
          { kind: 'message', sendIntent: 'NEXT_TURN', targetTurnId: null, status: 'PENDING' },
          how,
        );
        assert.equal((await requestRow(request.id)).replyClientTurnId, turn.clientTurnId, how);
        // Asked for the steer all the same: the route is the server's to decide, under the lock.
        assert.deepEqual(handOffs.slice(sent).map((opts) => opts.steerIfLive), [true], how);
        const row = (await listed(asker, 'active')).find((listedRow) => listedRow.turnId === turn.id);
        assert.equal(row?.placement, 'queued', how);
        assert.ok(!row?.content.includes(STEER_HEAD), `${how}: a turn of its own says it joined one:\n${row?.content}`);
        await prisma.runner.update({ where: { id: runnerId }, data: { capabilities: ROUTING } });
      }
    } finally {
      await prisma.runner.update({ where: { id: runnerId }, data: { capabilities: ROUTING } });
    }

    // Delivered as the turn of its own it is, in the words it has always had.
    const asker = await session('Coordinator: idle when the answer comes');
    const recipient = await session('Worker: answers');
    const request = await ask(asker, recipient, 'which migration number is free?');
    await reply(recipient, request.requestId, '0383');
    const back = await deliver(asker);
    assert.equal(blocksFor(back.content, request.id), 1);
    assert.ok(back.content.startsWith('<orbit-session-reply '), back.content);
    assert.ok(!back.content.includes(STEER_HEAD), back.content);
  });

  // ── 29. coalescing, one route at a time ─────────────────────────────────────────────────────────

  await t.test('outcomes join a reply waiting on their own route only, and never a steer the runner has taken', async () => {
    const asker = await session('Coordinator: asks five workers while it works');
    const recipient = await session('Worker: answers all five');
    const [a, b, c, d, e] = [
      await ask(asker, recipient, 'shard A?'), await ask(asker, recipient, 'shard B?'), await ask(asker, recipient, 'shard C?'),
      await ask(asker, recipient, 'shard D?'), await ask(asker, recipient, 'shard E?'),
    ];
    const running = await busy(asker);

    // The running turn's lease is running out, so A waits for the next turn.
    await leaseRunsOut(running);
    assert.equal((await reply(recipient, a.requestId, 'A done')).handOff, 'QUEUED');
    const [nextTurn] = await replyTurnsOf(asker);
    assert.equal(nextTurn.kind, 'message');
    // Renewed: B goes into the running turn, as a steer of its own — not onto the queued reply turn.
    await leaseRenewed(running);
    assert.equal((await reply(recipient, b.requestId, 'B done')).handOff, 'QUEUED');
    const steer = (await replyTurnsOf(asker)).find((turn) => turn.id !== nextTurn.id)!;
    assert.equal(steer.kind, 'steer');
    assert.equal(steer.targetTurnId, running);
    // C joins the steer still waiting for that turn...
    assert.equal((await reply(recipient, c.requestId, 'C done')).handOff, 'MERGED');
    // ...and D, with the lease running out again, the queued reply turn — not the steer.
    await leaseRunsOut(running);
    assert.equal((await reply(recipient, d.requestId, 'D done')).handOff, 'MERGED');
    await leaseRenewed(running);
    assert.equal((await replyTurnsOf(asker)).length, 2);
    assert.equal((await requestRow(a.id)).replyClientTurnId, nextTurn.clientTurnId);
    assert.equal((await requestRow(b.id)).replyClientTurnId, steer.clientTurnId);
    assert.equal((await requestRow(c.id)).replyClientTurnId, steer.clientTurnId);
    assert.equal((await requestRow(d.id)).replyClientTurnId, nextTurn.clientTurnId);

    // Once the runner has taken the steer, nothing more joins it: E is a steer of its own.
    const handed = await deliverSteer(asker);
    assert.equal(handed.turnId, steer.id);
    assert.equal(blocksFor(handed.content, b.id) + blocksFor(handed.content, c.id), 2);
    assert.equal(blocksFor(handed.content, a.id) + blocksFor(handed.content, d.id), 0);
    assert.equal((await reply(recipient, e.requestId, 'E done')).handOff, 'QUEUED');
    const turns = await replyTurnsOf(asker);
    assert.equal(turns.length, 3);
    const second = turns.find((turn) => turn.id !== nextTurn.id && turn.id !== steer.id)!;
    assert.deepEqual([second.kind, second.status, second.targetTurnId], ['steer', 'PENDING', running]);
    assert.equal((await requestRow(e.id)).replyClientTurnId, second.clientTurnId);
  });

  // ── 30. a steer that misses its turn ────────────────────────────────────────────────────────────

  await t.test('a reply steer its turn finished without reading is the next-turn reply turn again, and takes the queued one into itself', async () => {
    const asker = await session('Coordinator: its turn ends before the answer is read');
    const recipient = await session('Worker: answers twice');
    const first = await ask(asker, recipient, 'is the schema frozen?');
    const second = await ask(asker, recipient, 'is the release branch cut?');
    const running = await busy(asker);
    await leaseRunsOut(running);
    await reply(recipient, first.requestId, 'frozen');
    const [queued] = await replyTurnsOf(asker);
    assert.equal(queued.kind, 'message');
    await leaseRenewed(running);
    await reply(recipient, second.requestId, 'cut at 6cdca5a03');
    const steer = (await replyTurnsOf(asker)).find((turn) => turn.id !== queued.id)!;
    assert.equal(steer.kind, 'steer');

    // The turn ends before the runner took the steer: the same row is the next-turn reply turn now,
    // and the reply turn queued beside it is folded into it rather than opening a second turn.
    await finish(asker, running);
    const left = await replyTurnsOf(asker);
    assert.deepEqual(left.map((turn) => [turn.id, turn.kind, turn.sendIntent, turn.targetTurnId, turn.status]), [
      [steer.id, 'message', 'NEXT_TURN', null, 'PENDING'],
    ], 'a missed reply steer and the queued reply turn would each open a turn');
    assert.equal(left[0].clientTurnId, steer.clientTurnId);
    // Every outcome names the turn that delivers it.
    assert.equal((await requestRow(first.id)).replyClientTurnId, steer.clientTurnId);
    assert.equal((await requestRow(second.id)).replyClientTurnId, steer.clientTurnId);
    // The slot passed to it rather than the session parking with a reply queued behind nothing.
    assert.equal(await statusOf(asker), RunStatus.RUNNING);
    const row = (await listed(asker)).find((listedRow) => listedRow.turnId === steer.id);
    assert.equal(row?.kind, 'message');

    // Delivered as a turn of its own, both outcomes in the order they came, in the bytes it listed.
    const back = await deliver(asker);
    assert.equal(back.turnId, steer.id);
    assert.equal(blocksFor(back.content, first.id), 1);
    assert.equal(blocksFor(back.content, second.id), 1);
    assert.ok(back.content.indexOf('frozen') < back.content.indexOf('cut at 6cdca5a03'), 'out of the order they came');
    assert.ok(!back.content.includes(STEER_HEAD), back.content);
    assert.equal(back.content, row?.content);
    assert.equal(await queuedExecutables(asker), 0, 'a second reply turn is still queued');
  });

  await t.test('a reply steer the runner hands back unread takes the queued reply turn with it', async () => {
    const asker = await session('Coordinator: its engine is fenced before it reads the answer');
    const recipient = await session('Worker: answers twice');
    const first = await ask(asker, recipient, 'did the canary pass?');
    const second = await ask(asker, recipient, 'did the rollback drill pass?');
    const running = await busy(asker);
    await reply(recipient, first.requestId, 'canary green');
    const [steer] = await replyTurnsOf(asker);
    assert.equal(steer.kind, 'steer');
    const handed = await deliverSteer(asker);
    assert.equal(handed.turnId, steer.id);
    // Out with the runner, and the lease running out: the second outcome is queued for the next turn.
    await leaseRunsOut(running);
    await reply(recipient, second.requestId, 'drill green');
    await leaseRenewed(running);
    assert.equal((await replyTurnsOf(asker)).length, 2);

    // The runner proves the engine never read it (steer_requeue): the same row, the next-turn reply turn.
    await requeueSteer(asker, steer.id);
    const left = await replyTurnsOf(asker);
    assert.deepEqual(left.map((turn) => [turn.id, turn.kind, turn.sendIntent, turn.status]), [
      [steer.id, 'message', 'NEXT_TURN', 'PENDING'],
    ]);
    assert.equal((await requestRow(first.id)).replyClientTurnId, steer.clientTurnId);
    assert.equal((await requestRow(second.id)).replyClientTurnId, steer.clientTurnId);

    await finish(asker, running);
    const back = await deliver(asker);
    assert.equal(back.turnId, steer.id);
    assert.equal(blocksFor(back.content, first.id), 1);
    assert.equal(blocksFor(back.content, second.id), 1);
    assert.ok(!back.content.includes(STEER_HEAD), back.content);
  });

  await t.test('a reply steer the runner could not write in lets its outcome go, and the request worker hands it back', async () => {
    const asker = await session('Coordinator: its runtime refuses the steer');
    const recipient = await session('Worker: answers');
    const request = await ask(asker, recipient, 'may I take the migration lock?');
    const running = await busy(asker);
    await reply(recipient, request.requestId, 'take it');
    const [steer] = await replyTurnsOf(asker);
    await deliverSteer(asker);
    await settleSteer(asker, steer.id, false);
    const failed = await turnRow(steer.id);
    assert.deepEqual([failed.status, failed.deliveryStatus], ['ANSWERED', 'FAILED']);
    // On no turn and not held: nothing will deliver it where it was, and the asker has not stopped.
    const released = await requestRow(request.id);
    assert.equal(released.replyClientTurnId, null);
    assert.equal(released.replyHeldAt, null);

    // The worker's next pass hands it back: into the running turn again, which can still take it.
    assert.deepEqual((await worker.drain()).handedOff, [request.id]);
    const again = (await replyTurnsOf(asker)).find((turn) => turn.id !== steer.id)!;
    assert.deepEqual([again.kind, again.status, again.targetTurnId], ['steer', 'PENDING', running]);
    assert.equal((await requestRow(request.id)).replyClientTurnId, again.clientTurnId);
    // That turn ends first: the new steer is the next turn's reply turn, and says it once.
    await finish(asker, running);
    const back = await deliver(asker);
    assert.equal(back.turnId, again.id);
    assert.equal(blocksFor(back.content, request.id), 1);
    assert.match(back.content, /Reply: take it/);
  });

  // ── 31. an interrupt ────────────────────────────────────────────────────────────────────────────

  await t.test('an interrupt takes a reply steer not yet taken with the queue: the outcome is held, and said on the next delivered turn', async () => {
    const asker = await session('Coordinator: interrupted while an answer is on its way in');
    const recipient = await session('Worker: answers');
    const request = await ask(asker, recipient, 'go or no-go?');
    const running = await busy(asker);
    await reply(recipient, request.requestId, 'go');
    const [steer] = await replyTurnsOf(asker);
    assert.equal(steer.kind, 'steer');

    // Stopped: the steer goes with the queue, and nothing starts the asker running again for it.
    await sessions.interrupt(ownerId, asker);
    const dropped = await turnRow(steer.id);
    assert.equal(dropped.status, 'ANSWERED');
    assert.equal(dropped.deliveryStatus, 'FAILED');
    const held = await requestRow(request.id);
    assert.equal(held.replyClientTurnId, null);
    assert.ok(held.replyHeldAt, 'the outcome was not held on its request row');
    assert.deepEqual((await worker.drain()).handedOff, [], 'the worker queued it again, after a stop');
    // Nothing of it is listed, not even as a message that failed to arrive: nobody typed it.
    assert.ok(!(await listed(asker, 'active')).some((row) => row.turnId === steer.id));
    await finish(asker, running);
    assert.equal(await statusOf(asker), RunStatus.AWAITING_INPUT);
    assert.equal(await queuedExecutables(asker), 0);

    // The asker's next turn — the owner's own message — says it, once.
    const ownerKey = randomUUID();
    await sessions.createTurn(ownerId, asker, { clientTurnId: ownerKey, content: 'what did the worker say?' });
    const next = await deliver(asker);
    assert.equal(next.clientTurnId, ownerKey);
    assert.ok(next.content.startsWith('what did the worker say?'), 'the owner\'s words were not first');
    assert.equal(blocksFor(next.content, request.id), 1);
    assert.ok(!next.content.includes(STEER_HEAD), next.content);
    assert.equal((await requestRow(request.id)).replyClientTurnId, ownerKey);
    const stored = await say(asker, next.turnId, RunEventType.USER, { text: next.content });
    assert.equal((stored.sessionReplies as unknown[]).length, 1);
    await finish(asker, next.turnId);
    await sessions.createTurn(ownerId, asker, { clientTurnId: randomUUID(), content: 'thanks' });
    assert.equal(blocksFor((await deliver(asker)).content, request.id), 0);
  });

  // ── 32. the auto-retry ─────────────────────────────────────────────────────────────────────────

  await t.test('a transient failure of the turn a reply steer joined re-sends that turn, and the re-sent turn says the outcome', async () => {
    const asker = await session('Coordinator: its provider is overloaded mid-turn');
    const recipient = await session('Worker: answers');
    const request = await ask(asker, recipient, 'is the index rebuilt?');
    await sessions.createTurn(ownerId, asker, { clientTurnId: randomUUID(), content: 'keep rebuilding the index' });
    const running = await deliver(asker);
    await say(asker, running.turnId, RunEventType.USER, { text: running.content });
    await reply(recipient, request.requestId, 'rebuilt');
    const [steer] = await replyTurnsOf(asker);
    // The runner writes the steer in and echoes it, and the provider fails the turn before the engine
    // acknowledges it: the steer's echo is the last message the runner recorded.
    const handed = await deliverSteer(asker);
    await say(asker, steer.id, RunEventType.USER, { text: handed.content, steer: true, delivery: 'enqueued' });
    const overloaded = 'API Error: 529 {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}';
    await say(asker, running.turnId, RunEventType.ASSISTANT, { text: overloaded });
    await api.turnComplete({ id: runnerId } as never, asker, {
      turnId: running.turnId, status: SharedRunStatus.FAILED, subtype: 'error_during_execution',
      numTurns: 1, costUsd: 0, error: overloaded,
    } as never);
    const failed = await prisma.session.findUniqueOrThrow({ where: { id: asker } });
    assert.equal(failed.status, RunStatus.FAILED);
    assert.ok(failed.retryAt, 'the overload armed no retry');
    assert.equal((await turnRow(steer.id)).deliveryStatus, 'FAILED');
    // Held for the retry's turn: not on the steer nothing will deliver, not handed to an asker that is
    // waiting for its retry.
    const held = await requestRow(request.id);
    assert.equal(held.replyClientTurnId, null, 'the outcome stayed on a steer that will never be delivered');
    assert.ok(held.replyHeldAt);
    assert.ok(!(await worker.drain()).handedOff.includes(request.id));

    // The retry re-sends the turn that failed — the owner's words — and not a reply turn in its place.
    await prisma.session.update({ where: { id: asker }, data: { retryAt: new Date(Date.now() - HOUR) } });
    await heartbeat();
    await new AutoRetryService(db, sessions, realtime as never).sweep();
    const resent = await prisma.conversationTurn.findMany({
      where: { sessionId: asker, clientTurnId: { startsWith: AUTO_RETRY_TURN_KEY_PREFIX } },
    });
    assert.deepEqual(resent.map((turn) => turn.content), ['keep rebuilding the index'],
      'the retry did not re-send the turn the steer joined');
    assert.equal((await replyTurnsOf(asker)).length, 1, 'the retry re-sent a reply turn in place of the owner\'s words');
    // ...and that turn says the outcome the steer never got to.
    const back = await deliver(asker);
    assert.equal(back.turnId, resent[0].id);
    assert.ok(back.content.startsWith('keep rebuilding the index'), back.content);
    assert.equal(blocksFor(back.content, request.id), 1);
    assert.match(back.content, /Reply: rebuilt/);
    assert.equal((await requestRow(request.id)).replyClientTurnId, resent[0].clientTurnId);
  });
});
