/**
 * Another Orbit session's message — signed, delivered as such, and bounded — against a real
 * PostgreSQL (docs/session-request-reply-contract.md §8, P0 criteria 1, 2 and 4, and the three gaps
 * criteria 11–13 close).
 *
 *   1. A turn `session_send` or `project_send` writes carries the calling session as its sender, on
 *      the live write and on the revive alike; one the account owner, a headless credential or the
 *      platform writes carries none, whatever its body said.
 *   2. The engine is handed the words and then the `<orbit-session-message>` block, what ingest
 *      records beside the runner's echo is exactly that block, and the `user` event carries the card
 *      a client draws "From [that session]" from.
 *   4. The 21st message one session sends another inside an hour is refused with 409
 *      SESSION_MESSAGE_RATE_LIMITED — `project_send` counting against the coordinator it resolves —
 *      while a retry of a counted message is not another one, and nobody but a session is counted.
 *  11. The auto-retry sweep re-sends another session's message as that session's — the sender kept
 *      on the new turn, the block delivered with it, the card stored beside its echo — on the live
 *      path and on the revive alike; and as the platform's re-send it is charged to nobody: neither
 *      the pair's hour nor a steer.
 *  12. (the server's half) A message another session sent carries its card on both projections of
 *      the queue while it waits, the request it is included — the card its echo will carry.
 *  13. `session_interrupt`'s message is signed with the calling session and delivered as its
 *      message, and counts with that session's other messages against the pair's hour: the 21st is
 *      refused and leaves the queue as it found it, while a retry of a counted one and a bodyless
 *      interrupt are not messages at all.
 *  15. (the server's half) The failure card's Retry of another session's message asks the server to
 *      re-send it, through `POST /sessions/:id/retry-message`: the new turn keeps the sender and the
 *      request the message was, the engine reads the block again, and nobody is charged — not the
 *      pair's hour, not a steer. A replay of the click is its receipt.
 *  16. What one session sent another counts for the hour it was sent in, whatever happens to it next:
 *      queued messages an interrupt drops, or the owner withdraws, still count, and so do the ones a
 *      session drops itself with an interrupt that carries one more — the 21st is refused.
 *  22. (the server's half) The Retry door's key follows the failure the session is stopped on: a re-send
 *      that fails before its echo — refused by the runtime before it was written, with only the runner's
 *      receipt to show for it — is re-sent by the next press, and only once however often it is pressed;
 *      a re-send that went through, or the sweep's own, is never sent a second time by a press after it.
 *
 * The doors are the real controllers and the real orchestration credential; the inbox and the event
 * ingest are reached over real HTTP, through the guard and the public-id interceptor main.ts installs.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/sessions/session-message.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import {
  type Prisma,
  type PrismaClient,
  type Runner,
  RunStatus,
  RunnerStatus,
  SessionDispatchOrigin,
  SessionRunSource,
} from '@prisma/client';
import { base62ToUuid, uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { publicIdHeaders } from '../common/public-id-headers';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { AttemptBudgetMeterService } from '../projects/attempt-budget-meter.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { establishProjectContractForPgTest } from '../projects/project-contract-test-helper';
import { ProjectsService } from '../projects/projects.service';
import { PushService } from '../push/push.service';
import { QueueService } from '../queue/queue.service';
import { RealtimeService } from '../realtime/realtime.service';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerOrchestrationAuthorizer } from '../runner-api/runner-orchestration-authorizer';
import { RunnerProjectsController } from '../runner-api/runner-projects.controller';
import { RunnerSessionsController } from '../runner-api/runner-sessions.controller';
import { ListEventsService } from '../task-lists/list-events.service';
import { ReferenceExpansionService } from '../tasks/reference-expansion';
import { TasksService } from '../tasks/tasks.service';
import { AutoRetryService } from './auto-retry.service';
import { MergeReceiptService } from './merge-receipt.service';
import { SessionRequestService } from './session-request.service';
import { SessionsController } from './sessions.controller';
import {
  SESSION_MESSAGE_RATE_LIMITED_CODE,
  SESSION_MESSAGES_PER_PAIR_PER_HOUR,
  sessionMessageBlock,
} from './session-message';
import { SessionsService } from './sessions.service';
import { AUTO_RETRY_TURN_KEY_PREFIX } from './watch-turn-key';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a session row carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The runner credential, in the clear. Its hash is what both guards match. */
const RUNNER_TOKEN = 'the-runner-token-for-session-messages';

/** A response, kept as text as well as JSON: a body that failed to parse has to be readable. */
interface Answer {
  status: number;
  text: string;
  json: Record<string, unknown>;
}

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

/** The refusal an exception carries, as a caller reads it. */
function refusalOf(error: unknown): Record<string, unknown> {
  const response = (error as { getResponse?: () => unknown }).getResponse?.();
  assert.ok(response && typeof response === 'object', `expected a structured refusal, got ${String(error)}`);
  return response as Record<string, unknown>;
}

test('one session’s message to another is signed, delivered as such, and bounded', {
  skip, concurrency: 1, timeout: 300_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  let app: INestApplication | undefined;
  t.after(async () => {
    await app?.close().catch(() => undefined);
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  // ── the world: one account, one machine, a workspace each for the workers and the coordinator ──
  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const workerWorkspaceId = randomUUID();
  const landingWorkspaceId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `session-message-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: {
      id: runnerId, ownerId, name: 'the machine every session runs on', tokenHash: sha256(RUNNER_TOKEN),
      // Online and fresh: a revive refuses a session whose runner is not.
      status: RunnerStatus.ONLINE, lastHeartbeatAt: new Date(), capabilities: [], capabilitiesReportedAt: new Date(),
    },
  });
  await prisma.workspace.create({
    data: { id: workerWorkspaceId, ownerId, runnerId, name: 'orbit-worker', enabled: true },
  });
  await prisma.workspace.create({
    data: { id: landingWorkspaceId, ownerId, runnerId, name: 'orbit-coordinator', enabled: true },
  });
  const runner = { id: runnerId, ownerId } as Runner;

  /** A session on this runner, parked between turns — the shape a live orchestrating caller has. */
  async function session(title: string, data: Partial<Prisma.SessionUncheckedCreateInput> = {}): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id, ownerId, creatorId: ownerId, workspaceId: workerWorkspaceId, assignedRunnerId: runnerId,
        title, prompt: title, provider: 'claude', status: RunStatus.AWAITING_INPUT,
        numTurns: 1, startedAt: new Date(), runtimeSessionId: `runtime-${id}`,
        dispatchOrigin: SessionDispatchOrigin.USER, runSource: SessionRunSource.MANUAL,
        ...data,
      },
    });
    return id;
  }

  /** A session whose run has ended, and that its runner can bring back. */
  const ended = (title: string) =>
    session(title, { status: RunStatus.SUCCEEDED, completedAt: new Date(Date.now() - 60_000) });

  // ── the doors ─────────────────────────────────────────────────────────────────────────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(prisma as unknown as PrismaService, queue as never, realtime as never);
  const orchestration = new RunnerOrchestrationAuthorizer(
    prisma as unknown as PrismaService,
    new JwtService({ secret: 'session-message-pg' }),
  );
  // The orchestration send is budgeted as a steer. Recorded rather than stubbed away, so a change
  // that dropped the steer charge when it added the hourly one fails here.
  const steers: string[] = [];
  const attempts = {
    chargeSteer: async (_owner: string, sessionId: string) => {
      steers.push(sessionId);
    },
  };
  const sendDoor = new RunnerSessionsController(sessions, orchestration, {} as never, attempts as never);
  const projects = new ProjectsService(
    prisma as unknown as PrismaService,
    new ProjectAcceptanceService(prisma as unknown as PrismaService),
    sessions,
  );
  const projectDoor = new RunnerProjectsController(
    projects,
    new ProjectAcceptanceService(prisma as unknown as PrismaService),
    {} as never,
    orchestration,
    undefined,
    attempts as never,
  );

  /** `session_send` as the runner calls it: from a session with its own credential, or headless. */
  async function sessionSend(
    from: string | null,
    to: string,
    message: string,
    clientTurnId: string = randomUUID(),
    extra: Record<string, unknown> = {},
  ) {
    return sendDoor.sendMessage(
      runner,
      undefined,
      from ?? undefined,
      from ? await orchestration.issue(runnerId, from) : undefined,
      to,
      { message, clientTurnId, ...extra },
    );
  }

  /** `session_interrupt` as the runner calls it — always from a session: the verb has no headless
   *  path. With no message it is a plain interrupt. */
  async function sessionInterrupt(from: string, to: string, message?: string, clientTurnId?: string) {
    return sendDoor.interruptSession(
      runner,
      undefined,
      from,
      await orchestration.issue(runnerId, from),
      to,
      message === undefined ? undefined : { message, ...(clientTurnId ? { clientTurnId } : {}) },
    );
  }

  /** `project_send` as the runner calls it, from a session with its own credential. */
  async function projectSend(from: string, projectId: string, message: string, clientTurnId: string = randomUUID()) {
    return projectDoor.sendToCoordinator(
      runner,
      projectId,
      from,
      await orchestration.issue(runnerId, from),
      { message, clientTurnId },
    );
  }

  /** The account owner's own door: what `POST /sessions/:id/turns` hands the service. Answers the
   *  key it was written under. */
  async function ownerSend(to: string, content: string, body: Record<string, unknown> = {}): Promise<string> {
    const clientTurnId = randomUUID();
    await sessions.createTurn(ownerId, to, { content, clientTurnId, ...body } as never);
    return clientTurnId;
  }

  /** A project whose coordinator conversation is `coordinatorStatus`, ready to be addressed. */
  async function project(label: string, coordinator: Partial<Prisma.SessionUncheckedCreateInput> = {}) {
    const projectId = randomUUID();
    await prisma.project.create({
      data: {
        id: projectId, ownerId, title: `${label} 项目`, coordinatorEnabled: true,
        coordinatorWorkspaceId: landingWorkspaceId,
      },
    });
    await establishProjectContractForPgTest(prisma, ownerId, projectId, label);
    const coordinatorSessionId = await session(`coordinator: ${label}`, {
      workspaceId: landingWorkspaceId, titleManagedByProject: true, ...coordinator,
    });
    await prisma.project.update({ where: { id: projectId }, data: { coordinatorSessionId } });
    return { projectId, coordinatorSessionId };
  }

  const turnsOf = (sessionId: string) =>
    prisma.conversationTurn.findMany({ where: { sessionId }, orderBy: { seq: 'asc' } });

  /** The sender column, read the way nothing in the product reads it: straight off the row. */
  async function senderOf(sessionId: string, clientTurnId: string): Promise<string | null> {
    const rows = await sql.query<{ sender: string | null }>(
      `SELECT "sender_session_id"::text AS "sender" FROM "conversation_turn"
        WHERE "session_id" = $1::uuid AND "client_turn_id" = $2`,
      [sessionId, clientTurnId],
    );
    assert.equal(rows.rows.length, 1, `no turn ${clientTurnId} on ${sessionId}`);
    return rows.rows[0].sender;
  }

  // ── the app: the real runner door, its guard, main.ts's middleware and interceptor ─────────────
  @Module({
    controllers: [RunnerApiController],
    providers: [
      { provide: PrismaService, useValue: prisma },
      { provide: QueueService, useValue: queue },
      { provide: SessionsService, useValue: sessions },
      { provide: RealtimeService, useValue: realtime },
      { provide: PushService, useValue: silent() },
      { provide: RunnerOrchestrationAuthorizer, useValue: orchestration },
      // The messages here carry no `#`-references and reach no list console.
      { provide: ReferenceExpansionService, useValue: { expand: async (_owner: string, content?: string) => content } },
      { provide: ListEventsService, useValue: { appendFor: async (_tx: unknown, _id: string, content?: string) => content } },
      // A completed turn's spend is metered after it commits; nothing these sessions run is budgeted.
      { provide: AttemptBudgetMeterService, useValue: { meterQuietly: async () => undefined } },
      { provide: ProjectAcceptanceService, useValue: {} },
      { provide: TasksService, useValue: {} },
      { provide: MergeReceiptService, useValue: {} },
      RunnerAuthGuard,
    ],
  })
  class RunnerDoor {}

  app = await NestFactory.create(RunnerDoor, { logger: false, abortOnError: false });
  app.use(publicIdHeaders);
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
  app.useGlobalInterceptors(new PublicIdInterceptor());
  await app.listen(0, '127.0.0.1');
  const base = await app.getUrl();

  async function http(method: 'GET' | 'POST', route: string, body?: unknown): Promise<Answer> {
    const response = await fetch(`${base}/api${route}`, {
      method,
      headers: {
        authorization: `Bearer ${RUNNER_TOKEN}`,
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    const text = await response.text();
    let json: Record<string, unknown> = {};
    try { json = JSON.parse(text) as Record<string, unknown>; } catch { /* asserted on by the caller */ }
    return { status: response.status, text, json };
  }

  /** What the runner's claim does to a queued session, then the inbox poll that follows it. */
  async function claimAndPoll(sessionId: string): Promise<Answer> {
    await prisma.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    const delivered = await http('GET', `/runner/sessions/${uuidToBase62(sessionId)}/inbox`);
    assert.equal(delivered.status, 200, `inbox answered ${delivered.status}: ${delivered.text}`);
    return delivered;
  }

  /** The inbox after an interrupt-and-send: the interrupt goes out first, then the message. */
  async function claimToMessage(sessionId: string): Promise<Answer> {
    let delivered = await claimAndPoll(sessionId);
    for (let i = 0; i < 2 && delivered.json.kind !== 'message'; i++) {
      delivered = await http('GET', `/runner/sessions/${uuidToBase62(sessionId)}/inbox`);
      assert.equal(delivered.status, 200, `inbox answered ${delivered.status}: ${delivered.text}`);
    }
    assert.equal(delivered.json.kind, 'message', `the inbox never handed out the message: ${delivered.text}`);
    return delivered;
  }

  /** The runner echoing what it was handed as the turn's `user` event, and the row ingest stored. */
  async function echo(sessionId: string, seq: number, turnId: unknown, payload: Record<string, unknown>) {
    const echoed = await http('POST', `/runner/sessions/${uuidToBase62(sessionId)}/events`, {
      events: [{ seq, type: 'user', ts: new Date().toISOString(), turnId, payload }],
    });
    assert.equal(echoed.status, 202, `events answered ${echoed.status}: ${echoed.text}`);
    const stored = await prisma.runEvent.findFirstOrThrow({ where: { sessionId, seq } });
    return stored.payload as Record<string, unknown>;
  }

  // ── 1. who sent it ────────────────────────────────────────────────────────────────────────────

  await t.test('session_send signs the turn with the calling session; nobody else is a sender', async () => {
    const task = await prisma.task.create({
      data: {
        ownerId, title: 'criterion 3 needs a merge decision', creatorType: 'USER', creatorId: ownerId,
        completionCriterion: 'OWNER_CONFIRMED',
      },
      select: { id: true },
    });
    const worker = await session('Worker: criterion 3', { taskId: task.id });
    const recipient = await session('the conversation the worker writes to');

    await sessionSend(worker, recipient, 'from the worker', 'signed-1');
    await sessionSend(null, recipient, 'from a headless bridge', 'headless-1');
    // The owner's own door, with a body that names a sender: a field of the request is not one.
    const owner = await ownerSend(recipient, 'from the owner', { senderSessionId: worker });
    // The platform's own delivery: a background job waking the session.
    const wake = await http('POST', `/runner/sessions/${uuidToBase62(recipient)}/background-wake`, {
      wakeId: 'bgj_0123456789ab:exit', jobId: 'bgj_0123456789ab', trigger: 'exit', kind: 'watch',
      command: 'gh run watch 4242 --exit-status', status: 'failed', exitCode: 1,
      outputPath: '/root/.orbit/runs/session-message/bgj_0123456789ab.output', outputOffset: 0,
      outputSize: 64, outputExcerpt: 'X lint failed',
    });
    assert.equal(wake.status, 200, `background-wake answered ${wake.status}: ${wake.text}`);
    assert.equal(wake.json.outcome, 'ENQUEUED', wake.text);

    assert.equal(await senderOf(recipient, 'signed-1'), worker, 'the worker’s message is not signed by the worker');
    assert.equal(await senderOf(recipient, 'headless-1'), null, 'a headless credential was recorded as a session');
    assert.equal(await senderOf(recipient, owner), null, 'a request body named the sender');
    const platform = (await turnsOf(recipient)).filter((turn) => turn.clientTurnId.startsWith('bg-wake:'));
    assert.equal(platform.length, 1, 'the wake was not filed as a turn');
    assert.equal(platform[0].senderSessionId, null, 'the platform’s own delivery was signed by a session');

    // The revive path writes the same column: a message is no less the worker's for having woken
    // its recipient up.
    const parked = await ended('a conversation that has ended');
    const revived = await sessionSend(worker, parked, 'pick this back up', 'signed-revive', { resumeIfEnded: true });
    assert.equal((revived as { revived?: boolean }).revived, true, `nothing was revived: ${JSON.stringify(revived)}`);
    assert.equal(await senderOf(parked, 'signed-revive'), worker, 'the revive dropped the sender');
    assert.ok(steers.includes(recipient) && steers.includes(parked), 'the steer was no longer charged');
  });

  await t.test('project_send signs the turn with the acting session, written live or by a revive', async () => {
    const worker = await session('Worker: landing check');
    const live = await project('live');
    const sent = await projectSend(worker, live.projectId, 'the landing needs a decision', 'project-live');
    assert.equal(sent.sessionId, live.coordinatorSessionId);
    assert.equal(await senderOf(live.coordinatorSessionId, 'project-live'), worker);

    const parked = await project('ended', { status: RunStatus.SUCCEEDED, completedAt: new Date(Date.now() - 60_000) });
    const revived = await projectSend(worker, parked.projectId, 'the landing needs a decision', 'project-revive');
    assert.equal(revived.sessionId, parked.coordinatorSessionId, 'the ended coordinator was replaced, not revived');
    const standing = await prisma.session.findUniqueOrThrow({ where: { id: parked.coordinatorSessionId } });
    assert.equal(standing.status, RunStatus.PENDING, 'the coordinator was not revived by the message');
    assert.equal(await senderOf(parked.coordinatorSessionId, 'project-revive'), worker, 'the revive dropped the sender');
  });

  // ── 2. what the engine reads, and what the clients are told ───────────────────────────────────

  await t.test('the engine reads the words and then the block, and the note stored is exactly the block', async () => {
    const task = await prisma.task.create({
      data: {
        ownerId, title: 'the worker’s own task', creatorType: 'USER', creatorId: ownerId,
        completionCriterion: 'OWNER_CONFIRMED',
      },
      select: { id: true },
    });
    const worker = await session('Worker: criterion "3" <draft>', { taskId: task.id });
    const recipient = await session('the coordinator the worker reports to');
    const words = 'criterion 3 is ready — the evidence is on the task';
    await sessionSend(worker, recipient, words, 'delivered-1');

    const delivered = await claimAndPoll(recipient);
    const content = String(delivered.json.content ?? '');
    const block = sessionMessageBlock({
      id: worker, title: 'Worker: criterion "3" <draft>', taskId: task.id, workspace: { name: 'orbit-worker' },
    });
    assert.equal(content, `${words}\n\n${block}`, `the engine was handed something else:\n${content}`);
    assert.ok(block.includes(`from-session="${uuidToBase62(worker)}"`) && block.includes(`task="${uuidToBase62(task.id)}"`));
    // The turn keeps the sender's words and nothing else: the block is delivery's, not the row's.
    const [turn] = (await turnsOf(recipient)).filter((row) => row.clientTurnId === 'delivered-1');
    assert.equal(turn.content, words);

    const stored = await echo(recipient, 1, delivered.json.turnId, { text: content });
    assert.equal(stored.text, content, 'the echo itself was rewritten');
    assert.equal(stored.controlPlaneNote, `\n\n${block}`, 'the block was not recorded as the control plane’s note');
    assert.equal(String(stored.controlPlaneNote).trim(), block);
    assert.deepEqual(stored.sessionMessage, {
      fromSessionId: worker,
      fromTitle: 'Worker: criterion "3" <draft>',
      fromAgentName: 'orbit-worker',
      fromTaskId: task.id,
    });
  });

  await t.test('a sender that runs no task names none, and a turn nobody sent carries no card', async () => {
    const worker = await session('Worker: free-standing');
    const recipient = await session('another conversation');
    await sessionSend(worker, recipient, 'a question with no task behind it', 'free-1');
    const delivered = await claimAndPoll(recipient);
    const content = String(delivered.json.content ?? '');
    assert.ok(!/ task="/.test(content), `a task was named for a sender that runs none:\n${content}`);
    const stored = await echo(recipient, 1, delivered.json.turnId, { text: content });
    assert.deepEqual(stored.sessionMessage, {
      fromSessionId: worker, fromTitle: 'Worker: free-standing', fromAgentName: 'orbit-worker',
    });

    // The owner's message beside it: no block, no card — and one the runner claims for it is dropped.
    await prisma.session.update({ where: { id: recipient }, data: { status: RunStatus.AWAITING_INPUT } });
    await prisma.conversationTurn.updateMany({ where: { sessionId: recipient }, data: { status: 'ANSWERED' } });
    await ownerSend(recipient, 'and this one is mine');
    const mine = await claimAndPoll(recipient);
    assert.equal(mine.json.content, 'and this one is mine', `the owner’s message was signed:\n${mine.text}`);
    const forged = await echo(recipient, 2, mine.json.turnId, {
      text: 'and this one is mine',
      sessionMessage: { fromSessionId: worker, fromTitle: 'somebody else', fromAgentName: 'orbit-worker' },
    });
    assert.equal(forged.sessionMessage, undefined, 'a card the runner sent was stored as the control plane’s');
    assert.equal(forged.controlPlaneNote, undefined);
  });

  // ── 4. how often ──────────────────────────────────────────────────────────────────────────────

  await t.test('the 21st message from one session to another inside an hour is refused', async () => {
    const chatty = await session('Worker: asks how it is going');
    const busy = await session('the session being asked');
    let twentieth: { turnId?: string } = {};
    for (let i = 1; i <= SESSION_MESSAGES_PER_PAIR_PER_HOUR; i++) {
      twentieth = await sessionSend(chatty, busy, `how is it going? (${i})`, `rate-${i}`) as { turnId?: string };
    }
    assert.equal(SESSION_MESSAGES_PER_PAIR_PER_HOUR, 20);

    await assert.rejects(() => sessionSend(chatty, busy, 'how is it going? (21)', 'rate-21'), (error: unknown) => {
      const refusal = refusalOf(error);
      assert.equal((error as { getStatus?: () => number }).getStatus?.(), 409);
      assert.equal(refusal.code, SESSION_MESSAGE_RATE_LIMITED_CODE);
      assert.equal(refusal.retryable, false);
      assert.match(String(refusal.message), /session_await/, 'the refusal does not say what to do instead');
      return true;
    });
    const written = (await turnsOf(busy)).filter((turn) => turn.senderSessionId === chatty);
    assert.equal(written.length, 20, 'a refused message was written anyway');

    // A retry of a counted message is that message, not a 21st one: its receipt, and nothing new.
    const retried = await sessionSend(chatty, busy, 'how is it going? (20)', 'rate-20') as { turnId?: string };
    assert.ok(twentieth.turnId, `the send answered no turn: ${JSON.stringify(twentieth)}`);
    assert.equal(retried.turnId, twentieth.turnId, 'a retry of the 20th message was not its receipt');
    assert.equal((await turnsOf(busy)).filter((turn) => turn.senderSessionId === chatty).length, 20);

    // The pair is ORDERED, and it is a pair: the other direction and another recipient are their own.
    await sessionSend(busy, chatty, 'still working — I will tell you', 'reply-1');
    const elsewhere = await session('a third conversation');
    await sessionSend(chatty, elsewhere, 'a different question', 'elsewhere-1');

    // Rolling, not a fixed hour: once the oldest message is more than an hour old, one more fits.
    // What ages is what was SENT (migration 0351's record), not the turn it was sent as.
    await sql.query(
      `UPDATE "session_message_charge" SET "created_at" = "created_at" - interval '61 minutes'
        WHERE "id" = (SELECT "id" FROM "session_message_charge"
                       WHERE "to_session_id" = $1::uuid AND "from_session_id" = $2::uuid
                       ORDER BY "created_at", "id" LIMIT 1)`,
      [busy, chatty],
    );
    await sessionSend(chatty, busy, 'how is it going? (21, an hour on)', 'rate-21-later');
    await assert.rejects(() => sessionSend(chatty, busy, 'and again', 'rate-22'), (error: unknown) => {
      assert.equal(refusalOf(error).code, SESSION_MESSAGE_RATE_LIMITED_CODE);
      return true;
    });
  });

  await t.test('the owner and a headless credential are not counted, and are not refused', async () => {
    const chatty = await session('Worker: shares a recipient with people');
    const busy = await session('a conversation people talk to as well');
    // Thirty messages nobody's session sent, before and after the limit is reached.
    for (let i = 0; i < 25; i++) await ownerSend(busy, `the owner, ${i}`);
    for (let i = 0; i < 5; i++) await sessionSend(null, busy, `a bridge, ${i}`);
    for (let i = 1; i <= SESSION_MESSAGES_PER_PAIR_PER_HOUR; i++) {
      await sessionSend(chatty, busy, `message ${i}`);
    }
    await assert.rejects(() => sessionSend(chatty, busy, 'message 21'), (error: unknown) => {
      assert.equal(refusalOf(error).code, SESSION_MESSAGE_RATE_LIMITED_CODE);
      return true;
    });
    await ownerSend(busy, 'the owner, after the session was refused');
    await sessionSend(null, busy, 'a bridge, after the session was refused');
    const turns = await turnsOf(busy);
    assert.equal(turns.filter((turn) => turn.senderSessionId === null).length, 32);
    assert.equal(turns.filter((turn) => turn.senderSessionId === chatty).length, 20);
  });

  await t.test('project_send counts against the coordinator it resolves, and says so as itself', async () => {
    const worker = await session('Worker: reports to its coordinator');
    const { projectId, coordinatorSessionId } = await project('counted');
    // Nineteen addressed to the session, one to the project: the same pair, so twenty.
    for (let i = 1; i < SESSION_MESSAGES_PER_PAIR_PER_HOUR; i++) {
      await sessionSend(worker, coordinatorSessionId, `report ${i}`);
    }
    await projectSend(worker, projectId, 'report 20');
    await assert.rejects(() => projectSend(worker, projectId, 'report 21'), (error: unknown) => {
      const refusal = refusalOf(error);
      // Not COORDINATOR_MESSAGE_UNDELIVERED: what to do next is to wait, not to try the delivery again.
      assert.equal(refusal.code, SESSION_MESSAGE_RATE_LIMITED_CODE);
      assert.equal(refusal.retryable, false);
      return true;
    });
    await assert.rejects(() => sessionSend(worker, coordinatorSessionId, 'report 21, by session'), (error: unknown) => {
      assert.equal(refusalOf(error).code, SESSION_MESSAGE_RATE_LIMITED_CODE);
      return true;
    });
    const counted = (await turnsOf(coordinatorSessionId)).filter((turn) => turn.senderSessionId === worker);
    assert.equal(counted.length, 20);
  });

  // ── 11. what the auto-retry sweep re-sends ────────────────────────────────────────────────────

  // The sweep over every armed session there is, built the way the module builds it. It is run with
  // a `now` of its own, decades back, so it can only ever pick up the rows armed for it below.
  const autoRetry = new AutoRetryService(prisma as unknown as PrismaService, sessions, realtime as never);
  let armedAt = new Date('2001-01-01T00:00:00.000Z');

  /** A message the runner took and echoed, whose turn then died on the provider: the turn settled
   *  and the session parked as `parkedAs` with a retry armed — what ingest's quota and provider-error
   *  branches leave behind. Answers the instant to sweep at. */
  async function failAndArm(sessionId: string, parkedAs: RunStatus): Promise<Date> {
    const delivered = await claimAndPoll(sessionId);
    await echo(sessionId, 1, delivered.json.turnId, { text: String(delivered.json.content ?? '') });
    await prisma.conversationTurn.updateMany({
      where: { sessionId, status: 'IN_FLIGHT' },
      data: { status: 'ANSWERED', answeredAt: new Date() },
    });
    armedAt = new Date(armedAt.getTime() + 60_000);
    await prisma.session.update({
      where: { id: sessionId },
      data: {
        status: parkedAs, retryAt: armedAt, retryAttempts: 0,
        // A provider error settles the run FAILED and asks the process to stop (`sweep`'s own note).
        ...(parkedAs === RunStatus.FAILED ? { cancelRequestedAt: new Date(), finishedAt: new Date() } : {}),
      },
    });
    // A resume refuses a runner that has not been heard from in 90s, and this file runs for minutes.
    await prisma.runner.update({ where: { id: runnerId }, data: { lastHeartbeatAt: new Date() } });
    return new Date(armedAt.getTime() + 1_000);
  }

  const resentOn = async (sessionId: string) =>
    (await turnsOf(sessionId)).filter((turn) => turn.clientTurnId.startsWith(AUTO_RETRY_TURN_KEY_PREFIX));

  await t.test('the auto-retry sweep re-sends another session’s message as that session’s', async () => {
    const task = await prisma.task.create({
      data: {
        ownerId, title: 'the migration review', creatorType: 'USER', creatorId: ownerId,
        completionCriterion: 'OWNER_CONFIRMED',
      },
      select: { id: true },
    });
    const worker = await session('Worker: asks for a review', { taskId: task.id });
    const recipient = await session('the conversation whose turn the quota killed');
    const words = 'please review the migration before I merge it';
    await sessionSend(worker, recipient, words, 'retried-1');
    const steersBefore = steers.length;

    await autoRetry.sweep(await failAndArm(recipient, RunStatus.AWAITING_INPUT));

    const [resent, ...more] = await resentOn(recipient);
    assert.ok(resent, 'the sweep re-sent nothing');
    assert.equal(more.length, 0, 'the sweep re-sent the message twice');
    assert.equal(resent.content, words);
    assert.equal(resent.senderSessionId, worker, 'the re-send dropped the sender: it reads as the owner’s');
    assert.equal(await senderOf(recipient, 'retried-1'), worker, 'the original lost its sender');
    // The platform's re-send, not the worker's doing: nothing was charged as a steer for it.
    assert.equal(steers.length, steersBefore, 'the re-send was charged as a steer');

    // While it waits, the queue already draws it as the worker's (criterion 12, the server's half).
    const [waiting] = (await sessions.listQueuedTurns(ownerId, recipient, 'active'))
      .filter((row) => row.turnId === resent.id);
    assert.deepEqual(waiting?.sessionMessage, {
      fromSessionId: worker, fromTitle: 'Worker: asks for a review', fromAgentName: 'orbit-worker', fromTaskId: task.id,
    });

    // The engine reads it as the worker's message again: the words, then the block.
    const redelivered = await claimAndPoll(recipient);
    const content = String(redelivered.json.content ?? '');
    const block = sessionMessageBlock({
      id: worker, title: 'Worker: asks for a review', taskId: task.id, workspace: { name: 'orbit-worker' },
    });
    assert.equal(content, `${words}\n\n${block}`, `the engine was handed something else:\n${content}`);
    const stored = await echo(recipient, 2, redelivered.json.turnId, { text: content });
    assert.equal(stored.controlPlaneNote, `\n\n${block}`, 'the block was not recorded as the control plane’s note');
    assert.deepEqual(stored.sessionMessage, {
      fromSessionId: worker, fromTitle: 'Worker: asks for a review', fromAgentName: 'orbit-worker', fromTaskId: task.id,
    });
  });

  await t.test('a re-send that revives the session keeps the sender as well', async () => {
    const worker = await session('Worker: reports a green build');
    const recipient = await session('the conversation a provider error failed');
    await sessionSend(worker, recipient, 'the build is green — please merge', 'revive-retry-1');

    await autoRetry.sweep(await failAndArm(recipient, RunStatus.FAILED));

    const standing = await prisma.session.findUniqueOrThrow({ where: { id: recipient } });
    assert.equal(standing.status, RunStatus.PENDING, `the failed session was not revived: ${standing.status}`);
    const [resent] = await resentOn(recipient);
    assert.ok(resent, 'the sweep re-sent nothing');
    assert.equal(resent.senderSessionId, worker, 'the revive dropped the sender');
  });

  await t.test('the re-send is not one more message from that session in the pair’s hour', async () => {
    const chatty = await session('Worker: whose message failed once');
    const busy = await session('the session it writes to');
    await sessionSend(chatty, busy, 'message 1', 'counted-1');
    await autoRetry.sweep(await failAndArm(busy, RunStatus.AWAITING_INPUT));
    assert.equal((await resentOn(busy)).length, 1, 'the sweep re-sent nothing');

    // Nineteen more fit: the one it sent and the nineteen make twenty, and the re-send is none of them.
    for (let i = 2; i <= SESSION_MESSAGES_PER_PAIR_PER_HOUR; i++) {
      await sessionSend(chatty, busy, `message ${i}`, `counted-${i}`);
    }
    await assert.rejects(() => sessionSend(chatty, busy, 'message 21', 'counted-21'), (error: unknown) => {
      assert.equal(refusalOf(error).code, SESSION_MESSAGE_RATE_LIMITED_CODE);
      return true;
    });
    const signed = (await turnsOf(busy)).filter((turn) => turn.senderSessionId === chatty);
    assert.equal(signed.length, SESSION_MESSAGES_PER_PAIR_PER_HOUR + 1, 'twenty messages and the one re-send');
  });

  await t.test('the owner’s own message is re-sent as the owner’s, and the platform’s key is nobody else’s', async () => {
    const recipient = await session('a conversation only the owner talks to');
    await ownerSend(recipient, 'the owner’s question');
    await autoRetry.sweep(await failAndArm(recipient, RunStatus.AWAITING_INPUT));
    const [resent] = await resentOn(recipient);
    assert.ok(resent, 'the sweep re-sent nothing');
    assert.equal(resent.senderSessionId, null, 'the owner’s message was re-sent under a session’s name');

    // A session cannot file its own message under the re-send's key and pass it off as the platform's.
    const worker = await session('Worker: picks a key');
    await assert.rejects(
      () => sessionSend(worker, recipient, 'uncounted?', `${AUTO_RETRY_TURN_KEY_PREFIX}mine`),
      (error: unknown) => {
        assert.equal((error as { getStatus?: () => number }).getStatus?.(), 400);
        return true;
      },
    );
    await assert.rejects(
      () => sessionInterrupt(worker, recipient, 'uncounted?', `${AUTO_RETRY_TURN_KEY_PREFIX}mine`),
      (error: unknown) => {
        assert.equal((error as { getStatus?: () => number }).getStatus?.(), 400);
        return true;
      },
    );
  });

  // ── 12. the queue, while another session's message waits ──────────────────────────────────────

  await t.test('a waiting message from another session carries its card on both views of the queue', async () => {
    const worker = await session('Worker: queued behind the owner');
    const recipient = await session('a conversation with a queue');
    await ownerSend(recipient, 'the owner goes first');
    await sessionSend(worker, recipient, 'and then mine', 'queued-1');
    const [queuedTurn] = (await turnsOf(recipient)).filter((turn) => turn.clientTurnId === 'queued-1');
    // The request it carries, when its sender asked for a reply: the card names it, as the echo's does.
    const request = await prisma.sessionRequest.create({
      data: {
        ownerId, fromSessionId: worker, toSessionId: recipient, turnId: queuedTurn.id, clientTurnId: 'queued-1',
        requestPreview: 'and then mine', replyBy: new Date(Date.now() + 60 * 60_000),
      },
    });
    const card = {
      fromSessionId: worker, fromTitle: 'Worker: queued behind the owner', fromAgentName: 'orbit-worker',
      requestId: uuidToBase62(request.id),
    };

    // What the installed native clients read: queued rows only, the owner's accepted head left out.
    const narrow = await sessions.listQueuedTurns(ownerId, recipient);
    assert.deepEqual(narrow.map((row) => row.turnId), [queuedTurn.id]);
    assert.deepEqual(narrow[0].sessionMessage, card);
    assert.equal(narrow[0].authoredByOrbit, undefined, 'somebody did write it: the worker');

    // What the web reads: the owner's head with no card, the worker's message with its own.
    const active = await sessions.listQueuedTurns(ownerId, recipient, 'active');
    assert.equal(active.length, 2);
    assert.equal(active[0].placement, 'accepted');
    assert.equal(active[0].sessionMessage, undefined, 'the owner’s message was drawn as another session’s');
    assert.equal(active[1].turnId, queuedTurn.id);
    assert.equal(active[1].placement, 'queued');
    assert.deepEqual(active[1].sessionMessage, card);
  });

  // ── 13. the message an interrupt carries ──────────────────────────────────────────────────────

  await t.test('session_interrupt’s message is signed with the calling session and delivered as its message', async () => {
    const worker = await session('Worker: changes course');
    const recipient = await session('the session being redirected');
    const words = 'stop — the spec changed, use the v2 endpoint instead';
    const answer = await sessionInterrupt(worker, recipient, words, 'interrupt-1');
    assert.ok('turnId' in answer && answer.turnId, `the interrupt filed no message: ${JSON.stringify(answer)}`);

    assert.equal(await senderOf(recipient, 'interrupt-1'), worker, 'the interrupt’s message is not signed');
    // The interrupt itself says nothing, so it is nobody's message.
    const control = (await turnsOf(recipient)).filter((turn) => turn.kind === 'interrupt');
    assert.equal(control.length, 1);
    assert.equal(control[0].senderSessionId, null);
    // Charged as a steer as before: the hourly limit came in beside that charge, not instead of it.
    assert.ok(steers.includes(recipient), 'the steer was no longer charged');

    // While it waits for the interrupt to land, the queue draws it as the worker's.
    const [waiting] = await sessions.listQueuedTurns(ownerId, recipient, 'active');
    assert.equal(waiting?.turnId, answer.turnId);
    assert.deepEqual(waiting?.sessionMessage, {
      fromSessionId: worker, fromTitle: 'Worker: changes course', fromAgentName: 'orbit-worker',
    });

    const delivered = await claimToMessage(recipient);
    const content = String(delivered.json.content ?? '');
    const block = sessionMessageBlock({
      id: worker, title: 'Worker: changes course', taskId: null, workspace: { name: 'orbit-worker' },
    });
    assert.equal(content, `${words}\n\n${block}`, `the engine was handed something else:\n${content}`);
    const stored = await echo(recipient, 1, delivered.json.turnId, { text: content });
    assert.equal(stored.controlPlaneNote, `\n\n${block}`);
    assert.deepEqual(stored.sessionMessage, {
      fromSessionId: worker, fromTitle: 'Worker: changes course', fromAgentName: 'orbit-worker',
    });
  });

  await t.test('an interrupt’s message counts against the pair’s hour, and the 21st is refused', async () => {
    const chatty = await session('Worker: keeps redirecting');
    const busy = await session('the session it keeps redirecting');
    for (let i = 1; i < SESSION_MESSAGES_PER_PAIR_PER_HOUR; i++) {
      await sessionSend(chatty, busy, `message ${i}`, `sent-${i}`);
    }
    // Read and answered, so the interrupt below has nothing of the worker's left to drop: what is
    // counted is what was sent.
    await prisma.conversationTurn.updateMany({ where: { sessionId: busy }, data: { status: 'ANSWERED', answeredAt: new Date() } });
    await prisma.session.update({ where: { id: busy }, data: { status: RunStatus.AWAITING_INPUT } });

    // The twentieth is an interrupt's, counted with the nineteen sends.
    const twentieth = await sessionInterrupt(chatty, busy, 'stop and do this instead (20)', 'interrupt-20');
    assert.equal(await senderOf(busy, 'interrupt-20'), chatty);
    // The runner takes it, so the session is live again and the next interrupt is judged on the count
    // alone: one aimed at a session still waiting to be claimed is refused as ended before that.
    await claimToMessage(busy);

    const before = await turnsOf(busy);
    await assert.rejects(() => sessionInterrupt(chatty, busy, 'and this (21)', 'interrupt-21'), (error: unknown) => {
      const refusal = refusalOf(error);
      assert.equal((error as { getStatus?: () => number }).getStatus?.(), 409);
      assert.equal(refusal.code, SESSION_MESSAGE_RATE_LIMITED_CODE);
      assert.equal(refusal.retryable, false);
      return true;
    });
    // Refused before anything was dropped: the twentieth still waits, and no second interrupt was filed.
    const after = await turnsOf(busy);
    assert.deepEqual(after.map((turn) => [turn.id, turn.status]), before.map((turn) => [turn.id, turn.status]));
    // ...and the same pair's ordinary send is refused by the same count.
    await assert.rejects(() => sessionSend(chatty, busy, 'or this (21)', 'sent-21'), (error: unknown) => {
      assert.equal(refusalOf(error).code, SESSION_MESSAGE_RATE_LIMITED_CODE);
      return true;
    });

    // A retry of the counted interrupt is its receipt, not a 21st message.
    const replayed = await sessionInterrupt(chatty, busy, 'stop and do this instead (20)', 'interrupt-20');
    assert.ok('turnId' in twentieth && 'turnId' in replayed);
    assert.equal(replayed.turnId, twentieth.turnId, 'a retry of the counted interrupt was not its receipt');
    // A bodyless interrupt carries no message: the limit is not its business.
    assert.deepEqual(await sessionInterrupt(chatty, busy), { ok: true });
    const signed = (await turnsOf(busy)).filter((turn) => turn.senderSessionId === chatty);
    assert.equal(signed.length, SESSION_MESSAGES_PER_PAIR_PER_HOUR);
  });

  // ── 16. what was sent stays sent ───────────────────────────────────────────────────────────────

  /** `busy` in the middle of a turn of the owner's — the shape an interrupt is aimed at: one aimed
   *  at a session still waiting to be claimed is refused as ended. */
  async function midTurn(busy: string): Promise<void> {
    await ownerSend(busy, 'the owner’s own task');
    await claimAndPoll(busy);
  }

  /** Twenty messages from `chatty`, each still waiting in `busy`'s queue, none of them read. */
  async function twentyQueued(chatty: string, busy: string, label: string): Promise<string[]> {
    for (let i = 1; i <= SESSION_MESSAGES_PER_PAIR_PER_HOUR; i++) {
      await sessionSend(chatty, busy, `${label} (${i})`, `${label}-${i}`);
    }
    const queued = (await turnsOf(busy)).filter((turn) => turn.senderSessionId === chatty);
    assert.equal(queued.length, SESSION_MESSAGES_PER_PAIR_PER_HOUR);
    assert.ok(queued.every((turn) => turn.status === 'PENDING'), 'a message was read before it could be dropped');
    return queued.map((turn) => turn.id);
  }

  const refusedAsTheTwentyFirst = (error: unknown) => {
    assert.equal(refusalOf(error).code, SESSION_MESSAGE_RATE_LIMITED_CODE);
    return true;
  };

  await t.test('messages an interrupt drops from the queue still count for their hour', async () => {
    const chatty = await session('Worker: fills a queue');
    const busy = await session('the session whose queue the owner drops');
    await midTurn(busy);
    await twentyQueued(chatty, busy, 'dropped');
    await sessions.interrupt(ownerId, busy);
    assert.equal((await turnsOf(busy)).filter((turn) => turn.senderSessionId === chatty).length, 0,
      'the interrupt dropped nothing, so this proves nothing');
    await assert.rejects(() => sessionSend(chatty, busy, 'dropped (21)', 'dropped-21'), refusedAsTheTwentyFirst);
  });

  await t.test('messages the owner withdraws from the queue still count for their hour', async () => {
    const chatty = await session('Worker: fills a queue the owner empties');
    const busy = await session('the session whose owner withdraws them');
    for (const turnId of await twentyQueued(chatty, busy, 'withdrawn')) {
      await sessions.cancelQueuedTurn(ownerId, busy, turnId);
    }
    assert.equal((await turnsOf(busy)).filter((turn) => turn.senderSessionId === chatty).length, 0);
    await assert.rejects(() => sessionSend(chatty, busy, 'withdrawn (21)', 'withdrawn-21'), refusedAsTheTwentyFirst);
  });

  await t.test('a session cannot clear its own count by dropping its queued messages with an interrupt', async () => {
    const chatty = await session('Worker: queues, then interrupts its own queue');
    const busy = await session('the session it floods');
    await midTurn(busy);
    for (let i = 1; i < SESSION_MESSAGES_PER_PAIR_PER_HOUR; i++) {
      await sessionSend(chatty, busy, `queued (${i})`, `own-${i}`);
    }
    // The twentieth is an interrupt's, which drops the nineteen before it.
    await sessionInterrupt(chatty, busy, 'never mind those — do this (20)', 'own-interrupt-20');
    const left = (await turnsOf(busy)).filter((turn) => turn.senderSessionId === chatty);
    assert.deepEqual(left.map((turn) => turn.clientTurnId), ['own-interrupt-20'], 'the interrupt dropped nothing');
    await assert.rejects(() => sessionSend(chatty, busy, 'and again (21)', 'own-21'), refusedAsTheTwentyFirst);
    await assert.rejects(() => sessionInterrupt(chatty, busy, 'and again (21)', 'own-interrupt-21'), refusedAsTheTwentyFirst);
  });

  // ── 15. the failure card's Retry, for another session's message ───────────────────────────────

  await t.test('the failure card’s Retry has the server re-send another session’s message: its sender, its request, nobody charged', async () => {
    const door = new SessionsController(
      sessions, prisma as unknown as PrismaService, realtime as never, {} as never, {} as never, autoRetry,
    );
    const user = { userId: ownerId } as never;
    // Asked through a door that records requests (this file's own `sendDoor` was built without them).
    const askingDoor = new RunnerSessionsController(
      sessions, orchestration, {} as never, attempts as never, undefined,
      new SessionRequestService(prisma as unknown as PrismaService, sessions, realtime as never),
    );
    const options = [{ label: 'ship it' }, { label: 'hold' }];
    async function ask(worker: string, recipient: string, words: string, key: string): Promise<{ requestId: string; id: string }> {
      const asked = await askingDoor.sendMessage(
        runner, undefined, worker, await orchestration.issue(runnerId, worker), recipient,
        { message: words, clientTurnId: key, expectReply: true, replyOptions: options } as never,
      ) as { requestId?: string };
      assert.ok(asked.requestId, `the send asked for no reply: ${JSON.stringify(asked)}`);
      return { requestId: String(asked.requestId), id: base62ToUuid(String(asked.requestId)) };
    }

    // The quota killed the turn the request arrived on, and the card offers "Retry now anyway".
    {
      const worker = await session('Worker: asks for a decision');
      const recipient = await session('the conversation whose turn the quota killed on the request');
      const words = 'ship it or hold?';
      const request = await ask(worker, recipient, words, 'card-retry-1');
      await failAndArm(recipient, RunStatus.AWAITING_INPUT);

      // What the card is told before it offers the button: the words, and whose they are.
      const offered = await door.retryMessage(user, recipient);
      assert.equal(offered.text, words);
      assert.deepEqual(offered.sessionMessage, {
        fromSessionId: worker, fromTitle: 'Worker: asks for a decision', fromAgentName: 'orbit-worker',
        requestId: request.requestId,
      });

      const steersBefore = steers.length;
      const resent = await door.resendRetryMessage(user, recipient, {});
      const resentTurn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: resent.turnId } });
      assert.equal(await senderOf(recipient, resentTurn.clientTurnId), worker, 'the re-send went out in the owner’s name');
      assert.equal((await prisma.sessionRequest.findUniqueOrThrow({ where: { id: request.id } })).turnId, resent.turnId,
        'the request stayed on the turn that failed');
      assert.equal(steers.length, steersBefore, 'the re-send was charged as a steer');
      assert.equal((await prisma.session.findUniqueOrThrow({ where: { id: recipient } })).retryAt, null,
        'the armed retry would send it a second time');
      // §8 criterion 19: pressing again — a lost response, a double tap — is the turn already
      // queued, not a second one. Pressed here, at the instant the runner has taken the re-send and
      // its echo has not yet moved what "the failed message" is: the session is running again, so
      // with a key minted per click — what this door took before — the second press went through the
      // live path and queued a second, signed, uncharged copy of the same message. Called with a
      // body an older client still sends: this door takes no key, and ignores it.
      const clickAgain = door.resendRetryMessage.bind(door) as unknown as (
        user: unknown, id: string, body?: { clientTurnId?: string },
      ) => Promise<{ turnId: string }>;
      const redelivered = await claimAndPoll(recipient);
      assert.equal(redelivered.json.turnId, resent.turnId);
      assert.equal((await clickAgain(user, recipient, { clientTurnId: randomUUID() })).turnId, resent.turnId,
        'a second press queued a second turn for one failed message');
      assert.equal((await turnsOf(recipient)).filter((turn) => turn.content === words).length, 2,
        'the failed turn and its one re-send');

      // The engine reads the worker's request again: the words, then the block, asking for a reply.
      const content = String(redelivered.json.content ?? '');
      assert.ok(content.startsWith(`${words}\n\n<orbit-session-message from-session="${uuidToBase62(worker)}"`),
        `the engine was handed something else:\n${content}`);
      assert.match(content, new RegExp(`request-id="${request.requestId}" reply-by="`));
      assert.match(content, new RegExp(`session_reply\\(requestId="${request.requestId}"\\)`));
      const stored = await echo(recipient, 2, redelivered.json.turnId, { text: content });
      assert.equal((stored.sessionMessage as Record<string, unknown>).requestId, request.requestId);
      // …and once that echo has moved what a Retry would re-send to the re-sent turn itself, a press
      // is STILL that turn: the failed message is the one it re-sent, and the key names it (§2.1).
      assert.equal((await clickAgain(user, recipient, { clientTurnId: randomUUID() })).turnId, resent.turnId,
        'a press after the engine took the re-send queued a second turn');
      assert.equal((await turnsOf(recipient)).filter((turn) => turn.content === words).length, 2,
        'the failed turn and its one re-send');

      // Charged to nobody's hour: with the request, nineteen more from the worker make twenty, and the
      // next is refused — the re-send is none of them.
      for (let i = 2; i <= SESSION_MESSAGES_PER_PAIR_PER_HOUR; i++) {
        await sessionSend(worker, recipient, `and ${i}`, `card-retry-${i}`);
      }
      await assert.rejects(() => sessionSend(worker, recipient, 'and 21', 'card-retry-21'), refusedAsTheTwentyFirst);
    }

    // The provider failed the run: the Retry revives it, and the re-send is the worker's all the same.
    {
      const worker = await session('Worker: asks one the provider fails');
      const recipient = await session('the conversation a provider error failed on the request');
      const request = await ask(worker, recipient, 'cut the release branch?', 'card-revive-1');
      await failAndArm(recipient, RunStatus.FAILED);
      const resent = await door.resendRetryMessage(user, recipient, {});
      assert.equal(resent.revived, true, 'the failed run was not revived');
      const resentTurn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: resent.turnId } });
      assert.equal(await senderOf(recipient, resentTurn.clientTurnId), worker);
      assert.equal((await prisma.sessionRequest.findUniqueOrThrow({ where: { id: request.id } })).turnId, resent.turnId);
      assert.equal((await prisma.session.findUniqueOrThrow({ where: { id: recipient } })).status, RunStatus.PENDING);
    }
  });

  await t.test('a re-send that fails before its echo is re-sent by the next press; one that went through is not sent twice (§8 criterion 22)', async () => {
    const door = new SessionsController(
      sessions, prisma as unknown as PrismaService, realtime as never, {} as never, {} as never, autoRetry,
    );
    const user = { userId: ownerId } as never;
    const askingDoor = new RunnerSessionsController(
      sessions, orchestration, {} as never, attempts as never, undefined,
      new SessionRequestService(prisma as unknown as PrismaService, sessions, realtime as never),
    );
    async function ask(worker: string, recipient: string, words: string, key: string): Promise<string> {
      const asked = await askingDoor.sendMessage(
        runner, undefined, worker, await orchestration.issue(runnerId, worker), recipient,
        { message: words, clientTurnId: key, expectReply: true } as never,
      ) as { requestId?: string };
      assert.ok(asked.requestId, `the send asked for no reply: ${JSON.stringify(asked)}`);
      return base62ToUuid(String(asked.requestId));
    }
    /** The runner's account of a turn, posted as it posts one: events, then the completion. */
    async function report(sessionId: string, events: Array<{ seq: number; type: string; turnId: string; payload: unknown }>) {
      const posted = await http('POST', `/runner/sessions/${uuidToBase62(sessionId)}/events`, {
        events: events.map((event) => ({ ...event, ts: new Date().toISOString() })),
      });
      assert.equal(posted.status, 202, `events answered ${posted.status}: ${posted.text}`);
    }
    async function complete(sessionId: string, body: Record<string, unknown>) {
      const done = await http('POST', `/runner/sessions/${uuidToBase62(sessionId)}/turn-complete`, body);
      assert.equal(done.status, 200, `turn-complete answered ${done.status}: ${done.text}`);
    }
    /** Claude's delivery failure (runner-go session.go, `failUndeliveredTurn`): the runtime refused the
     *  message before writing it, so there is no echo — only the runner's receipt and a FAILED turn. */
    async function refusedBeforeWritten(sessionId: string, seq: number, turnId: string) {
      const why = 'write |1: broken pipe';
      await report(sessionId, [{
        seq, type: 'user_delivery', turnId, payload: { turnId, delivery: 'failed', reason: why, retryable: true },
      }]);
      await complete(sessionId, {
        turnId, status: 'FAILED', subtype: 'delivery_failed', numTurns: 0, costUsd: 0,
        result: `message not delivered to the engine: ${why}`,
      });
    }
    const press = (recipient: string) => door.resendRetryMessage(user, recipient, {});
    const copiesOf = async (sessionId: string, words: string) =>
      (await turnsOf(sessionId)).filter((turn) => turn.content === words);

    // The re-send meets a runtime that will not take it: no echo, the runner's receipt, the turn FAILED.
    // The next press re-sends it — a new turn, carrying the request on — where it used to answer with
    // the very turn that had failed, on every press after.
    {
      const worker = await session('Worker: whose re-send is refused before it is written');
      const recipient = await session('the conversation whose CLI stops reading stdin');
      const words = 'ship it or hold? (refused before written)';
      const requestId = await ask(worker, recipient, words, 'card-refused-1');
      await failAndArm(recipient, RunStatus.AWAITING_INPUT);
      const first = await press(recipient);
      const handed = await claimAndPoll(recipient);
      assert.equal(handed.json.turnId, first.turnId);
      await refusedBeforeWritten(recipient, 2, first.turnId);
      const failed = await prisma.session.findUniqueOrThrow({ where: { id: recipient } });
      assert.equal(failed.status, RunStatus.FAILED);
      assert.equal((await prisma.sessionRequest.findUniqueOrThrow({ where: { id: requestId } })).state, 'OPEN');

      const second = await press(recipient);
      assert.notEqual(second.turnId, first.turnId, 'the press answered with the re-send that had already failed');
      const secondTurn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: second.turnId } });
      assert.equal(secondTurn.content, words);
      assert.equal(await senderOf(recipient, secondTurn.clientTurnId), worker, 'the re-send went out in the owner’s name');
      assert.equal((await prisma.sessionRequest.findUniqueOrThrow({ where: { id: requestId } })).turnId, second.turnId,
        'the request stayed on the turn that failed');
      // Within this failure, a press is still the one turn: before the runner has it, and after.
      assert.equal((await press(recipient)).turnId, second.turnId, 'a second press queued a second turn');
      const again = await claimAndPoll(recipient);
      assert.equal(again.json.turnId, second.turnId);
      assert.equal((await press(recipient)).turnId, second.turnId);
      assert.equal((await copiesOf(recipient, words)).length, 3, 'the failed turn, its failed re-send, and one more');
    }

    // The re-send went through and was answered; only its response was lost. Pressed again, it is that
    // turn — where a press after it settled used to queue a signed, uncharged second copy.
    {
      const worker = await session('Worker: whose re-send goes through');
      const recipient = await session('the conversation that answers the re-send');
      const words = 'ship it or hold? (went through)';
      await ask(worker, recipient, words, 'card-through-1');
      await failAndArm(recipient, RunStatus.AWAITING_INPUT);
      const first = await press(recipient);
      const handed = await claimAndPoll(recipient);
      assert.equal(handed.json.turnId, first.turnId);
      await report(recipient, [
        { seq: 2, type: 'user', turnId: first.turnId, payload: { text: String(handed.json.content ?? '') } },
        { seq: 3, type: 'assistant', turnId: first.turnId, payload: { text: 'Shipping it.' } },
      ]);
      await complete(recipient, { turnId: first.turnId, status: 'SUCCEEDED', subtype: 'success', numTurns: 1, costUsd: 0 });
      assert.equal((await prisma.session.findUniqueOrThrow({ where: { id: recipient } })).status, RunStatus.AWAITING_INPUT);

      assert.equal((await press(recipient)).turnId, first.turnId, 'a press after the re-send went through re-sent it again');
      assert.equal((await copiesOf(recipient, words)).length, 2, 'the failed turn and its one re-send');
    }

    // The sweep's own re-send went through: there is no failure left for a press to re-send.
    {
      const worker = await session('Worker: whose message the sweep re-sends');
      const recipient = await session('the conversation the sweep revives');
      const words = 'ship it or hold? (re-sent by the sweep)';
      await ask(worker, recipient, words, 'card-swept-1');
      await autoRetry.sweep(await failAndArm(recipient, RunStatus.AWAITING_INPUT));
      const [resent] = await resentOn(recipient);
      assert.ok(resent, 'the sweep re-sent nothing');
      const handed = await claimAndPoll(recipient);
      assert.equal(handed.json.turnId, resent.id);
      await report(recipient, [
        { seq: 2, type: 'user', turnId: resent.id, payload: { text: String(handed.json.content ?? '') } },
        { seq: 3, type: 'assistant', turnId: resent.id, payload: { text: 'Holding.' } },
      ]);
      await complete(recipient, { turnId: resent.id, status: 'SUCCEEDED', subtype: 'success', numTurns: 1, costUsd: 0 });
      await assert.rejects(() => press(recipient), (error: unknown) => {
        assert.equal((error as { getStatus?: () => number }).getStatus?.(), 409);
        assert.match(String((error as Error).message), /not stopped on a failure/);
        return true;
      }, 'a press over a message that did not fail re-sent it');
      assert.equal((await copiesOf(recipient, words)).length, 2, 'the failed turn and the sweep’s one re-send');
    }
  });

  await t.test('the Retry door names no key of the caller’s: the server derives it from the failed message', async () => {
    const recipient = await session('a conversation the door is asked about');
    const door = new SessionsController(
      sessions, prisma as unknown as PrismaService, realtime as never, {} as never, {} as never, autoRetry,
    );
    const user = { userId: ownerId } as never;
    // Nothing to re-send is refused as itself, whatever body arrives with the call — including the
    // `clientTurnId` an older client still mints, which is ignored rather than refused (§2.1).
    const call = door.resendRetryMessage.bind(door) as unknown as (
      user: unknown, id: string, body?: { clientTurnId?: string },
    ) => Promise<unknown>;
    for (const extra of [{}, { clientTurnId: randomUUID() }, { clientTurnId: `${AUTO_RETRY_TURN_KEY_PREFIX}mine` }]) {
      await assert.rejects(() => call(user, recipient, extra), (error: unknown) => {
        assert.equal((error as { getStatus?: () => number }).getStatus?.(), 409);
        return true;
      }, `the door answered something else for ${JSON.stringify(extra)}`);
    }
  });
  await t.test('a Retry pressed with a provider picked carries it into the resume', async () => {
    const recipient = await session('the conversation retried onto a picked provider');
    await ownerSend(recipient, 'retry this on the other one?');
    await failAndArm(recipient, RunStatus.FAILED);
    const door = new SessionsController(
      sessions, prisma as unknown as PrismaService, realtime as never, {} as never, {} as never, autoRetry,
    );
    const user = { userId: ownerId } as never;

    // A session keeps its runtime (sessions.service.resolveProviderSwitch), so a pick that rule
    // refuses comes back as that refusal — and the refusal is the proof the pick reached the resume.
    // Before, this door took no body at all: nothing was ever sent, so nothing could be refused, and
    // the re-send ran on the provider the session was already on — which is how "choose the pool,
    // press Retry" came out on the account the person was trying to leave (2026-10-05).
    await assert.rejects(
      () => door.resendRetryMessage(user, recipient, { provider: 'codex' }),
      /cannot switch to a provider that runs on/,
      'the pick the composer had did not reach the resume',
    );
  });
});
