/**
 * One turn, one set of cards: a waiting turn is listed with the cards its echo is stored with
 * (sessions/turn-cards.ts) — against a real PostgreSQL.
 *
 * A turn the control plane opened is drawn as a card rather than as the owner's bubble, and it is
 * drawn at three moments: while it waits, off `listQueuedTurns` — the queue view the native clients
 * read and the active view the web reads — and once the runner echoes it, off the `user` event's
 * payload. For each kind of card this queues one such turn through the door that writes it in
 * production, reads both views, hands the turn to the runner and echoes it through the real event
 * ingest, and asserts that the card fields are the same in all three, field by field — and in the
 * active view's accepted row between hand-out and echo, for the turns that view keeps there.
 *
 * The card fields are listed below under a type that `TurnCards` keys, so a card added there does not
 * compile here until it is listed, and the last case is red until it has a case of its own.
 *
 * The doors are the real services and controllers; the inbox, the event ingest and the turn
 * completion are the real RunnerApiController methods, called as the runner does.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/sessions/turn-cards-parity.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { JwtService } from '@nestjs/jwt';
import {
  CreatorType,
  type Prisma,
  type PrismaClient,
  type Runner,
  RunStatus,
  RunnerStatus,
  SessionDispatchOrigin,
  SessionRunSource,
  TaskStatus,
} from '@prisma/client';
import { RunEventType, RunStatus as SharedRunStatus, base62ToUuid } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import type { PrismaService } from '../prisma/prisma.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { OPEN_ITEM_TURN_PREFIX } from '../projects/project-open-item';
import { ProjectOpenItemService } from '../projects/project-open-item.service';
import { PROJECT_STARTED_TURN_PREFIX, tellCoordinatorProjectStarted } from '../projects/project-started';
import type { PushService } from '../push/push.service';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerOrchestrationAuthorizer } from '../runner-api/runner-orchestration-authorizer';
import { RunnerSessionsController } from '../runner-api/runner-sessions.controller';
import { RunnerTaskOwnerConfirmationController } from '../runner-api/runner-task-owner-confirmation.controller';
import { OwnerConfirmationReviewService } from '../tasks/owner-confirmation-review.service';
import { buildTaskExecutionPrompt } from '../tasks/task-execution-prompt';
import { TaskOwnerConfirmationService } from '../tasks/task-owner-confirmation.service';
import { taskRunResumeTurnId } from '../tasks/task-run-identity';
import { TasksService } from '../tasks/tasks.service';
import { replyToSessionRequest, SESSION_REPLY_TURN_PREFIX } from './session-request';
import { SessionRequestService } from './session-request.service';
import { SessionsService } from './sessions.service';
import type { TurnCards } from './turn-cards';
import {
  CONFIRMATION_RETURN_TURN_KEY_PREFIX,
  OWNER_CONFIRMATION_REVIEW_TURN_KEY_PREFIX,
} from './watch-turn-key';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;
const SHA = 'c3'.repeat(20);

/** Every card a turn can carry, by the name its echo stores it under. Keyed by `TurnCards`: a card
 *  added there is a compile error here until it is listed, and then a red below until it has a case. */
const CARD_FIELDS: Record<keyof TurnCards, true> = {
  openItemDelivery: true,
  taskStart: true,
  projectStarted: true,
  confirmationReviewRequest: true,
  confirmationReturn: true,
  sessionMessage: true,
  sessionReplies: true,
};
const FIELDS = Object.keys(CARD_FIELDS) as Array<keyof TurnCards>;

/** The card fields a row or a payload carries, as a client reads them — over the wire, so a value is
 *  compared as the JSON it is sent as — with every absent field left out. */
function cardsOf(carrier: object): Partial<Record<keyof TurnCards, unknown>> {
  const fields = carrier as Record<string, unknown>;
  return Object.fromEntries(FIELDS
    .filter((field) => fields[field] !== undefined)
    .map((field) => [field, JSON.parse(JSON.stringify(fields[field]))]));
}

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

test('a waiting turn is listed with the cards its echo is stored with, in both views, for every kind of card', {
  skip, concurrency: 1, timeout: 600_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });
  const db = prisma as unknown as PrismaService;

  // ── the world: one account, one machine, one workspace every session runs in ─────────────────
  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const workspaceId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `turn-cards-${ownerId}@parity.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: {
      id: runnerId, ownerId, name: 'the machine every session runs on', tokenHash: sha256(`token-${runnerId}`),
      status: RunnerStatus.ONLINE, lastHeartbeatAt: new Date(), capabilities: [], capabilitiesReportedAt: new Date(),
    },
  });
  await prisma.workspace.create({ data: { id: workspaceId, ownerId, runnerId, name: 'orbit-worker', enabled: true } });
  const runner = { id: runnerId, ownerId } as Runner;

  /** A session on this runner, parked between turns. */
  async function session(title: string, data: Partial<Prisma.SessionUncheckedCreateInput> = {}): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id, ownerId, creatorId: ownerId, workspaceId, assignedRunnerId: runnerId,
        title, prompt: title, provider: 'claude', status: RunStatus.AWAITING_INPUT,
        numTurns: 1, startedAt: new Date(), runtimeSessionId: `runtime-${id}`,
        dispatchOrigin: SessionDispatchOrigin.USER, runSource: SessionRunSource.MANUAL,
        ...data,
      },
    });
    return id;
  }

  async function task(title: string, data: Partial<Prisma.TaskUncheckedCreateInput> = {}): Promise<string> {
    const created = await prisma.task.create({
      data: {
        ownerId, title, creatorType: CreatorType.USER, creatorId: ownerId, assigneeId: workspaceId,
        completionCriterion: 'EVIDENCE_JUDGMENT', ...data,
      },
      select: { id: true },
    });
    return created.id;
  }

  /** A project whose coordinator conversation is of record: the one an item or a start is told to. */
  async function coordinatedProject(title: string): Promise<{ projectId: string; coordinator: string }> {
    // The conversation first: a project's pointer at one is guarded (COORDINATOR_POINTER_INVALID).
    const coordinator = await session(`coordinator: ${title}`, { titleManagedByProject: true });
    const projectId = randomUUID();
    await prisma.project.create({
      data: {
        id: projectId, ownerId, title, coordinatorEnabled: true,
        coordinatorSessionId: coordinator, coordinatorWorkspaceId: workspaceId,
      },
    });
    return { projectId, coordinator };
  }

  // ── the doors ─────────────────────────────────────────────────────────────────────────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(db, queue as never, realtime as never);
  const tasks = new TasksService(db, sessions, realtime as never);
  const requests = new SessionRequestService(db, sessions, realtime as never);
  const push = { notifyConfirmationProblems: async () => undefined } as unknown as PushService;
  const reviews = new OwnerConfirmationReviewService(db, sessions, realtime as never, push);
  const confirmations = new TaskOwnerConfirmationService(db, sessions, tasks, realtime as never, reviews);
  const confirmationDoor = new RunnerTaskOwnerConfirmationController(confirmations, reviews);
  const openItems = new ProjectOpenItemService(db, sessions);
  const orchestration = new RunnerOrchestrationAuthorizer(db, new JwtService({ secret: 'turn-cards-parity-pg' }));
  const attempts = { chargeSteer: async () => undefined };
  const sendDoor = new RunnerSessionsController(sessions, orchestration, {} as never, attempts as never, undefined, requests);
  const api = new RunnerApiController(
    db,
    queue as never,
    realtime as never,
    {} as never,
    orchestration,
    // The messages here carry no `#`-references and reach no list console.
    { expand: async (_owner: string, content?: string) => content } as never,
    { appendFor: async (_tx: unknown, _id: string, content?: string) => content } as never,
    undefined,
    undefined,
    tasks,
    undefined,
    sessions,
    undefined,
    undefined,
    undefined,
    undefined,
    requests,
    reviews,
  );

  /** The owner's own message, waiting at the head of the queue: what the card's turn queues behind. */
  async function ownerSays(sessionId: string, words: string): Promise<string> {
    return (await sessions.createTurn(ownerId, sessionId, { clientTurnId: randomUUID(), content: words })).turnId;
  }

  /** The one turn of a session whose key starts with `prefix`. */
  async function turnKeyed(sessionId: string, prefix: string) {
    const turns = await prisma.conversationTurn.findMany({ where: { sessionId, clientTurnId: { startsWith: prefix } } });
    assert.equal(turns.length, 1, `expected one ${prefix} turn on the session, found ${turns.length}`);
    return turns[0];
  }

  /** `session_send` asking for a reply, as the runner calls it from the sending session's credential. */
  async function ask(from: string, to: string, message: string): Promise<{ requestId: string; id: string }> {
    const receipt = await sendDoor.sendMessage(
      runner, undefined, from, await orchestration.issue(runnerId, from), to,
      { message, clientTurnId: randomUUID(), expectReply: true } as never,
    ) as Record<string, unknown>;
    assert.equal(typeof receipt.requestId, 'string', `the send answered no request: ${JSON.stringify(receipt)}`);
    return { requestId: String(receipt.requestId), id: base62ToUuid(String(receipt.requestId)) };
  }

  /**
   * What the runner's claim does to a queued session, then the polls that follow it until a message
   * comes out — a control turn is handed out first and answered on the spot.
   */
  async function deliver(sessionId: string): Promise<{ turnId: string; content: string }> {
    await prisma.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    for (;;) {
      const handed = await (api as unknown as {
        dequeueTurn: (sessionId: string, runnerId: string, leaseGeneration: string | null) => Promise<Record<string, unknown> | null>;
      }).dequeueTurn.call(api, sessionId, runnerId, null);
      assert.ok(handed, `the inbox of ${sessionId} handed nothing out`);
      const turn = await prisma.conversationTurn.findUniqueOrThrow({ where: { id: String(handed.turnId) } });
      if (turn.kind !== 'message') continue;
      return { turnId: turn.id, content: String(handed.content ?? '') };
    }
  }

  const seqs = new Map<string, number>();
  /** The runner's event for one turn, through the real ingest. Answers the payload that was stored. */
  async function say(sessionId: string, turnId: string, type: RunEventType, payload: Record<string, unknown>) {
    const seq = (seqs.get(sessionId) ?? 100) + 1;
    seqs.set(sessionId, seq);
    await api.events({ id: runnerId } as never, sessionId, {
      events: [{ seq, type, ts: new Date().toISOString(), turnId, payload }],
    } as never);
    return (await prisma.runEvent.findFirstOrThrow({ where: { sessionId, seq } })).payload as Record<string, unknown>;
  }

  /** The turn ends as the runner reports it: something said, then the completion. */
  async function finish(sessionId: string, turnId: string, extra: Record<string, unknown> = {}) {
    await say(sessionId, turnId, RunEventType.ASSISTANT, { text: 'Done.' });
    await api.turnComplete({ id: runnerId } as never, sessionId, {
      turnId, status: SharedRunStatus.SUCCEEDED, subtype: 'success', numTurns: 1, costUsd: 0, ...extra,
    } as never);
  }

  const covered = new Set<keyof TurnCards>();
  /**
   * The assertion every case below makes. `turnId` is waiting in `sessionId`'s queue: it is read off
   * both views, handed to the runner — after the turn `ahead` of it, when there is one — read off the
   * active view again while handed out where that view keeps it (an executable turn is its accepted
   * row until its echo exists; a platform turn whose words were rendered at hand-out is not listed
   * once handed out), and echoed through the ingest. The queue view must carry exactly `field`, so a
   * turn that lost its card everywhere at once is not three absences agreeing; every other reading
   * must carry the same card fields, compared one by one.
   */
  async function assertSameCards(
    field: keyof TurnCards,
    sessionId: string,
    turnId: string,
    order: { ahead?: string; listedWhileHanded: boolean },
  ): Promise<void> {
    const queued = (await sessions.listQueuedTurns(ownerId, sessionId)).find((row) => row.turnId === turnId);
    assert.ok(queued, 'the queue view does not list the waiting turn');
    const expected = cardsOf(queued);
    assert.deepEqual(Object.keys(expected), [field], `the queue view does not list the turn as one ${field} card`);
    const active = (await sessions.listQueuedTurns(ownerId, sessionId, 'active')).find((row) => row.turnId === turnId);
    assert.ok(active, 'the active view does not list the waiting turn');
    const readings: Array<[string, object]> = [['the active view', active]];

    if (order.ahead) {
      const head = await deliver(sessionId);
      assert.equal(head.turnId, order.ahead, 'the turn ahead of it was not handed out first');
      await finish(sessionId, head.turnId);
    }
    const handed = await deliver(sessionId);
    assert.equal(handed.turnId, turnId, 'the runner was handed another turn');
    if (order.listedWhileHanded) {
      const accepted = (await sessions.listQueuedTurns(ownerId, sessionId, 'active')).find((row) => row.turnId === turnId);
      assert.ok(accepted, 'the active view lost the turn between hand-out and echo');
      readings.push(['the active view\'s accepted row', accepted]);
    }
    readings.push(['the echo', await say(sessionId, turnId, RunEventType.USER, { text: handed.content })]);

    for (const [where, carrier] of readings) {
      const cards = cardsOf(carrier);
      for (const each of FIELDS) {
        assert.deepEqual(cards[each], expected[each], `${each}: ${where} disagrees with the queue view`);
      }
    }
    covered.add(field);
  }

  // ── openItemDelivery ──────────────────────────────────────────────────────────────────────────

  await t.test('an exception item delivered to the coordinator (openItemDelivery)', async () => {
    const { projectId, coordinator } = await coordinatedProject('the project with a conflict');
    const taskId = await task('the task whose merge conflicted', { projectId, status: TaskStatus.IN_PROGRESS });
    const now = new Date();
    const item = await prisma.projectOpenItem.create({
      data: {
        projectId, ownerId, kind: 'INTEGRATION_CONFLICT', state: 'OPEN',
        assignee: 'COORDINATOR', assigneeReason: 'DEFAULT', taskId,
        dedupeKey: `IC:${randomUUID()}`, title: 'Merge conflict: the task whose merge conflicted',
        payload: { jobKind: 'LAND_TASK', phase: 'LAND_TASK', targetRef: 'refs/heads/main', files: ['src/a.ts', 'src/b.ts'] },
        waitingSince: now, assignedAt: now,
      },
      select: { id: true },
    });
    const ahead = await ownerSays(coordinator, 'the owner goes first');
    await openItems.deliver(item.id);
    const delivery = await turnKeyed(coordinator, OPEN_ITEM_TURN_PREFIX);
    await assertSameCards('openItemDelivery', coordinator, delivery.id, { ahead, listedWhileHanded: true });
  });

  // ── taskStart ─────────────────────────────────────────────────────────────────────────────────

  await t.test('the brief a run request hands a paused run (taskStart)', async () => {
    const taskId = await task('pick the parity run back up', {
      description: 'carry on from where the paused run stopped',
      acceptanceCriteria: 'the parity spec passes on an isolated database',
    });
    const run = await session('pick the parity run back up', { taskId, startsTaskWork: true });
    const ahead = await ownerSays(run, 'one thing before the brief');
    // What a run request delivers to a live paused run (`TasksService.applyWorkspaceRun`, through
    // `SessionsService.resume`, which hands a live run's turn to `createTurn`): the task's brief,
    // under the key its request names.
    const row = await prisma.task.findUniqueOrThrow({ where: { id: taskId }, include: { list: true } });
    const brief = await sessions.createTurn(ownerId, run, {
      clientTurnId: taskRunResumeTurnId(`batch:${randomUUID()}:${taskId}`, run),
      content: buildTaskExecutionPrompt(row),
    }, { startsTaskWork: true });
    await assertSameCards('taskStart', run, brief.turnId, { ahead, listedWhileHanded: true });
  });

  // ── projectStarted ────────────────────────────────────────────────────────────────────────────

  await t.test('a project start told to its coordinator (projectStarted)', async () => {
    const { projectId, coordinator } = await coordinatedProject('the project the owner started');
    // One task nothing starts but the coordinator: the card names it.
    await task('held for the coordinator', { projectId, autoRunWhenReady: false });
    const ahead = await ownerSays(coordinator, 'the owner goes first');
    const told = await tellCoordinatorProjectStarted(db, sessions, {
      ownerId, projectId, start: { by: 'SWITCH', configRevision: '2', at: new Date() },
    });
    assert.ok(told, 'the coordinator was not told');
    const started = await turnKeyed(coordinator, PROJECT_STARTED_TURN_PREFIX);
    await assertSameCards('projectStarted', coordinator, started.id, { ahead, listedWhileHanded: true });
  });

  // ── confirmationReviewRequest and confirmationReturn ──────────────────────────────────────────

  /** An OWNER_CONFIRMED task filed from a conversation of its own — which reviews it — and its run. */
  async function filedRun(title: string): Promise<{ taskId: string; run: string; reviewer: string }> {
    const reviewer = await session(`asked for: ${title}`, { startsTaskWork: false });
    const taskId = await task(title, {
      creatorSessionId: reviewer, completionCriterion: 'OWNER_CONFIRMED',
      acceptanceCriteria: `${title}: the work is on its branch.`, autoRunWhenReady: false,
    });
    const run = await session(title, { taskId, startsTaskWork: true, branch: `orbit/${taskId.slice(0, 8)}` });
    return { taskId, run, reviewer };
  }

  /** The run declares the work finished in a turn and stops: the request is asked, and its review
   *  handed to the reviewer. Answers the request's id. */
  async function declare(filed: { taskId: string; run: string }): Promise<string> {
    await ownerSays(filed.run, 'finish it');
    const { turnId } = await deliver(filed.run);
    await confirmationDoor.claim(runner, filed.taskId, filed.run);
    await finish(filed.run, turnId, { branchSha: SHA });
    const request = await prisma.taskOwnerConfirmationRequest.findFirstOrThrow({
      where: { taskId: filed.taskId },
      orderBy: [{ requestedAt: 'desc' }, { id: 'desc' }],
    });
    return request.id;
  }

  await t.test('a confirmation request handed to its reviewer (confirmationReviewRequest)', async () => {
    const filed = await filedRun('rename the parity invoices');
    await declare(filed);
    const review = await turnKeyed(filed.reviewer, OWNER_CONFIRMATION_REVIEW_TURN_KEY_PREFIX);
    await assertSameCards('confirmationReviewRequest', filed.reviewer, review.id, { listedWhileHanded: false });
  });

  await t.test('a reviewer\'s return handed to the run (confirmationReturn)', async () => {
    const filed = await filedRun('the parity run its reviewer sends back');
    const requestId = await declare(filed);
    // The reviewer is handed the review, and sends the work back in that turn.
    await deliver(filed.reviewer);
    const returned = await confirmationDoor.returnToRun(runner, filed.taskId, filed.reviewer, {
      requestId, reviewedSha: SHA, reason: 'The migration is missing from the branch.',
      problems: [{ text: 'no migration for the new column', evidenceRefs: ['git show --stat HEAD'] }],
    });
    const back = await turnKeyed(filed.run, CONFIRMATION_RETURN_TURN_KEY_PREFIX);
    assert.equal(back.clientTurnId, `${CONFIRMATION_RETURN_TURN_KEY_PREFIX}${returned.recordId}`);
    await assertSameCards('confirmationReturn', filed.run, back.id, { listedWhileHanded: false });
  });

  // ── sessionMessage ────────────────────────────────────────────────────────────────────────────

  await t.test('another session\'s message, naming the reply it asks for (sessionMessage)', async () => {
    const worker = await session('Worker: asks the parity question');
    const recipient = await session('a conversation with a queue');
    const ahead = await ownerSays(recipient, 'the owner goes first');
    await ask(worker, recipient, 'merge now, or wait for review?');
    const sent = await prisma.conversationTurn.findFirstOrThrow({ where: { sessionId: recipient, senderSessionId: worker } });
    await assertSameCards('sessionMessage', recipient, sent.id, { ahead, listedWhileHanded: true });
  });

  // ── sessionReplies ────────────────────────────────────────────────────────────────────────────

  await t.test('an outcome handed back on a reply turn (sessionReplies)', async () => {
    const asker = await session('Worker: waits for an answer');
    const recipient = await session('Coordinator: answers');
    const request = await ask(asker, recipient, 'go or no-go?');
    await deliver(recipient);
    const answered = await sendDoor.replyToRequest(
      runner, undefined, recipient, await orchestration.issue(runnerId, recipient), request.id, { message: 'go' } as never,
    );
    assert.equal(answered.handOff, 'QUEUED');
    const replyTurn = await turnKeyed(asker, SESSION_REPLY_TURN_PREFIX);
    await assertSameCards('sessionReplies', asker, replyTurn.id, { listedWhileHanded: false });
  });

  await t.test('an outcome riding on the next turn handed out, the owner\'s own: its accepted row carries the echo\'s cards', async () => {
    // Not a waiting turn's card: an outcome whose hand-off has not run yet joins whichever turn of the
    // asker is handed out next (`appendSessionRepliesContext`), so the turn becomes a reply card only
    // once handed out. Between hand-out and echo the active view's accepted row is what draws it, and
    // it must draw the cards the echo is stored with — not the owner's bare bubble.
    const asker = await session('Worker: answered before the hand-off ran');
    const recipient = await session('Coordinator: answers with no hand-off');
    const request = await ask(asker, recipient, 'ship it?');
    await deliver(recipient);
    const answered = await prisma.$transaction((tx) => replyToSessionRequest(tx, {
      ownerId, callerSessionId: recipient, requestId: request.id, reply: { message: 'ship it' },
    }));
    assert.equal(answered.ok, true);
    const own = await ownerSays(asker, 'what did the coordinator say?');
    const handed = await deliver(asker);
    assert.equal(handed.turnId, own);
    const accepted = (await sessions.listQueuedTurns(ownerId, asker, 'active')).find((row) => row.turnId === own);
    assert.ok(accepted, 'the active view lost the turn between hand-out and echo');
    const echoed = await say(asker, own, RunEventType.USER, { text: handed.content });
    const expected = cardsOf(echoed);
    assert.deepEqual(Object.keys(expected), ['sessionReplies'], 'the echo of the turn the outcome rode on is not a reply card');
    const cards = cardsOf(accepted);
    for (const each of FIELDS) {
      assert.deepEqual(cards[each], expected[each], `${each}: the active view's accepted row disagrees with the echo`);
    }
  });

  await t.test('every card a turn can carry has a case above', () => {
    assert.deepEqual([...covered].sort(), [...FIELDS].sort());
  });
});
