/**
 * The run a Wiki maintenance session is claimed with (contracts/wiki.contract.json `maintenance.run`,
 * wiki-maintenance-session.ts), against a real PostgreSQL, through the claim and the reclaim a runner makes:
 *
 *   1. only a maintenance session gets it — the provider and workspace its space's settings pin it to, no
 *      provider to fall back to, 120 model turns, sub-agents and the web disallowed, the clean start — and
 *      its agent config carries the same guardrails; an ordinary session, and a task session of any other
 *      list, get none of it;
 *   2. a runner that does not declare wiki-maintenance-run/v1 is never handed one, on the claim or the reclaim;
 *   3. the pin holds and nothing falls back: a provider turned off, deleted, on another runtime or an account
 *      pool, a session that names another provider or sits in another workspace, and maintenance turned off —
 *      each is claimed with its refusal and with no other provider's endpoint, and no pool member is chosen —
 *      while an ordinary session on a provider that cannot dispatch still waits, PENDING, and says why;
 *   4. the settings door takes only a provider on the Claude Code runtime, and `dailyRunLimit` — 8 by
 *      default, 1 to 48 — is what `wikiMaintenanceRunsToday` counts the day's runs against.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-maintenance-session.pg.spec.ts
 *
 * Not destructive: every id is generated by the run. Only the two credential checks are stood in for.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import { RunStatus, RunnerStatus, type PrismaClient } from '@prisma/client';
import {
  PermissionMode,
  WIKI_MAINTENANCE_RUN_V1,
  toUuid,
  type ClaimedSession,
  type ReclaimSession,
} from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { decideSessionSource } from '../projects/session-source';
import { encryptSecret } from '../providers/provider-crypto';
import type { PushService } from '../push/push.service';
import { QueueService } from '../queue/queue.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { PROVIDER_UNAVAILABLE_ERROR } from '../runner-api/runner-provider-support';
import { WikiController } from './wiki.controller';
import { wikiMaintenanceRunOf, wikiMaintenanceRunsToday } from './wiki-maintenance-session';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService } from './wiki.service';

process.env.PROVIDER_SECRET_KEY ??= 'wiki-maintenance-session-spec';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The contract's run, spelled out rather than imported from the module under test. */
const DISALLOWED = ['Task', 'Agent', 'WebFetch', 'WebSearch'];

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  queue: QueueService;
  runnerDoor: RunnerApiController;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, {} as unknown as PushService);

    @Module({
      controllers: [WikiController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiMaintenanceSessionModule {}

    const app = await NestFactory.create(WikiMaintenanceSessionModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');

    const realtime = { publishSessionUpdated: () => undefined, publishSessionCreated: () => undefined, notifyInbox: () => undefined };
    const queue = new QueueService(prisma as unknown as PrismaService, realtime as unknown as RealtimeService);
    const runnerDoor = new RunnerApiController(
      prisma as unknown as PrismaService,
      queue,
      realtime as unknown as RealtimeService,
      {} as never, {} as never, {} as never,
    );
    return { base: await app.getUrl(), sql, prisma, app, queue, runnerDoor, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

async function patch(h: Harness, bearer: string, spaceId: string, body: unknown): Promise<Answer> {
  const response = await fetch(`${h.base}/api/wiki/spaces/${spaceId}`, {
    method: 'PATCH',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${bearer}` },
    body: JSON.stringify(body),
  });
  const text = await response.text();
  return { status: response.status, body: text ? JSON.parse(text) : null };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 600)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

/** An owner, the runner their workspace runs on, and that workspace — with standing settings of its own. */
interface Owner {
  id: string;
  bearer: string;
  runnerId: string;
  workspaceId: string;
}

async function owner(h: Harness, name: string): Promise<Owner> {
  const id = randomUUID();
  await h.prisma.user.create({ data: { id, email: `wiki-maintenance-${id}@wiki.invalid`, name, passwordHash: 'x' } });
  h.bearers.set(`bearer-${id}`, id);
  const runnerId = randomUUID();
  await h.prisma.runner.create({
    data: {
      id: runnerId,
      name: `${name}'s machine`,
      ownerId: id,
      tokenHash: createHash('sha256').update(`runner-${runnerId}`).digest('hex'),
      status: RunnerStatus.ONLINE,
      maxConcurrent: 8,
    },
  });
  return { id, bearer: `bearer-${id}`, runnerId, workspaceId: await workspace(h, id, runnerId) };
}

/** A workspace on the runner, whose own settings a maintenance run must not inherit wholesale. */
async function workspace(h: Harness, ownerId: string, runnerId: string): Promise<string> {
  const id = randomUUID();
  await h.prisma.workspace.create({
    data: {
      id,
      ownerId,
      runnerId,
      name: `ws-${id.slice(0, 8)}`,
      enabled: true,
      workDir: '/tmp/wiki-maintenance-session',
      disallowedTools: ['Bash(rm -rf *)'],
      effort: 'high',
      env: { WORKSPACE_VAR: 'workspace-value' },
    },
  });
  return id;
}

/** A configured provider of the owner's: the local model on the Claude Code runtime, unless told otherwise. */
async function provider(h: Harness, ownerId: string, shape: { runtime?: string; enabled?: boolean } = {}): Promise<{ slug: string; key: string }> {
  const slug = `local-vllm-${randomUUID().slice(0, 8)}`;
  const key = `vllm-key-${randomUUID()}`;
  await h.prisma.modelProvider.create({
    data: {
      slug,
      label: 'Local vLLM',
      runtime: shape.runtime ?? 'claude',
      baseUrl: 'http://127.0.0.1:8000',
      apiKeyEnc: encryptSecret(key),
      models: [{ value: 'qwen3.8-27b-fp8', label: 'Qwen3.8 27B', contextWindow: 131072 }],
      defaultModel: 'qwen3.8-27b-fp8',
      enabled: shape.enabled ?? true,
      ownerId,
    },
  });
  return { slug, key };
}

/** A space of the owner's with its maintenance on, pinned to `slug` in the owner's workspace; and its list. */
async function maintainedSpace(h: Harness, who: Owner, slug: string): Promise<{ spaceId: string; listId: string }> {
  const made = await fetch(`${h.base}/api/wiki/spaces`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${who.bearer}` },
    body: JSON.stringify({ title: `A maintained space ${randomUUID().slice(0, 6)}` }),
  });
  assert.equal(made.status, 201, 'the owner creates a space');
  const spaceId = toUuid(((await made.json()) as { id: string }).id);
  const on = await patch(h, who.bearer, spaceId, { maintenance: { enabled: true, workspaceId: who.workspaceId, provider: slug } });
  expectStatus(on, 200, 'the owner turns maintenance on, pinned to the local model');
  return { spaceId, listId: toUuid(on.body.settings.maintenance.listId as string) };
}

async function task(h: Harness, who: Owner, listId: string | null, createdAt?: Date): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id",
                         "completion_criterion","created_at","updated_at")
     VALUES ($1,'Wiki maintenance run',$2,'USER',$2,'OPEN'::task_status,$3,$4,'OWNER_CONFIRMED',$5,now())`,
    [id, who.id, who.workspaceId, listId, (createdAt ?? new Date()).toISOString()],
  );
  return id;
}

/** A session queued on the owner's runner, created the way `SessionsService.create` creates one. */
async function queued(
  h: Harness,
  who: Owner,
  shape: { provider: string; taskId?: string | null; workspaceId?: string },
): Promise<string> {
  const decision = await decideSessionSource(h.prisma as unknown as PrismaService, null);
  const session = await h.prisma.session.create({
    data: {
      title: 'a session',
      prompt: 'pick this up',
      status: RunStatus.PENDING,
      ownerId: who.id,
      creatorId: who.id,
      workspaceId: shape.workspaceId ?? who.workspaceId,
      assignedRunnerId: who.runnerId,
      taskId: shape.taskId ?? null,
      provider: shape.provider,
      providerBuiltin: shape.provider === 'claude',
      ...decision.columns,
    },
    select: { id: true },
  });
  return session.id;
}

/** The claim this runner makes, and it must be of `sessionId`: the payload the runner is handed. */
async function claim(h: Harness, who: Owner, sessionId: string, capable = true): Promise<ClaimedSession> {
  const claimed = await h.queue.claimSessionForRunner({ id: who.runnerId }, 0, false, true, capable);
  assert.equal(claimed?.sessionId, sessionId, `the runner was handed ${claimed?.sessionId ?? 'nothing'}, not ${sessionId}`);
  return claimed!;
}

/** What a restarted runner is told of every session it hosts. */
async function reclaim(h: Harness, who: Owner, capable: boolean): Promise<Map<string, ReclaimSession>> {
  const answer = await h.runnerDoor.reclaim(
    { id: who.runnerId, ownerId: who.id },
    capable ? WIKI_MAINTENANCE_RUN_V1 : undefined,
    undefined,
  );
  return new Map(answer.sessions.map((session) => [toUuid(session.sessionId), session]));
}

/** An ordinary claim: nothing of a maintenance run in it. */
function assertOrdinary(job: ClaimedSession | ReclaimSession, why: string): void {
  assert.equal(job.wikiMaintenance, undefined, `${why}: carries a maintenance run`);
  assert.equal(job.agent.maxTurns, undefined, `${why}: carries a turn limit`);
  assert.deepEqual(job.agent.disallowedTools, ['Bash(rm -rf *)'], `${why}: its disallowed tools are not its workspace's`);
  assert.notEqual(job.agent.permissionMode, PermissionMode.DONT_ASK, `${why}: runs dontAsk`);
}

// ── 1. only a maintenance session gets the run ──────────────────────────────────────────────────

test('only a maintenance session is claimed with the run: pinned, 120 turns, no sub-agents or web, clean', { skip }, async () => {
  const h = await boot();
  const who = await owner(h, 'maintainer');
  const local = await provider(h, who.id);
  const { spaceId, listId } = await maintainedSpace(h, who, local.slug);

  // An ordinary session of the same workspace, and a task session of an ordinary list, first.
  const plain = await queued(h, who, { provider: 'claude' });
  assertOrdinary(await claim(h, who, plain), 'an ordinary session');
  const otherList = await h.prisma.taskList.create({ data: { ownerId: who.id, title: 'Chores' }, select: { id: true } });
  const chore = await queued(h, who, { provider: local.slug, taskId: await task(h, who, otherList.id) });
  assertOrdinary(await claim(h, who, chore), 'a task session of another list');

  const runId = await queued(h, who, { provider: local.slug, taskId: await task(h, who, listId) });
  const job = await claim(h, who, runId);
  assert.deepEqual(job.wikiMaintenance, {
    spaceId,
    workspaceId: who.workspaceId,
    provider: local.slug,
    providerFallbacks: [],
    maxTurns: 120,
    disallowedTools: DISALLOWED,
    cleanStart: true,
  }, 'the maintenance session is claimed with its run, and no refusal');
  // The guardrails are in the agent config too, where every runtime reads them.
  assert.equal(job.agent.maxTurns, 120);
  assert.deepEqual([...job.agent.disallowedTools].sort(), ['Bash(rm -rf *)', ...DISALLOWED].sort(),
    "the run's disallowed tools join the workspace's own");
  assert.equal(job.agent.permissionMode, PermissionMode.DONT_ASK, 'nobody is asked: what is not pre-approved is refused');
  assert.equal(job.agent.effort, undefined, "the workspace's effort does not reach it: it thinks only when told to");
  assert.equal(job.allowOrchestration, false, 'a maintenance run orchestrates nothing');
  // Pinned: the engine talks to the provider the settings name, with its key.
  assert.equal(job.provider, 'claude', 'on the Claude Code runtime');
  assert.equal(job.agent.model, 'qwen3.8-27b-fp8');
  assert.equal(job.agent.env?.ANTHROPIC_BASE_URL, 'http://127.0.0.1:8000');
  assert.equal(job.agent.env?.ANTHROPIC_AUTH_TOKEN, local.key);

  // The reclaim a restarted runner rebuilds it from carries the same run; the ordinary sessions, none.
  const back = await reclaim(h, who, true);
  assert.deepEqual(back.get(runId)?.wikiMaintenance, job.wikiMaintenance, 'the reclaim hands the run back');
  assert.equal(back.get(runId)?.agent.maxTurns, 120);
  assert.equal(back.get(runId)?.agent.permissionMode, PermissionMode.DONT_ASK);
  assert.equal(back.get(runId)?.allowOrchestration, false);
  assertOrdinary(back.get(plain)!, 'an ordinary session, reclaimed');
  assertOrdinary(back.get(chore)!, 'a task session of another list, reclaimed');
});

// ── 2. only a runner that knows the run ─────────────────────────────────────────────────────────

test('a runner that does not declare wiki-maintenance-run/v1 is never handed a maintenance session', { skip }, async () => {
  const h = await boot();
  const who = await owner(h, 'older runner');
  const local = await provider(h, who.id);
  const { listId } = await maintainedSpace(h, who, local.slug);
  const runId = await queued(h, who, { provider: local.slug, taskId: await task(h, who, listId) });

  const offered = await h.queue.claimSessionForRunner({ id: who.runnerId }, 0, false, true, false);
  assert.equal(offered, null, 'an older runner is not offered the row');
  const row = await h.prisma.session.findUniqueOrThrow({ where: { id: runId }, select: { status: true } });
  assert.equal(row.status, RunStatus.PENDING, 'the run waits for a runner that can start it clean');
  // An ordinary session of the same runner is still handed to it: only the maintenance row is withheld.
  const plain = await queued(h, who, { provider: 'claude' });
  assertOrdinary(await claim(h, who, plain, false), 'the ordinary session beside it');

  // A runner that declares it takes the run; a restarted one that does not is not handed it back.
  await claim(h, who, runId, true);
  const olderBack = await reclaim(h, who, false);
  assert.equal(olderBack.has(runId), false, 'the reclaim leaves the run out for a runner that cannot start it clean');
  assert.equal(olderBack.has(plain), true, 'and hands the ordinary session back as always');
  assert.equal((await reclaim(h, who, true)).has(runId), true);
});

// ── 3. pinned, and nothing falls back ───────────────────────────────────────────────────────────

test('the pin holds: a run its settings cannot carry is claimed with its refusal, and falls back to nothing', { skip }, async () => {
  const h = await boot();

  /** A maintenance run whose world `arrange` bends; the claim it gets, and its session. */
  async function refused(
    name: string,
    arrange: (h: Harness, who: Owner, pinned: { slug: string }, spaceId: string) => Promise<{ provider?: string; workspaceId?: string } | void>,
  ): Promise<{ job: ClaimedSession; runId: string }> {
    const who = await owner(h, name);
    const local = await provider(h, who.id);
    const { spaceId, listId } = await maintainedSpace(h, who, local.slug);
    const shape = (await arrange(h, who, local, spaceId)) ?? {};
    const runId = await queued(h, who, { provider: shape.provider ?? local.slug, taskId: await task(h, who, listId), workspaceId: shape.workspaceId });
    const job = await claim(h, who, runId);
    assert.ok(job.wikiMaintenance, `${name}: the run is a maintenance run`);
    assert.match(job.wikiMaintenance!.refusal ?? '', /^This Wiki maintenance run did not start: /u, `${name}: it carries no refusal`);
    assert.deepEqual(job.wikiMaintenance!.providerFallbacks, [], `${name}: a fallback was offered`);
    const { model } = await h.prisma.session.findUniqueOrThrow({ where: { id: runId }, select: { model: true } });
    assert.equal(model, null, `${name}: its row was given a model it never ran`);
    return { job, runId };
  }
  const settingsOf = (sql: Client, spaceId: string, maintenance: Record<string, unknown>) =>
    sql.query(`UPDATE "wiki_space" SET "settings" = jsonb_set("settings", '{maintenance}', "settings"->'maintenance' || $2::jsonb) WHERE "id" = $1`,
      [spaceId, JSON.stringify(maintenance)]);

  // The pinned provider turned off after it was pinned: no other provider's endpoint, and none of its own.
  const off = await refused('turned off', async (h, who, pinned) => {
    await h.prisma.modelProvider.update({ where: { slug: pinned.slug }, data: { enabled: false } });
  });
  assert.match(off.job.wikiMaintenance!.refusal!, /is turned off, and a Wiki maintenance run falls back to no other/u);
  assert.equal(off.job.agent.env?.ANTHROPIC_AUTH_TOKEN, undefined, 'a provider turned off hands out no key');

  // Deleted: the claim would otherwise dispatch it on the runner's own Claude login.
  const gone = await refused('deleted', async (h, who, pinned) => {
    await h.prisma.modelProvider.delete({ where: { slug: pinned.slug } });
  });
  assert.match(gone.job.wikiMaintenance!.refusal!, /no provider of this account is called 'local-vllm-[0-9a-f]{8}'/u);
  assert.equal(gone.job.agent.env?.ANTHROPIC_BASE_URL, undefined);

  // A session that names another provider than the pin, or sits in another workspace.
  const other = await refused('another provider', async () => ({ provider: 'claude' }));
  assert.match(other.job.wikiMaintenance!.refusal!, /pin, 'local-vllm-[0-9a-f]{8}', and this session names 'claude'/u);
  const elsewhere = await refused('another workspace', async (h, who) => ({ workspaceId: await workspace(h, who.id, who.runnerId) }));
  assert.match(elsewhere.job.wikiMaintenance!.refusal!, /only in the workspace its space's maintenance settings name/u);

  // Maintenance turned off after the run was made.
  const disabled = await refused('maintenance off', async (h, who, _pinned, spaceId) => {
    await settingsOf(h.sql, spaceId, { enabled: false });
  });
  assert.match(disabled.job.wikiMaintenance!.refusal!, /maintenance is off in its space/u);

  // A pin the settings door would have refused, written behind it: another runtime, and an account pool.
  const codex = await refused('codex runtime', async (h, who, _pinned, spaceId) => {
    const onCodex = await provider(h, who.id, { runtime: 'codex' });
    await settingsOf(h.sql, spaceId, { provider: onCodex.slug });
    return { provider: onCodex.slug };
  });
  assert.match(codex.job.wikiMaintenance!.refusal!, /runs on the codex runtime, and a Wiki maintenance run takes a provider on the Claude Code runtime only/u);
  const pooled = await refused('account pool', async (h, who, _pinned, spaceId) => {
    const pool = await h.prisma.providerPool.create({ data: { slug: `pool-${randomUUID().slice(0, 8)}`, label: 'Pool', ownerId: who.id } });
    const member = await h.prisma.modelProvider.create({
      data: {
        slug: `pool-member-${randomUUID().slice(0, 8)}`, label: 'A sign-in', runtime: 'claude',
        baseUrl: 'https://api.anthropic.com', apiKeyEnc: encryptSecret('sk-ant-oat01-x'), ownerId: who.id,
      },
    });
    await h.prisma.providerPoolMember.create({ data: { poolId: pool.id, providerId: member.id, ownerId: who.id } });
    await settingsOf(h.sql, spaceId, { provider: pool.slug });
    return { provider: pool.slug };
  });
  assert.match(pooled.job.wikiMaintenance!.refusal!, /is an account pool/u);
  assert.equal(pooled.job.agent.env?.ANTHROPIC_AUTH_TOKEN, undefined, "no pool member's key was handed out");
  const pooledRow = await h.prisma.session.findUniqueOrThrow({ where: { id: pooled.runId }, select: { poolMemberProviderId: true } });
  assert.equal(pooledRow.poolMemberProviderId, null, 'no pool member was chosen for it');

  // Claimed with its refusal is the maintenance run's alone. An ordinary session — or a task session of another
  // list — on a provider turned off, deleted, or on a runtime no runner has is still not handed to this runner,
  // which declares wiki-maintenance-run/v1, and says why: PENDING, with PROVIDER_UNAVAILABLE_ERROR.
  const plain = await owner(h, 'ordinary');
  const offRow = await provider(h, plain.id, { enabled: false });
  const oddRuntime = await provider(h, plain.id, { runtime: 'unknown-runtime' });
  const chores = await h.prisma.taskList.create({ data: { ownerId: plain.id, title: 'Chores' }, select: { id: true } });
  for (const [slug, taskId] of [
    [offRow.slug, null],
    [offRow.slug, await task(h, plain, chores.id)],
    [`local-vllm-${randomUUID().slice(0, 8)}`, null],
    [oddRuntime.slug, null],
  ] as const) {
    const id = await queued(h, plain, { provider: slug, taskId });
    const offered = await h.queue.claimSessionForRunner({ id: plain.runnerId }, 0, false, true, true);
    assert.equal(offered, null, `an ordinary session on ${slug} was handed out`);
    assert.deepEqual(await h.prisma.session.findUniqueOrThrow({ where: { id }, select: { status: true, error: true } }),
      { status: RunStatus.PENDING, error: PROVIDER_UNAVAILABLE_ERROR }, `an ordinary session on ${slug}`);
  }
});

// The settings' key on another engine is not that run: a run's clean start and its disallowed tools hold
// on Claude Code alone (docs/provider-engine-contract.md §3.5), whatever else the key runs.
test('T3 a maintenance run on its pinned key starts only on Claude Code, whatever else that key runs', { skip }, async () => {
  const h = await boot();
  const who = await owner(h, 'other-engine');
  const local = await provider(h, who.id);
  const { listId } = await maintainedSpace(h, who, local.slug);
  const runOf = async (id: string) =>
    wikiMaintenanceRunOf(h.prisma as never, await h.prisma.session.findUniqueOrThrow({ where: { id } }));

  // On Claude Code, recorded or from before engines were: it starts.
  const onClaude = await queued(h, who, { provider: local.slug, taskId: await task(h, who, listId) });
  assert.equal((await runOf(onClaude))?.refusal, undefined);
  await h.prisma.session.update({ where: { id: onClaude }, data: { engine: 'claude' } });
  assert.equal((await runOf(onClaude))?.refusal, undefined);
  // The same key on OpenCode, which runs it too: refused, for the engine.
  const onOpenCode = await queued(h, who, { provider: local.slug, taskId: await task(h, who, listId) });
  await h.prisma.session.update({ where: { id: onOpenCode }, data: { engine: 'opencode' } });
  assert.equal((await runOf(onOpenCode))?.refusal,
    'This Wiki maintenance run did not start: it runs only on Claude Code, and this session runs on OpenCode.');
});

// ── 4. the settings door ────────────────────────────────────────────────────────────────────────

test('the settings door pins only a Claude Code provider, and dailyRunLimit is 8, within 1 to 48, counted per UTC day', { skip }, async () => {
  const h = await boot();
  const who = await owner(h, 'settings');
  const local = await provider(h, who.id);
  const { spaceId, listId } = await maintainedSpace(h, who, local.slug);

  // A provider no maintenance run could start on is refused where the owner names it, and says why.
  const onCodex = await provider(h, who.id, { runtime: 'codex' });
  const pool = await h.prisma.providerPool.create({ data: { slug: `pool-${randomUUID().slice(0, 8)}`, label: 'Pool', ownerId: who.id } });
  for (const [slug, why] of [
    ['codex', /'codex' runs on the codex runtime/u],
    ['claude', /'claude' is this machine's own Claude Code sign-in, which a clean start cannot use/u],
    [onCodex.slug, /runs on the codex runtime/u],
    [pool.slug, /is an account pool/u],
  ] as const) {
    const answer = await patch(h, who.bearer, spaceId, { maintenance: { provider: slug } });
    expectStatus(answer, 400, `maintenance pinned to ${slug}`);
    assert.match(String(answer.body.message), why, `${slug}: ${JSON.stringify(answer.body)}`);
  }
  // A name no provider has yet is taken — the claim refuses a run that finds it still missing — and so is
  // a configured provider on the Claude Code runtime.
  expectStatus(await patch(h, who.bearer, spaceId, { maintenance: { provider: 'configured-later' } }), 200, 'a name to configure next');
  const back = await patch(h, who.bearer, spaceId, { maintenance: { provider: local.slug } });
  expectStatus(back, 200, 'the local model on the Claude Code runtime');
  assert.equal(back.body.settings.maintenance.provider, local.slug);

  // Eight runs a day by default; one to forty-eight may be set; nothing else.
  assert.equal(back.body.settings.maintenance.dailyRunLimit, 8, 'eight a day by default');
  for (const limit of [1, 48]) {
    const set = await patch(h, who.bearer, spaceId, { maintenance: { dailyRunLimit: limit } });
    expectStatus(set, 200, `dailyRunLimit ${limit}`);
    assert.equal(set.body.settings.maintenance.dailyRunLimit, limit);
  }
  for (const limit of [0, 49, 2.5, '12', -1]) {
    expectStatus(await patch(h, who.bearer, spaceId, { maintenance: { dailyRunLimit: limit } }), 400, `dailyRunLimit ${JSON.stringify(limit)}`);
  }
  const stored = await h.sql.query<{ settings: { maintenance: Record<string, unknown> } }>(
    `SELECT "settings" FROM "wiki_space" WHERE "id" = $1`, [spaceId]);
  assert.equal(stored.rows[0].settings.maintenance.dailyRunLimit, 48, 'a refused value wrote nothing');
  assert.equal('dailyTokenBudget' in stored.rows[0].settings.maintenance, false, 'the token budget is gone');

  // The day's runs: the tasks of the maintenance list made since midnight UTC, however they ended — not
  // yesterday's, and not another list's.
  expectStatus(await patch(h, who.bearer, spaceId, { maintenance: { dailyRunLimit: 3 } }), 200, 'three a day');
  const now = new Date();
  const midnight = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  assert.deepEqual(await wikiMaintenanceRunsToday(h.prisma, who.id, spaceId, now), {
    limit: 3, used: 0, remaining: 3, since: midnight.toISOString(),
  });
  await task(h, who, listId, new Date(midnight.getTime() - 60_000));
  await task(h, who, listId, new Date(midnight.getTime() + 1_000));
  const done = await task(h, who, listId);
  await h.sql.query(`UPDATE "task" SET "status" = 'CANCELLED'::task_status WHERE "id" = $1`, [done]);
  await task(h, who, (await h.prisma.taskList.create({ data: { ownerId: who.id, title: 'Chores' } })).id);
  assert.deepEqual(await wikiMaintenanceRunsToday(h.prisma, who.id, spaceId, now), {
    limit: 3, used: 2, remaining: 1, since: midnight.toISOString(),
  }, "two of today's runs count, whatever became of them");
  await task(h, who, listId);
  await task(h, who, listId);
  assert.equal((await wikiMaintenanceRunsToday(h.prisma, who.id, spaceId, now)).remaining, 0, 'past the limit is none left, not less');
  await assert.rejects(wikiMaintenanceRunsToday(h.prisma, (await owner(h, 'stranger')).id, spaceId, now), /no such wiki space/u,
    "another owner's space is not found");
});
