/**
 * A space's review mode — Manual, Tiered, Automatic — over real HTTP and against a real PostgreSQL
 * (criterion 7 of the wiki's phase 2; contracts/wiki.contract.json `reviewModes`).
 *
 * The four things the criterion's verification names are four cases here, each read back from the
 * database and from the push the way a session would be handed it:
 *
 *   1. three modes × six kinds × three kinds of source (the owner's own words, a machine
 *      verification, an agent's say-so alone), cell by cell: what took effect, with which trust, and
 *      whether the next session is pushed it — in Automatic, nothing before its verdict, and what a
 *      supported verdict applies after it (revision 3; `wiki-verify.pg.spec.ts` takes the verdicts
 *      one by one);
 *   2. each of the five floors, in Automatic, with a counter-example that is not let through;
 *   3. Tiered's spot checks drawn by fact, a reject rate over the line sending the space back to
 *      Manual, and the owner told once — not again on the next rejection;
 *   4. a whole run reverted, and every entry it touched out of the push.
 *
 * Around them, what those four rest on: who may switch a mode (the owner's JWT, never a session), a
 * new space Tiered and an old one Manual, the owner's Reject of one entry, and the one-off import
 * the preview space is loaded with — origin import, authored by the system, bare record ids for
 * sources, an idempotency key that keeps a replay from writing twice, and thirty ops a changeset.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-review-mode.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in `wiki-api.pg.spec.ts`; the push is
 * the real `appendWikiContext`, and the owner's notification a stand-in that records each call.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { Prisma, PrismaClient } from '@prisma/client';
import { KIND_SPECS, WIKI_KINDS, WIKI_LIMITS, WIKI_REVIEW_RULES, toUuid, type WikiKind } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import type { RealtimeService } from '../realtime/realtime.service';
import { WikiController } from './wiki.controller';
import { appendWikiContext } from './wiki-push';
import { WikiRetrieval } from './wiki-retrieval';
import { isSpotCheckDraw, WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The push as a session starting now would be handed it: the wiki on, whatever this shell says. */
const WIKI_ON = { mode: 'on' as const, canaryOwners: new Set<string>(), problems: [] };

type Mode = 'manual' | 'tiered' | 'automatic';

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  bearers: Map<string, string>;
  /** Every notification the owner was sent that a space went back to Manual, in order. */
  notified: Array<{ ownerId: string; spaceId: string; rejected: number; window: number }>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const notified: Harness['notified'] = [];
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = {
      notifyWikiReviewModeTripped: async (input: Harness['notified'][number]) => {
        notified.push({ ownerId: input.ownerId, spaceId: input.spaceId, rejected: input.rejected, window: input.window });
      },
    } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);

    @Module({
      controllers: [WikiController, RunnerWikiController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiReviewModeModule {}

    const app = await NestFactory.create(WikiReviewModeModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, bearers, notified };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  headers?: Record<string, string>;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json', ...(who.headers ?? {}) };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

interface Outcome {
  seq: number;
  status: 'pending' | 'applied' | 'conflict' | 'refused';
  opId?: string | null;
  entryId?: string | null;
  waitsFor?: string;
  reasons?: Array<{ code: string; message: string }>;
  similar?: Array<{ id: string; rejectedReason?: string }>;
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-review-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return token;
}

async function runnerId(h: Harness, token: string): Promise<string> {
  const row = await h.sql.query<{ id: string }>(`SELECT "id" FROM "runner" WHERE "token_hash" = $1`, [
    createHash('sha256').update(token).digest('hex'),
  ]);
  return row.rows[0].id;
}

async function workspace(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id") VALUES ($1,'spec',$2)`, [id, ownerId]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string | null, machine: string | null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "dispatch_origin","updated_at")
     VALUES ($1,'a wiki session','p',$2,$2,$3,$4,'USER',now())`,
    [id, ownerId, workspaceId, machine ? await runnerId(h, machine) : null],
  );
  return id;
}

/**
 * A message the owner sent from the web: the user door files it with a routing intent under a
 * random client key. What the runner door files — an agent's or a coordinator's send — has no intent.
 */
async function turn(
  h: Harness,
  sessionId: string,
  content: string,
  shape: { sendIntent: string | null; clientTurnId?: string } = { sendIntent: 'NEXT_TURN' },
): Promise<string> {
  const id = randomUUID();
  const seq = (await h.sql.query<{ n: number }>(
    `SELECT COALESCE(MAX("seq"), 0)::int + 1 AS n FROM "conversation_turn" WHERE "session_id" = $1`,
    [sessionId],
  )).rows[0].n;
  await h.sql.query(
    `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status","kind","send_intent")
     VALUES ($1,$2,$3,$4,$5,'ANSWERED','message',$6)`,
    [id, sessionId, seq, shape.clientTurnId ?? randomUUID(), content, shape.sendIntent],
  );
  return id;
}

async function toolCall(h: Harness, sessionId: string, name: string, output: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","output") VALUES ($1,$2,$3,$4)`, [
    id,
    sessionId,
    name,
    JSON.stringify(output),
  ]);
  return id;
}

/** A space the owner makes through the door and puts in a mode, bound to a workspace when one is named. */
async function modeSpace(h: Harness, owner: Account, mode: Mode, workspaceId?: string): Promise<string> {
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: `A ${mode} space` });
  expectStatus(made, 201, 'the owner creates a space');
  const id = made.body.id as string;
  const switched = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${id}`, { reviewMode: mode });
  expectStatus(switched, 200, `the owner puts the space in ${mode}`);
  assert.equal(switched.body.settings.reviewMode, mode);
  if (workspaceId) {
    const bound = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${id}/workspaces`, { workspaceId });
    expectStatus(bound, 200, 'the owner binds the workspace');
  }
  return toUuid(id);
}

/** A valid draft of each kind (the contract's own vectors, retitled per use). */
function draft(kind: WikiKind, title: string, summary = `What the space knows about ${title.toLowerCase()}.`): Record<string, unknown> {
  const fields: Record<WikiKind, Record<string, unknown>> = {
    principle: { statement: 'When a record is deleted, every quote taken from it goes too.', rationale: 'Owners delete to forget.' },
    convention: { rule: 'Model a closed set as TEXT plus a CHECK constraint.', scope: ['src/apiserver/prisma/migrations/**'] },
    decision: {
      context: 'People ask what is true now.',
      decision: 'Store atomic entries and project every page from them.',
      alternatives: [{ option: 'A page-shaped wiki', whyRejected: 'Whole-page rewrites collapse.' }],
      consequences: 'Every view can be rebuilt.',
      decidedAt: '2026-09-26',
    },
    pitfall: {
      trigger: { paths: ['src/apiserver/src/wiki/'], commands: ['node --test build/wiki/x.pg.spec.js'] },
      symptom: 'A green run that witnessed no assertion.',
      cause: 'A pg spec skips itself without a database.',
      fix: 'Run it through scripts/run-pg-spec.sh.',
    },
    recipe: {
      steps: ['bash scripts/worktree-overlay.sh', 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-schema.pg.spec.ts'],
      verify: { command: 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-schema.pg.spec.ts', expectedExit: 0 },
    },
    concept: { definition: 'One owner\'s knowledge about one codebase.', boundaries: 'A space never spans owners.' },
  };
  return { kind, title, summary, fields: fields[kind] };
}

/**
 * An entry a review mode applied earlier, as the anchor re-verification left it: live, machine
 * trust, its anchor checked `verified`. Written directly — the anchor re-verification that would
 * write the check is criterion 4's — in the shape 0307's CHECKs ask (status and trust agree, no
 * successor, no retirement), with the revision and the source `applyOp` would have written.
 */
async function machineEntry(
  h: Harness,
  ownerId: string,
  spaceId: string,
  kind: WikiKind,
  title: string,
  shape: { trust?: 'auto' | 'unreviewed'; anchorState?: string; sourceSession: string },
): Promise<string> {
  const id = randomUUID();
  const body = draft(kind, title);
  const anchors = JSON.stringify([{ type: 'path', path: 'src/apiserver/src/wiki/wiki.service.ts' }]);
  await h.sql.query(
    `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary",
                               "fields","anchors","anchor_state")
     VALUES ($1,$2,$3,$4,'active',$5,1,$6,$7,$8,$9,$10)`,
    [id, ownerId, spaceId, kind, shape.trust ?? 'unreviewed', body.title, body.summary, JSON.stringify(body.fields),
      anchors, shape.anchorState ?? 'verified'],
  );
  const revision = randomUUID();
  await h.sql.query(
    `INSERT INTO "wiki_entry_revision"("id","entry_id","owner_id","revision","title","summary","fields","anchors",
                                        "content_sha256","author_kind")
     VALUES ($1,$2,$3,1,$4,$5,$6,$7,$8,'agent')`,
    [revision, id, ownerId, body.title, body.summary, JSON.stringify(body.fields), anchors, 'b'.repeat(64)],
  );
  await h.sql.query(
    `INSERT INTO "wiki_source"("id","revision_id","owner_id","kind","ref") VALUES ($1,$2,$3,'turn',$4)`,
    [randomUUID(), revision, ownerId, shape.sourceSession],
  );
  return id;
}

/** `count` active entries, written directly: what the circuit breaker measures a changeset against. */
async function activeEntries(h: Harness, ownerId: string, spaceId: string, count: number): Promise<void> {
  for (let n = 0; n < count; n += 1) {
    await h.sql.query(
      `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields")
       VALUES ($1,$2,$3,'concept','active','auto',1,$4,'Already in the space before this changeset.','{}')`,
      [randomUUID(), ownerId, spaceId, `Standing entry number ${n + 1}`],
    );
  }
}

/** The principal a one-off import in the API server's container runs as (reviewModes.import). */
function importer(ownerId: string): WikiPrincipal {
  return { origin: 'import', ownerId, userId: null, sessionId: null, toolCallId: null, authorKind: 'system' };
}

/** `count` adds of distinct concepts, each citing a record by its bare id: no quote. */
function importOps(count: number, cite: string, prefix: string): Array<Record<string, unknown>> {
  return Array.from({ length: count }, (_unused, n) => ({
    op: 'add',
    entry: draft('concept', `${prefix} concept ${n + 1} ${randomUUID().slice(0, 8)}`),
    sources: [{ kind: 'tool_call', ref: cite }],
  }));
}

async function entryRow(h: Harness, id: string) {
  return h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(id) } });
}

/** An agent's session as the runner door's report of its verdicts names it. */
function agent(ownerId: string, sessionId: string): WikiPrincipal {
  return { origin: 'agent', ownerId, userId: null, sessionId, toolCallId: null };
}

/**
 * Every op among `outcomes` that waits for its verification, found supported by its proposer — the
 * verdict that applies an Automatic space's op as Auto (contract `reviewModes.verification`).
 */
async function verifyAll(h: Harness, proposer: WikiPrincipal, spaceId: string, outcomes: readonly Outcome[]): Promise<void> {
  const waiting = outcomes.filter((outcome) => outcome.status === 'pending' && outcome.waitsFor === 'verification');
  for (let at = 0; at < waiting.length; at += WIKI_LIMITS.opsPerChangeset) {
    const verdicts = waiting.slice(at, at + WIKI_LIMITS.opsPerChangeset).map((outcome) => ({
      opId: outcome.opId!, verdict: 'supported', reason: 'The cited record says so.', model: 'qwen3.8-27b-fp8',
    }));
    const done = await h.service.recordVerifications(proposer, spaceId, verdicts);
    for (const outcome of done.outcomes) assert.equal(outcome.status, 'applied', JSON.stringify(outcome));
  }
}

/** The entries the next session in this workspace is handed, by id. */
async function pushed(h: Harness, ownerId: string, workspaceId: string, sessionId: string): Promise<Set<string>> {
  const content = await appendWikiContext(h.prisma as unknown as Prisma.TransactionClient, {
    sessionId,
    turnId: randomUUID(),
    leaseGeneration: randomUUID(),
    ownerId,
    workspaceId,
    taskId: null,
    task: null,
    dispatchOrigin: 'USER',
    content: 'What should I know about this codebase?',
  }, WIKI_ON);
  return new Set([...String(content).matchAll(/\(orbit-wiki:([0-9A-Za-z]+)\)/gu)].map((match) => toUuid(match[1])));
}

// ── the switch ──────────────────────────────────────────────────────────────────────────────────

test('review modes · who switches a mode, and what a space starts in', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test('a new space is Tiered, and one made before review modes reads as Manual', async () => {
    const owner = await account(h, 'defaults');
    const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: 'Made today' });
    expectStatus(made, 201, 'the owner creates a space');
    assert.equal(made.body.settings.reviewMode, 'tiered', 'a space made now is Tiered (criterion 7\'s default)');
    const stored = await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: toUuid(made.body.id) } });
    assert.equal((stored.settings as { reviewMode?: string }).reviewMode, 'tiered', 'and it is written so, not inferred');

    // A space as phase 1 left it: settings without the key. It stays Manual until its owner chooses.
    const old = randomUUID();
    await h.sql.query(`INSERT INTO "wiki_space"("id","owner_id","slug","title","settings") VALUES ($1,$2,'phase-one','Phase one','{"push":true}')`, [
      old,
      owner.id,
    ]);
    const read = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${old}`);
    expectStatus(read, 200, 'the owner reads the old space');
    assert.equal(read.body.settings.reviewMode, 'manual');
    const listed = await call(h, { bearer: owner.bearer }, 'GET', '/wiki/spaces');
    const modes = new Map((listed.body as Array<{ id: string; settings: { reviewMode: string } }>).map((s) => [toUuid(s.id), s.settings.reviewMode]));
    assert.equal(modes.get(old), 'manual');
    assert.equal(modes.get(toUuid(made.body.id)), 'tiered');
  });

  await t.test('only the owner channel switches it: a session header is refused, whatever the session', async () => {
    const owner = await account(h, 'switch');
    const ws = await workspace(h, owner.id);
    const machine = await runner(h, owner.id);
    const mine = await session(h, owner.id, ws, machine);
    const space = await modeSpace(h, owner, 'tiered');

    const refused = await call(h, { bearer: owner.bearer, headers: { 'x-orbit-session-id': mine } }, 'PATCH', `/wiki/spaces/${space}`, {
      reviewMode: 'automatic',
    });
    expectStatus(refused, 403, 'a switch carrying a session header');
    assert.equal(refused.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
    // Any header of the family, not only the session id: an orchestration token is a session's too.
    const token = await call(h, { bearer: owner.bearer, headers: { 'x-orbit-session-token': 'tok' } }, 'PATCH', `/wiki/spaces/${space}`, {
      reviewMode: 'manual',
    });
    expectStatus(token, 403, 'a switch carrying a session token');
    const unchanged = await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: space } });
    assert.equal((unchanged.settings as { reviewMode: string }).reviewMode, 'tiered', 'a refused switch wrote nothing');

    // The other settings are not the owner channel's alone, as in phase 1.
    const push = await call(h, { bearer: owner.bearer, headers: { 'x-orbit-session-id': mine } }, 'PATCH', `/wiki/spaces/${space}`, {
      push: false,
    });
    expectStatus(push, 200, 'a push toggle carrying a session header');

    expectStatus(await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${space}`, { reviewMode: 'sometimes' }), 400, 'a mode that is not one');

    const switched = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${space}`, { reviewMode: 'automatic' });
    expectStatus(switched, 200, 'the owner switches the mode');
    assert.equal(switched.body.settings.reviewMode, 'automatic');
    assert.equal(switched.body.settings.reviewModeChangedBy, 'owner');
    assert.ok(Date.parse(switched.body.settings.reviewModeChangedAt) > Date.now() - 60_000, 'and when');
    assert.equal(switched.body.settings.push, false, 'another setting survives the switch');

    // The runner door has no way to reach the setting at all.
    const runnerDoor = await call(h, { runner: machine, headers: { 'x-orbit-session-id': mine } }, 'PATCH', `/runner/wiki/spaces/${space}`, {
      reviewMode: 'manual',
    });
    assert.equal(runnerDoor.status, 404, 'the runner door serves no settings route');
  });
});

// ── 1. the matrix ───────────────────────────────────────────────────────────────────────────────

/**
 * Criterion 7's first assertion: every mode, every kind, every kind of source.
 *
 * - The owner's own words: an add citing a message the owner sent from the web, quoted verbatim.
 * - A machine verification: the next amend of an entry a mode applied before, whose anchors the
 *   re-verification found `verified`, citing records from two independent sessions and leaving the
 *   anchors alone. (A new entry's anchors are unchecked, so an add is never machine-verified.)
 * - An agent's say-so alone: an add citing the agent's own tool output.
 *
 * Each cell says what took effect (`pending`, applied `auto`, applied `unreviewed`, or the refusal
 * code), and whether a session starting next in the space's workspace is pushed it. An Automatic cell
 * takes effect only through its verdict (revision 3): before one, it waits and nothing of it is
 * pushed; a supported verdict applies it as `auto`, which is the cell's effect.
 */
type Source = 'owner_words' | 'machine_verified' | 'agent_alone';
type Cell = { effect: 'pending' } | { effect: 'applied'; trust: 'auto' | 'unreviewed' } | { effect: 'refused'; code: string };

function expected(mode: Mode, kind: WikiKind, source: Source): Cell {
  // Floor one, in every mode: a principle is the owner's to write.
  if (kind === 'principle') return { effect: 'refused', code: 'WIKI_KIND_OWNER_ONLY' };
  // The machine-verified op is an amend, and a decision is only ever superseded.
  if (source === 'machine_verified' && !KIND_SPECS[kind].amendable) return { effect: 'refused', code: 'WIKI_SCHEMA' };
  if (mode === 'manual') return { effect: 'pending' };
  // Once its verdict says supported: before it, the op waits for its verification (asserted apart).
  if (mode === 'automatic') return { effect: 'applied', trust: 'auto' };
  const auto =
    (source === 'owner_words' && (kind === 'decision' || kind === 'convention'))
    // A recipe is machine-verified by a green re-run of its verify command, which nothing reports yet.
    || (source === 'machine_verified' && kind === 'pitfall');
  return { effect: 'applied', trust: auto ? 'auto' : 'unreviewed' };
}

test('review modes · three modes × six kinds × three sources, cell by cell', { skip, concurrency: 1, timeout: 600_000 }, async () => {
  const h = await boot();
  const table: string[] = [];
  for (const mode of ['manual', 'tiered', 'automatic'] as const) {
    const owner = await account(h, `matrix ${mode}`);
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id);
    const space = await modeSpace(h, owner, mode, ws);
    // Where the cited records live: the owner's conversation, and two agent sessions of their own.
    const talk = await session(h, owner.id, ws, machine);
    const said = 'We decided: a closed set is a TEXT column with a CHECK constraint, never an enum type.';
    const ownerTurn = await turn(h, talk, said);
    const first = await session(h, owner.id, ws, machine);
    const second = await session(h, owner.id, ws, machine);
    const firstCall = await toolCall(h, first, 'Bash', 'node --test build/wiki/x.pg.spec.js exited 0 with every case skipped');
    const secondCall = await toolCall(h, second, 'Bash', 'the same spec skipped every case again in a second session');

    const cells: Array<{ kind: WikiKind; source: Source; outcome: Outcome; entryId: string | null; proposer: string }> = [];
    for (const kind of WIKI_KINDS) {
      for (const source of ['owner_words', 'machine_verified', 'agent_alone'] as const) {
        // One session per cell: in Manual every op here waits, and a session's quota counts those.
        const proposer = await session(h, owner.id, ws, machine);
        const title = `${mode} ${kind} from ${source.replace('_', ' ')}`;
        let op: Record<string, unknown>;
        if (source === 'owner_words') {
          op = { op: 'add', entry: draft(kind, title), sources: [{ kind: 'turn', ref: ownerTurn, quote: 'a closed set is a TEXT column with a CHECK constraint' }] };
        } else if (source === 'agent_alone') {
          const own = await toolCall(h, proposer, 'Bash', `what this session saw about ${title}`);
          op = { op: 'add', entry: draft(kind, title), sources: [{ kind: 'tool_call', ref: own, quote: `what this session saw about ${title}` }] };
        } else {
          const target = await machineEntry(h, owner.id, space, kind, title, { sourceSession: first });
          op = {
            op: 'amend',
            entryId: target,
            baseRevision: 1,
            changes: { summary: `A sharper summary of ${title.toLowerCase()}, checked twice.` },
            sources: [
              { kind: 'tool_call', ref: firstCall, quote: 'exited 0 with every case skipped' },
              { kind: 'tool_call', ref: secondCall, quote: 'skipped every case again' },
            ],
          };
        }
        const answer = await call(h, { runner: machine, headers: { 'x-orbit-session-id': proposer } }, 'POST', '/runner/wiki/changesets', {
          rationale: `the ${source} cell for a ${kind}`,
          ops: [op],
        });
        const outcome = answer.body.ops?.[0] as Outcome;
        assert.ok(outcome, `${mode}/${kind}/${source}: no outcome in ${JSON.stringify(answer.body)}`);
        const entryId = outcome.entryId ? toUuid(outcome.entryId) : (op.entryId as string | undefined) ?? null;
        cells.push({ kind, source, outcome, entryId, proposer });
      }
    }

    if (mode === 'automatic') {
      // Before any verdict: every cell the mode took waits for its verification, nothing of it is
      // live, and nothing of it is pushed. Then each proposer reports its op supported.
      const before = await pushed(h, owner.id, ws, await session(h, owner.id, ws, machine));
      for (const { kind, source, outcome, entryId, proposer } of cells) {
        if (expected(mode, kind, source).effect === 'refused') continue;
        const label: string = `automatic × ${kind} × ${source}, before its verdict`;
        assert.equal(outcome.status, 'pending', `${label}: ${JSON.stringify(outcome)}`);
        assert.equal(outcome.waitsFor, 'verification', label);
        const op = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: toUuid(outcome.opId!) } });
        assert.equal(op.decision, 'verifying', label);
        const entry = await entryRow(h, entryId!);
        if (source === 'machine_verified') assert.equal(entry.currentRevision, 1, `${label}: an amend wrote a revision`);
        else assert.equal(entry.status, 'proposed', label);
        assert.equal(before.has(entryId!), false, `${label}: pushed`);
        await verifyAll(h, agent(owner.id, proposer), space, [outcome]);
      }
    }

    const handed = await pushed(h, owner.id, ws, await session(h, owner.id, ws, machine));
    for (const { kind, source, outcome, entryId } of cells) {
      const want = expected(mode, kind, source);
      const where = `${mode} × ${kind} × ${source}`;
      if (want.effect === 'refused') {
        assert.equal(outcome.status, 'refused', `${where}: ${JSON.stringify(outcome)}`);
        assert.equal(outcome.reasons?.[0]?.code, want.code, `${where}: refused for the wrong reason`);
        table.push(`${where}: refused ${want.code}`);
        continue;
      }
      // An Automatic cell answered pending when it was proposed, and its verdict applied it since.
      assert.equal(outcome.status, mode === 'automatic' ? 'pending' : want.effect, `${where}: ${JSON.stringify(outcome)}`);
      const entry = await entryRow(h, entryId!);
      const op = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: toUuid(outcome.opId!) } });
      if (want.effect === 'pending') {
        // What waits changes nothing live: an add's lineage is born proposed, an amend's entry keeps its revision.
        assert.equal(op.decision, 'pending', where);
        assert.equal(op.appliedByMode, null, where);
        if (source === 'machine_verified') {
          assert.equal(entry.currentRevision, 1, `${where}: a waiting amend changed its entry`);
        } else {
          assert.equal(entry.status, 'proposed', where);
        }
      } else {
        assert.equal(entry.status, 'active', where);
        assert.equal(entry.trust, want.trust, `${where}: applied with the wrong trust`);
        assert.equal(op.appliedByMode, mode, `${where}: the op does not name the mode that applied it`);
        assert.ok(op.decision === 'auto_applied' || (op.decision === 'pending' && op.spotCheck), `${where}: ${op.decision}`);
      }
      // Pushed exactly when it is live, `auto`, and of a kind the push carries at all.
      const shouldPush = want.effect === 'applied' && want.trust === 'auto' && KIND_SPECS[kind].push !== 'never';
      assert.equal(handed.has(entryId!), shouldPush, `${where}: pushed=${handed.has(entryId!)}, expected ${shouldPush}`);
      table.push(`${where}: ${want.effect === 'applied' ? `applied ${want.trust}` : 'pending'}, ${shouldPush ? 'pushed' : 'not pushed'}`);
    }
  }
  assert.equal(table.length, 3 * 6 * 3, 'every cell was asserted');
});

test('review modes · what counts as the owner\'s own words, and what does not', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'words');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'tiered', ws);
  const talk = await session(h, owner.id, ws, machine);
  const said = 'Keep every closed set as a CHECK constraint.';
  const propose = async (title: string, sources: unknown[]) => {
    const proposer = await session(h, owner.id, ws, machine);
    const answer = await call(h, { runner: machine, headers: { 'x-orbit-session-id': proposer } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'what the owner said',
      ops: [{ op: 'add', entry: draft('convention', title), sources }],
    });
    expectStatus(answer, 200, title);
    return entryRow(h, answer.body.ops[0].entryId);
  };

  await t.test('a web message, quoted verbatim, is Auto', async () => {
    const web = await turn(h, talk, said);
    const entry = await propose('Closed sets from the web', [{ kind: 'turn', ref: web, quote: 'every closed set as a CHECK' }]);
    assert.equal(entry.trust, 'auto');
  });

  await t.test('the same message cited without a quote is not verified, so it is Unreviewed', async () => {
    const web = await turn(h, talk, said);
    const entry = await propose('Closed sets cited bare', [{ kind: 'turn', ref: web }]);
    assert.equal(entry.trust, 'unreviewed');
  });

  await t.test('a turn the runner door filed — no routing intent — is not the owner\'s, whatever its key', async () => {
    const relayed = await turn(h, talk, said, { sendIntent: null, clientTurnId: randomUUID().toUpperCase() });
    const entry = await propose('Closed sets relayed by an agent', [{ kind: 'turn', ref: relayed, quote: 'every closed set as a CHECK' }]);
    assert.equal(entry.trust, 'unreviewed');
  });

  await t.test('a turn the control plane filed on its own account is not the owner\'s', async () => {
    const own = await turn(h, talk, said, { sendIntent: 'NEXT_TURN', clientTurnId: `watch:${randomUUID()}:1` });
    const entry = await propose('Closed sets a watch delivered', [{ kind: 'turn', ref: own, quote: 'every closed set as a CHECK' }]);
    assert.equal(entry.trust, 'unreviewed');
  });

  await t.test('an AskUserQuestion the owner answered is theirs; one nobody decided is not', async () => {
    const answered = randomUUID();
    await h.sql.query(
      `INSERT INTO "approval"("id","session_id","tool_name","input","status","answers","decided_by_id","decided_at")
       VALUES ($1,$2,'AskUserQuestion','{}','ALLOWED',$3,$4,now())`,
      [answered, talk, JSON.stringify({ 'How are closed sets stored?': 'As a CHECK constraint, never an enum' }), owner.id],
    );
    const entry = await propose('Closed sets as the owner answered', [{ kind: 'approval', ref: answered, quote: 'As a CHECK constraint, never an enum' }]);
    assert.equal(entry.trust, 'auto');

    const undecided = randomUUID();
    await h.sql.query(
      `INSERT INTO "approval"("id","session_id","tool_name","input","status","answers")
       VALUES ($1,$2,'AskUserQuestion','{}','ALLOWED',$3)`,
      [undecided, talk, JSON.stringify({ 'How are closed sets stored?': 'As a CHECK constraint, never an enum' })],
    );
    const unowned = await propose('Closed sets as nobody answered', [{ kind: 'approval', ref: undecided, quote: 'As a CHECK constraint, never an enum' }]);
    assert.equal(unowned.trust, 'unreviewed');
    assert.ok(space);
  });
});

// ── 2. the floors ───────────────────────────────────────────────────────────────────────────────

test('review modes · the five floors hold in Automatic, each with a counter-example', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'floors');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const evidence = await toolCall(h, records, 'Bash', 'what the run observed');
  const cite = [{ kind: 'tool_call', ref: evidence, quote: 'what the run observed' }];
  const propose = async (ops: unknown[], proposer?: string) =>
    call(h, { runner: machine, headers: { 'x-orbit-session-id': proposer ?? (await session(h, owner.id, ws, machine)) } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'a floor, tested',
      ops,
    });

  await t.test('the control: an agent\'s add in Automatic waits for its verification, and a supported verdict applies it as auto', async () => {
    const proposer = await session(h, owner.id, ws, machine);
    const answer = await propose([{ op: 'add', entry: draft('pitfall', 'A floor control pitfall'), sources: cite }], proposer);
    expectStatus(answer, 200, 'the control');
    assert.equal(answer.body.ops[0].status, 'pending');
    assert.equal(answer.body.ops[0].waitsFor, 'verification');
    assert.equal((await entryRow(h, answer.body.ops[0].entryId)).status, 'proposed');
    await verifyAll(h, agent(owner.id, proposer), space, answer.body.ops);
    assert.equal((await entryRow(h, answer.body.ops[0].entryId)).trust, 'auto');
  });

  await t.test('1 · a principle is the owner\'s to write', async () => {
    const answer = await propose([{ op: 'add', entry: draft('principle', 'An agent\'s principle'), sources: cite }]);
    expectStatus(answer, 403, 'an agent\'s principle');
    assert.equal(answer.body.ops[0].reasons[0].code, 'WIKI_KIND_OWNER_ONLY');
    assert.equal(await h.prisma.wikiEntry.count({ where: { spaceId: space, kind: 'principle' } }), 0, 'nothing was written');
  });

  await t.test('2 · a tainted op waits for the owner', async () => {
    const reader = await session(h, owner.id, ws, machine);
    await toolCall(h, reader, 'WebFetch', 'a page from the web');
    const answer = await propose([{ op: 'add', entry: draft('pitfall', 'A pitfall read off the web'), sources: cite }], reader);
    expectStatus(answer, 200, 'a tainted add');
    assert.equal(answer.body.ops[0].status, 'pending', 'held back, not applied');
    assert.equal(answer.body.ops[0].waitsFor, undefined, 'for the owner: no verdict can apply what the floor holds');
    const entry = await entryRow(h, answer.body.ops[0].entryId);
    assert.equal(entry.status, 'proposed');
    assert.equal(entry.tainted, true);
  });

  await t.test('3 · a change to what the owner wrote or confirmed waits for the owner', async () => {
    // The owner's own entry: amend and retire both wait.
    const written = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${space}/changesets`, {
      rationale: 'the owner writes a convention',
      ops: [{ op: 'add', entry: draft('convention', 'The owner\'s own convention') }],
    });
    expectStatus(written, 200, 'the owner writes');
    const ownerEntry = written.body.ops[0].entryId as string;
    assert.equal((await entryRow(h, ownerEntry)).trust, 'owner');
    const amend = await propose([{ op: 'amend', entryId: ownerEntry, baseRevision: 1, changes: { summary: 'An agent rewrites the owner.' }, sources: cite }]);
    assert.equal(amend.body.ops[0].status, 'pending', 'an amend of the owner\'s entry');
    const retire = await propose([{ op: 'retire', entryId: ownerEntry, baseRevision: 1, reason: 'An agent retires the owner.' }]);
    assert.equal(retire.body.ops[0].status, 'pending', 'a retire of the owner\'s entry');
    assert.equal((await entryRow(h, ownerEntry)).currentRevision, 1, 'the owner\'s entry is as they wrote it');

    // An entry the mode applied, then the owner edited: an owner revision is the owner's hand on it.
    const verifier = await session(h, owner.id, ws, machine);
    const applied = await propose([{ op: 'add', entry: draft('pitfall', 'A pitfall the owner then edited'), sources: cite }], verifier);
    await verifyAll(h, agent(owner.id, verifier), space, applied.body.ops);
    const touched = applied.body.ops[0].entryId as string;
    const edited = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${space}/changesets`, {
      rationale: 'the owner sharpens it',
      ops: [{ op: 'amend', entryId: touched, baseRevision: 1, changes: { summary: 'The owner\'s own wording now.' } }],
    });
    expectStatus(edited, 200, 'the owner amends');
    const after = await propose([{ op: 'amend', entryId: touched, baseRevision: 2, changes: { summary: 'An agent again.' }, sources: cite }]);
    assert.equal(after.body.ops[0].status, 'pending', 'an amend of an entry the owner has written in');

    // A confirmed one: the supersede of an entry whose spot check the owner accepted waits, like every supersede.
    const confirmed = await machineEntry(h, owner.id, space, 'pitfall', 'A confirmed pitfall', { trust: 'auto', sourceSession: records });
    await h.sql.query(`UPDATE "wiki_entry" SET "trust" = 'confirmed' WHERE "id" = $1`, [confirmed]);
    const amendConfirmed = await propose([{ op: 'amend', entryId: confirmed, baseRevision: 1, changes: { summary: 'Rewritten.' }, sources: cite }]);
    assert.equal(amendConfirmed.body.ops[0].status, 'pending', 'an amend of a confirmed entry');
    const supersede = await propose([{ op: 'supersede', entryId: confirmed, baseRevision: 1, entry: draft('pitfall', 'Its successor'), sources: cite }]);
    assert.equal(supersede.body.ops[0].status, 'pending', 'a supersede of a confirmed entry');
  });

  await t.test('4 · the circuit breaker: 10% of the active entries a changeset, and none below 100', async () => {
    const importOwner = await account(h, 'breaker');
    const recordsOf = await session(h, importOwner.id, null, null);
    const cited = await toolCall(h, recordsOf, 'Bash', 'compiled from the dossier');
    const full = await modeSpace(h, importOwner, 'automatic');
    await activeEntries(h, importOwner.id, full, WIKI_REVIEW_RULES.breakerMinActiveEntries);
    const tripped = await h.service.submitChangeset(importer(importOwner.id), full, {
      rationale: 'twelve adds into a space of a hundred',
      ops: importOps(12, cited, 'breaker'),
      idempotencyKey: `breaker-${randomUUID()}`,
    });
    const statuses = (tripped.ops as Outcome[]).map((op) => op.waitsFor ?? op.status);
    assert.deepEqual(statuses, [...Array(10).fill('verification'), 'refused', 'refused'], 'ten of a hundred, and not one more');
    const refusal = (tripped.ops as Outcome[])[10].reasons![0];
    assert.equal(refusal.code, 'WIKI_QUOTA');
    assert.match(refusal.message, /circuit breaker/u);

    const young = await modeSpace(h, importOwner, 'automatic');
    await activeEntries(h, importOwner.id, young, WIKI_REVIEW_RULES.breakerMinActiveEntries - 1);
    const filled = await h.service.submitChangeset(importer(importOwner.id), young, {
      rationale: 'twelve adds into a space of ninety-nine',
      ops: importOps(12, cited, 'young'),
      idempotencyKey: `young-${randomUUID()}`,
    });
    assert.deepEqual((filled.ops as Outcome[]).map((op) => op.waitsFor), Array(12).fill('verification'), 'below a hundred there is no breaker');
  });

  await t.test('5 · thirty ops a changeset, and the thirty-first refused — whoever sends it', async () => {
    const importOwner = await account(h, 'thirty');
    const recordsOf = await session(h, importOwner.id, null, null);
    const cited = await toolCall(h, recordsOf, 'Bash', 'compiled from the dossier');
    const target = await modeSpace(h, importOwner, 'automatic');
    const answer = await h.service.submitChangeset(importer(importOwner.id), target, {
      rationale: 'one more than a changeset holds',
      ops: importOps(WIKI_LIMITS.opsPerChangeset + 1, cited, 'thirty'),
      idempotencyKey: `thirty-${randomUUID()}`,
    });
    const outcomes = answer.ops as Outcome[];
    assert.equal(outcomes.filter((op) => op.waitsFor === 'verification').length, WIKI_LIMITS.opsPerChangeset);
    assert.equal(outcomes[WIKI_LIMITS.opsPerChangeset].status, 'refused');
    assert.equal(outcomes[WIKI_LIMITS.opsPerChangeset].reasons![0].code, 'WIKI_QUOTA');
    assert.equal(await h.prisma.wikiEntry.count({ where: { spaceId: target } }), WIKI_LIMITS.opsPerChangeset);
  });

  await t.test('and what the mode takes is not held to the review queue\'s quotas: a session\'s six adds all go to their verification', async () => {
    const proposer = await session(h, owner.id, ws, machine);
    const ops = Array.from({ length: WIKI_LIMITS.opsPerTurn + 1 }, (_unused, n) => ({
      op: 'add',
      entry: draft('pitfall', `A quota pitfall numbered ${n + 1}`),
      sources: cite,
    }));
    const answer = await propose(ops, proposer);
    expectStatus(answer, 200, 'six adds in one turn');
    assert.deepEqual((answer.body.ops as Outcome[]).map((op) => [op.status, op.waitsFor]), Array(6).fill(['pending', 'verification']));
  });
});

// ── 3. spot checks ──────────────────────────────────────────────────────────────────────────────

test('review modes · Tiered\'s spot checks by fact, and a reject rate over the line sends the space back once', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'spot checks');
  const recordsOf = await session(h, owner.id, null, null);
  const cited = await toolCall(h, recordsOf, 'Bash', 'compiled from the dossier');
  // Tiered: it applies an import's adds at once, and draws one in ten as it does. (Automatic draws
  // none unless its owner asks — `wiki-verify.pg.spec.ts`.)
  const space = await modeSpace(h, owner, 'tiered');
  const load = async (count: number, prefix: string) => h.service.submitChangeset(importer(owner.id), space, {
    rationale: `a batch of ${count}`,
    ops: importOps(count, cited, prefix),
    idempotencyKey: `${prefix}-${randomUUID()}`,
  });
  const spotChecks = async () => h.prisma.wikiChangesetOp.findMany({
    where: { ownerId: owner.id, spotCheck: true, changeset: { spaceId: space } },
    orderBy: [{ changeset: { createdAt: 'asc' } }, { seq: 'asc' }],
    include: { changeset: { select: { id: true } } },
  });

  await t.test('one in every ten the mode applies is drawn, where the draw says, and waits in Review', async () => {
    // Seventy, in three changesets: 30 + 30 + 10. No clock anywhere: the draw is by position.
    for (const [count, prefix] of [[30, 'first'], [30, 'second'], [10, 'third']] as const) {
      const answer = await load(count, prefix);
      assert.deepEqual((answer.ops as Outcome[]).map((op) => op.status), Array(count).fill('applied'), `${prefix}: all applied`);
    }
    const drawn = await spotChecks();
    assert.equal(drawn.length, 7, 'seven blocks of ten, seven spot checks');
    const ops = await h.prisma.wikiChangesetOp.findMany({
      where: { ownerId: owner.id, appliedByMode: { not: null }, changeset: { spaceId: space } },
      orderBy: [{ changeset: { createdAt: 'asc' } }, { seq: 'asc' }],
      select: { id: true, spotCheck: true },
    });
    assert.equal(ops.length, 70);
    ops.forEach((op, position) => {
      assert.equal(op.spotCheck, isSpotCheckDraw(space, position), `position ${position}`);
    });
    for (let block = 0; block < 7; block += 1) {
      assert.equal(ops.slice(block * 10, block * 10 + 10).filter((op) => op.spotCheck).length, 1, `block ${block}`);
    }
    for (const check of drawn) {
      assert.equal(check.decision, 'pending', 'a spot check waits for the owner');
      assert.equal(check.appliedByMode, 'tiered');
      assert.equal((await entryRow(h, check.resultEntryId!)).status, 'active', 'and its effect already stands');
    }
    const review = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/review?space=${space}`);
    const cards = (review.body as Array<{ ops: Array<{ spotCheck: boolean; decision: string }> }>)
      .flatMap((changeset) => changeset.ops.filter((op) => op.spotCheck && op.decision === 'pending'));
    assert.equal(cards.length, 7, 'Review shows each as a spot-check card');
    const listed = await call(h, { bearer: owner.bearer }, 'GET', '/wiki/spaces');
    assert.equal((listed.body as Array<{ id: string; pendingOps: number }>).find((s) => toUuid(s.id) === space)?.pendingOps, 7);
  });

  await t.test('accepted is confirmed, edited is the owner\'s, and four rejections of ten send the space back to Manual', async () => {
    const drawn = await spotChecks();
    const decide = (index: number, decision: Record<string, unknown>) =>
      call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${drawn[index].changeset.id}/decide`, {
        decisions: [{ opId: drawn[index].id, ...decision }],
      });
    expectStatus(await decide(0, { action: 'accept' }), 200, 'accept');
    assert.equal((await entryRow(h, drawn[0].resultEntryId!)).trust, 'confirmed');
    expectStatus(await decide(1, { action: 'edit', edited: { summary: 'The owner\'s own summary of it.' } }), 200, 'edit');
    const edited = await entryRow(h, drawn[1].resultEntryId!);
    assert.equal(edited.trust, 'confirmed');
    assert.equal(edited.summary, 'The owner\'s own summary of it.');
    const editRevision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: edited.id, revision: 2 } });
    assert.equal(editRevision.authorKind, 'owner');

    for (const index of [2, 3, 4]) {
      expectStatus(await decide(index, { action: 'reject', reason: 'not_true' }), 200, `reject ${index}`);
      const rejected = await entryRow(h, drawn[index].resultEntryId!);
      assert.equal(rejected.status, 'rejected', 'a rejected spot check undoes the add');
      assert.equal(rejected.trust, 'proposed');
    }
    // Three of ten is 30%, which is not over the line.
    let settings = (await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: space } })).settings as Record<string, unknown>;
    assert.equal(settings.reviewMode, 'tiered', 'three rejections out of ten are not over 30%');
    assert.equal(h.notified.length, 0);

    // The fourth, answered from the entry itself rather than the card, is the same fact.
    const fourth = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${drawn[5].resultEntryId}/reject`, { reason: 'duplicate' });
    expectStatus(fourth, 200, 'the fourth rejection, from the entry');
    settings = (await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: space } })).settings as Record<string, unknown>;
    assert.equal(settings.reviewMode, 'manual', 'four of ten rejected: back to Manual');
    assert.equal(settings.reviewModeChangedBy, 'spot_checks');
    assert.deepEqual(h.notified, [{ ownerId: owner.id, spaceId: space, rejected: 4, window: 10 }], 'the owner is told once');
    const op = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: drawn[5].id } });
    assert.equal(op.decision, 'rejected');
    assert.equal(op.decisionReason, 'duplicate');

    // A fifth rejection finds the space already Manual: nothing switches, nobody is told again.
    expectStatus(await decide(6, { action: 'reject', reason: 'not_useful' }), 200, 'a fifth rejection');
    assert.equal(h.notified.length, 1, 'no second notification');
    settings = (await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: space } })).settings as Record<string, unknown>;
    assert.equal(settings.reviewMode, 'manual');

    // And Manual it is: the next import waits for Review.
    const after = await load(1, 'after');
    assert.equal((after.ops as Outcome[])[0].status, 'pending', 'a Manual space applies nothing an import proposes');
  });

  await t.test('switched back by the owner, the window starts again: one rejection is not four', async () => {
    const back = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${space}`, { reviewMode: 'tiered' });
    expectStatus(back, 200, 'the owner switches back');
    await load(10, 'fresh');
    const fresh = (await spotChecks()).filter((check) => check.decision === 'pending');
    assert.equal(fresh.length, 1, 'ten more, one more spot check');
    expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${fresh[0].changeset.id}/decide`, {
      decisions: [{ opId: fresh[0].id, action: 'reject', reason: 'too_specific' }],
    }), 200, 'a rejection after the switch');
    const settings = (await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: space } })).settings as Record<string, unknown>;
    assert.equal(settings.reviewMode, 'tiered', 'the rejections before the switch are not counted again');
    assert.equal(h.notified.length, 1);
  });
});

// ── 4. revert ───────────────────────────────────────────────────────────────────────────────────

test('review modes · a whole run reverted, and every entry it touched out of the push', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'revert');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const evidence = await toolCall(h, records, 'Bash', 'what the maintenance run found');
  const cite = [{ kind: 'tool_call', ref: evidence, quote: 'what the maintenance run found' }];

  // What the space held before the run: two conventions an earlier run applied.
  const earlier = await h.service.submitChangeset(importer(owner.id), space, {
    rationale: 'the space\'s first batch',
    ops: [
      { op: 'add', entry: draft('convention', 'Closed sets are CHECK constraints', 'A closed set is TEXT with a CHECK.'), sources: [{ kind: 'tool_call', ref: evidence }] },
      { op: 'add', entry: draft('convention', 'Migrations take the next free number', 'A migration takes the first free number on main.'), sources: [{ kind: 'tool_call', ref: evidence }] },
    ],
    idempotencyKey: `earlier-${randomUUID()}`,
  });
  await verifyAll(h, importer(owner.id), space, earlier.ops as Outcome[]);
  const [kept, amended] = (earlier.ops as Outcome[]).map((op) => op.entryId!);

  // The run: two adds and an amend, each applied by its supported verdict.
  const proposer = await session(h, owner.id, ws, machine);
  const run = await call(h, { runner: machine, headers: { 'x-orbit-session-id': proposer } }, 'POST', '/runner/wiki/changesets', {
    rationale: 'a maintenance run that went wrong',
    ops: [
      { op: 'add', entry: draft('convention', 'A convention the run made up'), sources: cite },
      { op: 'add', entry: draft('pitfall', 'A pitfall the run made up'), sources: cite },
      { op: 'amend', entryId: amended, baseRevision: 1, changes: { summary: 'A migration takes any number it likes.' }, sources: cite },
    ],
  });
  expectStatus(run, 200, 'the run');
  assert.deepEqual((run.body.ops as Outcome[]).map((op) => op.waitsFor), ['verification', 'verification', 'verification']);
  await verifyAll(h, agent(owner.id, proposer), space, run.body.ops as Outcome[]);
  const [madeUp, madeUpPitfall] = (run.body.ops as Outcome[]).map((op) => toUuid(op.entryId!));
  const before = await pushed(h, owner.id, ws, await session(h, owner.id, ws, machine));
  for (const id of [kept, amended, madeUp, madeUpPitfall]) assert.ok(before.has(id), `${id} is pushed before the revert`);

  await t.test('a session cannot take a run back', async () => {
    const refused = await call(h, { bearer: owner.bearer, headers: { 'x-orbit-session-id': proposer } }, 'POST', `/wiki/changesets/${run.body.changesetId}/revert`);
    expectStatus(refused, 403, 'a revert carrying a session header');
    assert.equal(refused.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
    assert.equal((await entryRow(h, madeUp)).status, 'active', 'and nothing was taken back');
  });

  await t.test('the owner takes it back: its adds retired, its amend restored, all out of the push', async () => {
    const reverted = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${run.body.changesetId}/revert`);
    expectStatus(reverted, 200, 'the owner reverts the run');
    assert.deepEqual(reverted.body.skipped, []);
    assert.deepEqual((reverted.body.ops as Outcome[]).map((op) => op.status), ['applied', 'applied', 'applied']);
    for (const id of [madeUp, madeUpPitfall]) {
      const entry = await entryRow(h, id);
      assert.equal(entry.status, 'retired', 'an add the run made is retired');
    }
    const restored = await entryRow(h, amended);
    assert.equal(restored.status, 'active');
    assert.equal(restored.summary, 'A migration takes the first free number on main.', 'the amend is undone');
    assert.equal(restored.currentRevision, 3, 'as a revision of its own: the history keeps what the run wrote');
    assert.equal(restored.trust, 'unreviewed', 'and it is out of the push until somebody looks');
    const revisions = await h.prisma.wikiEntryRevision.findMany({ where: { entryId: restored.id }, orderBy: { revision: 'asc' } });
    assert.deepEqual(revisions.map((r) => r.summary), [
      'A migration takes the first free number on main.',
      'A migration takes any number it likes.',
      'A migration takes the first free number on main.',
    ]);
    assert.equal(revisions[2].authorKind, 'owner');
    assert.ok(await h.prisma.wikiSource.count({ where: { revisionId: revisions[2].id } }) >= 1, 'with the sources the revision rested on');
    const revertSet = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(reverted.body.changesetId) } });
    assert.equal(revertSet.origin, 'owner', 'the undoing is the owner\'s own changeset');

    const after = await pushed(h, owner.id, ws, await session(h, owner.id, ws, machine));
    for (const id of [amended, madeUp, madeUpPitfall]) assert.equal(after.has(id), false, `${id} left the push`);
    assert.ok(after.has(kept), 'what the run did not touch is still pushed');
  });

  await t.test('a second revert answers with the first and writes nothing', async () => {
    const revisions = await h.prisma.wikiEntryRevision.count({ where: { ownerId: owner.id } });
    const again = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${run.body.changesetId}/revert`);
    expectStatus(again, 200, 'a second revert');
    assert.equal(again.body.replayed, true);
    assert.equal(await h.prisma.wikiEntryRevision.count({ where: { ownerId: owner.id } }), revisions);
  });
});

// ── the owner's Reject, and the import the preview space is loaded with ─────────────────────────

test('review modes · the owner rejects one entry, and a bulk import applies once', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'import');
  const recordsOf = await session(h, owner.id, null, null);
  const cited = await toolCall(h, recordsOf, 'Bash', 'compiled from the dossier');
  // The preview space: no workspace bound to it at all.
  const preview = await modeSpace(h, owner, 'automatic');
  const batch = importOps(WIKI_LIMITS.opsPerChangeset, cited, 'preview');

  await t.test('origin import, authored by the system, bare record ids, applied by its verdicts', async () => {
    const answer = await h.service.submitChangeset(importer(owner.id), preview, {
      rationale: 'the demo\'s compiled entries, batch one',
      ops: batch,
      idempotencyKey: 'preview-load:batch-0001',
    });
    assert.deepEqual((answer.ops as Outcome[]).map((op) => op.waitsFor), Array(WIKI_LIMITS.opsPerChangeset).fill('verification'));
    assert.equal(await h.prisma.wikiEntry.count({ where: { spaceId: preview, status: 'active' } }), 0, 'nothing is live before its verdict');
    await verifyAll(h, importer(owner.id), preview, answer.ops as Outcome[]);
    const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: String(answer.changesetId) } });
    assert.equal(changeset.origin, 'import');
    assert.equal(changeset.sessionId, null);
    const revisions = await h.prisma.wikiEntryRevision.findMany({ where: { ownerId: owner.id, entry: { spaceId: preview } } });
    assert.equal(revisions.length, WIKI_LIMITS.opsPerChangeset);
    assert.ok(revisions.every((r) => r.authorKind === 'system' && r.authorUserId === null), 'the system wrote them, and never as the owner');
    const sources = await h.prisma.wikiSource.findMany({ where: { revisionId: { in: revisions.map((r) => r.id) } } });
    assert.ok(sources.every((source) => source.quote === null && source.ref === cited), 'a bare record id, no quote');
    const entries = await h.prisma.wikiEntry.findMany({ where: { spaceId: preview } });
    assert.ok(entries.every((entry) => entry.status === 'active' && entry.trust === 'auto'));
  });

  await t.test('the same batch again is a replay, and writes nothing twice', async () => {
    const replay = await h.service.submitChangeset(importer(owner.id), preview, {
      rationale: 'the demo\'s compiled entries, batch one',
      ops: batch,
      idempotencyKey: 'preview-load:batch-0001',
    });
    assert.equal(replay.replayed, true);
    assert.ok((replay.ops as Outcome[]).every((op) => op.status === 'pending' && op.waitsFor === 'verification'), 'the recorded answer, as it was');
    assert.equal(await h.prisma.wikiEntry.count({ where: { spaceId: preview } }), WIKI_LIMITS.opsPerChangeset);
    await assert.rejects(
      h.service.submitChangeset(importer(owner.id), preview, {
        rationale: 'another batch under the same key',
        ops: importOps(1, cited, 'reused'),
        idempotencyKey: 'preview-load:batch-0001',
      }),
      (error: { refusal?: { code: string } }) => error.refusal?.code === 'WIKI_IDEMPOTENCY_KEY_REUSED',
    );
  });

  await t.test('the owner rejects one entry: it is a counter-example, and the next near neighbour says so', async () => {
    const entry = (await h.prisma.wikiEntry.findFirstOrThrow({ where: { spaceId: preview, status: 'active', trust: 'auto' } }));
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id);
    const someone = await session(h, owner.id, ws, machine);
    const refused = await call(h, { bearer: owner.bearer, headers: { 'x-orbit-session-id': someone } }, 'POST', `/wiki/entries/${entry.id}/reject`, { reason: 'not_true' });
    expectStatus(refused, 403, 'a Reject carrying a session header');
    expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${entry.id}/reject`, {}), 400, 'a Reject that names no reason');

    const rejected = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${entry.id}/reject`, { reason: 'not_true', note: 'The demo got this wrong.' });
    expectStatus(rejected, 200, 'the owner rejects the entry');
    assert.equal(rejected.body.status, 'rejected');
    const row = await entryRow(h, entry.id);
    assert.equal(row.trust, 'proposed');
    assert.ok(row.retiredAt, 'it left the live set');
    const made = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { resultEntryId: entry.id, op: 'add' } });
    assert.equal(made.decision, 'rejected', 'the rejection is on the add the mode applied');
    assert.equal(made.decisionReason, 'not_true');

    const again = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${entry.id}/reject`, { reason: 'not_true' });
    expectStatus(again, 409, 'an entry already rejected');

    const neighbour = await h.service.submitChangeset(importer(owner.id), preview, {
      rationale: 'the same claim again',
      ops: [{ op: 'add', entry: { ...draft('concept', entry.title, entry.summary) }, sources: [{ kind: 'tool_call', ref: cited }] }],
      idempotencyKey: `neighbour-${randomUUID()}`,
    });
    const similar = (neighbour.ops as Outcome[])[0].similar ?? [];
    assert.equal(similar.find((near) => near.id === entry.id)?.rejectedReason, 'not_true', 'a rejected neighbour says why');
    // The owner rejected it, not its verifier, which had found it supported: no verifier's words ride along.
    assert.equal((similar.find((near) => near.id === entry.id) as { rejectedBecause?: string } | undefined)?.rejectedBecause, undefined);
  });

  await t.test('what the owner wrote is retired, never rejected', async () => {
    const written = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${preview}/changesets`, {
      rationale: 'the owner writes a concept',
      ops: [{ op: 'add', entry: draft('concept', 'The owner\'s own concept') }],
    });
    const refused = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${written.body.ops[0].entryId}/reject`, { reason: 'not_true' });
    expectStatus(refused, 409, 'a Reject of the owner\'s own entry');
    assert.equal((await entryRow(h, written.body.ops[0].entryId)).status, 'active');
  });
});
