/**
 * The Orbit Wiki's write path, over real HTTP and against a real PostgreSQL.
 *
 * What is under test is what a caller gets back and what the database then holds, so both are read:
 * every request goes through the real controllers, the real WikiService, the global ValidationPipe
 * and the public-id interceptor, and every claim about "nothing was written" is a count of the rows
 * migration 0307 created. Only the two credential checks are stood in for — `JwtService.verifyAsync`
 * answers with the account a bearer was issued to, and the runner guard reads the runner row this
 * file wrote — which is what `watch-api.pg.spec.ts` stands in for and for the same reason.
 *
 * The contract is `contracts/wiki.contract.json`. Every case below is one of the behaviours design
 * §4 and this task's acceptance criteria name: cross-tenant 404s, a decide that carries a session
 * header, a compare-and-set conflict that answers with the current revision, sources that do not
 * resolve and quotes that are not in the record they cite, an idempotency key replayed, an agent's
 * proposal that waits for the owner while the owner's own writes, reinforces and challenges apply at
 * once, a probe refused, a service token refused on both doors, and which of those writes announce a
 * `wiki.changed` to the owner's other clients.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-api.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { WIKI_LIMITS, toUuid } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { ServiceTokenAuthorizer } from '../runner-api/service-token.authorizer';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { RealtimeService } from '../realtime/realtime.service';
import { WikiController } from './wiki.controller';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

// From build/wiki back to the repository root.
const CONTRACT = JSON.parse(
  readFileSync(path.resolve(__dirname, '../../../../contracts/wiki.contract.json'), 'utf8'),
) as {
  refusals: Array<{ code: string; httpStatus: number }>;
  limits: Record<string, number>;
  storage: { singleWriter: string };
  effectPolicy: { decide: { actions: string[] } };
  rejectReasons: Record<string, string>;
};

/**
 * One announcement the service made on the control plane — `RealtimeService.publishWikiChanged`,
 * stood in for here so a case can read what a browser would receive without a hub, a socket or a
 * second replica. The real publish's wire shape is `realtime/stream-for-user.spec.ts`'s subject;
 * what this file witnesses is WHICH writes make one and what it names.
 */
interface Announcement {
  ownerId: string;
  spaceId: string;
}

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  /** bearer → the account it was issued to */
  bearers: Map<string, string>;
  /** Every `wiki.changed` this process published, in order, across every case in the file. */
  announced: Announcement[];
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const announced: Announcement[] = [];
    const hub = {
      publishWikiChanged: (ownerId: string, spaceId: string) => {
        announced.push({ ownerId, spaceId });
      },
    } as unknown as RealtimeService;

    @Module({
      controllers: [WikiController, RunnerWikiController],
      providers: [
        { provide: WikiService, useValue: new WikiService(prisma as unknown as PrismaService, hub) },
        // The two controllers also answer the search route, which is T4's read; this spec exercises
        // the write path, so it only has to construct.
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiApiModule {}

    const app = await NestFactory.create(WikiApiModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, bearers, announced };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  headers?: Record<string, string>;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json', ...(who.headers ?? {}) };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

/** The first refusal in an answer, by its contract code. */
function refusalOf(answer: Answer): { code: string; message: string } {
  const ops = answer.body.ops as Array<{ status: string; reasons: Array<{ code: string; message: string }> }>;
  const refused = ops.find((op) => op.status === 'refused');
  assert.ok(refused, `expected a refusal, got ${JSON.stringify(answer.body)}`);
  return refused!.reasons[0];
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-api-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

interface Machine {
  id: string;
  token: string;
}

async function runner(h: Harness, ownerId: string): Promise<Machine> {
  const id = randomUUID();
  const token = `runner-${id}`;
  const tokenHash = createHash('sha256').update(token).digest('hex');
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    tokenHash,
  ]);
  return { id, token };
}

async function workspace(
  h: Harness,
  ownerId: string,
  shape: { repoUrl?: string | null; env?: Record<string, string> } = {},
): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","repo_url","env") VALUES ($1,'spec',$2,$3,$4)`, [
    id,
    ownerId,
    shape.repoUrl ?? null,
    shape.env ? JSON.stringify(shape.env) : null,
  ]);
  return id;
}

async function session(
  h: Harness,
  ownerId: string,
  shape: {
    workspaceId?: string | null;
    runnerId?: string | null;
    taskId?: string | null;
    dispatchOrigin?: string;
  } = {},
): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","dispatch_origin","updated_at")
     VALUES ($1,'a wiki session','p',$2,$2,$3,$4,$5,$6,now())`,
    [id, ownerId, shape.workspaceId ?? null, shape.runnerId ?? null, shape.taskId ?? null, shape.dispatchOrigin ?? 'USER'],
  );
  return id;
}

/** A conversation turn the wiki may cite. */
async function turn(h: Harness, sessionId: string, seq: number, content: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status")
     VALUES ($1,$2,$3,$4,$5,'ANSWERED')`,
    [id, sessionId, seq, `turn-${seq}-${id}`, content],
  );
  return id;
}

/** A tool call, whose output is what a quote is checked against. */
async function toolCall(h: Harness, sessionId: string, name: string, output: unknown): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","output") VALUES ($1,$2,$3,$4)`, [
    id,
    sessionId,
    name,
    JSON.stringify(output),
  ]);
  return id;
}

/** A task, so a session can be a verifier's or a foreman's. */
async function task(
  h: Harness,
  ownerId: string,
  shape: { verifiesTaskId?: string; isForeman?: boolean } = {},
): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","updated_at",
                          "completion_criterion","verifies_task_id","is_foreman")
     VALUES ($1,'watched work',$2,'USER',$2,'OPEN',now(),'OWNER_CONFIRMED',$3,$4)`,
    [id, ownerId, shape.verifiesTaskId ?? null, shape.isForeman ?? false],
  );
  return id;
}

/** A space the owner makes through the door, so the fixture is exercised the way a client uses it. */
async function space(h: Harness, who: Account, repoUrl?: string): Promise<string> {
  const answer = await call(h, { bearer: who.bearer }, 'POST', '/wiki/spaces', {
    title: 'The orbit repository',
    ...(repoUrl ? { repoUrl } : {}),
  });
  expectStatus(answer, 201, 'the owner creates a space');
  return answer.body.id as string;
}

// ── request bodies ──────────────────────────────────────────────────────────────────────────────

function draftOf(shape: { title: string; kind?: string; summary?: string; fields?: Record<string, unknown> }): Record<string, unknown> {
  return {
    kind: shape.kind ?? 'pitfall',
    title: shape.title,
    summary: shape.summary ?? 'A pg spec that skips itself proves nothing about what it tests.',
    fields: shape.fields ?? {
      trigger: { paths: ['src/apiserver/src/wiki/*.pg.spec.ts'], commands: ['node --test build/x.pg.spec.js'] },
      symptom: 'node exits 0 and no assertion ran.',
      cause: 'A pg spec skips itself when the URL is unset.',
      fix: 'Run it through scripts/run-pg-spec.sh, which treats a skip as red.',
    },
  };
}

function addOp(shape: { title: string; kind?: string; summary?: string; fields?: Record<string, unknown> }, sources: unknown[]): Record<string, unknown> {
  return { op: 'add', entry: draftOf(shape), sources };
}

// ── the frozen contract ─────────────────────────────────────────────────────────────────────────

test('the refusals, limits and effect policy this door answers with are the contract\'s', () => {
  const status = (code: string) => CONTRACT.refusals.find((refusal) => refusal.code === code)?.httpStatus;
  assert.deepEqual(
    CONTRACT.refusals.map((refusal) => [refusal.code, refusal.httpStatus]).sort(),
    [
      ['WIKI_DISABLED', 404],
      ['WIKI_IDEMPOTENCY_KEY_REUSED', 409],
      ['WIKI_KIND_OWNER_ONLY', 403],
      ['WIKI_NOT_MAINTENANCE_SESSION', 403],
      ['WIKI_OWNER_CHANNEL_ONLY', 403],
      ['WIKI_PROBE_REFUSED', 422],
      ['WIKI_QUOTA', 429],
      ['WIKI_QUOTE_NOT_FOUND', 422],
      ['WIKI_REVIEW_QUEUE_FULL', 429],
      ['WIKI_REVISION_CONFLICT', 409],
      ['WIKI_SCHEMA', 400],
      ['WIKI_SESSION_EXCLUDED', 403],
      ['WIKI_SOURCE_UNRESOLVED', 422],
      ['WIKI_SPACE_UNBOUND', 409],
    ].sort(),
  );
  assert.equal(status('WIKI_REVISION_CONFLICT'), 409);
  assert.deepEqual(CONTRACT.effectPolicy.decide.actions, ['accept', 'edit', 'reject']);
  assert.deepEqual(Object.keys(CONTRACT.rejectReasons), ['not_true', 'not_useful', 'duplicate', 'too_specific']);
  for (const [limit, value] of Object.entries(CONTRACT.limits)) {
    assert.equal((WIKI_LIMITS as unknown as Record<string, number>)[limit], value, `limits.${limit}`);
  }
  // The entry's state has two writers and no third: applyOp, and recomputeFlags.
  assert.match(CONTRACT.storage.singleWriter, /applyOp and WikiService\.recomputeFlags/u);
});

// ── the write path ──────────────────────────────────────────────────────────────────────────────

test('0307 · the wiki write path', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test('a proposal from a session waits for the owner, and the space comes from its workspace', async () => {
    const owner = await account(h, 'the owner');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'git@github.com:orbit/spec.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    await turn(h, mine, 1, 'the spec skipped itself and exited zero');
    const tool = await toolCall(h, mine, 'Bash', 'node --test build/x.pg.spec.js\n# tests 0\n# pass 0\n# skipped 3');

    const answer = await call(
      h,
      { runner: machine.token, headers: { 'x-orbit-session-id': mine } },
      'POST',
      '/runner/wiki/changesets',
      {
        rationale: 'the second time a pg spec proved nothing by skipping',
        ops: [
          addOp({ title: 'A skipped pg spec exits zero' }, [
            { kind: 'turn', session: 'self', seq: 1, quote: 'the spec skipped itself' },
            { kind: 'tool_call', ref: tool, quote: '# skipped 3' },
          ]),
        ],
      },
    );
    expectStatus(answer, 200, 'an agent proposes');
    assert.notEqual(answer.body.changesetId, null, 'a recorded proposal names its changeset');
    const outcome = answer.body.ops[0];
    assert.equal(outcome.status, 'pending', `an agent's add waits for the owner: ${JSON.stringify(answer.body)}`);
    assert.ok(outcome.entryId, 'the lineage it created is named back');

    const entry = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(outcome.entryId) } });
    assert.equal(entry.status, 'proposed');
    assert.equal(entry.trust, 'proposed');
    assert.equal(entry.currentRevision, 1);
    assert.equal(entry.tainted, false);
    const revision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: entry.id } });
    assert.equal(revision.authorKind, 'agent');
    assert.equal(revision.authorSessionId, mine);
    const sources = await h.prisma.wikiSource.findMany({ where: { revisionId: revision.id }, orderBy: { kind: 'asc' } });
    assert.equal(sources.length, 2);
    assert.deepEqual(sources.map((source) => source.quoteVerified), [true, true], 'both quotes are in their records');
    const selfTurn = sources.find((source) => source.kind === 'turn')!;
    assert.equal(toUuid(selfTurn.ref), mine, 'a turn of the calling session is stored under that session');
    assert.equal((selfTurn.locator as { seq: number }).seq, 1);
    const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(answer.body.changesetId) } });
    assert.equal(changeset.status, 'pending');
    assert.ok(changeset.expiresAt, 'a pending changeset carries its expiry');

    // The same repository, written the other way, is the same space: the binding happened on first use.
    const second = await workspace(h, owner.id, { repoUrl: 'https://github.com/orbit/spec' });
    const other = await session(h, owner.id, { workspaceId: second, runnerId: machine.id });
    const again = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': other } }, 'GET', `/runner/wiki/entries/${outcome.entryId}`);
    expectStatus(again, 200, "the second workspace shares the first one's space");
    assert.equal(again.body.id, outcome.entryId);
    const spaces = await h.prisma.wikiSpace.findMany({ where: { ownerId: owner.id } });
    assert.equal(spaces.length, 1);
    assert.equal(spaces[0].repoUrlNorm, 'github.com/orbit/spec');
    assert.equal(await h.prisma.wikiSpaceWorkspace.count({ where: { ownerId: owner.id } }), 2);
  });

  await t.test('a workspace bound to no space is told how to bind one', async () => {
    const owner = await account(h, 'unbound');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, {});
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const answer = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'nothing to bind this to',
      ops: [addOp({ title: 'A workspace with no repository' }, [{ kind: 'turn', session: 'self' }])],
    });
    expectStatus(answer, 409, 'an unbound workspace is refused');
    assert.equal(answer.body.code, 'WIKI_SPACE_UNBOUND');
    assert.match(answer.body.message, /binds it in Wiki settings|repository URL/u);
    assert.equal(await h.prisma.wikiSpace.count({ where: { ownerId: owner.id } }), 0, 'and no space is invented');

    const made = await space(h, owner);
    const bound = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${made}/workspaces`, { workspaceId: ws });
    expectStatus(bound, 200, 'the owner binds the workspace by hand');
    const retried = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'now it has a home',
      ops: [addOp({ title: 'A workspace with no repository' }, [{ kind: 'turn', session: 'self' }])],
    });
    expectStatus(retried, 200, 'the proposal lands in the bound space');
    assert.equal(retried.body.ops[0].status, 'pending');
  });

  await t.test('a source that does not resolve, and a quote that is not in its record, are refused', async () => {
    const owner = await account(h, 'sources');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/sources.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'the palette matched nothing at all');
    const stranger = await account(h, 'a second account');
    const strangerSession = await session(h, stranger.id, {});
    const theirs = await toolCall(h, strangerSession, 'Bash', 'their own tool output');

    const propose = (ops: unknown[]) =>
      call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
        rationale: 'checking what the door holds a source to',
        ops,
      });

    const dangling = await propose([addOp({ title: 'Something with no record behind it' }, [{ kind: 'tool_call', ref: randomUUID() }])]);
    expectStatus(dangling, 422, 'a source that resolves to nothing is refused');
    assert.equal(refusalOf(dangling).code, 'WIKI_SOURCE_UNRESOLVED');

    const foreign = await propose([addOp({ title: 'Something cited from another account' }, [{ kind: 'tool_call', ref: theirs }])]);
    expectStatus(foreign, 422, "another account's record is not a source");
    assert.equal(refusalOf(foreign).code, 'WIKI_SOURCE_UNRESOLVED');

    const uncited = await propose([addOp({ title: 'A claim with nothing behind it' }, [])]);
    expectStatus(uncited, 422, 'a non-owner add that cites nothing is refused');
    assert.equal(refusalOf(uncited).code, 'WIKI_SOURCE_UNRESOLVED');

    const misquote = await propose([
      addOp({ title: 'Something quoted loosely' }, [{ kind: 'tool_call', ref: tool, quote: 'the palette matched something' }]),
    ]);
    expectStatus(misquote, 422, 'a quote that is not in the record is refused');
    assert.equal(refusalOf(misquote).code, 'WIKI_QUOTE_NOT_FOUND');

    // Whitespace is normalized on both sides, so a wrapped quote is the same quote.
    const wrapped = await propose([
      addOp({ title: 'A quote wrapped across lines' }, [
        { kind: 'tool_call', ref: tool, quote: 'the   palette\nmatched nothing at all' },
      ]),
    ]);
    expectStatus(wrapped, 200, "a whitespace-normalized quote is still the record's words");
    assert.equal(await h.prisma.wikiEntry.count({ where: { ownerId: owner.id } }), 1, 'only the op that passed left a row');
  });

  await t.test("the owner accepts, edits and rejects, and only an accepted proposal is confirmed", async () => {
    const owner = await account(h, 'decider');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/decide.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'the second run finds the build directory gone');

    const proposed = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'three proposals, decided three ways',
      ops: [
        addOp({ title: 'A build tree left by another branch' }, [{ kind: 'tool_call', ref: tool, quote: 'the build directory gone' }]),
        addOp({ title: 'A spec that is green because it skipped' }, [{ kind: 'tool_call', ref: tool, quote: 'the second run' }]),
        addOp({ title: 'A summary written in the wrong voice' }, [{ kind: 'tool_call', ref: tool, quote: 'the build directory' }]),
      ],
    });
    expectStatus(proposed, 200, 'the agent proposes three');
    const ops = proposed.body.ops as Array<{ opId: string; entryId: string }>;

    const decided = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${proposed.body.changesetId}/decide`, {
      decisions: [
        { opId: ops[0].opId, action: 'accept' },
        {
          opId: ops[1].opId,
          action: 'edit',
          edited: { title: 'A spec that is green because it skipped', summary: 'Rewritten by the owner: a skip is not a pass.' },
        },
        { opId: ops[2].opId, action: 'reject', reason: 'too_specific' },
      ],
    });
    expectStatus(decided, 200, 'the owner decides all three');
    assert.equal(decided.body.status, 'settled', 'no op is left waiting');

    const entries = await h.prisma.wikiEntry.findMany({ where: { ownerId: owner.id }, orderBy: { recordedAt: 'asc' } });
    assert.deepEqual(entries.map((entry) => entry.status), ['active', 'active', 'rejected']);
    assert.deepEqual(entries.map((entry) => entry.trust), ['confirmed', 'confirmed', 'proposed']);
    assert.ok(entries[2].retiredAt, 'a rejected entry is terminal');
    assert.equal(entries[1].summary, 'Rewritten by the owner: a skip is not a pass.', 'the edit applied at once');

    const edited = await h.prisma.wikiEntryRevision.findMany({ where: { entryId: entries[1].id }, orderBy: { revision: 'asc' } });
    assert.equal(edited.length, 2, 'an edit adds a revision rather than rewriting one');
    assert.equal(edited[0].authorKind, 'agent', 'the revision the agent proposed stays as it was');
    assert.equal(edited[1].authorKind, 'owner', 'the owner edited it, so the owner authored the revision');
    assert.equal(edited[1].authorUserId, owner.id);
    const accepted = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: entries[0].id } });
    assert.equal(accepted.authorKind, 'agent', 'an accepted proposal keeps its proposer as author');
    const decidedOps = await h.prisma.wikiChangesetOp.findMany({
      where: { changesetId: toUuid(proposed.body.changesetId) },
      orderBy: { seq: 'asc' },
    });
    assert.deepEqual(decidedOps.map((op) => op.decision), ['accepted', 'edited', 'rejected']);
    assert.equal(decidedOps[2].decisionReason, 'too_specific');
  });

  await t.test("the owner's own write applies at once and is trusted as theirs", async () => {
    const owner = await account(h, 'author');
    const made = await space(h, owner, 'github.com/orbit/author.git');
    const answer = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${made}/changesets`, {
      rationale: 'the owner records a principle',
      ops: [
        {
          op: 'add',
          entry: {
            kind: 'principle',
            title: 'Delete means forget',
            summary: 'Deleting a record deletes every quote the wiki took from it.',
            fields: {
              statement: 'When a record is deleted, every quote taken from it is deleted with it.',
              rationale: 'Owners delete to forget; a wiki that kept the words would undo that.',
            },
          },
        },
      ],
    });
    expectStatus(answer, 200, 'the owner writes');
    assert.equal(answer.body.ops[0].status, 'applied');
    assert.equal(answer.body.ops[0].revision, 1);
    const entry = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(answer.body.ops[0].entryId) } });
    assert.equal(entry.status, 'active');
    assert.equal(entry.trust, 'owner');
    const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(answer.body.changesetId) } });
    assert.equal(changeset.status, 'settled', 'a changeset every op of which applied is settled when written');
    assert.ok(changeset.decidedAt);
  });

  await t.test("a principle is refused to an agent, and is the owner's to write", async () => {
    const owner = await account(h, 'owner-only');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/owner-only.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'the design says so');
    const answer = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'a principle the agent thinks it found',
      ops: [
        {
          op: 'add',
          entry: {
            kind: 'principle',
            title: 'Knowledge is not evidence',
            summary: 'A session that judges work is not told what the wiki says.',
            fields: { statement: 'Judgment sessions read no wiki.', rationale: 'Otherwise a claim grades itself.' },
          },
          sources: [{ kind: 'tool_call', ref: tool, quote: 'the design says' }],
        },
      ],
    });
    expectStatus(answer, 403, 'a non-owner may not write a principle');
    assert.equal(refusalOf(answer).code, 'WIKI_KIND_OWNER_ONLY');
    assert.equal(await h.prisma.wikiEntry.count({ where: { ownerId: owner.id } }), 0);
  });

  await t.test('a reinforce and a challenge apply at once, a supersede waits, and the space can turn reinforce off', async () => {
    const owner = await account(h, 'effects');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/effects.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const first = await toolCall(h, mine, 'Bash', 'the palette matched nothing at all');
    const second = await toolCall(h, mine, 'Bash', 'a second session saw the same failure');
    const propose = (body: Record<string, unknown>) =>
      call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', body);
    const decide = (changesetId: string, decisions: unknown[]) =>
      call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${changesetId}/decide`, { decisions });

    const seeded = await propose({
      rationale: 'the entry the other ops are about',
      ops: [addOp({ title: 'A palette that matched nothing' }, [{ kind: 'tool_call', ref: first, quote: 'matched nothing' }])],
    });
    const entryId = seeded.body.ops[0].entryId as string;
    await decide(seeded.body.changesetId, [{ opId: seeded.body.ops[0].opId, action: 'accept' }]);
    const spaceId = (await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } })).spaceId;

    const reinforced = await propose({
      rationale: 'a second session saw it too',
      ops: [{ op: 'reinforce', entryId, sources: [{ kind: 'tool_call', ref: second, quote: 'the same failure' }] }],
    });
    expectStatus(reinforced, 200, 'a reinforce is accepted');
    assert.equal(reinforced.body.ops[0].status, 'applied', 'a reinforce applies unless the space turned it off');
    const afterReinforce = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } });
    assert.equal(afterReinforce.currentRevision, 1, 'a reinforce changes no content');
    assert.equal(await h.prisma.wikiSource.count({ where: { ownerId: owner.id } }), 2, 'the second quote joined the revision');

    const challenged = await propose({
      rationale: 'the palette was fine in the next release',
      ops: [{ op: 'challenge', entryId, reason: 'the palette was renamed upstream' }],
    });
    expectStatus(challenged, 200, 'a challenge is accepted from every origin');
    assert.equal(challenged.body.ops[0].status, 'applied', 'a challenge applies at once');
    const afterChallenge = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } });
    assert.equal(afterChallenge.challenged, true, 'and it takes the entry out of the push');
    assert.equal(afterChallenge.status, 'active', 'without retiring it');

    const answered = await decide(challenged.body.changesetId, [{ opId: challenged.body.ops[0].opId, action: 'reject', reason: 'not_true' }]);
    expectStatus(answered, 200, 'the owner answers the challenge');
    const settledEntry = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } });
    assert.equal(settledEntry.challenged, false, 'the answer clears the flag');

    const supersede = await propose({
      rationale: 'a better statement of the same thing',
      ops: [
        {
          op: 'supersede',
          entryId,
          baseRevision: 1,
          entry: draftOf({ title: 'A palette that matched nothing, restated' }),
          sources: [{ kind: 'tool_call', ref: second, quote: 'a second session' }],
        },
      ],
    });
    expectStatus(supersede, 200, 'an agent may propose a supersede');
    assert.equal(supersede.body.ops[0].status, 'pending', 'and it waits for the owner');
    const still = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } });
    assert.equal(still.status, 'active', 'the entry it would replace is untouched until it is accepted');
    assert.equal(still.supersededById, null);
    const successor = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(supersede.body.ops[0].entryId) } });
    assert.equal(successor.status, 'proposed');
    assert.equal(successor.supersedesId, toUuid(entryId));

    // Accepting it retires the entry it replaces, in the same transaction.
    await decide(supersede.body.changesetId, [{ opId: supersede.body.ops[0].opId, action: 'accept' }]);
    const replaced = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } });
    assert.equal(replaced.status, 'superseded');
    assert.equal(replaced.supersededById, toUuid(supersede.body.ops[0].entryId));
    assert.ok(replaced.retiredAt);

    // A space that turned auto-accept off makes the next reinforce wait.
    const patched = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { autoAcceptReinforce: false });
    expectStatus(patched, 200, 'the owner turns auto-accept off');
    assert.equal(patched.body.settings.autoAcceptReinforce, false);
    const waiting = await propose({
      rationale: 'the space says wait',
      ops: [{ op: 'reinforce', entryId: successor.id, sources: [{ kind: 'tool_call', ref: second, quote: 'saw the same' }] }],
    });
    expectStatus(waiting, 200, 'a reinforce is still accepted');
    assert.equal(waiting.body.ops[0].status, 'pending', 'but it waits for the owner when the space says so');
  });

  await t.test('a compare-and-set that no longer holds answers 409 with the current revision', async () => {
    const owner = await account(h, 'cas');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/cas.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'the first revision said one thing');
    const ownerWrite = (spaceId: string, body: Record<string, unknown>) =>
      call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/changesets`, body);
    const propose = (body: Record<string, unknown>) =>
      call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', body);

    const seeded = await propose({
      rationale: 'the entry the amend is about',
      ops: [addOp({ title: 'An entry that will move on' }, [{ kind: 'tool_call', ref: tool, quote: 'the first revision' }])],
    });
    const entryId = seeded.body.ops[0].entryId as string;
    await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${seeded.body.changesetId}/decide`, {
      decisions: [{ opId: seeded.body.ops[0].opId, action: 'accept' }],
    });
    const spaceId = (await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } })).spaceId;

    const amended = await ownerWrite(spaceId, {
      rationale: 'the owner rewrites the summary',
      ops: [{ op: 'amend', entryId, baseRevision: 1, changes: { summary: 'A summary the owner rewrote.' } }],
    });
    expectStatus(amended, 200, 'the owner amends');
    assert.equal(amended.body.ops[0].revision, 2);

    const stale = await propose({
      rationale: 'written against the revision it read',
      ops: [
        {
          op: 'amend',
          entryId,
          baseRevision: 1,
          changes: { summary: 'A summary written against revision one.' },
          sources: [{ kind: 'tool_call', ref: tool, quote: 'the first revision' }],
        },
      ],
    });
    expectStatus(stale, 409, 'a stale base revision is a 409');
    const conflict = stale.body.ops[0];
    assert.equal(conflict.status, 'conflict');
    assert.equal(conflict.baseRevision, 1);
    assert.equal(conflict.currentRevision, 2, 'the answer carries the revision the entry is at now');
    assert.equal(conflict.current.summary, 'A summary the owner rewrote.', 'and what it says now');
    assert.ok(conflict.diff.length > 0, 'with a diff of the two');
    assert.equal(
      await h.prisma.wikiChangeset.count({ where: { ownerId: owner.id, status: 'pending' } }),
      0,
      'a request that recorded nothing left no changeset behind',
    );

    // The same op decided later is a conflict then too: the owner pressed on a card that had moved.
    const later = await propose({
      rationale: 'a proposal that will be stale by the time it is decided',
      ops: [
        {
          op: 'amend',
          entryId,
          baseRevision: 2,
          changes: { summary: 'A third summary.' },
          sources: [{ kind: 'tool_call', ref: tool, quote: 'said one thing' }],
        },
      ],
    });
    expectStatus(later, 200, 'written against the revision that is current now');
    assert.equal(later.body.ops[0].status, 'pending');
    await ownerWrite(spaceId, {
      rationale: 'the owner moves it on again',
      ops: [{ op: 'amend', entryId, baseRevision: 2, changes: { summary: 'A fourth summary.' } }],
    });
    const decided = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${later.body.changesetId}/decide`, {
      decisions: [{ opId: later.body.ops[0].opId, action: 'accept' }],
    });
    expectStatus(decided, 200, 'the decision is recorded');
    const op = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: toUuid(later.body.ops[0].opId) } });
    assert.equal(op.decision, 'conflict', 'an acceptance of a stale op applies nothing');
    const entry = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } });
    assert.equal(entry.currentRevision, 3, 'and the entry is where the owner left it');
    assert.equal(entry.summary, 'A fourth summary.');
  });

  await t.test('a replayed idempotency key returns the recorded answer and writes nothing', async () => {
    const owner = await account(h, 'keys');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/keys.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'it happened once');
    const body = {
      rationale: 'sent twice because the first answer was lost',
      idempotencyKey: `key-${randomUUID()}`,
      ops: [addOp({ title: 'An op recorded once' }, [{ kind: 'tool_call', ref: tool, quote: 'happened once' }])],
    };
    const send = (payload: Record<string, unknown>) =>
      call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', payload);

    const first = await send(body);
    expectStatus(first, 200, 'the first send');
    const replay = await send(body);
    expectStatus(replay, 200, 'the same request, resent');
    assert.equal(replay.body.replayed, true, 'the answer says it is a replay');
    assert.equal(replay.body.changesetId, first.body.changesetId, 'and it is the same changeset');
    assert.equal(replay.body.ops[0].opId, first.body.ops[0].opId);
    assert.equal(replay.body.ops[0].entryId, first.body.ops[0].entryId);
    assert.equal(await h.prisma.wikiEntry.count({ where: { ownerId: owner.id } }), 1, 'nothing was recorded twice');
    assert.equal(await h.prisma.wikiChangeset.count({ where: { ownerId: owner.id } }), 1);
    assert.equal(await h.prisma.wikiChangesetOp.count({ where: { ownerId: owner.id } }), 1);

    const reused = await send({
      ...body,
      ops: [addOp({ title: 'A different op under the same key' }, [{ kind: 'tool_call', ref: tool, quote: 'happened once' }])],
    });
    expectStatus(reused, 409, 'the same key with another request is refused');
    assert.equal(reused.body.code, 'WIKI_IDEMPOTENCY_KEY_REUSED');
    assert.equal(await h.prisma.wikiEntry.count({ where: { ownerId: owner.id } }), 1);
  });

  await t.test('a dry run answers as the request would and records nothing', async () => {
    const owner = await account(h, 'dry');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/dry.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'a rehearsal is not a record');
    const answer = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'checking before proposing',
      dryRun: true,
      ops: [
        addOp({ title: 'A rehearsal of an add' }, [{ kind: 'tool_call', ref: tool, quote: 'not a record' }]),
        addOp({ title: 'TEST_WRITE_CHECK' }, [{ kind: 'tool_call', ref: tool, quote: 'a rehearsal' }]),
      ],
    });
    expectStatus(answer, 200, 'a dry run answers');
    assert.equal(answer.body.changesetId, null);
    assert.equal(answer.body.replayed, false);
    assert.equal(answer.body.ops[0].status, 'pending');
    assert.equal(answer.body.ops[0].opId, null, 'a dry run records no op');
    assert.equal(answer.body.ops[0].entryId, null);
    assert.equal(answer.body.ops[1].status, 'refused', 'and it still refuses what the request would');
    assert.equal(refusalOf(answer).code, 'WIKI_PROBE_REFUSED');
    assert.equal(await h.prisma.wikiEntry.count({ where: { ownerId: owner.id } }), 0);
    assert.equal(await h.prisma.wikiChangeset.count({ where: { ownerId: owner.id } }), 0);
  });

  await t.test('a title that reads as a tool probe is refused, and knowledge that mentions testing is not', async () => {
    const owner = await account(h, 'probe');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/probe.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'the tool works');
    const propose = (title: string) =>
      call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
        rationale: 'a title',
        ops: [addOp({ title }, [{ kind: 'tool_call', ref: tool, quote: 'the tool works' }])],
      });

    for (const title of ['TEST_WRITE_CHECK', 'test', 'probe 2']) {
      const refused = await propose(title);
      expectStatus(refused, 422, `"${title}" is a probe`);
      const refusal = refusalOf(refused);
      assert.equal(refusal.code, 'WIKI_PROBE_REFUSED');
      assert.match(refusal.message, /do not retry/u, 'the agent is told the tool works and not to retry');
    }
    expectStatus(await propose('Testing strategy for a pg spec'), 200, 'a title that mentions testing is knowledge');
    assert.equal(await h.prisma.wikiEntry.count({ where: { ownerId: owner.id } }), 1);
  });

  await t.test('a near neighbour is answered with the add, and a rejected one says why it was rejected', async () => {
    const owner = await account(h, 'neighbours');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/neighbours.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'it happened twice');
    const propose = (summary: string) =>
      call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
        rationale: 'the same thing, twice',
        ops: [addOp({ title: 'A pg spec that skips itself proves nothing', summary }, [{ kind: 'tool_call', ref: tool, quote: 'happened twice' }])],
      });

    const first = await propose('A spec that skips itself proves nothing at all about what it tests.');
    expectStatus(first, 200, 'the first one lands');
    await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${first.body.changesetId}/decide`, {
      decisions: [{ opId: first.body.ops[0].opId, action: 'reject', reason: 'duplicate' }],
    });
    const second = await propose('A spec that skips itself proves nothing at all about what it tests either.');
    expectStatus(second, 200, 'a neighbour refuses nothing: the score cannot tell duplicate from related');
    const similar = second.body.ops[0].similar as Array<{ id: string; status: string; rejectedReason?: string }>;
    assert.ok(similar.length >= 1, 'the near neighbour is named');
    assert.equal(similar[0].id, first.body.ops[0].entryId);
    assert.equal(similar[0].rejectedReason, 'duplicate', 'and a rejected neighbour says why it was rejected');
  });

  await t.test('a turn may hold five ops and not six', async () => {
    const owner = await account(h, 'quota');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/quota.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'one too many');
    const source = [{ kind: 'tool_call', ref: tool, quote: 'one too many' }];
    const ops = Array.from({ length: WIKI_LIMITS.opsPerTurn + 1 }, (_unused, index) =>
      addOp({ title: `An op numbered ${index + 1}` }, source),
    );
    const answer = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'one more than a turn may hold',
      ops,
    });
    expectStatus(answer, 200, 'the ones within the limit are recorded');
    assert.deepEqual(
      (answer.body.ops as Array<{ status: string }>).map((outcome) => outcome.status),
      ['pending', 'pending', 'pending', 'pending', 'pending', 'refused'],
    );
    assert.equal(refusalOf(answer).code, 'WIKI_QUOTA');
  });
});

// ── what the write paths announce ───────────────────────────────────────────────────────────────

/**
 * `wiki.changed`: the nudge that says one of the owner's spaces moved, so the wiki pages and the
 * Review queue re-read instead of waiting out their poll. Owner-scoped, carrying the SPACE's id and
 * nothing else, and published by the two write paths alone (contract `realtime`).
 *
 * A nudge and nothing more: every assertion below would still hold of a wiki whose announcements
 * were all dropped — nothing about a write is decided by one (contract `realtime.correctness`).
 * What is under test is only that the two write paths make it, once, and stay quiet for the three
 * things that changed nothing.
 *
 * WHERE the call sits — after the write's transaction commits, and never inside the retry closure —
 * is not witnessed here, and cannot be from this side of the hub: a stand-in learns only that it was
 * called, and a read on another connection loses the race against the commit either way (tried;
 * moving the publish inside the transaction leaves every assertion below green). It is a property of
 * the call site in `wiki.service.ts`, which is why that site is the one place the predicate lives.
 */
test('0307 · a recorded write announces its space, and only a recorded write does', { skip, concurrency: 1, timeout: 300_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'announced');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/announced.git' });
  const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
  const tool = await toolCall(h, mine, 'Bash', 'the announcement names the space, and nothing else');
  // The hub is this process's, and every case in the file publishes into it: only this account's.
  const announced = () => h.announced.filter((one) => one.ownerId === owner.id);
  const send = (payload: Record<string, unknown>) =>
    call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', payload);

  const body = {
    rationale: 'the first thing this space records',
    idempotencyKey: `key-${randomUUID()}`,
    ops: [addOp({ title: 'An announcement names its space' }, [{ kind: 'tool_call', ref: tool, quote: 'names the space' }])],
  };
  const first = await send(body);
  expectStatus(first, 200, 'the proposal is recorded');
  const spaceId = (await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(first.body.changesetId) } })).spaceId;
  assert.deepEqual(
    announced().map((one) => one.spaceId),
    [spaceId],
    'exactly one announcement, naming the space the changeset landed in — not its entry or op',
  );

  // An idempotent replay changed nothing, so it announces nothing: a client that re-read on it would
  // be re-reading a write that already happened and was already announced.
  const replay = await send(body);
  expectStatus(replay, 200, 'the same request under the same key');
  assert.equal(replay.body.replayed, true);
  assert.equal(announced().length, 1, 'a replay announces nothing');

  // A dry run records nothing by construction.
  expectStatus(await send({ ...body, dryRun: true, idempotencyKey: undefined }), 200, 'a rehearsal');
  assert.equal(announced().length, 1, 'a dry run announces nothing');

  // A request none of whose ops was recorded left no changeset behind.
  const refused = await send({
    rationale: 'nothing here was recorded',
    ops: [addOp({ title: 'TEST_WRITE_CHECK' }, [{ kind: 'tool_call', ref: tool, quote: 'names the space' }])],
  });
  expectStatus(refused, 422, 'every op is refused');
  assert.equal(refusalOf(refused).code, 'WIKI_PROBE_REFUSED');
  assert.equal(announced().length, 1, 'a request that recorded nothing announces nothing');

  // The owner's own answer moves the space's review queue and its entries, and names the same space.
  const decided = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${first.body.changesetId}/decide`, {
    decisions: [{ opId: first.body.ops[0].opId, action: 'accept' }],
  });
  expectStatus(decided, 200, 'the owner accepts');
  assert.deepEqual(
    announced().map((one) => one.spaceId),
    [spaceId, spaceId],
    'a decision announces the same space, and one decision is one announcement',
  );
});

// ── tenancy, the owner channel, and the credentials each door takes ─────────────────────────────

test('0307 · who may reach the wiki, and with what', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test("another account's space, entry and changeset are 404s on both doors", async () => {
    const owner = await account(h, 'tenant');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/tenant.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'this belongs to one account');
    const seeded = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: "one account's entry",
      ops: [addOp({ title: 'An entry one account owns' }, [{ kind: 'tool_call', ref: tool, quote: 'one account' }])],
    });
    expectStatus(seeded, 200, 'the owner of the entry proposes');
    const entryId = seeded.body.ops[0].entryId as string;
    const spaceId = (await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } })).spaceId;

    const thief = await account(h, 'the other account');
    const thiefMachine = await runner(h, thief.id);
    const thiefWs = await workspace(h, thief.id, { repoUrl: 'github.com/orbit/tenant.git' });
    const thiefSession = await session(h, thief.id, { workspaceId: thiefWs, runnerId: thiefMachine.id });
    expectStatus(await call(h, { bearer: thief.bearer }, 'GET', `/wiki/entries/${entryId}`), 404, 'a foreign entry read');
    expectStatus(await call(h, { bearer: thief.bearer }, 'GET', `/wiki/spaces/${spaceId}`), 404, 'a foreign space read');
    expectStatus(await call(h, { bearer: thief.bearer }, 'GET', `/wiki/spaces/${spaceId}/entries`), 404, 'a foreign space listed');
    expectStatus(
      await call(h, { bearer: thief.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { push: false }),
      404,
      'a foreign space patched',
    );
    expectStatus(
      await call(h, { bearer: thief.bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId: thiefWs }),
      404,
      'a foreign space bound',
    );
    expectStatus(
      await call(h, { bearer: thief.bearer }, 'POST', `/wiki/spaces/${spaceId}/changesets`, {
        rationale: 'x',
        ops: [addOp({ title: 'Theirs' }, [])],
      }),
      404,
      'a foreign space written into',
    );
    expectStatus(
      await call(h, { bearer: thief.bearer }, 'POST', `/wiki/changesets/${seeded.body.changesetId}/decide`, {
        decisions: [{ opId: seeded.body.ops[0].opId, action: 'accept' }],
      }),
      404,
      'a foreign changeset decided',
    );
    expectStatus(
      await call(h, { runner: thiefMachine.token, headers: { 'x-orbit-session-id': thiefSession } }, 'GET', `/runner/wiki/entries/${entryId}`),
      404,
      'a foreign entry read from the runner door',
    );
    expectStatus(
      await call(h, { runner: thiefMachine.token, headers: { 'x-orbit-session-id': thiefSession } }, 'POST', '/runner/wiki/changesets', {
        rationale: "an op about somebody else's entry",
        ops: [{ op: 'challenge', entryId, reason: 'not mine to touch' }],
      }),
      404,
      'a foreign entry named by an op',
    );
    const entry = await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } });
    assert.equal(entry.status, 'proposed', 'nothing the other account did changed anything');
    assert.equal(entry.challenged, false);
    assert.equal(
      await h.prisma.wikiEntry.count({ where: { ownerId: thief.id } }),
      0,
      'and the other account holds no entry of its own out of any of it',
    );
  });

  await t.test('a decide that carries a session header is refused, whatever that session is', async () => {
    const owner = await account(h, 'channel');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/channel.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'a proposal the owner has not answered');
    const seeded = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'something to decide',
      ops: [addOp({ title: 'An op that waits for a person' }, [{ kind: 'tool_call', ref: tool, quote: 'not answered' }])],
    });
    const decision = { decisions: [{ opId: seeded.body.ops[0].opId, action: 'accept' }] };

    const withSession: Array<Record<string, string>> = [
      { 'x-orbit-session-id': mine },
      { 'x-orbit-session-token': 'a-proof' },
      { 'x-orbit-session-anything': 'x' },
    ];
    for (const headers of withSession) {
      const refused = await call(h, { bearer: owner.bearer, headers }, 'POST', `/wiki/changesets/${seeded.body.changesetId}/decide`, decision);
      expectStatus(refused, 403, `a decide carrying ${Object.keys(headers)[0]} is refused`);
      assert.equal(refused.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
    }
    const op = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: toUuid(seeded.body.ops[0].opId) } });
    assert.equal(op.decision, 'pending', 'and nothing was decided');

    // The same decision, on the owner channel with no acting session, goes through.
    expectStatus(
      await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${seeded.body.changesetId}/decide`, decision),
      200,
      "the owner's own call decides it",
    );
  });

  await t.test('a service token is refused on both doors and writes nothing', async () => {
    const owner = await account(h, 'service');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/service.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    // Minted by the real authorizer: a token this account could really hold, not a made-up string.
    const minted = await new ServiceTokenAuthorizer(
      h.prisma as unknown as PrismaService,
      new JwtService({ secret: 'wiki-spec-service-token' }),
    ).mint({ id: machine.id, ownerId: owner.id }, { scopes: ['session:get'], ttlSeconds: 3_600 });

    const onRunner = await call(h, { runner: minted.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'a bridge token asking for the wiki',
      ops: [addOp({ title: 'A bridge token proposes' }, [{ kind: 'turn', session: 'self' }])],
    });
    expectStatus(onRunner, 401, 'the runner door refuses a service token');
    expectStatus(await call(h, { bearer: minted.token }, 'GET', '/wiki/spaces'), 401, 'the user door refuses a service token');
    assert.equal(await h.prisma.wikiEntry.count({ where: { ownerId: owner.id } }), 0);
    assert.equal(await h.prisma.wikiChangeset.count({ where: { ownerId: owner.id } }), 0);
  });

  await t.test('a session that verifies, forems or judges work is excluded from the wiki', async () => {
    const owner = await account(h, 'excluded');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/excluded.git' });
    const subject = await task(h, owner.id);
    const verifier = await session(h, owner.id, {
      workspaceId: ws,
      runnerId: machine.id,
      taskId: await task(h, owner.id, { verifiesTaskId: subject }),
    });
    const foreman = await session(h, owner.id, {
      workspaceId: ws,
      runnerId: machine.id,
      taskId: await task(h, owner.id, { isForeman: true }),
    });
    const judging = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, dispatchOrigin: 'PROJECT_COORDINATOR' });

    for (const excluded of [verifier, foreman, judging]) {
      const refused = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': excluded } }, 'POST', '/runner/wiki/changesets', {
        rationale: 'knowledge is not evidence',
        ops: [addOp({ title: 'An op from a session that judges' }, [{ kind: 'turn', session: 'self' }])],
      });
      expectStatus(refused, 403, 'a session that judges work is refused');
      assert.equal(refused.body.code, 'WIKI_SESSION_EXCLUDED');
    }
    assert.equal(await h.prisma.wikiEntry.count({ where: { ownerId: owner.id } }), 0);
  });

  await t.test("a session another machine hosts is not this door's caller", async () => {
    const owner = await account(h, 'notmine');
    const machine = await runner(h, owner.id);
    const otherMachine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/notmine.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: otherMachine.id });
    const refused = await call(
      h,
      { runner: machine.token, headers: { 'x-orbit-session-id': mine } },
      'GET',
      `/runner/wiki/entries/${randomUUID()}`,
    );
    expectStatus(refused, 403, "a session another machine hosts is not this door's caller");
  });
});

// ── redaction ───────────────────────────────────────────────────────────────────────────────────

test('0307 · a credential in a submission is taken out of what is stored', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test('a secret in a quote, and an owner env value in a title, are redacted', async () => {
    const owner = await account(h, 'redaction');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, {
      repoUrl: 'github.com/orbit/redaction.git',
      env: { SPEC_DEPLOY_KEY: 's3cret-deploy-value' },
    });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'connect with postgres://orbit:hunter2@db:5432/orbit and it works');
    const propose = (ops: unknown[]) =>
      call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
        rationale: 'what was in the log line',
        ops,
      });

    const secret = await propose([
      addOp({ title: 'A connection string in a log line' }, [
        { kind: 'tool_call', ref: tool, quote: 'postgres://orbit:hunter2@db:5432/orbit' },
      ]),
    ]);
    expectStatus(secret, 200, 'the op is recorded');
    const op = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: toUuid(secret.body.ops[0].opId) } });
    assert.equal(JSON.stringify(op.payload).includes('hunter2'), false, 'the password is not in the stored payload');
    assert.match(JSON.stringify(op.payload), /\[redacted\]/u);

    // The stored quote is the redacted one, so nothing this account holds carries the credential.
    const revision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: toUuid(secret.body.ops[0].entryId) } });
    const stored = await h.prisma.wikiSource.findFirstOrThrow({ where: { revisionId: revision.id } });
    assert.equal(stored.quote?.includes('hunter2') ?? false, false, 'the stored quote is redacted too');
    assert.equal(stored.quoteVerified, false, 'and a quote that changed is no longer a verbatim quote');

    const envValue = await propose([
      addOp(
        { title: 'A deploy key that leaked into a summary', summary: 'It was s3cret-deploy-value in the log.' },
        [{ kind: 'turn', session: 'self' }],
      ),
    ]);
    expectStatus(envValue, 200, "a value only this account's environment holds is replaced wherever it appears");
    const second = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: toUuid(envValue.body.ops[0].opId) } });
    assert.equal(JSON.stringify(second.payload).includes('s3cret-deploy-value'), false);
    assert.match(JSON.stringify(second.payload), /\[redacted\]/u);
  });
});

// ── the reads the owner's pages use ─────────────────────────────────────────────────────────────

test('0307 · a space reads back what it holds', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test("the owner's spaces carry their pending count, and review and the entries read back", async () => {
    const owner = await account(h, 'reader');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id, { repoUrl: 'github.com/orbit/reader.git' });
    const mine = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
    const tool = await toolCall(h, mine, 'Bash', 'two things to review');
    const proposed = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': mine } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'two proposals',
      ops: [
        addOp({ title: 'A pg spec that skips itself proves nothing' }, [{ kind: 'tool_call', ref: tool, quote: 'two things' }]),
        addOp({ title: 'A pg spec that skips itself proves nothing either' }, [{ kind: 'tool_call', ref: tool, quote: 'to review' }]),
      ],
    });
    expectStatus(proposed, 200, 'two proposals land');

    const spaces = await call(h, { bearer: owner.bearer }, 'GET', '/wiki/spaces');
    expectStatus(spaces, 200, 'the owner lists their spaces');
    assert.equal(spaces.body.length, 1);
    assert.equal(spaces.body[0].pendingOps, 2, 'the sidebar number is the pending ops');
    assert.equal(spaces.body[0].settings.push, true, 'a new space pushes by default');
    assert.equal(spaces.body[0].settings.autoAcceptReinforce, true);

    const review = await call(h, { bearer: owner.bearer }, 'GET', '/wiki/review');
    expectStatus(review, 200, 'the review queue');
    assert.equal(review.body.length, 1);
    assert.equal(review.body[0].ops.length, 2);
    assert.equal(review.body[0].ops[1].similar[0]?.id, proposed.body.ops[0].entryId, 'an op carries the neighbours already in the space');

    const entryId = proposed.body.ops[0].entryId as string;
    const one = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/entries/${entryId}?include=sources,history`);
    expectStatus(one, 200, 'one entry');
    assert.equal(one.body.sources.length, 1);
    assert.equal(one.body.sources[0].quoteVerified, true);
    assert.equal(one.body.history.length, 1);
    assert.equal(one.body.history[0].authorKind, 'agent');

    const listed = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${spaces.body[0].id}/entries?kind=pitfall&status=proposed`);
    expectStatus(listed, 200, 'the entries of a space');
    assert.equal(listed.body.length, 2);
    const filtered = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${spaces.body[0].id}/entries?kind=principle`);
    assert.equal(filtered.body.length, 0);
  });
});
