/**
 * The near-neighbour lookup every add runs, at the size a maintenance run or an import writes into.
 *
 * `WikiService.nearNeighbours` answers `similar[]` for every add and supersede: the five entries of the
 * space whose search text is most trigram-similar to the draft's title and summary. It runs inside the
 * changeset's one interactive transaction, which Prisma closes after 5 s. On production, at 2,606
 * entries, it was planned as a scan of the space that tested every row at ~0.1 ms a row, so a large
 * space took one to three ops per changeset. Migration 0313 prices that test for the planner; the
 * lookup hands the draft's text over as an InitPlan output, and asks for a rejection's reason only for
 * the rows it returns.
 *
 * The data, bulk-inserted in SQL: first a space of 2,606 entries alone in the table — production as it
 * was when its writes slowed down — and then beside it one space of 10,000 active entries and another
 * owner's space of 5,000. Their text comes from a seeded generator shaped like the preview space's —
 * mixed runs of CJK and Latin words, Zipf-distributed, a few hundred characters an entry — heavier than
 * production if anything: a generated draft's trigrams pass the index's bound on ~4% of the entries on
 * average, against ~2.5% measured on production. Planted in every space: one family of
 * near-duplicates, with a tie on score, a rejected member and one past fifth place.
 *
 * Five claims, each its own case:
 *   1. at production's size the lookup reads the trigram index, where before 0313 it read and tested
 *      every entry of the space;
 *   2. the other owner's entries never reach this owner's `similar[]`, though they are neighbours in
 *      their own space;
 *   3. `similar[]` is what the lookup as it stood before 0313 returned: the same five in the same
 *      order, and a rejected neighbour still with the reason it was rejected;
 *   4. after an explicit ANALYZE the lookup among the 10,000 and the 5,000 reads the trigram index,
 *      never scans the table, and asks for a reason once per row it returns, not once per candidate;
 *   5. thirty adds into the 10,000 commit, within 3 s of the same thirty into an empty space in the
 *      same run. Relative, because the absolute time of a changeset is mostly its twelve statements an
 *      add (`recordOp`, `applyOp`, `recomputeFlags`) and the host's load, neither of which this is about.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-scale.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every row belongs to an account it created.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import { Prisma, type PrismaClient } from '@prisma/client';
import { toUuid } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { RealtimeService } from '../realtime/realtime.service';
import { WikiController } from './wiki.controller';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

const BIG = 10_000;
const OTHER = 5_000;
/** The preview space when its writes slowed to one to three ops a changeset (2026-09-27). */
const PRODUCTION = 2_606;
const OPS = 30;
/** What the thirty adds into the 10,000 may take over the same thirty into an empty space. */
const OVER_BASELINE_MS = 3_000;

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  /** bearer → the account it was issued to */
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const service = new WikiService(prisma as unknown as PrismaService, {
      publishWikiChanged: () => undefined,
    } as unknown as RealtimeService);

    @Module({
      controllers: [WikiController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiScaleModule {}

    const app = await NestFactory.create(WikiScaleModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
  ms: number;
}

/** One owner-door changeset, timed from the request to the answer — which comes after the commit. */
async function propose(h: Harness, owner: Account, spaceId: string, body: Record<string, unknown>): Promise<Answer> {
  const started = performance.now();
  const response = await fetch(`${h.base}/api/wiki/spaces/${spaceId}/changesets`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${owner.bearer}` },
    body: JSON.stringify({ rationale: 'the near-neighbour lookup at scale', ...body }),
  });
  const text = await response.text();
  const ms = performance.now() - started;
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed, ms };
}

interface Similar {
  id: string;
  score: number;
  rejectedReason: string | null;
}

/** An op's `similar[]` as raw ids — the door answers in public ids — with the score and the reason. */
function similarOf(answer: Answer, seq = 0): Similar[] {
  assert.equal(answer.status, 200, `the owner's changeset: answered ${answer.status} ${JSON.stringify(answer.body)}`);
  const op = (answer.body.ops as Array<{ status: string; similar?: Array<Record<string, unknown>> }>)[seq];
  assert.notEqual(op.status, 'refused', `op ${seq} was refused: ${JSON.stringify(op)}`);
  return (op.similar ?? []).map((s) => ({
    id: toUuid(String(s.id)),
    score: Number(s.score),
    rejectedReason: (s.rejectedReason as string | undefined) ?? null,
  }));
}

// ── the corpus ──────────────────────────────────────────────────────────────────────────────────

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** The words this codebase's wiki is written in, most frequent first; the long tail is made up. */
const CORE_WORDS = `worktree apiserver runner session task project migration prisma index trigram merge branch commit
review wiki entry space owner agent coordinator acceptance spec test build deploy release version client web ios
macos swift schema column table query plan cursor queue lease heartbeat timeout retry transaction lock row
container docker compose postgres node typescript shared contract door route controller service module cache
push search anchor source quote revision changeset op decision pitfall recipe concept convention principle
state status trust flag challenge reject accept promote supersede retire verify fixture overlay symlink tsc
vitest render layout sheet menu toolbar sidebar badge count list card button label tint theme dark light
provider model engine claude codex kimi token budget usage quota limit breaker spot check mode tiered manual
automatic import maintenance loader batch idempotency key replay conflict snapshot isolation vacuum analyze
the a to of and in is for on with not be it that this when from by as are at or run an if`.split(/\s+/u);

interface Vocabulary {
  latin: string[];
  cjk: string[];
}

let vocabulary: Vocabulary | undefined;

/** 20,000 Latin words and 3,000 ideographs, the same every run. */
function words(): Vocabulary {
  if (vocabulary) return vocabulary;
  const rand = mulberry32(12_345);
  const latin = [...CORE_WORDS];
  const seen = new Set(latin);
  while (latin.length < 20_000) {
    let word = '';
    for (let i = 3 + Math.floor(rand() * 8); i > 0; i -= 1) word += String.fromCharCode(97 + Math.floor(rand() * 26));
    if (!seen.has(word)) {
      seen.add(word);
      latin.push(word);
    }
  }
  const cjk: string[] = [];
  const seenCjk = new Set<string>();
  while (cjk.length < 3_000) {
    const ideograph = String.fromCodePoint(0x4e00 + Math.floor(rand() * 0x5000));
    if (!seenCjk.has(ideograph)) {
      seenCjk.add(ideograph);
      cjk.push(ideograph);
    }
  }
  vocabulary = { latin, cjk };
  return vocabulary;
}

/** Rank r drawn with weight 1/r, the way words are used. */
function zipf(n: number, rand: () => number): () => number {
  const cdf = new Float64Array(n);
  let sum = 0;
  for (let i = 0; i < n; i += 1) {
    sum += 1 / (i + 1);
    cdf[i] = sum;
  }
  return () => {
    const x = rand() * sum;
    let lo = 0;
    let hi = n - 1;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (cdf[mid] < x) lo = mid + 1;
      else hi = mid;
    }
    return lo;
  };
}

interface Text {
  title: string;
  summary: string;
  fields: { definition: string; boundaries: string };
}

/** A seeded stream of concept entries: runs of one to eight ideographs between Latin words. */
function corpus(seed: number): () => Text {
  const rand = mulberry32(seed);
  const { latin, cjk } = words();
  const pickLatin = zipf(latin.length, rand);
  const pickCjk = zipf(cjk.length, rand);
  const phrase = (min: number, max: number): string => {
    const parts: string[] = [];
    for (let n = min + Math.floor(rand() * (max - min + 1)); n > 0; n -= 1) {
      if (rand() < 0.5) {
        parts.push(latin[pickLatin()]);
      } else {
        let run = '';
        for (let k = 1 + Math.floor(rand() * 8); k > 0; k -= 1) run += cjk[pickCjk()];
        parts.push(rand() < 0.3 ? `${run}，` : run);
      }
    }
    return parts.join(' ');
  };
  const clip = (text: string, max: number): string => (text.length <= max ? text : text.slice(0, max).trimEnd());
  return () => ({
    title: clip(phrase(3, 7), 120),
    summary: clip(phrase(8, 18), 280),
    fields: { definition: phrase(8, 18), boundaries: phrase(5, 12) },
  });
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-scale-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

/** A Manual space: the owner's own writes apply at once in every mode, so the mode only keeps it plain. */
async function space(h: Harness, ownerId: string, slug: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "wiki_space"("id","owner_id","slug","title","settings") VALUES ($1,$2,$3,'spec',$4)`,
    [id, ownerId, slug, JSON.stringify({ reviewMode: 'manual' })],
  );
  return id;
}

/** `count` active entries in one statement per 2,000 — never through the door, which is what is timed. */
async function bulkEntries(h: Harness, ownerId: string, spaceId: string, count: number, seed: number): Promise<void> {
  const next = corpus(seed);
  const since = Date.parse('2026-01-01T00:00:00Z');
  for (let from = 0; from < count; from += 2_000) {
    const ids: string[] = [];
    const titles: string[] = [];
    const summaries: string[] = [];
    const fields: string[] = [];
    const recorded: string[] = [];
    for (let i = from; i < Math.min(count, from + 2_000); i += 1) {
      const text = next();
      ids.push(randomUUID());
      titles.push(text.title);
      summaries.push(text.summary);
      fields.push(JSON.stringify(text.fields));
      recorded.push(new Date(since + i * 60_000).toISOString());
    }
    await h.sql.query(
      `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision",
                                "title","summary","fields","valid_from","recorded_at")
       SELECT id, $6::uuid, $7::uuid, 'concept', 'active', 'confirmed', 1, title, summary, fields::jsonb,
              recorded::timestamptz, recorded::timestamptz
         FROM unnest($1::uuid[], $2::text[], $3::text[], $4::text[], $5::text[])
              AS input(id, title, summary, fields, recorded)`,
      [ids, titles, summaries, fields, recorded, ownerId, spaceId],
    );
  }
}

/** The draft whose neighbours are looked up: its title and summary are the text the lookup matches. */
const DRAFT: Text = {
  title: 'Migration numbers collide only when two branches merge',
  summary: '两条分支各取下一个空号 迁移撞号 each tree stays green and the ledger breaks after the merge',
  fields: { definition: 'Two migrations share a number', boundaries: 'Not a Prisma bug' },
};

/**
 * Its near-duplicates, strongest first: the similarity of each entry's search text to the draft's,
 * measured when this was written, is in the comment beside it. `twin` and `same` score alike and the
 * later-recorded comes first; `rejected` was rejected twice, most recently as a duplicate; `sixth` is a
 * neighbour one place past the five; `below` is under pg_trgm's 0.3 and no neighbour at all.
 */
const FAMILY: Array<{ key: string; text: Text; status?: 'rejected'; recordedAt: string }> = [
  { key: 'twin', recordedAt: '2026-06-01T00:00:07Z', text: DRAFT }, // 0.843
  { key: 'same', recordedAt: '2026-06-01T00:00:02Z', text: DRAFT }, // 0.843
  {
    key: 'close', // 0.643
    recordedAt: '2026-06-01T00:00:05Z',
    text: {
      title: 'Migration numbers collide when two branches merge',
      summary: '两条分支各取下一个空号 迁移撞号 each tree stays green until the merge',
      fields: DRAFT.fields,
    },
  },
  {
    key: 'rejected', // 0.559
    status: 'rejected',
    recordedAt: '2026-06-01T00:00:03Z',
    text: {
      title: 'Two branches can take the same migration number',
      summary: '迁移撞号 each tree stays green and the ledger breaks after the merge',
      fields: { definition: 'Renumber the later one', boundaries: 'Holes in the numbering are fine' },
    },
  },
  {
    key: 'fifth', // 0.532
    recordedAt: '2026-06-01T00:00:06Z',
    text: {
      title: 'Migration numbers collide after a merge',
      summary: '两条分支各取下一个空号 迁移撞号 each tree is green on its own',
      fields: DRAFT.fields,
    },
  },
  {
    key: 'sixth', // 0.358
    recordedAt: '2026-06-01T00:00:04Z',
    text: {
      title: 'Migration numbers collide',
      summary: '迁移撞号 the ledger breaks after the merge',
      fields: {
        definition: 'Renumber the later migration to the next free number and sync its references',
        boundaries: 'Holes in the numbering are fine; duplicates below 0246 are exempt',
      },
    },
  },
  {
    key: 'below', // 0.245
    recordedAt: '2026-06-01T00:00:01Z',
    text: {
      title: 'Renumber the later migration',
      summary: 'the ledger test names the colliding pair',
      fields: { definition: 'Renumber the later one', boundaries: 'Holes are fine' },
    },
  },
];

/** The family in one space, and the two decisions that rejected its `rejected` member. */
async function plantFamily(h: Harness, ownerId: string, spaceId: string): Promise<Record<string, string>> {
  const ids: Record<string, string> = {};
  for (const member of FAMILY) {
    const id = randomUUID();
    ids[member.key] = id;
    const rejected = member.status === 'rejected';
    // 0307's lineage CHECKs: a rejected entry's trust is `proposed`, and a terminal status has retired_at.
    await h.sql.query(
      `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision",
                                "title","summary","fields","valid_from","recorded_at","retired_at")
       VALUES ($1,$2,$3,'concept',$4,$5,1,$6,$7,$8,$9,$9,$10)`,
      [
        id,
        ownerId,
        spaceId,
        rejected ? 'rejected' : 'active',
        rejected ? 'proposed' : 'confirmed',
        member.text.title,
        member.text.summary,
        JSON.stringify(member.text.fields),
        member.recordedAt,
        rejected ? member.recordedAt : null,
      ],
    );
  }
  const changeset = randomUUID();
  await h.sql.query(
    `INSERT INTO "wiki_changeset"("id","owner_id","space_id","origin","rationale","status","decided_at")
     VALUES ($1,$2,$3,'agent','a proposal the owner rejected','settled',now())`,
    [changeset, ownerId, spaceId],
  );
  for (const [seq, reason, decidedAt] of [
    [0, 'not_useful', '2026-06-02T00:00:00Z'],
    [1, 'duplicate', '2026-06-03T00:00:00Z'],
  ] as const) {
    await h.sql.query(
      `INSERT INTO "wiki_changeset_op"("id","changeset_id","owner_id","seq","op","payload","decision",
                                       "decision_reason","decided_at","result_entry_id","result_revision")
       VALUES ($1,$2,$3,$4,'add','{}','rejected',$5,$6,$7,1)`,
      [randomUUID(), changeset, ownerId, seq, reason, decidedAt, ids.rejected],
    );
  }
  return ids;
}

/**
 * Where the space settles once autovacuum has caught up with a bulk load: GIN's pending list merged
 * into the index (every search scans what is still pending), and statistics that know the table's
 * size. Done here, and not left to the autovacuum clock, so every run starts the same.
 */
async function settle(h: Harness): Promise<void> {
  await h.sql.query('VACUUM (ANALYZE) "wiki_entry"');
  await h.sql.query('VACUUM (ANALYZE) "wiki_changeset_op"');
}

interface ProductionFixture {
  owner: Account;
  /** A space of 2,606 entries, alone in the table as the preview space was on production. */
  productionSized: string;
}

let production: Promise<ProductionFixture> | undefined;

function productionLoaded(h: Harness): Promise<ProductionFixture> {
  production ??= (async () => {
    const owner = await account(h, 'the owner of the big space');
    const productionSized = await space(h, owner.id, 'production-sized');
    await bulkEntries(h, owner.id, productionSized, PRODUCTION - FAMILY.length + 1, 4);
    await plantFamily(h, owner.id, productionSized);
    await settle(h);
    return { owner, productionSized };
  })();
  return production;
}

interface Fixture extends ProductionFixture {
  other: Account;
  big: string;
  otherSpace: string;
  family: Record<string, string>;
  otherFamily: Record<string, string>;
}

let fixture: Promise<Fixture> | undefined;

function loaded(h: Harness): Promise<Fixture> {
  fixture ??= (async () => {
    const { owner, productionSized } = await productionLoaded(h);
    const other = await account(h, 'another owner');
    const big = await space(h, owner.id, 'ten-thousand');
    const otherSpace = await space(h, other.id, 'five-thousand');
    await bulkEntries(h, owner.id, big, BIG - FAMILY.length + 1, 1);
    await bulkEntries(h, other.id, otherSpace, OTHER - FAMILY.length + 1, 2);
    const family = await plantFamily(h, owner.id, big);
    const otherFamily = await plantFamily(h, other.id, otherSpace);
    await settle(h);
    return { owner, productionSized, other, big, otherSpace, family, otherFamily };
  })();
  return fixture;
}

// ── the lookup, before 0313 ─────────────────────────────────────────────────────────────────────

/**
 * The lookup as it stood before 0313, word for word (commit 1f64da2cc, `nearNeighbours`), with the
 * template's parameters numbered: $1 the draft's text, $2 the owner, $3 the space, $4 the excluded
 * entry. The "before" that `similar[]` is held to.
 */
const NEIGHBOURS_BEFORE_0313 = `
      SELECT e."id" AS "id",
             e."kind" AS "kind",
             e."title" AS "title",
             e."status" AS "status",
             e."trust" AS "trust",
             similarity(wiki_entry_search_text(e."title", e."summary", e."aliases", e."fields"), $1)::float8 AS "score",
             (SELECT o."decision_reason"
                FROM "wiki_changeset_op" o
               WHERE o."result_entry_id" = e."id" AND o."decision" = 'rejected'
               ORDER BY o."decided_at" DESC NULLS LAST
               LIMIT 1) AS "rejectedReason"
        FROM "wiki_entry" e
       WHERE e."owner_id" = $2::uuid
         AND e."space_id" = $3::uuid
         AND ($4::uuid IS NULL OR e."id" <> $4::uuid)
         AND wiki_entry_search_text(e."title", e."summary", e."aliases", e."fields") % $1
       ORDER BY "score" DESC, e."recorded_at" DESC
       LIMIT 5
    `;

/** The five as the lookup before 0313 found them — under the function's cost before 0313 too. */
async function neighboursBefore0313(h: Harness, ownerId: string, spaceId: string, exclude: string | null): Promise<Similar[]> {
  const text = `${DRAFT.title} ${DRAFT.summary}`.trim();
  await h.sql.query('BEGIN');
  try {
    await h.sql.query('ALTER FUNCTION "wiki_entry_search_text"(TEXT, TEXT, TEXT[], JSONB) COST 100');
    const rows = await h.sql.query<{ id: string; score: number; rejectedReason: string | null }>(
      NEIGHBOURS_BEFORE_0313,
      [text, ownerId, spaceId, exclude],
    );
    return rows.rows.map((row) => ({ id: row.id, score: Number(row.score), rejectedReason: row.rejectedReason }));
  } finally {
    await h.sql.query('ROLLBACK');
  }
}

// ── the plan ────────────────────────────────────────────────────────────────────────────────────

interface PlanNode {
  'Node Type': string;
  'Relation Name'?: string;
  'Index Name'?: string;
  'Index Cond'?: string;
  'Parent Relationship'?: string;
  'Subplan Name'?: string;
  'Actual Rows': number;
  'Actual Loops': number;
  'Rows Removed by Index Recheck'?: number;
  'Rows Removed by Filter'?: number;
  Plans?: PlanNode[];
}

function nodesOf(node: PlanNode): PlanNode[] {
  return [node, ...(node.Plans ?? []).flatMap(nodesOf)];
}

/** The service's own lookup — the statement it builds, captured rather than copied — explained. */
async function explainLookup(h: Harness, ownerId: string, spaceId: string): Promise<{ root: PlanNode; text: string }> {
  const captured: Prisma.Sql[] = [];
  const recorder = {
    $queryRaw: (statement: Prisma.Sql) => {
      captured.push(statement);
      return Promise.resolve([]);
    },
  };
  const lookup = (h.service as unknown as {
    nearNeighbours: (tx: unknown, owner: string, space: string, draft: Record<string, unknown>, exclude: string | null) => Promise<unknown>;
  }).nearNeighbours.bind(h.service);
  await lookup(recorder, ownerId, spaceId, { title: DRAFT.title, summary: DRAFT.summary }, null);
  assert.equal(captured.length, 1, 'the lookup is one statement');
  const statement = captured[0];
  const json = await h.sql.query<{ 'QUERY PLAN': Array<{ Plan: PlanNode }> }>(
    `EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) ${statement.text}`,
    statement.values as unknown[],
  );
  const text = await h.sql.query<{ 'QUERY PLAN': string }>(`EXPLAIN (ANALYZE, BUFFERS) ${statement.text}`, statement.values as unknown[]);
  return { root: json.rows[0]['QUERY PLAN'][0].Plan, text: text.rows.map((row) => row['QUERY PLAN']).join('\n') };
}

/** A plan is a function of the statistics as much as of the data: taken now, not whenever autovacuum last ran. */
async function analyze(h: Harness): Promise<void> {
  await h.sql.query('ANALYZE "wiki_entry"');
  await h.sql.query('ANALYZE "wiki_changeset_op"');
}

/** The planted draft's lookup in `spaceId` reads the trigram index, and nothing else asks per candidate. */
async function assertReadsTheIndex(h: Harness, owner: Account, spaceId: string, size: number): Promise<void> {
  const { root, text } = await explainLookup(h, owner.id, spaceId);
  const nodes = nodesOf(root);
  const index = nodes.find((node) => node['Index Name'] === 'wiki_entry_search_trgm');
  assert.ok(index, `the lookup does not read the trigram index:\n${text}`);
  // The draft's text is an InitPlan's output to the plan, not a constant it was planned around —
  // around a constant, the planner runs `%` against every value in the expression's statistics.
  assert.ok(nodes.some((node) => node['Parent Relationship'] === 'InitPlan'), `the draft's text is not an InitPlan's output:\n${text}`);
  assert.doesNotMatch(index!['Index Cond'] ?? '', /Migration numbers/u, `the lookup was planned around the draft's text:\n${text}`);
  // `wiki_changeset_op` may be read whole — here it is a handful of rows, asked once per row
  // returned; the table of entries may not.
  assert.deepEqual(
    nodes.filter((node) => node['Node Type'] === 'Seq Scan' && node['Relation Name'] === 'wiki_entry'),
    [],
    `the lookup scans the table of entries:\n${text}`,
  );
  // The behaviour behind the shape: the rows it fetched from the table and tested are the index's
  // candidates, a small part of the space — not the space, which is what testing it row by row behind
  // the space's own index would read.
  const tested = nodes
    .filter((node) => node['Relation Name'] === 'wiki_entry')
    .reduce(
      (sum, node) => sum
        + (node['Actual Rows'] + (node['Rows Removed by Index Recheck'] ?? 0) + (node['Rows Removed by Filter'] ?? 0))
          * node['Actual Loops'],
      0,
    );
  assert.ok(tested < size / 10, `the lookup tested ${tested} of the space's ${size} entries:\n${text}`);

  const returned = root['Actual Rows'];
  assert.equal(returned, 5, `the planted draft has five neighbours:\n${text}`);
  const perRow = nodes.filter((node) => node['Parent Relationship'] === 'SubPlan');
  assert.ok(perRow.length > 0, `the rejection's reason is not asked per row at all:\n${text}`);
  for (const subplan of perRow) {
    assert.ok(subplan['Actual Loops'] > 0, `${subplan['Subplan Name']} never ran, so it proves nothing:\n${text}`);
    assert.ok(
      subplan['Actual Loops'] <= returned,
      `${subplan['Subplan Name']} ran ${subplan['Actual Loops']} times for ${returned} rows returned:\n${text}`,
    );
  }
}

// ── the cases ───────────────────────────────────────────────────────────────────────────────────

test('0313 · the near-neighbour lookup at 2,606 and at 10,000 entries', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const add = { op: 'add', entry: { kind: 'concept', ...DRAFT }, sources: [] };

  await t.test('at production\'s size, the space alone in the table as it was there, the lookup reads the index and not every entry', async () => {
    // Where the bug lived. A scan's price grows with the table, and the index's with the draft's
    // trigrams — about a hundred for a title and a summary — so with the test the scan repeats on every
    // row unpriced, the scan was the cheaper plan up to a few thousand entries: production read and
    // tested all 2,606, 290–470 ms an add. Past ~5,000 the index won even so, which is why this is
    // asked here and not only among the 10,000 below.
    const px = await productionLoaded(h);
    await analyze(h);
    await assertReadsTheIndex(h, px.owner, px.productionSized, PRODUCTION);
  });

  const fx = await loaded(h);

  await t.test('another owner\'s entries never reach this owner\'s neighbours, though they are neighbours in their own space', async () => {
    const mine = similarOf(await propose(h, fx.owner, fx.big, { dryRun: true, ops: [add] }));
    const theirs = new Set(Object.values(fx.otherFamily));
    assert.equal(mine.length, 5, 'the planted family is five neighbours deep');
    assert.deepEqual(mine.filter((s) => theirs.has(s.id)), [], 'another owner\'s entry is among this owner\'s neighbours');
    const outside = await h.sql.query(
      `SELECT count(*)::int AS n FROM "wiki_entry" WHERE "id" = ANY($1::uuid[]) AND "space_id" <> $2`,
      [mine.map((s) => s.id), fx.big],
    );
    assert.equal(outside.rows[0].n, 0, 'a neighbour came from outside the space asked about');
    // The twins are neighbours of the same draft where they live: absent above because of whose they
    // are, not because of what they say.
    const inTheirSpace = similarOf(await propose(h, fx.other, fx.otherSpace, { dryRun: true, ops: [add] }));
    assert.deepEqual(
      inTheirSpace.map((s) => s.id),
      ['twin', 'same', 'close', 'rejected', 'fifth'].map((key) => fx.otherFamily[key]),
      'in its own space the other owner\'s family is the five neighbours',
    );
  });

  await t.test('similar[] is what the lookup before 0313 returned: the same five in the same order, reasons kept', async () => {
    const before = await neighboursBefore0313(h, fx.owner.id, fx.big, null);
    const now = similarOf(await propose(h, fx.owner, fx.big, { dryRun: true, ops: [add] }));
    assert.deepEqual(now, before, 'an add\'s similar[] is not what the lookup before 0313 found');
    // What that comparison rests on, so it cannot pass by comparing two empty lists: the five in the
    // ranking's own order — score, then the later-recorded of a tie — the sixth left out, and the
    // rejected one carrying its latest reason.
    assert.deepEqual(
      now.map((s) => s.id),
      ['twin', 'same', 'close', 'rejected', 'fifth'].map((key) => fx.family[key]),
      'the five, in order',
    );
    assert.equal(now[0].score, now[1].score, 'the first two tie on score, and are ordered by when they were recorded');
    assert.deepEqual(
      now.map((s) => s.rejectedReason),
      [null, null, null, 'duplicate', null],
      'the rejected neighbour carries the reason of its latest rejection, and no other carries one',
    );

    // A supersede excludes the entry it replaces; the one after the five moves up.
    const superseding = {
      op: 'supersede',
      entryId: fx.family.close,
      baseRevision: 1,
      entry: { kind: 'concept', ...DRAFT },
      sources: [],
    };
    const beforeExcluding = await neighboursBefore0313(h, fx.owner.id, fx.big, fx.family.close);
    const nowExcluding = similarOf(await propose(h, fx.owner, fx.big, { dryRun: true, ops: [superseding] }));
    assert.deepEqual(nowExcluding, beforeExcluding, 'a supersede\'s similar[] is not what the lookup before 0313 found');
    assert.deepEqual(
      nowExcluding.map((s) => s.id),
      ['twin', 'same', 'rejected', 'fifth', 'sixth'].map((key) => fx.family[key]),
      'the superseded entry is left out and the sixth takes its place',
    );
  });

  await t.test('after an explicit ANALYZE the lookup reads the trigram index, not the table, and asks a reason per row it returns', async () => {
    await analyze(h);
    // What steers every caller of the function to its index, stated where a later migration cannot
    // quietly undo it: a `CREATE OR REPLACE FUNCTION "wiki_entry_search_text"` resets COST to 100.
    const cost = await h.sql.query<{ procost: number }>(
      `SELECT procost FROM pg_proc WHERE proname = 'wiki_entry_search_text'`,
    );
    assert.deepEqual(cost.rows.map((row) => Number(row.procost)), [10_000], 'wiki_entry_search_text lost the COST 0313 gave it');
    await assertReadsTheIndex(h, fx.owner, fx.big, BIG);
    await assertReadsTheIndex(h, fx.other, fx.otherSpace, OTHER);
  });

  await t.test(`${OPS} adds into ${BIG.toLocaleString('en-US')} entries commit within ${OVER_BASELINE_MS / 1_000} s of the same into an empty space`, async () => {
    const warm = await space(h, fx.owner.id, 'warm-up');
    const empty = await space(h, fx.owner.id, 'empty');
    const next = corpus(3);
    const drafts = Array.from({ length: OPS }, () => ({ op: 'add', entry: { kind: 'concept', ...next() }, sources: [] }));
    const applied = (answer: Answer): number =>
      (answer.body?.ops as Array<{ status: string }> | undefined)?.filter((op) => op.status === 'applied').length ?? 0;

    // Once through the door first: the first request of a process pays for what every later one
    // reuses (query compilation, the pool's connections), and a server that is up has paid it.
    const warmUp = await propose(h, fx.owner, warm, { ops: drafts.slice(0, 3) });
    assert.equal(warmUp.status, 200, `the warm-up: answered ${warmUp.status} ${JSON.stringify(warmUp.body)}`);

    const baseline = await propose(h, fx.owner, empty, { ops: drafts });
    assert.equal(baseline.status, 200, `the empty space: answered ${baseline.status} ${JSON.stringify(baseline.body)}`);
    assert.equal(applied(baseline), OPS, 'every add into the empty space applies');

    // A transaction Prisma closed (P2028) answers 500, and writes nothing.
    const loadedRun = await propose(h, fx.owner, fx.big, { ops: drafts });
    t.diagnostic(`baseline (empty space) ${Math.round(baseline.ms)} ms; ${BIG.toLocaleString('en-US')} entries ${Math.round(loadedRun.ms)} ms`);
    assert.equal(loadedRun.status, 200, `the big space: answered ${loadedRun.status} ${JSON.stringify(loadedRun.body)}`);
    assert.equal(applied(loadedRun), OPS, 'every add into the big space applies');
    assert.ok(
      loadedRun.ms <= baseline.ms + OVER_BASELINE_MS,
      `${OPS} adds took ${Math.round(loadedRun.ms)} ms among ${BIG} entries and ${Math.round(baseline.ms)} ms in an `
        + `empty space: the lookup costs more than ${OVER_BASELINE_MS} ms a changeset at this size`,
    );
    const committed = await h.sql.query(
      `SELECT count(*)::int AS n FROM "wiki_entry" WHERE "space_id" = $1 AND "status" = 'active'`,
      [fx.big],
    );
    assert.equal(committed.rows[0].n, BIG + OPS, 'the big space holds its entries and the thirty new ones');
  });
});
