/**
 * The wiki's rollout flag (wiki-rollout.ts) over real HTTP and against a real PostgreSQL: what each mode of ORBIT_WIKI
 * lets an account do on the two doors, and what the runner is told when it claims or reclaims that account's sessions.
 *
 *   1. Under off, EVERY route of both doors — enumerated from the controllers, so a route added later is in this case
 *      without anybody listing it — answers 404 WIKI_DISABLED for an account that has a space, entries and a bound
 *      workspace, and nothing is written.
 *   2. Under canary, the listed account keeps both doors; every other account is refused, and writes nothing.
 *   3. A request no credential vouches for is still the credential guard's refusal: the flag says nothing to it.
 *   4. The claim and the reclaim carry `wikiDisabled` exactly for the accounts the wiki is not on for.
 *   5. An `orbit-wiki:` link card is `unavailable` to an account the wiki is off for, its own entry included.
 *
 * The push through the real delivery path is a case of wiki-push.pg.spec.ts; the flag's parsing and the guard's
 * placement on the controllers are wiki-rollout.spec.ts.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-rollout.pg.spec.ts
 *
 * The flag is read from this process's environment on every request, as the apiserver reads it (a real replica is
 * restarted to change it); each case sets it and puts it back. Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { METHOD_METADATA, PATH_METADATA } from '@nestjs/common/constants';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import { RunStatus, RunnerStatus, type PrismaClient } from '@prisma/client';
import { toUuid, uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { LinkPreviewsService } from '../link-previews/link-previews.service';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { decideSessionSource } from '../projects/session-source';
import { QueueService } from '../queue/queue.service';
import { RealtimeService } from '../realtime/realtime.service';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiController } from './wiki.controller';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService } from './wiki.service';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a claimed session carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The refusal, spelled as the contract spells it rather than imported from the module under test. */
const WIKI_DISABLED = 'WIKI_DISABLED';

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

/** One account: its bearer on the user door, and a runner that hosts one session in one workspace. */
interface Account {
  id: string;
  bearer: string;
  runnerId: string;
  runnerToken: string;
  workspaceId: string;
  /** A session this account's runner hosts: the runner door's calling session. */
  sessionId: string;
}

/** The flag as ORBIT_WIKI and ORBIT_WIKI_CANARY_OWNERS set it, for the length of `run`; restored after. */
async function withFlag<T>(env: { ORBIT_WIKI?: string; ORBIT_WIKI_CANARY_OWNERS?: string }, run: () => Promise<T>): Promise<T> {
  const saved = { mode: process.env.ORBIT_WIKI, owners: process.env.ORBIT_WIKI_CANARY_OWNERS };
  const put = (name: 'ORBIT_WIKI' | 'ORBIT_WIKI_CANARY_OWNERS', value: string | undefined): void => {
    if (value === undefined) delete process.env[name];
    else process.env[name] = value;
  };
  try {
    put('ORBIT_WIKI', env.ORBIT_WIKI);
    put('ORBIT_WIKI_CANARY_OWNERS', env.ORBIT_WIKI_CANARY_OWNERS);
    return await run();
  } finally {
    put('ORBIT_WIKI', saved.mode);
    put('ORBIT_WIKI_CANARY_OWNERS', saved.owners);
  }
}

/** Every route a controller serves, as `METHOD path` with the global prefix — read the way Nest's router reads it. */
function routesOf(controller: new (...args: never[]) => unknown): Array<{ method: string; path: string }> {
  const methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'ALL', 'OPTIONS', 'HEAD', 'SEARCH'];
  const prefix = Reflect.getMetadata(PATH_METADATA, controller) as string;
  const prototype = controller.prototype as unknown as Record<string, object>;
  return Object.getOwnPropertyNames(prototype).flatMap((name) => {
    const handler = prototype[name];
    if (name === 'constructor' || typeof handler !== 'function') return [];
    const route = Reflect.getMetadata(PATH_METADATA, handler) as string | undefined;
    if (route === undefined) return [];
    return [{ method: methods[Reflect.getMetadata(METHOD_METADATA, handler) as number], path: `/${prefix}/${route}` }];
  });
}

test('the wiki rollout flag, over both doors and the runner\'s claim', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  let app: INestApplication | undefined;
  t.after(async () => {
    await app?.close().catch(() => undefined);
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  // ── the app: both wiki doors behind their credential guards, and main.ts's pipe and interceptor ──────────────────
  const bearers = new Map<string, string>();
  const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
  @Module({
    controllers: [WikiController, RunnerWikiController],
    providers: [
      { provide: WikiService, useValue: new WikiService(prisma as unknown as PrismaService, hub) },
      { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
      { provide: PrismaService, useValue: prisma },
      RunnerAuthGuard,
      JwtAuthGuard,
      Reflector,
      {
        provide: JwtService,
        useValue: {
          verifyAsync: async (token: string) => {
            const sub = bearers.get(token);
            if (!sub) throw new Error('not a bearer this run issued');
            return { sub, email: `${sub}@wiki.invalid` };
          },
        },
      },
    ],
  })
  class WikiRolloutDoors {}

  app = await NestFactory.create(WikiRolloutDoors, { logger: false, abortOnError: false });
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
  app.useGlobalInterceptors(new PublicIdInterceptor());
  await app.listen(0, '127.0.0.1');
  const base = await app.getUrl();

  async function call(
    who: { bearer?: string; runnerToken?: string; sessionId?: string },
    method: string,
    route: string,
    body?: unknown,
  ): Promise<Answer> {
    const headers: Record<string, string> = { 'content-type': 'application/json' };
    if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
    if (who.runnerToken) headers['x-runner-token'] = who.runnerToken;
    if (who.sessionId) headers['x-orbit-session-id'] = uuidToBase62(who.sessionId);
    const response = await fetch(`${base}/api${route}`, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const text = await response.text();
    let parsed: unknown = null;
    try {
      parsed = text ? JSON.parse(text) : null;
    } catch {
      parsed = { unparsed: text };
    }
    return { status: response.status, body: parsed };
  }

  function refusedDisabled(answer: Answer, why: string): void {
    assert.equal(answer.status, 404, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
    assert.equal(answer.body?.code, WIKI_DISABLED, `${why}: refused with ${JSON.stringify(answer.body)}`);
  }

  // ── fixtures ─────────────────────────────────────────────────────────────────────────────────────────────────────

  async function account(name: string): Promise<Account> {
    const id = randomUUID();
    await prisma.user.create({ data: { id, email: `wiki-rollout-${id}@wiki.invalid`, name, passwordHash: 'x' } });
    bearers.set(`bearer-${id}`, id);
    const runnerId = randomUUID();
    const runnerToken = `runner-${runnerId}`;
    await prisma.runner.create({
      data: {
        id: runnerId,
        name: `${name}'s machine`,
        ownerId: id,
        tokenHash: createHash('sha256').update(runnerToken).digest('hex'),
        status: RunnerStatus.ONLINE,
        maxConcurrent: 8,
      },
    });
    const workspaceId = randomUUID();
    await prisma.workspace.create({
      data: { id: workspaceId, ownerId: id, runnerId, name: `${name}-ws`, enabled: true, workDir: `/tmp/${name}` },
    });
    const sessionId = await pendingSession({ id, runnerId, workspaceId }, RunStatus.AWAITING_INPUT);
    return { id, bearer: `bearer-${id}`, runnerId, runnerToken, workspaceId, sessionId };
  }

  /** A session of this account on its runner, created the way `SessionsService.create` creates one. */
  async function pendingSession(
    who: { id: string; runnerId: string; workspaceId: string },
    status: RunStatus = RunStatus.PENDING,
  ): Promise<string> {
    const decision = await decideSessionSource(prisma as unknown as PrismaService, null);
    const session = await prisma.session.create({
      data: {
        title: 'a session',
        prompt: 'pick this up',
        status,
        ownerId: who.id,
        creatorId: who.id,
        workspaceId: who.workspaceId,
        assignedRunnerId: who.runnerId,
        provider: 'claude',
        providerBuiltin: true,
        ...decision.columns,
      },
      select: { id: true },
    });
    return session.id;
  }

  /** A space the account makes and binds its workspace to, with one entry of the owner's own — through the door. */
  async function furnish(who: Account): Promise<{ spaceId: string; entryId: string }> {
    const created = await call({ bearer: who.bearer }, 'POST', '/wiki/spaces', { title: 'The orbit repository' });
    assert.equal(created.status, 201, `the owner creates a space: ${JSON.stringify(created.body)}`);
    const spaceId = toUuid(created.body.id as string);
    const bound = await call({ bearer: who.bearer }, 'POST', `/wiki/spaces/${uuidToBase62(spaceId)}/workspaces`, {
      workspaceId: uuidToBase62(who.workspaceId),
    });
    assert.equal(bound.status, 200, `the owner binds the workspace: ${JSON.stringify(bound.body)}`);
    const written = await call({ bearer: who.bearer }, 'POST', `/wiki/spaces/${uuidToBase62(spaceId)}/changesets`, {
      rationale: 'the owner records what this codebase knows',
      ops: [{
        op: 'add',
        entry: {
          kind: 'pitfall',
          title: 'A pg spec that skips itself proves nothing',
          summary: 'Run pg specs through scripts/run-pg-spec.sh, which treats a skip as red.',
          fields: {
            trigger: { paths: ['src/apiserver/src/wiki/*.pg.spec.ts'], commands: ['node --test build/x.pg.spec.js'] },
            symptom: 'node exits 0 and no assertion ran.',
            cause: 'A pg spec skips itself when the URL is unset.',
            fix: 'Run it through scripts/run-pg-spec.sh.',
          },
        },
      }],
    });
    assert.equal(written.status, 200, `the owner writes an entry: ${JSON.stringify(written.body)}`);
    const op = (written.body.ops as Array<{ status: string; entryId: string }>)[0];
    assert.equal(op?.status, 'applied', `the owner's own write applies at once: ${JSON.stringify(written.body)}`);
    return { spaceId, entryId: toUuid(op.entryId) };
  }

  /** Every row the wiki has, table by table: what "nothing was written" is a count of. */
  async function wikiRows(): Promise<Record<string, number>> {
    const tables = [
      'wiki_space', 'wiki_space_workspace', 'wiki_topic', 'wiki_entry', 'wiki_entry_revision', 'wiki_source',
      'wiki_changeset', 'wiki_changeset_op', 'wiki_exposure',
    ];
    const counts: Record<string, number> = {};
    for (const table of tables) {
      counts[table] = Number((await sql.query(`SELECT count(*)::int AS n FROM "${table}"`)).rows[0].n);
    }
    return counts;
  }

  // Both accounts get everything the doors can give them while the wiki is on, the default.
  const a = await account('alice');
  const b = await account('bob');
  const aWiki = await furnish(a);
  const bWiki = await furnish(b);

  // ── 1. off: every route of both doors ────────────────────────────────────────────────────────────────────────────

  await t.test('under off, every route of both doors answers 404 WIKI_DISABLED and writes nothing', async () => {
    const routes = [
      ...routesOf(WikiController).map((route) => ({ ...route, door: 'user' as const })),
      ...routesOf(RunnerWikiController).map((route) => ({ ...route, door: 'runner' as const })),
    ];
    // What both controllers serve today; the walk above is what makes a later route part of this case.
    assert.ok(routes.filter((r) => r.door === 'user').length >= 14, `the user door lost routes: ${JSON.stringify(routes)}`);
    assert.ok(routes.filter((r) => r.door === 'runner').length >= 3, `the runner door lost routes: ${JSON.stringify(routes)}`);

    // Every address is one of this account's own rows, so a route that answered would have had something to answer
    // with: the 404 below is the flag's, not a missing row's, and its code is what says so.
    const address = (path: string): string =>
      path
        .replace('for-session/:id', `for-session/${uuidToBase62(a.sessionId)}`)
        .replace('entries/:id', `entries/${uuidToBase62(aWiki.entryId)}`)
        .replace('changesets/:id', `changesets/${uuidToBase62(randomUUID())}`)
        .replace(':id', uuidToBase62(aWiki.spaceId))
        .replace(':slug', 'general');
    const before = await wikiRows();
    await withFlag({ ORBIT_WIKI: 'off' }, async () => {
      for (const route of routes) {
        const who = route.door === 'user' ? { bearer: a.bearer } : { runnerToken: a.runnerToken, sessionId: a.sessionId };
        const path = address(route.path) + (route.path.endsWith('/search') ? '?q=spec' : '');
        const body = route.method === 'GET' ? undefined : {};
        const answer = await call(who, route.method, path, body);
        refusedDisabled(answer, `${route.method} ${route.path} on the ${route.door} door`);
        assert.match(answer.body.message, /ORBIT_WIKI=off/, `${route.method} ${route.path} does not say why`);
      }
    });
    assert.deepEqual(await wikiRows(), before, 'a refused request wrote a wiki row');

    // The paired positive: the same account, the same doors, the wiki on again.
    const listed = await call({ bearer: a.bearer }, 'GET', '/wiki/spaces');
    assert.equal(listed.status, 200, `the wiki back on: ${JSON.stringify(listed.body)}`);
    const found = await call({ runnerToken: a.runnerToken, sessionId: a.sessionId }, 'GET', '/runner/wiki/search?q=spec');
    assert.equal(found.status, 200, `the runner door back on: ${JSON.stringify(found.body)}`);
  });

  // ── 2. canary ────────────────────────────────────────────────────────────────────────────────────────────────────

  await t.test('under canary, the listed account keeps both doors, and every other is refused and writes nothing', async () => {
    await withFlag({ ORBIT_WIKI: 'canary', ORBIT_WIKI_CANARY_OWNERS: uuidToBase62(a.id) }, async () => {
      const listed = await call({ bearer: a.bearer }, 'GET', '/wiki/spaces');
      assert.equal(listed.status, 200, `the listed account reads its spaces: ${JSON.stringify(listed.body)}`);
      assert.deepEqual(
        (listed.body as Array<{ id: string }>).map((space) => toUuid(space.id)),
        [aWiki.spaceId],
      );
      const found = await call({ runnerToken: a.runnerToken, sessionId: a.sessionId }, 'GET', '/runner/wiki/search?q=spec');
      assert.equal(found.status, 200, `the listed account's session searches: ${JSON.stringify(found.body)}`);
      assert.deepEqual(
        (found.body.hits as Array<{ id: string }>).map((hit) => toUuid(hit.id)),
        [aWiki.entryId],
        'the listed account\'s session does not find its own entry',
      );

      const before = await wikiRows();
      refusedDisabled(await call({ bearer: b.bearer }, 'GET', '/wiki/spaces'), 'an unlisted account\'s spaces');
      refusedDisabled(
        await call({ bearer: b.bearer }, 'GET', `/wiki/entries/${uuidToBase62(bWiki.entryId)}`),
        'an unlisted account\'s own entry',
      );
      refusedDisabled(
        await call({ bearer: b.bearer }, 'POST', '/wiki/spaces', { title: 'Another codebase' }),
        'an unlisted account making a space',
      );
      refusedDisabled(
        await call({ runnerToken: b.runnerToken, sessionId: b.sessionId }, 'GET', '/runner/wiki/search?q=spec'),
        'an unlisted account\'s session searching',
      );
      refusedDisabled(
        await call({ runnerToken: b.runnerToken, sessionId: b.sessionId }, 'POST', '/runner/wiki/changesets', {
          rationale: 'what this session learned',
          ops: [{
            op: 'add',
            entry: { kind: 'convention', title: 'Tests go beside the code', summary: 'A spec sits next to its module.' },
            sources: [{ kind: 'turn', session: 'self' }],
          }],
        }),
        'an unlisted account\'s session proposing',
      );
      // Another account's credential cannot reach the listed account's rows either: the door is closed on the
      // credential's account, not on the address.
      refusedDisabled(
        await call({ bearer: b.bearer }, 'GET', `/wiki/spaces/${uuidToBase62(aWiki.spaceId)}`),
        'an unlisted account asking for the listed account\'s space',
      );
      assert.deepEqual(await wikiRows(), before, 'a refused request wrote a wiki row');
    });
  });

  // ── 3. credentials first ────────────────────────────────────────────────────────────────────────────────────────

  await t.test('a request no credential vouches for is refused by the credential guard, whatever the flag says', async () => {
    await withFlag({ ORBIT_WIKI: 'off' }, async () => {
      assert.equal((await call({}, 'GET', '/wiki/spaces')).status, 401, 'no bearer');
      assert.equal((await call({ bearer: 'bearer-nobody' }, 'GET', '/wiki/spaces')).status, 401, 'a bearer nobody issued');
      assert.equal((await call({}, 'GET', '/runner/wiki/search?q=spec')).status, 401, 'no runner token');
      assert.equal((await call({ runnerToken: 'no-such-runner' }, 'GET', '/runner/wiki/search?q=spec')).status, 401, 'a token no runner has');
    });
  });

  // ── 4. the claim and the reclaim ────────────────────────────────────────────────────────────────────────────────

  await t.test('the claim and the reclaim carry wikiDisabled exactly for the accounts the wiki is not on for', async () => {
    const realtime = { publishSessionUpdated: () => undefined, publishSessionCreated: () => undefined, notifyInbox: () => undefined };
    const queue = new QueueService(prisma as unknown as PrismaService, realtime as unknown as RealtimeService);
    const runnerDoor = new RunnerApiController(
      prisma as unknown as PrismaService,
      queue,
      realtime as unknown as RealtimeService,
      {} as never, {} as never, {} as never,
    );

    /** Queue one session for the account and claim it on the account's runner: the payload a runner receives. */
    const claim = async (who: Account): Promise<{ sessionId: string; wikiDisabled?: boolean }> => {
      const sessionId = await pendingSession({ id: who.id, runnerId: who.runnerId, workspaceId: who.workspaceId });
      const claimed = await queue.claimSessionForRunner({ id: who.runnerId }, 0, false, true);
      assert.equal(claimed?.sessionId, sessionId, `${who.id}'s runner was handed another session`);
      return { sessionId, wikiDisabled: claimed?.wikiDisabled };
    };
    /** What the account's runner is told about every session it hosts when it restarts. */
    const reclaim = async (who: Account): Promise<Map<string, boolean | undefined>> => {
      const answer = await runnerDoor.reclaim({ id: who.runnerId, ownerId: who.id }, undefined, undefined);
      assert.ok(answer.sessions.length > 0, `${who.id}'s runner reclaimed nothing`);
      return new Map(answer.sessions.map((session) => [toUuid(session.sessionId), session.wikiDisabled]));
    };

    const cases: Array<[string, { ORBIT_WIKI?: string; ORBIT_WIKI_CANARY_OWNERS?: string }, boolean, boolean]> = [
      // name, flag, whether A's sessions are told the wiki is off, whether B's are
      ['on, the default', {}, false, false],
      ['canary listing A', { ORBIT_WIKI: 'canary', ORBIT_WIKI_CANARY_OWNERS: uuidToBase62(a.id) }, false, true],
      ['off', { ORBIT_WIKI: 'off' }, true, true],
    ];
    for (const [name, flag, aOff, bOff] of cases) {
      await withFlag(flag, async () => {
        for (const [who, off] of [[a, aOff], [b, bOff]] as const) {
          const claimed = await claim(who);
          // Absent, not `false`, while the wiki is on: exactly the payload every runner has always received.
          assert.equal(claimed.wikiDisabled, off ? true : undefined, `${name}: the claim of ${who === a ? 'A' : 'B'}'s session`);
          const reclaimed = await reclaim(who);
          assert.ok(reclaimed.has(claimed.sessionId), `${name}: the reclaim left out the session just claimed`);
          for (const [sessionId, wikiDisabled] of reclaimed) {
            assert.equal(wikiDisabled, off ? true : undefined, `${name}: the reclaim of ${who === a ? 'A' : 'B'}'s ${sessionId}`);
          }
        }
      });
    }
  });

  // ── 5. link cards ───────────────────────────────────────────────────────────────────────────────────────────────

  await t.test('an orbit-wiki: card is unavailable to an account the wiki is off for, its own entry included', async () => {
    const previews = new LinkPreviewsService(prisma as unknown as PrismaService, {} as never, {} as never);
    const card = async (who: Account, entryId: string): Promise<string> => {
      const answer = await previews.read(who.id, [{ kind: 'wiki', id: uuidToBase62(entryId) }]);
      return answer.previews[0].state;
    };
    await withFlag({ ORBIT_WIKI: 'canary', ORBIT_WIKI_CANARY_OWNERS: uuidToBase62(a.id) }, async () => {
      assert.equal(await card(a, aWiki.entryId), 'ok', 'the listed account\'s own entry');
      assert.equal(await card(b, bWiki.entryId), 'unavailable', 'an unlisted account\'s own entry');
    });
    // The paired positive: the same card, the wiki on for everyone.
    assert.equal(await card(b, bWiki.entryId), 'ok', 'the unlisted account\'s entry once the wiki is on');
  });
});
