/**
 * A space's health (criterion 5; contracts/wiki.contract.json `maintenance.health`), against a real
 * PostgreSQL and over the doors' real routes.
 *
 * What criterion 5 asks of the server, each read back from what the routes answered and what was sent:
 *
 *   1. three failed runs in a row tell the owner once — the fourth and fifth tell nobody, and reports
 *      racing on the row still tell the owner once;
 *   2. a run that succeeds sets the streak back to zero, and the next streak tells the owner once more,
 *      at its own third failure;
 *   3. another account reads nothing of the space: its health is the plain 404, and its own failing runs
 *      ring its own owner's phone and nobody else's;
 *
 * and beside them, the read the Wiki home's status line draws from: every active entry of the space (not
 * the 200 a list stops at), maintenance off until the owner turns it on, the backlog counted from the
 * facts as the read is made, and the looks — off, ok, behind, running, failing — with the day's runs used
 * up said so. The read writes nothing.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-health.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, and the push sender records instead of
 * sending, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { WIKI_MAINTENANCE_HEALTH, WIKI_MAINTENANCE_RULES, toUuid, uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiMaintainController } from '../runner-api/runner-wiki-maintain.controller';
import { RunnerWikiMaintenanceController } from '../runner-api/runner-wiki-maintenance.controller';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiController } from './wiki.controller';
import { WikiHealth } from './wiki-health';
import { WikiHealthController } from './wiki-health.controller';
import { WikiMaintenance } from './wiki-maintenance';
import { considerWikiMaintenance } from './wiki-maintenance-run';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** What `PushService.notifyWikiMaintenanceFailing` was asked to send. */
interface Pushed {
  ownerId: string;
  spaceId: string;
  title: string;
  failures: number;
  lastError: string | null;
}

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  bearers: Map<string, string>;
  pushed: Pushed[];
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const pushed: Pushed[] = [];
    const hub = {
      publishWikiChanged: () => undefined,
      publishForUser: () => undefined,
    } as unknown as RealtimeService;
    // The sender records what it was asked to send: the phone is the one thing a spec cannot ring.
    const push = {
      notifyWikiMaintenanceFailing: async (input: Pushed) => {
        pushed.push(input);
      },
    } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);
    const maintenance = new WikiMaintenance(prisma as unknown as PrismaService, push);

    @Module({
      controllers: [WikiController, WikiHealthController, RunnerWikiController, RunnerWikiMaintenanceController, RunnerWikiMaintainController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiMaintenance, useValue: maintenance },
        { provide: WikiHealth, useValue: new WikiHealth(prisma as unknown as PrismaService) },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiHealthModule {}

    const app = await NestFactory.create(WikiHealthModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, bearers, pushed };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 600)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

const minutesAgo = (minutes: number): Date => new Date(Date.now() - minutes * 60_000);

/** A time as the UTC text Orbit's timestamp columns hold (see wiki-dossier.pg.spec.ts). */
const utc = (at: Date | null | undefined): string | null => (at ? at.toISOString() : null);

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-health-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env","work_dir") VALUES ($1,'spec',$2,'{}','~/orbit')`, [id, ownerId]);
  return id;
}

async function session(
  h: Harness,
  ownerId: string,
  shape: { workspaceId: string; runnerId?: string | null; taskId?: string | null; status?: string; lastTurnAt?: Date },
): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","status","last_turn_at","dispatch_origin","created_at","updated_at")
     VALUES ($1,'a session','p',$2,$2,$3,$4,$5,$6::run_status,$7,'USER',$8,now())`,
    [id, ownerId, shape.workspaceId, shape.runnerId ?? null, shape.taskId ?? null, shape.status ?? 'SUCCEEDED',
      utc(shape.lastTurnAt ?? minutesAgo(30)), utc(minutesAgo(24 * 60 * 3))],
  );
  return id;
}

interface Space {
  owner: Account;
  machine: { id: string; token: string };
  spaceId: string;
  workspaceId: string;
}

/** A space bound to a workspace of its owner's, with its maintenance as `maintenance` says: off when absent. */
async function space(h: Harness, name: string, maintenance?: Record<string, unknown>): Promise<Space> {
  const owner = await account(h, name);
  const machine = await runner(h, owner.id);
  const workspaceId = await workspace(h, owner.id);
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', {
    title: `${name} space`,
    repoUrl: `https://github.com/spec/${name}-${randomUUID().slice(0, 8)}`,
  });
  expectStatus(made, 201, 'the owner creates a space');
  const spaceId = toUuid(made.body.id as string);
  expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId }), 200, 'the owner binds the workspace');
  const s = { owner, machine, spaceId, workspaceId };
  if (maintenance) await turnOn(h, s, maintenance);
  return s;
}

async function turnOn(h: Harness, s: Space, settings: Record<string, unknown> = {}): Promise<void> {
  const on = await call(h, { bearer: s.owner.bearer }, 'PATCH', `/wiki/spaces/${s.spaceId}`, {
    maintenance: { enabled: true, workspaceId: s.workspaceId, provider: 'local-vllm', ...settings },
  });
  expectStatus(on, 200, 'the owner turns maintenance on');
}

/** Sessions of the space that came to rest about `minutes` ago, each one fact: the first the oldest. */
async function settledSessions(h: Harness, s: Space, count: number, minutes = 30): Promise<string[]> {
  const ids: string[] = [];
  for (let n = 0; n < count; n += 1) {
    ids.push(await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(minutes + (count - n) / 10) }));
  }
  return ids;
}

/**
 * The space's maintenance task, made by a fact as the trigger makes it, and its run under way: the task
 * IN_PROGRESS, its session on the space's runner, and the run's start read — what a claim and
 * `orbit wiki maintain` would have done. Answers the run's session and the position its task expects.
 */
async function startRun(h: Harness, s: Space): Promise<{ taskId: string; run: string; expect: string }> {
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold);
  const made = await considerWikiMaintenance(h.prisma as unknown as PrismaService, s.owner.id, s.spaceId, {
    sessionIds: [sessions[0]!],
    taskIds: [],
  });
  assert.equal(made.made, true, `a due space makes its maintenance task: ${JSON.stringify(made)}`);
  if (!made.made) throw new Error('unreachable');
  await h.sql.query(`UPDATE "task" SET "status" = 'IN_PROGRESS' WHERE "id" = $1`, [made.taskId!]);
  const run = await session(h, s.owner.id, {
    workspaceId: s.workspaceId, runnerId: s.machine.id, taskId: made.taskId!, status: 'RUNNING', lastTurnAt: minutesAgo(1),
  });
  expectStatus(await call(h, { runner: s.machine.token, session: run }, 'GET', `/runner/wiki/spaces/${s.spaceId}/maintenance/run`), 200, 'the run reads where it starts');
  return { taskId: made.taskId!, run, expect: made.expect };
}

/** Page the dossiers a run covers, up to what its task expects, as `orbit wiki maintain` does: the token it may advance to. */
async function pageToExpected(h: Harness, s: Space, run: string, expect: string): Promise<string> {
  let after = '';
  for (let n = 0; n < 100; n += 1) {
    const query = new URLSearchParams({ until: expect, limit: '10', ...(after ? { after } : {}) });
    const page = await call(h, { runner: s.machine.token, session: run }, 'GET', `/runner/wiki/spaces/${s.spaceId}/dossiers?${query}`);
    expectStatus(page, 200, 'the run reads a page');
    after = page.body.cursor as string;
    if (!page.body.more) return after;
  }
  throw new Error('the pages never ended');
}

/**
 * A run reporting that it did not succeed: through the cursor route (a truncated turn) or the finish route —
 * saying whose the failure was when `failureKind` is given, as `orbit wiki maintain` does since migration 0356.
 */
async function fail(h: Harness, s: Space, run: string, via: 'cursor' | 'finish', error: string, failureKind?: 'infra' | 'content'): Promise<void> {
  const answer = via === 'cursor'
    ? await call(h, { runner: s.machine.token, session: run }, 'POST', `/runner/wiki/spaces/${s.spaceId}/cursor`, {
      outcome: 'truncated',
      error,
      ...(failureKind ? { failureKind } : {}),
    })
    : await call(h, { runner: s.machine.token, session: run }, 'POST', `/runner/wiki/spaces/${s.spaceId}/maintenance/finish`, {
      outcome: 'failed',
      error,
      ...(failureKind ? { failureKind } : {}),
      report: { stoppedAt: 'extract', ops: { refused: 0 } },
    });
  expectStatus(answer, 200, `a failed run is recorded through the ${via} route`);
  assert.equal(answer.body.advanced, false);
}

/** A run reporting that it succeeded, at the token its pages reached. */
async function succeed(h: Harness, s: Space, run: string, token: string): Promise<void> {
  const answer = await call(h, { runner: s.machine.token, session: run }, 'POST', `/runner/wiki/spaces/${s.spaceId}/maintenance/finish`, {
    to: token,
    outcome: 'succeeded',
    report: { ops: { refused: 0 }, tokens: { input: 0, output: 0, calls: 0 } },
  });
  expectStatus(answer, 200, 'a succeeded run is recorded');
}

async function health(h: Harness, s: Space, who: Account = s.owner): Promise<Answer> {
  return call(h, { bearer: who.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/health`);
}

/** The owner's health read, which the owner is always answered. */
async function readHealth(h: Harness, s: Space) {
  const answer = await health(h, s);
  expectStatus(answer, 200, 'the owner reads the space\'s health');
  return answer.body;
}

const pushesFor = (h: Harness, s: Space): Pushed[] => h.pushed.filter((one) => one.spaceId === s.spaceId);

// ── the read ─────────────────────────────────────────────────────────────────────────────────────

test('the status line\'s read: every active entry of the space, and maintenance off until the owner turns it on', { skip }, async () => {
  const h = await boot();
  const s = await space(h, 'health-read');
  // More active entries than the entry list hands out (it stops at 200), and some that are not active.
  await h.sql.query(
    `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields","retired_at")
     SELECT gen_random_uuid(), $1, $2, 'concept', CASE WHEN n <= 205 THEN 'active' ELSE 'retired' END, 'auto', 1,
            'Standing entry number ' || n, 'Already in the space.', '{}', CASE WHEN n <= 205 THEN NULL ELSE now() END
       FROM generate_series(1, 209) AS n`,
    [s.owner.id, s.spaceId],
  );
  // A fact of the space: a session of its workspace that came to rest.
  const factAt = minutesAgo(30);
  await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: factAt });

  const off = await readHealth(h, s);
  assert.equal(toUuid(off.spaceId), s.spaceId);
  assert.equal(off.entries, 205, 'every active entry, not the 200 a list stops at');
  assert.deepEqual(off.maintenance, {
    look: 'off',
    enabled: false,
    lastOkAt: null,
    lastRunAt: null,
    consecutiveFailures: 0,
    backlog: 0,
    oldestPendingAt: null,
    lagSeconds: 0,
    dailyLimitReached: false,
    held: null,
    running: null,
    lastRun: null,
    lastFailure: null,
  }, 'a space whose maintenance is off counts nothing');
  const cursors = await h.sql.query(`SELECT 1 FROM "wiki_cursor" WHERE "space_id" = $1`, [s.spaceId]);
  assert.equal(cursors.rowCount, 0, 'the read writes nothing, not even the cursor row');

  // On, and never run: the one fact is the backlog, counted as the read is made. Turning maintenance on
  // started the cursor (fourteen days back, by default); the reads below leave that row as it was.
  await turnOn(h, s);
  const cursorRow = async () => (await h.sql.query(`SELECT * FROM "wiki_cursor" WHERE "space_id" = $1`, [s.spaceId])).rows;
  const started = await cursorRow();
  assert.equal(started.length, 1, 'turning maintenance on started the cursor');
  const on = await readHealth(h, s);
  assert.equal(on.maintenance.look, 'ok');
  assert.equal(on.maintenance.enabled, true);
  assert.equal(on.maintenance.backlog, 1);
  assert.equal(on.maintenance.oldestPendingAt, factAt.toISOString());
  assert.ok(on.maintenance.lagSeconds >= 29 * 60 && on.maintenance.lagSeconds < 40 * 60, `lag ${on.maintenance.lagSeconds}s`);
  assert.equal(on.maintenance.lastOkAt, null);

  // A fact older than a day: the space is behind.
  await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo((WIKI_MAINTENANCE_RULES.maxPendingAgeHours + 2) * 60) });
  const behind = await readHealth(h, s);
  assert.equal(behind.maintenance.look, 'behind');
  assert.equal(behind.maintenance.backlog, 2);
  assert.ok(behind.maintenance.lagSeconds >= (WIKI_MAINTENANCE_RULES.maxPendingAgeHours + 2) * 3600 - 60);
  assert.deepEqual(await cursorRow(), started, 'still nothing written');
});

test('a run under way reads as running, and a day whose runs are used up says so', { skip }, async () => {
  const h = await boot();
  const s = await space(h, 'health-running', { dailyRunLimit: 1 });
  const { run } = await startRun(h, s);
  const running = await readHealth(h, s);
  assert.equal(running.maintenance.look, 'running');
  assert.equal(toUuid(running.maintenance.running.sessionId), run, 'the run under way is the session that started it');
  assert.ok(Date.parse(running.maintenance.running.startedAt) <= Date.now());
  assert.equal(running.maintenance.dailyLimitReached, true, 'one task made today, and the limit is one');
  assert.equal(running.maintenance.lastRun, null, 'no run has ended yet');

  // Its task ended without the run saying how: it is no longer under way.
  await h.sql.query(`UPDATE "task" SET "status" = 'FAILED' WHERE "id" = (SELECT "task_id" FROM "session" WHERE "id" = $1)`, [run]);
  const ended = await readHealth(h, s);
  assert.equal(ended.maintenance.running, null);
  assert.notEqual(ended.maintenance.look, 'running');
});

// ── 1 and 2. the owner is told once a streak ─────────────────────────────────────────────────────

test('three failed runs in a row tell the owner once; a success sets the streak to zero, and the next streak tells once more', { skip }, async () => {
  const h = await boot();
  const s = await space(h, 'health-streak', { dailyRunLimit: 48 });
  const { run, expect } = await startRun(h, s);
  const token = await pageToExpected(h, s, run, expect);
  const threshold = WIKI_MAINTENANCE_HEALTH.notifyAfterFailures;
  assert.equal(threshold, 3);

  await fail(h, s, run, 'cursor', 'the run reached its limit of 120 model turns and was cut short');
  await fail(h, s, run, 'finish', 'extract: the local model answered 502');
  assert.equal(pushesFor(h, s).length, 0, 'two failures tell nobody');
  const two = await readHealth(h, s);
  assert.equal(two.maintenance.look, 'failing');
  assert.equal(two.maintenance.consecutiveFailures, 2);
  assert.equal(toUuid(two.maintenance.lastRun.sessionId), run, 'View run opens the run that failed');
  assert.equal(two.maintenance.lastRun.outcome, 'failed');

  await fail(h, s, run, 'finish', 'extract: the local model answered 502 again');
  assert.deepEqual(pushesFor(h, s), [{
    ownerId: s.owner.id,
    spaceId: s.spaceId,
    title: 'health-streak space',
    failures: threshold,
    lastError: 'extract: the local model answered 502 again',
  }], 'the third failure tells the owner, once');

  await fail(h, s, run, 'cursor', 'cut short again');
  await fail(h, s, run, 'finish', 'and again');
  assert.equal(pushesFor(h, s).length, 1, 'the fourth and fifth failures of the streak tell nobody');
  const five = await readHealth(h, s);
  assert.equal(five.maintenance.consecutiveFailures, 5);
  assert.equal(five.maintenance.look, 'failing');
  assert.equal(five.maintenance.lastOkAt, null);

  // The run succeeds: the streak is zero again, and the space is maintained.
  await succeed(h, s, run, token);
  const ok = await readHealth(h, s);
  assert.equal(ok.maintenance.consecutiveFailures, 0, 'a success sets the streak back to zero');
  assert.equal(ok.maintenance.look, 'ok');
  assert.equal(ok.maintenance.backlog, 0, 'the run took in every fact there was');
  assert.ok(ok.maintenance.lastOkAt, 'and says when it last succeeded');
  assert.equal(ok.maintenance.lastRun.outcome, 'succeeded');
  assert.equal((await h.sql.query<{ n: number }>(`SELECT "consecutive_failures" AS n FROM "wiki_cursor" WHERE "space_id" = $1`, [s.spaceId])).rows[0]!.n, 0);

  // The next streak is a streak of its own: told once more, at its own third failure.
  await fail(h, s, run, 'finish', 'one');
  await fail(h, s, run, 'finish', 'two');
  assert.equal(pushesFor(h, s).length, 1);
  await fail(h, s, run, 'cursor', 'three');
  assert.equal(pushesFor(h, s).length, 2, 'the new streak\'s third failure tells the owner again');
  assert.equal(pushesFor(h, s)[1]!.lastError, 'three');

  // Reports racing on the row: each counts, and only the one that reads the threshold back tells.
  await succeed(h, s, run, token); // a token at the watermark: a success that moves nothing, and ends the streak
  assert.equal((await readHealth(h, s)).maintenance.consecutiveFailures, 0);
  await Promise.all(Array.from({ length: 5 }, (_unused, n) => fail(h, s, run, n % 2 === 0 ? 'cursor' : 'finish', `raced ${n}`)));
  assert.equal((await readHealth(h, s)).maintenance.consecutiveFailures, 5, 'every racing report counted');
  assert.equal(pushesFor(h, s).length, 3, 'and the streak told the owner exactly once');
  assert.equal(pushesFor(h, s)[2]!.failures, threshold);
});

// ── whose the last failure was ──────────────────────────────────────────────────────────────────

test('the last failure says whose it was — the platform\'s or the run\'s — and why, until the run that failed succeeds', { skip }, async () => {
  const h = await boot();
  const s = await space(h, 'health-kind', { dailyRunLimit: 48 });
  const { run, expect } = await startRun(h, s);
  assert.equal((await readHealth(h, s)).maintenance.lastFailure, null, 'no run of the space has failed yet');

  // The run stopped on the server: `orbit wiki maintain` says so, and the health tells it from the run's own.
  await fail(h, s, run, 'finish', 'verify: POST /runner/wiki/spaces/x/verifications -> 500', 'infra');
  const infra = await readHealth(h, s);
  assert.equal(infra.maintenance.lastFailure.kind, 'infra');
  assert.equal(infra.maintenance.lastFailure.reason, 'verify: POST /runner/wiki/spaces/x/verifications -> 500');
  assert.equal(toUuid(infra.maintenance.lastFailure.sessionId), run);
  assert.equal(infra.maintenance.lastFailure.at, infra.maintenance.lastRun.endedAt, 'it is the run that ended last');
  const row = (await h.sql.query<{ failure_kind: string; outcome: string }>(
    `SELECT "failure_kind","outcome" FROM "wiki_maintenance_run" WHERE "session_id" = $1`, [run])).rows[0]!;
  assert.deepEqual([row.outcome, row.failure_kind], ['failed', 'infra'], 'the run row keeps whose the failure was');

  // A failure that says nothing of whose it was — a runner older than the field — is read off its error: a 500
  // is the platform's, and a turn limit the run's own.
  await fail(h, s, run, 'finish', 'self-check: orbit wiki maintain: POST /runner/wiki/spaces/x/maintenance/changesets -> 500');
  assert.equal((await readHealth(h, s)).maintenance.lastFailure.kind, 'infra', 'an older runner\'s 500');
  await fail(h, s, run, 'cursor', 'the run reached its limit of 120 model turns');
  const content = await readHealth(h, s);
  assert.deepEqual([content.maintenance.lastFailure.kind, content.maintenance.lastFailure.reason],
    ['content', 'the run reached its limit of 120 model turns']);

  // The same run's retry succeeds: its row says how its latest attempt ended, and no failure stands.
  await succeed(h, s, run, await pageToExpected(h, s, run, expect));
  const ok = await readHealth(h, s);
  assert.equal(ok.maintenance.lastRun.outcome, 'succeeded');
  assert.equal(ok.maintenance.lastFailure, null, 'the run that failed succeeded since');
  assert.equal((await h.sql.query<{ failure_kind: string | null }>(
    `SELECT "failure_kind" FROM "wiki_maintenance_run" WHERE "session_id" = $1`, [run])).rows[0]!.failure_kind, null,
    'a succeeded run has no failure kind');
});

// ── 3. another account reads nothing ────────────────────────────────────────────────────────────

test('another account reads nothing of the space: its health is a 404, and its failing runs ring nobody else', { skip }, async () => {
  const h = await boot();
  const mine = await space(h, 'health-mine', { dailyRunLimit: 48 });
  const theirs = await space(h, 'health-theirs', { dailyRunLimit: 48 });

  for (const id of [mine.spaceId, uuidToBase62(mine.spaceId)]) {
    const read = await call(h, { bearer: theirs.owner.bearer }, 'GET', `/wiki/spaces/${id}/health`);
    expectStatus(read, 404, 'another account reads nothing of the space');
    assert.equal(JSON.stringify(read.body).includes('maintenance'), false);
  }
  expectStatus(await call(h, {}, 'GET', `/wiki/spaces/${mine.spaceId}/health`), 401, 'nobody signed in reads nothing');
  expectStatus(await call(h, { bearer: mine.owner.bearer }, 'GET', `/wiki/spaces/${randomUUID()}/health`), 404, 'a space nobody has');
  expectStatus(await health(h, mine), 200, 'its owner reads it');

  // Their runs fail three times: their owner is told, and nobody else.
  const { run } = await startRun(h, theirs);
  for (const n of [1, 2, 3]) await fail(h, theirs, run, 'finish', `theirs ${n}`);
  assert.deepEqual(pushesFor(h, theirs).map((one) => one.ownerId), [theirs.owner.id]);
  assert.equal(h.pushed.some((one) => one.ownerId === mine.owner.id), false, 'my phone does not ring for their space');
  // Their failures are no part of my space's health.
  const my = await readHealth(h, mine);
  assert.equal(my.maintenance.consecutiveFailures, 0);
  assert.notEqual(my.maintenance.look, 'failing');
  // And their runner cannot report into my space: the run is not a maintenance session of it.
  const foreign = await call(h, { runner: theirs.machine.token, session: run }, 'POST', `/runner/wiki/spaces/${mine.spaceId}/cursor`, {
    outcome: 'failed',
    error: 'not yours',
  });
  assert.equal(foreign.status, 404, `another owner's runner is answered the plain 404: ${JSON.stringify(foreign.body).slice(0, 300)}`);
  assert.equal((await readHealth(h, mine)).maintenance.consecutiveFailures, 0);
});
