/**
 * What the spaces list adds to each space (contract `space.list`), over real HTTP and against a real
 * PostgreSQL: `planWaiting`, the things of its plan that wait on the owner; `workspaceIds`, the live
 * workspaces bound to it, in their public spelling; and `docs`, its confirmed plan's documents, written of
 * how many. One owner with four spaces, each in a different state:
 *
 *   - bare: made and never set up — its first draft held for a maintenance workspace: 1, no plan;
 *   - quiet: no job and no plan, three workspaces bound and one of them deleted: 0;
 *   - full: a confirmed plan with one document written, a draft waiting, two proposals and a revision that
 *     failed — 4 — beside a pending changeset op that `pendingOps` counts and `planWaiting` does not;
 *   - offline: a draft made and not started, whose runner is offline, then online, then quiet past the
 *     heartbeat window, then gone from the workspace — as the runners list and the clients read it.
 *
 * Every row's `planWaiting` is also the count of what its own plan read says (`wikiPlanWaiting`, held to
 * the clients' vectors in wiki-plan-waiting.spec.ts), and its `docs` the directory's.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-spaces-read.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { toUuid, uuidToBase62, type WikiPlanState } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiDocsController } from '../runner-api/runner-wiki-docs.controller';
import { RunnerWikiPlanController } from '../runner-api/runner-wiki-plan.controller';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiDocs } from './wiki-docs';
import { WikiDocsController } from './wiki-docs.controller';
import { WikiPlans } from './wiki-plan';
import { WikiPlanController } from './wiki-plan.controller';
import { wikiPlanWaiting } from './wiki-plan-waiting';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiController } from './wiki.controller';
import { WikiService } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = { notifyWikiReviewModeTripped: async () => undefined, notifyWikiVerificationTripped: async () => undefined } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);
    const plans = new WikiPlans(prisma as unknown as PrismaService, hub);
    const docs = new WikiDocs(prisma as unknown as PrismaService, service, hub);

    @Module({
      controllers: [WikiController, WikiPlanController, WikiDocsController, RunnerWikiController, RunnerWikiPlanController, RunnerWikiDocsController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiPlans, useValue: plans },
        { provide: WikiDocs, useValue: docs },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiSpacesReadModule {}

    const app = await NestFactory.create(WikiSpacesReadModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 1500)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [id, `wiki-spaces-${id}@wiki.invalid`, name]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

/** A runner as enrollment leaves it: OFFLINE, never heard from. */
async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

/** A runner's last word: its status, and how many seconds ago its heartbeat was (null: never). */
async function heard(h: Harness, runnerId: string, status: 'ONLINE' | 'OFFLINE', secondsAgo: number | null): Promise<void> {
  await h.sql.query(
    `UPDATE "runner" SET "status" = $2::runner_status,
                         "last_heartbeat_at" = CASE WHEN $3::int IS NULL THEN NULL ELSE now() - make_interval(secs => $3::int) END
      WHERE "id" = $1`,
    [runnerId, status, secondsAgo],
  );
}

async function workspace(h: Harness, ownerId: string, runnerId: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","runner_id") VALUES ($1,'spec',$2,$3)`, [id, ownerId, runnerId]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string, runnerId: string, taskId: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","status","dispatch_origin","updated_at")
     VALUES ($1,'a session','p',$2,$2,$3,$4,$5,'RUNNING'::run_status,'USER',now())`,
    [id, ownerId, workspaceId, runnerId, taskId],
  );
  return id;
}

async function task(h: Harness, ownerId: string, listId: string, assigneeId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id",
                         "completion_criterion","updated_at")
     VALUES ($1,'Wiki maintenance run',$2,'USER',$2,'OPEN'::task_status,$3,$4,'OWNER_CONFIRMED',now())`,
    [id, ownerId, assigneeId, listId],
  );
  return id;
}

async function toolCall(h: Harness, sessionId: string, output: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","output","started_at") VALUES ($1,$2,'Bash',$3,now())`, [id, sessionId, JSON.stringify(output)]);
  return id;
}

async function space(h: Harness, owner: Account, title: string): Promise<string> {
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title });
  expectStatus(made, 201, `the owner creates «${title}»`);
  return toUuid(made.body.id as string);
}

async function bind(h: Harness, owner: Account, spaceId: string, workspaceId: string): Promise<void> {
  expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId }), 200, 'the owner binds a workspace');
}

/** Maintenance on, in this workspace: the space's hidden list, and a maintenance run of it. */
async function maintain(
  h: Harness,
  owner: Account,
  spaceId: string,
  workspaceId: string,
  machine: { id: string; token: string },
): Promise<Caller & { session: string }> {
  const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true, workspaceId } });
  expectStatus(on, 200, 'the owner turns maintenance on');
  const listId = toUuid(on.body.settings.maintenance.listId as string);
  const run = await session(h, owner.id, workspaceId, machine.id, await task(h, owner.id, listId, workspaceId));
  return { runner: machine.token, session: run };
}

/**
 * The space's plan job, exactly: every job it has is taken away, and this one row written in its place —
 * what the doors made on the way here (a draft asked when the space was made, a build its confirmation
 * asked for) depends on whether a maintenance provider is set up, and the count is the subject here.
 */
async function onlyJob(
  h: Harness,
  ownerId: string,
  spaceId: string,
  job: { kind: 'draft' | 'revise' | 'build'; state: 'held' | 'made' | 'ended'; outcome?: 'succeeded' | 'failed'; startedAt?: boolean; version?: number } | null,
): Promise<void> {
  await h.sql.query(`DELETE FROM "wiki_plan_job" WHERE "space_id" = $1`, [spaceId]);
  if (!job) return;
  const made = job.state !== 'held';
  await h.sql.query(
    `INSERT INTO "wiki_plan_job"("id","space_id","owner_id","kind","trigger","instructions","state","held_reason","held_at",
                                 "task_id","made_at","started_at","ended_at","outcome","version","errors","error")
     VALUES ($1,$2,$3,$4,'owner',$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,
    [
      randomUUID(),
      spaceId,
      ownerId,
      job.kind,
      job.kind === 'revise' ? 'Split the session document in two.' : null,
      job.state,
      job.state === 'held' ? 'no_maintenance_workspace' : null,
      job.state === 'held' ? new Date() : null,
      made ? randomUUID() : null,
      made ? new Date() : null,
      job.startedAt ? new Date() : null,
      job.state === 'ended' ? new Date() : null,
      job.outcome ?? null,
      job.version ?? null,
      job.outcome === 'failed' ? JSON.stringify([{ check: 'docCount', path: 'plan.docs', message: 'too few documents' }]) : null,
      job.outcome === 'failed' ? 'the gate refused the third round' : null,
    ],
  );
}

// ── the plan ────────────────────────────────────────────────────────────────────────────────────

function docInput(slug: string, title: string): Record<string, unknown> {
  return {
    category: 'product',
    slug,
    title,
    question: `What is ${title}?`,
    audience: ['A new developer: can say how it works after reading it'],
    scopeIn: [`How ${slug} works`],
    scopeOut: [],
    length: { min: 800, max: 4000 },
    sections: [
      { title: '总览', kind: 'overview', covers: '它是什么。', length: 400, sources: {} },
      { title: '怎么运转', kind: 'flow', covers: '它的步骤。', length: 400, sources: {} },
    ],
  };
}

const PLAN = {
  categories: [{ key: 'product', title: 'Product', question: 'What Orbit is and how it runs' }],
  docs: [docInput('session-runtime', '会话运行模型'), docInput('task-dispatch', '任务派发'), docInput('runner-host', 'Runner 托管')],
};

const REPO = { sha: 'a'.repeat(40), checked: 3, missing: [] };

async function draft(h: Harness, maintainer: Caller, spaceId: string, baseVersion: number | null): Promise<number> {
  const drafted = await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/drafts`, {
    baseVersion,
    target: { min: 1, max: 10 },
    plan: PLAN,
    repoCheck: REPO,
    model: 'qwen3.8-27b-fp8',
  });
  expectStatus(drafted, 200, 'the maintenance run drafts the plan');
  return drafted.body.version as number;
}

const b62 = (id: string): string => uuidToBase62(id);

interface Row {
  id: string;
  pendingOps: number;
  planWaiting: number;
  workspaceIds: string[];
  workspacePublicIds?: string[];
  docs: { written: number; total: number } | null;
}

async function rows(h: Harness, owner: Account): Promise<Map<string, Row>> {
  const listed = await call(h, { bearer: owner.bearer }, 'GET', '/wiki/spaces');
  expectStatus(listed, 200, 'the owner lists their spaces');
  return new Map((listed.body as Row[]).map((row) => [toUuid(row.id), row]));
}

/** What the space's own plan read says waits on the owner, counted by the rule the list counts by. */
async function fromPlanRead(h: Harness, owner: Account, spaceId: string, runnerOnline: boolean | null): Promise<number> {
  const read = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${spaceId}/plan`);
  expectStatus(read, 200, 'the plan read');
  return wikiPlanWaiting(read.body as WikiPlanState, runnerOnline);
}

// ── the list ────────────────────────────────────────────────────────────────────────────────────

test('each space carries what of its plan waits on the owner, the workspaces bound to it and its documents written', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);

  // bare: made and nothing set up — its first draft is held for a maintenance workspace.
  const bare = await space(h, owner, 'A bare space');

  // quiet: no job, no plan; three workspaces bound in turn, the last of them deleted since.
  const quiet = await space(h, owner, 'A quiet space');
  await onlyJob(h, owner.id, quiet, null);
  const [wsA, wsB, wsGone] = [await workspace(h, owner.id), await workspace(h, owner.id), await workspace(h, owner.id)];
  for (const ws of [wsA, wsB, wsGone]) await bind(h, owner, quiet, ws);
  await h.sql.query(`UPDATE "workspace" SET "deleted_at" = now() WHERE "id" = $1`, [wsGone]);

  // full: v1 confirmed with one of its three documents written, two proposals, v2 drafted, a revision failed.
  const full = await space(h, owner, 'A full space');
  const wsFull = await workspace(h, owner.id, machine.id);
  await bind(h, owner, full, wsFull);
  const maintainer = await maintain(h, owner, full, wsFull, machine);
  const v1 = await draft(h, maintainer, full, null);
  expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${full}/plan/versions/${v1}/confirm`), 200, 'the owner confirms v1');
  expectStatus(await call(h, maintainer, 'POST', `/runner/wiki/spaces/${full}/docs/session-runtime`, {
    planVersion: v1,
    repoSha: 'c'.repeat(40),
    model: 'qwen3.8-27b-fp8',
    sections: [{ key: 's1', materialSha256: 'd'.repeat(64), markdown: 'Orbit 的会话跑在 runner 上。turn 先落库再投递。', footnotes: [] }],
  }), 200, 'one document is written');
  for (const slug of ['wiki-plan', 'wiki-docs']) {
    expectStatus(await call(h, maintainer, 'POST', `/runner/wiki/spaces/${full}/plan/proposals`, {
      reason: `The plan has no document for ${slug}.`,
      change: { doc: docInput(slug, slug) },
      facts: [{ kind: 'session', id: maintainer.session }],
    }), 200, `a proposal for ${slug}`);
  }
  const v2 = await draft(h, maintainer, full, v1);
  assert.equal(v2, v1 + 1);
  await onlyJob(h, owner.id, full, { kind: 'revise', state: 'ended', outcome: 'failed', startedAt: true });
  // A changeset op waiting in Review, beside the plan: the sidebar's number, which the plan's never joins.
  // Manual, so that the agent's add waits for the owner whatever the other modes would make of it.
  expectStatus(await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${full}`, { reviewMode: 'manual' }), 200, 'the owner sets Manual');
  const ordinary = await session(h, owner.id, wsFull, machine.id);
  const tool = await toolCall(h, ordinary, 'a pg spec that skips itself proves nothing');
  const proposed = await call(h, { runner: maintainer.runner, session: ordinary }, 'POST', '/runner/wiki/changesets', {
    rationale: 'one proposal',
    ops: [{
      op: 'add',
      entry: {
        kind: 'pitfall',
        title: 'A pg spec that skips itself proves nothing',
        summary: 'A pg spec skips itself when its URL is unset.',
        fields: {
          trigger: { paths: ['src/apiserver/src/wiki/*.pg.spec.ts'], commands: ['node --test build/x.pg.spec.js'] },
          symptom: 'node exits 0 and no assertion ran.',
          cause: 'A pg spec skips itself when the URL is unset.',
          fix: 'Run it through scripts/run-pg-spec.sh, which treats a skip as red.',
        },
      },
      sources: [{ kind: 'tool_call', ref: tool, quote: 'skips itself' }],
    }],
  });
  expectStatus(proposed, 200, 'an agent proposes an entry');

  // offline: maintenance in a workspace on a second runner, and its draft made but not started.
  const offline = await space(h, owner, 'An offline space');
  const elsewhere = await runner(h, owner.id);
  const wsOff = await workspace(h, owner.id, elsewhere.id);
  await bind(h, owner, offline, wsOff);
  await maintain(h, owner, offline, wsOff, elsewhere);
  await onlyJob(h, owner.id, offline, { kind: 'draft', state: 'made' });

  // Another owner's space is in nobody's list but theirs.
  const stranger = await account(h, 'stranger');
  const theirs = await space(h, stranger, 'Not yours');

  const listed = await rows(h, owner);
  assert.deepEqual([...listed.keys()].sort(), [bare, quiet, full, offline].sort(), 'the owner lists their four spaces, and only those');

  const bareRow = listed.get(bare)!;
  assert.deepEqual([bareRow.planWaiting, bareRow.docs, bareRow.workspaceIds, bareRow.pendingOps], [1, null, [], 0], 'bare: the draft held, no plan, nothing bound');

  const quietRow = listed.get(quiet)!;
  assert.deepEqual([quietRow.planWaiting, quietRow.docs, quietRow.pendingOps], [0, null, 0], 'quiet: nothing waits, no plan');
  assert.deepEqual(quietRow.workspaceIds, [b62(wsA), b62(wsB)], 'the live workspaces, in the order they were bound, in their public spelling');
  assert.deepEqual(quietRow.workspacePublicIds, quietRow.workspaceIds, 'the codec\'s twin says the same');

  const fullRow = listed.get(full)!;
  assert.equal(fullRow.planWaiting, 4, 'full: the draft to confirm, two proposals and the revision that failed');
  assert.equal(fullRow.pendingOps, 1, 'the changeset op is the sidebar\'s, and the plan\'s proposals are not');
  assert.deepEqual(fullRow.docs, { written: 1, total: 3 }, 'one of the confirmed plan\'s three documents written');
  assert.deepEqual(fullRow.workspaceIds, [b62(wsFull)]);
  const directory = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${full}/docs`);
  expectStatus(directory, 200, 'the directory');
  assert.deepEqual(fullRow.docs, directory.body.docs, 'the list counts the documents as the directory does');
  assert.equal(directory.body.plan.version, v1, 'counted from the confirmed version, not the draft');

  const offlineRow = listed.get(offline)!;
  assert.deepEqual([offlineRow.planWaiting, offlineRow.docs, offlineRow.workspaceIds], [1, null, [b62(wsOff)]], 'offline: made, not started, its runner offline: held');

  // Every row says what its own plan read says, counted by the clients' rule.
  for (const [spaceId, runnerOnline] of [[bare, null], [quiet, null], [full, false], [offline, false]] as const) {
    assert.equal(listed.get(spaceId)!.planWaiting, await fromPlanRead(h, owner, spaceId, runnerOnline), `the plan read of ${spaceId}`);
  }

  const strangers = await rows(h, stranger);
  assert.deepEqual([...strangers.keys()], [theirs]);
  assert.deepEqual([strangers.get(theirs)!.planWaiting, strangers.get(theirs)!.workspaceIds], [1, []]);
});

test('a draft made and not started waits on the owner only while its runner is known to be offline, by the runners list\'s own rule', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const spaceId = await space(h, owner, 'A space on one runner');
  const ws = await workspace(h, owner.id, machine.id);
  await bind(h, owner, spaceId, ws);
  await maintain(h, owner, spaceId, ws, machine);
  await onlyJob(h, owner.id, spaceId, { kind: 'draft', state: 'made' });
  const waiting = async () => (await rows(h, owner)).get(spaceId)!.planWaiting;

  assert.equal(await waiting(), 1, 'never heard from: offline');
  await heard(h, machine.id, 'ONLINE', 5);
  assert.equal(await waiting(), 0, 'heard from five seconds ago: online, and the draft only waits for its run');
  assert.equal(await fromPlanRead(h, owner, spaceId, true), 0);
  await heard(h, machine.id, 'ONLINE', 300);
  assert.equal(await waiting(), 1, 'quiet for five minutes, whatever its status says: offline');
  await heard(h, machine.id, 'OFFLINE', 5);
  assert.equal(await waiting(), 1, 'marked offline: offline');

  // Started: the run is under way on its runner, offline or not — nothing waits on the owner.
  await onlyJob(h, owner.id, spaceId, { kind: 'draft', state: 'made', startedAt: true });
  assert.equal(await waiting(), 0, 'a run under way');

  // A runner nobody can see: the workspace has none, or the space names a workspace since deleted — unknown, not offline.
  await onlyJob(h, owner.id, spaceId, { kind: 'draft', state: 'made' });
  await h.sql.query(`UPDATE "workspace" SET "runner_id" = NULL WHERE "id" = $1`, [ws]);
  assert.equal(await waiting(), 0, 'a workspace with no runner');
  assert.equal(await fromPlanRead(h, owner, spaceId, null), 0);
  await h.sql.query(`UPDATE "workspace" SET "runner_id" = $2, "deleted_at" = now() WHERE "id" = $1`, [ws, machine.id]);
  assert.equal(await waiting(), 0, 'a maintenance workspace deleted');
  assert.deepEqual((await rows(h, owner)).get(spaceId)!.workspaceIds, [], 'and it is no longer listed as bound');

  // The build of a confirmed version, held: the writing waits on the owner as a draft does.
  await onlyJob(h, owner.id, spaceId, { kind: 'build', state: 'held', version: 1 });
  assert.equal(await waiting(), 1, 'the writing held');
  // A build that failed is not counted, as the clients do not count it.
  await onlyJob(h, owner.id, spaceId, { kind: 'build', state: 'ended', outcome: 'failed', startedAt: true, version: 1 });
  assert.equal(await waiting(), 0, 'a build that failed');
});
