/**
 * Automatic verifies before it applies (criterion 7, revision 3; contracts/wiki.contract.json
 * `reviewModes.verification`), over real HTTP and against a real PostgreSQL.
 *
 * What the criterion asks of Automatic and of the spot checks, each read back from the database and
 * from the push the way a session would be handed it:
 *
 *   1. an op Automatic takes waits for its verification: nothing of it applies, it is pushed to
 *      nobody, it is no card in Review, and it takes no place in the queue or the quotas;
 *   2. the four verdicts, each with its own result — supported applies as Auto and is pushed, partial
 *      as Unreviewed, unsupported is rejected with its reason (which the next similar[] shows), and a
 *      duplicate becomes a reinforce of the entry it names — and the trail each leaves on its op;
 *   3. only the session that proposed may report, and anything of another owner's is a 404;
 *   4. no clock moves a waiting op, a space no longer Automatic records no verdict, and a revert
 *      withdraws what still waits;
 *   5. more than 30% unsupported among the latest 50 verdicts sends the space back to Tiered, and the
 *      owner is told once — through the one-off import's own service path, which leaves the same trail;
 *   6. Automatic sends no spot-check card unless the owner turns them on, then one in every 200; and a
 *      spot-check card takes no place in the 30-op queue.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-verify.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in `wiki-review-mode.pg.spec.ts`; the
 * push is the real `appendWikiContext`, and the owner's notifications stand-ins that record each call.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { Prisma, PrismaClient } from '@prisma/client';
import { WIKI_LIMITS, WIKI_MAINTENANCE_LIST_TITLE, WIKI_REVIEW_RULES, toUuid, type WikiKind } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import type { RealtimeService } from '../realtime/realtime.service';
import { WikiController } from './wiki.controller';
import { appendWikiContext } from './wiki-push';
import { WikiRetrieval } from './wiki-retrieval';
import { isSpotCheckDraw, WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The push as a session starting now would be handed it: the wiki on, whatever this shell says. */
const WIKI_ON = { mode: 'on' as const, canaryOwners: new Set<string>(), problems: [] };

type Mode = 'manual' | 'tiered' | 'automatic';

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  bearers: Map<string, string>;
  /** Every notification that a space's verification sent it back to Tiered, in order. */
  fellBack: Array<{ ownerId: string; spaceId: string; unsupported: number; window: number }>;
  /** And every one that its spot checks sent it back to Manual. */
  trippedToManual: Array<{ ownerId: string; spaceId: string }>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const fellBack: Harness['fellBack'] = [];
    const trippedToManual: Harness['trippedToManual'] = [];
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = {
      notifyWikiVerificationTripped: async (input: Harness['fellBack'][number]) => {
        fellBack.push({ ownerId: input.ownerId, spaceId: input.spaceId, unsupported: input.unsupported, window: input.window });
      },
      notifyWikiReviewModeTripped: async (input: { ownerId: string; spaceId: string }) => {
        trippedToManual.push({ ownerId: input.ownerId, spaceId: input.spaceId });
      },
    } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);

    @Module({
      controllers: [WikiController, RunnerWikiController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiVerifyModule {}

    const app = await NestFactory.create(WikiVerifyModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, bearers, fellBack, trippedToManual };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  headers?: Record<string, string>;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json', ...(who.headers ?? {}) };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

interface Outcome {
  seq: number;
  status: 'pending' | 'applied' | 'conflict' | 'refused';
  opId?: string | null;
  entryId?: string | null;
  waitsFor?: string;
  reasons?: Array<{ code: string; message: string }>;
  similar?: Array<{ id: string; status?: string; rejectedReason?: string; rejectedBecause?: string }>;
}

interface VerificationItem {
  opId: string;
  changesetId: string;
  op: 'add' | 'amend';
  entryId: string | null;
  entry: { kind: string; title: string; summary: string; fields: Record<string, unknown> };
  sources: Array<{ kind: string; ref: string; quote: string | null; text: string | null; truncated: boolean }>;
  similar: Array<{ id: string; title: string; status: string; trust: string }>;
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-verify-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return token;
}

async function runnerId(h: Harness, token: string): Promise<string> {
  const row = await h.sql.query<{ id: string }>(`SELECT "id" FROM "runner" WHERE "token_hash" = $1`, [
    createHash('sha256').update(token).digest('hex'),
  ]);
  return row.rows[0].id;
}

async function workspace(h: Harness, ownerId: string, env: Record<string, string> = {}): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env") VALUES ($1,'spec',$2,$3)`, [id, ownerId, JSON.stringify(env)]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string | null, machine: string | null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "dispatch_origin","updated_at")
     VALUES ($1,'a wiki session','p',$2,$2,$3,$4,'USER',now())`,
    [id, ownerId, workspaceId, machine ? await runnerId(h, machine) : null],
  );
  return id;
}

async function toolCall(h: Harness, sessionId: string, name: string, output: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","output") VALUES ($1,$2,$3,$4)`, [
    id,
    sessionId,
    name,
    JSON.stringify(output),
  ]);
  return id;
}

/** A space the owner makes through the door and puts in a mode, bound to a workspace when one is named. */
async function modeSpace(h: Harness, owner: Account, mode: Mode, workspaceId?: string): Promise<string> {
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: `A ${mode} space` });
  expectStatus(made, 201, 'the owner creates a space');
  const id = made.body.id as string;
  const switched = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${id}`, { reviewMode: mode });
  expectStatus(switched, 200, `the owner puts the space in ${mode}`);
  if (workspaceId) {
    const bound = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${id}/workspaces`, { workspaceId });
    expectStatus(bound, 200, 'the owner binds the workspace');
  }
  return toUuid(id);
}

/** A valid draft of each kind, retitled per use. */
function draft(kind: WikiKind, title: string, summary = `What the space knows about ${title.toLowerCase()}.`): Record<string, unknown> {
  const fields: Record<WikiKind, Record<string, unknown>> = {
    principle: { statement: 'When a record is deleted, every quote taken from it goes too.', rationale: 'Owners delete to forget.' },
    convention: { rule: 'Model a closed set as TEXT plus a CHECK constraint.', scope: ['src/apiserver/prisma/migrations/**'] },
    decision: {
      context: 'People ask what is true now.',
      decision: 'Store atomic entries and project every page from them.',
      alternatives: [{ option: 'A page-shaped wiki', whyRejected: 'Whole-page rewrites collapse.' }],
      consequences: 'Every view can be rebuilt.',
      decidedAt: '2026-09-26',
    },
    pitfall: {
      trigger: { paths: ['src/apiserver/src/wiki/'], commands: ['node --test build/wiki/x.pg.spec.js'] },
      symptom: 'A green run that witnessed no assertion.',
      cause: 'A pg spec skips itself without a database.',
      fix: 'Run it through scripts/run-pg-spec.sh.',
    },
    recipe: {
      steps: ['bash scripts/worktree-overlay.sh', 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-schema.pg.spec.ts'],
      verify: { command: 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-schema.pg.spec.ts', expectedExit: 0 },
    },
    concept: { definition: 'One owner\'s knowledge about one codebase.', boundaries: 'A space never spans owners.' },
  };
  return { kind, title, summary, fields: fields[kind] };
}

/**
 * An entry a review mode applied earlier, live with the machine's trust — written directly, in the
 * shape 0307's CHECKs ask (status and trust agree, no successor, no retirement), with the revision
 * and the source `applyOp` would have written.
 */
async function machineEntry(h: Harness, ownerId: string, spaceId: string, kind: WikiKind, title: string, sourceSession: string): Promise<string> {
  const id = randomUUID();
  const body = draft(kind, title);
  await h.sql.query(
    `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields")
     VALUES ($1,$2,$3,$4,'active','auto',1,$5,$6,$7)`,
    [id, ownerId, spaceId, kind, body.title, body.summary, JSON.stringify(body.fields)],
  );
  const revision = randomUUID();
  await h.sql.query(
    `INSERT INTO "wiki_entry_revision"("id","entry_id","owner_id","revision","title","summary","fields","content_sha256","author_kind")
     VALUES ($1,$2,$3,1,$4,$5,$6,$7,'agent')`,
    [revision, id, ownerId, body.title, body.summary, JSON.stringify(body.fields), 'b'.repeat(64)],
  );
  await h.sql.query(`INSERT INTO "wiki_source"("id","revision_id","owner_id","kind","ref") VALUES ($1,$2,$3,'turn',$4)`, [
    randomUUID(),
    revision,
    ownerId,
    sourceSession,
  ]);
  return id;
}

/** The principal a one-off import in the API server's container runs as (reviewModes.verification.who.import). */
function importer(ownerId: string): WikiPrincipal {
  return { origin: 'import', ownerId, userId: null, sessionId: null, toolCallId: null, authorKind: 'system' };
}

/** `count` adds of distinct concepts, each citing a record by its bare id: no quote. */
function importOps(count: number, cite: string, prefix: string): Array<Record<string, unknown>> {
  return Array.from({ length: count }, (_unused, n) => ({
    op: 'add',
    entry: draft('concept', `${prefix} concept ${n + 1} ${randomUUID().slice(0, 8)}`),
    sources: [{ kind: 'tool_call', ref: cite }],
  }));
}

async function entryRow(h: Harness, id: string) {
  return h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(id) } });
}

async function opRow(h: Harness, id: string) {
  return h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: toUuid(id) } });
}

/** The entries the next session in this workspace is handed, by id. */
async function pushed(h: Harness, ownerId: string, workspaceId: string, sessionId: string): Promise<Set<string>> {
  const content = await appendWikiContext(h.prisma as unknown as Prisma.TransactionClient, {
    sessionId,
    turnId: randomUUID(),
    leaseGeneration: randomUUID(),
    ownerId,
    workspaceId,
    taskId: null,
    task: null,
    dispatchOrigin: 'USER',
    content: 'What should I know about this codebase?',
  }, WIKI_ON);
  return new Set([...String(content).matchAll(/\(orbit-wiki:([0-9A-Za-z]+)\)/gu)].map((match) => toUuid(match[1])));
}

/** What the verification list hands the calling session, every page of it. */
async function listed(h: Harness, who: Caller, spaceId: string): Promise<VerificationItem[]> {
  const items: VerificationItem[] = [];
  let after: string | null = null;
  for (let page = 0; page < 50; page += 1) {
    const answer = await call(h, who, 'GET', `/runner/wiki/spaces/${spaceId}/verifications?limit=2${after ? `&after=${after}` : ''}`);
    expectStatus(answer, 200, 'the verification list');
    items.push(...(answer.body.items as VerificationItem[]));
    after = answer.body.next;
    if (!after) return items;
  }
  throw new Error('the verification list never ended');
}

/**
 * A maintenance run of the space, as `isWikiMaintenanceSession` reads one: a session whose task is in the
 * space's «Wiki maintenance» list (`settings.maintenance.listId`). What the server's own verification must
 * leave exactly as it was (contract `reviewModes.verification.servedBy`): the run verifies its own ops in
 * its own process until P8.
 */
async function maintenanceSession(h: Harness, owner: Account, machine: string, spaceId: string, workspaceId: string): Promise<string> {
  const listId = randomUUID();
  await h.prisma.taskList.create({
    data: { id: listId, ownerId: owner.id, title: WIKI_MAINTENANCE_LIST_TITLE, hidden: true, maxConcurrent: 1 },
  });
  await h.sql.query(
    `UPDATE "wiki_space" SET "settings" = jsonb_set(COALESCE("settings", '{}'::jsonb), '{maintenance}',
                                                    jsonb_build_object('listId', $2::text)) WHERE "id" = $1`,
    [spaceId, listId],
  );
  const taskId = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","list_id","completion_criterion","updated_at")
     VALUES ($1,'a maintenance run',$2,'USER',$2,'OPEN',$3,'OWNER_CONFIRMED', now())`,
    [taskId, owner.id, listId],
  );
  const sessionId = await session(h, owner.id, workspaceId, machine);
  await h.sql.query(`UPDATE "session" SET "task_id" = $2 WHERE "id" = $1`, [sessionId, taskId]);
  return sessionId;
}

/** How many verify jobs this session and space are owed (contract `jobs.make`). */
async function verifyJobs(h: Harness, ownerId: string, spaceId: string, sessionId: string): Promise<number> {
  const { rows } = await h.sql.query<{ n: string }>(
    `SELECT count(*)::text AS n FROM "wiki_job"
      WHERE "owner_id" = $1 AND "space_id" = $2 AND "kind" = 'verify' AND "input" ->> 'sessionId' = $3`,
    [ownerId, spaceId, sessionId],
  );
  return Number(rows[0].n);
}

function verdict(opId: string, value: string, over: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    opId,
    verdict: value,
    reason: `The sources ${value === 'supported' ? 'bear every claim out' : value === 'partial' ? 'bear out only part of it' : 'do not say this'}.`,
    model: 'qwen3.8-27b-fp8',
    ...over,
  };
}

// ── 1. what waits ───────────────────────────────────────────────────────────────────────────────

test('verification · an op Automatic takes waits for its verdict, and nothing of it applies meanwhile', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'waits');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const evidence = await toolCall(h, records, 'Bash', 'what the run observed about closed sets');
  const cite = [{ kind: 'tool_call', ref: evidence, quote: 'what the run observed' }];
  const proposer = await session(h, owner.id, ws, machine);
  const mine = { runner: machine, headers: { 'x-orbit-session-id': proposer } };
  const target = await machineEntry(h, owner.id, space, 'pitfall', 'A pitfall an earlier run applied', records);

  // Six ops in one turn: more than opsPerTurn, because what waits for a verdict waits on nobody's queue.
  const ops = [
    ...Array.from({ length: WIKI_LIMITS.opsPerTurn }, (_unused, n) => ({ op: 'add', entry: draft('pitfall', `A waiting pitfall ${n + 1}`), sources: cite })),
    { op: 'amend', entryId: target, baseRevision: 1, changes: { summary: 'A sharper summary nobody has verified yet.' }, sources: cite },
  ];
  const answer = await call(h, mine, 'POST', '/runner/wiki/changesets', { rationale: 'a batch that waits', ops, idempotencyKey: `waits-${randomUUID()}` });
  expectStatus(answer, 200, 'the batch');
  const outcomes = answer.body.ops as Outcome[];

  await t.test('each op is pending, and says it waits for its verification rather than for the owner', async () => {
    assert.deepEqual(outcomes.map((op) => [op.status, op.waitsFor]), Array(ops.length).fill(['pending', 'verification']));
    for (const outcome of outcomes) {
      const op = await opRow(h, outcome.opId!);
      assert.equal(op.decision, 'verifying');
      assert.equal(op.appliedByMode, null, 'no mode has applied it');
      assert.equal(op.decidedAt, null, 'and nothing has decided it');
      assert.equal(op.verificationVerdict, null);
    }
    const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(answer.body.changesetId) } });
    assert.equal(changeset.status, 'pending', 'the changeset is open while its ops wait');
  });

  await t.test('nothing of it is live: an add is born proposed, an amend changes nothing, and none is pushed', async () => {
    for (const outcome of outcomes.slice(0, WIKI_LIMITS.opsPerTurn)) {
      const entry = await entryRow(h, outcome.entryId!);
      assert.equal(entry.status, 'proposed');
      assert.equal(entry.trust, 'proposed');
    }
    const amended = await entryRow(h, target);
    assert.equal(amended.currentRevision, 1, 'an amend waiting for its verdict wrote no revision');
    // The adds are pushed to nobody; the amend's entry goes on being pushed as it was, unamended.
    const handed = await pushed(h, owner.id, ws, await session(h, owner.id, ws, machine));
    for (const outcome of outcomes.slice(0, WIKI_LIMITS.opsPerTurn)) {
      assert.equal(handed.has(toUuid(outcome.entryId!)), false, 'pushed before any verdict');
    }
    assert.ok(handed.has(target), 'the live entry an amend waits on is still what it was, and still pushed');
  });

  await t.test('it is no card in Review, and takes no place in the queue', async () => {
    const review = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/review?space=${space}`);
    expectStatus(review, 200, 'Review');
    assert.deepEqual(review.body, [], 'Review lists nothing the owner has to decide');
    const listed = await call(h, { bearer: owner.bearer }, 'GET', '/wiki/spaces');
    assert.equal((listed.body as Array<{ id: string; pendingOps: number }>).find((s) => toUuid(s.id) === space)?.pendingOps, 0);
  });

  await t.test('a dry run says the same, and records nothing', async () => {
    const dry = await call(h, mine, 'POST', '/runner/wiki/changesets', {
      rationale: 'checked first', ops: [{ op: 'add', entry: draft('pitfall', 'A dry pitfall'), sources: cite }], idempotencyKey: `dry-${randomUUID()}`, dryRun: true,
    });
    expectStatus(dry, 200, 'the dry run');
    assert.equal(dry.body.ops[0].status, 'pending');
    assert.equal(dry.body.ops[0].waitsFor, 'verification');
    assert.equal(await h.prisma.wikiEntry.count({ where: { spaceId: space, title: 'A dry pitfall' } }), 0);
  });

  await t.test('the list hands the proposer its ops: the entry as it would read, and each source\'s text, redacted', async () => {
    const secretSession = await session(h, owner.id, ws, machine);
    const secret = await toolCall(h, secretSession, 'Bash', 'curl -H "Authorization: Bearer abcdefghijklmnopqrstuvwx0123" reported the index missing');
    const proposed = await call(h, mine, 'POST', '/runner/wiki/changesets', {
      rationale: 'cites a record with a credential in it',
      ops: [{ op: 'add', entry: draft('pitfall', 'The index was missing'), sources: [{ kind: 'tool_call', ref: secret, quote: 'reported the index missing' }] }],
      idempotencyKey: `secret-${randomUUID()}`,
    });
    expectStatus(proposed, 200, 'the proposal');
    const items = await listed(h, mine, space);
    assert.equal(items.length, ops.length + 1, 'every op this session is waiting on, over every page');
    const amend = items.find((item) => item.op === 'amend')!;
    assert.equal(toUuid(amend.entryId!), target);
    assert.equal(amend.entry.summary, 'A sharper summary nobody has verified yet.', 'the amend laid over its entry');
    assert.equal(amend.entry.title, 'A pitfall an earlier run applied');
    const cited = items.find((item) => item.entry.title === 'The index was missing')!;
    assert.equal(cited.sources.length, 1);
    assert.match(cited.sources[0].text!, /reported the index missing/u, 'the record\'s own text');
    assert.doesNotMatch(cited.sources[0].text!, /abcdefghijklmnopqrstuvwx0123/u, 'and never its credential');
    assert.match(cited.sources[0].text!, /\[redacted\]/u);
    assert.equal(cited.sources[0].quote, 'reported the index missing');
  });
});

// ── 2. the four verdicts ────────────────────────────────────────────────────────────────────────

test('verification · four verdicts, each with its own result, and the trail each leaves on its op', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'verdicts');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const evidence = await toolCall(h, records, 'Bash', 'the spec skipped every case without a database');
  const cite = [{ kind: 'tool_call', ref: evidence, quote: 'the spec skipped every case' }];
  const existing = await machineEntry(h, owner.id, space, 'convention', 'Closed sets are CHECK constraints', records);
  const proposer = await session(h, owner.id, ws, machine);
  const mine = { runner: machine, headers: { 'x-orbit-session-id': proposer } };
  const request = {
    rationale: 'four claims to verify',
    idempotencyKey: `four-${randomUUID()}`,
    ops: [
      { op: 'add', entry: draft('pitfall', 'A pg spec skips without a database'), sources: cite },
      { op: 'add', entry: draft('convention', 'Run pg specs through the runner script'), sources: cite },
      { op: 'add', entry: draft('pitfall', 'Tmpfs fills up during every build'), sources: cite },
      { op: 'add', entry: draft('convention', 'Closed sets are CHECK constraints'), sources: cite },
    ],
  };
  const proposed = await call(h, mine, 'POST', '/runner/wiki/changesets', request);
  expectStatus(proposed, 200, 'the proposal');
  const [supported, partial, unsupported, duplicate] = (proposed.body.ops as Outcome[]).map((op) => op);
  const items = await listed(h, mine, space);
  const itemOf = (outcome: Outcome) => items.find((item) => item.opId === outcome.opId)!;
  const neighbour = itemOf(duplicate).similar.find((near) => toUuid(near.id) === existing);
  assert.ok(neighbour, `the duplicate's similar[] names the entry it duplicates: ${JSON.stringify(itemOf(duplicate).similar)}`);
  assert.equal(neighbour!.status, 'active');

  const report = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, {
    verdicts: [
      verdict(supported.opId!, 'supported'),
      verdict(partial.opId!, 'partial'),
      verdict(unsupported.opId!, 'unsupported', { reason: 'Nothing in the cited output mentions tmpfs.' }),
      verdict(duplicate.opId!, 'duplicate', { duplicateOf: neighbour!.id, reason: 'The space already says this.' }),
    ],
  });
  expectStatus(report, 200, 'the report');
  assert.equal(report.body.mode, 'automatic');
  assert.deepEqual((report.body.outcomes as Array<{ status: string }>).map((o) => o.status), ['applied', 'applied', 'rejected', 'reinforced']);

  await t.test('supported applies as Auto and is pushed; partial applies as Unreviewed and is not', async () => {
    const s = await entryRow(h, supported.entryId!);
    assert.equal(s.status, 'active');
    assert.equal(s.trust, 'auto');
    const p = await entryRow(h, partial.entryId!);
    assert.equal(p.status, 'active');
    assert.equal(p.trust, 'unreviewed');
    for (const outcome of [supported, partial]) {
      const op = await opRow(h, outcome.opId!);
      assert.equal(op.decision, 'auto_applied');
      assert.equal(op.appliedByMode, 'automatic', 'the mode applied it, by its verdict');
      assert.ok(op.decidedAt);
    }
    const handed = await pushed(h, owner.id, ws, await session(h, owner.id, ws, machine));
    assert.ok(handed.has(s.id), 'supported is pushed');
    assert.equal(handed.has(p.id), false, 'partial is shown, never pushed');
  });

  await t.test('unsupported is rejected with its reason, and the next similar[] says why', async () => {
    const u = await entryRow(h, unsupported.entryId!);
    assert.equal(u.status, 'rejected');
    assert.equal(u.trust, 'proposed');
    const op = await opRow(h, unsupported.opId!);
    assert.equal(op.decision, 'rejected');
    assert.equal(op.decisionReason, 'not_true');
    assert.equal(op.verificationReason, 'Nothing in the cited output mentions tmpfs.');
    const again = await call(h, { runner: machine, headers: { 'x-orbit-session-id': await session(h, owner.id, ws, machine) } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'the same claim again',
      ops: [{ op: 'add', entry: draft('pitfall', 'Tmpfs fills up during every build'), sources: cite }],
      idempotencyKey: `again-${randomUUID()}`,
    });
    expectStatus(again, 200, 'the same claim again');
    const near = (again.body.ops[0] as Outcome).similar?.find((row) => toUuid(row.id) === u.id);
    assert.equal(near?.rejectedReason, 'not_true', 'a rejected neighbour says it was rejected');
    assert.equal(near?.rejectedBecause, 'Nothing in the cited output mentions tmpfs.', 'and, in the verifier\'s words, why');
  });

  await t.test('a duplicate becomes a reinforce: the named entry gains the sources, and nothing else changes', async () => {
    const d = await entryRow(h, duplicate.entryId!);
    assert.equal(d.status, 'rejected', 'the new lineage is not kept as a second copy');
    const op = await opRow(h, duplicate.opId!);
    assert.equal(op.decision, 'rejected');
    assert.equal(op.decisionReason, 'duplicate');
    assert.equal(op.verificationDuplicateOf, existing);
    const kept = await entryRow(h, existing);
    assert.equal(kept.currentRevision, 1, 'no new revision: only sources are added');
    assert.equal(kept.trust, 'auto');
    assert.equal(kept.title, 'Closed sets are CHECK constraints');
    const revision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: existing, revision: 1 } });
    const refs = (await h.prisma.wikiSource.findMany({ where: { revisionId: revision.id } })).map((source) => source.ref);
    assert.ok(refs.includes(evidence), `the duplicate's source was added to the entry it names: ${refs}`);
    assert.ok(refs.includes(records), 'beside the ones it had');
  });

  await t.test('every verdict leaves its trail on its op: the verdict, the reason, the model and when', async () => {
    for (const [outcome, value] of [[supported, 'supported'], [partial, 'partial'], [unsupported, 'unsupported'], [duplicate, 'duplicate']] as const) {
      const op = await opRow(h, outcome.opId!);
      assert.equal(op.verificationVerdict, value);
      assert.equal(op.verificationModel, 'qwen3.8-27b-fp8');
      assert.ok(op.verificationReason && op.verificationReason.length > 0);
      assert.ok(op.verifiedAt && op.verifiedAt.getTime() > Date.now() - 300_000);
    }
    const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(proposed.body.changesetId) } });
    assert.equal(changeset.status, 'settled', 'nothing of it waits any more');
    // A replay of the request is the answer THAT request got — every op pending, for its verification —
    // with what each has since become beside it.
    const replay = await call(h, mine, 'POST', '/runner/wiki/changesets', request);
    expectStatus(replay, 200, 'the replay');
    assert.equal(replay.body.replayed, true);
    assert.deepEqual((replay.body.ops as Array<Outcome & { decision?: string }>).map((op) => [op.status, op.waitsFor, op.decision]), [
      ['pending', 'verification', 'auto_applied'],
      ['pending', 'verification', 'auto_applied'],
      ['pending', 'verification', 'rejected'],
      ['pending', 'verification', 'rejected'],
    ]);
  });

  await t.test('the same verdict again is its recorded answer; another verdict is refused', async () => {
    const same = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, { verdicts: [verdict(supported.opId!, 'supported')] });
    expectStatus(same, 200, 'the same verdict again');
    assert.equal(same.body.outcomes[0].replayed, true);
    const other = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, { verdicts: [verdict(supported.opId!, 'unsupported')] });
    expectStatus(other, 409, 'another verdict for a verified op');
    assert.equal((await opRow(h, supported.opId!)).verificationVerdict, 'supported', 'the first verdict stands');
  });

  await t.test('an amend: supported writes its revision as Auto; one whose entry the owner touched meanwhile applies nothing', async () => {
    const machineWritten = await machineEntry(h, owner.id, space, 'pitfall', 'An amendable pitfall', records);
    const touched = await machineEntry(h, owner.id, space, 'pitfall', 'A pitfall the owner edits meanwhile', records);
    const amends = await call(h, mine, 'POST', '/runner/wiki/changesets', {
      rationale: 'two amends',
      idempotencyKey: `amends-${randomUUID()}`,
      ops: [
        { op: 'amend', entryId: machineWritten, baseRevision: 1, changes: { summary: 'Amended after verification.' }, sources: cite },
        { op: 'amend', entryId: touched, baseRevision: 1, changes: { summary: 'Amended by the machine.' }, sources: cite },
      ],
    });
    expectStatus(amends, 200, 'the amends');
    const [first, second] = amends.body.ops as Outcome[];
    const owners = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${space}/changesets`, {
      rationale: 'the owner writes over it first',
      ops: [{ op: 'amend', entryId: touched, baseRevision: 1, changes: { summary: 'The owner\'s own wording.' } }],
    });
    expectStatus(owners, 200, 'the owner amends');
    const verified = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, {
      verdicts: [verdict(first.opId!, 'supported'), verdict(second.opId!, 'supported')],
    });
    expectStatus(verified, 200, 'the two verdicts');
    assert.deepEqual((verified.body.outcomes as Array<{ status: string }>).map((o) => o.status), ['applied', 'conflict']);
    const amended = await entryRow(h, machineWritten);
    assert.equal(amended.currentRevision, 2);
    assert.equal(amended.summary, 'Amended after verification.');
    assert.equal(amended.trust, 'auto');
    const kept = await entryRow(h, touched);
    assert.equal(kept.summary, 'The owner\'s own wording.', 'the owner\'s revision stands');
    const conflict = await opRow(h, second.opId!);
    assert.equal(conflict.decision, 'conflict');
    assert.equal(conflict.verificationVerdict, 'supported', 'the verdict is on record even so');
  });

  await t.test('a duplicate may only name a live neighbour of its own op', async () => {
    const stray = await machineEntry(h, owner.id, space, 'concept', 'Something else entirely unrelated', records);
    const lone = await call(h, mine, 'POST', '/runner/wiki/changesets', {
      rationale: 'one more', idempotencyKey: `lone-${randomUUID()}`,
      ops: [{ op: 'add', entry: draft('pitfall', 'Builds fail when the disk is full'), sources: cite }],
    });
    expectStatus(lone, 200, 'the proposal');
    const opId = (lone.body.ops[0] as Outcome).opId!;
    const refused = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, {
      verdicts: [verdict(opId, 'duplicate', { duplicateOf: stray })],
    });
    expectStatus(refused, 400, 'a duplicate of an entry that is not among its neighbours');
    assert.equal(refused.body.outcomes[0].code, 'WIKI_SCHEMA');
    const shapeless = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, {
      verdicts: [{ opId, verdict: 'probably', reason: 'x', model: 'm' }],
    });
    expectStatus(shapeless, 400, 'a verdict that is not one');
    assert.equal((await opRow(h, opId)).decision, 'verifying', 'and the op keeps waiting');
  });
});

// ── 3. who reports ──────────────────────────────────────────────────────────────────────────────

test('verification · only the session that proposed reports, and another owner\'s is a 404', { skip, concurrency: 1, timeout: 300_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'proposer');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const evidence = await toolCall(h, records, 'Bash', 'what was observed');
  const proposer = await session(h, owner.id, ws, machine);
  const answer = await call(h, { runner: machine, headers: { 'x-orbit-session-id': proposer } }, 'POST', '/runner/wiki/changesets', {
    rationale: 'mine', idempotencyKey: `mine-${randomUUID()}`,
    ops: [{ op: 'add', entry: draft('pitfall', 'A proposer-only pitfall'), sources: [{ kind: 'tool_call', ref: evidence }] }],
  });
  expectStatus(answer, 200, 'the proposal');
  const opId = (answer.body.ops[0] as Outcome).opId!;

  // Another session of the same owner, on the same machine: it sees none of it, and may report none of it.
  const sibling = await session(h, owner.id, ws, machine);
  const theirs = { runner: machine, headers: { 'x-orbit-session-id': sibling } };
  assert.deepEqual(await listed(h, theirs, space), [], 'another session lists none of this session\'s ops');
  const sibling404 = await call(h, theirs, 'POST', `/runner/wiki/spaces/${space}/verifications`, { verdicts: [verdict(opId, 'supported')] });
  expectStatus(sibling404, 404, 'another session reporting this session\'s op');

  // No session at all: nobody to be the proposer.
  expectStatus(await call(h, { runner: machine }, 'GET', `/runner/wiki/spaces/${space}/verifications`), 400, 'a headless list');
  expectStatus(await call(h, { runner: machine }, 'POST', `/runner/wiki/spaces/${space}/verifications`, { verdicts: [verdict(opId, 'supported')] }), 400, 'a headless report');

  // Another owner: their own session and runner, our space and our op.
  const stranger = await account(h, 'stranger');
  const strangerMachine = await runner(h, stranger.id);
  const strangerWs = await workspace(h, stranger.id);
  const strangerSpace = await modeSpace(h, stranger, 'automatic', strangerWs);
  const strangerSession = await session(h, stranger.id, strangerWs, strangerMachine);
  const them = { runner: strangerMachine, headers: { 'x-orbit-session-id': strangerSession } };
  expectStatus(await call(h, them, 'GET', `/runner/wiki/spaces/${space}/verifications`), 404, 'another owner lists our space');
  expectStatus(await call(h, them, 'POST', `/runner/wiki/spaces/${space}/verifications`, { verdicts: [verdict(opId, 'supported')] }), 404, 'another owner reports into our space');
  expectStatus(await call(h, them, 'POST', `/runner/wiki/spaces/${strangerSpace}/verifications`, { verdicts: [verdict(opId, 'supported')] }), 404, 'another owner reports our op through their own space');
  // A header naming a session this runner does not host is no session at all.
  expectStatus(await call(h, { runner: strangerMachine, headers: { 'x-orbit-session-id': proposer } }, 'GET', `/runner/wiki/spaces/${space}/verifications`), 403, 'another machine borrowing our session id');

  assert.equal((await opRow(h, opId)).decision, 'verifying', 'none of that recorded anything');
  const own = await call(h, { runner: machine, headers: { 'x-orbit-session-id': proposer } }, 'POST', `/runner/wiki/spaces/${space}/verifications`, {
    verdicts: [verdict(opId, 'supported')],
  });
  expectStatus(own, 200, 'the proposer reports');
  assert.equal((await opRow(h, opId)).verificationVerdict, 'supported');
});

// ── Where the server verifies, and what this door still hands out ───────────────────────────────

test('verification · the server executes: the door hands out no material, accepts no verdicts, and a run is untouched', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'server-executes');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);

  const first = await session(h, owner.id, ws, machine);
  const cite1 = await toolCall(h, first, 'Bash', 'what was observed first');
  const asFirst = { runner: machine, headers: { 'x-orbit-session-id': first } };
  const propose = (sessionId: string, cite: string, title: string) => call(h, { runner: machine, headers: { 'x-orbit-session-id': sessionId } }, 'POST',
    '/runner/wiki/changesets', {
      rationale: `the spec records ${title}`, idempotencyKey: `server-executes-${randomUUID()}`,
      ops: [{ op: 'add', entry: draft('pitfall', title), sources: [{ kind: 'tool_call', ref: cite }] }],
    });

  t.after(() => {
    delete process.env.ORBIT_WIKI_EXECUTOR;
    delete process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS;
  });

  // The default runner mode, first: the field is absent, the session's own list is what it always was, and
  // its own verdict is accepted.
  const proposed = await propose(first, cite1, 'A pitfall the session verifies itself');
  expectStatus(proposed, 200, 'the proposal');
  assert.equal(proposed.body.servedBy, undefined, 'the default runner mode says nothing about who verifies');
  assert.equal((await listed(h, asFirst, space)).length, 1, "runner mode lists the session's own ops");

  // The server executes for this account: the list is empty and says who verifies and how many wait, and a
  // verdict of the session's own is refused — its provider is not to be asked about any of this.
  process.env.ORBIT_WIKI_EXECUTOR = 'canary';
  process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS = owner.id;
  const page = await call(h, asFirst, 'GET', `/runner/wiki/spaces/${space}/verifications`);
  expectStatus(page, 200, 'the list where the server executes');
  assert.deepEqual(page.body.items, [], 'no material is handed out');
  assert.equal(page.body.servedBy, 'server', 'the list says who verifies');
  assert.equal(page.body.waiting, 1, "and how many of the session's ops wait");
  const refused = await call(h, asFirst, 'POST', `/runner/wiki/spaces/${space}/verifications`, {
    verdicts: [verdict(String(proposed.body.ops[0].opId), 'supported')],
  });
  expectStatus(refused, 409, 'a verdict where the server verifies');
  assert.equal(refused.body.code, 'WIKI_SERVER_EXECUTES', 'the refusal names the code');
  assert.equal((await opRow(h, String(proposed.body.ops[0].opId))).decision, 'verifying', 'nothing was recorded');

  // A submission's answer carries the same field, queues the one job, and asking for a verification is that
  // same job rather than a second one.
  const second = await session(h, owner.id, ws, machine);
  const cite2 = await toolCall(h, second, 'Bash', 'what was observed second');
  const asSecond = { runner: machine, headers: { 'x-orbit-session-id': second } };
  const proposed2 = await propose(second, cite2, 'A pitfall the server verifies');
  expectStatus(proposed2, 200, 'the proposal where the server executes');
  assert.equal(proposed2.body.servedBy, 'server', 'the answer says who verifies');
  assert.equal(await verifyJobs(h, owner.id, space, second), 1, 'the submission queued one job');
  const asked = await call(h, asSecond, 'POST', `/runner/wiki/spaces/${space}/verifications/request`);
  expectStatus(asked, 200, 'asking for a verification');
  assert.equal(asked.body.servedBy, 'server');
  assert.ok(asked.body.jobId, 'the ask names the job it waits on');
  assert.equal(await verifyJobs(h, owner.id, space, second), 1, 'asking again is the same job');

  // A maintenance run of the space: its own list, its own verdicts, and no job of its own.
  const run = await maintenanceSession(h, owner, machine, space, ws);
  const cite3 = await toolCall(h, run, 'Bash', 'what the run observed');
  const asRun = { runner: machine, headers: { 'x-orbit-session-id': run } };
  const runProposed = await propose(run, cite3, 'A pitfall the run verifies itself');
  expectStatus(runProposed, 200, 'the run proposes');
  assert.equal(runProposed.body.servedBy, undefined, "a maintenance run is told nothing of the server's own verification");
  const runItems = await listed(h, asRun, space);
  assert.equal(runItems.length, 1, 'a maintenance run reads its own ops');
  assert.equal(await verifyJobs(h, owner.id, space, run), 0, 'a maintenance run queues no job');
  const runVerdict = await call(h, asRun, 'POST', `/runner/wiki/spaces/${space}/verifications`, {
    verdicts: [verdict(String(runProposed.body.ops[0].opId), 'supported')],
  });
  expectStatus(runVerdict, 200, 'a maintenance run reports as it always has');

  // Back to runner: the session's own verdict is accepted again, and the op is verified by it.
  process.env.ORBIT_WIKI_EXECUTOR = 'runner';
  delete process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS;
  const back = await call(h, asFirst, 'POST', `/runner/wiki/spaces/${space}/verifications`, {
    verdicts: [verdict(String(proposed.body.ops[0].opId), 'supported')],
  });
  expectStatus(back, 200, 'runner mode reports as it always has');
  assert.equal((await opRow(h, String(proposed.body.ops[0].opId))).verificationVerdict, 'supported');
});

// ── 4. no clock, and a space that left Automatic ────────────────────────────────────────────────

test('verification · no clock moves a waiting op, a space out of Automatic records no verdict, and a revert withdraws what waits', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'no clock');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const evidence = await toolCall(h, records, 'Bash', 'what was observed');
  const proposer = await session(h, owner.id, ws, machine);
  const mine = { runner: machine, headers: { 'x-orbit-session-id': proposer } };
  const propose = async (title: string) => {
    const answer = await call(h, mine, 'POST', '/runner/wiki/changesets', {
      rationale: title, idempotencyKey: `${title}-${randomUUID()}`,
      ops: [{ op: 'add', entry: draft('pitfall', title), sources: [{ kind: 'tool_call', ref: evidence }] }],
    });
    expectStatus(answer, 200, title);
    return { changesetId: answer.body.changesetId as string, ...(answer.body.ops[0] as Outcome) };
  };

  await t.test('switched out of Automatic, the space records no verdict, and its ops wait on untouched', async () => {
    const waiting = await propose('A pitfall caught by a switch');
    expectStatus(await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${space}`, { reviewMode: 'tiered' }), 200, 'the owner switches');
    const refused = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, { verdicts: [verdict(waiting.opId!, 'supported')] });
    expectStatus(refused, 409, 'a verdict in a Tiered space');
    assert.match(refused.body.outcomes[0].message, /not automatic/u);
    assert.equal((await opRow(h, waiting.opId!)).decision, 'verifying');
    assert.equal((await entryRow(h, waiting.entryId!)).status, 'proposed');
    const list = await call(h, mine, 'GET', `/runner/wiki/spaces/${space}/verifications`);
    assert.equal(list.body.mode, 'tiered', 'the list says so, before any model is asked');

    // A month passes, as far as the rows are concerned: nothing a clock does moves the op.
    await h.sql.query(
      `UPDATE "wiki_changeset" SET "created_at" = now() - interval '30 days', "expires_at" = now() - interval '16 days' WHERE "id" = $1`,
      [toUuid(waiting.changesetId)],
    );
    assert.equal((await listed(h, mine, space)).some((item) => item.opId === waiting.opId), true, 'it is still waiting');
    expectStatus(await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${space}`, { reviewMode: 'automatic' }), 200, 'the owner switches back');
    const recorded = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, { verdicts: [verdict(waiting.opId!, 'supported')] });
    expectStatus(recorded, 200, 'the verdict, a month on');
    assert.equal((await entryRow(h, waiting.entryId!)).trust, 'auto');
  });

  await t.test('the owner reverts the run: what still waits is withdrawn, and no verdict can apply it', async () => {
    const waiting = await propose('A pitfall whose run is reverted');
    const reverted = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${waiting.changesetId}/revert`);
    expectStatus(reverted, 200, 'the revert');
    const op = await opRow(h, waiting.opId!);
    assert.equal(op.decision, 'withdrawn');
    assert.equal((await entryRow(h, waiting.entryId!)).status, 'rejected', 'its proposed lineage goes with it');
    const late = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, { verdicts: [verdict(waiting.opId!, 'supported')] });
    expectStatus(late, 409, 'a verdict for a withdrawn op');
    const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(waiting.changesetId) } });
    assert.equal(changeset.status, 'settled');
  });
});

// ── 5. the fallback, through the import's own path ──────────────────────────────────────────────

test('verification · over 30% unsupported of the latest 50 sends the space back to Tiered, once', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'fallback');
  const recordsOf = await session(h, owner.id, null, null);
  const cited = await toolCall(h, recordsOf, 'Bash', 'compiled from the dossier');
  // The preview space: no workspace bound, filled by the one-off import.
  const space = await modeSpace(h, owner, 'automatic');
  const system = importer(owner.id);
  for (const [count, prefix] of [[30, 'first'], [30, 'second']] as const) {
    const answer = await h.service.submitChangeset(system, space, { rationale: `batch ${prefix}`, ops: importOps(count, cited, prefix), idempotencyKey: `${prefix}-${randomUUID()}` });
    assert.deepEqual((answer.ops as Outcome[]).map((op) => op.waitsFor), Array(count).fill('verification'), `${prefix}: every op waits`);
  }
  const all: string[] = [];
  for (let after: string | null = null, page = 0; page < 10; page += 1) {
    const read = await h.service.listVerifications(system, space, { after, limit: WIKI_REVIEW_RULES.verificationListMax });
    all.push(...read.items.map((item) => item.opId));
    after = read.next;
    if (!after) break;
  }
  assert.equal(all.length, 60, 'the import reads its own ops through the service');
  const record = (opId: string, value: string) => h.service.recordVerifications(system, space, [verdict(opId, value)]);

  await t.test('fifteen of fifty is not over 30%', async () => {
    for (const opId of all.slice(0, 35)) assert.equal((await record(opId, 'supported')).outcomes[0].status, 'applied');
    for (const opId of all.slice(35, 50)) assert.equal((await record(opId, 'unsupported')).outcomes[0].status, 'rejected');
    const settings = (await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: space } })).settings as Record<string, unknown>;
    assert.equal(settings.reviewMode, 'automatic');
    assert.deepEqual(h.fellBack, []);
    const trail = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: all[0] } });
    assert.equal(trail.verificationModel, 'qwen3.8-27b-fp8', 'the import\'s verdicts leave the same trail');
    const revision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: trail.resultEntryId!, revision: 1 } });
    assert.equal(revision.authorKind, 'system', 'and what they applied is the system\'s, never the owner\'s');
  });

  await t.test('the sixteenth sends it back to Tiered, and the owner is told once', async () => {
    const tripped = await record(all[50], 'unsupported');
    assert.equal(tripped.outcomes[0].status, 'rejected');
    assert.equal(tripped.mode, 'tiered');
    const settings = (await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: space } })).settings as Record<string, unknown>;
    assert.equal(settings.reviewMode, 'tiered');
    assert.equal(settings.reviewModeChangedBy, 'verification');
    assert.deepEqual(h.fellBack, [{ ownerId: owner.id, spaceId: space, unsupported: 16, window: WIKI_REVIEW_RULES.verificationWindow }]);

    // The next verdict finds the space Tiered: refused, nothing written, nobody told again.
    const after = await record(all[51], 'unsupported');
    assert.equal(after.outcomes[0].status, 'refused');
    assert.equal((after.outcomes[0] as { httpStatus: number }).httpStatus, 409);
    assert.equal((await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: all[51] } })).decision, 'verifying');
    assert.equal(h.fellBack.length, 1, 'no second notification');
  });

  await t.test('made Automatic again by the owner, the window starts again: one more unsupported is not over the line', async () => {
    expectStatus(await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${space}`, { reviewMode: 'automatic' }), 200, 'the owner switches back');
    const one = await record(all[51], 'unsupported');
    assert.equal(one.outcomes[0].status, 'rejected');
    assert.equal(one.mode, 'automatic');
    assert.equal(h.fellBack.length, 1);
  });
});

// ── 6. spot checks, and the queue ───────────────────────────────────────────────────────────────

test('verification · Automatic sends no spot check unless asked, one in 200 when asked, and none takes a place in the queue', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'spot checks');
  const recordsOf = await session(h, owner.id, null, null);
  const cited = await toolCall(h, recordsOf, 'Bash', 'compiled from the dossier');
  const system = importer(owner.id);

  await t.test('one in every block of 200, wherever the draw puts it', () => {
    const space = randomUUID();
    for (let block = 0; block < 3; block += 1) {
      const drawn = Array.from({ length: 200 }, (_unused, n) => block * 200 + n).filter((position) => isSpotCheckDraw(space, position, 200));
      assert.equal(drawn.length, 1, `block ${block}`);
    }
  });

  /** An Automatic space whose next verdict lands on the position its first block draws. */
  const atTheDraw = async (asked: boolean) => {
    const space = await modeSpace(h, owner, 'automatic');
    if (asked) {
      const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${space}`, { automaticSpotChecks: true });
      expectStatus(on, 200, 'the owner asks for spot checks');
      assert.equal(on.body.settings.automaticSpotChecks, true);
    }
    let position = 0;
    while (!isSpotCheckDraw(space, position, WIKI_REVIEW_RULES.automaticSpotCheckEvery)) position += 1;
    // The ops the mode applied before, as the draw counts them: written directly, settled long ago.
    const earlier = randomUUID();
    await h.sql.query(
      `INSERT INTO "wiki_changeset"("id","owner_id","space_id","origin","status","decided_at") VALUES ($1,$2,$3,'import','settled',now())`,
      [earlier, owner.id, space],
    );
    for (let seq = 0; seq < position; seq += 1) {
      await h.sql.query(
        `INSERT INTO "wiki_changeset_op"("id","changeset_id","owner_id","seq","op","payload","decision","decided_at","applied_by_mode")
         VALUES ($1,$2,$3,$4,'add','{}','auto_applied',now(),'automatic')`,
        [randomUUID(), earlier, owner.id, seq],
      );
    }
    const answer = await h.service.submitChangeset(system, space, { rationale: 'two more', ops: importOps(2, cited, 'draw'), idempotencyKey: `draw-${randomUUID()}` });
    return { space, ops: (answer.ops as Outcome[]).map((op) => op.opId!) };
  };

  await t.test('a new space sends none, and only the owner channel turns them on', async () => {
    const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: 'Defaults' });
    assert.equal(made.body.settings.automaticSpotChecks, false);
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id);
    const someone = await session(h, owner.id, ws, machine);
    const refused = await call(h, { bearer: owner.bearer, headers: { 'x-orbit-session-id': someone } }, 'PATCH', `/wiki/spaces/${made.body.id}`, { automaticSpotChecks: true });
    expectStatus(refused, 403, 'a session turning spot checks on');
    assert.equal(refused.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
    const runnerDoor = await call(h, { runner: machine, headers: { 'x-orbit-session-id': someone } }, 'PATCH', `/runner/wiki/spaces/${made.body.id}`, { automaticSpotChecks: true });
    assert.equal(runnerDoor.status, 404, 'the runner door serves no settings route');
  });

  await t.test('off, the verdict at the drawn position applies with no card', async () => {
    const { space, ops } = await atTheDraw(false);
    const done = await h.service.recordVerifications(system, space, [verdict(ops[0], 'supported')]);
    assert.equal((done.outcomes[0] as { spotCheck?: boolean }).spotCheck, false);
    assert.equal((await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: ops[0] } })).decision, 'auto_applied');
    const review = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/review?space=${space}`);
    assert.deepEqual(review.body, []);
  });

  await t.test('on, the verdict at the drawn position is a spot check in Review, and the next one is not', async () => {
    const { space, ops } = await atTheDraw(true);
    const drawn = await h.service.recordVerifications(system, space, [verdict(ops[0], 'supported')]);
    assert.equal((drawn.outcomes[0] as { spotCheck?: boolean }).spotCheck, true);
    const op = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: ops[0] } });
    assert.equal(op.decision, 'pending');
    assert.equal(op.spotCheck, true);
    assert.equal(op.appliedByMode, 'automatic');
    assert.equal((await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: op.resultEntryId! } })).trust, 'auto', 'its effect stands');
    const review = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/review?space=${space}`);
    const cards = (review.body as Array<{ ops: Array<{ spotCheck: boolean; decision: string; verification: { verdict: string; model: string } | null }> }>)
      .flatMap((changeset) => changeset.ops.filter((row) => row.decision === 'pending'));
    assert.equal(cards.length, 1, 'one spot-check card');
    assert.equal(cards[0].spotCheck, true);
    assert.equal(cards[0].verification?.verdict, 'supported', 'with the verdict it rests on');
    assert.equal(cards[0].verification?.model, 'qwen3.8-27b-fp8');
    const next = await h.service.recordVerifications(system, space, [verdict(ops[1], 'supported')]);
    assert.equal((next.outcomes[0] as { spotCheck?: boolean }).spotCheck, false, 'one in the block, and only one');
  });

  await t.test('a spot-check card takes no place in the 30-op queue: thirty proposals still wait beside it', async () => {
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id);
    const tiered = await modeSpace(h, owner, 'tiered', ws);
    // Tiered draws one in ten as it applies, and applies an import's adds at once.
    const loaded = await h.service.submitChangeset(system, tiered, { rationale: 'ten', ops: importOps(10, cited, 'tiered'), idempotencyKey: `tiered-${randomUUID()}` });
    assert.deepEqual((loaded.ops as Outcome[]).map((op) => op.status), Array(10).fill('applied'));
    const checks = await h.prisma.wikiChangesetOp.count({ where: { spotCheck: true, decision: 'pending', changeset: { spaceId: tiered } } });
    assert.equal(checks, 1, 'Tiered still draws one in ten');
    // Thirty proposals that wait on the owner's decision: a session that read the web proposes each.
    const outcomes: Outcome[] = [];
    for (let batch = 0; batch < WIKI_LIMITS.pendingOpsPerSpace / WIKI_LIMITS.opsPerTurn; batch += 1) {
      const reader = await session(h, owner.id, ws, machine);
      await toolCall(h, reader, 'WebFetch', 'a page from the web');
      const answer = await call(h, { runner: machine, headers: { 'x-orbit-session-id': reader } }, 'POST', '/runner/wiki/changesets', {
        rationale: 'read off the web', idempotencyKey: `web-${randomUUID()}`,
        ops: Array.from({ length: WIKI_LIMITS.opsPerTurn }, (_unused, n) => ({
          op: 'add', entry: draft('pitfall', `A web pitfall ${batch}-${n}`), sources: [{ kind: 'tool_call', ref: cited }],
        })),
      });
      outcomes.push(...(answer.body.ops as Outcome[]));
    }
    assert.deepEqual(outcomes.map((op) => op.status), Array(WIKI_LIMITS.pendingOpsPerSpace).fill('pending'), 'all thirty wait, the card beside them');
    const reader = await session(h, owner.id, ws, machine);
    await toolCall(h, reader, 'WebFetch', 'one more page');
    const full = await call(h, { runner: machine, headers: { 'x-orbit-session-id': reader } }, 'POST', '/runner/wiki/changesets', {
      rationale: 'one too many', idempotencyKey: `full-${randomUUID()}`,
      ops: [{ op: 'add', entry: draft('pitfall', 'A thirty-first web pitfall'), sources: [{ kind: 'tool_call', ref: cited }] }],
    });
    assert.equal(full.body.ops[0].reasons[0].code, 'WIKI_REVIEW_QUEUE_FULL', 'the thirty-first decision is the one refused');
  });
});
