/**
 * The wiki context is no longer handed to a session (the owner, 2026-10-06): `dequeueTurn` used to
 * append `<orbit_wiki_context>` to an engine's first turn (design §7.1, contract `push`), and now
 * delivers the person's words alone. Sessions pull notes with `wiki_search` and `wiki_get`.
 *
 * WHAT IS UNDER TEST is what `dequeueTurn` hands the runner — the delivered content of the turn,
 * read off the runner door — over real HTTP and against real PostgreSQL, for a session whose
 * workspace is bound to a space holding an owner-written, otherwise pushable entry: the content is
 * exactly what was typed, and no `wiki_exposure(channel='push')` row is written.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-push.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the
 * run created.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import { RunStatus, SessionDispatchOrigin, type PrismaClient } from '@prisma/client';
import { toUuid, uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { publicIdHeaders } from '../common/public-id-headers';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { AttemptBudgetMeterService } from '../projects/attempt-budget-meter.service';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { PushService } from '../push/push.service';
import { QueueService } from '../queue/queue.service';
import { RealtimeService } from '../realtime/realtime.service';
import { MergeReceiptService } from '../sessions/merge-receipt.service';
import { SessionsService } from '../sessions/sessions.service';
import { ListEventsService } from '../task-lists/list-events.service';
import { ReferenceExpansionService } from '../tasks/reference-expansion';
import { TasksService } from '../tasks/tasks.service';
import { RunnerApiController } from '../runner-api/runner-api.controller';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerOrchestrationAuthorizer } from '../runner-api/runner-orchestration-authorizer';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiController } from './wiki.controller';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService } from './wiki.service';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a session row carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The runner credential, in the clear. Its hash is what `RunnerAuthGuard` matches. */
const RUNNER_TOKEN = 'the-runner-token-for-wiki-pushes';

interface Answer {
  status: number;
  text: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  json: any;
}

/** A collaborator whose every method answers nothing: the broadcasts a delivery fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

test('the wiki context a session is handed when it starts', {
  skip, concurrency: 1, timeout: 600_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  let app: INestApplication | undefined;
  t.after(async () => {
    await app?.close().catch(() => undefined);
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const tokenHash = createHash('sha256').update(RUNNER_TOKEN).digest('hex');
  await prisma.user.create({
    data: { id: ownerId, email: `wiki-push-${ownerId}@wiki.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({ data: { id: runnerId, name: 'the machine', ownerId, tokenHash } });

  // ── the app: both wiki doors, the runner door, its guard, and main.ts's middleware ──────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(prisma as unknown as PrismaService, queue as never, realtime as never);
  @Module({
    controllers: [WikiController, RunnerWikiController, RunnerApiController],
    providers: [
      { provide: PrismaService, useValue: prisma },
      { provide: WikiService, useValue: new WikiService(prisma as unknown as PrismaService) },
      { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
      { provide: QueueService, useValue: queue },
      { provide: SessionsService, useValue: sessions },
      { provide: RealtimeService, useValue: realtime },
      { provide: PushService, useValue: silent() },
      { provide: RunnerOrchestrationAuthorizer, useValue: {} },
      // The person's turn carries no `#`-references and no list console; both are other blocks
      // with their own specs, and either would be appended beside this one.
      { provide: ReferenceExpansionService, useValue: { expand: async (_owner: string, content?: string) => content } },
      { provide: ListEventsService, useValue: { appendFor: async (_tx: unknown, _id: string, content?: string) => content } },
      { provide: AttemptBudgetMeterService, useValue: {} },
      { provide: ProjectAcceptanceService, useValue: {} },
      { provide: TasksService, useValue: {} },
      { provide: MergeReceiptService, useValue: {} },
      RunnerAuthGuard,
      JwtAuthGuard,
      Reflector,
      {
        provide: JwtService,
        useValue: {
          verifyAsync: async (token: string) => {
            if (token !== `bearer-${ownerId}`) throw new Error('not a bearer this run issued');
            return { sub: ownerId, email: `wiki-push-${ownerId}@wiki.invalid` };
          },
        },
      },
    ],
  })
  class WikiPushDoor {}

  app = await NestFactory.create(WikiPushDoor, { logger: false, abortOnError: false });
  app.use(publicIdHeaders);
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
  app.useGlobalInterceptors(new PublicIdInterceptor());
  await app.listen(0, '127.0.0.1');
  const base = await app.getUrl();

  async function send(
    method: 'GET' | 'POST' | 'PATCH',
    route: string,
    body?: unknown,
    who: 'runner' | 'owner' = 'runner',
    /** The calling session, for the doors whose read boundary is derived from one. */
    headers: Record<string, string> = {},
  ): Promise<Answer> {
    const response = await fetch(`${base}/api${route}`, {
      method,
      headers: {
        authorization: who === 'runner' ? `Bearer ${RUNNER_TOKEN}` : `Bearer bearer-${ownerId}`,
        ...headers,
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    const text = await response.text();
    let json: unknown = null;
    try { json = text ? JSON.parse(text) : null; } catch { /* asserted on by the caller */ }
    return { status: response.status, text, json };
  }

  // ── fixtures ────────────────────────────────────────────────────────────────────────────────────

  /**
   * A space the owner makes and binds this workspace to — the read boundary itself (§10.1). Manual,
   * unless a case says otherwise: this file pins phase 1's push, whose proposals wait for Review, and
   * a space is made Tiered now (contract `space.settings.reviewMode`).
   */
  async function boundSpace(settings: Record<string, unknown> = {}): Promise<{ spaceId: string; workspaceId: string }> {
    const workspaceId = randomUUID();
    await prisma.workspace.create({
      data: { id: workspaceId, ownerId, runnerId, name: `spec-${workspaceId}`, enabled: true },
    });
    const created = await send('POST', '/wiki/spaces', {
      title: 'The orbit repository',
      repoUrl: `https://github.com/example/${randomUUID()}`,
    }, 'owner');
    assert.equal(created.status, 201, `the owner creates a space: ${created.text}`);
    // The doors answer with public ids; every write below names the row it is about by its own id.
    const spaceId = toUuid(created.json.id as string);
    const patched = await send('PATCH', `/wiki/spaces/${spaceId}`, { reviewMode: 'manual', ...settings }, 'owner');
    assert.ok([200, 204].includes(patched.status), `the owner changes the space's settings: ${patched.text}`);
    const bound = await send('POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId }, 'owner');
    assert.ok([200, 201].includes(bound.status), `the owner binds the workspace: ${bound.text}`);
    return { spaceId, workspaceId };
  }

  /** An entry the owner writes themselves: applied at once, trusted as theirs, and pushable. */
  async function ownerEntry(spaceId: string, entry: Record<string, unknown>): Promise<string> {
    const answer = await send('POST', `/wiki/spaces/${spaceId}/changesets`, {
      rationale: 'the owner records what this codebase knows',
      ops: [{ op: 'add', entry }],
    }, 'owner');
    assert.equal(answer.status, 200, `the owner records ${String(entry.title)}: ${answer.text}`);
    const op = (answer.json.ops as Array<{ status: string; entryId: string }>)[0];
    assert.equal(op?.status, 'applied', `the owner's own write applies at once: ${answer.text}`);
    return toUuid(op.entryId);
  }

  /** A session bound to a space's workspace, parked between turns: the state a start leaves it in. */
  async function session(data: {
    workspaceId: string;
    taskId?: string;
    dispatchOrigin?: SessionDispatchOrigin;
    title?: string;
    prompt?: string;
  }): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id,
        ownerId,
        creatorId: ownerId,
        workspaceId: data.workspaceId,
        title: data.title ?? 'a session that just started',
        prompt: data.prompt ?? 'pick this up',
        provider: 'claude',
        status: RunStatus.AWAITING_INPUT,
        dispatchOrigin: data.dispatchOrigin ?? SessionDispatchOrigin.USER,
        // A run of a task is a session that starts task work; one that merely asks about a
        // codebase is not.
        startsTaskWork: data.taskId !== undefined,
        assignedRunnerId: runnerId,
        numTurns: 0,
        ...(data.taskId ? { taskId: data.taskId } : {}),
      },
    });
    return id;
  }

  /** A queued message turn, as the composer leaves it: after every turn the session already has. */
  async function messageTurn(sessionId: string, content: string, clientTurnId?: string): Promise<string> {
    const id = randomUUID();
    await prisma.conversationTurn.create({
      data: {
        id,
        sessionId,
        seq: (await prisma.conversationTurn.count({ where: { sessionId } })) + 1,
        clientTurnId: clientTurnId ?? `turn-${randomUUID()}`,
        kind: 'message',
        content,
        status: 'PENDING',
      },
    });
    return id;
  }

  interface Delivered {
    content: string;
    turnId: string;
    leaseOwner: string;
    leaseGeneration: string;
  }

  /**
   * Hand the session's queued turn to its runner, through the runner door.
   *
   * The claim's own handshake is stood in for: the queue is what writes `inbox_lease_owner` when it
   * gives a session a runner slot, and the engine's activation is what mints the generation it then
   * polls under. Both are written here because the subject is what the delivery carries, not who
   * handed it out.
   */
  async function deliver(sessionId: string): Promise<Delivered> {
    const leaseOwner = randomUUID();
    const leaseGeneration = randomUUID();
    await prisma.session.update({
      where: { id: sessionId },
      data: { inboxLeaseOwner: leaseOwner, status: RunStatus.RUNNING },
    });
    const activated = await send('POST', `/runner/sessions/${uuidToBase62(sessionId)}/activate-leases`, {
      leaseOwner,
      leaseGeneration,
    });
    assert.equal(activated.status, 200, `activate-leases answered ${activated.status}: ${activated.text}`);
    const answer = await send(
      'GET',
      `/runner/sessions/${uuidToBase62(sessionId)}/inbox?leaseGeneration=${leaseGeneration}`,
    );
    assert.equal(answer.status, 200, `the inbox answered ${answer.status}: ${answer.text}`);
    const turnId = String(answer.json.turnId ?? '');
    assert.ok(turnId, `the inbox handed out no turn: ${answer.text}`);
    return { content: String(answer.json.content ?? ''), turnId, leaseOwner, leaseGeneration };
  }

  const exposureRows = (sessionId: string) =>
    prisma.wikiExposure.findMany({ where: { sessionId }, orderBy: { at: 'asc' } });

  await t.test('a session is handed the person\'s words and no wiki context', async () => {
    const { spaceId, workspaceId } = await boundSpace();
    await ownerEntry(spaceId, {
      kind: 'principle',
      title: 'Completion is adjudicated, not claimed',
      summary: 'A run is not done because it says so; the declared criterion decides.',
      fields: { statement: 'Completion is adjudicated, not claimed.', rationale: 'Self-reported done is how failures pass.' },
    });

    const sessionId = await session({ workspaceId });
    const authored = 'pick this up';
    await messageTurn(sessionId, authored);
    const delivered = await deliver(sessionId);

    assert.equal(delivered.content, authored, `delivery appended to what the person sent:\n${delivered.content}`);
    assert.deepEqual(await exposureRows(sessionId), [], 'a push was recorded for a delivery that sent none');
  });
});
