/**
 * `orbit wiki import`'s server half — the `note` source and the import's proposals — over real HTTP
 * and against a real PostgreSQL (criterion 1 of the wiki's phase 2; contracts/wiki.contract.json
 * `import`, migration 0316).
 *
 * The five things the criterion's verification names are five cases here, each read back from the
 * database and, where it matters, from the push a session would be handed:
 *
 *   1. seeded secrets: after a file is registered and entries are proposed from it, not one of them —
 *      credential shapes and the owner's own workspace.env values — is left in anything stored;
 *   2. one content is one note: the same file imported again, or its text under another name, is the
 *      note already there, and no second row is made;
 *   3. a note is cited by its owner and by nobody else;
 *   4. what an import proposes takes effect as the space's review mode says: all of it waits in Manual,
 *      Tiered applies it Unreviewed and draws its spot check, Automatic holds it for a verification that
 *      reads the note's own text — and the floors hold in every mode;
 *   5. the caps a batch is held to: thirty ops a changeset, five that wait for review a request, fifteen
 *      a session, thirty a space.
 *
 * Around them, the door: a session the runner hosts is required, a session that judges work is refused,
 * another owner's space is a 404, and a note is held to its limits.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-import.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in `wiki-api.pg.spec.ts`; the push is
 * the real `appendWikiContext`. Every secret below is put together when the case runs: this repository
 * is public and scanned on push, and a key written out whole would be refused there as a leak.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { Prisma, PrismaClient } from '@prisma/client';
import { WIKI_IMPORT_RULES, WIKI_LIMITS, toUuid, type WikiKind } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import type { RealtimeService } from '../realtime/realtime.service';
import { WikiController } from './wiki.controller';
import { wikiImportPrincipal } from './wiki-import';
import { appendWikiContext } from './wiki-push';
import { WikiRetrieval } from './wiki-retrieval';
import { isSpotCheckDraw, WikiService } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The push as a session starting now would be handed it: the wiki on, whatever this shell says. */
const WIKI_ON = { mode: 'on' as const, canaryOwners: new Set<string>(), problems: [] };

type Mode = 'manual' | 'tiered' | 'automatic';

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = { notifyWikiReviewModeTripped: async () => undefined } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);

    @Module({
      controllers: [WikiController, RunnerWikiController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiImportModule {}

    const app = await NestFactory.create(WikiImportModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

interface Outcome {
  seq: number;
  status: 'pending' | 'applied' | 'conflict' | 'refused';
  opId?: string | null;
  entryId?: string | null;
  waitsFor?: string;
  reasons?: Array<{ code: string; message: string }>;
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-import-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

interface Machine {
  id: string;
  token: string;
}

async function runner(h: Harness, ownerId: string): Promise<Machine> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string, env?: Record<string, string>): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    env ? JSON.stringify(env) : null,
  ]);
  return id;
}

async function task(h: Harness, ownerId: string, shape: { verifiesTaskId?: string; isForeman?: boolean } = {}): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","updated_at",
                          "completion_criterion","verifies_task_id","is_foreman")
     VALUES ($1,'imported work',$2,'USER',$2,'OPEN',now(),'OWNER_CONFIRMED',$3,$4)`,
    [id, ownerId, shape.verifiesTaskId ?? null, shape.isForeman ?? false],
  );
  return id;
}

async function session(
  h: Harness,
  ownerId: string,
  shape: { workspaceId?: string | null; runnerId?: string | null; taskId?: string | null } = {},
): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","dispatch_origin","updated_at")
     VALUES ($1,'an import session','p',$2,$2,$3,$4,$5,'USER',now())`,
    [id, ownerId, shape.workspaceId ?? null, shape.runnerId ?? null, shape.taskId ?? null],
  );
  return id;
}

async function toolCall(h: Harness, sessionId: string, name: string, output: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","output") VALUES ($1,$2,$3,$4)`, [
    id,
    sessionId,
    name,
    JSON.stringify(output),
  ]);
  return id;
}

/** A space the owner makes through the door, in a mode, bound to a workspace when one is named. */
async function modeSpace(h: Harness, owner: Account, mode: Mode, workspaceId?: string): Promise<string> {
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: `An ${mode} import` });
  expectStatus(made, 201, 'the owner creates a space');
  const id = made.body.id as string;
  const switched = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${id}`, { reviewMode: mode });
  expectStatus(switched, 200, `the owner puts the space in ${mode}`);
  if (workspaceId) {
    const bound = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${id}/workspaces`, { workspaceId });
    expectStatus(bound, 200, 'the owner binds the workspace');
  }
  return id;
}

/** The owner, their machine, a workspace, a space in `mode` bound to it, and a session that imports. */
interface Importer {
  owner: Account;
  machine: Machine;
  workspaceId: string;
  spaceId: string;
  session: string;
  as: Caller;
}

async function importer(h: Harness, name: string, mode: Mode, env?: Record<string, string>): Promise<Importer> {
  const owner = await account(h, name);
  const machine = await runner(h, owner.id);
  const workspaceId = await workspace(h, owner.id, env);
  const spaceId = await modeSpace(h, owner, mode, workspaceId);
  const importing = await session(h, owner.id, { workspaceId, runnerId: machine.id });
  return { owner, machine, workspaceId, spaceId, session: importing, as: { runner: machine.token, session: importing } };
}

async function registerNote(h: Harness, who: Caller, spaceId: string, path: string, text: string): Promise<Answer> {
  return call(h, who, 'POST', `/runner/wiki/spaces/${spaceId}/notes`, { path, text });
}

async function note(h: Harness, who: Importer, path: string, text: string): Promise<{ id: string; text: string; created: boolean }> {
  const answer = await registerNote(h, who.as, who.spaceId, path, text);
  expectStatus(answer, 200, `the file ${path} is registered as a note`);
  return answer.body;
}

async function propose(
  h: Harness,
  who: Caller,
  spaceId: string,
  ops: unknown[],
  extra: Record<string, unknown> = {},
): Promise<Answer> {
  return call(h, who, 'POST', `/runner/wiki/spaces/${spaceId}/imports`, {
    rationale: 'orbit wiki import: what the local model found in the file',
    ops,
    ...extra,
  });
}

/** A valid draft of each kind, retitled per use. */
function draft(kind: WikiKind, title: string): Record<string, unknown> {
  const fields: Record<WikiKind, Record<string, unknown>> = {
    principle: { statement: 'Delete means forget.', rationale: 'Owners delete to forget.' },
    convention: { rule: 'Run pg specs through scripts/run-pg-spec.sh.', scope: ['src/apiserver/**/*.pg.spec.ts'] },
    decision: {
      context: 'An import could store the file as it was read.',
      decision: 'Store only the redacted text and its hash.',
      alternatives: [{ option: 'Keep the original text', whyRejected: 'It would keep the credentials in it.' }],
      consequences: 'A quote is checked against what the model read.',
      decidedAt: '2026-09-28',
    },
    pitfall: {
      trigger: { paths: ['scripts/run-pg-spec.sh'], commands: ['node --test build/wiki/x.pg.spec.js'] },
      symptom: 'A green run that witnessed no assertion.',
      cause: 'A pg spec skips itself without a database.',
      fix: 'Run it through scripts/run-pg-spec.sh.',
    },
    recipe: {
      steps: ['bash scripts/worktree-overlay.sh', 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-import.pg.spec.ts'],
      verify: { command: 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-import.pg.spec.ts', expectedExit: 0 },
    },
    concept: { definition: 'A file an import read, kept redacted.', boundaries: 'A note is never the owner\'s own words.' },
  };
  return { kind, title, summary: `What the note says about ${title.toLowerCase()}.`, fields: fields[kind] };
}

/** An add of `kind`, citing the note (with a quote from its text when one is given). */
function addFrom(noteId: string, kind: WikiKind, title: string, quote?: string): Record<string, unknown> {
  return {
    op: 'add',
    entry: draft(kind, title),
    sources: [{ kind: 'note', ref: noteId, ...(quote ? { quote } : {}) }],
  };
}

/** `count` distinct concepts citing the note. */
function concepts(noteId: string, count: number, prefix: string): Array<Record<string, unknown>> {
  return Array.from({ length: count }, (_unused, n) => addFrom(noteId, 'concept', `${prefix} concept ${n + 1} ${randomUUID().slice(0, 8)}`));
}

/** `count` active entries, written directly: what the circuit breaker measures a changeset against. */
async function activeEntries(h: Harness, ownerId: string, spaceId: string, count: number): Promise<void> {
  for (let n = 0; n < count; n += 1) {
    await h.sql.query(
      `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields")
       VALUES ($1,$2,$3,'concept','active','auto',1,$4,'Already in the space before the import.','{}')`,
      [randomUUID(), ownerId, spaceId, `Standing entry number ${n + 1}`],
    );
  }
}

/** The entries the next session in this workspace is handed, by id. */
async function pushed(h: Harness, who: Importer): Promise<Set<string>> {
  const reader = await session(h, who.owner.id, { workspaceId: who.workspaceId, runnerId: who.machine.id });
  const content = await appendWikiContext(h.prisma as unknown as Prisma.TransactionClient, {
    sessionId: reader,
    turnId: randomUUID(),
    leaseGeneration: randomUUID(),
    ownerId: who.owner.id,
    workspaceId: who.workspaceId,
    taskId: null,
    task: null,
    dispatchOrigin: 'USER',
    content: 'What should I know about this codebase?',
  }, WIKI_ON);
  return new Set([...String(content).matchAll(/\(orbit-wiki:([0-9A-Za-z]+)\)/gu)].map((match) => toUuid(match[1])));
}

async function opRow(h: Harness, opId: string) {
  return h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: toUuid(opId) }, include: { changeset: true } });
}

async function entryRow(h: Harness, entryId: string) {
  return h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(entryId) } });
}

function sha256(text: string): string {
  return createHash('sha256').update(text).digest('hex');
}

// ── the seeded secrets ──────────────────────────────────────────────────────────────────────────

/** A credential in the shape its issuer gives it, put together when the case runs. */
function issued(prefix: string, length: number, alphabet = 'Ex4mpLeN0tReaL9'): string {
  return prefix + alphabet.repeat(Math.ceil(length / alphabet.length)).slice(0, length);
}

const PEM_BODY = [issued('MIIEpAIBAAKCAQEA', 48, 'q7Zr2Kd9Xw4Lp0Tn'), issued('', 64, 'Hs3Jm8Vb1Rc6Yf5Q')];
const JWT = ['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9', 'eyJzdWIiOiJpbXBvcnQiLCJpYXQiOjE3MjcyNjAwMDB9', issued('', 43, 'k3Jp_Xq9-Wm2Zt7B')].join('.');
/** The owner's own workspace.env value, under a name no credential shape knows. */
const ENV_VALUE = 'Tr0ub4dor&3-imp0rt';

/** Each line of a memory note that carries a secret, and the secret it carries. */
const SEEDS: ReadonlyArray<{ line: string; secret: string | string[] }> = [
  { line: 'Start it with `docker run -e POSTGRES_PASSWORD=hunter2-Imp0rt postgres:16` first.', secret: 'hunter2-Imp0rt' },
  { line: 'The provider env carries ANTHROPIC_API_KEY=abc123-Imp0rt-K3y for bare runs.', secret: 'abc123-Imp0rt-K3y' },
  { line: 'A runner reads ORBIT_RUNNER_TOKEN=xyz-Imp0rt-T0ken from its config.', secret: 'xyz-Imp0rt-T0ken' },
  { line: 'JWT_SECRET=4f9a1c77e2d8b6053a1e-imp0rt signs the web session.', secret: '4f9a1c77e2d8b6053a1e-imp0rt' },
  { line: `The old Anthropic key ${issued('sk-ant-api03-', 95)} was revoked.`, secret: issued('sk-ant-api03-', 95) },
  { line: `An OpenAI project key ${issued('sk-proj-', 64)} leaked once.`, secret: issued('sk-proj-', 64) },
  { line: `CI used ${issued('ghp_', 36)} to push tags.`, secret: issued('ghp_', 36) },
  { line: `The fine-grained token ${issued('github_pat_', 82, '11AbCdEfG0_hIjKlMn9')} reads releases.`, secret: issued('github_pat_', 82, '11AbCdEfG0_hIjKlMn9') },
  { line: `AWS access key id ${issued('AKIA', 16, 'EXAMPLE0KEY1ID2Q')} belongs to the backup user.`, secret: issued('AKIA', 16, 'EXAMPLE0KEY1ID2Q') },
  { line: `The Slack bot token ${issued('xoxb-', 50, '0000-Ex4mpLe-')} posts alerts.`, secret: issued('xoxb-', 50, '0000-Ex4mpLe-') },
  { line: `Maps used ${issued('AIza', 35, 'Ex4mpLe_N0t-ReaL9')} for a week.`, secret: issued('AIza', 35, 'Ex4mpLe_N0t-ReaL9') },
  { line: `GitLab mirror token ${issued('glpat-', 20)} is read-only.`, secret: issued('glpat-', 20) },
  { line: `npm publish takes ${issued('npm_', 36)} from the vault.`, secret: issued('npm_', 36) },
  { line: `The web session cookie held session=${JWT} for ops.`, secret: JWT },
  { line: 'curl -H "Authorization: Bearer or9aF3kQ2mX7pLzImp" https://api.orbit.dev/v1', secret: 'or9aF3kQ2mX7pLzImp' },
  { line: 'The proxy sends Authorization: Basic dXNlcjppbXBvcnQtcGFzcw==', secret: 'dXNlcjppbXBvcnQtcGFzcw==' },
  { line: 'connect postgres://orbit:hunter3-Imp0rt@db:5432/orbit refused', secret: 'orbit:hunter3-Imp0rt' },
  { line: 'git remote set-url origin https://x-access-token:r3mote-Imp0rt@github.com/org/repo.git', secret: 'r3mote-Imp0rt' },
  { line: 'The service account is {"clientId": "orbit-web", "clientSecret": "js0n-Imp0rt-S3cret"}.', secret: 'js0n-Imp0rt-S3cret' },
  { line: 'redis:\n  host: cache\n  redis_password: yaml-Imp0rt-S3cret\n  port: 6379', secret: 'yaml-Imp0rt-S3cret' },
  { line: `The deploy key:\n-----BEGIN OPENSSH PRIVATE KEY-----\n${PEM_BODY.join('\n')}\n-----END OPENSSH PRIVATE KEY-----`, secret: PEM_BODY },
  { line: `Log in to the database with DB_PASS set to ${ENV_VALUE} and nothing else.`, secret: ENV_VALUE },
];

/** Any eight characters in a row of `secret` (all of it, when shorter) that `text` still holds. */
function survivingPiece(text: string, secret: string): string | undefined {
  const width = Math.min(8, secret.length);
  for (let start = 0; start + width <= secret.length; start += 1) {
    const piece = secret.slice(start, start + width);
    if (text.includes(piece)) return piece;
  }
  return undefined;
}

/** Every wiki row the owner has, each as its JSON text: what "stored" means. */
async function everythingStored(h: Harness, ownerId: string): Promise<string> {
  const tables = ['wiki_note', 'wiki_space', 'wiki_entry', 'wiki_entry_revision', 'wiki_source', 'wiki_changeset', 'wiki_changeset_op'];
  const parts: string[] = [];
  for (const table of tables) {
    const rows = await h.sql.query<{ row: string }>(`SELECT row_to_json(t)::text AS row FROM "${table}" t WHERE "owner_id" = $1`, [ownerId]);
    parts.push(...rows.rows.map((r) => r.row));
  }
  return parts.join('\n');
}

// ── 1. seeded secrets ───────────────────────────────────────────────────────────────────────────

test('import · a note keeps its text redacted, and nothing stored holds a seeded secret', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test('credential shapes and the owner\'s workspace.env values are gone before anything is kept', async () => {
    const who = await importer(h, 'secrets', 'tiered', { DB_PASS: ENV_VALUE });
    const raw = ['---', 'name: deploy-credentials', 'description: where the deploy credentials live', 'type: reference', '---', '',
      ...SEEDS.map((seed) => `- ${seed.line}`), ''].join('\n');
    for (const seed of SEEDS) for (const secret of [seed.secret].flat()) assert.ok(raw.includes(secret), `the note does not hold ${secret}`);

    const registered = await registerNote(h, who.as, who.spaceId, 'memory/deploy-credentials.md', raw);
    expectStatus(registered, 200, 'the file is registered');
    const answer = registered.body;
    assert.equal(answer.created, true);
    assert.equal(answer.redacted, true, 'the answer says something was taken out');
    assert.match(answer.text, /\[redacted\]/u);
    assert.equal(answer.contentSha256, sha256(answer.text), 'the hash is the stored text\'s');
    assert.notEqual(answer.contentSha256, sha256(raw), 'and never the hash of the text as it was sent');
    // The text around each secret is still there to be read and quoted.
    assert.match(answer.text, /POSTGRES_PASSWORD=\[redacted\]/u);
    assert.match(answer.text, /Log in to the database with DB_PASS set to \[redacted\] and nothing else\./u);

    // An entry quoting the redacted text around a secret, as the model that read it would.
    const proposed = await propose(h, who.as, who.spaceId, [
      addFrom(answer.id, 'pitfall', 'Postgres needs its password at start', 'docker run -e POSTGRES_PASSWORD=[redacted] postgres:16'),
      addFrom(answer.id, 'convention', 'Database logins read DB_PASS alone', 'with DB_PASS set to [redacted] and nothing else'),
    ]);
    expectStatus(proposed, 200, 'entries citing the note are recorded');
    for (const op of proposed.body.ops as Outcome[]) assert.equal(op.status, 'applied', JSON.stringify(op));
    const sources = await h.prisma.wikiSource.findMany({ where: { ownerId: who.owner.id, kind: 'note' } });
    assert.equal(sources.length, 2);
    for (const source of sources) {
      assert.equal(source.quoteVerified, true, 'the quote is found in the note it cites');
      assert.equal(source.ref, toUuid(answer.id));
    }

    const stored = await everythingStored(h, who.owner.id);
    assert.ok(stored.includes('[redacted]'), 'the redacted text was stored');
    for (const seed of SEEDS) {
      for (const secret of [seed.secret].flat()) {
        assert.equal(survivingPiece(stored, secret), undefined, `a seeded secret leaked into what is stored: ${secret}`);
        assert.equal(survivingPiece(answer.text, secret), undefined, `a seeded secret leaked into the answer: ${secret}`);
      }
    }
    // A path is redacted the same way.
    const path = await registerNote(h, who.as, who.spaceId, `notes/POSTGRES_PASSWORD=hunter4-Imp0rt.md`, 'A plain note with no secret in its text.');
    expectStatus(path, 200, 'a file whose path carries a secret is registered');
    assert.equal(path.body.redacted, true);
    assert.equal(survivingPiece(await everythingStored(h, who.owner.id), 'hunter4-Imp0rt'), undefined, 'the path leaked');
  });
});

// ── 2. one content, one note ────────────────────────────────────────────────────────────────────

test('import · one content is one note: importing again makes no new source', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test('the same file, the same text under another name, and the same text with other line endings are one note', async () => {
    const who = await importer(h, 'dedup', 'tiered');
    const text = '# Orbit\n\nRun every pg spec through scripts/run-pg-spec.sh: a skip is red.\n';
    const first = await note(h, who, 'CLAUDE.md', text);
    assert.equal(first.created, true);
    const again = await note(h, who, 'CLAUDE.md', text);
    assert.deepEqual([again.id, again.created], [first.id, false], 'the same file again is the note already there');
    const renamed = await note(h, who, 'AGENTS.md', text);
    assert.deepEqual([renamed.id, renamed.created], [first.id, false], 'the same text under another name is the same note');
    const crlf = await note(h, who, 'CLAUDE.md', text.replace(/\n/gu, '\r\n'));
    assert.deepEqual([crlf.id, crlf.created], [first.id, false], 'a file read with other line endings is the same text');
    const rows = await h.prisma.wikiNote.findMany({ where: { ownerId: who.owner.id } });
    assert.equal(rows.length, 1, 'one row');
    assert.equal(rows[0].path, 'CLAUDE.md', 'the path is the one it was first read from');

    // Entries proposed from it, then the whole import run again: still one note.
    const proposed = await propose(h, who.as, who.spaceId, [addFrom(first.id, 'convention', 'Every pg spec runs through the script', 'a skip is red')]);
    expectStatus(proposed, 200, 'an entry citing the note is recorded');
    const rerun = await note(h, who, 'CLAUDE.md', text);
    assert.equal(rerun.created, false);
    assert.equal(await h.prisma.wikiNote.count({ where: { ownerId: who.owner.id } }), 1, 'the re-import made no new note');

    // A file whose text changed is a new note: it says something else.
    const changed = await note(h, who, 'CLAUDE.md', `${text}Never deploy on a Friday.\n`);
    assert.equal(changed.created, true);
    assert.notEqual(changed.id, first.id);
    assert.equal(await h.prisma.wikiNote.count({ where: { ownerId: who.owner.id } }), 2);
  });
});

// ── 3. a note is its owner's ────────────────────────────────────────────────────────────────────

test('import · a note is cited by its owner and by nobody else', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test('another owner can neither cite the note nor reach the space it is in', async () => {
    const mine = await importer(h, 'note-owner', 'manual');
    const theirs = await importer(h, 'note-stranger', 'manual');
    const kept = await note(h, mine, 'memory/release.md', 'release.sh next tags at once: it is not a dry run.');

    const cited = await propose(h, theirs.as, theirs.spaceId, [addFrom(kept.id, 'pitfall', 'release.sh next tags at once')]);
    expectStatus(cited, 422, "another owner's import cannot cite the note");
    assert.equal((cited.body.ops as Outcome[])[0].reasons?.[0].code, 'WIKI_SOURCE_UNRESOLVED');
    const agent = await call(h, theirs.as, 'POST', '/runner/wiki/changesets', {
      rationale: 'citing a note that is not mine',
      idempotencyKey: randomUUID(),
      ops: [addFrom(kept.id, 'pitfall', 'release.sh next tags at once')],
    });
    expectStatus(agent, 422, "another owner's agent cannot cite it either");
    assert.equal((agent.body.ops as Outcome[])[0].reasons?.[0].code, 'WIKI_SOURCE_UNRESOLVED');

    const intoMine = await registerNote(h, theirs.as, mine.spaceId, 'memory/x.md', 'A note for somebody else.');
    expectStatus(intoMine, 404, "another owner's space is not there to register into");
    const proposeIntoMine = await propose(h, theirs.as, mine.spaceId, [addFrom(kept.id, 'pitfall', 'Into a space not mine')]);
    expectStatus(proposeIntoMine, 404, "another owner's space is not there to propose into");
    assert.equal(await h.prisma.wikiChangeset.count({ where: { ownerId: theirs.owner.id } }), 0);
    assert.equal(await h.prisma.wikiNote.count({ where: { ownerId: theirs.owner.id } }), 0);

    // The owner cites it — with a quote from its text, and with none.
    const own = await propose(h, mine.as, mine.spaceId, [
      addFrom(kept.id, 'pitfall', 'release.sh next tags at once', 'it is not a dry run'),
      addFrom(kept.id, 'concept', 'What release.sh next does'),
    ]);
    expectStatus(own, 200, 'the owner cites their own note');
    // uuid(7): the id order is the order the two were written in.
    const sources = await h.prisma.wikiSource.findMany({ where: { ownerId: mine.owner.id }, orderBy: { id: 'asc' } });
    assert.deepEqual(sources.map((s) => [s.kind, s.ref, s.quoteVerified, s.locator]), [
      ['note', toUuid(kept.id), true, { path: 'memory/release.md' }],
      ['note', toUuid(kept.id), false, { path: 'memory/release.md' }],
    ]);
  });

  await t.test('a quote is checked against the note, and a ref that names no note resolves to nothing', async () => {
    const who = await importer(h, 'note-quote', 'manual');
    const kept = await note(h, who, 'memory/quotes.md', 'The   overlay    must stay\nuntil the acceptance run is over.');
    const whitespace = await propose(h, who.as, who.spaceId, [addFrom(kept.id, 'convention', 'Keep the overlay', 'The overlay must stay until the acceptance run')]);
    expectStatus(whitespace, 200, 'a quote the model wrapped differently is still the note\'s');
    const wrong = await propose(h, who.as, who.spaceId, [addFrom(kept.id, 'convention', 'Remove the overlay', 'remove the overlay at once')]);
    expectStatus(wrong, 422, 'a quote the note does not hold is refused');
    assert.equal((wrong.body.ops as Outcome[])[0].reasons?.[0].code, 'WIKI_QUOTE_NOT_FOUND');
    for (const ref of ['n1', randomUUID()]) {
      const none = await propose(h, who.as, who.spaceId, [addFrom(ref, 'concept', `A note that is not there ${ref}`)]);
      expectStatus(none, 422, `a ref that names no note (${ref})`);
      assert.equal((none.body.ops as Outcome[])[0].reasons?.[0].code, 'WIKI_SOURCE_UNRESOLVED');
    }
  });
});

// ── 4. the review mode decides, and the floors hold ─────────────────────────────────────────────

test('import · what an import proposes takes effect as the space\'s review mode says', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test('Manual: every imported entry waits for review, recorded as the import of the session that ran it', async () => {
    const who = await importer(h, 'manual', 'manual');
    const kept = await note(h, who, 'CLAUDE.md', 'Conventions for agents working in this repository.');
    const proposed = await propose(h, who.as, who.spaceId, [
      addFrom(kept.id, 'convention', 'A convention from CLAUDE.md'),
      addFrom(kept.id, 'pitfall', 'A pitfall from CLAUDE.md'),
      addFrom(kept.id, 'decision', 'A decision from CLAUDE.md'),
    ]);
    expectStatus(proposed, 200, 'the import is recorded');
    const ops = proposed.body.ops as Outcome[];
    assert.deepEqual(ops.map((op) => [op.status, op.waitsFor]), [['pending', undefined], ['pending', undefined], ['pending', undefined]]);
    const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(proposed.body.changesetId) } });
    assert.deepEqual([changeset.origin, changeset.sessionId, changeset.status], ['import', who.session, 'pending']);
    for (const op of ops) {
      const entry = await entryRow(h, op.entryId!);
      assert.deepEqual([entry.status, entry.trust], ['proposed', 'proposed']);
    }
    const review = await call(h, { bearer: who.owner.bearer }, 'GET', `/wiki/review?space=${who.spaceId}`);
    expectStatus(review, 200, 'Review lists it');
    assert.equal((review.body as Array<{ ops: unknown[] }>).flatMap((c) => c.ops).length, 3);
    assert.equal((await pushed(h, who)).size, 0, 'nothing is pushed before the owner accepts it');
  });

  await t.test('Tiered: applied as Unreviewed — a note is never the owner\'s own words — never pushed, and its spot check drawn', async () => {
    const who = await importer(h, 'tiered', 'tiered');
    const kept = await note(h, who, 'memory/feedback-rules.md', 'The owner wants replies in Chinese, and code left as it is.');
    const ops = [
      addFrom(kept.id, 'convention', 'Reply in Chinese', 'The owner wants replies in Chinese'),
      addFrom(kept.id, 'decision', 'Code stays in English'),
      ...concepts(kept.id, 8, 'Tiered'),
    ];
    const proposed = await propose(h, who.as, who.spaceId, ops);
    expectStatus(proposed, 200, 'the import is recorded');
    const outcomes = proposed.body.ops as Outcome[];
    assert.ok(outcomes.every((op) => op.status === 'applied'), JSON.stringify(outcomes));
    for (const op of outcomes) {
      const entry = await entryRow(h, op.entryId!);
      assert.deepEqual([entry.status, entry.trust], ['active', 'unreviewed'], `${entry.title} is shown, and unreviewed`);
    }
    // One of the ten is drawn into Review as a spot check, at the place the draw names.
    const rows = await Promise.all(outcomes.map((op) => opRow(h, op.opId!)));
    const spaceUuid = toUuid(who.spaceId);
    const drawn = rows.map((row, n) => (isSpotCheckDraw(spaceUuid, n) ? n : -1)).filter((n) => n >= 0);
    assert.deepEqual(rows.map((row, n) => (row.spotCheck ? n : -1)).filter((n) => n >= 0), drawn);
    assert.equal(drawn.length, 1);
    assert.ok(rows.every((row) => row.appliedByMode === 'tiered'));
    assert.equal((await pushed(h, who)).size, 0, 'an Unreviewed entry is shown, and never pushed');
  });

  await t.test('Automatic: held for a verification that reads the note\'s own text; a supported verdict pushes it', async () => {
    const who = await importer(h, 'automatic', 'automatic');
    const text = 'Wait for GET /health to answer 200 before calling the local model: the tunnel drops.';
    const kept = await note(h, who, 'memory/vllm-health.md', text);
    const proposed = await propose(h, who.as, who.spaceId, [
      addFrom(kept.id, 'pitfall', 'The local model tunnel drops', 'the tunnel drops'),
      addFrom(kept.id, 'convention', 'Check the local model health first'),
    ]);
    expectStatus(proposed, 200, 'the import is recorded');
    const outcomes = proposed.body.ops as Outcome[];
    assert.deepEqual(outcomes.map((op) => [op.status, op.waitsFor]), [['pending', 'verification'], ['pending', 'verification']]);
    for (const op of outcomes) assert.equal((await opRow(h, op.opId!)).decision, 'verifying');
    assert.equal((await pushed(h, who)).size, 0, 'nothing is live before its verdict');

    // What `orbit wiki verify`, run in the session that imported, is handed: the note's own text.
    const list = await call(h, who.as, 'GET', `/runner/wiki/spaces/${who.spaceId}/verifications`);
    expectStatus(list, 200, 'the importing session lists what waits for its verdict');
    const items = list.body.items as Array<{ opId: string; sources: Array<{ kind: string; text: string | null; quote: string | null }> }>;
    assert.equal(items.length, 2);
    for (const item of items) {
      assert.equal(item.sources[0].kind, 'note');
      assert.equal(item.sources[0].text, text, 'the verifier reads the note\'s stored text');
    }
    assert.equal(items[0].sources[0].quote, 'the tunnel drops');

    const verified = await h.service.recordVerifications(wikiImportPrincipal(who.owner.id, who.session), toUuid(who.spaceId), [
      { opId: items[0].opId, verdict: 'supported', reason: 'The note says the tunnel drops.', model: 'qwen3.8-27b-fp8' },
      { opId: items[1].opId, verdict: 'partial', reason: 'The note says to wait, not that it is a rule.', model: 'qwen3.8-27b-fp8' },
    ]);
    assert.deepEqual(verified.outcomes.map((o) => [o.status, 'trust' in o ? o.trust : null]), [['applied', 'auto'], ['applied', 'unreviewed']]);
    const live = await pushed(h, who);
    assert.ok(live.has(toUuid(outcomes[0].entryId!)), 'the supported entry is pushed');
    // A convention is pushed wherever the session is — when it is trusted: a partial one is shown only.
    assert.ok(!live.has(toUuid(outcomes[1].entryId!)), 'the partial one is shown and not pushed');
  });

  await t.test('the floors: a principle is refused, and an import in a session that read the web waits', async () => {
    const who = await importer(h, 'floors', 'tiered');
    const kept = await note(h, who, 'memory/values.md', 'Delete means forget: nothing is kept for later.');
    const principle = await propose(h, who.as, who.spaceId, [addFrom(kept.id, 'principle', 'Delete means forget')]);
    expectStatus(principle, 403, 'a principle is the owner\'s alone, whoever imports it');
    assert.equal((principle.body.ops as Outcome[])[0].reasons?.[0].code, 'WIKI_KIND_OWNER_ONLY');

    const tainted = await session(h, who.owner.id, { workspaceId: who.workspaceId, runnerId: who.machine.id });
    await toolCall(h, tainted, 'WebFetch', 'a page from the web');
    const fromTheWeb = await propose(h, { runner: who.machine.token, session: tainted }, who.spaceId, [addFrom(kept.id, 'convention', 'Nothing is kept for later')]);
    expectStatus(fromTheWeb, 200, 'the op is recorded');
    const op = (fromTheWeb.body.ops as Outcome[])[0];
    assert.equal(op.status, 'pending', 'a tainted op waits for the owner even in Tiered');
    assert.equal((await opRow(h, op.opId!)).tainted, true);
  });

  await t.test('the floors: the circuit breaker counts what an import applies', async () => {
    const who = await importer(h, 'breaker', 'tiered');
    await activeEntries(h, who.owner.id, toUuid(who.spaceId), 100);
    const kept = await note(h, who, 'memory/many.md', 'Many small facts about the repository.');
    const proposed = await propose(h, who.as, who.spaceId, concepts(kept.id, 12, 'Breaker'));
    expectStatus(proposed, 200, 'the import is recorded up to the breaker');
    const outcomes = proposed.body.ops as Outcome[];
    assert.equal(outcomes.filter((op) => op.status === 'applied').length, 10, 'ten percent of a hundred');
    assert.deepEqual(outcomes.slice(10).map((op) => op.reasons?.[0].code), ['WIKI_QUOTA', 'WIKI_QUOTA']);
  });
});

// ── 5. the caps a batch is held to ──────────────────────────────────────────────────────────────

test('import · a batch is capped, and what needs review arrives a batch at a time', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test(`a changeset holds at most ${WIKI_LIMITS.opsPerChangeset} ops`, async () => {
    const who = await importer(h, 'thirty', 'tiered');
    const kept = await note(h, who, 'memory/thirty.md', 'Thirty-one facts, one too many for a run.');
    const proposed = await propose(h, who.as, who.spaceId, concepts(kept.id, WIKI_LIMITS.opsPerChangeset + 1, 'Cap'));
    expectStatus(proposed, 200, 'the first thirty are recorded');
    const outcomes = proposed.body.ops as Outcome[];
    assert.equal(outcomes.filter((op) => op.status === 'applied').length, WIKI_LIMITS.opsPerChangeset);
    assert.equal(outcomes[WIKI_LIMITS.opsPerChangeset].reasons?.[0].code, 'WIKI_QUOTA');
    assert.equal(WIKI_IMPORT_RULES.opsPerRun, WIKI_LIMITS.opsPerChangeset, 'a run of the import is one changeset\'s worth');
  });

  await t.test('Manual: five that wait for review a request, fifteen a session, thirty a space — and a dry run says so first', async () => {
    const who = await importer(h, 'batches', 'manual');
    const kept = await note(h, who, 'memory/batches.md', 'Facts the owner has to review.');

    const dry = await propose(h, who.as, who.spaceId, concepts(kept.id, 6, 'Dry'), { dryRun: true });
    expectStatus(dry, 200, 'a dry run answers');
    assert.deepEqual((dry.body.ops as Outcome[]).map((op) => op.status), ['pending', 'pending', 'pending', 'pending', 'pending', 'refused']);
    assert.equal((dry.body.ops as Outcome[])[5].reasons?.[0].code, 'WIKI_QUOTA');
    assert.equal(await h.prisma.wikiChangeset.count({ where: { ownerId: who.owner.id } }), 0, 'a dry run records nothing');

    const first = await propose(h, who.as, who.spaceId, concepts(kept.id, 6, 'First'));
    expectStatus(first, 200, 'five are recorded');
    assert.deepEqual((first.body.ops as Outcome[]).map((op) => op.status), ['pending', 'pending', 'pending', 'pending', 'pending', 'refused']);
    for (const batch of ['Second', 'Third']) {
      expectStatus(await propose(h, who.as, who.spaceId, concepts(kept.id, 5, batch)), 200, `the ${batch.toLowerCase()} batch`);
    }
    const fourth = await propose(h, who.as, who.spaceId, concepts(kept.id, 1, 'Fourth'));
    expectStatus(fourth, 429, 'a session has put fifteen in front of the owner');
    assert.equal((fourth.body.ops as Outcome[])[0].reasons?.[0].code, 'WIKI_QUOTA');

    // Another session of the same import fills the space's queue to thirty, and no further.
    const next = await session(h, who.owner.id, { workspaceId: who.workspaceId, runnerId: who.machine.id });
    const as = { runner: who.machine.token, session: next };
    for (const batch of ['Fifth', 'Sixth', 'Seventh']) expectStatus(await propose(h, as, who.spaceId, concepts(kept.id, 5, batch)), 200, batch);
    const third = await session(h, who.owner.id, { workspaceId: who.workspaceId, runnerId: who.machine.id });
    const full = await propose(h, { runner: who.machine.token, session: third }, who.spaceId, concepts(kept.id, 2, 'Overflow'));
    expectStatus(full, 429, 'the space holds thirty waiting for review');
    assert.deepEqual((full.body.ops as Outcome[]).map((op) => op.reasons?.[0].code), ['WIKI_REVIEW_QUEUE_FULL', 'WIKI_REVIEW_QUEUE_FULL']);
    assert.equal(await h.prisma.wikiChangesetOp.count({ where: { ownerId: who.owner.id, decision: 'pending' } }), WIKI_LIMITS.pendingOpsPerSpace);
  });

  await t.test('the same batch sent twice under its key is recorded once', async () => {
    const who = await importer(h, 'replay', 'tiered');
    const kept = await note(h, who, 'memory/replay.md', 'A batch sent again after a lost answer.');
    const ops = concepts(kept.id, 3, 'Replay');
    const key = `wiki-import:${randomUUID()}`;
    const once = await propose(h, who.as, who.spaceId, ops, { idempotencyKey: key });
    const twice = await propose(h, who.as, who.spaceId, ops, { idempotencyKey: key });
    expectStatus(twice, 200, 'the replay answers');
    assert.equal(twice.body.replayed, true);
    assert.equal(twice.body.changesetId, once.body.changesetId);
    assert.equal(await h.prisma.wikiEntry.count({ where: { ownerId: who.owner.id } }), 3);
  });
});

// ── the door ────────────────────────────────────────────────────────────────────────────────────

test('import · the door: a session the runner hosts, not one that judges work, and a note within its limits', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test('a headless call, a session another machine hosts and a session that judges work are refused', async () => {
    const who = await importer(h, 'door', 'manual');
    const kept = await note(h, who, 'memory/door.md', 'A note for the door checks.');
    for (const [route, body] of [
      [`/runner/wiki/spaces/${who.spaceId}/notes`, { path: 'x.md', text: 'x' }],
      [`/runner/wiki/spaces/${who.spaceId}/imports`, { rationale: 'r', ops: [addFrom(kept.id, 'concept', 'Headless')] }],
    ] as const) {
      expectStatus(await call(h, { runner: who.machine.token }, 'POST', route, body), 400, `${route} without a session`);
      const elsewhere = await runner(h, who.owner.id);
      const hosted = await session(h, who.owner.id, { workspaceId: who.workspaceId, runnerId: elsewhere.id });
      expectStatus(await call(h, { runner: who.machine.token, session: hosted }, 'POST', route, body), 403, `${route} for a session another machine hosts`);
      const foreman = await session(h, who.owner.id, {
        workspaceId: who.workspaceId,
        runnerId: who.machine.id,
        taskId: await task(h, who.owner.id, { isForeman: true }),
      });
      const excluded = await call(h, { runner: who.machine.token, session: foreman }, 'POST', route, body);
      expectStatus(excluded, 403, `${route} for a session that forems work`);
      assert.equal(excluded.body.code, 'WIKI_SESSION_EXCLUDED');
    }
    assert.equal(await h.prisma.wikiChangeset.count({ where: { ownerId: who.owner.id } }), 0);
  });

  await t.test('a session with no workspace imports into the space it names', async () => {
    const owner = await account(h, 'no-workspace');
    const machine = await runner(h, owner.id);
    const spaceId = await modeSpace(h, owner, 'manual');
    const loose = await session(h, owner.id, { runnerId: machine.id });
    const as = { runner: machine.token, session: loose };
    const registered = await registerNote(h, as, spaceId, 'AGENTS.md', 'Agents read this before they start.');
    expectStatus(registered, 200, 'a note into the named space');
    const proposed = await propose(h, as, spaceId, [addFrom(registered.body.id, 'concept', 'What agents read first')]);
    expectStatus(proposed, 200, 'an import into the named space');
    const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(proposed.body.changesetId) } });
    assert.equal(changeset.spaceId, toUuid(spaceId));
  });

  await t.test('a note is held to its limits, and an empty one is not a note', async () => {
    const who = await importer(h, 'limits', 'manual');
    const long = await registerNote(h, who.as, who.spaceId, 'memory/long.md', 'x'.repeat(WIKI_IMPORT_RULES.noteMaxChars + 1));
    expectStatus(long, 400, 'a text past the limit');
    assert.equal(long.body.code, 'WIKI_SCHEMA');
    assert.deepEqual(long.body.errors.map((e: { path: string }) => e.path), ['text']);
    const fits = await registerNote(h, who.as, who.spaceId, 'memory/fits.md', 'y'.repeat(WIKI_IMPORT_RULES.noteMaxChars));
    expectStatus(fits, 200, 'a text at the limit');
    assert.equal(fits.body.chars, WIKI_IMPORT_RULES.noteMaxChars);
    const blank = await registerNote(h, who.as, who.spaceId, '  ', '   ');
    expectStatus(blank, 400, 'a blank path and text');
    assert.deepEqual(blank.body.errors.map((e: { path: string }) => e.path).sort(), ['path', 'text']);
    const longPath = await registerNote(h, who.as, who.spaceId, 'p'.repeat(WIKI_IMPORT_RULES.notePathMaxChars + 1), 'fine');
    expectStatus(longPath, 400, 'a path past the limit');
    assert.equal(await h.prisma.wikiNote.count({ where: { ownerId: who.owner.id } }), 1);
  });
});
