/**
 * The dossier and the cursor (criterion 2; contracts/wiki.contract.json `maintenance`), over real HTTP
 * and against a real PostgreSQL — and a space's maintenance settings, which say who a maintenance run is.
 *
 * What criterion 2's verification method asks, each read back from the doors and from the database:
 *
 *   1. the same records extracted twice give the same text byte for byte, and the same hash;
 *   2. the seeded secrets — every shape the shared redactor knows, and the owner's workspace.env
 *      values — leak zero times, in lines the dossier provably carries;
 *   3. a session whose timeline passes 8,000 tokens is cut to it, and says it was;
 *   4. a session that is not a maintenance run of the space, and any other tenant, are refused;
 *   5. each of the five committed facts adds one to the backlog;
 *   6. the cursor only moves forward, and a run that did not succeed does not move it;
 *   7. every line goes back to its first-hand record: the words at the positions it names, read from the
 *      record as a quote of it is checked and redacted, are the words it declares — the lines the dossier
 *      compressed as much as the ones it copied whole (revision 2);
 *
 * and beside them: maintenance is off by default and only the owner changes it; turning it on makes
 * one hidden list, and starts the cursor as far back as the owner's look-back says — 14 days by default,
 * the moment itself, or the earliest fact — never moving a cursor that has a position; the dossier
 * keeps nothing but its sources and hash; the agent's own trace is in it
 * and memory-file tool calls are not; a batch project gets counts and no dossiers; and a tool error
 * shared by three sessions is a cluster.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-dossier.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { WIKI_MAINTENANCE_RULES, toUuid, wikiEstimateTokens, type WikiDossierSpan, type WikiSourceKind } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { redactSecrets } from '../common/secret-redaction';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiMaintenanceController } from '../runner-api/runner-wiki-maintenance.controller';
import { WikiController } from './wiki.controller';
import { buildDossier, loadDossierRecords, storedDossierSources } from './wiki-dossier';
import { isWikiMaintenanceSession, WikiMaintenance, wikiMaintenanceSpaceOf } from './wiki-maintenance';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  maintenance: WikiMaintenance;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = {} as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);
    const maintenance = new WikiMaintenance(prisma as unknown as PrismaService);

    @Module({
      controllers: [WikiController, RunnerWikiMaintenanceController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiMaintenance, useValue: maintenance },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiDossierModule {}

    const app = await NestFactory.create(WikiDossierModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, maintenance, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 600)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

/** Ten minutes ago and earlier: past the grace a fact is given to commit before a page hands it out. */
const minutesAgo = (minutes: number): Date => new Date(Date.now() - minutes * 60_000);

/**
 * A time as the UTC text Orbit's `timestamp(3)` columns hold. Handed a Date, `pg` writes the local
 * time with its offset, which a column without a zone keeps as local wall-clock time — hours off on a
 * host whose clock is not UTC, the way Prisma never writes one.
 */
const utc = (at: Date | null | undefined): string | null => (at ? at.toISOString() : null);

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-dossier-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string, env: Record<string, string> = {}): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env") VALUES ($1,'spec',$2,$3)`, [id, ownerId, JSON.stringify(env)]);
  return id;
}

interface SessionShape {
  workspaceId: string | null;
  runnerId?: string | null;
  taskId?: string | null;
  status?: string;
  lastTurnAt?: Date | null;
  title?: string;
  createdAt?: Date;
}

async function session(h: Harness, ownerId: string, shape: SessionShape): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","status","last_turn_at","dispatch_origin","created_at","updated_at")
     VALUES ($1,$2,'p',$3,$3,$4,$5,$6,$7::run_status,$8,'USER',$9,now())`,
    [
      id,
      shape.title ?? 'a session',
      ownerId,
      shape.workspaceId,
      shape.runnerId ?? null,
      shape.taskId ?? null,
      shape.status ?? 'AWAITING_INPUT',
      utc(shape.lastTurnAt === undefined ? minutesAgo(30) : shape.lastTurnAt),
      utc(shape.createdAt ?? minutesAgo(60)),
    ],
  );
  return id;
}

interface TaskShape {
  title?: string;
  status?: string;
  assigneeId?: string | null;
  listId?: string | null;
  projectId?: string | null;
  acceptance?: string | null;
  updatedAt?: Date;
}

async function task(h: Harness, ownerId: string, shape: TaskShape = {}): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id","project_id",
                         "acceptance_criteria","completion_criterion","updated_at")
     VALUES ($1,$2,$3,'USER',$3,$4::task_status,$5,$6,$7,$8,'OWNER_CONFIRMED',$9)`,
    [
      id,
      shape.title ?? 'a task',
      ownerId,
      shape.status ?? 'OPEN',
      shape.assigneeId ?? null,
      shape.listId ?? null,
      shape.projectId ?? null,
      shape.acceptance ?? null,
      utc(shape.updatedAt ?? minutesAgo(20)),
    ],
  );
  return id;
}

async function turn(
  h: Harness,
  sessionId: string,
  content: string,
  shape: { kind?: string; sendIntent?: string | null; clientTurnId?: string; at?: Date } = {},
): Promise<string> {
  const id = randomUUID();
  const seq = (await h.sql.query<{ n: number }>(
    `SELECT COALESCE(MAX("seq"), 0)::int + 1 AS n FROM "conversation_turn" WHERE "session_id" = $1`,
    [sessionId],
  )).rows[0].n;
  await h.sql.query(
    `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status","kind","send_intent","created_at")
     VALUES ($1,$2,$3,$4,$5,'ANSWERED',$6,$7,$8)`,
    [id, sessionId, seq, shape.clientTurnId ?? randomUUID(), content, shape.kind ?? 'message',
      shape.sendIntent === undefined ? 'NEXT_TURN' : shape.sendIntent, utc(shape.at ?? minutesAgo(50))],
  );
  return id;
}

async function event(h: Harness, sessionId: string, type: string, payload: unknown, at: Date = minutesAgo(45)): Promise<string> {
  const id = randomUUID();
  const seq = (await h.sql.query<{ n: number }>(
    `SELECT COALESCE(MAX("seq"), 0)::int + 1 AS n FROM "run_event" WHERE "session_id" = $1`,
    [sessionId],
  )).rows[0].n;
  await h.sql.query(
    `INSERT INTO "run_event"("id","session_id","seq","type","payload","created_at") VALUES ($1,$2,$3,$4,$5,$6)`,
    [id, sessionId, seq, type, JSON.stringify(payload), utc(at)],
  );
  return id;
}

/** A tool call as the runner records it: the tool_use and tool_result events, and the tool_call row. */
async function tool(
  h: Harness,
  sessionId: string,
  name: string,
  input: Record<string, unknown>,
  output: unknown,
  shape: { isError?: boolean; at?: Date } = {},
): Promise<{ useEventId: string; toolCallId: string }> {
  const toolUseId = `toolu_${randomUUID().replace(/-/g, '')}`;
  const at = shape.at ?? minutesAgo(44);
  const useEventId = await event(h, sessionId, 'tool_use', { id: toolUseId, name, input }, at);
  await event(h, sessionId, 'tool_result', { toolUseId, content: output, isError: shape.isError ?? false }, at);
  const toolCallId = randomUUID();
  await h.sql.query(
    `INSERT INTO "tool_call"("id","session_id","name","tool_use_id","input","output","is_error","started_at","finished_at")
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$8)`,
    [toolCallId, sessionId, name, toolUseId, JSON.stringify(input), JSON.stringify(output), shape.isError ?? false, utc(at)],
  );
  return { useEventId, toolCallId };
}

async function approval(
  h: Harness,
  sessionId: string,
  shape: { tool: string; status: string; input?: unknown; answers?: unknown; message?: string | null; decidedBy?: string | null; decidedAt?: Date | null },
): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "approval"("id","session_id","tool_name","input","status","answers","message","decided_by_id","created_at","decided_at")
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
    [
      id,
      sessionId,
      shape.tool,
      JSON.stringify(shape.input ?? {}),
      shape.status,
      shape.answers === undefined ? null : JSON.stringify(shape.answers),
      shape.message ?? null,
      shape.decidedBy ?? null,
      utc(minutesAgo(48)),
      utc(shape.decidedAt === undefined ? minutesAgo(47) : shape.decidedAt),
    ],
  );
  return id;
}

async function receipt(h: Harness, ownerId: string, sessionId: string, at: Date = minutesAgo(15)): Promise<{ id: string; sourceSha: string; targetSha: string }> {
  const id = randomUUID();
  const sourceSha = createHash('sha1').update(id).digest('hex');
  const targetSha = createHash('sha1').update(`${id}-after`).digest('hex');
  await h.sql.query(
    `INSERT INTO "session_merge_receipt"("id","owner_id","session_id","result","source_branch","source_sha","target_branch",
                                          "target_sha_after","recorded_by","idempotency_key","created_at")
     VALUES ($1,$2,$3,'MERGED','orbit/dossier-spec',$4,'main',$5,'RUNNER',$6,$7)`,
    [id, ownerId, sessionId, sourceSha, targetSha, `key-${id}`, utc(at)],
  );
  return { id, sourceSha, targetSha };
}

async function project(h: Harness, ownerId: string, repoUrl?: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "project"("id","title","owner_id","updated_at") VALUES ($1,'a project',$2,now())`, [id, ownerId]);
  if (repoUrl) {
    await h.sql.query(
      `INSERT INTO "project_codebase"("id","project_id","owner_id","canonical_repo_url","upstream_ref","integration_ref","ref_authority","updated_at")
       VALUES ($1,$2,$3,$4,'refs/heads/main','refs/heads/main','REMOTE',now())`,
      [randomUUID(), id, ownerId, repoUrl],
    );
  }
  return id;
}

async function criterion(h: Harness, projectId: string, ordinal: number): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "project_acceptance_criterion_definition"("id","project_id","ordinal","text","verification_method","content_hash","created_at","updated_at")
     VALUES ($1,$2,$3,'the dossier is cut to 8k','EXECUTABLE: a spec',$4,$5,$5)`,
    [id, projectId, ordinal, createHash('sha256').update(id).digest('hex'), utc(minutesAgo(12))],
  );
  return id;
}

async function blocker(h: Harness, projectId: string, subjectId: string, note: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "project_blocker"(
       "id","project_id","kind","owner","recovery","severity","required_action","next_check_at",
       "subject_type","subject_id","dedupe_key","lifecycle_generation","condition_version",
       "first_seen_at","last_seen_at","resolved_at","resolved_by","resolution_note","updated_at")
     VALUES ($1,$2,'AWAITING_USER_APPROVAL','USER','HUMAN','CRITICAL','decide whether the extra files land',now(),
             'TASK',$3,$4,1,repeat('0',64),now(),now(),$5,'USER',$6,now())`,
    [id, projectId, subjectId, `spec:${id}`, utc(minutesAgo(14)), note],
  );
  return id;
}

async function comment(h: Harness, taskId: string, authorType: 'AGENT' | 'USER', authorId: string, body: string, at: Date): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task_comment"("id","task_id","author_type","author_id","body","created_at") VALUES ($1,$2,$3::creator_type,$4,$5,$6)`,
    [id, taskId, authorType, authorId, body, utc(at)],
  );
  return id;
}

interface Space {
  id: string;
  workspaceId: string;
}

/** A space the owner makes through the door, bound to a workspace of theirs. */
async function space(h: Harness, owner: Account, workspaceId: string, repoUrl?: string): Promise<string> {
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', {
    title: 'A maintained space',
    ...(repoUrl ? { repoUrl } : {}),
  });
  expectStatus(made, 201, 'the owner creates a space');
  const id = toUuid(made.body.id as string);
  const bound = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${id}/workspaces`, { workspaceId });
  expectStatus(bound, 200, 'the owner binds the workspace');
  return id;
}

/** Maintenance turned on by the owner, and the list it made. */
async function maintained(h: Harness, owner: Account, spaceId: string, workspaceId: string): Promise<string> {
  const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true, workspaceId } });
  expectStatus(on, 200, 'the owner turns maintenance on');
  const listId = on.body.settings.maintenance.listId as string;
  assert.ok(listId, 'turning maintenance on makes the list');
  return toUuid(listId);
}

/** A maintenance run of the space: a task in its list, and that task's session on the runner. */
async function maintenanceRun(h: Harness, ownerId: string, listId: string, workspaceId: string, runnerId: string): Promise<string> {
  const run = await task(h, ownerId, { title: 'Wiki maintenance run', listId, assigneeId: workspaceId });
  return session(h, ownerId, { workspaceId, runnerId, taskId: run, status: 'RUNNING', lastTurnAt: minutesAgo(1) });
}

// ── 0. maintenance settings: off by default, the owner's alone ───────────────────────────────────

test('maintenance is off by default, only the owner changes it, and turning it on makes one hidden list', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const stranger = await account(h, 'stranger');
  const ws = await workspace(h, owner.id);
  const spaceId = await space(h, owner, ws);

  const fresh = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${spaceId}`);
  expectStatus(fresh, 200, 'the owner reads the space');
  const { enabled, workspaceId, provider, dailyRunLimit, listId: noList } = fresh.body.settings.maintenance;
  assert.deepEqual({ enabled, workspaceId, provider, dailyRunLimit, listId: noList }, {
    enabled: false,
    workspaceId: null,
    provider: 'local-vllm',
    dailyRunLimit: 8,
    listId: null,
  }, 'maintenance is off until the owner turns it on');

  // A request that carries a session header is a session's, whatever it authenticated as.
  const fromSession = await call(h, { bearer: owner.bearer, session: randomUUID() }, 'PATCH', `/wiki/spaces/${spaceId}`, {
    maintenance: { enabled: true, workspaceId: ws },
  });
  expectStatus(fromSession, 403, 'a session may not turn maintenance on');
  assert.equal(fromSession.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
  const byStranger = await call(h, { bearer: stranger.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, {
    maintenance: { enabled: true, workspaceId: ws },
  });
  expectStatus(byStranger, 404, "another account's space is a plain 404");
  const runnerDoor = await call(h, { runner: (await runner(h, owner.id)).token }, 'PATCH', `/runner/wiki/spaces/${spaceId}`, {
    maintenance: { enabled: true, workspaceId: ws },
  });
  expectStatus(runnerDoor, 404, 'the runner door has no settings route at all');
  const withoutWorkspace = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true } });
  expectStatus(withoutWorkspace, 400, 'maintenance needs the workspace its runs take place in');
  const otherWorkspace = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, {
    maintenance: { enabled: true, workspaceId: await workspace(h, stranger.id) },
  });
  expectStatus(otherWorkspace, 404, "another account's workspace is a 404");
  const still = await h.sql.query<{ settings: Record<string, unknown> }>(`SELECT "settings" FROM "wiki_space" WHERE "id" = $1`, [spaceId]);
  assert.equal((still.rows[0].settings.maintenance as { enabled?: boolean } | undefined)?.enabled ?? false, false,
    'none of the refused requests turned it on');
  assert.equal((await h.sql.query(`SELECT 1 FROM "task_list" WHERE "owner_id" = $1`, [owner.id])).rowCount, 0, 'and none made a list');

  // The owner turns it on: the list is made hidden, and recorded; a listId in the request is not taken.
  const decoy = randomUUID();
  const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, {
    push: false,
    maintenance: { enabled: true, workspaceId: ws, provider: 'local-vllm', dailyRunLimit: 12, listId: decoy },
  });
  expectStatus(on, 200, 'the owner turns maintenance on');
  const settings = on.body.settings;
  assert.equal(settings.push, false, 'the other settings of the same request are written too');
  assert.equal(settings.maintenance.enabled, true);
  assert.equal(toUuid(settings.maintenance.workspaceId), ws);
  assert.equal(settings.maintenance.dailyRunLimit, 12);
  const listId = toUuid(settings.maintenance.listId);
  assert.notEqual(listId, decoy, 'the list is the server\'s, never the request\'s');
  const list = await h.sql.query<{ title: string; hidden: boolean; max_concurrent: number | null; owner_id: string }>(
    `SELECT "title", "hidden", "max_concurrent", "owner_id" FROM "task_list" WHERE "id" = $1`,
    [listId],
  );
  assert.deepEqual(list.rows[0], { title: 'Wiki maintenance', hidden: true, max_concurrent: 1, owner_id: owner.id });

  // Changing it again, turning it off and on: still the one list.
  const budget = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { dailyRunLimit: 24 } });
  expectStatus(budget, 200, 'the owner changes the daily limit');
  assert.equal(budget.body.settings.maintenance.enabled, true, 'a key left out stays as it was');
  const off = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: false } });
  expectStatus(off, 200, 'the owner turns it off');
  assert.equal(off.body.settings.maintenance.enabled, false);
  assert.equal(toUuid(off.body.settings.maintenance.listId), listId, 'turning it off keeps the list');
  const again = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true } });
  expectStatus(again, 200, 'the owner turns it on again');
  assert.equal(toUuid(again.body.settings.maintenance.listId), listId);
  assert.equal((await h.sql.query(`SELECT 1 FROM "task_list" WHERE "owner_id" = $1`, [owner.id])).rowCount, 1, 'one list, ever');
  // A write of another setting leaves maintenance as it stands.
  const push = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { push: true });
  expectStatus(push, 200, 'the owner turns push back on');
  assert.equal(push.body.settings.maintenance.enabled, true);
  assert.equal(push.body.settings.maintenance.dailyRunLimit, 24);
});

// ── 0b. where the cursor starts: as far back as the owner says, once ────────────────────────────

const DAY_MS = 86_400_000;

/** The space's cursor row as the database holds it, or null before anything made it. */
async function cursorRowOf(h: Harness, spaceId: string) {
  const rows = await h.sql.query<{
    position_at: Date | null; position_kind: string | null; position_ref: string | null;
    issued_at: Date | null; issued_kind: string | null; issued_ref: string | null;
  }>(`SELECT "position_at","position_kind","position_ref","issued_at","issued_kind","issued_ref" FROM "wiki_cursor" WHERE "space_id" = $1`,
    [spaceId]);
  return rows.rows[0] ?? null;
}

test('turning maintenance on starts the cursor as far back as the owner says — 14 days by default, now, or the earliest fact — and never moves one that has a position', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const stranger = await account(h, 'stranger');
  const machine = await runner(h, owner.id);

  /** A space of its own workspace, whose sessions came to rest 40, 20 and 13 days ago and half an hour ago. */
  const withHistory = async () => {
    const ws = await workspace(h, owner.id);
    const spaceId = await space(h, owner, ws);
    const sessions: Array<{ id: string; at: Date }> = [];
    for (const at of [new Date(Date.now() - 40 * DAY_MS), new Date(Date.now() - 20 * DAY_MS), new Date(Date.now() - 13 * DAY_MS), minutesAgo(30)]) {
      const id = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, lastTurnAt: at, createdAt: new Date(at.getTime() - 60_000) });
      await turn(h, id, 'The owner says what the wiki should know.', { at: new Date(at.getTime() - 30_000) });
      sessions.push({ id, at });
    }
    return { ws, spaceId, sessions };
  };
  const patch = (spaceId: string, maintenance: Record<string, unknown>, who: Caller = { bearer: owner.bearer }) =>
    call(h, who, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance });
  /** The owner turns maintenance on: when, to the millisecond either side, and the settings it answered. */
  const turnOn = async (spaceId: string, ws: string, maintenance: Record<string, unknown> = {}) => {
    const before = Date.now();
    const on = await patch(spaceId, { enabled: true, workspaceId: ws, ...maintenance });
    expectStatus(on, 200, 'the owner turns maintenance on');
    return { before, after: Date.now(), settings: on.body.settings.maintenance };
  };
  const within = (at: Date | null | undefined, from: number, to: number, why: string) =>
    assert.ok(at && at.getTime() >= from && at.getTime() <= to, `${why}: ${at?.toISOString()} is not within ${new Date(from).toISOString()} … ${new Date(to).toISOString()}`);

  // ── By default: fourteen days back, as the one position before every fact of that moment.
  const fourteen = await withHistory();
  const fresh = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${fourteen.spaceId}`);
  assert.equal(fresh.body.settings.maintenance.lookbackDays, 14, 'fourteen days unless the owner says otherwise');
  assert.equal(await cursorRowOf(h, fourteen.spaceId), null, 'no cursor before maintenance is on');
  const on = await turnOn(fourteen.spaceId, fourteen.ws);
  assert.equal(on.settings.lookbackDays, 14);
  const started = (await cursorRowOf(h, fourteen.spaceId))!;
  within(started.position_at, on.before - 14 * DAY_MS, on.after - 14 * DAY_MS, 'the watermark is now less fourteen days');
  assert.deepEqual([started.position_kind, started.position_ref], ['approval_answered', '00000000-0000-0000-0000-000000000000'],
    'the first kind in the order and the nil id: before every fact of that moment');
  assert.deepEqual([started.issued_at, started.issued_kind, started.issued_ref], [started.position_at, started.position_kind, started.position_ref],
    'and the furthest position handed out is the start too');
  const state = await h.maintenance.cursorState(owner.id, fourteen.spaceId);
  assert.equal(state.backlog, 2, 'the facts of the last fourteen days, and none older');
  assert.equal(state.oldestPendingAt, fourteen.sessions[2]!.at.toISOString(), 'the oldest fact after the start is thirteen days old');
  // The first run reads from there.
  const run = await maintenanceRun(h, owner.id, toUuid(on.settings.listId as string), fourteen.ws, machine.id);
  const page = await call(h, { runner: machine.token, session: run }, 'GET', `/runner/wiki/spaces/${fourteen.spaceId}/dossiers`);
  expectStatus(page, 200, 'the first run reads its first page');
  assert.deepEqual((page.body.dossiers as Array<{ sessionId: string }>).map((dossier) => toUuid(dossier.sessionId)),
    [fourteen.sessions[2]!.id, fourteen.sessions[3]!.id], 'the first page starts thirteen days back, not forty');

  // ── 0: from the moment it is turned on, and nothing before.
  const now = await withHistory();
  const zero = await turnOn(now.spaceId, now.ws, { lookbackDays: 0 });
  assert.equal(zero.settings.lookbackDays, 0);
  within((await cursorRowOf(h, now.spaceId))?.position_at, zero.before, zero.after, 'the watermark is the moment maintenance was turned on');
  assert.equal((await h.maintenance.cursorState(owner.id, now.spaceId)).backlog, 0, 'not even the half-hour-old session is after it');
  await session(h, owner.id, { workspaceId: now.ws, lastTurnAt: new Date() });
  assert.equal((await h.maintenance.cursorState(owner.id, now.spaceId)).backlog, 1, 'what comes to rest after it is');

  // ── All of history: no position, which reads from the earliest fact.
  const all = await withHistory();
  const everything = await turnOn(all.spaceId, all.ws, { lookbackDays: null });
  assert.equal(everything.settings.lookbackDays, null, 'all of history is kept as the choice it is, not read as the default');
  assert.equal((await cursorRowOf(h, all.spaceId))?.position_at ?? null, null, 'the cursor has no position');
  const allState = await h.maintenance.cursorState(owner.id, all.spaceId);
  assert.equal(allState.position, null);
  assert.equal(allState.backlog, 4, 'every fact there is');
  assert.equal(allState.oldestPendingAt, all.sessions[0]!.at.toISOString(), 'the forty-day-old session first');
  const kept = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${all.spaceId}`);
  assert.equal(kept.body.settings.maintenance.lookbackDays, null, 'and it reads back as all of history');

  // ── A cursor that has a position is never moved: not by a look-back changed, nor by maintenance turned
  // off and on again — and one a run advanced stays where the run put it.
  const read = await cursorRowOf(h, fourteen.spaceId);
  for (const lookbackDays of [0, null, 365]) {
    expectStatus(await patch(fourteen.spaceId, { lookbackDays }), 200, `the owner sets the look-back to ${lookbackDays}`);
    assert.deepEqual(await cursorRowOf(h, fourteen.spaceId), read, `a look-back of ${lookbackDays} moves no cursor`);
  }
  expectStatus(await patch(fourteen.spaceId, { enabled: false }), 200, 'the owner turns maintenance off');
  const again = await turnOn(fourteen.spaceId, fourteen.ws, { lookbackDays: 1 });
  assert.equal(again.settings.lookbackDays, 1);
  assert.deepEqual(await cursorRowOf(h, fourteen.spaceId), read, 'turning it on again starts nothing: the cursor has its position');
  const advanced = await call(h, { runner: machine.token, session: run }, 'POST', `/runner/wiki/spaces/${fourteen.spaceId}/cursor`, { to: page.body.cursor });
  expectStatus(advanced, 200, 'the run advances past what it read');
  assert.equal(advanced.body.advanced, true);
  const moved = await cursorRowOf(h, fourteen.spaceId);
  assert.equal(moved?.position_ref, fourteen.sessions[3]!.id, 'the watermark is the last fact the run read');
  expectStatus(await patch(fourteen.spaceId, { enabled: false }), 200, 'off');
  expectStatus(await patch(fourteen.spaceId, { enabled: true, lookbackDays: 30 }), 200, 'on, thirty days back');
  assert.deepEqual(await cursorRowOf(h, fourteen.spaceId), moved, 'a cursor a run advanced is never moved back');
  // A cursor that has no position yet has read nothing: the next turn-on starts it as its own look-back says.
  expectStatus(await patch(all.spaceId, { enabled: false }), 200, 'off');
  const week = await turnOn(all.spaceId, all.ws, { lookbackDays: 7 });
  within((await cursorRowOf(h, all.spaceId))?.position_at, week.before - 7 * DAY_MS, week.after - 7 * DAY_MS, 'a week back');
  assert.equal((await h.maintenance.cursorState(owner.id, all.spaceId)).backlog, 1, 'only the half-hour-old session is after it');

  // ── The owner's alone: a session, another account and the runner door change nothing, nor does a bad value.
  const fromSession = await patch(now.spaceId, { lookbackDays: 30 }, { bearer: owner.bearer, session: randomUUID() });
  expectStatus(fromSession, 403, 'a session may not set the look-back');
  assert.equal(fromSession.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
  expectStatus(await patch(now.spaceId, { lookbackDays: 30 }, { bearer: stranger.bearer }), 404, "another account's space is a plain 404");
  const runnerDoor = await call(h, { runner: machine.token, session: run }, 'PATCH', `/runner/wiki/spaces/${now.spaceId}`, { maintenance: { lookbackDays: 30 } });
  expectStatus(runnerDoor, 404, 'the runner door has no settings route at all');
  for (const bad of [-1, 366, 2.5, '14']) {
    expectStatus(await patch(now.spaceId, { lookbackDays: bad }), 400, `a look-back of ${JSON.stringify(bad)}`);
  }
  const unchanged = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${now.spaceId}`);
  assert.equal(unchanged.body.settings.maintenance.lookbackDays, 0, 'none of them changed it');
  expectStatus(await patch(now.spaceId, { lookbackDays: 30 }), 200, 'the owner changes it');
  assert.equal((await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${now.spaceId}`)).body.settings.maintenance.lookbackDays, 30);
});

// ── 4. only a maintenance session of the space, and no other tenant ──────────────────────────────

test('the dossier door and the cursor answer a maintenance session of the space and refuse everyone else', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const spaceId = await space(h, owner, ws);
  const listId = await maintained(h, owner, spaceId, ws);
  const run = await maintenanceRun(h, owner.id, listId, ws, machine.id);
  const plain = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id });
  const otherTask = await task(h, owner.id, { assigneeId: ws });
  const taskSession = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, taskId: otherTask });
  const secondSpace = await space(h, owner, await workspace(h, owner.id));

  assert.equal(await isWikiMaintenanceSession(h.prisma, { ownerId: owner.id, sessionId: run, spaceId }), true);
  assert.deepEqual(await wikiMaintenanceSpaceOf(h.prisma, run), { spaceId, ownerId: owner.id });
  assert.equal(await isWikiMaintenanceSession(h.prisma, { ownerId: owner.id, sessionId: plain, spaceId }), false);
  assert.equal(await isWikiMaintenanceSession(h.prisma, { ownerId: owner.id, sessionId: taskSession, spaceId }), false);
  assert.equal(await isWikiMaintenanceSession(h.prisma, { ownerId: owner.id, sessionId: run, spaceId: secondSpace }), false);

  const ok = await call(h, { runner: machine.token, session: run }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  expectStatus(ok, 200, 'a maintenance run reads its space\'s dossiers');
  for (const [who, sessionId] of [['a plain session', plain], ['a task outside the list', taskSession]] as const) {
    const read = await call(h, { runner: machine.token, session: sessionId }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
    expectStatus(read, 403, `${who} reads no dossier`);
    assert.equal(read.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
    const move = await call(h, { runner: machine.token, session: sessionId }, 'POST', `/runner/wiki/spaces/${spaceId}/cursor`, { to: ok.body.cursor });
    expectStatus(move, 403, `${who} moves no cursor`);
    assert.equal(move.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
  }
  const elsewhere = await call(h, { runner: machine.token, session: run }, 'GET', `/runner/wiki/spaces/${secondSpace}/dossiers`);
  expectStatus(elsewhere, 403, 'a maintenance run of one space reads nothing of another');
  const headless = await call(h, { runner: machine.token }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  expectStatus(headless, 400, 'a headless call has no session to be a maintenance run');

  // Another tenant: their runner, their own maintenance run, our space — and our session on their runner.
  const tenant = await account(h, 'tenant');
  const theirs = await runner(h, tenant.id);
  const theirWorkspace = await workspace(h, tenant.id);
  const theirSpace = await space(h, tenant, theirWorkspace);
  const theirList = await maintained(h, tenant, theirSpace, theirWorkspace);
  const theirRun = await maintenanceRun(h, tenant.id, theirList, theirWorkspace, theirs.id);
  const across = await call(h, { runner: theirs.token, session: theirRun }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  expectStatus(across, 404, "another owner's space is a plain 404");
  const acrossMove = await call(h, { runner: theirs.token, session: theirRun }, 'POST', `/runner/wiki/spaces/${spaceId}/cursor`, { to: ok.body.cursor });
  expectStatus(acrossMove, 404, "and its cursor is as absent");
  const borrowed = await call(h, { runner: theirs.token, session: run }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  expectStatus(borrowed, 403, 'a session their runner does not host is nobody here');
  assert.equal(await isWikiMaintenanceSession(h.prisma, { ownerId: tenant.id, sessionId: run, spaceId }), false);
  const theirsOk = await call(h, { runner: theirs.token, session: theirRun }, 'GET', `/runner/wiki/spaces/${theirSpace}/dossiers`);
  expectStatus(theirsOk, 200, 'their own run reads their own space');
  assert.equal(theirsOk.body.dossiers.length, 0, 'and finds nothing of ours in it');
});

// ── 5. each of the five facts adds one to the backlog ────────────────────────────────────────────

test('each committed fact — settled session, settled task, answered approval, merge receipt, revised criterion — adds one', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const repo = `https://github.com/orbit-dossier-spec/${randomUUID()}`;
  const spaceId = await space(h, owner, ws, repo);
  const listId = await maintained(h, owner, spaceId, ws);
  const run = await maintenanceRun(h, owner.id, listId, ws, machine.id);

  const backlog = async () => h.maintenance.cursorState(owner.id, spaceId);
  let state = await backlog();
  assert.equal(state.backlog, 0, 'a space with no facts has no backlog');
  assert.equal(state.lagSeconds, 0);

  const expectOneMore = async (kind: string, why: string) => {
    const before = state;
    state = await backlog();
    assert.equal(state.backlog, before.backlog + 1, `${why} adds exactly one: ${JSON.stringify(state.byKind)}`);
    assert.equal(state.byKind[kind as keyof typeof state.byKind], before.byKind[kind as keyof typeof state.byKind] + 1, `${why} is a ${kind}`);
  };

  const talk = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'AWAITING_INPUT', lastTurnAt: minutesAgo(40) });
  await expectOneMore('session_settled', 'a session come to rest');
  await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'RUNNING', lastTurnAt: minutesAgo(39) });
  assert.equal((await backlog()).backlog, state.backlog, 'a session still running has not settled');

  // DONE is the completion fence's to write (TASK_DONE_CANONICAL_FACT_REQUIRED); CANCELLED settles as well.
  await task(h, owner.id, { status: 'CANCELLED', assigneeId: ws, updatedAt: minutesAgo(35) });
  await expectOneMore('task_terminal', 'a task settled');
  await task(h, owner.id, { status: 'OPEN', assigneeId: ws });
  assert.equal((await backlog()).backlog, state.backlog, 'an open task is no fact');

  await approval(h, talk, {
    tool: 'AskUserQuestion', status: 'ALLOWED', decidedBy: owner.id,
    input: { questions: [{ question: 'Which budget?', options: [{ label: '8k' }, { label: '16k' }] }] },
    answers: { 'Which budget?': '8k' },
  });
  await expectOneMore('approval_answered', 'an answered question');
  await approval(h, talk, { tool: 'Bash', status: 'ALLOWED', input: { command: 'ls' }, decidedBy: owner.id });
  assert.equal((await backlog()).backlog, state.backlog, 'a bare Bash allow carries nothing to learn, and is no fact');

  await receipt(h, owner.id, talk);
  await expectOneMore('merge_receipt', 'a merge receipt');

  await criterion(h, await project(h, owner.id, repo), 1);
  await expectOneMore('criterion_revised', "a criterion of a project on the space's repository");
  await criterion(h, await project(h, owner.id, 'https://github.com/somebody-else/other'), 1);
  assert.equal((await backlog()).backlog, state.backlog, "another repository's criterion is not this space's");

  // A maintenance run feeds nothing to its own backlog: its session, its task and its receipt.
  await h.sql.query(`UPDATE "session" SET "status" = 'AWAITING_INPUT', "last_turn_at" = $2 WHERE "id" = $1`, [run, utc(minutesAgo(5))]);
  await receipt(h, owner.id, run, minutesAgo(5));
  await h.sql.query(`UPDATE "task" SET "status" = 'CANCELLED', "updated_at" = $2 WHERE "list_id" = $1`, [listId, utc(minutesAgo(5))]);
  assert.equal((await backlog()).backlog, state.backlog, 'nothing of the maintenance run is a fact');

  assert.equal(state.backlog, 5);
  assert.equal(state.pendingSessions, 1, 'the session, its approval and its receipt name one session');
  assert.ok(state.oldestPendingAt && new Date(state.oldestPendingAt).getTime() <= minutesAgo(39).getTime());
  assert.ok((state.lagSeconds ?? 0) >= 39 * 60, 'the lag is how long the oldest fact has waited');
  assert.deepEqual(state.due, { backlog: false, age: false }, 'five facts, the oldest forty minutes old: not due');
  const row = await h.sql.query<{ backlog: number; pending_sessions: number }>(
    `SELECT "backlog", "pending_sessions" FROM "wiki_cursor" WHERE "space_id" = $1`, [spaceId]);
  assert.deepEqual(row.rows[0], { backlog: 5, pending_sessions: 1 }, 'the count is written back for the status line to read');

  // A fact from a day and a half ago makes it due by age; twenty make it due by count.
  await session(h, owner.id, { workspaceId: ws, status: 'SUCCEEDED', lastTurnAt: minutesAgo(36 * 60) });
  assert.equal((await backlog()).due.age, true, 'the oldest fact is older than 24 hours');
  for (let n = 0; n < 15; n += 1) await session(h, owner.id, { workspaceId: ws, status: 'CANCELLED', lastTurnAt: minutesAgo(30) });
  const facts = await backlog();
  assert.equal(facts.backlog, 21);
  // The threshold counts SESSIONS (design §8.2: «20 个会话», criterion 3): 21 facts of 17 sessions are not due by count.
  assert.equal(facts.pendingSessions, 17);
  assert.equal(facts.due.backlog, false, 'twenty facts are not twenty sessions');
  for (let n = 0; n < 3; n += 1) await session(h, owner.id, { workspaceId: ws, status: 'CANCELLED', lastTurnAt: minutesAgo(30) });
  const full = await backlog();
  assert.equal(full.pendingSessions, WIKI_MAINTENANCE_RULES.backlogThreshold);
  assert.equal(full.due.backlog, true, `${WIKI_MAINTENANCE_RULES.backlogThreshold} sessions make a run due`);
});

// ── 6. forward only, and only for a run that succeeded ───────────────────────────────────────────

test('the cursor only moves forward, and a failed or truncated run does not move it', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const spaceId = await space(h, owner, ws);
  const listId = await maintained(h, owner, spaceId, ws);
  const run = await maintenanceRun(h, owner.id, listId, ws, machine.id);
  const as = { runner: machine.token, session: run };
  const page = () => call(h, as, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  const advance = (body: Record<string, unknown>) => call(h, as, 'POST', `/runner/wiki/spaces/${spaceId}/cursor`, body);

  for (let n = 0; n < 3; n += 1) {
    const talk = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, lastTurnAt: minutesAgo(30 - n) });
    await turn(h, talk, `The owner asks for thing ${n}.`);
  }
  // A fact inside the grace is counted in the backlog and left for a later page.
  await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, lastTurnAt: new Date() });

  const first = await page();
  expectStatus(first, 200, 'the run reads its first page');
  assert.equal(first.body.dossiers.length, 3, 'one dossier per settled session past the grace');
  assert.equal(first.body.facts, 3);
  assert.equal(first.body.more, false);
  assert.equal(first.body.state.backlog, 4, 'the backlog counts every fact after the watermark, however recent');
  const t1 = first.body.cursor as string;
  // Where turning maintenance on started it (fourteen days back, by default): a page moves no watermark.
  const start = first.body.state.position as string;
  assert.ok(start, 'the cursor starts where turning maintenance on put it');

  const failed = await advance({ to: t1, outcome: 'failed', error: 'the model endpoint answered 500; POSTGRES_PASSWORD=hunter2-dossier-spec' });
  expectStatus(failed, 200, 'a failed run is recorded');
  assert.equal(failed.body.advanced, false);
  assert.equal(failed.body.state.position, start, 'a failed run moves nothing');
  assert.equal(failed.body.state.consecutiveFailures, 1);
  assert.equal(failed.body.state.lastOutcome, 'failed');
  assert.doesNotMatch(failed.body.state.lastError, /hunter2/, 'the error is redacted before it is kept');
  const truncated = await advance({ to: t1, outcome: 'truncated' });
  expectStatus(truncated, 200, 'a truncated run is recorded');
  assert.equal(truncated.body.advanced, false);
  assert.equal(truncated.body.state.position, start, 'a truncated run moves nothing');
  assert.equal(truncated.body.state.consecutiveFailures, 2);
  assert.equal(truncated.body.state.backlog, 4);
  const noToken = await advance({ outcome: 'failed', error: 'died before its first page' });
  expectStatus(noToken, 200, 'a run that failed before reading a page is counted too');
  assert.equal(noToken.body.state.consecutiveFailures, 3);

  const moved = await advance({ to: t1 });
  expectStatus(moved, 200, 'a succeeded run moves the cursor');
  assert.equal(moved.body.advanced, true);
  assert.equal(moved.body.state.position, t1);
  assert.equal(moved.body.state.backlog, 1, 'what the page covered is behind the watermark now; the recent fact is not');
  assert.equal(moved.body.state.consecutiveFailures, 0);
  assert.ok(moved.body.state.lastOkAt);
  const replay = await advance({ to: t1 });
  expectStatus(replay, 200, 'the same advance again is a success that moves nothing');
  assert.equal(replay.body.advanced, false);
  assert.equal(replay.body.state.position, t1);

  // The recent fact ages past the grace, and a second page covers it and one more.
  await h.sql.query(`UPDATE "session" SET "last_turn_at" = $2 WHERE "id" IN (
      SELECT "id" FROM "session" WHERE "workspace_id" = $1 AND "last_turn_at" > now() - interval '1 minute' AND "task_id" IS NULL)`,
  [ws, utc(minutesAgo(10))]);
  await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, lastTurnAt: minutesAgo(9) });
  const second = await page();
  expectStatus(second, 200, 'the run reads its next page');
  assert.equal(second.body.dossiers.length, 2, 'only the facts after the watermark');
  const t2 = second.body.cursor as string;
  assert.notEqual(t2, t1);
  const forward = await advance({ to: t2 });
  expectStatus(forward, 200, 'the cursor moves on to the second page');
  assert.equal(forward.body.advanced, true);
  assert.equal(forward.body.state.backlog, 0);

  const back = await advance({ to: t1 });
  expectStatus(back, 409, 'a token behind the watermark moves nothing');
  assert.equal(back.body.code, 'WIKI_CURSOR_BEHIND');
  assert.equal(back.body.state.position, t2, 'the answer says where the cursor stands');
  const stillThere = await h.maintenance.cursorState(owner.id, spaceId);
  assert.equal(stillThere.position, t2, 'and it stands where it was');

  // A token no page of this space handed out is none: past the furthest issue, another space's, noise.
  const decoded = JSON.parse(Buffer.from(t2.slice('wc1.'.length), 'base64url').toString('utf8')) as { s: string; p: [string, string, string] };
  const ahead = `wc1.${Buffer.from(JSON.stringify({ s: decoded.s, p: [new Date(Date.now() + 86_400_000).toISOString(), 'session_settled', randomUUID()] })).toString('base64url')}`;
  const forged = await advance({ to: ahead });
  expectStatus(forged, 400, 'a position no page handed out');
  assert.equal(forged.body.code, 'WIKI_CURSOR_INVALID');
  const foreign = `wc1.${Buffer.from(JSON.stringify({ s: randomUUID(), p: decoded.p })).toString('base64url')}`;
  expectStatus(await advance({ to: foreign }), 400, "another space's token");
  expectStatus(await advance({ to: 'not-a-token' }), 400, 'noise');
  expectStatus(await advance({}), 400, 'a succeeded run names where it got to');
  assert.equal((await h.maintenance.cursorState(owner.id, spaceId)).position, t2, 'none of them moved it');

  // A page asked to start after the watermark is empty, and its token is where it started.
  const empty = await call(h, as, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers?after=${encodeURIComponent(t2)}`);
  expectStatus(empty, 200, 'a page past everything');
  assert.equal(empty.body.dossiers.length, 0);
  assert.equal(empty.body.cursor, t2);
  expectStatus(await call(h, as, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers?limit=0`), 400, 'a page of no sessions');
});

// ── 1, 2, 3. the dossier: deterministic, redacted first, cut to 8k ──────────────────────────────

/**
 * Every shape the shared redactor names, and the secret each one hides. `value` is what must never
 * appear; `text` is how it is written in the record.
 */
function seededSecrets(literal: string): Array<{ text: string; value: string }> {
  const r = () => randomUUID().replace(/-/g, '');
  const pemBody = `MIIEowIBAAKCAQEA${r()}${r()}`;
  const list: Array<{ text: string; value: string }> = [];
  const push = (text: string, value: string) => list.push({ text, value });
  push(`-----BEGIN RSA PRIVATE KEY-----\n${pemBody}\n-----END RSA PRIVATE KEY-----`, pemBody);
  const openssh = `b3BlbnNzaC1rZXktdjEAAAAA${r()}`;
  push(`-----BEGIN OPENSSH PRIVATE KEY-----\n${openssh}\n-----END OPENSSH PRIVATE KEY-----`, openssh);
  const ec = `MHcCAQEEI${r()}`;
  push(`-----BEGIN EC PRIVATE KEY-----\n${ec}\n-----END EC PRIVATE KEY-----`, ec);
  const cut = `MIIBVAIBADANBgkqhkiG9w0${r()}`;
  push(`-----BEGIN PRIVATE KEY-----\n${cut}`, cut);
  const pg = `pgpw${r()}`;
  push(`postgres://orbit:${pg}@db:5432/orbit`, pg);
  const redis = `rpw${r()}`;
  push(`redis://:${redis}@cache:6379`, redis);
  const gitCred = `ghcred${r()}`;
  push(`https://jane:${gitCred}@github.com/a/b.git`, gitCred);
  const bearer = `bt${r()}${r()}`;
  push(`Authorization: Bearer ${bearer}`, bearer);
  const shortBearer = `Ab3${r().slice(0, 10)}`;
  push(`bearer ${shortBearer}`, shortBearer);
  const basic = Buffer.from(`jane:${r()}`).toString('base64');
  push(`Authorization: Basic ${basic}`, basic);
  const jwt = `eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI${r()}.${r()}`;
  push(`token was ${jwt} for a minute`, jwt);
  const ant = `sk-ant-api03-${r()}${r()}`;
  push(`the key ${ant}`, ant);
  const proj = `sk-proj-${r()}${r()}`;
  push(`OPENAI said ${proj}`, proj);
  const pk = `pk-${r()}`;
  push(`public-ish ${pk}`, pk);
  const rk = `rk-${r()}`;
  push(`restricted ${rk}`, rk);
  const stripeLive = `sk_live_${r()}`;
  push(`stripe ${stripeLive}`, stripeLive);
  const stripeTest = `sk_test_${r()}`;
  push(`stripe test ${stripeTest}`, stripeTest);
  for (const prefix of ['ghp_', 'gho_', 'ghu_', 'ghs_', 'ghr_']) {
    const value = `${prefix}${r()}${r().slice(0, 4)}`;
    push(`github says ${value}`, value);
  }
  const pat = `github_pat_${r()}${r()}`;
  push(`fine-grained ${pat}`, pat);
  const akia = `AKIA${r().toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 16)}`;
  push(`aws ${akia} in the log`, akia);
  const asia = `ASIA${r().toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 16)}`;
  push(`sts ${asia} again`, asia);
  for (const prefix of ['xoxb-', 'xoxp-', 'xoxa-']) {
    const value = `${prefix}${r()}`;
    push(`slack ${value}`, value);
  }
  const google = `AIza${r()}${r().slice(0, 8)}`;
  push(`maps ${google}`, google);
  const gitlab = `glpat-${r()}`;
  push(`gitlab ${gitlab}`, gitlab);
  const npm = `npm_${r()}${r().slice(0, 4)}`;
  push(`registry ${npm}`, npm);
  const named: Array<[string, string]> = [
    ['POSTGRES_PASSWORD=', ''],
    ['ANTHROPIC_API_KEY=', ''],
    ['ORBIT_RUNNER_TOKEN=', ''],
    ['x-api-key: ', ''],
    ['"clientSecret": "', '"'],
    ['password := "', '"'],
    ["api_key => '", "'"],
    ['access_key=', ''],
    ['private_key: ', ''],
    ['SECRET_KEY=', ''],
    ['DB_PASSWD=', ''],
    ['pwd=', ''],
    ['token: ', ''],
    ['AUTH_TOKEN="', '"'],
    ['aws_secret_access_key = ', ''],
    ['PASSWORD: ', ''],
    ['https://example.invalid/login?password=', ''],
    ['GITHUB_TOKEN=', ''],
    ['--token=', ''],
    ['NPM_TOKEN: ', ''],
    ['sessionSecret=', ''],
  ];
  for (const [before, after] of named) {
    const value = `v${r()}`;
    push(`${before}${value}${after}`, value);
  }
  push(`the literal ${literal} as it is`, literal);
  return list;
}

test('a dossier is the same twice, carries no secret, keeps the agent\'s trace, and is cut to 8k', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const literal = `envval-${randomUUID()}`;
  const ws = await workspace(h, owner.id, { DEPLOY_HOOK: literal });
  const spaceId = await space(h, owner, ws);
  const listId = await maintained(h, owner, spaceId, ws);
  const run = await maintenanceRun(h, owner.id, listId, ws, machine.id);
  const secrets = seededSecrets(literal);
  assert.ok(secrets.length >= 50, `seed ${secrets.length} shapes, at least fifty`);

  const work = await task(h, owner.id, {
    title: `Cut the dossier ${secrets[0]!.text}`,
    status: 'FAILED',
    assigneeId: ws,
    acceptance: `The spec passes. ${secrets[1]!.text}`,
  });
  const talk = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, taskId: work, status: 'SUCCEEDED', lastTurnAt: minutesAgo(20) });
  const opening = await turn(h, talk, 'Build the dossier.\n\n请按以下步骤进行：\n1. read\n2. write', { clientTurnId: `initial-${randomUUID()}`, sendIntent: null, at: minutesAgo(59) });
  // Every seed in an owner message: always carried, so a seed that survived would be in the text.
  const owned: string[] = [];
  for (const [index, secret] of secrets.slice(2).entries()) {
    owned.push(await turn(h, talk, `seed ${String(index).padStart(2, '0')} · do not keep this: ${secret.text}`, { at: new Date(minutesAgo(58).getTime() + index * 1000) }));
  }
  await turn(h, talk, 'Stop — never push tags from a session.', { kind: 'steer', sendIntent: null, clientTurnId: randomUUID().toUpperCase(), at: minutesAgo(40) });
  await event(h, talk, 'assistant', { text: 'I will read the packer first, then write the extraction.' }, minutesAgo(46));
  await event(h, talk, 'thinking', {
    text: 'Planning the next step carefully. It turns out release.sh next is not a dry run: it tags and pushes. Moving on.',
  }, minutesAgo(45));
  const failing = await tool(h, talk, 'Bash', { command: 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-dossier.pg.spec.ts' },
    'Exit code 1\nrun-pg-spec: a skip is red', { isError: true, at: minutesAgo(44) });
  const fixed = await tool(h, talk, 'Bash', { command: 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-dossier.pg.spec.ts' },
    '# pass 7\n# fail 0', { at: minutesAgo(43) });
  const memoryPath = '/root/.claude/projects/-root-orbit/memory/release-script-next-tags-immediately.md';
  const memory = await tool(h, talk, 'Read', { file_path: memoryPath }, 'release.sh next tags at once', { at: minutesAgo(42) });
  const memoryWrite = await tool(h, talk, 'Write', { file_path: '/root/.claude/projects/-root-orbit/memory/MEMORY.md', content: 'x' }, 'ok', { at: minutesAgo(42) });
  await event(h, talk, 'assistant', {
    text: 'Root cause found: the packer counted the header twice. Fixed it in src/apiserver/src/wiki/wiki-dossier.ts and the spec is green now; the dossier stays under the budget.',
  }, minutesAgo(41));
  const asked = await approval(h, talk, {
    tool: 'AskUserQuestion', status: 'ALLOWED', decidedBy: owner.id,
    input: { questions: [{ question: 'Which budget should a dossier get?', options: [{ label: '8k (Recommended)' }, { label: '16k' }] }] },
    answers: { 'Which budget should a dossier get?': '8k (Recommended)' },
  });
  const denied = await approval(h, talk, {
    tool: 'Bash', status: 'DENIED', input: { command: 'git push --tags' }, decidedBy: owner.id,
    message: 'No tags from a session: releases are the owner\'s.',
  });
  const plan = await approval(h, talk, { tool: 'ExitPlanMode', status: 'ALLOWED', input: { plan: 'Port pack.py to TypeScript.' }, decidedBy: owner.id });
  const tail = await comment(h, work, 'AGENT', owner.id, 'Delivered.\n\n结论：8k 的案卷召回更高。', minutesAgo(16));
  const ownerNote = await comment(h, work, 'USER', owner.id, 'Looks right to me.', minutesAgo(15));
  const merged = await receipt(h, owner.id, talk, minutesAgo(15));
  const decision = await blocker(h, await project(h, owner.id), work, 'Accepted: the extra files belong to the same change.');

  // 1. The same records, twice: byte for byte, hash for hash.
  const records = await loadDossierRecords(h.prisma, owner.id, talk);
  assert.ok(records, 'the session is the owner\'s');
  const once = await buildDossier(h.prisma, records, { literals: [literal] });
  const twice = await buildDossier(h.prisma, (await loadDossierRecords(h.prisma, owner.id, talk))!, { literals: [literal] });
  assert.equal(twice.text, once.text, 'the same records give the same text');
  assert.equal(twice.hash, once.hash, 'and the same hash');
  assert.deepEqual(twice.sources, once.sources);

  const first = await call(h, { runner: machine.token, session: run }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  expectStatus(first, 200, 'the maintenance run reads the page');
  const dossier = (first.body.dossiers as Array<{ sessionId: string; text: string; hash: string; tokens: number; truncated: boolean; unchanged: boolean; sources: Array<{ ref: string; kind: string; id: string; spans: WikiDossierSpan[] }> }>)
    .find((one) => toUuid(one.sessionId) === talk);
  assert.ok(dossier, 'the settled session has its dossier on the page');
  assert.equal(dossier.hash, once.hash, 'the door hands out the very dossier the function makes');
  assert.equal(dossier.text, once.text);
  assert.equal(dossier.unchanged, false, 'never handed out before');

  // 2. No seed survives, in lines the dossier provably carries.
  for (const index of secrets.slice(2).keys()) {
    assert.match(dossier.text, new RegExp(`seed ${String(index).padStart(2, '0')} · do not keep this`), `the line of seed ${index} is carried`);
  }
  assert.match(dossier.text, /TASK: Cut the dossier/, 'the header carries the task');
  assert.match(dossier.text, /ACCEPTANCE: The spec passes\./, 'and its acceptance criteria');
  for (const secret of secrets) {
    assert.ok(!dossier.text.includes(secret.value), `a seeded secret leaked: ${secret.text.slice(0, 60)}`);
  }
  assert.ok(dossier.text.includes('[redacted]'));

  // What the dossier carries, and cites. The door serves every id in its public spelling.
  const sources = dossier.sources.map((source) => ({ ref: source.ref, kind: source.kind, id: toUuid(source.id), spans: source.spans }));
  assert.deepEqual(sources, once.sources, 'the door hands out the sources the function made');
  const cited = new Map(sources.map((source) => [source.id, source.kind]));
  for (const [id, kind] of [
    [opening, 'turn'], [owned[0]!, 'turn'], [asked, 'approval'], [denied, 'approval'], [plan, 'approval'],
    [failing.toolCallId, 'tool_call'], [fixed.toolCallId, 'tool_call'], [tail, 'task_comment'], [ownerNote, 'task_comment'],
    [merged.id, 'merge_receipt'], [decision, 'owner_decision'],
  ] as const) {
    assert.equal(cited.get(id), kind, `${kind} ${id} is a line of the dossier and cites its record`);
  }
  assert.match(dossier.text, /not a dry run/, 'the thought that carries the surprise is kept…');
  assert.doesNotMatch(dossier.text, /Planning the next step carefully/, '…and the rest of the thought is not');
  assert.match(dossier.text, /\$ bash scripts\/run-pg-spec\.sh .* → ERR: Exit code 1/, 'the failed command and its error line');
  assert.match(dossier.text, /→ ok: # pass 7/, 'and the success that fixed it');
  assert.match(dossier.text, /Which budget should a dossier get\? .*→ A: "8k \(Recommended\)"/, 'the question and its answer');
  assert.match(dossier.text, /Bash denied .*No tags from a session/, 'a denial with its reason');
  assert.match(dossier.text, /PLAN: Port pack\.py to TypeScript\./, 'the plan');
  assert.match(dossier.text, /\(steer\) Stop — never push tags from a session\./, 'the steer');
  assert.match(dossier.text, new RegExp(`MERGED orbit/dossier-spec@${merged.sourceSha} → main@${merged.targetSha}`), 'the receipt with its shas');
  assert.match(dossier.text, /the owner resolved it: Accepted: the extra files belong/, "the owner's resolution");
  assert.doesNotMatch(dossier.text, /请按以下步骤进行/, 'the task boilerplate is cut from the opening prompt');
  assert.ok(!dossier.text.includes('memory/release-script-next-tags-immediately.md'), 'a memory-file read is left out');
  assert.ok(!dossier.text.includes('MEMORY.md'), 'and so is a memory-file write');
  assert.ok(!cited.has(memory.toolCallId) && !cited.has(memory.useEventId) && !cited.has(memoryWrite.toolCallId), 'and cited by nothing');
  assert.ok(dossier.tokens <= WIKI_MAINTENANCE_RULES.dossierMaxTokens);
  assert.equal(dossier.tokens, wikiEstimateTokens(dossier.text));

  // The lines cite records a proposal can name: the receipt and the owner's decision resolve, and a
  // quote taken from the dossier's receipt line is found in the receipt.
  const proposer: WikiPrincipal = { origin: 'agent', ownerId: owner.id, userId: null, sessionId: run, toolCallId: null };
  const checked = await h.service.submitChangeset(proposer, spaceId, {
    dryRun: true,
    idempotencyKey: `dossier-dry-${randomUUID()}`,
    rationale: 'cite what the dossier cites',
    ops: [{
      op: 'add',
      entry: {
        kind: 'pitfall',
        title: 'A merge receipt names both shas',
        summary: 'The dossier carries a merge receipt with the source and the target sha.',
        fields: {
          trigger: { paths: ['src/apiserver/src/wiki/'], commands: ['git merge --no-ff origin/main'] },
          symptom: 'The receipt reads MERGED.',
          cause: 'The branch landed.',
          fix: 'Read the target sha.',
        },
      },
      sources: [
        { kind: 'merge_receipt', ref: merged.id, quote: `orbit/dossier-spec@${merged.sourceSha}` },
        { kind: 'owner_decision', ref: decision, quote: 'the extra files belong to the same change' },
      ],
    }],
  }) as { ops: Array<{ status: string; reasons?: Array<{ code: string }> }> };
  assert.notEqual(checked.ops[0]!.status, 'refused', `the dossier's records resolve: ${JSON.stringify(checked.ops[0])}`);

  // What is kept: the sources and the hash, and no text anywhere.
  const kept = await h.sql.query<{ hash: string; source_ids: unknown; tokens: number }>(
    `SELECT "hash", "source_ids", "tokens" FROM "wiki_dossier" WHERE "space_id" = $1 AND "session_id" = $2`, [spaceId, talk]);
  assert.equal(kept.rowCount, 1);
  assert.equal(kept.rows[0]!.hash, dossier.hash);
  assert.deepEqual(kept.rows[0]!.source_ids, storedDossierSources(once.sources), 'each line\'s record and where its spans are');
  assert.ok(once.sources.every((source) => source.spans.length > 0), 'and every line has them');
  const columns = await h.sql.query<{ column_name: string }>(
    `SELECT column_name FROM information_schema.columns WHERE table_name = 'wiki_dossier' ORDER BY column_name`);
  assert.deepEqual(columns.rows.map((row) => row.column_name).sort(), [
    'hash', 'id', 'issued_at', 'owner_id', 'page_at', 'page_kind', 'page_ref', 'session_id', 'source_ids', 'space_id', 'tokens', 'truncated',
  ], 'no column holds a dossier\'s text');
  assert.equal((await h.sql.query(`SELECT 1 FROM "wiki_dossier" WHERE "source_ids"::text LIKE '%do not keep this%'`)).rowCount, 0);

  // Once the cursor has advanced past it, the same dossier is marked unchanged.
  expectStatus(await call(h, { runner: machine.token, session: run }, 'POST', `/runner/wiki/spaces/${spaceId}/cursor`, { to: first.body.cursor }), 200, 'advance');
  await h.sql.query(`UPDATE "session" SET "last_turn_at" = $2 WHERE "id" = $1`, [talk, utc(minutesAgo(8))]);
  const again = await call(h, { runner: machine.token, session: run }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  expectStatus(again, 200, 'the session comes to rest again');
  const same = (again.body.dossiers as Array<{ sessionId: string; hash: string; unchanged: boolean }>).find((one) => toUuid(one.sessionId) === talk);
  assert.equal(same?.hash, dossier.hash, 'nothing it is made of changed');
  assert.equal(same?.unchanged, true, 'so the run can skip it');

  // 3. A session past 8,000 tokens is cut to it, and says so; a short one is whole.
  const long = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'AWAITING_INPUT', lastTurnAt: minutesAgo(7) });
  for (let n = 0; n < 60; n += 1) {
    await turn(h, long, `Owner message ${n}: always keep the budget at 8k. ${'lorem ipsum dolor sit amet '.repeat(40)}`, { at: new Date(minutesAgo(58).getTime() + n * 2000) });
    await event(h, long, 'assistant', { text: `Reply ${n}: actually the reason is subtle. ${'consectetur adipiscing elit '.repeat(60)}` }, new Date(minutesAgo(58).getTime() + n * 2000 + 1000));
  }
  const short = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'AWAITING_INPUT', lastTurnAt: minutesAgo(7) });
  await turn(h, short, 'One small thing.');
  await event(h, short, 'assistant', { text: 'Done.' }, minutesAgo(50));
  const cutPage = await call(h, { runner: machine.token, session: run }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  expectStatus(cutPage, 200, 'the page with the long session');
  const byId = new Map((cutPage.body.dossiers as Array<{ sessionId: string; text: string; tokens: number; truncated: boolean }>).map((one) => [toUuid(one.sessionId), one]));
  const longOne = byId.get(long)!;
  assert.ok(longOne, 'the long session has its dossier');
  const whole = 60 * 2 * 400;
  assert.ok(whole > WIKI_MAINTENANCE_RULES.dossierMaxTokens, 'the timeline is far past the budget');
  assert.equal(longOne.truncated, true, 'the long session is cut, and says it was');
  assert.ok(wikiEstimateTokens(longOne.text) <= WIKI_MAINTENANCE_RULES.dossierMaxTokens, `cut to 8k: ${longOne.tokens}`);
  assert.equal(longOne.tokens, wikiEstimateTokens(longOne.text));
  assert.match(longOne.text, /lines omitted/, 'with the gaps marked');
  assert.equal(byId.get(short)!.truncated, false, 'a short session is whole');
  const smaller = await buildDossier(h.prisma, (await loadDossierRecords(h.prisma, owner.id, long))!, { literals: [], maxTokens: 1_000 });
  assert.ok(wikiEstimateTokens(smaller.text) <= 1_000, 'the cut holds at any budget');
});

// ── 7. every line goes back to its record, word for word ───────────────────────────────────────

interface Placed {
  ref: string;
  kind: WikiSourceKind;
  id: string;
  spans: WikiDossierSpan[];
}

test('every line goes back to its record: the words at its spans, redacted, are the words it declares — compressed lines too', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const literal = `envval-${randomUUID()}`;
  const ws = await workspace(h, owner.id, { DEPLOY_HOOK: literal });
  const spaceId = await space(h, owner, ws);
  const listId = await maintained(h, owner, spaceId, ws);
  const run = await maintenanceRun(h, owner.id, listId, ws, machine.id);
  // A token the redactor takes out wherever it stands: the positions count in the text as redacted, so a
  // secret before a line's words moves them, and the spans must say where they are after it.
  const token = `ghp_${randomUUID().replace(/-/g, '')}Ab12`;
  const at = (minutes: number, seconds = 0) => new Date(minutesAgo(minutes).getTime() + seconds * 1000);

  const work = await task(h, owner.id, { title: 'Place every line', status: 'FAILED', assigneeId: ws, acceptance: 'Every line has its place.' });
  const talk = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, taskId: work, status: 'SUCCEEDED', lastTurnAt: minutesAgo(20) });
  const prompt = 'Place every line of the dossier 🎯.\n\nPositions count in code points, not in UTF-16 units.\n\n请按以下步骤进行：\n1. read\n2. write';
  const opening = await turn(h, talk, prompt, { clientTurnId: `initial-${randomUUID()}`, sendIntent: null, at: at(59) });
  const retried = await turn(h, talk, prompt, { clientTurnId: `initial-${randomUUID()}`, sendIntent: null, at: at(58) });
  const long = await turn(h, talk, `Keep 🎯 the budget at 8k, never 16k: ${token} ${literal} ${'the reason is recall, measured. '.repeat(220)}`, { at: at(57) });
  const steer = await turn(h, talk, 'Stop — never push tags from a session.', { kind: 'steer', sendIntent: null, clientTurnId: randomUUID().toUpperCase(), at: at(56) });
  const silent = await turn(h, talk, '', { kind: 'interrupt', sendIntent: null, clientTurnId: randomUUID().toUpperCase(), at: at(55) });
  const shell = await turn(h, talk, 'git log --oneline -3', { kind: 'shell', sendIntent: null, at: at(54) });
  const reply = await event(h, talk, 'assistant', {
    text: 'I read the packer first. See /root/.claude/projects/-root-orbit/memory/packer.md for the old notes. The root cause is that the header was counted twice.',
  }, at(53));
  const thought = await event(h, talk, 'thinking', {
    text: 'Planning the next step carefully. It turns out release.sh next is not a dry run. Moving on to the spec. Actually the tag is pushed at once.',
  }, at(52));
  const command = 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-dossier.pg.spec.ts \\\n  --verbose';
  const failing = await tool(h, talk, 'Bash', { command, description: 'Run the dossier spec' },
    `Exit code 1\ntoken: ${token}\n${'x'.repeat(1500)}\nrun-pg-spec: a skip is red`, { isError: true, at: at(51) });
  const fixed = await tool(h, talk, 'Bash', { command, description: 'Run it again' }, '# pass 7\n# fail 0', { at: at(50) });
  const firstRead = await tool(h, talk, 'Read', { file_path: 'src/apiserver/src/wiki/wiki-dossier.ts' }, 'import { Prisma } …', { at: at(49) });
  await tool(h, talk, 'Read', { file_path: 'src/shared/src/wiki.ts', limit: 50 }, 'export const …', { at: at(49, 1) });
  await event(h, talk, 'assistant', { text: 'Both files read.' }, at(46));
  const mcp = await tool(h, talk, 'mcp__orbit__task_comment', { taskId: 'task-1', body: 'Delivered after git push origin HEAD.' }, [
    { type: 'text', text: 'Comment recorded.\nid 34Wabc' },
    { type: 'image', source: { type: 'base64', media_type: 'image/png', data: 'AAAA' } },
  ], { at: at(45) });
  // A call from before tool calls had rows: its line cites the tool_use event, whose text is the call alone.
  const bare = await event(h, talk, 'tool_use', { id: 'toolu_bare', name: 'Bash', input: { command: 'git status --short' } }, at(44));
  await event(h, talk, 'tool_result', { toolUseId: 'toolu_bare', content: ' M src/x.ts', isError: false }, at(44));
  await event(h, talk, 'assistant', { text: 'The tree has one change.' }, at(43));
  const background = await event(h, talk, 'background_task', {
    toolUseId: 'toolu_bg', shellId: 'bg-1', kind: 'bash', status: 'completed', exitCode: 0, command: 'git push origin HEAD', summary: 'Pushed to origin in 3s',
  }, at(42));
  const failure = await event(h, talk, 'error', { message: 'The engine stopped: overloaded' }, at(41));
  const ended = await event(h, talk, 'turn_end', { subtype: 'error_max_turns', numTurns: 120 }, at(40));
  await event(h, talk, 'assistant', { text: 'It turns out the engine was overloaded, so the turn ran out.' }, at(39));
  const asked = await approval(h, talk, {
    tool: 'AskUserQuestion', status: 'ALLOWED', decidedBy: owner.id,
    input: { questions: [{ question: 'Which unit do positions count in?', options: [{ label: 'Code points' }, { label: 'UTF-16 units' }] }] },
    answers: { 'Which unit do positions count in?': 'Code points' },
  });
  const plan = await approval(h, talk, { tool: 'ExitPlanMode', status: 'ALLOWED', input: { plan: 'Give every line its spans.' }, decidedBy: owner.id });
  const denied = await approval(h, talk, {
    tool: 'Bash', status: 'DENIED', input: { command: 'git push --tags' }, decidedBy: owner.id, message: 'No tags from a session.',
  });
  const delivered = await comment(h, work, 'AGENT', owner.id,
    'Delivered the positions.\n\nThe tests ran twice.\n\n结论：every line has its place, compressed ones too.', minutesAgo(16));
  const merged = await receipt(h, owner.id, talk, minutesAgo(15));
  const decision = await blocker(h, await project(h, owner.id), work, 'Accepted: spans count in code points.');

  const records = (await loadDossierRecords(h.prisma, owner.id, talk))!;
  const dossier = await buildDossier(h.prisma, records, { literals: [literal] });
  const again = await buildDossier(h.prisma, (await loadDossierRecords(h.prisma, owner.id, talk))!, { literals: [literal] });
  assert.deepEqual(again.sources, dossier.sources, 'the same records place every line the same way');
  assert.equal(again.hash, dossier.hash);

  // Every line: its record resolves among the owner's own, and the words at each of its spans — read from the
  // record as a quote of it is checked, then redacted — are the words it declares, in order, none overlapping.
  const reader: WikiPrincipal = { origin: 'agent', ownerId: owner.id, userId: null, sessionId: run, toolCallId: null };
  const recordWords = async (source: { kind: WikiSourceKind; id: string }): Promise<string[]> => {
    const found = await h.service.sourceText(h.prisma, reader, { kind: source.kind, ref: source.id });
    assert.ok(found, `${source.kind} ${source.id} is one of the owner's records`);
    return Array.from(redactSecrets(found.text ?? '', { literals: [literal] }).text);
  };
  const lineOf = new Map<string, string>();
  for (const line of dossier.text.split(/\n(?! {4})/u)) {
    const name = /^(L\d+) /u.exec(line);
    if (name) lineOf.set(name[1]!, line);
  }
  assert.ok(dossier.sources.length >= 20, `the session's lines are carried: ${dossier.sources.length}`);
  for (const source of dossier.sources) {
    assert.ok(source.spans.length > 0, `${source.ref} says where its words are`);
    const words = await recordWords(source);
    let end = 0;
    for (const span of source.spans) {
      assert.ok(span.start >= end && span.end >= span.start && span.end <= words.length,
        `${source.ref}: ${span.start}–${span.end} lies in its record of ${words.length} code points, after ${end}`);
      assert.equal(words.slice(span.start, span.end).join(''), span.text,
        `${source.ref} (${source.kind}): the record's words at ${span.start}–${span.end} are the words the line declares`);
      end = span.end;
    }
    assert.ok(!source.spans.some((span) => span.text.includes(token) || span.text.includes(literal)), `${source.ref} declares no secret`);
  }

  const bySource = (id: string, kind: string): Placed => {
    const found = dossier.sources.filter((source) => source.id === id && source.kind === kind);
    assert.equal(found.length, 1, `one line cites ${kind} ${id}`);
    return found[0]!;
  };
  const texts = (placed: Placed) => placed.spans.map((span) => span.text);

  // The compressed lines point at the pieces of the record they were cut from.
  const failed = bySource(failing.toolCallId, 'tool_call');
  assert.match(lineOf.get(failed.ref)!, /\$ bash scripts\/run-pg-spec\.sh .* …\(\+1 lines\) → ERR: Exit code 1 … run-pg-spec: a skip is red$/u);
  assert.deepEqual(texts(failed), [
    'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-dossier.pg.spec.ts \\', 'Exit code 1', 'run-pg-spec: a skip is red',
  ], 'a tool call: its command, and its result\'s first and last line — the last found after a secret the redactor shortened');
  assert.deepEqual(texts(bySource(fixed.toolCallId, 'tool_call')).slice(1), ['# pass 7'], 'a success: the command, then the line it printed');
  const thinking = bySource(thought, 'event');
  assert.equal(lineOf.get(thinking.ref), `${thinking.ref} think: It turns out release.sh next is not a dry run. … Actually the tag is pushed at once.`);
  assert.deepEqual(texts(thinking), ['It turns out release.sh next is not a dry run.', 'Actually the tag is pushed at once.'],
    'a thought: its signal sentences, each where it stands');
  assert.deepEqual(texts(bySource(reply, 'event')), ['I read the packer first. ', 'The root cause is that the header was counted twice.'],
    'a reply with its memory sentence cut out: the two pieces around it');
  const cut = bySource(long, 'turn');
  assert.match(lineOf.get(cut.ref)!, /…\[cut\]$/u, 'the long message is cut to its cap');
  assert.equal(cut.spans.length, 1);
  assert.equal(cut.spans[0]!.start, 0);
  assert.equal(cut.spans[0]!.end, 3_000, 'and its span is the part it kept, counted in code points');
  assert.match(cut.spans[0]!.text, /^Keep 🎯 the budget at 8k, never 16k: \[redacted\] \[redacted\] the reason/u);
  const opened = bySource(opening, 'turn');
  assert.deepEqual(texts(opened), ['Place every line of the dossier 🎯.\n\nPositions count in code points, not in UTF-16 units.'],
    'the opening prompt without the step list every task ends with');
  const repeated = bySource(retried, 'turn');
  assert.equal(lineOf.get(repeated.ref), `${repeated.ref} taskprompt: (the same opening prompt again)`);
  assert.deepEqual(texts(repeated), texts(opened), 'a repeated prompt points at the prompt it stands for');
  assert.deepEqual(texts(bySource(steer, 'turn')), ['Stop — never push tags from a session.']);
  assert.deepEqual(bySource(silent, 'turn').spans, [{ start: 0, end: 0, text: '' }], 'an interrupt with no words points at its record, which has none');
  assert.deepEqual(texts(bySource(shell, 'turn')), ['git log --oneline -3']);
  assert.deepEqual(texts(bySource(firstRead.toolCallId, 'tool_call')), ['src/apiserver/src/wiki/wiki-dossier.ts'],
    'two reads folded into one line: the path of the call it cites');
  assert.deepEqual(texts(bySource(mcp.toolCallId, 'tool_call')), ['mcp__orbit__task_comment', 'Comment recorded.'],
    'a tool of its own: its name, and the first line of its result\'s text blocks');
  assert.deepEqual(texts(bySource(bare, 'event')), ['git status --short'], 'a call with no row: the command in its tool_use event');
  assert.deepEqual(texts(bySource(background, 'event')), ['git push origin HEAD', 'Pushed to origin in 3s'], 'a background task: its command and its summary');
  assert.deepEqual(texts(bySource(failure, 'event')), ['The engine stopped: overloaded']);
  assert.deepEqual(texts(bySource(ended, 'event')), ['error_max_turns']);
  assert.deepEqual(texts(bySource(asked, 'approval')), ['Which unit do positions count in?', '"Code points"'],
    'a question and its answer, as the answers the approval holds have them');
  const planned = dossier.sources.filter((source) => source.id === plan);
  assert.deepEqual(planned.map(texts), [['Give every line its spans.'], ['Give every line its spans.']],
    'the plan, and the decision about it, which shows none of its words');
  assert.deepEqual(texts(bySource(denied, 'approval')), ['No tags from a session.']);
  assert.deepEqual(texts(bySource(delivered, 'task_comment')), ['Delivered the positions.', '结论：every line has its place, compressed ones too.'],
    'a comment: its first paragraph and its conclusion');
  assert.deepEqual(texts(bySource(merged.id, 'merge_receipt')), [`MERGED orbit/dossier-spec@${merged.sourceSha} → main@${merged.targetSha}`]);
  assert.deepEqual(texts(bySource(decision, 'owner_decision')), ['decide whether the extra files land', 'Accepted: spans count in code points.']);

  // The door hands the spans out with the words at them; the table keeps where they are and nothing they say.
  const page = await call(h, { runner: machine.token, session: run }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  expectStatus(page, 200, 'the maintenance run reads the page');
  const served = (page.body.dossiers as Array<{ sessionId: string; sources: Placed[] }>).find((one) => toUuid(one.sessionId) === talk)!;
  assert.deepEqual(served.sources.map(({ ref, kind, id, spans }) => ({ ref, kind, id: toUuid(id), spans })), dossier.sources,
    'the door serves every id in its public spelling, and the spans as they are');
  const kept = await h.sql.query<{ source_ids: unknown }>(`SELECT "source_ids" FROM "wiki_dossier" WHERE "space_id" = $1 AND "session_id" = $2`, [spaceId, talk]);
  assert.deepEqual(kept.rows[0]!.source_ids, storedDossierSources(dossier.sources));
  assert.equal((await h.sql.query(`SELECT 1 FROM "wiki_dossier" WHERE "session_id" = $1 AND "source_ids"::text LIKE '%release.sh next%'`, [talk])).rowCount, 0,
    'no span\'s words are stored');

  // A quote the spans declare is found in its record by the check every proposal meets; the dossier's own
  // shorthand for the same call is not.
  const quote = (text: string) => ({
    op: 'add',
    entry: {
      kind: 'pitfall',
      title: `A spec that skips is red ${randomUUID().slice(0, 8)}`,
      summary: 'run-pg-spec counts a skip as a failure.',
      fields: { trigger: { paths: ['scripts/run-pg-spec.sh'], commands: ['bash scripts/run-pg-spec.sh'] }, symptom: 'Exit code 1.', cause: 'A skip.', fix: 'Set the URL.' },
    },
    sources: [{ kind: 'tool_call', ref: failing.toolCallId, quote: text }],
  });
  const checked = await h.service.submitChangeset(reader, spaceId, {
    dryRun: true,
    idempotencyKey: `dossier-quotes-${randomUUID()}`,
    rationale: 'quote what the spans declare, and what the line says',
    ops: [quote(failed.spans[0]!.text), quote(failed.spans[2]!.text), quote('$ bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-dossier.pg.spec.ts \\ …(+1 lines) → ERR: Exit code 1')],
  }) as { ops: Array<{ status: string; reasons?: Array<{ code: string }> }> };
  assert.notEqual(checked.ops[0]!.status, 'refused', `the command, quoted from its span: ${JSON.stringify(checked.ops[0])}`);
  assert.notEqual(checked.ops[1]!.status, 'refused', `the result's last line, quoted from its span: ${JSON.stringify(checked.ops[1])}`);
  assert.equal(checked.ops[2]!.status, 'refused', 'the line as the dossier wrote it is not the record\'s words');
  assert.equal(checked.ops[2]!.reasons?.[0]?.code, 'WIKI_QUOTE_NOT_FOUND');
});

// ── a session that speaks for a project belongs where the project's work runs ─────────────────

test("a project's coordinator and judgment sessions are the space's only when the project works in it", { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const elsewhere = await workspace(h, owner.id);
  const spaceId = await space(h, owner, ws);
  const listId = await maintained(h, owner, spaceId, ws);
  const run = await maintenanceRun(h, owner.id, listId, ws, machine.id);

  // The demo's werewolf project: coordinated from this space's workspace, its task sessions all elsewhere.
  const game = await project(h, owner.id);
  const coordinator = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'AWAITING_INPUT', lastTurnAt: minutesAgo(30), title: 'Werewolf MVP' });
  await h.sql.query(`UPDATE "project" SET "coordinator_session_id" = $2, "coordinator_workspace_id" = $3 WHERE "id" = $1`, [game, coordinator, ws]);
  await turn(h, coordinator, 'Plan the werewolf game: night phase, day phase, voting.');
  await approval(h, coordinator, {
    tool: 'AskUserQuestion', status: 'ALLOWED', decidedBy: owner.id,
    input: { questions: [{ question: 'How many players?', options: [{ label: '8' }, { label: '12' }] }] },
    answers: { 'How many players?': '8' },
  });
  const judgment = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'SUCCEEDED', lastTurnAt: minutesAgo(29), title: 'judgment' });
  await h.sql.query(
    `INSERT INTO "project_coordinator_wake"("id","project_id","event","subject_type","subject_id","subject_version","idempotency_key","status","session_id")
     VALUES ($1,$2,'CRITERION_READY','PROJECT',$3,'v1',$4,'SESSION_OPENED',$5)`,
    [randomUUID(), game, game, `wake-${randomUUID()}`, judgment],
  );
  await receipt(h, owner.id, judgment);
  for (let n = 0; n < 2; n += 1) {
    const shard = await task(h, owner.id, { title: `Werewolf role ${n}`, status: 'FAILED', assigneeId: elsewhere, projectId: game });
    await session(h, owner.id, { workspaceId: elsewhere, runnerId: machine.id, taskId: shard, status: 'SUCCEEDED', lastTurnAt: minutesAgo(28) });
  }
  await criterion(h, game, 1);

  // A project whose work runs here: its coordinator is the space's, and so are its criteria.
  const ours = await project(h, owner.id);
  const ourCoordinator = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'AWAITING_INPUT', lastTurnAt: minutesAgo(27), title: 'Wiki phase 2' });
  await h.sql.query(`UPDATE "project" SET "coordinator_session_id" = $2, "coordinator_workspace_id" = $3 WHERE "id" = $1`, [ours, ourCoordinator, ws]);
  await turn(h, ourCoordinator, 'Coordinate the dossier task.');
  const ourTask = await task(h, owner.id, { title: 'The dossier', assigneeId: ws, projectId: ours });
  await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, taskId: ourTask, status: 'RUNNING', lastTurnAt: minutesAgo(26) });
  await criterion(h, ours, 1);

  // A project whose tasks are assigned here and have not run yet works here too, and so does a project
  // with no task and no codebase at all: its coordinator's workspace is all there is to go by.
  const planned = await project(h, owner.id);
  const plannedCoordinator = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'AWAITING_INPUT', lastTurnAt: minutesAgo(25), title: 'Planned' });
  await h.sql.query(`UPDATE "project" SET "coordinator_session_id" = $2, "coordinator_workspace_id" = $3 WHERE "id" = $1`, [planned, plannedCoordinator, ws]);
  await task(h, owner.id, { title: 'Not run yet', assigneeId: ws, projectId: planned });
  // A project whose tasks nobody assigned and nothing ran says nothing about where it works either.
  const empty = await project(h, owner.id);
  const emptyCoordinator = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'AWAITING_INPUT', lastTurnAt: minutesAgo(24), title: 'Empty' });
  await h.sql.query(`UPDATE "project" SET "coordinator_session_id" = $2, "coordinator_workspace_id" = $3 WHERE "id" = $1`, [empty, emptyCoordinator, ws]);
  await task(h, owner.id, { title: 'Nobody has it yet', projectId: empty });

  const state = await h.maintenance.cursorState(owner.id, spaceId);
  assert.deepEqual(state.byKind, {
    session_settled: 3,
    task_terminal: 0,
    approval_answered: 0,
    merge_receipt: 0,
    criterion_revised: 1,
  }, "our three coordinators' rests and our criterion: nothing of the game's is this space's");
  const page = await call(h, { runner: machine.token, session: run }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers`);
  expectStatus(page, 200, 'the page');
  assert.deepEqual((page.body.dossiers as Array<{ sessionId: string }>).map((one) => toUuid(one.sessionId)),
    [ourCoordinator, plannedCoordinator, emptyCoordinator],
    "the game's coordinator and judgment sessions get no dossier here");
  assert.ok(!(page.body.dossiers as Array<{ text: string }>).some((one) => /werewolf/i.test(one.text)));
});

// ── batch projects and error clusters ───────────────────────────────────────────────────────────

test('a batch project is counted, never extracted, and a tool error three sessions share is a cluster', { skip }, async () => {
  const h = await boot();
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const spaceId = await space(h, owner, ws);
  const listId = await maintained(h, owner, spaceId, ws);
  const run = await maintenanceRun(h, owner.id, listId, ws, machine.id);

  // FineWeb's shape: one project, one title template, many tasks.
  const fineweb = await project(h, owner.id);
  const batchSessions: string[] = [];
  for (let n = 0; n < WIKI_MAINTENANCE_RULES.batchTemplateMinTasks + 1; n += 1) {
    const shard = await task(h, owner.id, {
      title: `[FineWeb][CC-MAIN-2024-10] ${String(n).padStart(5, '0')}_00003.parquet`,
      status: n < 2 ? 'FAILED' : 'CANCELLED',
      assigneeId: ws,
      projectId: fineweb,
    });
    const shardSession = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, taskId: shard, status: 'SUCCEEDED', lastTurnAt: minutesAgo(30) });
    await turn(h, shardSession, `convert shard ${n}`, { clientTurnId: `initial-${randomUUID()}`, sendIntent: null });
    batchSessions.push(shardSession);
  }
  // A project with distinct titles is no batch.
  const ordinary = await project(h, owner.id);
  const plainTask = await task(h, owner.id, { title: 'Port the packer', status: 'CANCELLED', assigneeId: ws, projectId: ordinary });
  const plainSession = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, taskId: plainTask, status: 'SUCCEEDED', lastTurnAt: minutesAgo(29) });

  // The same error, numbers aside, in three sessions — and another in two.
  const shared: string[] = [];
  for (const port of [5432, 5433, 5434]) {
    const s = await session(h, owner.id, { workspaceId: ws, runnerId: machine.id, status: 'AWAITING_INPUT', lastTurnAt: minutesAgo(28) });
    shared.push(s);
    await tool(h, s, 'Bash', { command: 'psql' }, `psql: error: connection to server at "127.0.0.1", port ${port} failed: Connection refused`, { isError: true });
    await tool(h, s, 'Bash', { command: 'git push' }, 'error: failed to push some refs to origin', { isError: port !== 5434 });
  }

  const page = await call(h, { runner: machine.token, session: run }, 'GET', `/runner/wiki/spaces/${spaceId}/dossiers?limit=50`);
  expectStatus(page, 200, 'the page');
  const dossierSessions = new Set((page.body.dossiers as Array<{ sessionId: string }>).map((one) => toUuid(one.sessionId)));
  for (const s of batchSessions) assert.ok(!dossierSessions.has(s), 'a batch project\'s session gets no dossier of its own');
  assert.ok(dossierSessions.has(plainSession), 'an ordinary project\'s session does');
  const batches = page.body.batches as Array<{ projectId: string; template: string; tasks: number; byStatus: Record<string, number>; sessions: number }>;
  assert.equal(batches.length, 1, 'one batch');
  assert.equal(toUuid(batches[0]!.projectId), fineweb);
  assert.equal(batches[0]!.template, '[FineWeb][CC-MAIN-#-#] #_#.parquet');
  assert.equal(batches[0]!.tasks, WIKI_MAINTENANCE_RULES.batchTemplateMinTasks + 1);
  assert.deepEqual(batches[0]!.byStatus, { CANCELLED: WIKI_MAINTENANCE_RULES.batchTemplateMinTasks - 1, FAILED: 2 });
  assert.equal(batches[0]!.sessions, batchSessions.length, 'every shard session of the page is counted in it');
  assert.equal((await h.sql.query(`SELECT 1 FROM "wiki_dossier" WHERE "session_id" = ANY($1::uuid[])`, [batchSessions])).rowCount, 0,
    'and nothing of theirs is kept');

  const clusters = page.body.errorClusters as Array<{ tool: string; signature: string; sessions: number; examples: Array<{ sessionId: string }> }>;
  assert.equal(clusters.length, 1, `one signature three sessions share: ${JSON.stringify(clusters)}`);
  assert.equal(clusters[0]!.tool, 'Bash');
  assert.equal(clusters[0]!.sessions, 3);
  assert.match(clusters[0]!.signature, /^psql: error: connection to server at <q>, port # failed: Connection refused$/);
  assert.deepEqual(new Set(clusters[0]!.examples.map((one) => toUuid(one.sessionId))), new Set(shared));
});
