/**
 * Activity's read of a space's server runs (contracts/wiki.contract.json `jobs.read`, P9), the executor switch as the
 * reads tell it to an account (`jobs.executor.read`), and the System model's state beside them on the health read —
 * against a real PostgreSQL, over the doors' real routes, with ids as the production app encodes them:
 *
 *   1. the runs read: the space's newest `jobs` rows newest first; each run's calls counted by state with their tokens,
 *      its newest `callsPerJob` listed oldest first; a queued run's and a queued call's place in the deployment's
 *      queues, counted across every account; the pipeline's progress read as a step and done of total;
 *   2. a call is its metadata alone: no prompt, system prompt, answer or partial, no lease column, no job input or
 *      report reaches the client;
 *   3. another account's space is the plain 404, and each account is told the mode and whether the server runs its
 *      own wiki — never who is on the canary list;
 *   4. with a recognisable System model address and key in the environment, and the worker's rows written against
 *      them (its state, and calls that answered, were refused and failed), neither appears in the jobs, the
 *      system-model or the health read (project criterion 1: the reads carry neither the address nor the key).
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-job-reads.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every row belongs to an account the run created. Only the
 * two credential checks are stood in for.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import type { AddressInfo, Socket } from 'node:net';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { WIKI_JOBS_READ, toUuid, uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { enqueueWikiModelRequest } from '../wiki-worker/wiki-model-queue';
import { WikiModelRequestQueue } from '../wiki-worker/wiki-model-queue.service';
import { WikiModelStatusProbe } from '../wiki-worker/wiki-model-status';
import { readWikiSystemModel, type WikiSystemModelConfig } from '../wiki-worker/wiki-system-model';
import { WikiHealth } from './wiki-health';
import { WikiHealthController } from './wiki-health.controller';
import { WikiJobReads } from './wiki-job-reads';
import { WikiJobsController } from './wiki-jobs.controller';
import { WikiSystemModelReads } from './wiki-system-model';
import { WikiSystemModelController } from './wiki-system-model.controller';

const URL_ = process.env.COORDINATOR_PG_URL;
const skip = !URL_;

/** A key and a model nobody could mistake for anything else in a response body. */
const KEY = `sk-p9-jobs-read-${randomUUID()}`;
const MODEL = 'qwen3-p9-jobs-read';
/** Words a call's request and answer carry, which the call log must never echo. */
const SECRET = { system: `SYSTEM-${randomUUID()}`, prompt: `PROMPT-${randomUUID()}`, answer: `ANSWER-${randomUUID()}`, partial: `PARTIAL-${randomUUID()}` };

// ── the System model, played by a local server ──────────────────────────────────────────────────────

interface FakeModel {
  base: string;
  host: string;
  /** What the next call is answered: a stream, or a refusal with this status. */
  answer: { kind: 'stream' } | { kind: 'status'; status: number };
  close: () => Promise<void>;
}

async function fakeModel(): Promise<FakeModel> {
  const sockets = new Set<Socket>();
  const state: FakeModel = { base: '', host: '', answer: { kind: 'stream' }, close: async () => undefined };
  const server = createServer((request: IncomingMessage, response: ServerResponse) => {
    request.on('data', () => undefined);
    request.on('end', () => {
      if (request.url === '/health') {
        response.writeHead(200, { 'content-type': 'application/json' });
        response.end('{}');
        return;
      }
      const answer = state.answer;
      if (answer.kind === 'status') {
        // The body names the address and the key outright: whatever reaches a row from it must not reach a read.
        response.writeHead(answer.status, { 'content-type': 'application/json' });
        response.end(JSON.stringify({ type: 'error', error: { type: 'authentication_error', message: `bad key ${KEY} at ${state.base}` } }));
        return;
      }
      response.writeHead(200, { 'content-type': 'text/event-stream' });
      const event = (name: string, data: unknown) => `event: ${name}\ndata: ${JSON.stringify(data)}\n\n`;
      response.write(event('message_start', { type: 'message_start', message: { model: MODEL, usage: { input_tokens: 21, output_tokens: 1 } } }));
      response.write(event('content_block_delta', { type: 'content_block_delta', index: 0, delta: { type: 'text_delta', text: SECRET.answer } }));
      response.write(event('message_delta', { type: 'message_delta', delta: { stop_reason: 'end_turn' }, usage: { output_tokens: 7 } }));
      response.write(event('message_stop', { type: 'message_stop' }));
      response.end();
    });
  });
  server.on('connection', (socket: Socket) => {
    sockets.add(socket);
    socket.on('close', () => sockets.delete(socket));
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const { port } = server.address() as AddressInfo;
  state.base = `http://127.0.0.1:${port}`;
  state.host = `127.0.0.1:${port}`;
  state.close = async () => {
    for (const socket of sockets) socket.destroy();
    await new Promise<void>((resolve) => server.close(() => resolve()));
  };
  return state;
}

// ── the harness ─────────────────────────────────────────────────────────────────────────────────────

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  model: FakeModel;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;
const made: string[] = [];

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL_);
    const sql = new Client({ connectionString: URL_, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL_ as string);
    const model = await fakeModel();
    // The deployment's System model, in the environment of the process the reads run in: the apiserver never needs
    // them, so nothing it answers may name them either.
    process.env.ORBIT_WIKI_MODEL_BASE_URL = model.base;
    process.env.ORBIT_WIKI_MODEL_API_KEY = KEY;
    process.env.ORBIT_WIKI_MODEL = MODEL;
    const bearers = new Map<string, string>();

    @Module({
      controllers: [WikiJobsController, WikiHealthController, WikiSystemModelController],
      providers: [
        { provide: WikiJobReads, useValue: new WikiJobReads(prisma as unknown as PrismaService) },
        { provide: WikiHealth, useValue: new WikiHealth(prisma as unknown as PrismaService) },
        { provide: WikiSystemModelReads, useValue: new WikiSystemModelReads(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiJobReadsModule {}

    const app = await NestFactory.create(WikiJobReadsModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, model, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql, model } = await harness;
  await app.close().catch(() => undefined);
  // Not destructive: the accounts this run made take their spaces, jobs and calls with them.
  for (const id of made) {
    await prisma.wikiSpace.deleteMany({ where: { ownerId: id } }).catch(() => undefined);
    await prisma.user.deleteMany({ where: { id } }).catch(() => undefined);
  }
  await prisma.wikiModelStatus.deleteMany({ where: { id: 1 } }).catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
  await model.close().catch(() => undefined);
});

/** The switch the reads are made under: canary, with these accounts on its list (or another mode). */
function executor(mode: string, owners: string[] = []): void {
  process.env.ORBIT_WIKI_EXECUTOR = mode;
  process.env.ORBIT_WIKI_EXECUTOR_CANARY_OWNERS = owners.join(',');
}

interface Answer {
  status: number;
  text: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

async function get(h: Harness, bearer: string, route: string): Promise<Answer> {
  const response = await fetch(`${h.base}/api${route}`, { headers: { authorization: `Bearer ${bearer}` } });
  const text = await response.text();
  return { status: response.status, text, body: text ? JSON.parse(text) : null };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${answer.text.slice(0, 600)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
  spaceId: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  made.push(id);
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [id, `wiki-jobs-${id}@wiki.invalid`, name]);
  const spaceId = randomUUID();
  await h.sql.query(`INSERT INTO "wiki_space"("id","owner_id","slug","title") VALUES ($1,$2,$3,$4)`, [spaceId, id, `jobs-${id.slice(0, 8)}`, name]);
  const bearer = `bearer-${id}`;
  h.bearers.set(bearer, id);
  return { id, bearer, spaceId };
}

const base = Date.now() - 3 * 3_600_000;
const at = (minutes: number): string => new Date(base + minutes * 60_000).toISOString();

interface JobRow {
  kind?: string;
  state?: string;
  waitingFor?: string | null;
  priority?: number;
  createdAt: string;
  startedAt?: string | null;
  endedAt?: string | null;
  failureKind?: string | null;
  error?: string | null;
  progress?: unknown;
}

/** One `wiki_job` row of `who`'s space, as a worker would have left it. */
async function job(h: Harness, who: Account, row: JobRow): Promise<string> {
  const id = randomUUID();
  const state = row.state ?? 'succeeded';
  const running = state === 'running';
  const ended = ['succeeded', 'failed', 'cancelled'].includes(state);
  await h.sql.query(
    `INSERT INTO "wiki_job"("id","owner_id","space_id","kind","input","priority","state","waiting_for","lease_owner","lease_generation",
                            "lease_deadline_at","progress","report","error","failure_kind","created_at","updated_at","started_at","ended_at")
     VALUES ($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14,$15,$16,$16,$17,$18)`,
    [
      id, who.id, who.spaceId, row.kind ?? 'smoke', JSON.stringify({ secret: SECRET.prompt }), row.priority ?? 0, state, row.waitingFor ?? null,
      running ? randomUUID() : null, running ? randomUUID() : null, running ? new Date(Date.now() + 60_000).toISOString() : null,
      row.progress === undefined ? null : JSON.stringify(row.progress), ended ? JSON.stringify({ secret: SECRET.answer }) : null,
      row.error ?? null, row.failureKind ?? null, row.createdAt,
      row.startedAt ?? (state === 'queued' ? null : row.createdAt), ended ? (row.endedAt ?? row.createdAt) : null,
    ],
  );
  return id;
}

interface CallRow {
  unit: string;
  state: 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';
  priority?: number;
  enqueuedAt: string;
  tokens?: [number, number];
  httpStatus?: number;
  error?: string;
}

/** One `wiki_model_request` row of `jobId`, as the queue would have left it. */
async function call(h: Harness, who: Account, jobId: string, row: CallRow): Promise<string> {
  const id = randomUUID();
  const running = row.state === 'running';
  const started = row.state === 'queued' ? null : row.enqueuedAt;
  const ended = ['succeeded', 'failed', 'cancelled'].includes(row.state) ? row.enqueuedAt : null;
  await h.sql.query(
    `INSERT INTO "wiki_model_request"("id","job_id","owner_id","space_id","step","unit","attempt","attempts","priority","request","request_sha256",
                                      "state","lease_owner","lease_generation","lease_deadline_at","enqueued_at","started_at","ended_at",
                                      "answer","partial","input_tokens","output_tokens","http_status","error","error_kind")
     VALUES ($1,$2,$3,$4,'verify',$5,1,$6,$7,$8::jsonb,'sha',$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)`,
    [
      id, jobId, who.id, who.spaceId, row.unit, row.error ? 1 : 0, row.priority ?? 0,
      JSON.stringify({ system: SECRET.system, prompt: SECRET.prompt, maxTokens: 64 }), row.state,
      running ? randomUUID() : null, running ? randomUUID() : null, running ? new Date(Date.now() + 60_000).toISOString() : null,
      row.enqueuedAt, started, ended,
      row.state === 'succeeded' ? SECRET.answer : null, row.state === 'running' || row.state === 'failed' ? SECRET.partial : null,
      row.tokens?.[0] ?? null, row.tokens?.[1] ?? null, row.httpStatus ?? null, row.error ?? null, row.error ? 'other' : null,
    ],
  );
  return id;
}

async function clean(h: Harness, ...who: Account[]): Promise<void> {
  for (const one of who) await h.sql.query('DELETE FROM "wiki_job" WHERE "owner_id" = $1', [one.id]);
}

// ── 1 and 2: the runs read ──────────────────────────────────────────────────────────────────────────

test('the runs read: the newest runs newest first, their calls counted and the newest listed, each queue\'s place, and metadata alone', { skip }, async () => {
  const h = await boot();
  const a = await account(h, 'P9 jobs owner');
  const b = await account(h, 'P9 jobs stranger');
  executor('canary', [a.id]);

  // Twelve runs of the space, oldest first: the read answers the newest ten.
  const jobs: string[] = [];
  for (let i = 0; i < 7; i += 1) jobs.push(await job(h, a, { kind: 'smoke', createdAt: at(i) }));
  const failed = await job(h, a, { kind: 'verify', state: 'failed', failureKind: 'content', error: 'The model gave no verdict for any op.', createdAt: at(7) });
  const queuedFirst = await job(h, a, { kind: 'articles', state: 'queued', createdAt: at(8) });
  const queuedSecond = await job(h, a, { kind: 'articles', state: 'queued', createdAt: at(9) });
  const waiting = await job(h, a, {
    kind: 'import', state: 'waiting', waitingFor: 'repo', createdAt: at(10),
    progress: { step: 'snapshot', notes: 40, read: 10, failed: 2, ops: 3 },
  });
  const running = await job(h, a, { kind: 'verify', state: 'running', createdAt: at(11), progress: { step: 'verify', done: 3, total: 7 } });
  // Another account's run waits in the same queue, a priority above: it is ahead of both of this space's.
  const strangers = await job(h, b, { kind: 'verify', state: 'queued', priority: 1, createdAt: at(30) });

  // The running run's calls: 41 answered, one failed, one running, two queued — 45, the newest 40 listed.
  for (let i = 0; i < 41; i += 1) {
    await call(h, a, running, { unit: `u${String(i).padStart(2, '0')}`, state: 'succeeded', enqueuedAt: at(60 + i), tokens: [10, 2] });
  }
  await call(h, a, running, { unit: 'u41', state: 'failed', enqueuedAt: at(60 + 41), httpStatus: 400, error: 'HTTP 400: the request was malformed' });
  await call(h, a, running, { unit: 'u42', state: 'running', enqueuedAt: at(60 + 42) });
  await call(h, a, running, { unit: 'u43', state: 'queued', priority: 1, enqueuedAt: at(60 + 43) });
  await call(h, a, running, { unit: 'u44', state: 'queued', priority: 1, enqueuedAt: at(60 + 44) });
  // The stranger's calls in the deployment's queue: a priority above (ahead of both), the same priority and older
  // (ahead of both), the same priority between the two (ahead of the second only), and a priority below (behind).
  await call(h, b, strangers, { unit: 'b-high', state: 'queued', priority: 2, enqueuedAt: at(200) });
  await call(h, b, strangers, { unit: 'b-older', state: 'queued', priority: 1, enqueuedAt: at(10) });
  await call(h, b, strangers, { unit: 'b-between', state: 'queued', priority: 1, enqueuedAt: new Date(base + (60 + 43.5) * 60_000).toISOString() });
  await call(h, b, strangers, { unit: 'b-low', state: 'queued', priority: 0, enqueuedAt: at(0) });

  const answer = await get(h, a.bearer, `/wiki/spaces/${a.spaceId}/jobs`);
  expectStatus(answer, 200, 'the owner reads the space\'s runs');
  const read = answer.body;
  assert.equal(toUuid(read.spaceId), a.spaceId);
  assert.equal(read.jobs.length, WIKI_JOBS_READ.jobs, 'the newest ten of twelve');
  assert.deepEqual(read.jobs.map((one: { id: string }) => toUuid(one.id)),
    [running, waiting, queuedSecond, queuedFirst, failed, ...jobs.slice(2).reverse()], 'newest first');
  assert.equal(read.jobs[0].publicId, uuidToBase62(running), 'ids are the public ids the app hands out');

  const [run, park, second, first, broke] = read.jobs;
  // The running run: its calls counted over all 45, its newest 40 listed oldest first.
  assert.equal(run.kind, 'verify');
  assert.equal(run.state, 'running');
  assert.deepEqual(run.calls, { total: 45, queued: 2, running: 1, succeeded: 41, failed: 1, cancelled: 0, inputTokens: 410, outputTokens: 82 });
  assert.equal(run.requests.length, WIKI_JOBS_READ.callsPerJob);
  assert.deepEqual(run.requests.map((one: { unit: string }) => one.unit), Array.from({ length: 40 }, (_, i) => `u${String(i + 5).padStart(2, '0')}`));
  assert.deepEqual(run.progress, { step: 'verify', done: 3, total: 7 });
  // Each queued call's place in the deployment's queue: priority first, then first-come, whoever's it is.
  const unit = (name: string) => run.requests.find((one: { unit: string }) => one.unit === name);
  assert.equal(unit('u43').ahead, 2, 'b-high and b-older go first');
  assert.equal(unit('u44').ahead, 4, 'b-high, b-older, u43 and b-between go first');
  assert.equal(unit('u42').ahead, null, 'a running call is in no queue');
  assert.equal(unit('u40').ahead, null);
  assert.deepEqual(run.nextCall, { ahead: 2, enqueuedAt: at(60 + 43) }, 'the call the queue reaches first, and since when it waits');
  // A call: its metadata, its times, its tokens and how it failed.
  assert.deepEqual(Object.keys(unit('u41')).sort(), [
    'ahead', 'attempt', 'attempts', 'endedAt', 'enqueuedAt', 'error', 'errorKind', 'httpStatus', 'id', 'inputTokens', 'outputTokens',
    'publicId', 'startedAt', 'state', 'step', 'unit',
  ]);
  assert.deepEqual([unit('u41').state, unit('u41').httpStatus, unit('u41').error, unit('u41').errorKind], ['failed', 400, 'HTTP 400: the request was malformed', 'other']);
  assert.deepEqual([unit('u05').inputTokens, unit('u05').outputTokens, unit('u05').startedAt, unit('u05').endedAt], [10, 2, at(65), at(65)]);
  assert.equal(unit('u43').startedAt, null);

  // The waiting import: parked on the repository, its progress read as notes read or failed of the notes handed.
  assert.deepEqual([park.kind, park.state, park.waitingFor, park.ahead], ['import', 'waiting', 'repo', null]);
  assert.deepEqual(park.progress, { step: 'snapshot', done: 12, total: 40 });
  assert.deepEqual(park.calls, { total: 0, queued: 0, running: 0, succeeded: 0, failed: 0, cancelled: 0, inputTokens: 0, outputTokens: 0 });
  assert.deepEqual([park.requests, park.nextCall], [[], null]);
  // The queued runs: the stranger's priority-1 run goes before both, and the older of the two before the newer.
  assert.deepEqual([first.state, first.ahead, second.state, second.ahead], ['queued', 1, 'queued', 2]);
  assert.equal(first.startedAt, null);
  // The run that failed: whose failure it was, and why.
  assert.deepEqual([broke.state, broke.failureKind, broke.error, broke.ahead], ['failed', 'content', 'The model gave no verdict for any op.', null]);
  assert.ok(broke.endedAt);

  // Metadata alone: nothing of a call's request or answer, nothing of a job's input or report, no lease column.
  for (const words of Object.values(SECRET)) assert.equal(answer.text.includes(words), false, `the read names ${words}`);
  assert.deepEqual(Object.keys(run).sort(), [
    'ahead', 'attempts', 'calls', 'createdAt', 'endedAt', 'error', 'failureKind', 'id', 'kind', 'nextAttemptAt', 'nextCall', 'priority',
    'progress', 'publicId', 'requests', 'startedAt', 'state', 'updatedAt', 'waitingFor',
  ]);
  for (const field of ['input', 'report', 'request', 'answer', 'partial', 'leaseOwner', 'leaseGeneration', 'leaseDeadlineAt', 'requestSha256']) {
    assert.equal(answer.text.includes(`"${field}"`), false, `the read carries ${field}`);
  }
  // Nor does the read say whose the runs and calls ahead are: the stranger's ids appear nowhere in it.
  for (const id of [b.id, b.spaceId, strangers]) {
    assert.equal(answer.text.includes(id) || answer.text.includes(uuidToBase62(id)), false, `the read names ${id}`);
  }
  await clean(h, a, b);
});

// ── 3: whose it is ──────────────────────────────────────────────────────────────────────────────────

test('another account\'s space is the plain 404, and each account is told the mode and whether the server runs its own wiki', { skip }, async () => {
  const h = await boot();
  const a = await account(h, 'P9 canary owner');
  const b = await account(h, 'P9 other owner');
  executor('canary', [a.id]);
  await job(h, a, { kind: 'verify', createdAt: at(1) });

  expectStatus(await get(h, b.bearer, `/wiki/spaces/${a.spaceId}/jobs`), 404, 'a stranger reads nothing of another account\'s runs');
  expectStatus(await get(h, a.bearer, `/wiki/spaces/${randomUUID()}/jobs`), 404, 'a space nobody has');
  const own = await get(h, b.bearer, `/wiki/spaces/${b.spaceId}/jobs`);
  expectStatus(own, 200, 'an account reads its own space');
  assert.deepEqual(own.body.jobs, [], 'a space the server never ran anything for');

  // The executor as each account is told it: the mode, and whether the server runs this account's wiki.
  const mine = await get(h, a.bearer, '/wiki/system-model');
  expectStatus(mine, 200, 'the system-model read');
  assert.deepEqual(mine.body.executor, { mode: 'canary', serverExecutes: true });
  const theirs = await get(h, b.bearer, '/wiki/system-model');
  assert.deepEqual(theirs.body.executor, { mode: 'canary', serverExecutes: false });
  // The canary list stays on the server: the other account's read names nobody on it.
  assert.equal(theirs.text.includes(a.id) || theirs.text.includes(uuidToBase62(a.id)), false, 'the canary list leaks');

  // The health read carries the same answer, and the System model only while the server runs the account's wiki.
  const healthy = await get(h, a.bearer, `/wiki/spaces/${a.spaceId}/health`);
  expectStatus(healthy, 200, 'the health read');
  assert.deepEqual(healthy.body.executor, { mode: 'canary', serverExecutes: true });
  assert.ok(healthy.body.systemModel, 'the model\'s state beside the health of an account the server runs');
  assert.deepEqual(Object.keys(healthy.body.systemModel).sort(), ['checkedAt', 'model', 'since', 'state', 'workerSeenAt']);
  const other = await get(h, b.bearer, `/wiki/spaces/${b.spaceId}/health`);
  assert.deepEqual([other.body.executor, other.body.systemModel], [{ mode: 'canary', serverExecutes: false }, null]);
  assert.equal(other.text.includes(a.id) || other.text.includes(uuidToBase62(a.id)), false, 'the canary list leaks');
  expectStatus(await get(h, b.bearer, `/wiki/spaces/${a.spaceId}/health`), 404, 'nor another account\'s health');

  // Under server every account is the server's; unset is runner, as it always was.
  executor('server');
  assert.deepEqual((await get(h, b.bearer, '/wiki/system-model')).body.executor, { mode: 'server', serverExecutes: true });
  executor('');
  assert.deepEqual((await get(h, a.bearer, '/wiki/system-model')).body.executor, { mode: 'runner', serverExecutes: false });
  assert.equal((await get(h, a.bearer, `/wiki/spaces/${a.spaceId}/health`)).body.systemModel, null);
  await clean(h, a, b);
});

// ── 4: neither the address nor the key ──────────────────────────────────────────────────────────────

test('with the System model\'s address and key in the environment and the worker\'s rows written against them, no read names either', { skip, timeout: 60_000 }, async () => {
  const h = await boot();
  const a = await account(h, 'P9 no-secrets owner');
  executor('canary', [a.id]);
  const config: WikiSystemModelConfig = readWikiSystemModel({
    ORBIT_WIKI_MODEL_BASE_URL: process.env.ORBIT_WIKI_MODEL_BASE_URL,
    ORBIT_WIKI_MODEL_API_KEY: process.env.ORBIT_WIKI_MODEL_API_KEY,
    ORBIT_WIKI_MODEL: process.env.ORBIT_WIKI_MODEL,
  });
  assert.equal(config.baseUrl, h.model.base, 'the worker is pointed at the fake');

  // The worker's own writes, against the fake at that address with that key: its state row, a call that answers,
  // one refused (401, which also turns the state auth_failed) and one that fails outright (400).
  const probe = new WikiModelStatusProbe(h.prisma as unknown as PrismaService, config);
  await probe.check();
  const run = await job(h, a, { kind: 'smoke', state: 'running', createdAt: at(5) });
  const queue = new WikiModelRequestQueue(h.prisma as unknown as PrismaService, config, probe, undefined,
    { leaseMs: 2_000, renewMs: 500, partialMs: 100, pollMs: 50 });
  const ask = async (unit: string) => {
    const id = randomUUID();
    await enqueueWikiModelRequest(h.prisma as unknown as PrismaService, {
      id, jobId: run, ownerId: a.id, spaceId: a.spaceId, step: 'smoke', unit, request: { system: SECRET.system, prompt: SECRET.prompt, maxTokens: 16 },
    });
    await queue.runOnce();
    await queue.whenIdle();
    return id;
  };
  try {
    h.model.answer = { kind: 'stream' };
    await ask('answers');
    h.model.answer = { kind: 'status', status: 400 };
    await ask('fails');
    h.model.answer = { kind: 'status', status: 401 };
    await ask('refused');
  } finally {
    await queue.onModuleDestroy();
  }
  const { rows } = await h.sql.query<{ unit: string; state: string; error: string | null }>(
    'SELECT "unit", "state", "error" FROM "wiki_model_request" WHERE "job_id" = $1 ORDER BY "enqueued_at"', [run]);
  assert.deepEqual(rows.map((row) => [row.unit, row.state]), [['answers', 'succeeded'], ['fails', 'failed'], ['refused', 'queued']]);
  assert.ok(rows[1].error && rows[2].error, 'the refusals were written down');

  const reads = {
    jobs: await get(h, a.bearer, `/wiki/spaces/${a.spaceId}/jobs`),
    systemModel: await get(h, a.bearer, '/wiki/system-model'),
    health: await get(h, a.bearer, `/wiki/spaces/${a.spaceId}/health`),
  };
  for (const [name, answer] of Object.entries(reads)) {
    expectStatus(answer, 200, `the ${name} read`);
    for (const secret of [KEY, h.model.base, h.model.host]) {
      assert.equal(answer.text.includes(secret), false, `the ${name} read names ${secret}: ${answer.text.slice(0, 400)}`);
    }
  }
  // And what they do say: the refused key, as the state the settings page and the health line show.
  assert.deepEqual([reads.systemModel.body.state, reads.systemModel.body.model], ['auth_failed', MODEL]);
  assert.equal(reads.health.body.systemModel.state, 'auth_failed');
  const listed = reads.jobs.body.jobs[0];
  assert.deepEqual(listed.requests.map((one: { unit: string; state: string }) => [one.unit, one.state]),
    [['answers', 'succeeded'], ['fails', 'failed'], ['refused', 'queued']]);
  assert.deepEqual([listed.requests[0].inputTokens, listed.requests[0].outputTokens], [21, 7]);
  assert.deepEqual([listed.requests[1].httpStatus, listed.requests[1].errorKind], [400, 'other']);
  assert.equal(listed.requests[2].errorKind, 'unauthorized');
  assert.equal(listed.requests[2].ahead, 0, 'the refused call waits at the head of the queue');
  await clean(h, a);
});
