/**
 * The documents (criterion 9, revised 2026-09-28; contracts/wiki.contract.json `docs`, migration 0326),
 * over real HTTP and against a real PostgreSQL.
 *
 * What the task's verification asks, each read back from the doors and from the database:
 *
 *   1. with no confirmed plan a write is refused — a draft is not enough;
 *   2. a record's quote is checked by the server, word for word, against the record read again and
 *      redacted: a fabricated, a translated and a spliced quote are not found;
 *   3. a repository footnote without a sha is refused;
 *   4. a fact with no footnote is marked, a transition passes by the rule, and more than 5% marks the
 *      whole document for review;
 *   5. a section whose material did not change is not written again;
 *   6. an entry rejected — and one retired, one whose anchor went missing — withdraws the sentences that
 *      came through it, and marks their section to be written again;
 *   7. a document is not in the push block and cannot be cited as a source;
 *   8. another tenant's read is a 404, every one of them;
 *
 * and beside them what the design leans on: the pure rules (folding, fact tokens, the body's cut, the
 * threshold), only a maintenance run of the space writes, a write from a plan version no longer in
 * force is refused, the reads (directory, document, index) say what the page shows, and the
 * migration's CHECKs are the contract's closed sets.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-docs.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import {
  toUuid,
  uuidToBase62,
  WIKI_DOC_CHECKERS,
  WIKI_DOC_FOOTNOTE_KINDS,
  WIKI_DOC_LEAD_RULES,
  WIKI_DOC_SENTENCE_STATUSES,
  WIKI_DOC_STATUSES,
  WIKI_DOC_VERDICTS,
  WIKI_DOC_WITHDRAW_REASONS,
} from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiDocsController } from '../runner-api/runner-wiki-docs.controller';
import { RunnerWikiPlanController } from '../runner-api/runner-wiki-plan.controller';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { classifyDoc, docStatusOf, factTokens, findQuote, parseSectionBody, WikiDocs } from './wiki-docs';
import { WikiDocsController } from './wiki-docs.controller';
import { WikiPlans } from './wiki-plan';
import { WikiPlanController } from './wiki-plan.controller';
import { appendWikiContext } from './wiki-push';
import type { WikiRollout } from './wiki-rollout';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiController } from './wiki.controller';
import { WikiRefusalError, WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The wiki switched on for every account, whatever this environment's ORBIT_WIKI says. */
const ON: WikiRollout = { mode: 'on', canaryOwners: new Set<string>(), problems: [] };

const CONTRACT = JSON.parse(readFileSync(path.resolve(__dirname, '../../../../contracts/wiki.contract.json'), 'utf8'));

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  docs: WikiDocs;
  bearers: Map<string, string>;
  /** Every space `wiki.changed` was published for by the documents, in order. */
  published: string[];
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const published: string[] = [];
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const recorder = { publishWikiChanged: (_owner: string, space: string) => published.push(space) } as unknown as RealtimeService;
    const push = { notifyWikiReviewModeTripped: async () => undefined, notifyWikiVerificationTripped: async () => undefined } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);
    const plans = new WikiPlans(prisma as unknown as PrismaService, hub);
    const docs = new WikiDocs(prisma as unknown as PrismaService, service, recorder);

    @Module({
      controllers: [WikiController, WikiPlanController, WikiDocsController, RunnerWikiController, RunnerWikiPlanController, RunnerWikiDocsController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiPlans, useValue: plans },
        { provide: WikiDocs, useValue: docs },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiDocsModule {}

    const app = await NestFactory.create(WikiDocsModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, docs, bearers, published };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 1500)}`);
}

/** A refusal of the write's shape: 422 WIKI_DOC_INVALID, and among its errors one at `at`. */
function expectInvalid(answer: Answer, at: string, why: string): void {
  expectStatus(answer, 422, why);
  assert.equal(answer.body.code, 'WIKI_DOC_INVALID', why);
  const errors: Array<{ path: string; message: string }> = answer.body.errors ?? [];
  assert.ok(errors.some((error) => error.path === at), `${why}: no error at ${at} among ${JSON.stringify(errors).slice(0, 1500)}`);
  for (const error of errors) assert.ok(error.message.trim().length > 0, `${why}: an error with no words at ${error.path}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [id, `wiki-docs-${id}@wiki.invalid`, name]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

/** The owner's workspace.env holds this value: the redactor takes it out of every record it reads. */
const LITERAL = 'orbit-docs-literal-4f2a9c';

async function workspace(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env") VALUES ($1,'spec',$2,$3)`, [id, ownerId, JSON.stringify({ DOCS_SPEC_KEY: LITERAL })]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string, runnerId: string, taskId: string | null = null, title = 'a session'): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","status","dispatch_origin","updated_at")
     VALUES ($1,$2,'p',$3,$3,$4,$5,$6,'RUNNING'::run_status,'USER',now())`,
    [id, title, ownerId, workspaceId, runnerId, taskId],
  );
  return id;
}

async function task(h: Harness, ownerId: string, listId: string, assigneeId: string, title = 'Wiki maintenance run'): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id",
                         "completion_criterion","updated_at")
     VALUES ($1,$2,$3,'USER',$3,'OPEN'::task_status,$4,$5,'OWNER_CONFIRMED',now())`,
    [id, title, ownerId, assigneeId, listId],
  );
  return id;
}

async function turn(h: Harness, sessionId: string, content: string): Promise<string> {
  const id = randomUUID();
  const seq = (await h.sql.query<{ n: number }>(`SELECT COALESCE(MAX("seq"), 0)::int + 1 AS n FROM "conversation_turn" WHERE "session_id" = $1`, [sessionId])).rows[0].n;
  await h.sql.query(
    `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status","kind","send_intent")
     VALUES ($1,$2,$3,$4,$5,'ANSWERED','message','NEXT_TURN')`,
    [id, sessionId, seq, randomUUID(), content],
  );
  return id;
}

async function event(h: Harness, sessionId: string, type: string, payload: unknown): Promise<string> {
  const id = randomUUID();
  const seq = (await h.sql.query<{ n: number }>(`SELECT COALESCE(MAX("seq"), 0)::int + 1 AS n FROM "run_event" WHERE "session_id" = $1`, [sessionId])).rows[0].n;
  await h.sql.query(`INSERT INTO "run_event"("id","session_id","seq","type","payload") VALUES ($1,$2,$3,$4,$5)`, [id, sessionId, seq, type, JSON.stringify(payload)]);
  return id;
}

async function toolCall(h: Harness, sessionId: string, name: string, output: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","output","started_at") VALUES ($1,$2,$3,$4,now())`, [id, sessionId, name, JSON.stringify(output)]);
  return id;
}

async function comment(h: Harness, taskId: string, authorId: string, body: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "task_comment"("id","task_id","author_type","author_id","body") VALUES ($1,$2,'AGENT'::creator_type,$3,$4)`, [id, taskId, authorId, body]);
  return id;
}

/** The records the footnotes cite. */
const T1 = "先存后投：turn 先落库，runner 再通过出站 long-poll 从 inbox 领取；网关强制了 Connection '' 头，所以别用 WebSocket。";
const E1 = 'inbox handler 会 **hold 至多 25 秒**，然后返回 `204`。';
const TC1 = 'a shell started that way is a child of this coding-engine process, so recycling the engine (idle TTL, memory pressure) kills your build with it.\nUse mcp__orbit__bg_run instead.';
const C1 = '提交 9c7de42a。6 个新文件 / 7 个改动文件';
const T2 = `deploy with the key ${LITERAL}, then restart the runner`;
const SESSION_TITLE = '执行任务：会话运行模型与长连接';
const TASK_TITLE = '阶段 2 runner 托管 agent 后台作业';

/**
 * One owner's world: a runner, a bound workspace whose env holds LITERAL, a space (Tiered, a new space's
 * default) with maintenance on and a maintenance run of it, an ordinary session of the same workspace,
 * and the records the footnotes cite.
 */
interface Scene {
  owner: Account;
  runner: { id: string; token: string };
  ws: string;
  spaceId: string;
  listId: string;
  maintainer: Caller;
  maintenanceSession: string;
  ordinary: string;
  r: { t1: string; e1: string; tc1: string; c1: string; t2: string; taskId: string };
}

async function scene(h: Harness, title = 'A documented space'): Promise<Scene> {
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title });
  expectStatus(made, 201, 'the owner creates a space');
  const spaceId = toUuid(made.body.id as string);
  expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId: ws }), 200, 'the owner binds the workspace');
  const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true, workspaceId: ws } });
  expectStatus(on, 200, 'the owner turns maintenance on');
  const listId = toUuid(on.body.settings.maintenance.listId as string);
  const maintenanceSession = await session(h, owner.id, ws, machine.id, await task(h, owner.id, listId, ws));
  const ordinary = await session(h, owner.id, ws, machine.id, null, SESSION_TITLE);
  const taskId = await task(h, owner.id, listId, ws, TASK_TITLE);
  const r = {
    t1: await turn(h, ordinary, T1),
    e1: await event(h, ordinary, 'assistant', { text: E1 }),
    tc1: await toolCall(h, ordinary, 'Bash', TC1),
    c1: await comment(h, taskId, owner.id, C1),
    t2: await turn(h, ordinary, T2),
    taskId,
  };
  return { owner, runner: machine, ws, spaceId, listId, maintainer: { runner: machine.token, session: maintenanceSession }, maintenanceSession, ordinary, r };
}

// ── the plan ────────────────────────────────────────────────────────────────────────────────────

interface DocSpec {
  slug: string;
  category: string;
  title: string;
  question: string;
  scopeOut?: Array<{ text: string; docs: string[] }>;
  sections: Array<[string, string]>;
}

/** Three documents; `总览`, `已知的坑` and `约定` are section titles more than one of them has. */
const DOCS: DocSpec[] = [
  {
    slug: 'session-runtime',
    category: 'product',
    title: '会话运行模型与长连接',
    question: '一个 session 怎么被 runner 领取、turn 怎么投递？',
    scopeOut: [{ text: '任务怎么派发', docs: ['task-dispatch'] }],
    sections: [['总览', 'overview'], ['turn 投递与 inbox 领取', 'flow'], ['已知的坑', 'pitfalls'], ['约定', 'conventions']],
  },
  {
    slug: 'task-dispatch',
    category: 'product',
    title: '任务派发与领取',
    question: '一次派发怎么发生？',
    sections: [['总览', 'overview'], ['派发的三步握手', 'flow'], ['已知的坑', 'pitfalls']],
  },
  {
    slug: 'dev-testing',
    category: 'dev',
    title: '测试与 CI 约定',
    question: '在这个仓库里怎么跑测试？',
    sections: [['pg spec 怎么跑', 'conventions'], ['约定', 'conventions']],
  },
];

function docInput(doc: DocSpec): Record<string, unknown> {
  return {
    category: doc.category,
    slug: doc.slug,
    title: doc.title,
    question: doc.question,
    audience: ['A new developer: can say how it works after reading it'],
    scopeIn: [`How ${doc.slug} works`],
    scopeOut: doc.scopeOut ?? [],
    length: { min: 800, max: 4000 },
    sections: doc.sections.map(([title, kind]) => ({ title, kind, covers: `${title}讲什么。`, length: 400, sources: {} })),
  };
}

function planOf(docs: DocSpec[]): Record<string, unknown> {
  return {
    categories: [
      { key: 'product', title: 'Product', question: 'What Orbit is and how it runs' },
      { key: 'dev', title: 'Development conventions', question: 'How agents work in this repository', forAgents: true },
    ],
    docs: docs.map(docInput),
  };
}

const REPO = { sha: 'a'.repeat(40), checked: 3, missing: [] };

/** A draft from the maintenance run, and the owner's confirmation of it: the version now in force. */
async function confirmPlan(h: Harness, s: Scene, docs: DocSpec[] = DOCS, baseVersion: number | null = null): Promise<number> {
  const drafted = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/drafts`, {
    baseVersion,
    target: { min: 1, max: 10 },
    plan: planOf(docs),
    repoCheck: REPO,
    model: 'qwen3.8-27b-fp8',
  });
  expectStatus(drafted, 200, 'the maintenance run drafts the plan');
  const confirmed = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/plan/versions/${drafted.body.version}/confirm`);
  expectStatus(confirmed, 200, 'the owner confirms the plan');
  return drafted.body.version as number;
}

// ── writes ──────────────────────────────────────────────────────────────────────────────────────

/** The origin/main commit the run read the repository at. */
const HEAD = 'c'.repeat(40);

const sha256 = (text: string): string => createHash('sha256').update(text).digest('hex');

interface SectionSpec {
  key: string;
  markdown: string;
  footnotes: unknown[];
  /** The material's fingerprint; the markdown's own digest when left out. */
  material?: string;
}

function writeBody(planVersion: number, sections: SectionSpec[], extra: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    planVersion,
    repoSha: HEAD,
    model: 'qwen3.8-27b-fp8',
    sections: sections.map((section) => ({
      key: section.key,
      materialSha256: section.material ?? sha256(section.markdown),
      markdown: section.markdown,
      footnotes: section.footnotes,
    })),
    ...extra,
  };
}

async function writeDoc(h: Harness, s: Scene, slug: string, body: unknown, who: Caller = s.maintainer): Promise<Answer> {
  return call(h, who, 'POST', `/runner/wiki/spaces/${s.spaceId}/docs/${slug}`, body);
}

/** A code footnote the runner checked at a sha, and found. */
function code(quote: string | null, over: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    kind: 'code',
    path: 'src/apiserver/src/tasks/tasks.service.ts',
    sha: 'b'.repeat(40),
    lines: { start: 10, end: 20 },
    symbol: 'claimTask',
    quote,
    verified: true,
    ...over,
  };
}

/** A document as the database holds it: its sections by key, each with its sentences and their footnotes in order. */
async function stored(h: Harness, spaceId: string, slug: string) {
  const doc = await h.prisma.wikiDoc.findFirst({
    where: { spaceId, slug },
    include: {
      sections: {
        include: { sentences: { orderBy: { position: 'asc' }, include: { footnotes: { orderBy: { position: 'asc' } } } } },
      },
    },
  });
  return { doc, sections: new Map((doc?.sections ?? []).map((section) => [section.key, section])) };
}

/** The values a CHECK spells out, in the order it spells them. */
async function checkValues(h: Harness, table: string, constraint: string): Promise<string[]> {
  const def = await h.sql.query<{ def: string }>(
    `SELECT pg_get_constraintdef(oid) AS def FROM pg_constraint WHERE conname = $1 AND conrelid = $2::regclass`,
    [constraint, table],
  );
  assert.equal(def.rowCount, 1, `${table} has no constraint ${constraint}`);
  return [...def.rows[0].def.matchAll(/'([^']+)'::text/gu)].map((m) => m[1]);
}

const b62 = (id: string): string => uuidToBase62(id);

// ── 0. the rules themselves ─────────────────────────────────────────────────────────────────────

test('a quote is found folded, as one passage: punctuation, emphasis, code marks and comment markers aside — never translated, spliced or elided', () => {
  // Full-width punctuation reads as ASCII, whitespace goes, ** and backticks go.
  assert.ok(findQuote(T1, '先存后投: turn 先落库, runner 再通过出站 long-poll 从 inbox 领取'));
  assert.ok(findQuote(E1, 'inbox handler 会 hold 至多 25 秒，然后返回 204'));
  assert.ok(findQuote('用 \\*星号\\* 转义', '用 *星号* 转义'), 'a Markdown escape reads as what it escapes');
  // A code comment's words, without the marker each line starts with.
  assert.ok(findQuote('    // Park until a turn is enqueued\n    // for this run.', 'Park until a turn is enqueued for this run.'));
  assert.ok(findQuote('# 标题行\n正文', '标题行正文'));
  // Where it was found is where it is, in code points of the source.
  const at = findQuote(T1, '先存后投: turn 先落库, runner 再通过出站 long-poll 从 inbox 领取');
  assert.equal(Array.from(T1).slice(at!.start, at!.end).join(''), '先存后投：turn 先落库，runner 再通过出站 long-poll 从 inbox 领取');
  // Not the words: made up, translated, two passages joined, an ellipsis over a gap, a summary.
  assert.equal(findQuote(T1, '网关的 WebSocket 握手总是成功'), null);
  assert.equal(findQuote(T1, 'Store first, then deliver: the turn lands in the database first'), null);
  assert.equal(findQuote(T1, '先存后投，所以别用 WebSocket'), null);
  assert.equal(findQuote(T1, '先存后投……从 inbox 领取'), null);
  assert.equal(findQuote(T1, 'Runner 用 long-poll 领取 turn'), null);
  // Too short to say anything: found nowhere.
  assert.equal(findQuote(T1, '先存'), null);
  // A range narrows the search.
  assert.equal(findQuote(T1, '所以别用 WebSocket', { start: 0, end: 20 }), null);
  assert.ok(findQuote(T1, '所以别用 WebSocket', { start: 0, end: Array.from(T1).length }));
});

test('fact tokens: code spans, identifiers and paths, numbers of two or more digits, numbers with a unit', () => {
  assert.deepEqual(factTokens('派发时 `claimTask` 先把任务标成 CLAIMED。').sort(), ['claimed', 'claimtask']);
  assert.deepEqual(factTokens('src/web/lib.ts 里 hold 25 秒，5 秒后重试。').sort(), ['25', '5秒', 'hold', 'src/web/lib.ts']);
  // Stop words and identifiers under three characters are not facts; a sentence of prose has none.
  assert.deepEqual(factTokens('the id and a via for it'), []);
  assert.deepEqual(factTokens('这一步保证同一个任务只派给一个人。'), []);
});

test('a section body is cut as the articles are: its own heading dropped, a ； ends nothing, code not checked, stray markers dropped', () => {
  const body = parseSectionBody(
    [
      '## turn 投递与 inbox 领取',
      '',
      'Runner 通过出站 long-poll 领取 turn[1]；hold 至多 25 秒[2]。它不用 WebSocket[3]。',
      '',
      '### 为什么',
      '- 网关强制了 Connection 头[1]',
      '  所以握手会失败[9]',
      '',
      '```ts',
      'const x = arr[1]; // not a footnote',
      '```',
      '[2][3]',
    ].join('\n'),
    3,
  );
  assert.deepEqual(body.blocks.map((block) => block.kind), ['paragraph', 'heading', 'item', 'code']);
  assert.equal(body.blocks[1].text, '为什么');
  assert.deepEqual(
    body.sentences.map((sentence) => [sentence.block, sentence.text, sentence.notes]),
    [
      [0, 'Runner 通过出站 long-poll 领取 turn；hold 至多 25 秒。', [0, 1]],
      [0, '它不用 WebSocket。', [2]],
      [2, '网关强制了 Connection 头 所以握手会失败', [0]],
    ],
  );
  // [9] names no footnote of three; a line of markers alone is not a sentence.
  assert.equal(body.markersDropped, 3);
});

test('a transition brings no new fact; more than 5% unsourced or unverified marks the document, exactly 5% does not', () => {
  const sentences = [
    { text: '派发由 `claimTask` 开始。', marked: true, status: 'sourced' as const, newTokens: [] as string[] },
    { text: '它从 `claimTask` 开始。', marked: false, status: 'transition' as const, newTokens: [] as string[] },
    { text: '失败时由 `rollbackClaim` 回滚。', marked: false, status: 'transition' as const, newTokens: [] as string[] },
    { text: '标题里说过 inbox。', marked: false, status: 'transition' as const, newTokens: [] as string[] },
  ];
  classifyDoc(['inbox 领取'], sentences);
  assert.deepEqual(sentences.map((s) => s.status), ['sourced', 'transition', 'unsourced', 'transition']);
  assert.deepEqual(sentences[2].newTokens, ['rollbackclaim']);
  const counts = (unsourced: number, unverified: number, sentences: number) =>
    ({ sentences, sourced: sentences - unsourced - unverified, transition: 0, unsourced, unverified, withdrawn: 0 });
  assert.equal(docStatusOf(counts(1, 0, 20)), 'ok', '1 of 20 is 5% exactly');
  assert.equal(docStatusOf(counts(1, 1, 20)), 'needs_review', '2 of 20 is 10%');
  assert.equal(docStatusOf(counts(0, 1, 19)), 'needs_review', '1 of 19 is more than 5%');
  assert.equal(docStatusOf(counts(0, 0, 0)), 'ok');
});

// ── 1. no confirmed plan, no document ───────────────────────────────────────────────────────────

test('with no confirmed plan a write is refused — a draft is not enough — and a write from another version is stale', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const body = writeBody(1, [{ key: 's2', markdown: 'Runner 通过 long-poll 领取 turn[1]。', footnotes: [{ kind: 'turn', ref: s.r.t1, quote: '先存后投' }] }]);
  const none = await writeDoc(h, s, 'session-runtime', body);
  expectStatus(none, 409, 'a write to a space with no plan at all');
  assert.equal(none.body.code, 'WIKI_PLAN_UNCONFIRMED');
  const state = await call(h, s.maintainer, 'GET', `/runner/wiki/spaces/${s.spaceId}/docs`);
  expectStatus(state, 200, 'the maintenance run reads what is written');
  assert.equal(state.body.planVersion, null);
  assert.deepEqual(state.body.docs, []);

  // A draft nobody confirmed is not a plan documents are written from.
  const drafted = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/drafts`, {
    baseVersion: null,
    target: { min: 1, max: 10 },
    plan: planOf(DOCS),
    repoCheck: REPO,
  });
  expectStatus(drafted, 200, 'a draft');
  const draftOnly = await writeDoc(h, s, 'session-runtime', body);
  expectStatus(draftOnly, 409, 'a write to a space whose only plan is a draft');
  assert.equal(draftOnly.body.code, 'WIKI_PLAN_UNCONFIRMED');
  // The server's own import is held to the same guard.
  const importer: WikiPrincipal = { origin: 'import', ownerId: s.owner.id, userId: null, sessionId: null, toolCallId: null, authorKind: 'system' };
  await assert.rejects(h.docs.write(importer, s.spaceId, 'session-runtime', body), (error: unknown) => {
    assert.ok(error instanceof WikiRefusalError, `refused with a wiki code, not ${String(error)}`);
    assert.equal(error.refusal.code, 'WIKI_PLAN_UNCONFIRMED');
    return true;
  });
  assert.equal(await h.prisma.wikiDoc.count({ where: { spaceId: s.spaceId } }), 0, 'nothing was written');

  expectStatus(await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/plan/versions/1/confirm`), 200, 'the owner confirms it');
  // A write names the version in force; another one is stale, and a document the plan does not have is none.
  const stale = await writeDoc(h, s, 'session-runtime', { ...body, planVersion: 2 });
  expectStatus(stale, 409, 'a write from a version that is not the one confirmed');
  assert.equal(stale.body.code, 'WIKI_PLAN_STALE');
  expectStatus(await writeDoc(h, s, 'no-such-doc', body), 404, 'a document the plan does not have');
  assert.equal(await h.prisma.wikiDoc.count({ where: { spaceId: s.spaceId } }), 0, 'still nothing');
  const written = await writeDoc(h, s, 'session-runtime', body);
  expectStatus(written, 200, 'a write from the confirmed plan');
  assert.equal(written.body.planVersion, 1);
  assert.deepEqual(written.body.sections.map((section: { key: string; outcome: string }) => [section.key, section.outcome]), [['s2', 'written']]);
  const { doc } = await stored(h, s.spaceId, 'session-runtime');
  assert.equal(doc?.planVersion, 1);
  assert.equal(doc?.repoSha, HEAD);
  assert.ok(h.published.includes(s.spaceId), 'the write announced the space');
});

// ── 2. a record's quote, checked by the server ──────────────────────────────────────────────────

test('a record\'s quote is read again, redacted and checked word for word: a fabricated, a translated or a spliced one is not verified', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const version = await confirmPlan(h, s);
  const other = await scene(h, 'Somebody else\'s space');
  const theirs = await turn(h, other.ordinary, '别的账号的会话里的一句原话，别人读不到。');
  const markdown = [
    'Runner 通过出站 long-poll 从 inbox 领取 turn[1]。',
    'inbox handler 最多 hold 25 秒[2]。',
    '网关让 WebSocket 握手成功[3]。',
    'The turn is stored first and delivered after[4]。',
    '先存后投，所以别用 WebSocket[5]。',
    'Runner 用 long-poll 领取 turn[6]。',
    '长命令交给 bg_run 托管[7]。',
    '别的账号说过同样的话[8]。',
    '一条不存在的记录说过[9]。',
    '部署用的 key 不会原样留下[10]。',
    '提交 9c7de42a 带了 6 个新文件[11]。',
    '先存后投，再从 inbox 领取[12]。',
  ].join('\n');
  const footnotes = [
    { kind: 'turn', ref: b62(s.r.t1), quote: '先存后投: turn 先落库, runner 再通过出站 long-poll 从 inbox 领取' },
    { kind: 'event', ref: s.r.e1, quote: 'inbox handler 会 hold 至多 25 秒，然后返回 204' },
    { kind: 'turn', ref: s.r.t1, quote: '网关的 WebSocket 握手总是成功' },
    { kind: 'turn', ref: s.r.t1, quote: 'Store first, then deliver: the turn lands in the database first' },
    { kind: 'turn', ref: s.r.t1, quote: '先存后投，所以别用 WebSocket' },
    { kind: 'turn', ref: s.r.t1, quote: 'Runner 用 long-poll 领取 turn' },
    { kind: 'tool_call', ref: s.r.tc1, quote: null },
    { kind: 'turn', ref: theirs, quote: '别的账号的会话里的一句原话' },
    { kind: 'event', ref: randomUUID(), quote: 'a record nobody has at all' },
    { kind: 'turn', ref: s.r.t2, quote: `deploy with the key ${LITERAL}, then restart` },
    { kind: 'task_comment', ref: s.r.c1, quote: '提交 9c7de42a。6 个新文件' },
    { kind: 'turn', ref: s.r.t1, quote: '先存后投……从 inbox 领取' },
  ];
  const written = await writeDoc(h, s, 'session-runtime', writeBody(version, [{ key: 's2', markdown, footnotes }]));
  expectStatus(written, 200, 'the write');
  const section = written.body.sections[0];
  assert.equal(section.outcome, 'written');
  assert.deepEqual(
    [section.stats.footnotes, section.stats.verified, section.stats.notFound, section.stats.noQuote, section.stats.unresolved],
    [12, 4, 5, 1, 2],
  );

  const { doc, sections } = await stored(h, s.spaceId, 'session-runtime');
  const sentences = sections.get('s2')!.sentences;
  const verdicts = sentences.map((sentence) => sentence.footnotes[0].verdict);
  assert.deepEqual(verdicts, [
    'verified', 'verified', 'not_found', 'not_found', 'not_found', 'not_found', 'no_quote', 'unresolved', 'unresolved', 'verified', 'verified', 'not_found',
  ]);
  // Fabricated, translated, spliced, a summary as if it were the words, an ellipsis over a gap: unverified.
  assert.deepEqual(sentences.map((sentence) => sentence.status), [
    'sourced', 'sourced', 'unverified', 'unverified', 'unverified', 'unverified', 'unverified', 'unverified', 'unverified', 'sourced', 'sourced', 'unverified',
  ]);
  for (const sentence of sentences) assert.equal(sentence.footnotes[0].checkedBy, 'server');
  // Where the quote was found is where it is in the record.
  const first = sentences[0].footnotes[0];
  assert.equal(first.ref, s.r.t1, 'the record is kept by its id, however it was spelled');
  assert.equal(Array.from(T1).slice(first.charStart!, first.charEnd!).join(''), '先存后投：turn 先落库，runner 再通过出站 long-poll 从 inbox 领取');
  assert.equal((first.locator as { sessionId: string }).sessionId, s.ordinary);
  // Redacted before it was compared and before it was kept: the literal is nowhere.
  const key = sentences[9].footnotes[0];
  assert.ok(key.quote!.includes('[redacted]') && !key.quote!.includes(LITERAL), `the stored quote: ${key.quote}`);
  const redactedT2 = `deploy with the key [redacted], then restart the runner`;
  assert.equal(Array.from(redactedT2).slice(key.charStart!, key.charEnd!).join(''), 'deploy with the key [redacted], then restart');
  const everything = JSON.stringify(await h.prisma.wikiDocFootnote.findMany({ where: { ownerId: s.owner.id } }));
  assert.ok(!everything.includes(LITERAL), 'no footnote row holds the workspace\'s secret');
  // 8 of 12 unverified: the whole document needs review.
  assert.equal(doc?.status, 'needs_review');
  assert.equal(written.body.status, 'needs_review');
  assert.deepEqual(written.body.counts, { sentences: 12, sourced: 4, transition: 0, unsourced: 0, unverified: 8, withdrawn: 0 });

  // The page: each footnote with its verdict, its quote and where it links to.
  const page = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/session-runtime`);
  expectStatus(page, 200, 'the owner reads the document');
  assert.equal(page.body.status, 'needs_review');
  assert.equal(page.body.footnotes.length, 12);
  const [onTurn, onEvent] = page.body.footnotes;
  assert.equal(onTurn.n, 1);
  assert.equal(onTurn.verdict, 'verified');
  assert.equal(onTurn.sessionTitle, SESSION_TITLE);
  assert.equal(onTurn.seq, 1);
  assert.equal(onTurn.label, 'message');
  assert.equal(toUuid(onTurn.recordId as string), s.r.t1);
  assert.match(onTurn.location, new RegExp(`^turn:${s.r.t1}#c\\d+-\\d+$`, 'u'));
  assert.equal(onEvent.label, 'assistant');
  // A turn, an event and a tool call are read back with their session beside their id: the pair the
  // deep link needs (contract `docs.links.sessionRecord`), since a source keeps a record's id alone.
  for (const [n, kind, record] of [[1, 'turn', s.r.t1], [2, 'event', s.r.e1], [7, 'tool_call', s.r.tc1]] as const) {
    const footnote = page.body.footnotes.find((f: { n: number }) => f.n === n);
    assert.equal(footnote.kind, kind);
    assert.equal(toUuid(footnote.recordId as string), record, `${kind}: its record`);
    assert.equal(toUuid(footnote.sessionId as string), s.ordinary, `${kind}: the session it is in`);
    assert.ok(footnote.sessionPublicId || footnote.sessionId, `${kind}: a session id the client can put in a link`);
  }
  const onComment = page.body.footnotes.find((footnote: { kind: string }) => footnote.kind === 'task_comment');
  assert.equal(onComment.taskTitle, TASK_TITLE);
  assert.equal(toUuid(onComment.taskId as string), s.r.taskId);
  const unresolved = page.body.footnotes.filter((footnote: { verdict: string }) => footnote.verdict === 'unresolved');
  assert.equal(unresolved.length, 2);
  for (const footnote of unresolved) assert.equal(footnote.sessionTitle, null, 'nothing of another account\'s record is shown');
  assert.ok(!JSON.stringify(page.body).includes('别的账号的会话里的一句原话，别人读不到'), 'nor its words');
  const written2 = page.body.sections.find((sec: { key: string }) => sec.key === 's2');
  assert.deepEqual(written2.blocks[0].sentences.map((sentence: { notes: number[] }) => sentence.notes), [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12]]);
});

// ── 3. the repository: the runner's check, at a sha ─────────────────────────────────────────────

test('a repository footnote without a sha is refused, with every other shape error of the write, and nothing is written', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const version = await confirmPlan(h, s);
  const stranger = await scene(h, 'A stranger\'s space');
  const theirEntry = { id: randomUUID() };
  await h.sql.query(
    `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields")
     VALUES ($1,$2,$3,'concept','active','owner',1,'Somebody else''s','Not this space''s.','{"definition":"x","boundaries":"y"}')`,
    [theirEntry.id, stranger.owner.id, stranger.spaceId],
  );
  const bad = writeBody(version, [
    {
      key: 's2',
      markdown: '派发由 `claimTask` 开始[1]。设计文档这样说[2]。它会重试[3]。',
      footnotes: [
        code('export function claimTask('),
        { kind: 'design_doc', path: 'docs/task-dispatch.md', lines: { start: 3, end: 9 }, section: 'Claim', quote: '三步握手', verified: true },
        { kind: 'contract', path: 'contracts/task.contract.json', sha: 'e'.repeat(40), lines: { start: 9, end: 2 }, quote: 'retry', verified: true, confidence: 0.9 },
      ],
    },
    { key: 's9', markdown: '不在计划里的一节[1]。', footnotes: [{ kind: 'turn', ref: s.r.t1, quote: '先存后投', viaEntryId: theirEntry.id }] },
  ]);
  delete bad.repoSha;
  const refused = await writeDoc(h, s, 'task-dispatch', bad);
  expectInvalid(refused, 'sections[0].footnotes[1].sha', 'a design-document footnote with no sha');
  expectInvalid(refused, 'sections[0].footnotes[2].lines.end', 'lines that end before they start');
  expectInvalid(refused, 'sections[0].footnotes[2].confidence', 'a field the schema does not have');
  expectInvalid(refused, 'sections[1].key', 'a section the plan\'s document does not have');
  expectInvalid(refused, 'sections[1].footnotes[0].viaEntryId', 'a via entry of another account\'s space');
  expectInvalid(refused, 'repoSha', 'a write that does not say which commit it read');
  assert.match(refused.body.message, /Nothing was written/u);
  assert.equal(await h.prisma.wikiDoc.count({ where: { spaceId: s.spaceId } }), 0, 'nothing was written');

  // With its sha, the runner's check is what is kept, as the runner's, at that sha.
  const ok = await writeDoc(h, s, 'task-dispatch', writeBody(version, [
    {
      key: 's2',
      markdown: '派发由 `claimTask` 开始[1]。设计文档把它叫三步握手[2]。契约里没有这句[3]。它会重试[4]。',
      footnotes: [
        code('export function claimTask(', { excerpt: '/** Claim a task. */\nexport function claimTask(id: string) {' }),
        { kind: 'design_doc', path: 'docs/task-dispatch.md', sha: 'd'.repeat(40), lines: { start: 3, end: 9 }, section: 'Claim', quote: '三步握手', verified: true },
        { kind: 'contract', path: 'contracts/task.contract.json', sha: 'e'.repeat(40), lines: { start: 2, end: 9 }, quote: 'a sentence the contract never had', verified: false },
        { kind: 'contract', path: 'contracts/task.contract.json', sha: 'e'.repeat(40), lines: { start: 2, end: 9 }, quote: null, verified: true },
      ],
    },
  ]));
  expectStatus(ok, 200, 'repository footnotes with their sha');
  const { sections } = await stored(h, s.spaceId, 'task-dispatch');
  const rows = sections.get('s2')!.sentences.map((sentence) => sentence.footnotes[0]);
  assert.deepEqual(rows.map((row) => [row.kind, row.verdict, row.checkedBy, row.sha]), [
    ['code', 'verified', 'runner', 'b'.repeat(40)],
    ['design_doc', 'verified', 'runner', 'd'.repeat(40)],
    ['contract', 'not_found', 'runner', 'e'.repeat(40)],
    ['contract', 'no_quote', 'runner', 'e'.repeat(40)],
  ]);
  assert.deepEqual([rows[0].lineStart, rows[0].lineEnd, rows[0].charStart], [10, 20, null]);
  assert.deepEqual(sections.get('s2')!.sentences.map((sentence) => sentence.status), ['sourced', 'sourced', 'unverified', 'unverified']);
  const page = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/task-dispatch`);
  expectStatus(page, 200, 'the page');
  const [onCode, onDesign] = page.body.footnotes;
  assert.equal(onCode.location, `src/apiserver/src/tasks/tasks.service.ts@${'b'.repeat(40)}#L10-20`);
  assert.equal(onCode.symbol, 'claimTask');
  assert.match(onCode.excerpt, /export function claimTask/u);
  assert.equal(onCode.recordId, null);
  assert.equal(onDesign.section, 'Claim');
  assert.equal(onDesign.checkedBy, 'runner');
});

// ── 4. statuses, the transition rule and the threshold ──────────────────────────────────────────

test('a fact with no footnote is marked, a transition passes by the rule, and past 5% the whole document needs review', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const version = await confirmPlan(h, s);
  const steps = (from: number, to: number): string[] => Array.from({ length: to - from + 1 }, (_, i) => `第 ${from + i} 步由 \`step${from + i}\` 完成[1]。`);
  // Eighteen sourced sentences, a transition and one fact nothing backs: 1 of 20 is 5%, which is not more.
  const s2 = [...steps(1, 18), '这些步骤依次完成，最后由 `step18` 收尾。', '失败时由 `rollbackClaim` 回滚。'].join('\n');
  const first = await writeDoc(h, s, 'task-dispatch', writeBody(version, [{ key: 's2', markdown: s2, footnotes: [code('export function claimTask(')] }]));
  expectStatus(first, 200, 'the flow section');
  assert.equal(first.body.status, 'ok', 'exactly 5% does not mark the document');
  assert.deepEqual(first.body.counts, { sentences: 20, sourced: 18, transition: 1, unsourced: 1, unverified: 0, withdrawn: 0 });
  let { sections } = await stored(h, s.spaceId, 'task-dispatch');
  const unsourced = sections.get('s2')!.sentences.find((sentence) => sentence.status === 'unsourced')!;
  assert.equal(unsourced.text, '失败时由 `rollbackClaim` 回滚。');
  assert.deepEqual(unsourced.newTokens, ['rollbackclaim']);
  assert.equal(sections.get('s2')!.sentences.find((sentence) => sentence.status === 'transition')!.text, '这些步骤依次完成，最后由 `step18` 收尾。');

  // The overview's transition rests on what the flow section sourced; the pitfalls' fact rests on nothing.
  const second = await writeDoc(h, s, 'task-dispatch', writeBody(version, [
    { key: 's1', markdown: '派发从 `step1` 开始，到 `step18` 结束。', footnotes: [] },
    { key: 's3', markdown: '重试超过 `maxAttempts` 次就放弃。', footnotes: [] },
  ]));
  expectStatus(second, 200, 'the overview and the pitfalls');
  assert.equal(second.body.status, 'needs_review', '2 of 22 is more than 5%');
  ({ sections } = await stored(h, s.spaceId, 'task-dispatch'));
  assert.equal(sections.get('s1')!.sentences[0].status, 'transition');
  assert.deepEqual(sections.get('s3')!.sentences[0].newTokens, ['maxattempts']);
  assert.equal((await stored(h, s.spaceId, 'task-dispatch')).doc?.status, 'needs_review');

  // The flow section written again without step 1: the overview, not written again, is classified again.
  const s2b = [...steps(2, 19), '这些步骤依次完成，最后由 `step19` 收尾。'].join('\n');
  const third = await writeDoc(h, s, 'task-dispatch', writeBody(version, [{ key: 's2', markdown: s2b, footnotes: [code('export function claimTask(')] }]));
  expectStatus(third, 200, 'the flow section again');
  ({ sections } = await stored(h, s.spaceId, 'task-dispatch'));
  const overview = sections.get('s1')!.sentences[0];
  assert.equal(overview.status, 'unsourced', 'step1 is no longer in a sourced sentence');
  assert.deepEqual(overview.newTokens, ['step1']);
  assert.deepEqual(third.body.counts, { sentences: 21, sourced: 18, transition: 1, unsourced: 2, unverified: 0, withdrawn: 0 });

  // The page says the same: the marked sentences, their new tokens, and the share.
  const page = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/task-dispatch`);
  expectStatus(page, 200, 'the page');
  assert.equal(page.body.status, 'needs_review');
  assert.equal(page.body.unsourcedShare, 2 / 21);
  const s1 = page.body.sections.find((section: { key: string }) => section.key === 's1');
  assert.deepEqual(s1.blocks[0].sentences[0].newTokens, ['step1']);
  // Every sentence citing the one original with the one quote is one footnote.
  assert.equal(page.body.footnotes.length, 1);
});

// ── 5. unchanged material, unchanged section ────────────────────────────────────────────────────

test('a section whose material did not change is not written again; one whose material did is; a section the plan dropped goes', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const version = await confirmPlan(h, s);
  const material = sha256('the material of the pg spec section');
  const first = await writeDoc(h, s, 'dev-testing', writeBody(version, [
    { key: 's1', material, markdown: 'pg spec 只用 `run-pg-spec.sh` 跑[1]。', footnotes: [code('run-pg-spec.sh', { path: 'scripts/run-pg-spec.sh', symbol: null })] },
    { key: 's2', markdown: '任何 skip 都判红[1]。', footnotes: [code('A SKIP IS RED', { path: 'scripts/run-pg-spec.sh', symbol: null })] },
  ]));
  expectStatus(first, 200, 'the first write');
  const before = (await stored(h, s.spaceId, 'dev-testing')).sections.get('s1')!;

  // The same material: nothing is written, whatever the text says now.
  const again = await writeDoc(h, s, 'dev-testing', writeBody(version, [
    { key: 's1', material, markdown: 'pg spec 换了一种说法[1]。', footnotes: [code('run-pg-spec.sh', { path: 'scripts/run-pg-spec.sh', symbol: null })] },
  ]));
  expectStatus(again, 200, 'the same material again');
  assert.deepEqual(again.body.sections, [{ key: 's1', outcome: 'unchanged', stats: null }]);
  const kept = (await stored(h, s.spaceId, 'dev-testing')).sections.get('s1')!;
  assert.equal(kept.id, before.id, 'the section row is the one written first');
  assert.equal(kept.generatedAt.toISOString(), before.generatedAt.toISOString());
  assert.equal(kept.sentences[0].text, 'pg spec 只用 `run-pg-spec.sh` 跑。');
  const published = h.published.filter((space) => space === s.spaceId).length;

  // New material: written again, as a new row.
  const changed = await writeDoc(h, s, 'dev-testing', writeBody(version, [
    { key: 's1', material: sha256('new material'), markdown: 'pg spec 用 `run-pg-spec.sh` 跑，skip 判红[1]。', footnotes: [code('A SKIP IS RED', { path: 'scripts/run-pg-spec.sh', symbol: null })] },
  ]));
  expectStatus(changed, 200, 'new material');
  assert.equal(changed.body.sections[0].outcome, 'written');
  const rewritten = (await stored(h, s.spaceId, 'dev-testing')).sections.get('s1')!;
  assert.notEqual(rewritten.id, before.id);
  assert.equal(rewritten.materialSha256, sha256('new material'));
  assert.equal(h.published.filter((space) => space === s.spaceId).length, published + 1, 'an unchanged write announced nothing; a written one did');

  // The owner drops a section from the plan: a write from the old version is stale, and the next one
  // from the new version drops the section — its unchanged neighbour left as it was.
  const dropped: DocSpec = { ...DOCS[2], sections: [DOCS[2].sections[0]] };
  const edit = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/plan/edits`, { baseVersion: version, docSlug: 'dev-testing', doc: docInput(dropped) });
  expectStatus(edit, 200, 'the owner edits the plan');
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/plan/versions/${edit.body.version}/confirm`), 200, 'and confirms it');
  const old = await writeDoc(h, s, 'dev-testing', writeBody(version, [{ key: 's1', material: sha256('new material'), markdown: 'x[1]。', footnotes: [code('A SKIP IS RED')] }]));
  expectStatus(old, 409, 'a write from the version no longer in force');
  assert.equal(old.body.code, 'WIKI_PLAN_STALE');
  const next = await writeDoc(h, s, 'dev-testing', writeBody(edit.body.version, [{ key: 's1', material: sha256('new material'), markdown: 'x[1]。', footnotes: [code('A SKIP IS RED')] }]));
  expectStatus(next, 200, 'a write from the new version');
  assert.equal(next.body.sections[0].outcome, 'unchanged');
  const after = await stored(h, s.spaceId, 'dev-testing');
  assert.deepEqual([...after.sections.keys()], ['s1'], 'the dropped section is gone');
  assert.equal(after.sections.get('s1')!.id, rewritten.id);
  assert.equal(after.doc?.planVersion, edit.body.version);
});

// ── 6. withdrawal ───────────────────────────────────────────────────────────────────────────────

test('an entry rejected, retired or whose anchor went missing withdraws the sentences that came through it, and marks their section for rewriting', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const version = await confirmPlan(h, s);
  // A: the space's mode applied an agent's add (Tiered): the owner rejects it from the entry.
  const proposed = await call(h, { runner: s.runner.token, session: s.ordinary }, 'POST', '/runner/wiki/changesets', {
    rationale: 'what the session said about delivery',
    idempotencyKey: `docs-agent-${randomUUID()}`,
    ops: [{
      op: 'add',
      entry: { kind: 'concept', title: '先存后投', summary: 'A turn is stored before it is delivered.', fields: { definition: 'store, then deliver', boundaries: 'delivery only' } },
      sources: [{ kind: 'turn', ref: s.r.t1, quote: '先存后投' }],
    }],
  });
  expectStatus(proposed, 200, 'an agent proposes an entry');
  assert.equal(proposed.body.ops[0].status, 'applied', `the space's mode applies it: ${JSON.stringify(proposed.body.ops[0]).slice(0, 400)}`);
  const a = toUuid(proposed.body.ops[0].entryId as string);
  // P and R: the owner's own, one anchored at a path, one to be retired.
  const owned = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/changesets`, {
    rationale: 'the owner writes two entries',
    ops: [
      {
        op: 'add',
        entry: {
          kind: 'pitfall',
          title: 'inbox 的 hold 上限',
          summary: 'The inbox holds a poll for at most 25 seconds.',
          fields: { trigger: { paths: ['src/apiserver/src/realtime/realtime.service.ts'], commands: [] }, symptom: 'a long wait', cause: 'the hold', fix: 'poll again' },
          anchors: [{ type: 'path', path: 'src/apiserver/src/realtime/realtime.service.ts' }],
        },
      },
      { op: 'add', entry: { kind: 'convention', title: '长命令用 bg_run', summary: 'Long commands run in bg_run.', fields: { rule: 'Use bg_run for long commands.', scope: ['**'] } } },
    ],
  });
  expectStatus(owned, 200, 'the owner writes');
  const [p, r] = owned.body.ops.map((op: { entryId: string }) => toUuid(op.entryId));

  const markdown = ['turn 先落库再投递[1]。', 'inbox 最多 hold 25 秒[2]。', '长命令交给 bg_run[3]。', '提交 9c7de42a 带了 6 个新文件[4]。'].join('\n');
  const footnotes = [
    { kind: 'turn', ref: s.r.t1, quote: '先存后投：turn 先落库', viaEntryId: b62(a) },
    { kind: 'event', ref: s.r.e1, quote: 'hold 至多 25 秒', viaEntryId: p },
    { kind: 'tool_call', ref: s.r.tc1, quote: 'Use mcp__orbit__bg_run instead', viaEntryId: r },
    { kind: 'task_comment', ref: s.r.c1, quote: '6 个新文件 / 7 个改动文件' },
  ];
  const material = sha256('the pitfalls material');
  const written = await writeDoc(h, s, 'session-runtime', writeBody(version, [{ key: 's3', material, markdown, footnotes }]));
  expectStatus(written, 200, 'the pitfalls section');
  const statuses = async () => (await stored(h, s.spaceId, 'session-runtime')).sections.get('s3')!;
  assert.deepEqual((await statuses()).sentences.map((sentence) => sentence.status), ['sourced', 'sourced', 'sourced', 'sourced']);
  assert.equal((await statuses()).staleAt, null);
  assert.equal((await statuses()).sentences[0].footnotes[0].viaEntryId, a);

  // Rejected: the sentence it carried is withdrawn, its section marked; the rest stand.
  const rejected = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/entries/${a}/reject`, { reason: 'not_true' });
  expectStatus(rejected, 200, 'the owner rejects the entry');
  let section = await statuses();
  assert.deepEqual(section.sentences.map((sentence) => sentence.status), ['withdrawn', 'sourced', 'sourced', 'sourced']);
  assert.deepEqual([section.sentences[0].withdrawnReason, section.sentences[0].withdrawnEntryId], ['rejected', a]);
  assert.ok(section.sentences[0].withdrawnAt);
  assert.ok(section.staleAt, 'the section is to be written again');
  // Withdrawn sentences wait for the rewrite: they do not mark the document.
  assert.equal((await stored(h, s.spaceId, 'session-runtime')).doc?.status, 'ok');

  // An anchor gone missing, and a retirement, do the same.
  const checked = await h.service.recordAnchorChecks({ ownerId: s.owner.id, sessionId: s.maintenanceSession }, s.spaceId, {
    ref: 'f'.repeat(40),
    entries: [{ entryId: p, revision: 1, checks: [{ index: 0, type: 'path', state: 'missing' }] }],
  });
  assert.equal(checked.outcomes[0].status, 'recorded', JSON.stringify(checked.outcomes[0]));
  const retired = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/changesets`, {
    rationale: 'no longer how it works',
    ops: [{ op: 'retire', entryId: r, baseRevision: 1, reason: 'bg_run replaced it' }],
  });
  expectStatus(retired, 200, 'the owner retires an entry');
  section = await statuses();
  assert.deepEqual(section.sentences.map((sentence) => [sentence.status, sentence.withdrawnReason]), [
    ['withdrawn', 'rejected'],
    ['withdrawn', 'anchor_missing'],
    ['withdrawn', 'retired'],
    ['sourced', null],
  ]);

  // What the reads say: the section stale, the sentences withdrawn and why, the entries as they stand.
  const state = await call(h, s.maintainer, 'GET', `/runner/wiki/spaces/${s.spaceId}/docs`);
  expectStatus(state, 200, 'what is written');
  const doc = state.body.docs.find((d: { slug: string }) => d.slug === 'session-runtime');
  assert.deepEqual(doc.sections.map((sec: { key: string; stale: boolean; repoSha: string }) => [sec.key, sec.stale, sec.repoSha]), [['s3', true, HEAD]]);
  const page = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/session-runtime`);
  expectStatus(page, 200, 'the page');
  const s3 = page.body.sections.find((sec: { key: string }) => sec.key === 's3');
  assert.equal(s3.stale, true);
  assert.equal(s3.blocks[0].sentences[0].withdrawn.reason, 'rejected');
  assert.equal(toUuid(s3.blocks[0].sentences[0].withdrawn.entryId as string), a);
  assert.deepEqual(page.body.counts, { sentences: 4, sourced: 1, transition: 0, unsourced: 0, unverified: 0, withdrawn: 3 });
  const viaA = page.body.entries.find((entry: { id: string }) => toUuid(entry.id) === a);
  assert.equal(viaA.status, 'rejected');
  assert.deepEqual(viaA.notes, [1]);
  const directory = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs`);
  const listed = directory.body.categories[0].docs.find((d: { slug: string }) => d.slug === 'session-runtime');
  assert.equal(listed.sections.find((sec: { key: string }) => sec.key === 's3').stale, true);

  // The next run writes it again even from the same material, and it is whole again.
  const rewrite = await writeDoc(h, s, 'session-runtime', writeBody(version, [{
    key: 's3',
    material,
    markdown: '提交 9c7de42a 带了 6 个新文件[1]。',
    footnotes: [{ kind: 'task_comment', ref: s.r.c1, quote: '6 个新文件 / 7 个改动文件' }],
  }]));
  expectStatus(rewrite, 200, 'the rewrite');
  assert.equal(rewrite.body.sections[0].outcome, 'written', 'a stale section is written again whatever its fingerprint');
  section = await statuses();
  assert.equal(section.staleAt, null);
  assert.deepEqual(section.sentences.map((sentence) => sentence.status), ['sourced']);

  // A write citing through an entry already rejected keeps that sentence withdrawn, and its section stale, at once.
  const late = await writeDoc(h, s, 'session-runtime', writeBody(version, [{
    key: 's4',
    markdown: 'turn 先落库[1]。它先落库才投递[2]。',
    footnotes: [{ kind: 'turn', ref: s.r.t1, quote: '先存后投：turn 先落库', viaEntryId: a }, { kind: 'turn', ref: s.r.t1, quote: 'turn 先落库' }],
  }]));
  expectStatus(late, 200, 'a write through a rejected entry');
  const s4 = (await stored(h, s.spaceId, 'session-runtime')).sections.get('s4')!;
  assert.deepEqual(s4.sentences.map((sentence) => [sentence.status, sentence.withdrawnReason]), [['withdrawn', 'rejected'], ['sourced', null]]);
  assert.ok(s4.staleAt);
});

// ── 7. a view, not knowledge ────────────────────────────────────────────────────────────────────

test('a document is not in the push block, is never a source, and is not what an agent\'s search or get returns', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const version = await confirmPlan(h, s);
  const principle = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/changesets`, {
    rationale: 'something the push always carries',
    ops: [{ op: 'add', entry: { kind: 'principle', title: 'Completion is adjudicated, not claimed', summary: 'The declared criterion decides.', fields: { statement: 'Completion is adjudicated.', rationale: 'Self-reported done is how failures pass.' } } }],
  });
  expectStatus(principle, 200, 'the owner writes a principle');
  const phrase = '紫色长颈鹿只在文档里出现';
  const written = await writeDoc(h, s, 'session-runtime', writeBody(version, [{
    key: 's1',
    markdown: `${phrase}，先存后投[1]。`,
    footnotes: [{ kind: 'turn', ref: s.r.t1, quote: '先存后投：turn 先落库' }],
  }]));
  expectStatus(written, 200, 'the document');
  const { doc, sections } = await stored(h, s.spaceId, 'session-runtime');
  const section = sections.get('s1')!;
  const ids = [doc!.id, section.id, section.sentences[0].id, section.sentences[0].footnotes[0].id];

  // The push: an ordinary session of the bound workspace is handed entries, and nothing of the document.
  const pushed = await h.prisma.$transaction((tx) => appendWikiContext(tx, {
    sessionId: s.ordinary,
    turnId: randomUUID(),
    leaseGeneration: randomUUID(),
    ownerId: s.owner.id,
    workspaceId: s.ws,
    taskId: null,
    task: null,
    dispatchOrigin: null,
    content: '先存后投 与 inbox 领取',
  }, ON));
  assert.ok(pushed && pushed.includes('<orbit_wiki_context'), `the session is pushed its space's entries: ${String(pushed).slice(0, 300)}`);
  assert.ok(!pushed.includes(phrase), 'no sentence of the document is in the block');
  for (const id of ids) assert.ok(!pushed.includes(id) && !pushed.includes(b62(id)), 'nor any of its ids');
  const exposures = await h.prisma.wikiExposure.findMany({ where: { sessionId: s.ordinary }, select: { entryId: true } });
  const entryIds = new Set((await h.prisma.wikiEntry.findMany({ where: { spaceId: s.spaceId }, select: { id: true } })).map((e) => e.id));
  assert.ok(exposures.length > 0);
  for (const exposure of exposures) assert.ok(entryIds.has(exposure.entryId), 'every line pushed is an entry');

  // A source: the document, a section, a sentence or a footnote, in any kind a source takes, resolves to nothing.
  const agent: Caller = { runner: s.runner.token, session: s.ordinary };
  for (const kind of ['note', 'task', 'event', 'turn', 'tool_call', 'task_comment', 'approval', 'merge_receipt', 'owner_decision']) {
    for (const id of ids) {
      const cited = await call(h, agent, 'POST', '/runner/wiki/changesets', {
        rationale: 'citing a document',
        idempotencyKey: `cite-doc-${kind}-${randomUUID()}`,
        ops: [{ op: 'add', entry: { kind: 'concept', title: `As the document says (${kind})`, summary: '文档这样说。', fields: { definition: 'x', boundaries: 'y' } }, sources: [{ kind, ref: b62(id) }] }],
      });
      expectStatus(cited, 422, `a document row cited as a ${kind} source`);
      assert.equal(cited.body.ops[0].reasons[0].code, 'WIKI_SOURCE_UNRESOLVED', `a document is never a ${kind} source`);
    }
  }
  // A footnote kind of its own is no source kind at all.
  const asFootnote = await call(h, agent, 'POST', '/runner/wiki/changesets', {
    rationale: 'citing a design document the way a footnote does',
    idempotencyKey: `cite-design-${randomUUID()}`,
    ops: [{ op: 'add', entry: { kind: 'concept', title: 'Per the design document', summary: '设计文档这样说。', fields: { definition: 'x', boundaries: 'y' } }, sources: [{ kind: 'design_doc', ref: 'docs/wiki-design.md' }] }],
  });
  expectStatus(asFootnote, 400, 'a design document cited as a source');
  assert.equal(asFootnote.body.ops[0].reasons[0].code, 'WIKI_SCHEMA');

  // An agent's search and get: entries only.
  const search = await call(h, agent, 'GET', `/runner/wiki/search?q=${encodeURIComponent(phrase)}`);
  expectStatus(search, 200, 'an agent searches for the document\'s own words');
  assert.ok(Array.isArray(search.body.hits));
  const hits = JSON.stringify(search.body.hits);
  assert.ok(!hits.includes(phrase), `the document is not a hit: ${hits.slice(0, 300)}`);
  for (const id of ids) assert.ok(!hits.includes(b62(id)) && !hits.includes(id));
  for (const id of ids) expectStatus(await call(h, agent, 'GET', `/runner/wiki/entries/${b62(id)}`), 404, 'an agent gets a document row by its id');
});

// ── 8. tenancy, and who writes ──────────────────────────────────────────────────────────────────

test('another owner reads none of it, and writes none of it: every route is a 404', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const version = await confirmPlan(h, s);
  expectStatus(await writeDoc(h, s, 'session-runtime', writeBody(version, [{
    key: 's2',
    markdown: 'Runner 通过出站 long-poll 从 inbox 领取 turn[1]。',
    footnotes: [{ kind: 'turn', ref: s.r.t1, quote: '先存后投：turn 先落库' }],
  }])), 200, 'the owner\'s document');
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/session-runtime`), 200, 'the owner reads it');

  const stranger = await scene(h, 'The stranger\'s own space');
  for (const route of [`/wiki/spaces/${s.spaceId}/docs`, `/wiki/spaces/${s.spaceId}/docs/session-runtime`, `/wiki/spaces/${s.spaceId}/doc-index`]) {
    const answer = await call(h, { bearer: stranger.owner.bearer }, 'GET', route);
    expectStatus(answer, 404, `another owner reads ${route}`);
    assert.ok(!JSON.stringify(answer.body).includes('会话运行模型'), 'and learns nothing of it');
  }
  // Another owner's maintenance run, on their own runner: the same 404, and nothing moves.
  expectStatus(await call(h, stranger.maintainer, 'GET', `/runner/wiki/spaces/${s.spaceId}/docs`), 404, 'another owner\'s run reads what is written');
  expectStatus(await writeDoc(h, s, 'session-runtime', writeBody(version, [{ key: 's1', markdown: '别人写的[1]。', footnotes: [code('x')] }]), stranger.maintainer), 404,
    'another owner\'s run writes');
  assert.deepEqual([...(await stored(h, s.spaceId, 'session-runtime')).sections.keys()], ['s2']);
  // Their own space has no plan: an empty directory, and no document.
  const theirs = await call(h, { bearer: stranger.owner.bearer }, 'GET', `/wiki/spaces/${stranger.spaceId}/docs`);
  expectStatus(theirs, 200, 'their own directory');
  assert.deepEqual([theirs.body.plan, theirs.body.categories], [null, []]);
  expectStatus(await call(h, { bearer: stranger.owner.bearer }, 'GET', `/wiki/spaces/${stranger.spaceId}/docs/session-runtime`), 404, 'no such document in their space');
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${randomUUID()}/docs`), 404, 'an unknown space');
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/no-such-doc`), 404, 'a document the plan does not have');

  // Only a maintenance run of the space writes: not an ordinary session, not a headless call, not the owner's door.
  const body = writeBody(version, [{ key: 's1', markdown: '一句[1]。', footnotes: [code('x')] }]);
  const ordinary = await writeDoc(h, s, 'session-runtime', body, { runner: s.runner.token, session: s.ordinary });
  expectStatus(ordinary, 403, 'an ordinary session writes');
  assert.equal(ordinary.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
  expectStatus(await writeDoc(h, s, 'session-runtime', body, { runner: s.runner.token }), 400, 'a headless write');
  expectStatus(await call(h, { runner: s.runner.token, session: s.ordinary }, 'GET', `/runner/wiki/spaces/${s.spaceId}/docs`), 403, 'an ordinary session reads what is written');
  for (const method of ['POST', 'PUT', 'PATCH']) {
    expectStatus(await call(h, { bearer: s.owner.bearer }, method, `/wiki/spaces/${s.spaceId}/docs/session-runtime`, body), 404, `the owner ${method}s a document on the user door`);
  }
  assert.deepEqual([...(await stored(h, s.spaceId, 'session-runtime')).sections.keys()], ['s2'], 'none of them wrote anything');
});

// ── the reads ───────────────────────────────────────────────────────────────────────────────────

test('the directory, a document and the index follow the confirmed plan: numbers, scope, what is written and what is not', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const version = await confirmPlan(h, s);
  const quote = { kind: 'turn', ref: s.r.t1, quote: '先存后投：turn 先落库' };
  expectStatus(await writeDoc(h, s, 'session-runtime', writeBody(version, [
    { key: 's2', markdown: 'turn 先落库[1]。它才投递给 runner[1]。', footnotes: [quote] },
  ])), 200, 'one section of one document');

  const directory = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs`);
  expectStatus(directory, 200, 'the directory');
  assert.equal(directory.body.plan.version, version);
  assert.deepEqual(directory.body.docs, { total: 3, written: 1 });
  assert.deepEqual(directory.body.categories.map((c: { key: string; number: number; forAgents: boolean }) => [c.key, c.number, c.forAgents]), [['product', 1, false], ['dev', 2, true]]);
  const [runtime, dispatch] = directory.body.categories[0].docs;
  assert.deepEqual([runtime.slug, runtime.number, runtime.written, runtime.status, runtime.planVersion], ['session-runtime', '1.1', true, 'ok', version]);
  assert.deepEqual([dispatch.slug, dispatch.number, dispatch.written, dispatch.status], ['task-dispatch', '1.2', false, null]);
  assert.equal(directory.body.categories[1].docs[0].number, '2.1');
  assert.deepEqual(runtime.sections.map((sec: { key: string; number: number; written: boolean }) => [sec.key, sec.number, sec.written]), [['s1', 1, false], ['s2', 2, true], ['s3', 3, false], ['s4', 4, false]]);

  const page = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/session-runtime`);
  expectStatus(page, 200, 'the document');
  assert.deepEqual([page.body.number, page.body.title, page.body.category.title, page.body.written], ['1.1', '会话运行模型与长连接', 'Product', true]);
  assert.deepEqual(page.body.scopeOut, [{ text: '任务怎么派发', docs: [{ slug: 'task-dispatch', number: '1.2', title: '任务派发与领取' }] }]);
  assert.deepEqual([page.body.planVersion, page.body.writtenFromPlanVersion, page.body.repoSha], [version, version, HEAD]);
  assert.deepEqual(page.body.sections.map((sec: { key: string; written: boolean }) => [sec.key, sec.written]), [['s1', false], ['s2', true], ['s3', false], ['s4', false]]);
  const s2 = page.body.sections[1];
  assert.equal(s2.title, 'turn 投递与 inbox 领取');
  assert.equal(s2.repoSha, HEAD);
  assert.deepEqual(s2.blocks[0].sentences.map((sentence: { notes: number[] }) => sentence.notes), [[1], [1]], 'one original, one quote: one footnote number');
  assert.equal(page.body.footnotes.length, 1);

  const unwritten = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/task-dispatch`);
  expectStatus(unwritten, 200, 'a document of the plan nobody has written');
  assert.deepEqual([unwritten.body.written, unwritten.body.status, unwritten.body.counts.sentences], [false, null, 0]);
  assert.ok(unwritten.body.sections.every((sec: { written: boolean; blocks: unknown[] }) => !sec.written && sec.blocks.length === 0));

  const index = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/doc-index`);
  expectStatus(index, 200, 'the index');
  const titles = index.body.items.map((item: { title: string }) => item.title);
  // The generic section titles every document has are left out; the rest are in, A to Z.
  for (const generic of ['总览', '已知的坑', '约定']) assert.ok(!titles.includes(generic), `${generic} is in the index`);
  for (const specific of ['会话运行模型与长连接', '任务派发与领取', '测试与 CI 约定', 'turn 投递与 inbox 领取', '派发的三步握手', 'pg spec 怎么跑']) {
    assert.ok(titles.includes(specific), `${specific} is not in the index`);
  }
  assert.deepEqual([...titles].sort((a: string, b: string) => (a.toLowerCase() < b.toLowerCase() ? -1 : a.toLowerCase() > b.toLowerCase() ? 1 : 0)), titles);
  const flow = index.body.items.find((item: { title: string }) => item.title === 'turn 投递与 inbox 领取');
  assert.deepEqual([flow.kind, flow.docNumber, flow.sectionKey, flow.sectionNumber, flow.written], ['section', '1.1', 's2', 2, true]);
  const docItem = index.body.items.find((item: { title: string }) => item.title === '任务派发与领取');
  assert.deepEqual([docItem.kind, docItem.written], ['doc', false]);
});

test('a written document\'s lead on the directory: its first section\'s first two sentences, a withdrawn one skipped, a long one cut; none until it is written', { skip }, async () => {
  const h = await boot();
  const s = await scene(h, 'A space with leads');
  const runbook: DocSpec = { slug: 'ops-runbook', category: 'dev', title: '回滚手册', question: '出了事怎么回滚？', sections: [['总览', 'overview'], ['怎么回滚', 'ops']] };
  const version = await confirmPlan(h, s, [...DOCS, runbook]);
  // session-runtime: the first sentence of its first section cites a file a later run finds deleted. Its
  // second section is written too, and lends the lead nothing.
  expectStatus(await writeDoc(h, s, 'session-runtime', writeBody(version, [
    { key: 's2', markdown: 'inbox 最多 hold 25 秒。', footnotes: [] },
    { key: 's1', markdown: 'Orbit 的会话跑在 runner 上[1]。turn 先落库再投递。它不用 WebSocket。', footnotes: [code('export function claimTask(', { path: 'src/gone.ts' })] },
  ])), 200, 'session-runtime is written');
  // task-dispatch: two English sentences, longer together than a lead holds.
  const first = 'Dispatch hands a task to exactly one runner, which claims it atomically and opens a session for it; a runner that crashes mid-claim leaves the task to be claimed again.';
  const second = 'The claim is one UPDATE guarded by the task status, so two runners racing for one task cannot both win it.';
  expectStatus(await writeDoc(h, s, 'task-dispatch', writeBody(version, [{ key: 's1', markdown: `${first} ${second}`, footnotes: [] }])), 200, 'task-dispatch is written');
  // ops-runbook: written, but not its first section.
  expectStatus(await writeDoc(h, s, 'ops-runbook', writeBody(version, [{ key: 's2', markdown: '回滚前先停写入。', footnotes: [] }])), 200, 'ops-runbook is written');

  const leads = async (): Promise<Map<string, [boolean, string | null]>> => {
    const directory = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs`);
    expectStatus(directory, 200, 'the directory');
    const docs: Array<{ slug: string; written: boolean; lead: string | null }> = directory.body.categories.flatMap((c: { docs: unknown[] }) => c.docs);
    return new Map(docs.map((doc) => [doc.slug, [doc.written, doc.lead]]));
  };
  let read = await leads();
  assert.deepEqual(read.get('session-runtime'), [true, 'Orbit 的会话跑在 runner 上。turn 先落库再投递。'], 'its first section\'s first two sentences, as they read');
  const both = `${first} ${second}`;
  assert.ok(first.length < WIKI_DOC_LEAD_RULES.maxChars && both.length > WIKI_DOC_LEAD_RULES.maxChars, 'the cut falls in the second sentence');
  assert.deepEqual(read.get('task-dispatch'), [true, `${both.slice(0, WIKI_DOC_LEAD_RULES.maxChars).trimEnd()}…`], 'a space after a full stop, and cut with an ellipsis');
  assert.deepEqual(read.get('dev-testing'), [false, null], 'a document not written has none');
  assert.deepEqual(read.get('ops-runbook'), [true, null], 'nor has one whose first section is not written');

  // The file the first sentence cites is gone from origin/main: the sentence is withdrawn, and the lead reads past it.
  const withdrawn = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/maintenance/docs/withdrawals`, {
    repoSha: HEAD,
    paths: [{ path: 'src/gone.ts', change: 'deleted' }],
  });
  expectStatus(withdrawn, 200, 'the run withdraws what cites the deleted file');
  assert.equal(withdrawn.body.withdrawn, 1);
  read = await leads();
  assert.deepEqual(read.get('session-runtime'), [true, 'turn 先落库再投递。它不用 WebSocket。'], 'the withdrawn sentence is skipped');
});

// ── the schema ──────────────────────────────────────────────────────────────────────────────────

test('the migration\'s CHECKs are the contract\'s closed sets, and deleting the space deletes its documents', { skip }, async () => {
  const h = await boot();
  assert.deepEqual(await checkValues(h, 'wiki_doc', 'wiki_doc_status_chk'), [...WIKI_DOC_STATUSES]);
  assert.deepEqual(await checkValues(h, 'wiki_doc_sentence', 'wiki_doc_sentence_status_chk'), [...WIKI_DOC_SENTENCE_STATUSES]);
  assert.deepEqual(await checkValues(h, 'wiki_doc_sentence', 'wiki_doc_sentence_withdrawn_reason_chk'), [...WIKI_DOC_WITHDRAW_REASONS]);
  assert.deepEqual(await checkValues(h, 'wiki_doc_footnote', 'wiki_doc_footnote_kind_chk'), [...WIKI_DOC_FOOTNOTE_KINDS]);
  assert.deepEqual(await checkValues(h, 'wiki_doc_footnote', 'wiki_doc_footnote_verdict_chk'), [...WIKI_DOC_VERDICTS]);
  assert.deepEqual(await checkValues(h, 'wiki_doc_footnote', 'wiki_doc_footnote_checked_by_chk'), [...WIKI_DOC_CHECKERS]);
  assert.deepEqual(CONTRACT.docs.tables, ['wiki_doc', 'wiki_doc_section', 'wiki_doc_sentence', 'wiki_doc_footnote']);

  const s = await scene(h);
  const version = await confirmPlan(h, s);
  expectStatus(await writeDoc(h, s, 'session-runtime', writeBody(version, [{
    key: 's2',
    markdown: '派发由 `claimTask` 开始[1]。',
    footnotes: [code('export function claimTask(')],
  }])), 200, 'a document');
  const { sections } = await stored(h, s.spaceId, 'session-runtime');
  const sentence = sections.get('s2')!.sentences[0];
  // A repository footnote with no sha, written past the service, is refused by its CHECK.
  const unpinned = await h.sql.query(
    `INSERT INTO "wiki_doc_footnote"("id","sentence_id","owner_id","position","kind","ref","verdict","checked_by","quote")
     VALUES ($1,$2,$3,5,'code','src/x.ts','verified','runner','x')`,
    [randomUUID(), sentence.id, s.owner.id],
  ).then(() => null, (e: Error) => e);
  assert.ok(unpinned, 'a code footnote with no sha was stored');
  assert.match(unpinned.message, /wiki_doc_footnote_repository_chk/u);
  // A withdrawn sentence that says nothing of why is refused by its CHECK.
  const unexplained = await h.sql.query(`UPDATE "wiki_doc_sentence" SET "status" = 'withdrawn' WHERE "id" = $1`, [sentence.id]).then(() => null, (e: Error) => e);
  assert.ok(unexplained, 'a withdrawal with no reason was stored');
  assert.match(unexplained.message, /wiki_doc_sentence_withdrawn_chk/u);

  await h.sql.query(`DELETE FROM "wiki_space" WHERE "id" = $1`, [s.spaceId]);
  const left = await h.sql.query<{ n: number }>(
    `SELECT ((SELECT count(*) FROM "wiki_doc" WHERE "owner_id" = $1)
           + (SELECT count(*) FROM "wiki_doc_section" WHERE "owner_id" = $1)
           + (SELECT count(*) FROM "wiki_doc_sentence" WHERE "owner_id" = $1)
           + (SELECT count(*) FROM "wiki_doc_footnote" WHERE "owner_id" = $1))::int AS n`,
    [s.owner.id],
  );
  assert.equal(left.rows[0].n, 0);
});
