/**
 * The reads that let the owner take back ANY run (criterion 8; contracts/wiki.contract.json
 * `reviewModes.run`), over real HTTP and against a real PostgreSQL.
 *
 * Criterion 8 asks that the entries one run applied can be taken back as a whole. The clients could
 * only open a run that still had a card in Review — the one read that tied an op to its changeset —
 * and an Automatic run draws no spot check by default, so once its verdicts applied it there was
 * nothing left to open it from. What is under test is the three reads that close that gap:
 *
 *   1. the timeline names each op's changeset, and the review mode that applied any op of it;
 *   2. `GET /api/wiki/changesets/:id` reads such a run — every op settled, nothing in Review — with
 *      what it did counted and what Revert run… would undo, by the revert's own rules; another
 *      account's is a 404, and a request carrying a session header is refused;
 *   3. an entry's read says where its current revision came from: the changeset, the mode that
 *      applied it and the verdict it was applied on;
 *
 * and, beside them, the article read naming the entries it was written from (`entryIds`, the pool its
 * generation stored), which is what the list under an article is drawn from.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-run-reads.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs; the verdicts
 * are recorded through `WikiService.recordVerifications`, the call the runner door's route makes.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { toUuid, uuidToBase62, WIKI_LIMITS, type WikiKind } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiArticles } from './wiki-articles';
import { WikiArticlesController } from './wiki-articles.controller';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiRunReads } from './wiki-run-reads';
import { WikiRunsController } from './wiki-runs.controller';
import { WikiController } from './wiki.controller';
import { WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  articles: WikiArticles;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = { notifyWikiReviewModeTripped: async () => undefined, notifyWikiVerificationTripped: async () => undefined } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);
    const articles = new WikiArticles(prisma as unknown as PrismaService, hub);

    @Module({
      controllers: [WikiController, WikiRunsController, WikiArticlesController, RunnerWikiController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiArticles, useValue: articles },
        { provide: WikiRunReads, useValue: new WikiRunReads(prisma as unknown as PrismaService) },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiRunReadsModule {}

    const app = await NestFactory.create(WikiRunReadsModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, articles, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  headers?: Record<string, string>;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json', ...(who.headers ?? {}) };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

interface Outcome {
  seq: number;
  status: 'pending' | 'applied' | 'conflict' | 'refused';
  opId?: string | null;
  entryId?: string | null;
  waitsFor?: string;
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-run-reads-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id") VALUES ($1,'spec',$2)`, [id, ownerId]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string, runnerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "dispatch_origin","updated_at")
     VALUES ($1,'a wiki session','p',$2,$2,$3,$4,'USER',now())`,
    [id, ownerId, workspaceId, runnerId],
  );
  return id;
}

async function toolCall(h: Harness, sessionId: string, output: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","output") VALUES ($1,$2,'Bash',$3)`, [
    id,
    sessionId,
    JSON.stringify(output),
  ]);
  return id;
}

/** A space the owner makes through the door, in Automatic, bound to the workspace. */
async function automaticSpace(h: Harness, owner: Account, workspaceId: string, title: string): Promise<string> {
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title });
  expectStatus(made, 201, 'the owner creates a space');
  const id = made.body.id as string;
  const switched = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${id}`, { reviewMode: 'automatic' });
  expectStatus(switched, 200, 'the owner puts the space in Automatic');
  assert.equal(switched.body.settings.reviewMode, 'automatic');
  assert.equal(switched.body.settings.automaticSpotChecks, false, 'Automatic draws no spot check by default');
  const bound = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${id}/workspaces`, { workspaceId });
  expectStatus(bound, 200, 'the owner binds the workspace');
  return toUuid(id);
}

function draft(kind: WikiKind, title: string, summary = `What the space knows about ${title.toLowerCase()}.`): Record<string, unknown> {
  const fields: Partial<Record<WikiKind, Record<string, unknown>>> = {
    convention: { rule: 'Model a closed set as TEXT plus a CHECK constraint.', scope: ['src/apiserver/prisma/migrations/**'] },
    pitfall: {
      trigger: { paths: ['src/apiserver/src/wiki/'], commands: ['node --test build/wiki/x.pg.spec.js'] },
      symptom: 'A green run that witnessed no assertion.',
      cause: 'A pg spec skips itself without a database.',
      fix: 'Run it through scripts/run-pg-spec.sh.',
    },
    concept: { definition: 'One owner\'s knowledge about one codebase.', boundaries: 'A space never spans owners.' },
  };
  return { kind, title, summary, fields: fields[kind] };
}

function agent(ownerId: string, sessionId: string): WikiPrincipal {
  return { origin: 'agent', ownerId, userId: null, sessionId, toolCallId: null };
}

function importer(ownerId: string): WikiPrincipal {
  return { origin: 'import', ownerId, userId: null, sessionId: null, toolCallId: null, authorKind: 'system' };
}

/** Each op that waits for its verification, given the verdict named for it by its position. */
async function verify(
  h: Harness,
  proposer: WikiPrincipal,
  spaceId: string,
  outcomes: readonly Outcome[],
  verdicts: ReadonlyArray<'supported' | 'partial'>,
): Promise<void> {
  const waiting = outcomes.filter((outcome) => outcome.status === 'pending' && outcome.waitsFor === 'verification');
  assert.equal(waiting.length, verdicts.length, 'a verdict for every op that waits for one');
  assert.ok(waiting.length <= WIKI_LIMITS.opsPerChangeset);
  const done = await h.service.recordVerifications(proposer, spaceId, waiting.map((outcome, i) => ({
    opId: outcome.opId!,
    verdict: verdicts[i],
    reason: verdicts[i] === 'supported' ? 'The cited record says so.' : 'The cited record says part of it.',
    model: 'qwen3.8-27b-fp8',
  })));
  for (const outcome of done.outcomes) assert.equal(outcome.status, 'applied', JSON.stringify(outcome));
}

const b62 = (id: string): string => uuidToBase62(toUuid(id));

// ── a run nothing of which waits in Review ──────────────────────────────────────────────────────

test('run reads · an Automatic run fully applied, with nothing in Review, is still read, counted and revertible', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'run-reads');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await automaticSpace(h, owner, ws, 'An automatic space');
  const records = await session(h, owner.id, ws, machine.id);
  const evidence = await toolCall(h, records, 'what the maintenance run found');
  const cite = [{ kind: 'tool_call', ref: evidence, quote: 'what the maintenance run found' }];

  // What the space held before the run: a convention an earlier import applied, and one the owner wrote.
  const earlier = await h.service.submitChangeset(importer(owner.id), space, {
    rationale: 'the space\'s first batch',
    ops: [{ op: 'add', entry: draft('convention', 'Migrations take the next free number', 'A migration takes the first free number on main.'), sources: [{ kind: 'tool_call', ref: evidence }] }],
    idempotencyKey: `earlier-${randomUUID()}`,
  });
  await verify(h, importer(owner.id), space, earlier.ops as Outcome[], ['supported']);
  const amended = toUuid((earlier.ops as Outcome[])[0].entryId!);
  const owners = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${space}/changesets`, {
    rationale: 'the owner writes one down',
    ops: [{ op: 'add', entry: draft('concept', 'A space is one owner\'s') }],
  });
  expectStatus(owners, 200, 'the owner\'s own write');
  const ownerEntry = toUuid(owners.body.ops[0].entryId);

  // The run: two adds and an amend, applied by their verdicts — two supported, one partly.
  const proposer = await session(h, owner.id, ws, machine.id);
  const run = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': proposer } }, 'POST', '/runner/wiki/changesets', {
    rationale: 'a maintenance run',
    ops: [
      { op: 'add', entry: draft('convention', 'A convention the run wrote'), sources: cite },
      { op: 'add', entry: draft('pitfall', 'A pitfall the run wrote'), sources: cite },
      { op: 'amend', entryId: amended, baseRevision: 1, changes: { summary: 'A migration takes the first free number on origin/main.' }, sources: cite },
    ],
  });
  expectStatus(run, 200, 'the run');
  assert.deepEqual((run.body.ops as Outcome[]).map((op) => op.waitsFor), ['verification', 'verification', 'verification']);
  await verify(h, agent(owner.id, proposer), space, run.body.ops as Outcome[], ['supported', 'partial', 'supported']);
  const runId = b62(run.body.changesetId as string);
  const [added, partly] = (run.body.ops as Outcome[]).map((op) => toUuid(op.entryId!));

  await t.test('Review holds nothing of it: the one read the clients had could not open it', async () => {
    const review = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/review?space=${b62(space)}`);
    expectStatus(review, 200, 'the space\'s Review');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    assert.equal(review.body.some((changeset: any) => changeset.id === runId), false, 'the run is not in Review');
    const ops = await h.prisma.wikiChangesetOp.findMany({ where: { changesetId: toUuid(runId) }, orderBy: { seq: 'asc' } });
    assert.deepEqual(ops.map((op) => [op.decision, op.appliedByMode, op.spotCheck]), [
      ['auto_applied', 'automatic', false],
      ['auto_applied', 'automatic', false],
      ['auto_applied', 'automatic', false],
    ]);
  });

  await t.test('the timeline names each op\'s changeset, and the mode that applied the run', async () => {
    const timeline = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${b62(space)}/timeline?limit=50`);
    expectStatus(timeline, 200, 'the timeline');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const items: any[] = timeline.body.items;
    const ops = await h.prisma.wikiChangesetOp.findMany({ where: { ownerId: owner.id }, select: { id: true, changesetId: true } });
    const changesetOf = new Map(ops.map((op) => [op.id, op.changesetId]));
    assert.ok(items.length >= 5, `every applied op is listed: ${items.length}`);
    for (const item of items) {
      assert.equal(typeof item.changesetId, 'string', `${item.opId} names its changeset`);
      assert.equal(item.changesetId, b62(changesetOf.get(toUuid(item.opId))!), `${item.opId} names the changeset it came in, as a public id`);
    }
    const ofRun = items.filter((item) => item.changesetId === runId);
    assert.deepEqual(ofRun.map((item) => toUuid(item.entryId)).sort(), [added, partly, amended].sort(), 'the run\'s three ops');
    for (const item of ofRun) {
      assert.equal(item.changesetAppliedByMode, 'automatic', 'the run was applied by Automatic');
      assert.equal(item.origin, 'agent', 'origin is the changeset\'s');
    }
    const ofOwner = items.find((item) => item.entryId && toUuid(item.entryId) === ownerEntry);
    assert.equal(ofOwner.changesetId, b62(owners.body.changesetId), 'the owner\'s write names its own changeset');
    assert.equal(ofOwner.changesetAppliedByMode, null, 'no mode applied the owner\'s write: it is no run');
  });

  await t.test('the run is read by its id: its ops, its entries, what it did, and what Revert would undo', async () => {
    const read = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/changesets/${runId}`);
    expectStatus(read, 200, 'the run\'s read');
    const view = read.body;
    assert.equal(view.id, runId);
    assert.equal(view.spaceId, b62(space));
    assert.equal(view.origin, 'agent');
    assert.equal(view.sessionId, b62(proposer));
    assert.equal(view.status, 'settled', 'nothing of it waits for anybody');
    assert.equal(view.appliedByMode, 'automatic');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    assert.deepEqual(view.ops.map((op: any) => [op.op, op.decision, op.verification?.verdict, op.verification?.model]), [
      ['add', 'auto_applied', 'supported', 'qwen3.8-27b-fp8'],
      ['add', 'auto_applied', 'partial', 'qwen3.8-27b-fp8'],
      ['amend', 'auto_applied', 'supported', 'qwen3.8-27b-fp8'],
    ]);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const entries = new Map<string, any>(view.entries.map((entry: any) => [toUuid(entry.id), entry]));
    assert.deepEqual([...entries.keys()].sort(), [added, partly, amended].sort(), 'every entry its ops name, and no other');
    assert.deepEqual([entries.get(added).trust, entries.get(partly).trust, entries.get(amended).trust], ['auto', 'unreviewed', 'auto']);
    assert.equal(entries.get(amended).currentRevision, 2, 'as it stands now');
    assert.deepEqual(view.counts, { applied: 3, auto: 2, unreviewed: 1, rejectedByCheck: 0, toReview: 0 });
    assert.equal(view.revertible, true, 'the run can be taken back though nothing of it is in Review');
    assert.deepEqual(view.revert, { adds: 2, amends: 1 });
  });

  await t.test('another account\'s run is a 404, and a request carrying a session header is refused', async () => {
    const stranger = await account(h, 'stranger');
    expectStatus(await call(h, { bearer: stranger.bearer }, 'GET', `/wiki/changesets/${runId}`), 404, 'another account reads the run');
    expectStatus(await call(h, { bearer: stranger.bearer }, 'GET', `/wiki/changesets/${toUuid(runId)}`), 404, 'by its UUID too');
    expectStatus(await call(h, { bearer: owner.bearer }, 'GET', `/wiki/changesets/${b62(randomUUID())}`), 404, 'a changeset that does not exist');
    expectStatus(await call(h, { bearer: owner.bearer }, 'GET', '/wiki/changesets/not-an-id'), 400, 'an id that is no id');
    for (const header of ['x-orbit-session-id', 'x-orbit-session-token']) {
      const refused = await call(h, { bearer: owner.bearer, headers: { [header]: proposer } }, 'GET', `/wiki/changesets/${runId}`);
      expectStatus(refused, 403, `the owner's credential carrying ${header}`);
      assert.equal(refused.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
    }
    const headless = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': proposer } }, 'GET', `/wiki/changesets/${runId}`);
    expectStatus(headless, 401, 'a runner credential is no JWT');
  });

  await t.test('an entry\'s read says where its current revision came from', async () => {
    const read = async (id: string) => {
      const answer = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/entries/${b62(id)}?include=history`);
      expectStatus(answer, 200, `entry ${id}`);
      return answer.body;
    };
    const supported = await read(added);
    assert.equal(supported.changesetId, runId, 'the run wrote it');
    assert.equal(supported.appliedByMode, 'automatic');
    assert.deepEqual(
      { verdict: supported.verification.verdict, model: supported.verification.model, reason: supported.verification.reason },
      { verdict: 'supported', model: 'qwen3.8-27b-fp8', reason: 'The cited record says so.' },
    );
    const partial = await read(partly);
    assert.equal(partial.trust, 'unreviewed');
    assert.deepEqual([partial.changesetId, partial.appliedByMode, partial.verification.verdict], [runId, 'automatic', 'partial']);
    assert.equal(partial.verification.reason, 'The cited record says part of it.');
    // The amended entry's current revision is the run's amend, not the import that first wrote it.
    const changed = await read(amended);
    assert.equal(changed.currentRevision, 2);
    assert.deepEqual([changed.changesetId, changed.appliedByMode, changed.verification.verdict], [runId, 'automatic', 'supported']);
    // What the owner wrote: its changeset, no mode, no verdict.
    const own = await read(ownerEntry);
    assert.deepEqual([own.changesetId, own.appliedByMode, own.verification], [b62(owners.body.changesetId), null, null]);
    // The runner door's read is an agent's, and says none of it.
    const agentRead = await call(h, { runner: machine.token, headers: { 'x-orbit-session-id': proposer } }, 'GET', `/runner/wiki/entries/${b62(added)}`);
    expectStatus(agentRead, 200, 'a session of the bound workspace reads the entry');
    assert.equal(toUuid(agentRead.body.id), added);
    for (const key of ['changesetId', 'appliedByMode', 'verification']) {
      assert.equal(key in agentRead.body, false, `an agent is not handed ${key}`);
    }
  });

  await t.test('what Revert would undo is what it undoes: what the owner answered or changed since is neither counted nor touched', async () => {
    const read = async (why: string) => {
      const answer = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/changesets/${runId}`);
      expectStatus(answer, 200, why);
      return answer.body;
    };
    // The owner rejects the partly supported entry: its add is answered, and no revert undoes an answer.
    expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${b62(partly)}/reject`, { reason: 'not_useful' }), 200,
      'the owner rejects the partly supported entry');
    const answered = await read('the run after the reject');
    assert.deepEqual(answered.counts, { applied: 2, auto: 2, unreviewed: 0, rejectedByCheck: 0, toReview: 0 });
    assert.deepEqual(answered.revert, { adds: 1, amends: 1 });
    // The owner edits the amended entry: changed again since, so the revert would leave it as it is.
    const edited = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${b62(space)}/changesets`, {
      rationale: 'the owner says it better',
      ops: [{ op: 'amend', entryId: amended, baseRevision: 2, changes: { summary: 'A migration takes the first free number, checked on main.' } }],
    });
    expectStatus(edited, 200, 'the owner amends the entry the run amended');
    const changed = await read('the run after the owner\'s edit');
    assert.deepEqual(changed.counts, { applied: 2, auto: 1, unreviewed: 0, rejectedByCheck: 0, toReview: 0 },
      'the amended entry no longer stands at the revision the run wrote');
    assert.deepEqual(changed.revert, { adds: 1, amends: 0 });
    assert.equal(changed.revertible, true);

    const reverted = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/changesets/${runId}/revert`);
    expectStatus(reverted, 200, 'the owner reverts the run');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const undone = (reverted.body.ops as any[]).filter((op) => op.status === 'applied');
    assert.equal(undone.length, changed.revert.adds + changed.revert.amends, 'the plan counted exactly what the revert did');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    assert.deepEqual(reverted.body.skipped.map((skip: any) => [toUuid(skip.entryId), skip.reason]), [[amended, 'changed again since']],
      'and what it skipped is what the plan left out');
    assert.equal((await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: added } })).status, 'retired');
    assert.equal((await h.prisma.wikiEntry.findFirstOrThrow({ where: { id: partly } })).status, 'rejected', 'the rejected entry is left alone');

    const after = await read('the run after its revert');
    assert.equal(after.revertible, false, 'nothing is left to take back');
    assert.equal(after.revert, null);
    assert.deepEqual(after.counts, { applied: 2, auto: 0, unreviewed: 0, rejectedByCheck: 0, toReview: 0 },
      'its entries no longer wear the marks it gave them');
    // The revert is the owner's own changeset, and its op is a timeline row of no run.
    const timeline = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/spaces/${b62(space)}/timeline?limit=50`);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const ofRevert = timeline.body.items.filter((item: any) => item.changesetId === b62(reverted.body.changesetId));
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    assert.deepEqual(ofRevert.map((item: any) => [item.op, item.origin, item.changesetAppliedByMode]), [['retire', 'owner', null]]);
  });
});

// ── the entries an article is written from ─────────────────────────────────────────────────────

test('run reads · an article\'s read names the entries it was written from, as its generation stored them', { skip, concurrency: 1, timeout: 300_000 }, async () => {
  const h = await boot();
  const owner = await account(h, 'article-pool');
  const ws = await workspace(h, owner.id);
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: 'An article pool space' });
  expectStatus(made, 201, 'the owner creates a space');
  const space = toUuid(made.body.id);
  const bound = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${made.body.id}/workspaces`, { workspaceId: ws });
  expectStatus(bound, 200, 'the owner binds the workspace');

  // Five entries that name the wiki topic, written by the owner so they apply at once.
  const written = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${made.body.id}/changesets`, {
    rationale: 'what the article is written from',
    ops: ['One', 'Two', 'Three', 'Four', 'Five'].map((n) => ({
      op: 'add',
      entry: { ...draft('concept', `Wiki fact ${n}`, `The wiki's fact number ${n.toLowerCase()}.`), topics: ['wiki'] },
    })),
  });
  expectStatus(written, 200, 'the owner writes five entries');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const ids: string[] = written.body.ops.map((op: any) => toUuid(op.entryId));

  // The server's own import writes the topic's articles: an overview over all five, and a subtopic
  // written from three of them that cites two.
  const principal = importer(owner.id);
  await h.articles.plan(principal, space);
  const input = await h.articles.input(principal, space, 'wiki');
  assert.deepEqual(new Set(input.entries.map((entry) => toUuid(entry.id))), new Set(ids), 'the topic holds the five');
  const answer = await h.articles.write(principal, space, 'wiki', {
    entrySetSha256: input.entrySetSha256,
    ref: '0123456789abcdef0123456789abcdef01234567',
    model: 'qwen3.8-27b-fp8',
    articles: [
      { part: 0, kind: 'overview', title: 'Wiki', markdown: '# Wiki\nThe wiki has five facts[1]. The last one matters most[2].', notes: [ids[0], ids[4]] },
      { part: 1, kind: 'subtopic', title: 'The first facts', markdown: '# First\nThe second fact comes first[1]. The third follows[2].', notes: [ids[1], ids[2]], entries: [ids[3], ids[2], ids[1]] },
    ],
  });
  assert.equal(answer.written, true, JSON.stringify(answer));
  const stored = await h.prisma.wikiTopicSummary.findMany({ where: { ownerId: owner.id, topic: { spaceId: space, slug: 'wiki' } }, orderBy: { part: 'asc' } });
  assert.equal(stored.length, 2);

  for (const row of stored) {
    const route = row.part === 0 ? `/wiki/spaces/${made.body.id}/articles/wiki` : `/wiki/spaces/${made.body.id}/articles/wiki/${row.part}`;
    const read = await call(h, { bearer: owner.bearer }, 'GET', route);
    expectStatus(read, 200, `part ${row.part}`);
    assert.deepEqual(read.body.entryIds, row.entryIds.map(b62), `part ${row.part}: entryIds are the pool its generation stored, as public ids`);
    assert.equal(read.body.entryCount, row.entryIds.length);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const listed: string[] = read.body.entries.map((entry: any) => entry.id);
    assert.deepEqual(new Set(listed), new Set(row.entryIds.map(b62)), `part ${row.part}: the list is those entries`);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const cited: string[] = read.body.footnotes.map((note: any) => note.entryId);
    assert.deepEqual(listed.slice(0, cited.length), cited, `part ${row.part}: the cited ones come first`);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    for (const entry of read.body.entries as any[]) {
      assert.equal(entry.status, 'active');
      assert.equal(typeof entry.title, 'string');
      assert.equal(entry.kind, 'concept');
    }
  }
  assert.deepEqual(new Set(stored[0].entryIds), new Set(ids), 'the overview is written from the whole topic');
  assert.deepEqual(stored[1].entryIds, [ids[3], ids[2], ids[1]], 'the subtopic from the three it was given, in its order');

  const stranger = await account(h, 'stranger-articles');
  expectStatus(await call(h, { bearer: stranger.bearer }, 'GET', `/wiki/spaces/${made.body.id}/articles/wiki`), 404, 'another account reads the article');
});
