/**
 * The plan (criterion 11; contracts/wiki.contract.json `plan`, migration 0325), over real HTTP and
 * against a real PostgreSQL.
 *
 * What the task's verification asks, each read back from the doors and from the database:
 *
 *   1. with no confirmed plan, `requireConfirmedPlan` refuses — a draft is not enough;
 *   2. a revision is a new version, and a confirmed version does not change: its rows are the same
 *      bytes after every later draft, edit and confirmation;
 *   3. the gate stops a draft with a field outside the schema, a document count outside its target, a
 *      protected document changed, or a project or topic that does not exist — and says each one;
 *   4. a proposal changes nothing before the owner accepts it;
 *   5. another tenant's read is a 404, every one of them, and a confirmation that carries a session
 *      header is refused.
 *
 * and beside them what the design leans on: a field declared as needing adding passes and is shown,
 * only a maintenance run of the space drafts or proposes, a draft built on a version that is no longer
 * the newest is refused, and the migration's CHECKs are the contract's closed sets.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-plan.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import {
  toUuid,
  WIKI_PLAN_ORIGINS,
  WIKI_PLAN_PROPOSAL_STATUSES,
  WIKI_PLAN_RULES,
  WIKI_PLAN_SECTION_KINDS,
  WIKI_PLAN_STATUSES,
} from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiPlanController } from '../runner-api/runner-wiki-plan.controller';
import { requireConfirmedPlan, WikiPlans } from './wiki-plan';
import { WikiPlanController } from './wiki-plan.controller';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiController } from './wiki.controller';
import { WikiRefusalError, WikiService } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  bearers: Map<string, string>;
  /** Every space `wiki.changed` was published for by the plan, in order. */
  published: string[];
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const published: string[] = [];
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const recorder = { publishWikiChanged: (_owner: string, space: string) => published.push(space) } as unknown as RealtimeService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, {} as unknown as PushService);
    const plans = new WikiPlans(prisma as unknown as PrismaService, recorder);

    @Module({
      controllers: [WikiController, WikiPlanController, RunnerWikiPlanController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiPlans, useValue: plans },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiPlanModule {}

    const app = await NestFactory.create(WikiPlanModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, bearers, published };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 1200)}`);
}

/** A refusal of the gate: 422 WIKI_PLAN_GATE, and among its errors one of `check` at `path`. */
function expectGate(answer: Answer, check: string, path: string | RegExp, why: string): void {
  expectStatus(answer, 422, why);
  assert.equal(answer.body.code, 'WIKI_PLAN_GATE', why);
  const errors: Array<{ check: string; path: string; message: string }> = answer.body.errors ?? [];
  const hit = errors.find((error) => error.check === check && (typeof path === 'string' ? error.path === path : path.test(error.path)));
  assert.ok(hit, `${why}: no ${check} error at ${path} among ${JSON.stringify(errors).slice(0, 1500)}`);
  for (const error of errors) assert.ok(error.message.trim().length > 0, `${why}: an error with no words at ${error.path}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [id, `wiki-plan-${id}@wiki.invalid`, name]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id") VALUES ($1,'spec',$2)`, [id, ownerId]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string, runnerId: string, taskId: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","status","dispatch_origin","updated_at")
     VALUES ($1,'a session','p',$2,$2,$3,$4,$5,'RUNNING'::run_status,'USER',now())`,
    [id, ownerId, workspaceId, runnerId, taskId],
  );
  return id;
}

async function task(h: Harness, ownerId: string, listId: string, assigneeId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id",
                         "completion_criterion","updated_at")
     VALUES ($1,'Wiki maintenance run',$2,'USER',$2,'OPEN'::task_status,$3,$4,'OWNER_CONFIRMED',now())`,
    [id, ownerId, assigneeId, listId],
  );
  return id;
}

async function project(h: Harness, ownerId: string, title: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "project"("id","title","owner_id","updated_at") VALUES ($1,$2,$3,now())`, [id, title, ownerId]);
  return id;
}

async function topic(h: Harness, ownerId: string, spaceId: string, slug: string): Promise<void> {
  await h.sql.query(`INSERT INTO "wiki_topic"("id","space_id","owner_id","slug","title") VALUES ($1,$2,$3,$4,$4)`, [randomUUID(), spaceId, ownerId, slug]);
}

async function entry(h: Harness, ownerId: string, spaceId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields")
     VALUES ($1,$2,$3,'concept','active','owner',1,'Knowledge that fits no section','It needs a document of its own.','{"definition":"x","boundaries":"y"}')`,
    [id, ownerId, spaceId],
  );
  return id;
}

/**
 * One owner's world: a runner, a bound workspace, a space with maintenance on and a maintenance run of
 * it, an ordinary session of the same workspace, two projects (one title shared by two of them) and
 * the topics the drafts name.
 */
interface Scene {
  owner: Account;
  runner: { id: string; token: string };
  spaceId: string;
  maintainer: Caller;
  maintenanceSession: string;
  ordinary: string;
  projectId: string;
}

const PROJECT = 'Orbit Wiki · 阶段 2';
const TWIN = 'Two projects share this title';

async function scene(h: Harness): Promise<Scene> {
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: 'A planned space' });
  expectStatus(made, 201, 'the owner creates a space');
  const spaceId = toUuid(made.body.id as string);
  expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId: ws }), 200, 'the owner binds the workspace');
  const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true, workspaceId: ws } });
  expectStatus(on, 200, 'the owner turns maintenance on');
  const listId = toUuid(on.body.settings.maintenance.listId as string);
  const maintenanceSession = await session(h, owner.id, ws, machine.id, await task(h, owner.id, listId, ws));
  const ordinary = await session(h, owner.id, ws, machine.id);
  const projectId = await project(h, owner.id, PROJECT);
  await project(h, owner.id, TWIN);
  await project(h, owner.id, TWIN);
  for (const slug of ['wiki', 'sessions']) await topic(h, owner.id, spaceId, slug);
  return {
    owner,
    runner: machine,
    spaceId,
    maintainer: { runner: machine.token, session: maintenanceSession },
    maintenanceSession,
    ordinary,
    projectId,
  };
}

// ── drafts ──────────────────────────────────────────────────────────────────────────────────────

/** One document as the drafting job writes it: an overview, a mechanism and a pitfalls section. */
function docOf(i: number, count: number, over: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    category: i % 5 === 0 ? 'dev' : 'product',
    slug: `doc-${i}`,
    title: `Document ${i}`,
    question: `What does part ${i} of Orbit do, and how?`,
    audience: [`A new developer: can say what part ${i} does after reading it`],
    scopeIn: [`How part ${i} runs`],
    scopeOut: [{ text: 'What the next part does', docs: [`doc-${(i + 1) % count}`] }],
    length: { min: 1200, max: 2000 },
    sections: [
      { title: 'Overview', kind: 'overview', covers: `What part ${i} is, in one paragraph.`, length: 300, sources: {} },
      {
        title: 'How it runs',
        kind: 'flow',
        covers: `The steps part ${i} takes.`,
        length: 800,
        sources: {
          docs: [{ path: 'docs/architecture.md', section: 'Execution model' }],
          code: [{ path: 'src/runner-go/runloop.go', symbols: ['runLoop()'] }],
          contracts: [{ path: 'contracts/wiki.contract.json' }],
        },
      },
      {
        title: 'Known pitfalls',
        kind: 'pitfalls',
        covers: `What went wrong in part ${i}, in the owner's words.`,
        length: 400,
        sources: {
          sessions: {
            projects: [PROJECT],
            since: '2026-09-01',
            until: null,
            keywords: ['plan', '检查闸'],
            anchorPaths: ['src/apiserver/src/wiki/'],
            entryKinds: ['pitfall', 'convention'],
            topics: ['wiki'],
            evidence: 'the owner saying what the plan must not do',
          },
        },
      },
    ],
    ...over,
  };
}

function planOf(count: number, docOver: (i: number) => Record<string, unknown> = () => ({})): Record<string, unknown> {
  return {
    categories: [
      { key: 'product', title: 'Product', question: 'What Orbit is and how it runs' },
      { key: 'dev', title: 'Development conventions', question: 'How agents work in this repository', forAgents: true },
    ],
    docs: Array.from({ length: count }, (_, i) => docOf(i, count, docOver(i))),
  };
}

const REPO = { sha: 'a'.repeat(40), checked: 3, missing: [] };

function draftBody(baseVersion: number | null, plan: Record<string, unknown>, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return { baseVersion, plan, repoCheck: REPO, model: 'qwen3.8-27b-fp8', ...extra };
}

async function draft(h: Harness, s: Scene, baseVersion: number | null, plan: Record<string, unknown>, extra: Record<string, unknown> = {}): Promise<Answer> {
  return call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/drafts`, draftBody(baseVersion, plan, extra));
}

async function confirm(h: Harness, s: Scene, version: number, who: Caller = { bearer: s.owner.bearer }): Promise<Answer> {
  return call(h, who, 'POST', `/wiki/spaces/${s.spaceId}/plan/versions/${version}/confirm`);
}

async function planState(h: Harness, s: Scene): Promise<Answer> {
  return call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/plan`);
}

/** Everything stored of one version but its status: its row, its documents and their sections, as the database has them. */
async function snapshot(h: Harness, spaceId: string, version: number): Promise<string> {
  const rows = await h.sql.query<{ doc: unknown }>(
    `SELECT jsonb_build_object(
              'plan', (SELECT to_jsonb(p) - 'status' - 'superseded_at' FROM "wiki_plan" p WHERE p."id" = v."id"),
              'docs', (SELECT coalesce(jsonb_agg(to_jsonb(d) ORDER BY d."position"), '[]'::jsonb) FROM "wiki_plan_doc" d WHERE d."plan_id" = v."id"),
              'sections', (SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY d."position", x."position"), '[]'::jsonb)
                             FROM "wiki_plan_section" x JOIN "wiki_plan_doc" d ON d."id" = x."doc_id" WHERE d."plan_id" = v."id")
            ) AS "doc"
       FROM "wiki_plan" v WHERE v."space_id" = $1 AND v."version" = $2`,
    [spaceId, version],
  );
  assert.equal(rows.rowCount, 1, `version ${version} is not stored`);
  return JSON.stringify(rows.rows[0].doc);
}

async function statuses(h: Harness, spaceId: string): Promise<Array<[number, string]>> {
  const rows = await h.sql.query<{ version: number; status: string }>(
    `SELECT "version", "status" FROM "wiki_plan" WHERE "space_id" = $1 ORDER BY "version"`,
    [spaceId],
  );
  return rows.rows.map((row): [number, string] => [row.version, row.status]);
}

/** The values a CHECK spells out, in the order it spells them. */
async function checkValues(h: Harness, table: string, constraint: string): Promise<string[]> {
  const def = await h.sql.query<{ def: string }>(
    `SELECT pg_get_constraintdef(oid) AS def FROM pg_constraint WHERE conname = $1 AND conrelid = $2::regclass`,
    [constraint, table],
  );
  assert.equal(def.rowCount, 1, `${table} has no constraint ${constraint}`);
  return [...def.rows[0].def.matchAll(/'([^']+)'::text/gu)].map((m) => m[1]);
}

// ── 1. the guard ────────────────────────────────────────────────────────────────────────────────

test('with no confirmed plan requireConfirmedPlan refuses — a draft is not enough — and with one it names it', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const db = h.prisma as unknown as PrismaService;
  const refused = async (why: string): Promise<void> => {
    const error = await requireConfirmedPlan(db, { ownerId: s.owner.id, spaceId: s.spaceId }).then(() => null, (e: unknown) => e);
    assert.ok(error instanceof WikiRefusalError, `${why}: requireConfirmedPlan did not refuse`);
    assert.equal(error.refusal.code, 'WIKI_PLAN_UNCONFIRMED', why);
    assert.equal(error.getStatus(), 409, why);
  };
  await refused('a space with no plan at all');

  const first = await draft(h, s, null, planOf(20));
  expectStatus(first, 200, 'the first draft passes the gate');
  assert.equal(first.body.version, 1);
  assert.equal(first.body.status, 'draft');
  await refused('a space whose only version is a draft nobody confirmed');

  // A proposal needs a confirmed plan too: there is nothing in force to change.
  const early = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/proposals`, {
    reason: 'Too early',
    change: { doc: docOf(20, 21) },
    facts: [{ kind: 'session', id: s.maintenanceSession }],
  });
  expectStatus(early, 409, 'a proposal to a space with no confirmed plan');
  assert.equal(early.body.code, 'WIKI_PLAN_UNCONFIRMED');

  expectStatus(await confirm(h, s, 1), 200, 'the owner confirms the draft');
  const confirmed = await requireConfirmedPlan(db, { ownerId: s.owner.id, spaceId: s.spaceId });
  assert.equal(confirmed.version, 1);
  assert.ok(confirmed.confirmedAt instanceof Date);
  // Another owner's space has no plan of this one's: the guard is per space and per owner.
  const other = await account(h, 'another owner');
  const error = await requireConfirmedPlan(db, { ownerId: other.id, spaceId: s.spaceId }).then(() => null, (e: unknown) => e);
  assert.ok(error instanceof WikiRefusalError && error.refusal.code === 'WIKI_PLAN_UNCONFIRMED', 'another owner found a plan in a space not theirs');
});

// ── 2. versions ─────────────────────────────────────────────────────────────────────────────────

test('a revision is a new version, and a confirmed version is never changed', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  expectStatus(await draft(h, s, null, planOf(20)), 200, 'the first draft');
  const one = await confirm(h, s, 1);
  expectStatus(one, 200, 'the owner confirms version 1');
  assert.equal(one.body.status, 'confirmed');
  assert.equal(toUuid(one.body.confirmedByUserId as string), s.owner.id);
  assert.ok(one.body.confirmedAt);
  const before = await snapshot(h, s.spaceId, 1);

  // What was stored is what was drafted: every document in order, every section with its sources, and a
  // key for each section the draft gave none.
  assert.equal(one.body.docs.length, 20);
  assert.deepEqual(one.body.docs.map((doc: { slug: string }) => doc.slug), Array.from({ length: 20 }, (_, i) => `doc-${i}`));
  const pitfalls = one.body.docs[3].sections[2];
  assert.deepEqual(one.body.docs[3].sections.map((section: { key: string }) => section.key), ['s1', 's2', 's3']);
  assert.equal(pitfalls.kind, 'pitfalls');
  assert.deepEqual(pitfalls.sources.sessions.projects.map((p: { id: string; title: string }) => [toUuid(p.id), p.title]), [[s.projectId, PROJECT]]);
  assert.deepEqual(pitfalls.sources.sessions.entryKinds, ['pitfall', 'convention']);
  assert.deepEqual(one.body.docs[3].sections[1].sources.code, [{ path: 'src/runner-go/runloop.go', symbols: ['runLoop()'] }]);
  assert.equal(one.body.categories[1].forAgents, true);
  // The runner's repository check is kept with its sha, and the gate's report with the version.
  assert.deepEqual(one.body.repoCheck, REPO);
  assert.deepEqual(one.body.gate.checks, { schema: 'passed', docCount: 'passed', protected: 'passed', references: 'passed' });
  assert.deepEqual(one.body.target, { min: WIKI_PLAN_RULES.docsMin, max: WIKI_PLAN_RULES.docsMax });
  assert.equal(toUuid(one.body.authorSessionId as string), s.maintenanceSession);

  // A redraft: version 2, a draft beside the confirmed version 1, which does not move.
  const redraft = await draft(h, s, 1, planOf(21), { target: { min: 20, max: 22 } });
  expectStatus(redraft, 200, 'a redraft of the confirmed version');
  assert.equal(redraft.body.version, 2);
  assert.equal(redraft.body.baseVersion, 1);
  assert.deepEqual(redraft.body.target, { min: 20, max: 22 });
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'confirmed'], [2, 'draft']]);
  assert.equal(await snapshot(h, s.spaceId, 1), before, 'the confirmed version changed when a draft was stored');

  // The owner's edit of one section of the draft: version 3, and the draft it was made from is superseded.
  const edited = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/plan/edits`, {
    baseVersion: 2,
    docSlug: 'doc-4',
    sectionKey: 's2',
    section: { title: 'How it really runs', kind: 'flow', covers: 'The steps, as the owner wants them told.', length: 900, sources: { docs: [{ path: 'docs/wiki-design.md', section: '§8.2' }] } },
  });
  expectStatus(edited, 200, 'the owner edits one section of the draft');
  assert.equal(edited.body.version, 3);
  assert.equal(edited.body.origin, 'owner');
  assert.equal(edited.body.gate.checks.protected, 'skipped');
  assert.equal(edited.body.repoCheck, null, 'no runner checked the owner\'s edit');
  const section = edited.body.docs[4].sections[1];
  assert.deepEqual([section.key, section.title, section.length], ['s2', 'How it really runs', 900]);
  assert.equal(edited.body.docs[5].sections[1].title, 'How it runs', 'the edit changed another document');
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'confirmed'], [2, 'superseded'], [3, 'draft']]);
  assert.equal(await snapshot(h, s.spaceId, 1), before, 'the confirmed version changed when the owner edited the draft');

  // A version once superseded is kept whole: history.
  const history = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/plan/versions`);
  expectStatus(history, 200, 'the history');
  assert.deepEqual(history.body.versions.map((v: { version: number; status: string; docCount: number }) => [v.version, v.status, v.docCount]), [
    [3, 'draft', 21],
    [2, 'superseded', 21],
    [1, 'confirmed', 20],
  ]);
  const two = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/plan/versions/2`);
  expectStatus(two, 200, 'a superseded version is read whole');
  assert.equal(two.body.docs[4].sections[1].title, 'How it runs');

  // Confirming the draft supersedes version 1 — whose rows, status aside, are still the ones confirmed.
  expectStatus(await confirm(h, s, 3), 200, 'the owner confirms version 3');
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'superseded'], [2, 'superseded'], [3, 'confirmed']]);
  assert.equal(await snapshot(h, s.spaceId, 1), before, 'the once-confirmed version changed when it was superseded');
  const state = await planState(h, s);
  expectStatus(state, 200, 'the plan');
  assert.equal(state.body.confirmed.version, 3);
  assert.equal(state.body.draft, null);
  // A version that is not the draft is not confirmed again.
  const again = await confirm(h, s, 1);
  expectStatus(again, 409, 'confirming a superseded version');
  assert.equal(again.body.code, 'WIKI_PLAN_STALE');
  expectStatus(await confirm(h, s, 9), 404, 'confirming a version that does not exist');

  // A draft built on a version that is no longer the newest is refused, and writes nothing.
  const stale = await draft(h, s, 2, planOf(20));
  expectStatus(stale, 409, 'a draft built on a superseded version');
  assert.equal(stale.body.code, 'WIKI_PLAN_STALE');
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'superseded'], [2, 'superseded'], [3, 'confirmed']]);
  assert.ok(h.published.filter((space) => space === s.spaceId).length >= 4, 'the plan\'s writes announced nothing');
});

// ── 3. the gate ─────────────────────────────────────────────────────────────────────────────────

test('the gate stops a field outside the schema, a count outside the target, and a project or topic that does not exist', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);

  // A field the model made up, at the section and at the document: each named, with where it is.
  const invented = planOf(20, (i) => (i === 2 ? { priority: 'high' } : {}));
  ((invented.docs as Array<{ sections: Array<Record<string, unknown>> }>)[7].sections[1]).evidenceWeight = 'decision > receipt';
  const schema = await draft(h, s, null, invented);
  expectGate(schema, 'schema', 'plan.docs[2].priority', 'a document with a field the schema does not have');
  expectGate(schema, 'schema', 'plan.docs[7].sections[1].evidenceWeight', 'a section with a field the schema does not have');
  // A kind that is not one, and a date that is not one.
  const kinds = planOf(20, (i) => (i === 1 ? { sections: [{ title: 'Musings', kind: 'essay', covers: 'x', length: 100, sources: { sessions: { since: 'last week' } } }] } : {}));
  const kindAnswer = await draft(h, s, null, kinds);
  expectGate(kindAnswer, 'schema', 'plan.docs[1].sections[0].kind', 'a section kind outside the closed set');
  expectGate(kindAnswer, 'schema', 'plan.docs[1].sections[0].sources.sessions.since', 'a date that is not one');

  // The same field, declared as needing adding: it passes, apart, and the report says so.
  const declared = planOf(20);
  declared.newFields = [{ at: 'section', name: 'evidenceWeight', why: 'the merge step orders material by it' }];
  ((declared.docs as Array<{ sections: Array<Record<string, unknown>> }>)[7].sections[1]).extra = { evidenceWeight: 'decision > receipt' };
  const needs = await draft(h, s, null, declared);
  expectStatus(needs, 200, 'a draft that declares its new field and keeps its value in extra');
  assert.deepEqual(needs.body.gate.needsNewFields, [{ at: 'section', name: 'evidenceWeight', why: 'the merge step orders material by it', values: 1 }]);
  assert.deepEqual(needs.body.docs[7].sections[1].extra, { evidenceWeight: 'decision > receipt' });
  // An undeclared name in extra, or a declared name that is already the schema's, is refused.
  const sneaky = planOf(20);
  sneaky.newFields = [{ at: 'doc', name: 'title', why: 'x' }];
  ((sneaky.docs as Array<Record<string, unknown>>)[0]).extra = { audienceLevel: 'expert' };
  const sneakyAnswer = await draft(h, s, 1, sneaky);
  expectGate(sneakyAnswer, 'schema', 'plan.newFields[0].name', 'a new field that the schema already has');
  expectGate(sneakyAnswer, 'schema', 'plan.docs[0].extra.audienceLevel', 'a value in extra nobody declared');

  // The document count: 20 to 35 unless the request names its own target.
  expectGate(await draft(h, s, 1, planOf(19)), 'docCount', 'plan.docs', 'nineteen documents');
  expectGate(await draft(h, s, 1, planOf(36)), 'docCount', 'plan.docs', 'thirty-six documents');
  expectGate(await draft(h, s, 1, planOf(20), { target: { min: 25, max: 30 } }), 'docCount', 'plan.docs', 'twenty documents against a target of 25 to 30');
  expectStatus(await draft(h, s, 1, planOf(4), { target: { min: 3, max: 5 } }), 200, 'four documents against a target of 3 to 5');

  // References: a project no one has, a title two projects share, a topic the space does not have, an
  // entry kind that is none, a category the plan does not list, a document a scope leaves to that is not there.
  const refs = planOf(20, (i) => (i === 3 ? { category: 'marketing', scopeOut: [{ text: 'x', docs: ['doc-99'] }] } : {}));
  const pitfalls = (refs.docs as Array<{ sections: Array<{ sources: { sessions: Record<string, unknown> } }> }>)[6].sections[2].sources.sessions;
  pitfalls.projects = [PROJECT, 'Sharing', TWIN];
  pitfalls.topics = ['wiki', 'engineering'];
  pitfalls.entryKinds = ['pitfall', 'rumour'];
  const refAnswer = await draft(h, s, 2, refs);
  const at = 'plan.docs[6].sections[2].sources.sessions';
  expectGate(refAnswer, 'references', `${at}.projects[1]`, 'a project that does not exist');
  expectGate(refAnswer, 'references', `${at}.projects[2]`, 'a title two projects share');
  expectGate(refAnswer, 'references', `${at}.topics[1]`, 'a topic the space does not have');
  expectGate(refAnswer, 'references', `${at}.entryKinds[1]`, 'an entry kind that is none');
  expectGate(refAnswer, 'references', 'plan.docs[3].category', 'a category the plan does not list');
  expectGate(refAnswer, 'references', 'plan.docs[3].scopeOut[0].docs[0]', 'a document the plan does not have');
  const listed: Array<{ path: string }> = refAnswer.body.errors;
  assert.ok(!listed.some((error) => error.path === `${at}.projects[0]` || error.path === `${at}.topics[0]`), 'a project and a topic that exist were refused');
  // A project named by its id is as good as by its title.
  const byId = planOf(20);
  (byId.docs as Array<{ sections: Array<{ sources: { sessions: Record<string, unknown> } }> }>)[0].sections[2].sources.sessions.projects = [s.projectId];
  expectStatus(await draft(h, s, 2, byId), 200, 'a project named by its id');

  // Nothing a refused draft sent was stored: versions 1 to 3 are the three that passed.
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'superseded'], [2, 'superseded'], [3, 'draft']]);
  // Without a repository check the draft is not taken, and its sha must be one.
  const noRepo = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/drafts`, { baseVersion: 3, plan: planOf(20) });
  expectGate(noRepo, 'schema', 'repoCheck', 'a draft with no repository check');
  expectGate(await draft(h, s, 3, planOf(20), { repoCheck: { sha: 'main', checked: 1, missing: [] } }), 'schema', 'repoCheck.sha', 'a sha that is not one');
});

test('a protected document stays as it was: a draft that changes it, drops it or protects another is refused', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  expectStatus(await draft(h, s, null, planOf(20)), 200, 'the first draft');
  // Only the owner protects: the owner edits doc-3 into a protected one.
  const protectedDoc = docOf(3, 20, { protected: true });
  const edit = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/plan/edits`, { baseVersion: 1, docSlug: 'doc-3', doc: protectedDoc });
  expectStatus(edit, 200, 'the owner protects a document');
  assert.equal(edit.body.docs[3].protected, true);
  expectStatus(await confirm(h, s, 2), 200, 'the owner confirms it');

  const changed = planOf(20, (i) => (i === 3 ? { protected: true, title: 'Document 3, rewritten by the model' } : {}));
  expectGate(await draft(h, s, 2, changed), 'protected', 'plan.docs[3]', 'a draft that rewrites a protected document');
  const reordered = planOf(20, (i) => (i === 3 ? { protected: true, sections: [...(docOf(3, 20).sections as unknown[])].reverse() } : {}));
  expectGate(await draft(h, s, 2, reordered), 'protected', 'plan.docs[3]', 'a draft that reorders a protected document\'s sections');
  const dropped = planOf(21, (i) => (i === 3 ? { slug: 'doc-3-merged' } : {}));
  expectGate(await draft(h, s, 2, dropped), 'protected', 'plan.docs', 'a draft that leaves a protected document out');
  const protects = planOf(20, (i) => (i === 3 ? { protected: true } : i === 9 ? { protected: true } : {}));
  expectGate(await draft(h, s, 2, protects), 'protected', 'plan.docs[9].protected', 'a draft that protects a document itself');

  // Carried exactly as it was, it passes — with the keys its sections had.
  const kept = await draft(h, s, 2, planOf(20, (i) => (i === 3 ? { protected: true } : i === 8 ? { title: 'Document 8, clearer' } : {})));
  expectStatus(kept, 200, 'a draft that carries the protected document as it was');
  assert.equal(kept.body.docs[3].protected, true);
  assert.deepEqual(kept.body.docs[3].sections.map((section: { key: string }) => section.key), ['s1', 's2', 's3']);
  assert.equal(kept.body.docs[8].title, 'Document 8, clearer');
});

// ── 4. proposals ────────────────────────────────────────────────────────────────────────────────

test('a proposal changes nothing until the owner accepts it; accepting makes a draft, rejecting changes nothing', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  expectStatus(await draft(h, s, null, planOf(20)), 200, 'the first draft');
  expectStatus(await confirm(h, s, 1), 200, 'the owner confirms it');
  const before = await snapshot(h, s.spaceId, 1);
  const knowledge = await entry(h, s.owner.id, s.spaceId);

  const propose = (body: Record<string, unknown>): Promise<Answer> =>
    call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/proposals`, body);
  // A new document in a new category, for knowledge that fits no section.
  const newDoc = docOf(20, 21, { category: 'ops', slug: 'backups' });
  const made = await propose({
    reason: 'Backups came up in three sessions and no document covers them.',
    change: { doc: newDoc, category: { key: 'ops', title: 'Operations' } },
    facts: [{ kind: 'entry', id: knowledge }, { kind: 'session', id: s.maintenanceSession }],
  });
  expectStatus(made, 200, 'a proposal for a new document');
  assert.equal(made.body.status, 'pending');
  assert.equal(made.body.baseVersion, 1);
  // A section added to an existing document, the other way a proposal changes the plan.
  const extended = docOf(5, 20);
  (extended.sections as unknown[]).push({ title: 'Decisions', kind: 'decisions', covers: 'Why it is this way.', length: 400, sources: { sessions: { projects: [PROJECT], keywords: ['why'] } } });
  const second = await propose({ reason: 'A decision that fits no section of doc-5.', change: { doc: extended }, facts: [{ kind: 'entry', id: knowledge }] });
  expectStatus(second, 200, 'a proposal that adds a section');

  // Before anyone answers, the plan is as it was: the same versions, the same confirmed rows.
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'confirmed']]);
  assert.equal(await snapshot(h, s.spaceId, 1), before, 'a pending proposal changed the confirmed version');
  const state = await planState(h, s);
  expectStatus(state, 200, 'the plan');
  assert.equal(state.body.draft, null);
  assert.equal(state.body.confirmed.docs.length, 20);
  assert.deepEqual(state.body.proposals.map((p: { id: string }) => toUuid(p.id)), [toUuid(made.body.id as string), toUuid(second.body.id as string)]);

  // The gate holds a proposal too: a protected document, a fact that is not one, a field made up.
  const bad = await propose({
    reason: 'x',
    change: { doc: docOf(21, 22, { slug: 'extra-doc', protected: true, mood: 'hopeful' }) },
    facts: [{ kind: 'entry', id: randomUUID() }],
  });
  expectGate(bad, 'protected', 'plan.docs[20].protected', 'a proposal that protects a document');
  expectGate(bad, 'schema', 'change.doc.mood', 'a proposal with a field the schema does not have');
  expectGate(bad, 'references', 'facts[0].id', 'a proposal naming an entry that does not exist');
  assert.equal((await planState(h, s)).body.proposals.length, 2, 'a refused proposal was stored');

  // Rejecting one changes nothing but the proposal.
  const rejected = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/plan-proposals/${made.body.id}/decide`, { action: 'reject', note: 'Not now.' });
  expectStatus(rejected, 200, 'the owner rejects the first proposal');
  assert.equal(rejected.body.proposal.status, 'rejected');
  assert.equal(rejected.body.proposal.decisionNote, 'Not now.');
  assert.equal(rejected.body.draft, null);
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'confirmed']]);
  assert.equal(await snapshot(h, s.spaceId, 1), before, 'a rejection changed the confirmed version');
  const twice = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/plan-proposals/${made.body.id}/decide`, { action: 'accept' });
  expectStatus(twice, 409, 'answering a decided proposal');
  assert.equal(twice.body.code, 'WIKI_PLAN_STALE');

  // Accepting the other makes a draft with the section added; the confirmed version is still the one in force.
  const accepted = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/plan-proposals/${second.body.id}/decide`, { action: 'accept' });
  expectStatus(accepted, 200, 'the owner accepts the second proposal');
  assert.equal(accepted.body.proposal.status, 'accepted');
  assert.equal(accepted.body.proposal.resultVersion, 2);
  assert.equal(accepted.body.draft.version, 2);
  assert.equal(toUuid(accepted.body.draft.proposalId as string), toUuid(second.body.id as string));
  assert.deepEqual(accepted.body.draft.docs[5].sections.map((section: { key: string; title: string }) => [section.key, section.title]), [
    ['s1', 'Overview'],
    ['s2', 'How it runs'],
    ['s3', 'Known pitfalls'],
    ['s4', 'Decisions'],
  ]);
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'confirmed'], [2, 'draft']]);
  assert.equal(await snapshot(h, s.spaceId, 1), before, 'an acceptance changed the confirmed version');
  const pending = await planState(h, s);
  assert.equal(pending.body.proposals.length, 0);
  assert.equal(pending.body.draft.version, 2);
});

// ── 5. who ──────────────────────────────────────────────────────────────────────────────────────

test('only a maintenance run drafts or proposes; the owner channel alone reads, edits, confirms and decides', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const body = draftBody(null, planOf(20));
  // Another session of the owner is not a maintenance run; a call with no session names nobody.
  const ordinary = await call(h, { runner: s.runner.token, session: s.ordinary }, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/drafts`, body);
  expectStatus(ordinary, 403, 'an ordinary session drafting');
  assert.equal(ordinary.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
  expectStatus(await call(h, { runner: s.runner.token }, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/drafts`, body), 400, 'a headless draft');
  const reads = await call(h, { runner: s.runner.token, session: s.ordinary }, 'GET', `/runner/wiki/spaces/${s.spaceId}/plan`);
  expectStatus(reads, 403, 'an ordinary session reading the plan on the runner door');
  expectStatus(await draft(h, s, null, planOf(20)), 200, 'the maintenance run drafts');
  const runnerRead = await call(h, s.maintainer, 'GET', `/runner/wiki/spaces/${s.spaceId}/plan`);
  expectStatus(runnerRead, 200, 'the maintenance run reads the plan');
  assert.equal(runnerRead.body.draft.version, 1);

  // Every user-door route, with a session header: refused before anything is read.
  const header: Caller = { bearer: s.owner.bearer, session: s.maintenanceSession };
  for (const [method, route, payload] of [
    ['POST', `/wiki/spaces/${s.spaceId}/plan/versions/1/confirm`, undefined],
    ['GET', `/wiki/spaces/${s.spaceId}/plan`, undefined],
    ['GET', `/wiki/spaces/${s.spaceId}/plan/versions`, undefined],
    ['GET', `/wiki/spaces/${s.spaceId}/plan/versions/1`, undefined],
    ['POST', `/wiki/spaces/${s.spaceId}/plan/edits`, { baseVersion: 1, docSlug: 'doc-1', doc: docOf(1, 20) }],
    ['POST', `/wiki/plan-proposals/${randomUUID()}/decide`, { action: 'accept' }],
  ] as const) {
    const answer = await call(h, header, method, route, payload);
    expectStatus(answer, 403, `${method} ${route} with a session header`);
    assert.equal(answer.body.code, 'WIKI_OWNER_CHANNEL_ONLY', `${method} ${route}`);
  }
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'draft']], 'a confirmation with a session header confirmed');
  expectStatus(await confirm(h, s, 1), 200, 'the owner, on the owner channel, confirms');
});

test('another owner reads and does none of it: every plan route is a 404', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  expectStatus(await draft(h, s, null, planOf(20)), 200, 'the owner\'s draft');
  expectStatus(await confirm(h, s, 1), 200, 'the owner confirms it');
  const proposal = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/proposals`, {
    reason: 'x',
    change: { doc: docOf(20, 21) },
    facts: [{ kind: 'session', id: s.maintenanceSession }],
  });
  expectStatus(proposal, 200, 'the maintenance run proposes');

  const other = await account(h, 'another owner');
  const them: Caller = { bearer: other.bearer };
  for (const [method, route, payload] of [
    ['GET', `/wiki/spaces/${s.spaceId}/plan`, undefined],
    ['GET', `/wiki/spaces/${s.spaceId}/plan/versions`, undefined],
    ['GET', `/wiki/spaces/${s.spaceId}/plan/versions/1`, undefined],
    ['POST', `/wiki/spaces/${s.spaceId}/plan/edits`, { baseVersion: 1, docSlug: 'doc-1', doc: docOf(1, 20) }],
    ['POST', `/wiki/spaces/${s.spaceId}/plan/versions/1/confirm`, undefined],
    ['POST', `/wiki/plan-proposals/${proposal.body.id}/decide`, { action: 'accept' }],
  ] as const) {
    const answer = await call(h, them, method, route, payload);
    expectStatus(answer, 404, `another owner: ${method} ${route}`);
    assert.ok(!JSON.stringify(answer.body).includes('Document 1'), `another owner: ${method} ${route} told something of the plan`);
  }
  // Another owner's maintenance run, through their own runner, finds no such space either.
  const theirs = await scene(h);
  for (const [method, route, payload] of [
    ['GET', `/runner/wiki/spaces/${s.spaceId}/plan`, undefined],
    ['POST', `/runner/wiki/spaces/${s.spaceId}/plan/drafts`, draftBody(1, planOf(20))],
    ['POST', `/runner/wiki/spaces/${s.spaceId}/plan/proposals`, { reason: 'x', change: { doc: docOf(20, 21) }, facts: [] }],
  ] as const) {
    expectStatus(await call(h, theirs.maintainer, method, route, payload), 404, `another owner's run: ${method} ${route}`);
  }
  // Nothing moved.
  assert.deepEqual(await statuses(h, s.spaceId), [[1, 'confirmed']]);
  assert.equal((await planState(h, s)).body.proposals.length, 1);
});

// ── the schema ──────────────────────────────────────────────────────────────────────────────────

test('the migration\'s CHECKs are the contract\'s closed sets, and a space has one draft and one confirmed version', { skip }, async () => {
  const h = await boot();
  assert.deepEqual(await checkValues(h, 'wiki_plan', 'wiki_plan_status_chk'), [...WIKI_PLAN_STATUSES]);
  assert.deepEqual(await checkValues(h, 'wiki_plan', 'wiki_plan_origin_chk'), [...WIKI_PLAN_ORIGINS]);
  assert.deepEqual(await checkValues(h, 'wiki_plan_section', 'wiki_plan_section_kind_chk'), [...WIKI_PLAN_SECTION_KINDS]);
  assert.deepEqual(await checkValues(h, 'wiki_plan_proposal', 'wiki_plan_proposal_status_chk'), [...WIKI_PLAN_PROPOSAL_STATUSES]);
  const s = await scene(h);
  expectStatus(await draft(h, s, null, planOf(20)), 200, 'a draft');
  // A second draft beside the first, written past the service, is refused by the index.
  const second = await h.sql.query(
    `INSERT INTO "wiki_plan"("id","space_id","owner_id","version","status","origin","categories","docs_min","docs_max","gate","author_user_id")
     VALUES ($1,$2,$3,7,'draft','owner','[]',20,35,'{}',$3)`,
    [randomUUID(), s.spaceId, s.owner.id],
  ).then(() => null, (e: Error) => e);
  assert.ok(second, 'a second draft of one space was stored');
  assert.match(second.message, /wiki_plan_space_id_draft_key/u);
  // A confirmed version that says nobody confirmed it is refused by its CHECK.
  const unsigned = await h.sql.query(
    `INSERT INTO "wiki_plan"("id","space_id","owner_id","version","status","origin","categories","docs_min","docs_max","gate","author_user_id")
     VALUES ($1,$2,$3,8,'confirmed','owner','[]',20,35,'{}',$3)`,
    [randomUUID(), s.spaceId, s.owner.id],
  ).then(() => null, (e: Error) => e);
  assert.ok(unsigned, 'a confirmed version with no confirmation was stored');
  assert.match(unsigned.message, /wiki_plan_confirmed_chk/u);
  // Deleting the space deletes its plan, its documents, their sections and its proposals.
  await h.sql.query(`DELETE FROM "wiki_space" WHERE "id" = $1`, [s.spaceId]);
  const left = await h.sql.query<{ n: number }>(
    `SELECT ((SELECT count(*) FROM "wiki_plan" WHERE "owner_id" = $1)
           + (SELECT count(*) FROM "wiki_plan_doc" WHERE "owner_id" = $1)
           + (SELECT count(*) FROM "wiki_plan_section" WHERE "owner_id" = $1)
           + (SELECT count(*) FROM "wiki_plan_proposal" WHERE "owner_id" = $1))::int AS n`,
    [s.owner.id],
  );
  assert.equal(left.rows[0].n, 0);
});
