/**
 * The three reads the owner's pages ask for: a topic's page, the space's timeline, and the rolling
 * usage window — over real HTTP and against a real PostgreSQL.
 *
 * These are the reads T3 deliberately left out (`wiki.controller.ts` said so where it listed them)
 * and the ones T8's pages cannot be built without: the topic page needs the entries that carry a
 * slug, the home page's timeline needs a ledger of changes, and its usage block needs the exposure
 * rows counted over a window rather than over all time.
 *
 * What is under test is what a caller gets back, so every request goes through the real controller,
 * the real WikiService, the global ValidationPipe and the public-id interceptor, and every fixture
 * is written through the real write door wherever one exists. `wiki_exposure` has no door — it is
 * written by the push and by the reads that serve an agent — so those rows are inserted directly,
 * which is also what lets a case set the window it is testing.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-reads.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { toUuid } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { WikiController } from './wiki.controller';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService, topicTitleFromSlug } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();

    @Module({
      controllers: [WikiController, RunnerWikiController],
      providers: [
        { provide: WikiService, useValue: new WikiService(prisma as unknown as PrismaService) },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiReadsModule {}

    const app = await NestFactory.create(WikiReadsModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests and fixtures ───────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

async function call(
  h: Harness,
  bearer: string,
  method: string,
  route: string,
  body?: unknown,
): Promise<Answer> {
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers: { 'content-type': 'application/json', authorization: `Bearer ${bearer}` },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-reads-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function space(h: Harness, owner: Account, repoUrl: string): Promise<string> {
  const answer = await call(h, owner.bearer, 'POST', '/wiki/spaces', { title: 'spec', repoUrl });
  expectStatus(answer, 201, 'the owner makes a space');
  return answer.body.id as string;
}

/** One entry, written through the door the owner writes through so it applies at once. */
async function write(
  h: Harness,
  owner: Account,
  spaceId: string,
  ops: unknown[],
  rationale = 'the spec records something',
): Promise<Answer> {
  return call(h, owner.bearer, 'POST', `/wiki/spaces/${spaceId}/changesets`, { rationale, ops });
}

function principled(title: string, topics: string[]): Record<string, unknown> {
  return {
    op: 'add',
    entry: {
      kind: 'principle',
      title,
      summary: `${title}, in one line.`,
      topics,
      fields: { statement: `${title}.`, rationale: 'Because the spec says so.' },
    },
  };
}

/** An exposure row, the one table with no write door. `at` is set explicitly to place it in time. */
async function exposure(
  h: Harness,
  owner: Account,
  entryId: string,
  channel: 'push' | 'search' | 'get',
  shape: { sessionId?: string; at?: Date } = {},
): Promise<void> {
  await h.sql.query(
    `INSERT INTO "wiki_exposure"("id","owner_id","entry_id","revision","session_id","channel","at")
     VALUES ($1,$2,$3,1,$4,$5,$6)`,
    [randomUUID(), owner.id, toUuid(entryId), shape.sessionId ?? null, channel, shape.at ?? new Date()],
  );
}

// ── the reads ───────────────────────────────────────────────────────────────────────────────────

test('wiki reads · a topic page, the timeline and the usage window', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  await t.test('a topic page names itself from the slug and carries only the entries that hold it', async () => {
    const owner = await account(h, 'topic owner');
    const made = await space(h, owner, 'github.com/orbit/topic.git');
    await write(h, owner, made, [
      principled('A clock never starts agent work', ['tasks-dispatch', 'runner-engines']),
      principled('Completion is adjudicated, not claimed', ['tasks-dispatch']),
      principled('Delete means forget', ['runner-engines']),
    ]);

    const answer = await call(h, owner.bearer, 'GET', `/wiki/spaces/${made}/topics/tasks-dispatch`);
    expectStatus(answer, 200, 'the topic page');
    assert.equal(answer.body.slug, 'tasks-dispatch');
    assert.equal(answer.body.title, 'Tasks dispatch', 'the name is read back out of the slug');
    assert.equal(answer.body.declared, false, 'and the page is told the owner never named it');
    assert.equal(answer.body.entryCount, 2);
    assert.deepEqual(
      (answer.body.entries as Array<{ title: string }>).map((entry) => entry.title).sort(),
      ['A clock never starts agent work', 'Completion is adjudicated, not claimed'],
    );
    assert.ok(
      (answer.body.entries as Array<Record<string, unknown>>).every((entry) => entry.kind === 'principle'),
      'an entry comes back whole, the same shape every other read gives it',
    );
  });

  await t.test('a topic nothing carries is a 404, and another account\'s space is the same 404', async () => {
    const owner = await account(h, 'topic owner');
    const theirs = await account(h, 'somebody else');
    const made = await space(h, owner, 'github.com/orbit/topic-404.git');
    await write(h, owner, made, [principled('A principle', ['known'])]);

    expectStatus(await call(h, owner.bearer, 'GET', `/wiki/spaces/${made}/topics/typo`), 404, 'no such topic');
    expectStatus(
      await call(h, theirs.bearer, 'GET', `/wiki/spaces/${made}/topics/known`),
      404,
      'another account cannot read the topic of a space it does not own',
    );
  });

  await t.test('the timeline is the ledger of changes, not of revisions', async () => {
    const owner = await account(h, 'timeline owner');
    const made = await space(h, owner, 'github.com/orbit/timeline.git');
    const seeded = await write(h, owner, made, [principled('Wakeups are held by the server', ['tasks-dispatch'])]);
    expectStatus(seeded, 200, 'the owner writes one');
    const entryId = seeded.body.ops[0].entryId as string;

    // An amend, then a retire: `applyOp` writes a revision for the first and no row at all for the
    // second, so a feed built from revisions would lose the retirement.
    const amended = await write(h, owner, made, [
      {
        op: 'amend',
        entryId,
        baseRevision: 1,
        changes: { summary: 'Held by the server, and refused to the client.' },
      },
      { op: 'retire', entryId, baseRevision: 2, reason: 'the fix landed' },
    ]);
    expectStatus(amended, 200, "the owner amends and retires");

    const answer = await call(h, owner.bearer, 'GET', `/wiki/spaces/${made}/timeline`);
    expectStatus(answer, 200, 'the timeline');
    const items = answer.body.items as Array<Record<string, unknown>>;
    assert.deepEqual(
      items.map((item) => item.op),
      ['retire', 'amend', 'add'],
      'newest first, one row per recorded change',
    );
    assert.equal(items[0].reason, 'the fix landed', "a retire carries the reason it was retired for");
    assert.equal(items[0].status, 'retired', 'and the entry it left behind');
    assert.equal(items[2].entryId, entryId, 'every row names the entry it is about');
    assert.equal(items[2].origin, 'owner');
    assert.ok(items.every((item) => typeof item.at === 'string'));
  });

  await t.test('a pending proposal is not a change, and neither is a rejected one', async () => {
    const owner = await account(h, 'pending owner');
    const made = await space(h, owner, 'github.com/orbit/pending.git');
    const seeded = await call(h, owner.bearer, 'POST', `/wiki/spaces/${made}/changesets`, {
      rationale: 'the owner writes the entry a proposal will amend',
      ops: [principled('A principle with a history', ['tasks-dispatch'])],
    });
    expectStatus(seeded, 200, 'the owner writes one');
    const entryId = seeded.body.ops[0].entryId as string;

    // A proposal from an agent is the one thing this spec cannot make through the owner door: the
    // owner's own writes apply at once. Written straight into the two tables a proposal lives in,
    // which is what `submitChangeset` would have written.
    const changesetId = randomUUID();
    const opId = randomUUID();
    await h.sql.query(
      `INSERT INTO "wiki_changeset"("id","owner_id","space_id","origin","rationale","status","created_at","expires_at")
       VALUES ($1,$2,$3,'agent','a session proposes','pending',now(),now() + interval '14 days')`,
      [changesetId, owner.id, toUuid(made)],
    );
    await h.sql.query(
      `INSERT INTO "wiki_changeset_op"("id","owner_id","changeset_id","seq","op","entry_id","base_revision","payload","similar","tainted","decision")
       VALUES ($1,$2,$3,0,'amend',$4,1,'{}'::jsonb,'[]'::jsonb,false,'pending')`,
      [opId, owner.id, changesetId, toUuid(entryId)],
    );

    const waiting = await call(h, owner.bearer, 'GET', `/wiki/spaces/${made}/timeline`);
    expectStatus(waiting, 200, 'the timeline while one waits');
    assert.deepEqual(
      (waiting.body.items as Array<{ op: string }>).map((item) => item.op),
      ['add'],
      'a pending proposal has changed nothing yet',
    );

    await h.sql.query(`UPDATE "wiki_changeset_op" SET "decision"='rejected', "decision_reason"='not_true',
                              "decided_at"=now() WHERE "id"=$1`, [opId]);
    const rejected = await call(h, owner.bearer, 'GET', `/wiki/spaces/${made}/timeline`);
    assert.deepEqual(
      (rejected.body.items as Array<{ op: string }>).map((item) => item.op),
      ['add'],
      'and a rejected one never did',
    );
  });

  await t.test('the usage window counts this space, this window, and its own channels', async () => {
    const owner = await account(h, 'usage owner');
    const theirs = await account(h, 'somebody else');
    const made = await space(h, owner, 'github.com/orbit/usage.git');
    const other = await space(h, owner, 'github.com/orbit/usage-other.git');
    const theirSpace = await space(h, theirs, 'github.com/orbit/usage-theirs.git');

    const written = await write(h, owner, made, [
      principled('A principle agents keep reading', ['tasks-dispatch']),
      principled('A principle nobody has read', ['tasks-dispatch']),
    ]);
    expectStatus(written, 200, 'two entries');
    const [first, second] = written.body.ops as Array<{ entryId: string }>;
    const elsewhere = await write(h, owner, other, [principled('A principle in another space', ['x'])]);
    const foreign = await write(h, theirs, theirSpace, [principled('A principle in another account', ['x'])]);

    const sessionA = randomUUID();
    const sessionB = randomUUID();
    await exposure(h, owner, first.entryId, 'push', { sessionId: sessionA });
    await exposure(h, owner, first.entryId, 'push', { sessionId: sessionA }); // same session, twice
    await exposure(h, owner, first.entryId, 'push', { sessionId: sessionB });
    await exposure(h, owner, first.entryId, 'search');
    await exposure(h, owner, first.entryId, 'get');
    await exposure(h, owner, second.entryId, 'search');
    await exposure(h, owner, first.entryId, 'search', { at: new Date(Date.now() - 30 * 86_400_000) });
    await exposure(h, owner, elsewhere.body.ops[0].entryId, 'search');
    await exposure(h, theirs, foreign.body.ops[0].entryId, 'search');

    const answer = await call(h, owner.bearer, 'GET', `/wiki/spaces/${made}?include=usage`);
    expectStatus(answer, 200, 'the space with its usage');
    const usage = answer.body.usage as {
      days: number;
      sessionsPushed: number;
      searches: number;
      gets: number;
      entries: Array<{ entryId: string; title: string; total: number; pushed: number; searched: number; fetched: number }>;
    };
    assert.equal(usage.days, 7);
    assert.equal(usage.sessionsPushed, 2, 'two sessions received it, however many entries they were shown');
    assert.equal(usage.searches, 2, 'the search from 30 days ago is outside the window, and another space is another space');
    assert.equal(usage.gets, 1);
    assert.equal(usage.entries[0].entryId, first.entryId, 'the most used entry leads');
    assert.equal(usage.entries[0].total, 5);
    assert.deepEqual(
      [usage.entries[0].pushed, usage.entries[0].searched, usage.entries[0].fetched],
      [3, 1, 1],
    );
    assert.equal(usage.entries[1].entryId, second.entryId);
    assert.equal(usage.entries[1].total, 1, 'the other entry is counted on its own');
    assert.ok(usage.entries.every((entry) => typeof entry.title === 'string'));

    const plain = await call(h, owner.bearer, 'GET', `/wiki/spaces/${made}`);
    expectStatus(plain, 200, 'the same space without asking');
    assert.equal(plain.body.usage, undefined, 'the four aggregates are paid for only by the read that asks');
    assert.equal(plain.body.id, made, 'and it is still the space itself that answers');
  });
});

// ── the one pure piece ──────────────────────────────────────────────────────────────────────────

test('a slug read as words', () => {
  assert.equal(topicTitleFromSlug('tasks-dispatch'), 'Tasks dispatch');
  assert.equal(topicTitleFromSlug('deploy-ops'), 'Deploy ops');
  assert.equal(topicTitleFromSlug('migrations'), 'Migrations');
  assert.equal(topicTitleFromSlug(''), '');
});
