/**
 * What `orbit wiki docs build` reads and writes on the runner door that the documents' own spec does not
 * (criterion 9; contracts/wiki.contract.json `docs.material`, `docs.reads.material`, `docs.reads.writerDoc`,
 * `docs.dispositions`, migration 0337), over real HTTP and against a real PostgreSQL.
 *
 * What the task's verification asks, each read back from the doors and from the database:
 *
 *   1. the server's half of a section's material, and the document as it is written, are a maintenance
 *      run's of the space and no one else's: another session of the owner is refused
 *      WIKI_NOT_MAINTENANCE_SESSION, a call with no session 400, a session this runner does not host 403;
 *   2. every record it hands out is redacted — the owner's workspace.env values and the shared
 *      redactor's shapes taken out — and placed: `chars` is where the text stands in the record's
 *      redacted text, as a footnote's check reads it, so a quote copied from it verifies;
 *   3. another tenant gets a 404 for every one of it, and no record of theirs ever comes back through
 *      an entry that cites one;
 *
 * and beside them: what the condition finds (the entries its keywords and anchor paths pick, best first,
 * as the way in to the records they cite; the owner's own words and the tasks' comments in its projects
 * and window), a long record cut around what found it, and the material's ledger (dispositions) written
 * with the section, refused when malformed, and read back on both doors.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-docs-build.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { toUuid, WIKI_DOC_DISPOSITION_ACTIONS, WIKI_DOC_MATERIAL_RULES } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { redactSecrets } from '../common/secret-redaction';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiDocsController } from '../runner-api/runner-wiki-docs.controller';
import { RunnerWikiPlanController } from '../runner-api/runner-wiki-plan.controller';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiDocs } from './wiki-docs';
import { WikiDocsController } from './wiki-docs.controller';
import { WikiPlans } from './wiki-plan';
import { WikiPlanController } from './wiki-plan.controller';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiController } from './wiki.controller';
import { WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

const CONTRACT = JSON.parse(readFileSync(path.resolve(__dirname, '../../../../contracts/wiki.contract.json'), 'utf8'));

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = { notifyWikiReviewModeTripped: async () => undefined, notifyWikiVerificationTripped: async () => undefined } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);
    const plans = new WikiPlans(prisma as unknown as PrismaService, hub);
    const docs = new WikiDocs(prisma as unknown as PrismaService, service, hub);

    @Module({
      controllers: [WikiController, WikiPlanController, WikiDocsController, RunnerWikiController, RunnerWikiPlanController, RunnerWikiDocsController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiPlans, useValue: plans },
        { provide: WikiDocs, useValue: docs },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiDocsBuildModule {}

    const app = await NestFactory.create(WikiDocsBuildModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 1500)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [id, `wiki-docs-build-${id}@wiki.invalid`, name]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

/** The owner's workspace.env holds this value: the redactor takes it out of every record it reads. */
const LITERAL = 'orbit-build-literal-7d31e0';
/** A shape the shared redactor knows whatever the owner's env says. */
const TOKEN = `ghp_${'A1b2C3d4E5f6G7h8I9j0'.repeat(2)}`;

async function workspace(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env") VALUES ($1,'spec',$2,$3)`, [id, ownerId, JSON.stringify({ BUILD_SPEC_KEY: LITERAL })]);
  return id;
}

async function project(h: Harness, ownerId: string, title: string, coordinatorSessionId: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "project"("id","title","owner_id","coordinator_session_id","updated_at") VALUES ($1,$2,$3,$4,now())`, [id, title, ownerId, coordinatorSessionId]);
  return id;
}

async function task(h: Harness, ownerId: string, assigneeId: string, over: { listId?: string | null; projectId?: string | null; title?: string } = {}): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id","project_id",
                         "completion_criterion","updated_at")
     VALUES ($1,$2,$3,'USER',$3,'OPEN'::task_status,$4,$5,$6,'OWNER_CONFIRMED',now())`,
    [id, over.title ?? 'a task', ownerId, assigneeId, over.listId ?? null, over.projectId ?? null],
  );
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string, runnerId: string, taskId: string | null = null, title = 'a session'): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","status","dispatch_origin","updated_at")
     VALUES ($1,$2,'p',$3,$3,$4,$5,$6,'RUNNING'::run_status,'USER',now())`,
    [id, title, ownerId, workspaceId, runnerId, taskId],
  );
  return id;
}

/** A message in a session: the owner's (a client turn id and an intent), or not (neither). */
async function turn(h: Harness, sessionId: string, content: string, owner = true, at: string | null = null): Promise<string> {
  const id = randomUUID();
  const seq = (await h.sql.query<{ n: number }>(`SELECT COALESCE(MAX("seq"), 0)::int + 1 AS n FROM "conversation_turn" WHERE "session_id" = $1`, [sessionId])).rows[0].n;
  await h.sql.query(
    `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status","kind","send_intent","created_at")
     VALUES ($1,$2,$3,$4,$5,'ANSWERED','message',$6,COALESCE($7::timestamptz, now()))`,
    [id, sessionId, seq, randomUUID(), content, owner ? 'NEXT_TURN' : null, at],
  );
  return id;
}

async function toolCall(h: Harness, sessionId: string, name: string, input: unknown, output: string, isError = false): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","input","output","is_error","started_at") VALUES ($1,$2,$3,$4,$5,$6,now())`, [
    id,
    sessionId,
    name,
    JSON.stringify(input),
    JSON.stringify(output),
    isError,
  ]);
  return id;
}

async function comment(h: Harness, taskId: string, authorId: string, body: string, author: 'AGENT' | 'USER' = 'AGENT', at: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task_comment"("id","task_id","author_type","author_id","body","created_at") VALUES ($1,$2,$3::creator_type,$4,$5,COALESCE($6::timestamptz, now()))`,
    [id, taskId, author, authorId, body, at],
  );
  return id;
}

/** The words the condition looks for, and what the records say. */
const KEYWORD = 'runner 宿主';
const OTHER_KEYWORD = 'env -u';
const OWNER_WORDS = `runner-go 的全量测试要在 runner 宿主上跑，别在引擎的 Bash 里跑；token 是 ${LITERAL}，别贴出来。`;
const OLD_OWNER_WORDS = 'runner 宿主那台机器上周换过（这句在时间窗之前）。';
const NOT_OWNERS = 'runner 宿主的约定（这是平台发的，不是 owner 说的）。';
const DELIVERY = `交付：在 runner 宿主上跑完整包，env -u 清掉 ORBIT_* 后 0 FAIL。push 用的 ${TOKEN}。`;
/** A long command output: the keyword sits deep in it, far past excerptChars. */
const LONG_OUTPUT = `${'ok  orbit/runner 0.12s\n'.repeat(120)}FAIL: the suite must run on the runner 宿主, with env -u ORBIT_SESSION_ID; key ${LITERAL}\n${'PASS\n'.repeat(400)}`;

interface Scene {
  owner: Account;
  runner: { id: string; token: string };
  ws: string;
  spaceId: string;
  maintainer: Caller;
  maintenanceSession: string;
  ordinary: string;
  projectId: string;
  r: { owner: string; old: string; notOwners: string; delivery: string; long: string; plain: string };
  entries: { keyword: string; path: string; unrelated: string };
}

/** The window the condition names: 2026-09-01 .. 2026-09-30, both days included. */
const SINCE = '2026-09-01';
const UNTIL = '2026-09-30';

async function scene(h: Harness): Promise<Scene> {
  const owner = await account(h, 'owner');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: 'A built space' });
  expectStatus(made, 201, 'the owner creates a space');
  const spaceId = toUuid(made.body.id as string);
  expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId: ws }), 200, 'the owner binds the workspace');
  const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true, workspaceId: ws } });
  expectStatus(on, 200, 'the owner turns maintenance on');
  const listId = toUuid(on.body.settings.maintenance.listId as string);
  const maintenanceSession = await session(h, owner.id, ws, machine.id, await task(h, owner.id, ws, { listId, title: 'Wiki maintenance run' }));
  const ordinary = await session(h, owner.id, ws, machine.id, null, 'an ordinary session');

  // A project, its coordinator conversation and one of its tasks' sessions, with what was said in them.
  const coordinator = await session(h, owner.id, ws, machine.id, null, 'the coordinator');
  const projectId = await project(h, owner.id, 'Runner 托管后台作业', coordinator);
  const projectTask = await task(h, owner.id, ws, { projectId, title: '整包测试在宿主上跑' });
  const taskSession = await session(h, owner.id, ws, machine.id, projectTask, '执行任务：整包测试在宿主上跑');
  const r = {
    owner: await turn(h, coordinator, OWNER_WORDS, true, '2026-09-20T10:00:00Z'),
    old: await turn(h, coordinator, OLD_OWNER_WORDS, true, '2026-08-01T10:00:00Z'),
    notOwners: await turn(h, taskSession, NOT_OWNERS, false, '2026-09-21T10:00:00Z'),
    delivery: await comment(h, projectTask, owner.id, DELIVERY, 'AGENT', '2026-09-22T10:00:00Z'),
    long: await toolCall(h, ordinary, 'Bash', { command: 'go test ./...' }, LONG_OUTPUT, true),
    plain: await toolCall(h, ordinary, 'Bash', { command: 'git status' }, 'nothing to commit, working tree clean'),
  };

  // The entries the space holds: one a keyword finds, one an anchor path finds, one neither does.
  const agent = { runner: machine.token, session: ordinary };
  const propose = async (entry: Record<string, unknown>, sources: unknown[]): Promise<string> => {
    const proposed = await call(h, agent, 'POST', '/runner/wiki/changesets', {
      rationale: 'what the session learned',
      idempotencyKey: `docs-build-${randomUUID()}`,
      ops: [{ op: 'add', entry, sources }],
    });
    expectStatus(proposed, 200, 'an agent proposes an entry');
    assert.equal(proposed.body.ops[0].status, 'applied', `the space's mode applies it: ${JSON.stringify(proposed.body.ops[0]).slice(0, 400)}`);
    return toUuid(proposed.body.ops[0].entryId as string);
  };
  const entries = {
    keyword: await propose(
      { kind: 'concept', title: '全量测试在 runner 宿主上跑', summary: 'The whole suite runs on the runner host.', fields: { definition: 'where the suite runs', boundaries: 'tests only' } },
      [{ kind: 'tool_call', ref: r.long, quote: 'the suite must run on the runner 宿主' }],
    ),
    path: await propose(
      {
        kind: 'concept',
        title: 'git status 是干净的',
        summary: 'A clean tree before a run.',
        fields: { definition: 'a clean tree', boundaries: 'the checkout' },
        anchors: [{ type: 'path', path: 'src/runner-go/runloop.go' }],
      },
      [{ kind: 'tool_call', ref: r.plain, quote: 'nothing to commit' }],
    ),
    unrelated: await propose(
      { kind: 'concept', title: '别的事', summary: 'Something else entirely.', fields: { definition: 'something else', boundaries: 'none' } },
      [{ kind: 'tool_call', ref: r.plain, quote: 'working tree clean' }],
    ),
  };
  return { owner, runner: machine, ws, spaceId, maintainer: { runner: machine.token, session: maintenanceSession }, maintenanceSession, ordinary, projectId, r, entries };
}

// ── the plan ────────────────────────────────────────────────────────────────────────────────────

/** One document: an overview, a mechanism with no session condition, and conventions with one. */
function planFor(s: Scene): Record<string, unknown> {
  return {
    categories: [{ key: 'dev', title: 'Development conventions', question: 'How agents work here', forAgents: true }],
    docs: [{
      category: 'dev',
      slug: 'dev-session-commands',
      title: '会话里跑命令与后台作业',
      question: '会话里怎么跑命令？',
      audience: ['A developer: can run the suite after reading it'],
      scopeIn: ['Where and how the suite runs'],
      scopeOut: [],
      length: { min: 800, max: 4000 },
      sections: [
        { title: '总览', kind: 'overview', covers: '这篇讲什么。', length: 300, sources: {} },
        { title: '测试在哪跑', kind: 'flow', covers: '测试怎么跑。', length: 500, sources: { code: [{ path: 'src/runner-go/runloop.go', symbols: ['runLoop'] }] } },
        {
          title: '约定',
          kind: 'conventions',
          covers: '跑测试的约定。',
          length: 400,
          sources: {
            sessions: {
              projects: [s.projectId],
              since: SINCE,
              until: UNTIL,
              keywords: [KEYWORD, OTHER_KEYWORD],
              anchorPaths: ['src/runner-go/'],
              entryKinds: ['convention', 'pitfall'],
              topics: [],
              evidence: 'where the suite runs, in the owner\'s words',
            },
          },
        },
      ],
    }],
  };
}

async function confirmPlan(h: Harness, s: Scene): Promise<{ version: number; keys: string[] }> {
  const drafted = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/plan/drafts`, {
    baseVersion: null,
    target: { min: 1, max: 10 },
    plan: planFor(s),
    repoCheck: { sha: 'a'.repeat(40), checked: 1, missing: [] },
    model: 'qwen3.8-27b-fp8',
  });
  expectStatus(drafted, 200, 'the maintenance run drafts the plan');
  const confirmed = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/plan/versions/${drafted.body.version}/confirm`);
  expectStatus(confirmed, 200, 'the owner confirms the plan');
  const state = await call(h, s.maintainer, 'GET', `/runner/wiki/spaces/${s.spaceId}/plan`);
  expectStatus(state, 200, 'the plan in force');
  const keys = state.body.confirmed.docs[0].sections.map((section: { key: string }) => section.key);
  return { version: drafted.body.version as number, keys };
}

const SLUG = 'dev-session-commands';

function materialRoute(s: Scene, key: string | null): string {
  return `/runner/wiki/spaces/${s.spaceId}/docs/${SLUG}/material${key === null ? '' : `?section=${key}`}`;
}

/** A record's text as a footnote's check reads it: the one reader, redacted with the owner's env values. */
async function redactedRecord(h: Harness, ownerId: string, kind: 'turn' | 'tool_call' | 'task_comment', ref: string): Promise<string[]> {
  const reader: WikiPrincipal = { origin: 'maintenance', ownerId, userId: null, sessionId: null, toolCallId: null };
  const found = await h.service.sourceText(h.prisma as never, reader, { kind, ref });
  assert.ok(found?.text, `${kind} ${ref} reads`);
  return Array.from(redactSecrets(found.text, { literals: [LITERAL] }).text.normalize('NFC'));
}

// ── 1. who reads it ─────────────────────────────────────────────────────────────────────────────

test('the material and the written document are a maintenance run\'s of the space: any other session is refused, a call with none 400', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const { keys } = await confirmPlan(h, s);
  const conventions = keys[2];
  const routes = [materialRoute(s, conventions), `/runner/wiki/spaces/${s.spaceId}/docs/${SLUG}`];
  for (const route of routes) {
    const ordinary = await call(h, { runner: s.runner.token, session: s.ordinary }, 'GET', route);
    expectStatus(ordinary, 403, `another session of the owner asks ${route}`);
    assert.equal(ordinary.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
    expectStatus(await call(h, { runner: s.runner.token }, 'GET', route), 400, `no session asks ${route}`);
    const elsewhere = await runner(h, s.owner.id);
    expectStatus(await call(h, { runner: elsewhere.token, session: s.maintenanceSession }, 'GET', route), 403, `a runner that does not host the session asks ${route}`);
    expectStatus(await call(h, s.maintainer, 'GET', route), 200, `the maintenance run asks ${route}`);
  }
  // The contract's routes, and nothing a runner could decide with.
  assert.ok(CONTRACT.agentSurface.doors.runner.maintenanceRoutes.includes(CONTRACT.docs.routes.material));
  assert.ok(CONTRACT.agentSurface.doors.runner.maintenanceRoutes.includes(CONTRACT.docs.routes.writerDoc));
  // A section the plan's document does not have, or none named, is not read at all.
  expectStatus(await call(h, s.maintainer, 'GET', materialRoute(s, 'no-such-section')), 404, 'a section the plan does not have');
  expectStatus(await call(h, s.maintainer, 'GET', materialRoute(s, null)), 400, 'no section named');
  expectStatus(await call(h, s.maintainer, 'GET', `/runner/wiki/spaces/${s.spaceId}/docs/no-such-doc/material?section=${conventions}`), 404, 'a document the plan does not have');
});

test('with no confirmed plan there is no material to read', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const answer = await call(h, s.maintainer, 'GET', materialRoute(s, 's1'));
  expectStatus(answer, 409, 'no plan confirmed');
  assert.equal(answer.body.code, 'WIKI_PLAN_UNCONFIRMED');
});

// ── 2. redacted and placed ──────────────────────────────────────────────────────────────────────

test('every record handed out is redacted and placed where a footnote\'s check reads it, and a quote copied from it verifies', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const { version, keys } = await confirmPlan(h, s);
  const answer = await call(h, s.maintainer, 'GET', materialRoute(s, keys[2]));
  expectStatus(answer, 200, 'the conventions section\'s material');
  const material = answer.body;
  assert.equal(material.section, keys[2]);
  assert.equal(material.planVersion, version);
  assert.deepEqual(material.condition.keywords, [KEYWORD, OTHER_KEYWORD]);
  assert.deepEqual(material.condition.projects.map((p: { id: string; title: string }) => [toUuid(p.id), p.title]), [[s.projectId, 'Runner 托管后台作业']]);

  // Nothing secret in any of it: not the owner's env value, not a token the shared redactor knows.
  const all = JSON.stringify(material);
  assert.ok(!all.includes(LITERAL), 'the owner\'s workspace.env value is taken out');
  assert.ok(!all.includes(TOKEN), 'a GitHub token is taken out');
  assert.ok(all.includes('[redacted]'), 'where they stood says so');

  type Rec = { kind: 'turn' | 'tool_call' | 'task_comment'; ref: string; found: string; text: string; chars: { start: number; end: number }; length: number; via: { entryId: string; title: string } | null; weight: string; ownerWords: boolean; sessionTitle: string | null; projectTitle: string | null; taskTitle: string | null };
  const records: Rec[] = material.records;
  const byRef = new Map(records.map((record) => [toUuid(record.ref), record]));
  // Each one placed: its text is exactly the range it names of the record's redacted text.
  for (const record of records) {
    const points = await redactedRecord(h, s.owner.id, record.kind, toUuid(record.ref));
    assert.equal(record.length, points.length, `${record.kind} ${record.ref}: its length`);
    assert.equal(points.slice(record.chars.start, record.chars.end).join(''), record.text, `${record.kind} ${record.ref}: the text is where chars says`);
    assert.ok(record.chars.end - record.chars.start <= WIKI_DOC_MATERIAL_RULES.excerptChars);
  }

  // The owner's words in the project's window, found by its keywords; not the ones before it, not the platform's.
  const owner = byRef.get(s.r.owner)!;
  assert.ok(owner, 'the owner\'s words in the window are found');
  assert.deepEqual([owner.found, owner.ownerWords, owner.weight, owner.via], ['search', true, 'decision', null]);
  assert.equal(owner.projectTitle, null, 'a coordinator conversation belongs to no task');
  assert.ok(owner.text.includes('runner 宿主上跑') && owner.text.includes('[redacted]'), owner.text);
  assert.ok(!byRef.has(s.r.old), 'words before since are not found');
  assert.ok(!byRef.has(s.r.notOwners), 'a turn that is not the owner\'s is not the owner\'s words');
  // A delivery comment on one of its tasks: a record of what was delivered.
  const delivery = byRef.get(s.r.delivery)!;
  assert.deepEqual([delivery.found, delivery.weight, delivery.taskTitle, delivery.projectTitle], ['search', 'merge', '整包测试在宿主上跑', 'Runner 托管后台作业']);
  assert.ok(delivery.text.includes('[redacted]') && !delivery.text.includes('ghp_'), delivery.text);

  // Through the entries: the one a keyword found and the one an anchor path found, each the way in to its record.
  const long = byRef.get(s.r.long)!;
  assert.deepEqual([long.found, long.weight, toUuid(long.via!.entryId)], ['entry', 'error', s.entries.keyword]);
  assert.ok(long.length > WIKI_DOC_MATERIAL_RULES.excerptChars, 'the long output is longer than an excerpt');
  assert.equal(long.chars.end - long.chars.start, WIKI_DOC_MATERIAL_RULES.excerptChars, 'and is cut to one');
  assert.ok(long.text.includes('the suite must run on the runner 宿主'), 'around what found it: its entry source\'s quote');
  assert.ok(long.chars.start > 0);
  const plain = byRef.get(s.r.plain)!;
  assert.deepEqual([plain.found, plain.weight, toUuid(plain.via!.entryId)], ['entry', 'output', s.entries.path]);
  const picked = material.entries.map((entry: { id: string }) => toUuid(entry.id));
  assert.deepEqual(picked, [s.entries.keyword, s.entries.path], 'the keyword\'s entry first, then the path\'s; the unrelated one not at all');
  assert.equal(records.filter((record) => toUuid(record.ref) === s.r.plain).length, 1, 'a record met twice is handed out once');

  // A quote copied from what was handed out, at the range it was handed out at, verifies.
  const quote = Array.from(long.text).slice(30, 90).join('');
  const written = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/docs/${SLUG}`, {
    planVersion: version,
    repoSha: 'c'.repeat(40),
    sections: [{
      key: keys[2],
      materialSha256: 'd'.repeat(64),
      markdown: '整包测试在 runner 宿主上跑[1]。',
      footnotes: [{ kind: 'tool_call', ref: long.ref, chars: long.chars, quote, viaEntryId: long.via!.entryId }],
    }],
  });
  expectStatus(written, 200, 'a section written from the material');
  const footnote = await h.prisma.wikiDocFootnote.findFirst({ where: { ownerId: s.owner.id, ref: s.r.long } });
  assert.equal(footnote?.verdict, 'verified', `the quote verifies: ${JSON.stringify(footnote)}`);
  assert.ok(footnote!.charStart! >= long.chars.start && footnote!.charEnd! <= long.chars.end, 'and is found inside the range it was handed out at');

  // A section with no session condition has no server half.
  const mechanism = await call(h, s.maintainer, 'GET', materialRoute(s, keys[1]));
  expectStatus(mechanism, 200, 'the mechanism section');
  assert.deepEqual([mechanism.body.condition, mechanism.body.entries, mechanism.body.records], [null, [], []]);
});

// ── 3. another tenant ───────────────────────────────────────────────────────────────────────────

test('another tenant gets a 404 for all of it, and no record of theirs comes back through an entry that cites one', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const { keys } = await confirmPlan(h, s);
  const other = await scene(h);
  await confirmPlan(h, other);
  for (const route of [materialRoute(s, keys[2]), `/runner/wiki/spaces/${s.spaceId}/docs/${SLUG}`]) {
    const answer = await call(h, other.maintainer, 'GET', route);
    expectStatus(answer, 404, `another owner's maintenance run asks ${route}`);
    assert.ok(!JSON.stringify(answer.body).includes(OWNER_WORDS.slice(0, 20)));
  }
  // An entry of this space that cites the other owner's record (written by hand: no door would take it).
  const foreign = await h.prisma.wikiEntry.findUniqueOrThrow({ where: { id: s.entries.keyword }, select: { currentRevision: true } });
  const revision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: s.entries.keyword, revision: foreign.currentRevision }, select: { id: true } });
  await h.prisma.wikiSource.create({ data: { revisionId: revision.id, ownerId: s.owner.id, kind: 'turn', ref: other.r.owner, locator: {}, quote: null, state: 'live' } });
  const answer = await call(h, s.maintainer, 'GET', materialRoute(s, keys[2]));
  expectStatus(answer, 200, 'the material');
  assert.ok(!answer.body.records.some((record: { ref: string }) => toUuid(record.ref) === other.r.owner), 'the other owner\'s turn is not read');
  assert.deepEqual(
    answer.body.unresolved.map((item: { kind: string; ref: string; entryId: string }) => [item.kind, toUuid(item.ref), toUuid(item.entryId)]),
    [['turn', other.r.owner, s.entries.keyword]],
    'it is listed as a source no record of this account answers',
  );
});

// ── the ledger ──────────────────────────────────────────────────────────────────────────────────

test('what became of each piece of material is written with its section, refused when malformed, and read back on both doors', { skip }, async () => {
  const h = await boot();
  const s = await scene(h);
  const { version, keys } = await confirmPlan(h, s);
  const section = (dispositions: unknown[]) => ({
    planVersion: version,
    repoSha: 'c'.repeat(40),
    sections: [{
      key: keys[1],
      materialSha256: createHash('sha256').update(JSON.stringify(dispositions)).digest('hex'),
      markdown: '测试在宿主上跑。',
      footnotes: [],
      dispositions,
    }],
  });
  const write = (body: unknown) => call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/docs/${SLUG}`, body);
  const ledger = [
    { material: 'C1', kind: 'code', ref: 'src/runner-go/runloop.go#L10-40', action: 'adopt', into: null, reason: '讲 runLoop 怎么领取' },
    { material: 'S1', kind: 'turn', ref: s.r.owner, action: 'merge', into: 'S2', reason: `与 S2 说的是同一件事，S2 更新；密钥 ${LITERAL}` },
    { material: 'S2', kind: 'task_comment', ref: s.r.delivery, action: 'adopt', into: null, reason: '交付记录' },
    { material: 'S3', kind: 'tool_call', ref: s.r.plain, action: 'drop', into: null, reason: '与本节无关' },
    { material: 'S4', kind: 'turn', ref: s.r.notOwners, action: 'filtered', into: null, reason: '平台自动生成的复查模板' },
    { material: 'D1', kind: 'design_doc', ref: 'docs/architecture.md#L1-80', action: 'over_cap', into: null, reason: '超出本节材料上限' },
  ];
  assert.deepEqual([...new Set(ledger.map((item) => item.action))].sort(), [...WIKI_DOC_DISPOSITION_ACTIONS].sort(), 'every action is exercised');
  expectStatus(await write(section(ledger)), 200, 'a section with its ledger');
  const stored = await h.prisma.wikiDocSection.findFirstOrThrow({ where: { ownerId: s.owner.id, key: keys[1] }, select: { dispositions: true } });
  const kept = stored.dispositions as Array<{ material: string; reason: string }>;
  assert.deepEqual(kept.map((item) => item.material), ledger.map((item) => item.material), 'stored as it came, in its order');
  assert.ok(kept.every((item) => !item.reason.includes(LITERAL)), 'a reason is redacted like everything stored');

  // Both doors read it back with the section.
  const page = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/docs/${SLUG}`);
  expectStatus(page, 200, 'the owner\'s page');
  const onPage = page.body.sections.find((sec: { key: string }) => sec.key === keys[1]);
  assert.deepEqual(onPage.dispositions.map((item: { action: string }) => item.action), ledger.map((item) => item.action));
  const writerDoc = await call(h, s.maintainer, 'GET', `/runner/wiki/spaces/${s.spaceId}/docs/${SLUG}`);
  expectStatus(writerDoc, 200, 'the maintenance run\'s read');
  assert.deepEqual(writerDoc.body, page.body, 'the runner door reads the document as the owner does');
  const unwritten = page.body.sections.find((sec: { key: string }) => sec.key === keys[0]);
  assert.deepEqual(unwritten.dispositions, [], 'a section not written yet has none');

  // Malformed: every error at once, nothing written.
  const bad = await write(section([
    { material: 'S1', kind: 'turn', ref: s.r.owner, action: 'keep', into: null, reason: 'x' },
    { material: 'S2', kind: 'turn', ref: s.r.owner, action: 'merge', into: null, reason: 'x' },
    { material: 'S3', kind: 'turn', ref: s.r.owner, action: 'merge', into: 'S9', reason: 'x' },
    { material: 'S4', kind: 'turn', ref: s.r.owner, action: 'drop', into: 'S1', reason: 'x' },
    { material: 'S5', kind: 'turn', ref: s.r.owner, action: 'drop', into: null, reason: '  ' },
    { material: 'S5', kind: 'nothing', ref: s.r.owner, action: 'drop', into: null, reason: 'x', extra: true },
  ]));
  expectStatus(bad, 422, 'a malformed ledger');
  assert.equal(bad.body.code, 'WIKI_DOC_INVALID');
  const paths = bad.body.errors.map((error: { path: string }) => error.path);
  for (const at of [
    'sections[0].dispositions[0].action',
    'sections[0].dispositions[1].into',
    'sections[0].dispositions[2].into',
    'sections[0].dispositions[3].into',
    'sections[0].dispositions[4].reason',
    'sections[0].dispositions[5].material',
    'sections[0].dispositions[5].kind',
    'sections[0].dispositions[5].extra',
  ]) {
    assert.ok(paths.includes(at), `an error at ${at} among ${paths.join(', ')}`);
  }
  const after = await h.prisma.wikiDocSection.findFirstOrThrow({ where: { ownerId: s.owner.id, key: keys[1] }, select: { dispositions: true } });
  assert.deepEqual(after.dispositions, stored.dispositions, 'nothing was written');
  // Stored as an array, and the migration holds it to one.
  const check = await h.sql.query<{ def: string }>(`SELECT pg_get_constraintdef(oid) AS def FROM pg_constraint WHERE conname = 'wiki_doc_section_dispositions_chk'`);
  assert.match(check.rows[0]?.def ?? '', /jsonb_typeof\(dispositions\) = 'array'/u);
});
