/**
 * The near-neighbour lookup every add runs, at the size a maintenance run or an import writes into.
 *
 * `WikiService.nearNeighbours` answers `similar[]` for every add and supersede: the five entries of the
 * space whose search text is most trigram-similar to the draft's title and summary. It ran inside the
 * changeset's one interactive transaction, which Prisma closed after 5 s. On production, at 2,606
 * entries, it was planned as a scan of the space that tested every row at ~0.1 ms a row, so a large
 * space took one to three ops per changeset. Migration 0313 prices that test for the planner; the
 * lookup hands the draft's text over as an InitPlan output, and asks for a rejection's reason only for
 * the rows it returns. Even so, on 2026-09-29 a maintenance run's thirty adds at 4,300 entries spent a
 * third of the transaction in it under a loaded host and the transaction closed (P2028): now every
 * draft's neighbours are read before the transaction opens, in one statement, and the transaction
 * re-checks them (wiki-neighbours.ts) under a timeout of its own.
 *
 * The data, bulk-inserted in SQL: first a space of 2,606 entries alone in the table — production as it
 * was when its writes slowed down — and then beside it one space of 10,000 active entries and another
 * owner's space of 5,000. Their text comes from a seeded generator shaped like the preview space's —
 * mixed runs of CJK and Latin words, Zipf-distributed, a few hundred characters an entry — heavier than
 * production if anything: a generated draft's trigrams pass the index's bound on ~4% of the entries on
 * average, against ~2.5% measured on production. Planted in every space: one family of
 * near-duplicates, with a tie on score, a rejected member and one past fifth place.
 *
 * Five claims, each its own case:
 *   1. at production's size the lookup reads the trigram index, where before 0313 it read and tested
 *      every entry of the space;
 *   2. the other owner's entries never reach this owner's `similar[]`, though they are neighbours in
 *      their own space;
 *   3. `similar[]` is what the lookup as it stood before 0313 returned: the same five in the same
 *      order, and a rejected neighbour still with the reason it was rejected;
 *   4. after an explicit ANALYZE the lookup among the 10,000 and the 5,000 reads the trigram index,
 *      never scans the table, and asks for a reason once per row it returns, not once per candidate;
 *   5. thirty adds into the 10,000 commit, their transaction within 3 s of the same thirty's into an
 *      empty space in the same run. Relative, because the absolute time of a changeset is mostly its
 *      twelve statements an add (`recordOp`, `applyOp`, `recomputeFlags`) and the host's load, neither of
 *      which this is about; and the transaction's, because the lookups are paid before it opens.
 *
 * And, of the neighbours read before the transaction (a second test, over the same data):
 *   6. what thirty drafts are answered is what the lookup inside the transaction answers, draft by
 *      draft, and the one statement that reads them reads the trigram index once per draft;
 *   7. a draft meets what the changeset's own earlier ops wrote — a lineage an add wrote, an entry a
 *      retire moved, an entry an amend rewrote — exactly as when every lookup ran inside, and a neighbour
 *      another writer changed between the read and the transaction is read again;
 *   8. a maintenance run's thirty adds among 10,000 entries, each citing three records, keep the
 *      transaction well under the 5 s that closed it, with no lookup inside it, and about as long as
 *      the same thirty into an empty space; every step's time is in the diagnostics;
 *   9. with every statement slowed, and with four such changesets at once, every one commits.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-scale.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every row belongs to an account it created.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { after, test } from 'node:test';
import { setTimeout as sleep } from 'node:timers/promises';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import { Prisma, type PrismaClient } from '@prisma/client';
import { toUuid, type WikiSimilar } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { RealtimeService } from '../realtime/realtime.service';
import { WikiController } from './wiki.controller';
import { ChangesetNeighbours, type NeighbourDraft } from './wiki-neighbours';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

const BIG = 10_000;
const OTHER = 5_000;
/** The preview space when its writes slowed to one to three ops a changeset (2026-09-27). */
const PRODUCTION = 2_606;
const OPS = 30;
/** What the thirty adds into the 10,000 may take over the same thirty into an empty space. */
const OVER_BASELINE_MS = 3_000;

// ── the probe ───────────────────────────────────────────────────────────────────────────────────

/** One statement the service under test issued, inside its changeset's transaction or before it. */
interface Statement {
  inside: boolean;
  /** `model.operation`, or `raw:<which statement>` for a raw one. */
  what: string;
  ms: number;
}

/** One transaction the service under test opened. */
interface Opened {
  /** What it was opened with. */
  options: unknown;
  /** From the closure's start to the commit: what Prisma's timeout counts. */
  ms: number;
  committed: boolean;
  error?: string;
}

type Call = (...args: unknown[]) => unknown;

/** Which raw statement this is, by what it says. */
function rawStatement(args: readonly unknown[]): string {
  const first = args[0] as { sql?: string } | readonly string[] | undefined;
  const text = Array.isArray(first) ? first.join('?') : ((first as { sql?: string } | undefined)?.sql ?? '');
  if (/AS "earlier"/u.test(text)) return 'raw:neighbour pairs';
  if (/similarity\(/u.test(text)) return 'raw:neighbours';
  if (/"current_revision" AS "currentRevision"/u.test(text)) return 'raw:neighbour re-check';
  if (/"applied_by_mode"/u.test(text)) return 'raw:run changes';
  return 'raw:other';
}

/**
 * The client the service under test is handed instead of the real one: every statement timed and named,
 * inside its transaction or before it; every one slowed by `delayMs`, and a neighbour lookup by
 * `lookupDelayMs` more, as a loaded host slows them — the lookup most; and `beforeTransaction` run once,
 * between what a submission reads before its transaction and the transaction itself, which is when
 * another writer can commit in between.
 */
class Probe {
  statements: Statement[] = [];
  opened: Opened[] = [];
  delayMs = 0;
  lookupDelayMs = 0;
  beforeTransaction: (() => Promise<void>) | null = null;
  readonly client: PrismaClient;

  constructor(real: PrismaClient) {
    this.client = this.wrap(real, false) as PrismaClient;
  }

  reset(): void {
    this.statements = [];
    this.opened = [];
    this.delayMs = 0;
    this.lookupDelayMs = 0;
    this.beforeTransaction = null;
  }

  private wrap(target: object, inside: boolean): unknown {
    return new Proxy(target, {
      get: (object, property) => {
        const value = Reflect.get(object, property, object) as unknown;
        if (property === '$transaction' && !inside && typeof value === 'function') {
          return async (work: (tx: unknown) => Promise<unknown>, options?: unknown) => {
            const hook = this.beforeTransaction;
            this.beforeTransaction = null;
            if (hook) await hook();
            let started = 0;
            try {
              const result = await (value as Call).call(object, (tx: object) => {
                started = performance.now();
                return work(this.wrap(tx, true));
              }, options);
              this.opened.push({ options, ms: performance.now() - started, committed: true });
              return result;
            } catch (error) {
              this.opened.push({
                options,
                ms: started ? performance.now() - started : 0,
                committed: false,
                error: String((error as Error)?.message ?? error),
              });
              throw error;
            }
          };
        }
        if (typeof property === 'string' && /^\$(queryRaw|executeRaw)/u.test(property) && typeof value === 'function') {
          return (...args: unknown[]) => this.run(inside, rawStatement(args), () => (value as Call).apply(object, args));
        }
        if (typeof property === 'string' && !/^[$_]/u.test(property) && value !== null && typeof value === 'object') {
          return new Proxy(value, {
            get: (delegate, operation) => {
              const fn = Reflect.get(delegate, operation, delegate) as unknown;
              if (typeof fn !== 'function') return fn;
              return (...args: unknown[]) => this.run(inside, `${property}.${String(operation)}`, () => (fn as Call).apply(delegate, args));
            },
          });
        }
        return typeof value === 'function' ? (value as Call).bind(object) : value;
      },
    });
  }

  private async run(inside: boolean, what: string, statement: () => unknown): Promise<unknown> {
    const delay = this.delayMs + (what === 'raw:neighbours' ? this.lookupDelayMs : 0);
    if (delay > 0) await sleep(delay);
    const started = performance.now();
    try {
      return await statement();
    } finally {
      this.statements.push({ inside, what, ms: performance.now() - started });
    }
  }
}

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  /** The service both doors are served by, over `probe.client`. */
  service: WikiService;
  probe: Probe;
  /** bearer → the account it was issued to */
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const probe = new Probe(prisma);
    const service = new WikiService(probe.client as unknown as PrismaService, {
      publishWikiChanged: () => undefined,
    } as unknown as RealtimeService);

    @Module({
      controllers: [WikiController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiScaleModule {}

    const app = await NestFactory.create(WikiScaleModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, probe, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
  ms: number;
}

/** One owner-door changeset, timed from the request to the answer — which comes after the commit. */
async function propose(h: Harness, owner: Account, spaceId: string, body: Record<string, unknown>): Promise<Answer> {
  const started = performance.now();
  const response = await fetch(`${h.base}/api/wiki/spaces/${spaceId}/changesets`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: `Bearer ${owner.bearer}` },
    body: JSON.stringify({ rationale: 'the near-neighbour lookup at scale', ...body }),
  });
  const text = await response.text();
  const ms = performance.now() - started;
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed, ms };
}

interface Similar {
  id: string;
  score: number;
  rejectedReason: string | null;
}

/** An op's `similar[]` as raw ids — the door answers in public ids — with the score and the reason. */
function similarOf(answer: Answer, seq = 0): Similar[] {
  assert.equal(answer.status, 200, `the owner's changeset: answered ${answer.status} ${JSON.stringify(answer.body)}`);
  const op = (answer.body.ops as Array<{ status: string; similar?: Array<Record<string, unknown>> }>)[seq];
  assert.notEqual(op.status, 'refused', `op ${seq} was refused: ${JSON.stringify(op)}`);
  return (op.similar ?? []).map((s) => ({
    id: toUuid(String(s.id)),
    score: Number(s.score),
    rejectedReason: (s.rejectedReason as string | undefined) ?? null,
  }));
}

// ── the corpus ──────────────────────────────────────────────────────────────────────────────────

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** The words this codebase's wiki is written in, most frequent first; the long tail is made up. */
const CORE_WORDS = `worktree apiserver runner session task project migration prisma index trigram merge branch commit
review wiki entry space owner agent coordinator acceptance spec test build deploy release version client web ios
macos swift schema column table query plan cursor queue lease heartbeat timeout retry transaction lock row
container docker compose postgres node typescript shared contract door route controller service module cache
push search anchor source quote revision changeset op decision pitfall recipe concept convention principle
state status trust flag challenge reject accept promote supersede retire verify fixture overlay symlink tsc
vitest render layout sheet menu toolbar sidebar badge count list card button label tint theme dark light
provider model engine claude codex kimi token budget usage quota limit breaker spot check mode tiered manual
automatic import maintenance loader batch idempotency key replay conflict snapshot isolation vacuum analyze
the a to of and in is for on with not be it that this when from by as are at or run an if`.split(/\s+/u);

interface Vocabulary {
  latin: string[];
  cjk: string[];
}

let vocabulary: Vocabulary | undefined;

/** 20,000 Latin words and 3,000 ideographs, the same every run. */
function words(): Vocabulary {
  if (vocabulary) return vocabulary;
  const rand = mulberry32(12_345);
  const latin = [...CORE_WORDS];
  const seen = new Set(latin);
  while (latin.length < 20_000) {
    let word = '';
    for (let i = 3 + Math.floor(rand() * 8); i > 0; i -= 1) word += String.fromCharCode(97 + Math.floor(rand() * 26));
    if (!seen.has(word)) {
      seen.add(word);
      latin.push(word);
    }
  }
  const cjk: string[] = [];
  const seenCjk = new Set<string>();
  while (cjk.length < 3_000) {
    const ideograph = String.fromCodePoint(0x4e00 + Math.floor(rand() * 0x5000));
    if (!seenCjk.has(ideograph)) {
      seenCjk.add(ideograph);
      cjk.push(ideograph);
    }
  }
  vocabulary = { latin, cjk };
  return vocabulary;
}

/** Rank r drawn with weight 1/r, the way words are used. */
function zipf(n: number, rand: () => number): () => number {
  const cdf = new Float64Array(n);
  let sum = 0;
  for (let i = 0; i < n; i += 1) {
    sum += 1 / (i + 1);
    cdf[i] = sum;
  }
  return () => {
    const x = rand() * sum;
    let lo = 0;
    let hi = n - 1;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (cdf[mid] < x) lo = mid + 1;
      else hi = mid;
    }
    return lo;
  };
}

interface Text {
  title: string;
  summary: string;
  fields: { definition: string; boundaries: string };
}

/** A seeded stream of concept entries: runs of one to eight ideographs between Latin words. */
function corpus(seed: number): () => Text {
  const rand = mulberry32(seed);
  const { latin, cjk } = words();
  const pickLatin = zipf(latin.length, rand);
  const pickCjk = zipf(cjk.length, rand);
  const phrase = (min: number, max: number): string => {
    const parts: string[] = [];
    for (let n = min + Math.floor(rand() * (max - min + 1)); n > 0; n -= 1) {
      if (rand() < 0.5) {
        parts.push(latin[pickLatin()]);
      } else {
        let run = '';
        for (let k = 1 + Math.floor(rand() * 8); k > 0; k -= 1) run += cjk[pickCjk()];
        parts.push(rand() < 0.3 ? `${run}，` : run);
      }
    }
    return parts.join(' ');
  };
  const clip = (text: string, max: number): string => (text.length <= max ? text : text.slice(0, max).trimEnd());
  return () => ({
    title: clip(phrase(3, 7), 120),
    summary: clip(phrase(8, 18), 280),
    fields: { definition: phrase(8, 18), boundaries: phrase(5, 12) },
  });
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-scale-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

/**
 * A Manual space unless another mode is named: the owner's own writes apply at once in every mode, so
 * the mode only keeps it plain. A maintenance run writes into the Automatic space the owner's is.
 */
async function space(h: Harness, ownerId: string, slug: string, mode: 'manual' | 'automatic' = 'manual'): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "wiki_space"("id","owner_id","slug","title","settings") VALUES ($1,$2,$3,'spec',$4)`,
    [id, ownerId, slug, JSON.stringify({ reviewMode: mode })],
  );
  return id;
}

/** `count` active entries in one statement per 2,000 — never through the door, which is what is timed. */
async function bulkEntries(h: Harness, ownerId: string, spaceId: string, count: number, seed: number): Promise<void> {
  const next = corpus(seed);
  const since = Date.parse('2026-01-01T00:00:00Z');
  for (let from = 0; from < count; from += 2_000) {
    const ids: string[] = [];
    const titles: string[] = [];
    const summaries: string[] = [];
    const fields: string[] = [];
    const recorded: string[] = [];
    for (let i = from; i < Math.min(count, from + 2_000); i += 1) {
      const text = next();
      ids.push(randomUUID());
      titles.push(text.title);
      summaries.push(text.summary);
      fields.push(JSON.stringify(text.fields));
      recorded.push(new Date(since + i * 60_000).toISOString());
    }
    await h.sql.query(
      `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision",
                                "title","summary","fields","valid_from","recorded_at")
       SELECT id, $6::uuid, $7::uuid, 'concept', 'active', 'confirmed', 1, title, summary, fields::jsonb,
              recorded::timestamptz, recorded::timestamptz
         FROM unnest($1::uuid[], $2::text[], $3::text[], $4::text[], $5::text[])
              AS input(id, title, summary, fields, recorded)`,
      [ids, titles, summaries, fields, recorded, ownerId, spaceId],
    );
  }
}

/** The draft whose neighbours are looked up: its title and summary are the text the lookup matches. */
const DRAFT: Text = {
  title: 'Migration numbers collide only when two branches merge',
  summary: '两条分支各取下一个空号 迁移撞号 each tree stays green and the ledger breaks after the merge',
  fields: { definition: 'Two migrations share a number', boundaries: 'Not a Prisma bug' },
};

/**
 * Its near-duplicates, strongest first: the similarity of each entry's search text to the draft's,
 * measured when this was written, is in the comment beside it. `twin` and `same` score alike and the
 * later-recorded comes first; `rejected` was rejected twice, most recently as a duplicate; `sixth` is a
 * neighbour one place past the five; `below` is under pg_trgm's 0.3 and no neighbour at all.
 */
const FAMILY: Array<{ key: string; text: Text; status?: 'rejected'; recordedAt: string }> = [
  { key: 'twin', recordedAt: '2026-06-01T00:00:07Z', text: DRAFT }, // 0.843
  { key: 'same', recordedAt: '2026-06-01T00:00:02Z', text: DRAFT }, // 0.843
  {
    key: 'close', // 0.643
    recordedAt: '2026-06-01T00:00:05Z',
    text: {
      title: 'Migration numbers collide when two branches merge',
      summary: '两条分支各取下一个空号 迁移撞号 each tree stays green until the merge',
      fields: DRAFT.fields,
    },
  },
  {
    key: 'rejected', // 0.559
    status: 'rejected',
    recordedAt: '2026-06-01T00:00:03Z',
    text: {
      title: 'Two branches can take the same migration number',
      summary: '迁移撞号 each tree stays green and the ledger breaks after the merge',
      fields: { definition: 'Renumber the later one', boundaries: 'Holes in the numbering are fine' },
    },
  },
  {
    key: 'fifth', // 0.532
    recordedAt: '2026-06-01T00:00:06Z',
    text: {
      title: 'Migration numbers collide after a merge',
      summary: '两条分支各取下一个空号 迁移撞号 each tree is green on its own',
      fields: DRAFT.fields,
    },
  },
  {
    key: 'sixth', // 0.358
    recordedAt: '2026-06-01T00:00:04Z',
    text: {
      title: 'Migration numbers collide',
      summary: '迁移撞号 the ledger breaks after the merge',
      fields: {
        definition: 'Renumber the later migration to the next free number and sync its references',
        boundaries: 'Holes in the numbering are fine; duplicates below 0246 are exempt',
      },
    },
  },
  {
    key: 'below', // 0.245
    recordedAt: '2026-06-01T00:00:01Z',
    text: {
      title: 'Renumber the later migration',
      summary: 'the ledger test names the colliding pair',
      fields: { definition: 'Renumber the later one', boundaries: 'Holes are fine' },
    },
  },
];

/** The family in one space, and the two decisions that rejected its `rejected` member. */
async function plantFamily(h: Harness, ownerId: string, spaceId: string): Promise<Record<string, string>> {
  const ids: Record<string, string> = {};
  for (const member of FAMILY) {
    const id = randomUUID();
    ids[member.key] = id;
    const rejected = member.status === 'rejected';
    // 0307's lineage CHECKs: a rejected entry's trust is `proposed`, and a terminal status has retired_at.
    await h.sql.query(
      `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision",
                                "title","summary","fields","valid_from","recorded_at","retired_at")
       VALUES ($1,$2,$3,'concept',$4,$5,1,$6,$7,$8,$9,$9,$10)`,
      [
        id,
        ownerId,
        spaceId,
        rejected ? 'rejected' : 'active',
        rejected ? 'proposed' : 'confirmed',
        member.text.title,
        member.text.summary,
        JSON.stringify(member.text.fields),
        member.recordedAt,
        rejected ? member.recordedAt : null,
      ],
    );
  }
  const changeset = randomUUID();
  await h.sql.query(
    `INSERT INTO "wiki_changeset"("id","owner_id","space_id","origin","rationale","status","decided_at")
     VALUES ($1,$2,$3,'agent','a proposal the owner rejected','settled',now())`,
    [changeset, ownerId, spaceId],
  );
  for (const [seq, reason, decidedAt] of [
    [0, 'not_useful', '2026-06-02T00:00:00Z'],
    [1, 'duplicate', '2026-06-03T00:00:00Z'],
  ] as const) {
    await h.sql.query(
      `INSERT INTO "wiki_changeset_op"("id","changeset_id","owner_id","seq","op","payload","decision",
                                       "decision_reason","decided_at","result_entry_id","result_revision")
       VALUES ($1,$2,$3,$4,'add','{}','rejected',$5,$6,$7,1)`,
      [randomUUID(), changeset, ownerId, seq, reason, decidedAt, ids.rejected],
    );
  }
  return ids;
}

/**
 * Where the space settles once autovacuum has caught up with a bulk load: GIN's pending list merged
 * into the index (every search scans what is still pending), and statistics that know the table's
 * size. Done here, and not left to the autovacuum clock, so every run starts the same.
 */
async function settle(h: Harness): Promise<void> {
  await h.sql.query('VACUUM (ANALYZE) "wiki_entry"');
  await h.sql.query('VACUUM (ANALYZE) "wiki_changeset_op"');
}

interface ProductionFixture {
  owner: Account;
  /** A space of 2,606 entries, alone in the table as the preview space was on production. */
  productionSized: string;
}

let production: Promise<ProductionFixture> | undefined;

function productionLoaded(h: Harness): Promise<ProductionFixture> {
  production ??= (async () => {
    const owner = await account(h, 'the owner of the big space');
    const productionSized = await space(h, owner.id, 'production-sized');
    await bulkEntries(h, owner.id, productionSized, PRODUCTION - FAMILY.length + 1, 4);
    await plantFamily(h, owner.id, productionSized);
    await settle(h);
    return { owner, productionSized };
  })();
  return production;
}

interface Fixture extends ProductionFixture {
  other: Account;
  big: string;
  otherSpace: string;
  family: Record<string, string>;
  otherFamily: Record<string, string>;
}

let fixture: Promise<Fixture> | undefined;

function loaded(h: Harness): Promise<Fixture> {
  fixture ??= (async () => {
    const { owner, productionSized } = await productionLoaded(h);
    const other = await account(h, 'another owner');
    const big = await space(h, owner.id, 'ten-thousand');
    const otherSpace = await space(h, other.id, 'five-thousand');
    await bulkEntries(h, owner.id, big, BIG - FAMILY.length + 1, 1);
    await bulkEntries(h, other.id, otherSpace, OTHER - FAMILY.length + 1, 2);
    const family = await plantFamily(h, owner.id, big);
    const otherFamily = await plantFamily(h, other.id, otherSpace);
    await settle(h);
    return { owner, productionSized, other, big, otherSpace, family, otherFamily };
  })();
  return fixture;
}

// ── the lookup, before 0313 ─────────────────────────────────────────────────────────────────────

/**
 * The lookup as it stood before 0313, word for word (commit 1f64da2cc, `nearNeighbours`), with the
 * template's parameters numbered: $1 the draft's text, $2 the owner, $3 the space, $4 the excluded
 * entry. The "before" that `similar[]` is held to.
 */
const NEIGHBOURS_BEFORE_0313 = `
      SELECT e."id" AS "id",
             e."kind" AS "kind",
             e."title" AS "title",
             e."status" AS "status",
             e."trust" AS "trust",
             similarity(wiki_entry_search_text(e."title", e."summary", e."aliases", e."fields"), $1)::float8 AS "score",
             (SELECT o."decision_reason"
                FROM "wiki_changeset_op" o
               WHERE o."result_entry_id" = e."id" AND o."decision" = 'rejected'
               ORDER BY o."decided_at" DESC NULLS LAST
               LIMIT 1) AS "rejectedReason"
        FROM "wiki_entry" e
       WHERE e."owner_id" = $2::uuid
         AND e."space_id" = $3::uuid
         AND ($4::uuid IS NULL OR e."id" <> $4::uuid)
         AND wiki_entry_search_text(e."title", e."summary", e."aliases", e."fields") % $1
       ORDER BY "score" DESC, e."recorded_at" DESC
       LIMIT 5
    `;

/** The five as the lookup before 0313 found them — under the function's cost before 0313 too. */
async function neighboursBefore0313(h: Harness, ownerId: string, spaceId: string, exclude: string | null): Promise<Similar[]> {
  const text = `${DRAFT.title} ${DRAFT.summary}`.trim();
  await h.sql.query('BEGIN');
  try {
    await h.sql.query('ALTER FUNCTION "wiki_entry_search_text"(TEXT, TEXT, TEXT[], JSONB) COST 100');
    const rows = await h.sql.query<{ id: string; score: number; rejectedReason: string | null }>(
      NEIGHBOURS_BEFORE_0313,
      [text, ownerId, spaceId, exclude],
    );
    return rows.rows.map((row) => ({ id: row.id, score: Number(row.score), rejectedReason: row.rejectedReason }));
  } finally {
    await h.sql.query('ROLLBACK');
  }
}

// ── the plan ────────────────────────────────────────────────────────────────────────────────────

interface PlanNode {
  'Node Type': string;
  'Relation Name'?: string;
  'Index Name'?: string;
  'Index Cond'?: string;
  'Parent Relationship'?: string;
  'Subplan Name'?: string;
  'Actual Rows': number;
  'Actual Loops': number;
  'Rows Removed by Index Recheck'?: number;
  'Rows Removed by Filter'?: number;
  Plans?: PlanNode[];
}

function nodesOf(node: PlanNode): PlanNode[] {
  return [node, ...(node.Plans ?? []).flatMap(nodesOf)];
}

/** The service's own lookup — the statement it builds, captured rather than copied — explained. */
async function explainLookup(h: Harness, ownerId: string, spaceId: string): Promise<{ root: PlanNode; text: string }> {
  const captured: Prisma.Sql[] = [];
  const recorder = {
    $queryRaw: (statement: Prisma.Sql) => {
      captured.push(statement);
      return Promise.resolve([]);
    },
  };
  const lookup = (h.service as unknown as {
    nearNeighbours: (tx: unknown, owner: string, space: string, draft: Record<string, unknown>, exclude: string | null) => Promise<unknown>;
  }).nearNeighbours.bind(h.service);
  await lookup(recorder, ownerId, spaceId, { title: DRAFT.title, summary: DRAFT.summary }, null);
  assert.equal(captured.length, 1, 'the lookup is one statement');
  const statement = captured[0];
  const json = await h.sql.query<{ 'QUERY PLAN': Array<{ Plan: PlanNode }> }>(
    `EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) ${statement.text}`,
    statement.values as unknown[],
  );
  const text = await h.sql.query<{ 'QUERY PLAN': string }>(`EXPLAIN (ANALYZE, BUFFERS) ${statement.text}`, statement.values as unknown[]);
  return { root: json.rows[0]['QUERY PLAN'][0].Plan, text: text.rows.map((row) => row['QUERY PLAN']).join('\n') };
}

/** A plan is a function of the statistics as much as of the data: taken now, not whenever autovacuum last ran. */
async function analyze(h: Harness): Promise<void> {
  await h.sql.query('ANALYZE "wiki_entry"');
  await h.sql.query('ANALYZE "wiki_changeset_op"');
}

/** The planted draft's lookup in `spaceId` reads the trigram index, and nothing else asks per candidate. */
async function assertReadsTheIndex(h: Harness, owner: Account, spaceId: string, size: number): Promise<void> {
  const { root, text } = await explainLookup(h, owner.id, spaceId);
  const nodes = nodesOf(root);
  const index = nodes.find((node) => node['Index Name'] === 'wiki_entry_search_trgm');
  assert.ok(index, `the lookup does not read the trigram index:\n${text}`);
  // The draft's text is an InitPlan's output to the plan, not a constant it was planned around —
  // around a constant, the planner runs `%` against every value in the expression's statistics.
  assert.ok(nodes.some((node) => node['Parent Relationship'] === 'InitPlan'), `the draft's text is not an InitPlan's output:\n${text}`);
  assert.doesNotMatch(index!['Index Cond'] ?? '', /Migration numbers/u, `the lookup was planned around the draft's text:\n${text}`);
  // `wiki_changeset_op` may be read whole — here it is a handful of rows, asked once per row
  // returned; the table of entries may not.
  assert.deepEqual(
    nodes.filter((node) => node['Node Type'] === 'Seq Scan' && node['Relation Name'] === 'wiki_entry'),
    [],
    `the lookup scans the table of entries:\n${text}`,
  );
  // The behaviour behind the shape: the rows it fetched from the table and tested are the index's
  // candidates, a small part of the space — not the space, which is what testing it row by row behind
  // the space's own index would read.
  const tested = nodes
    .filter((node) => node['Relation Name'] === 'wiki_entry')
    .reduce(
      (sum, node) => sum
        + (node['Actual Rows'] + (node['Rows Removed by Index Recheck'] ?? 0) + (node['Rows Removed by Filter'] ?? 0))
          * node['Actual Loops'],
      0,
    );
  assert.ok(tested < size / 10, `the lookup tested ${tested} of the space's ${size} entries:\n${text}`);

  const returned = root['Actual Rows'];
  assert.equal(returned, 5, `the planted draft has five neighbours:\n${text}`);
  const perRow = nodes.filter((node) => node['Parent Relationship'] === 'SubPlan');
  assert.ok(perRow.length > 0, `the rejection's reason is not asked per row at all:\n${text}`);
  for (const subplan of perRow) {
    assert.ok(subplan['Actual Loops'] > 0, `${subplan['Subplan Name']} never ran, so it proves nothing:\n${text}`);
    assert.ok(
      subplan['Actual Loops'] <= returned,
      `${subplan['Subplan Name']} ran ${subplan['Actual Loops']} times for ${returned} rows returned:\n${text}`,
    );
  }
}

// ── the cases ───────────────────────────────────────────────────────────────────────────────────

test('0313 · the near-neighbour lookup at 2,606 and at 10,000 entries', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const add = { op: 'add', entry: { kind: 'concept', ...DRAFT }, sources: [] };

  await t.test('at production\'s size, the space alone in the table as it was there, the lookup reads the index and not every entry', async () => {
    // Where the bug lived. A scan's price grows with the table, and the index's with the draft's
    // trigrams — about a hundred for a title and a summary — so with the test the scan repeats on every
    // row unpriced, the scan was the cheaper plan up to a few thousand entries: production read and
    // tested all 2,606, 290–470 ms an add. Past ~5,000 the index won even so, which is why this is
    // asked here and not only among the 10,000 below.
    const px = await productionLoaded(h);
    await analyze(h);
    await assertReadsTheIndex(h, px.owner, px.productionSized, PRODUCTION);
  });

  const fx = await loaded(h);

  await t.test('another owner\'s entries never reach this owner\'s neighbours, though they are neighbours in their own space', async () => {
    const mine = similarOf(await propose(h, fx.owner, fx.big, { dryRun: true, ops: [add] }));
    const theirs = new Set(Object.values(fx.otherFamily));
    assert.equal(mine.length, 5, 'the planted family is five neighbours deep');
    assert.deepEqual(mine.filter((s) => theirs.has(s.id)), [], 'another owner\'s entry is among this owner\'s neighbours');
    const outside = await h.sql.query(
      `SELECT count(*)::int AS n FROM "wiki_entry" WHERE "id" = ANY($1::uuid[]) AND "space_id" <> $2`,
      [mine.map((s) => s.id), fx.big],
    );
    assert.equal(outside.rows[0].n, 0, 'a neighbour came from outside the space asked about');
    // The twins are neighbours of the same draft where they live: absent above because of whose they
    // are, not because of what they say.
    const inTheirSpace = similarOf(await propose(h, fx.other, fx.otherSpace, { dryRun: true, ops: [add] }));
    assert.deepEqual(
      inTheirSpace.map((s) => s.id),
      ['twin', 'same', 'close', 'rejected', 'fifth'].map((key) => fx.otherFamily[key]),
      'in its own space the other owner\'s family is the five neighbours',
    );
  });

  await t.test('similar[] is what the lookup before 0313 returned: the same five in the same order, reasons kept', async () => {
    const before = await neighboursBefore0313(h, fx.owner.id, fx.big, null);
    const now = similarOf(await propose(h, fx.owner, fx.big, { dryRun: true, ops: [add] }));
    assert.deepEqual(now, before, 'an add\'s similar[] is not what the lookup before 0313 found');
    // What that comparison rests on, so it cannot pass by comparing two empty lists: the five in the
    // ranking's own order — score, then the later-recorded of a tie — the sixth left out, and the
    // rejected one carrying its latest reason.
    assert.deepEqual(
      now.map((s) => s.id),
      ['twin', 'same', 'close', 'rejected', 'fifth'].map((key) => fx.family[key]),
      'the five, in order',
    );
    assert.equal(now[0].score, now[1].score, 'the first two tie on score, and are ordered by when they were recorded');
    assert.deepEqual(
      now.map((s) => s.rejectedReason),
      [null, null, null, 'duplicate', null],
      'the rejected neighbour carries the reason of its latest rejection, and no other carries one',
    );

    // A supersede excludes the entry it replaces; the one after the five moves up.
    const superseding = {
      op: 'supersede',
      entryId: fx.family.close,
      baseRevision: 1,
      entry: { kind: 'concept', ...DRAFT },
      sources: [],
    };
    const beforeExcluding = await neighboursBefore0313(h, fx.owner.id, fx.big, fx.family.close);
    const nowExcluding = similarOf(await propose(h, fx.owner, fx.big, { dryRun: true, ops: [superseding] }));
    assert.deepEqual(nowExcluding, beforeExcluding, 'a supersede\'s similar[] is not what the lookup before 0313 found');
    assert.deepEqual(
      nowExcluding.map((s) => s.id),
      ['twin', 'same', 'rejected', 'fifth', 'sixth'].map((key) => fx.family[key]),
      'the superseded entry is left out and the sixth takes its place',
    );
  });

  await t.test('after an explicit ANALYZE the lookup reads the trigram index, not the table, and asks a reason per row it returns', async () => {
    await analyze(h);
    // What steers every caller of the function to its index, stated where a later migration cannot
    // quietly undo it: a `CREATE OR REPLACE FUNCTION "wiki_entry_search_text"` resets COST to 100.
    const cost = await h.sql.query<{ procost: number }>(
      `SELECT procost FROM pg_proc WHERE proname = 'wiki_entry_search_text'`,
    );
    assert.deepEqual(cost.rows.map((row) => Number(row.procost)), [10_000], 'wiki_entry_search_text lost the COST 0313 gave it');
    await assertReadsTheIndex(h, fx.owner, fx.big, BIG);
    await assertReadsTheIndex(h, fx.other, fx.otherSpace, OTHER);
  });

  await t.test(`${OPS} adds into ${BIG.toLocaleString('en-US')} entries commit, their transaction within ${OVER_BASELINE_MS / 1_000} s of the same into an empty space`, async () => {
    const warm = await space(h, fx.owner.id, 'warm-up');
    const empty = await space(h, fx.owner.id, 'empty');
    const next = corpus(3);
    const drafts = Array.from({ length: OPS }, () => ({ op: 'add', entry: { kind: 'concept', ...next() }, sources: [] }));
    const applied = (answer: Answer): number =>
      (answer.body?.ops as Array<{ status: string }> | undefined)?.filter((op) => op.status === 'applied').length ?? 0;

    // Once through the door first: the first request of a process pays for what every later one
    // reuses (query compilation, the pool's connections), and a server that is up has paid it.
    const warmUp = await propose(h, fx.owner, warm, { ops: drafts.slice(0, 3) });
    assert.equal(warmUp.status, 200, `the warm-up: answered ${warmUp.status} ${JSON.stringify(warmUp.body)}`);

    h.probe.reset();
    const baseline = await propose(h, fx.owner, empty, { ops: drafts });
    assert.equal(baseline.status, 200, `the empty space: answered ${baseline.status} ${JSON.stringify(baseline.body)}`);
    assert.equal(applied(baseline), OPS, 'every add into the empty space applies');
    const [baselineTransaction] = h.probe.opened;

    // A transaction Prisma closed (P2028) answers 500, and writes nothing.
    h.probe.reset();
    const loadedRun = await propose(h, fx.owner, fx.big, { ops: drafts });
    const [loadedTransaction] = h.probe.opened;
    const lookups = h.probe.statements.filter((statement) => statement.what === 'raw:neighbours' && !statement.inside);
    t.diagnostic(`baseline (empty space) ${Math.round(baseline.ms)} ms, its transaction ${Math.round(baselineTransaction.ms)} ms; `
      + `${BIG.toLocaleString('en-US')} entries ${Math.round(loadedRun.ms)} ms, its transaction ${Math.round(loadedTransaction.ms)} ms, `
      + `the lookup before it ${Math.round(lookups.reduce((sum, lookup) => sum + lookup.ms, 0))} ms`);
    assert.equal(loadedRun.status, 200, `the big space: answered ${loadedRun.status} ${JSON.stringify(loadedRun.body)}`);
    assert.equal(applied(loadedRun), OPS, 'every add into the big space applies');
    // The transaction, not the request: the lookups the 10,000 cost are paid before it opens (the second
    // test below), and what the transaction still does is the same statements for either space. The
    // request as a whole pays the lookups wherever they run, at whatever the host's load makes them cost —
    // that the lookup reads the index is asserted above, as a plan, which no load changes.
    assert.ok(
      loadedTransaction.ms <= baselineTransaction.ms + OVER_BASELINE_MS,
      `${OPS} adds held their transaction ${Math.round(loadedTransaction.ms)} ms among ${BIG} entries and `
        + `${Math.round(baselineTransaction.ms)} ms in an empty space: the space's size reached the transaction`,
    );
    const committed = await h.sql.query(
      `SELECT count(*)::int AS n FROM "wiki_entry" WHERE "space_id" = $1 AND "status" = 'active'`,
      [fx.big],
    );
    assert.equal(committed.rows[0].n, BIG + OPS, 'the big space holds its entries and the thirty new ones');
  });
});

// ── the neighbours read before the transaction ──────────────────────────────────────────────────

/** Where the drafts' neighbours were looked up: before the transaction, and inside it. */
function lookupsOf(probe: Probe): { before: number; inside: number } {
  const lookups = probe.statements.filter((statement) => statement.what === 'raw:neighbours');
  return { before: lookups.filter((lookup) => !lookup.inside).length, inside: lookups.filter((lookup) => lookup.inside).length };
}

/** The step of an add a statement belongs to, as the diagnostics name them. */
function stepOf(what: string): string {
  if (what.startsWith('raw:neighbour') || what === 'wikiChangesetOp.findMany') return 'neighbours';
  if (/^(conversationTurn|runEvent|toolCall|task|taskComment|approval|sessionMergeReceipt|projectBlocker|wikiNote)\./u.test(what)) {
    return 'sources and taint';
  }
  if (what.endsWith('.count') || what === 'raw:run changes') return 'review mode and quotas';
  if (/\.(create|createMany|update|updateMany|upsert|delete|deleteMany)$/u.test(what)) return 'writes';
  return 'other reads';
}

interface Timing {
  statements: number;
  ms: number;
  steps: Map<string, { statements: number; ms: number }>;
}

/** The statements before the transaction, or inside it, by step. */
function timing(probe: Probe, inside: boolean): Timing {
  const own = probe.statements.filter((statement) => statement.inside === inside);
  const steps = new Map<string, { statements: number; ms: number }>();
  for (const statement of own) {
    const step = steps.get(stepOf(statement.what)) ?? { statements: 0, ms: 0 };
    step.statements += 1;
    step.ms += statement.ms;
    steps.set(stepOf(statement.what), step);
  }
  return { statements: own.length, ms: own.reduce((sum, statement) => sum + statement.ms, 0), steps };
}

function spelled(of: Timing): string {
  const steps = [...of.steps]
    .sort((left, right) => right[1].ms - left[1].ms)
    .map(([step, spent]) => `${step} ${spent.statements} × ${Math.round(spent.ms)} ms`);
  return `${of.statements} statements, ${Math.round(of.ms)} ms: ${steps.join('; ')}`;
}

interface Outcome {
  seq: number;
  status: string;
  entryId?: string | null;
  waitsFor?: string;
  similar?: WikiSimilar[];
}

/** A changeset's outcomes with every entry it wrote named by the op that wrote it, so two runs compare. */
function comparable(answer: Record<string, unknown>, ops: ReadonlyArray<Record<string, unknown>>): unknown[] {
  const outcomes = answer.ops as Outcome[];
  const written = new Map<string, string>();
  outcomes.forEach((outcome, seq) => {
    if ((ops[seq].op === 'add' || ops[seq].op === 'supersede') && outcome.entryId) written.set(outcome.entryId, `written by op ${seq}`);
  });
  return outcomes.map((outcome) => ({
    status: outcome.status,
    similar: (outcome.similar ?? []).map((near) => ({ ...near, id: written.get(near.id) ?? near.id })),
  }));
}

/**
 * The same changeset recorded with every lookup inside its transaction — as it was before the neighbours
 * were read ahead of it — and rolled back, so the space is as it was for the run under test.
 */
async function everyLookupInside(h: Harness, principal: WikiPrincipal, spaceId: string, ops: unknown[]): Promise<Record<string, unknown>> {
  const record = (h.service as unknown as { recordChangeset: Call }).recordChangeset.bind(h.service);
  const settings = (await h.sql.query(`SELECT "settings" FROM "wiki_space" WHERE "id" = $1`, [spaceId])).rows[0].settings;
  const rollback = new Error('the reference run is rolled back');
  let answer: Record<string, unknown> | undefined;
  await h.prisma
    .$transaction(async (tx) => {
      answer = (await record(tx, principal, { id: spaceId, settings }, ops, { rationale: 'the reference', ops }, null, [])) as Record<string, unknown>;
      throw rollback;
    }, { timeout: 60_000, maxWait: 10_000 })
    .catch((error: unknown) => {
      if (error !== rollback) throw error;
    });
  assert.ok(answer, 'the reference run answered');
  return answer!;
}

/** Entries already in the space, written directly: what a changeset's drafts will meet. */
async function standing(h: Harness, ownerId: string, spaceId: string, texts: readonly Text[]): Promise<string[]> {
  const ids: string[] = [];
  for (const text of texts) {
    const id = randomUUID();
    await h.sql.query(
      `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields")
       VALUES ($1,$2,$3,'concept','active','confirmed',1,$4,$5,$6)`,
      [id, ownerId, spaceId, text.title, text.summary, JSON.stringify(text.fields)],
    );
    ids.push(id);
  }
  return ids;
}

/** The statement `ChangesetNeighbours.read` builds for these drafts — captured rather than copied — explained. */
async function explainRead(h: Harness, ownerId: string, spaceId: string, drafts: NeighbourDraft[]): Promise<{ root: PlanNode; text: string }> {
  const captured: Prisma.Sql[] = [];
  const recorder = {
    $queryRaw: (statement: Prisma.Sql) => {
      captured.push(statement);
      return Promise.resolve([]);
    },
    wikiChangesetOp: { findMany: () => Promise.resolve([]) },
  };
  await ChangesetNeighbours.read(recorder as never, ownerId, spaceId, drafts);
  const statement = captured[0];
  const json = await h.sql.query<{ 'QUERY PLAN': Array<{ Plan: PlanNode }> }>(
    `EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) ${statement.text}`,
    statement.values as unknown[],
  );
  const text = await h.sql.query<{ 'QUERY PLAN': string }>(`EXPLAIN (ANALYZE, BUFFERS) ${statement.text}`, statement.values as unknown[]);
  return { root: json.rows[0]['QUERY PLAN'][0].Plan, text: text.rows.map((row) => row['QUERY PLAN']).join('\n') };
}

/** A draft as a lookup is asked about it. */
function asDraft(seq: number, text: Text): NeighbourDraft {
  return {
    seq,
    text: `${text.title} ${text.summary}`.trim(),
    exclude: null,
    written: { title: text.title, summary: text.summary, aliases: [], fields: text.fields },
  };
}

// ── a maintenance run's changesets ──────────────────────────────────────────────────────────────

/** One of the owner's sessions, in a workspace of theirs. */
async function session(h: Harness, ownerId: string): Promise<string> {
  const workspace = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id") VALUES ($1,'spec',$2)`, [workspace, ownerId]);
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","dispatch_origin","updated_at")
     VALUES ($1,'a wiki session','p',$2,$2,$3,'USER',now())`,
    [id, ownerId, workspace],
  );
  return id;
}

/** `count` tool calls of a session, none of them a web read: what the taint check reads, op after op. */
async function toolCalls(h: Harness, sessionId: string, count: number): Promise<void> {
  await h.sql.query(
    `INSERT INTO "tool_call"("id","session_id","name","output")
     SELECT gen_random_uuid(), $1::uuid, (ARRAY['Bash','Read','Edit','Grep'])[1 + g % 4], '"ok"'::jsonb
       FROM generate_series(1, $2::int) g`,
    [sessionId, count],
  );
}

interface Records {
  turns: string[];
  calls: string[];
  events: string[];
}

/** `count` of each record a dossier line cites — a turn, a tool call, an event — the i-th of each saying `fact <i>`. */
async function citedRecords(h: Harness, sessionId: string, count: number): Promise<Records> {
  const records: Records = {
    turns: Array.from({ length: count }, () => randomUUID()),
    calls: Array.from({ length: count }, () => randomUUID()),
    events: Array.from({ length: count }, () => randomUUID()),
  };
  await h.sql.query(
    `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status","kind","send_intent")
     SELECT r."id", $2::uuid, r."n"::int, gen_random_uuid()::text, 'the owner said fact ' || (r."n" - 1) || ' holds for the run',
            'ANSWERED', 'message', 'NEXT_TURN'
       FROM unnest($1::uuid[]) WITH ORDINALITY AS r("id", "n")`,
    [records.turns, sessionId],
  );
  await h.sql.query(
    `INSERT INTO "tool_call"("id","session_id","name","output")
     SELECT r."id", $2::uuid, 'Bash', to_jsonb('the command printed fact ' || (r."n" - 1) || ' in full')
       FROM unnest($1::uuid[]) WITH ORDINALITY AS r("id", "n")`,
    [records.calls, sessionId],
  );
  await h.sql.query(
    `INSERT INTO "run_event"("id","session_id","seq","type","payload")
     SELECT r."id", $2::uuid, r."n"::int, 'assistant', jsonb_build_object('text', 'the agent noticed fact ' || (r."n" - 1) || ' while it worked')
       FROM unnest($1::uuid[]) WITH ORDINALITY AS r("id", "n")`,
    [records.events, sessionId],
  );
  return records;
}

/** `count` adds as a maintenance run proposes them: each citing a turn, a tool call and an event, with a quote. */
function maintenanceOps(records: Records, seed: number, count = OPS): Array<Record<string, unknown>> {
  const next = corpus(seed);
  return Array.from({ length: count }, (_unused, n) => {
    const i = (seed * OPS + n) % records.turns.length;
    return {
      op: 'add',
      entry: { kind: 'concept', ...next() },
      sources: [
        { kind: 'turn', ref: records.turns[i], quote: `fact ${i} holds` },
        { kind: 'tool_call', ref: records.calls[i], quote: `printed fact ${i}` },
        { kind: 'event', ref: records.events[i], quote: `noticed fact ${i}` },
      ],
    };
  });
}

interface Maintained {
  /** The session the run proposes from. */
  maintainer: string;
  records: Records;
  /** Automatic, with 10,000 active entries. */
  big: string;
  /** Automatic, with none. */
  empty: string;
  /** Automatic, for the warm-up. */
  warm: string;
}

let maintained: Promise<Maintained> | undefined;

/** The owner's Automatic spaces a maintenance run writes into: one of 10,000 entries, one empty. */
function maintenanceLoaded(h: Harness, owner: Account): Promise<Maintained> {
  maintained ??= (async () => {
    const maintainer = await session(h, owner.id);
    const cited = await session(h, owner.id);
    await toolCalls(h, maintainer, 400);
    await toolCalls(h, cited, 2_000);
    const records = await citedRecords(h, cited, 120);
    const big = await space(h, owner.id, 'maintained', 'automatic');
    const empty = await space(h, owner.id, 'maintained-empty', 'automatic');
    const warm = await space(h, owner.id, 'maintained-warm-up', 'automatic');
    await bulkEntries(h, owner.id, big, BIG, 5);
    await settle(h);
    await h.sql.query('ANALYZE "tool_call"');
    return { maintainer, records, big, empty, warm };
  })();
  return maintained;
}

/** Every op of a maintenance run's changeset recorded, each waiting for its verification. */
function assertAllRecorded(answer: Record<string, unknown>, count: number, why: string): void {
  const outcomes = answer.ops as Outcome[];
  assert.equal(outcomes.length, count, `${why}: ${JSON.stringify(answer).slice(0, 500)}`);
  const refused = outcomes.filter((outcome) => outcome.status !== 'pending' || outcome.waitsFor !== 'verification');
  assert.deepEqual(refused, [], `${why}: every op waits for its verification`);
}

test('the neighbours read before the transaction · the same similar[], and a transaction that no longer grows with the space', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const fx = await loaded(h);
  const { probe, service } = h;
  const owner: WikiPrincipal = { origin: 'owner', ownerId: fx.owner.id, userId: fx.owner.id, sessionId: null, toolCallId: null };
  const lookup = (h.service as unknown as {
    nearNeighbours: (tx: unknown, owner: string, space: string, draft: Record<string, unknown>, exclude: string | null) => Promise<WikiSimilar[]>;
  }).nearNeighbours.bind(h.service);

  await t.test('thirty drafts: what was read before the transaction is what the lookup inside it answers, draft by draft', async () => {
    const next = corpus(7);
    const ops: Array<Record<string, unknown>> = [
      { op: 'add', entry: { kind: 'concept', ...DRAFT }, sources: [] },
      { op: 'supersede', entryId: fx.family.close, baseRevision: 1, entry: { kind: 'concept', ...DRAFT }, sources: [] },
      ...Array.from({ length: OPS - 2 }, () => ({ op: 'add', entry: { kind: 'concept', ...next() }, sources: [] })),
    ];
    probe.reset();
    const answer = await service.submitChangeset(owner, fx.big, { rationale: 'thirty drafts', ops: ops as never, dryRun: true });
    const outcomes = answer.ops as Outcome[];
    assert.equal(outcomes.length, OPS);
    for (const [seq, op] of ops.entries()) {
      const inside = await lookup(h.prisma, fx.owner.id, fx.big, op.entry as Record<string, unknown>, op.op === 'supersede' ? fx.family.close : null);
      assert.deepEqual(outcomes[seq].similar ?? [], inside, `draft ${seq}'s similar[] is not what the lookup inside the transaction answers`);
    }
    // What that rests on, so it cannot pass by comparing empty lists: the planted family, the supersede's
    // exclusion, and the rejected neighbour's reason.
    assert.deepEqual((outcomes[0].similar ?? []).map((near) => near.id), ['twin', 'same', 'close', 'rejected', 'fifth'].map((key) => fx.family[key]));
    assert.equal(outcomes[0].similar?.[3].rejectedReason, 'duplicate');
    assert.deepEqual((outcomes[1].similar ?? []).map((near) => near.id), ['twin', 'same', 'rejected', 'fifth', 'sixth'].map((key) => fx.family[key]));
    assert.deepEqual(lookupsOf(probe), { before: 1, inside: 0 }, 'thirty drafts are one statement before the transaction, and none inside it');
    t.diagnostic(`thirty drafts, ${outcomes.filter((outcome) => (outcome.similar ?? []).length > 0).length} with neighbours: `
      + `before the transaction ${spelled(timing(probe, false))}; inside ${spelled(timing(probe, true))}`);
  });

  await t.test('the statement that reads them asks the trigram index once per draft, and never reads the table', async () => {
    await analyze(h);
    const next = corpus(8);
    const drafts = [DRAFT, ...Array.from({ length: 9 }, () => next())].map((text, seq) => asDraft(seq, text));
    const { root, text } = await explainRead(h, fx.owner.id, fx.big, drafts);
    const nodes = nodesOf(root);
    const index = nodes.filter((node) => node['Index Name'] === 'wiki_entry_search_trgm');
    assert.equal(index.length, 1, `the read does not ask the trigram index:\n${text}`);
    assert.equal(index[0]['Actual Loops'], drafts.length, `the trigram index is not asked once per draft:\n${text}`);
    assert.doesNotMatch(index[0]['Index Cond'] ?? '', /Migration numbers/u, `the read was planned around a draft's text:\n${text}`);
    assert.deepEqual(
      nodes.filter((node) => node['Node Type'] === 'Seq Scan' && node['Relation Name'] === 'wiki_entry'),
      [],
      `the read scans the table of entries:\n${text}`,
    );
    const tested = nodes
      .filter((node) => node['Relation Name'] === 'wiki_entry')
      .reduce(
        (sum, node) => sum
          + (node['Actual Rows'] + (node['Rows Removed by Index Recheck'] ?? 0) + (node['Rows Removed by Filter'] ?? 0))
            * node['Actual Loops'],
        0,
      );
    assert.ok(tested / drafts.length < BIG / 10, `the read tested ${tested} entries for ${drafts.length} drafts:\n${text}`);
    const returned = root['Actual Rows'];
    assert.ok(returned >= 5, `the planted draft's five are among what the read returns:\n${text}`);
    for (const subplan of nodes.filter((node) => node['Parent Relationship'] === 'SubPlan')) {
      assert.ok(
        subplan['Actual Loops'] <= returned,
        `${subplan['Subplan Name']} ran ${subplan['Actual Loops']} times for ${returned} rows returned:\n${text}`,
      );
    }
  });

  await t.test('a draft meets what the changeset\'s earlier ops wrote, exactly as when every lookup ran inside', async () => {
    const shared = { definition: 'A shell that runs after the turn', boundaries: 'Not an agent tool' };
    const first: Text = {
      title: 'Acceptance shells run after the turn ends',
      summary: '验收命令在回合结束后运行 in the same worktree as the session',
      fields: shared,
    };
    const second: Text = {
      title: 'Acceptance shells run after the turn has ended',
      summary: '验收命令在回合结束后运行 in the same worktree as the session did',
      fields: shared,
    };
    const copied: Text = {
      title: 'The worktree overlay copies the Prisma client',
      summary: '每个 worktree 复制自己的 Prisma client instead of reading the main checkout',
      fields: { definition: 'A copied client', boundaries: 'Not the main checkout' },
    };
    const [retired] = await standing(h, fx.owner.id, fx.big, [copied]);
    const ops: Array<Record<string, unknown>> = [
      { op: 'add', entry: { kind: 'concept', ...first }, sources: [] },
      { op: 'add', entry: { kind: 'concept', ...second }, sources: [] },
      { op: 'retire', entryId: retired, baseRevision: 1, reason: 'the overlay no longer copies it', sources: [] },
      {
        op: 'add',
        entry: { kind: 'concept', ...copied, title: 'The worktree overlay copies the Prisma client per tree' },
        sources: [],
      },
      { op: 'add', entry: { kind: 'concept', ...corpus(9)() }, sources: [] },
    ];
    const reference = comparable(await everyLookupInside(h, owner, fx.big, ops), ops);
    probe.reset();
    const answer = await service.submitChangeset(owner, fx.big, { rationale: 'what earlier ops wrote', ops: ops as never });
    assert.deepEqual(comparable(answer, ops), reference, 'similar[] is not what it is with every lookup inside the transaction');
    const outcomes = answer.ops as Outcome[];
    assert.equal(outcomes[1].similar?.[0]?.id, outcomes[0].entryId, 'the second draft meets the lineage the first one wrote');
    const again = outcomes[3].similar?.find((near) => near.id === retired);
    assert.equal(again?.status, 'retired', 'a draft meets the entry an earlier op retired, as retired');
    // Looked up again inside: the draft that meets an earlier draft's lineage, and the one whose neighbour
    // an earlier op retired; the other two as read before the transaction.
    assert.deepEqual(lookupsOf(probe), { before: 1, inside: 2 });

    // An amend rewrites an entry, which can then rank anywhere: every draft after it is looked up again.
    const rewritten = { title: 'Runner restarts leave an index.lock behind', summary: '重启留下 index.lock，下一次 git status 失败 until it is removed' };
    const [amended] = await standing(h, fx.owner.id, fx.big, [{
      title: 'Trigram lookups price their test',
      summary: 'COST 10000 steers the planner to the GIN index',
      fields: { definition: 'A priced function', boundaries: 'Not an index' },
    }]);
    const amending: Array<Record<string, unknown>> = [
      { op: 'amend', entryId: amended, baseRevision: 1, changes: rewritten, sources: [] },
      {
        op: 'add',
        entry: {
          kind: 'concept',
          title: 'Runner restarts leave an index.lock',
          summary: '重启留下 index.lock，下一次 git status 失败 until someone removes it',
          fields: { definition: 'A stale lock file', boundaries: 'Not a git bug' },
        },
        sources: [],
      },
    ];
    const amendReference = comparable(await everyLookupInside(h, owner, fx.big, amending), amending);
    probe.reset();
    const amendAnswer = await service.submitChangeset(owner, fx.big, { rationale: 'an amend, then a draft', ops: amending as never });
    assert.deepEqual(comparable(amendAnswer, amending), amendReference, 'similar[] after an amend is not what it is with every lookup inside');
    const met = (amendAnswer.ops as Outcome[])[1].similar?.find((near) => near.id === amended);
    assert.equal(met?.title, rewritten.title, 'the draft meets the entry as the amend rewrote it');
    assert.deepEqual(lookupsOf(probe), { before: 1, inside: 1 });
  });

  await t.test('a neighbour another writer changes between the read and the transaction is read again inside it', async () => {
    const shared = { definition: 'A replay of the recorded range', boundaries: 'Not a rebase' };
    const [moved, retired] = await standing(h, fx.owner.id, fx.big, [
      { title: 'Session merges replay the recorded base', summary: 'session_merge 按记录的 base_sha 重放 the commits since it', fields: shared },
      { title: 'Session merges replay from the recorded base', summary: 'session_merge 按记录的 base_sha 重放 every commit since', fields: shared },
    ]);
    const draft = {
      kind: 'concept',
      title: 'Session merges replay the recorded base sha',
      summary: 'session_merge 按记录的 base_sha 重放 the commits since it',
      fields: shared,
    };
    const ops = [
      { op: 'add', entry: draft, sources: [] },
      { op: 'add', entry: { kind: 'concept', ...corpus(10)() }, sources: [] },
    ];
    const retitled = 'Session merges replay the base they recorded';
    probe.reset();
    probe.beforeTransaction = async () => {
      // Another writer, between the read and the transaction: an amend of one neighbour, a retire of another.
      await h.sql.query(`UPDATE "wiki_entry" SET "title" = $2, "current_revision" = 2 WHERE "id" = $1`, [moved, retitled]);
      await h.sql.query(`UPDATE "wiki_entry" SET "status" = 'retired', "retired_at" = now(), "valid_to" = now() WHERE "id" = $1`, [retired]);
    };
    const answer = await service.submitChangeset(owner, fx.big, { rationale: 'a neighbour moved', ops: ops as never });
    const similar = new Map(((answer.ops as Outcome[])[0].similar ?? []).map((near) => [near.id, near]));
    assert.equal(similar.get(moved)?.title, retitled, 'the neighbour is listed as it reads now, not as it was read');
    const score = await h.sql.query<{ score: number }>(
      `SELECT similarity(wiki_entry_search_text("title", "summary", "aliases", "fields"), $2)::float8 AS "score" FROM "wiki_entry" WHERE "id" = $1`,
      [moved, `${draft.title} ${draft.summary}`],
    );
    assert.equal(similar.get(moved)?.score, Number(score.rows[0].score), 'and scored by its text now');
    assert.equal(similar.get(retired)?.status, 'retired', 'the neighbour retired in between is listed retired');
    assert.deepEqual(lookupsOf(probe), { before: 1, inside: 1 }, 'the draft whose neighbours moved is looked up again, and only it');
    assert.equal(probe.statements.filter((statement) => statement.inside && statement.what === 'raw:neighbour re-check').length, 1);
  });

  const mx = await maintenanceLoaded(h, fx.owner);
  const maintainer: WikiPrincipal = { origin: 'maintenance', ownerId: fx.owner.id, userId: null, sessionId: mx.maintainer, toolCallId: null };

  await t.test(`a maintenance run's ${OPS} adds among ${BIG.toLocaleString('en-US')} entries keep the transaction well under 5 s, with no lookup inside it`, async () => {
    // The first request of a process pays for what every later one reuses.
    assertAllRecorded(
      await service.submitChangeset(maintainer, mx.warm, { rationale: 'the warm-up', ops: maintenanceOps(mx.records, 20, 3) as never }),
      3,
      'the warm-up',
    );
    probe.reset();
    assertAllRecorded(
      await service.submitChangeset(maintainer, mx.empty, { rationale: 'into an empty space', ops: maintenanceOps(mx.records, 21) as never }),
      OPS,
      'the empty space',
    );
    const empty = { opened: probe.opened[0], before: timing(probe, false), inside: timing(probe, true) };

    probe.reset();
    const started = performance.now();
    assertAllRecorded(
      await service.submitChangeset(maintainer, mx.big, { rationale: 'among ten thousand', ops: maintenanceOps(mx.records, 22) as never }),
      OPS,
      'the big space',
    );
    const wall = performance.now() - started;
    const opened = probe.opened[0];
    const before = timing(probe, false);
    const inside = timing(probe, true);
    t.diagnostic(`empty space: transaction ${Math.round(empty.opened.ms)} ms; before it ${spelled(empty.before)}; inside ${spelled(empty.inside)}`);
    t.diagnostic(`${BIG.toLocaleString('en-US')} entries: ${Math.round(wall)} ms in all, transaction ${Math.round(opened.ms)} ms; `
      + `before it ${spelled(before)}; inside ${spelled(inside)}`);

    assert.deepEqual(probe.opened.map((transaction) => transaction.options), [{ timeout: 15_000, maxWait: 5_000 }], 'the transaction names its own timeout');
    assert.ok(opened.committed);
    // The lookup, where the time that grows with the space went: one statement before the transaction for
    // all thirty drafts, none inside it — whose share of the neighbours is the one re-check.
    assert.deepEqual(lookupsOf(probe), { before: 1, inside: 0 }, 'a draft was looked up inside the transaction');
    const recheck = inside.steps.get('neighbours') ?? { statements: 0, ms: 0 };
    assert.ok(recheck.statements <= 1, `the transaction read the neighbours ${recheck.statements} times`);
    assert.ok(
      recheck.ms <= opened.ms * 0.1,
      `the neighbours took ${Math.round(recheck.ms)} ms of the transaction's ${Math.round(opened.ms)} ms`,
    );
    // Well under the 5 s that closed it, and about as long as into an empty space: what is left is the
    // statements an add is made of, whatever the size of the space. The margin is the noise of two runs
    // on a loaded host; the lookup it would have to hide is a second or more at this size, and none of
    // it is inside (asserted above).
    assert.ok(opened.ms < 5_000, `the transaction was open ${Math.round(opened.ms)} ms`);
    assert.ok(
      opened.ms <= empty.opened.ms + Math.max(1_000, empty.opened.ms / 2),
      `the transaction took ${Math.round(opened.ms)} ms among ${BIG} entries and ${Math.round(empty.opened.ms)} ms in an empty space`,
    );
  });

  await t.test('every statement slowed as a loaded host slows it, the lookup most: the changeset still commits', async () => {
    probe.reset();
    probe.delayMs = 5;
    probe.lookupDelayMs = 250;
    assertAllRecorded(
      await service.submitChangeset(maintainer, mx.big, { rationale: 'on a slow host', ops: maintenanceOps(mx.records, 23) as never }),
      OPS,
      'the slowed changeset',
    );
    const opened = probe.opened[0];
    t.diagnostic(`every statement +5 ms and the lookup +250 ms: transaction ${Math.round(opened.ms)} ms; `
      + `before it ${spelled(timing(probe, false))}; inside ${spelled(timing(probe, true))}`);
    assert.ok(opened.committed && opened.ms < 15_000, `the transaction was open ${Math.round(opened.ms)} ms`);
    // The slowest statement is paid once, before the transaction; inside it thirty would be 7.5 s.
    assert.deepEqual(lookupsOf(probe), { before: 1, inside: 0 });
  });

  await t.test('four such changesets at once all commit', async () => {
    probe.reset();
    const answers = await Promise.all(
      [24, 25, 26, 27].map((seed) => service.submitChangeset(maintainer, mx.big, { rationale: `at once ${seed}`, ops: maintenanceOps(mx.records, seed) as never })),
    );
    for (const [n, answer] of answers.entries()) assertAllRecorded(answer, OPS, `changeset ${n + 1} of four`);
    t.diagnostic(`four at once: transactions ${probe.opened.map((transaction) => `${Math.round(transaction.ms)} ms`).join(', ')}; `
      + `before them ${spelled(timing(probe, false))}; inside ${spelled(timing(probe, true))}`);
    assert.equal(probe.opened.length, 4);
    for (const transaction of probe.opened) {
      assert.ok(transaction.committed && transaction.ms < 15_000, `a transaction was open ${Math.round(transaction.ms)} ms: ${transaction.error ?? ''}`);
    }
    assert.deepEqual(lookupsOf(probe), { before: 4, inside: 0 });
    const committed = await h.sql.query<{ n: number }>(
      `SELECT count(*)::int AS n FROM "wiki_entry" WHERE "space_id" = $1 AND "status" = 'proposed'`,
      [mx.big],
    );
    assert.equal(committed.rows[0].n, OPS * 6, 'every add of the six changesets wrote its lineage, proposed until verified');
  });
});
