/**
 * The plan's jobs (criterion 11; contracts/wiki.contract.json `plan.jobs`, migration 0336), over real
 * HTTP and against a real PostgreSQL.
 *
 * What the task's verification asks, each read back from the doors and from the database:
 *
 *   1. a new space makes a drafting task: in the space's maintenance list, pinned to the maintenance
 *      workspace and provider, runAt now — and a space a session's proposal made asks for one too;
 *   2. the owner's redraft through the JWT door makes one; with a session header it is refused 403;
 *   3. a space with a draft that has not ended makes no second; a list whose maintenance task has not
 *      ended queues the job, and that task's end makes it;
 *   4. a space whose maintenance is not set up makes none and says why; the settings supplied make it;
 *   5. the new reads are a maintenance run's alone, and another tenant's is a 404, every one of them.
 *
 * and beside them what the design leans on: the run's start, rounds and end, and the check its task's
 * acceptance command asks; a job is no maintenance run (the day's count, the day's limit, maintenance
 * off); and the migration's CHECKs are the contract's closed sets.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-plan-draft.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import {
  RunEventType,
  toUuid,
  uuidToBase62,
  WIKI_PLAN_JOB_HELD_REASONS,
  WIKI_PLAN_JOB_KINDS,
  WIKI_PLAN_JOB_OUTCOMES,
  WIKI_PLAN_JOB_STORED_STATES,
  WIKI_PLAN_JOB_TRIGGERS,
  type NormalizedRunEvent,
} from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { encryptSecret } from '../providers/provider-crypto';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiPlanController } from '../runner-api/runner-wiki-plan.controller';
import { wikiMaintenanceRunOf, wikiMaintenanceRunsToday } from './wiki-maintenance-session';
import { isWikiMaintenanceSession } from './wiki-maintenance-settings';
import { WikiPlans } from './wiki-plan';
import { WikiPlanJobFacts } from './wiki-plan-job';
import { WikiPlanController } from './wiki-plan.controller';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiController } from './wiki.controller';
import { WikiService } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;
// The providers these fixtures configure keep their keys encrypted, as every provider does.
process.env.PROVIDER_SECRET_KEY ??= 'wiki-plan-draft-spec';

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  bearers: Map<string, string>;
  service: WikiService;
  facts: WikiPlanJobFacts;
  /** Every task the doors published as changed, in order. */
  published: string[];
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const published: string[] = [];
    const hub = {
      publishWikiChanged: () => undefined,
      publishForUser: (_owner: string, _type: string, payload: { taskIds?: string[] }) => published.push(...(payload.taskIds ?? [])),
    } as unknown as RealtimeService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, {} as unknown as PushService);
    const plans = new WikiPlans(prisma as unknown as PrismaService, hub);
    const facts = new WikiPlanJobFacts(prisma as unknown as PrismaService);

    @Module({
      controllers: [WikiController, WikiPlanController, RunnerWikiPlanController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiPlans, useValue: plans },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiPlanDraftModule {}

    const app = await NestFactory.create(WikiPlanDraftModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, bearers, service, facts, published };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 1200)}`);
}

function expectRefusal(answer: Answer, status: number, code: string, why: string): void {
  expectStatus(answer, status, why);
  assert.equal(answer.body.code, code, `${why}: ${JSON.stringify(answer.body).slice(0, 600)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [id, `wiki-plan-draft-${id}@wiki.invalid`, name]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string, repoUrl: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env","repo_url","work_dir") VALUES ($1,'orbit',$2,'{}',$3,'~/orbit')`, [id, ownerId, repoUrl]);
  return id;
}

/** A configured provider of the owner's: the local model on the Claude Code runtime. */
async function provider(h: Harness, ownerId: string, slug = `local-vllm-${randomUUID().slice(0, 8)}`): Promise<string> {
  await h.prisma.modelProvider.create({
    data: {
      slug,
      label: 'Local vLLM',
      runtime: 'claude',
      baseUrl: 'http://127.0.0.1:8000',
      apiKeyEnc: encryptSecret(`vllm-key-${randomUUID()}`),
      models: [{ value: 'qwen3.8-27b-fp8', label: 'Qwen3.8 27B', contextWindow: 131072 }],
      defaultModel: 'qwen3.8-27b-fp8',
      enabled: true,
      ownerId,
    },
  });
  return slug;
}

async function session(h: Harness, ownerId: string, workspaceId: string, runnerId: string, taskId: string | null = null, title = 'a session'): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","status","dispatch_origin","updated_at")
     VALUES ($1,$2,'p',$3,$3,$4,$5,$6,'RUNNING'::run_status,'USER',now())`,
    [id, title, ownerId, workspaceId, runnerId, taskId],
  );
  return id;
}

/** A maintenance run of the list, as the maintenance trigger would have made it, still open. */
async function maintenanceTask(h: Harness, ownerId: string, listId: string, assigneeId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id",
                         "completion_criterion","updated_at")
     VALUES ($1,'Wiki maintenance: a space',$2,'USER',$2,'OPEN'::task_status,$3,$4,'OWNER_CONFIRMED',now())`,
    [id, ownerId, assigneeId, listId],
  );
  return id;
}

async function settle(h: Harness, taskId: string, status: 'DONE' | 'FAILED' | 'CANCELLED'): Promise<void> {
  await h.sql.query(`UPDATE "task" SET "status" = $2::task_status, "updated_at" = now() WHERE "id" = $1`, [taskId, status]);
}

/** A task change, as the tasks module publishes it, taken by the job facts and waited for. */
async function taskChanged(h: Harness, ownerId: string, taskIds: string[]): Promise<void> {
  const event: NormalizedRunEvent = { seq: 0, type: RunEventType.TASK_CHANGED, ts: new Date().toISOString(), payload: { taskIds, resync: false } };
  h.facts.take(`user:${ownerId}`, event);
  await h.facts.idle();
}

interface JobRow {
  id: string;
  kind: string;
  trigger: string;
  state: string;
  held_reason: string | null;
  held_at: Date | null;
  task_id: string | null;
  instructions: string | null;
  outcome: string | null;
}

async function jobs(h: Harness, spaceId: string): Promise<JobRow[]> {
  return (await h.sql.query<JobRow>(
    `SELECT "id","kind","trigger","state","held_reason","held_at","task_id","instructions","outcome"
       FROM "wiki_plan_job" WHERE "space_id" = $1 ORDER BY "created_at", "id"`,
    [spaceId],
  )).rows;
}

interface TaskRow {
  id: string;
  title: string;
  description: string | null;
  status: string;
  list_id: string | null;
  assignee_id: string | null;
  provider: string | null;
  run_at: Date | null;
  creator_type: string;
  creator_id: string;
  completion_criterion: string;
  acceptance_command: string | null;
  acceptance_expected_exit_code: number | null;
}

async function taskRow(h: Harness, taskId: string): Promise<TaskRow> {
  const rows = await h.sql.query<TaskRow>(
    `SELECT "id","title","description","status","list_id","assignee_id","provider","run_at","creator_type","creator_id",
            "completion_criterion","acceptance_command","acceptance_expected_exit_code"
       FROM "task" WHERE "id" = $1`,
    [taskId],
  );
  assert.equal(rows.rowCount, 1, `task ${taskId} is not stored`);
  return rows.rows[0];
}

async function listTasks(h: Harness, listId: string): Promise<string[]> {
  return (await h.sql.query<{ id: string }>(`SELECT "id" FROM "task" WHERE "list_id" = $1 ORDER BY "created_at", "id"`, [listId])).rows.map((r) => r.id);
}

async function settingsOf(h: Harness, spaceId: string): Promise<{ enabled?: boolean; listId?: string; workspaceId?: string; provider?: string }> {
  const rows = await h.sql.query<{ settings: { maintenance?: Record<string, unknown> } }>(`SELECT "settings" FROM "wiki_space" WHERE "id" = $1`, [spaceId]);
  return (rows.rows[0]?.settings?.maintenance ?? {}) as { enabled?: boolean; listId?: string; workspaceId?: string; provider?: string };
}

/** One owner with a runner, a workspace and a provider a maintenance run could start on. */
interface World {
  owner: Account;
  machine: { id: string; token: string };
  ws: string;
  slug: string;
}

async function world(h: Harness, name: string): Promise<World> {
  const owner = await account(h, name);
  return { owner, machine: await runner(h, owner.id), ws: await workspace(h, owner.id), slug: await provider(h, owner.id) };
}

/** A space its owner created with its maintenance set up from the start, bound to their workspace. */
async function plannedSpace(h: Harness, w: World, extra: Record<string, unknown> = {}): Promise<{ spaceId: string; answer: Answer }> {
  const answer = await call(h, { bearer: w.owner.bearer }, 'POST', '/wiki/spaces', {
    title: 'A planned space',
    repoUrl: `https://github.com/spec/planned-${randomUUID().slice(0, 8)}`,
    maintenance: { workspaceId: w.ws, provider: w.slug, ...extra },
  });
  expectStatus(answer, 201, 'the owner creates a space with its maintenance set up');
  const spaceId = toUuid(answer.body.id as string);
  expectStatus(await call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId: w.ws }), 200, 'the owner binds the workspace');
  return { spaceId, answer };
}

async function planState(h: Harness, w: World, spaceId: string): Promise<Answer> {
  const answer = await call(h, { bearer: w.owner.bearer }, 'GET', `/wiki/spaces/${spaceId}/plan`);
  expectStatus(answer, 200, 'the owner reads the plan');
  return answer;
}

/** The only job a space has, made: its row and its task. */
async function madeJob(h: Harness, spaceId: string): Promise<{ job: JobRow; task: TaskRow }> {
  const rows = await jobs(h, spaceId);
  assert.equal(rows.length, 1, `the space has ${rows.length} jobs: ${JSON.stringify(rows)}`);
  assert.equal(rows[0].state, 'made', `the job is ${rows[0].state} (${rows[0].held_reason ?? 'not held'})`);
  return { job: rows[0], task: await taskRow(h, rows[0].task_id!) };
}

/** A plan the server's gate lets through: twenty documents, one category for the agents' conventions. */
function planOf(count = 20): Record<string, unknown> {
  return {
    categories: [
      { key: 'product', title: 'Product', question: 'What Orbit is and how it runs' },
      { key: 'dev', title: 'Development conventions', question: 'How agents work in this repository', forAgents: true },
    ],
    docs: Array.from({ length: count }, (_, i) => ({
      category: i % 5 === 0 ? 'dev' : 'product',
      slug: `doc-${i}`,
      title: `Document ${i}`,
      question: `What does part ${i} of Orbit do, and how?`,
      audience: [`A new developer: can say what part ${i} does after reading it`],
      scopeIn: [`How part ${i} runs`],
      scopeOut: [{ text: 'What the next part does', docs: [`doc-${(i + 1) % count}`] }],
      length: { min: 1200, max: 2000 },
      sections: [
        { title: 'Overview', kind: 'overview', covers: `What part ${i} is, in one paragraph.`, length: 300, sources: {} },
        {
          title: 'How it runs',
          kind: 'flow',
          covers: `The steps part ${i} takes.`,
          length: 800,
          sources: { docs: [{ path: 'docs/architecture.md', section: 'Execution model' }], code: [{ path: 'src/runner-go/runloop.go', symbols: ['runLoop()'] }] },
        },
      ],
    })),
  };
}

// ── 1. a new space ──────────────────────────────────────────────────────────────────────────────

test('a new space makes its first draft at once: a task of its maintenance list, pinned to the workspace and the provider, runAt now', { skip }, async () => {
  const h = await boot();
  const w = await world(h, 'creator');
  const before = Date.now();
  const { spaceId, answer } = await plannedSpace(h, w);
  const after_ = Date.now();
  // Maintenance itself stays off: a plan is drafted before the owner turns maintenance on.
  assert.equal(answer.body.settings.maintenance.enabled, false);
  const settings = await settingsOf(h, spaceId);
  assert.ok(settings.listId, 'the space has no maintenance list: the job made none');
  const { job, task } = await madeJob(h, spaceId);
  assert.deepEqual([job.kind, job.trigger, job.instructions], ['draft', 'space_created', null]);

  // The task, as the maintenance trigger makes its own: in the hidden list, pinned, due now, the owner's.
  assert.equal(task.list_id, settings.listId);
  assert.equal(task.assignee_id, w.ws, 'pinned to the maintenance workspace');
  assert.equal(task.provider, w.slug, 'pinned to the maintenance provider');
  // Read through Prisma: `run_at` is a timestamp without a zone, which pg would read as the host's local time.
  const { runAt } = await h.prisma.task.findUniqueOrThrow({ where: { id: task.id }, select: { runAt: true } });
  assert.ok(runAt && runAt.getTime() >= before - 1_000 && runAt.getTime() <= after_ + 1_000, `runAt is not now: ${runAt?.toISOString()}`);
  assert.deepEqual([task.creator_type, task.creator_id, task.status], ['USER', w.owner.id, 'OPEN']);
  assert.equal(task.title, 'Wiki plan draft: A planned space');
  assert.equal(task.completion_criterion, 'EXECUTABLE');
  assert.equal(task.acceptance_command, `orbit wiki plan check --space ${uuidToBase62(spaceId)} --job ${uuidToBase62(job.id)}`);
  assert.equal(task.acceptance_expected_exit_code, 0);
  assert.match(task.description ?? '', new RegExp(`orbit wiki plan draft --space ${uuidToBase62(spaceId)}`, 'u'));
  assert.match(task.description ?? '', /token spend/u, 'the description does not ask for the token spend');
  const list = await h.sql.query<{ hidden: boolean; title: string; max_concurrent: number }>(
    `SELECT "hidden","title","max_concurrent" FROM "task_list" WHERE "id" = $1`,
    [settings.listId],
  );
  assert.deepEqual(list.rows[0], { hidden: true, title: 'Wiki maintenance', max_concurrent: 1 });
  assert.ok(h.published.includes(task.id), 'the task made was not published');

  // Its session is a maintenance session, and is claimed as one although maintenance is off.
  const run = await session(h, w.owner.id, w.ws, w.machine.id, task.id);
  assert.equal(await isWikiMaintenanceSession(h.prisma, { ownerId: w.owner.id, sessionId: run, spaceId }), true);
  const claimed = await wikiMaintenanceRunOf(h.prisma, { id: run, taskId: task.id, workspaceId: w.ws, provider: w.slug });
  assert.ok(claimed, 'the plan job\'s session is not claimed as a maintenance run');
  assert.equal(claimed!.refusal, undefined, `the plan job's run was refused: ${claimed!.refusal}`);
  assert.equal(claimed!.provider, w.slug);

  // The plan's read says it runs.
  const state = await planState(h, w, spaceId);
  assert.equal(state.body.job.state, 'running');
  assert.equal(state.body.job.kind, 'draft');
  assert.equal(state.body.job.trigger, 'space_created');
  assert.equal(toUuid(state.body.job.taskId), task.id);
  assert.equal(state.body.job.provider, w.slug);
  assert.equal(state.body.job.attemptsMax, 3);
  assert.equal(state.body.job.held, null);

  // A space a session's proposal made where its workspace's repository had none asks for its draft too —
  // held, since nobody has set its maintenance up.
  const repoUrl = `https://github.com/spec/implicit-${randomUUID().slice(0, 8)}`;
  const proposing = await session(h, w.owner.id, await workspace(h, w.owner.id, repoUrl), w.machine.id);
  const implicit = await h.service.resolveSpaceForCall(w.owner.id, proposing);
  const made = await jobs(h, implicit);
  assert.deepEqual(made.map((row) => [row.kind, row.trigger, row.state, row.held_reason]), [['draft', 'space_created', 'held', 'no_maintenance_workspace']]);
  // …and only once: the space found again asks for nothing more.
  await h.service.resolveSpaceForCall(w.owner.id, proposing);
  assert.equal((await jobs(h, implicit)).length, 1);
});

// ── 2. the owner's redraft ──────────────────────────────────────────────────────────────────────

test('the owner asks for a redraft through the owner channel and a job is made; with a session header it is refused', { skip }, async () => {
  const h = await boot();
  const w = await world(h, 'redrafter');
  const { spaceId } = await plannedSpace(h, w);
  const first = await madeJob(h, spaceId);
  // The first draft's run: it drafts, the gate lets it through, and it says so; its task then ends.
  const run = await session(h, w.owner.id, w.ws, w.machine.id, first.task.id);
  const maintainer: Caller = { runner: w.machine.token, session: run };
  expectStatus(await call(h, maintainer, 'GET', `/runner/wiki/spaces/${spaceId}/plan/job`), 200, 'the run reads its job');
  const drafted = await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/drafts`, {
    baseVersion: null,
    plan: planOf(),
    repoCheck: { sha: 'a'.repeat(40), checked: 40, missing: [] },
    model: 'qwen3.8-27b-fp8',
  });
  expectStatus(drafted, 200, 'the run drafts');
  expectStatus(await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'succeeded', version: 1, attempt: 1 }), 200, 'the run ends');
  await settle(h, first.task.id, 'DONE');

  // A request with a session header is refused before anything is read, and makes nothing.
  const headed = await call(h, { bearer: w.owner.bearer, session: run }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, {});
  expectRefusal(headed, 403, 'WIKI_OWNER_CHANNEL_ONLY', 'a redraft with a session header');
  assert.equal((await jobs(h, spaceId)).length, 1, 'a redraft with a session header made a job');

  // The owner, on the owner channel: a draft, made at once.
  const redraft = await call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, {});
  expectStatus(redraft, 200, 'the owner asks for a redraft');
  assert.equal(redraft.body.created, true);
  assert.deepEqual([redraft.body.job.kind, redraft.body.job.trigger, redraft.body.job.state], ['draft', 'owner', 'running']);
  const second = (await jobs(h, spaceId))[1];
  assert.equal(second.state, 'made');
  const secondTask = await taskRow(h, second.task_id!);
  assert.deepEqual([secondTask.list_id, secondTask.assignee_id, secondTask.provider], [first.task.list_id, w.ws, w.slug]);
  assert.match(secondTask.description ?? '', /orbit wiki plan draft --space/u);

  // With instructions, a revision: the owner's words ride on the job and are quoted in the task.
  await settle(h, second.task_id!, 'CANCELLED');
  const words = '合并到 30 篇左右；给 agent 的开发约定单列一类；3.1 的节一节都不许移出。';
  const revise = await call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, { instructions: `  ${words}\n` });
  expectStatus(revise, 200, 'the owner asks for a revision');
  assert.equal(revise.body.created, true);
  assert.equal(revise.body.job.kind, 'revise');
  assert.equal(revise.body.job.instructions, words);
  const third = (await jobs(h, spaceId))[2];
  assert.deepEqual([third.kind, third.trigger, third.instructions], ['revise', 'owner', words]);
  const thirdTask = await taskRow(h, third.task_id!);
  assert.equal(thirdTask.title, 'Wiki plan redraft: A planned space');
  assert.match(thirdTask.description ?? '', /orbit wiki plan revise --space/u);
  assert.ok((thirdTask.description ?? '').includes(`> ${words}`), 'the owner\'s instructions are not quoted in the task');
  // The job the cancelled task left made was ended when the next request found it: failed, with why.
  const ended = (await jobs(h, spaceId))[1];
  assert.deepEqual([ended.state, ended.outcome], ['ended', 'failed']);

  // What the owner may send: an object with instructions, and nothing else.
  for (const [body, why] of [
    [{ instructions: 'x', force: true }, 'a field a redraft does not have'],
    [{ instructions: 42 }, 'instructions that are not words'],
    [{ instructions: 'x'.repeat(4001) }, 'instructions past their limit'],
  ] as const) {
    expectRefusal(await call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, body), 400, 'WIKI_SCHEMA', why);
  }
});

// ── 3. one at a time ────────────────────────────────────────────────────────────────────────────

test('a draft that has not ended answers a second request; a maintenance task not ended queues the job, and its end makes it', { skip }, async () => {
  const h = await boot();
  const w = await world(h, 'queued');
  const { spaceId } = await plannedSpace(h, w);
  const first = await madeJob(h, spaceId);
  const listId = first.task.list_id!;

  // Asked again while it runs: the same job, and nothing new.
  const again = await call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, { instructions: 'Keep it to thirty documents.' });
  expectStatus(again, 200, 'a second request');
  assert.equal(again.body.created, false);
  assert.equal(toUuid(again.body.job.id), first.job.id);
  assert.equal(again.body.job.kind, 'draft', 'a second request changed the job that answered it');
  assert.equal((await jobs(h, spaceId)).length, 1);
  assert.deepEqual(await listTasks(h, listId), [first.task.id]);
  // …and two at once still leave one.
  const pair = await Promise.all([1, 2].map(() => call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, {})));
  for (const answer of pair) expectStatus(answer, 200, 'one of two requests at once');
  assert.equal((await jobs(h, spaceId)).length, 1);

  // The draft's task ends; a maintenance run of the space is under way when the owner asks again.
  await settle(h, first.task.id, 'FAILED');
  await taskChanged(h, w.owner.id, [first.task.id]);
  assert.deepEqual((await jobs(h, spaceId)).map((row) => [row.state, row.outcome]), [['ended', 'failed']], 'the ended task did not end its job');
  const maintenance = await maintenanceTask(h, w.owner.id, listId, w.ws);
  const maintenanceRun = await session(h, w.owner.id, w.ws, w.machine.id, maintenance);
  await h.sql.query(
    `INSERT INTO "wiki_maintenance_run"("id","space_id","owner_id","task_id","session_id","started_at") VALUES ($1,$2,$3,$4,$5,now())`,
    [randomUUID(), spaceId, w.owner.id, maintenance, maintenanceRun],
  );
  const queued = await call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, {});
  expectStatus(queued, 200, 'a request while a maintenance run is under way');
  assert.equal(queued.body.created, true);
  assert.equal(queued.body.job.state, 'queued');
  assert.equal(toUuid(queued.body.job.waitingFor.taskId), maintenance, 'it does not say what it waits for');
  assert.equal(toUuid(queued.body.job.waitingFor.sessionId), maintenanceRun);
  assert.ok(queued.body.job.waitingFor.startedAt);
  assert.deepEqual(await listTasks(h, listId), [first.task.id, maintenance], 'a task was made beside the maintenance run');
  // A task change that frees nothing moves nothing.
  await taskChanged(h, w.owner.id, [randomUUID()]);
  assert.equal((await jobs(h, spaceId))[1].state, 'queued');

  // The maintenance run's task ends: that fact makes the job.
  await settle(h, maintenance, 'FAILED');
  await taskChanged(h, w.owner.id, [maintenance]);
  const made = (await jobs(h, spaceId))[1];
  assert.equal(made.state, 'made', `the job is ${made.state} after the list was freed`);
  const task = await taskRow(h, made.task_id!);
  assert.deepEqual([task.list_id, task.assignee_id, task.provider, task.status], [listId, w.ws, w.slug, 'OPEN']);
  assert.equal((await planState(h, w, spaceId)).body.job.state, 'running');
});

// ── 4. held until the settings are there ────────────────────────────────────────────────────────

test('a space whose maintenance names no workspace, or a provider no run could start on, makes no task and says why; the settings supplied make it', { skip }, async () => {
  const h = await boot();
  const w = await world(h, 'held');
  const made = await call(h, { bearer: w.owner.bearer }, 'POST', '/wiki/spaces', { title: 'A space nobody set up', repoUrl: `https://github.com/spec/held-${randomUUID().slice(0, 8)}` });
  expectStatus(made, 201, 'the owner creates a space');
  const spaceId = toUuid(made.body.id as string);
  let [job] = await jobs(h, spaceId);
  assert.deepEqual([job.kind, job.trigger, job.state, job.held_reason, job.task_id], ['draft', 'space_created', 'held', 'no_maintenance_workspace', null]);
  assert.equal((await settingsOf(h, spaceId)).listId ?? null, null, 'a held job made a list');
  let state = await planState(h, w, spaceId);
  assert.equal(state.body.job.state, 'held');
  assert.equal(state.body.job.held.reason, 'no_maintenance_workspace');
  const heldAt = state.body.job.held.at;
  assert.ok(heldAt);
  // Asked again, still held, and since the same moment.
  const again = await call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, {});
  expectStatus(again, 200, 'asked again while held');
  assert.deepEqual([again.body.created, again.body.job.state, again.body.job.held.at], [false, 'held', heldAt]);

  // A workspace, and a provider no run could start on yet: held for the provider now.
  const missing = `local-vllm-missing-${randomUUID().slice(0, 6)}`;
  expectStatus(await call(h, { bearer: w.owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { workspaceId: w.ws, provider: missing } }), 200, 'the owner names a workspace');
  [job] = await jobs(h, spaceId);
  assert.deepEqual([job.state, job.held_reason, job.task_id], ['held', 'maintenance_provider_unusable', null]);
  state = await planState(h, w, spaceId);
  assert.equal(state.body.job.held.reason, 'maintenance_provider_unusable');

  // The provider set up, and the settings saved again: that fact makes the job.
  await provider(h, w.owner.id, missing);
  const saved = await call(h, { bearer: w.owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { provider: missing } });
  expectStatus(saved, 200, 'the owner saves the maintenance settings');
  [job] = await jobs(h, spaceId);
  assert.deepEqual([job.state, job.held_reason, job.held_at], ['made', null, null]);
  const task = await taskRow(h, job.task_id!);
  const settings = await settingsOf(h, spaceId);
  assert.deepEqual([task.list_id, task.assignee_id, task.provider], [settings.listId, w.ws, missing]);
  assert.equal(settings.enabled, false, 'making the job turned maintenance on');
  assert.equal((await planState(h, w, spaceId)).body.job.state, 'running');
});

// ── 5. the new reads, and who may use the job's routes ───────────────────────────────────────────

test('the plan job\'s routes and the materials are a maintenance run\'s alone, and another tenant\'s is a 404', { skip }, async () => {
  const h = await boot();
  const w = await world(h, 'materials');
  const { spaceId } = await plannedSpace(h, w);
  const { task } = await madeJob(h, spaceId);
  const run = await session(h, w.owner.id, w.ws, w.machine.id, task.id);
  const maintainer: Caller = { runner: w.machine.token, session: run };
  // What the materials count: a project with a task and its session, sessions of the bound workspace (one
  // whose title carries a secret), a topic and its entry.
  const projectId = randomUUID();
  await h.sql.query(`INSERT INTO "project"("id","title","owner_id","updated_at") VALUES ($1,'Orbit Wiki · 阶段 2',$2,now())`, [projectId, w.owner.id]);
  const projectTask = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","project_id","completion_criterion","updated_at")
     VALUES ($1,'a task',$2,'USER',$2,'DONE'::task_status,$3,'OWNER_CONFIRMED',now())`,
    [projectTask, w.owner.id, projectId],
  );
  await session(h, w.owner.id, w.ws, w.machine.id, projectTask, '执行任务：Wiki plan · 起草');
  const secret = `AKIA${'Q'.repeat(16)}`;
  await session(h, w.owner.id, w.ws, w.machine.id, null, `rotate ${secret} today`);
  await h.sql.query(`INSERT INTO "wiki_topic"("id","space_id","owner_id","slug","title","category","path_prefixes") VALUES ($1,$2,$3,'wiki','Wiki','platform','{src/apiserver/src/wiki/}')`, [randomUUID(), spaceId, w.owner.id]);
  await h.sql.query(
    `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields","topics")
     VALUES ($1,$2,$3,'pitfall','active','owner',1,'The plan gate refuses a moved protected section','x','{"symptom":"x","cause":"y","fix":"z"}','{wiki}')`,
    [randomUUID(), w.owner.id, spaceId],
  );

  const materials = await call(h, maintainer, 'GET', `/runner/wiki/spaces/${spaceId}/plan/materials`);
  expectStatus(materials, 200, 'the plan job reads its materials');
  assert.equal(materials.body.title, 'A planned space');
  assert.equal(toUuid(materials.body.workspace.id), w.ws);
  assert.equal(materials.body.workspace.workDir, '~/orbit');
  const project = materials.body.projects.find((p: { title: string }) => p.title === 'Orbit Wiki · 阶段 2');
  assert.deepEqual([project.tasks, project.sessions], [1, 1]);
  assert.equal(materials.body.sessions.days, 90);
  assert.ok(materials.body.sessions.total >= 3, `sessions counted ${materials.body.sessions.total}`);
  const titles: string[] = materials.body.sessions.items.map((s: { title: string }) => s.title);
  assert.ok(titles.includes('执行任务：Wiki plan · 起草'), JSON.stringify(titles));
  assert.ok(!JSON.stringify(materials.body).includes(secret), 'a secret in a session title left the server');
  const withProject = materials.body.sessions.items.find((s: { project: string | null }) => s.project === 'Orbit Wiki · 阶段 2');
  assert.equal(withProject.task, true);
  assert.deepEqual(materials.body.entries, [{ kind: 'pitfall', status: 'active', count: 1 }]);
  assert.deepEqual(materials.body.topics.map((t: { slug: string; active: number; recent: unknown[] }) => [t.slug, t.active, t.recent.length]), [['wiki', 1, 1]]);

  // Another session of the owner is not a maintenance run; a call with no session names nobody.
  const ordinary: Caller = { runner: w.machine.token, session: await session(h, w.owner.id, w.ws, w.machine.id) };
  for (const [method, route, body] of [
    ['GET', `/runner/wiki/spaces/${spaceId}/plan/materials`, undefined],
    ['GET', `/runner/wiki/spaces/${spaceId}/plan/job`, undefined],
    ['POST', `/runner/wiki/spaces/${spaceId}/plan/job/progress`, { attempt: 1 }],
    ['POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'failed' }],
    ['GET', `/runner/wiki/spaces/${spaceId}/plan/check?jobId=${uuidToBase62((await jobs(h, spaceId))[0].id)}`, undefined],
  ] as const) {
    expectRefusal(await call(h, ordinary, method, route, body), 403, 'WIKI_NOT_MAINTENANCE_SESSION', `an ordinary session: ${method} ${route}`);
  }
  for (const [method, route, body] of [
    ['GET', `/runner/wiki/spaces/${spaceId}/plan/materials`, undefined],
    ['GET', `/runner/wiki/spaces/${spaceId}/plan/job`, undefined],
    ['POST', `/runner/wiki/spaces/${spaceId}/plan/job/progress`, { attempt: 1 }],
    ['POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'failed' }],
  ] as const) {
    expectStatus(await call(h, { runner: w.machine.token }, method, route, body), 400, `a headless call: ${method} ${route}`);
  }
  // A maintenance run whose task was made for no job reads the materials, and runs no job.
  const listId = task.list_id!;
  const maintenanceRun: Caller = { runner: w.machine.token, session: await session(h, w.owner.id, w.ws, w.machine.id, await maintenanceTask(h, w.owner.id, listId, w.ws)) };
  expectStatus(await call(h, maintenanceRun, 'GET', `/runner/wiki/spaces/${spaceId}/plan/materials`), 200, 'a maintenance run reads the materials');
  expectRefusal(await call(h, maintenanceRun, 'GET', `/runner/wiki/spaces/${spaceId}/plan/job`), 409, 'WIKI_PLAN_NO_JOB', 'a maintenance run with no job');
  expectRefusal(await call(h, maintenanceRun, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'failed' }), 409, 'WIKI_PLAN_NO_JOB', 'a maintenance run ending no job');

  // Another owner: through their own maintenance run and runner, and with their bearer, every route is a 404.
  const them = await world(h, 'another owner');
  const theirs = await plannedSpace(h, them);
  const theirTask = (await madeJob(h, theirs.spaceId)).task;
  const theirRun: Caller = { runner: them.machine.token, session: await session(h, them.owner.id, them.ws, them.machine.id, theirTask.id) };
  const jobId = uuidToBase62((await jobs(h, spaceId))[0].id);
  for (const [method, route, body] of [
    ['GET', `/runner/wiki/spaces/${spaceId}/plan/materials`, undefined],
    ['GET', `/runner/wiki/spaces/${spaceId}/plan/job`, undefined],
    ['POST', `/runner/wiki/spaces/${spaceId}/plan/job/progress`, { attempt: 1 }],
    ['POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'failed' }],
    ['GET', `/runner/wiki/spaces/${spaceId}/plan/check?jobId=${jobId}`, undefined],
  ] as const) {
    const answer = await call(h, theirRun, method, route, body);
    expectStatus(answer, 404, `another owner's run: ${method} ${route}`);
    assert.ok(!JSON.stringify(answer.body).includes('A planned space'), `another owner's run: ${method} ${route} told something of the space`);
  }
  // Their runner with no session, asking for the check of a job of this space, or of theirs through this space.
  expectStatus(await call(h, { runner: them.machine.token }, 'GET', `/runner/wiki/spaces/${spaceId}/plan/check?jobId=${jobId}`), 404, 'another owner\'s runner checks this job');
  const theirJob = uuidToBase62((await jobs(h, theirs.spaceId))[0].id);
  expectStatus(await call(h, { runner: w.machine.token }, 'GET', `/runner/wiki/spaces/${spaceId}/plan/check?jobId=${theirJob}`), 404, 'a job of another space, through this one');
  for (const [method, route, body] of [
    ['POST', `/wiki/spaces/${spaceId}/plan/redraft`, {}],
    ['GET', `/wiki/spaces/${spaceId}/plan`, undefined],
  ] as const) {
    expectStatus(await call(h, { bearer: them.owner.bearer }, method, route, body), 404, `another owner: ${method} ${route}`);
  }
  assert.equal((await jobs(h, spaceId)).length, 1, 'another owner\'s request made a job here');
});

// ── the run's start, rounds and end, and its check ──────────────────────────────────────────────

test('a run reports its rounds and how it ended; the check passes only for a draft the gate let through; a failed run keeps its errors and its last draft', { skip }, async () => {
  const h = await boot();
  const w = await world(h, 'reporter');
  const { spaceId } = await plannedSpace(h, w);
  const { job, task } = await madeJob(h, spaceId);
  const run = await session(h, w.owner.id, w.ws, w.machine.id, task.id);
  const maintainer: Caller = { runner: w.machine.token, session: run };
  const check = () => call(h, { runner: w.machine.token }, 'GET', `/runner/wiki/spaces/${spaceId}/plan/check?jobId=${uuidToBase62(job.id)}`);

  const context = await call(h, maintainer, 'GET', `/runner/wiki/spaces/${spaceId}/plan/job`);
  expectStatus(context, 200, 'the run reads its job');
  assert.equal(toUuid(context.body.job.id), job.id);
  assert.equal(context.body.job.kind, 'draft');
  assert.equal(toUuid(context.body.job.sessionId), run);
  assert.ok(context.body.job.startedAt, 'the start was not recorded');
  assert.equal(toUuid(context.body.space.workspace.id), w.ws);
  assert.match(context.body.space.repo.urlNorm, /^github\.com\/spec\/planned-/u);

  let checked = await check();
  expectStatus(checked, 200, 'the headless check before the run ended');
  assert.equal(checked.body.ok, false);
  assert.match(checked.body.problems.join(' '), /has not said how it ended/u);

  expectStatus(await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/progress`, { attempt: 2 }), 200, 'round 2');
  let state = await planState(h, w, spaceId);
  assert.deepEqual([state.body.job.state, state.body.job.attempt, state.body.job.attemptsMax], ['running', 2, 3]);
  expectRefusal(await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/progress`, { attempt: 4 }), 400, 'WIKI_SCHEMA', 'a round past the last');

  // A run that says it succeeded names a draft it stored, or is refused.
  expectRefusal(await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'succeeded', version: 1 }), 400, 'WIKI_SCHEMA', 'a success with no draft stored');
  expectRefusal(await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'succeeded' }), 400, 'WIKI_SCHEMA', 'a success naming no version');

  // It failed: the gate's errors on its last round, why, its report and the last draft it had are kept.
  const errors = [
    { check: 'docCount', path: 'plan.docs', message: 'the plan has 40 documents; it must have 20 to 35' },
    { check: 'references', path: 'plan.docs[3].sections[1].sources.code[0]', message: 'claudeRuntime.setPhase is not a symbol of src/runner-go/claude_runtime.go at 99cd3c4' },
  ];
  const report = {
    categories: 11, docs: 40, sections: 321, target: { min: 20, max: 35 },
    attempts: [{ attempt: 1, local: 12, server: 0, checks: { docCount: 1, references: 11 } }, { attempt: 3, local: 2, server: 0, checks: { docCount: 1, references: 1 } }],
    repo: { sha: 'b'.repeat(40), checked: 5566, missing: 47 }, tokens: { input: 1_300_000, output: 150_000, calls: 70 }, seconds: 6400, model: 'qwen3.8-27b-fp8',
  };
  const lastDraft = planOf(40);
  const failed = await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, {
    outcome: 'failed', errors, error: `the gate refused the third round (token ${`AKIA${'Z'.repeat(16)}`})`, report, draft: lastDraft, attempt: 3,
  });
  expectStatus(failed, 200, 'the run ends failed');
  state = await planState(h, w, spaceId);
  const shown = state.body.job;
  assert.deepEqual([shown.state, shown.attempt, shown.version], ['failed', 3, null]);
  assert.deepEqual(shown.errors, errors);
  assert.deepEqual(shown.report, report);
  assert.equal(shown.draft.docs.length, 40, 'the last draft was not kept');
  assert.match(shown.error, /the gate refused the third round/u);
  assert.ok(!shown.error.includes('AKIA'), 'a secret in the error was kept');
  checked = await check();
  assert.equal(checked.body.ok, false);
  assert.match(checked.body.problems.join(' '), /ended failed.*2 errors/u);
  // Ended once: a second end, and a later round, are refused.
  expectRefusal(await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'failed' }), 409, 'WIKI_PLAN_NO_JOB', 'a second end');
  expectRefusal(await call(h, maintainer, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/progress`, { attempt: 1 }), 409, 'WIKI_PLAN_NO_JOB', 'a round after the end');

  // The next job succeeds: it drafts, the gate lets it through, and the check passes.
  await settle(h, task.id, 'FAILED');
  const next = await call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, {});
  expectStatus(next, 200, 'the owner asks again');
  const nextJob = (await jobs(h, spaceId))[1];
  const nextRun: Caller = { runner: w.machine.token, session: await session(h, w.owner.id, w.ws, w.machine.id, nextJob.task_id) };
  expectStatus(await call(h, nextRun, 'GET', `/runner/wiki/spaces/${spaceId}/plan/job`), 200, 'the next run reads its job');
  expectStatus(await call(h, nextRun, 'POST', `/runner/wiki/spaces/${spaceId}/plan/drafts`, {
    baseVersion: null, plan: planOf(), repoCheck: { sha: 'c'.repeat(40), checked: 40, missing: [] }, model: 'qwen3.8-27b-fp8',
  }), 200, 'the next run drafts');
  // Another run's draft is not this one's to claim.
  const otherRun: Caller = { runner: w.machine.token, session: run };
  expectRefusal(await call(h, otherRun, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'succeeded', version: 1 }), 409, 'WIKI_PLAN_NO_JOB', 'the ended run claims a draft');
  expectStatus(await call(h, nextRun, 'POST', `/runner/wiki/spaces/${spaceId}/plan/job/finish`, { outcome: 'succeeded', version: 1, attempt: 1, report }), 200, 'the next run ends');
  const passed = await call(h, { runner: w.machine.token }, 'GET', `/runner/wiki/spaces/${spaceId}/plan/check?jobId=${uuidToBase62(nextJob.id)}`);
  expectStatus(passed, 200, 'the check');
  assert.deepEqual([passed.body.ok, passed.body.outcome, passed.body.version, passed.body.problems], [true, 'succeeded', 1, []]);
  assert.equal(toUuid(passed.body.jobId), nextJob.id);
  state = await planState(h, w, spaceId);
  assert.deepEqual([state.body.job.state, state.body.job.version, state.body.job.draft], ['succeeded', 1, null]);
  assert.equal(state.body.draft.version, 1);
});

// ── a job is no maintenance run ─────────────────────────────────────────────────────────────────

test('a plan job is no maintenance run: it does not count against the day, the day does not hold it, and it runs with maintenance off', { skip }, async () => {
  const h = await boot();
  const w = await world(h, 'daily');
  const { spaceId } = await plannedSpace(h, w, { enabled: true, dailyRunLimit: 1 });
  const { task } = await madeJob(h, spaceId);
  const listId = task.list_id!;
  let today = await wikiMaintenanceRunsToday(h.prisma, w.owner.id, spaceId);
  assert.deepEqual([today.used, today.remaining], [0, 1], 'the plan job counted against the day');

  // A maintenance run uses the day up; the draft's task ended meanwhile.
  await settle(h, task.id, 'CANCELLED');
  const maintenance = await maintenanceTask(h, w.owner.id, listId, w.ws);
  today = await wikiMaintenanceRunsToday(h.prisma, w.owner.id, spaceId);
  assert.deepEqual([today.used, today.remaining], [1, 0]);
  await settle(h, maintenance, 'FAILED');
  const redraft = await call(h, { bearer: w.owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/plan/redraft`, {});
  expectStatus(redraft, 200, 'a redraft on a used-up day');
  assert.equal(redraft.body.job.state, 'running', 'the day\'s limit held the plan job back');
  today = await wikiMaintenanceRunsToday(h.prisma, w.owner.id, spaceId);
  assert.deepEqual([today.used, today.remaining], [1, 0], 'the second plan job counted against the day');

  // Maintenance off: the plan job's session is still claimed, a maintenance run's is refused.
  expectStatus(await call(h, { bearer: w.owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: false } }), 200, 'maintenance off');
  const planTask = (await jobs(h, spaceId))[1].task_id!;
  const planRun = await wikiMaintenanceRunOf(h.prisma, { id: await session(h, w.owner.id, w.ws, w.machine.id, planTask), taskId: planTask, workspaceId: w.ws, provider: w.slug });
  assert.equal(planRun?.refusal, undefined, `the plan job's run was refused: ${planRun?.refusal}`);
  const other = await maintenanceTask(h, w.owner.id, listId, w.ws);
  const maintenanceRun = await wikiMaintenanceRunOf(h.prisma, { id: await session(h, w.owner.id, w.ws, w.machine.id, other), taskId: other, workspaceId: w.ws, provider: w.slug });
  assert.match(maintenanceRun?.refusal ?? '', /maintenance is off/u);
});

// ── the schema ──────────────────────────────────────────────────────────────────────────────────

/** The values a CHECK spells out, in the order it spells them. */
async function checkValues(h: Harness, constraint: string): Promise<string[]> {
  const def = await h.sql.query<{ def: string }>(
    `SELECT pg_get_constraintdef(oid) AS def FROM pg_constraint WHERE conname = $1 AND conrelid = 'wiki_plan_job'::regclass`,
    [constraint],
  );
  assert.equal(def.rowCount, 1, `wiki_plan_job has no constraint ${constraint}`);
  return [...def.rows[0].def.matchAll(/'([^']+)'::text/gu)].map((m) => m[1]);
}

test('the migration\'s CHECKs are the contract\'s closed sets, a space has one open draft, and its delete takes its jobs', { skip }, async () => {
  const h = await boot();
  assert.deepEqual(await checkValues(h, 'wiki_plan_job_kind_chk'), [...WIKI_PLAN_JOB_KINDS]);
  assert.deepEqual(await checkValues(h, 'wiki_plan_job_trigger_chk'), [...WIKI_PLAN_JOB_TRIGGERS]);
  assert.deepEqual(await checkValues(h, 'wiki_plan_job_state_chk'), [...WIKI_PLAN_JOB_STORED_STATES]);
  assert.deepEqual(await checkValues(h, 'wiki_plan_job_held_reason_chk'), [...WIKI_PLAN_JOB_HELD_REASONS]);
  assert.deepEqual(await checkValues(h, 'wiki_plan_job_outcome_chk'), [...WIKI_PLAN_JOB_OUTCOMES]);
  const w = await world(h, 'schema');
  const made = await call(h, { bearer: w.owner.bearer }, 'POST', '/wiki/spaces', { title: 'A space', repoUrl: `https://github.com/spec/schema-${randomUUID().slice(0, 8)}` });
  const spaceId = toUuid(made.body.id as string);
  // A second open draft beside the held one, written past the service, is refused by the index.
  const second = await h.sql.query(
    `INSERT INTO "wiki_plan_job"("id","space_id","owner_id","kind","trigger","state") VALUES ($1,$2,$3,'draft','owner','queued')`,
    [randomUUID(), spaceId, w.owner.id],
  ).then(() => null, (e: Error) => e);
  assert.ok(second, 'a second open draft of one space was stored');
  assert.match(second.message, /wiki_plan_job_space_id_open_draft_key/u);
  // A revision with no instructions, a held job with no reason, and a success with no version are refused
  // by their CHECKs — each row wrong in that one way alone.
  for (const [values, constraint] of [
    [`'revise','owner',NULL,'ended',NULL,gen_random_uuid(),now(),now(),'failed',NULL`, /wiki_plan_job_instructions_chk/u],
    [`'build','owner',NULL,'held',NULL,NULL,NULL,NULL,NULL,NULL`, /wiki_plan_job_held_chk/u],
    [`'build','owner',NULL,'ended',NULL,gen_random_uuid(),now(),now(),'succeeded',NULL`, /wiki_plan_job_ended_chk/u],
  ] as const) {
    const refused = await h.sql.query(
      `INSERT INTO "wiki_plan_job"("id","space_id","owner_id","kind","trigger","instructions","state","held_reason","task_id","made_at","ended_at","outcome","version")
       VALUES ($1,$2,$3,${values})`,
      [randomUUID(), spaceId, w.owner.id],
    ).then(() => null, (e: Error) => e);
    assert.ok(refused, `${constraint} let a row through`);
    assert.match(refused.message, constraint);
  }
  await h.sql.query(`DELETE FROM "wiki_space" WHERE "id" = $1`, [spaceId]);
  assert.equal((await jobs(h, spaceId)).length, 0, 'the space\'s delete left its jobs');
});
