/**
 * The anchor re-verification (criterion 4; contracts/wiki.contract.json `anchorRules.verify`), over
 * real HTTP and against a real PostgreSQL.
 *
 * What criterion 4's verification method asks, each read back from the doors and from the database:
 *
 *   1. an entry whose anchor a check finds missing or changed is not in the next push;
 *   2. Review holds one more card for it: a system challenge, filed once however often the check says so;
 *   3. the owner's Re-confirm (a new baseline), Amend and Retire each do what they say, on the owner's
 *      door alone;
 *   4. a session that is not a maintenance run of the space reports nothing;
 *
 * and beside them: the list hands out each entry's git anchors at its revision, and the checkout the
 * space's workspace names as stored; a symbol is held to its baseline by the server whatever the runner
 * says; a report against a revision that moved is stale and writes nothing; a revision stores its
 * anchors without the check; and a Tiered pitfall whose anchors verified becomes Auto when its sources
 * span two sessions, and only then.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-anchors.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { Prisma, PrismaClient } from '@prisma/client';
import { toUuid, type WikiAnchor } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiAnchorsController } from '../runner-api/runner-wiki-anchors.controller';
import { WikiController } from './wiki.controller';
import { appendWikiContext } from './wiki-push';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The push as a session starting now would be handed it: the wiki on, whatever this shell says. */
const WIKI_ON = { mode: 'on' as const, canaryOwners: new Set<string>(), problems: [] };

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = {} as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);

    @Module({
      controllers: [WikiController, RunnerWikiAnchorsController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiAnchorsModule {}

    const app = await NestFactory.create(WikiAnchorsModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 800)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

/** The refs a run checked on, and the region hashes it found: the server takes both as reported. */
const REF_1 = createHash('sha1').update('origin/main, first check').digest('hex');
const REF_2 = createHash('sha1').update('origin/main, second check').digest('hex');
const REF_3 = createHash('sha1').update('origin/main, third check').digest('hex');
const REGION_1 = createHash('sha256').update('export function foo() {\n').digest('hex');
const REGION_2 = createHash('sha256').update('export function foo(bar: string) {\n').digest('hex');
const COMMIT = createHash('sha1').update('a commit the entry names').digest('hex');

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-anchors-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string, workDir: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","work_dir") VALUES ($1,'spec',$2,$3)`, [id, ownerId, workDir]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string | null, runnerId: string | null, taskId: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id","task_id",
                            "dispatch_origin","updated_at")
     VALUES ($1,'a wiki session','p',$2,$2,$3,$4,$5,'USER',now())`,
    [id, ownerId, workspaceId, runnerId, taskId],
  );
  return id;
}

async function task(h: Harness, ownerId: string, listId: string | null, assigneeId: string | null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id","completion_criterion","updated_at")
     VALUES ($1,'Wiki maintenance run',$2,'USER',$2,'OPEN'::task_status,$3,$4,'OWNER_CONFIRMED',now())`,
    [id, ownerId, assigneeId, listId],
  );
  return id;
}

async function toolCall(h: Harness, sessionId: string, output: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","output") VALUES ($1,$2,'Bash',$3)`, [
    id,
    sessionId,
    JSON.stringify(output),
  ]);
  return id;
}

/** A space the owner makes and binds, with maintenance on, and one maintenance run of it on the runner. */
interface Maintained {
  owner: Account;
  machine: { id: string; token: string };
  workspaceId: string;
  spaceId: string;
  /** The maintenance run: a session whose task is in the space's hidden list. */
  run: string;
}

async function maintainedSpace(h: Harness, name: string, workDir = '~/orbit-anchors-spec'): Promise<Maintained> {
  const owner = await account(h, name);
  const machine = await runner(h, owner.id);
  const workspaceId = await workspace(h, owner.id, workDir);
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: `${name}'s codebase` });
  expectStatus(made, 201, 'the owner creates a space');
  const spaceId = toUuid(made.body.id as string);
  expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId }), 200, 'the owner binds the workspace');
  const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true, workspaceId } });
  expectStatus(on, 200, 'the owner turns maintenance on');
  const listId = toUuid(on.body.settings.maintenance.listId as string);
  const run = await session(h, owner.id, workspaceId, machine.id, await task(h, owner.id, listId, workspaceId));
  return { owner, machine, workspaceId, spaceId, run };
}

function convention(title: string, anchors: unknown[]): Record<string, unknown> {
  return {
    kind: 'convention',
    title,
    summary: `What the space holds about ${title.toLowerCase()}.`,
    fields: { rule: 'Model a closed set as TEXT plus a CHECK constraint.', scope: ['src/apiserver/prisma/migrations/**'] },
    anchors,
  };
}

/** An entry the owner writes: live at once, trust owner, and pushed while nothing holds it out. */
async function ownerEntry(h: Harness, m: Maintained, title: string, anchors: unknown[]): Promise<string> {
  const written = await call(h, { bearer: m.owner.bearer }, 'POST', `/wiki/spaces/${m.spaceId}/changesets`, {
    rationale: `the owner records ${title}`,
    idempotencyKey: `anchors-${randomUUID()}`,
    ops: [{ op: 'add', entry: convention(title, anchors) }],
  });
  expectStatus(written, 200, `the owner writes ${title}`);
  assert.equal(written.body.ops[0].status, 'applied');
  return toUuid(written.body.ops[0].entryId as string);
}

async function entryRow(h: Harness, id: string) {
  return h.prisma.wikiEntry.findFirstOrThrow({ where: { id } });
}

/** The entries the next session in this workspace is handed, by id. */
async function pushed(h: Harness, m: Maintained): Promise<Set<string>> {
  const content = await appendWikiContext(h.prisma as unknown as Prisma.TransactionClient, {
    sessionId: await session(h, m.owner.id, m.workspaceId, m.machine.id),
    turnId: randomUUID(),
    leaseGeneration: randomUUID(),
    ownerId: m.owner.id,
    workspaceId: m.workspaceId,
    taskId: null,
    task: null,
    dispatchOrigin: 'USER',
    content: 'What should I know about this codebase?',
  }, WIKI_ON);
  return new Set([...String(content).matchAll(/\(orbit-wiki:([0-9A-Za-z]+)\)/gu)].map((match) => toUuid(match[1])));
}

async function listAnchors(h: Harness, m: Maintained, query = ''): Promise<Answer> {
  return call(h, { runner: m.machine.token, session: m.run }, 'GET', `/runner/wiki/spaces/${m.spaceId}/anchors${query}`);
}

interface Check {
  index: number;
  type: 'path' | 'symbol' | 'commit';
  state: 'verified' | 'changed' | 'missing';
  regionSha256?: string;
}

async function report(h: Harness, m: Maintained, ref: string, entries: Array<{ entryId: string; revision: number; checks: Check[] }>, who?: Caller): Promise<Answer> {
  return call(h, who ?? { runner: m.machine.token, session: m.run }, 'POST', `/runner/wiki/spaces/${m.spaceId}/anchor-checks`, { ref, entries });
}

/** The pending changesets of the space's Review that hold a challenge of this entry. */
async function challengesOf(h: Harness, m: Maintained, entryId: string): Promise<Array<Record<string, unknown>>> {
  const review = await call(h, { bearer: m.owner.bearer }, 'GET', `/wiki/review?space=${m.spaceId}`);
  expectStatus(review, 200, 'the owner reads Review');
  return (review.body as Array<{ ops: Array<Record<string, unknown>> } & Record<string, unknown>>)
    .filter((changeset) => changeset.ops.some((op) => op.op === 'challenge' && op.decision === 'pending' && toUuid(op.entryId as string) === entryId));
}

async function decide(h: Harness, m: Maintained, changesetId: string, decision: Record<string, unknown>, who?: Caller): Promise<Answer> {
  return call(h, who ?? { bearer: m.owner.bearer }, 'POST', `/wiki/changesets/${changesetId}/decide`, { decisions: [decision] });
}

/** The system challenge of an entry, as Review shows it: its changeset and its op. */
async function theChallenge(h: Harness, m: Maintained, entryId: string): Promise<{ changesetId: string; opId: string; reason: string }> {
  const found = await challengesOf(h, m, entryId);
  assert.equal(found.length, 1, `one challenge of the entry waits in Review: ${JSON.stringify(found).slice(0, 600)}`);
  const op = (found[0].ops as Array<Record<string, unknown>>).find((row) => row.op === 'challenge')!;
  return { changesetId: found[0].id as string, opId: op.id as string, reason: String((op.payload as { reason?: string }).reason ?? '') };
}

// ── 4. only a maintenance run of the space reports ──────────────────────────────────────────────

test('the anchors door answers a maintenance run of the space and refuses everyone else', { skip }, async () => {
  const h = await boot();
  const m = await maintainedSpace(h, 'door');
  const entryId = await ownerEntry(h, m, 'Closed sets are CHECK constraints', [{ type: 'path', path: 'docs/wiki-design.md' }]);
  const plain = await session(h, m.owner.id, m.workspaceId, m.machine.id);
  const otherTask = await session(h, m.owner.id, m.workspaceId, m.machine.id, await task(h, m.owner.id, null, m.workspaceId));

  const listed = await listAnchors(h, m);
  expectStatus(listed, 200, 'a maintenance run reads its space\'s anchors');
  assert.equal(listed.body.entries.length, 1);
  assert.equal(toUuid(listed.body.entries[0].entryId), entryId);
  assert.equal(listed.body.entries[0].revision, 1);
  assert.deepEqual(listed.body.entries[0].anchors, [{ index: 0, type: 'path', path: 'docs/wiki-design.md' }]);
  // The checkout the space's workspace names, AS STORED: the runner expands `~`, this server cannot.
  assert.equal(listed.body.repo.workDir, '~/orbit-anchors-spec');
  assert.equal(toUuid(listed.body.repo.workspaceId), m.workspaceId);
  assert.equal(listed.body.next, null);

  const checks = [{ entryId, revision: 1, checks: [{ index: 0, type: 'path', state: 'missing' }] }];
  for (const [who, sessionId] of [['a plain session', plain], ['a task outside the maintenance list', otherTask]] as const) {
    const read = await call(h, { runner: m.machine.token, session: sessionId }, 'GET', `/runner/wiki/spaces/${m.spaceId}/anchors`);
    expectStatus(read, 403, `${who} reads no anchors`);
    assert.equal(read.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
    const reported = await report(h, m, REF_1, checks as never, { runner: m.machine.token, session: sessionId });
    expectStatus(reported, 403, `${who} reports no check`);
    assert.equal(reported.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
  }
  const headless = await report(h, m, REF_1, checks as never, { runner: m.machine.token });
  expectStatus(headless, 400, 'a headless call has no session to be a maintenance run');

  // Another tenant: their runner and their own maintenance run, and our space — and our run on their runner.
  const theirs = await maintainedSpace(h, 'tenant');
  const across = await report(h, m, REF_1, checks as never, { runner: theirs.machine.token, session: theirs.run });
  expectStatus(across, 404, "another account's space is a plain 404");
  const borrowed = await report(h, m, REF_1, checks as never, { runner: theirs.machine.token, session: m.run });
  expectStatus(borrowed, 403, 'a session another runner hosts is not this runner\'s to name');
  const intoTheirs = await call(h, { runner: m.machine.token, session: m.run }, 'GET', `/runner/wiki/spaces/${theirs.spaceId}/anchors`);
  expectStatus(intoTheirs, 404, 'a maintenance run reads nothing of another account');

  // Nothing any refused report said was written.
  const row = await entryRow(h, entryId);
  assert.equal(row.anchorState, 'unchecked');
  assert.equal(row.challenged, false);
  assert.equal(row.anchorCheckedRef, null);
  assert.deepEqual(await challengesOf(h, m, entryId), []);
});

// ── 1 and 2. a broken anchor: out of the next push, and one system challenge in Review ─────────

test('a check that finds an anchor missing or changed takes the entry out of the next push and files one system challenge', { skip }, async () => {
  const h = await boot();
  const m = await maintainedSpace(h, 'broken');
  const byPath = await ownerEntry(h, m, 'Design lives in docs', [{ type: 'path', path: 'docs/a.md' }]);
  const bySymbol = await ownerEntry(h, m, 'Foo takes no argument', [{ type: 'symbol', path: 'src/a.ts', symbol: 'foo' }]);
  const byCommit = await ownerEntry(h, m, 'The fix landed', [{ type: 'commit', sha: COMMIT }]);
  const before = await pushed(h, m);
  for (const id of [byPath, bySymbol, byCommit]) assert.ok(before.has(id), 'the owner\'s entries are pushed before any check');

  // The first check: everything as recorded. The symbol named no hash of its own, so this check's is its baseline.
  const first = await report(h, m, REF_1, [
    { entryId: byPath, revision: 1, checks: [{ index: 0, type: 'path', state: 'verified' }] },
    { entryId: bySymbol, revision: 1, checks: [{ index: 0, type: 'symbol', state: 'verified', regionSha256: REGION_1 }] },
    { entryId: byCommit, revision: 1, checks: [{ index: 0, type: 'commit', state: 'verified' }] },
  ]);
  expectStatus(first, 200, 'the first check is recorded');
  for (const outcome of first.body.outcomes) {
    assert.equal(outcome.status, 'recorded', JSON.stringify(outcome));
    assert.equal(outcome.anchorState, 'verified');
    assert.equal(outcome.challenged, false);
    assert.equal(outcome.challengeOpId, null);
  }
  const verified = await entryRow(h, bySymbol);
  assert.equal(verified.anchorState, 'verified');
  assert.equal(verified.anchorCheckedRef, REF_1);
  assert.ok(verified.anchorCheckedAt, 'the check says when');
  const kept = (verified.anchors as unknown as WikiAnchor[])[0];
  assert.deepEqual({ ...kept.check, at: undefined }, { state: 'verified', ref: REF_1, at: undefined, regionSha256: REGION_1, baselineSha256: REGION_1 });
  assert.equal(verified.currentRevision, 1, 'a check is not a revision');
  const listed = await listAnchors(h, m);
  const symbolDue = listed.body.entries.find((row: { entryId: string }) => toUuid(row.entryId) === bySymbol);
  assert.equal(symbolDue.anchors[0].regionSha256, REGION_1, 'the list hands the runner the baseline the symbol is held to');

  // The second check: the path is gone, and the symbol's region moved — which the runner calls verified,
  // and the server, holding the symbol to its baseline, records as changed.
  const second = await report(h, m, REF_2, [
    { entryId: byPath, revision: 1, checks: [{ index: 0, type: 'path', state: 'missing' }] },
    { entryId: bySymbol, revision: 1, checks: [{ index: 0, type: 'symbol', state: 'verified', regionSha256: REGION_2 }] },
    { entryId: byCommit, revision: 1, checks: [{ index: 0, type: 'commit', state: 'verified' }] },
  ]);
  expectStatus(second, 200, 'the second check is recorded');
  const [pathOutcome, symbolOutcome, commitOutcome] = second.body.outcomes;
  assert.deepEqual([pathOutcome.anchorState, symbolOutcome.anchorState, commitOutcome.anchorState], ['missing', 'changed', 'verified']);
  assert.deepEqual([pathOutcome.challenged, symbolOutcome.challenged, commitOutcome.challenged], [true, true, false]);
  assert.ok(pathOutcome.challengeOpId && symbolOutcome.challengeOpId, 'each broken entry filed its challenge');
  assert.equal(commitOutcome.challengeOpId, null);
  const changed = await entryRow(h, bySymbol);
  const changedCheck = (changed.anchors as unknown as WikiAnchor[])[0].check!;
  assert.equal(changedCheck.state, 'changed');
  assert.equal(changedCheck.regionSha256, REGION_2, 'what this check found');
  assert.equal(changedCheck.baselineSha256, REGION_1, 'a changed region does not move the baseline');

  // 1. Out of the next push, at once — and the entry whose anchors held stays in it.
  const after = await pushed(h, m);
  assert.equal(after.has(byPath), false, 'a missing anchor takes its entry out of the push');
  assert.equal(after.has(bySymbol), false, 'a changed anchor takes its entry out of the push');
  assert.equal(after.has(byCommit), true, 'an entry whose anchors held is still pushed');

  // 2. One system challenge each in Review: the maintenance origin, no session, the anchor in its reason.
  const pathChallenge = await theChallenge(h, m, byPath);
  const symbolChallenge = await theChallenge(h, m, bySymbol);
  assert.equal(toUuid(pathChallenge.opId), toUuid(pathOutcome.challengeOpId));
  assert.match(pathChallenge.reason, /path docs\/a\.md is missing/u);
  assert.match(symbolChallenge.reason, /symbol foo in src\/a\.ts has changed/u);
  assert.match(symbolChallenge.reason, new RegExp(REF_2, 'u'));
  const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: toUuid(pathChallenge.changesetId) } });
  assert.equal(changeset.origin, 'maintenance');
  assert.equal(changeset.sessionId, null, 'a system challenge counts against no session');
  assert.equal(changeset.status, 'pending');

  // The same finding reported again files no second card.
  const again = await report(h, m, REF_2, [
    { entryId: byPath, revision: 1, checks: [{ index: 0, type: 'path', state: 'missing' }] },
    { entryId: bySymbol, revision: 1, checks: [{ index: 0, type: 'symbol', state: 'changed', regionSha256: REGION_2 }] },
  ]);
  expectStatus(again, 200, 'the same check reported again');
  assert.deepEqual(again.body.outcomes.map((outcome: { challengeOpId: unknown }) => outcome.challengeOpId), [null, null]);
  for (const id of [byPath, bySymbol]) {
    const open = await h.prisma.wikiChangesetOp.count({ where: { entryId: id, op: 'challenge', decision: 'pending' } });
    assert.equal(open, 1, 'one challenge, however often the check says so');
  }
  // A check is not content: the revision the entry rests on stores its anchors as they were written.
  const revision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: bySymbol, revision: 1 } });
  assert.deepEqual(revision.anchors, [{ type: 'symbol', path: 'src/a.ts', symbol: 'foo' }]);
});

// ── 3. the owner's three answers ────────────────────────────────────────────────────────────────

test('Re-confirm resets the baseline, Amend applies the owner\'s changes, Retire retires — on the owner\'s door alone', { skip }, async () => {
  const h = await boot();
  const m = await maintainedSpace(h, 'answers');
  const symbol = await ownerEntry(h, m, 'Foo takes one argument', [{ type: 'symbol', path: 'src/a.ts', symbol: 'foo' }]);
  const twoPaths = await ownerEntry(h, m, 'Two files hold it', [{ type: 'path', path: 'docs/keep.md' }, { type: 'path', path: 'docs/gone.md' }]);
  const moved = await ownerEntry(h, m, 'The design moved', [{ type: 'path', path: 'docs/old.md' }]);
  const unmerged = await ownerEntry(h, m, 'A fix on a branch', [{ type: 'commit', sha: COMMIT }]);
  expectStatus(await report(h, m, REF_1, [
    { entryId: symbol, revision: 1, checks: [{ index: 0, type: 'symbol', state: 'verified', regionSha256: REGION_1 }] },
  ]), 200, 'the symbol is checked once');
  const broke = await report(h, m, REF_2, [
    { entryId: symbol, revision: 1, checks: [{ index: 0, type: 'symbol', state: 'changed', regionSha256: REGION_2 }] },
    { entryId: twoPaths, revision: 1, checks: [{ index: 0, type: 'path', state: 'verified' }, { index: 1, type: 'path', state: 'missing' }] },
    { entryId: moved, revision: 1, checks: [{ index: 0, type: 'path', state: 'missing' }] },
    // A sha that is not an ancestor of origin/main is missing: the runner says so, and it is recorded so.
    { entryId: unmerged, revision: 1, checks: [{ index: 0, type: 'commit', state: 'missing' }] },
  ]);
  expectStatus(broke, 200, 'the breaking check is recorded');
  assert.deepEqual(broke.body.outcomes.map((outcome: { anchorState: string }) => outcome.anchorState), ['changed', 'missing', 'missing', 'missing']);
  const out = await pushed(h, m);
  for (const id of [symbol, twoPaths, moved, unmerged]) assert.equal(out.has(id), false, 'every broken entry is out of the push');

  // Deciding is the owner channel's: a request carrying a session header is refused, whatever it is.
  const symbolChallenge = await theChallenge(h, m, symbol);
  const fromSession = await decide(h, m, symbolChallenge.changesetId, { opId: symbolChallenge.opId, action: 'reconfirm' },
    { bearer: m.owner.bearer, session: m.run });
  expectStatus(fromSession, 403, 'a session does not answer a challenge');
  assert.equal(fromSession.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
  assert.equal((await entryRow(h, symbol)).challenged, true, 'the refused answer changed nothing');

  // Re-confirm: the region the check found is the new baseline, written as the anchor's own, in the owner's revision.
  const reconfirmed = await decide(h, m, symbolChallenge.changesetId, { opId: symbolChallenge.opId, action: 'reconfirm' });
  expectStatus(reconfirmed, 200, 'the owner re-confirms');
  assert.equal(reconfirmed.body.ops[0].decision, 'accepted');
  const rebased = await entryRow(h, symbol);
  assert.equal(rebased.currentRevision, 2, 'a new baseline is a revision of the owner\'s');
  const rebasedAnchor = (rebased.anchors as unknown as WikiAnchor[])[0] as WikiAnchor & { regionSha256?: string };
  assert.equal(rebasedAnchor.regionSha256, REGION_2, 'the region the check found is the anchor\'s own now');
  assert.equal(rebasedAnchor.check?.state, 'verified');
  assert.equal(rebased.anchorState, 'verified');
  assert.equal(rebased.anchorCheckedRef, REF_2);
  assert.equal(rebased.challenged, false);
  assert.equal(rebased.trust, 'owner');
  const rebasedRevision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: symbol, revision: 2 } });
  assert.equal(rebasedRevision.authorKind, 'owner');
  assert.equal(rebasedRevision.authorUserId, m.owner.id);
  assert.deepEqual(rebasedRevision.anchors, [{ type: 'symbol', path: 'src/a.ts', symbol: 'foo', regionSha256: REGION_2 }]);
  // And the next check holds it to the new baseline: the same region is verified now.
  const held = await report(h, m, REF_3, [
    { entryId: symbol, revision: 2, checks: [{ index: 0, type: 'symbol', state: 'verified', regionSha256: REGION_2 }] },
  ]);
  expectStatus(held, 200, 'the next check');
  assert.equal(held.body.outcomes[0].anchorState, 'verified');
  assert.equal(held.body.outcomes[0].challengeOpId, null);

  // Re-confirm drops an anchor the check found missing, and keeps the one that held.
  const twoChallenge = await theChallenge(h, m, twoPaths);
  expectStatus(await decide(h, m, twoChallenge.changesetId, { opId: twoChallenge.opId, action: 'reconfirm', note: 'gone.md was folded into keep.md' }),
    200, 'the owner re-confirms the entry without the file that went');
  const pruned = await entryRow(h, twoPaths);
  assert.deepEqual((pruned.anchors as unknown as WikiAnchor[]).map((anchor) => (anchor as { path?: string }).path), ['docs/keep.md']);
  assert.equal(pruned.anchorState, 'verified');
  assert.equal(pruned.challenged, false);

  // Amend: the owner's changes over the entry; anchors given are new, and unchecked until the next check.
  const movedChallenge = await theChallenge(h, m, moved);
  const noEdit = await decide(h, m, movedChallenge.changesetId, { opId: movedChallenge.opId, action: 'amend' });
  expectStatus(noEdit, 400, 'an amend with nothing to change');
  assert.equal(noEdit.body.code, 'WIKI_SCHEMA');
  const amended = await decide(h, m, movedChallenge.changesetId, {
    opId: movedChallenge.opId,
    action: 'amend',
    edited: { summary: 'The design lives in docs/new.md now.', anchors: [{ type: 'path', path: 'docs/new.md' }] },
  });
  expectStatus(amended, 200, 'the owner amends');
  assert.equal(amended.body.ops[0].decision, 'edited');
  const moving = await entryRow(h, moved);
  assert.equal(moving.currentRevision, 2);
  assert.equal(moving.summary, 'The design lives in docs/new.md now.');
  assert.deepEqual(moving.anchors, [{ type: 'path', path: 'docs/new.md' }]);
  assert.equal(moving.anchorState, 'unchecked');
  assert.equal(moving.anchorCheckedRef, null);
  assert.equal(moving.challenged, false);

  // Retire: the owner's own retire, recorded as one; the challenge goes with the entry.
  const unmergedChallenge = await theChallenge(h, m, unmerged);
  const retired = await decide(h, m, unmergedChallenge.changesetId, { opId: unmergedChallenge.opId, action: 'retire', note: 'The branch was abandoned.' });
  expectStatus(retired, 200, 'the owner retires');
  assert.equal(retired.body.ops[0].decision, 'withdrawn', 'the challenge left with the entry it was about');
  assert.equal(retired.body.status, 'settled');
  const gone = await entryRow(h, unmerged);
  assert.equal(gone.status, 'retired');
  const retire = await h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { entryId: unmerged, op: 'retire' }, include: { changeset: true } });
  assert.equal(retire.decision, 'auto_applied');
  assert.equal(retire.changeset.origin, 'owner');
  assert.equal((retire.payload as { reason?: string }).reason, 'The branch was abandoned.');

  // Back in the push: the re-confirmed and the amended; not the retired.
  const back = await pushed(h, m);
  assert.equal(back.has(symbol), true, 'a re-confirmed entry is pushed again');
  assert.equal(back.has(twoPaths), true, 'so is one re-confirmed without its missing anchor');
  assert.equal(back.has(moved), true, 'an amended entry is pushed again');
  assert.equal(back.has(unmerged), false, 'a retired one never is');
  for (const id of [symbol, twoPaths, moved, unmerged]) assert.deepEqual(await challengesOf(h, m, id), [], 'Review holds none of them now');

  // The three answer a challenge and nothing else: a retire waiting for the owner is not re-confirmed.
  const system: WikiPrincipal = { origin: 'maintenance', ownerId: m.owner.id, userId: null, sessionId: null, toolCallId: null, authorKind: 'system' };
  const proposed = await h.service.submitChangeset(system, m.spaceId, {
    rationale: 'a run thinks it stale',
    ops: [{ op: 'retire', entryId: symbol, baseRevision: 2, reason: 'foo is going away' }],
  });
  const waiting = (proposed.ops as Array<{ status: string; opId: string }>)[0];
  assert.equal(waiting.status, 'pending');
  const wrongOp = await decide(h, m, proposed.changesetId as string, { opId: waiting.opId, action: 'reconfirm' });
  expectStatus(wrongOp, 400, 'reconfirm answers a challenge only');
  assert.equal(wrongOp.body.code, 'WIKI_SCHEMA');
  expectStatus(await decide(h, m, proposed.changesetId as string, { opId: waiting.opId, action: 'reject', reason: 'not_true' }), 200,
    'the owner rejects the retire');
});

// ── the report itself: stale, malformed, another space's ────────────────────────────────────────

test('a report against a revision that moved is stale, and a malformed one is refused, writing nothing', { skip }, async () => {
  const h = await boot();
  const m = await maintainedSpace(h, 'stale');
  const entryId = await ownerEntry(h, m, 'Paths are repo-relative', [{ type: 'path', path: 'docs/a.md' }, { type: 'symbol', path: 'src/a.ts', symbol: 'foo' }]);
  const amended = await call(h, { bearer: m.owner.bearer }, 'POST', `/wiki/spaces/${m.spaceId}/changesets`, {
    rationale: 'the owner sharpens it',
    idempotencyKey: `anchors-${randomUUID()}`,
    ops: [{ op: 'amend', entryId, baseRevision: 1, changes: { summary: 'Paths are repo-relative, with no leading slash.' } }],
  });
  expectStatus(amended, 200, 'the owner amends the entry after the list was read');

  const late = await report(h, m, REF_1, [{ entryId, revision: 1, checks: [{ index: 0, type: 'path', state: 'missing' }] }]);
  expectStatus(late, 200, 'a stale entry is no failure of the report');
  assert.equal(late.body.outcomes[0].status, 'stale');
  assert.match(late.body.outcomes[0].message, /revision 2/u);
  const wrongType = await report(h, m, REF_1, [{ entryId, revision: 2, checks: [{ index: 0, type: 'symbol', state: 'missing' }] }]);
  expectStatus(wrongType, 200, 'an anchor list that moved');
  assert.equal(wrongType.body.outcomes[0].status, 'stale');
  let row = await entryRow(h, entryId);
  assert.equal(row.anchorState, 'unchecked', 'nothing of a stale report is written');
  assert.equal(row.anchorCheckedRef, null);

  const badRef = await report(h, m, 'origin/main', [{ entryId, revision: 2, checks: [{ index: 0, type: 'path', state: 'verified' }] }]);
  expectStatus(badRef, 400, 'the ref is a commit sha');
  assert.equal(badRef.body.code, 'WIKI_SCHEMA');
  const noHash = await report(h, m, REF_1, [{ entryId, revision: 2, checks: [{ index: 1, type: 'symbol', state: 'verified' }] }]);
  expectStatus(noHash, 400, 'a symbol found carries the hash of its region');
  assert.equal(noHash.body.outcomes[0].code, 'WIKI_SCHEMA');
  assert.match(noHash.body.outcomes[0].message, /regionSha256/u);
  const pathChanged = await report(h, m, REF_1, [{ entryId, revision: 2, checks: [{ index: 0, type: 'path', state: 'changed' }] }]);
  expectStatus(pathChanged, 400, 'a path is verified or missing, never changed');
  const elsewhere = await maintainedSpace(h, 'elsewhere');
  const foreign = await ownerEntry(h, elsewhere, 'Not this space', [{ type: 'path', path: 'docs/a.md' }]);
  const notHere = await report(h, m, REF_1, [{ entryId: foreign, revision: 1, checks: [{ index: 0, type: 'path', state: 'missing' }] }]);
  expectStatus(notHere, 404, "another space's entry is not this space's to report");
  row = await entryRow(h, entryId);
  assert.equal(row.anchorState, 'unchecked', 'no refused report wrote anything');
  assert.equal((await entryRow(h, foreign)).anchorState, 'unchecked');

  // And one that is well formed now: both anchors, at the entry's current revision.
  const good = await report(h, m, REF_1, [{ entryId, revision: 2, checks: [
    { index: 0, type: 'path', state: 'verified' },
    { index: 1, type: 'symbol', state: 'verified', regionSha256: REGION_1 },
  ] }]);
  expectStatus(good, 200, 'a report of the current revision');
  assert.equal(good.body.outcomes[0].anchorState, 'verified');
});

// ── Tiered reads what a check writes ────────────────────────────────────────────────────────────

test('a pitfall Tiered applied as Unreviewed becomes Auto once its anchors verify, when its sources span two sessions', { skip }, async () => {
  const h = await boot();
  const m = await maintainedSpace(h, 'tiered');
  const space = await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: m.spaceId } });
  assert.equal((space.settings as { reviewMode?: string }).reviewMode, 'tiered', 'a space made today is Tiered');
  const proposer = await session(h, m.owner.id, m.workspaceId, m.machine.id);
  const first = await toolCall(h, await session(h, m.owner.id, m.workspaceId, m.machine.id), 'exited 0 with every case skipped');
  const second = await toolCall(h, await session(h, m.owner.id, m.workspaceId, m.machine.id), 'the same spec skipped every case again');
  const agent: WikiPrincipal = { origin: 'agent', ownerId: m.owner.id, userId: null, sessionId: proposer, toolCallId: null };
  const pitfall = (title: string, sources: unknown[]) => ({
    op: 'add',
    entry: {
      kind: 'pitfall',
      title,
      summary: 'A green run that witnessed no assertion.',
      fields: {
        trigger: { paths: ['src/apiserver/src/wiki/'], commands: ['node --test build/wiki/x.pg.spec.js'] },
        symptom: 'A green run that witnessed no assertion.',
        cause: 'A pg spec skips itself without a database.',
        fix: 'Run it through scripts/run-pg-spec.sh.',
      },
      anchors: [{ type: 'path', path: 'scripts/run-pg-spec.sh' }],
    },
    sources,
  });
  const proposed = await h.service.submitChangeset(agent, m.spaceId, {
    rationale: 'two pitfalls this session ran into',
    idempotencyKey: `anchors-${randomUUID()}`,
    ops: [
      pitfall('A pg spec with no database skips green', [
        { kind: 'tool_call', ref: first, quote: 'exited 0 with every case skipped' },
        { kind: 'tool_call', ref: second, quote: 'skipped every case again' },
      ]),
      pitfall('One session saw a skipped spec', [{ kind: 'tool_call', ref: first, quote: 'every case skipped' }]),
    ],
  });
  const [twice, once] = (proposed.ops as Array<{ status: string; entryId: string }>).map((op) => {
    assert.equal(op.status, 'applied', 'Tiered applies an add at once');
    return toUuid(op.entryId);
  });
  for (const id of [twice, once]) {
    const row = await entryRow(h, id);
    assert.equal(row.trust, 'unreviewed', 'a new pitfall\'s anchors are unchecked, so it is not machine-verified yet');
  }
  const unpushed = await pushed(h, m);
  assert.equal(unpushed.has(twice), false, 'an unreviewed entry is never pushed');

  const checked = await report(h, m, REF_1, [
    { entryId: twice, revision: 1, checks: [{ index: 0, type: 'path', state: 'verified' }] },
    { entryId: once, revision: 1, checks: [{ index: 0, type: 'path', state: 'verified' }] },
  ]);
  expectStatus(checked, 200, 'the check is recorded');
  assert.deepEqual(checked.body.outcomes.map((outcome: { trust: string }) => outcome.trust), ['auto', 'unreviewed'],
    'verified anchors and two sessions make a pitfall Auto; one session does not');
  assert.equal((await entryRow(h, twice)).trust, 'auto');
  assert.equal((await entryRow(h, once)).trust, 'unreviewed');
  const handed = await pushed(h, m);
  assert.equal(handed.has(twice), true, 'what Tiered made Auto is pushed');
  assert.equal(handed.has(once), false);

  // And a pitfall the check found broken is out of the push again, challenged, and keeps its trust for the owner to judge.
  const broken = await report(h, m, REF_2, [{ entryId: twice, revision: 1, checks: [{ index: 0, type: 'path', state: 'missing' }] }]);
  expectStatus(broken, 200, 'the next check');
  assert.equal(broken.body.outcomes[0].challenged, true);
  assert.equal((await pushed(h, m)).has(twice), false);
  // Re-confirming what the machine wrote confirms it.
  const challenge = await theChallenge(h, m, twice);
  expectStatus(await decide(h, m, challenge.changesetId, { opId: challenge.opId, action: 'reconfirm' }), 200, 'the owner re-confirms');
  const confirmed = await entryRow(h, twice);
  assert.equal(confirmed.trust, 'confirmed');
  assert.deepEqual(confirmed.anchors, [], 'the anchor that went is dropped');
  assert.equal(confirmed.anchorState, 'unchecked', 'an entry with no anchor is unchecked');
  const sources = await h.prisma.wikiSource.count({ where: { revision: { entryId: twice, revision: confirmed.currentRevision } } });
  assert.equal(sources, 2, 'the owner\'s revision rests on the sources the entry rested on');
  assert.equal(confirmed.unsupported, false);
  assert.equal((await pushed(h, m)).has(twice), true, 'and it is pushed again');
});
