/**
 * The Wiki maintenance job (criterion 3; contracts/wiki.contract.json `maintenance.job`), against a real
 * PostgreSQL and over the runner door's real routes.
 *
 * What criterion 3's verification method asks, each read back from the rows the job wrote:
 *
 *   1. the threshold — twenty sessions with a fact after the cursor make the task, nineteen do not;
 *   2. the day — a fact arriving while the oldest pending fact is more than 24 hours old makes it, and the
 *      age alone, with no fact arriving, makes nothing;
 *   3. no new fact, no task — an event that names nothing new of the space (a session already taken in, the
 *      maintenance run's own session and task, another space's work) makes nothing, however due;
 *   4. one task at a time — a fact arriving while the maintenance task has not ended makes no second one,
 *      and the next fact after it ended makes the next;
 *   5. a truncated run does not move the cursor — it is one more consecutive failure, and its check fails;
 *   6. the circuit breaker — a maintenance run's changesets are one run to it: what the earlier ones
 *      changed through the mode is spent, so the run stops at ten percent of the active entries it began
 *      with, where the same ops in one changeset each would have passed;
 *
 * and beside them: the daily limit holds a due space and says so in its health; the task is made pinned,
 * at once, with `orbit wiki check --expect-cursor` as its one criterion; the run proposes as `maintenance`
 * and nobody else may; and the check passes only for a run that reached the position with no op refused.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-maintenance.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import {
  RunEventType,
  WIKI_MAINTENANCE_JOB,
  WIKI_MAINTENANCE_RULES,
  WIKI_REVIEW_RULES,
  toUuid,
  uuidToBase62,
  type NormalizedRunEvent,
} from '@orbit/shared';
import { Client } from 'pg';
import { Subject } from 'rxjs';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiMaintainController } from '../runner-api/runner-wiki-maintain.controller';
import { RunnerWikiMaintenanceController } from '../runner-api/runner-wiki-maintenance.controller';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiController } from './wiki.controller';
import { WikiMaintenance } from './wiki-maintenance';
import { considerWikiMaintenance, WikiMaintenanceTrigger, wikiMaintenanceHintFor, type WikiMaintenanceHint } from './wiki-maintenance-run';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  maintenance: WikiMaintenance;
  bearers: Map<string, string>;
  /** What the trigger's owner-scoped announcements said. */
  announced: Array<{ ownerId: string; type: string; change: unknown }>;
  published: Subject<{ runId: string; event: NormalizedRunEvent }>;
  trigger: WikiMaintenanceTrigger;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const announced: Harness['announced'] = [];
    const published = new Subject<{ runId: string; event: NormalizedRunEvent }>();
    const hub = {
      publishWikiChanged: () => undefined,
      publishForUser: (ownerId: string, type: string, change: unknown) => announced.push({ ownerId, type, change }),
      localPublications: () => published.asObservable(),
    } as unknown as RealtimeService;
    const push = {} as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);
    const maintenance = new WikiMaintenance(prisma as unknown as PrismaService);
    const trigger = new WikiMaintenanceTrigger(prisma as unknown as PrismaService, hub);
    trigger.onModuleInit();

    @Module({
      controllers: [WikiController, RunnerWikiController, RunnerWikiMaintenanceController, RunnerWikiMaintainController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiMaintenance, useValue: maintenance },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiMaintenanceJobModule {}

    const app = await NestFactory.create(WikiMaintenanceJobModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, maintenance, bearers, announced, published, trigger };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql, trigger } = await harness;
  trigger.onModuleDestroy();
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 600)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

const minutesAgo = (minutes: number): Date => new Date(Date.now() - minutes * 60_000);

/** A time as the UTC text Orbit's timestamp columns hold (see wiki-dossier.pg.spec.ts). */
const utc = (at: Date | null | undefined): string | null => (at ? at.toISOString() : null);

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-maintenance-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string, workDir: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env","work_dir") VALUES ($1,'spec',$2,'{}',$3)`, [id, ownerId, workDir]);
  return id;
}

async function session(
  h: Harness,
  ownerId: string,
  shape: { workspaceId: string; runnerId?: string | null; taskId?: string | null; status?: string; lastTurnAt?: Date },
): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","status","last_turn_at","dispatch_origin","created_at","updated_at")
     VALUES ($1,'a session','p',$2,$2,$3,$4,$5,$6::run_status,$7,'USER',$8,now())`,
    [id, ownerId, shape.workspaceId, shape.runnerId ?? null, shape.taskId ?? null, shape.status ?? 'SUCCEEDED',
      utc(shape.lastTurnAt ?? minutesAgo(30)), utc(minutesAgo(24 * 60 * 3))],
  );
  return id;
}

async function task(
  h: Harness,
  ownerId: string,
  shape: { status?: string; assigneeId?: string | null; listId?: string | null; updatedAt?: Date } = {},
): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id",
                         "completion_criterion","updated_at")
     VALUES ($1,'a task',$2,'USER',$2,$3::task_status,$4,$5,'OWNER_CONFIRMED',$6)`,
    [id, ownerId, shape.status ?? 'OPEN', shape.assigneeId ?? null, shape.listId ?? null, utc(shape.updatedAt ?? minutesAgo(20))],
  );
  return id;
}

async function turn(h: Harness, sessionId: string, content: string): Promise<string> {
  const id = randomUUID();
  const seq = (await h.sql.query<{ n: number }>(
    `SELECT COALESCE(MAX("seq"), 0)::int + 1 AS n FROM "conversation_turn" WHERE "session_id" = $1`, [sessionId],
  )).rows[0].n;
  await h.sql.query(
    `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status","kind","send_intent","created_at")
     VALUES ($1,$2,$3,$4,$5,'ANSWERED','message','NEXT_TURN',$6)`,
    [id, sessionId, seq, randomUUID(), content, utc(minutesAgo(40))],
  );
  return id;
}

interface Space {
  owner: Account;
  machine: { id: string; token: string };
  spaceId: string;
  workspaceId: string;
  listId: string;
}

/** A space bound to a workspace, its maintenance on and pinned to that workspace. */
async function maintainedSpace(h: Harness, name: string, settings: Record<string, unknown> = {}): Promise<Space> {
  const owner = await account(h, name);
  const machine = await runner(h, owner.id);
  const workspaceId = await workspace(h, owner.id, '~/orbit');
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: `${name} space`, repoUrl: `https://github.com/spec/${name}-${randomUUID().slice(0, 8)}` });
  expectStatus(made, 201, 'the owner creates a space');
  const spaceId = toUuid(made.body.id as string);
  expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/workspaces`, { workspaceId }), 200, 'the owner binds the workspace');
  const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, {
    maintenance: { enabled: true, workspaceId, provider: 'local-vllm', ...settings },
  });
  expectStatus(on, 200, 'the owner turns maintenance on');
  return { owner, machine, spaceId, workspaceId, listId: toUuid(on.body.settings.maintenance.listId as string) };
}

/** Sessions of the space that came to rest about `minutes` ago, each one fact: the first the oldest. */
async function settledSessions(h: Harness, s: Space, count: number, minutes = 30): Promise<string[]> {
  const ids: string[] = [];
  for (let n = 0; n < count; n += 1) {
    ids.push(await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(minutes + (count - n) / 10) }));
  }
  return ids;
}

const hintOf = (sessionIds: string[] = [], taskIds: string[] = []): WikiMaintenanceHint => ({ sessionIds, taskIds });

function consider(h: Harness, s: Space, hint: WikiMaintenanceHint) {
  return considerWikiMaintenance(h.prisma as unknown as PrismaService, s.owner.id, s.spaceId, hint);
}

async function maintenanceTasks(h: Harness, s: Space) {
  return (await h.sql.query<{
    id: string; status: string; assignee_id: string; provider: string; run_at: Date | null; completion_criterion: string;
    acceptance_command: string; acceptance_expected_exit_code: number; acceptance_timeout_seconds: number; title: string; description: string;
  }>(`SELECT "id","status","assignee_id","provider","run_at","completion_criterion","acceptance_command",
             "acceptance_expected_exit_code","acceptance_timeout_seconds","title","description"
        FROM "task" WHERE "list_id" = $1 ORDER BY "created_at"`, [s.listId])).rows;
}

async function cursorRow(h: Harness, s: Space) {
  return (await h.sql.query<{
    position_at: Date | null; consecutive_failures: number; last_outcome: string | null; held_reason: string | null; held_at: Date | null;
  }>(`SELECT "position_at","consecutive_failures","last_outcome","held_reason","held_at" FROM "wiki_cursor" WHERE "space_id" = $1`, [s.spaceId])).rows[0];
}

/** The maintenance task's own session, on the space's runner, as a claim would have made it. */
async function runSession(h: Harness, s: Space, taskId: string): Promise<string> {
  await h.sql.query(`UPDATE "task" SET "status" = 'IN_PROGRESS' WHERE "id" = $1`, [taskId]);
  return session(h, s.owner.id, { workspaceId: s.workspaceId, runnerId: s.machine.id, taskId, status: 'RUNNING', lastTurnAt: minutesAgo(1) });
}

/** Page the dossiers a run covers, from the cursor up to what its task expects, as `orbit wiki maintain` does. */
async function pageToExpected(h: Harness, s: Space, sessionId: string, expect: string): Promise<{ token: string; sessions: string[] }> {
  let after = '';
  const sessions: string[] = [];
  for (let n = 0; n < 100; n += 1) {
    const query = new URLSearchParams({ until: expect, limit: '5', ...(after ? { after } : {}) });
    const page = await call(h, { runner: s.machine.token, session: sessionId }, 'GET', `/runner/wiki/spaces/${s.spaceId}/dossiers?${query}`);
    expectStatus(page, 200, 'the run reads a page');
    for (const dossier of page.body.dossiers as Array<{ sessionId: string }>) sessions.push(toUuid(dossier.sessionId));
    after = page.body.cursor as string;
    if (!page.body.more) return { token: after, sessions };
  }
  throw new Error('the pages never ended');
}

function draft(title: string): Record<string, unknown> {
  return {
    kind: 'pitfall',
    title,
    summary: `What the space learned about ${title.toLowerCase()}.`,
    fields: {
      trigger: { paths: ['src/apiserver/src/wiki/'], commands: [] },
      symptom: 'A green run that witnessed no assertion.',
      cause: 'A pg spec skips itself without a database.',
      fix: 'Run it through scripts/run-pg-spec.sh.',
    },
  };
}

function adds(count: number, cite: string, prefix: string): Array<Record<string, unknown>> {
  return Array.from({ length: count }, (_unused, n) => ({
    op: 'add',
    entry: draft(`${prefix} pitfall ${n + 1} ${randomUUID().slice(0, 8)}`),
    sources: [{ kind: 'turn', ref: cite }],
  }));
}

/** `count` active entries written directly: what the circuit breaker measures a run against. */
async function activeEntries(h: Harness, s: Space, count: number): Promise<void> {
  for (let n = 0; n < count; n += 1) {
    await h.sql.query(
      `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields")
       VALUES ($1,$2,$3,'concept','active','auto',1,$4,'Already in the space before this run.','{}')`,
      [randomUUID(), s.owner.id, s.spaceId, `Standing entry number ${n + 1}`],
    );
  }
}

// ── 1. the threshold ─────────────────────────────────────────────────────────────────────────────

test('twenty sessions with a fact after the cursor make the task — pinned, at once, judged by its check', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'threshold');
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold - 1);
  // A session with several facts is one session: its task settled too, and its approval was answered.
  const busy = sessions[0]!;
  const settledTask = await task(h, s.owner.id, { status: 'CANCELLED', assigneeId: s.workspaceId, updatedAt: minutesAgo(25) });
  await h.sql.query(`UPDATE "session" SET "task_id" = $2 WHERE "id" = $1`, [busy, settledTask]);

  const nineteen = await consider(h, s, hintOf([sessions.at(-1)!]));
  assert.deepEqual(nineteen, { made: false, spaceId: s.spaceId, why: 'not_due' }, 'nineteen sessions are not due');
  assert.equal((await maintenanceTasks(h, s)).length, 0);

  const twentieth = await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(10) });
  const made = await consider(h, s, hintOf([twentieth]));
  assert.equal(made.made, true, `the twentieth session makes the task: ${JSON.stringify(made)}`);
  if (!made.made) return;
  assert.equal(made.due, 'backlog');
  assert.equal(made.runSessions, WIKI_MAINTENANCE_JOB.runSessionsMax, 'a space of no entries has no breaker to fit');

  const [row] = await maintenanceTasks(h, s);
  assert.ok(row, 'the task is in the space\'s hidden maintenance list');
  assert.equal(row.id, made.taskId);
  assert.equal(row.status, 'OPEN');
  assert.equal(row.assignee_id, s.workspaceId, 'pinned to the maintenance workspace');
  assert.equal(row.provider, 'local-vllm', 'pinned to the maintenance provider');
  // Read through Prisma: `run_at` is a timestamp without a zone, which pg would read as the host's local time.
  const { runAt } = await h.prisma.task.findUniqueOrThrow({ where: { id: row.id }, select: { runAt: true } });
  assert.ok(runAt && Math.abs(runAt.getTime() - Date.now()) < 60_000, `runAt is now: ${runAt?.toISOString()}`);
  assert.equal(row.title, 'Wiki maintenance: threshold space');
  assert.match(row.description, new RegExp(`orbit wiki maintain --space ${uuidToBase62(s.spaceId)}`));
  assert.equal(row.completion_criterion, 'EXECUTABLE');
  assert.equal(row.acceptance_command, `orbit wiki check --space ${uuidToBase62(s.spaceId)} --expect-cursor ${made.expect}`);
  assert.equal(row.acceptance_expected_exit_code, 0);
  assert.equal(row.acceptance_timeout_seconds, WIKI_MAINTENANCE_JOB.checkTimeoutSeconds);

  // The run row: why, and the position the check expects — the last fact of the twenty sessions.
  const run = await h.prisma.wikiMaintenanceRun.findUniqueOrThrow({ where: { taskId: made.taskId } });
  assert.equal(run.due, 'backlog');
  assert.equal(run.pendingSessions, WIKI_MAINTENANCE_RULES.backlogThreshold);
  assert.equal(run.expectKind, 'session_settled');
  assert.equal(run.expectRef, twentieth, 'the newest of the twenty is the last fact the run must cover');
  assert.equal(run.outcome, null);
});

test('a published event is the hint: the trigger takes it, and only a fact of the space makes the task', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'events');
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold);
  const event = (type: string): NormalizedRunEvent => ({ seq: 0, type, ts: new Date().toISOString(), payload: {} }) as NormalizedRunEvent;

  // What an event may name: a session's own events, and a user-scoped task change's tasks. Nothing else.
  assert.deepEqual(wikiMaintenanceHintFor(sessions[0]!, event(RunEventType.SESSION_UPDATED)),
    { ownerId: null, sessionIds: [sessions[0]!], taskIds: [] });
  assert.equal(wikiMaintenanceHintFor(sessions[0]!, event(RunEventType.TEXT_DELTA)), null, 'a streamed word is no fact');
  const change = { ...event(RunEventType.TASK_CHANGED), payload: { taskIds: [sessions[1]!], resync: false } } as NormalizedRunEvent;
  assert.deepEqual(wikiMaintenanceHintFor(`user:${s.owner.id}`, change), { ownerId: s.owner.id, sessionIds: [], taskIds: [sessions[1]!] });

  // Another owner's session is none of this space's facts.
  const stranger = await maintainedSpace(h, 'stranger');
  const theirs = (await settledSessions(h, stranger, 1))[0]!;
  await h.trigger.take(theirs, event(RunEventType.SESSION_UPDATED));
  await h.trigger.idle();
  assert.equal((await maintenanceTasks(h, s)).length, 0, "another owner's fact makes nothing here");

  // The subscription: the event goes out on the hub, and the task comes of it.
  h.published.next({ runId: sessions.at(-1)!, event: event(RunEventType.STATUS) });
  for (let waited = 0; waited < 100 && (await maintenanceTasks(h, s)).length === 0; waited += 1) {
    await new Promise((resolve) => setTimeout(resolve, 50));
    await h.trigger.idle();
  }
  const made = await maintenanceTasks(h, s);
  assert.equal(made.length, 1, 'the published event made the task');
  assert.ok(h.announced.some((a) => a.ownerId === s.owner.id && a.type === RunEventType.TASK_CHANGED
    && JSON.stringify(a.change).includes(made[0]!.id)), 'and the task was announced once it committed');
});

// ── 2. the day ───────────────────────────────────────────────────────────────────────────────────

test('a fact arriving while the oldest pending fact is a day old makes the task; the age alone makes nothing', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'age');
  const old = (await settledSessions(h, s, 1, 30 * 60))[0]!;
  const runs = () => h.prisma.wikiMaintenanceRun.count({ where: { spaceId: s.spaceId } });
  assert.equal(await runs(), 0);

  // Due by age — but an event that names no new fact is no arrival: the maintenance list's own task, a
  // session the space has no fact of.
  const own = await task(h, s.owner.id, { status: 'CANCELLED', listId: s.listId, updatedAt: minutesAgo(5) });
  assert.deepEqual(await consider(h, s, hintOf([], [own])), { made: false, spaceId: s.spaceId, why: 'no_new_fact' },
    "the maintenance list's own task is no fact");
  const running = await session(h, s.owner.id, { workspaceId: s.workspaceId, status: 'RUNNING' });
  assert.deepEqual(await consider(h, s, hintOf([running])), { made: false, spaceId: s.spaceId, why: 'no_new_fact' },
    'a session still running has not come to rest');
  assert.equal(await runs(), 0, 'the age alone made nothing');

  // A task of the space settles: a new fact, and the oldest pending one is thirty hours old.
  const settled = await task(h, s.owner.id, { status: 'CANCELLED', assigneeId: s.workspaceId, updatedAt: minutesAgo(4) });
  const made = await consider(h, s, hintOf([], [settled]));
  assert.equal(made.made, true, `a new fact on a day-old backlog makes the task: ${JSON.stringify(made)}`);
  if (!made.made) return;
  assert.equal(made.due, 'age');
  const run = await h.prisma.wikiMaintenanceRun.findUniqueOrThrow({ where: { taskId: made.taskId } });
  assert.equal(run.due, 'age');
  assert.ok(run.oldestPendingAt && run.oldestPendingAt.getTime() <= minutesAgo(29 * 60).getTime());
  // The two facts are both past the grace, so the run covers both: the task's, being the later, is the last.
  assert.equal(run.expectKind, 'task_terminal');
  assert.equal(run.expectRef, settled);
  assert.ok(old);
});

// ── 3. no new fact, no task ──────────────────────────────────────────────────────────────────────

test('no new fact makes no task, however due: nothing pending, a fact already taken in, the run\'s own work', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'nofact');
  // Nothing at all.
  assert.deepEqual(await consider(h, s, hintOf()), { made: false, spaceId: s.spaceId, why: 'no_new_fact' });
  const lone = await session(h, s.owner.id, { workspaceId: s.workspaceId, status: 'RUNNING' });
  assert.deepEqual(await consider(h, s, hintOf([lone])), { made: false, spaceId: s.spaceId, why: 'no_new_fact' });

  // Twenty sessions, taken in by a run that advanced past them: an event about one of them afterwards —
  // a rename — is about a fact the wiki already has.
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold);
  const made = await consider(h, s, hintOf([sessions[0]!]));
  assert.equal(made.made, true);
  if (!made.made) return;
  const runner1 = await runSession(h, s, made.taskId);
  const { token } = await pageToExpected(h, s, runner1, made.expect);
  const finished = await call(h, { runner: s.machine.token, session: runner1 }, 'POST', `/runner/wiki/spaces/${s.spaceId}/maintenance/finish`, {
    to: token,
    outcome: 'succeeded',
    report: { ops: { refused: 0 }, tokens: { input: 0, output: 0, calls: 0 } },
  });
  expectStatus(finished, 200, 'the run ends');
  assert.equal(finished.body.advanced, true);
  await h.sql.query(`UPDATE "task" SET "status" = 'CANCELLED' WHERE "id" = $1`, [made.taskId]);
  await h.sql.query(`UPDATE "session" SET "status" = 'SUCCEEDED', "last_turn_at" = $2 WHERE "id" = $1`, [runner1, utc(minutesAgo(1))]);

  assert.deepEqual(await consider(h, s, hintOf([sessions[3]!])), { made: false, spaceId: s.spaceId, why: 'no_new_fact' },
    'a fact behind the cursor is no new fact');
  // The run's own session and task are not facts either, now that they have ended.
  assert.deepEqual(await consider(h, s, hintOf([runner1], [made.taskId])), { made: false, spaceId: s.spaceId, why: 'no_new_fact' },
    'the maintenance run feeds nothing to its own backlog');
  assert.equal((await maintenanceTasks(h, s)).length, 1, 'still the one task');

  // And a new fact that is not due makes nothing either.
  const next = await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(5) });
  assert.deepEqual(await consider(h, s, hintOf([next])), { made: false, spaceId: s.spaceId, why: 'not_due' });
});

// ── 4. one task at a time ────────────────────────────────────────────────────────────────────────

test('a fact arriving while the maintenance task has not ended makes no second one; the next one after it does', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'unfinished');
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold);
  await h.maintenance.cursorState(s.owner.id, s.spaceId);
  // Two facts arriving together: one task between them.
  const both = await Promise.all([consider(h, s, hintOf([sessions[0]!])), consider(h, s, hintOf([sessions[1]!]))]);
  assert.equal(both.filter((outcome) => outcome.made).length, 1, `one of the two made the task: ${JSON.stringify(both)}`);
  assert.equal((await maintenanceTasks(h, s)).length, 1);
  const first = (await maintenanceTasks(h, s))[0]!;

  for (const status of ['OPEN', 'IN_PROGRESS']) {
    await h.sql.query(`UPDATE "task" SET "status" = $2::task_status WHERE "id" = $1`, [first.id, status]);
    const more = await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(8) });
    assert.deepEqual(await consider(h, s, hintOf([more])), { made: false, spaceId: s.spaceId, why: 'unfinished' },
      `a task ${status} is the run this fact waits for`);
  }
  assert.equal((await maintenanceTasks(h, s)).length, 1, 'no second task');

  // It ended (failed, say): the next fact makes the next task, from the same cursor.
  await h.sql.query(`UPDATE "task" SET "status" = 'FAILED' WHERE "id" = $1`, [first.id]);
  const after = await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(6) });
  const second = await consider(h, s, hintOf([after]));
  assert.equal(second.made, true, `the next fact after it ended makes the next task: ${JSON.stringify(second)}`);
  assert.equal((await maintenanceTasks(h, s)).length, 2);
});

// ── the day's limit, in the health ───────────────────────────────────────────────────────────────

test('a due space whose runs for the day are used up makes none, and says so in its health until one is made', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'limit', { dailyRunLimit: 1 });
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold);
  const first = await consider(h, s, hintOf([sessions[0]!]));
  assert.equal(first.made, true);
  if (!first.made) return;
  await h.sql.query(`UPDATE "task" SET "status" = 'FAILED' WHERE "id" = $1`, [first.taskId]);

  const next = await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(5) });
  assert.deepEqual(await consider(h, s, hintOf([next])), { made: false, spaceId: s.spaceId, why: 'daily_limit_reached' });
  assert.equal((await maintenanceTasks(h, s)).length, 1, 'no second task today');
  const held = await cursorRow(h, s);
  assert.equal(held.held_reason, 'daily_limit_reached');
  const heldAt = held.held_at!.getTime();
  const state = await h.maintenance.cursorState(s.owner.id, s.spaceId);
  assert.deepEqual(state.held, { reason: 'daily_limit_reached', at: new Date(heldAt).toISOString() }, 'the health says why');
  // A later fact held for the same reason keeps the time it first held.
  const later = await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(4) });
  assert.equal((await consider(h, s, hintOf([later]))).made, false);
  assert.equal((await cursorRow(h, s)).held_at!.getTime(), heldAt);

  // The owner raises the limit: the next fact makes the task, and the health is clear again.
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'PATCH', `/wiki/spaces/${s.spaceId}`, { maintenance: { dailyRunLimit: 2 } }), 200, 'raise the limit');
  const again = await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(3) });
  assert.equal((await consider(h, s, hintOf([again]))).made, true);
  assert.equal((await cursorRow(h, s)).held_reason, null, 'made: held no more');
  assert.equal((await h.maintenance.cursorState(s.owner.id, s.spaceId)).held, null);
});

test('a Manual space whose review queue has no room is held too, and a run of one is sized to what it can leave waiting', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'manual');
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'PATCH', `/wiki/spaces/${s.spaceId}`, { reviewMode: 'manual' }), 200, 'manual');
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold);
  const made = await consider(h, s, hintOf([sessions[0]!]));
  assert.equal(made.made, true);
  if (!made.made) return;
  assert.equal(made.runSessions, 2, 'fifteen ops a session may leave waiting, six entries a session: two sessions');
  const run = await h.prisma.wikiMaintenanceRun.findUniqueOrThrow({ where: { taskId: made.taskId } });
  assert.equal(run.expectRef, sessions[1], 'the run covers the two oldest sessions');
  await h.sql.query(`UPDATE "task" SET "status" = 'CANCELLED' WHERE "id" = $1`, [made.taskId]);

  // Thirty proposals wait for the owner: no room for even one session's.
  const proposer = await session(h, s.owner.id, { workspaceId: s.workspaceId, runnerId: s.machine.id, status: 'RUNNING' });
  const cite = await turn(h, proposer, 'a record to cite');
  for (let batch = 0; batch < 6; batch += 1) {
    const other = await session(h, s.owner.id, { workspaceId: s.workspaceId, runnerId: s.machine.id, status: 'RUNNING' });
    const answer = await call(h, { runner: s.machine.token, session: other }, 'POST', '/runner/wiki/changesets', {
      ops: adds(5, cite, `queue ${batch}`), rationale: 'fill the review queue', idempotencyKey: randomUUID(),
    });
    expectStatus(answer, 200, 'an agent fills the queue');
  }
  const next = await session(h, s.owner.id, { workspaceId: s.workspaceId, lastTurnAt: minutesAgo(5) });
  assert.deepEqual(await consider(h, s, hintOf([next])), { made: false, spaceId: s.spaceId, why: 'review_queue_full' });
  assert.equal((await cursorRow(h, s)).held_reason, 'review_queue_full');
});

// ── 5. a truncated run does not move the cursor ──────────────────────────────────────────────────

test('a run cut short by its turn limit moves nothing, counts one more failure, and its check fails', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'truncated');
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold);
  const made = await consider(h, s, hintOf([sessions[0]!]));
  assert.equal(made.made, true);
  if (!made.made) return;
  const run = await runSession(h, s, made.taskId);
  const context = await call(h, { runner: s.machine.token, session: run }, 'GET', `/runner/wiki/spaces/${s.spaceId}/maintenance/run`);
  expectStatus(context, 200, 'the run reads where it starts');
  assert.equal(context.body.expect, made.expect, 'it is told the position its task expects');
  await pageToExpected(h, s, run, made.expect);

  // What the runner says on the cursor route when the CLI ends the turn with error_max_turns.
  const truncated = await call(h, { runner: s.machine.token, session: run }, 'POST', `/runner/wiki/spaces/${s.spaceId}/cursor`, {
    outcome: 'truncated',
    error: 'the run reached its limit of 120 model turns and was cut short, so it failed and moved nothing',
  });
  expectStatus(truncated, 200, 'a truncated run is recorded');
  assert.equal(truncated.body.advanced, false);
  const cursor = await cursorRow(h, s);
  assert.equal(cursor.position_at, null, 'the cursor did not move');
  assert.equal(cursor.consecutive_failures, 1);
  assert.equal(cursor.last_outcome, 'truncated');
  const row = await h.prisma.wikiMaintenanceRun.findUniqueOrThrow({ where: { taskId: made.taskId } });
  assert.equal(row.outcome, 'truncated', "the run's row says how it ended");
  assert.equal(toUuid(row.sessionId!), run);

  const check = await call(h, { runner: s.machine.token }, 'GET', `/runner/wiki/spaces/${s.spaceId}/maintenance/check?expect=${encodeURIComponent(made.expect)}`);
  expectStatus(check, 200, 'the check answers the runner with no session');
  assert.equal(check.body.ok, false);
  assert.equal(check.body.reached, false);
  assert.ok((check.body.problems as string[]).some((p) => /cursor has never moved/u.test(p)));
  assert.ok((check.body.problems as string[]).some((p) => /ended truncated/u.test(p)));
});

// ── 6. the circuit breaker over a run ────────────────────────────────────────────────────────────

test('the circuit breaker counts a whole maintenance run: its changesets stop at 10% of what it began with', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'breaker');
  await activeEntries(h, s, WIKI_REVIEW_RULES.breakerMinActiveEntries);
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold);
  const cite = await turn(h, sessions[0]!, 'the record every proposal of this run cites');
  const made = await consider(h, s, hintOf([sessions[0]!]));
  assert.equal(made.made, true);
  if (!made.made) return;
  assert.equal(made.runSessions, 1, 'a hundred active entries at six entries a session: a run of one session');
  const run = await runSession(h, s, made.taskId);
  const propose = (ops: unknown[], dryRun = false) => call(h, { runner: s.machine.token, session: run }, 'POST',
    `/runner/wiki/spaces/${s.spaceId}/maintenance/changesets`, { ops, rationale: 'what the run learned', idempotencyKey: randomUUID(), dryRun });

  // Eight adds the Tiered mode applies: eight of the hundred.
  const first = await propose(adds(8, cite, 'first'));
  expectStatus(first, 200, 'the first changeset is recorded');
  assert.deepEqual((first.body.ops as Array<{ status: string }>).map((op) => op.status), Array(8).fill('applied'));
  const origin = await h.sql.query<{ origin: string }>(`SELECT "origin" FROM "wiki_changeset" WHERE "id" = $1`, [toUuid(first.body.changesetId)]);
  assert.equal(origin.rows[0]!.origin, 'maintenance', 'a maintenance run proposes as maintenance');

  // Five more: the space holds 108 active entries now, and five is nowhere near a changeset's 10% of them —
  // but the run began with 100, and has changed eight: the ninth and tenth pass, the eleventh trips.
  const second = await propose(adds(5, cite, 'second'));
  expectStatus(second, 200, 'what fits is recorded');
  const statuses = (second.body.ops as Array<{ status: string; reasons?: Array<{ code: string; message: string }> }>);
  assert.deepEqual(statuses.map((op) => op.status), ['applied', 'applied', 'refused', 'refused', 'refused']);
  assert.equal(statuses[2]!.reasons![0]!.code, 'WIKI_QUOTA');
  assert.match(statuses[2]!.reasons![0]!.message, /circuit breaker: this Wiki maintenance run has already changed 10 of the 100 entries/u);
  // A dry run of the same says the same, before anything is recorded.
  const dry = await propose(adds(1, cite, 'dry'), true);
  assert.equal((dry.body.ops as Array<{ status: string }>)[0]!.status, 'refused', 'the run is spent');

  // The run stops: it ends failed, the cursor stays, and its check fails.
  const { token } = await pageToExpected(h, s, run, made.expect);
  const failed = await call(h, { runner: s.machine.token, session: run }, 'POST', `/runner/wiki/spaces/${s.spaceId}/maintenance/finish`, {
    to: token,
    outcome: 'failed',
    error: 'circuit breaker: the run would change more than 10% of the active entries',
    report: { stoppedAt: 'propose', ops: { proposed: 13, recorded: 10, refused: 3 }, tokens: { input: 1, output: 1, calls: 1 } },
  });
  expectStatus(failed, 200, 'a failed run is recorded');
  assert.equal(failed.body.advanced, false);
  const cursor = await cursorRow(h, s);
  assert.equal(cursor.position_at, null, 'a tripped run moves no cursor');
  assert.equal(cursor.consecutive_failures, 1);
  const row = await h.prisma.wikiMaintenanceRun.findUniqueOrThrow({ where: { taskId: made.taskId } });
  assert.equal(row.outcome, 'failed');
  assert.equal(row.opsRefused, 3);
  const check = await call(h, { runner: s.machine.token }, 'GET', `/runner/wiki/spaces/${s.spaceId}/maintenance/check?expect=${encodeURIComponent(made.expect)}`);
  assert.equal(check.body.ok, false);

  // Below a hundred active entries there is no breaker: a space's first batch goes in whole.
  const young = await maintainedSpace(h, 'young');
  await activeEntries(h, young, WIKI_REVIEW_RULES.breakerMinActiveEntries - 1);
  const youngSessions = await settledSessions(h, young, WIKI_MAINTENANCE_RULES.backlogThreshold);
  const youngCite = await turn(h, youngSessions[0]!, 'a record');
  const youngTask = await consider(h, young, hintOf([youngSessions[0]!]));
  assert.equal(youngTask.made, true);
  if (!youngTask.made) return;
  const youngRun = await runSession(h, young, youngTask.taskId);
  for (const prefix of ['one', 'two']) {
    const answer = await call(h, { runner: young.machine.token, session: youngRun }, 'POST', `/runner/wiki/spaces/${young.spaceId}/maintenance/changesets`,
      { ops: adds(12, youngCite, prefix), rationale: 'the first batch', idempotencyKey: randomUUID() });
    expectStatus(answer, 200, 'no breaker below a hundred');
    assert.deepEqual((answer.body.ops as Array<{ status: string }>).map((op) => op.status), Array(12).fill('applied'));
  }
});

// ── the check, and who may run ───────────────────────────────────────────────────────────────────

test('the check passes a run that reached its position with no op refused, and nothing else; only the run proposes', { skip }, async () => {
  const h = await boot();
  const s = await maintainedSpace(h, 'check');
  const sessions = await settledSessions(h, s, WIKI_MAINTENANCE_RULES.backlogThreshold);
  const cite = await turn(h, sessions[0]!, 'what the owner said');
  const made = await consider(h, s, hintOf([sessions[0]!]));
  assert.equal(made.made, true);
  if (!made.made) return;
  const run = await runSession(h, s, made.taskId);
  const route = (path: string) => `/runner/wiki/spaces/${s.spaceId}/maintenance/${path}`;

  // Nobody but the run starts, proposes to or ends it.
  const other = await session(h, s.owner.id, { workspaceId: s.workspaceId, runnerId: s.machine.id, status: 'RUNNING' });
  for (const [method, path, body] of [['GET', 'run', undefined], ['POST', 'changesets', { ops: adds(1, cite, 'x'), rationale: 'r' }],
    ['POST', 'finish', { outcome: 'failed', error: 'e' }]] as const) {
    const refused = await call(h, { runner: s.machine.token, session: other }, method, route(path), body);
    expectStatus(refused, 403, `another session of the owner may not ${method} ${path}`);
    assert.equal(refused.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
    expectStatus(await call(h, { runner: s.machine.token }, method, route(path), body), 400, `a headless ${method} ${path} is refused`);
  }
  const stranger = await maintainedSpace(h, 'check-stranger');
  expectStatus(await call(h, { runner: stranger.machine.token }, 'GET', `${route('check')}?expect=${encodeURIComponent(made.expect)}`), 404,
    "another owner's runner meets a 404");
  const otherCheck = await call(h, { runner: s.machine.token, session: other }, 'GET', `${route('check')}?expect=${encodeURIComponent(made.expect)}`);
  expectStatus(otherCheck, 403, 'a session that is not the run may not check through it');

  // The run: where it starts, its proposal, its dossiers, its end.
  const context = await call(h, { runner: s.machine.token, session: run }, 'GET', route('run'));
  expectStatus(context, 200, 'the run reads where it starts');
  assert.equal(context.body.expect, made.expect);
  assert.equal(context.body.reviewMode, 'tiered');
  assert.equal(context.body.workspace.workDir, '~/orbit', 'the work directory as stored: the runner expands ~');
  assert.equal(context.body.runSessions, WIKI_MAINTENANCE_JOB.runSessionsMax);
  assert.ok((context.body.topics as unknown[]).length > 0, 'the topics an entry may name');
  const started = await h.prisma.wikiMaintenanceRun.findUniqueOrThrow({ where: { taskId: made.taskId } });
  assert.equal(started.sessionId, run, 'the run is recorded as started by its session');

  const proposed = await call(h, { runner: s.machine.token, session: run }, 'POST', route('changesets'),
    { ops: adds(2, cite, 'checked'), rationale: 'what the run learned', idempotencyKey: randomUUID() });
  expectStatus(proposed, 200, 'the run proposes');
  const { token, sessions: covered } = await pageToExpected(h, s, run, made.expect);
  assert.equal(covered.length, WIKI_MAINTENANCE_RULES.backlogThreshold, 'the pages up to the expected position cover the twenty sessions');

  // Before it ends, the check fails: the cursor has not moved.
  const early = await call(h, { runner: s.machine.token }, 'GET', `${route('check')}?expect=${encodeURIComponent(made.expect)}`);
  assert.equal(early.body.ok, false);

  const ended = await call(h, { runner: s.machine.token, session: run }, 'POST', route('finish'), {
    to: token,
    outcome: 'succeeded',
    report: { sessions: 20, ops: { proposed: 2, recorded: 2, refused: 0 }, tokens: { input: 1200, output: 300, calls: 20 }, seconds: 42 },
  });
  expectStatus(ended, 200, 'the run ends');
  assert.equal(ended.body.advanced, true, 'a succeeded run moves the cursor to its token');
  const passed = await call(h, { runner: s.machine.token }, 'GET', `${route('check')}?expect=${encodeURIComponent(made.expect)}`);
  expectStatus(passed, 200, 'the check answers');
  assert.equal(passed.body.ok, true, `the run passes its check: ${JSON.stringify(passed.body)}`);
  assert.equal(passed.body.reached, true);
  assert.deepEqual(passed.body.problems, []);
  const row = await h.prisma.wikiMaintenanceRun.findUniqueOrThrow({ where: { taskId: made.taskId } });
  assert.equal(row.outcome, 'succeeded');
  assert.equal(row.opsRefused, 0);
  assert.deepEqual((row.report as { tokens: unknown }).tokens, { input: 1200, output: 300, calls: 20 }, 'the token spend is kept with the run');

  // The same run, had the server refused two of its ops, does not pass.
  await h.prisma.wikiMaintenanceRun.update({ where: { taskId: made.taskId }, data: { opsRefused: 2 } });
  const refused = await call(h, { runner: s.machine.token }, 'GET', `${route('check')}?expect=${encodeURIComponent(made.expect)}`);
  assert.equal(refused.body.ok, false);
  assert.deepEqual(refused.body.problems, ["The server refused 2 of the run's ops."]);
  // Nor one that said nothing of its ops.
  await h.prisma.wikiMaintenanceRun.update({ where: { taskId: made.taskId }, data: { opsRefused: null } });
  assert.equal((await call(h, { runner: s.machine.token }, 'GET', `${route('check')}?expect=${encodeURIComponent(made.expect)}`)).body.ok, false);
  // A token no task expects: the cursor is past it, and still no run vouches for it.
  const behind = await call(h, { runner: s.machine.token }, 'GET', `${route('check')}?expect=${encodeURIComponent(context.body.expect)}x`);
  expectStatus(behind, 400, 'a token that does not decode is refused');
  assert.equal(behind.body.code, 'WIKI_CURSOR_INVALID');
});
