/**
 * A verification has to be able to read its evidence (criterion 7, revision 4; contracts/wiki.contract.json
 * `reviewModes.verification.evidence`, `.reopen`, `reviewModes.entryConfirm` and `floors.taintedWaits`),
 * over real HTTP and against a real PostgreSQL.
 *
 *   1. a tool call, a tool result — a string or blocks — a thinking and a system event's words reach the
 *      verifier as text, redacted and cut, and the quote a submission cites is checked against that same
 *      text; an empty thinking and a system event's counts are nothing to read, and an op none of whose
 *      sources has text is listed as having no readable evidence;
 *   2. a verdict about records nobody could read leaves its op no more than Unreviewed — whatever the
 *      verifier said, enforced by the server — a duplicate still adds its sources, and none of it
 *      counts toward the fallback to Tiered;
 *   3. in Automatic a tainted op is verified instead of queued, never more than Unreviewed, pushed to
 *      nobody and invisible to an agent's search and get, and takes no place in the 30-op queue; the
 *      owner's Confirm (their door alone) makes it confirmed, a revision of theirs, and pushed; its
 *      duplicate changes nothing about the entry it names; Manual and Tiered still hold it for the owner;
 *   4. the reopening: an op an unsupported verdict rejected when the reader of the time could read
 *      none of its sources waits for its verification again, the earlier verdict kept in its history
 *      and gone from the neighbours' hints; and a tainted op an automatic space holds for the owner is
 *      sent to its verification.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-verify-evidence.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in `wiki-verify.pg.spec.ts`; the push is
 * the real `appendWikiContext`, and the owner's notifications stand-ins that record each call.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { Prisma, PrismaClient } from '@prisma/client';
import { WIKI_LIMITS, WIKI_REVIEW_RULES, toUuid, type WikiKind } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import type { RealtimeService } from '../realtime/realtime.service';
import { WikiController } from './wiki.controller';
import { appendWikiContext } from './wiki-push';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The push as a session starting now would be handed it: the wiki on, whatever this shell says. */
const WIKI_ON = { mode: 'on' as const, canaryOwners: new Set<string>(), problems: [] };

type Mode = 'manual' | 'tiered' | 'automatic';

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  service: WikiService;
  bearers: Map<string, string>;
  /** Every notification that a space's verification sent it back to Tiered, in order. */
  fellBack: Array<{ ownerId: string; spaceId: string; unsupported: number; window: number }>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const fellBack: Harness['fellBack'] = [];
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const push = {
      notifyWikiVerificationTripped: async (input: Harness['fellBack'][number]) => {
        fellBack.push({ ownerId: input.ownerId, spaceId: input.spaceId, unsupported: input.unsupported, window: input.window });
      },
      notifyWikiReviewModeTripped: async () => undefined,
    } as unknown as PushService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, push);

    @Module({
      controllers: [WikiController, RunnerWikiController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiVerifyEvidenceModule {}

    const app = await NestFactory.create(WikiVerifyEvidenceModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, service, bearers, fellBack };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  headers?: Record<string, string>;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json', ...(who.headers ?? {}) };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

interface Outcome {
  seq: number;
  status: 'pending' | 'applied' | 'conflict' | 'refused';
  opId?: string | null;
  entryId?: string | null;
  waitsFor?: string;
  reasons?: Array<{ code: string; message: string }>;
  similar?: Array<{ id: string; status?: string; rejectedReason?: string; rejectedBecause?: string }>;
}

interface VerificationItem {
  opId: string;
  op: 'add' | 'amend';
  entry: { kind: string; title: string; summary: string };
  sources: Array<{ kind: string; ref: string; quote: string | null; text: string | null; truncated: boolean }>;
  evidence: 'readable' | 'unreadable';
  similar: Array<{ id: string; title: string; status: string; rejectedReason?: string; rejectedBecause?: string }>;
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-evidence-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return token;
}

async function runnerId(h: Harness, token: string): Promise<string> {
  const row = await h.sql.query<{ id: string }>(`SELECT "id" FROM "runner" WHERE "token_hash" = $1`, [
    createHash('sha256').update(token).digest('hex'),
  ]);
  return row.rows[0].id;
}

async function workspace(h: Harness, ownerId: string, env: Record<string, string> = {}): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","env") VALUES ($1,'spec',$2,$3)`, [id, ownerId, JSON.stringify(env)]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string | null, machine: string | null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "dispatch_origin","updated_at")
     VALUES ($1,'a wiki session','p',$2,$2,$3,$4,'USER',now())`,
    [id, ownerId, workspaceId, machine ? await runnerId(h, machine) : null],
  );
  return id;
}

async function toolCall(h: Harness, sessionId: string, name: string, output: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "tool_call"("id","session_id","name","output") VALUES ($1,$2,$3,$4)`, [
    id,
    sessionId,
    name,
    JSON.stringify(output),
  ]);
  return id;
}

/** One run event of a session, in the payload shapes the runner stores (run_event.payload). */
async function event(h: Harness, sessionId: string, type: string, payload: Record<string, unknown>): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "run_event"("id","session_id","seq","type","payload")
     VALUES ($1,$2,(SELECT COALESCE(MAX("seq"), 0) + 1 FROM "run_event" WHERE "session_id" = $2),$3,$4)`,
    [id, sessionId, type, JSON.stringify(payload)],
  );
  return id;
}

/** A space the owner makes through the door and puts in a mode, bound to a workspace when one is named. */
async function modeSpace(h: Harness, owner: Account, mode: Mode, workspaceId?: string): Promise<string> {
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title: `A ${mode} space` });
  expectStatus(made, 201, 'the owner creates a space');
  const id = made.body.id as string;
  await setMode(h, owner, toUuid(id), mode);
  if (workspaceId) {
    const bound = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${id}/workspaces`, { workspaceId });
    expectStatus(bound, 200, 'the owner binds the workspace');
  }
  return toUuid(id);
}

async function setMode(h: Harness, owner: Account, spaceId: string, mode: Mode): Promise<void> {
  const switched = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { reviewMode: mode });
  expectStatus(switched, 200, `the owner puts the space in ${mode}`);
}

/** A valid pitfall, retitled per use. */
function pitfall(title: string, summary = `What the space knows about ${title.toLowerCase()}.`): Record<string, unknown> {
  return {
    kind: 'pitfall' satisfies WikiKind,
    title,
    summary,
    fields: {
      trigger: { paths: ['scripts/release.sh'], commands: ['bash scripts/release.sh next'] },
      symptom: 'A tag is pushed before anybody looked at it.',
      cause: 'The script is not a dry run.',
      fix: 'Read the script before running it.',
    },
  };
}

/** The principal a one-off import in the API server's container runs as (reviewModes.verification.who.import). */
function importer(ownerId: string): WikiPrincipal {
  return { origin: 'import', ownerId, userId: null, sessionId: null, toolCallId: null, authorKind: 'system' };
}

/** The proposing session, as the runner door's verification path knows it. */
function agent(ownerId: string, sessionId: string): WikiPrincipal {
  return { origin: 'agent', ownerId, userId: null, sessionId, toolCallId: null };
}

function verdict(opId: string, value: string, over: Record<string, unknown> = {}): Record<string, unknown> {
  return { opId, verdict: value, reason: `The records ${value === 'unsupported' ? 'do not say this' : 'were read'}.`, model: 'qwen3.8-27b-fp8', ...over };
}

async function entryRow(h: Harness, id: string) {
  return h.prisma.wikiEntry.findFirstOrThrow({ where: { id: toUuid(id) } });
}

async function opRow(h: Harness, id: string) {
  return h.prisma.wikiChangesetOp.findFirstOrThrow({ where: { id: toUuid(id) } });
}

/** The live sources of an entry's current revision. */
async function liveSources(h: Harness, entryId: string): Promise<number> {
  const entry = await entryRow(h, entryId);
  const revision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: entry.id, revision: entry.currentRevision } });
  return h.prisma.wikiSource.count({ where: { revisionId: revision.id, state: 'live' } });
}

/** The entries the next session in this workspace is handed, by id. */
async function pushed(h: Harness, ownerId: string, workspaceId: string, sessionId: string): Promise<Set<string>> {
  const content = await appendWikiContext(h.prisma as unknown as Prisma.TransactionClient, {
    sessionId,
    turnId: randomUUID(),
    leaseGeneration: randomUUID(),
    ownerId,
    workspaceId,
    taskId: null,
    task: null,
    dispatchOrigin: 'USER',
    content: 'What should I know about this codebase?',
  }, WIKI_ON);
  return new Set([...String(content).matchAll(/\(orbit-wiki:([0-9A-Za-z]+)\)/gu)].map((match) => toUuid(match[1])));
}

/** What an agent's wiki_search returns, by id. */
async function agentFinds(h: Harness, who: Caller, q: string): Promise<Set<string>> {
  const answer = await call(h, who, 'GET', `/runner/wiki/search?q=${encodeURIComponent(q)}`);
  expectStatus(answer, 200, 'an agent\'s search');
  return new Set((answer.body.hits as Array<{ id: string }>).map((hit) => toUuid(hit.id)));
}

/** What the owner's own search returns in one space, by id. */
async function ownerFinds(h: Harness, owner: Account, spaceId: string, q: string): Promise<Set<string>> {
  const answer = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/search?space=${spaceId}&q=${encodeURIComponent(q)}`);
  expectStatus(answer, 200, 'the owner\'s search');
  return new Set((answer.body.hits as Array<{ id: string }>).map((hit) => toUuid(hit.id)));
}

/** What the verification list hands the calling session, every page of it. */
async function listed(h: Harness, who: Caller, spaceId: string): Promise<VerificationItem[]> {
  const items: VerificationItem[] = [];
  let after: string | null = null;
  for (let page = 0; page < 50; page += 1) {
    const answer = await call(h, who, 'GET', `/runner/wiki/spaces/${spaceId}/verifications?limit=5${after ? `&after=${after}` : ''}`);
    expectStatus(answer, 200, 'the verification list');
    items.push(...(answer.body.items as VerificationItem[]));
    after = answer.body.next;
    if (!after) return items;
  }
  throw new Error('the verification list never ended');
}

async function propose(h: Harness, who: Caller, ops: unknown[], rationale = 'what the records say'): Promise<Outcome[]> {
  const answer = await call(h, who, 'POST', '/runner/wiki/changesets', { rationale, ops, idempotencyKey: `evidence-${randomUUID()}` });
  expectStatus(answer, 200, rationale);
  return answer.body.ops as Outcome[];
}

// ── 1. what a verifier reads ────────────────────────────────────────────────────────────────────

test('evidence · a tool call, a tool result and a thinking reach the verifier as text, and the quote check reads the same', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'evidence-text');
  const machine = await runner(h, owner.id);
  const literal = 'wiki-evidence-literal-9f3c2a71';
  const ws = await workspace(h, owner.id, { DEPLOY_SECRET: literal });
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const toolUse = await event(h, records, 'tool_use', {
    id: 'toolu_01', name: 'Bash', input: { command: 'bash scripts/release.sh next', description: 'Cut the next release' },
  });
  const toolResult = await event(h, records, 'tool_result', {
    toolUseId: 'toolu_01', isError: false, content: 'Tagged v0.1.196 and pushed the tag: release.sh next is not a dry run',
  });
  const blocks = await event(h, records, 'tool_result', {
    toolUseId: 'toolu_02',
    isError: false,
    content: [
      { type: 'text', text: 'The first block of the result' },
      { type: 'image', source: { type: 'base64', media_type: 'image/png', data: 'AAAA' } },
      { type: 'text', text: 'The second block says the index is missing' },
    ],
  });
  const failed = await event(h, records, 'tool_result', { toolUseId: 'toolu_03', isError: true, content: 'permission denied: /var/lib/orbit' });
  const thought = await event(h, records, 'thinking', { text: 'The script tags before it asks anything, so next is not a dry run.' });
  const emptyThought = await event(h, records, 'thinking', { text: '' });
  const counts = await event(h, records, 'system', { subtype: 'context', contextTokens: 51234 });
  const summary = await event(h, records, 'system', { subtype: 'compact_summary', text: 'So far: the release script tags at once.' });
  const long = await event(h, records, 'tool_result', {
    toolUseId: 'toolu_04',
    content: `Authorization: Bearer abcdefghijklmnopqrstuvwx0123 and ${literal} ${'x'.repeat(9_000)} the end of the output`,
  });
  const proposer = await session(h, owner.id, ws, machine);
  const mine = { runner: machine, headers: { 'x-orbit-session-id': proposer } };
  const ev = (ref: string, quote?: string) => ({ kind: 'event', ref, ...(quote ? { quote } : {}) });

  const outcomes = await propose(h, mine, [
    { op: 'add', entry: pitfall('The release script tags at once'), sources: [ev(toolUse, 'release.sh next'), ev(toolResult, 'is not a dry run')] },
    { op: 'add', entry: pitfall('The index is missing after a restore'), sources: [ev(blocks, 'the index is missing')] },
    { op: 'add', entry: pitfall('Permission denied under the orbit state directory'), sources: [ev(failed, 'permission denied')] },
    { op: 'add', entry: pitfall('Next is not a dry run'), sources: [ev(thought, 'tags before it asks anything')] },
    { op: 'add', entry: pitfall('A claim that rests on nothing readable'), sources: [ev(emptyThought), ev(counts)] },
    { op: 'add', entry: pitfall('A long tool output'), sources: [ev(long)] },
    { op: 'add', entry: pitfall('A compaction summary says the script tags'), sources: [ev(summary, 'tags at once')] },
  ]);

  await t.test('every quote is checked against the text the verifier reads: a tool call\'s input, a result, a thinking', async () => {
    assert.deepEqual(outcomes.map((op) => [op.status, op.waitsFor]), Array(7).fill(['pending', 'verification']));
    const quoted = await h.prisma.wikiSource.findMany({ where: { ownerId: owner.id, quote: { not: null } }, select: { ref: true, quoteVerified: true } });
    const verified = new Map(quoted.map((source) => [source.ref, source.quoteVerified]));
    for (const ref of [toolUse, toolResult, blocks, failed, thought, summary]) assert.equal(verified.get(ref), true, `the quote of ${ref} was verified`);
    // A quote the record does not hold is refused, now that its text can be read.
    const wrong = await call(h, mine, 'POST', '/runner/wiki/changesets', {
      rationale: 'a quote the tool never printed',
      idempotencyKey: `wrong-${randomUUID()}`,
      ops: [{ op: 'add', entry: pitfall('A quote nobody printed'), sources: [ev(toolResult, 'the build was green')] }],
    });
    expectStatus(wrong, 422, 'a quote that is not in the result');
    assert.equal(wrong.body.ops[0].reasons[0].code, 'WIKI_QUOTE_NOT_FOUND');
    // An empty thinking has no text to check a quote against: kept, and marked unverified, as before.
    const unchecked = await propose(h, mine, [{ op: 'add', entry: pitfall('A quote of an empty thinking'), sources: [ev(emptyThought, 'something it never said')] }]);
    assert.equal(unchecked[0].status, 'pending');
    const kept = await h.prisma.wikiSource.findFirstOrThrow({ where: { ownerId: owner.id, ref: emptyThought, quote: 'something it never said' } });
    assert.equal(kept.quoteVerified, false);
  });

  await t.test('the list hands each source\'s text: a tool\'s name and input, a result\'s content, a thinking\'s words', async () => {
    const items = await listed(h, mine, space);
    const item = (title: string) => {
      const found = items.find((candidate) => candidate.entry.title === title);
      assert.ok(found, `${title} is not in the list`);
      return found;
    };
    const release = item('The release script tags at once');
    assert.equal(release.sources[0].text, 'Bash\ncommand: bash scripts/release.sh next\ndescription: Cut the next release');
    assert.equal(release.sources[1].text, 'Tagged v0.1.196 and pushed the tag: release.sh next is not a dry run');
    assert.equal(release.evidence, 'readable');
    assert.equal(item('The index is missing after a restore').sources[0].text, 'The first block of the result\nThe second block says the index is missing');
    assert.equal(item('Permission denied under the orbit state directory').sources[0].text, 'The tool reported an error:\npermission denied: /var/lib/orbit');
    assert.equal(item('Next is not a dry run').sources[0].text, 'The script tags before it asks anything, so next is not a dry run.');
    assert.equal(item('A compaction summary says the script tags').sources[0].text, 'So far: the release script tags at once.');
    for (const source of release.sources) assert.equal(source.truncated, false);
  });

  await t.test('an empty thinking and a system event\'s counts are nothing to read, and the op says so', async () => {
    const items = await listed(h, mine, space);
    const nothing = items.find((candidate) => candidate.entry.title === 'A claim that rests on nothing readable')!;
    assert.deepEqual(nothing.sources.map((source) => source.text), [null, null]);
    assert.equal(nothing.evidence, 'unreadable');
    const quotedEmpty = items.find((candidate) => candidate.entry.title === 'A quote of an empty thinking')!;
    assert.equal(quotedEmpty.sources[0].text, null, 'a quote is not the record\'s text');
    assert.equal(quotedEmpty.evidence, 'unreadable');
  });

  await t.test('a long result is redacted before it is cut, and the cut is marked', async () => {
    const items = await listed(h, mine, space);
    const source = items.find((candidate) => candidate.entry.title === 'A long tool output')!.sources[0];
    assert.equal(source.truncated, true);
    assert.equal([...source.text!].length, WIKI_REVIEW_RULES.verificationSourceMaxChars);
    assert.doesNotMatch(source.text!, /abcdefghijklmnopqrstuvwx0123/u, 'a credential shape is redacted');
    assert.ok(!source.text!.includes(literal), 'and so is the owner\'s own workspace value');
    assert.match(source.text!, /\[redacted\]/u);
  });
});

// ── 2. nothing readable: no more than Unreviewed, and not counted ────────────────────────────────

test('evidence · a verdict about records nobody could read leaves its op no more than Unreviewed, and is not counted', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'evidence-cap');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const empty = await event(h, records, 'thinking', { text: '   ' });
  const counts = await event(h, records, 'system', { subtype: 'context', contextTokens: 812 });
  const readable = await event(h, records, 'tool_result', { toolUseId: 'toolu_r', content: 'The migration applied in 41 seconds.' });
  const proposer = await session(h, owner.id, ws, machine);
  const mine = { runner: machine, headers: { 'x-orbit-session-id': proposer } };
  const nothing = [{ kind: 'event', ref: empty }, { kind: 'event', ref: counts }];
  const reader = await session(h, owner.id, ws, machine);

  await t.test('supported, partial and unsupported all apply it as Unreviewed: shown, never pushed', async () => {
    const outcomes = await propose(h, mine, ['Supported', 'Partial', 'Unsupported'].map((word) => ({
      op: 'add', entry: pitfall(`${word} about nothing readable`), sources: nothing,
    })));
    const items = await listed(h, mine, space);
    for (const outcome of outcomes) {
      assert.equal(items.find((item) => toUuid(item.opId) === toUuid(outcome.opId!))?.evidence, 'unreadable', 'the list says so first');
    }
    const said = ['supported', 'partial', 'unsupported'];
    for (const [index, outcome] of outcomes.entries()) {
      const done = await h.service.recordVerifications(agent(owner.id, proposer), space, [verdict(outcome.opId!, said[index])]);
      assert.equal(done.outcomes[0].status, 'applied', `${said[index]} about nothing readable: ${JSON.stringify(done.outcomes[0])}`);
      assert.equal((done.outcomes[0] as { trust?: string }).trust, 'unreviewed');
      const op = await opRow(h, outcome.opId!);
      assert.equal(op.decision, 'auto_applied');
      assert.equal(op.decisionReason, null, 'nothing rejected it');
      assert.equal(op.verificationVerdict, said[index], 'the verifier\'s verdict is kept as it said it');
      assert.equal(op.verificationEvidence, 'unreadable', 'with what it could read');
      const entry = await entryRow(h, outcome.entryId!);
      assert.equal(entry.status, 'active');
      assert.equal(entry.trust, 'unreviewed');
    }
    const handed = await pushed(h, owner.id, ws, reader);
    for (const outcome of outcomes) assert.ok(!handed.has(toUuid(outcome.entryId!)), 'an Unreviewed entry is never pushed');
  });

  await t.test('the server reads the evidence itself: a verdict can be no more than its op\'s sources allow', async () => {
    // The same verdict, reported over the runner door: what the verifier claims it read does not enter into it.
    const [outcome] = await propose(h, mine, [{ op: 'add', entry: pitfall('A second claim about nothing readable'), sources: nothing }]);
    const answer = await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications`, {
      verdicts: [{ ...verdict(outcome.opId!, 'supported'), evidence: 'readable' }],
    });
    expectStatus(answer, 200, 'the report');
    assert.equal(answer.body.outcomes[0].trust, 'unreviewed');
    assert.equal((await entryRow(h, outcome.entryId!)).trust, 'unreviewed');
  });

  await t.test('a duplicate is still a reinforce: the entry it names gains its sources', async () => {
    const [control] = await propose(h, mine, [{ op: 'add', entry: pitfall('The migration applied in forty one seconds'), sources: [{ kind: 'event', ref: readable, quote: 'applied in 41 seconds' }] }]);
    const applied = await h.service.recordVerifications(agent(owner.id, proposer), space, [verdict(control.opId!, 'supported')]);
    assert.equal((applied.outcomes[0] as { trust?: string }).trust, 'auto', 'the control: a readable op is decided as revision 3 decided it');
    assert.equal((await opRow(h, control.opId!)).verificationEvidence, 'readable');
    const target = toUuid(control.entryId!);
    const before = await liveSources(h, target);
    const [again] = await propose(h, mine, [{
      op: 'add', entry: pitfall('The migration applied in forty one seconds', 'What the space knows about the migration applied in forty one seconds.'), sources: nothing,
    }]);
    assert.ok(again.similar?.some((near) => toUuid(near.id) === target), 'the neighbour is recorded with the op');
    const done = await h.service.recordVerifications(agent(owner.id, proposer), space, [verdict(again.opId!, 'duplicate', { duplicateOf: target })]);
    assert.equal(done.outcomes[0].status, 'reinforced');
    assert.equal((done.outcomes[0] as { reinforced?: boolean }).reinforced, true);
    assert.equal(await liveSources(h, target), before + nothing.length, 'its sources were added');
    assert.equal((await opRow(h, again.opId!)).verificationEvidence, 'unreadable');
  });

  await t.test('none of it counts toward the fallback: only what could be read can send the space back to Tiered', async () => {
    const fresh = await modeSpace(h, owner, 'automatic');
    const system = importer(owner.id);
    const adds = (count: number, prefix: string, sources: unknown[]) => Array.from({ length: count }, (_unused, n) => ({
      op: 'add', entry: { ...pitfall(`${prefix} ${n + 1} ${randomUUID().slice(0, 8)}`), kind: 'concept', fields: { definition: 'A thing the records name.', boundaries: 'Only this one.' } }, sources,
    }));
    const blind = await h.service.submitChangeset(system, fresh, { rationale: 'nothing readable', ops: adds(20, 'Blind', nothing), idempotencyKey: `blind-${randomUUID()}` });
    const seen = await h.service.submitChangeset(system, fresh, { rationale: 'readable', ops: adds(16, 'Seen', [{ kind: 'event', ref: readable }]), idempotencyKey: `seen-${randomUUID()}` });
    const blindOps = (blind.ops as Outcome[]).map((op) => op.opId!);
    const seenOps = (seen.ops as Outcome[]).map((op) => op.opId!);
    const record = (opId: string) => h.service.recordVerifications(system, fresh, [verdict(opId, 'unsupported')]);
    const modeOf = async () => ((await h.prisma.wikiSpace.findFirstOrThrow({ where: { id: fresh } })).settings as { reviewMode: string }).reviewMode;
    const notified = h.fellBack.length;
    for (const opId of blindOps) assert.equal((await record(opId)).outcomes[0].status, 'applied', 'unsupported about nothing readable is not a rejection');
    assert.equal(await modeOf(), 'automatic', 'twenty unsupported verdicts about nothing readable send nothing back');
    for (const opId of seenOps.slice(0, 15)) assert.equal((await record(opId)).outcomes[0].status, 'rejected');
    assert.equal(await modeOf(), 'automatic', 'fifteen readable ones of fifty are not over 30%');
    assert.equal(h.fellBack.length, notified);
    const tripped = await record(seenOps[15]);
    assert.equal(tripped.mode, 'tiered', 'the sixteenth readable one is');
    assert.deepEqual(h.fellBack.slice(notified), [{ ownerId: owner.id, spaceId: fresh, unsupported: 16, window: WIKI_REVIEW_RULES.verificationWindow }]);
  });
});

// ── 3. tainted, in Automatic ────────────────────────────────────────────────────────────────────

test('evidence · in Automatic a tainted op is verified, never past Unreviewed, and only the owner\'s Confirm lets it reach an agent', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'evidence-tainted');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const result = await event(h, records, 'tool_result', { toolUseId: 'toolu_w', content: 'The vendor page says the API rate limit is 600 requests a minute.' });
  const cite = [{ kind: 'event', ref: result, quote: 'rate limit is 600 requests a minute' }];
  // A session that read the web: everything it proposes is tainted.
  const reader = await session(h, owner.id, ws, machine);
  await toolCall(h, reader, 'WebFetch', 'the vendor\'s pricing page');
  const tainted = { runner: machine, headers: { 'x-orbit-session-id': reader } };
  const plain = await session(h, owner.id, ws, machine);
  const clean = { runner: machine, headers: { 'x-orbit-session-id': plain } };
  const bystander = await session(h, owner.id, ws, machine);
  const agentReads = { runner: machine, headers: { 'x-orbit-session-id': bystander } };
  const verify = (sessionId: string, opId: string, value: string, over: Record<string, unknown> = {}) =>
    h.service.recordVerifications(agent(owner.id, sessionId), space, [verdict(opId, value, over)]);

  let webEntry = '';
  let webOp = '';

  await t.test('it waits for its verification, not for the owner, and takes no place in the queue', async () => {
    const [outcome] = await propose(h, tainted, [{ op: 'add', entry: pitfall('The vendor rate limit is six hundred a minute'), sources: cite }]);
    assert.equal(outcome.status, 'pending');
    assert.equal(outcome.waitsFor, 'verification');
    const op = await opRow(h, outcome.opId!);
    assert.equal(op.tainted, true);
    assert.equal(op.decision, 'verifying');
    webEntry = toUuid(outcome.entryId!);
    webOp = toUuid(outcome.opId!);
    const review = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/review?space=${space}`);
    expectStatus(review, 200, 'Review');
    assert.deepEqual(review.body, [], 'no card for the owner');
    const spaces = await call(h, { bearer: owner.bearer }, 'GET', '/wiki/spaces');
    assert.equal((spaces.body as Array<{ id: string; pendingOps: number }>).find((s) => toUuid(s.id) === space)?.pendingOps, 0);
  });

  await t.test('a full queue does not refuse it: what waits for a verdict waits on nobody\'s queue', async () => {
    const queued = await modeSpace(h, owner, 'tiered');
    const queue = await workspace(h, owner.id);
    expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${queued}/workspaces`, { workspaceId: queue }), 200, 'bind');
    // Thirty tainted proposals wait for the owner in Tiered: the queue is full.
    for (let batch = 0; batch < WIKI_LIMITS.pendingOpsPerSpace / WIKI_LIMITS.opsPerTurn; batch += 1) {
      const web = await session(h, owner.id, queue, machine);
      await toolCall(h, web, 'WebFetch', 'a page');
      const outcomes = await propose(h, { runner: machine, headers: { 'x-orbit-session-id': web } }, Array.from({ length: WIKI_LIMITS.opsPerTurn }, (_unused, n) => ({
        op: 'add', entry: pitfall(`A queued web pitfall ${batch}-${n}`), sources: cite,
      })));
      assert.deepEqual(outcomes.map((op) => op.status), Array(WIKI_LIMITS.opsPerTurn).fill('pending'));
    }
    const web = await session(h, owner.id, queue, machine);
    await toolCall(h, web, 'WebFetch', 'one more page');
    const who = { runner: machine, headers: { 'x-orbit-session-id': web } };
    const full = await call(h, who, 'POST', '/runner/wiki/changesets', {
      rationale: 'one too many for Tiered', idempotencyKey: `full-${randomUUID()}`,
      ops: [{ op: 'add', entry: pitfall('A thirty-first web pitfall'), sources: cite }],
    });
    assert.equal(full.body.ops[0].reasons[0].code, 'WIKI_REVIEW_QUEUE_FULL', 'the control: Tiered holds it for the owner, and the queue is full');
    await setMode(h, owner, queued, 'automatic');
    const [taken] = await propose(h, who, [{ op: 'add', entry: pitfall('A thirty-first web pitfall, in Automatic'), sources: cite }]);
    assert.equal(taken.status, 'pending');
    assert.equal(taken.waitsFor, 'verification', 'Automatic sends it to its verification, full queue or not');
  });

  await t.test('a supported verdict leaves it Unreviewed: the owner sees it, no session is handed it, no agent finds it', async () => {
    const done = await verify(reader, webOp, 'supported');
    assert.equal(done.outcomes[0].status, 'applied');
    assert.equal((done.outcomes[0] as { trust?: string }).trust, 'unreviewed');
    const entry = await entryRow(h, webEntry);
    assert.equal(entry.status, 'active');
    assert.equal(entry.trust, 'unreviewed');
    assert.equal(entry.tainted, true);
    assert.equal((await opRow(h, webOp)).verificationEvidence, 'readable', 'capped for the taint, not for want of text');
    // The control: the same verdict on an op nobody read the web for, with nearly the same words.
    const [control] = await propose(h, clean, [{ op: 'add', entry: pitfall('The vendor rate limit is six hundred a minute per key'), sources: cite }]);
    await verify(plain, control.opId!, 'partial');
    const controlEntry = toUuid(control.entryId!);
    assert.equal((await entryRow(h, controlEntry)).trust, 'unreviewed');

    assert.ok(!(await pushed(h, owner.id, ws, bystander)).has(webEntry), 'never pushed');
    for (const who of [agentReads, tainted]) {
      const found = await agentFinds(h, who, 'vendor rate limit');
      assert.ok(!found.has(webEntry), 'an agent\'s search does not return it — not even the session that proposed it');
      assert.ok(found.has(controlEntry), 'while an Unreviewed entry nobody read the web for is still found');
    }
    expectStatus(await call(h, agentReads, 'GET', `/runner/wiki/entries/${webEntry}`), 404, 'an agent\'s get');
    expectStatus(await call(h, agentReads, 'GET', `/runner/wiki/entries/${controlEntry}`), 200, 'the control\'s get');
    const read = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/entries/${webEntry}`);
    expectStatus(read, 200, 'the owner reads it');
    assert.equal(read.body.trust, 'unreviewed');
    assert.ok((await ownerFinds(h, owner, space, 'vendor rate limit')).has(webEntry), 'and finds it');
  });

  await t.test('an unsupported verdict still rejects it, and counts', async () => {
    const [outcome] = await propose(h, tainted, [{ op: 'add', entry: pitfall('The vendor never rate limits anybody'), sources: cite }]);
    const done = await verify(reader, outcome.opId!, 'unsupported');
    assert.equal(done.outcomes[0].status, 'rejected');
    const op = await opRow(h, outcome.opId!);
    assert.equal(op.decisionReason, 'not_true');
    assert.equal(op.verificationEvidence, 'readable');
    assert.equal((await entryRow(h, outcome.entryId!)).status, 'rejected');
  });

  await t.test('its duplicate adds nothing to the entry it names, so nothing about that entry\'s push can change', async () => {
    const [kept] = await propose(h, clean, [{ op: 'add', entry: pitfall('Retries back off to thirty seconds'), sources: cite }]);
    await verify(plain, kept.opId!, 'supported');
    const target = toUuid(kept.entryId!);
    assert.equal((await entryRow(h, target)).trust, 'auto');
    const before = await liveSources(h, target);
    const [again] = await propose(h, tainted, [{ op: 'add', entry: pitfall('Retries back off to thirty seconds'), sources: cite }]);
    assert.ok(again.similar?.some((near) => toUuid(near.id) === target));
    const done = await verify(reader, again.opId!, 'duplicate', { duplicateOf: target });
    assert.equal(done.outcomes[0].status, 'reinforced');
    assert.equal((done.outcomes[0] as { reinforced?: boolean }).reinforced, false, 'nothing was added');
    assert.equal(await liveSources(h, target), before);
    const entry = await entryRow(h, target);
    assert.equal(entry.tainted, false, 'the entry it named rests on nothing from the web');
    assert.equal(entry.trust, 'auto');
    assert.ok((await pushed(h, owner.id, ws, bystander)).has(target), 'and is pushed as before');
  });

  await t.test('only the owner\'s door confirms it', async () => {
    const withSession = await call(h, { bearer: owner.bearer, headers: { 'x-orbit-session-id': bystander } }, 'POST', `/wiki/entries/${webEntry}/confirm`);
    expectStatus(withSession, 403, 'a confirm that names a session');
    assert.equal(withSession.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
    expectStatus(await call(h, agentReads, 'POST', `/runner/wiki/entries/${webEntry}/confirm`), 404, 'the runner door has no confirm');
    const stranger = await account(h, 'stranger');
    expectStatus(await call(h, { bearer: stranger.bearer }, 'POST', `/wiki/entries/${webEntry}/confirm`), 404, 'another owner\'s entry');
    assert.equal((await entryRow(h, webEntry)).trust, 'unreviewed', 'none of them changed it');
  });

  await t.test('the owner\'s Confirm: confirmed, a revision of theirs, pushed, and found', async () => {
    const before = await liveSources(h, webEntry);
    const confirmed = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${webEntry}/confirm`);
    expectStatus(confirmed, 200, 'the owner confirms');
    assert.equal(confirmed.body.trust, 'confirmed');
    const entry = await entryRow(h, webEntry);
    assert.equal(entry.trust, 'confirmed');
    assert.equal(entry.status, 'active');
    assert.equal(entry.tainted, true, 'it still says it rests on the web');
    assert.equal(entry.currentRevision, 2);
    const revision = await h.prisma.wikiEntryRevision.findFirstOrThrow({ where: { entryId: webEntry, revision: 2 } });
    assert.equal(revision.authorKind, 'owner');
    assert.equal(revision.authorUserId, owner.id);
    assert.equal(revision.title, entry.title, 'the same content');
    assert.equal(await liveSources(h, webEntry), before, 'resting on the same records');
    assert.equal((await opRow(h, webOp)).decision, 'accepted', 'what the mode applied is answered');
    assert.ok((await pushed(h, owner.id, ws, bystander)).has(webEntry), 'pushed now');
    assert.ok((await agentFinds(h, agentReads, 'vendor rate limit')).has(webEntry), 'and found by an agent');
    expectStatus(await call(h, agentReads, 'GET', `/runner/wiki/entries/${webEntry}`), 200, 'and read by one');
    expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${webEntry}/confirm`), 409, 'confirmed once is confirmed');
  });

  await t.test('an entry nobody read the web for is confirmed the same way', async () => {
    const [outcome] = await propose(h, clean, [{ op: 'add', entry: pitfall('The vendor sends a retry-after header'), sources: cite }]);
    await verify(plain, outcome.opId!, 'partial');
    const confirmed = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${outcome.entryId}/confirm`);
    expectStatus(confirmed, 200, 'the owner confirms an Unreviewed entry');
    assert.equal((await entryRow(h, outcome.entryId!)).trust, 'confirmed');
    const proposal = await propose(h, tainted, [{ op: 'add', entry: pitfall('Nobody verified this yet'), sources: cite }]);
    expectStatus(await call(h, { bearer: owner.bearer }, 'POST', `/wiki/entries/${proposal[0].entryId}/confirm`), 409, 'a proposal is accepted in Review');
  });

  await t.test('Manual and Tiered still hold a tainted op for the owner', async () => {
    for (const mode of ['manual', 'tiered'] as const) {
      const bound = await workspace(h, owner.id);
      await modeSpace(h, owner, mode, bound);
      const web = await session(h, owner.id, bound, machine);
      await toolCall(h, web, 'WebFetch', 'a page');
      const [outcome] = await propose(h, { runner: machine, headers: { 'x-orbit-session-id': web } }, [{ op: 'add', entry: pitfall(`A ${mode} web pitfall`), sources: cite }]);
      assert.equal(outcome.status, 'pending', mode);
      assert.equal(outcome.waitsFor, undefined, `${mode}: it waits for the owner`);
      assert.equal((await opRow(h, outcome.opId!)).decision, 'pending');
    }
  });
});

// ── 4. reopening what was decided without evidence ─────────────────────────────────────────────

test('evidence · reopening: what was rejected for want of text waits for its verification again, and a tainted op goes to its', { skip, concurrency: 1, timeout: 600_000 }, async (t) => {
  const h = await boot();
  const owner = await account(h, 'evidence-reopen');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id);
  const space = await modeSpace(h, owner, 'automatic', ws);
  const records = await session(h, owner.id, ws, machine);
  const tool = await event(h, records, 'tool_result', { toolUseId: 'toolu_x', content: 'The worktree overlay symlinks node_modules from the main checkout.' });
  const said = await event(h, records, 'assistant', { text: 'The overlay symlinks node_modules from the main checkout.' });
  const proposer = await session(h, owner.id, ws, machine);
  const mine = { runner: machine, headers: { 'x-orbit-session-id': proposer } };
  const verify = (opId: string, value: string) => h.service.recordVerifications(agent(owner.id, proposer), space, [verdict(opId, value)]);
  const reopen = (who: Caller = { bearer: owner.bearer }, spaceId = space) => call(h, who, 'POST', `/wiki/spaces/${spaceId}/verifications/reopen`);

  // Three unsupported verdicts. Two were given before revision 4 (no evidence mark): one about a tool
  // result, which that reader could not read, and one about an assistant's words, which it could. The
  // third was given since, and says it could read its sources.
  const [blind, heard, recent] = await propose(h, mine, [
    { op: 'add', entry: pitfall('The overlay symlinks node modules'), sources: [{ kind: 'event', ref: tool }] },
    { op: 'add', entry: pitfall('The overlay links the main checkout'), sources: [{ kind: 'event', ref: said }] },
    { op: 'add', entry: pitfall('The overlay copies node modules'), sources: [{ kind: 'event', ref: tool }] },
  ]);
  for (const outcome of [blind, heard, recent]) assert.equal((await verify(outcome.opId!, 'unsupported')).outcomes[0].status, 'rejected');
  await h.sql.query(`UPDATE "wiki_changeset_op" SET "verification_evidence" = NULL WHERE "id" = ANY($1::uuid[])`, [[toUuid(blind.opId!), toUuid(heard.opId!)]]);
  const blindEntry = toUuid(blind.entryId!);
  const blindOp = toUuid(blind.opId!);
  // A proposal made while the rejection stood, whose recorded neighbours say not_true.
  const [probe] = await propose(h, mine, [{ op: 'add', entry: pitfall('The overlay symlinks node modules', 'What the space knows about the overlay symlinks node modules, again.'), sources: [{ kind: 'event', ref: said }] }]);

  await t.test('the control: while it stands, the next similar[] offers it as a claim found not true', async () => {
    const near = probe.similar?.find((candidate) => toUuid(candidate.id) === blindEntry);
    assert.equal(near?.rejectedReason, 'not_true');
    assert.ok(near?.rejectedBecause);
  });

  await t.test('only the owner\'s door reopens, with no session header', async () => {
    const withSession = await reopen({ bearer: owner.bearer, headers: { 'x-orbit-session-id': proposer } });
    expectStatus(withSession, 403, 'a reopening that names a session');
    assert.equal(withSession.body.code, 'WIKI_OWNER_CHANNEL_ONLY');
    expectStatus(await call(h, mine, 'POST', `/runner/wiki/spaces/${space}/verifications/reopen`), 404, 'the runner door has no reopening');
    const stranger = await account(h, 'stranger');
    expectStatus(await reopen({ bearer: stranger.bearer }), 404, 'another owner\'s space');
    assert.equal((await opRow(h, blindOp)).decision, 'rejected', 'none of them moved it');
  });

  await t.test('it reopens what the reader of the time could not read, and nothing else', async () => {
    const answer = await reopen();
    expectStatus(answer, 200, 'the owner reopens');
    assert.deepEqual((answer.body.reopened as string[]).map(toUuid), [blindOp]);
    assert.deepEqual(answer.body.toVerification, []);
    assert.deepEqual(answer.body.skipped, []);
    const op = await opRow(h, blindOp);
    assert.equal(op.decision, 'verifying');
    assert.equal(op.decisionReason, null);
    assert.equal(op.decidedAt, null);
    assert.equal(op.verificationVerdict, null);
    assert.equal(op.verificationEvidence, null);
    const history = op.verificationHistory as Array<Record<string, unknown>>;
    assert.equal(history.length, 1, 'the earlier verdict is kept');
    assert.equal(history[0].verdict, 'unsupported');
    assert.equal(history[0].decision, 'rejected');
    assert.equal(history[0].decisionReason, 'not_true');
    assert.equal(history[0].evidence, 'unreadable');
    assert.equal(history[0].model, 'qwen3.8-27b-fp8');
    assert.ok(history[0].reopenedAt);
    const entry = await entryRow(h, blindEntry);
    assert.equal(entry.status, 'proposed');
    assert.equal(entry.trust, 'proposed');
    assert.equal(entry.retiredAt, null);
    const changeset = await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: op.changesetId } });
    assert.equal(changeset.status, 'pending');
    assert.equal(changeset.decidedAt, null);
    assert.ok(changeset.expiresAt);
    for (const other of [heard, recent]) assert.equal((await opRow(h, other.opId!)).decision, 'rejected', 'a verdict that could read its sources stands');
    const view = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/review?space=${space}`);
    expectStatus(view, 200, 'Review');
    assert.deepEqual(view.body, [], 'what waits for a verdict is no card');
  });

  await t.test('it is no longer a counter-example in the neighbours\' hints', async () => {
    const [next] = await propose(h, mine, [{ op: 'add', entry: pitfall('The overlay symlinks node modules', 'What the space knows about the overlay symlinks node modules, once more.'), sources: [{ kind: 'event', ref: said }] }]);
    const near = next.similar?.find((candidate) => toUuid(candidate.id) === blindEntry);
    assert.ok(near, 'still a neighbour');
    assert.equal(near.status, 'proposed');
    assert.equal(near.rejectedReason, undefined);
    assert.equal(near.rejectedBecause, undefined);
    const items = await listed(h, mine, space);
    const recorded = items.find((item) => toUuid(item.opId) === toUuid(probe.opId!))!.similar.find((candidate) => toUuid(candidate.id) === blindEntry);
    assert.ok(recorded, 'the probe\'s recorded neighbour, read now');
    assert.equal(recorded.rejectedReason, undefined, 'no longer offered as a claim found not true');
  });

  await t.test('the list hands it back with its text, and a new verdict decides it', async () => {
    const items = await listed(h, mine, space);
    const item = items.find((candidate) => toUuid(candidate.opId) === blindOp);
    assert.ok(item, 'listed again');
    assert.equal(item.evidence, 'readable');
    assert.equal(item.sources[0].text, 'The worktree overlay symlinks node_modules from the main checkout.');
    const done = await verify(blindOp, 'supported');
    assert.equal(done.outcomes[0].status, 'applied');
    const op = await opRow(h, blindOp);
    assert.equal(op.decision, 'auto_applied');
    assert.equal(op.verificationEvidence, 'readable');
    assert.equal((op.verificationHistory as unknown[]).length, 1, 'the earlier verdict is still there');
    assert.equal((await entryRow(h, blindEntry)).trust, 'auto');
    assert.equal((await h.prisma.wikiChangeset.findFirstOrThrow({ where: { id: op.changesetId } })).status, 'settled', 'nothing of it waits any more');
  });

  await t.test('a second call finds nothing left to move', async () => {
    const answer = await reopen();
    expectStatus(answer, 200, 'again');
    assert.deepEqual(answer.body.reopened, []);
    assert.deepEqual(answer.body.toVerification, []);
  });

  await t.test('the import reopens the ops of its own changesets, and no session\'s', async () => {
    const system = importer(owner.id);
    const loaded = await h.service.submitChangeset(system, space, {
      rationale: 'imported', idempotencyKey: `import-${randomUUID()}`,
      ops: [{ op: 'add', entry: pitfall('The import says the overlay is symlinked'), sources: [{ kind: 'event', ref: tool }] }],
    });
    const imported = (loaded.ops as Outcome[])[0].opId!;
    assert.equal((await h.service.recordVerifications(system, space, [verdict(imported, 'unsupported')])).outcomes[0].status, 'rejected');
    const [agents] = await propose(h, mine, [{ op: 'add', entry: pitfall('A session says the overlay is symlinked'), sources: [{ kind: 'event', ref: tool }] }]);
    assert.equal((await verify(agents.opId!, 'unsupported')).outcomes[0].status, 'rejected');
    await h.sql.query(`UPDATE "wiki_changeset_op" SET "verification_evidence" = NULL WHERE "id" = ANY($1::uuid[])`, [[toUuid(imported), toUuid(agents.opId!)]]);
    const answer = await h.service.reopenVerifications(system, space);
    assert.deepEqual(answer.reopened.map(toUuid), [toUuid(imported)]);
    assert.equal((await opRow(h, agents.opId!)).decision, 'rejected', 'a session\'s op is the owner\'s to reopen, not the import\'s');
    await assert.rejects(
      h.service.reopenVerifications(agent(owner.id, proposer), space),
      (error: unknown) => (error as { refusal?: { code?: string } }).refusal?.code === 'WIKI_OWNER_CHANNEL_ONLY',
      'and never a session\'s',
    );
  });

  await t.test('a tainted op that waits for the owner goes to its verification once the space is automatic', async () => {
    const bound = await workspace(h, owner.id);
    const tiered = await modeSpace(h, owner, 'tiered', bound);
    const web = await session(h, owner.id, bound, machine);
    await toolCall(h, web, 'WebFetch', 'a page');
    const reads = { runner: machine, headers: { 'x-orbit-session-id': web } };
    const written = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${tiered}/changesets`, {
      rationale: 'the owner writes one', ops: [{ op: 'add', entry: pitfall('The owner\'s own overlay pitfall') }],
    });
    expectStatus(written, 200, 'the owner writes');
    const ownerEntry = toUuid(written.body.ops[0].entryId);
    const [add, amend] = await propose(h, reads, [
      { op: 'add', entry: pitfall('A web page says the overlay is fragile'), sources: [{ kind: 'event', ref: tool }] },
      { op: 'amend', entryId: ownerEntry, baseRevision: 1, changes: { summary: 'A web page rewrites the owner.' }, sources: [{ kind: 'event', ref: tool }] },
    ]);
    for (const outcome of [add, amend]) assert.equal((await opRow(h, outcome.opId!)).decision, 'pending');
    const inTiered = await reopen({ bearer: owner.bearer }, tiered);
    expectStatus(inTiered, 200, 'in Tiered');
    assert.deepEqual(inTiered.body.toVerification, [], 'Tiered holds a tainted op for the owner');
    await setMode(h, owner, tiered, 'automatic');
    const moved = await reopen({ bearer: owner.bearer }, tiered);
    expectStatus(moved, 200, 'in Automatic');
    assert.deepEqual((moved.body.toVerification as string[]).map(toUuid), [toUuid(add.opId!)]);
    assert.deepEqual((moved.body.skipped as Array<{ opId: string }>).map((skipped) => toUuid(skipped.opId)), [toUuid(amend.opId!)], 'an amend of the owner\'s entry keeps waiting for them');
    assert.equal((await opRow(h, add.opId!)).decision, 'verifying');
    assert.equal((await opRow(h, amend.opId!)).decision, 'pending');
    const spaces = await call(h, { bearer: owner.bearer }, 'GET', '/wiki/spaces');
    assert.equal((spaces.body as Array<{ id: string; pendingOps: number }>).find((s) => toUuid(s.id) === tiered)?.pendingOps, 1, 'it left the queue');
    const done = await h.service.recordVerifications(agent(owner.id, web), tiered, [verdict(add.opId!, 'supported')]);
    assert.equal((done.outcomes[0] as { trust?: string }).trust, 'unreviewed', 'and its verdict is capped like any tainted op\'s');
  });
});
