/**
 * The articles (criterion 9; contracts/wiki.contract.json `articles`, migration 0317), over real HTTP
 * and against a real PostgreSQL.
 *
 * What criterion 9's verification method asks, each read back from the doors and from the database:
 *
 *   1. an entry set that did not change is not written again, and one that changed is;
 *   2. a footnote out of range, naming another topic's entry or naming no entry is stripped, and a
 *      sentence left with none is deleted;
 *   3. an article is not in the push block and cannot be cited as a source — nor is it what an
 *      agent's wiki_search or wiki_get returns;
 *   4. another tenant's read is a 404, every one of them;
 *
 * and beside them what this task was given to fix and to guard: an entry is filed by its anchors'
 * paths before the slug it names and before its words (the demo filed a database write under
 * "sessions"); an article past 900 characters is cut back to it; a topic is split into an overview
 * and subtopic parts; a space with no topic is given the default ones, each with its display name
 * and category; and only a maintenance run of the space, or the server's own import, writes.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-articles.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created. Only the two credential checks are stood in for, as in the other wiki specs.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';
import { readFileSync } from 'node:fs';
import path from 'node:path';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { toUuid, uuidToBase62, WIKI_ARTICLE_CATEGORY_KEYS, WIKI_ARTICLE_KINDS, WIKI_DEFAULT_TOPICS } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import type { PushService } from '../push/push.service';
import type { RealtimeService } from '../realtime/realtime.service';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiArticlesController } from '../runner-api/runner-wiki-articles.controller';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { assignTopics, pathClaim, splitSentences, WikiArticles } from './wiki-articles';
import { WikiArticlesController } from './wiki-articles.controller';
import { appendWikiContext } from './wiki-push';
import type { WikiRollout } from './wiki-rollout';
import { WikiRetrieval } from './wiki-retrieval';
import { WikiController } from './wiki.controller';
import { WikiRefusalError, WikiService, type WikiPrincipal } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The wiki switched on for every account, whatever this environment's ORBIT_WIKI says. */
const ON: WikiRollout = { mode: 'on', canaryOwners: new Set<string>(), problems: [] };

const CONTRACT = JSON.parse(readFileSync(path.resolve(__dirname, '../../../../contracts/wiki.contract.json'), 'utf8'));

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  articles: WikiArticles;
  bearers: Map<string, string>;
  /** Every space `wiki.changed` was published for by the articles, in order. */
  published: string[];
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();
    const published: string[] = [];
    const hub = { publishWikiChanged: () => undefined } as unknown as RealtimeService;
    const recorder = { publishWikiChanged: (_owner: string, space: string) => published.push(space) } as unknown as RealtimeService;
    const service = new WikiService(prisma as unknown as PrismaService, hub, {} as unknown as PushService);
    const articles = new WikiArticles(prisma as unknown as PrismaService, recorder);

    @Module({
      controllers: [WikiController, WikiArticlesController, RunnerWikiController, RunnerWikiArticlesController],
      providers: [
        { provide: WikiService, useValue: service },
        { provide: WikiArticles, useValue: articles },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiArticlesModule {}

    const app = await NestFactory.create(WikiArticlesModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, articles, bearers, published };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  session?: string;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  if (who.session) headers['x-orbit-session-id'] = who.session;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body).slice(0, 800)}`);
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-articles-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

async function runner(h: Harness, ownerId: string): Promise<{ id: string; token: string }> {
  const id = randomUUID();
  const token = `runner-${id}`;
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    createHash('sha256').update(token).digest('hex'),
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id") VALUES ($1,'spec',$2)`, [id, ownerId]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string, runnerId: string, taskId: string | null = null): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id",
                            "task_id","status","dispatch_origin","updated_at")
     VALUES ($1,'a session','p',$2,$2,$3,$4,$5,'RUNNING'::run_status,'USER',now())`,
    [id, ownerId, workspaceId, runnerId, taskId],
  );
  return id;
}

async function task(h: Harness, ownerId: string, listId: string, assigneeId: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "task"("id","title","owner_id","creator_type","creator_id","status","assignee_id","list_id",
                         "completion_criterion","updated_at")
     VALUES ($1,'Wiki maintenance run',$2,'USER',$2,'OPEN'::task_status,$3,$4,'OWNER_CONFIRMED',now())`,
    [id, ownerId, assigneeId, listId],
  );
  return id;
}

/** A space the owner makes through the door, bound to a workspace of theirs. */
async function space(h: Harness, owner: Account, workspaceId: string, title = 'An article space'): Promise<string> {
  const made = await call(h, { bearer: owner.bearer }, 'POST', '/wiki/spaces', { title });
  expectStatus(made, 201, 'the owner creates a space');
  const id = toUuid(made.body.id as string);
  const bound = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${id}/workspaces`, { workspaceId });
  expectStatus(bound, 200, 'the owner binds the workspace');
  return id;
}

/** A maintenance run of the space: maintenance turned on by the owner, a task in its list, and that task's session. */
async function maintenanceRun(h: Harness, owner: Account, spaceId: string, workspaceId: string, runnerId: string): Promise<string> {
  const on = await call(h, { bearer: owner.bearer }, 'PATCH', `/wiki/spaces/${spaceId}`, { maintenance: { enabled: true, workspaceId } });
  expectStatus(on, 200, 'the owner turns maintenance on');
  const listId = toUuid(on.body.settings.maintenance.listId as string);
  return session(h, owner.id, workspaceId, runnerId, await task(h, owner.id, listId, workspaceId));
}

/** A concept: what the owner writes when an entry has no code to point at. */
function concept(title: string, summary: string, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    kind: 'concept',
    title,
    summary,
    fields: { definition: summary, boundaries: 'It says nothing beyond this.' },
    ...extra,
  };
}

/** A convention scoped to a path, so it names that path and is pushed wherever it applies. */
function convention(title: string, summary: string, scope: string, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return { kind: 'convention', title, summary, fields: { rule: summary, scope: [scope] }, ...extra };
}

/** A pitfall anchored at a path. */
function pitfall(title: string, summary: string, at: string, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    kind: 'pitfall',
    title,
    summary,
    fields: {
      trigger: { paths: [at], commands: [] },
      symptom: summary,
      cause: 'It was done in the wrong order.',
      fix: 'Do it in the right order.',
    },
    anchors: [{ type: 'path', path: at }],
    ...extra,
  };
}

/** The owner's own adds, which apply at once (trust owner): the ids of the entries they made. */
async function ownerAdds(h: Harness, owner: Account, spaceId: string, entries: Array<Record<string, unknown>>): Promise<string[]> {
  const answer = await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${spaceId}/changesets`, {
    rationale: 'what the articles are written from',
    ops: entries.map((entry) => ({ op: 'add', entry })),
  });
  expectStatus(answer, 200, 'the owner writes entries');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return answer.body.ops.map((op: any) => {
    assert.equal(op.status, 'applied', `the owner's add applies at once: ${JSON.stringify(op).slice(0, 300)}`);
    return toUuid(op.entryId as string);
  });
}

/** An entry written straight into the table: what no owner write can make (a proposal, a tainted one). */
async function rawEntry(h: Harness, ownerId: string, spaceId: string, shape: { status: string; trust: string; tainted: boolean; title: string; anchorAt: string }): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "wiki_entry"("id","owner_id","space_id","kind","status","trust","current_revision","title","summary","fields","anchors","tainted")
     VALUES ($1,$2,$3,'concept',$4,$5,1,$6,'Written straight into the table.','{"definition":"x","boundaries":"y"}',$7,$8)`,
    [id, ownerId, spaceId, shape.status, shape.trust, shape.title, JSON.stringify([{ type: 'path', path: shape.anchorAt }]), shape.tainted],
  );
  return id;
}

/** One topic's generation input, read as the maintenance run reads it. */
async function input(h: Harness, who: Caller, spaceId: string, slug: string): Promise<Answer> {
  return call(h, who, 'GET', `/runner/wiki/spaces/${spaceId}/articles/${slug}/input`);
}

/** The entry ids an input answer carries, as uuids. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const inputIds = (answer: Answer): string[] => answer.body.entries.map((entry: any) => toUuid(entry.id as string));

/** The values a CHECK spells out, in the order it spells them. */
async function checkValues(h: Harness, table: string, constraint: string): Promise<string[]> {
  const def = await h.sql.query<{ def: string }>(
    `SELECT pg_get_constraintdef(oid) AS def FROM pg_constraint WHERE conname = $1 AND conrelid = $2::regclass`,
    [constraint, table],
  );
  assert.equal(def.rowCount, 1, `${table} has no constraint ${constraint}`);
  return [...def.rows[0].def.matchAll(/'([^']+)'::text/gu)].map((m) => m[1]);
}

/**
 * One scene every test reads: an owner, their runner, a bound workspace, a space with maintenance on
 * and a maintenance run of it, an ordinary session of the same workspace, and entries whose topics
 * each step of membership decides.
 */
interface Scene {
  owner: Account;
  runner: { id: string; token: string };
  ws: string;
  spaceId: string;
  maintainer: Caller;
  ordinary: string;
  e: {
    /** Anchored in the write inventory, naming "sessions" and talking about sessions: the database's by path. */
    dbPath: string;
    /** No path, no slug: about Prisma migrations, and the database's by its words. */
    dbWords: string;
    /** Scoped to the web's lib: the web client's. */
    web: string;
    /** A second web entry, anchored at a page. */
    webPage: string;
    /** No path; names workflow-owner. */
    declared: string;
    /** Anchored by a worktree's absolute path under the runner's wiki files: the wiki's, by the longest prefix. */
    wikiAbs: string;
    wikiA: string;
    wikiB: string;
    /** Active but tainted, and a proposal: neither is in any topic. */
    tainted: string;
    proposed: string;
  };
}

let scene: Promise<Scene> | undefined;

function setUp(h: Harness): Promise<Scene> {
  scene ??= (async () => {
    const owner = await account(h, 'owner');
    const machine = await runner(h, owner.id);
    const ws = await workspace(h, owner.id);
    const spaceId = await space(h, owner, ws);
    const maintenanceSession = await maintenanceRun(h, owner, spaceId, ws, machine.id);
    const ordinary = await session(h, owner.id, ws, machine.id);
    const [dbPath, dbWords, web, webPage, declared, wikiAbs, wikiA, wikiB] = await ownerAdds(h, owner, spaceId, [
      pitfall(
        '会话写入前要登记写入清单',
        '会话服务新增一处 Prisma 写入时，要在 db-write-inventory 里登记，否则整包测试红。',
        'src/apiserver/src/common/db-write-inventory.ts',
        { topics: ['sessions'] },
      ),
      concept('Prisma 迁移之后先 generate', '改了 schema.prisma 要先跑 prisma generate，否则 PostgreSQL 数据库的字段类型对不上。'),
      convention('Web 的 lib 不直接 fetch', 'src/web 的 lib 里一律走 api 模块发请求。', 'src/web/src/lib/**'),
      pitfall('页面测试要 stub sendTurn', '断言消息真的发出去，要 stub sendTurn 而不是 mock api。', 'src/web/src/pages/SessionPage.tsx'),
      concept('用中文回复 owner', 'owner 读中文，回复一律用中文。', { topics: ['workflow-owner'] }),
      pitfall(
        '核实调用默认不开 thinking',
        '干净的 Claude Code 调本地模型时，EFFORT_LEVEL=unset 仍会发 thinking，要再加 MAX_THINKING_TOKENS=0。',
        '/root/.orbit/worktrees/0a1b2c/src/runner-go/wiki_verify.go',
      ),
      pitfall('文章写入只认维护会话', '文章写入先问 isWikiMaintenanceSession，别的会话一律拒绝。', 'src/apiserver/src/wiki/wiki-articles.ts'),
      pitfall('案卷先脱敏再截断', '案卷每行先过共享脱敏器，再量长度、装箱。', 'src/apiserver/src/wiki/wiki-dossier.ts'),
    ]);
    const tainted = await rawEntry(h, owner.id, spaceId, {
      status: 'active',
      trust: 'unreviewed',
      tainted: true,
      title: 'A web page said so',
      anchorAt: 'src/apiserver/prisma/schema.prisma',
    });
    const proposed = await rawEntry(h, owner.id, spaceId, {
      status: 'proposed',
      trust: 'proposed',
      tainted: false,
      title: 'Nobody has looked at this yet',
      anchorAt: 'src/apiserver/prisma/schema.prisma',
    });
    return {
      owner,
      runner: machine,
      ws,
      spaceId,
      maintainer: { runner: machine.token, session: maintenanceSession },
      ordinary,
      e: { dbPath, dbWords, web, webPage, declared, wikiAbs, wikiA, wikiB, tainted, proposed },
    };
  })();
  return scene;
}

/** The article write body for one topic: its fingerprint and parts. */
function writeBody(sha: string, articles: Array<Record<string, unknown>>, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return { entrySetSha256: sha, ref: '0123456789abcdef0123456789abcdef01234567', model: 'qwen3.8-27b-fp8', articles, ...extra };
}

const b62 = (id: string): string => uuidToBase62(id);

// ── 1. topics: seeded, named, categorized; entries filed by their paths first ────────────────────

test('a space with no topic is given the default ones, and an entry is filed by its paths before its slug or its words', { skip }, async () => {
  const h = await boot();
  const s = await setUp(h);

  // The closed sets are CHECKs that list exactly the contract's values.
  assert.deepEqual(await checkValues(h, 'wiki_topic', 'wiki_topic_category_chk'), [...WIKI_ARTICLE_CATEGORY_KEYS]);
  assert.deepEqual(await checkValues(h, 'wiki_topic_summary', 'wiki_topic_summary_kind_chk'), [...WIKI_ARTICLE_KINDS]);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.deepEqual(WIKI_ARTICLE_CATEGORY_KEYS, CONTRACT.articles.categories.map((c: any) => c.key));

  const before = h.published.length;
  const plan = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/article-plan`);
  expectStatus(plan, 200, 'the maintenance run asks for its plan');
  assert.equal(plan.body.seeded, WIKI_DEFAULT_TOPICS.length, 'a space with no topic is given the default ones');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.deepEqual(plan.body.topics.map((t: any) => t.slug), WIKI_DEFAULT_TOPICS.map((t) => t.slug), 'in the default order');
  assert.equal(h.published.slice(before).filter((id) => id === s.spaceId).length, 1, 'seeding is announced once');

  // Each topic now has its display name and category in wiki_topic.
  const rows = await h.prisma.wikiTopic.findMany({ where: { spaceId: s.spaceId }, select: { slug: true, title: true, category: true, pathPrefixes: true } });
  for (const topic of WIKI_DEFAULT_TOPICS) {
    const row = rows.find((r) => r.slug === topic.slug);
    assert.ok(row, `topic ${topic.slug} was written`);
    assert.equal(row.title, topic.title, `${topic.slug} has its display name`);
    assert.equal(row.category, topic.category, `${topic.slug} is filed under its category`);
    assert.deepEqual(row.pathPrefixes, [...topic.pathPrefixes]);
  }
  // A category the contract does not list is refused by the CHECK.
  await assert.rejects(
    h.sql.query(`UPDATE "wiki_topic" SET "category" = 'bogus' WHERE "space_id" = $1 AND "slug" = 'wiki'`, [s.spaceId]),
    /wiki_topic_category_chk/u,
  );

  // A second plan seeds nothing more.
  const again = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/article-plan`);
  expectStatus(again, 200, 'a second plan');
  assert.equal(again.body.seeded, 0);
  assert.equal(await h.prisma.wikiTopic.count({ where: { spaceId: s.spaceId } }), WIKI_DEFAULT_TOPICS.length);

  // Membership, read off each topic's input.
  const database = await input(h, s.maintainer, s.spaceId, 'database');
  expectStatus(database, 200, 'the database topic\'s input');
  assert.deepEqual(new Set(inputIds(database)), new Set([s.e.dbPath, s.e.dbWords]),
    'the write-inventory pitfall is the database\'s by its path, though it names "sessions" and talks about sessions; the Prisma concept by its words');
  const sessions = await input(h, s.maintainer, s.spaceId, 'sessions');
  assert.deepEqual(inputIds(sessions), [], 'nothing is filed under sessions by the slug it names when its path says otherwise');
  assert.deepEqual(new Set(inputIds(await input(h, s.maintainer, s.spaceId, 'web-client'))), new Set([s.e.web, s.e.webPage]),
    'a convention by its scope, a pitfall by its anchor');
  assert.deepEqual(inputIds(await input(h, s.maintainer, s.spaceId, 'workflow-owner')), [s.e.declared], 'no path: the slug it names');
  assert.deepEqual(new Set(inputIds(await input(h, s.maintainer, s.spaceId, 'wiki'))), new Set([s.e.wikiAbs, s.e.wikiA, s.e.wikiB]),
    'a worktree\'s absolute path is read relative to the repository, and src/runner-go/wiki is longer than src/runner-go/');
  assert.deepEqual(inputIds(await input(h, s.maintainer, s.spaceId, 'runner')), [], 'the longest prefix wins');
  // Neither the tainted entry nor the proposal is in any topic.
  const everyInput = await Promise.all(WIKI_DEFAULT_TOPICS.map((topic) => input(h, s.maintainer, s.spaceId, topic.slug)));
  const filed = everyInput.flatMap(inputIds);
  assert.ok(!filed.includes(s.e.tainted), 'a tainted entry is not written from');
  assert.ok(!filed.includes(s.e.proposed), 'a proposal is not written from');
  assert.equal(filed.length, 8, 'each active untainted entry in exactly one topic');
  assert.equal(plan.body.entries, 8);
  assert.equal(plan.body.unassigned, 0);
  // The input carries what the writer needs: kind, fields, paths, and the fingerprint.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pathEntry = database.body.entries.find((entry: any) => toUuid(entry.id) === s.e.dbPath);
  assert.equal(pathEntry.kind, 'pitfall');
  assert.deepEqual(pathEntry.paths, ['src/apiserver/src/common/db-write-inventory.ts']);
  assert.equal(pathEntry.revision, 1);
  assert.match(database.body.entrySetSha256, /^[0-9a-f]{64}$/u);
  assert.equal(database.body.articleSha256, null, 'no article yet');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const planned = (slug: string) => plan.body.topics.find((t: any) => t.slug === slug);
  assert.equal(planned('database').changed, true, 'entries and no article: changed');
  assert.equal(planned('database').entryCount, 2);
  assert.equal(planned('sessions').changed, false, 'no entries: nothing to write');
  assert.equal(planned('database').entrySetSha256, database.body.entrySetSha256);

  // The steps in isolation: paths, then the slug named, then words.
  const members = assignTopics(
    [
      { id: 'a', revision: 1, title: 'x', summary: 'x', aliases: [], topics: ['beta'], paths: ['lib/alpha/one.ts', 'lib/beta/two.ts', 'lib/alpha/three.ts'] },
      { id: 'b', revision: 1, title: 'x', summary: 'x', aliases: [], topics: ['beta', 'alpha'], paths: [] },
      { id: 'c', revision: 1, title: 'gamma rays everywhere', summary: 'gamma', aliases: [], topics: [], paths: ['elsewhere/x.ts'] },
      { id: 'd', revision: 1, title: 'nothing', summary: 'nothing', aliases: [], topics: ['unknown'], paths: [] },
    ],
    [
      { slug: 'alpha', title: 'Alpha', description: null, pathPrefixes: ['lib/alpha/'] },
      { slug: 'beta', title: 'Beta', description: null, pathPrefixes: ['lib/beta/'] },
      { slug: 'gamma', title: 'Gamma', description: 'gamma rays', pathPrefixes: [] },
    ],
  );
  assert.equal(members.topicOf.get('a'), 'alpha', 'two votes beat one, and beat the slug it names');
  assert.equal(members.how.get('a'), 'paths');
  assert.equal(members.topicOf.get('b'), 'beta', 'the first slug it names that is a topic');
  assert.equal(members.how.get('b'), 'declared');
  assert.equal(members.topicOf.get('c'), 'gamma', 'no prefix claims its path: its words');
  assert.equal(members.how.get('c'), 'text');
  assert.equal(members.topicOf.has('d'), false, 'close to nothing: in no topic');
  assert.equal(members.unassigned, 1);

  // A pattern's claim: a prefix, which ending in / names the directory too; a * pattern, a suffix.
  assert.equal(pathClaim('src/web/src/lib/api.ts', 'src/web/'), 8);
  assert.equal(pathClaim('src/web', 'src/web/'), 8, 'an anchor at the directory itself');
  assert.equal(pathClaim('src/webhooks/x.ts', 'src/web/'), 0);
  assert.equal(pathClaim('ConsoleModel.swift', '*.swift'), 6, 'a bare file name, by its suffix');
  assert.equal(pathClaim('src/macos/OrbitApp/X.swift', '*.swift'), 6);
  assert.equal(pathClaim('anything', '*'), 0);
  // With the default topics: the longest claim wins, so a directory's prefix outranks a suffix, and
  // what the demo misfiled under sessions by its words goes where its code is.
  const defaults = WIKI_DEFAULT_TOPICS.map((topic) => ({ ...topic, description: topic.description, pathPrefixes: [...topic.pathPrefixes] }));
  const topicFor = (paths: string[]) => assignTopics([{ id: 'x', revision: 1, title: 'x', summary: 'x', aliases: [], topics: ['sessions'], paths }], defaults).topicOf.get('x');
  assert.equal(topicFor(['ConsoleModel.swift']), 'apple-clients');
  assert.equal(topicFor(['src/runner-go']), 'runner', 'the runner directory itself');
  assert.equal(topicFor(['src/runner-go/session_pool.go']), 'runner', 'the runner\'s own session code is the runner\'s, as the demo filed it');
  assert.equal(topicFor(['src/runner-go/wiki_verify_test.go']), 'wiki', 'src/runner-go/wiki is longer than *_test.go and src/runner-go/');
  assert.equal(topicFor(['src/runner-go/task_cli.go']), 'agent-tooling');
  assert.equal(topicFor(['src/apiserver/src/common/db-write-inventory.ts']), 'database');
  assert.equal(topicFor(['prisma/schema.prisma']), 'database', 'a path written from src/apiserver');
  assert.equal(topicFor(['scripts/pg-matrix-summary.lib.sh']), 'testing', 'scripts/pg-matrix- is longer than scripts/pg-');
  assert.equal(topicFor(['src/apiserver/Dockerfile']), 'deploy-ops');
  assert.equal(topicFor(['src/apiserver/src/main.ts']), 'sessions', 'no pattern claims the API server as a whole: the slug it names decides');

  // Sentences: code a model left outside backticks (a ?? b, a != b) ends nothing; a full stop, or an
  // ASCII ? after a word, followed by a space does, and its markers go with it.
  assert.deepEqual(splitSentences('lastTurnAt ?? createdAt 降序[1]。为什么? 因为[2]。a != b 时成立[3]！'),
    ['lastTurnAt ?? createdAt 降序[1]。', '为什么?', ' 因为[2]。', 'a != b 时成立[3]！']);
  assert.deepEqual(splitSentences('It holds. [2] Then `x?.y` stays whole[1].'), ['It holds. [2]', ' Then `x?.y` stays whole[1].']);
});

// ── 2. validation ───────────────────────────────────────────────────────────────────────────────

test('a write keeps only footnotes to the topic\'s entries, deletes a sentence left without one, and stops at 900 characters', { skip }, async () => {
  const h = await boot();
  const s = await setUp(h);
  await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/article-plan`);
  const database = await input(h, s.maintainer, s.spaceId, 'database');
  expectStatus(database, 200, 'the input');
  const dangling = randomUUID();
  const markdown = [
    '# 数据库写入治理',
    '',
    '写入清单登记每一处 Prisma 写入[1]。事务冲突时整段重跑[1][2]。',
    '这句话没有任何脚注。',
    '这句话引用了别的主题的条目[3]。',
    '这句话引用了不存在的条目[4]，也引用了越界的编号[9]。',
    '`arr[0]` 这样的代码不是脚注[2]。',
    '',
    '## 迁移',
    '',
    '- 迁移按号排列，合并前要核对撞号[2]。',
  ].join('\n');
  const before = h.published.length;
  const written = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/database`, writeBody(database.body.entrySetSha256, [{
    part: 0,
    kind: 'article',
    title: '数据库写入治理',
    markdown,
    // [1] and [2] the topic's; [3] another topic's; [4] no entry at all — in either spelling of an id.
    notes: [b62(s.e.dbPath), s.e.dbWords, b62(s.e.web), dangling],
  }]));
  expectStatus(written, 200, 'the maintenance run writes the database article');
  assert.equal(written.body.written, true);
  assert.equal(written.body.unchanged, false);
  assert.deepEqual(written.body.parts[0].stats, {
    sentences: 7,
    sentencesDeleted: 3,
    markers: 8,
    markersStripped: 3,
    sentencesTrimmed: 0,
    chars: written.body.parts[0].stats.chars,
    footnotes: 2,
  }, 'seven sentences, three deleted for want of a valid footnote; eight markers, three stripped');
  assert.equal(h.published.slice(before).filter((id) => id === s.spaceId).length, 1, 'a write is announced once');

  // What the owner reads.
  const article = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/articles/database`);
  expectStatus(article, 200, 'the owner reads the article');
  assert.equal(article.body.kind, 'article');
  assert.equal(article.body.title, '数据库写入治理');
  assert.deepEqual(article.body.topic, { slug: 'database', title: '数据库与 Prisma', category: 'data', categoryTitle: 'Data & backend' });
  assert.deepEqual(article.body.blocks, [
    {
      heading: null,
      sentences: [
        { text: '写入清单登记每一处 Prisma 写入。', notes: [1] },
        { text: '事务冲突时整段重跑。', notes: [1, 2] },
        { text: '`arr[0]` 这样的代码不是脚注。', notes: [2] },
      ],
    },
    { heading: '迁移', sentences: [{ text: '迁移按号排列，合并前要核对撞号。', notes: [2] }] },
  ]);
  const text = JSON.stringify(article.body.blocks);
  for (const gone of ['没有任何脚注', '别的主题', '不存在的条目']) assert.ok(!text.includes(gone), `the deleted sentence "${gone}" is not in the article`);
  // Footnotes resolve to the entries they name, by the entries' public ids.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.deepEqual(article.body.footnotes.map((f: any) => [f.n, f.entryId, f.revision, f.entry.title, f.entry.status]), [
    [1, b62(s.e.dbPath), 1, '会话写入前要登记写入清单', 'active'],
    [2, b62(s.e.dbWords), 1, 'Prisma 迁移之后先 generate', 'active'],
  ]);
  assert.match(article.body.footnotes[0].entry.summary, /db-write-inventory/u);
  assert.equal(article.body.entryCount, 2);
  assert.equal(article.body.ref, '0123456789abcdef0123456789abcdef01234567');
  assert.equal(article.body.model, 'qwen3.8-27b-fp8');
  assert.equal(article.body.overview, null);
  assert.deepEqual(article.body.parts, []);

  // Past 900 characters the tail of the longest block goes, and the lead stays.
  const web = await input(h, s.maintainer, s.spaceId, 'web-client');
  const long = (n: number) => `这是一句关于 Web 客户端请求约定的长句，第 ${n} 句，它解释 lib 模块为什么一律走 api 模块发请求而不是直接调用 fetch，这样测试才能统一拦截[${n % 2 === 0 ? 1 : 2}]。`;
  const lead = '导语只有一句，说明本文讲 Web 客户端的请求约定[1]。';
  const body = ['# Web 客户端请求约定', lead, '## 约定', ...Array.from({ length: 8 }, (_u, i) => long(i + 1)), '## 常见的坑', ...Array.from({ length: 6 }, (_u, i) => long(i + 20))].join('\n');
  const capped = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/web-client`, writeBody(web.body.entrySetSha256, [{
    part: 0, kind: 'article', title: 'Web 客户端请求约定', markdown: body, notes: [s.e.web, s.e.webPage],
  }]));
  expectStatus(capped, 200, 'a long article is written');
  const stats = capped.body.parts[0].stats;
  assert.ok(stats.sentencesTrimmed > 0, 'sentences were cut');
  assert.ok(stats.chars <= 900, `the article is at most 900 characters: ${stats.chars}`);
  assert.ok(stats.chars > 900 - 100, 'and no more was cut than it took');
  const cappedView = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/articles/web-client`);
  expectStatus(cappedView, 200, 'the capped article');
  assert.equal(cappedView.body.blocks[0].sentences[0].text, '导语只有一句，说明本文讲 Web 客户端的请求约定。', 'the lead stays');
  assert.equal(cappedView.body.chars, stats.chars);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const kept = cappedView.body.blocks.reduce((n: number, b: any) => n + b.sentences.reduce((m: number, x: any) => m + [...x.text].length, 0), 0);
  assert.equal(kept, stats.chars, 'what is stored is what was counted');
});

// ── 3. regeneration: the entry set decides ──────────────────────────────────────────────────────

test('an entry set that did not change is not written again; one that changed is; one that moved mid-write is refused', { skip }, async () => {
  const h = await boot();
  const s = await setUp(h);
  const topic = await h.prisma.wikiTopic.findFirstOrThrow({ where: { spaceId: s.spaceId, slug: 'workflow-owner' }, select: { id: true } });
  const first = await input(h, s.maintainer, s.spaceId, 'workflow-owner');
  const sha1 = first.body.entrySetSha256 as string;
  const one = (text: string) => [{ part: 0, kind: 'article', title: '与 owner 协作', markdown: `# 与 owner 协作\n${text}[1]。`, notes: [s.e.declared] }];
  const written = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/workflow-owner`, writeBody(sha1, one('回复一律用中文')));
  expectStatus(written, 200, 'the first write');
  assert.equal(written.body.written, true);
  const stored = await h.prisma.wikiTopicSummary.findFirstOrThrow({ where: { topicId: topic.id, part: 0 } });
  assert.equal(stored.entrySetSha256, sha1);

  // The same entries: the plan says unchanged, and a write rewrites nothing.
  const plan = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/article-plan`);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const planned = plan.body.topics.find((t: any) => t.slug === 'workflow-owner');
  assert.equal(planned.changed, false, 'the article was written from exactly these entries');
  assert.equal(planned.articleSha256, sha1);
  const before = h.published.length;
  const again = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/workflow-owner`, writeBody(sha1, one('这次写了别的话')));
  expectStatus(again, 200, 'a write from the same entries');
  assert.equal(again.body.unchanged, true);
  assert.equal(again.body.written, false);
  const still = await h.prisma.wikiTopicSummary.findFirstOrThrow({ where: { topicId: topic.id, part: 0 } });
  assert.equal(still.id, stored.id, 'the row is the one written first');
  assert.equal(still.generatedAt.getTime(), stored.generatedAt.getTime());
  assert.deepEqual(still.body, stored.body, 'and says what it said');
  assert.equal(h.published.length, before, 'nothing written, nothing announced');

  // The entry changes: the owner amends it. The plan sees it, and a write from the new set rewrites.
  const amended = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/changesets`, {
    rationale: 'the owner sharpens it',
    ops: [{ op: 'amend', entryId: s.e.declared, baseRevision: 1, changes: { summary: 'owner 读中文，回复、评论和提交说明一律用中文。' } }],
  });
  expectStatus(amended, 200, 'the owner amends the entry');
  const replan = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/article-plan`);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const changed = replan.body.topics.find((t: any) => t.slug === 'workflow-owner');
  assert.equal(changed.changed, true, 'an amended entry changes the set');
  assert.notEqual(changed.entrySetSha256, sha1);
  const second = await input(h, s.maintainer, s.spaceId, 'workflow-owner');
  const sha2 = second.body.entrySetSha256 as string;
  assert.equal(sha2, changed.entrySetSha256);
  assert.equal(second.body.articleSha256, sha1);

  // A write that names the stored set is still unchanged; one that names neither set is stale.
  const old = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/workflow-owner`, writeBody(sha1, one('旧的')));
  assert.equal(old.body.unchanged, true);
  const stale = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/workflow-owner`,
    writeBody(createHash('sha256').update('another set').digest('hex'), one('读的不是现在的条目')));
  expectStatus(stale, 409, 'a write from entries the topic no longer has');
  assert.equal(stale.body.code, 'WIKI_ARTICLE_STALE');
  assert.equal((await h.prisma.wikiTopicSummary.findFirstOrThrow({ where: { topicId: topic.id, part: 0 } })).id, stored.id, 'nothing written');

  const rewritten = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/workflow-owner`, writeBody(sha2, one('回复、评论和提交说明一律用中文')));
  expectStatus(rewritten, 200, 'the write from the changed set');
  assert.equal(rewritten.body.written, true);
  const replaced = await h.prisma.wikiTopicSummary.findMany({ where: { topicId: topic.id } });
  assert.equal(replaced.length, 1, 'the topic\'s rows were replaced, not added to');
  assert.notEqual(replaced[0].id, stored.id);
  assert.equal(replaced[0].entrySetSha256, sha2);
  assert.deepEqual(replaced[0].citations, [{ n: 1, entryId: s.e.declared, revision: 2 }], 'cited at the revision it was written from');
  const final = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/article-plan`);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.equal(final.body.topics.find((t: any) => t.slug === 'workflow-owner').changed, false);
});

// ── 4. a split topic ────────────────────────────────────────────────────────────────────────────

test('a split topic is an overview and its subtopic parts; a part with no footnote left is dropped', { skip }, async () => {
  const h = await boot();
  const s = await setUp(h);
  const wiki = await input(h, s.maintainer, s.spaceId, 'wiki');
  const written = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/wiki`, writeBody(wiki.body.entrySetSha256, [
    { part: 0, kind: 'overview', title: 'Wiki 模块', markdown: '# Wiki\n本主题讲 Wiki 的写入与维护[1]。核实调用不开 thinking[2]。', notes: [s.e.wikiA, s.e.wikiAbs] },
    // A subtopic may cite any entry of its topic, not only its own group's.
    { part: 1, kind: 'subtopic', title: 'Articles and dossiers', markdown: '# Articles\n文章写入只认维护会话[1]。案卷先脱敏再截断[2]。', notes: [s.e.wikiA, s.e.wikiB], entries: [s.e.wikiA, b62(s.e.wikiAbs)] },
    // An entry of another topic in the group is dropped from it, and a part whose every footnote goes is dropped whole.
    { part: 2, kind: 'subtopic', title: 'Nothing survives here', markdown: '这里的脚注都指向别的主题[1]。', notes: [s.e.web], entries: [s.e.wikiB, s.e.dbPath] },
  ]));
  expectStatus(written, 200, 'an overview with its parts');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.deepEqual(written.body.parts.map((p: any) => [p.part, p.kept]), [[0, true], [1, true], [2, false]]);

  const overview = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/articles/wiki`);
  expectStatus(overview, 200, 'the overview');
  assert.equal(overview.body.kind, 'overview');
  assert.deepEqual(overview.body.parts, [{ part: 1, kind: 'subtopic', title: 'Articles and dossiers', entryCount: 2 }], 'the dropped part is not listed');
  assert.equal(overview.body.entryCount, 3, 'the overview is written from the whole topic');
  const part = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/articles/wiki/1`);
  expectStatus(part, 200, 'subtopic part 1');
  assert.equal(part.body.kind, 'subtopic');
  assert.deepEqual(part.body.overview, { part: 0, kind: 'overview', title: 'Wiki 模块', entryCount: 3 });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.deepEqual(part.body.footnotes.map((f: any) => f.entryId), [b62(s.e.wikiA), b62(s.e.wikiB)]);
  const stored = await h.prisma.wikiTopicSummary.findMany({ where: { ownerId: s.owner.id, topic: { spaceId: s.spaceId, slug: 'wiki' } }, orderBy: { part: 'asc' } });
  assert.equal(stored.length, 2);
  assert.equal(stored[1].parentId, stored[0].id, 'a subtopic part hangs on its overview');
  assert.deepEqual(new Set(stored[1].entryIds), new Set([s.e.wikiA, s.e.wikiAbs]));
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/articles/wiki/2`), 404, 'the dropped part');

  // The directory: six categories in order, each topic with its article and parts.
  const directory = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/articles`);
  expectStatus(directory, 200, 'the directory');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.deepEqual(directory.body.categories.map((c: any) => [c.key, c.title]), CONTRACT.articles.categories.map((c: any) => [c.key, c.title]));
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const platform = directory.body.categories.find((c: any) => c.key === 'platform');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.deepEqual(platform.topics.map((t: any) => t.slug), ['sessions', 'tasks', 'projects', 'watches-wakeups', 'wiki']);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const wikiTopic = platform.topics.find((t: any) => t.slug === 'wiki');
  assert.equal(wikiTopic.title, 'Wiki');
  assert.equal(wikiTopic.article.kind, 'overview');
  assert.deepEqual(wikiTopic.parts, [{ part: 1, kind: 'subtopic', title: 'Articles and dossiers', entryCount: 2 }]);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.equal(platform.topics.find((t: any) => t.slug === 'sessions').article, null, 'a topic with no article yet');
  assert.deepEqual(directory.body.uncategorized, []);

  // The index: every article, A to Z.
  const index = await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/article-index`);
  expectStatus(index, 200, 'the index');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const titles = index.body.items.map((item: any) => item.title);
  assert.ok(titles.includes('Articles and dossiers') && titles.includes('Wiki 模块'));
  assert.deepEqual(titles, [...titles].sort((a: string, b: string) => (a.toLowerCase() < b.toLowerCase() ? -1 : a.toLowerCase() > b.toLowerCase() ? 1 : 0)));
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const item = index.body.items.find((i: any) => i.title === 'Articles and dossiers');
  assert.deepEqual([item.initial, item.part, item.kind, item.topic.slug, item.entryCount], ['A', 1, 'subtopic', 'wiki', 2]);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.equal(index.body.items.find((i: any) => i.title === 'Wiki 模块').initial, 'W');
});

// ── 5. a view: not pushed, not a source, not an agent's search or get ─────────────────────────────

test('an article is a view: not in the push block, never a source, and not what an agent\'s search or get returns', { skip }, async () => {
  const h = await boot();
  const s = await setUp(h);
  const topic = 'git-worktrees';
  // An entry of its own, and an article whose words appear nowhere else.
  const [anchored] = await ownerAdds(h, s.owner, s.spaceId, [
    convention('worktree 里先铺 overlay', '新 worktree 先跑 worktree-overlay.sh 再编译。', 'scripts/worktree-overlay.sh'),
  ]);
  const own = await input(h, s.maintainer, s.spaceId, topic);
  assert.deepEqual(inputIds(own), [anchored]);
  const phrase = '紫色长颈鹿只在这篇文章里出现';
  const written = await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/${topic}`, writeBody(own.body.entrySetSha256, [
    { part: 0, kind: 'article', title: 'Worktree overlay', markdown: `# Worktree\n${phrase}，新 worktree 先铺 overlay[1]。`, notes: [anchored] },
  ]));
  expectStatus(written, 200, 'the article');
  const article = await h.prisma.wikiTopicSummary.findFirstOrThrow({ where: { ownerId: s.owner.id, topic: { spaceId: s.spaceId, slug: topic } } });

  // The push: an ordinary session of the bound workspace is handed entries, and nothing of the article.
  const pushed = await h.prisma.$transaction((tx) => appendWikiContext(tx, {
    sessionId: s.ordinary,
    turnId: randomUUID(),
    leaseGeneration: randomUUID(),
    ownerId: s.owner.id,
    workspaceId: s.ws,
    taskId: null,
    task: null,
    dispatchOrigin: null,
    content: 'worktree overlay 与 Web 客户端请求约定',
  }, ON));
  assert.ok(pushed && pushed.includes('<orbit_wiki_context'), `the session is pushed its space's entries: ${String(pushed).slice(0, 300)}`);
  assert.ok(pushed.includes(`orbit-wiki:${b62(anchored)}`), 'the entry the article was written from is pushed as an entry');
  assert.ok(!pushed.includes(phrase), 'no sentence of the article is in the block');
  assert.ok(!pushed.includes(b62(article.id)) && !pushed.includes(article.id), 'nor its id');
  const exposures = await h.prisma.wikiExposure.findMany({ where: { sessionId: s.ordinary }, select: { entryId: true } });
  assert.ok(exposures.length > 0);
  const entryIds = new Set((await h.prisma.wikiEntry.findMany({ where: { spaceId: s.spaceId }, select: { id: true } })).map((e) => e.id));
  for (const exposure of exposures) assert.ok(entryIds.has(exposure.entryId), 'every line pushed is an entry');

  // A source: citing the article, in any kind a source can take, does not resolve.
  for (const kind of ['note', 'task', 'event', 'turn', 'tool_call', 'task_comment']) {
    const cited = await call(h, { runner: s.runner.token, session: s.ordinary }, 'POST', '/runner/wiki/changesets', {
      rationale: 'citing an article',
      idempotencyKey: `cite-article-${kind}-${randomUUID()}`,
      ops: [{ op: 'add', entry: concept(`Worktree overlay as the article says ${kind}`, '文章说要先铺 overlay。'), sources: [{ kind, ref: b62(article.id) }] }],
    });
    expectStatus(cited, 422, `an article cited as a ${kind} source`);
    assert.equal(cited.body.ops[0].status, 'refused');
    assert.equal(cited.body.ops[0].reasons[0].code, 'WIKI_SOURCE_UNRESOLVED', `an article is never a ${kind} source`);
  }
  // Nor as the owner's, whose writes may cite nothing but whose citations must resolve all the same.
  const ownerCites = await call(h, { bearer: s.owner.bearer }, 'POST', `/wiki/spaces/${s.spaceId}/changesets`, {
    rationale: 'the owner cites an article',
    ops: [{ op: 'add', entry: concept('Overlay per the article', '按文章说的做。'), sources: [{ kind: 'task', ref: article.id }] }],
  });
  expectStatus(ownerCites, 422, 'the owner cites the article');
  assert.equal(ownerCites.body.ops[0].reasons[0].code, 'WIKI_SOURCE_UNRESOLVED');

  // An agent's search and get: entries only.
  const search = await call(h, { runner: s.runner.token, session: s.ordinary }, 'GET', `/runner/wiki/search?q=${encodeURIComponent(phrase)}`);
  expectStatus(search, 200, 'an agent searches for the article\'s own words');
  // The answer echoes the query back as `q`: what it found is `hits`, and that is where the article is not.
  const hits = JSON.stringify(search.body.hits);
  assert.ok(Array.isArray(search.body.hits), 'the answer lists its hits');
  assert.ok(!hits.includes(phrase) && !hits.includes(b62(article.id)), `the article is not a hit: ${hits.slice(0, 300)}`);
  const overlay = await call(h, { runner: s.runner.token, session: s.ordinary }, 'GET', `/runner/wiki/search?q=${encodeURIComponent('worktree overlay')}`);
  expectStatus(overlay, 200, 'an agent searches for the topic');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const found: any[] = overlay.body.hits ?? overlay.body.items ?? overlay.body;
  assert.ok(Array.isArray(found) && found.length > 0, `the entry is found: ${JSON.stringify(overlay.body).slice(0, 300)}`);
  for (const hit of found) assert.ok(entryIds.has(toUuid(hit.id as string)), 'every hit is an entry');
  const get = await call(h, { runner: s.runner.token, session: s.ordinary }, 'GET', `/runner/wiki/entries/${b62(article.id)}`);
  expectStatus(get, 404, 'an agent gets the article by its id');
});

// ── 6. who writes ───────────────────────────────────────────────────────────────────────────────

test('only a maintenance run of the space, or the server\'s own import, writes articles', { skip }, async () => {
  const h = await boot();
  const s = await setUp(h);
  const own = await input(h, s.maintainer, s.spaceId, 'workflow-owner');
  const body = writeBody(own.body.entrySetSha256, [{ part: 0, kind: 'article', title: 'x', markdown: '用中文回复[1]。', notes: [s.e.declared] }]);
  const routes: Array<[string, string, unknown?]> = [
    ['POST', `/runner/wiki/spaces/${s.spaceId}/article-plan`],
    ['GET', `/runner/wiki/spaces/${s.spaceId}/articles/workflow-owner/input`],
    ['POST', `/runner/wiki/spaces/${s.spaceId}/articles/workflow-owner`, body],
  ];

  // An ordinary session of the owner, on the owner's runner, in the bound workspace.
  for (const [method, route, payload] of routes) {
    const answer = await call(h, { runner: s.runner.token, session: s.ordinary }, method, route, payload);
    expectStatus(answer, 403, `an ordinary session: ${method} ${route}`);
    assert.equal(answer.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
  }
  // Headless: no session at all.
  for (const [method, route, payload] of routes) {
    expectStatus(await call(h, { runner: s.runner.token }, method, route, payload), 400, `headless: ${method} ${route}`);
  }
  // A maintenance run of another space of the same owner.
  const otherWs = await workspace(h, s.owner.id);
  const otherSpace = await space(h, s.owner, otherWs, 'Another space of the owner');
  const otherRun = await maintenanceRun(h, s.owner, otherSpace, otherWs, s.runner.id);
  for (const [method, route, payload] of routes) {
    const answer = await call(h, { runner: s.runner.token, session: otherRun }, method, route, payload);
    expectStatus(answer, 403, `another space's maintenance run: ${method} ${route}`);
    assert.equal(answer.body.code, 'WIKI_NOT_MAINTENANCE_SESSION');
  }
  // Another owner's maintenance run, on their own runner, against this space: a plain 404.
  const stranger = await account(h, 'stranger');
  const theirRunner = await runner(h, stranger.id);
  const theirWs = await workspace(h, stranger.id);
  const theirSpace = await space(h, stranger, theirWs, 'The stranger\'s space');
  const theirRun = await maintenanceRun(h, stranger, theirSpace, theirWs, theirRunner.id);
  for (const [method, route, payload] of routes) {
    expectStatus(await call(h, { runner: theirRunner.token, session: theirRun }, method, route, payload), 404, `another owner: ${method} ${route}`);
  }
  // The user door has no route that writes an article, for the owner or anybody.
  for (const method of ['POST', 'PUT', 'PATCH']) {
    expectStatus(await call(h, { bearer: s.owner.bearer }, method, `/wiki/spaces/${s.spaceId}/articles/workflow-owner`, body), 404,
      `the owner ${method}s an article on the user door`);
  }
  assert.equal(await h.prisma.wikiTopicSummary.count({ where: { topic: { spaceId: s.spaceId, slug: 'workflow-owner' }, entrySetSha256: own.body.entrySetSha256, title: 'x' } }), 0,
    'none of them wrote anything');

  // In the server's own process: the import principal writes; the owner's and an agent's do not.
  const importer: WikiPrincipal = { origin: 'import', ownerId: s.owner.id, userId: null, sessionId: null, toolCallId: null, authorKind: 'system' };
  const refusedAs = async (principal: WikiPrincipal, why: string) => {
    await assert.rejects(h.articles.write(principal, s.spaceId, 'workflow-owner', body), (error: unknown) => {
      assert.ok(error instanceof WikiRefusalError, `${why}: refused with a wiki code, not ${String(error)}`);
      assert.equal(error.refusal.code, 'WIKI_NOT_MAINTENANCE_SESSION', why);
      return true;
    });
  };
  await refusedAs({ origin: 'owner', ownerId: s.owner.id, userId: s.owner.id, sessionId: null, toolCallId: null }, 'the owner principal');
  await refusedAs({ origin: 'agent', ownerId: s.owner.id, userId: null, sessionId: s.ordinary, toolCallId: null }, 'an agent');
  await refusedAs({ origin: 'maintenance', ownerId: s.owner.id, userId: null, sessionId: s.ordinary, toolCallId: null }, 'an ordinary session calling itself maintenance');
  await refusedAs({ origin: 'import', ownerId: s.owner.id, userId: null, sessionId: s.ordinary, toolCallId: null }, 'an import that carries a session');
  await assert.rejects(h.articles.write({ ...importer, ownerId: stranger.id }, s.spaceId, 'workflow-owner', body), /no such wiki space/u,
    'the import principal of another owner does not find this space');

  const planned = await h.articles.plan(importer, s.spaceId);
  assert.equal(planned.spaceId, s.spaceId);
  const fromImport = await h.articles.input(importer, s.spaceId, 'workflow-owner');
  const imported = await h.articles.write(importer, s.spaceId, 'workflow-owner', writeBody(fromImport.entrySetSha256, [
    { part: 0, kind: 'article', title: '与 owner 协作（导入）', markdown: 'owner 读中文，回复一律用中文[1]。', notes: [s.e.declared] },
  ]));
  assert.equal(imported.written || imported.unchanged, true, 'the import writes (or finds the articles already written from these entries)');
});

// ── 7. tenancy ──────────────────────────────────────────────────────────────────────────────────

test('another owner reads none of it: every read is a 404', { skip }, async () => {
  const h = await boot();
  const s = await setUp(h);
  // Make sure there is something to read.
  const own = await input(h, s.maintainer, s.spaceId, 'web-client');
  await call(h, s.maintainer, 'POST', `/runner/wiki/spaces/${s.spaceId}/articles/web-client`, writeBody(own.body.entrySetSha256, [
    { part: 0, kind: 'article', title: 'Web 客户端', markdown: 'lib 里一律走 api 模块[1]。', notes: [s.e.web] },
  ]));
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/articles/web-client`), 200, 'the owner reads it');

  const stranger = await account(h, 'reader from elsewhere');
  const reads = [
    `/wiki/spaces/${s.spaceId}/articles`,
    `/wiki/spaces/${s.spaceId}/articles/web-client`,
    `/wiki/spaces/${s.spaceId}/articles/web-client/1`,
    `/wiki/spaces/${s.spaceId}/article-index`,
  ];
  for (const route of reads) {
    const answer = await call(h, { bearer: stranger.bearer }, 'GET', route);
    expectStatus(answer, 404, `another owner reads ${route}`);
    assert.ok(!JSON.stringify(answer.body).includes('Web 客户端'), 'and learns nothing of it');
  }
  // Their own space with the same slugs is theirs alone, and empty.
  const theirWs = await workspace(h, stranger.id);
  const theirSpace = await space(h, stranger, theirWs, 'The reader\'s own space');
  const theirs = await call(h, { bearer: stranger.bearer }, 'GET', `/wiki/spaces/${theirSpace}/articles`);
  expectStatus(theirs, 200, 'their own directory');
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  assert.equal(theirs.body.categories.flatMap((c: any) => c.topics).length, 0, 'a space nobody planned has no topic');
  expectStatus(await call(h, { bearer: stranger.bearer }, 'GET', `/wiki/spaces/${theirSpace}/articles/web-client`), 404, 'no such topic in their space');
  // And the owner's own address mistakes are 404s too.
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/articles/no-such-topic`), 404, 'an unknown topic');
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${s.spaceId}/articles/sessions`), 404, 'a topic with no article yet');
  expectStatus(await call(h, { bearer: s.owner.bearer }, 'GET', `/wiki/spaces/${randomUUID()}/articles`), 404, 'an unknown space');
});
