/**
 * Orbit Wiki's retrieval, over real HTTP and against a real PostgreSQL.
 *
 * What is under test is what a caller gets back — the entries, why each one matched, and the order
 * — so every request goes through the real controllers, the real WikiRetrieval and WikiService, the
 * global ValidationPipe and the public-id interceptor, and every fixture is written through the
 * doors a client uses. Only the two credential checks are stood in for (`JwtService.verifyAsync`
 * answers with the account a bearer was issued to, and the runner guard reads the runner row this
 * file wrote), which is what `wiki-api.pg.spec.ts` stands in for and for the same reason.
 *
 * The design is §6 and the contract is `searchMatches`; each case below is one of the behaviours
 * this task's acceptance criteria names: a Chinese query reaching a Chinese entry, a Chinese word
 * reaching an entry whose only Chinese is an alias, a path reaching an entry through its anchor or
 * its pitfall trigger, an entry that both legs found ranking above one only the keyword leg did,
 * tenant and space isolation on both doors, the match reasons the contract lists, and the semantic
 * placeholder changing nothing.
 *
 *     bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-search.pg.spec.ts
 *
 * Not destructive: every id is generated by the run, and every fixture belongs to an account the run
 * created.
 */
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { after, test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import type { PrismaClient } from '@prisma/client';
import { WIKI_LIMITS, toUuid, type WikiAnchorState, type WikiSearchMatch, type WikiTrust } from '@orbit/shared';
import { Client } from 'pg';

import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { RunnerAuthGuard } from '../runner-api/runner-auth.guard';
import { RunnerWikiController } from '../runner-api/runner-wiki.controller';
import { WikiController } from './wiki.controller';
import { compareRanked, looksLikePath, pathQueries, rrfFuse, usageOf, WikiRetrieval } from './wiki-retrieval';
import { WikiService } from './wiki.service';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

interface Harness {
  base: string;
  sql: Client;
  prisma: PrismaClient;
  app: INestApplication;
  /** bearer → the account it was issued to */
  bearers: Map<string, string>;
}

let harness: Promise<Harness> | undefined;

function boot(): Promise<Harness> {
  harness ??= (async () => {
    assertCoordinatorPgUrlIsIsolated(URL);
    const sql = new Client({ connectionString: URL, connectionTimeoutMillis: 5_000 });
    await sql.connect();
    await verifyCoordinatorPgIdentity(sql);
    const prisma = prismaClientFor(URL);
    const bearers = new Map<string, string>();

    @Module({
      controllers: [WikiController, RunnerWikiController],
      providers: [
        { provide: WikiService, useValue: new WikiService(prisma as unknown as PrismaService) },
        { provide: WikiRetrieval, useValue: new WikiRetrieval(prisma as unknown as PrismaService) },
        { provide: PrismaService, useValue: prisma },
        RunnerAuthGuard,
        JwtAuthGuard,
        Reflector,
        {
          provide: JwtService,
          useValue: {
            verifyAsync: async (token: string) => {
              const sub = bearers.get(token);
              if (!sub) throw new Error('not a bearer this run issued');
              return { sub, email: `${sub}@wiki.invalid` };
            },
          },
        },
      ],
    })
    class WikiSearchModule {}

    const app = await NestFactory.create(WikiSearchModule, { logger: false, abortOnError: false });
    app.setGlobalPrefix('api');
    app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
    app.useGlobalInterceptors(new PublicIdInterceptor());
    await app.listen(0, '127.0.0.1');
    return { base: await app.getUrl(), sql, prisma, app, bearers };
  })();
  return harness;
}

after(async () => {
  if (!harness) return;
  const { app, prisma, sql } = await harness;
  await app.close().catch(() => undefined);
  await prisma.$disconnect().catch(() => undefined);
  await sql.end().catch(() => undefined);
});

// ── requests ────────────────────────────────────────────────────────────────────────────────────

interface Answer {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any;
}

interface Caller {
  bearer?: string;
  runner?: string;
  headers?: Record<string, string>;
}

async function call(h: Harness, who: Caller, method: string, route: string, body?: unknown): Promise<Answer> {
  const headers: Record<string, string> = { 'content-type': 'application/json', ...(who.headers ?? {}) };
  if (who.bearer) headers.authorization = `Bearer ${who.bearer}`;
  if (who.runner) headers['x-runner-token'] = who.runner;
  const response = await fetch(`${h.base}/api${route}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed: unknown = null;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    parsed = { unparsed: text };
  }
  return { status: response.status, body: parsed };
}

function expectStatus(answer: Answer, status: number, why: string): void {
  assert.equal(answer.status, status, `${why}: answered ${answer.status} ${JSON.stringify(answer.body)}`);
}

/** The owner door's search: `q` first, then whatever narrows it. */
async function ownerSearch(h: Harness, who: Account, query: Record<string, string>): Promise<Answer> {
  const answer = await call(h, { bearer: who.bearer }, 'GET', `/wiki/search?${new URLSearchParams(query)}`);
  expectStatus(answer, 200, `the owner searches for ${JSON.stringify(query)}`);
  return answer;
}

/** The runner door's search, on behalf of the session whose header it carries. */
async function sessionSearch(
  h: Harness,
  machine: Machine,
  sessionId: string,
  query: Record<string, string>,
): Promise<Answer> {
  const answer = await call(
    h,
    { runner: machine.token, headers: { 'x-orbit-session-id': sessionId } },
    'GET',
    `/runner/wiki/search?${new URLSearchParams(query)}`,
  );
  expectStatus(answer, 200, `the session searches for ${JSON.stringify(query)}`);
  return answer;
}

interface Hit {
  id: string;
  kind: string;
  title: string;
  summary: string;
  trust: string;
  anchorState: string;
  match: string[];
  score: number;
}

const hitsOf = (answer: Answer): Hit[] => answer.body.hits as Hit[];

/** The one hit for an entry, and the honest failure when it is not there at all. */
function hitFor(answer: Answer, id: string, what: string): Hit {
  const hit = hitsOf(answer).find((candidate) => candidate.id === id);
  assert.ok(hit, `${what}: expected ${id}, got ${JSON.stringify(answer.body.hits)}`);
  return hit!;
}

// ── fixtures ────────────────────────────────────────────────────────────────────────────────────

interface Account {
  id: string;
  bearer: string;
}

async function account(h: Harness, name: string): Promise<Account> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "user"("id","email","name","password_hash") VALUES ($1,$2,$3,'x')`, [
    id,
    `wiki-search-${id}@wiki.invalid`,
    name,
  ]);
  h.bearers.set(`bearer-${id}`, id);
  return { id, bearer: `bearer-${id}` };
}

interface Machine {
  id: string;
  token: string;
}

async function runner(h: Harness, ownerId: string): Promise<Machine> {
  const id = randomUUID();
  const token = `runner-${id}`;
  const tokenHash = createHash('sha256').update(token).digest('hex');
  await h.sql.query(`INSERT INTO "runner"("id","name","owner_id","token_hash") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    tokenHash,
  ]);
  return { id, token };
}

async function workspace(h: Harness, ownerId: string, repoUrl: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(`INSERT INTO "workspace"("id","name","owner_id","repo_url") VALUES ($1,'spec',$2,$3)`, [
    id,
    ownerId,
    repoUrl,
  ]);
  return id;
}

async function session(h: Harness, ownerId: string, workspaceId: string, runnerId: string, title: string): Promise<string> {
  const id = randomUUID();
  await h.sql.query(
    `INSERT INTO "session"("id","title","prompt","owner_id","creator_id","workspace_id","assigned_runner_id","updated_at")
     VALUES ($1,$2,'p',$3,$3,$4,$5,now())`,
    [id, title, ownerId, workspaceId, runnerId],
  );
  return id;
}

/** A conversation turn the wiki may cite, which is what an agent's proposal has to cite. */
async function turn(h: Harness, sessionId: string, seq: number, content: string): Promise<void> {
  await h.sql.query(
    `INSERT INTO "conversation_turn"("id","session_id","seq","client_turn_id","content","status")
     VALUES ($1,$2,$3,$4,$5,'ANSWERED')`,
    [randomUUID(), sessionId, seq, `turn-${seq}-${randomUUID()}`, content],
  );
}

/** A space the owner makes through the door, so the fixture is exercised the way a client uses it. */
async function space(h: Harness, who: Account, repoUrl: string): Promise<string> {
  const answer = await call(h, { bearer: who.bearer }, 'POST', '/wiki/spaces', {
    title: 'The orbit repository',
    repoUrl,
  });
  expectStatus(answer, 201, 'the owner creates a space');
  return answer.body.id as string;
}

/** An entry the owner writes themselves, which applies at once and is trusted as theirs. */
async function ownerEntry(h: Harness, who: Account, spaceId: string, entry: Record<string, unknown>): Promise<string> {
  const answer = await call(h, { bearer: who.bearer }, 'POST', `/wiki/spaces/${spaceId}/changesets`, {
    rationale: 'the owner records what this codebase knows',
    ops: [{ op: 'add', entry }],
  });
  expectStatus(answer, 200, `the owner records ${String(entry.title)}`);
  const ops = answer.body.ops as Array<{ status: string; entryId: string }>;
  assert.equal(ops[0]?.status, 'applied', `the owner's own write applies at once: ${JSON.stringify(answer.body)}`);
  return ops[0].entryId;
}

/** An agent's proposal, which waits for Review — the entry exists and is not yet anyone's. */
async function proposedEntry(
  h: Harness,
  machine: Machine,
  sessionId: string,
  entry: Record<string, unknown>,
): Promise<string> {
  const answer = await call(
    h,
    { runner: machine.token, headers: { 'x-orbit-session-id': sessionId } },
    'POST',
    '/runner/wiki/changesets',
    {
      rationale: 'the session records what it learned',
      ops: [{ op: 'add', entry, sources: [{ kind: 'turn', session: 'self' }] }],
    },
  );
  expectStatus(answer, 200, `the session proposes ${String(entry.title)}`);
  const ops = answer.body.ops as Array<{ status: string; entryId: string }>;
  assert.equal(ops[0]?.status, 'pending', `an agent's proposal waits: ${JSON.stringify(answer.body)}`);
  return ops[0].entryId;
}

// ── the rules that need no database ─────────────────────────────────────────────────────────────

/**
 * The fusion and the ordering, asserted on their own: the same functions the door runs, with no
 * rows in the way. The cases below are the ones a database cannot show as cleanly as a diff can —
 * an entry two legs found against one that one leg found, and the tiebreak chain, which needs two
 * fused scores to be EQUAL before it applies at all.
 */
test('the fusion and the tiebreak order hits the way the design says', () => {
  // RRF with k=60: a leg's first hit is worth 1/61, and being found twice is worth both.
  const fused = rrfFuse([
    { match: 'keyword', ids: ['both', 'keyword-only'] },
    { match: 'path', ids: ['both', 'path-only'] },
  ]);
  assert.deepEqual(
    fused.map((hit) => [hit.id, hit.match]),
    [
      ['both', ['keyword', 'path']],
      ['keyword-only', ['keyword']],
      ['path-only', ['path']],
    ],
  );
  assert.equal(fused[0].score, 2 / 61, 'first in both legs');
  assert.equal(fused[1].score, 1 / 62, 'second in the keyword leg');
  assert.equal(fused[2].score, 1 / 62, 'second in the path leg: a tie with the one above');

  // The tie, decided the way §6.1 says: trust, then anchor state, then use, then recency.
  const tied = (
    id: string,
    over: { trust: WikiTrust; anchorState: WikiAnchorState; stats: Record<string, number>; changedAt: Date | null },
  ) => ({ id, score: 1 / 62, match: ['keyword'] as WikiSearchMatch[], ...over });
  assert.equal(
    compareRanked(
      tied('a', { trust: 'owner', anchorState: 'missing', stats: {}, changedAt: null }),
      tied('b', { trust: 'confirmed', anchorState: 'verified', stats: { gets: 9 }, changedAt: new Date() }),
    ) < 0,
    true,
    'trust comes before everything else',
  );
  assert.equal(
    compareRanked(
      tied('a', { trust: 'confirmed', anchorState: 'verified', stats: {}, changedAt: null }),
      tied('b', { trust: 'confirmed', anchorState: 'unchecked', stats: { gets: 9 }, changedAt: new Date() }),
    ) < 0,
    true,
    'then the anchor state',
  );
  assert.equal(
    compareRanked(
      tied('a', { trust: 'confirmed', anchorState: 'unchecked', stats: { searchHits: 1, gets: 1 }, changedAt: null }),
      tied('b', { trust: 'confirmed', anchorState: 'unchecked', stats: { gets: 1 }, changedAt: new Date() }),
    ) < 0,
    true,
    'then how much it has been used',
  );
  assert.equal(
    compareRanked(
      tied('a', { trust: 'confirmed', anchorState: 'unchecked', stats: {}, changedAt: new Date(2_000) }),
      tied('b', { trust: 'confirmed', anchorState: 'unchecked', stats: {}, changedAt: new Date(1_000) }),
    ) < 0,
    true,
    'then how recently it changed',
  );
  assert.equal(
    compareRanked(
      tied('a', { trust: 'confirmed', anchorState: 'unchecked', stats: {}, changedAt: null }),
      tied('b', { trust: 'confirmed', anchorState: 'unchecked', stats: {}, changedAt: null }),
    ) < 0,
    true,
    'and the id last, so two runs answer in the same order',
  );
  // `stats` is JSONB, so what it holds is a claim rather than a shape: neither a missing key nor a
  // string in one is a use count.
  assert.equal(usageOf({ searchHits: 2, gets: 3 }), 5);
  assert.equal(usageOf({ searchHits: '2', gets: null }), 0);
  assert.equal(usageOf(null), 0);

  // What counts as a path, and which paths a request asks about.
  assert.equal(looksLikePath('src/apiserver/src/wiki'), true);
  assert.equal(looksLikePath('src/a and/or b'), false, 'words that contain a slash are words');
  assert.equal(looksLikePath('wiki-retrieval.ts'), false, 'a bare name has no directory in it');
  assert.deepEqual(pathQueries('src/apiserver/src/', undefined), ['src/apiserver/src/']);
  assert.deepEqual(pathQueries('a query', undefined), []);
  assert.deepEqual(pathQueries('a query', ['./src/web', 'src/web']), ['src/web'], 'a caller names them');
});

// ── the two-legged search ───────────────────────────────────────────────────────────────────────

test('0307 · the wiki search path', { skip, concurrency: 1, timeout: 300_000 }, async (t) => {
  const h = await boot();

  // ── the fixture ───────────────────────────────────────────────────────────────────────────────
  const owner = await account(h, 'the owner');
  const other = await account(h, 'another owner');
  const machine = await runner(h, owner.id);
  const ws = await workspace(h, owner.id, 'git@github.com:orbit/wiki-search.git');
  const mine = await session(h, owner.id, ws, machine.id, 'the session that searched');
  const siblings = await session(h, owner.id, ws, machine.id, 'another session of the same account');
  const here = await space(h, owner, 'git@github.com:orbit/wiki-search.git');
  const elsewhere = await space(h, owner, 'git@github.com:orbit/elsewhere.git');
  const foreign = await space(h, other, 'git@github.com:orbit/foreign.git');
  await turn(h, mine, 1, 'the pipeline swallowed the exit code again');
  expectStatus(
    await call(h, { bearer: owner.bearer }, 'POST', `/wiki/spaces/${here}/workspaces`, { workspaceId: ws }),
    200,
    'the owner binds this workspace to the space',
  );

  // A Chinese convention whose Chinese lives in its title and its fields.
  const closedSets = await ownerEntry(h, owner, here, {
    kind: 'convention',
    title: '闭集一律用 CHECK 约束表达',
    summary: '不用枚举类型：闭集的取值写进 TEXT 列的 CHECK 里。',
    fields: {
      rule: '把闭集写成 TEXT 加 CHECK，不要用 enum。',
      scope: ['src/apiserver/prisma/migrations/**'],
    },
    aliases: ['closed sets', 'CHECK not enum'],
  });
  // An English concept reachable in Chinese only through an alias.
  const spaceEntry = await ownerEntry(h, owner, here, {
    kind: 'concept',
    title: 'Space',
    summary: "One owner's wiki for one codebase.",
    fields: {
      definition: "A space is one owner's knowledge about one codebase.",
      boundaries: 'A space never spans owners.',
    },
    aliases: ['知识空间', 'wiki 空间'],
  });
  // A recipe anchored to the path a caller would name while working on it.
  const recipe = await ownerEntry(h, owner, here, {
    kind: 'recipe',
    title: 'Run one pg spec against a throwaway PostgreSQL',
    summary: 'scripts/run-pg-spec.sh builds the tree, migrates a template and runs the spec on a clone.',
    fields: {
      steps: ['bash scripts/worktree-overlay.sh', 'bash scripts/run-pg-spec.sh <spec>'],
      verify: { command: 'bash scripts/run-pg-spec.sh src/apiserver/src/wiki/wiki-schema.pg.spec.ts', expectedExit: 0 },
    },
    anchors: [{ type: 'path', path: 'scripts/run-pg-spec.sh' }],
    topics: ['testing'],
  });
  // A pitfall that bites under a directory, and whose text does not carry the file being asked about.
  const pitfall = await ownerEntry(h, owner, here, {
    kind: 'pitfall',
    title: 'A pg spec with no database skips and exits 0',
    summary: 'node --test on a spec with no COORDINATOR_PG_URL skips every case and still exits 0.',
    fields: {
      trigger: { paths: ['src/apiserver/src/'], commands: ['node --test build/'] },
      symptom: 'A green acceptance run that witnessed no assertion.',
      cause: 'Each pg spec skips itself when the URL is unset.',
      fix: 'Run the spec through scripts/run-pg-spec.sh, which counts a skip as red.',
    },
  });
  // The same owner's other space, and another account's: neither is this space's to answer with.
  const elsewhereEntry = await ownerEntry(h, owner, elsewhere, {
    kind: 'concept',
    title: 'Aurora has no staging environment',
    summary: 'Aurora deploys straight to production.',
    fields: { definition: 'Aurora is the deploy pipeline.', boundaries: 'Not this repository.' },
  });
  await ownerEntry(h, other, foreign, {
    kind: 'concept',
    title: 'Borealis runs on another account',
    summary: 'Borealis belongs to a different owner entirely.',
    fields: { definition: 'Borealis is another account about another codebase.', boundaries: 'Another owner.' },
  });

  await t.test('a Chinese query finds the Chinese entry, and a Chinese word finds an English one', async () => {
    const chinese = await ownerSearch(h, owner, { q: '闭集', space: here });
    assert.deepEqual(
      hitsOf(chinese).map((hit) => hit.id),
      [closedSets],
      `only the convention is about 闭集: ${JSON.stringify(chinese.body)}`,
    );
    assert.deepEqual(hitFor(chinese, closedSets, 'the Chinese entry').match, ['keyword']);

    // 知识空间 is in the aliases and nowhere else, which is what aliases are for: the entry itself is
    // written in English.
    const aliased = await ownerSearch(h, owner, { q: '知识空间', space: here });
    assert.deepEqual(
      hitsOf(aliased).map((hit) => hit.id),
      [spaceEntry],
      `the alias is the only Chinese for it: ${JSON.stringify(aliased.body)}`,
    );
    assert.deepEqual(hitFor(aliased, spaceEntry, 'the aliased entry').match, ['keyword']);
  });

  await t.test('a path reaches anchors and pitfall triggers, and says which legs found it', async () => {
    // A path-shaped query: the anchor leg finds the recipe, and the recipe's own text carries the
    // script's name, so the keyword leg does too — and an entry BOTH legs found outranks one only
    // the keyword leg did, which is the whole point of fusing by rank.
    const both = await ownerSearch(h, owner, { q: 'scripts/run-pg-spec.sh', space: here });
    assert.deepEqual(hitFor(both, recipe, 'the recipe, anchored to that script').match, ['keyword', 'path']);
    assert.deepEqual(hitFor(both, pitfall, 'the pitfall, which names the script in its fix').match, ['keyword']);
    assert.equal(hitsOf(both)[0]?.id, recipe, `two legs beat one: ${JSON.stringify(both.body.hits)}`);

    // The name alone is not a path — there is no directory in it — so only the keyword leg answers.
    const named = await ownerSearch(h, owner, { q: 'run-pg-spec.sh', space: here });
    assert.deepEqual(hitFor(named, recipe, 'the recipe, named without its directory').match, ['keyword']);

    // A file under a directory a pitfall triggers on: the pitfall's own words say nothing about this
    // file, so the path leg is the only one that can reach it.
    const under = await ownerSearch(h, owner, { q: 'src/apiserver/src/wiki/wiki-retrieval.ts', space: here });
    assert.deepEqual(
      hitsOf(under).map((hit) => hit.id),
      [pitfall],
      `the trigger path covers it: ${JSON.stringify(under.body)}`,
    );
    assert.deepEqual(hitFor(under, pitfall, 'the triggered pitfall').match, ['path']);

    // The directory itself: the same relation read the other way, and both legs this time — a
    // pitfall's trigger path is a string in the entry's own fields, so the keyword leg finds the
    // entry that says it bites exactly where the caller is asking.
    const directory = await ownerSearch(h, owner, { q: 'src/apiserver/src/', space: here });
    assert.deepEqual(hitFor(directory, pitfall, 'the pitfall triggered under the directory').match, [
      'keyword',
      'path',
    ]);

    // A caller that knows what it is working on passes paths, and the query itself need not be one.
    const byPaths = await sessionSearch(h, machine, mine, { paths: 'src/apiserver/src/wiki/', limit: '5' });
    assert.deepEqual(
      hitFor(byPaths, pitfall, 'the pitfall, reached by the paths a session passed').match,
      ['path'],
      `a paths parameter drives the leg with no query at all: ${JSON.stringify(byPaths.body)}`,
    );
    // And a file it names without its directory, which no prefix of the whole path would catch.
    const byName = await sessionSearch(h, machine, mine, { paths: 'run-pg-spec.sh' });
    assert.deepEqual(
      hitsOf(byName).map((hit) => hit.id),
      [recipe],
      `the last segment of an anchor path answers to the file's name: ${JSON.stringify(byName.body)}`,
    );
  });

  await t.test('another space, another account and another session are not in the answer', async () => {
    const crossSpace = await ownerSearch(h, owner, { q: 'aurora', space: here });
    assert.deepEqual(hitsOf(crossSpace), [], 'the entry lives in another space of this owner');
    // ...which the same owner finds when nothing narrows the search to one space.
    const everySpace = await ownerSearch(h, owner, { q: 'aurora' });
    assert.deepEqual(
      hitsOf(everySpace).map((hit) => hit.id),
      [elsewhereEntry],
      "the owner's own search spans their spaces by default",
    );

    const crossOwner = await ownerSearch(h, owner, { q: 'borealis', space: here });
    assert.deepEqual(hitsOf(crossOwner), [], "another account's entry is not this account's");
    // Even naming the other account's space: the space is checked as this owner's before it is used.
    const named = await call(h, { bearer: owner.bearer }, 'GET', `/wiki/search?q=borealis&space=${foreign}`);
    assert.equal(named.status, 404, `another account's space is a 404: ${JSON.stringify(named.body)}`);

    // A session reads the space its workspace is bound to, and no other.
    const sessionCrossSpace = await sessionSearch(h, machine, mine, { q: 'aurora' });
    assert.deepEqual(hitsOf(sessionCrossSpace), [], 'a session reads one space');
  });

  await t.test('a session reads its own proposal, and nobody else does', async () => {
    const proposal = await proposedEntry(h, machine, mine, {
      kind: 'pitfall',
      title: 'Zephyr swallows the exit code of a pipeline',
      summary: "A pipeline reports the last command's status, not the failing one's.",
      fields: {
        trigger: { paths: ['src/runner-go/'], commands: ['go test ./... | grep PASS'] },
        symptom: 'The run looks green and something failed inside it.',
        cause: "A pipe's exit status is the last command's.",
        fix: 'Read the exit status before filtering the output.',
      },
    });

    const own = await sessionSearch(h, machine, mine, { q: 'zephyr' });
    assert.deepEqual(
      hitsOf(own).map((hit) => hit.id),
      [proposal],
      `the session reads what it proposed: ${JSON.stringify(own.body)}`,
    );
    assert.deepEqual(hitFor(own, proposal, "the session's own pending proposal").match, ['keyword']);

    const sibling = await sessionSearch(h, machine, siblings, { q: 'zephyr' });
    assert.deepEqual(
      hitsOf(sibling),
      [],
      "a pending proposal is visible only to the session that made it (contract readBoundary)",
    );

    // The owner's search is active entries unless they ask otherwise; the proposal waits in Review.
    const activeOnly = await ownerSearch(h, owner, { q: 'zephyr', space: here });
    assert.deepEqual(hitsOf(activeOnly), [], 'a proposal is not an answer to a search');
    const asked = await ownerSearch(h, owner, { q: 'zephyr', space: here, status: 'proposed' });
    assert.deepEqual(
      hitsOf(asked).map((hit) => hit.id),
      [proposal],
      `the owner may ask for what waits: ${JSON.stringify(asked.body)}`,
    );

    // Reads on the runner door need a session, because what a session may read is what its bound
    // workspace shares.
    const headless = await call(h, { runner: machine.token }, 'GET', '/runner/wiki/search?q=zephyr');
    assert.equal(headless.status, 400, `a headless read is refused: ${JSON.stringify(headless.body)}`);
  });

  await t.test('a hit is an entry and nothing else, and the semantic leg changes nothing', async () => {
    const answer = await ownerSearch(h, owner, { q: '闭集', space: here });
    assert.equal(answer.body.semantic, false, 'the semantic leg did not run');
    assert.equal(answer.body.q, '闭集', 'the query as it was understood comes back');
    for (const hit of hitsOf(answer)) {
      assert.deepEqual(
        Object.keys(hit).sort(),
        // `publicId` is the interceptor's twin of `id`, the API's convention for every address.
        ['anchorState', 'id', 'kind', 'match', 'publicId', 'score', 'summary', 'title', 'trust'],
        "a hit carries the contract's fields and no others: no fields, no sources, no history",
      );
      assert.ok(hit.score > 0 && hit.score <= 2 / 61, `a fused score is a sum of two RRF terms: ${hit.score}`);
    }

    // Phase 2's leg is a placeholder (design §6.3): asking for it changes nothing at all, which is
    // exactly what makes it safe for a client to start sending the parameter today.
    const askedFor = await ownerSearch(h, owner, { q: '闭集', space: here, semantic: 'true' });
    assert.deepEqual(askedFor.body, answer.body, 'asking for the semantic leg answers identically');
    const declined = await ownerSearch(h, owner, { q: '闭集', space: here, semantic: 'false' });
    assert.deepEqual(declined.body, answer.body, 'declining it answers identically too');
  });

  await t.test("the filters narrow within the reader's own boundary and cannot widen it", async () => {
    const limited = await ownerSearch(h, owner, { q: 'run-pg-spec.sh', space: here, limit: '1' });
    assert.equal(hitsOf(limited).length, 1, "the limit is the answer's size");
    const tooMany = await ownerSearch(h, owner, { q: 'run-pg-spec.sh', space: here, limit: '99' });
    assert.ok(
      hitsOf(tooMany).length <= WIKI_LIMITS.searchLimitMax,
      `the contract's ceiling holds at ${WIKI_LIMITS.searchLimitMax}: ${JSON.stringify(tooMany.body)}`,
    );

    const conventions = await ownerSearch(h, owner, { q: 'TEXT', space: here, kind: 'convention' });
    assert.deepEqual(
      hitsOf(conventions).map((hit) => hit.id),
      [closedSets],
      `kind narrows to the convention that says TEXT: ${JSON.stringify(conventions.body)}`,
    );
    const tested = await ownerSearch(h, owner, { q: 'run-pg-spec.sh', space: here, topic: 'testing' });
    assert.deepEqual(
      hitsOf(tested).map((hit) => hit.id),
      [recipe],
      `the topic's entry is the only one under it: ${JSON.stringify(tested.body)}`,
    );
    const confirmed = await ownerSearch(h, owner, { q: 'TEXT', space: here, trust: 'confirmed' });
    assert.deepEqual(hitsOf(confirmed), [], 'nothing this owner wrote is merely confirmed');
  });

  // The fixture, read back through the database once at the end: an assertion that a search found
  // nothing is only worth something if the row it should have found is really there.
  assert.equal(
    await h.prisma.wikiEntry.count({ where: { ownerId: other.id } }),
    1,
    "the other account's entry exists, so the empty cross-owner answer is isolation",
  );
  assert.equal(
    await h.prisma.wikiEntry.count({ where: { ownerId: owner.id, spaceId: toUuid(elsewhere) } }),
    1,
    'the other space of this owner holds its entry',
  );
});
