/**
 * A runner-hosted background job that asked to wake its session is delivered to it as a turn,
 * through the runner door: `POST /api/runner/sessions/:id/background-wake`.
 *
 * The job may end hours after the engine that started it was recycled, so the wake cannot be the
 * engine's own: the runner reports it, and the control plane files it as a turn that goes through
 * the same queue, claim and inbox as any other. Three facts, each over real HTTP and against real
 * PostgreSQL:
 *
 *   1. A wake is one turn. The inbox hands it out with the wake written into it — which job, how it
 *      ended, the end of its output and where the rest is — and what the runner echoes back is
 *      stored as the control plane's note. None of it is recorded as words the person typed.
 *   2. Wakes nobody has been handed yet are one turn however many arrive, and a job's later wake
 *      replaces its earlier one. A wake after delivery is a turn of its own.
 *   3. A session that has ended is not woken: nothing is queued and nothing is revived. The same
 *      request to a session that is still open is.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/runner-api/background-job-wake.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { type Prisma, RunStatus, SessionDispatchOrigin, type PrismaClient } from '@prisma/client';
import { uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { publicIdHeaders } from '../common/public-id-headers';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { AttemptBudgetMeterService } from '../projects/attempt-budget-meter.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { PushService } from '../push/push.service';
import { QueueService } from '../queue/queue.service';
import { RealtimeService } from '../realtime/realtime.service';
import { MergeReceiptService } from '../sessions/merge-receipt.service';
import { SessionsService } from '../sessions/sessions.service';
import { ListEventsService } from '../task-lists/list-events.service';
import { ReferenceExpansionService } from '../tasks/reference-expansion';
import { TasksService } from '../tasks/tasks.service';
import { RunnerApiController } from './runner-api.controller';
import { RunnerAuthGuard } from './runner-auth.guard';
import { RunnerOrchestrationAuthorizer } from './runner-orchestration-authorizer';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a session row carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The runner credential, in the clear. Its hash is what `RunnerAuthGuard` matches. */
const RUNNER_TOKEN = 'the-runner-token-for-background-wakes';

/** A response, kept as text as well as JSON: a body that failed to parse has to be readable. */
interface Answer {
  status: number;
  text: string;
  json: Record<string, unknown>;
}

/** A collaborator whose every method answers nothing: the broadcasts a turn's enqueue fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

/** What the runner reports when a job that asked to be woken for its exit has exited. */
function exitWake(jobId: string, fields: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    wakeId: `${jobId}:exit`,
    jobId,
    trigger: 'exit',
    kind: 'watch',
    command: 'gh run watch 4242 --exit-status',
    status: 'failed',
    exitCode: 1,
    outputPath: `/root/.orbit/runs/wake-spec/${jobId}.output`,
    outputOffset: 0,
    outputSize: 2048,
    outputExcerpt: 'X lint (ubuntu-latest) failed in 41s',
    ...fields,
  };
}

test('a background job wakes its session through the runner door', {
  skip, concurrency: 1, timeout: 300_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  let app: INestApplication | undefined;
  t.after(async () => {
    await app?.close().catch(() => undefined);
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const otherRunnerId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `bg-wake-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: { id: runnerId, name: 'the machine the jobs run on', ownerId, tokenHash: sha256(RUNNER_TOKEN) },
  });
  await prisma.runner.create({
    data: { id: otherRunnerId, name: 'another machine of the same owner', ownerId, tokenHash: sha256(`${RUNNER_TOKEN}-other`) },
  });

  /** A session on this runner, parked between turns: the state a long wait leaves it in. */
  async function session(data: Partial<Prisma.SessionUncheckedCreateInput> = {}): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id,
        ownerId,
        creatorId: ownerId,
        title: 'a session parked on a CI run',
        prompt: 'watch CI and fix what fails',
        provider: 'claude',
        status: RunStatus.AWAITING_INPUT,
        dispatchOrigin: SessionDispatchOrigin.USER,
        startsTaskWork: false,
        assignedRunnerId: runnerId,
        numTurns: 1,
        ...data,
      },
    });
    return id;
  }

  // ── the app: the real runner door, its guard, main.ts's middleware and interceptor ─────────────
  const queue = { notifySessionQueued: () => undefined };
  const realtime = silent();
  const sessions = new SessionsService(prisma as unknown as PrismaService, queue as never, realtime as never);
  @Module({
    controllers: [RunnerApiController],
    providers: [
      { provide: PrismaService, useValue: prisma },
      { provide: QueueService, useValue: queue },
      { provide: SessionsService, useValue: sessions },
      { provide: RealtimeService, useValue: realtime },
      { provide: PushService, useValue: silent() },
      { provide: RunnerOrchestrationAuthorizer, useValue: {} },
      // A wake has no `#`-references to expand and no list console to report into.
      { provide: ReferenceExpansionService, useValue: { expand: async (_owner: string, content?: string) => content } },
      { provide: ListEventsService, useValue: { appendFor: async (_tx: unknown, _id: string, content?: string) => content } },
      { provide: AttemptBudgetMeterService, useValue: {} },
      { provide: ProjectAcceptanceService, useValue: {} },
      { provide: TasksService, useValue: {} },
      { provide: MergeReceiptService, useValue: {} },
      RunnerAuthGuard,
    ],
  })
  class RunnerDoor {}

  app = await NestFactory.create(RunnerDoor, { logger: false, abortOnError: false });
  app.use(publicIdHeaders);
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
  app.useGlobalInterceptors(new PublicIdInterceptor());
  await app.listen(0, '127.0.0.1');
  const base = await app.getUrl();

  async function send(method: 'GET' | 'POST', route: string, body?: unknown): Promise<Answer> {
    const response = await fetch(`${base}/api${route}`, {
      method,
      headers: {
        authorization: `Bearer ${RUNNER_TOKEN}`,
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    const text = await response.text();
    let json: Record<string, unknown> = {};
    try { json = JSON.parse(text) as Record<string, unknown>; } catch { /* asserted on by the caller */ }
    return { status: response.status, text, json };
  }

  const wake = (sessionId: string, body: Record<string, unknown>): Promise<Answer> =>
    send('POST', `/runner/sessions/${uuidToBase62(sessionId)}/background-wake`, body);

  const turnsOf = (sessionId: string) =>
    prisma.conversationTurn.findMany({ where: { sessionId }, orderBy: { seq: 'asc' } });

  /** What the runner's claim does to a queued session, then the inbox poll that follows it. */
  async function claimAndPoll(sessionId: string): Promise<Answer> {
    await prisma.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    return send('GET', `/runner/sessions/${uuidToBase62(sessionId)}/inbox`);
  }

  await t.test('a wake is one turn, and everything it says is the control plane\'s note', async () => {
    const sessionId = await session();
    const job = 'bgj_0123456789ab';
    const answer = await wake(sessionId, exitWake(job, { exitCode: 3, outputExcerpt: 'FAIL src/widget.test.ts' }));
    assert.equal(answer.status, 200, `background-wake answered ${answer.status}: ${answer.text}`);
    assert.equal(answer.json.outcome, 'ENQUEUED', answer.text);

    const turns = await turnsOf(sessionId);
    assert.equal(turns.length, 1, 'the wake was not filed as a turn');
    assert.equal(turns[0].kind, 'message');
    assert.equal(turns[0].status, 'PENDING');
    assert.ok(!turns[0].content, `the turn records words as the person's: ${JSON.stringify(turns[0].content)}`);
    const queued = await prisma.session.findUniqueOrThrow({ where: { id: sessionId } });
    assert.equal(queued.status, RunStatus.PENDING, 'the wake did not ask for a runner slot');
    assert.equal(queued.lastUserText, null, 'the session list would preview the wake as the person\'s message');

    const delivered = await claimAndPoll(sessionId);
    assert.equal(delivered.status, 200, `inbox answered ${delivered.status}: ${delivered.text}`);
    assert.ok(
      [turns[0].id, uuidToBase62(turns[0].id)].includes(String(delivered.json.turnId)),
      `the inbox handed out something else: ${delivered.text}`,
    );
    const content = String(delivered.json.content ?? '');
    for (const fact of [job, 'exit code 3', `/root/.orbit/runs/wake-spec/${job}.output`, 'FAIL src/widget.test.ts']) {
      assert.ok(content.includes(fact), `the delivered turn does not say ${fact}:\n${content}`);
    }

    // The runner echoes what it was handed as the turn's `user` event.
    const echoed = await send('POST', `/runner/sessions/${uuidToBase62(sessionId)}/events`, {
      events: [{ seq: 1, type: 'user', ts: new Date().toISOString(), turnId: delivered.json.turnId, payload: { text: content } }],
    });
    assert.equal(echoed.status, 202, `events answered ${echoed.status}: ${echoed.text}`);
    const stored = await prisma.runEvent.findFirstOrThrow({ where: { sessionId, type: 'user' } });
    const payload = stored.payload as { text?: string; controlPlaneNote?: string };
    assert.equal(payload.text, content);
    assert.equal(payload.controlPlaneNote, content, 'the wake was stored as words the person wrote');
  });

  await t.test('wakes nobody has been handed are one turn; a wake after delivery is another', async () => {
    const sessionId = await session();
    const build = 'bgj_aaaaaaaaaaaa';
    const deploy = 'bgj_bbbbbbbbbbbb';
    const answers: Answer[] = [];
    for (const body of [
      exitWake(build, {
        wakeId: `${build}:output:1`, trigger: 'output', status: 'running', exitCode: undefined,
        outputSize: 100, outputExcerpt: 'step 3/9: compiling',
      }),
      exitWake(deploy, { status: 'completed', exitCode: 0, outputExcerpt: 'deployed to staging' }),
      exitWake(build, { outputOffset: 100, outputSize: 400, outputExcerpt: 'step 9/9: 2 tests failed' }),
    ]) {
      const answer = await wake(sessionId, body);
      assert.equal(answer.status, 200, `background-wake answered ${answer.status}: ${answer.text}`);
      answers.push(answer);
    }
    // An output wake found as the job exited, arriving after its exit wake: how the job ended stays.
    const late = await wake(sessionId, exitWake(build, {
      wakeId: `${build}:output:2`, trigger: 'output', status: 'running', exitCode: undefined,
      outputOffset: 100, outputSize: 400, outputExcerpt: 'an output wake that lost the race',
    }));
    assert.equal(late.status, 200, `background-wake answered ${late.status}: ${late.text}`);
    answers.push(late);
    assert.deepEqual(answers.map((answer) => answer.json.outcome), ['ENQUEUED', 'MERGED', 'MERGED', 'MERGED']);
    assert.equal((await turnsOf(sessionId)).length, 1, 'four wakes nobody had been handed became more than one turn');

    const delivered = await claimAndPoll(sessionId);
    assert.equal(delivered.status, 200, `inbox answered ${delivered.status}: ${delivered.text}`);
    const content = String(delivered.json.content ?? '');
    for (const fact of [build, 'step 9/9: 2 tests failed', deploy, 'deployed to staging']) {
      assert.ok(content.includes(fact), `the merged turn does not say ${fact}:\n${content}`);
    }
    assert.ok(!content.includes('step 3/9: compiling'),
      `a job's earlier wake was delivered beside the one that replaced it:\n${content}`);

    const later = await wake(sessionId, exitWake('bgj_cccccccccccc'));
    assert.equal(later.status, 200, `background-wake answered ${later.status}: ${later.text}`);
    assert.equal(later.json.outcome, 'ENQUEUED', later.text);
    assert.equal((await turnsOf(sessionId)).length, 2, 'a wake after delivery was folded into a turn already handed out');
  });

  await t.test('a session that has ended is not woken; the same wake to an open one is', async () => {
    const ended: Record<string, string> = {
      cancelled: await session({ status: RunStatus.CANCELLED, endReason: 'ended' }),
      'completed while parked': await session({ completedAt: new Date() }),
      'interrupted and ended': await session({ status: RunStatus.INTERRUPTED, endReason: 'stopped' }),
      'in the trash': await session({ deletedAt: new Date() }),
    };
    for (const [how, sessionId] of Object.entries(ended)) {
      const before = await prisma.session.findUniqueOrThrow({ where: { id: sessionId } });
      const answer = await wake(sessionId, exitWake('bgj_dddddddddddd'));
      assert.equal(answer.status, 200, `${how}: background-wake answered ${answer.status}: ${answer.text}`);
      assert.equal(answer.json.outcome, 'DROPPED', `${how}: ${answer.text}`);
      assert.equal((await turnsOf(sessionId)).length, 0, `${how}: a wake was queued on a session that has ended`);
      const after = await prisma.session.findUniqueOrThrow({ where: { id: sessionId } });
      assert.equal(after.status, before.status, `${how}: the wake moved the session's status`);
    }

    // Another runner's session is not this runner's to wake.
    const elsewhere = await session({ assignedRunnerId: otherRunnerId });
    const refused = await wake(elsewhere, exitWake('bgj_dddddddddddd'));
    assert.equal(refused.status, 403, `a wake for another runner's session answered ${refused.status}: ${refused.text}`);
    assert.equal((await turnsOf(elsewhere)).length, 0);

    // The paired positive, last: the identical request to a session that is still open is a turn.
    const open = await session();
    const answer = await wake(open, exitWake('bgj_dddddddddddd'));
    assert.equal(answer.status, 200, `background-wake answered ${answer.status}: ${answer.text}`);
    assert.equal(answer.json.outcome, 'ENQUEUED', answer.text);
    assert.equal((await turnsOf(open)).length, 1, 'the wake to an open session was not queued');
  });
});
