/**
 * A runner-hosted background job that a self-updated runner adopts is back in its session's running
 * background set — `Session.runningBgShells`, which the session list and header read "Background
 * running" from — against a real PostgreSQL, through the runner door's own handlers.
 *
 * A runner that re-executes into a self-update hands its jobs on rather than killing them
 * (runner-go background_job_adopt_unix.go). The process that comes next takes the session over,
 * which empties the set: a takeover is where a change of supervisor is observable. It then adopts
 * each recorded job and reports it with a `running` background_task carrying the job's `kind`. It
 * does not re-send the job's tool_use — tool_call has no uniqueness on (session, tool_use_id), so a
 * second one would be a second call — which leaves that report as the only thing that can put the
 * job back. Two facts:
 *
 *   1. The takeover empties the set; the adopted job's `running` report puts it back; the job's
 *      terminal report takes it out again.
 *   2. A `running` report without a `kind` — what an engine's own Bash shell reports, and that shell
 *      died with its engine — puts nothing back. Each such report is tried on a session of its own,
 *      paired on that session with the report that does.
 *
 * A runner that replaces the session's engine in place, with no takeover — a setting only a new
 * process takes, an engine that crashed in the middle of a turn — says so with a `resumed` system
 * event, which empties the set as well: the replaced engine's shells died with it. The jobs the
 * runner hosts did not, and it reports each one still running again, with the same `running` report,
 * behind the handshake (runner-go session.go emitThrough). A third fact, about the batch that carries
 * both:
 *
 *   3. A `resumed` handshake alone empties the set. With the job's `running` report behind it in the
 *      same batch, the set holds the job and only the job: the batch is folded reset first.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/runner-api/background-job-adoption-running-set.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type PrismaClient, RunStatus, SessionDispatchOrigin } from '@prisma/client';
import { type NormalizedRunEvent, RunEventType } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { RunnerApiController } from './runner-api.controller';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** A collaborator whose every method answers nothing: the broadcasts the two handlers fire. */
const silent = (): never =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) }) as never;

type Reported = Pick<NormalizedRunEvent, 'type' | 'payload'>;

const JOB = 'bgj_5e1f0a2b3c4d';
const JOB_COMMAND = 'npm run build';
const JOB_OUTPUT = `/root/.orbit/runs/adoption-spec/${JOB}.output`;
/** An engine's own Bash(run_in_background) shell, started beside the job. */
const SHELL = 'toolu_01EngineOwnedShell';

/** The job's `running` report but for its kind: the one field the negatives below take away. */
const JOB_RUNNING_WITHOUT_KIND = {
  shellId: JOB,
  toolUseId: JOB,
  status: 'running',
  command: JOB_COMMAND,
  outputPath: JOB_OUTPUT,
};

/** The job's `running` report, as runner-go sends it at launch and again from the process that adopts it. */
const jobRunning = (): Record<string, unknown> => ({ ...JOB_RUNNING_WITHOUT_KIND, kind: 'job' });

/** What runner-go's bg_run emits for a job it starts: the launch pair, and the durable half beside it. */
function jobLaunch(): Reported[] {
  return [
    {
      type: RunEventType.TOOL_USE,
      payload: { id: JOB, name: 'Bash', input: { command: JOB_COMMAND, run_in_background: true } },
    },
    {
      type: RunEventType.TOOL_RESULT,
      payload: {
        toolUseId: JOB,
        content: `Command running in background with ID: ${JOB}. Output is being written to: ${JOB_OUTPUT}. Read it with mcp__orbit__bg_output.`,
      },
    },
    { type: RunEventType.BACKGROUND_TASK, payload: jobRunning() },
  ];
}

/** The engine's own shell, launched as Claude reports it. */
function shellLaunch(): Reported[] {
  return [
    {
      type: RunEventType.TOOL_USE,
      payload: { id: SHELL, name: 'Bash', input: { command: 'npm run dev', run_in_background: true } },
    },
    {
      type: RunEventType.TOOL_RESULT,
      payload: {
        toolUseId: SHELL,
        content: 'Command running in background with ID: b7k2m9. Output is being written to: /tmp/claude/tasks/b7k2m9.output',
      },
    },
  ];
}

/** The job's terminal report (runner-go bgJob.endPayload). */
const jobEnded = (): Record<string, unknown> => ({
  ...jobRunning(),
  status: 'completed',
  summary: 'Background job completed (exit code 0)',
  output: 'built in 41s',
  exitCode: 0,
});

/** The handshake runner-go sends when it replaces the session's engine in place (session.go). */
const RESUMED: Reported = { type: RunEventType.SYSTEM, payload: { subtype: 'resumed', reason: 'config_changed' } };

/** `running` reports that carry no kind, each tried on a session of its own. */
const WITHOUT_KIND: ReadonlyArray<[string, Record<string, unknown>]> = [
  [
    'the engine\'s own shell, reported off its <task-notification>',
    {
      shellId: 'b7k2m9',
      toolUseId: SHELL,
      status: 'running',
      summary: 'npm run dev',
      outputFile: '/tmp/claude/tasks/b7k2m9.output',
    },
  ],
  ['the job\'s own report with its kind taken off', JOB_RUNNING_WITHOUT_KIND],
  ['the job\'s own report with an empty kind', { ...JOB_RUNNING_WITHOUT_KIND, kind: '' }],
];

test('a background job adopted after a self-update is back in the running background set', {
  skip, concurrency: 1, timeout: 300_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  const ownerId = randomUUID();
  const runner = { id: randomUUID() };
  await prisma.user.create({
    data: { id: ownerId, email: `bg-adopt-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: { id: runner.id, name: 'the machine that self-updates', ownerId, tokenHash: sha256(`bg-adopt-${runner.id}`) },
  });
  const door = new RunnerApiController(prisma as never, silent(), silent(), silent(), silent(), silent());

  /**
   * A session whose runner process P1 hosts the job while P1's engine runs its own shell. Returns what
   * P1 reports through, how another process takes the session over from P1, and the running set as
   * stored, sorted: it is a set.
   */
  async function bothRunning() {
    const sessionId = randomUUID();
    await prisma.session.create({
      data: {
        id: sessionId,
        ownerId,
        creatorId: ownerId,
        title: 'a session with a build running',
        prompt: 'build it and tell me what breaks',
        provider: 'claude',
        status: RunStatus.AWAITING_INPUT,
        dispatchOrigin: SessionDispatchOrigin.USER,
        startsTaskWork: false,
        assignedRunnerId: runner.id,
        numTurns: 1,
      },
    });
    let seq = 0;
    const report = (leaseOwner: string, events: Reported[]) =>
      door.events(runner, sessionId, {
        leaseOwner,
        events: events.map((event) => ({ ...event, seq: ++seq, ts: new Date().toISOString() })),
      });
    const running = async () => {
      const stored = await prisma.session.findUniqueOrThrow({
        where: { id: sessionId },
        select: { runningBgShells: true },
      });
      return [...stored.runningBgShells].sort();
    };

    const p1 = randomUUID();
    await door.takeoverLeases(runner, sessionId, { leaseOwner: p1, expectedLeaseOwner: null } as never);
    await report(p1, [...jobLaunch(), ...shellLaunch()]);
    assert.deepEqual(await running(), [JOB, SHELL].sort(), 'the fixture: both launches are running');

    /** P2 takes the session over from P1; returns what P2 reports through. */
    const takeOver = async () => {
      const p2 = randomUUID();
      await door.takeoverLeases(runner, sessionId, { leaseOwner: p2, expectedLeaseOwner: p1 } as never);
      return (events: Reported[]) => report(p2, events);
    };
    return { report: (events: Reported[]) => report(p1, events), takeOver, running };
  }

  /** The same session once P1 has re-executed into a self-update and P2 has taken it over. */
  async function selfUpdated() {
    const session = await bothRunning();
    return { report: await session.takeOver(), running: session.running };
  }

  await t.test('the takeover empties the set, the adopted job\'s running report puts it back, and its end takes it out', async () => {
    const session = await selfUpdated();
    assert.deepEqual(await session.running(), [], 'the takeover left the predecessor\'s background work in the set');

    await session.report([{ type: RunEventType.BACKGROUND_TASK, payload: jobRunning() }]);
    assert.deepEqual(
      await session.running(),
      [JOB],
      'the job the new process adopted is still running, and the session does not say so',
    );

    await session.report([{ type: RunEventType.BACKGROUND_TASK, payload: jobEnded() }]);
    assert.deepEqual(await session.running(), [], 'the adopted job ended, and the session still reads it as running');
  });

  for (const [what, payload] of WITHOUT_KIND) {
    await t.test(`a running report without a kind puts nothing back: ${what}`, async () => {
      const session = await selfUpdated();
      assert.deepEqual(await session.running(), []);

      await session.report([{ type: RunEventType.BACKGROUND_TASK, payload }]);
      assert.deepEqual(await session.running(), [], `${what} put an id in the running set`);

      // The paired positive, last and on the same session: the report that does carry the kind.
      await session.report([{ type: RunEventType.BACKGROUND_TASK, payload: jobRunning() }]);
      assert.deepEqual(await session.running(), [JOB], 'the same door did not record the adopted job');
    });
  }

  await t.test('a resumed handshake alone empties the set: the job goes with the replaced engine\'s shell', async () => {
    const session = await bothRunning();
    await session.report([RESUMED]);
    assert.deepEqual(await session.running(), [], 'the handshake left background work in the set');
  });

  await t.test('the job\'s running report behind a resumed handshake in the same batch leaves the job, and only the job, in the set', async () => {
    const session = await bothRunning();
    await session.report([RESUMED, { type: RunEventType.BACKGROUND_TASK, payload: jobRunning() }]);
    assert.deepEqual(
      await session.running(),
      [JOB],
      'the batch runner-go sends when it replaces the engine under a live job: the job is still running, and the replaced engine\'s shell is not',
    );
  });
});
