/**
 * "Work in flight" means work that is still MOVING: a `bg_run` whose process is up but has produced
 * nothing for longer than the threshold stops counting as background activity, while staying a
 * running process — the marker stops breathing, the tray still lists it.
 *
 * `Session.runningBgJobs` (0288) answers "is a job in flight", which a hung process answers as
 * convincingly as a working one. The runner is the only party that knows better: it tails each job's
 * `.output` file, and it states how long that file has been silent as `idleMs` on the job's
 * `running` report (runner-go background_job.go), at launch, on adoption, and on a heartbeat. The
 * event transaction records each report as an instant in the control plane's own timebase
 * (`receivedAt - idleMs`, migration 0289), pruned to the jobs still in flight; the readers apply the
 * threshold (sessions/background-job-activity.ts).
 *
 * Four facts, each asserted against a real PostgreSQL through the runner door's own handlers and the
 * session service's own readers:
 *
 *   1. Two jobs in one session — one that just produced output, one whose last output is past the
 *      threshold — and the counts separate them: `runningBgJobCount` and the workspace's `jobs` tally
 *      count one, while `runningBgCount` and `runningBgShells` count both, because the quiet job is
 *      still a process. "Stalled" and "gone" are different answers, and this is the pair that says so.
 *   2. A job that goes quiet while it was counted drops out with no terminal event at all — the
 *      report that carries the growing silence is what moves it — and a job that writes again is
 *      counted again, on the same session.
 *   3. A `running` report that carries no `idleMs` (a runner from before the field) leaves the job
 *      counted: unknown is not the same claim as "silent for ten minutes".
 *   4. The terminal report clears the job from both sets and from the activity map beside them.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/runner-api/background-job-activity-freshness.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type PrismaClient, RunStatus, SessionDispatchOrigin } from '@prisma/client';
import { type NormalizedRunEvent, RunEventType } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { BG_JOB_ACTIVITY_STALE_AFTER_MS } from '../sessions/background-job-activity';
import { SessionsService } from '../sessions/sessions.service';
import { RunnerApiController } from './runner-api.controller';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** A collaborator whose every method answers nothing: the broadcasts the two services fire. */
const silent = (): never =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) }) as never;

type Reported = Pick<NormalizedRunEvent, 'type' | 'payload'>;

/** The job that has just produced output, and the one that has not produced any for a long time. */
const LIVE = 'bgj_4a1c9d7e2b30';
const STALE = 'bgj_6f2b8e4a1c95';
/** A dev server, to prove the activity map never grows an entry for something that is not a job. */
const SERVICE = 'bgj_9c7a51d2e0f3';

const outputPathFor = (id: string) => `/root/.orbit/runs/activity-spec/${id}.output`;

/** The launch pair runner-go emits for a `bg_run`, then the `running` report that carries its kind. */
function jobLaunch(id: string, idleMs?: number): Reported[] {
  return [
    {
      type: RunEventType.TOOL_USE,
      payload: { id, name: 'Bash', input: { command: 'npm run build', run_in_background: true } },
    },
    {
      type: RunEventType.TOOL_RESULT,
      payload: {
        toolUseId: id,
        content: `Command running in background with ID: ${id}. Output is being written to: ${outputPathFor(id)}. Read it with mcp__orbit__bg_output.`,
      },
    },
    runningReport(id, idleMs),
  ];
}

/** One `running` background_task, as the launch, the adoption and the heartbeat all send it. */
function runningReport(id: string, idleMs?: number): Reported {
  const payload: Record<string, unknown> = {
    shellId: id,
    toolUseId: id,
    status: 'running',
    kind: 'job',
    command: 'npm run build',
    outputPath: outputPathFor(id),
  };
  if (idleMs !== undefined) payload.idleMs = idleMs;
  return { type: RunEventType.BACKGROUND_TASK, payload };
}

/** The terminal report, as bgJob.endPayload sends it: kind and all. */
const jobEnded = (id: string): Reported => ({
  type: RunEventType.BACKGROUND_TASK,
  payload: {
    shellId: id,
    toolUseId: id,
    status: 'completed',
    kind: 'job',
    command: 'npm run build',
    summary: 'Background job completed (exit code 0)',
    output: 'built in 41s',
    outputPath: outputPathFor(id),
    exitCode: 0,
  },
});

test('a background job that has stopped producing stops counting as work in flight', {
  skip, concurrency: 1, timeout: 300_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  const ownerId = randomUUID();
  const runner = { id: randomUUID() };
  await prisma.user.create({
    data: {
      id: ownerId,
      email: `bg-activity-${ownerId}@runner-door.invalid`,
      name: 'The account owner',
      passwordHash: 'x',
    },
  });
  await prisma.runner.create({
    data: { id: runner.id, name: 'the machine with the hung job', ownerId, tokenHash: sha256(`bg-activity-${runner.id}`) },
  });
  const door = new RunnerApiController(prisma as never, silent(), silent(), silent(), silent(), silent());
  const sessions = new SessionsService(prisma as never, silent(), silent());

  /**
   * A session whose runner hosts one job that just produced output and one that has not produced any
   * for longer than the threshold, in a workspace of its own. The workspace is per case because the
   * rail's `jobs` tally is per WORKSPACE: a session left over from an earlier case is still counted
   * there, and the number this spec is about is the one this session contributes.
   *
   * Returns how the runner reports through, and how the three readers that answer "is there work in
   * flight here" see it: the counts endpoint the workspace rail polls, the session payload the glyph
   * is drawn from, and the list row the clients read beside it.
   */
  async function sessionWithTwoJobs() {
    const workspaceId = randomUUID();
    await prisma.workspace.create({
      data: { id: workspaceId, ownerId, name: 'the checked-out repo' },
    });
    const sessionId = randomUUID();
    await prisma.session.create({
      data: {
        id: sessionId,
        ownerId,
        creatorId: ownerId,
        workspaceId,
        title: 'a build that has stopped moving',
        prompt: 'build it and tell me what breaks',
        provider: 'claude',
        status: RunStatus.AWAITING_INPUT,
        dispatchOrigin: SessionDispatchOrigin.USER,
        startsTaskWork: false,
        assignedRunnerId: runner.id,
        numTurns: 1,
      },
    });
    let seq = 0;
    const leaseOwner = randomUUID();
    const report = (events: Reported[]) =>
      door.events(runner, sessionId, {
        leaseOwner,
        events: events.map((event) => ({ ...event, seq: ++seq, ts: new Date().toISOString() })),
      });

    await door.takeoverLeases(runner, sessionId, { leaseOwner, expectedLeaseOwner: null } as never);

    /** The two sets as stored: what is up, and what is up AND counted as work in flight. */
    const storedSets = async () => {
      const stored = await prisma.session.findUniqueOrThrow({
        where: { id: sessionId },
        select: { runningBgShells: true, runningBgJobs: true, runningBgJobActivity: true },
      });
      return {
        shells: [...stored.runningBgShells].sort(),
        jobs: [...stored.runningBgJobs].sort(),
        activity: stored.runningBgJobActivity as Record<string, number>,
      };
    };
    /** The workspace tally the rail draws its quieter mark from. */
    const railJobs = async () => {
      const rows = await sessions.workspaceSessionCounts(ownerId);
      return rows.find((row) => row.workspaceId === workspaceId)?.jobs ?? 0;
    };
    /** The session payload: the count the glyph is drawn from, and the raw set beside it. */
    const payload = async () => {
      const row = await sessions.get(ownerId, sessionId);
      return { jobs: row.runningBgJobCount, shells: row.runningBgShells as string[] };
    };
    /** The list row the clients read the glyph off (a different code path: raw SQL + mapper). */
    const listRow = async () => {
      const rows = await sessions.list(ownerId, { view: 'open' });
      const row = rows.find((r) => r.id === sessionId);
      assert.ok(row, 'the session is missing from its own owner\'s Open list');
      return { jobs: row.runningBgJobCount, shells: row.runningBgCount };
    };
    return { sessionId, report, storedSets, railJobs, payload, listRow };
  }

  await t.test('a job that has gone quiet stops counting, and goes on being a process', async () => {
    const session = await sessionWithTwoJobs();
    // The launch: one job that has this instant produced output, one already silent past the
    // threshold. Both are reported the way the runner reports them, which is the only way the
    // control plane hears about either.
    await session.report([
      ...jobLaunch(LIVE, 0),
      ...jobLaunch(STALE, BG_JOB_ACTIVITY_STALE_AFTER_MS + 60_000),
    ]);

    const sets = await session.storedSets();
    assert.deepEqual(
      sets.shells,
      [LIVE, STALE].sort(),
      'both jobs are running processes, so both belong in running_bg_shells',
    );
    assert.deepEqual(
      sets.jobs,
      [LIVE, STALE].sort(),
      'both jobs are in flight — a job does not stop being in flight by going quiet — so the stored set holds both',
    );

    // What the readers say, which is where the threshold applies. The first is the question the
    // marker is: is there work in flight that is still moving.
    assert.equal(await session.railJobs(), 1, 'the workspace rail counts a job that has gone quiet as background activity');
    const payload = await session.payload();
    assert.deepEqual(
      payload,
      { jobs: 1, shells: [LIVE, STALE].sort() },
      'the session payload counts one job in flight and still reports both processes',
    );
    assert.deepEqual(
      await session.listRow(),
      { jobs: 1, shells: 2 },
      'the list row — what the glyph and the rail actually read — counts the same way the other two do',
    );
    // The pairing that matters, on one session: the count says one, the process count says two.
    // "This job has stalled" and "this job is gone" are different answers, and the second is not
    // what a quiet process is.
    assert.equal(payload.shells.length, 2, 'the quiet job stopped being a process, which it is not');
    assert.equal(payload.jobs, 1, 'the quiet job is still counted as work in flight');
  });

  await t.test('the report that carries the growing silence is what drops it, and a write brings it back', async () => {
    const session = await sessionWithTwoJobs();
    await session.report([
      ...jobLaunch(LIVE, 0),
      ...jobLaunch(STALE, 0),
    ]);
    assert.equal((await session.payload()).jobs, 2, 'the fixture: both jobs have just produced output');
    assert.equal(await session.railJobs(), 1, 'the fixture: the workspace has a session with work in flight');

    // No terminal event, no kill, nothing that happens to the process: the same job, still running,
    // reported with the silence that has accumulated since. This is the heartbeat of a job that is
    // stuck, and it is the only thing that has to happen for the marker to stop — the eleven minutes
    // of waiting are compressed into the report, which states them as the idle duration it exists to
    // state (a spec that waited them out would be a spec nobody runs).
    await session.report([runningReport(STALE, BG_JOB_ACTIVITY_STALE_AFTER_MS + 60_000)]);
    assert.equal((await session.payload()).jobs, 1, 'a job that stopped producing is still counted as work in flight');
    assert.equal(
      await session.railJobs(),
      1,
      'the session still has work in flight — the other job is moving — so the workspace still counts it',
    );
    assert.deepEqual(
      (await session.storedSets()).shells,
      [LIVE, STALE].sort(),
      'and it is still running: the marker stopping does not mean the process went away',
    );

    // And back: a job that writes again is work in flight again, at the next report.
    await session.report([runningReport(STALE, 0)]);
    assert.equal((await session.payload()).jobs, 2, 'a job that started producing again did not come back');

    // Both quiet, and the session itself stops counting — the number the rail draws its mark from is
    // about the workspace's sessions, so it drops only when no job in the session is moving.
    await session.report([
      runningReport(STALE, BG_JOB_ACTIVITY_STALE_AFTER_MS + 60_000),
      runningReport(LIVE, BG_JOB_ACTIVITY_STALE_AFTER_MS + 60_000),
    ]);
    assert.equal((await session.payload()).jobs, 0, 'the same job, quiet again, is still counted');
    assert.equal(await session.railJobs(), 0, 'the workspace still shows work where nothing is moving');
    assert.deepEqual(
      (await session.storedSets()).shells,
      [LIVE, STALE].sort(),
      'both jobs are still processes with nothing producing',
    );
  });

  await t.test('a report with no idle duration leaves the job counted: unknown is not silent', async () => {
    const session = await sessionWithTwoJobs();
    // A runner from before this field reports `running` with a kind and nothing about progress —
    // which is a fact about the runner, not about the job. Reading it as "silent since the epoch"
    // would darken the marker for every job on every runner that has not updated yet.
    await session.report([...jobLaunch(LIVE), ...jobLaunch(STALE)]);
    const sets = await session.storedSets();
    assert.deepEqual(
      sets.activity,
      {},
      'a report that says nothing about progress records nothing about it',
    );
    assert.equal((await session.payload()).jobs, 2, 'a job nobody has reported progress on is not a job that has stopped producing');
    assert.equal(await session.railJobs(), 1);

    // The paired positive on the same session: once a report DOES carry the duration, the same read
    // applies the threshold to it — while the sibling that has still reported nothing stays counted,
    // which is the whole difference between the two.
    await session.report([runningReport(STALE, BG_JOB_ACTIVITY_STALE_AFTER_MS + 60_000)]);
    assert.equal((await session.payload()).jobs, 1, 'the threshold was not applied to a job that reported its silence');
  });

  await t.test('the activity map holds the jobs in flight and nothing else', async () => {
    const session = await sessionWithTwoJobs();
    await session.report([
      ...jobLaunch(LIVE, 0),
      ...jobLaunch(STALE, 0),
      // A service is a running process that is never work in flight (0288), so it is not a job this
      // map has anything to say about — and the map is pruned to what is in flight, which is what
      // keeps it the size of the session's live work.
      {
        type: RunEventType.BACKGROUND_TASK,
        payload: {
          shellId: SERVICE,
          toolUseId: SERVICE,
          status: 'running',
          kind: 'service',
          command: 'vite dev',
          outputPath: outputPathFor(SERVICE),
          idleMs: 0,
        },
      },
    ]);
    assert.deepEqual(
      Object.keys((await session.storedSets()).activity).sort(),
      [LIVE, STALE].sort(),
      'the activity map is the session\'s jobs in flight, and a service is not one of them',
    );

    // A job's end takes it out of both sets and out of the map, so a job that has finished cannot
    // leave an instant behind that some later read mistakes for a job still in flight. The service
    // stays in `running_bg_shells` — nothing ends it, which is the whole reason 0288 keeps it out of
    // the in-flight set — so it is the one id the two sets disagree about here.
    await session.report([jobEnded(STALE)]);
    const after = await session.storedSets();
    assert.deepEqual(
      after.shells,
      [LIVE, SERVICE].sort(),
      'the job that ended is gone from the process set, and the service is still up',
    );
    assert.deepEqual(after.jobs, [LIVE], 'the job that ended is still counted as in flight');
    assert.deepEqual(
      Object.keys(after.activity),
      [LIVE],
      'the job that ended left its last-output instant behind',
    );
    assert.equal(await session.railJobs(), 1);

    // And the terminal report is durable in the other direction too: the OTHER job, still quiet,
    // is still not counted, so neither assertion above passed by accident.
    await session.report([runningReport(LIVE, BG_JOB_ACTIVITY_STALE_AFTER_MS + 60_000)]);
    assert.equal(await session.railJobs(), 0, 'the last job in flight went quiet and is still counted');
    assert.deepEqual(
      await session.listRow(),
      { jobs: 0, shells: 2 },
      'nothing is in flight, and the two processes are still up: the counts answer different questions',
    );
  });
});
