/**
 * The whole failure path, end to end: a claim whose answer is lost, the reclaim that recovers it,
 * and the first spawn of an engine for a session no engine has ever run.
 *
 * WHAT THIS DRIVES
 * ----------------
 * A session that was claimed and never answered — the runner's claim HTTP response dropped after the
 * control plane had already committed PENDING -> RUNNING. That is the chain in the project's own goal:
 *
 *   1. the runner's `claimSession` fails with a transport error (the harness's proxy drops the answer)
 *   2. `reclaimMissingSessions` picks the now-RUNNING row back up, `claimedSessionFromReclaim` marks it
 *      `Reclaimed` with `maxSeq` 0, and the run loop logs "recovering ambiguously claimed session"
 *   3. the supervisor starts and spawns the engine for the FIRST time
 *
 * The runner is this repository's Go runner, built from `src/runner-go` with the `claimrecoveryfault`
 * tag (`claim_recovery_fault_process_test.go`) and driven one command at a time. The control plane is
 * the real `RunnerApiController` behind the real `RunnerAuthGuard`, over a disposable PostgreSQL.
 * `claude` is the runner's own scripted fake CLI, put first on PATH, and it is asked for the two
 * endings a real engine has: it opens the conversation and answers, or it starts and dies without
 * answering.
 *
 * WHAT IT ASSERTS
 * ---------------
 * Neither ending may leave the session parked at AWAITING_INPUT having never said anything, and the
 * person's turn may be ANSWERED only when something answered it:
 *
 *   * (1) the engine was asked to OPEN the conversation (`--session-id`, never `--resume` on a
 *     conversation this machine has never held), the turn comes back ANSWERED, an ASSISTANT event
 *     hangs off it and the session carries the reply.
 *   * (2) an engine that starts and dies answers nothing: the turn is NOT ANSWERED, it is handed out
 *     again by the next inbox poll, and the session is not parked as if it were idle.
 *
 * Both are asserted against the database, read on a second connection, never through the answer that
 * wrote them.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/runner-api/claim-recovery-e2e.pg.spec.ts
 *
 * Needs COORDINATOR_PG_URL (the script provides a disposable one) and Go. Nothing here reaches a real
 * Claude account or a real model. Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { execFile, spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { createServer, request as httpRequest, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { test } from 'node:test';
import { setTimeout as sleep } from 'node:timers/promises';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { type PrismaClient, RunStatus } from '@prisma/client';
import { uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { publicIdHeaders } from '../common/public-id-headers';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { AttemptBudgetMeterService } from '../projects/attempt-budget-meter.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { PushService } from '../push/push.service';
import { QueueService } from '../queue/queue.service';
import { RealtimeService } from '../realtime/realtime.service';
import { MergeReceiptService } from '../sessions/merge-receipt.service';
import { SessionsService } from '../sessions/sessions.service';
import { ListEventsService } from '../task-lists/list-events.service';
import { ReferenceExpansionService } from '../tasks/reference-expansion';
import { TasksService } from '../tasks/tasks.service';
import { RunnerApiController } from './runner-api.controller';
import { RunnerAuthGuard } from './runner-auth.guard';
import { RunnerOrchestrationAuthorizer } from './runner-orchestration-authorizer';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; session rows carry BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

const REPO = path.resolve(__dirname, '../../../..');
const RUNNER_GO = path.join(REPO, 'src/runner-go');
/** The runner's credential, in the clear. Its hash is what `RunnerAuthGuard` matches. */
const RUNNER_TOKEN = 'the-runner-token-for-a-lost-claim';
/** The path whose answer the proxy drops after the control plane has committed it. */
const CLAIM_PATH = '/api/runner/sessions/claim';
/** The opening question, in the words the incident's session was started with. */
const OPENING = 'review this confirm card and tell me what a person would misread';

/** A collaborator whose every method answers nothing: the broadcasts a claim fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

/** One `CLAIMREC {...}` answer from the runner process. */
type Receipt = Record<string, unknown>;

interface Scenario {
  sessionId: string;
  turnId: string;
  /** The runtime id the claim materialized: the conversation this session's engine has to open. */
  sessionUuid: string;
  /** The machine the session was queued on, which is the runner every request below must come from. */
  machineId: string;
  /** Where the scripted `claude` records its spawns and reads its script. */
  recDir: string;
  /** The argv of every process the runner spawned, oldest first. */
  spawns: () => Array<{ pid: number; argv: string[]; cwd: string }>;
  receipt: Receipt;
}

test('a lost claim is recovered without the session ever going silent', {
  skip,
  concurrency: 1,
  timeout: 900_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);

  const ownerId = randomUUID();

  // ── the runner's own process: built once, started once per scenario ────────────────────────────
  await prisma.user.create({
    data: { id: ownerId, email: `claim-recovery-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  const workDir = mkdtempSync(path.join(tmpdir(), 'claimrec-'));
  const binary = path.join(workDir, 'runner-fault.bin');
  const built = await new Promise<{ code: number; stderr: string }>((resolve) => {
    execFile('go', ['test', '-c', '-tags', 'claimrecoveryfault', '-o', binary, '.'], {
      cwd: RUNNER_GO,
      maxBuffer: 32 * 1024 * 1024,
    }, (error, _stdout, stderr) => resolve({ code: error ? 1 : 0, stderr: String(stderr) }));
  });
  assert.equal(built.code, 0, `the runner's fault process did not build:\n${built.stderr}`);
  assert.ok(existsSync(binary), 'the build reported success and wrote no binary');

  // ── the control plane's own HTTP door, its guard and main.ts's middleware ──────────────────────
  const queue = new QueueService(prisma as unknown as PrismaService, silent() as never);
  const realtime = silent();
  const sessions = new SessionsService(prisma as unknown as PrismaService, queue as never, realtime as never);
  @Module({
    controllers: [RunnerApiController],
    providers: [
      { provide: PrismaService, useValue: prisma },
      { provide: QueueService, useValue: queue },
      { provide: SessionsService, useValue: sessions },
      { provide: RealtimeService, useValue: realtime },
      { provide: PushService, useValue: silent() },
      { provide: RunnerOrchestrationAuthorizer, useValue: {} },
      { provide: ReferenceExpansionService, useValue: { expand: async (_owner: string, content?: string) => content } },
      { provide: ListEventsService, useValue: { appendFor: async (_tx: unknown, _id: string, content?: string) => content } },
      { provide: AttemptBudgetMeterService, useValue: {} },
      { provide: ProjectAcceptanceService, useValue: {} },
      { provide: TasksService, useValue: {} },
      { provide: MergeReceiptService, useValue: {} },
      RunnerAuthGuard,
    ],
  })
  class RunnerDoor {}

  let app: INestApplication | undefined;
  let proxy: Server | undefined;
  const children: ChildProcessWithoutNullStreams[] = [];
  t.after(async () => {
    for (const child of children) child.kill('SIGKILL');
    await new Promise<void>((resolve) => (proxy ? proxy.close(() => resolve()) : resolve()));
    await app?.close().catch(() => undefined);
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  app = await NestFactory.create(RunnerDoor, { logger: false, abortOnError: false });
  app.use(publicIdHeaders);
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
  app.useGlobalInterceptors(new PublicIdInterceptor());
  await app.listen(0, '127.0.0.1');
  const doorUrl = await app.getUrl();
  const doorPort = Number(doorUrl.slice(doorUrl.lastIndexOf(':') + 1));

  // ── the fault: a proxy that answers a claim by hanging up, with the claim already committed ────
  //
  // Dropping the RESPONSE rather than the request is the whole point: the control plane has already
  // run its PENDING -> RUNNING transaction and has already sent a job back, and the runner is left
  // with a transport error and no idea whether anything happened.
  const claimsToDrop = new Set<string>();
  const dropped: string[] = [];
  proxy = createServer((req, res) => {
    const chunks: Buffer[] = [];
    req.on('data', (chunk: Buffer) => chunks.push(chunk));
    req.on('error', () => res.destroy());
    req.on('end', () => {
      const upstream = httpRequest({
        host: '127.0.0.1',
        port: doorPort,
        method: req.method,
        path: req.url,
        headers: { ...req.headers, host: `127.0.0.1:${doorPort}` },
      }, (up) => {
        const body: Buffer[] = [];
        up.on('data', (chunk: Buffer) => body.push(chunk));
        up.on('end', () => {
          const payload = Buffer.concat(body);
          if (req.url === CLAIM_PATH) {
            let claimed: unknown;
            try { claimed = (JSON.parse(payload.toString('utf8')) as { sessionId?: unknown }).sessionId; } catch { /* an empty long poll */ }
            if (typeof claimed === 'string' && claimsToDrop.has(claimed)) {
              dropped.push(claimed);
              res.destroy();
              return;
            }
          }
          const headers = { ...up.headers };
          delete headers['transfer-encoding'];
          headers['content-length'] = String(payload.length);
          res.writeHead(up.statusCode ?? 502, headers);
          res.end(payload);
        });
      });
      upstream.on('error', () => res.destroy());
      if (chunks.length > 0) upstream.write(Buffer.concat(chunks));
      upstream.end();
    });
  });
  await new Promise<void>((resolve) => proxy!.listen(0, '127.0.0.1', resolve));
  const proxyPort = (proxy.address() as AddressInfo).port;

  // ── the fixture ────────────────────────────────────────────────────────────────────────────────
  /**
   * A queued session nobody has run: one person's message waiting for a first claim, with the two
   * images the incident's session carried. No engine has ever named this session's runtime id, which
   * is what makes the claim that follows a first spawn rather than a resume.
   *
   * Each scenario gets its own runner, and its own token: a reclaim returns every open session the
   * claiming machine owns, so two scenarios on one runner would each recover the other's session —
   * which is real runner behaviour and not what either of these cases is about.
   */
  async function queueSession(title: string, machineId: string): Promise<{ sessionId: string; turnId: string }> {
    const sessionId = randomUUID();
    const turnId = randomUUID();
    const workspaceId = randomUUID();
    const execDir = mkdtempSync(path.join(tmpdir(), 'claimrec-exec-'));
    await prisma.workspace.create({
      data: {
        id: workspaceId,
        ownerId,
        runnerId: machineId,
        name: 'the checkout this session runs in',
        enabled: true,
        workDir: execDir,
        // The session's own credentials, so the spawn's auth preflight never asks this machine's
        // login about a CLI that is not the real one.
        env: { ANTHROPIC_API_KEY: 'test' },
      },
    });
    await prisma.session.create({
      data: {
        id: sessionId,
        ownerId,
        creatorId: ownerId,
        workspaceId,
        assignedRunnerId: machineId,
        title,
        prompt: OPENING,
        provider: 'claude',
        status: RunStatus.PENDING,
        dispatchOrigin: 'USER',
        startsTaskWork: false,
      },
    });
    await prisma.conversationTurn.create({
      data: {
        id: turnId,
        sessionId,
        seq: 1,
        clientTurnId: randomUUID(),
        kind: 'message',
        content: OPENING,
        status: 'PENDING',
      },
    });
    for (const [i, name] of ['27.png', '28.png'].entries()) {
      await prisma.attachment.create({
        data: {
          id: randomUUID(),
          ownerId,
          sessionId,
          turnId,
          fileName: name,
          mimeType: 'image/png',
          sizeBytes: 64,
          data: Buffer.from(`not a real image, attachment ${i + 1}`),
        },
      });
    }
    return { sessionId, turnId };
  }

  /**
   * The scripted `claude`, put first on PATH. It records every spawn's argv before it reads its
   * script, so "what was this engine asked to do" is answerable even for a run that ended at once.
   * `script-resume.json`, when written, is what it answers a `--resume` with: the real CLI refuses a
   * conversation this machine does not hold, and no scripted stand-in reproduces that on its own.
   */
  function scriptedClaude(steps: unknown[], resumeSteps?: unknown[]): string {
    const dir = mkdtempSync(path.join(tmpdir(), 'claimrec-rec-'));
    writeFileSync(path.join(dir, 'script.json'), JSON.stringify(steps));
    if (resumeSteps) writeFileSync(path.join(dir, 'script-resume.json'), JSON.stringify(resumeSteps));
    const binDir = mkdtempSync(path.join(tmpdir(), 'claimrec-bin-'));
    writeFileSync(
      path.join(binDir, 'claude'),
      `#!/bin/sh\nORBIT_FAKE_CLAUDE_DIR='${dir}' exec '${binary}' "$@"\n`,
      { mode: 0o755 },
    );
    return binDir;
  }

  /** Start one runner process, with one scenario's scripted CLI in front on its PATH. */
  async function startRunner(binDir: string, token: string, home: string): Promise<ChildProcessWithoutNullStreams> {
    const child = spawn(binary, ['-test.run', '^TestClaimRecoveryFaultProcess$', '-test.v', '-test.timeout', '800s'], {
      cwd: RUNNER_GO,
      stdio: ['pipe', 'pipe', 'pipe'],
      env: {
        PATH: `${binDir}:${process.env.PATH ?? ''}`,
        // A scratch home, so nothing here reads or writes the real ~/.claude.
        HOME: home,
        ORBIT_HOME: path.join(home, 'orbit-home'),
        ORBIT_CLAIMREC_URL: `http://127.0.0.1:${proxyPort}`,
        ORBIT_CLAIMREC_TOKEN: token,
        ORBIT_NO_SELFUPDATE: '1',
        NO_COLOR: '1',
        TMPDIR: tmpdir(),
      },
    });
    children.push(child);
    return child;
  }

  /** The receipts the runner answered with, keyed by command id as they arrive. */
  function receiptsOf(child: ChildProcessWithoutNullStreams): Map<number, Receipt> {
    const answers = new Map<number, Receipt>();
    let buffered = '';
    child.stderr.on('data', (chunk: Buffer) => {
      buffered += chunk.toString('utf8');
      const lines = buffered.split('\n');
      buffered = lines.pop() ?? '';
      for (const line of lines) {
        const marker = line.indexOf('CLAIMREC ');
        if (marker < 0) continue;
        try {
          const parsed = JSON.parse(line.slice(marker + 'CLAIMREC '.length)) as Receipt;
          if (typeof parsed.id === 'number') answers.set(parsed.id, parsed);
        } catch { /* the runner's own stderr, not an answer */ }
      }
    });
    return answers;
  }

  async function command(child: ChildProcessWithoutNullStreams, answers: Map<number, Receipt>, id: number, body: Record<string, unknown>): Promise<Receipt> {
    child.stdin.write(`${JSON.stringify({ id, ...body })}\n`);
    const deadline = Date.now() + 120_000;
    while (Date.now() < deadline) {
      const answer = answers.get(id);
      if (answer) return answer;
      await sleep(50);
    }
    throw new Error(`the runner never answered ${JSON.stringify(body)}`);
  }

  /**
   * Run one scenario: queue a session, drop its claim's answer, let the runner recover it, and give
   * back what the runner decided plus what its engine was told.
   */
  async function runScenario(title: string, steps: unknown[], resumeSteps?: unknown[]): Promise<Scenario> {
    const token = `${RUNNER_TOKEN}:${randomUUID()}`;
    const machineId = randomUUID();
    await prisma.runner.create({
      data: { id: machineId, ownerId, name: 'the machine whose claim was lost', tokenHash: sha256(token), maxConcurrent: 4 },
    });
    const { sessionId, turnId } = await queueSession(title, machineId);
    const binDir = scriptedClaude(steps, resumeSteps);
    const child = await startRunner(binDir, token, mkdtempSync(path.join(tmpdir(), 'claimrec-home-')));
    const answers = receiptsOf(child);

    claimsToDrop.add(sessionId);
    const receipt = await command(child, answers, 1, { cmd: 'recover', execDir: mkdtempSync(path.join(tmpdir(), 'claimrec-run-')) });
    const recDir = readFileSync(path.join(binDir, 'claude'), 'utf8').match(/ORBIT_FAKE_CLAUDE_DIR='([^']+)'/)![1];
    const recovered = receipt.recovered as Array<Record<string, unknown>>;
    assert.equal(recovered?.length, 1, `the reclaim recovered ${JSON.stringify(recovered)}`);
    return {
      sessionId,
      turnId,
      sessionUuid: recovered[0].sessionUuid as string,
      machineId,
      recDir,
      spawns: () => {
        const file = path.join(recDir, 'spawns.jsonl');
        if (!existsSync(file)) return [];
        return readFileSync(file, 'utf8').split('\n').filter(Boolean)
          .map((line) => JSON.parse(line) as { pid: number; argv: string[]; cwd: string });
      },
      receipt,
    };
  }

  /** Poll until the read settles, so a spec never depends on how long a spawn takes. */
  async function eventually<T>(what: string, read: () => Promise<T | undefined>, timeoutMs = 90_000): Promise<T> {
    const deadline = Date.now() + timeoutMs;
    let last: T | undefined;
    while (Date.now() < deadline) {
      last = await read();
      if (last !== undefined) return last;
      await sleep(250);
    }
    throw new Error(`timed out waiting for ${what}`);
  }

  interface TurnRow {
    status: string;
    answered_at: Date | null;
    delivered_at: Date | null;
  }
  const turnRow = async (turnId: string): Promise<TurnRow> => {
    const { rows } = await sql.query<TurnRow>(
      'SELECT status, answered_at, delivered_at FROM "conversation_turn" WHERE id = $1::uuid', [turnId]);
    return rows[0];
  };
  interface SessionRow {
    status: string;
    num_turns: number;
    last_assistant_text: string | null;
  }
  const sessionRow = async (sessionId: string): Promise<SessionRow> => {
    const { rows } = await sql.query<SessionRow>(
      'SELECT status, num_turns, last_assistant_text FROM "session" WHERE id = $1::uuid', [sessionId]);
    return rows[0];
  };

  /**
   * The invariant this whole project is about, stated once and asserted by both scenarios: a session
   * that never said anything may not be sitting at AWAITING_INPUT, where the interface reads as an
   * agent waiting for the person rather than a question that was never answered.
   */
  function assertNotSilentlyParked(where: string, session: SessionRow): void {
    const silent = session.status === 'AWAITING_INPUT' && session.last_assistant_text === null;
    assert.equal(silent, false,
      `${where}: the session is parked at AWAITING_INPUT having never produced a word (num_turns ${session.num_turns})`);
  }

  // ── (1) the engine opens the conversation and answers ──────────────────────────────────────────
  await t.test('the recovered session is answered, not resumed into nothing', async () => {
    const scenario = await runScenario(
      'the session whose claim answer was lost',
      [{ await: 'user' }, { emit: 'system_init' }, { emit: 'assistant', text: 'Three things a person would misread.' }, { emit: 'result', text: 'Three things a person would misread.' }],
      // What the real CLI answers a --resume with on a machine that has never held this conversation.
      [{ emit: 'eof' }],
    );

    // The branch itself: the claim failed for a reason that may have committed, and the reclaim is
    // what recovered the session — as a first spawn, on an id nothing holds a conversation for.
    assert.ok(typeof scenario.receipt.claimError === 'string' && scenario.receipt.claimError !== '',
      `the claim was answered, so the chain under test never ran: ${JSON.stringify(scenario.receipt)}`);
    assert.equal(scenario.receipt.retryable, true, 'the lost claim was not treated as retryable');
    const recovered = scenario.receipt.recovered as Array<Record<string, unknown>>;
    assert.equal(recovered[0].sessionId, scenario.sessionId, 'the reclaim recovered a different session');
    assert.equal(recovered[0].reclaimed, true, 'the recovered job was not marked reclaimed');
    assert.equal(recovered[0].maxSeq, 0, 'the recovered job was not the never-run one (maxSeq must be 0)');
    assert.equal(recovered[0].firstSpawn, true, 'the recovered job did not resolve to a first spawn');
    assert.ok(dropped.includes(scenario.sessionId), 'the proxy did not drop the claim under test');

    // What the engine was handed. This is the whole first-spawn question: an id never opened is
    // opened, and a conversation this machine does not have is never resumed.
    const spawns = await eventually('the engine to be spawned', async () => {
      const seen = scenario.spawns();
      return seen.length > 0 ? seen : undefined;
    });
    assert.equal(spawns.length, 1, `the engine was spawned ${spawns.length} times, not once`);
    assert.ok(spawns[0].argv.includes('--session-id'), `the engine was not asked to open the conversation: ${spawns[0].argv.join(' ')}`);
    assert.ok(!spawns[0].argv.includes('--resume'), `the engine was asked to resume a conversation this machine has never held: ${spawns[0].argv.join(' ')}`);
    assert.equal(spawns[0].argv[spawns[0].argv.indexOf('--session-id') + 1], scenario.sessionUuid, 'the opened conversation is not this session');

    // The ending: something answered the person, and the reading of the row says so.
    const turn = await eventually('the turn to be answered', async () => {
      const row = await turnRow(scenario.turnId);
      return row.status === 'ANSWERED' ? row : undefined;
    });
    assert.notEqual(turn.answered_at, null, 'the turn is ANSWERED with no answered_at');
    const assistant = await sql.query<{ n: string }>(
      'SELECT count(*) AS n FROM "run_event" WHERE session_id = $1::uuid AND turn_id = $2::uuid AND type = $3',
      [scenario.sessionId, scenario.turnId, 'assistant']);
    assert.ok(Number(assistant.rows[0].n) > 0, 'the turn is ANSWERED with no assistant text under it');
    const session = await eventually('the session to carry the reply', async () => {
      const row = await sessionRow(scenario.sessionId);
      return row.last_assistant_text ? row : undefined;
    });
    assert.ok(session.num_turns > 0, `a conversation that was opened and answered advanced num_turns to ${session.num_turns}`);
    assertNotSilentlyParked('the answered session', session);

    // The images arrived with the message: the opening turn was delivered carrying both, which is
    // the half of the incident's report that the message itself was swallowed whole.
    const delivered = await sql.query<{ n: string }>(
      `SELECT jsonb_array_length(payload->'attachments') AS n FROM "run_event"
        WHERE session_id = $1::uuid AND turn_id = $2::uuid AND type = 'user'`,
      [scenario.sessionId, scenario.turnId]);
    assert.equal(Number(delivered.rows[0]?.n), 2, 'the engine was handed the message without its two images');
  });

  // ── (2) an engine that answers nothing ────────────────────────────────────────────────────────
  await t.test('a first spawn that produces no reply leaves the turn owed, not answered', async () => {
    const scenario = await runScenario(
      'the session whose engine could not answer',
      // The incident's completion, byte for byte, from an engine that was correctly asked to open
      // the conversation: `error_during_execution` with nothing said. It is not the resume bug —
      // that one is (1)'s — and the control plane cannot tell the two apart, which is the point.
      [{ await: 'user' }, { emit: 'result', subtype: 'error_during_execution', isError: true, text: 'No conversation found with session ID' }],
    );

    const recovered = scenario.receipt.recovered as Array<Record<string, unknown>>;
    assert.equal(recovered[0].firstSpawn, true, 'the recovered job did not resolve to a first spawn');

    const spawns = await eventually('the engine to be spawned', async () => {
      const seen = scenario.spawns();
      return seen.length > 0 ? seen : undefined;
    });
    assert.ok(spawns[0].argv.includes('--session-id'), `the engine was not asked to open the conversation: ${spawns[0].argv.join(' ')}`);

    // The engine ended the turn without answering. Wait for that turn to have ended at all — its
    // `turn_end` is written before the completion that follows it — and then ask what the control
    // plane did with a turn nothing answered.
    const turn = await eventually('the turn to be handed back', async () => {
      const ended = await sql.query<{ n: string }>(
        `SELECT count(*) AS n FROM "run_event"
          WHERE session_id = $1::uuid AND turn_id = $2::uuid AND type = 'turn_end'`,
        [scenario.sessionId, scenario.turnId]);
      if (Number(ended.rows[0].n) === 0) return undefined;
      const row = await turnRow(scenario.turnId);
      return row.delivered_at === null && row.status === 'PENDING' ? row : undefined;
    });
    assert.notEqual(turn.status, 'ANSWERED', 'a turn nothing answered was marked ANSWERED');
    assert.equal(turn.answered_at, null, 'a turn nothing answered carries an answered_at');

    // …and owed means nothing was consumed: the row still carries the words it was sent with and
    // both images are still hanging off it, so the delivery that comes back is this message again
    // and not a message with its attachments already spent. (What the next delivery hands over is
    // pinned by turn-complete-unanswered.pg.spec.ts; that the row is owed at all is this one's.)
    const queued = await sql.query<{ content: string; n: string }>(
      `SELECT t.content, (SELECT count(*) FROM "attachment" a WHERE a.turn_id = t.id) AS n
         FROM "conversation_turn" t WHERE t.id = $1::uuid`, [scenario.turnId]);
    assert.equal(queued.rows[0].content, OPENING, 'the requeued message lost the words it was sent with');
    assert.equal(Number(queued.rows[0].n), 2, 'the requeued message lost the two images it was sent with');

    const session = await sessionRow(scenario.sessionId);
    assertNotSilentlyParked('the session whose engine answered nothing', session);
    assert.notEqual(session.status, 'AWAITING_INPUT',
      'a session with a message still owed is not idle: the turn is back in the queue, so the session must read as running');
  });
});
