/**
 * The whole failure path, end to end: a claim whose answer is lost, the reclaim that recovers it,
 * and the first spawn of an engine for a session no engine has ever run.
 *
 * WHAT THIS DRIVES
 * ----------------
 * A session that was claimed and never answered — the runner's claim HTTP response dropped after the
 * control plane had already committed PENDING -> RUNNING. That is the chain in the project's own goal:
 *
 *   1. the runner's `claimSession` fails with a transport error (the harness's proxy drops the answer)
 *   2. `reclaimMissingSessions` picks the now-RUNNING row back up, `claimedSessionFromReclaim` marks it
 *      `Reclaimed` with `maxSeq` 0, and the run loop logs "recovering ambiguously claimed session"
 *   3. the supervisor starts and spawns the engine for the FIRST time
 *
 * The runner is this repository's Go runner, built from `src/runner-go` with the `claimrecoveryfault`
 * tag (`claim_recovery_fault_process_test.go`) and driven one command at a time. The control plane is
 * the real `RunnerApiController` behind the real `RunnerAuthGuard`, over a disposable PostgreSQL.
 * `claude` is the runner's own scripted fake CLI, put first on PATH, and it is asked for the two
 * endings a real engine has: it opens the conversation and answers, or it starts and dies without
 * answering.
 *
 * WHAT IT ASSERTS
 * ---------------
 * Neither ending may leave the session parked at AWAITING_INPUT having never said anything, and the
 * person's turn may be ANSWERED only when something answered it:
 *
 *   * (1) the engine was asked to OPEN the conversation (`--session-id`, never `--resume` on a
 *     conversation this machine has never held), the turn comes back ANSWERED, an ASSISTANT event
 *     hangs off it and the session carries the reply.
 *   * (2) an engine that starts and dies answers nothing: the turn is NOT ANSWERED, it is handed
 *     back to the queue with nothing outstanding and with its words and both images still on the
 *     row, the session is not parked as if it were idle, and the completion put it on the
 *     sweeper's retry ladder instead of leaving the message where nothing would deliver it. (That
 *     the next delivery hands the same turn — images included — over again is pinned where the
 *     inbox poll is driven: turn-complete-unanswered.pg.spec.ts.)
 *
 * Both are asserted against the database, read on a second connection, never through the answer that
 * wrote them.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/runner-api/claim-recovery-e2e.pg.spec.ts
 *
 * Needs COORDINATOR_PG_URL (the script provides a disposable one) and Go. Nothing here reaches a real
 * Claude account or a real model. Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { execFile, spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { createServer, request as httpRequest, type Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { test } from 'node:test';
import { setTimeout as sleep } from 'node:timers/promises';

import { type ArgumentsHost, HttpException, type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { type PrismaClient, RunStatus } from '@prisma/client';
import { uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { publicIdHeaders } from '../common/public-id-headers';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { AttemptBudgetMeterService } from '../projects/attempt-budget-meter.service';
import { assertCoordinatorPgUrlIsIsolated, verifyCoordinatorPgIdentity } from '../projects/coordinator-pg-test-safety';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { PushService } from '../push/push.service';
import { QueueService } from '../queue/queue.service';
import { RealtimeService } from '../realtime/realtime.service';
import { MergeReceiptService } from '../sessions/merge-receipt.service';
import { SessionsService } from '../sessions/sessions.service';
import { ListEventsService } from '../task-lists/list-events.service';
import { ReferenceExpansionService } from '../tasks/reference-expansion';
import { TasksService } from '../tasks/tasks.service';
import { RunnerApiController } from './runner-api.controller';
import { RunnerAuthGuard } from './runner-auth.guard';
import { RunnerOrchestrationAuthorizer } from './runner-orchestration-authorizer';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; session rows carry BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

const REPO = path.resolve(__dirname, '../../../..');
const RUNNER_GO = path.join(REPO, 'src/runner-go');
/** The runner's credential, in the clear. Its hash is what `RunnerAuthGuard` matches. */
const RUNNER_TOKEN = 'the-runner-token-for-a-lost-claim';
/** The path whose answer the proxy drops after the control plane has committed it. */
const CLAIM_PATH = '/api/runner/sessions/claim';
/** The opening question, in the words the incident's session was started with. */
const OPENING = 'review this confirm card and tell me what a person would misread';

/**
 * How long the scripted engine waits for the message it is about to answer nothing with — the
 * same number the waits below budget, and for a reason that is not symmetry:
 *
 * The engine is a real process on the other side of a real HTTP door, and the frame its
 * `await user` is waiting for has to be fetched and written to it by the runner. The fake CLI's
 * own default is ten seconds, which is right for a unit test whose peer is the test itself and
 * wrong here: an engine that gives up on a slow delivery exits without ever emitting the
 * `result` this file's second scenario waits for, and the completion that follows is then not
 * late — it is never written at all (the runner settles the never-written message as owed, and
 * fails the session). That is a spec that reports a product invariant missing when what went
 * missing was its own fixture's patience, and no budget on the wait can wait it out.
 *
 * So the engine is given the harness's own budget: whatever a delivery takes, the engine is
 * still there to receive it, and what the wait below measures is the product's settle rather
 * than this file's clock.
 */
const ENGINE_AWAIT_MS = 90_000;

/** A collaborator whose every method answers nothing: the broadcasts a claim fires. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

// ── what this run saw, on stderr, timestamps relative to the spec's own start ───────────────────
//
// The waits below are the only place this file can be wrong in a way its own assertions cannot
// name: a wait that ran out says "it never happened", which is the same sentence for a fact that
// was slow, a fact that was never going to exist, and a fact nobody wrote. On 2026-09-20 that
// ambiguity cost a session a CI red it could not read (`not ok 2 … duration_ms 90289`, twice, and
// clean on the re-run). So every wait reports how long the thing it waited for actually took —
// and on the way out, what the row, the session, the events and the engine's own stderr held at
// that moment. It is one line per observation, marked `CLAIMREC-TRACE`, and the harness reads
// TAP counts rather than this, so nothing downstream depends on it.
const TRACE_START = Date.now();
function trace(label: string, extra = ''): void {
  process.stderr.write(`CLAIMREC-TRACE ${Date.now() - TRACE_START}ms ${label}${extra ? ` ${extra}` : ''}\n`);
}

/** One `CLAIMREC {...}` answer from the runner process. */
type Receipt = Record<string, unknown>;

interface Scenario {
  sessionId: string;
  turnId: string;
  /** The runtime id the claim materialized: the conversation this session's engine has to open. */
  sessionUuid: string;
  /** The machine the session was queued on, which is the runner every request below must come from. */
  machineId: string;
  /** Where the scripted `claude` records its spawns and reads its script. */
  recDir: string;
  /** The argv of every process the runner spawned, oldest first. */
  spawns: () => Array<{ pid: number; argv: string[]; cwd: string }>;
  /** Every line the runner wrote, both streams, timestamped in arrival order — see trace(). */
  runnerLog: () => string[];
  receipt: Receipt;
}

test('a lost claim is recovered without the session ever going silent', {
  skip,
  concurrency: 1,
  timeout: 900_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);

  const ownerId = randomUUID();

  // ── the runner's own process: built once, started once per scenario ────────────────────────────
  await prisma.user.create({
    data: { id: ownerId, email: `claim-recovery-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  const workDir = mkdtempSync(path.join(tmpdir(), 'claimrec-'));
  const binary = path.join(workDir, 'runner-fault.bin');
  const built = await new Promise<{ code: number; stderr: string }>((resolve) => {
    execFile('go', ['test', '-c', '-tags', 'claimrecoveryfault', '-o', binary, '.'], {
      cwd: RUNNER_GO,
      maxBuffer: 32 * 1024 * 1024,
    }, (error, _stdout, stderr) => resolve({ code: error ? 1 : 0, stderr: String(stderr) }));
  });
  assert.equal(built.code, 0, `the runner's fault process did not build:\n${built.stderr}`);
  assert.ok(existsSync(binary), 'the build reported success and wrote no binary');

  // ── the control plane's own HTTP door, its guard and main.ts's middleware ──────────────────────
  const queue = new QueueService(prisma as unknown as PrismaService, silent() as never);
  const realtime = silent();
  const sessions = new SessionsService(prisma as unknown as PrismaService, queue as never, realtime as never);
  @Module({
    controllers: [RunnerApiController],
    providers: [
      { provide: PrismaService, useValue: prisma },
      { provide: QueueService, useValue: queue },
      { provide: SessionsService, useValue: sessions },
      { provide: RealtimeService, useValue: realtime },
      { provide: PushService, useValue: silent() },
      { provide: RunnerOrchestrationAuthorizer, useValue: {} },
      { provide: ReferenceExpansionService, useValue: { expand: async (_owner: string, content?: string) => content } },
      { provide: ListEventsService, useValue: { appendFor: async (_tx: unknown, _id: string, content?: string) => content } },
      // Answers, rather than being an empty object: after a completion commits, the door meters
      // that turn's spend through this collaborator, and `{}` has no `meterQuietly` to call — so
      // EVERY completion answered 500, after its write had already committed, which is why the
      // database kept looking right and nothing here noticed. The runner retries a 5xx without a
      // ceiling, on its own backoff ladder (measured: eight retries of one turn, 0.3s→2.1s apart),
      // and each retry re-runs the settle — which is what turned the settled row into a state the
      // waits below could only ever catch between two of their own polls. `silent()` answers
      // undefined for every method, and the door awaits the answer, so undefined is what it takes.
      { provide: AttemptBudgetMeterService, useValue: silent() },
      { provide: ProjectAcceptanceService, useValue: {} },
      { provide: TasksService, useValue: {} },
      { provide: MergeReceiptService, useValue: {} },
      RunnerAuthGuard,
    ],
  })
  class RunnerDoor {}

  let app: INestApplication | undefined;
  let proxy: Server | undefined;
  const children: ChildProcessWithoutNullStreams[] = [];
  // One entry per scenario, holding everything its runner wrote.
  const runnerLogs: string[][] = [];
  t.after(async () => {
    for (const log of runnerLogs) for (const line of log) process.stderr.write(`CLAIMREC-RUNNER ${line}\n`);
    for (const child of children) child.kill('SIGKILL');
    await new Promise<void>((resolve) => (proxy ? proxy.close(() => resolve()) : resolve()));
    await app?.close().catch(() => undefined);
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  app = await NestFactory.create(RunnerDoor, { logger: false, abortOnError: false });
  // DIAGNOSTIC: the door's own account of a request it was slow to answer. The proxy on the other
  // side of it times the same round trip, so the two together say whether a late answer was the
  // door working or the door never being asked — the fixture's `logger: false` is otherwise the one
  // place a run of this says nothing at all.
  app.use((req: { method?: string; url?: string }, res: { statusCode?: number; on(event: string, listener: () => void): void }, next: () => void): void => {
    const at = Date.now();
    res.on('finish', () => {
      const ms = Date.now() - at;
      if (ms > 200) trace('DOOR', `${req.method ?? '?'} ${(req.url ?? '').split('?')[0]} ${ms}ms -> ${res.statusCode ?? '?'}`);
    });
    next();
  });
  app.use(publicIdHeaders);
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
  app.useGlobalInterceptors(new PublicIdInterceptor());
  // DIAGNOSTIC: what a 5xx was ABOUT. Nest answers a thrown error with a 500 and no body worth
  // reading, and `logger: false` means the fixture prints nothing about it at all — so a runner
  // retrying a completion for ninety seconds is invisible from both ends. The status and the body
  // a caller would have seen are unchanged; this only says what was thrown.
  app.useGlobalFilters({
    catch(exception: unknown, host: ArgumentsHost): void {
      const http = host.switchToHttp();
      const req = http.getRequest<{ method?: string; url?: string }>();
      const res = http.getResponse<{ status(code: number): { send(body: unknown): void } }>();
      const status = exception instanceof HttpException ? exception.getStatus() : 500;
      if (status >= 500) {
        const err = exception as { name?: string; message?: string; code?: string };
        trace('DOOR-500', `${req.method} ${(req.url ?? '').split('?')[0]} ${err.name ?? 'Error'} ${err.code ?? ''}: ${err.message ?? ''}`);
      }
      res.status(status).send(
        exception instanceof HttpException ? exception.getResponse() : { statusCode: 500, message: 'Internal server error' },
      );
    },
  });
  await app.listen(0, '127.0.0.1');
  const doorUrl = await app.getUrl();
  const doorPort = Number(doorUrl.slice(doorUrl.lastIndexOf(':') + 1));

  // ── the fault: a proxy that answers a claim by hanging up, with the claim already committed ────
  //
  // Dropping the RESPONSE rather than the request is the whole point: the control plane has already
  // run its PENDING -> RUNNING transaction and has already sent a job back, and the runner is left
  // with a transport error and no idea whether anything happened.
  const claimsToDrop = new Set<string>();
  const dropped: string[] = [];
  proxy = createServer((req, res) => {
    // DIAGNOSTIC: every request the runner makes, with how long the door took to answer it. A
    // settle this spec waits on is either a request the door was slow to answer or one that was
    // never made, and those two look identical from the database the wait is reading.
    const arrivedAt = Date.now();
    res.on('finish', () => {
      const ms = Date.now() - arrivedAt;
      if (ms > 200 || (req.url ?? '').includes('turn-complete')) {
        trace('PROXY', `${req.method} ${(req.url ?? '').split('?')[0]} ${ms}ms -> ${res.statusCode}`);
      }
    });
    const chunks: Buffer[] = [];
    req.on('data', (chunk: Buffer) => chunks.push(chunk));
    req.on('error', () => res.destroy());
    req.on('end', () => {
      const upstream = httpRequest({
        host: '127.0.0.1',
        port: doorPort,
        method: req.method,
        path: req.url,
        headers: { ...req.headers, host: `127.0.0.1:${doorPort}` },
      }, (up) => {
        const body: Buffer[] = [];
        up.on('data', (chunk: Buffer) => body.push(chunk));
        up.on('end', () => {
          const payload = Buffer.concat(body);
          if (req.url === CLAIM_PATH) {
            let claimed: unknown;
            try { claimed = (JSON.parse(payload.toString('utf8')) as { sessionId?: unknown }).sessionId; } catch { /* an empty long poll */ }
            if (typeof claimed === 'string' && claimsToDrop.has(claimed)) {
              dropped.push(claimed);
              res.destroy();
              return;
            }
          }
          const headers = { ...up.headers };
          delete headers['transfer-encoding'];
          headers['content-length'] = String(payload.length);
          res.writeHead(up.statusCode ?? 502, headers);
          res.end(payload);
        });
      });
      upstream.on('error', () => res.destroy());
      if (chunks.length > 0) upstream.write(Buffer.concat(chunks));
      upstream.end();
    });
  });
  await new Promise<void>((resolve) => proxy!.listen(0, '127.0.0.1', resolve));
  const proxyPort = (proxy.address() as AddressInfo).port;

  // ── the fixture ────────────────────────────────────────────────────────────────────────────────
  /**
   * A queued session nobody has run: one person's message waiting for a first claim, with the two
   * images the incident's session carried. No engine has ever named this session's runtime id, which
   * is what makes the claim that follows a first spawn rather than a resume.
   *
   * Each scenario gets its own runner, and its own token: a reclaim returns every open session the
   * claiming machine owns, so two scenarios on one runner would each recover the other's session —
   * which is real runner behaviour and not what either of these cases is about.
   */
  async function queueSession(title: string, machineId: string): Promise<{ sessionId: string; turnId: string }> {
    const sessionId = randomUUID();
    const turnId = randomUUID();
    const workspaceId = randomUUID();
    const execDir = mkdtempSync(path.join(tmpdir(), 'claimrec-exec-'));
    await prisma.workspace.create({
      data: {
        id: workspaceId,
        ownerId,
        runnerId: machineId,
        name: 'the checkout this session runs in',
        enabled: true,
        workDir: execDir,
        // The session's own credentials, so the spawn's auth preflight never asks this machine's
        // login about a CLI that is not the real one.
        env: { ANTHROPIC_API_KEY: 'test' },
      },
    });
    await prisma.session.create({
      data: {
        id: sessionId,
        ownerId,
        creatorId: ownerId,
        workspaceId,
        assignedRunnerId: machineId,
        title,
        prompt: OPENING,
        provider: 'claude',
        status: RunStatus.PENDING,
        dispatchOrigin: 'USER',
        startsTaskWork: false,
      },
    });
    await prisma.conversationTurn.create({
      data: {
        id: turnId,
        sessionId,
        seq: 1,
        clientTurnId: randomUUID(),
        kind: 'message',
        content: OPENING,
        status: 'PENDING',
      },
    });
    for (const [i, name] of ['27.png', '28.png'].entries()) {
      await prisma.attachment.create({
        data: {
          id: randomUUID(),
          ownerId,
          sessionId,
          turnId,
          fileName: name,
          mimeType: 'image/png',
          sizeBytes: 64,
          data: Buffer.from(`not a real image, attachment ${i + 1}`),
        },
      });
    }
    return { sessionId, turnId };
  }

  /**
   * The scripted `claude`, put first on PATH. It records every spawn's argv before it reads its
   * script, so "what was this engine asked to do" is answerable even for a run that ended at once.
   * `script-resume.json`, when written, is what it answers a `--resume` with: the real CLI refuses a
   * conversation this machine does not hold, and no scripted stand-in reproduces that on its own.
   */
  function scriptedClaude(steps: unknown[], resumeSteps?: unknown[]): string {
    const dir = mkdtempSync(path.join(tmpdir(), 'claimrec-rec-'));
    writeFileSync(path.join(dir, 'script.json'), JSON.stringify(steps));
    if (resumeSteps) writeFileSync(path.join(dir, 'script-resume.json'), JSON.stringify(resumeSteps));
    const binDir = mkdtempSync(path.join(tmpdir(), 'claimrec-bin-'));
    writeFileSync(
      path.join(binDir, 'claude'),
      `#!/bin/sh\nORBIT_FAKE_CLAUDE_DIR='${dir}' exec '${binary}' "$@"\n`,
      { mode: 0o755 },
    );
    return binDir;
  }

  /** Start one runner process, with one scenario's scripted CLI in front on its PATH. */
  async function startRunner(binDir: string, token: string, home: string, log?: string[]): Promise<ChildProcessWithoutNullStreams> {
    const child = spawn(binary, ['-test.run', '^TestClaimRecoveryFaultProcess$', '-test.v', '-test.timeout', '800s'], {
      cwd: RUNNER_GO,
      stdio: ['pipe', 'pipe', 'pipe'],
      env: {
        PATH: `${binDir}:${process.env.PATH ?? ''}`,
        // A scratch home, so nothing here reads or writes the real ~/.claude.
        HOME: home,
        ORBIT_HOME: path.join(home, 'orbit-home'),
        ORBIT_CLAIMREC_URL: `http://127.0.0.1:${proxyPort}`,
        ORBIT_CLAIMREC_TOKEN: token,
        // The scripted engine's patience with the delivery it is waiting for — see ENGINE_AWAIT_MS.
        ORBIT_FAKE_CLAUDE_AWAIT_MS: String(ENGINE_AWAIT_MS),
        ORBIT_NO_SELFUPDATE: '1',
        NO_COLOR: '1',
        TMPDIR: tmpdir(),
      },
    });
    children.push(child);
    // The runner's own account of the run, timestamped as it arrives.
    if (log) {
      let outBuffered = '';
      child.stdout.on('data', (chunk: Buffer) => {
        outBuffered += chunk.toString('utf8');
        const lines = outBuffered.split('\n');
        outBuffered = lines.pop() ?? '';
        for (const line of lines) if (line.trim() !== '') log.push(`${Date.now() - TRACE_START}ms [out] ${line}`);
      });
    }
    return child;
  }

  /** The receipts the runner answered with, keyed by command id as they arrive. */
  function receiptsOf(child: ChildProcessWithoutNullStreams, log?: string[]): Map<number, Receipt> {
    const answers = new Map<number, Receipt>();
    let buffered = '';
    child.stderr.on('data', (chunk: Buffer) => {
      buffered += chunk.toString('utf8');
      const lines = buffered.split('\n');
      buffered = lines.pop() ?? '';
      for (const line of lines) {
        const marker = line.indexOf('CLAIMREC ');
        if (marker < 0) {
          // The runner's own stderr — the scripted engine's complaints arrive on this stream too.
          if (log && line.trim() !== '') log.push(`${Date.now() - TRACE_START}ms [err] ${line}`);
          continue;
        }
        try {
          const parsed = JSON.parse(line.slice(marker + 'CLAIMREC '.length)) as Receipt;
          if (typeof parsed.id === 'number') answers.set(parsed.id, parsed);
        } catch { /* the runner's own stderr, not an answer */ }
      }
    });
    return answers;
  }

  async function command(child: ChildProcessWithoutNullStreams, answers: Map<number, Receipt>, id: number, body: Record<string, unknown>): Promise<Receipt> {
    child.stdin.write(`${JSON.stringify({ id, ...body })}\n`);
    const deadline = Date.now() + 120_000;
    while (Date.now() < deadline) {
      const answer = answers.get(id);
      if (answer) return answer;
      await sleep(50);
    }
    throw new Error(`the runner never answered ${JSON.stringify(body)}`);
  }

  /**
   * Run one scenario: queue a session, drop its claim's answer, let the runner recover it, and give
   * back what the runner decided plus what its engine was told.
   */
  async function runScenario(title: string, steps: unknown[], resumeSteps?: unknown[]): Promise<Scenario> {
    const token = `${RUNNER_TOKEN}:${randomUUID()}`;
    const machineId = randomUUID();
    await prisma.runner.create({
      data: { id: machineId, ownerId, name: 'the machine whose claim was lost', tokenHash: sha256(token), maxConcurrent: 4 },
    });
    const { sessionId, turnId } = await queueSession(title, machineId);
    const binDir = scriptedClaude(steps, resumeSteps);
    const log: string[] = [];
    runnerLogs.push(log);
    trace(`scenario ${JSON.stringify(title)} — runner starting`);
    const child = await startRunner(binDir, token, mkdtempSync(path.join(tmpdir(), 'claimrec-home-')), log);
    const answers = receiptsOf(child, log);

    claimsToDrop.add(sessionId);
    const recoverSentAt = Date.now();
    const receipt = await command(child, answers, 1, { cmd: 'recover', execDir: mkdtempSync(path.join(tmpdir(), 'claimrec-run-')) });
    trace(`scenario ${JSON.stringify(title)} — recover answered`, `${Date.now() - recoverSentAt}ms, claimDurationMs=${String(receipt.claimDurationMs)}`);
    const recDir = readFileSync(path.join(binDir, 'claude'), 'utf8').match(/ORBIT_FAKE_CLAUDE_DIR='([^']+)'/)![1];
    const recovered = receipt.recovered as Array<Record<string, unknown>>;
    assert.equal(recovered?.length, 1, `the reclaim recovered ${JSON.stringify(recovered)}`);
    return {
      sessionId,
      turnId,
      sessionUuid: recovered[0].sessionUuid as string,
      machineId,
      recDir,
      spawns: () => {
        const file = path.join(recDir, 'spawns.jsonl');
        if (!existsSync(file)) return [];
        return readFileSync(file, 'utf8').split('\n').filter(Boolean)
          .map((line) => JSON.parse(line) as { pid: number; argv: string[]; cwd: string });
      },
      runnerLog: () => log,
      receipt,
    };
  }

  /**
   * Poll until the read settles, so a spec never depends on how long a spawn takes. It also says
   * how long the fact it was waiting for actually took — whether it arrived or not, which is the
   * number a budget has to be argued from rather than a green run's silence (see trace()).
   */
  async function eventually<T>(what: string, read: () => Promise<T | undefined>, timeoutMs = 90_000): Promise<T> {
    const started = Date.now();
    const deadline = started + timeoutMs;
    let last: T | undefined;
    let polls = 0;
    while (Date.now() < deadline) {
      last = await read();
      polls += 1;
      if (last !== undefined) {
        trace(`eventually OK ${JSON.stringify(what)}`, `${Date.now() - started}ms (${polls} polls, budget ${timeoutMs}ms)`);
        return last;
      }
      await sleep(250);
    }
    throw new Error(`timed out waiting for ${what} (waited ${Date.now() - started}ms of a ${timeoutMs}ms budget, ${polls} polls, last read ${JSON.stringify(last)})`);
  }

  interface TurnRow {
    status: string;
    answered_at: Date | null;
    delivered_at: Date | null;
  }
  const turnRow = async (turnId: string): Promise<TurnRow> => {
    const { rows } = await sql.query<TurnRow>(
      'SELECT status, answered_at, delivered_at FROM "conversation_turn" WHERE id = $1::uuid', [turnId]);
    return rows[0];
  };
  interface SessionRow {
    status: string;
    num_turns: number;
    last_assistant_text: string | null;
    /** Non-null while the sweeper owes this session another attempt — see auto-retry.service. */
    retry_at: Date | null;
  }
  const sessionRow = async (sessionId: string): Promise<SessionRow> => {
    const { rows } = await sql.query<SessionRow>(
      'SELECT status, num_turns, last_assistant_text, retry_at FROM "session" WHERE id = $1::uuid', [sessionId]);
    return rows[0];
  };

  /**
   * What the database held at the moment a wait gave up: the turn's own row, the session's, every
   * run_event type filed under it, what the engine's stderr said, and what the engines were
   * spawned with. Dumped rather than inferred, because a wait that ran out cannot tell "the fact
   * never arrived" from "the fact arrived late" — and those are two different bugs.
   */
  async function dumpScenario(where: string, scenario: Scenario): Promise<void> {
    const turn = await turnRow(scenario.turnId).catch((err: Error) => ({ err: err.message }));
    const session = await sessionRow(scenario.sessionId).catch((err: Error) => ({ err: err.message }));
    const events = await sql.query<{ type: string; n: string }>(
      'SELECT type, count(*) AS n FROM "run_event" WHERE session_id = $1::uuid GROUP BY type ORDER BY type',
      [scenario.sessionId]).catch(() => ({ rows: [] as Array<{ type: string; n: string }> }));
    // What the engine's own stderr said, which is where a stand-in that gave up on the delivery
    // names itself ("fake claude: timed out waiting for a frame") — the one line that tells a
    // delivery that never arrived from a completion that never came.
    const engineStderr = await sql.query<{ text: string }>(
      `SELECT payload->>'stderr' AS text FROM "run_event"
        WHERE session_id = $1::uuid AND type = 'system' AND payload ? 'stderr' ORDER BY seq`,
      [scenario.sessionId]).catch(() => ({ rows: [] as Array<{ text: string }> }));
    trace(`DUMP ${where} — turns`, JSON.stringify(turn));
    trace(`DUMP ${where} — session`, JSON.stringify(session));
    trace(`DUMP ${where} — run_event`, JSON.stringify(events.rows.map((r) => `${r.type}:${r.n}`)));
    trace(`DUMP ${where} — engine stderr`, JSON.stringify(engineStderr.rows.map((r) => r.text.trim())));
    // The flags, not the whole argv: the appended system prompt is thousands of characters and
    // says nothing about this run. What matters is --session-id vs --resume, and how many spawns.
    const spawns = scenario.spawns();
    trace(`DUMP ${where} — spawns`, JSON.stringify(spawns.map((s) => s.argv.slice(0, 12).join(' '))));
    const stdinFile = path.join(scenario.recDir, 'stdin.jsonl');
    trace(`DUMP ${where} — frames the engine read off stdin`, existsSync(stdinFile) ? readFileSync(stdinFile, 'utf8') : '(no stdin.jsonl)');
    for (const line of scenario.runnerLog()) process.stderr.write(`CLAIMREC-RUNNER ${line}\n`);
  }

  /**
   * The invariant this whole project is about, stated once and asserted by both scenarios: a session
   * that never said anything may not be sitting at AWAITING_INPUT, where the interface reads as an
   * agent waiting for the person rather than a question that was never answered.
   */
  function assertNotSilentlyParked(where: string, session: SessionRow): void {
    const silent = session.status === 'AWAITING_INPUT' && session.last_assistant_text === null;
    assert.equal(silent, false,
      `${where}: the session is parked at AWAITING_INPUT having never produced a word (num_turns ${session.num_turns})`);
  }

  // ── (1) the engine opens the conversation and answers ──────────────────────────────────────────
  await t.test('the recovered session is answered, not resumed into nothing', async () => {
    const scenario = await runScenario(
      'the session whose claim answer was lost',
      [{ await: 'user' }, { emit: 'system_init' }, { emit: 'assistant', text: 'Three things a person would misread.' }, { emit: 'result', text: 'Three things a person would misread.' }],
      // What the real CLI answers a --resume with on a machine that has never held this conversation.
      [{ emit: 'eof' }],
    );

    // The ending first, because it is what the person sees: something answered the message, and
    // the reading of the row says so. A session that recovered into a resume of nothing lands here
    // as the opposite — a turn consumed with no word under it — which is where the fix's absence
    // has to show.
    const turn = await eventually('the turn to be answered', async () => {
      const row = await turnRow(scenario.turnId);
      return row.status === 'ANSWERED' ? row : undefined;
    });
    assert.notEqual(turn.answered_at, null, 'the turn is ANSWERED with no answered_at');
    const assistant = await sql.query<{ n: string }>(
      'SELECT count(*) AS n FROM "run_event" WHERE session_id = $1::uuid AND turn_id = $2::uuid AND type = $3',
      [scenario.sessionId, scenario.turnId, 'assistant']);
    assert.ok(Number(assistant.rows[0].n) > 0, 'the turn is ANSWERED with no assistant text under it');
    const session = await eventually('the session to carry the reply', async () => {
      const row = await sessionRow(scenario.sessionId);
      return row.last_assistant_text ? row : undefined;
    });
    assert.ok(session.num_turns > 0, `a conversation that was opened and answered advanced num_turns to ${session.num_turns}`);
    assertNotSilentlyParked('the answered session', session);

    // The images arrived with the message: the opening turn was delivered carrying both, which is
    // the half of the incident's report that the message itself was swallowed whole.
    const delivered = await sql.query<{ n: string }>(
      `SELECT jsonb_array_length(payload->'attachments') AS n FROM "run_event"
        WHERE session_id = $1::uuid AND turn_id = $2::uuid AND type = 'user'`,
      [scenario.sessionId, scenario.turnId]);
    assert.equal(Number(delivered.rows[0]?.n), 2, 'the engine was handed the message without its two images');

    // What the engine was handed. This is the whole first-spawn question: an id never opened is
    // opened, and a conversation this machine does not have is never resumed.
    const spawns = await eventually('the engine to be spawned', async () => {
      const seen = scenario.spawns();
      return seen.length > 0 ? seen : undefined;
    });
    trace('first spawn recorded', `${statSync(path.join(scenario.recDir, 'spawns.jsonl')).mtimeMs - TRACE_START}ms`);
    assert.equal(spawns.length, 1, `the engine was spawned ${spawns.length} times, not once`);
    assert.ok(spawns[0].argv.includes('--session-id'), `the engine was not asked to open the conversation: ${spawns[0].argv.join(' ')}`);
    assert.ok(!spawns[0].argv.includes('--resume'), `the engine was asked to resume a conversation this machine has never held: ${spawns[0].argv.join(' ')}`);
    assert.equal(spawns[0].argv[spawns[0].argv.indexOf('--session-id') + 1], scenario.sessionUuid, 'the opened conversation is not this session');

    // And the runner's own account of the branch: the claim failed for a reason that may have
    // committed, and the reclaim is what recovered the session, as a first spawn on an id nothing
    // holds a conversation for. Corroboration for the two readings above, not a substitute.
    assert.ok(typeof scenario.receipt.claimError === 'string' && scenario.receipt.claimError !== '',
      `the claim was answered, so the chain under test never ran: ${JSON.stringify(scenario.receipt)}`);
    assert.equal(scenario.receipt.retryable, true, 'the lost claim was not treated as retryable');
    const recovered = scenario.receipt.recovered as Array<Record<string, unknown>>;
    assert.equal(recovered[0].sessionId, scenario.sessionId, 'the reclaim recovered a different session');
    assert.equal(recovered[0].reclaimed, true, 'the recovered job was not marked reclaimed');
    assert.equal(recovered[0].maxSeq, 0, 'the recovered job was not the never-run one (maxSeq must be 0)');
    assert.equal(recovered[0].firstSpawn, true, 'the recovered job did not resolve to a first spawn');
    assert.ok(dropped.includes(scenario.sessionId), 'the proxy did not drop the claim under test');
  });

  // ── (2) an engine that answers nothing ────────────────────────────────────────────────────────
  await t.test('a first spawn that produces no reply leaves the turn owed, not answered', async () => {
    const scenario = await runScenario(
      'the session whose engine could not answer',
      // The incident's completion, byte for byte, from an engine that was correctly asked to open
      // the conversation: `error_during_execution`, `num_turns` 0, and nothing billed. It is not
      // the resume bug — that one is (1)'s — and the control plane cannot tell the two apart, which
      // is the point. The counter is not decoration: "ran no turn and billed nothing" is half of
      // what the completion reads to arm the retry this case ends on.
      [{ await: 'user' }, { emit: 'result', subtype: 'error_during_execution', isError: true, text: 'No conversation found with session ID', numTurns: 0 }],
    );

    const recovered = scenario.receipt.recovered as Array<Record<string, unknown>>;
    assert.equal(recovered[0].firstSpawn, true, 'the recovered job did not resolve to a first spawn');

    const spawns = await eventually('the engine to be spawned', async () => {
      const seen = scenario.spawns();
      return seen.length > 0 ? seen : undefined;
    });
    // The engine-side half of the timeline, read off the fake's own recordings.
    trace('first spawn recorded', `${statSync(path.join(scenario.recDir, 'spawns.jsonl')).mtimeMs - TRACE_START}ms`);
    assert.ok(spawns[0].argv.includes('--session-id'), `the engine was not asked to open the conversation: ${spawns[0].argv.join(' ')}`);

    // The engine ended the turn without answering. Its `turn_end` is written before the completion
    // that follows it, so wait for the control plane to have settled the row one way or the other,
    // then say which way: waiting only for the handing-back would report the missing invariant as a
    // timeout, where the invariant's absence is a thing this can name.
    //
    // "Settled" is read off two facts that STAY true, and deliberately not off the row's `status`:
    //
    //   * the runner wrote this turn's `turn_end` — it does that before it reports the turn, and
    //   * the completion's own record landed. Its ACK arms the session's retry ladder for a turn
    //     that ran nothing and billed nothing, and it ANSWERS the row when something did answer the
    //     person — the two outcomes this scenario exists to tell apart.
    //
    // The row's status is not one of them. A requeued turn is handed to the engine again as soon as
    // the runner's inbox poll comes round — that second delivery is exactly what "handed back" is
    // for — so `PENDING` exists for about sixty milliseconds at a time (measured: 20ms sampler,
    // 61ms window). Waiting for `status` on a 250ms poll is a lottery on that window, and a
    // completion the runner has to retry makes the window RARER rather than wider: each retry
    // re-queues, each re-delivery re-marks, and once the retries' backoff outruns the wait the row
    // is IN_FLIGHT for the rest of it. That is the `not ok 2 … duration_ms 90289` this spec spent
    // two CI runs reporting as a timeout with no reading of its own.
    let endedSeen = 0;
    let statusSeen = '';
    let stdinSeen = 0;
    let armedSeen = '';
    const settleWait = 'the turn to be settled by the completion that followed it';
    const turn = await eventually(settleWait, async () => {
      const ended = await sql.query<{ n: string }>(
        `SELECT count(*) AS n FROM "run_event"
          WHERE session_id = $1::uuid AND turn_id = $2::uuid AND type = 'turn_end'`,
        [scenario.sessionId, scenario.turnId]);
      const endedCount = Number(ended.rows[0].n);
      if (endedCount !== endedSeen) {
        endedSeen = endedCount;
        trace('turn_end events in run_event', String(endedCount));
      }
      const frames = existsSync(path.join(scenario.recDir, 'stdin.jsonl'))
        ? readFileSync(path.join(scenario.recDir, 'stdin.jsonl'), 'utf8').split('\n').filter(Boolean).length
        : 0;
      if (frames !== stdinSeen) {
        stdinSeen = frames;
        trace('frames the engine read off stdin', String(frames));
      }
      if (endedCount === 0) return undefined;
      const row = await turnRow(scenario.turnId);
      if (row.status !== statusSeen) {
        statusSeen = row.status;
        trace('turn row is now', row.status);
      }
      const session = await sessionRow(scenario.sessionId);
      const armed = session.retry_at ? String(session.retry_at) : '';
      if (armed !== armedSeen) {
        armedSeen = armed;
        trace('the completion armed the retry ladder at', armed === '' ? '(not armed)' : armed);
      }
      return row.status === 'ANSWERED' || session.retry_at !== null ? row : undefined;
    }).catch(async (err: Error) => {
      await dumpScenario(settleWait, scenario);
      throw err;
    });
    assert.notEqual(turn.status, 'ANSWERED', 'a turn nothing answered was marked ANSWERED');
    assert.equal(turn.answered_at, null, 'a turn nothing answered carries an answered_at');
    // NOT `assert.equal(turn.delivered_at, null)`, which this file used to say and which cannot be
    // read here: by the time the settle above is visible the runner has usually handed the requeued
    // message to the engine again, so the delivery on the row IS that next one. What that assertion
    // meant — the failed attempt's delivery is out of the way — is carried by the retry ladder
    // armed in the same transaction as the requeue (asserted at the end of this case), and by the
    // row still holding the words and both images. A delivery that is still there says nothing
    // either way, and asserting it is how this spec came to be red on CI for a state the product
    // leaves on its own.

    // …and owed means nothing was consumed: the row still carries the words it was sent with and
    // both images are still hanging off it, so the delivery that comes back is this message again
    // and not a message with its attachments already spent. What the next delivery hands over is
    // read off the row, not watched: this runner's inbox is never polled a second time here, so
    // the delivery itself is pinned where the poll is driven — turn-complete-unanswered.pg.spec.
    const queued = await sql.query<{ content: string; n: string }>(
      `SELECT t.content, (SELECT count(*) FROM "attachment" a WHERE a.turn_id = t.id) AS n
         FROM "conversation_turn" t WHERE t.id = $1::uuid`, [scenario.turnId]);
    assert.equal(queued.rows[0].content, OPENING, 'the requeued message lost the words it was sent with');
    assert.equal(Number(queued.rows[0].n), 2, 'the requeued message lost the two images it was sent with');

    // What the completion left the session as. Read here, not waited on: the ack above and this
    // row are written in one transaction, so a settle that has happened cannot leave either half
    // unseen — and an arm that never arrives is the third fix's absence, which a timeout would
    // report as nothing having happened.
    const session = await sessionRow(scenario.sessionId);
    assertNotSilentlyParked('the session whose engine answered nothing', session);
    assert.notEqual(session.status, 'AWAITING_INPUT',
      'a session with a message still owed is not idle: the turn is back in the queue, so the session must read as running');
    assert.notEqual(session.retry_at, null,
      'a startup that ran no turn, billed nothing and answered nothing was left off the retry ladder');
  });
});
