/**
 * A background launch that never happened is not a running process: the session list's
 * "N background processes running" does not count the call the runner's own bg-guard hook refused.
 *
 * `Session.runningBgShells` is what the list and the header read that count from, and it is folded
 * from launches. The fold took a `Bash(run_in_background)` tool_use as proof one had occurred —
 * while the result that says whether it did sat in the same batch. For the refusal that is the whole
 * event: `orbit hook bg-guard` (runner-go hook_bg_guard.go) denies the call, no process is ever
 * created, and no terminal <task-notification> can arrive for a shell the runner never registered
 * (runner-go background.go). So the id stayed in the set for good — one live session read "5
 * background processes running" from 09-20 until something else emptied the set, while its tray read
 * "1 running" off the same history (the tray derives from the shared derivation, which has always
 * required the receipt).
 *
 * Four facts, each asserted through the runner door's own handler and read back out of the column
 * the clients read:
 *
 *   1. A batch carrying the refused pair beside a real launch counts the real one and not the
 *      refused one — the two differ only in what their results say.
 *   2. The 250ms flush may split a launch from its own result: the verdict comes from the tool_call
 *      row, where the pair is joined, so the launch is counted when its result lands in the batch
 *      after it — and the refused one is not counted when its refusal does.
 *   3. A set already wedged that way heals at the next fold: the refused id is dropped while the
 *      Monitor receipts and the runner-hosted job beside it stay — the shape the live session had.
 *   4. That healing needs no new evidence at all: a batch that mentions none of them drops the
 *      refused id, and leaves the ones with a receipt and the `bgj_` job, which states itself with a
 *      `running` report and has no launch row to read.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/runner-api/refused-bg-launch-not-counted.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type PrismaClient, RunStatus, SessionDispatchOrigin } from '@prisma/client';
import { type NormalizedRunEvent, RunEventType } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { RunnerApiController } from './runner-api.controller';

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** A collaborator whose every method answers nothing: the broadcasts the handler fires. */
const silent = (): never =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) }) as never;

type Reported = Pick<NormalizedRunEvent, 'type' | 'payload'>;

/** The call the hook refused, the shell that really started, and the two Monitors beside them. */
const REFUSED = 'toolu_01RefusedByBgGuard';
const LAUNCHED = 'toolu_01CommandReallyStarted';
const MONITOR_A = 'toolu_01MonitorTailOne';
const MONITOR_B = 'toolu_01MonitorTailTwo';
/** The runner-hosted job (`bg_run`), which reports itself and never has a launch tool_use here. */
const JOB = 'bgj_b0dc1aeed09f';

/**
 * `orbit hook bg-guard`'s refusal, verbatim — the `bgGuardDenyReason` const in
 * src/runner-go/hook_bg_guard.go, which is what the engine gets back for a `Bash` it refuses. The
 * tool_call row holds this as the call's output, which is all the fold needs to see.
 */
const REFUSAL =
  "Orbit hosts background work for this session. Bash's run_in_background is" +
  ' unavailable here: a shell started that way is a child of this coding-engine process, so' +
  ' recycling the engine (idle TTL, memory pressure) kills your build with it. Use' +
  ' mcp__orbit__bg_run instead — it takes the same command string, and requires kind:' +
  ' "service" for something valuable while it runs (dev server, watcher), "job" for' +
  ' something valuable when it finishes (build, test suite), or "watch" for a wait on' +
  ' something else (CI, a deploy); with wakeOnExit: true you are woken when it ends, even after' +
  ' this engine is recycled. Read its output with' +
  ' mcp__orbit__bg_output, stop it with mcp__orbit__bg_kill. To wait for Orbit tasks or sessions, run' +
  ' nothing: mcp__orbit__task_await and mcp__orbit__session_await wake you when they finish.';

/**
 * A Monitor's start receipt, as runner-go parses it (its `monitorStarted`): the deadline form the
 * live sessions carry, and the fixed-timeout form. Either one is what says the watch started.
 */
const MONITOR_RECEIPT_A =
  'Monitor started (task blr05iybn, expires in 30m unless the source ends first; you get one' +
  ' notice at expiry — re-arm if you still need the watch). You will be notified on each event.' +
  ' Keep working — do not poll or sleep.';
const MONITOR_RECEIPT_B =
  'Monitor started (task b97q4j1iy, timeout 2400000ms). You will be notified on each event.' +
  ' Keep working — do not poll or sleep.';

/** The refused `Bash(run_in_background)`: the call, then the hook's refusal as its result. */
function refusedLaunch(): Reported[] {
  return [
    {
      type: RunEventType.TOOL_USE,
      payload: {
        id: REFUSED,
        name: 'Bash',
        input: { command: 'sleep 60; echo engine up', run_in_background: true, description: 'Wait for engine' },
      },
    },
    {
      type: RunEventType.TOOL_RESULT,
      payload: { toolUseId: REFUSED, content: REFUSAL, isError: true },
    },
  ];
}

/** A shell that really started: the same shape of call, and the receipt that names the process. */
function launchedShell(): Reported[] {
  return [
    {
      type: RunEventType.TOOL_USE,
      payload: {
        id: LAUNCHED,
        name: 'Bash',
        input: { command: 'npm run dev', run_in_background: true, description: 'Run the dev server' },
      },
    },
    {
      type: RunEventType.TOOL_RESULT,
      payload: {
        toolUseId: LAUNCHED,
        content:
          'Command running in background with ID: b7k2m9. Output is being written to:' +
          ' /tmp/claude/tasks/b7k2m9.output',
      },
    },
  ];
}

/** A Monitor, launched and confirmed by its own receipt. */
function monitorLaunch(toolUseId: string, receipt: string): Reported[] {
  return [
    {
      type: RunEventType.TOOL_USE,
      payload: { id: toolUseId, name: 'Monitor', input: { command: 'tail -f build.log', description: 'Watch the build' } },
    },
    { type: RunEventType.TOOL_RESULT, payload: { toolUseId, content: receipt } },
  ];
}

/**
 * The runner-hosted job's own `running` report (runner-go background_job.go): it states its `kind`,
 * which is what marks it as one, and it is the only thing that puts the job in the set — there is
 * no tool_use of its own on this side.
 */
const jobRunning = (): Reported => ({
  type: RunEventType.BACKGROUND_TASK,
  payload: {
    shellId: JOB,
    toolUseId: JOB,
    status: 'running',
    kind: 'job',
    command: 'npm run build',
    outputPath: `/root/.orbit/runs/refused-launch-spec/${JOB}.output`,
  },
});

/** An ordinary call of the session's own work — a batch that says nothing about any of the above. */
const readFile = (): Reported[] => [
  {
    type: RunEventType.TOOL_USE,
    payload: { id: 'toolu_01ReadPoll', name: 'Read', input: { file_path: '/root/orbit/README.md' } },
  },
  { type: RunEventType.TOOL_RESULT, payload: { toolUseId: 'toolu_01ReadPoll', content: '# Orbit\n' } },
];

test('a background launch that was refused is not counted as a running process', {
  skip, concurrency: 1, timeout: 300_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  const ownerId = randomUUID();
  const runner = { id: randomUUID() };
  await prisma.user.create({
    data: { id: ownerId, email: `refused-launch-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: { id: runner.id, name: 'the machine that refused the shell', ownerId, tokenHash: sha256(`refused-${runner.id}`) },
  });
  const door = new RunnerApiController(prisma as never, silent(), silent(), silent(), silent(), silent());

  /** A live session of that runner, with its own process reporting through. */
  async function newSession() {
    const sessionId = randomUUID();
    await prisma.session.create({
      data: {
        id: sessionId,
        ownerId,
        creatorId: ownerId,
        title: 'a session watching a build',
        prompt: 'watch the build and tell me when it breaks',
        provider: 'claude',
        status: RunStatus.AWAITING_INPUT,
        dispatchOrigin: SessionDispatchOrigin.USER,
        startsTaskWork: false,
        assignedRunnerId: runner.id,
        numTurns: 1,
      },
    });
    let seq = 0;
    const leaseOwner = randomUUID();
    const report = (events: Reported[]) =>
      door.events(runner, sessionId, {
        leaseOwner,
        events: events.map((event) => ({ ...event, seq: ++seq, ts: new Date().toISOString() })),
      });
    // The one background process the predecessor handed on — see the note on takeoverLeases —
    // comes back through the `running` report the new process sends when it adopts the job.
    await door.takeoverLeases(runner, sessionId, { leaseOwner, expectedLeaseOwner: null } as never);
    /** The set as stored, sorted: it is a set. */
    const shells = async () => {
      const stored = await prisma.session.findUniqueOrThrow({
        where: { id: sessionId },
        select: { runningBgShells: true },
      });
      return [...stored.runningBgShells].sort();
    };
    /** The set as the bug left it: an id put there by something other than the fold under test. */
    const wedge = async (ids: string[]) => {
      await prisma.session.update({ where: { id: sessionId }, data: { runningBgShells: ids } });
    };
    /** What the fold read to decide: the calls on record whose result is in. */
    const toolCallIds = async () => {
      const rows = await prisma.toolCall.findMany({
        where: { sessionId },
        select: { toolUseId: true, output: true },
      });
      return rows.map((row) => row.toolUseId);
    };
    return { sessionId, report, shells, wedge, toolCallIds };
  }

  await t.test('a refused call and a real launch in one batch: only the real one is counted', async () => {
    const session = await newSession();
    await session.report([...refusedLaunch(), ...launchedShell()]);

    // Both calls are on record with their results, so the difference between the two is only what
    // those results say — which is the whole of what the fold reads.
    assert.deepEqual(
      (await session.toolCallIds()).sort(),
      [REFUSED, LAUNCHED].sort(),
      'the fixture: both calls are on record',
    );
    assert.deepEqual(
      await session.shells(),
      [LAUNCHED],
      'the shell that started is a running process, and the one the hook refused — which has no process and never will — is not',
    );
  });

  await t.test('the verdict survives the flush boundary: a launch whose result lands in the next batch', async () => {
    const session = await newSession();
    // The runner flushes every 250ms, so a tool_use and its result can be split across two batches.
    // Neither the call nor its result says enough on its own; the row they share does.
    const [refusedCall, refusedResult] = refusedLaunch();
    const [launchedCall, launchedReceipt] = launchedShell();
    await session.report([refusedCall, launchedCall]);
    assert.deepEqual(
      await session.shells(),
      [],
      'an outstanding result is not a receipt: nothing is counted before either call says it started',
    );

    await session.report([refusedResult, launchedReceipt]);
    assert.deepEqual(
      await session.shells(),
      [LAUNCHED],
      'the batch carrying the two results counts the launch that started and not the one that was refused',
    );
  });

  await t.test('a set already wedged by the refused id heals at the next fold, and only that id leaves', async () => {
    const session = await newSession();
    const history = [
      ...monitorLaunch(MONITOR_A, MONITOR_RECEIPT_A),
      ...monitorLaunch(MONITOR_B, MONITOR_RECEIPT_B),
      jobRunning(),
      ...refusedLaunch(),
    ];
    await session.wedge([REFUSED, MONITOR_A, MONITOR_B, JOB]);

    await session.report(history);

    assert.deepEqual(
      await session.shells(),
      [MONITOR_A, MONITOR_B, JOB].sort(),
      'the refused id is gone, and the two Monitors with their receipts and the adopted job are still running processes',
    );
  });

  await t.test('the healing needs no new evidence: a batch that mentions none of them drops the refused id', async () => {
    const session = await newSession();
    // The session has been running since: the two Monitors and the job were launched, reported, and
    // nothing has ended them. This is the live shape the bug left behind — the refused id beside
    // three ids that are genuinely up.
    await session.report([
      ...monitorLaunch(MONITOR_A, MONITOR_RECEIPT_A),
      ...monitorLaunch(MONITOR_B, MONITOR_RECEIPT_B),
      ...refusedLaunch(),
      jobRunning(),
    ]);
    await session.wedge([REFUSED, MONITOR_A, MONITOR_B, JOB]);
    assert.deepEqual(
      await session.shells(),
      [REFUSED, MONITOR_A, MONITOR_B, JOB].sort(),
      'the fixture: the wedged set, as the pre-fix fold left it',
    );

    // The next batch of any kind: the session's own work, which speaks about none of the four.
    await session.report(readFile());

    assert.deepEqual(
      await session.shells(),
      [MONITOR_A, MONITOR_B, JOB].sort(),
      'the refused id was dropped from the stored set on a batch that never mentions it, and the ids with a receipt — or a `running` report, for the job — were left where they are',
    );
  });
});
