/**
 * WHO EDITED THE RULER, ALL THE WAY FROM THE RUNNER'S REQUEST TO THE ROW.
 *
 * WHAT WAS BROKEN
 * ===============
 * Two durable facts about a project's acceptance criteria are keyed on the conversation that
 * wrote them: `project_criteria_authorship` records which session authored each criterion
 * VERSION (migration 0251), and a held loosening proposal records which principal asked for it
 * (`project_ratified_action_intent.principal_type` / `principal_id`). Both are read off one input
 * — the `x-orbit-session-id` header on `PATCH /runner/projects/:id` — and until this task the
 * runner never sent it. `updateProject` in `src/runner-go/transport.go` went out through the
 * plain `do` helper while `createProject` next door used `doHeaders(..., sessionHeader(...))`.
 *
 * The failure was silent and it fell one way. `actingSessionId` arrived `undefined`, so
 * `principalType: actingSessionId ? 'AGENT' : 'OWNER'` recorded every agent's proposal as the
 * account owner's own, and `authoredByType: authoredBySessionId === null ? 'USER' : 'AGENT'`
 * recorded every criterion an agent wrote as owner-authored with a NULL session. A
 * separation-of-duties rule — no criterion counts at settlement if the session that wrote it is
 * the session whose evidence is being counted — compares `authored_by_session_id` against an
 * evidence-producing session. Against a column that is NULL on every real write, that comparison
 * can never match, so the rule was not merely unenforced: it was unenforceable.
 *
 * WHY THIS SPEC RUNS OVER REAL HTTP AND A REAL POSTGRESQL
 * ======================================================
 * `criteria-authorship.pg.spec.ts` already pins what the SERVICE does when it is handed an acting
 * session — it calls `ProjectsService.update(..., actingSessionId)` directly. That is the half
 * that was never broken. What was broken is upstream of it, in the wire, and a unit call cannot
 * see any of the three things between the header and the service:
 *
 *   * the header is a PUBLIC id. `publicIdHeaders` decodes base62 to a UUID before any guard runs,
 *     and a session id that reached the service in the spelling a model sees would match no row.
 *   * the route has to bind it. `@Headers('x-orbit-session-id')` on `updateProject` is one
 *     parameter decorator away from being dropped, and dropping it 200s.
 *   * absence has to stay absence. `orbit project update` (the headless owner path) sends no
 *     header, and the two facts must come out `USER` / `OWNER` for it — which is the same shape
 *     the bug produced, and the reason a spec that only asserted `AGENT` would not have caught it.
 *
 * And real PostgreSQL because both rows under test are written by machinery this file does not get
 * to fake: `revision` on a criterion version is decided by the `project_acceptance_definition_
 * normalize` BEFORE trigger and is the second half of the authorship primary key, and
 * `project_ratified_action_intent` is guarded by an immutability trigger and a BEFORE INSERT check
 * that re-derives the project's contract binding. Every row asserted below is read back over a
 * SECOND connection, never through the response that wrote it.
 *
 * WHAT THE CASES ARE, AND WHY THE CONTROL IS NOT OPTIONAL
 * ======================================================
 *   (a) the runner's own source: the PATCH carries the header when a session is known, and the
 *       headless CLI path passes none. Unconditional — it needs no database — so even a run with
 *       no PostgreSQL witnesses the half of the chain that lives in Go.
 *   (1) an attributed criteria edit that tightens → the authorship row names the acting session.
 *   (2) an attributed criteria edit that loosens → the held proposal names the acting session.
 *   (3) THE CONTROL, same fixture, same owner, byte-identical bodies, one variable: no header.
 *       Both writes still land, and they land as `USER` / `OWNER` with a NULL session.
 *
 * (3) is what makes (1) and (2) mean anything. An implementation that recorded `AGENT` for
 * everybody — or that stopped writing authorship altogether and left the table empty — passes a
 * file that only looked at the attributed project. It also states the rule the product depends on
 * in the other direction: the owner-authenticated channel is a real, distinguishable principal,
 * not "an agent we failed to identify".
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/runner-api/runner-project-edit-attribution.pg.spec.ts
 *
 * Not destructive: every id is generated by the case and every assertion is scoped to its own
 * project.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';

import { Module, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { RunStatus, SessionDispatchOrigin, type PrismaClient } from '@prisma/client';
import { uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { publicIdHeaders } from '../common/public-id-headers';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { ProjectHandoffService } from '../projects/project-handoff.service';
import { ProjectsService } from '../projects/projects.service';
import { RunnerAuthGuard } from './runner-auth.guard';
import { RunnerOrchestrationAuthorizer } from './runner-orchestration-authorizer';
import { RunnerProjectsController } from './runner-projects.controller';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app, and a project response needs it: Prisma maps
// `project.config_revision` to a native BigInt, which `JSON.stringify` throws on. Without it every
// PATCH below answers 500 — a real server-shaped failure, but not the one under test.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

const ROOT = path.resolve(__dirname, '../../../..');

/** How the criteria say they are to be judged. Restated byte for byte by every edit below. */
const METHOD = 'A person reads the criterion and says whether it holds';

const KEPT = 'the criterion both projects keep, so a deletion is the only difference';
const DROPPED = 'the criterion each project deletes, which is what makes the second edit a loosening';

/** The runner credential this spec enrolls, in the clear. Its hash is what the guard matches. */
const RUNNER_TOKEN = 'the-runner-token-for-attribution';

/** One authorship row, read from the table rather than from the service that wrote it. */
interface AuthorshipRow {
  definition_id: string;
  revision: number;
  authored_by_session_id: string | null;
  authored_by_type: string;
}

/** One held proposal, in the two columns that say who asked for it. */
interface IntentRow {
  id: string;
  principal_type: string;
  principal_id: string;
}

/** A response, kept as text as well as JSON: a body that failed to parse has to be readable. */
interface Sent {
  status: number;
  body: string;
  json: Record<string, unknown>;
}

// ═══ (a) the runner's half of the chain, which needs no database ═════════════════════════════════

test('the runner sends the acting session on a project edit, and only from a session', () => {
  const read = (relative: string): string => readFileSync(path.join(ROOT, relative), 'utf8');
  const transport = read('src/runner-go/transport.go');

  const updateProject = transport.slice(transport.indexOf('func (t *Transport) updateProject('));
  assert.ok(updateProject.startsWith('func (t *Transport) updateProject('),
    'transport.go no longer declares updateProject');
  const body = updateProject.slice(0, updateProject.indexOf('\n}\n') + 3);

  assert.match(body, /"PATCH", "\/runner\/projects\/"\+url\.PathEscape\(id\)/u,
    'updateProject is no longer the PATCH under test');
  // The header, and the helper that decides it: `sessionHeader` returns nil for the empty string,
  // so "known session" and "no session at all" are one expression rather than a branch that can
  // fall the wrong way. Asserting the CALL rather than the literal name is what keeps this honest
  // — a file that merely mentioned the header in a comment would satisfy a grep.
  assert.match(body, /doHeaders\([\s\S]*sessionHeader\(sessionID\)\)/u,
    'the PATCH does not carry sessionHeader(sessionID) — the acting session never leaves the runner');
  assert.match(read('src/runner-go/mcp.go'), /updateProject\(s\.sessionID, id, body\)/u,
    'the project_update tool does not pass its calling session');
  // The headless door passes the empty string on purpose, which `sessionHeader` turns into no
  // header at all rather than an empty one the server would try to resolve as a session.
  assert.match(read('src/runner-go/project_cli.go'), /updateProject\("", id, body\)/u,
    '`orbit project update` must stay the headless owner path');
});

// ═══ the wire, the door and the rows ═════════════════════════════════════════════════════════════

test('a criteria edit through the runner door is attributed to the session that made it', {
  skip, concurrency: 1, timeout: 300_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  t.after(async () => {
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  const acceptance = new ProjectAcceptanceService(prisma as unknown as PrismaService);
  const projects = new ProjectsService(prisma as unknown as PrismaService, acceptance);

  const ownerId = randomUUID();
  await prisma.user.create({
    data: {
      id: ownerId,
      email: `edit-attribution-${ownerId}@runner-door.invalid`,
      name: 'The account owner',
      passwordHash: 'x',
    },
  });
  // A real runner row, because `RunnerAuthGuard` looks the credential up by hash and puts the row
  // it finds on the request: the owner every write below is scoped to is the runner's owner, the
  // same way it is in production.
  await prisma.runner.create({
    data: {
      id: randomUUID(),
      name: 'the machine the agent runs on',
      ownerId,
      tokenHash: sha256(RUNNER_TOKEN),
    },
  });

  /**
   * The acting session, as `sessions.create` would have written it.
   *
   * `USER` rather than the judgment origin: `refuseHumanOnlyAction` refuses only the one-shot
   * judgment role from editing criteria at all, so the session that CAN make this edit — an
   * ordinary task run, a conversation somebody opened — is precisely the one whose identity had
   * nowhere to land.
   */
  const actingSessionId = randomUUID();
  await prisma.session.create({
    data: {
      id: actingSessionId,
      ownerId,
      creatorId: ownerId,
      title: 'the conversation that edits the ruler',
      prompt: 'state what would settle this project',
      provider: 'claude',
      status: RunStatus.RUNNING,
      dispatchOrigin: SessionDispatchOrigin.USER,
      startsTaskWork: false,
    },
  });

  // ── the app: the real runner controller, the real service, the real header middleware ────────
  // The two collaborators these routes never reach are stubbed to THROW rather than to answer
  // quietly — a probe that a shadowed route reached would otherwise pass as a green.
  const refuse = (name: string) => () => {
    throw new Error(`${name} must not be reached by this probe`);
  };
  @Module({
    controllers: [RunnerProjectsController],
    providers: [
      { provide: ProjectsService, useValue: projects },
      { provide: ProjectAcceptanceService, useValue: acceptance },
      { provide: ProjectHandoffService, useValue: { listForProject: refuse('handoffs') } },
      { provide: RunnerOrchestrationAuthorizer, useValue: { assert: refuse('orchestration') } },
      RunnerAuthGuard,
      { provide: PrismaService, useValue: prisma },
    ],
  })
  class RunnerDoorModule {}

  const app = await NestFactory.create(RunnerDoorModule, { logger: false, abortOnError: false });
  // Before the guards and in main.ts's order: the session header arrives spelled base62, and a
  // decode that happened later would leave a second spelling reachable from a guard.
  app.use(publicIdHeaders);
  app.setGlobalPrefix('api');
  app.useGlobalPipes(
    new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }),
  );
  app.useGlobalInterceptors(new PublicIdInterceptor());
  await app.listen(0, '127.0.0.1');
  const base = await app.getUrl();
  t.after(() => app.close());

  /**
   * One PATCH through the runner door, with the acting session named or not named.
   *
   * `sessionId` is spelled the way the runner spells it — base62 — so the decode in
   * `publicIdHeaders` is part of what every case below exercises. Omitted entirely rather than
   * sent empty when there is none, which is what `sessionHeader` does in Go.
   */
  async function patch(
    projectId: string,
    items: Array<{ id?: string; text: string }>,
    sessionId?: string,
  ): Promise<Sent> {
    const response = await fetch(`${base}/api/runner/projects/${uuidToBase62(projectId)}`, {
      method: 'PATCH',
      headers: {
        authorization: `Bearer ${RUNNER_TOKEN}`,
        'content-type': 'application/json',
        ...(sessionId ? { 'x-orbit-session-id': uuidToBase62(sessionId) } : {}),
      },
      body: JSON.stringify({
        acceptanceCriteriaItems: items.map((item) => ({
          ...(item.id ? { id: uuidToBase62(item.id) } : {}),
          text: item.text,
          verificationMethod: METHOD,
        })),
      }),
    });
    const text = await response.text();
    let json: Record<string, unknown> = {};
    try { json = JSON.parse(text) as Record<string, unknown>; } catch { /* asserted on below */ }
    return { status: response.status, body: text, json };
  }

  /** The definitions as the database holds them, ordinal order. */
  async function definitions(projectId: string): Promise<Array<{ id: string; text: string }>> {
    const { rows } = await sql.query<{ id: string; text: string }>(
      `SELECT "id", "text" FROM "project_acceptance_criterion_definition"
        WHERE "project_id" = $1::uuid ORDER BY "ordinal"`,
      [projectId],
    );
    return rows;
  }

  async function authorship(projectId: string): Promise<AuthorshipRow[]> {
    const { rows } = await sql.query<AuthorshipRow>(
      `SELECT "definition_id", "revision", "authored_by_session_id", "authored_by_type"
         FROM "project_criteria_authorship" WHERE "project_id" = $1::uuid
        ORDER BY "definition_id", "revision"`,
      [projectId],
    );
    return rows;
  }

  async function intents(projectId: string): Promise<IntentRow[]> {
    const { rows } = await sql.query<IntentRow>(
      `SELECT "id", "principal_type", "principal_id"
         FROM "project_ratified_action_intent" WHERE "project_id" = $1::uuid
        ORDER BY "created_at", "id"`,
      [projectId],
    );
    return rows;
  }

  /**
   * The whole story of one project, told twice: state two criteria, then delete one of them.
   *
   * Stating them from nothing is the ruler walking toward strictness, so it lands where it is made
   * and leaves authorship rows. Deleting one is a loosening, which the door does not apply at all
   * — it becomes one held proposal — so the two facts under test are produced by two genuinely
   * different code paths off the same header.
   *
   * Byte-identical between the attributed project and the control except for `sessionId`, which is
   * the entire point: anything that differs in the rows below differs because of the header.
   */
  async function stateThenLoosen(projectId: string, title: string, sessionId?: string) {
    await prisma.project.create({ data: { id: projectId, ownerId, title } });

    const stated = await patch(projectId, [{ text: KEPT }, { text: DROPPED }], sessionId);
    assert.equal(stated.status, 200, `stating the criteria was refused: ${stated.body}`);
    const written = await definitions(projectId);
    assert.deepEqual(written.map((row) => row.text), [KEPT, DROPPED],
      'the tightening edit has to have landed, or there is no authorship to attribute');

    const keep = written.find((row) => row.text === KEPT)!;
    const loosened = await patch(projectId, [{ id: keep.id, text: KEPT }], sessionId);
    assert.equal(loosened.status, 200, `the loosening edit was refused outright: ${loosened.body}`);
    assert.deepEqual((await definitions(projectId)).map((row) => row.text), [KEPT, DROPPED],
      'a loosening edit must not take effect where it is made, or it filed no proposal');
    assert.ok(loosened.json.acceptanceCriteriaHold,
      'the loosening edit was applied instead of held — there is no proposal to attribute');
  }

  const attributedId = randomUUID();
  const headlessId = randomUUID();
  await stateThenLoosen(attributedId, 'The project whose ruler an agent edits', actingSessionId);
  await stateThenLoosen(headlessId, 'The project whose ruler the owner edits');

  // ═══ (1) an attributed tightening edit names the session in every version it wrote ══════════════

  await t.test('(1) authorship of a criterion version names the session that sent the edit', async () => {
    const rows = await authorship(attributedId);
    assert.equal(rows.length, 2, 'both criterion versions the edit wrote are attributed');
    for (const row of rows) {
      assert.equal(row.authored_by_type, 'AGENT',
        'a session-attributed edit is an AGENT authoring event, not the owner’s');
      assert.equal(row.authored_by_session_id, actingSessionId,
        'the acting session reached the row — base62 header, decoded, bound and stored');
    }
  });

  // ═══ (2) an attributed loosening edit names the session as the principal that asked ════════════

  await t.test('(2) a held proposal names the session as its principal', async () => {
    const rows = await intents(attributedId);
    assert.equal(rows.length, 1, 'the loosening edit filed exactly one proposal');
    assert.equal(rows[0].principal_type, 'AGENT',
      'the proposal is the agent’s ask; recorded as OWNER it reads as the account owner’s own');
    assert.equal(rows[0].principal_id, actingSessionId,
      'and it names WHICH conversation asked, which is the whole of what makes it answerable');
  });

  // ═══ (3) the control: the same two writes with no header stay the owner-authenticated channel ══

  await t.test('(3) the same edits with no acting session are still the owner’s own', async () => {
    const rows = await authorship(headlessId);
    assert.equal(rows.length, 2, 'the headless edit wrote its versions too — it was not refused');
    for (const row of rows) {
      assert.equal(row.authored_by_type, 'USER',
        'no header is the owner-authenticated channel, which is a principal and not an unknown');
      assert.equal(row.authored_by_session_id, null,
        'and there is no session to name, which is what tells USER apart from AGENT');
    }

    const held = await intents(headlessId);
    assert.equal(held.length, 1, 'the headless loosening filed exactly one proposal as well');
    assert.equal(held[0].principal_type, 'OWNER');
    assert.equal(held[0].principal_id, ownerId,
      'a request with no acting session reached the API as the account owner’s own');
  });

  // ═══ (4) and the two are actually told apart, in one run, over the same fixture ════════════════

  await t.test('(4) the header is the only thing that differs, and it decides both facts', async () => {
    const [attributed, headless] = await Promise.all([
      authorship(attributedId), authorship(headlessId),
    ]);
    assert.deepEqual(
      [...new Set(attributed.map((row) => row.authored_by_type))], ['AGENT'],
    );
    assert.deepEqual(
      [...new Set(headless.map((row) => row.authored_by_type))], ['USER'],
      'both projects coming out the same way is the bug this file exists for, in either direction');

    const [agentIntent] = await intents(attributedId);
    const [ownerIntent] = await intents(headlessId);
    assert.notEqual(agentIntent.principal_type, ownerIntent.principal_type,
      'one classifier answering both requests the same way cannot enforce anything');
    assert.notEqual(agentIntent.principal_id, ownerIntent.principal_id,
      'and the principals are different rows, not one id wearing two labels');
  });
});
