/**
 * A wakeup a session asks for is held by the control plane and delivered to the session as a turn when
 * it is due, with no runner process involved: `POST /api/runner/sessions/:id/scheduled-wakeup`, then the
 * production apiserver — `build/main.js`, the whole AppModule, run as a child process — does the rest.
 *
 * The timer cannot be the engine's: Claude Code's ScheduleWakeup keeps it inside the engine process, and
 * Orbit recycles engines and restarts runners (task 34NGdppVIQ5iLJBaHZ406 found wakeups lost that way).
 * Against real PostgreSQL and a real apiserver process:
 *
 *   1. The runner door takes a wakeup for its own session only, clamps its delay the way ScheduleWakeup
 *      does, and holds it until it is due.
 *   2. A due wakeup is one turn of its session, filed when it is due and carrying nobody's words: the
 *      inbox hands it out with its reason and prompt written in, and the runner's echo of it is stored
 *      as the control plane's note.
 *   3. A later request replaces a waiting wakeup, and stop cancels one: neither ever becomes a turn, and
 *      a wakeup not yet due is not delivered.
 *   4. A session that ended before its wakeup came due is not woken.
 *   5. A wakeup that comes due while a background job's wake turn is still queued joins that turn.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/runner-api/scheduled-wakeup.pg.spec.ts
 *
 * The wakeup table is read with SQL rather than through the Prisma client, so this file also compiles on
 * a tree without the feature, where the first request is answered 404. Not destructive: every id is
 * generated by the run.
 */
import assert from 'node:assert/strict';
import { spawn, type ChildProcess } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import http from 'node:http';
import net from 'node:net';
import path from 'node:path';
import { test } from 'node:test';
import { setTimeout as sleep } from 'node:timers/promises';

import { type Prisma, RunStatus, SessionDispatchOrigin } from '@prisma/client';
import { uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { prismaClientFor } from '../prisma/prisma-client';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';

const PG_URL = process.env.COORDINATOR_PG_URL;
const skip = !PG_URL;
/** build/runner-api → build/main.js, the apiserver's production entry point. */
const MAIN = path.resolve(__dirname, '..', 'main.js');
const API_DIR = path.resolve(__dirname, '..', '..');
const RUNNER_TOKEN = `scheduled-wakeup-runner-${randomUUID()}`;

interface Reply {
  status: number;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  json: any;
  text: string;
}

interface Apiserver {
  port: number;
  child: ChildProcess;
  output(): string;
  stop(): Promise<void>;
}

async function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const probe = net.createServer();
    probe.once('error', reject);
    probe.listen(0, '127.0.0.1', () => {
      const { port } = probe.address() as net.AddressInfo;
      probe.close(() => resolve(port));
    });
  });
}

function request(server: Apiserver, method: string, route: string, body?: unknown): Promise<Reply> {
  return new Promise((resolve, reject) => {
    const payload = body === undefined ? undefined : JSON.stringify(body);
    const req = http.request(
      {
        host: '127.0.0.1',
        port: server.port,
        path: route,
        method,
        agent: false,
        headers: {
          authorization: `Bearer ${RUNNER_TOKEN}`,
          ...(payload ? { 'content-type': 'application/json', 'content-length': Buffer.byteLength(payload) } : {}),
        },
      },
      (res) => {
        const parts: Buffer[] = [];
        res.on('data', (chunk: Buffer) => parts.push(chunk));
        res.on('end', () => {
          const text = Buffer.concat(parts).toString('utf8');
          let json: unknown = null;
          try {
            json = JSON.parse(text);
          } catch {
            json = null;
          }
          resolve({ status: res.statusCode ?? 0, json, text });
        });
      },
    );
    req.on('error', reject);
    req.setTimeout(30_000, () => req.destroy(new Error(`${method} ${route} timed out`)));
    if (payload) req.write(payload);
    req.end();
  });
}

/** `node build/main.js`, as the container starts it, on a port of its own; resolves once it answers. */
async function startApiserver(): Promise<Apiserver> {
  const port = await freePort();
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    DATABASE_URL: PG_URL,
    JWT_SECRET: `scheduled-wakeup-${randomUUID()}`,
    PORT: String(port),
    NO_COLOR: '1',
    CORS_ORIGINS: 'http://127.0.0.1',
  };
  delete env.NODE_TEST_CONTEXT;
  let log = '';
  const child = spawn(process.execPath, [MAIN], { cwd: API_DIR, env, stdio: ['ignore', 'pipe', 'pipe'] });
  const collect = (chunk: Buffer) => {
    log = (log + chunk.toString('utf8')).slice(-400_000);
  };
  child.stdout!.on('data', collect);
  child.stderr!.on('data', collect);
  const server: Apiserver = {
    port,
    child,
    output: () => log,
    async stop() {
      if (child.exitCode !== null || child.signalCode !== null) return;
      const exited = new Promise<void>((resolve) => child.once('exit', () => resolve()));
      child.kill('SIGTERM');
      await Promise.race([exited, sleep(20_000)]);
      if (child.exitCode === null && child.signalCode === null) {
        child.kill('SIGKILL');
        await exited;
      }
    },
  };
  const deadline = Date.now() + 150_000;
  for (;;) {
    if (child.exitCode !== null) assert.fail(`the apiserver exited ${child.exitCode} before answering:\n${log.slice(-6_000)}`);
    const reply = await request(server, 'GET', '/api/auth/setup-status').catch(() => null);
    if (reply?.status === 200) return server;
    if (Date.now() > deadline) assert.fail(`the apiserver did not answer within 150s:\n${log.slice(-6_000)}`);
    await sleep(250);
  }
}

async function eventually<T>(what: string, check: () => Promise<T | null>, timeoutMs: number): Promise<T> {
  const deadline = Date.now() + Math.max(timeoutMs, 5_000);
  for (;;) {
    const value = await check();
    if (value !== null) return value;
    if (Date.now() > deadline) assert.fail(`timed out waiting for ${what}`);
    await sleep(1_000);
  }
}

test('a scheduled wakeup is held by the control plane and delivered as a turn when it is due', {
  skip, concurrency: 1, timeout: 540_000,
}, async (t) => {
  const url = PG_URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const heartbeats = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await heartbeats.connect();
  const prisma = prismaClientFor(url);
  let server: Apiserver | undefined;
  let heartbeat: ReturnType<typeof setInterval> | undefined;
  t.after(async () => {
    if (heartbeat) clearInterval(heartbeat);
    await server?.stop();
    await prisma.$disconnect().catch(() => undefined);
    await heartbeats.end().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const otherRunnerId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `scheduled-wakeup-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: { id: runnerId, name: 'the machine the sessions run on', ownerId, tokenHash: sha256(RUNNER_TOKEN) },
  });
  await prisma.runner.create({
    data: { id: otherRunnerId, name: 'another machine of the same owner', ownerId, tokenHash: sha256(`${RUNNER_TOKEN}-other`) },
  });
  // The apiserver's reaper ends a RUNNING session whose runner stopped heartbeating. These runners stay
  // online for as long as the file runs, the way a real one would — and none of them ever polls.
  const beat = () =>
    heartbeats
      .query(`UPDATE "runner" SET "last_heartbeat_at" = clock_timestamp() WHERE "id" = ANY($1::uuid[])`, [[runnerId, otherRunnerId]])
      .catch(() => undefined);
  await beat();
  heartbeat = setInterval(() => void beat(), 3_000);

  /** A session on this runner, parked between turns: the state a long wait leaves it in. */
  async function session(data: Partial<Prisma.SessionUncheckedCreateInput> = {}): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id,
        ownerId,
        creatorId: ownerId,
        title: 'a session waiting on CI',
        prompt: 'watch CI and fix what fails',
        provider: 'claude',
        status: RunStatus.AWAITING_INPUT,
        dispatchOrigin: SessionDispatchOrigin.USER,
        startsTaskWork: false,
        assignedRunnerId: runnerId,
        numTurns: 1,
        ...data,
      },
    });
    return id;
  }

  server = await startApiserver();
  const api = server;

  const schedule = (sessionId: string, body: Record<string, unknown>) =>
    request(api, 'POST', `/api/runner/sessions/${uuidToBase62(sessionId)}/scheduled-wakeup`, body);

  interface HeldWakeup {
    state: string;
    reason: string;
    clientTurnId: string | null;
    dueAt: Date;
    createdAt: Date;
  }
  const wakeupsOf = async (sessionId: string): Promise<HeldWakeup[]> =>
    (
      await sql.query(
        `SELECT "state", "reason", "client_turn_id" AS "clientTurnId", "due_at" AS "dueAt", "created_at" AS "createdAt"
         FROM "session_scheduled_wakeup" WHERE "session_id" = $1::uuid ORDER BY "created_at", "id"`,
        [sessionId],
      )
    ).rows;

  const turnsOf = (sessionId: string) =>
    prisma.conversationTurn.findMany({ where: { sessionId }, orderBy: { seq: 'asc' } });

  /** What the runner's claim does to a queued session, then the inbox poll that follows it. */
  async function claimAndPoll(sessionId: string): Promise<Reply> {
    await prisma.session.update({ where: { id: sessionId }, data: { status: RunStatus.RUNNING } });
    return request(api, 'GET', `/api/runner/sessions/${uuidToBase62(sessionId)}/inbox`);
  }

  const on = {
    due: await session(),
    replaced: await session(),
    cancelled: await session(),
    ended: await session(),
    notYetDue: await session(),
    joined: await session(),
  };

  await t.test('the runner door holds a wakeup for its own session, and only for its own', async () => {
    const answer = await schedule(on.due, {
      delaySeconds: 60,
      reason: 'waiting for CI run 4242',
      prompt: 'read the CI result and fix what failed',
    });
    assert.equal(answer.status, 200, `scheduled-wakeup answered ${answer.status}: ${answer.text}`);
    assert.equal(answer.json.outcome, 'SCHEDULED', answer.text);
    assert.equal(answer.json.delaySeconds, 60, answer.text);
    assert.equal(answer.json.clamped, false, answer.text);
    assert.equal(answer.json.replaced, false, answer.text);
    const [held] = await wakeupsOf(on.due);
    assert.equal(held?.state, 'PENDING', 'the wakeup is not held');
    assert.equal(new Date(String(answer.json.dueAt)).getTime(), held.dueAt.getTime(), 'the receipt names another due time than the one held');
    const ahead = (held.dueAt.getTime() - held.createdAt.getTime()) / 1_000;
    assert.ok(Math.abs(ahead - 60) < 2, `the wakeup is due ${ahead}s after it was asked for, not 60s`);
    assert.equal((await turnsOf(on.due)).length, 0, 'a wakeup was delivered before it was due');

    // Clamped to ScheduleWakeup's own bounds, and said so: this one stays far off while the file runs.
    const far = await schedule(on.notYetDue, { delaySeconds: 86_400, reason: 'not due while this file runs' });
    assert.equal(far.status, 200, far.text);
    assert.deepEqual([far.json.delaySeconds, far.json.clamped], [3_600, true], far.text);

    // A wakeup needs its delay and its reason.
    for (const incomplete of [{ reason: 'no delay' }, { delaySeconds: 60 }]) {
      const refused = await schedule(on.notYetDue, incomplete);
      assert.equal(refused.status, 400, `${JSON.stringify(incomplete)} answered ${refused.status}: ${refused.text}`);
    }
    assert.equal((await wakeupsOf(on.notYetDue)).length, 1, 'a refused request changed what is held');

    // Another runner's session is not this runner's to wake.
    const elsewhere = await session({ assignedRunnerId: otherRunnerId });
    const refused = await schedule(elsewhere, { delaySeconds: 60, reason: 'not mine to schedule' });
    assert.equal(refused.status, 403, `a wakeup for another runner's session answered ${refused.status}: ${refused.text}`);
    assert.equal((await wakeupsOf(elsewhere)).length, 0);
  });

  await t.test('a later request replaces a waiting wakeup, and stop cancels one', async () => {
    assert.equal((await schedule(on.replaced, { delaySeconds: 60, reason: 'the first plan' })).status, 200);
    const second = await schedule(on.replaced, { delaySeconds: 75, reason: 'the second plan' });
    assert.equal(second.status, 200, second.text);
    assert.equal(second.json.replaced, true, second.text);
    assert.deepEqual(
      (await wakeupsOf(on.replaced)).map((held) => [held.reason, held.state]),
      [['the first plan', 'SUPERSEDED'], ['the second plan', 'PENDING']],
    );

    assert.equal((await schedule(on.cancelled, { delaySeconds: 60, reason: 'about to be cancelled' })).status, 200);
    const stopped = await schedule(on.cancelled, { stop: true });
    assert.equal(stopped.status, 200, stopped.text);
    assert.deepEqual([stopped.json.outcome, stopped.json.cancelled], ['CANCELLED', 1], stopped.text);
    const again = await schedule(on.cancelled, { stop: true });
    assert.deepEqual([again.json.outcome, again.json.cancelled], ['CANCELLED', 0], `a second stop cancelled something: ${again.text}`);
    assert.deepEqual((await wakeupsOf(on.cancelled)).map((held) => held.state), ['CANCELLED']);

    // The session ends while its wakeup waits.
    assert.equal((await schedule(on.ended, { delaySeconds: 60, reason: 'the session ends first' })).status, 200);
    await prisma.session.update({ where: { id: on.ended }, data: { status: RunStatus.CANCELLED, endReason: 'ended' } });

    // A background job's wake turn nobody has been handed yet; a wakeup comes due while it waits.
    const job = 'bgj_0123456789ab';
    const wake = await request(api, 'POST', `/api/runner/sessions/${uuidToBase62(on.joined)}/background-wake`, {
      wakeId: `${job}:exit`,
      jobId: job,
      trigger: 'exit',
      kind: 'watch',
      command: 'gh run watch 4242 --exit-status',
      status: 'failed',
      exitCode: 1,
      outputPath: `/root/.orbit/runs/wakeup-spec/${job}.output`,
      outputOffset: 0,
      outputSize: 64,
      outputExcerpt: 'X lint (ubuntu-latest) failed in 41s',
    });
    assert.equal(wake.status, 200, `background-wake answered ${wake.status}: ${wake.text}`);
    assert.equal(wake.json.outcome, 'ENQUEUED', wake.text);
    assert.equal((await schedule(on.joined, { delaySeconds: 60, reason: 'look at the job again' })).status, 200);
  });

  await t.test('a due wakeup is one turn, filed when it is due; a replaced, cancelled or far-off one is not', { timeout: 300_000 }, async () => {
    const [held] = await wakeupsOf(on.due);
    const turns = await eventually(
      `the wakeup due at ${held.dueAt.toISOString()} to be filed`,
      async () => {
        const found = await turnsOf(on.due);
        return found.length > 0 ? found : null;
      },
      held.dueAt.getTime() - Date.now() + 60_000,
    );
    assert.equal(turns.length, 1, 'one wakeup became more than one turn');
    const [turn] = turns;
    assert.equal(turn.kind, 'message');
    assert.equal(turn.status, 'PENDING');
    assert.ok(!turn.content, `the turn records words as the person's: ${JSON.stringify(turn.content)}`);
    assert.ok(
      turn.createdAt.getTime() >= held.dueAt.getTime(),
      `filed at ${turn.createdAt.toISOString()}, before it was due at ${held.dueAt.toISOString()}`,
    );
    assert.ok(
      turn.createdAt.getTime() <= held.dueAt.getTime() + 20_000,
      `filed at ${turn.createdAt.toISOString()}, long after it was due at ${held.dueAt.toISOString()}`,
    );
    const [settled] = await wakeupsOf(on.due);
    assert.equal(settled.state, 'DELIVERED');
    assert.equal(settled.clientTurnId, turn.clientTurnId, 'the wakeup does not name the turn that delivers it');
    const queued = await prisma.session.findUniqueOrThrow({ where: { id: on.due } });
    assert.equal(queued.status, RunStatus.PENDING, 'the wakeup did not ask for a runner slot');
    assert.equal(queued.lastUserText, null, "the session list would preview the wakeup as the person's message");

    // The first plan of `replaced` came due at the same moment, and nothing was filed for it.
    assert.equal((await turnsOf(on.replaced)).length, 0, 'the replaced wakeup was delivered');
    const [, plan] = await wakeupsOf(on.replaced);
    await eventually(
      'the replacing wakeup to be filed',
      async () => ((await turnsOf(on.replaced)).length > 0 ? true : null),
      plan.dueAt.getTime() - Date.now() + 60_000,
    );
    // Two more polls, for a second turn to have had its chance.
    await sleep(12_000);
    assert.equal((await turnsOf(on.replaced)).length, 1, 'the replaced wakeup was delivered beside the one that replaced it');
    assert.deepEqual((await wakeupsOf(on.replaced)).map((row) => row.state), ['SUPERSEDED', 'DELIVERED']);

    assert.equal((await turnsOf(on.cancelled)).length, 0, 'the cancelled wakeup was delivered');
    assert.deepEqual((await wakeupsOf(on.cancelled)).map((row) => row.state), ['CANCELLED']);
    assert.equal((await turnsOf(on.notYetDue)).length, 0, 'a wakeup an hour away was delivered');
    assert.deepEqual((await wakeupsOf(on.notYetDue)).map((row) => row.state), ['PENDING']);
  });

  await t.test('a session that ended before its wakeup came due is not woken', async () => {
    const [held] = await wakeupsOf(on.ended);
    await eventually(
      'the ended session\'s wakeup to be settled',
      async () => ((await wakeupsOf(on.ended))[0].state !== 'PENDING' ? true : null),
      held.dueAt.getTime() - Date.now() + 60_000,
    );
    assert.deepEqual((await wakeupsOf(on.ended)).map((row) => row.state), ['DROPPED']);
    assert.equal((await turnsOf(on.ended)).length, 0, 'a wakeup was queued on a session that has ended');
    const after = await prisma.session.findUniqueOrThrow({ where: { id: on.ended } });
    assert.equal(after.status, RunStatus.CANCELLED, 'the wakeup revived the session');
  });

  await t.test("a wakeup due while a job's wake turn is queued joins that turn", async () => {
    const [held] = await wakeupsOf(on.joined);
    await eventually(
      'the wakeup to be filed',
      async () => ((await wakeupsOf(on.joined))[0].state !== 'PENDING' ? true : null),
      held.dueAt.getTime() - Date.now() + 60_000,
    );
    const turns = await turnsOf(on.joined);
    assert.equal(turns.length, 1, 'the wakeup became a second turn beside the queued wake turn');
    const [settled] = await wakeupsOf(on.joined);
    assert.equal(settled.state, 'DELIVERED');
    assert.equal(settled.clientTurnId, turns[0].clientTurnId);
    const delivered = await claimAndPoll(on.joined);
    assert.equal(delivered.status, 200, `inbox answered ${delivered.status}: ${delivered.text}`);
    const content = String(delivered.json.content ?? '');
    for (const fact of ['<background-job-wake>', 'X lint (ubuntu-latest) failed in 41s', '<scheduled-wakeup>', 'look at the job again']) {
      assert.ok(content.includes(fact), `the joined turn does not say ${fact}:\n${content}`);
    }
  });

  await t.test("the inbox hands out the wakeup's reason and prompt, stored as the control plane's note", async () => {
    const delivered = await claimAndPoll(on.due);
    assert.equal(delivered.status, 200, `inbox answered ${delivered.status}: ${delivered.text}`);
    const [turn] = await turnsOf(on.due);
    assert.ok(
      [turn.id, uuidToBase62(turn.id)].includes(String(delivered.json.turnId)),
      `the inbox handed out something else: ${delivered.text}`,
    );
    const content = String(delivered.json.content ?? '');
    for (const fact of ['<scheduled-wakeup>', 'waiting for CI run 4242', 'read the CI result and fix what failed', 'mcp__orbit__schedule_wakeup']) {
      assert.ok(content.includes(fact), `the delivered turn does not say ${fact}:\n${content}`);
    }
    const echoed = await request(api, 'POST', `/api/runner/sessions/${uuidToBase62(on.due)}/events`, {
      events: [{ seq: 1, type: 'user', ts: new Date().toISOString(), turnId: delivered.json.turnId, payload: { text: content } }],
    });
    assert.equal(echoed.status, 202, `events answered ${echoed.status}: ${echoed.text}`);
    const stored = await prisma.runEvent.findFirstOrThrow({ where: { sessionId: on.due, type: 'user' } });
    const payload = stored.payload as { text?: string; controlPlaneNote?: string };
    assert.equal(payload.text, content);
    assert.equal(payload.controlPlaneNote, content, 'the wakeup was stored as words the person wrote');

    // And the worker never failed a pass on the way.
    const errors = api.output().split('\n').filter((line) => /ERROR\s+\[ScheduledWakeup\]/.test(line));
    assert.deepEqual(errors, []);
  });
});
