/**
 * D3 over real HTTP and a real PostgreSQL: in a project nobody has started, the tasks its
 * coordinator files are not put in front of the owner one card at a time — the start card reviews
 * them — nor in a project whose Automatic is on, where its coordinator decides them; every other
 * create is asked exactly as before.
 *
 * Driven through the doors a runner reaches, in the order `askBeforeCreate` / `askBeforeBatch`
 * reach them: the batch preview, the card (`POST /api/runner/sessions/:id/approvals`) and the poll
 * that reads its answer, then the write (`POST /api/runner/tasks`, `POST
 * /api/runner/tasks/batch-create`). Nothing on the runner changed, so these are the requests every
 * installed runner already sends — the ones below carry no write-protocol headers, as an older
 * runner's do.
 *
 *   1. All of it in the unstarted project, from its coordinator: the card is written already
 *      allowed, traced as the platform's rule rather than a person's answer, and raises nothing —
 *      no card on the conversation, no push, no pending row for the session list or Needs you to
 *      count — and the tasks are written.
 *   2. One item in a project that has started: asked.
 *   3. The same create from a conversation that does not coordinate the project: asked.
 *   4. The project already started, with Automatic off: asked.
 *   5. The batch preview in the unstarted project promises no run, where the same batch in a
 *      started project does: nothing starts before the start.
 *   6. An item that names no project is asked even from the coordinator: which project an unnamed
 *      create lands in is the write's own derivation, and the card door does not guess it.
 *   7. All of it in a started project whose Automatic is on, from its coordinator: as in 1, under
 *      the Automatic rule's own message, and the tasks are written.
 *   8. The Automatic project, but from a conversation that does not coordinate it, or with one
 *      item in another project: asked.
 *
 *   bash scripts/run-pg-spec.sh src/apiserver/src/runner-api/unstarted-project-create-no-card.pg.spec.ts
 *
 * Not destructive: every id is generated by the run.
 */
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';

import { type INestApplication, Module, ValidationPipe } from '@nestjs/common';
import { HttpAdapterHost, NestFactory } from '@nestjs/core';
import { RunStatus, SessionDispatchOrigin, type PrismaClient } from '@prisma/client';
import { RunEventType, toUuid, uuidToBase62 } from '@orbit/shared';
import { Client } from 'pg';

import { sha256 } from '../common/crypto.util';
import { publicIdHeaders } from '../common/public-id-headers';
import { PublicIdExceptionFilter } from '../common/public-id.filter';
import { PublicIdInterceptor } from '../common/public-id.interceptor';
import { TransientDbConflictFilter } from '../common/transient-db-conflict.filter';
import { prismaClientFor } from '../prisma/prisma-client';
import { PrismaService } from '../prisma/prisma.service';
import { AttemptBudgetMeterService } from '../projects/attempt-budget-meter.service';
import {
  assertCoordinatorPgUrlIsIsolated,
  verifyCoordinatorPgIdentity,
} from '../projects/coordinator-pg-test-safety';
import { ProjectAcceptanceService } from '../projects/project-acceptance.service';
import { ProjectAttributionService } from '../projects/project-attribution.service';
import { PushService } from '../push/push.service';
import { QueueService } from '../queue/queue.service';
import { RealtimeService } from '../realtime/realtime.service';
import { MergeReceiptService } from '../sessions/merge-receipt.service';
import { SessionsService } from '../sessions/sessions.service';
import { ListEventsService } from '../task-lists/list-events.service';
import { TaskListsService } from '../task-lists/task-lists.service';
import { ReferenceExpansionService } from '../tasks/reference-expansion';
import { TasksService } from '../tasks/tasks.service';
import { RunnerApiController } from './runner-api.controller';
import { RunnerAuthGuard } from './runner-auth.guard';
import { RunnerOrchestrationAuthorizer } from './runner-orchestration-authorizer';
import { RunnerTasksController } from './runner-tasks.controller';
import { AUTOMATIC_COORDINATOR_DECIDES_MESSAGE, START_CARD_REVIEWS_MESSAGE } from './unstarted-project-create';

declare global {
  interface BigInt { toJSON(): string; }
}
// `main.ts` installs this before it creates the app; a task row carries BIGINT columns.
BigInt.prototype.toJSON = function toJSON(this: bigint): string {
  return this.toString();
};

const URL = process.env.COORDINATOR_PG_URL;
const skip = !URL;

/** The runner credential, in the clear. Its hash is what `RunnerAuthGuard` matches. */
const RUNNER_TOKEN = 'the-runner-token-for-unstarted-project-creates';

/** A response, kept as text as well as JSON: a body that failed to parse has to be readable. */
interface Answer {
  status: number;
  text: string;
  json: Record<string, any>;
}

/** A collaborator whose every method answers nothing. */
const silent = (): unknown =>
  new Proxy({}, { get: (_target, key) => (key === 'then' ? undefined : () => undefined) });

test('a coordinator’s creates in a project nobody has started, or one that is Automatic, are not carded one by one', {
  skip, concurrency: 1, timeout: 300_000,
}, async (t) => {
  const url = URL!;
  assertCoordinatorPgUrlIsIsolated(url);
  const sql = new Client({ connectionString: url, connectionTimeoutMillis: 5_000 });
  await sql.connect();
  await verifyCoordinatorPgIdentity(sql);
  const prisma: PrismaClient = prismaClientFor(url);
  let app: INestApplication | undefined;
  t.after(async () => {
    await app?.close().catch(() => undefined);
    await prisma.$disconnect().catch(() => undefined);
    await sql.end().catch(() => undefined);
  });

  // ── what raising a card does, recorded ──────────────────────────────────────────────────────
  // The conversation's card and the phone's buzz are the two things a raised card does beyond its
  // row; the row's PENDING status is the third, and it is read from the table below.
  const published: Array<{ sessionId: string; type: unknown }> = [];
  const pushed: Array<{ sessionId: string; toolName: string }> = [];
  const realtime = new Proxy({}, {
    get: (_target, key) => {
      if (key === 'then') return undefined;
      if (key === 'publish') {
        return (sessionId: string, event: { type: unknown }) => {
          published.push({ sessionId, type: event.type });
        };
      }
      return () => undefined;
    },
  });
  const push = {
    notifyApprovalRequest: async (sessionId: string, toolName: string) => {
      pushed.push({ sessionId, toolName });
    },
  };

  // ── the app: both runner doors, their guard, main.ts's middleware, pipe, interceptor, filters ──
  const queue = { notifySessionQueued: () => undefined };
  const sessions = new SessionsService(prisma as unknown as PrismaService, queue as never, silent() as never);
  const tasks = new TasksService(prisma as unknown as PrismaService, sessions, silent() as never);
  @Module({
    controllers: [RunnerApiController, RunnerTasksController],
    providers: [
      { provide: PrismaService, useValue: prisma },
      { provide: QueueService, useValue: queue },
      { provide: RealtimeService, useValue: realtime },
      { provide: PushService, useValue: push },
      { provide: RunnerOrchestrationAuthorizer, useValue: {} },
      { provide: ReferenceExpansionService, useValue: {} },
      { provide: ListEventsService, useValue: {} },
      { provide: AttemptBudgetMeterService, useValue: {} },
      { provide: ProjectAcceptanceService, useValue: {} },
      // Lent one method at a time: an instance the module OWNS gets its onModuleInit, which starts
      // the auto-run sweeps over this database.
      {
        provide: TasksService,
        useValue: {
          previewCreateMany: tasks.previewCreateMany.bind(tasks),
          create: tasks.create.bind(tasks),
          createMany: tasks.createMany.bind(tasks),
          resolveAgentCreator: tasks.resolveAgentCreator.bind(tasks),
        },
      },
      { provide: MergeReceiptService, useValue: {} },
      { provide: TaskListsService, useValue: {} },
      { provide: ProjectAttributionService, useValue: {} },
      RunnerAuthGuard,
    ],
  })
  class RunnerDoors {}

  app = await NestFactory.create(RunnerDoors, { logger: false, abortOnError: false });
  app.use(publicIdHeaders);
  app.setGlobalPrefix('api');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: false }));
  app.useGlobalInterceptors(new PublicIdInterceptor());
  const httpAdapter = app.get(HttpAdapterHost).httpAdapter;
  app.useGlobalFilters(new TransientDbConflictFilter(new PublicIdExceptionFilter(httpAdapter), httpAdapter));
  await app.listen(0, '127.0.0.1');
  const base = await app.getUrl();

  async function send(
    method: 'GET' | 'POST',
    route: string,
    body?: unknown,
    headers: Record<string, string> = {},
  ): Promise<Answer> {
    const response = await fetch(`${base}/api${route}`, {
      method,
      headers: {
        authorization: `Bearer ${RUNNER_TOKEN}`,
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
        ...headers,
      },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    const text = await response.text();
    let json: Record<string, any> = {};
    try { json = JSON.parse(text) as Record<string, any>; } catch { /* asserted on by the caller */ }
    return { status: response.status, text, json };
  }

  // ── fixtures ─────────────────────────────────────────────────────────────────────────────────
  const ownerId = randomUUID();
  const runnerId = randomUUID();
  const workspaceId = randomUUID();
  await prisma.user.create({
    data: { id: ownerId, email: `d3-${ownerId}@runner-door.invalid`, name: 'The account owner', passwordHash: 'x' },
  });
  await prisma.runner.create({
    data: { id: runnerId, name: 'the machine the coordinator runs on', ownerId, tokenHash: sha256(RUNNER_TOKEN) },
  });
  // Bound to the runner, so a task assigned to it is one the sweeps would dispatch.
  await prisma.workspace.create({
    data: { id: workspaceId, ownerId, runnerId, name: 'orbit', enabled: true },
  });

  /** A conversation on this runner, in the middle of a turn — where an agent's create is asked. */
  async function conversation(title: string): Promise<string> {
    const id = randomUUID();
    await prisma.session.create({
      data: {
        id,
        ownerId,
        creatorId: ownerId,
        workspaceId,
        assignedRunnerId: runnerId,
        title,
        prompt: title,
        provider: 'claude',
        providerBuiltin: true,
        status: RunStatus.RUNNING,
        dispatchOrigin: SessionDispatchOrigin.USER,
        startedAt: new Date(),
      },
    });
    return id;
  }

  /** A project of this owner, coordinated from `coordinator` when one is given; Automatic off unless asked. */
  async function project(
    title: string,
    options: { coordinator?: string; started: boolean; automatic?: boolean },
  ): Promise<string> {
    const id = randomUUID();
    await prisma.project.create({
      data: {
        id,
        ownerId,
        title,
        ...(options.coordinator
          ? { coordinatorWorkspaceId: workspaceId, coordinatorSessionId: options.coordinator }
          : {}),
        startedAt: options.started ? new Date() : null,
        coordinatorEnabled: options.automatic ?? false,
      },
    });
    await prisma.projectRuntime.upsert({ where: { projectId: id }, create: { projectId: id }, update: {} });
    return id;
  }

  /** One task as the runner's `task_create` sends it, and what its card is filed with. */
  function taskBody(title: string, projectId: string | null, extra: Record<string, unknown> = {}) {
    return {
      title,
      ...(projectId ? { projectId: uuidToBase62(projectId) } : {}),
      completionCriterion: 'EXECUTABLE',
      acceptanceCommand: 'true',
      acceptanceExpectedExitCode: 0,
      ...extra,
    };
  }

  /** The card, filed the way `askBeforeCreate` files it. */
  async function ask(sessionId: string, toolName: string, input: unknown): Promise<{ id: string; status: string }> {
    const answer = await send('POST', `/runner/sessions/${uuidToBase62(sessionId)}/approvals`, {
      toolName,
      input,
      toolUseId: `call-${randomUUID()}`,
    });
    assert.equal(answer.status, 201, answer.text);
    return answer.json as { id: string; status: string };
  }

  /** The batch card, filed the way `askBeforeBatch` files it: the preview first, then the card. */
  async function askBatch(sessionId: string, bodies: Array<Record<string, unknown>>) {
    const preview = await send('POST', '/runner/tasks/batch-preview', { tasks: bodies }, {
      'x-orbit-session-id': uuidToBase62(sessionId),
      'x-orbit-workspace-id': uuidToBase62(workspaceId),
    });
    assert.equal(preview.status, 201, preview.text);
    return ask(sessionId, 'orbit_task_batch', { tasks: bodies, preview: preview.json });
  }

  async function approvalRow(id: string) {
    const { rows } = await sql.query<{
      status: string;
      message: string | null;
      decided_by_id: string | null;
      decided: boolean;
    }>(
      `SELECT "status", "message", "decided_by_id", "decided_at" IS NOT NULL AS "decided"
         FROM "approval" WHERE "id" = $1::uuid`,
      [toUuid(id)],
    );
    assert.equal(rows.length, 1, `approval ${id} was not written`);
    return rows[0];
  }

  /** Everything a raised card does for this conversation: its card, its push, its pending rows. */
  async function raised(sessionId: string) {
    const { rows } = await sql.query<{ n: number }>(
      `SELECT count(*)::int AS "n" FROM "approval" WHERE "session_id" = $1::uuid AND "status" = 'PENDING'`,
      [sessionId],
    );
    return {
      cards: published.filter((e) => e.sessionId === sessionId && e.type === RunEventType.APPROVAL_REQUEST).length,
      pushes: pushed.filter((p) => p.sessionId === sessionId).length,
      pending: rows[0].n,
    };
  }

  /** The write the runner makes after a yes, from the conversation that asked. */
  async function write(sessionId: string, route: '/runner/tasks' | '/runner/tasks/batch-create', body: unknown) {
    const answer = await send('POST', route, body, {
      'x-orbit-session-id': uuidToBase62(sessionId),
      'x-orbit-workspace-id': uuidToBase62(workspaceId),
    });
    assert.equal(answer.status, 201, answer.text);
    return answer;
  }

  async function tasksIn(projectId: string): Promise<string[]> {
    const { rows } = await sql.query<{ title: string }>(
      `SELECT "title" FROM "task" WHERE "project_id" = $1::uuid ORDER BY "title"`,
      [projectId],
    );
    return rows.map((row) => row.title);
  }

  /** A card that was asked: pending, on the conversation, on the phone. */
  async function assertAsked(sessionId: string, card: { id: string; status: string }) {
    assert.equal(card.status, 'PENDING');
    const row = await approvalRow(card.id);
    assert.equal(row.status, 'PENDING');
    assert.equal(row.decided, false);
    assert.equal(row.message, null);
    assert.deepEqual(await raised(sessionId), { cards: 1, pushes: 1, pending: 1 });
  }

  // ── 1 ────────────────────────────────────────────────────────────────────────────────────────
  await t.test('all of it in the unstarted project, from its coordinator: no card, and the tasks are written', async () => {
    const coordinator = await conversation('协调：未开工的项目');
    const unstarted = await project('未开工的项目', { coordinator, started: false });

    // One task, the way `task_create` asks and then writes.
    const single = taskBody('the first step', unstarted);
    const card = await ask(coordinator, 'orbit_task_create', single);
    assert.equal(card.status, 'ALLOWED');
    // What the runner's poll reads next — the same request it has always made, answered at once.
    const polled = await send('GET', `/runner/sessions/${uuidToBase62(coordinator)}/approvals/${card.id}`);
    assert.equal(polled.status, 200, polled.text);
    assert.equal(polled.json.status, 'ALLOWED');
    assert.equal(polled.json.behavior, 'allow');
    assert.equal(polled.json.message, START_CARD_REVIEWS_MESSAGE);
    // The trace: allowed and decided, by the platform's rule — no person's id, the rule's sentence.
    assert.deepEqual(await approvalRow(card.id), {
      status: 'ALLOWED',
      message: 'project not started: the start card reviews these',
      decided_by_id: null,
      decided: true,
    });
    await write(coordinator, '/runner/tasks', single);

    // A batch, the way `task_create_batch` asks and then writes.
    const batch = [taskBody('the second step', unstarted), taskBody('the third step', unstarted)];
    const batchCard = await askBatch(coordinator, batch);
    assert.equal(batchCard.status, 'ALLOWED');
    assert.equal((await approvalRow(batchCard.id)).message, START_CARD_REVIEWS_MESSAGE);
    await write(coordinator, '/runner/tasks/batch-create', { tasks: batch });

    // Nothing was raised for either: no card drawn, no phone buzzed, nothing pending to count.
    assert.deepEqual(await raised(coordinator), { cards: 0, pushes: 0, pending: 0 });
    assert.deepEqual(await tasksIn(unstarted), ['the first step', 'the second step', 'the third step']);
  });

  // ── 2 ────────────────────────────────────────────────────────────────────────────────────────
  await t.test('one item in a project that has started: asked', async () => {
    const coordinator = await conversation('协调：混入已开工项目');
    const unstarted = await project('未开工的项目（混入）', { coordinator, started: false });
    const started = await project('已开工的项目', { started: true });

    const card = await askBatch(coordinator, [
      taskBody('here', unstarted),
      taskBody('and there', started),
    ]);

    await assertAsked(coordinator, card);
  });

  // ── 3 ────────────────────────────────────────────────────────────────────────────────────────
  await t.test('the same create from a conversation that does not coordinate the project: asked', async () => {
    const coordinator = await conversation('协调：别人来建');
    const unstarted = await project('未开工的项目（非协调会话）', { coordinator, started: false });
    const someoneElse = await conversation('一个普通会话');

    const single = await ask(someoneElse, 'orbit_task_create', taskBody('filed from elsewhere', unstarted));
    await assertAsked(someoneElse, single);

    const batch = await askBatch(someoneElse, [taskBody('also from elsewhere', unstarted)]);
    assert.equal(batch.status, 'PENDING');
    assert.equal((await raised(someoneElse)).cards, 2);
  });

  // ── 4 ────────────────────────────────────────────────────────────────────────────────────────
  await t.test('the project already started, with Automatic off: asked', async () => {
    const coordinator = await conversation('协调：已开工');
    const started = await project('已开工的项目（协调）', { coordinator, started: true });

    const card = await ask(coordinator, 'orbit_task_create', taskBody('after the start', started));

    await assertAsked(coordinator, card);
  });

  // ── 5 ────────────────────────────────────────────────────────────────────────────────────────
  await t.test('the batch preview in the unstarted project promises no run', async () => {
    const coordinator = await conversation('协调：预览');
    const unstarted = await project('未开工的项目（预览）', { coordinator, started: false });
    const started = await project('已开工的项目（预览）', { started: true });
    // Two roots the independent release would start, and a step waiting on the first of them.
    const plan = (projectId: string) => [
      taskBody('root one', projectId, { ref: 'one', assigneeId: uuidToBase62(workspaceId) }),
      taskBody('root two', projectId, { ref: 'two', assigneeId: uuidToBase62(workspaceId) }),
      taskBody('after one', projectId, { dependsOnRefs: ['one'], assigneeId: uuidToBase62(workspaceId) }),
    ];
    const preview = async (projectId: string) => {
      const answer = await send('POST', '/runner/tasks/batch-preview', { tasks: plan(projectId) });
      assert.equal(answer.status, 201, answer.text);
      return answer.json;
    };

    const before = await preview(unstarted);
    assert.equal(before.startingNow, 0, 'nothing in a project nobody has started runs before the start');
    assert.equal(before.awaitingProjectStart, 2);
    assert.equal(before.blocked, 1);
    assert.equal(before.needsManualStart, 0);

    // The control: the same plan where the project has started, so the zero above is the start's.
    const after = await preview(started);
    assert.equal(after.startingNow, 2);
    assert.equal(after.awaitingProjectStart, 0);
    assert.equal(after.blocked, 1);
  });

  // ── 6 ────────────────────────────────────────────────────────────────────────────────────────
  await t.test('an item that names no project is asked, even from the coordinator', async () => {
    const coordinator = await conversation('协调：未写项目');
    const unstarted = await project('未开工的项目（未写项目）', { coordinator, started: false });

    const card = await askBatch(coordinator, [
      taskBody('named', unstarted),
      taskBody('unnamed', null),
    ]);

    await assertAsked(coordinator, card);
  });

  // ── 7 ────────────────────────────────────────────────────────────────────────────────────────
  await t.test('all of it in the Automatic project, from its coordinator: no card, and the tasks are written', async () => {
    const coordinator = await conversation('协调：Automatic 项目');
    const automatic = await project('Automatic 的项目', { coordinator, started: true, automatic: true });

    const single = taskBody('a fix the coordinator decided on', automatic);
    const card = await ask(coordinator, 'orbit_task_create', single);
    assert.equal(card.status, 'ALLOWED');
    const polled = await send('GET', `/runner/sessions/${uuidToBase62(coordinator)}/approvals/${card.id}`);
    assert.equal(polled.status, 200, polled.text);
    assert.equal(polled.json.status, 'ALLOWED');
    assert.equal(polled.json.behavior, 'allow');
    assert.equal(polled.json.message, AUTOMATIC_COORDINATOR_DECIDES_MESSAGE);
    assert.deepEqual(await approvalRow(card.id), {
      status: 'ALLOWED',
      message: 'project is Automatic: its coordinator decides these',
      decided_by_id: null,
      decided: true,
    });
    await write(coordinator, '/runner/tasks', single);

    const batch = [taskBody('a second fix', automatic), taskBody('a third fix', automatic)];
    const batchCard = await askBatch(coordinator, batch);
    assert.equal(batchCard.status, 'ALLOWED');
    assert.equal((await approvalRow(batchCard.id)).message, AUTOMATIC_COORDINATOR_DECIDES_MESSAGE);
    await write(coordinator, '/runner/tasks/batch-create', { tasks: batch });

    assert.deepEqual(await raised(coordinator), { cards: 0, pushes: 0, pending: 0 });
    assert.deepEqual(await tasksIn(automatic), ['a fix the coordinator decided on', 'a second fix', 'a third fix']);
  });

  // ── 8 ────────────────────────────────────────────────────────────────────────────────────────
  await t.test('the Automatic project from another conversation, or with an item elsewhere: asked', async () => {
    const coordinator = await conversation('协调：Automatic 项目（反例）');
    const automatic = await project('Automatic 的项目（反例）', { coordinator, started: true, automatic: true });
    const elsewhere = await project('另一个 Automatic 的项目', { started: true, automatic: true });
    const someoneElse = await conversation('一个普通会话（Automatic）');

    const fromElsewhere = await ask(someoneElse, 'orbit_task_create', taskBody('filed from elsewhere', automatic));
    await assertAsked(someoneElse, fromElsewhere);

    const straddling = await askBatch(coordinator, [
      taskBody('here', automatic),
      taskBody('and there', elsewhere),
    ]);
    await assertAsked(coordinator, straddling);
  });
});
